In [1]:
from sqlalchemy import * 
from sqlalchemy.orm import * 
from sqlalchemy.ext.declarative import declarative_base
import time
import pandas as pd

In [2]:
Base = declarative_base() 

class Station(Base):
    __tablename__ ='Station'
    id = Column(Integer, primary_key=True)
    station = Column(String(30))
    name = Column(String(255))
    latitude = Column(Float)
    longitude = Column(Float)
    elevation = Column(Float)

class Measurement(Base): 
     __abstract__ = True 

     id = Column(Integer, primary_key=True)
     Date = Column(DateTime)
     prcp = Column(Float)
     tobs= Column(Integer)

     _symbols = {} 

     @classmethod 
     def for_symbol(cls, symbol): 
         if symbol in cls._symbols: 
             return cls._symbols[symbol] 

         cls._symbols[symbol] = measurement_cls = type( 
             "%s_Station" % symbol, 
             (cls, ), 
             { 
                 "__tablename__": "measurement_%s" % symbol, 
                 "symbol": symbol 
             } 
         ) 

         return measurement_cls

In [3]:
station_df = pd.read_csv('clean_hawaii_stations.csv')
symbols = []
for index, row in station_df.iterrows():
    symbols.append(row['station'])
    
symbols

['USC00519397',
 'USC00513117',
 'USC00514830',
 'USC00517948',
 'USC00518838',
 'USC00519523',
 'USC00519281',
 'USC00511918',
 'USC00516128']

In [4]:
 
#timestr = time.strftime("%Y%m%d%H%M%S")
#file_name = 'sqlite:///test' + timestr + '.sqlite'
file_name = 'sqlite:///hawaii.sqlite'
engine = create_engine(file_name, echo=True)

for symbol in symbols: 
     Measurement.for_symbol(symbol) 

Base.metadata.create_all(engine) 


sess = sessionmaker(engine)()

2018-05-08 18:30:58,692 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-05-08 18:30:58,696 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,698 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-05-08 18:30:58,699 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,701 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("Station")
2018-05-08 18:30:58,702 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,704 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00519397")
2018-05-08 18:30:58,705 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,706 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00513117")
2018-05-08 18:30:58,708 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,710 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00514830")
2018-05-08 18:30:58,710 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,712 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00517948")
2018-05-08 18:30:58,718 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,721 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00518838")
2018-05-08 18:30:58,724 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,725 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00519523")
2018-05-08 18:30:58,727 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,728 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00519281")
2018-05-08 18:30:58,729 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,731 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00511918")
2018-05-08 18:30:58,732 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,733 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("measurement_USC00516128")
2018-05-08 18:30:58,735 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,739 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Station" (
	id INTEGER NOT NULL,
	station VARCHAR(30),
	name VARCHAR(255),
	latitude FLOAT,
	longitude FLOAT,
	elevation FLOAT,
	PRIMARY KEY (id)
)


2018-05-08 18:30:58,741 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:58,906 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:58,910 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00519397" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:58,915 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,101 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,107 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00513117" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,109 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,199 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,200 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00514830" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,201 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,313 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,315 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00517948" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,316 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,487 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,494 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00518838" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,496 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,593 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,595 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00519523" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,596 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,676 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,678 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00519281" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,679 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,832 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,836 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00511918" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,838 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:30:59,948 INFO sqlalchemy.engine.base.Engine COMMIT
2018-05-08 18:30:59,949 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "measurement_USC00516128" (
	id INTEGER NOT NULL,
	"Date" DATETIME,
	prcp FLOAT,
	tobs INTEGER,
	PRIMARY KEY (id)
)


2018-05-08 18:30:59,950 INFO sqlalchemy.engine.base.Engine ()
2018-05-08 18:31:00,048 INFO sqlalchemy.engine.base.Engine COMMIT

# Start entering data

In [5]:

measurements_df = pd.read_csv('clean_hawaii_measurements.csv')

In [6]:
station_df

,Unnamed: 0,station,name,latitude,longitude,elevation
0,0,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0
1,1,USC00513117,"KANEOHE 838.1, HI US",21.42340,-157.80150,14.6
2,2,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0
3,3,USC00517948,"PEARL CITY, HI US",21.39340,-157.97510,11.9
4,4,USC00518838,"UPPER WAHIAWA 874.3, HI US",21.49920,-158.01110,306.6
5,5,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5
6,6,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9
7,7,USC00511918,"HONOLULU OBSERVATORY 702.2, HI US",21.31520,-157.99920,0.9
8,8,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4

In [7]:
measurements_df

       Unnamed: 0      station        date  prcp  tobs
0               0  USC00519397  2010-01-01  0.08    65
1               1  USC00519397  2010-01-02  0.00    63
2               2  USC00519397  2010-01-03  0.00    74
3               3  USC00519397  2010-01-04  0.00    76
4               5  USC00519397  2010-01-07  0.06    70
5               6  USC00519397  2010-01-08  0.00    64
6               7  USC00519397  2010-01-09  0.00    68
7               8  USC00519397  2010-01-10  0.00    73
8               9  USC00519397  2010-01-11  0.01    64
9              10  USC00519397  2010-01-12  0.00    61
10             11  USC00519397  2010-01-14  0.00    66
11             12  USC00519397  2010-01-15  0.00    65
12             13  USC00519397  2010-01-16  0.00    68
13             14  USC00519397  2010-01-17  0.00    64
14             15  USC00519397  2010-01-18  0.00    72
15             16  USC00519397  2010-01-19  0.00    66
16             17  USC00519397  2010-01-20  0.00    66
17             18  USC00519397  2010-01-21  0.00    69
18             19  USC00519397  2010-01-22  0.00    67
19             20  USC00519397  2010-01-23  0.00    67
20             21  USC00519397  2010-01-24  0.01    71
21             22  USC00519397  2010-01-25  0.00    67
22             23  USC00519397  2010-01-26  0.04    76
23             24  USC00519397  2010-01-27  0.12    68
24             25  USC00519397  2010-01-28  0.00    72
25             27  USC00519397  2010-01-31  0.03    67
26             28  USC00519397  2010-02-01  0.01    66
27             30  USC00519397  2010-02-04  0.01    69
28             31  USC00519397  2010-02-05  0.00    67
29             32  USC00519397  2010-02-06  0.00    67
...           ...          ...         ...   ...   ...
18073       19513  USC00516128  2017-07-17  0.39    72
18074       19514  USC00516128  2017-07-18  2.40    77
18075       19515  USC00516128  2017-07-19  0.27    74
18076       19516  USC00516128  2017-07-20  0.70    75
18077       19517  USC00516128  2017-07-21  0.10    72
18078       19518  USC00516128  2017-07-22  4.00    72
18079       19519  USC00516128  2017-07-23  0.80    78
18080       19520  USC00516128  2017-07-24  0.84    77
18081       19521  USC00516128  2017-07-25  0.30    79
18082       19522  USC00516128  2017-07-26  0.30    73
18083       19523  USC00516128  2017-07-27  0.00    75
18084       19524  USC00516128  2017-07-28  0.40    73
18085       19525  USC00516128  2017-07-29  0.30    77
18086       19526  USC00516128  2017-07-30  0.30    79
18087       19527  USC00516128  2017-07-31  0.00    74
18088       19529  USC00516128  2017-08-02  0.25    80
18089       19530  USC00516128  2017-08-03  0.06    76
18090       19533  USC00516128  2017-08-07  0.05    78
18091       19534  USC00516128  2017-08-08  0.34    74
18092       19535  USC00516128  2017-08-09  0.15    71
18093       19536  USC00516128  2017-08-10  0.07    75
18094       19538  USC00516128  2017-08-12  0.14    74
18095       19540  USC00516128  2017-08-14  0.22    79
18096       19541  USC00516128  2017-08-15  0.42    70
18097       19542  USC00516128  2017-08-16  0.42    71
18098       19543  USC00516128  2017-08-17  0.13    72
18099       19545  USC00516128  2017-08-19  0.09    71
18100       19547  USC00516128  2017-08-21  0.56    76
18101       19548  USC00516128  2017-08-22  0.50    76
18102       19549  USC00516128  2017-08-23  0.45    76

[18103 rows x 5 columns]

In [8]:
measurements_df['date'] = pd.to_datetime(measurements_df['date'],format='%Y-%m-%d')

In [9]:
for index, row in station_df.iterrows():
    print (row['station'], row['name'],row['latitude'],row['longitude'],row['elevation'])
    sess.add(Station(station=row['station'], name=row['name'], latitude=row['latitude'], longitude=row['longitude'],
                     elevation=row['elevation']))

USC00519397 WAIKIKI 717.2, HI US 21.2716 -157.8168 3.0
USC00513117 KANEOHE 838.1, HI US 21.4234 -157.8015 14.6
USC00514830 KUALOA RANCH HEADQUARTERS 886.9, HI US 21.5213 -157.8374 7.0
USC00517948 PEARL CITY, HI US 21.3934 -157.9751 11.9
USC00518838 UPPER WAHIAWA 874.3, HI US 21.4992 -158.0111 306.6
USC00519523 WAIMANALO EXPERIMENTAL FARM, HI US 21.33556 -157.71139 19.5
USC00519281 WAIHEE 837.5, HI US 21.45167 -157.84888999999995 32.9
USC00511918 HONOLULU OBSERVATORY 702.2, HI US 21.3152 -157.9992 0.9
USC00516128 MANOA LYON ARBO 785.2, HI US 21.3331 -157.8025 152.4

In [10]:
for index, row in station_df.iterrows():
    print (row['station'], row['name'])
    x_df= measurements_df.loc[measurements_df['station']==row['station'],:]
    for i, j in x_df.iterrows():
        print (j['station'],j['date'],str(j['prcp']),str(j['tobs']))
        sess.add(Measurement.for_symbol(row['station'])(Date=j['date'], prcp=j['prcp'],tobs=j['tobs']))

USC00519397 WAIKIKI 717.2, HI US
USC00519397 2010-01-01 00:00:00 0.08 65
USC00519397 2010-01-02 00:00:00 0.0 63
USC00519397 2010-01-03 00:00:00 0.0 74
USC00519397 2010-01-04 00:00:00 0.0 76
USC00519397 2010-01-07 00:00:00 0.06 70
USC00519397 2010-01-08 00:00:00 0.0 64
USC00519397 2010-01-09 00:00:00 0.0 68
USC00519397 2010-01-10 00:00:00 0.0 73
USC00519397 2010-01-11 00:00:00 0.01 64
USC00519397 2010-01-12 00:00:00 0.0 61
USC00519397 2010-01-14 00:00:00 0.0 66
USC00519397 2010-01-15 00:00:00 0.0 65
USC00519397 2010-01-16 00:00:00 0.0 68
USC00519397 2010-01-17 00:00:00 0.0 64
USC00519397 2010-01-18 00:00:00 0.0 72
USC00519397 2010-01-19 00:00:00 0.0 66
USC00519397 2010-01-20 00:00:00 0.0 66
USC00519397 2010-01-21 00:00:00 0.0 69
USC00519397 2010-01-22 00:00:00 0.0 67
USC00519397 2010-01-23 00:00:00 0.0 67
USC00519397 2010-01-24 00:00:00 0.01 71
USC00519397 2010-01-25 00:00:00 0.0 67
USC00519397 2010-01-26 00:00:00 0.04 76
USC00519397 2010-01-27 00:00:00 0.12 68
USC00519397 2010-01-28 00:00:00 0.0 72
USC00519397 2010-01-31 00:00:00 0.03 67
USC00519397 2010-02-01 00:00:00 0.01 66
USC00519397 2010-02-04 00:00:00 0.01 69
USC00519397 2010-02-05 00:00:00 0.0 67
USC00519397 2010-02-06 00:00:00 0.0 67
USC00519397 2010-02-07 00:00:00 0.0 64
USC00519397 2010-02-08 00:00:00 0.0 69
USC00519397 2010-02-09 00:00:00 0.0 73
USC00519397 2010-02-11 00:00:00 0.0 73
USC00519397 2010-02-12 00:00:00 0.02 69
USC00519397 2010-02-13 00:00:00 0.01 69
USC00519397 2010-02-14 00:00:00 0.0 69
USC00519397 2010-02-15 00:00:00 0.0 71
USC00519397 2010-02-16 00:00:00 0.0 61
USC00519397 2010-02-17 00:00:00 0.0 69
USC00519397 2010-02-20 00:00:00 0.03 64
USC00519397 2010-02-21 00:00:00 0.0 65
USC00519397 2010-02-22 00:00:00 0.0 67
USC00519397 2010-02-23 00:00:00 0.0 68
USC00519397 2010-02-24 00:00:00 0.0 65
USC00519397 2010-02-25 00:00:00 0.0 76
USC00519397 2010-02-26 00:00:00 0.0 75
USC00519397 2010-02-28 00:00:00 0.0 66
USC00519397 2010-03-01 00:00:00 0.01 70
USC00519397 2010-03-02 00:00:00 0.0 72
USC00519397 2010-03-03 00:00:00 0.0 73
USC00519397 2010-03-04 00:00:00 0.12 70
USC00519397 2010-03-05 00:00:00 0.08 71
USC00519397 2010-03-06 00:00:00 0.03 72
USC00519397 2010-03-07 00:00:00 0.0 72
USC00519397 2010-03-08 00:00:00 0.43 69
USC00519397 2010-03-09 00:00:00 0.06 70
USC00519397 2010-03-12 00:00:00 0.0 72
USC00519397 2010-03-13 00:00:00 0.0 73
USC00519397 2010-03-14 00:00:00 0.0 70
USC00519397 2010-03-15 00:00:00 0.06 71
USC00519397 2010-03-17 00:00:00 0.0 68
USC00519397 2010-03-18 00:00:00 0.0 70
USC00519397 2010-03-21 00:00:00 0.0 72
USC00519397 2010-03-22 00:00:00 0.0 69
USC00519397 2010-03-23 00:00:00 0.0 68
USC00519397 2010-03-24 00:00:00 0.0 74
USC00519397 2010-03-27 00:00:00 0.0 72
USC00519397 2010-03-28 00:00:00 0.0 73
USC00519397 2010-03-29 00:00:00 0.0 74
USC00519397 2010-03-30 00:00:00 0.0 73
USC00519397 2010-03-31 00:00:00 0.0 73
USC00519397 2010-04-01 00:00:00 0.0 74
USC00519397 2010-04-02 00:00:00 0.01 74
USC00519397 2010-04-03 00:00:00 0.17 74
USC00519397 2010-04-04 00:00:00 0.15 71
USC00519397 2010-04-05 00:00:00 0.27 72
USC00519397 2010-04-06 00:00:00 0.01 75
USC00519397 2010-04-08 00:00:00 0.0 75
USC00519397 2010-04-09 00:00:00 0.01 75
USC00519397 2010-04-10 00:00:00 0.0 75
USC00519397 2010-04-11 00:00:00 0.01 73
USC00519397 2010-04-12 00:00:00 0.01 73
USC00519397 2010-04-13 00:00:00 0.0 71
USC00519397 2010-04-15 00:00:00 0.0 71
USC00519397 2010-04-16 00:00:00 0.01 68
USC00519397 2010-04-17 00:00:00 0.0 70
USC00519397 2010-04-18 00:00:00 0.0 71
USC00519397 2010-04-19 00:00:00 0.0 74
USC00519397 2010-04-20 00:00:00 0.04 71
USC00519397 2010-04-21 00:00:00 0.01 75
USC00519397 2010-04-22 00:00:00 0.0 76
USC00519397 2010-04-23 00:00:00 0.02 75
USC00519397 2010-04-24 00:00:00 0.0 75
USC00519397 2010-04-25 00:00:00 0.0 76
USC00519397 2010-04-26 00:00:00 0.0 76
USC00519397 2010-04-28 00:00:00 0.0 76
USC00519397 2010-04-30 00:00:00 0.0 77
USC00519397 2010-05-01 00:00:00 0.0 77
USC00519397 2010-05-02 00:00:00 0.03 73
USC00519397 2010-05-03 00:00:00 0.2 74
USC00519397 2010-05-04 00:00:00 0.08 76
USC00519397 2010-05-05 00:00:00 0.01 76
USC00519397 2010-05-06 00:00:00 0.0 80
USC00519397 2010-05-07 00:00:00 0.05 74
USC00519397 2010-05-08 00:00:00 0.0 77
USC00519397 2010-05-09 00:00:00 0.0 77
USC00519397 2010-05-10 00:00:00 0.0 76
USC00519397 2010-05-11 00:00:00 0.0 77
USC00519397 2010-05-13 00:00:00 0.0 78
USC00519397 2010-05-14 00:00:00 0.0 78
USC00519397 2010-05-15 00:00:00 0.0 75
USC00519397 2010-05-16 00:00:00 0.03 73
USC00519397 2010-05-17 00:00:00 0.0 77
USC00519397 2010-05-18 00:00:00 0.0 76
USC00519397 2010-05-19 00:00:00 0.0 77
USC00519397 2010-05-22 00:00:00 0.0 78
USC00519397 2010-05-23 00:00:00 0.05 75
USC00519397 2010-05-24 00:00:00 0.0 77
USC00519397 2010-05-25 00:00:00 0.0 77
USC00519397 2010-05-26 00:00:00 0.02 77
USC00519397 2010-05-27 00:00:00 0.0 76
USC00519397 2010-05-28 00:00:00 0.0 75
USC00519397 2010-05-29 00:00:00 0.0 77
USC00519397 2010-05-30 00:00:00 0.0 77
USC00519397 2010-05-31 00:00:00 0.0 77
USC00519397 2010-06-01 00:00:00 0.0 78
USC00519397 2010-06-02 00:00:00 0.01 76
USC00519397 2010-06-03 00:00:00 0.0 78
USC00519397 2010-06-04 00:00:00 0.0 76
USC00519397 2010-06-05 00:00:00 0.0 77
USC00519397 2010-06-06 00:00:00 0.0 78
USC00519397 2010-06-07 00:00:00 0.0 77
USC00519397 2010-06-08 00:00:00 0.0 78
USC00519397 2010-06-09 00:00:00 0.0 78
USC00519397 2010-06-10 00:00:00 0.0 79
USC00519397 2010-06-11 00:00:00 0.0 78
USC00519397 2010-06-12 00:00:00 0.0 78
USC00519397 2010-06-13 00:00:00 0.0 78
USC00519397 2010-06-14 00:00:00 0.0 77
USC00519397 2010-06-15 00:00:00 0.0 78
USC00519397 2010-06-16 00:00:00 0.0 78
USC00519397 2010-06-17 00:00:00 0.0 77
USC00519397 2010-06-18 00:00:00 0.0 77
USC00519397 2010-06-19 00:00:00 0.0 82
USC00519397 2010-06-20 00:00:00 0.0 78
USC00519397 2010-06-21 00:00:00 0.0 78
USC00519397 2010-06-22 00:00:00 0.0 78
USC00519397 2010-06-23 00:00:00 0.0 78
USC00519397 2010-06-24 00:00:00 0.0 78
USC00519397 2010-06-25 00:00:00 0.0 77
USC00519397 2010-06-26 00:00:00 0.02 76
USC00519397 2010-06-27 00:00:00 0.0 78
USC00519397 2010-06-28 00:00:00 0.0 78
USC00519397 2010-06-29 00:00:00 0.0 78
USC00519397 2010-06-30 00:00:00 0.0 78
USC00519397 2010-07-01 00:00:00 0.01 75
USC00519397 2010-07-02 00:00:00 0.05 77
USC00519397 2010-07-03 00:00:00 0.09 77
USC00519397 2010-07-04 00:00:00 0.05 78
USC00519397 2010-07-05 00:00:00 0.06 78
USC00519397 2010-07-06 00:00:00 0.08 76
USC00519397 2010-07-07 00:00:00 0.08 74
USC00519397 2010-07-08 00:00:00 0.03 76
USC00519397 2010-07-09 00:00:00 0.06 74
USC00519397 2010-07-10 00:00:00 0.09 76
USC00519397 2010-07-11 00:00:00 0.0 78
USC00519397 2010-07-12 00:00:00 0.0 77
USC00519397 2010-07-13 00:00:00 0.0 80
USC00519397 2010-07-17 00:00:00 0.02 76
USC00519397 2010-07-18 00:00:00 0.0 77
USC00519397 2010-07-19 00:00:00 0.04 77
USC00519397 2010-07-21 00:00:00 0.0 80
USC00519397 2010-07-22 00:00:00 0.0 78
USC00519397 2010-07-24 00:00:00 0.0 80
USC00519397 2010-07-25 00:00:00 0.0 79
USC00519397 2010-07-26 00:00:00 0.0 78
USC00519397 2010-07-27 00:00:00 0.0 79
USC00519397 2010-07-28 00:00:00 0.0 78
USC00519397 2010-07-29 00:00:00 0.0 79
USC00519397 2010-07-30 00:00:00 0.0 78
USC00519397 2010-07-31 00:00:00 0.02 77
USC00519397 2010-08-01 00:00:00 0.04 77
USC00519397 2010-08-02 00:00:00 0.01 76
USC00519397 2010-08-03 00:00:00 0.02 77
USC00519397 2010-08-04 00:00:00 0.07 77
USC00519397 2010-08-05 00:00:00 0.08 75
USC00519397 2010-08-06 00:00:00 0.03 75
USC00519397 2010-08-07 00:00:00 0.0 80
USC00519397 2010-08-08 00:00:00 0.0 77
USC00519397 2010-08-09 00:00:00 0.0 78
USC00519397 2010-08-10 00:00:00 0.0 78
USC00519397 2010-08-11 00:00:00 0.0 77
USC00519397 2010-08-12 00:00:00 0.0 76
USC00519397 2010-08-13 00:00:00 0.0 78
USC00519397 2010-08-14 00:00:00 0.0 78
USC00519397 2010-08-15 00:00:00 0.01 76
USC00519397 2010-08-16 00:00:00 0.0 76
USC00519397 2010-08-17 00:00:00 0.05 74
USC00519397 2010-08-18 00:00:00 0.0 77
USC00519397 2010-08-19 00:00:00 0.0 79
USC00519397 2010-08-20 00:00:00 0.0 79
USC00519397 2010-08-21 00:00:00 0.0 79
USC00519397 2010-08-22 00:00:00 0.0 75
USC00519397 2010-08-23 00:00:00 0.01 87
USC00519397 2010-08-24 00:00:00 0.0 78
USC00519397 2010-08-25 00:00:00 0.04 76
USC00519397 2010-08-26 00:00:00 0.03 78
USC00519397 2010-08-27 00:00:00 0.0 78
USC00519397 2010-08-28 00:00:00 0.04 79
USC00519397 2010-08-29 00:00:00 0.0 78
USC00519397 2010-08-30 00:00:00 0.0 78
USC00519397 2010-08-31 00:00:00 0.0 80
USC00519397 2010-09-01 00:00:00 0.0 77
USC00519397 2010-09-02 00:00:00 0.02 76
USC00519397 2010-09-03 00:00:00 0.04 78
USC00519397 2010-09-04 00:00:00 0.01 77
USC00519397 2010-09-05 00:00:00 0.0 77
USC00519397 2010-09-06 00:00:00 0.0 77
USC00519397 2010-09-07 00:00:00 0.06 76
USC00519397 2010-09-08 00:00:00 0.0 78
USC00519397 2010-09-09 00:00:00 0.0 78
USC00519397 2010-09-10 00:00:00 0.0 78
USC00519397 2010-09-11 00:00:00 0.05 78
USC00519397 2010-09-12 00:00:00 0.0 74
USC00519397 2010-09-13 00:00:00 0.0 78
USC00519397 2010-09-14 00:00:00 0.0 79
USC00519397 2010-09-15 00:00:00 0.0 77
USC00519397 2010-09-16 00:00:00 0.0 79
USC00519397 2010-09-17 00:00:00 0.0 78
USC00519397 2010-09-19 00:00:00 0.0 78
USC00519397 2010-09-20 00:00:00 0.0 78
USC00519397 2010-09-21 00:00:00 0.0 79
USC00519397 2010-09-22 00:00:00 0.04 76
USC00519397 2010-09-23 00:00:00 0.0 78
USC00519397 2010-09-24 00:00:00 0.0 78
USC00519397 2010-09-25 00:00:00 0.0 79
USC00519397 2010-09-26 00:00:00 0.0 74
USC00519397 2010-09-27 00:00:00 0.0 75
USC00519397 2010-09-28 00:00:00 0.0 75
USC00519397 2010-09-29 00:00:00 0.0 78
USC00519397 2010-09-30 00:00:00 0.57 73
USC00519397 2010-10-01 00:00:00 0.31 78
USC00519397 2010-10-02 00:00:00 0.03 78
USC00519397 2010-10-03 00:00:00 0.0 78
USC00519397 2010-10-04 00:00:00 0.06 78
USC00519397 2010-10-05 00:00:00 0.0 80
USC00519397 2010-10-06 00:00:00 0.0 79
USC00519397 2010-10-07 00:00:00 0.0 79
USC00519397 2010-10-08 00:00:00 0.0 78
USC00519397 2010-10-09 00:00:00 0.0 78
USC00519397 2010-10-10 00:00:00 0.0 78
USC00519397 2010-10-11 00:00:00 0.0 77
USC00519397 2010-10-12 00:00:00 0.0 79
USC00519397 2010-10-13 00:00:00 0.0 78
USC00519397 2010-10-15 00:00:00 0.0 78
USC00519397 2010-10-16 00:00:00 0.0 77
USC00519397 2010-10-17 00:00:00 0.0 76
USC00519397 2010-10-18 00:00:00 0.0 76
USC00519397 2010-10-19 00:00:00 0.07 72
USC00519397 2010-10-20 00:00:00 0.0 74
USC00519397 2010-10-21 00:00:00 0.0 80
USC00519397 2010-10-22 00:00:00 0.0 77
USC00519397 2010-10-23 00:00:00 0.0 75
USC00519397 2010-10-24 00:00:00 0.0 78
USC00519397 2010-10-25 00:00:00 0.0 78
USC00519397 2010-10-26 00:00:00 0.07 76
USC00519397 2010-10-27 00:00:00 0.05 79
USC00519397 2010-10-28 00:00:00 0.06 78
USC00519397 2010-10-29 00:00:00 0.03 78
USC00519397 2010-10-30 00:00:00 0.02 77
USC00519397 2010-10-31 00:00:00 0.0 76
USC00519397 2010-11-01 00:00:00 0.01 75
USC00519397 2010-11-02 00:00:00 0.01 73
USC00519397 2010-11-05 00:00:00 0.0 77
USC00519397 2010-11-06 00:00:00 0.0 76
USC00519397 2010-11-07 00:00:00 0.0 77
USC00519397 2010-11-08 00:00:00 0.0 76
USC00519397 2010-11-09 00:00:00 0.0 73
USC00519397 2010-11-10 00:00:00 0.23 73
USC00519397 2010-11-11 00:00:00 0.0 77
USC00519397 2010-11-12 00:00:00 0.0 77
USC00519397 2010-11-13 00:00:00 0.0 76
USC00519397 2010-11-16 00:00:00 0.0 73
USC00519397 2010-11-17 00:00:00 0.0 73
USC00519397 2010-11-20 00:00:00 0.03 69
USC00519397 2010-11-21 00:00:00 0.0 69
USC00519397 2010-11-22 00:00:00 0.0 68
USC00519397 2010-11-23 00:00:00 0.0 69
USC00519397 2010-11-24 00:00:00 0.0 76
USC00519397 2010-11-25 00:00:00 0.0 76
USC00519397 2010-11-27 00:00:00 0.0 75
USC00519397 2010-11-28 00:00:00 0.0 74
USC00519397 2010-11-29 00:00:00 0.0 69
USC00519397 2010-11-30 00:00:00 0.0 74
USC00519397 2010-12-01 00:00:00 0.04 76
USC00519397 2010-12-03 00:00:00 0.0 74
USC00519397 2010-12-04 00:00:00 0.0 74
USC00519397 2010-12-06 00:00:00 0.0 64
USC00519397 2010-12-07 00:00:00 0.0 64
USC00519397 2010-12-08 00:00:00 0.0 67
USC00519397 2010-12-09 00:00:00 0.0 77
USC00519397 2010-12-10 00:00:00 1.58 66
USC00519397 2010-12-11 00:00:00 0.77 69
USC00519397 2010-12-12 00:00:00 0.0 68
USC00519397 2010-12-13 00:00:00 0.0 68
USC00519397 2010-12-14 00:00:00 0.0 71
USC00519397 2010-12-15 00:00:00 0.0 74
USC00519397 2010-12-16 00:00:00 0.0 67
USC00519397 2010-12-17 00:00:00 0.0 66
USC00519397 2010-12-18 00:00:00 0.0 69

USC00519397 2010-12-19 00:00:00 1.4 71
USC00519397 2010-12-23 00:00:00 0.0 70
USC00519397 2010-12-24 00:00:00 0.0 70
USC00519397 2010-12-27 00:00:00 0.13 74
USC00519397 2010-12-28 00:00:00 0.55 71
USC00519397 2010-12-29 00:00:00 0.06 75
USC00519397 2010-12-30 00:00:00 0.01 75
USC00519397 2010-12-31 00:00:00 0.0 72
USC00519397 2011-01-01 00:00:00 0.0 69
USC00519397 2011-01-02 00:00:00 0.0 72
USC00519397 2011-01-03 00:00:00 0.0 74
USC00519397 2011-01-04 00:00:00 0.0 73
USC00519397 2011-01-05 00:00:00 0.0 64
USC00519397 2011-01-06 00:00:00 0.01 65
USC00519397 2011-01-07 00:00:00 0.0 68
USC00519397 2011-01-08 00:00:00 0.0 62
USC00519397 2011-01-09 00:00:00 0.0 58
USC00519397 2011-01-10 00:00:00 0.0 73
USC00519397 2011-01-11 00:00:00 0.09 60
USC00519397 2011-01-14 00:00:00 0.03 76
USC00519397 2011-01-15 00:00:00 0.0 68
USC00519397 2011-01-16 00:00:00 0.0 66
USC00519397 2011-01-17 00:00:00 0.0 64
USC00519397 2011-01-18 00:00:00 0.0 64
USC00519397 2011-01-19 00:00:00 0.03 64
USC00519397 2011-01-20 00:00:00 0.0 76
USC00519397 2011-01-21 00:00:00 0.0 75
USC00519397 2011-01-22 00:00:00 0.0 68
USC00519397 2011-01-23 00:00:00 0.0 68
USC00519397 2011-01-24 00:00:00 0.0 72
USC00519397 2011-01-25 00:00:00 0.0 63
USC00519397 2011-01-27 00:00:00 0.0 68
USC00519397 2011-01-28 00:00:00 0.0 75
USC00519397 2011-01-29 00:00:00 0.0 65
USC00519397 2011-01-30 00:00:00 0.0 64
USC00519397 2011-01-31 00:00:00 0.22 68
USC00519397 2011-02-01 00:00:00 0.0 68
USC00519397 2011-02-02 00:00:00 0.0 66
USC00519397 2011-02-03 00:00:00 0.0 67
USC00519397 2011-02-04 00:00:00 0.0 64
USC00519397 2011-02-05 00:00:00 0.0 65
USC00519397 2011-02-06 00:00:00 0.0 75
USC00519397 2011-02-07 00:00:00 1.29 68
USC00519397 2011-02-08 00:00:00 1.3 71
USC00519397 2011-02-09 00:00:00 0.0 71
USC00519397 2011-02-10 00:00:00 0.29 71
USC00519397 2011-02-13 00:00:00 0.0 68
USC00519397 2011-02-14 00:00:00 0.04 72
USC00519397 2011-02-15 00:00:00 0.05 70
USC00519397 2011-02-16 00:00:00 0.0 74
USC00519397 2011-02-19 00:00:00 0.0 67
USC00519397 2011-02-20 00:00:00 1.72 71
USC00519397 2011-02-21 00:00:00 0.0 71
USC00519397 2011-02-22 00:00:00 0.82 71
USC00519397 2011-02-23 00:00:00 0.0 74
USC00519397 2011-02-24 00:00:00 0.2 68
USC00519397 2011-02-25 00:00:00 0.0 71
USC00519397 2011-02-26 00:00:00 0.0 69
USC00519397 2011-02-27 00:00:00 0.0 69
USC00519397 2011-02-28 00:00:00 0.0 68
USC00519397 2011-03-01 00:00:00 0.1 68
USC00519397 2011-03-02 00:00:00 0.0 72
USC00519397 2011-03-03 00:00:00 0.0 74
USC00519397 2011-03-04 00:00:00 0.88 72
USC00519397 2011-03-05 00:00:00 0.4 69
USC00519397 2011-03-06 00:00:00 0.03 70
USC00519397 2011-03-09 00:00:00 0.2 71
USC00519397 2011-03-10 00:00:00 0.15 71
USC00519397 2011-03-12 00:00:00 0.0 72
USC00519397 2011-03-13 00:00:00 0.0 70
USC00519397 2011-03-14 00:00:00 0.0 71
USC00519397 2011-03-16 00:00:00 0.0 76
USC00519397 2011-03-17 00:00:00 0.01 73
USC00519397 2011-03-18 00:00:00 0.05 74
USC00519397 2011-03-19 00:00:00 0.01 74
USC00519397 2011-03-20 00:00:00 0.02 74
USC00519397 2011-03-21 00:00:00 0.0 74
USC00519397 2011-03-22 00:00:00 0.02 74
USC00519397 2011-03-23 00:00:00 0.0 74
USC00519397 2011-03-24 00:00:00 0.06 73
USC00519397 2011-03-25 00:00:00 0.0 74
USC00519397 2011-03-26 00:00:00 0.0 74
USC00519397 2011-03-27 00:00:00 0.0 73
USC00519397 2011-03-28 00:00:00 0.04 74
USC00519397 2011-03-30 00:00:00 0.0 75
USC00519397 2011-03-31 00:00:00 0.0 74
USC00519397 2011-04-01 00:00:00 0.05 74
USC00519397 2011-04-02 00:00:00 0.04 75
USC00519397 2011-04-03 00:00:00 0.0 74
USC00519397 2011-04-04 00:00:00 0.0 75
USC00519397 2011-04-05 00:00:00 0.0 74
USC00519397 2011-04-06 00:00:00 0.09 70
USC00519397 2011-04-07 00:00:00 1.11 70
USC00519397 2011-04-08 00:00:00 0.36 70
USC00519397 2011-04-09 00:00:00 0.02 76
USC00519397 2011-04-10 00:00:00 0.0 76
USC00519397 2011-04-11 00:00:00 0.0 76
USC00519397 2011-04-12 00:00:00 0.0 76
USC00519397 2011-04-13 00:00:00 0.0 70
USC00519397 2011-04-15 00:00:00 0.0 77
USC00519397 2011-04-16 00:00:00 0.12 74
USC00519397 2011-04-17 00:00:00 0.0 73
USC00519397 2011-04-18 00:00:00 0.0 76
USC00519397 2011-04-19 00:00:00 0.0 76
USC00519397 2011-04-20 00:00:00 0.0 74
USC00519397 2011-04-21 00:00:00 0.0 77
USC00519397 2011-04-22 00:00:00 0.0 77
USC00519397 2011-04-23 00:00:00 0.0 78
USC00519397 2011-04-24 00:00:00 0.0 77
USC00519397 2011-04-25 00:00:00 0.0 77
USC00519397 2011-04-26 00:00:00 0.0 76
USC00519397 2011-04-27 00:00:00 0.0 77
USC00519397 2011-04-29 00:00:00 0.0 78
USC00519397 2011-04-30 00:00:00 0.04 76
USC00519397 2011-05-01 00:00:00 0.0 77
USC00519397 2011-05-02 00:00:00 0.0 77
USC00519397 2011-05-03 00:00:00 2.1 70
USC00519397 2011-05-04 00:00:00 0.02 76
USC00519397 2011-05-05 00:00:00 0.12 74
USC00519397 2011-05-06 00:00:00 0.12 72
USC00519397 2011-05-07 00:00:00 0.55 74
USC00519397 2011-05-08 00:00:00 0.55 73
USC00519397 2011-05-09 00:00:00 0.02 75
USC00519397 2011-05-10 00:00:00 0.11 75
USC00519397 2011-05-11 00:00:00 0.1 75
USC00519397 2011-05-12 00:00:00 0.0 76
USC00519397 2011-05-13 00:00:00 0.0 77
USC00519397 2011-05-14 00:00:00 0.0 78
USC00519397 2011-05-15 00:00:00 0.0 77
USC00519397 2011-05-16 00:00:00 0.0 78
USC00519397 2011-05-17 00:00:00 0.0 77
USC00519397 2011-05-18 00:00:00 0.0 76
USC00519397 2011-05-19 00:00:00 0.01 77
USC00519397 2011-05-20 00:00:00 0.0 79
USC00519397 2011-05-21 00:00:00 0.0 77
USC00519397 2011-05-22 00:00:00 0.06 74
USC00519397 2011-05-23 00:00:00 0.02 78
USC00519397 2011-05-24 00:00:00 0.0 77
USC00519397 2011-05-25 00:00:00 0.0 79
USC00519397 2011-05-26 00:00:00 0.0 78
USC00519397 2011-05-27 00:00:00 0.0 78
USC00519397 2011-05-28 00:00:00 0.0 77
USC00519397 2011-05-29 00:00:00 0.0 78
USC00519397 2011-05-30 00:00:00 0.0 78
USC00519397 2011-05-31 00:00:00 0.05 73
USC00519397 2011-06-01 00:00:00 0.07 77
USC00519397 2011-06-02 00:00:00 0.0 78
USC00519397 2011-06-03 00:00:00 0.56 73
USC00519397 2011-06-04 00:00:00 0.89 70
USC00519397 2011-06-05 00:00:00 0.0 76
USC00519397 2011-06-06 00:00:00 0.0 77
USC00519397 2011-06-07 00:00:00 0.0 77
USC00519397 2011-06-08 00:00:00 0.03 77
USC00519397 2011-06-09 00:00:00 0.01 77
USC00519397 2011-06-10 00:00:00 0.0 78
USC00519397 2011-06-11 00:00:00 0.0 77
USC00519397 2011-06-12 00:00:00 0.0 77
USC00519397 2011-06-13 00:00:00 0.0 78
USC00519397 2011-06-14 00:00:00 0.0 78
USC00519397 2011-06-15 00:00:00 0.0 77
USC00519397 2011-06-17 00:00:00 0.0 78
USC00519397 2011-06-18 00:00:00 0.0 78
USC00519397 2011-06-19 00:00:00 0.05 75
USC00519397 2011-06-20 00:00:00 0.06 76
USC00519397 2011-06-21 00:00:00 0.07 76
USC00519397 2011-06-25 00:00:00 0.0 78
USC00519397 2011-06-26 00:00:00 0.0 76
USC00519397 2011-06-27 00:00:00 0.01 77
USC00519397 2011-06-28 00:00:00 0.01 75
USC00519397 2011-06-29 00:00:00 0.0 77
USC00519397 2011-07-01 00:00:00 0.05 77
USC00519397 2011-07-02 00:00:00 0.02 78
USC00519397 2011-07-03 00:00:00 0.0 78
USC00519397 2011-07-04 00:00:00 0.0 78
USC00519397 2011-07-05 00:00:00 0.01 78
USC00519397 2011-07-06 00:00:00 0.01 76
USC00519397 2011-07-07 00:00:00 0.01 76
USC00519397 2011-07-08 00:00:00 0.0 77
USC00519397 2011-07-09 00:00:00 0.03 77
USC00519397 2011-07-10 00:00:00 0.02 77
USC00519397 2011-07-11 00:00:00 0.0 78
USC00519397 2011-07-12 00:00:00 0.0 77
USC00519397 2011-07-13 00:00:00 0.15 73
USC00519397 2011-07-14 00:00:00 0.0 77
USC00519397 2011-07-15 00:00:00 0.0 79
USC00519397 2011-07-16 00:00:00 0.0 78
USC00519397 2011-07-17 00:00:00 0.04 77
USC00519397 2011-07-18 00:00:00 0.0 78
USC00519397 2011-07-19 00:00:00 0.0 78
USC00519397 2011-07-20 00:00:00 0.0 76
USC00519397 2011-07-21 00:00:00 0.03 77
USC00519397 2011-07-23 00:00:00 0.0 78
USC00519397 2011-07-24 00:00:00 0.0 77
USC00519397 2011-07-25 00:00:00 0.0 78
USC00519397 2011-07-26 00:00:00 0.0 78
USC00519397 2011-07-27 00:00:00 0.04 77
USC00519397 2011-07-28 00:00:00 0.09 77
USC00519397 2011-07-29 00:00:00 0.04 78
USC00519397 2011-07-30 00:00:00 0.12 80
USC00519397 2011-07-31 00:00:00 0.0 77
USC00519397 2011-08-01 00:00:00 0.0 78
USC00519397 2011-08-02 00:00:00 0.0 77
USC00519397 2011-08-03 00:00:00 0.0 78
USC00519397 2011-08-04 00:00:00 0.02 76
USC00519397 2011-08-05 00:00:00 0.03 78
USC00519397 2011-08-06 00:00:00 0.01 77
USC00519397 2011-08-07 00:00:00 0.0 78
USC00519397 2011-08-08 00:00:00 0.0 78
USC00519397 2011-08-09 00:00:00 0.0 79
USC00519397 2011-08-11 00:00:00 0.0 78
USC00519397 2011-08-12 00:00:00 0.0 78
USC00519397 2011-08-13 00:00:00 0.0 76
USC00519397 2011-08-14 00:00:00 0.0 78
USC00519397 2011-08-15 00:00:00 0.0 77
USC00519397 2011-08-16 00:00:00 0.0 79
USC00519397 2011-08-17 00:00:00 0.02 77
USC00519397 2011-08-18 00:00:00 0.0 77
USC00519397 2011-08-19 00:00:00 0.0 78
USC00519397 2011-08-20 00:00:00 0.07 77
USC00519397 2011-08-21 00:00:00 0.0 77
USC00519397 2011-08-22 00:00:00 0.0 78
USC00519397 2011-08-23 00:00:00 0.0 78
USC00519397 2011-08-24 00:00:00 0.0 79
USC00519397 2011-08-25 00:00:00 0.0 78
USC00519397 2011-08-26 00:00:00 0.0 78
USC00519397 2011-08-27 00:00:00 0.0 79
USC00519397 2011-08-28 00:00:00 0.05 76
USC00519397 2011-08-29 00:00:00 0.1 76
USC00519397 2011-08-30 00:00:00 0.02 78
USC00519397 2011-08-31 00:00:00 0.0 79
USC00519397 2011-09-02 00:00:00 0.0 79
USC00519397 2011-09-03 00:00:00 0.0 78
USC00519397 2011-09-04 00:00:00 0.03 77
USC00519397 2011-09-05 00:00:00 0.0 77
USC00519397 2011-09-06 00:00:00 0.0 73
USC00519397 2011-09-07 00:00:00 0.0 73
USC00519397 2011-09-08 00:00:00 0.0 77
USC00519397 2011-09-09 00:00:00 0.0 79
USC00519397 2011-09-10 00:00:00 0.0 77
USC00519397 2011-09-11 00:00:00 0.0 77
USC00519397 2011-09-12 00:00:00 0.0 85
USC00519397 2011-09-13 00:00:00 0.01 77
USC00519397 2011-09-14 00:00:00 0.0 76
USC00519397 2011-09-15 00:00:00 0.0 79
USC00519397 2011-09-16 00:00:00 0.0 79
USC00519397 2011-09-17 00:00:00 0.02 77
USC00519397 2011-09-18 00:00:00 0.04 77
USC00519397 2011-09-19 00:00:00 0.0 82
USC00519397 2011-09-20 00:00:00 0.0 80
USC00519397 2011-09-21 00:00:00 0.0 79
USC00519397 2011-09-22 00:00:00 0.03 78
USC00519397 2011-09-23 00:00:00 0.0 76
USC00519397 2011-09-24 00:00:00 0.0 77
USC00519397 2011-09-25 00:00:00 0.0 74
USC00519397 2011-09-26 00:00:00 0.0 77
USC00519397 2011-09-27 00:00:00 0.0 78
USC00519397 2011-09-28 00:00:00 0.0 77
USC00519397 2011-10-01 00:00:00 0.0 78
USC00519397 2011-10-02 00:00:00 0.0 78
USC00519397 2011-10-03 00:00:00 0.0 80
USC00519397 2011-10-06 00:00:00 0.0 75
USC00519397 2011-10-07 00:00:00 0.03 78
USC00519397 2011-10-08 00:00:00 0.0 79
USC00519397 2011-10-09 00:00:00 0.0 78
USC00519397 2011-10-10 00:00:00 0.02 77
USC00519397 2011-10-11 00:00:00 0.03 78
USC00519397 2011-10-12 00:00:00 0.0 77
USC00519397 2011-10-13 00:00:00 0.0 77
USC00519397 2011-10-14 00:00:00 0.03 78
USC00519397 2011-10-15 00:00:00 0.02 77
USC00519397 2011-10-16 00:00:00 0.0 76
USC00519397 2011-10-17 00:00:00 0.02 77
USC00519397 2011-10-18 00:00:00 0.01 76
USC00519397 2011-10-19 00:00:00 0.0 74
USC00519397 2011-10-20 00:00:00 0.0 78
USC00519397 2011-10-21 00:00:00 0.0 76
USC00519397 2011-10-22 00:00:00 0.0 77
USC00519397 2011-10-23 00:00:00 0.0 75
USC00519397 2011-10-24 00:00:00 0.14 74
USC00519397 2011-10-25 00:00:00 1.6 77
USC00519397 2011-10-26 00:00:00 0.01 76
USC00519397 2011-10-27 00:00:00 0.0 77
USC00519397 2011-10-28 00:00:00 0.05 73
USC00519397 2011-10-29 00:00:00 0.01 76
USC00519397 2011-10-30 00:00:00 0.0 75
USC00519397 2011-10-31 00:00:00 0.03 76
USC00519397 2011-11-01 00:00:00 0.58 71
USC00519397 2011-11-02 00:00:00 0.28 77

USC00519397 2011-11-03 00:00:00 0.02 77
USC00519397 2011-11-04 00:00:00 0.01 75
USC00519397 2011-11-05 00:00:00 0.0 76
USC00519397 2011-11-06 00:00:00 0.0 77
USC00519397 2011-11-07 00:00:00 0.0 78
USC00519397 2011-11-08 00:00:00 0.0 76
USC00519397 2011-11-09 00:00:00 0.02 76
USC00519397 2011-11-10 00:00:00 0.0 76
USC00519397 2011-11-11 00:00:00 0.05 74
USC00519397 2011-11-12 00:00:00 0.0 75
USC00519397 2011-11-13 00:00:00 0.0 76
USC00519397 2011-11-14 00:00:00 0.0 73
USC00519397 2011-11-15 00:00:00 0.0 71
USC00519397 2011-11-16 00:00:00 0.0 75
USC00519397 2011-11-17 00:00:00 0.0 76
USC00519397 2011-11-18 00:00:00 0.0 78
USC00519397 2011-11-19 00:00:00 0.0 76
USC00519397 2011-11-20 00:00:00 0.0 75
USC00519397 2011-11-21 00:00:00 0.01 76
USC00519397 2011-11-22 00:00:00 0.02 73
USC00519397 2011-11-23 00:00:00 0.01 75
USC00519397 2011-11-24 00:00:00 0.0 73
USC00519397 2011-11-25 00:00:00 0.01 70
USC00519397 2011-11-26 00:00:00 0.02 75
USC00519397 2011-11-27 00:00:00 0.07 73
USC00519397 2011-11-28 00:00:00 0.0 72
USC00519397 2011-11-29 00:00:00 0.0 72
USC00519397 2011-11-30 00:00:00 0.02 66
USC00519397 2011-12-01 00:00:00 0.03 69
USC00519397 2011-12-02 00:00:00 0.08 68
USC00519397 2011-12-03 00:00:00 0.0 73
USC00519397 2011-12-04 00:00:00 0.0 74
USC00519397 2011-12-05 00:00:00 0.0 73
USC00519397 2011-12-06 00:00:00 0.0 73
USC00519397 2011-12-07 00:00:00 0.0 73
USC00519397 2011-12-08 00:00:00 0.0 73
USC00519397 2011-12-09 00:00:00 0.13 71
USC00519397 2011-12-10 00:00:00 0.07 73
USC00519397 2011-12-11 00:00:00 0.07 73
USC00519397 2011-12-12 00:00:00 0.08 77
USC00519397 2011-12-13 00:00:00 0.4 72
USC00519397 2011-12-14 00:00:00 0.7 71
USC00519397 2011-12-15 00:00:00 0.0 73
USC00519397 2011-12-16 00:00:00 0.01 70
USC00519397 2011-12-17 00:00:00 0.07 73
USC00519397 2011-12-18 00:00:00 0.02 69
USC00519397 2011-12-19 00:00:00 0.15 74
USC00519397 2011-12-20 00:00:00 0.02 72
USC00519397 2011-12-21 00:00:00 0.18 71
USC00519397 2011-12-22 00:00:00 0.03 72
USC00519397 2011-12-23 00:00:00 0.04 72
USC00519397 2011-12-24 00:00:00 0.1 70
USC00519397 2011-12-25 00:00:00 0.03 73
USC00519397 2011-12-26 00:00:00 0.0 73
USC00519397 2011-12-27 00:00:00 0.0 72
USC00519397 2011-12-28 00:00:00 0.0 73
USC00519397 2011-12-29 00:00:00 0.0 73
USC00519397 2011-12-30 00:00:00 0.0 72
USC00519397 2011-12-31 00:00:00 0.01 63
USC00519397 2012-01-01 00:00:00 0.0 63
USC00519397 2012-01-02 00:00:00 0.0 66
USC00519397 2012-01-03 00:00:00 0.0 66
USC00519397 2012-01-04 00:00:00 0.0 74
USC00519397 2012-01-06 00:00:00 0.0 71
USC00519397 2012-01-07 00:00:00 0.0 65
USC00519397 2012-01-08 00:00:00 0.0 61
USC00519397 2012-01-10 00:00:00 0.0 71
USC00519397 2012-01-11 00:00:00 0.0 65
USC00519397 2012-01-12 00:00:00 0.0 66
USC00519397 2012-01-14 00:00:00 0.0 61
USC00519397 2012-01-15 00:00:00 0.0 74
USC00519397 2012-01-16 00:00:00 0.04 75
USC00519397 2012-01-17 00:00:00 0.0 75
USC00519397 2012-01-18 00:00:00 0.0 75
USC00519397 2012-01-19 00:00:00 0.02 68
USC00519397 2012-01-20 00:00:00 0.0 73
USC00519397 2012-01-21 00:00:00 0.0 74
USC00519397 2012-01-22 00:00:00 0.0 74
USC00519397 2012-01-23 00:00:00 0.0 67
USC00519397 2012-01-24 00:00:00 0.0 66
USC00519397 2012-01-25 00:00:00 0.0 69
USC00519397 2012-01-26 00:00:00 0.0 74
USC00519397 2012-01-27 00:00:00 0.04 68
USC00519397 2012-01-28 00:00:00 0.03 72
USC00519397 2012-01-29 00:00:00 1.03 72
USC00519397 2012-01-30 00:00:00 0.01 71
USC00519397 2012-01-31 00:00:00 0.0 71
USC00519397 2012-02-01 00:00:00 0.0 66
USC00519397 2012-02-02 00:00:00 0.0 72
USC00519397 2012-02-03 00:00:00 0.0 63
USC00519397 2012-02-04 00:00:00 0.0 65
USC00519397 2012-02-05 00:00:00 0.0 69
USC00519397 2012-02-06 00:00:00 0.0 71
USC00519397 2012-02-07 00:00:00 0.37 71
USC00519397 2012-02-08 00:00:00 0.28 65
USC00519397 2012-02-09 00:00:00 0.01 61
USC00519397 2012-02-10 00:00:00 0.0 71
USC00519397 2012-02-11 00:00:00 0.0 72
USC00519397 2012-02-12 00:00:00 0.0 72
USC00519397 2012-02-13 00:00:00 0.04 72
USC00519397 2012-02-14 00:00:00 0.01 65
USC00519397 2012-02-15 00:00:00 0.0 66
USC00519397 2012-02-16 00:00:00 0.0 73
USC00519397 2012-02-17 00:00:00 0.0 73
USC00519397 2012-02-18 00:00:00 0.04 71
USC00519397 2012-02-19 00:00:00 0.01 72
USC00519397 2012-02-20 00:00:00 0.0 73
USC00519397 2012-02-21 00:00:00 0.0 72
USC00519397 2012-02-22 00:00:00 0.0 73
USC00519397 2012-02-23 00:00:00 0.0 77
USC00519397 2012-02-24 00:00:00 0.0 67
USC00519397 2012-02-25 00:00:00 0.0 69
USC00519397 2012-02-26 00:00:00 0.05 73
USC00519397 2012-02-27 00:00:00 0.06 72
USC00519397 2012-02-28 00:00:00 0.0 73
USC00519397 2012-02-29 00:00:00 0.0 74
USC00519397 2012-03-01 00:00:00 0.06 73
USC00519397 2012-03-02 00:00:00 0.0 67
USC00519397 2012-03-03 00:00:00 0.03 71
USC00519397 2012-03-04 00:00:00 0.01 72
USC00519397 2012-03-05 00:00:00 1.08 67
USC00519397 2012-03-06 00:00:00 4.0 69
USC00519397 2012-03-07 00:00:00 2.42 67
USC00519397 2012-03-08 00:00:00 0.02 69
USC00519397 2012-03-09 00:00:00 0.19 66
USC00519397 2012-03-10 00:00:00 0.06 73
USC00519397 2012-03-11 00:00:00 0.0 74
USC00519397 2012-03-12 00:00:00 0.03 71
USC00519397 2012-03-13 00:00:00 0.0 72
USC00519397 2012-03-14 00:00:00 0.0 73
USC00519397 2012-03-15 00:00:00 0.0 71
USC00519397 2012-03-16 00:00:00 0.05 72
USC00519397 2012-03-17 00:00:00 0.0 73
USC00519397 2012-03-18 00:00:00 0.0 72
USC00519397 2012-03-19 00:00:00 0.0 73
USC00519397 2012-03-20 00:00:00 0.0 69
USC00519397 2012-03-21 00:00:00 0.0 73
USC00519397 2012-03-22 00:00:00 0.03 74
USC00519397 2012-03-23 00:00:00 0.01 72
USC00519397 2012-03-24 00:00:00 0.0 74
USC00519397 2012-03-25 00:00:00 0.0 74
USC00519397 2012-03-26 00:00:00 0.11 72
USC00519397 2012-03-27 00:00:00 0.03 70
USC00519397 2012-03-28 00:00:00 0.02 71
USC00519397 2012-03-29 00:00:00 0.0 72
USC00519397 2012-03-30 00:00:00 0.0 73
USC00519397 2012-03-31 00:00:00 0.0 74
USC00519397 2012-04-01 00:00:00 0.0 73
USC00519397 2012-04-02 00:00:00 0.0 74
USC00519397 2012-04-03 00:00:00 0.0 75
USC00519397 2012-04-04 00:00:00 0.0 74
USC00519397 2012-04-05 00:00:00 0.19 74
USC00519397 2012-04-06 00:00:00 0.0 74
USC00519397 2012-04-07 00:00:00 0.03 74
USC00519397 2012-04-08 00:00:00 0.0 74
USC00519397 2012-04-09 00:00:00 0.07 72
USC00519397 2012-04-10 00:00:00 0.05 69
USC00519397 2012-04-11 00:00:00 0.06 71
USC00519397 2012-04-12 00:00:00 0.0 70
USC00519397 2012-04-13 00:00:00 0.03 71
USC00519397 2012-04-14 00:00:00 0.0 70
USC00519397 2012-04-15 00:00:00 0.01 75
USC00519397 2012-04-16 00:00:00 0.01 75
USC00519397 2012-04-17 00:00:00 0.0 75
USC00519397 2012-04-18 00:00:00 0.0 75
USC00519397 2012-04-19 00:00:00 0.0 75
USC00519397 2012-04-20 00:00:00 0.0 75
USC00519397 2012-04-21 00:00:00 0.01 74
USC00519397 2012-04-22 00:00:00 0.04 69
USC00519397 2012-04-23 00:00:00 0.03 73
USC00519397 2012-04-24 00:00:00 0.0 73
USC00519397 2012-04-25 00:00:00 0.0 75
USC00519397 2012-04-26 00:00:00 0.0 74
USC00519397 2012-04-27 00:00:00 0.0 75
USC00519397 2012-04-28 00:00:00 0.0 76
USC00519397 2012-04-29 00:00:00 0.0 75
USC00519397 2012-04-30 00:00:00 0.0 75
USC00519397 2012-05-01 00:00:00 0.0 75
USC00519397 2012-05-02 00:00:00 0.0 75
USC00519397 2012-05-03 00:00:00 0.0 75
USC00519397 2012-05-04 00:00:00 0.0 75
USC00519397 2012-05-05 00:00:00 0.04 74
USC00519397 2012-05-06 00:00:00 0.0 75
USC00519397 2012-05-07 00:00:00 0.0 74
USC00519397 2012-05-08 00:00:00 0.0 75
USC00519397 2012-05-09 00:00:00 0.0 74
USC00519397 2012-05-10 00:00:00 0.0 74
USC00519397 2012-05-11 00:00:00 0.0 75
USC00519397 2012-05-12 00:00:00 0.0 75
USC00519397 2012-05-13 00:00:00 0.0 72
USC00519397 2012-05-14 00:00:00 0.0 74
USC00519397 2012-05-15 00:00:00 0.0 74
USC00519397 2012-05-16 00:00:00 0.0 75
USC00519397 2012-05-17 00:00:00 0.0 76
USC00519397 2012-05-18 00:00:00 0.0 77
USC00519397 2012-05-19 00:00:00 0.0 77
USC00519397 2012-05-20 00:00:00 0.0 77
USC00519397 2012-05-21 00:00:00 0.0 76
USC00519397 2012-05-22 00:00:00 0.0 77
USC00519397 2012-05-23 00:00:00 0.0 76
USC00519397 2012-05-24 00:00:00 0.0 78
USC00519397 2012-05-25 00:00:00 0.0 77
USC00519397 2012-05-26 00:00:00 0.0 76
USC00519397 2012-05-27 00:00:00 0.0 76
USC00519397 2012-05-28 00:00:00 0.0 77
USC00519397 2012-05-29 00:00:00 0.0 76
USC00519397 2012-05-30 00:00:00 0.0 76
USC00519397 2012-05-31 00:00:00 0.01 73
USC00519397 2012-06-01 00:00:00 0.02 76
USC00519397 2012-06-02 00:00:00 0.02 76
USC00519397 2012-06-03 00:00:00 0.0 75
USC00519397 2012-06-04 00:00:00 0.0 77
USC00519397 2012-06-05 00:00:00 0.0 77
USC00519397 2012-06-06 00:00:00 0.0 76
USC00519397 2012-06-07 00:00:00 0.0 78
USC00519397 2012-06-10 00:00:00 0.0 77
USC00519397 2012-06-11 00:00:00 0.0 76
USC00519397 2012-06-12 00:00:00 0.0 76
USC00519397 2012-06-13 00:00:00 0.0 77
USC00519397 2012-06-14 00:00:00 0.0 77
USC00519397 2012-06-15 00:00:00 0.0 78
USC00519397 2012-06-16 00:00:00 0.0 77
USC00519397 2012-06-17 00:00:00 0.0 77
USC00519397 2012-06-18 00:00:00 0.0 77
USC00519397 2012-06-19 00:00:00 0.0 76
USC00519397 2012-06-20 00:00:00 0.0 75
USC00519397 2012-06-21 00:00:00 0.0 76
USC00519397 2012-06-22 00:00:00 0.0 76
USC00519397 2012-06-23 00:00:00 0.0 77
USC00519397 2012-06-24 00:00:00 0.0 76
USC00519397 2012-06-25 00:00:00 0.03 73
USC00519397 2012-06-26 00:00:00 0.15 73
USC00519397 2012-06-27 00:00:00 0.01 75
USC00519397 2012-06-28 00:00:00 0.0 77
USC00519397 2012-06-29 00:00:00 0.05 76
USC00519397 2012-06-30 00:00:00 0.0 77
USC00519397 2012-07-01 00:00:00 0.0 76
USC00519397 2012-07-02 00:00:00 0.0 77
USC00519397 2012-07-03 00:00:00 0.04 74
USC00519397 2012-07-04 00:00:00 0.01 77
USC00519397 2012-07-05 00:00:00 0.03 77
USC00519397 2012-07-06 00:00:00 0.0 78
USC00519397 2012-07-07 00:00:00 0.04 76
USC00519397 2012-07-08 00:00:00 0.0 77
USC00519397 2012-07-10 00:00:00 0.0 76
USC00519397 2012-07-11 00:00:00 0.0 76
USC00519397 2012-07-12 00:00:00 0.0 76
USC00519397 2012-07-13 00:00:00 0.0 77
USC00519397 2012-07-14 00:00:00 0.0 78
USC00519397 2012-07-15 00:00:00 0.0 77
USC00519397 2012-07-16 00:00:00 0.01 78
USC00519397 2012-07-17 00:00:00 0.0 78
USC00519397 2012-07-18 00:00:00 0.0 78
USC00519397 2012-07-19 00:00:00 0.0 75
USC00519397 2012-07-20 00:00:00 0.0 77
USC00519397 2012-07-21 00:00:00 0.0 76
USC00519397 2012-07-22 00:00:00 0.0 76
USC00519397 2012-07-23 00:00:00 0.0 79
USC00519397 2012-07-24 00:00:00 0.0 77
USC00519397 2012-07-25 00:00:00 0.0 77
USC00519397 2012-07-26 00:00:00 0.02 77
USC00519397 2012-07-27 00:00:00 0.0 77
USC00519397 2012-07-28 00:00:00 0.0 77
USC00519397 2012-07-29 00:00:00 0.01 73
USC00519397 2012-07-30 00:00:00 0.01 78
USC00519397 2012-07-31 00:00:00 0.0 78
USC00519397 2012-08-01 00:00:00 0.0 79
USC00519397 2012-08-02 00:00:00 0.0 78
USC00519397 2012-08-03 00:00:00 0.0 78
USC00519397 2012-08-04 00:00:00 0.0 78
USC00519397 2012-08-05 00:00:00 0.0 78
USC00519397 2012-08-06 00:00:00 0.0 77
USC00519397 2012-08-07 00:00:00 0.0 77
USC00519397 2012-08-08 00:00:00 0.02 78
USC00519397 2012-08-09 00:00:00 0.0 78
USC00519397 2012-08-10 00:00:00 0.0 76
USC00519397 2012-08-11 00:00:00 0.0 75
USC00519397 2012-08-12 00:00:00 0.0 78
USC00519397 2012-08-13 00:00:00 0.0 78
USC00519397 2012-08-14 00:00:00 0.0 77
USC00519397 2012-08-15 00:00:00 0.01 79
USC00519397 2012-08-16 00:00:00 0.0 78
USC00519397 2012-08-17 00:00:00 0.0 78
USC00519397 2012-08-20 00:00:00 0.0 79
USC00519397 2012-08-21 00:00:00 0.0 77
USC00519397 2012-08-22 00:00:00 0.03 77
USC00519397 2012-08-23 00:00:00 0.0 78
USC00519397 2012-08-24 00:00:00 0.0 78
USC00519397 2012-08-25 00:00:00 0.0 78
USC00519397 2012-08-26 00:00:00 0.0 78
USC00519397 2012-08-27 00:00:00 0.02 73
USC00519397 2012-08-28 00:00:00 1.0 75
USC00519397 2012-08-29 00:00:00 0.02 78
USC00519397 2012-08-30 00:00:00 0.04 78
USC00519397 2012-08-31 00:00:00 0.0 78
USC00519397 2012-09-01 00:00:00 0.01 77
USC00519397 2012-09-02 00:00:00 0.04 76
USC00519397 2012-09-03 00:00:00 0.06 77
USC00519397 2012-09-04 00:00:00 0.0 77
USC00519397 2012-09-05 00:00:00 0.01 75
USC00519397 2012-09-06 00:00:00 0.04 77
USC00519397 2012-09-07 00:00:00 0.0 75
USC00519397 2012-09-08 00:00:00 0.06 78
USC00519397 2012-09-09 00:00:00 0.0 76
USC00519397 2012-09-10 00:00:00 0.0 77
USC00519397 2012-09-11 00:00:00 0.0 77

USC00519397 2012-09-12 00:00:00 0.02 76
USC00519397 2012-09-13 00:00:00 0.05 76
USC00519397 2012-09-14 00:00:00 0.04 78
USC00519397 2012-09-15 00:00:00 0.0 78
USC00519397 2012-09-16 00:00:00 0.0 77
USC00519397 2012-09-17 00:00:00 0.0 78
USC00519397 2012-09-18 00:00:00 0.06 71
USC00519397 2012-09-19 00:00:00 0.0 74
USC00519397 2012-09-20 00:00:00 0.07 76
USC00519397 2012-09-21 00:00:00 0.08 77
USC00519397 2012-09-22 00:00:00 0.0 77
USC00519397 2012-09-23 00:00:00 0.04 76
USC00519397 2012-09-24 00:00:00 0.0 77
USC00519397 2012-09-25 00:00:00 0.0 76
USC00519397 2012-09-26 00:00:00 0.01 76
USC00519397 2012-09-27 00:00:00 0.02 78
USC00519397 2012-09-28 00:00:00 0.0 78
USC00519397 2012-09-29 00:00:00 0.0 77
USC00519397 2012-09-30 00:00:00 0.02 75
USC00519397 2012-10-01 00:00:00 0.0 78
USC00519397 2012-10-02 00:00:00 0.0 74
USC00519397 2012-10-03 00:00:00 0.0 75
USC00519397 2012-10-04 00:00:00 0.0 77
USC00519397 2012-10-05 00:00:00 0.0 73
USC00519397 2012-10-06 00:00:00 0.03 73
USC00519397 2012-10-07 00:00:00 0.0 76
USC00519397 2012-10-08 00:00:00 0.0 78
USC00519397 2012-10-09 00:00:00 0.0 75
USC00519397 2012-10-10 00:00:00 0.0 75
USC00519397 2012-10-11 00:00:00 0.0 80
USC00519397 2012-10-12 00:00:00 0.0 78
USC00519397 2012-10-13 00:00:00 0.0 79
USC00519397 2012-10-14 00:00:00 0.0 78
USC00519397 2012-10-15 00:00:00 0.02 78
USC00519397 2012-10-16 00:00:00 0.0 77
USC00519397 2012-10-17 00:00:00 0.0 72
USC00519397 2012-10-18 00:00:00 0.0 75
USC00519397 2012-10-19 00:00:00 0.0 77
USC00519397 2012-10-20 00:00:00 0.0 78
USC00519397 2012-10-21 00:00:00 0.0 77
USC00519397 2012-10-22 00:00:00 0.0 76
USC00519397 2012-10-23 00:00:00 0.0 78
USC00519397 2012-10-24 00:00:00 0.0 78
USC00519397 2012-10-25 00:00:00 0.0 76
USC00519397 2012-10-26 00:00:00 0.0 76
USC00519397 2012-10-27 00:00:00 0.0 74
USC00519397 2012-10-28 00:00:00 0.02 77
USC00519397 2012-10-29 00:00:00 0.04 77
USC00519397 2012-10-30 00:00:00 0.0 76
USC00519397 2012-10-31 00:00:00 0.02 78
USC00519397 2012-11-01 00:00:00 0.0 71
USC00519397 2012-11-02 00:00:00 0.0 70
USC00519397 2012-11-03 00:00:00 0.0 74
USC00519397 2012-11-04 00:00:00 0.0 71
USC00519397 2012-11-05 00:00:00 0.0 69
USC00519397 2012-11-06 00:00:00 0.0 76
USC00519397 2012-11-07 00:00:00 0.0 77
USC00519397 2012-11-08 00:00:00 0.0 77
USC00519397 2012-11-09 00:00:00 0.03 76
USC00519397 2012-11-10 00:00:00 0.0 75
USC00519397 2012-11-11 00:00:00 0.0 76
USC00519397 2012-11-12 00:00:00 0.0 77
USC00519397 2012-11-13 00:00:00 0.06 77
USC00519397 2012-11-14 00:00:00 0.0 77
USC00519397 2012-11-15 00:00:00 0.08 75
USC00519397 2012-11-16 00:00:00 0.03 73
USC00519397 2012-11-17 00:00:00 0.01 74
USC00519397 2012-11-18 00:00:00 0.03 76
USC00519397 2012-11-19 00:00:00 0.0 75
USC00519397 2012-11-20 00:00:00 0.0 75
USC00519397 2012-11-21 00:00:00 0.0 71
USC00519397 2012-11-22 00:00:00 0.0 69
USC00519397 2012-11-23 00:00:00 0.0 71
USC00519397 2012-11-24 00:00:00 0.02 69
USC00519397 2012-11-25 00:00:00 0.0 74
USC00519397 2012-11-26 00:00:00 0.06 72
USC00519397 2012-11-27 00:00:00 0.0 74
USC00519397 2012-11-28 00:00:00 0.0 65
USC00519397 2012-11-29 00:00:00 0.0 67
USC00519397 2012-11-30 00:00:00 0.0 65
USC00519397 2012-12-01 00:00:00 0.0 65
USC00519397 2012-12-02 00:00:00 0.0 71
USC00519397 2012-12-03 00:00:00 0.0 76
USC00519397 2012-12-04 00:00:00 0.2 70
USC00519397 2012-12-05 00:00:00 0.01 76
USC00519397 2012-12-08 00:00:00 0.0 69
USC00519397 2012-12-09 00:00:00 0.0 74
USC00519397 2012-12-10 00:00:00 0.0 76
USC00519397 2012-12-11 00:00:00 0.0 74
USC00519397 2012-12-12 00:00:00 0.0 73
USC00519397 2012-12-13 00:00:00 0.14 73
USC00519397 2012-12-14 00:00:00 0.09 74
USC00519397 2012-12-15 00:00:00 0.01 73
USC00519397 2012-12-16 00:00:00 0.02 73
USC00519397 2012-12-17 00:00:00 0.02 73
USC00519397 2012-12-18 00:00:00 0.12 74
USC00519397 2012-12-19 00:00:00 0.0 74
USC00519397 2012-12-20 00:00:00 0.1 71
USC00519397 2012-12-21 00:00:00 0.0 73
USC00519397 2012-12-22 00:00:00 0.0 72
USC00519397 2012-12-23 00:00:00 0.0 64
USC00519397 2012-12-24 00:00:00 0.0 66
USC00519397 2012-12-26 00:00:00 0.03 73
USC00519397 2012-12-27 00:00:00 0.0 72
USC00519397 2012-12-28 00:00:00 0.0 65
USC00519397 2012-12-29 00:00:00 0.0 64
USC00519397 2012-12-30 00:00:00 0.0 69
USC00519397 2012-12-31 00:00:00 0.04 68
USC00519397 2013-01-01 00:00:00 0.02 71
USC00519397 2013-01-02 00:00:00 0.13 71
USC00519397 2013-01-03 00:00:00 0.23 69
USC00519397 2013-01-04 00:00:00 0.04 72
USC00519397 2013-01-05 00:00:00 0.03 72
USC00519397 2013-01-06 00:00:00 0.04 73
USC00519397 2013-01-07 00:00:00 0.04 72
USC00519397 2013-01-08 00:00:00 0.0 72
USC00519397 2013-01-09 00:00:00 0.09 71
USC00519397 2013-01-12 00:00:00 0.0 70
USC00519397 2013-01-13 00:00:00 0.0 68
USC00519397 2013-01-14 00:00:00 0.0 74
USC00519397 2013-01-15 00:00:00 0.4 63
USC00519397 2013-01-16 00:00:00 0.0 58
USC00519397 2013-01-17 00:00:00 0.0 62
USC00519397 2013-01-18 00:00:00 0.0 60
USC00519397 2013-01-19 00:00:00 0.0 60
USC00519397 2013-01-20 00:00:00 0.0 67
USC00519397 2013-01-21 00:00:00 0.0 71
USC00519397 2013-01-22 00:00:00 0.0 70
USC00519397 2013-01-23 00:00:00 0.0 71
USC00519397 2013-01-24 00:00:00 0.14 68
USC00519397 2013-01-25 00:00:00 0.43 64
USC00519397 2013-01-26 00:00:00 0.0 65
USC00519397 2013-01-27 00:00:00 0.0 73
USC00519397 2013-01-28 00:00:00 1.13 66
USC00519397 2013-01-29 00:00:00 0.04 68
USC00519397 2013-01-30 00:00:00 0.0 64
USC00519397 2013-01-31 00:00:00 0.0 71
USC00519397 2013-02-01 00:00:00 0.0 71
USC00519397 2013-02-02 00:00:00 0.0 72
USC00519397 2013-02-03 00:00:00 0.0 67
USC00519397 2013-02-04 00:00:00 0.0 71
USC00519397 2013-02-05 00:00:00 0.0 71
USC00519397 2013-02-06 00:00:00 0.04 70
USC00519397 2013-02-07 00:00:00 0.04 71
USC00519397 2013-02-08 00:00:00 0.0 72
USC00519397 2013-02-09 00:00:00 0.01 67
USC00519397 2013-02-10 00:00:00 0.0 72
USC00519397 2013-02-11 00:00:00 0.0 70
USC00519397 2013-02-12 00:00:00 0.0 70
USC00519397 2013-02-13 00:00:00 0.0 69
USC00519397 2013-02-14 00:00:00 0.0 69
USC00519397 2013-02-15 00:00:00 0.0 71
USC00519397 2013-02-16 00:00:00 0.0 71
USC00519397 2013-02-17 00:00:00 0.0 71
USC00519397 2013-02-18 00:00:00 0.0 71
USC00519397 2013-02-19 00:00:00 0.09 71
USC00519397 2013-02-20 00:00:00 0.09 71
USC00519397 2013-02-21 00:00:00 0.07 71
USC00519397 2013-02-22 00:00:00 0.31 72
USC00519397 2013-02-23 00:00:00 0.15 71
USC00519397 2013-02-24 00:00:00 0.04 71
USC00519397 2013-02-25 00:00:00 0.0 71
USC00519397 2013-02-26 00:00:00 0.01 71
USC00519397 2013-02-27 00:00:00 0.03 71
USC00519397 2013-02-28 00:00:00 0.0 72
USC00519397 2013-03-01 00:00:00 0.0 71
USC00519397 2013-03-02 00:00:00 0.0 72
USC00519397 2013-03-03 00:00:00 0.0 72
USC00519397 2013-03-04 00:00:00 0.0 70
USC00519397 2013-03-05 00:00:00 0.0 71
USC00519397 2013-03-06 00:00:00 0.0 71
USC00519397 2013-03-07 00:00:00 0.0 65
USC00519397 2013-03-08 00:00:00 0.0 64
USC00519397 2013-03-09 00:00:00 0.02 73
USC00519397 2013-03-10 00:00:00 1.29 68
USC00519397 2013-03-11 00:00:00 0.8 63
USC00519397 2013-03-12 00:00:00 0.01 66
USC00519397 2013-03-13 00:00:00 0.0 63
USC00519397 2013-03-14 00:00:00 0.0 66
USC00519397 2013-03-15 00:00:00 0.0 64
USC00519397 2013-03-16 00:00:00 0.0 69
USC00519397 2013-03-17 00:00:00 0.0 62
USC00519397 2013-03-18 00:00:00 0.0 64
USC00519397 2013-03-19 00:00:00 0.0 66
USC00519397 2013-03-20 00:00:00 0.0 69
USC00519397 2013-03-21 00:00:00 0.0 71
USC00519397 2013-03-22 00:00:00 0.0 74
USC00519397 2013-03-23 00:00:00 0.02 72
USC00519397 2013-03-24 00:00:00 0.0 71
USC00519397 2013-03-25 00:00:00 0.32 68
USC00519397 2013-03-26 00:00:00 0.0 69
USC00519397 2013-03-27 00:00:00 0.0 71
USC00519397 2013-03-28 00:00:00 0.3 72
USC00519397 2013-03-29 00:00:00 0.06 70
USC00519397 2013-03-30 00:00:00 0.01 70
USC00519397 2013-03-31 00:00:00 0.25 64
USC00519397 2013-04-01 00:00:00 0.0 63
USC00519397 2013-04-02 00:00:00 0.0 61
USC00519397 2013-04-03 00:00:00 0.0 67
USC00519397 2013-04-04 00:00:00 0.0 68
USC00519397 2013-04-05 00:00:00 0.0 73
USC00519397 2013-04-06 00:00:00 0.03 74
USC00519397 2013-04-07 00:00:00 0.0 71
USC00519397 2013-04-08 00:00:00 0.0 74
USC00519397 2013-04-09 00:00:00 0.0 74
USC00519397 2013-04-10 00:00:00 0.0 74
USC00519397 2013-04-11 00:00:00 0.01 77
USC00519397 2013-04-12 00:00:00 0.0 75
USC00519397 2013-04-13 00:00:00 0.0 75
USC00519397 2013-04-14 00:00:00 0.0 76
USC00519397 2013-04-15 00:00:00 0.8 72
USC00519397 2013-04-16 00:00:00 0.08 70
USC00519397 2013-04-17 00:00:00 0.0 77
USC00519397 2013-04-18 00:00:00 0.0 75
USC00519397 2013-04-19 00:00:00 0.01 75
USC00519397 2013-04-20 00:00:00 0.0 74
USC00519397 2013-04-21 00:00:00 0.0 73
USC00519397 2013-04-22 00:00:00 0.05 73
USC00519397 2013-04-23 00:00:00 0.01 76
USC00519397 2013-04-24 00:00:00 0.55 70
USC00519397 2013-04-25 00:00:00 0.01 76
USC00519397 2013-04-26 00:00:00 0.0 76
USC00519397 2013-04-27 00:00:00 0.0 74
USC00519397 2013-04-28 00:00:00 0.0 72
USC00519397 2013-04-29 00:00:00 0.0 76
USC00519397 2013-04-30 00:00:00 0.0 74
USC00519397 2013-05-01 00:00:00 0.0 78
USC00519397 2013-05-02 00:00:00 0.0 75
USC00519397 2013-05-03 00:00:00 0.0 84
USC00519397 2013-05-04 00:00:00 0.14 69
USC00519397 2013-05-05 00:00:00 0.12 69
USC00519397 2013-05-06 00:00:00 0.09 75
USC00519397 2013-05-07 00:00:00 0.0 72
USC00519397 2013-05-08 00:00:00 0.0 73
USC00519397 2013-05-09 00:00:00 0.0 77
USC00519397 2013-05-10 00:00:00 0.0 77
USC00519397 2013-05-11 00:00:00 0.0 76
USC00519397 2013-05-12 00:00:00 0.0 75
USC00519397 2013-05-13 00:00:00 0.0 77
USC00519397 2013-05-14 00:00:00 0.0 78
USC00519397 2013-05-15 00:00:00 0.0 77
USC00519397 2013-05-16 00:00:00 0.0 77
USC00519397 2013-05-17 00:00:00 0.0 77
USC00519397 2013-05-18 00:00:00 0.02 78
USC00519397 2013-05-19 00:00:00 0.04 73
USC00519397 2013-05-20 00:00:00 0.03 74
USC00519397 2013-05-21 00:00:00 0.0 71
USC00519397 2013-05-22 00:00:00 0.0 78
USC00519397 2013-05-23 00:00:00 0.0 79
USC00519397 2013-05-24 00:00:00 0.0 79
USC00519397 2013-05-25 00:00:00 0.0 77
USC00519397 2013-05-26 00:00:00 0.0 77
USC00519397 2013-05-27 00:00:00 0.0 78
USC00519397 2013-05-28 00:00:00 0.04 77
USC00519397 2013-05-29 00:00:00 0.0 78
USC00519397 2013-05-30 00:00:00 0.03 77
USC00519397 2013-05-31 00:00:00 0.0 79
USC00519397 2013-06-01 00:00:00 0.01 79
USC00519397 2013-06-02 00:00:00 0.0 78
USC00519397 2013-06-03 00:00:00 0.0 79
USC00519397 2013-06-04 00:00:00 0.0 78
USC00519397 2013-06-05 00:00:00 0.0 78
USC00519397 2013-06-06 00:00:00 0.0 79
USC00519397 2013-06-07 00:00:00 0.0 77
USC00519397 2013-06-08 00:00:00 0.0 77
USC00519397 2013-06-09 00:00:00 0.0 77
USC00519397 2013-06-10 00:00:00 0.0 77
USC00519397 2013-06-11 00:00:00 0.0 77
USC00519397 2013-06-12 00:00:00 0.0 78
USC00519397 2013-06-13 00:00:00 0.0 77
USC00519397 2013-06-14 00:00:00 0.37 76
USC00519397 2013-06-15 00:00:00 0.0 78
USC00519397 2013-06-16 00:00:00 0.0 78
USC00519397 2013-06-17 00:00:00 0.0 77
USC00519397 2013-06-18 00:00:00 0.01 78
USC00519397 2013-06-19 00:00:00 0.0 78
USC00519397 2013-06-20 00:00:00 0.04 73
USC00519397 2013-06-21 00:00:00 0.12 76
USC00519397 2013-06-22 00:00:00 0.04 77
USC00519397 2013-06-23 00:00:00 0.02 75
USC00519397 2013-06-24 00:00:00 0.35 76

USC00519397 2013-06-25 00:00:00 0.03 74
USC00519397 2013-06-26 00:00:00 0.01 75
USC00519397 2013-06-27 00:00:00 0.0 77
USC00519397 2013-06-28 00:00:00 0.0 76
USC00519397 2013-06-29 00:00:00 0.03 77
USC00519397 2013-06-30 00:00:00 0.01 78
USC00519397 2013-07-01 00:00:00 0.0 78
USC00519397 2013-07-02 00:00:00 0.0 77
USC00519397 2013-07-03 00:00:00 0.03 77
USC00519397 2013-07-04 00:00:00 0.0 78
USC00519397 2013-07-05 00:00:00 0.0 73
USC00519397 2013-07-06 00:00:00 0.0 76
USC00519397 2013-07-07 00:00:00 0.0 75
USC00519397 2013-07-08 00:00:00 0.0 79
USC00519397 2013-07-09 00:00:00 0.0 80
USC00519397 2013-07-10 00:00:00 0.0 79
USC00519397 2013-07-11 00:00:00 0.03 77
USC00519397 2013-07-12 00:00:00 0.01 79
USC00519397 2013-07-13 00:00:00 0.0 78
USC00519397 2013-07-14 00:00:00 0.0 78
USC00519397 2013-07-15 00:00:00 0.0 78
USC00519397 2013-07-16 00:00:00 0.0 78
USC00519397 2013-07-17 00:00:00 0.0 78
USC00519397 2013-07-18 00:00:00 0.0 78
USC00519397 2013-07-19 00:00:00 0.0 78
USC00519397 2013-07-20 00:00:00 0.0 78
USC00519397 2013-07-21 00:00:00 0.07 78
USC00519397 2013-07-22 00:00:00 0.0 79
USC00519397 2013-07-23 00:00:00 0.0 77
USC00519397 2013-07-25 00:00:00 0.0 78
USC00519397 2013-07-26 00:00:00 0.0 78
USC00519397 2013-07-27 00:00:00 0.0 78
USC00519397 2013-07-28 00:00:00 0.02 76
USC00519397 2013-07-29 00:00:00 0.06 78
USC00519397 2013-07-30 00:00:00 0.74 79
USC00519397 2013-07-31 00:00:00 0.01 79
USC00519397 2013-08-01 00:00:00 0.02 79
USC00519397 2013-08-02 00:00:00 0.0 78
USC00519397 2013-08-03 00:00:00 0.0 78
USC00519397 2013-08-04 00:00:00 0.0 77
USC00519397 2013-08-05 00:00:00 0.0 79
USC00519397 2013-08-06 00:00:00 0.0 79
USC00519397 2013-08-07 00:00:00 0.0 79
USC00519397 2013-08-08 00:00:00 0.0 79
USC00519397 2013-08-09 00:00:00 0.0 78
USC00519397 2013-08-10 00:00:00 0.03 76
USC00519397 2013-08-11 00:00:00 0.05 79
USC00519397 2013-08-12 00:00:00 0.0 79
USC00519397 2013-08-13 00:00:00 0.0 79
USC00519397 2013-08-14 00:00:00 0.02 78
USC00519397 2013-08-15 00:00:00 0.0 78
USC00519397 2013-08-16 00:00:00 0.01 76
USC00519397 2013-08-17 00:00:00 0.0 78
USC00519397 2013-08-18 00:00:00 0.0 78
USC00519397 2013-08-19 00:00:00 0.0 77
USC00519397 2013-08-20 00:00:00 0.0 74
USC00519397 2013-08-21 00:00:00 0.25 77
USC00519397 2013-08-22 00:00:00 0.0 79
USC00519397 2013-08-23 00:00:00 0.0 77
USC00519397 2013-08-24 00:00:00 0.0 79
USC00519397 2013-08-25 00:00:00 0.0 80
USC00519397 2013-08-26 00:00:00 0.0 80
USC00519397 2013-08-27 00:00:00 0.0 79
USC00519397 2013-08-28 00:00:00 0.0 76
USC00519397 2013-08-29 00:00:00 0.0 79
USC00519397 2013-08-30 00:00:00 0.0 78
USC00519397 2013-08-31 00:00:00 0.0 79
USC00519397 2013-09-01 00:00:00 0.02 78
USC00519397 2013-09-02 00:00:00 0.0 79
USC00519397 2013-09-03 00:00:00 0.0 79
USC00519397 2013-09-04 00:00:00 0.0 77
USC00519397 2013-09-05 00:00:00 0.0 74
USC00519397 2013-09-06 00:00:00 0.0 74
USC00519397 2013-09-07 00:00:00 0.14 75
USC00519397 2013-09-08 00:00:00 0.01 80
USC00519397 2013-09-09 00:00:00 0.0 79
USC00519397 2013-09-10 00:00:00 0.0 78
USC00519397 2013-09-11 00:00:00 0.0 79
USC00519397 2013-09-12 00:00:00 0.03 78
USC00519397 2013-09-13 00:00:00 0.02 78
USC00519397 2013-09-14 00:00:00 0.14 83
USC00519397 2013-09-15 00:00:00 0.01 79
USC00519397 2013-09-16 00:00:00 0.0 70
USC00519397 2013-09-17 00:00:00 0.02 76
USC00519397 2013-09-18 00:00:00 0.14 78
USC00519397 2013-09-19 00:00:00 0.02 78
USC00519397 2013-09-20 00:00:00 0.0 80
USC00519397 2013-09-21 00:00:00 0.02 77
USC00519397 2013-09-22 00:00:00 0.02 79
USC00519397 2013-09-23 00:00:00 0.01 77
USC00519397 2013-09-24 00:00:00 0.01 78
USC00519397 2013-09-25 00:00:00 0.25 79
USC00519397 2013-09-26 00:00:00 0.07 78
USC00519397 2013-09-27 00:00:00 0.0 79
USC00519397 2013-09-28 00:00:00 0.0 79
USC00519397 2013-09-29 00:00:00 0.08 78
USC00519397 2013-09-30 00:00:00 0.02 79
USC00519397 2013-10-01 00:00:00 0.0 79
USC00519397 2013-10-02 00:00:00 0.0 80
USC00519397 2013-10-03 00:00:00 0.0 81
USC00519397 2013-10-04 00:00:00 0.0 80
USC00519397 2013-10-05 00:00:00 0.0 74
USC00519397 2013-10-06 00:00:00 0.0 78
USC00519397 2013-10-07 00:00:00 0.0 80
USC00519397 2013-10-08 00:00:00 0.0 79
USC00519397 2013-10-09 00:00:00 0.0 79
USC00519397 2013-10-10 00:00:00 0.0 78
USC00519397 2013-10-11 00:00:00 0.0 78
USC00519397 2013-10-12 00:00:00 0.0 77
USC00519397 2013-10-13 00:00:00 0.0 76
USC00519397 2013-10-14 00:00:00 0.18 73
USC00519397 2013-10-15 00:00:00 0.02 74
USC00519397 2013-10-16 00:00:00 0.0 75
USC00519397 2013-10-17 00:00:00 0.0 74
USC00519397 2013-10-18 00:00:00 0.0 75
USC00519397 2013-10-19 00:00:00 0.0 71
USC00519397 2013-10-20 00:00:00 0.0 73
USC00519397 2013-10-21 00:00:00 0.0 72
USC00519397 2013-10-22 00:00:00 0.0 73
USC00519397 2013-10-23 00:00:00 0.0 74
USC00519397 2013-10-24 00:00:00 0.0 74
USC00519397 2013-10-25 00:00:00 0.0 80
USC00519397 2013-10-26 00:00:00 0.0 76
USC00519397 2013-10-27 00:00:00 0.0 76
USC00519397 2013-10-28 00:00:00 0.01 74
USC00519397 2013-10-29 00:00:00 0.0 77
USC00519397 2013-10-30 00:00:00 0.0 78
USC00519397 2013-10-31 00:00:00 0.0 78
USC00519397 2013-11-01 00:00:00 0.0 79
USC00519397 2013-11-02 00:00:00 0.02 78
USC00519397 2013-11-03 00:00:00 0.0 77
USC00519397 2013-11-04 00:00:00 0.01 74
USC00519397 2013-11-05 00:00:00 0.0 77
USC00519397 2013-11-06 00:00:00 0.0 73
USC00519397 2013-11-07 00:00:00 0.02 74
USC00519397 2013-11-08 00:00:00 0.0 74
USC00519397 2013-11-09 00:00:00 0.01 76
USC00519397 2013-11-10 00:00:00 1.98 72
USC00519397 2013-11-11 00:00:00 0.2 74
USC00519397 2013-11-12 00:00:00 0.0 68
USC00519397 2013-11-13 00:00:00 0.0 67
USC00519397 2013-11-14 00:00:00 0.0 76
USC00519397 2013-11-15 00:00:00 0.89 75
USC00519397 2013-11-16 00:00:00 0.0 77
USC00519397 2013-11-17 00:00:00 0.0 71
USC00519397 2013-11-18 00:00:00 0.0 74
USC00519397 2013-11-19 00:00:00 0.0 70
USC00519397 2013-11-20 00:00:00 0.0 72
USC00519397 2013-11-21 00:00:00 0.0 72
USC00519397 2013-11-22 00:00:00 0.0 69
USC00519397 2013-11-23 00:00:00 0.0 69
USC00519397 2013-11-24 00:00:00 0.0 66
USC00519397 2013-11-25 00:00:00 0.0 75
USC00519397 2013-11-26 00:00:00 0.0 76
USC00519397 2013-11-27 00:00:00 0.0 73
USC00519397 2013-11-28 00:00:00 0.0 74
USC00519397 2013-11-29 00:00:00 0.0 74
USC00519397 2013-11-30 00:00:00 0.18 77
USC00519397 2013-12-01 00:00:00 0.0 77
USC00519397 2013-12-02 00:00:00 2.01 71
USC00519397 2013-12-03 00:00:00 0.01 71
USC00519397 2013-12-04 00:00:00 0.0 69
USC00519397 2013-12-05 00:00:00 0.0 68
USC00519397 2013-12-06 00:00:00 0.0 68
USC00519397 2013-12-07 00:00:00 0.0 69
USC00519397 2013-12-08 00:00:00 0.0 70
USC00519397 2013-12-09 00:00:00 0.0 72
USC00519397 2013-12-10 00:00:00 0.03 76
USC00519397 2013-12-11 00:00:00 0.0 75
USC00519397 2013-12-12 00:00:00 0.0 69
USC00519397 2013-12-13 00:00:00 0.02 71
USC00519397 2013-12-14 00:00:00 0.0 71
USC00519397 2013-12-15 00:00:00 0.0 71
USC00519397 2013-12-16 00:00:00 1.1 68
USC00519397 2013-12-17 00:00:00 0.02 65
USC00519397 2013-12-18 00:00:00 0.0 70
USC00519397 2013-12-19 00:00:00 0.16 69
USC00519397 2013-12-20 00:00:00 0.09 69
USC00519397 2013-12-21 00:00:00 0.02 71
USC00519397 2013-12-22 00:00:00 0.0 67
USC00519397 2013-12-23 00:00:00 0.0 73
USC00519397 2013-12-24 00:00:00 0.05 74
USC00519397 2013-12-25 00:00:00 0.02 73
USC00519397 2013-12-26 00:00:00 0.0 67
USC00519397 2013-12-27 00:00:00 0.0 74
USC00519397 2013-12-28 00:00:00 0.0 75
USC00519397 2013-12-29 00:00:00 0.0 75
USC00519397 2013-12-30 00:00:00 0.0 74
USC00519397 2013-12-31 00:00:00 0.0 67
USC00519397 2014-01-01 00:00:00 0.0 66
USC00519397 2014-01-02 00:00:00 0.0 75
USC00519397 2014-01-03 00:00:00 0.76 65
USC00519397 2014-01-04 00:00:00 0.0 69
USC00519397 2014-01-05 00:00:00 0.0 68
USC00519397 2014-01-06 00:00:00 0.0 71
USC00519397 2014-01-07 00:00:00 0.0 70
USC00519397 2014-01-08 00:00:00 0.0 71
USC00519397 2014-01-09 00:00:00 0.03 65
USC00519397 2014-01-12 00:00:00 0.35 69
USC00519397 2014-01-13 00:00:00 0.0 69
USC00519397 2014-01-14 00:00:00 0.43 70
USC00519397 2014-01-15 00:00:00 0.01 66
USC00519397 2014-01-16 00:00:00 0.25 69
USC00519397 2014-01-17 00:00:00 0.0 67
USC00519397 2014-01-18 00:00:00 0.0 66
USC00519397 2014-01-19 00:00:00 0.0 66
USC00519397 2014-01-20 00:00:00 0.0 64
USC00519397 2014-01-21 00:00:00 0.0 72
USC00519397 2014-01-22 00:00:00 0.35 69
USC00519397 2014-01-23 00:00:00 0.0 58
USC00519397 2014-01-24 00:00:00 0.0 59
USC00519397 2014-01-25 00:00:00 0.0 72
USC00519397 2014-01-26 00:00:00 0.0 74
USC00519397 2014-01-27 00:00:00 0.14 68
USC00519397 2014-01-28 00:00:00 0.02 70
USC00519397 2014-01-29 00:00:00 0.27 70
USC00519397 2014-01-30 00:00:00 0.04 65
USC00519397 2014-01-31 00:00:00 0.0 68
USC00519397 2014-02-01 00:00:00 0.22 74
USC00519397 2014-02-02 00:00:00 0.38 67
USC00519397 2014-02-03 00:00:00 0.0 69
USC00519397 2014-02-04 00:00:00 0.5 68
USC00519397 2014-02-05 00:00:00 0.23 73
USC00519397 2014-02-06 00:00:00 0.08 72
USC00519397 2014-02-07 00:00:00 0.03 77
USC00519397 2014-02-08 00:00:00 0.0 70
USC00519397 2014-02-09 00:00:00 0.0 71
USC00519397 2014-02-10 00:00:00 0.0 71
USC00519397 2014-02-11 00:00:00 0.0 69
USC00519397 2014-02-12 00:00:00 0.0 71
USC00519397 2014-02-13 00:00:00 0.0 67
USC00519397 2014-02-14 00:00:00 0.0 74
USC00519397 2014-02-15 00:00:00 0.01 73
USC00519397 2014-02-16 00:00:00 0.0 72
USC00519397 2014-02-17 00:00:00 0.35 72
USC00519397 2014-02-18 00:00:00 0.03 72
USC00519397 2014-02-19 00:00:00 0.0 71
USC00519397 2014-02-20 00:00:00 0.0 70
USC00519397 2014-02-21 00:00:00 0.0 69
USC00519397 2014-02-22 00:00:00 0.0 69
USC00519397 2014-02-23 00:00:00 0.0 68
USC00519397 2014-02-24 00:00:00 0.0 68
USC00519397 2014-02-25 00:00:00 0.0 67
USC00519397 2014-02-26 00:00:00 0.0 67
USC00519397 2014-02-27 00:00:00 0.0 70
USC00519397 2014-02-28 00:00:00 0.0 74
USC00519397 2014-03-01 00:00:00 0.25 70
USC00519397 2014-03-02 00:00:00 0.48 71
USC00519397 2014-03-03 00:00:00 0.16 65
USC00519397 2014-03-04 00:00:00 0.0 61
USC00519397 2014-03-05 00:00:00 0.0 69
USC00519397 2014-03-06 00:00:00 0.0 66
USC00519397 2014-03-07 00:00:00 0.25 72
USC00519397 2014-03-08 00:00:00 0.64 68
USC00519397 2014-03-09 00:00:00 0.04 72
USC00519397 2014-03-10 00:00:00 0.0 71
USC00519397 2014-03-11 00:00:00 0.16 74
USC00519397 2014-03-12 00:00:00 0.0 72
USC00519397 2014-03-13 00:00:00 0.0 75
USC00519397 2014-03-14 00:00:00 0.0 75
USC00519397 2014-03-15 00:00:00 0.0 71
USC00519397 2014-03-16 00:00:00 0.0 69
USC00519397 2014-03-17 00:00:00 0.0 69
USC00519397 2014-03-18 00:00:00 0.0 69
USC00519397 2014-03-19 00:00:00 0.0 73
USC00519397 2014-03-20 00:00:00 0.0 72
USC00519397 2014-03-21 00:00:00 0.0 73
USC00519397 2014-03-22 00:00:00 0.0 72
USC00519397 2014-03-23 00:00:00 0.0 72
USC00519397 2014-03-24 00:00:00 0.0 76
USC00519397 2014-03-25 00:00:00 0.0 74
USC00519397 2014-03-26 00:00:00 0.05 74
USC00519397 2014-03-27 00:00:00 0.0 75
USC00519397 2014-03-28 00:00:00 0.0 71
USC00519397 2014-03-29 00:00:00 0.0 73
USC00519397 2014-03-30 00:00:00 0.0 73
USC00519397 2014-03-31 00:00:00 0.02 75
USC00519397 2014-04-01 00:00:00 0.16 73
USC00519397 2014-04-02 00:00:00 0.02 76
USC00519397 2014-04-03 00:00:00 0.16 76
USC00519397 2014-04-04 00:00:00 0.0 75
USC00519397 2014-04-05 00:00:00 0.0 71
USC00519397 2014-04-06 00:00:00 0.0 69
USC00519397 2014-04-07 00:00:00 0.01 71
USC00519397 2014-04-08 00:00:00 0.0 71
USC00519397 2014-04-09 00:00:00 0.0 73
USC00519397 2014-04-10 00:00:00 0.0 72
USC00519397 2014-04-11 00:00:00 0.0 75
USC00519397 2014-04-12 00:00:00 0.01 69
USC00519397 2014-04-13 00:00:00 0.04 73
USC00519397 2014-04-14 00:00:00 0.08 74
USC00519397 2014-04-15 00:00:00 0.0 75
USC00519397 2014-04-16 00:00:00 0.05 74
USC00519397 2014-04-17 00:00:00 0.0 76
USC00519397 2014-04-18 00:00:00 0.02 76
USC00519397 2014-04-19 00:00:00 0.01 76
USC00519397 2014-04-20 00:00:00 0.0 74
USC00519397 2014-04-21 00:00:00 0.06 73
USC00519397 2014-04-22 00:00:00 0.05 76
USC00519397 2014-04-23 00:00:00 0.0 76
USC00519397 2014-04-24 00:00:00 0.0 76
USC00519397 2014-04-25 00:00:00 0.01 75
USC00519397 2014-04-26 00:00:00 0.01 72
USC00519397 2014-04-27 00:00:00 0.01 73
USC00519397 2014-04-28 00:00:00 0.07 73
USC00519397 2014-04-29 00:00:00 0.0 75
USC00519397 2014-04-30 00:00:00 0.0 74
USC00519397 2014-05-01 00:00:00 0.0 74
USC00519397 2014-05-02 00:00:00 0.0 76
USC00519397 2014-05-03 00:00:00 0.0 77
USC00519397 2014-05-04 00:00:00 0.0 76
USC00519397 2014-05-05 00:00:00 0.06 75
USC00519397 2014-05-06 00:00:00 0.07 77
USC00519397 2014-05-07 00:00:00 0.03 72
USC00519397 2014-05-10 00:00:00 0.01 76
USC00519397 2014-05-11 00:00:00 0.0 79
USC00519397 2014-05-12 00:00:00 0.45 74
USC00519397 2014-05-13 00:00:00 0.0 75
USC00519397 2014-05-14 00:00:00 0.0 76
USC00519397 2014-05-15 00:00:00 0.0 77
USC00519397 2014-05-16 00:00:00 0.0 78
USC00519397 2014-05-17 00:00:00 0.0 78
USC00519397 2014-05-18 00:00:00 0.0 76
USC00519397 2014-05-19 00:00:00 0.43 75
USC00519397 2014-05-20 00:00:00 0.0 78
USC00519397 2014-05-21 00:00:00 0.15 74
USC00519397 2014-05-23 00:00:00 0.0 79
USC00519397 2014-05-24 00:00:00 0.0 77
USC00519397 2014-05-25 00:00:00 0.76 74
USC00519397 2014-05-26 00:00:00 0.05 73
USC00519397 2014-05-27 00:00:00 0.01 77
USC00519397 2014-05-28 00:00:00 0.03 76
USC00519397 2014-05-29 00:00:00 0.0 78
USC00519397 2014-05-30 00:00:00 0.0 79
USC00519397 2014-05-31 00:00:00 0.0 79
USC00519397 2014-06-01 00:00:00 0.0 79
USC00519397 2014-06-02 00:00:00 0.66 77
USC00519397 2014-06-03 00:00:00 0.01 78
USC00519397 2014-06-04 00:00:00 0.0 79
USC00519397 2014-06-05 00:00:00 0.0 78
USC00519397 2014-06-06 00:00:00 0.0 78
USC00519397 2014-06-07 00:00:00 0.03 78

USC00519397 2014-06-08 00:00:00 0.0 78
USC00519397 2014-06-09 00:00:00 0.0 79
USC00519397 2014-06-10 00:00:00 0.0 79
USC00519397 2014-06-11 00:00:00 0.0 82
USC00519397 2014-06-12 00:00:00 0.0 80
USC00519397 2014-06-13 00:00:00 0.0 79
USC00519397 2014-06-14 00:00:00 0.0 79
USC00519397 2014-06-15 00:00:00 0.01 78
USC00519397 2014-06-16 00:00:00 0.0 78
USC00519397 2014-06-17 00:00:00 0.03 77
USC00519397 2014-06-18 00:00:00 0.15 78
USC00519397 2014-06-19 00:00:00 0.01 78
USC00519397 2014-06-20 00:00:00 0.07 73
USC00519397 2014-06-21 00:00:00 0.01 75
USC00519397 2014-06-22 00:00:00 0.01 75
USC00519397 2014-06-23 00:00:00 0.19 76
USC00519397 2014-06-24 00:00:00 0.0 84
USC00519397 2014-06-25 00:00:00 0.05 79
USC00519397 2014-06-26 00:00:00 0.06 76
USC00519397 2014-06-27 00:00:00 0.04 79
USC00519397 2014-06-28 00:00:00 0.0 79
USC00519397 2014-06-29 00:00:00 0.01 77
USC00519397 2014-06-30 00:00:00 0.02 79
USC00519397 2014-07-01 00:00:00 0.0 79
USC00519397 2014-07-02 00:00:00 0.01 80
USC00519397 2014-07-03 00:00:00 0.06 77
USC00519397 2014-07-04 00:00:00 0.01 80
USC00519397 2014-07-05 00:00:00 0.02 76
USC00519397 2014-07-06 00:00:00 0.05 76
USC00519397 2014-07-07 00:00:00 0.0 78
USC00519397 2014-07-08 00:00:00 0.0 80
USC00519397 2014-07-09 00:00:00 0.01 78
USC00519397 2014-07-10 00:00:00 0.0 79
USC00519397 2014-07-11 00:00:00 0.0 80
USC00519397 2014-07-12 00:00:00 0.0 81
USC00519397 2014-07-13 00:00:00 0.0 80
USC00519397 2014-07-14 00:00:00 0.0 81
USC00519397 2014-07-15 00:00:00 0.0 80
USC00519397 2014-07-16 00:00:00 0.03 77
USC00519397 2014-07-17 00:00:00 0.05 75
USC00519397 2014-07-18 00:00:00 0.05 79
USC00519397 2014-07-19 00:00:00 0.0 79
USC00519397 2014-07-20 00:00:00 1.09 77
USC00519397 2014-07-21 00:00:00 0.0 81
USC00519397 2014-07-22 00:00:00 0.0 78
USC00519397 2014-07-23 00:00:00 0.01 81
USC00519397 2014-07-24 00:00:00 0.0 79
USC00519397 2014-07-25 00:00:00 0.0 80
USC00519397 2014-07-26 00:00:00 0.0 80
USC00519397 2014-07-27 00:00:00 0.79 81
USC00519397 2014-07-28 00:00:00 0.0 79
USC00519397 2014-07-29 00:00:00 0.0 80
USC00519397 2014-07-30 00:00:00 0.0 79
USC00519397 2014-07-31 00:00:00 0.0 80
USC00519397 2014-08-01 00:00:00 0.0 80
USC00519397 2014-08-02 00:00:00 0.0 80
USC00519397 2014-08-03 00:00:00 0.0 81
USC00519397 2014-08-04 00:00:00 0.0 81
USC00519397 2014-08-05 00:00:00 0.0 80
USC00519397 2014-08-06 00:00:00 0.01 78
USC00519397 2014-08-07 00:00:00 0.15 80
USC00519397 2014-08-10 00:00:00 0.0 78
USC00519397 2014-08-11 00:00:00 0.0 74
USC00519397 2014-08-12 00:00:00 0.0 76
USC00519397 2014-08-13 00:00:00 0.0 81
USC00519397 2014-08-14 00:00:00 0.06 80
USC00519397 2014-08-15 00:00:00 0.0 80
USC00519397 2014-08-16 00:00:00 0.0 79
USC00519397 2014-08-17 00:00:00 0.0 79
USC00519397 2014-08-18 00:00:00 0.0 80
USC00519397 2014-08-19 00:00:00 0.0 77
USC00519397 2014-08-20 00:00:00 0.0 79
USC00519397 2014-08-21 00:00:00 0.0 80
USC00519397 2014-08-22 00:00:00 0.0 80
USC00519397 2014-08-23 00:00:00 0.0 79
USC00519397 2014-08-24 00:00:00 0.08 75
USC00519397 2014-08-25 00:00:00 0.01 78
USC00519397 2014-08-26 00:00:00 0.05 77
USC00519397 2014-08-27 00:00:00 0.01 80
USC00519397 2014-08-28 00:00:00 0.01 81
USC00519397 2014-08-29 00:00:00 0.0 81
USC00519397 2014-08-30 00:00:00 0.0 80
USC00519397 2014-08-31 00:00:00 0.0 76
USC00519397 2014-09-01 00:00:00 0.0 77
USC00519397 2014-09-02 00:00:00 0.0 81
USC00519397 2014-09-03 00:00:00 0.0 80
USC00519397 2014-09-04 00:00:00 0.04 74
USC00519397 2014-09-05 00:00:00 0.39 78
USC00519397 2014-09-07 00:00:00 0.0 78
USC00519397 2014-09-08 00:00:00 0.0 83
USC00519397 2014-09-09 00:00:00 0.0 81
USC00519397 2014-09-10 00:00:00 0.0 79
USC00519397 2014-09-11 00:00:00 0.0 79
USC00519397 2014-09-12 00:00:00 0.0 78
USC00519397 2014-09-13 00:00:00 0.0 80
USC00519397 2014-09-14 00:00:00 0.0 73
USC00519397 2014-09-15 00:00:00 0.01 80
USC00519397 2014-09-16 00:00:00 0.0 83
USC00519397 2014-09-17 00:00:00 0.0 76
USC00519397 2014-09-18 00:00:00 0.0 77
USC00519397 2014-09-19 00:00:00 0.04 76
USC00519397 2014-09-20 00:00:00 0.05 77
USC00519397 2014-09-21 00:00:00 0.01 83
USC00519397 2014-09-22 00:00:00 0.0 84
USC00519397 2014-09-23 00:00:00 0.0 83
USC00519397 2014-09-24 00:00:00 0.0 84
USC00519397 2014-09-25 00:00:00 0.1 83
USC00519397 2014-09-26 00:00:00 0.0 85
USC00519397 2014-09-27 00:00:00 0.04 78
USC00519397 2014-09-28 00:00:00 0.01 82
USC00519397 2014-09-29 00:00:00 0.02 83
USC00519397 2014-09-30 00:00:00 0.18 79
USC00519397 2014-10-01 00:00:00 0.37 78
USC00519397 2014-10-02 00:00:00 0.0 83
USC00519397 2014-10-03 00:00:00 0.0 82
USC00519397 2014-10-04 00:00:00 0.0 81
USC00519397 2014-10-05 00:00:00 0.0 82
USC00519397 2014-10-06 00:00:00 0.24 77
USC00519397 2014-10-07 00:00:00 1.22 79
USC00519397 2014-10-08 00:00:00 0.0 82
USC00519397 2014-10-09 00:00:00 0.0 82
USC00519397 2014-10-10 00:00:00 0.0 81
USC00519397 2014-10-11 00:00:00 0.0 81
USC00519397 2014-10-12 00:00:00 0.0 80
USC00519397 2014-10-13 00:00:00 0.06 80
USC00519397 2014-10-14 00:00:00 0.01 80
USC00519397 2014-10-15 00:00:00 0.04 81
USC00519397 2014-10-16 00:00:00 0.0 80
USC00519397 2014-10-17 00:00:00 0.0 82
USC00519397 2014-10-18 00:00:00 0.02 83
USC00519397 2014-10-20 00:00:00 2.1 82
USC00519397 2014-10-21 00:00:00 0.0 80
USC00519397 2014-10-22 00:00:00 0.05 80
USC00519397 2014-10-23 00:00:00 0.23 80
USC00519397 2014-10-24 00:00:00 0.0 79
USC00519397 2014-10-25 00:00:00 0.0 78
USC00519397 2014-10-26 00:00:00 0.0 79
USC00519397 2014-10-27 00:00:00 0.0 78
USC00519397 2014-10-28 00:00:00 0.0 81
USC00519397 2014-10-29 00:00:00 0.01 80
USC00519397 2014-10-30 00:00:00 0.05 79
USC00519397 2014-10-31 00:00:00 0.02 77
USC00519397 2014-11-01 00:00:00 0.04 79
USC00519397 2014-11-02 00:00:00 0.0 77
USC00519397 2014-11-03 00:00:00 0.0 81
USC00519397 2014-11-04 00:00:00 0.0 76
USC00519397 2014-11-05 00:00:00 0.14 75
USC00519397 2014-11-06 00:00:00 0.1 77
USC00519397 2014-11-07 00:00:00 0.0 75
USC00519397 2014-11-08 00:00:00 0.09 71
USC00519397 2014-11-09 00:00:00 0.0 70
USC00519397 2014-11-10 00:00:00 0.0 69
USC00519397 2014-11-11 00:00:00 0.0 70
USC00519397 2014-11-12 00:00:00 0.05 72
USC00519397 2014-11-13 00:00:00 0.0 73
USC00519397 2014-11-14 00:00:00 0.0 76
USC00519397 2014-11-15 00:00:00 0.62 77
USC00519397 2014-11-16 00:00:00 0.01 72
USC00519397 2014-11-17 00:00:00 0.0 76
USC00519397 2014-11-18 00:00:00 0.0 76
USC00519397 2014-11-19 00:00:00 0.0 78
USC00519397 2014-11-20 00:00:00 0.08 76
USC00519397 2014-11-21 00:00:00 0.0 78
USC00519397 2014-11-22 00:00:00 0.0 77
USC00519397 2014-11-23 00:00:00 0.0 70
USC00519397 2014-11-24 00:00:00 0.04 74
USC00519397 2014-11-25 00:00:00 0.0 73
USC00519397 2014-11-26 00:00:00 0.0 75
USC00519397 2014-11-27 00:00:00 0.0 75
USC00519397 2014-11-28 00:00:00 0.0 76
USC00519397 2014-11-29 00:00:00 0.0 74
USC00519397 2014-11-30 00:00:00 0.01 74
USC00519397 2014-12-01 00:00:00 0.0 73
USC00519397 2014-12-02 00:00:00 0.02 73
USC00519397 2014-12-03 00:00:00 0.15 71
USC00519397 2014-12-04 00:00:00 0.09 72
USC00519397 2014-12-05 00:00:00 0.0 71
USC00519397 2014-12-06 00:00:00 0.0 68
USC00519397 2014-12-07 00:00:00 0.0 65
USC00519397 2014-12-08 00:00:00 0.0 69
USC00519397 2014-12-09 00:00:00 0.0 70
USC00519397 2014-12-10 00:00:00 0.0 70
USC00519397 2014-12-11 00:00:00 0.05 74
USC00519397 2014-12-12 00:00:00 0.01 71
USC00519397 2014-12-13 00:00:00 0.0 74
USC00519397 2014-12-14 00:00:00 0.03 73
USC00519397 2014-12-15 00:00:00 0.02 72
USC00519397 2014-12-16 00:00:00 0.01 74
USC00519397 2014-12-17 00:00:00 0.01 72
USC00519397 2014-12-18 00:00:00 0.0 74
USC00519397 2014-12-19 00:00:00 0.0 75
USC00519397 2014-12-20 00:00:00 0.0 74
USC00519397 2014-12-21 00:00:00 0.0 70
USC00519397 2014-12-22 00:00:00 0.0 74
USC00519397 2014-12-23 00:00:00 0.93 70
USC00519397 2014-12-24 00:00:00 0.04 66
USC00519397 2014-12-25 00:00:00 0.02 61
USC00519397 2014-12-26 00:00:00 0.0 63
USC00519397 2014-12-27 00:00:00 0.0 63
USC00519397 2014-12-28 00:00:00 0.0 63
USC00519397 2014-12-29 00:00:00 0.0 63
USC00519397 2014-12-30 00:00:00 0.0 67
USC00519397 2014-12-31 00:00:00 0.05 56
USC00519397 2015-01-01 00:00:00 0.0 63
USC00519397 2015-01-02 00:00:00 0.04 65
USC00519397 2015-01-03 00:00:00 0.86 62
USC00519397 2015-01-04 00:00:00 0.02 58
USC00519397 2015-01-05 00:00:00 0.0 58
USC00519397 2015-01-06 00:00:00 0.02 64
USC00519397 2015-01-07 00:00:00 0.0 63
USC00519397 2015-01-08 00:00:00 0.0 64
USC00519397 2015-01-09 00:00:00 0.0 64
USC00519397 2015-01-10 00:00:00 0.0 65
USC00519397 2015-01-11 00:00:00 0.0 64
USC00519397 2015-01-12 00:00:00 0.0 64
USC00519397 2015-01-13 00:00:00 0.0 62
USC00519397 2015-01-14 00:00:00 0.0 68
USC00519397 2015-01-15 00:00:00 0.0 74
USC00519397 2015-01-16 00:00:00 0.0 71
USC00519397 2015-01-17 00:00:00 0.0 69
USC00519397 2015-01-18 00:00:00 0.0 63
USC00519397 2015-01-19 00:00:00 0.0 66
USC00519397 2015-01-20 00:00:00 0.0 65
USC00519397 2015-01-21 00:00:00 0.0 64
USC00519397 2015-01-22 00:00:00 0.0 64
USC00519397 2015-01-23 00:00:00 0.0 69
USC00519397 2015-01-24 00:00:00 0.2 68
USC00519397 2015-01-25 00:00:00 0.03 68
USC00519397 2015-01-26 00:00:00 0.0 70
USC00519397 2015-01-27 00:00:00 0.0 72
USC00519397 2015-01-28 00:00:00 0.0 70
USC00519397 2015-01-29 00:00:00 0.0 74
USC00519397 2015-01-30 00:00:00 0.0 63
USC00519397 2015-01-31 00:00:00 0.0 64
USC00519397 2015-02-01 00:00:00 0.0 68
USC00519397 2015-02-02 00:00:00 0.0 74
USC00519397 2015-02-03 00:00:00 0.0 76
USC00519397 2015-02-04 00:00:00 0.01 72
USC00519397 2015-02-05 00:00:00 0.19 67
USC00519397 2015-02-06 00:00:00 0.0 62
USC00519397 2015-02-07 00:00:00 0.0 64
USC00519397 2015-02-08 00:00:00 0.0 61
USC00519397 2015-02-09 00:00:00 0.0 73
USC00519397 2015-02-10 00:00:00 0.1 71
USC00519397 2015-02-11 00:00:00 0.0 72
USC00519397 2015-02-12 00:00:00 0.0 64
USC00519397 2015-02-13 00:00:00 0.0 74
USC00519397 2015-02-14 00:00:00 0.08 76
USC00519397 2015-02-15 00:00:00 0.46 58
USC00519397 2015-02-16 00:00:00 0.0 64
USC00519397 2015-02-17 00:00:00 0.0 69
USC00519397 2015-02-18 00:00:00 0.0 67
USC00519397 2015-02-19 00:00:00 0.01 71
USC00519397 2015-02-20 00:00:00 0.01 73
USC00519397 2015-02-21 00:00:00 0.24 63
USC00519397 2015-02-22 00:00:00 0.0 70
USC00519397 2015-02-23 00:00:00 0.0 73
USC00519397 2015-02-24 00:00:00 0.0 69
USC00519397 2015-02-25 00:00:00 0.0 73
USC00519397 2015-02-26 00:00:00 0.0 70
USC00519397 2015-02-27 00:00:00 0.0 71
USC00519397 2015-02-28 00:00:00 0.0 72
USC00519397 2015-03-01 00:00:00 0.0 73
USC00519397 2015-03-02 00:00:00 0.0 74
USC00519397 2015-03-03 00:00:00 0.0 74
USC00519397 2015-03-04 00:00:00 0.0 73
USC00519397 2015-03-05 00:00:00 0.65 67
USC00519397 2015-03-08 00:00:00 0.0 68
USC00519397 2015-03-09 00:00:00 0.0 64
USC00519397 2015-03-10 00:00:00 0.0 63
USC00519397 2015-03-11 00:00:00 0.0 65
USC00519397 2015-03-13 00:00:00 0.0 67
USC00519397 2015-03-14 00:00:00 0.0 68
USC00519397 2015-03-15 00:00:00 0.0 68
USC00519397 2015-03-16 00:00:00 0.0 67
USC00519397 2015-03-17 00:00:00 0.0 68
USC00519397 2015-03-18 00:00:00 0.0 69
USC00519397 2015-03-19 00:00:00 0.0 71
USC00519397 2015-03-20 00:00:00 0.05 74
USC00519397 2015-03-21 00:00:00 0.0 72
USC00519397 2015-03-22 00:00:00 0.0 75
USC00519397 2015-03-23 00:00:00 0.0 75

USC00519397 2015-03-24 00:00:00 0.0 71
USC00519397 2015-03-25 00:00:00 0.0 71
USC00519397 2015-03-26 00:00:00 0.26 65
USC00519397 2015-03-27 00:00:00 0.0 76
USC00519397 2015-03-28 00:00:00 0.0 75
USC00519397 2015-03-29 00:00:00 0.41 70
USC00519397 2015-03-30 00:00:00 0.04 73
USC00519397 2015-03-31 00:00:00 0.0 75
USC00519397 2015-04-01 00:00:00 0.0 76
USC00519397 2015-04-02 00:00:00 0.0 76
USC00519397 2015-04-03 00:00:00 0.0 72
USC00519397 2015-04-04 00:00:00 0.0 76
USC00519397 2015-04-05 00:00:00 0.0 76
USC00519397 2015-04-06 00:00:00 0.0 74
USC00519397 2015-04-07 00:00:00 0.0 76
USC00519397 2015-04-08 00:00:00 0.01 75
USC00519397 2015-04-09 00:00:00 0.0 75
USC00519397 2015-04-10 00:00:00 0.0 74
USC00519397 2015-04-11 00:00:00 0.0 75
USC00519397 2015-04-12 00:00:00 0.0 74
USC00519397 2015-04-13 00:00:00 0.0 76
USC00519397 2015-04-14 00:00:00 0.03 75
USC00519397 2015-04-15 00:00:00 0.01 75
USC00519397 2015-04-16 00:00:00 0.0 76
USC00519397 2015-04-17 00:00:00 0.06 77
USC00519397 2015-04-18 00:00:00 0.0 77
USC00519397 2015-04-19 00:00:00 0.0 75
USC00519397 2015-04-20 00:00:00 0.0 76
USC00519397 2015-04-21 00:00:00 0.0 76
USC00519397 2015-04-22 00:00:00 0.03 76
USC00519397 2015-04-23 00:00:00 0.0 78
USC00519397 2015-04-24 00:00:00 0.07 77
USC00519397 2015-04-25 00:00:00 0.0 74
USC00519397 2015-04-26 00:00:00 0.01 78
USC00519397 2015-04-27 00:00:00 0.06 81
USC00519397 2015-04-28 00:00:00 0.04 74
USC00519397 2015-04-29 00:00:00 0.02 77
USC00519397 2015-04-30 00:00:00 0.0 77
USC00519397 2015-05-01 00:00:00 0.06 75
USC00519397 2015-05-02 00:00:00 0.0 76
USC00519397 2015-05-03 00:00:00 0.0 76
USC00519397 2015-05-04 00:00:00 0.0 76
USC00519397 2015-05-05 00:00:00 0.05 77
USC00519397 2015-05-06 00:00:00 0.03 75
USC00519397 2015-05-07 00:00:00 0.01 77
USC00519397 2015-05-08 00:00:00 0.18 73
USC00519397 2015-05-09 00:00:00 0.05 76
USC00519397 2015-05-10 00:00:00 0.0 76
USC00519397 2015-05-11 00:00:00 0.0 76
USC00519397 2015-05-12 00:00:00 0.01 74
USC00519397 2015-05-13 00:00:00 0.0 76
USC00519397 2015-05-14 00:00:00 0.0 76
USC00519397 2015-05-15 00:00:00 0.13 74
USC00519397 2015-05-16 00:00:00 0.0 76
USC00519397 2015-05-17 00:00:00 0.0 77
USC00519397 2015-05-18 00:00:00 0.0 77
USC00519397 2015-05-19 00:00:00 0.0 76
USC00519397 2015-05-20 00:00:00 0.0 76
USC00519397 2015-05-21 00:00:00 0.0 77
USC00519397 2015-05-22 00:00:00 0.0 75
USC00519397 2015-05-23 00:00:00 0.07 75
USC00519397 2015-05-24 00:00:00 0.0 73
USC00519397 2015-05-25 00:00:00 0.0 74
USC00519397 2015-05-26 00:00:00 0.0 75
USC00519397 2015-05-27 00:00:00 0.0 76
USC00519397 2015-05-28 00:00:00 0.0 77
USC00519397 2015-05-29 00:00:00 0.0 78
USC00519397 2015-05-30 00:00:00 0.0 78
USC00519397 2015-05-31 00:00:00 0.0 77
USC00519397 2015-06-01 00:00:00 0.0 78
USC00519397 2015-06-02 00:00:00 0.0 78
USC00519397 2015-06-03 00:00:00 0.0 79
USC00519397 2015-06-04 00:00:00 0.0 77
USC00519397 2015-06-05 00:00:00 0.0 79
USC00519397 2015-06-06 00:00:00 0.0 78
USC00519397 2015-06-07 00:00:00 0.0 78
USC00519397 2015-06-08 00:00:00 0.0 78
USC00519397 2015-06-09 00:00:00 0.0 79
USC00519397 2015-06-10 00:00:00 0.0 77
USC00519397 2015-06-11 00:00:00 0.0 78
USC00519397 2015-06-12 00:00:00 0.0 78
USC00519397 2015-06-13 00:00:00 0.0 78
USC00519397 2015-06-14 00:00:00 0.0 78
USC00519397 2015-06-15 00:00:00 0.0 79
USC00519397 2015-06-16 00:00:00 0.0 79
USC00519397 2015-06-17 00:00:00 0.03 77
USC00519397 2015-06-18 00:00:00 0.0 78
USC00519397 2015-06-19 00:00:00 0.01 78
USC00519397 2015-06-20 00:00:00 0.04 78
USC00519397 2015-06-21 00:00:00 0.0 79
USC00519397 2015-06-22 00:00:00 0.0 79
USC00519397 2015-06-23 00:00:00 0.03 77
USC00519397 2015-06-24 00:00:00 0.03 79
USC00519397 2015-06-25 00:00:00 0.03 79
USC00519397 2015-06-26 00:00:00 0.0 79
USC00519397 2015-06-27 00:00:00 0.0 81
USC00519397 2015-06-28 00:00:00 0.0 76
USC00519397 2015-06-29 00:00:00 0.0 80
USC00519397 2015-06-30 00:00:00 0.0 78
USC00519397 2015-07-01 00:00:00 0.0 79
USC00519397 2015-07-02 00:00:00 0.0 80
USC00519397 2015-07-03 00:00:00 0.0 82
USC00519397 2015-07-04 00:00:00 0.0 81
USC00519397 2015-07-05 00:00:00 0.0 81
USC00519397 2015-07-06 00:00:00 0.0 81
USC00519397 2015-07-07 00:00:00 0.0 81
USC00519397 2015-07-08 00:00:00 0.03 80
USC00519397 2015-07-09 00:00:00 0.0 81
USC00519397 2015-07-10 00:00:00 0.01 81
USC00519397 2015-07-11 00:00:00 0.02 79
USC00519397 2015-07-12 00:00:00 0.02 79
USC00519397 2015-07-13 00:00:00 0.0 80
USC00519397 2015-07-14 00:00:00 0.01 81
USC00519397 2015-07-15 00:00:00 0.0 81
USC00519397 2015-07-16 00:00:00 0.0 83
USC00519397 2015-07-17 00:00:00 0.0 83
USC00519397 2015-07-18 00:00:00 0.0 82
USC00519397 2015-07-19 00:00:00 0.05 78
USC00519397 2015-07-20 00:00:00 0.0 79
USC00519397 2015-07-21 00:00:00 0.0 81
USC00519397 2015-07-22 00:00:00 0.01 79
USC00519397 2015-07-23 00:00:00 0.0 81
USC00519397 2015-07-24 00:00:00 0.0 81
USC00519397 2015-07-25 00:00:00 0.0 81
USC00519397 2015-07-26 00:00:00 0.0 80
USC00519397 2015-07-27 00:00:00 0.0 81
USC00519397 2015-07-28 00:00:00 0.0 81
USC00519397 2015-07-29 00:00:00 0.0 82
USC00519397 2015-07-30 00:00:00 0.0 82
USC00519397 2015-07-31 00:00:00 0.0 80
USC00519397 2015-08-01 00:00:00 0.02 78
USC00519397 2015-08-02 00:00:00 0.0 81
USC00519397 2015-08-03 00:00:00 0.0 81
USC00519397 2015-08-04 00:00:00 0.0 77
USC00519397 2015-08-05 00:00:00 0.0 82
USC00519397 2015-08-06 00:00:00 0.1 81
USC00519397 2015-08-07 00:00:00 0.14 80
USC00519397 2015-08-08 00:00:00 0.0 82
USC00519397 2015-08-09 00:00:00 0.0 79
USC00519397 2015-08-10 00:00:00 0.01 81
USC00519397 2015-08-11 00:00:00 0.0 82
USC00519397 2015-08-12 00:00:00 0.0 83
USC00519397 2015-08-13 00:00:00 0.0 83
USC00519397 2015-08-14 00:00:00 0.0 82
USC00519397 2015-08-15 00:00:00 0.01 80
USC00519397 2015-08-16 00:00:00 0.0 81
USC00519397 2015-08-17 00:00:00 0.01 79
USC00519397 2015-08-18 00:00:00 0.06 78
USC00519397 2015-08-21 00:00:00 0.0 82
USC00519397 2015-08-22 00:00:00 0.0 84
USC00519397 2015-08-23 00:00:00 0.02 81
USC00519397 2015-08-24 00:00:00 0.42 74
USC00519397 2015-08-25 00:00:00 0.2 79
USC00519397 2015-08-26 00:00:00 0.62 77
USC00519397 2015-08-27 00:00:00 0.62 77
USC00519397 2015-08-28 00:00:00 0.06 81
USC00519397 2015-08-29 00:00:00 0.0 82
USC00519397 2015-08-30 00:00:00 0.0 81
USC00519397 2015-08-31 00:00:00 0.0 81
USC00519397 2015-09-01 00:00:00 0.0 80
USC00519397 2015-09-02 00:00:00 0.0 80
USC00519397 2015-09-03 00:00:00 0.23 77
USC00519397 2015-09-04 00:00:00 0.52 77
USC00519397 2015-09-05 00:00:00 0.08 80
USC00519397 2015-09-06 00:00:00 0.0 78
USC00519397 2015-09-07 00:00:00 0.06 79
USC00519397 2015-09-08 00:00:00 0.01 81
USC00519397 2015-09-09 00:00:00 0.0 80
USC00519397 2015-09-10 00:00:00 0.0 79
USC00519397 2015-09-11 00:00:00 0.77 79
USC00519397 2015-09-12 00:00:00 0.5 76
USC00519397 2015-09-13 00:00:00 0.11 79
USC00519397 2015-09-14 00:00:00 0.77 78
USC00519397 2015-09-15 00:00:00 0.26 78
USC00519397 2015-09-16 00:00:00 0.01 81
USC00519397 2015-09-17 00:00:00 0.0 81
USC00519397 2015-09-18 00:00:00 0.02 81
USC00519397 2015-09-19 00:00:00 0.02 83
USC00519397 2015-09-20 00:00:00 0.0 82
USC00519397 2015-09-21 00:00:00 0.07 79
USC00519397 2015-09-22 00:00:00 0.09 81
USC00519397 2015-09-23 00:00:00 0.01 80
USC00519397 2015-09-24 00:00:00 0.0 81
USC00519397 2015-09-25 00:00:00 0.08 81
USC00519397 2015-09-26 00:00:00 0.03 80
USC00519397 2015-09-27 00:00:00 0.15 79
USC00519397 2015-09-28 00:00:00 0.04 79
USC00519397 2015-09-29 00:00:00 0.11 78
USC00519397 2015-09-30 00:00:00 0.04 80
USC00519397 2015-10-01 00:00:00 0.05 76
USC00519397 2015-10-02 00:00:00 0.03 79
USC00519397 2015-10-03 00:00:00 0.0 79
USC00519397 2015-10-04 00:00:00 0.0 79
USC00519397 2015-10-05 00:00:00 0.0 78
USC00519397 2015-10-06 00:00:00 0.0 76
USC00519397 2015-10-07 00:00:00 0.04 79
USC00519397 2015-10-08 00:00:00 0.0 76
USC00519397 2015-10-09 00:00:00 0.0 79
USC00519397 2015-10-10 00:00:00 0.0 81
USC00519397 2015-10-11 00:00:00 0.0 78
USC00519397 2015-10-12 00:00:00 0.03 77
USC00519397 2015-10-13 00:00:00 0.04 79
USC00519397 2015-10-14 00:00:00 0.01 82
USC00519397 2015-10-15 00:00:00 0.01 78
USC00519397 2015-10-16 00:00:00 0.0 80
USC00519397 2015-10-17 00:00:00 0.0 83
USC00519397 2015-10-18 00:00:00 0.04 82
USC00519397 2015-10-19 00:00:00 0.0 80
USC00519397 2015-10-20 00:00:00 0.01 76
USC00519397 2015-10-21 00:00:00 0.06 72
USC00519397 2015-10-22 00:00:00 0.01 73
USC00519397 2015-10-23 00:00:00 0.0 78
USC00519397 2015-10-24 00:00:00 0.0 79
USC00519397 2015-10-25 00:00:00 0.0 74
USC00519397 2015-10-26 00:00:00 0.0 77
USC00519397 2015-10-27 00:00:00 0.11 75
USC00519397 2015-10-28 00:00:00 0.01 79
USC00519397 2015-10-29 00:00:00 0.0 76
USC00519397 2015-10-30 00:00:00 0.0 77
USC00519397 2015-10-31 00:00:00 0.0 80
USC00519397 2015-11-01 00:00:00 0.19 75
USC00519397 2015-11-02 00:00:00 0.01 79
USC00519397 2015-11-03 00:00:00 0.0 80
USC00519397 2015-11-04 00:00:00 0.02 79
USC00519397 2015-11-05 00:00:00 0.03 78
USC00519397 2015-11-06 00:00:00 0.01 79
USC00519397 2015-11-07 00:00:00 0.1 76
USC00519397 2015-11-08 00:00:00 0.02 78
USC00519397 2015-11-09 00:00:00 0.11 76
USC00519397 2015-11-10 00:00:00 0.0 78
USC00519397 2015-11-11 00:00:00 0.0 78
USC00519397 2015-11-12 00:00:00 0.01 77
USC00519397 2015-11-13 00:00:00 0.0 76
USC00519397 2015-11-14 00:00:00 0.17 78
USC00519397 2015-11-15 00:00:00 0.02 77
USC00519397 2015-11-16 00:00:00 0.0 77
USC00519397 2015-11-17 00:00:00 0.0 70
USC00519397 2015-11-18 00:00:00 0.02 77
USC00519397 2015-11-19 00:00:00 0.0 79
USC00519397 2015-11-20 00:00:00 1.57 73
USC00519397 2015-11-21 00:00:00 0.85 75
USC00519397 2015-11-22 00:00:00 0.33 75
USC00519397 2015-11-23 00:00:00 0.62 76
USC00519397 2015-11-24 00:00:00 0.75 71
USC00519397 2015-11-25 00:00:00 0.01 76
USC00519397 2015-11-26 00:00:00 0.36 76
USC00519397 2015-11-27 00:00:00 0.11 77
USC00519397 2015-11-28 00:00:00 0.02 77
USC00519397 2015-11-29 00:00:00 0.03 76
USC00519397 2015-11-30 00:00:00 0.01 77
USC00519397 2015-12-01 00:00:00 0.0 75
USC00519397 2015-12-02 00:00:00 0.0 77
USC00519397 2015-12-03 00:00:00 0.06 75
USC00519397 2015-12-04 00:00:00 0.02 75
USC00519397 2015-12-05 00:00:00 0.0 75
USC00519397 2015-12-06 00:00:00 0.0 75
USC00519397 2015-12-07 00:00:00 0.0 71
USC00519397 2015-12-08 00:00:00 0.0 70
USC00519397 2015-12-09 00:00:00 0.0 74
USC00519397 2015-12-10 00:00:00 0.06 74
USC00519397 2015-12-11 00:00:00 0.0 75
USC00519397 2015-12-12 00:00:00 0.39 72
USC00519397 2015-12-13 00:00:00 0.0 70
USC00519397 2015-12-14 00:00:00 0.0 66
USC00519397 2015-12-15 00:00:00 0.08 74
USC00519397 2015-12-16 00:00:00 0.0 75
USC00519397 2015-12-17 00:00:00 0.02 74
USC00519397 2015-12-18 00:00:00 0.08 75
USC00519397 2015-12-19 00:00:00 0.13 76
USC00519397 2015-12-20 00:00:00 0.03 74
USC00519397 2015-12-21 00:00:00 0.01 75
USC00519397 2015-12-22 00:00:00 0.0 74
USC00519397 2015-12-23 00:00:00 0.0 73
USC00519397 2015-12-24 00:00:00 0.0 68
USC00519397 2015-12-25 00:00:00 0.0 73
USC00519397 2015-12-26 00:00:00 0.02 74
USC00519397 2015-12-27 00:00:00 0.43 74
USC00519397 2015-12-28 00:00:00 0.01 77
USC00519397 2015-12-29 00:00:00 0.0 70
USC00519397 2015-12-30 00:00:00 0.0 70
USC00519397 2015-12-31 00:00:00 0.0 69
USC00519397 2016-01-01 00:00:00 0.0 62
USC00519397 2016-01-02 00:00:00 0.0 71
USC00519397 2016-01-03 00:00:00 0.0 63
USC00519397 2016-01-04 00:00:00 0.0 62
USC00519397 2016-01-05 00:00:00 0.0 68
USC00519397 2016-01-06 00:00:00 0.0 73
USC00519397 2016-01-07 00:00:00 0.18 65
USC00519397 2016-01-08 00:00:00 0.01 67
USC00519397 2016-01-09 00:00:00 0.03 75
USC00519397 2016-01-10 00:00:00 0.01 66
USC00519397 2016-01-11 00:00:00 0.0 68
USC00519397 2016-01-12 00:00:00 0.0 64
USC00519397 2016-01-13 00:00:00 0.0 64
USC00519397 2016-01-14 00:00:00 0.0 64
USC00519397 2016-01-15 00:00:00 0.0 69
USC00519397 2016-01-16 00:00:00 0.01 65
USC00519397 2016-01-17 00:00:00 0.0 64
USC00519397 2016-01-18 00:00:00 0.0 64
USC00519397 2016-01-19 00:00:00 0.0 63
USC00519397 2016-01-20 00:00:00 0.0 68
USC00519397 2016-01-21 00:00:00 0.0 71
USC00519397 2016-01-22 00:00:00 0.0 70
USC00519397 2016-01-23 00:00:00 0.0 70
USC00519397 2016-01-24 00:00:00 0.0 70
USC00519397 2016-01-25 00:00:00 0.04 71
USC00519397 2016-01-26 00:00:00 0.16 68
USC00519397 2016-01-27 00:00:00 0.01 68
USC00519397 2016-01-28 00:00:00 0.0 65
USC00519397 2016-01-29 00:00:00 0.0 67
USC00519397 2016-01-30 00:00:00 0.0 65
USC00519397 2016-01-31 00:00:00 0.0 69
USC00519397 2016-02-01 00:00:00 0.0 69
USC00519397 2016-02-02 00:00:00 0.06 68
USC00519397 2016-02-03 00:00:00 0.0 70
USC00519397 2016-02-04 00:00:00 0.0 66
USC00519397 2016-02-05 00:00:00 0.0 69
USC00519397 2016-02-06 00:00:00 0.0 72
USC00519397 2016-02-07 00:00:00 0.02 68
USC00519397 2016-02-08 00:00:00 0.01 65
USC00519397 2016-02-09 00:00:00 0.0 69
USC00519397 2016-02-10 00:00:00 0.0 61
USC00519397 2016-02-11 00:00:00 0.0 62
USC00519397 2016-02-12 00:00:00 0.02 75
USC00519397 2016-02-13 00:00:00 0.0 74
USC00519397 2016-02-14 00:00:00 0.0 69
USC00519397 2016-02-15 00:00:00 0.0 73
USC00519397 2016-02-16 00:00:00 0.02 74
USC00519397 2016-02-17 00:00:00 0.21 71
USC00519397 2016-02-18 00:00:00 0.02 73
USC00519397 2016-02-19 00:00:00 0.03 66
USC00519397 2016-02-20 00:00:00 0.01 66
USC00519397 2016-02-21 00:00:00 0.0 73
USC00519397 2016-02-22 00:00:00 0.0 63
USC00519397 2016-02-23 00:00:00 0.0 64
USC00519397 2016-02-24 00:00:00 0.0 67
USC00519397 2016-02-25 00:00:00 0.0 66
USC00519397 2016-02-26 00:00:00 0.0 68
USC00519397 2016-02-27 00:00:00 0.0 69
USC00519397 2016-02-28 00:00:00 0.0 68
USC00519397 2016-02-29 00:00:00 0.0 71
USC00519397 2016-03-01 00:00:00 0.0 73
USC00519397 2016-03-02 00:00:00 0.0 68
USC00519397 2016-03-03 00:00:00 0.0 66
USC00519397 2016-03-04 00:00:00 0.0 65
USC00519397 2016-03-05 00:00:00 0.0 66
USC00519397 2016-03-06 00:00:00 0.0 68
USC00519397 2016-03-07 00:00:00 0.0 69
USC00519397 2016-03-08 00:00:00 0.0 76
USC00519397 2016-03-09 00:00:00 0.19 68
USC00519397 2016-03-10 00:00:00 0.0 70
USC00519397 2016-03-11 00:00:00 0.0 71
USC00519397 2016-03-12 00:00:00 0.0 73
USC00519397 2016-03-13 00:00:00 0.0 74
USC00519397 2016-03-14 00:00:00 0.0 72
USC00519397 2016-03-15 00:00:00 0.08 66
USC00519397 2016-03-16 00:00:00 0.05 72
USC00519397 2016-03-17 00:00:00 0.0 70
USC00519397 2016-03-18 00:00:00 0.0 69
USC00519397 2016-03-19 00:00:00 0.0 71
USC00519397 2016-03-20 00:00:00 0.0 73
USC00519397 2016-03-21 00:00:00 0.0 74
USC00519397 2016-03-22 00:00:00 0.0 70
USC00519397 2016-03-23 00:00:00 0.0 70
USC00519397 2016-03-24 00:00:00 0.0 72
USC00519397 2016-03-25 00:00:00 0.01 73
USC00519397 2016-03-26 00:00:00 0.09 68
USC00519397 2016-03-27 00:00:00 0.01 68
USC00519397 2016-03-28 00:00:00 0.0 70
USC00519397 2016-03-29 00:00:00 0.09 73
USC00519397 2016-03-30 00:00:00 0.01 70
USC00519397 2016-03-31 00:00:00 0.0 71
USC00519397 2016-04-01 00:00:00 0.0 77
USC00519397 2016-04-02 00:00:00 0.0 72
USC00519397 2016-04-03 00:00:00 0.0 75

USC00519397 2016-04-04 00:00:00 0.0 72
USC00519397 2016-04-05 00:00:00 0.0 74
USC00519397 2016-04-06 00:00:00 0.01 72
USC00519397 2016-04-07 00:00:00 0.0 73
USC00519397 2016-04-08 00:00:00 0.0 76
USC00519397 2016-04-09 00:00:00 0.0 76
USC00519397 2016-04-10 00:00:00 0.0 78
USC00519397 2016-04-11 00:00:00 0.01 75
USC00519397 2016-04-12 00:00:00 0.0 76
USC00519397 2016-04-13 00:00:00 0.01 77
USC00519397 2016-04-14 00:00:00 0.0 77
USC00519397 2016-04-15 00:00:00 0.0 78
USC00519397 2016-04-16 00:00:00 0.0 80
USC00519397 2016-04-17 00:00:00 0.17 70
USC00519397 2016-04-18 00:00:00 0.15 72
USC00519397 2016-04-19 00:00:00 0.0 73
USC00519397 2016-04-20 00:00:00 0.0 75
USC00519397 2016-04-21 00:00:00 0.0 76
USC00519397 2016-04-22 00:00:00 0.0 77
USC00519397 2016-04-23 00:00:00 0.05 75
USC00519397 2016-04-24 00:00:00 0.05 77
USC00519397 2016-04-25 00:00:00 0.0 77
USC00519397 2016-04-26 00:00:00 0.0 77
USC00519397 2016-04-27 00:00:00 0.0 76
USC00519397 2016-04-28 00:00:00 0.0 78
USC00519397 2016-04-29 00:00:00 0.0 78
USC00519397 2016-04-30 00:00:00 0.0 76
USC00519397 2016-05-01 00:00:00 0.0 77
USC00519397 2016-05-02 00:00:00 0.0 76
USC00519397 2016-05-03 00:00:00 0.01 78
USC00519397 2016-05-04 00:00:00 0.0 77
USC00519397 2016-05-05 00:00:00 0.13 76
USC00519397 2016-05-06 00:00:00 0.0 76
USC00519397 2016-05-07 00:00:00 0.03 73
USC00519397 2016-05-08 00:00:00 0.0 73
USC00519397 2016-05-09 00:00:00 0.0 74
USC00519397 2016-05-10 00:00:00 0.0 75
USC00519397 2016-05-11 00:00:00 0.0 75
USC00519397 2016-05-12 00:00:00 0.0 74
USC00519397 2016-05-13 00:00:00 0.0 75
USC00519397 2016-05-14 00:00:00 0.0 77
USC00519397 2016-05-15 00:00:00 0.02 78
USC00519397 2016-05-16 00:00:00 0.0 77
USC00519397 2016-05-17 00:00:00 0.0 78
USC00519397 2016-05-18 00:00:00 0.0 79
USC00519397 2016-05-19 00:00:00 0.0 78
USC00519397 2016-05-20 00:00:00 0.01 77
USC00519397 2016-05-21 00:00:00 0.03 76
USC00519397 2016-05-22 00:00:00 0.0 78
USC00519397 2016-05-23 00:00:00 0.0 79
USC00519397 2016-05-24 00:00:00 0.0 77
USC00519397 2016-05-25 00:00:00 0.0 77
USC00519397 2016-05-26 00:00:00 0.06 76
USC00519397 2016-05-27 00:00:00 0.0 79
USC00519397 2016-05-28 00:00:00 0.1 75
USC00519397 2016-05-29 00:00:00 0.54 73
USC00519397 2016-05-30 00:00:00 0.16 71
USC00519397 2016-05-31 00:00:00 0.05 74
USC00519397 2016-06-01 00:00:00 0.06 76
USC00519397 2016-06-02 00:00:00 0.0 71
USC00519397 2016-06-03 00:00:00 0.0 71
USC00519397 2016-06-04 00:00:00 0.0 74
USC00519397 2016-06-05 00:00:00 0.0 76
USC00519397 2016-06-06 00:00:00 0.0 78
USC00519397 2016-06-07 00:00:00 0.01 77
USC00519397 2016-06-08 00:00:00 0.0 77
USC00519397 2016-06-09 00:00:00 0.01 73
USC00519397 2016-06-10 00:00:00 0.05 77
USC00519397 2016-06-11 00:00:00 0.0 78
USC00519397 2016-06-12 00:00:00 0.01 78
USC00519397 2016-06-13 00:00:00 0.0 80
USC00519397 2016-06-14 00:00:00 0.0 79
USC00519397 2016-06-15 00:00:00 0.01 78
USC00519397 2016-06-16 00:00:00 0.02 77
USC00519397 2016-06-17 00:00:00 0.02 76
USC00519397 2016-06-18 00:00:00 0.0 77
USC00519397 2016-06-19 00:00:00 0.01 77
USC00519397 2016-06-20 00:00:00 0.01 78
USC00519397 2016-06-21 00:00:00 0.0 80
USC00519397 2016-06-22 00:00:00 0.0 79
USC00519397 2016-06-23 00:00:00 0.0 79
USC00519397 2016-06-24 00:00:00 0.01 77
USC00519397 2016-06-25 00:00:00 0.03 78
USC00519397 2016-06-26 00:00:00 0.01 79
USC00519397 2016-06-27 00:00:00 0.01 80
USC00519397 2016-06-28 00:00:00 0.0 76
USC00519397 2016-06-29 00:00:00 0.0 79
USC00519397 2016-06-30 00:00:00 0.0 80
USC00519397 2016-07-01 00:00:00 0.0 79
USC00519397 2016-07-02 00:00:00 0.0 79
USC00519397 2016-07-03 00:00:00 0.0 77
USC00519397 2016-07-04 00:00:00 0.04 79
USC00519397 2016-07-05 00:00:00 0.02 78
USC00519397 2016-07-06 00:00:00 0.02 78
USC00519397 2016-07-07 00:00:00 0.01 80
USC00519397 2016-07-08 00:00:00 0.0 80
USC00519397 2016-07-09 00:00:00 0.0 80
USC00519397 2016-07-10 00:00:00 0.02 78
USC00519397 2016-07-11 00:00:00 0.0 72
USC00519397 2016-07-12 00:00:00 0.0 80
USC00519397 2016-07-13 00:00:00 0.0 79
USC00519397 2016-07-14 00:00:00 0.0 79
USC00519397 2016-07-15 00:00:00 0.46 78
USC00519397 2016-07-16 00:00:00 0.03 78
USC00519397 2016-07-17 00:00:00 0.0 78
USC00519397 2016-07-18 00:00:00 1.25 76
USC00519397 2016-07-19 00:00:00 0.03 78
USC00519397 2016-07-20 00:00:00 0.0 78
USC00519397 2016-07-21 00:00:00 0.04 78
USC00519397 2016-07-22 00:00:00 0.02 76
USC00519397 2016-07-23 00:00:00 0.0 78
USC00519397 2016-07-24 00:00:00 0.13 79
USC00519397 2016-07-25 00:00:00 4.2 78
USC00519397 2016-07-26 00:00:00 0.0 80
USC00519397 2016-07-27 00:00:00 0.0 80
USC00519397 2016-07-28 00:00:00 0.0 80
USC00519397 2016-07-29 00:00:00 0.0 79
USC00519397 2016-07-30 00:00:00 0.0 78
USC00519397 2016-07-31 00:00:00 0.06 76
USC00519397 2016-08-01 00:00:00 0.08 77
USC00519397 2016-08-02 00:00:00 0.05 78
USC00519397 2016-08-03 00:00:00 0.0 80
USC00519397 2016-08-04 00:00:00 0.04 80
USC00519397 2016-08-05 00:00:00 0.01 80
USC00519397 2016-08-06 00:00:00 0.0 80
USC00519397 2016-08-07 00:00:00 0.39 77
USC00519397 2016-08-08 00:00:00 0.02 81
USC00519397 2016-08-09 00:00:00 0.0 80
USC00519397 2016-08-10 00:00:00 0.0 80
USC00519397 2016-08-11 00:00:00 0.0 80
USC00519397 2016-08-12 00:00:00 0.0 79
USC00519397 2016-08-13 00:00:00 0.0 79
USC00519397 2016-08-14 00:00:00 0.0 79
USC00519397 2016-08-15 00:00:00 0.0 79
USC00519397 2016-08-16 00:00:00 0.0 80
USC00519397 2016-08-17 00:00:00 0.0 78
USC00519397 2016-08-18 00:00:00 0.0 80
USC00519397 2016-08-19 00:00:00 0.04 77
USC00519397 2016-08-20 00:00:00 0.0 80
USC00519397 2016-08-21 00:00:00 0.12 76
USC00519397 2016-08-22 00:00:00 0.4 77
USC00519397 2016-08-23 00:00:00 0.0 81
USC00519397 2016-08-24 00:00:00 0.08 79
USC00519397 2016-08-25 00:00:00 0.08 80
USC00519397 2016-08-26 00:00:00 0.0 79
USC00519397 2016-08-27 00:00:00 0.0 77
USC00519397 2016-08-28 00:00:00 0.01 78
USC00519397 2016-08-29 00:00:00 0.0 78
USC00519397 2016-08-30 00:00:00 0.0 79
USC00519397 2016-08-31 00:00:00 0.13 80
USC00519397 2016-09-01 00:00:00 0.0 81
USC00519397 2016-09-02 00:00:00 0.0 80
USC00519397 2016-09-03 00:00:00 0.0 79
USC00519397 2016-09-04 00:00:00 0.03 75
USC00519397 2016-09-07 00:00:00 0.05 76
USC00519397 2016-09-08 00:00:00 0.0 80
USC00519397 2016-09-09 00:00:00 0.03 79
USC00519397 2016-09-10 00:00:00 0.0 78
USC00519397 2016-09-11 00:00:00 0.05 76
USC00519397 2016-09-12 00:00:00 0.0 78
USC00519397 2016-09-13 00:00:00 0.02 78
USC00519397 2016-09-14 00:00:00 1.32 75
USC00519397 2016-09-15 00:00:00 0.42 79
USC00519397 2016-09-16 00:00:00 0.06 80
USC00519397 2016-09-17 00:00:00 0.05 79
USC00519397 2016-09-18 00:00:00 0.0 81
USC00519397 2016-09-19 00:00:00 0.0 77
USC00519397 2016-09-20 00:00:00 0.0 77
USC00519397 2016-09-21 00:00:00 0.0 78
USC00519397 2016-09-22 00:00:00 0.02 76
USC00519397 2016-09-23 00:00:00 0.0 82
USC00519397 2016-09-24 00:00:00 0.0 81
USC00519397 2016-09-25 00:00:00 0.0 78
USC00519397 2016-09-26 00:00:00 0.06 80
USC00519397 2016-09-27 00:00:00 0.02 80
USC00519397 2016-09-28 00:00:00 0.0 79
USC00519397 2016-09-29 00:00:00 0.0 80
USC00519397 2016-09-30 00:00:00 0.0 80
USC00519397 2016-10-01 00:00:00 0.0 80
USC00519397 2016-10-02 00:00:00 0.0 79
USC00519397 2016-10-03 00:00:00 0.0 79
USC00519397 2016-10-04 00:00:00 0.0 79
USC00519397 2016-10-05 00:00:00 0.0 80
USC00519397 2016-10-06 00:00:00 0.0 80
USC00519397 2016-10-07 00:00:00 0.0 79
USC00519397 2016-10-08 00:00:00 0.0 78
USC00519397 2016-10-09 00:00:00 0.0 76
USC00519397 2016-10-10 00:00:00 0.0 75
USC00519397 2016-10-11 00:00:00 0.0 80
USC00519397 2016-10-12 00:00:00 0.0 80
USC00519397 2016-10-13 00:00:00 0.0 79
USC00519397 2016-10-14 00:00:00 0.0 80
USC00519397 2016-10-15 00:00:00 0.0 79
USC00519397 2016-10-16 00:00:00 0.0 78
USC00519397 2016-10-17 00:00:00 0.01 78
USC00519397 2016-10-18 00:00:00 0.0 80
USC00519397 2016-10-19 00:00:00 0.0 81
USC00519397 2016-10-20 00:00:00 0.0 79
USC00519397 2016-10-21 00:00:00 0.05 77
USC00519397 2016-10-22 00:00:00 0.15 79
USC00519397 2016-10-23 00:00:00 0.01 78
USC00519397 2016-10-24 00:00:00 0.0 77
USC00519397 2016-10-25 00:00:00 0.03 77
USC00519397 2016-10-26 00:00:00 0.0 78
USC00519397 2016-10-27 00:00:00 0.0 77
USC00519397 2016-10-28 00:00:00 0.0 78
USC00519397 2016-10-29 00:00:00 0.0 77
USC00519397 2016-10-30 00:00:00 0.24 76
USC00519397 2016-10-31 00:00:00 0.03 77
USC00519397 2016-11-01 00:00:00 0.0 77
USC00519397 2016-11-02 00:00:00 0.0 77
USC00519397 2016-11-03 00:00:00 0.0 77
USC00519397 2016-11-04 00:00:00 0.0 77
USC00519397 2016-11-05 00:00:00 0.0 76
USC00519397 2016-11-06 00:00:00 0.0 75
USC00519397 2016-11-07 00:00:00 0.0 71
USC00519397 2016-11-08 00:00:00 0.07 71
USC00519397 2016-11-09 00:00:00 0.0 71
USC00519397 2016-11-10 00:00:00 0.0 71
USC00519397 2016-11-11 00:00:00 0.0 72
USC00519397 2016-11-12 00:00:00 0.0 71
USC00519397 2016-11-13 00:00:00 0.0 72
USC00519397 2016-11-14 00:00:00 0.0 77
USC00519397 2016-11-15 00:00:00 0.0 77
USC00519397 2016-11-16 00:00:00 0.0 77
USC00519397 2016-11-17 00:00:00 0.0 77
USC00519397 2016-11-18 00:00:00 0.0 77
USC00519397 2016-11-19 00:00:00 0.03 75
USC00519397 2016-11-20 00:00:00 0.05 76
USC00519397 2016-11-21 00:00:00 0.01 76
USC00519397 2016-11-22 00:00:00 0.13 75
USC00519397 2016-11-23 00:00:00 0.14 72
USC00519397 2016-11-24 00:00:00 0.05 74
USC00519397 2016-11-25 00:00:00 0.05 75
USC00519397 2016-11-26 00:00:00 0.05 73
USC00519397 2016-11-27 00:00:00 0.0 76
USC00519397 2016-11-28 00:00:00 0.01 75
USC00519397 2016-11-29 00:00:00 0.0 68
USC00519397 2016-11-30 00:00:00 0.14 75
USC00519397 2016-12-01 00:00:00 0.12 75
USC00519397 2016-12-02 00:00:00 0.03 72
USC00519397 2016-12-03 00:00:00 0.0 69
USC00519397 2016-12-04 00:00:00 0.03 71
USC00519397 2016-12-05 00:00:00 0.43 68
USC00519397 2016-12-06 00:00:00 0.02 67
USC00519397 2016-12-07 00:00:00 0.0 69
USC00519397 2016-12-08 00:00:00 0.03 73
USC00519397 2016-12-09 00:00:00 0.52 70
USC00519397 2016-12-10 00:00:00 0.05 70
USC00519397 2016-12-11 00:00:00 0.04 70
USC00519397 2016-12-12 00:00:00 0.01 66
USC00519397 2016-12-13 00:00:00 0.05 67
USC00519397 2016-12-14 00:00:00 0.03 70
USC00519397 2016-12-15 00:00:00 0.0 66
USC00519397 2016-12-16 00:00:00 0.0 62
USC00519397 2016-12-17 00:00:00 0.01 71
USC00519397 2016-12-18 00:00:00 0.13 73
USC00519397 2016-12-19 00:00:00 0.01 69
USC00519397 2016-12-20 00:00:00 0.0 77
USC00519397 2016-12-21 00:00:00 0.0 74
USC00519397 2016-12-22 00:00:00 0.01 71
USC00519397 2016-12-23 00:00:00 0.01 72
USC00519397 2016-12-24 00:00:00 0.01 74
USC00519397 2016-12-25 00:00:00 0.0 74
USC00519397 2016-12-26 00:00:00 0.02 74
USC00519397 2016-12-27 00:00:00 0.0 74
USC00519397 2016-12-28 00:00:00 0.02 71
USC00519397 2016-12-29 00:00:00 0.04 73
USC00519397 2016-12-30 00:00:00 0.12 69
USC00519397 2016-12-31 00:00:00 0.01 66
USC00519397 2017-01-01 00:00:00 0.0 62
USC00519397 2017-01-02 00:00:00 0.0 66
USC00519397 2017-01-03 00:00:00 0.0 63
USC00519397 2017-01-04 00:00:00 0.0 62
USC00519397 2017-01-05 00:00:00 0.0 63
USC00519397 2017-01-06 00:00:00 0.0 64
USC00519397 2017-01-07 00:00:00 0.0 66
USC00519397 2017-01-08 00:00:00 0.0 60
USC00519397 2017-01-09 00:00:00 0.0 64
USC00519397 2017-01-10 00:00:00 0.0 63
USC00519397 2017-01-11 00:00:00 0.0 78
USC00519397 2017-01-12 00:00:00 0.0 67
USC00519397 2017-01-13 00:00:00 0.0 67
USC00519397 2017-01-14 00:00:00 0.0 65
USC00519397 2017-01-15 00:00:00 0.0 66
USC00519397 2017-01-16 00:00:00 0.0 67
USC00519397 2017-01-17 00:00:00 0.0 66
USC00519397 2017-01-18 00:00:00 0.0 72
USC00519397 2017-01-19 00:00:00 0.0 73
USC00519397 2017-01-20 00:00:00 0.0 71
USC00519397 2017-01-21 00:00:00 0.0 72
USC00519397 2017-01-22 00:00:00 0.16 72
USC00519397 2017-01-23 00:00:00 0.0 72
USC00519397 2017-01-24 00:00:00 0.04 69
USC00519397 2017-01-25 00:00:00 0.03 72
USC00519397 2017-01-26 00:00:00 0.0 71
USC00519397 2017-01-27 00:00:00 0.0 65
USC00519397 2017-01-28 00:00:00 0.0 64
USC00519397 2017-01-29 00:00:00 0.18 67
USC00519397 2017-01-30 00:00:00 0.0 67
USC00519397 2017-01-31 00:00:00 0.0 68
USC00519397 2017-02-01 00:00:00 0.0 70
USC00519397 2017-02-02 00:00:00 0.0 61
USC00519397 2017-02-03 00:00:00 0.0 65
USC00519397 2017-02-04 00:00:00 0.0 72
USC00519397 2017-02-05 00:00:00 0.0 73
USC00519397 2017-02-06 00:00:00 0.0 76
USC00519397 2017-02-07 00:00:00 0.51 64
USC00519397 2017-02-08 00:00:00 0.0 62
USC00519397 2017-02-09 00:00:00 0.0 61
USC00519397 2017-02-10 00:00:00 0.0 71
USC00519397 2017-02-11 00:00:00 0.31 69
USC00519397 2017-02-12 00:00:00 2.62 68
USC00519397 2017-02-13 00:00:00 0.01 74
USC00519397 2017-02-14 00:00:00 0.0 75
USC00519397 2017-02-15 00:00:00 0.0 75
USC00519397 2017-02-16 00:00:00 0.07 71
USC00519397 2017-02-17 00:00:00 0.0 71
USC00519397 2017-02-18 00:00:00 0.0 68
USC00519397 2017-02-19 00:00:00 0.0 69
USC00519397 2017-02-20 00:00:00 0.0 71
USC00519397 2017-02-21 00:00:00 0.06 70
USC00519397 2017-02-22 00:00:00 0.06 72
USC00519397 2017-02-23 00:00:00 0.01 74
USC00519397 2017-02-24 00:00:00 0.0 70
USC00519397 2017-02-25 00:00:00 0.03 64
USC00519397 2017-02-26 00:00:00 0.0 65
USC00519397 2017-02-27 00:00:00 0.0 72
USC00519397 2017-02-28 00:00:00 0.0 74
USC00519397 2017-03-01 00:00:00 1.19 66
USC00519397 2017-03-02 00:00:00 0.73 73
USC00519397 2017-03-03 00:00:00 0.47 69
USC00519397 2017-03-04 00:00:00 0.0 74
USC00519397 2017-03-05 00:00:00 0.35 71
USC00519397 2017-03-06 00:00:00 0.0 69
USC00519397 2017-03-07 00:00:00 0.0 68
USC00519397 2017-03-08 00:00:00 0.0 71
USC00519397 2017-03-09 00:00:00 0.0 72
USC00519397 2017-03-10 00:00:00 0.0 68
USC00519397 2017-03-11 00:00:00 0.0 71
USC00519397 2017-03-12 00:00:00 0.0 74
USC00519397 2017-03-13 00:00:00 0.0 71
USC00519397 2017-03-14 00:00:00 0.0 71
USC00519397 2017-03-15 00:00:00 0.0 71
USC00519397 2017-03-16 00:00:00 0.0 70
USC00519397 2017-03-17 00:00:00 0.0 72
USC00519397 2017-03-18 00:00:00 0.0 69
USC00519397 2017-03-19 00:00:00 0.0 73
USC00519397 2017-03-20 00:00:00 0.0 75
USC00519397 2017-03-21 00:00:00 0.0 75
USC00519397 2017-03-22 00:00:00 0.0 74
USC00519397 2017-03-23 00:00:00 0.0 70
USC00519397 2017-03-24 00:00:00 0.02 73
USC00519397 2017-03-25 00:00:00 0.0 76
USC00519397 2017-03-26 00:00:00 0.0 76
USC00519397 2017-03-27 00:00:00 0.0 75
USC00519397 2017-03-28 00:00:00 0.0 77
USC00519397 2017-03-29 00:00:00 0.0 76
USC00519397 2017-03-30 00:00:00 0.0 77
USC00519397 2017-03-31 00:00:00 0.0 76
USC00519397 2017-04-01 00:00:00 0.0 76
USC00519397 2017-04-02 00:00:00 0.0 76
USC00519397 2017-04-03 00:00:00 0.0 77
USC00519397 2017-04-04 00:00:00 0.0 76
USC00519397 2017-04-05 00:00:00 0.0 78
USC00519397 2017-04-06 00:00:00 0.0 77
USC00519397 2017-04-07 00:00:00 0.0 77
USC00519397 2017-04-08 00:00:00 0.0 77
USC00519397 2017-04-09 00:00:00 0.0 72
USC00519397 2017-04-10 00:00:00 0.0 75
USC00519397 2017-04-11 00:00:00 0.0 79
USC00519397 2017-04-12 00:00:00 0.0 78
USC00519397 2017-04-13 00:00:00 0.0 77
USC00519397 2017-04-14 00:00:00 0.26 75
USC00519397 2017-04-15 00:00:00 0.01 73

USC00519397 2017-04-16 00:00:00 0.0 74
USC00519397 2017-04-17 00:00:00 0.02 74
USC00519397 2017-04-18 00:00:00 0.0 75
USC00519397 2017-04-19 00:00:00 0.02 74
USC00519397 2017-04-20 00:00:00 0.05 78
USC00519397 2017-04-21 00:00:00 0.23 73
USC00519397 2017-04-22 00:00:00 0.32 76
USC00519397 2017-04-23 00:00:00 0.03 77
USC00519397 2017-04-24 00:00:00 0.0 77
USC00519397 2017-04-25 00:00:00 0.0 77
USC00519397 2017-04-26 00:00:00 0.0 77
USC00519397 2017-04-27 00:00:00 0.0 78
USC00519397 2017-04-28 00:00:00 0.0 76
USC00519397 2017-04-29 00:00:00 0.12 72
USC00519397 2017-04-30 00:00:00 0.89 63
USC00519397 2017-05-01 00:00:00 0.26 75
USC00519397 2017-05-02 00:00:00 0.0 78
USC00519397 2017-05-03 00:00:00 0.0 78
USC00519397 2017-05-04 00:00:00 0.0 78
USC00519397 2017-05-05 00:00:00 0.0 79
USC00519397 2017-05-06 00:00:00 0.0 79
USC00519397 2017-05-07 00:00:00 0.0 79
USC00519397 2017-05-08 00:00:00 0.0 77
USC00519397 2017-05-10 00:00:00 0.0 78
USC00519397 2017-05-11 00:00:00 0.01 78
USC00519397 2017-05-12 00:00:00 0.0 79
USC00519397 2017-05-13 00:00:00 0.0 79
USC00519397 2017-05-14 00:00:00 0.0 77
USC00519397 2017-05-15 00:00:00 0.05 78
USC00519397 2017-05-16 00:00:00 0.01 78
USC00519397 2017-05-17 00:00:00 0.0 78
USC00519397 2017-05-18 00:00:00 0.01 73
USC00519397 2017-05-19 00:00:00 0.0 76
USC00519397 2017-05-20 00:00:00 0.0 78
USC00519397 2017-05-21 00:00:00 0.0 76
USC00519397 2017-05-22 00:00:00 0.0 77
USC00519397 2017-05-23 00:00:00 0.08 87
USC00519397 2017-05-24 00:00:00 0.13 77
USC00519397 2017-05-25 00:00:00 0.15 77
USC00519397 2017-05-27 00:00:00 0.01 74
USC00519397 2017-05-28 00:00:00 0.02 76
USC00519397 2017-05-29 00:00:00 0.0 75
USC00519397 2017-05-30 00:00:00 0.26 76
USC00519397 2017-05-31 00:00:00 0.02 79
USC00519397 2017-06-01 00:00:00 0.0 79
USC00519397 2017-06-02 00:00:00 0.0 79
USC00519397 2017-06-03 00:00:00 0.02 79
USC00519397 2017-06-04 00:00:00 0.0 79
USC00519397 2017-06-05 00:00:00 0.0 80
USC00519397 2017-06-06 00:00:00 0.0 79
USC00519397 2017-06-07 00:00:00 0.0 79
USC00519397 2017-06-08 00:00:00 0.0 80
USC00519397 2017-06-09 00:00:00 0.0 80
USC00519397 2017-06-10 00:00:00 0.04 77
USC00519397 2017-06-11 00:00:00 0.08 79
USC00519397 2017-06-12 00:00:00 0.02 83
USC00519397 2017-06-13 00:00:00 0.0 80
USC00519397 2017-06-14 00:00:00 0.0 80
USC00519397 2017-06-15 00:00:00 0.0 78
USC00519397 2017-06-16 00:00:00 0.0 79
USC00519397 2017-06-17 00:00:00 0.0 80
USC00519397 2017-06-18 00:00:00 0.05 77
USC00519397 2017-06-19 00:00:00 0.0 80
USC00519397 2017-06-20 00:00:00 0.02 78
USC00519397 2017-06-21 00:00:00 0.0 79
USC00519397 2017-06-22 00:00:00 0.0 80
USC00519397 2017-06-23 00:00:00 0.0 78
USC00519397 2017-06-24 00:00:00 0.06 80
USC00519397 2017-06-25 00:00:00 0.0 80
USC00519397 2017-06-26 00:00:00 0.0 81
USC00519397 2017-06-27 00:00:00 0.0 80
USC00519397 2017-06-28 00:00:00 0.0 79
USC00519397 2017-06-29 00:00:00 0.0 79
USC00519397 2017-06-30 00:00:00 0.08 75
USC00519397 2017-07-01 00:00:00 0.02 80
USC00519397 2017-07-02 00:00:00 0.02 80
USC00519397 2017-07-03 00:00:00 0.04 78
USC00519397 2017-07-04 00:00:00 0.04 80
USC00519397 2017-07-05 00:00:00 0.0 80
USC00519397 2017-07-06 00:00:00 0.0 81
USC00519397 2017-07-07 00:00:00 0.0 79
USC00519397 2017-07-08 00:00:00 0.0 80
USC00519397 2017-07-09 00:00:00 0.0 80
USC00519397 2017-07-10 00:00:00 0.0 80
USC00519397 2017-07-11 00:00:00 0.0 78
USC00519397 2017-07-12 00:00:00 0.0 81
USC00519397 2017-07-13 00:00:00 0.07 79
USC00519397 2017-07-14 00:00:00 0.02 81
USC00519397 2017-07-15 00:00:00 0.0 80
USC00519397 2017-07-16 00:00:00 0.02 78
USC00519397 2017-07-17 00:00:00 0.03 80
USC00519397 2017-07-18 00:00:00 0.05 80
USC00519397 2017-07-20 00:00:00 0.03 80
USC00519397 2017-07-21 00:00:00 0.0 80
USC00519397 2017-07-22 00:00:00 0.03 81
USC00519397 2017-07-23 00:00:00 0.0 81
USC00519397 2017-07-24 00:00:00 0.05 78
USC00519397 2017-07-25 00:00:00 0.0 80
USC00519397 2017-07-26 00:00:00 0.0 82
USC00519397 2017-07-27 00:00:00 0.0 79
USC00519397 2017-07-28 00:00:00 0.0 81
USC00519397 2017-07-29 00:00:00 0.0 81
USC00519397 2017-07-30 00:00:00 0.0 81
USC00519397 2017-07-31 00:00:00 0.0 80
USC00519397 2017-08-01 00:00:00 0.02 77
USC00519397 2017-08-02 00:00:00 0.0 73
USC00519397 2017-08-03 00:00:00 0.0 79
USC00519397 2017-08-04 00:00:00 0.02 80
USC00519397 2017-08-05 00:00:00 0.0 81
USC00519397 2017-08-06 00:00:00 0.0 80
USC00519397 2017-08-07 00:00:00 0.0 80
USC00519397 2017-08-08 00:00:00 0.0 80
USC00519397 2017-08-09 00:00:00 0.0 80
USC00519397 2017-08-10 00:00:00 0.0 81
USC00519397 2017-08-11 00:00:00 0.0 78
USC00519397 2017-08-12 00:00:00 0.0 80
USC00519397 2017-08-13 00:00:00 0.0 81
USC00519397 2017-08-14 00:00:00 0.0 79
USC00519397 2017-08-15 00:00:00 0.02 78
USC00519397 2017-08-18 00:00:00 0.0 80
USC00519397 2017-08-19 00:00:00 0.0 79
USC00519397 2017-08-20 00:00:00 0.0 81
USC00519397 2017-08-21 00:00:00 0.0 81
USC00519397 2017-08-22 00:00:00 0.0 82
USC00519397 2017-08-23 00:00:00 0.0 81
USC00513117 KANEOHE 838.1, HI US
USC00513117 2010-01-01 00:00:00 0.28 67
USC00513117 2010-01-02 00:00:00 0.0 65
USC00513117 2010-01-03 00:00:00 0.0 75
USC00513117 2010-01-04 00:00:00 0.0 76
USC00513117 2010-01-05 00:00:00 0.0 76
USC00513117 2010-01-06 00:00:00 0.02 76
USC00513117 2010-01-07 00:00:00 0.38 70
USC00513117 2010-01-08 00:00:00 0.01 66
USC00513117 2010-01-09 00:00:00 0.0 69
USC00513117 2010-01-10 00:00:00 0.0 74
USC00513117 2010-01-11 00:00:00 0.03 67
USC00513117 2010-01-12 00:00:00 0.0 64
USC00513117 2010-01-13 00:00:00 0.0 64
USC00513117 2010-01-14 00:00:00 0.0 65
USC00513117 2010-01-15 00:00:00 0.0 69
USC00513117 2010-01-16 00:00:00 0.0 71
USC00513117 2010-01-17 00:00:00 0.0 69
USC00513117 2010-01-18 00:00:00 0.0 73
USC00513117 2010-01-19 00:00:00 0.0 73
USC00513117 2010-01-20 00:00:00 0.01 72
USC00513117 2010-01-21 00:00:00 0.04 70
USC00513117 2010-01-22 00:00:00 0.0 65
USC00513117 2010-01-23 00:00:00 0.0 73
USC00513117 2010-01-24 00:00:00 0.0 74
USC00513117 2010-01-25 00:00:00 0.0 68
USC00513117 2010-01-26 00:00:00 0.0 77
USC00513117 2010-01-27 00:00:00 0.12 71
USC00513117 2010-01-28 00:00:00 0.19 68
USC00513117 2010-01-29 00:00:00 0.19 68
USC00513117 2010-01-30 00:00:00 1.7 69
USC00513117 2010-01-31 00:00:00 0.28 73
USC00513117 2010-02-01 00:00:00 0.01 69
USC00513117 2010-02-02 00:00:00 0.0 70
USC00513117 2010-02-03 00:00:00 0.31 66
USC00513117 2010-02-04 00:00:00 0.0 69
USC00513117 2010-02-05 00:00:00 0.0 70
USC00513117 2010-02-06 00:00:00 0.06 66
USC00513117 2010-02-07 00:00:00 0.0 66
USC00513117 2010-02-08 00:00:00 0.0 71
USC00513117 2010-02-09 00:00:00 0.0 72
USC00513117 2010-02-10 00:00:00 0.0 65
USC00513117 2010-02-14 00:00:00 0.0 67
USC00513117 2010-02-15 00:00:00 0.0 72
USC00513117 2010-02-16 00:00:00 0.0 64
USC00513117 2010-02-17 00:00:00 0.02 69
USC00513117 2010-02-18 00:00:00 0.0 68
USC00513117 2010-02-19 00:00:00 0.05 63
USC00513117 2010-02-20 00:00:00 0.17 66
USC00513117 2010-02-21 00:00:00 0.04 66
USC00513117 2010-02-22 00:00:00 0.87 66
USC00513117 2010-02-23 00:00:00 0.0 65
USC00513117 2010-02-24 00:00:00 0.0 65
USC00513117 2010-02-25 00:00:00 0.0 70
USC00513117 2010-02-26 00:00:00 0.0 74
USC00513117 2010-02-27 00:00:00 0.0 70
USC00513117 2010-02-28 00:00:00 0.0 70
USC00513117 2010-03-01 00:00:00 0.04 70
USC00513117 2010-03-02 00:00:00 0.0 71
USC00513117 2010-03-03 00:00:00 0.0 71
USC00513117 2010-03-04 00:00:00 0.33 68
USC00513117 2010-03-05 00:00:00 0.21 69
USC00513117 2010-03-06 00:00:00 0.09 71
USC00513117 2010-03-07 00:00:00 0.0 70
USC00513117 2010-03-08 00:00:00 0.34 70
USC00513117 2010-03-09 00:00:00 0.05 68
USC00513117 2010-03-10 00:00:00 0.04 70
USC00513117 2010-03-11 00:00:00 0.09 71
USC00513117 2010-03-12 00:00:00 0.03 71
USC00513117 2010-03-13 00:00:00 0.0 70
USC00513117 2010-03-14 00:00:00 0.0 72
USC00513117 2010-03-15 00:00:00 0.16 70
USC00513117 2010-03-16 00:00:00 0.16 71
USC00513117 2010-03-17 00:00:00 0.4 66
USC00513117 2010-03-18 00:00:00 0.44 66
USC00513117 2010-03-19 00:00:00 0.08 69
USC00513117 2010-03-20 00:00:00 0.01 69
USC00513117 2010-03-21 00:00:00 0.0 71
USC00513117 2010-03-22 00:00:00 0.0 68
USC00513117 2010-03-23 00:00:00 0.0 67
USC00513117 2010-03-24 00:00:00 0.03 72
USC00513117 2010-03-25 00:00:00 0.01 72
USC00513117 2010-03-26 00:00:00 0.02 71
USC00513117 2010-03-27 00:00:00 0.01 71
USC00513117 2010-03-28 00:00:00 0.01 71
USC00513117 2010-03-29 00:00:00 0.0 72
USC00513117 2010-03-30 00:00:00 0.02 73
USC00513117 2010-03-31 00:00:00 0.02 71
USC00513117 2010-04-01 00:00:00 0.01 73
USC00513117 2010-04-02 00:00:00 0.02 71
USC00513117 2010-04-03 00:00:00 0.03 72
USC00513117 2010-04-04 00:00:00 0.13 71
USC00513117 2010-04-05 00:00:00 0.19 71
USC00513117 2010-04-06 00:00:00 0.07 69
USC00513117 2010-04-07 00:00:00 0.51 70
USC00513117 2010-04-08 00:00:00 0.0 73
USC00513117 2010-04-09 00:00:00 0.24 69
USC00513117 2010-04-10 00:00:00 0.03 72
USC00513117 2010-04-11 00:00:00 0.03 69
USC00513117 2010-04-12 00:00:00 0.01 71
USC00513117 2010-04-13 00:00:00 0.06 71
USC00513117 2010-04-14 00:00:00 0.07 69
USC00513117 2010-04-15 00:00:00 0.0 69
USC00513117 2010-04-16 00:00:00 0.03 67
USC00513117 2010-04-17 00:00:00 0.02 69
USC00513117 2010-04-18 00:00:00 0.0 70
USC00513117 2010-04-19 00:00:00 0.01 71
USC00513117 2010-04-20 00:00:00 0.06 70
USC00513117 2010-04-21 00:00:00 0.0 72
USC00513117 2010-04-22 00:00:00 0.0 72
USC00513117 2010-04-23 00:00:00 0.13 71
USC00513117 2010-04-24 00:00:00 0.15 73
USC00513117 2010-04-25 00:00:00 0.0 74
USC00513117 2010-04-26 00:00:00 0.0 72
USC00513117 2010-04-27 00:00:00 0.01 72
USC00513117 2010-04-28 00:00:00 0.07 71
USC00513117 2010-04-29 00:00:00 0.01 74
USC00513117 2010-04-30 00:00:00 0.02 74
USC00513117 2010-05-01 00:00:00 0.02 72
USC00513117 2010-05-02 00:00:00 0.03 72
USC00513117 2010-05-03 00:00:00 0.89 72
USC00513117 2010-05-04 00:00:00 0.07 73
USC00513117 2010-05-05 00:00:00 0.0 74
USC00513117 2010-05-06 00:00:00 0.0 73
USC00513117 2010-05-07 00:00:00 0.08 72

USC00513117 2010-05-08 00:00:00 0.01 76
USC00513117 2010-05-09 00:00:00 0.0 73
USC00513117 2010-05-10 00:00:00 0.0 74
USC00513117 2010-05-11 00:00:00 0.0 74
USC00513117 2010-05-12 00:00:00 0.01 73
USC00513117 2010-05-13 00:00:00 0.01 75
USC00513117 2010-05-14 00:00:00 0.0 74
USC00513117 2010-05-15 00:00:00 0.06 69
USC00513117 2010-05-16 00:00:00 0.1 74
USC00513117 2010-05-17 00:00:00 0.0 73
USC00513117 2010-05-18 00:00:00 0.0 74
USC00513117 2010-05-19 00:00:00 0.0 73
USC00513117 2010-05-20 00:00:00 0.08 72
USC00513117 2010-05-21 00:00:00 0.05 73
USC00513117 2010-05-22 00:00:00 0.05 75
USC00513117 2010-05-23 00:00:00 0.04 74
USC00513117 2010-05-24 00:00:00 0.07 74
USC00513117 2010-05-25 00:00:00 0.09 74
USC00513117 2010-05-26 00:00:00 0.08 74
USC00513117 2010-05-27 00:00:00 0.0 74
USC00513117 2010-05-28 00:00:00 0.0 71
USC00513117 2010-05-29 00:00:00 0.01 74
USC00513117 2010-05-30 00:00:00 0.0 75
USC00513117 2010-05-31 00:00:00 0.02 75
USC00513117 2010-06-01 00:00:00 0.03 74
USC00513117 2010-06-02 00:00:00 0.0 76
USC00513117 2010-06-03 00:00:00 0.0 75
USC00513117 2010-06-04 00:00:00 0.0 75
USC00513117 2010-06-05 00:00:00 0.0 74
USC00513117 2010-06-06 00:00:00 0.0 75
USC00513117 2010-06-07 00:00:00 0.02 75
USC00513117 2010-06-08 00:00:00 0.0 75
USC00513117 2010-06-09 00:00:00 0.0 75
USC00513117 2010-06-10 00:00:00 0.02 75
USC00513117 2010-06-11 00:00:00 0.0 83
USC00513117 2010-06-12 00:00:00 0.0 75
USC00513117 2010-06-13 00:00:00 0.01 76
USC00513117 2010-06-14 00:00:00 0.06 73
USC00513117 2010-06-15 00:00:00 0.0 74
USC00513117 2010-06-16 00:00:00 0.01 74
USC00513117 2010-06-17 00:00:00 0.02 75
USC00513117 2010-06-18 00:00:00 0.06 70
USC00513117 2010-06-19 00:00:00 0.13 74
USC00513117 2010-06-20 00:00:00 0.02 75
USC00513117 2010-06-21 00:00:00 0.01 75
USC00513117 2010-06-22 00:00:00 0.0 75
USC00513117 2010-06-23 00:00:00 0.0 75
USC00513117 2010-06-24 00:00:00 0.01 75
USC00513117 2010-06-25 00:00:00 0.05 74
USC00513117 2010-06-26 00:00:00 0.24 72
USC00513117 2010-06-27 00:00:00 0.03 76
USC00513117 2010-06-28 00:00:00 0.11 73
USC00513117 2010-06-29 00:00:00 0.0 75
USC00513117 2010-06-30 00:00:00 0.03 76
USC00513117 2010-07-01 00:00:00 0.01 73
USC00513117 2010-07-02 00:00:00 0.14 72
USC00513117 2010-07-03 00:00:00 0.06 75
USC00513117 2010-07-04 00:00:00 0.07 75
USC00513117 2010-07-05 00:00:00 0.03 72
USC00513117 2010-07-06 00:00:00 0.05 72
USC00513117 2010-07-07 00:00:00 0.11 73
USC00513117 2010-07-08 00:00:00 0.04 74
USC00513117 2010-07-09 00:00:00 0.04 74
USC00513117 2010-07-10 00:00:00 0.09 73
USC00513117 2010-07-11 00:00:00 0.02 81
USC00513117 2010-07-12 00:00:00 0.0 72
USC00513117 2010-07-13 00:00:00 0.01 72
USC00513117 2010-07-14 00:00:00 0.45 70
USC00513117 2010-07-15 00:00:00 0.04 72
USC00513117 2010-07-16 00:00:00 0.02 76
USC00513117 2010-07-17 00:00:00 0.04 75
USC00513117 2010-07-18 00:00:00 0.05 75
USC00513117 2010-07-19 00:00:00 0.12 74
USC00513117 2010-07-20 00:00:00 0.21 75
USC00513117 2010-07-21 00:00:00 0.0 74
USC00513117 2010-07-22 00:00:00 0.15 76
USC00513117 2010-07-23 00:00:00 0.09 73
USC00513117 2010-07-24 00:00:00 0.0 77
USC00513117 2010-07-25 00:00:00 0.0 77
USC00513117 2010-07-26 00:00:00 0.0 76
USC00513117 2010-07-27 00:00:00 0.03 72
USC00513117 2010-07-28 00:00:00 0.46 75
USC00513117 2010-07-29 00:00:00 0.02 75
USC00513117 2010-07-30 00:00:00 0.01 76
USC00513117 2010-07-31 00:00:00 0.02 77
USC00513117 2010-08-01 00:00:00 0.16 72
USC00513117 2010-08-02 00:00:00 0.15 74
USC00513117 2010-08-03 00:00:00 0.04 74
USC00513117 2010-08-04 00:00:00 0.12 74
USC00513117 2010-08-05 00:00:00 0.13 72
USC00513117 2010-08-06 00:00:00 0.0 75
USC00513117 2010-08-07 00:00:00 0.05 74
USC00513117 2010-08-08 00:00:00 0.1 73
USC00513117 2010-08-09 00:00:00 0.04 76
USC00513117 2010-08-10 00:00:00 0.0 76
USC00513117 2010-08-11 00:00:00 0.0 72
USC00513117 2010-08-12 00:00:00 0.02 76
USC00513117 2010-08-13 00:00:00 0.19 76
USC00513117 2010-08-14 00:00:00 0.0 75
USC00513117 2010-08-15 00:00:00 0.0 75
USC00513117 2010-08-16 00:00:00 0.12 70
USC00513117 2010-08-17 00:00:00 0.24 72
USC00513117 2010-08-18 00:00:00 0.08 73
USC00513117 2010-08-19 00:00:00 0.06 76
USC00513117 2010-08-20 00:00:00 0.01 76
USC00513117 2010-08-21 00:00:00 0.0 76
USC00513117 2010-08-22 00:00:00 0.02 75
USC00513117 2010-08-23 00:00:00 0.0 76
USC00513117 2010-08-24 00:00:00 0.08 74
USC00513117 2010-08-25 00:00:00 0.25 73
USC00513117 2010-08-26 00:00:00 0.05 74
USC00513117 2010-08-27 00:00:00 0.21 75
USC00513117 2010-08-28 00:00:00 0.0 76
USC00513117 2010-08-29 00:00:00 0.1 76
USC00513117 2010-08-30 00:00:00 0.02 76
USC00513117 2010-08-31 00:00:00 0.0 76
USC00513117 2010-09-01 00:00:00 0.0 75
USC00513117 2010-09-02 00:00:00 0.03 73
USC00513117 2010-09-03 00:00:00 0.29 72
USC00513117 2010-09-04 00:00:00 0.04 73
USC00513117 2010-09-05 00:00:00 0.08 74
USC00513117 2010-09-06 00:00:00 0.01 75
USC00513117 2010-09-07 00:00:00 0.03 75
USC00513117 2010-09-08 00:00:00 0.01 75
USC00513117 2010-09-09 00:00:00 0.01 75
USC00513117 2010-09-10 00:00:00 0.03 76
USC00513117 2010-09-11 00:00:00 0.02 77
USC00513117 2010-09-12 00:00:00 0.0 76
USC00513117 2010-09-13 00:00:00 0.0 75
USC00513117 2010-09-14 00:00:00 0.01 76
USC00513117 2010-09-15 00:00:00 0.0 76
USC00513117 2010-09-16 00:00:00 0.01 77
USC00513117 2010-09-17 00:00:00 0.0 76
USC00513117 2010-09-18 00:00:00 0.03 76
USC00513117 2010-09-19 00:00:00 0.08 78
USC00513117 2010-09-20 00:00:00 0.03 77
USC00513117 2010-09-21 00:00:00 0.02 75
USC00513117 2010-09-22 00:00:00 0.5 74
USC00513117 2010-09-23 00:00:00 0.33 75
USC00513117 2010-09-24 00:00:00 0.0 75
USC00513117 2010-09-25 00:00:00 0.0 76
USC00513117 2010-09-28 00:00:00 0.0 73
USC00513117 2010-09-29 00:00:00 0.0 73
USC00513117 2010-09-30 00:00:00 0.02 73
USC00513117 2010-10-01 00:00:00 0.43 72
USC00513117 2010-10-02 00:00:00 0.16 76
USC00513117 2010-10-03 00:00:00 0.07 82
USC00513117 2010-10-04 00:00:00 0.06 76
USC00513117 2010-10-05 00:00:00 0.07 77
USC00513117 2010-10-06 00:00:00 0.0 76
USC00513117 2010-10-07 00:00:00 0.0 74
USC00513117 2010-10-08 00:00:00 0.0 72
USC00513117 2010-10-09 00:00:00 0.0 76
USC00513117 2010-10-10 00:00:00 0.03 75
USC00513117 2010-10-11 00:00:00 0.04 76
USC00513117 2010-10-12 00:00:00 0.06 71
USC00513117 2010-10-13 00:00:00 0.02 77
USC00513117 2010-10-14 00:00:00 0.0 76
USC00513117 2010-10-15 00:00:00 0.0 74
USC00513117 2010-10-16 00:00:00 0.0 76
USC00513117 2010-10-17 00:00:00 0.16 77
USC00513117 2010-10-18 00:00:00 0.02 71
USC00513117 2010-10-19 00:00:00 0.0 72
USC00513117 2010-10-20 00:00:00 0.0 71
USC00513117 2010-10-21 00:00:00 0.04 73
USC00513117 2010-10-22 00:00:00 0.0 76
USC00513117 2010-10-23 00:00:00 0.0 84
USC00513117 2010-10-24 00:00:00 0.0 76
USC00513117 2010-10-25 00:00:00 0.0 77
USC00513117 2010-10-26 00:00:00 0.16 76
USC00513117 2010-10-27 00:00:00 0.06 76
USC00513117 2010-10-28 00:00:00 0.09 76
USC00513117 2010-10-29 00:00:00 0.1 75
USC00513117 2010-10-30 00:00:00 0.11 74
USC00513117 2010-10-31 00:00:00 0.0 71
USC00513117 2010-11-01 00:00:00 0.42 73
USC00513117 2010-11-02 00:00:00 0.1 70
USC00513117 2010-11-03 00:00:00 0.0 71
USC00513117 2010-11-04 00:00:00 0.39 73
USC00513117 2010-11-05 00:00:00 0.07 75
USC00513117 2010-11-06 00:00:00 0.1 75
USC00513117 2010-11-07 00:00:00 0.21 75
USC00513117 2010-11-08 00:00:00 0.0 75
USC00513117 2010-11-09 00:00:00 0.01 75
USC00513117 2010-11-10 00:00:00 0.0 76
USC00513117 2010-11-11 00:00:00 0.0 75
USC00513117 2010-11-12 00:00:00 0.0 75
USC00513117 2010-11-13 00:00:00 0.03 75
USC00513117 2010-11-14 00:00:00 0.02 74
USC00513117 2010-11-15 00:00:00 0.35 75
USC00513117 2010-11-16 00:00:00 0.01 74
USC00513117 2010-11-17 00:00:00 0.0 70
USC00513117 2010-11-18 00:00:00 0.0 71
USC00513117 2010-11-19 00:00:00 0.19 71
USC00513117 2010-11-20 00:00:00 0.02 71
USC00513117 2010-11-21 00:00:00 0.0 71
USC00513117 2010-11-22 00:00:00 0.02 68
USC00513117 2010-11-23 00:00:00 0.0 69
USC00513117 2010-11-24 00:00:00 0.0 75
USC00513117 2010-11-25 00:00:00 0.16 75
USC00513117 2010-11-26 00:00:00 0.0 74
USC00513117 2010-11-27 00:00:00 0.03 74
USC00513117 2010-11-28 00:00:00 0.49 71
USC00513117 2010-11-29 00:00:00 0.04 70
USC00513117 2010-11-30 00:00:00 0.15 73
USC00513117 2010-12-01 00:00:00 0.76 73
USC00513117 2010-12-02 00:00:00 0.13 72
USC00513117 2010-12-03 00:00:00 0.16 73
USC00513117 2010-12-04 00:00:00 0.0 74
USC00513117 2010-12-05 00:00:00 0.0 73
USC00513117 2010-12-06 00:00:00 0.0 66
USC00513117 2010-12-07 00:00:00 0.0 64
USC00513117 2010-12-08 00:00:00 0.0 66
USC00513117 2010-12-09 00:00:00 0.0 75
USC00513117 2010-12-10 00:00:00 1.95 65
USC00513117 2010-12-11 00:00:00 0.62 69
USC00513117 2010-12-12 00:00:00 0.15 71
USC00513117 2010-12-13 00:00:00 0.47 69
USC00513117 2010-12-14 00:00:00 0.0 78
USC00513117 2010-12-15 00:00:00 0.0 74
USC00513117 2010-12-16 00:00:00 0.0 68
USC00513117 2010-12-17 00:00:00 0.0 68
USC00513117 2010-12-18 00:00:00 0.0 70
USC00513117 2010-12-19 00:00:00 3.18 70
USC00513117 2010-12-20 00:00:00 4.94 71
USC00513117 2010-12-21 00:00:00 0.43 71
USC00513117 2010-12-22 00:00:00 0.01 71
USC00513117 2010-12-23 00:00:00 0.02 71
USC00513117 2010-12-24 00:00:00 0.0 69
USC00513117 2010-12-25 00:00:00 2.95 69
USC00513117 2010-12-26 00:00:00 0.99 72
USC00513117 2010-12-27 00:00:00 0.46 76
USC00513117 2010-12-28 00:00:00 0.63 72
USC00513117 2010-12-29 00:00:00 0.02 73
USC00513117 2010-12-30 00:00:00 0.11 73
USC00513117 2010-12-31 00:00:00 0.05 74
USC00513117 2011-01-01 00:00:00 0.42 69
USC00513117 2011-01-02 00:00:00 0.11 74
USC00513117 2011-01-03 00:00:00 0.01 74
USC00513117 2011-01-04 00:00:00 0.0 73
USC00513117 2011-01-05 00:00:00 0.04 67
USC00513117 2011-01-06 00:00:00 0.21 67
USC00513117 2011-01-07 00:00:00 0.02 65
USC00513117 2011-01-08 00:00:00 0.01 64
USC00513117 2011-01-09 00:00:00 0.0 63
USC00513117 2011-01-10 00:00:00 0.0 72
USC00513117 2011-01-11 00:00:00 0.11 61
USC00513117 2011-01-12 00:00:00 0.46 71
USC00513117 2011-01-13 00:00:00 5.21 70
USC00513117 2011-01-14 00:00:00 0.22 76

USC00513117 2011-01-15 00:00:00 0.0 68
USC00513117 2011-01-16 00:00:00 0.0 69
USC00513117 2011-01-17 00:00:00 0.03 69
USC00513117 2011-01-18 00:00:00 0.0 66
USC00513117 2011-01-19 00:00:00 0.05 64
USC00513117 2011-01-20 00:00:00 0.01 72
USC00513117 2011-01-21 00:00:00 0.01 73
USC00513117 2011-01-22 00:00:00 0.0 73
USC00513117 2011-01-23 00:00:00 0.0 72
USC00513117 2011-01-24 00:00:00 0.01 72
USC00513117 2011-01-25 00:00:00 0.0 65
USC00513117 2011-01-26 00:00:00 0.0 67
USC00513117 2011-01-27 00:00:00 0.0 72
USC00513117 2011-01-28 00:00:00 0.0 72
USC00513117 2011-01-29 00:00:00 0.01 69
USC00513117 2011-01-30 00:00:00 0.02 72
USC00513117 2011-01-31 00:00:00 0.02 70
USC00513117 2011-02-01 00:00:00 0.0 67
USC00513117 2011-02-02 00:00:00 0.0 72
USC00513117 2011-02-03 00:00:00 0.0 68
USC00513117 2011-02-04 00:00:00 0.0 65
USC00513117 2011-02-05 00:00:00 0.0 71
USC00513117 2011-02-06 00:00:00 0.02 76
USC00513117 2011-02-07 00:00:00 1.06 68
USC00513117 2011-02-08 00:00:00 0.52 70
USC00513117 2011-02-09 00:00:00 0.02 71
USC00513117 2011-02-10 00:00:00 0.03 71
USC00513117 2011-02-11 00:00:00 0.33 71
USC00513117 2011-02-12 00:00:00 1.54 68
USC00513117 2011-02-13 00:00:00 0.19 67
USC00513117 2011-02-14 00:00:00 0.0 70
USC00513117 2011-02-15 00:00:00 0.0 70
USC00513117 2011-02-16 00:00:00 0.2 74
USC00513117 2011-02-17 00:00:00 0.05 74
USC00513117 2011-02-18 00:00:00 0.1 74
USC00513117 2011-02-19 00:00:00 0.0 70
USC00513117 2011-02-20 00:00:00 4.88 71
USC00513117 2011-02-21 00:00:00 0.0 69
USC00513117 2011-02-22 00:00:00 0.02 72
USC00513117 2011-02-23 00:00:00 0.0 73
USC00513117 2011-02-24 00:00:00 3.3 67
USC00513117 2011-02-25 00:00:00 0.0 66
USC00513117 2011-02-26 00:00:00 0.0 69
USC00513117 2011-02-27 00:00:00 0.02 69
USC00513117 2011-02-28 00:00:00 0.0 70
USC00513117 2011-03-01 00:00:00 0.14 66
USC00513117 2011-03-02 00:00:00 0.0 72
USC00513117 2011-03-03 00:00:00 0.12 70
USC00513117 2011-03-04 00:00:00 1.05 71
USC00513117 2011-03-05 00:00:00 0.13 69
USC00513117 2011-03-06 00:00:00 1.16 72
USC00513117 2011-03-07 00:00:00 0.01 73
USC00513117 2011-03-08 00:00:00 0.03 72
USC00513117 2011-03-09 00:00:00 0.09 69
USC00513117 2011-03-10 00:00:00 1.33 72
USC00513117 2011-03-11 00:00:00 0.07 72
USC00513117 2011-03-12 00:00:00 0.14 71
USC00513117 2011-03-13 00:00:00 0.0 72
USC00513117 2011-03-14 00:00:00 0.0 73
USC00513117 2011-03-15 00:00:00 0.0 73
USC00513117 2011-03-16 00:00:00 0.01 74
USC00513117 2011-03-17 00:00:00 0.01 71
USC00513117 2011-03-18 00:00:00 0.03 71
USC00513117 2011-03-19 00:00:00 0.04 73
USC00513117 2011-03-20 00:00:00 0.14 73
USC00513117 2011-03-21 00:00:00 0.0 72
USC00513117 2011-03-22 00:00:00 0.18 70
USC00513117 2011-03-23 00:00:00 0.04 72
USC00513117 2011-03-24 00:00:00 0.12 72
USC00513117 2011-03-25 00:00:00 0.07 72
USC00513117 2011-03-26 00:00:00 0.02 72
USC00513117 2011-03-27 00:00:00 0.04 72
USC00513117 2011-03-28 00:00:00 0.08 72
USC00513117 2011-03-29 00:00:00 0.05 72
USC00513117 2011-03-30 00:00:00 0.08 73
USC00513117 2011-03-31 00:00:00 0.0 72
USC00513117 2011-04-01 00:00:00 0.03 72
USC00513117 2011-04-02 00:00:00 0.01 72
USC00513117 2011-04-03 00:00:00 0.01 70
USC00513117 2011-04-04 00:00:00 0.0 73
USC00513117 2011-04-05 00:00:00 0.0 71
USC00513117 2011-04-06 00:00:00 0.09 70
USC00513117 2011-04-07 00:00:00 0.68 67
USC00513117 2011-04-08 00:00:00 0.39 68
USC00513117 2011-04-09 00:00:00 0.02 74
USC00513117 2011-04-10 00:00:00 0.0 74
USC00513117 2011-04-11 00:00:00 0.0 73
USC00513117 2011-04-12 00:00:00 0.0 73
USC00513117 2011-04-13 00:00:00 0.02 67
USC00513117 2011-04-14 00:00:00 0.02 73
USC00513117 2011-04-15 00:00:00 0.04 69
USC00513117 2011-04-16 00:00:00 0.05 70
USC00513117 2011-04-17 00:00:00 0.0 73
USC00513117 2011-04-18 00:00:00 0.0 72
USC00513117 2011-04-19 00:00:00 0.0 72
USC00513117 2011-04-20 00:00:00 0.0 70
USC00513117 2011-04-21 00:00:00 0.0 71
USC00513117 2011-04-22 00:00:00 0.0 73
USC00513117 2011-04-23 00:00:00 0.0 75
USC00513117 2011-04-24 00:00:00 0.0 73
USC00513117 2011-04-25 00:00:00 0.0 74
USC00513117 2011-04-26 00:00:00 0.12 73
USC00513117 2011-04-27 00:00:00 0.02 74
USC00513117 2011-04-28 00:00:00 0.01 74
USC00513117 2011-04-29 00:00:00 0.13 72
USC00513117 2011-04-30 00:00:00 0.02 71
USC00513117 2011-05-01 00:00:00 0.0 74
USC00513117 2011-05-02 00:00:00 0.22 74
USC00513117 2011-05-03 00:00:00 0.42 71
USC00513117 2011-05-04 00:00:00 0.25 73
USC00513117 2011-05-05 00:00:00 0.15 72
USC00513117 2011-05-06 00:00:00 0.23 72
USC00513117 2011-05-07 00:00:00 0.86 72
USC00513117 2011-05-08 00:00:00 1.76 68
USC00513117 2011-05-09 00:00:00 0.73 74
USC00513117 2011-05-10 00:00:00 0.24 72
USC00513117 2011-05-11 00:00:00 0.92 71
USC00513117 2011-05-12 00:00:00 0.02 74
USC00513117 2011-05-13 00:00:00 0.01 74
USC00513117 2011-05-14 00:00:00 0.0 76
USC00513117 2011-05-15 00:00:00 0.0 73
USC00513117 2011-05-16 00:00:00 0.01 74
USC00513117 2011-05-17 00:00:00 0.0 73
USC00513117 2011-05-18 00:00:00 0.3 70
USC00513117 2011-05-19 00:00:00 0.01 71
USC00513117 2011-05-20 00:00:00 0.03 74
USC00513117 2011-05-21 00:00:00 0.0 75
USC00513117 2011-05-22 00:00:00 0.08 74
USC00513117 2011-05-23 00:00:00 0.06 74
USC00513117 2011-05-24 00:00:00 0.0 74
USC00513117 2011-05-25 00:00:00 0.02 74
USC00513117 2011-05-26 00:00:00 0.0 74
USC00513117 2011-05-27 00:00:00 0.03 74
USC00513117 2011-05-28 00:00:00 0.02 76
USC00513117 2011-05-29 00:00:00 0.1 76
USC00513117 2011-05-30 00:00:00 0.0 75
USC00513117 2011-05-31 00:00:00 0.0 74
USC00513117 2011-06-01 00:00:00 0.03 74
USC00513117 2011-06-02 00:00:00 0.08 75
USC00513117 2011-06-03 00:00:00 0.63 71
USC00513117 2011-06-04 00:00:00 4.43 69
USC00513117 2011-06-05 00:00:00 4.02 69
USC00513117 2011-06-06 00:00:00 0.02 74
USC00513117 2011-06-07 00:00:00 0.06 71
USC00513117 2011-06-08 00:00:00 0.04 74
USC00513117 2011-06-09 00:00:00 0.01 74
USC00513117 2011-06-10 00:00:00 0.02 75
USC00513117 2011-06-11 00:00:00 0.01 73
USC00513117 2011-06-12 00:00:00 0.12 73
USC00513117 2011-06-13 00:00:00 0.16 73
USC00513117 2011-06-14 00:00:00 0.0 75
USC00513117 2011-06-15 00:00:00 0.0 75
USC00513117 2011-06-16 00:00:00 0.06 74
USC00513117 2011-06-17 00:00:00 0.0 74
USC00513117 2011-06-18 00:00:00 0.02 75
USC00513117 2011-06-19 00:00:00 0.09 74
USC00513117 2011-06-20 00:00:00 0.03 73
USC00513117 2011-06-21 00:00:00 0.54 72
USC00513117 2011-06-22 00:00:00 0.22 74
USC00513117 2011-06-23 00:00:00 0.03 72
USC00513117 2011-06-24 00:00:00 0.21 75
USC00513117 2011-06-25 00:00:00 0.0 76
USC00513117 2011-06-26 00:00:00 0.04 74
USC00513117 2011-06-27 00:00:00 0.03 74
USC00513117 2011-06-28 00:00:00 0.1 74
USC00513117 2011-06-29 00:00:00 0.0 74
USC00513117 2011-06-30 00:00:00 0.0 74
USC00513117 2011-07-01 00:00:00 0.09 74
USC00513117 2011-07-02 00:00:00 0.0 75
USC00513117 2011-07-03 00:00:00 0.04 76
USC00513117 2011-07-04 00:00:00 0.0 74
USC00513117 2011-07-05 00:00:00 0.03 74
USC00513117 2011-07-06 00:00:00 0.02 76
USC00513117 2011-07-07 00:00:00 0.07 73
USC00513117 2011-07-08 00:00:00 0.1 75
USC00513117 2011-07-09 00:00:00 0.05 75
USC00513117 2011-07-10 00:00:00 0.02 76
USC00513117 2011-07-11 00:00:00 0.01 74
USC00513117 2011-07-12 00:00:00 0.0 74
USC00513117 2011-07-13 00:00:00 0.0 74
USC00513117 2011-07-14 00:00:00 0.06 73
USC00513117 2011-07-15 00:00:00 0.0 75
USC00513117 2011-07-16 00:00:00 0.0 75
USC00513117 2011-07-17 00:00:00 0.15 75
USC00513117 2011-07-18 00:00:00 0.04 74
USC00513117 2011-07-19 00:00:00 0.0 74
USC00513117 2011-07-20 00:00:00 0.1 71
USC00513117 2011-07-21 00:00:00 0.04 75
USC00513117 2011-07-22 00:00:00 0.08 74
USC00513117 2011-07-23 00:00:00 0.0 75
USC00513117 2011-07-24 00:00:00 0.1 70
USC00513117 2011-07-25 00:00:00 0.22 74
USC00513117 2011-07-26 00:00:00 0.01 74
USC00513117 2011-07-27 00:00:00 0.04 75
USC00513117 2011-07-28 00:00:00 0.03 75
USC00513117 2011-07-29 00:00:00 0.15 74
USC00513117 2011-07-30 00:00:00 0.61 75
USC00513117 2011-07-31 00:00:00 0.0 76
USC00513117 2011-08-01 00:00:00 0.01 74
USC00513117 2011-08-02 00:00:00 0.0 74
USC00513117 2011-08-03 00:00:00 0.02 75
USC00513117 2011-08-04 00:00:00 0.03 74
USC00513117 2011-08-05 00:00:00 0.04 75
USC00513117 2011-08-06 00:00:00 0.04 74
USC00513117 2011-08-07 00:00:00 0.01 76
USC00513117 2011-08-08 00:00:00 0.0 75
USC00513117 2011-08-09 00:00:00 0.16 76
USC00513117 2011-08-10 00:00:00 0.0 75
USC00513117 2011-08-11 00:00:00 0.06 75
USC00513117 2011-08-12 00:00:00 0.0 75
USC00513117 2011-08-13 00:00:00 0.0 76
USC00513117 2011-08-14 00:00:00 0.04 75
USC00513117 2011-08-15 00:00:00 0.03 75
USC00513117 2011-08-16 00:00:00 0.05 74
USC00513117 2011-08-17 00:00:00 0.12 75
USC00513117 2011-08-18 00:00:00 0.02 75
USC00513117 2011-08-19 00:00:00 0.04 75
USC00513117 2011-08-20 00:00:00 0.0 76
USC00513117 2011-08-21 00:00:00 0.03 75
USC00513117 2011-08-22 00:00:00 0.28 72
USC00513117 2011-08-23 00:00:00 0.21 74
USC00513117 2011-08-24 00:00:00 0.06 75
USC00513117 2011-08-25 00:00:00 0.03 74
USC00513117 2011-08-26 00:00:00 0.08 74
USC00513117 2011-08-27 00:00:00 0.0 78
USC00513117 2011-08-28 00:00:00 0.09 74
USC00513117 2011-08-29 00:00:00 0.24 76
USC00513117 2011-08-30 00:00:00 0.16 74
USC00513117 2011-08-31 00:00:00 0.02 76
USC00513117 2011-09-01 00:00:00 0.13 78
USC00513117 2011-09-17 00:00:00 0.0 78
USC00513117 2011-09-18 00:00:00 0.05 76
USC00513117 2011-09-19 00:00:00 0.04 76
USC00513117 2011-09-20 00:00:00 0.03 75
USC00513117 2011-09-21 00:00:00 0.07 76
USC00513117 2011-09-22 00:00:00 0.1 75
USC00513117 2011-09-23 00:00:00 0.08 72
USC00513117 2011-09-24 00:00:00 0.0 78
USC00513117 2011-09-26 00:00:00 0.0 71
USC00513117 2011-09-27 00:00:00 0.0 76
USC00513117 2011-09-28 00:00:00 0.03 74
USC00513117 2011-09-29 00:00:00 0.02 76
USC00513117 2011-09-30 00:00:00 0.11 75
USC00513117 2011-10-01 00:00:00 0.0 76
USC00513117 2011-10-02 00:00:00 0.0 77
USC00513117 2011-10-03 00:00:00 0.0 77
USC00513117 2011-10-04 00:00:00 0.01 77
USC00513117 2011-10-05 00:00:00 0.07 77
USC00513117 2011-10-06 00:00:00 0.05 76

USC00513117 2011-10-07 00:00:00 0.11 72
USC00513117 2011-10-08 00:00:00 0.03 76
USC00513117 2011-10-09 00:00:00 0.07 76
USC00513117 2011-10-10 00:00:00 0.0 76
USC00513117 2011-10-11 00:00:00 0.04 75
USC00513117 2011-10-12 00:00:00 0.0 73
USC00513117 2011-10-13 00:00:00 0.11 74
USC00513117 2011-10-14 00:00:00 0.06 75
USC00513117 2011-10-15 00:00:00 0.15 75
USC00513117 2011-10-16 00:00:00 0.0 74
USC00513117 2011-10-17 00:00:00 0.03 71
USC00513117 2011-10-18 00:00:00 0.32 70
USC00513117 2011-10-19 00:00:00 0.08 68
USC00513117 2011-10-20 00:00:00 0.0 74
USC00513117 2011-10-21 00:00:00 0.0 76
USC00513117 2011-10-22 00:00:00 0.3 73
USC00513117 2011-10-23 00:00:00 1.56 72
USC00513117 2011-10-24 00:00:00 4.47 70
USC00513117 2011-10-25 00:00:00 0.01 75
USC00513117 2011-10-26 00:00:00 0.0 76
USC00513117 2011-10-27 00:00:00 0.04 70
USC00513117 2011-10-28 00:00:00 0.04 74
USC00513117 2011-10-29 00:00:00 0.05 77
USC00513117 2011-10-30 00:00:00 0.03 72
USC00513117 2011-10-31 00:00:00 0.33 71
USC00513117 2011-11-01 00:00:00 0.8 72
USC00513117 2011-11-02 00:00:00 0.1 73
USC00513117 2011-11-03 00:00:00 0.19 76
USC00513117 2011-11-04 00:00:00 0.62 75
USC00513117 2011-11-05 00:00:00 0.06 75
USC00513117 2011-11-06 00:00:00 0.01 76
USC00513117 2011-11-07 00:00:00 0.0 75
USC00513117 2011-11-08 00:00:00 0.05 74
USC00513117 2011-11-09 00:00:00 0.03 74
USC00513117 2011-11-10 00:00:00 0.04 74
USC00513117 2011-11-11 00:00:00 0.16 75
USC00513117 2011-11-12 00:00:00 0.07 73
USC00513117 2011-11-13 00:00:00 0.01 69
USC00513117 2011-11-14 00:00:00 0.0 71
USC00513117 2011-11-15 00:00:00 0.0 70
USC00513117 2011-11-16 00:00:00 0.0 74
USC00513117 2011-11-17 00:00:00 0.01 75
USC00513117 2011-11-18 00:00:00 0.04 74
USC00513117 2011-11-19 00:00:00 0.03 74
USC00513117 2011-11-20 00:00:00 0.02 74
USC00513117 2011-11-21 00:00:00 0.38 74
USC00513117 2011-11-22 00:00:00 0.03 74
USC00513117 2011-11-23 00:00:00 0.08 74
USC00513117 2011-11-24 00:00:00 0.0 73
USC00513117 2011-11-25 00:00:00 0.05 71
USC00513117 2011-11-26 00:00:00 0.0 74
USC00513117 2011-11-27 00:00:00 0.07 72
USC00513117 2011-11-28 00:00:00 0.0 71
USC00513117 2011-11-29 00:00:00 0.03 72
USC00513117 2011-11-30 00:00:00 0.36 66
USC00513117 2011-12-01 00:00:00 0.11 69
USC00513117 2011-12-02 00:00:00 0.14 68
USC00513117 2011-12-03 00:00:00 0.03 74
USC00513117 2011-12-04 00:00:00 0.01 73
USC00513117 2011-12-05 00:00:00 0.0 73
USC00513117 2011-12-06 00:00:00 0.0 72
USC00513117 2011-12-07 00:00:00 0.04 71
USC00513117 2011-12-08 00:00:00 0.08 71
USC00513117 2011-12-09 00:00:00 0.07 68
USC00513117 2011-12-10 00:00:00 0.11 72
USC00513117 2011-12-11 00:00:00 0.76 71
USC00513117 2011-12-12 00:00:00 0.58 72
USC00513117 2011-12-13 00:00:00 1.55 71
USC00513117 2011-12-14 00:00:00 0.05 71
USC00513117 2011-12-15 00:00:00 0.02 72
USC00513117 2011-12-16 00:00:00 0.0 71
USC00513117 2011-12-17 00:00:00 0.02 71
USC00513117 2011-12-18 00:00:00 0.11 72
USC00513117 2011-12-19 00:00:00 0.05 72
USC00513117 2011-12-20 00:00:00 0.02 72
USC00513117 2011-12-21 00:00:00 0.24 69
USC00513117 2011-12-22 00:00:00 0.06 71
USC00513117 2011-12-23 00:00:00 0.02 71
USC00513117 2011-12-24 00:00:00 0.02 69
USC00513117 2011-12-25 00:00:00 0.05 74
USC00513117 2011-12-26 00:00:00 0.0 72
USC00513117 2011-12-27 00:00:00 0.0 71
USC00513117 2011-12-28 00:00:00 0.03 71
USC00513117 2011-12-29 00:00:00 0.01 72
USC00513117 2011-12-30 00:00:00 0.02 71
USC00513117 2011-12-31 00:00:00 0.04 67
USC00513117 2012-01-01 00:00:00 0.01 67
USC00513117 2012-01-02 00:00:00 0.04 65
USC00513117 2012-01-03 00:00:00 0.0 66
USC00513117 2012-01-04 00:00:00 0.0 71
USC00513117 2012-01-05 00:00:00 0.01 72
USC00513117 2012-01-06 00:00:00 0.0 72
USC00513117 2012-01-07 00:00:00 0.0 74
USC00513117 2012-01-08 00:00:00 0.0 65
USC00513117 2012-01-09 00:00:00 0.01 71
USC00513117 2012-01-10 00:00:00 0.01 71
USC00513117 2012-01-11 00:00:00 0.05 68
USC00513117 2012-01-12 00:00:00 0.04 66
USC00513117 2012-01-13 00:00:00 0.0 69
USC00513117 2012-01-14 00:00:00 0.0 64
USC00513117 2012-01-15 00:00:00 0.0 74
USC00513117 2012-01-16 00:00:00 0.2 76
USC00513117 2012-01-17 00:00:00 0.06 76
USC00513117 2012-01-19 00:00:00 0.0 70
USC00513117 2012-01-20 00:00:00 0.0 72
USC00513117 2012-01-21 00:00:00 0.01 72
USC00513117 2012-01-22 00:00:00 0.0 73
USC00513117 2012-01-23 00:00:00 0.03 65
USC00513117 2012-01-24 00:00:00 0.0 65
USC00513117 2012-01-25 00:00:00 0.02 73
USC00513117 2012-01-26 00:00:00 0.0 73
USC00513117 2012-01-27 00:00:00 0.1 69
USC00513117 2012-01-28 00:00:00 0.0 73
USC00513117 2012-01-29 00:00:00 0.01 73
USC00513117 2012-01-30 00:00:00 0.06 71
USC00513117 2012-01-31 00:00:00 0.01 71
USC00513117 2012-02-01 00:00:00 0.0 66
USC00513117 2012-02-02 00:00:00 0.0 70
USC00513117 2012-02-03 00:00:00 0.0 63
USC00513117 2012-02-04 00:00:00 0.0 66
USC00513117 2012-02-05 00:00:00 0.0 69
USC00513117 2012-02-06 00:00:00 0.04 66
USC00513117 2012-02-07 00:00:00 0.28 70
USC00513117 2012-02-08 00:00:00 0.5 63
USC00513117 2012-02-09 00:00:00 0.0 66
USC00513117 2012-02-10 00:00:00 0.0 69
USC00513117 2012-02-11 00:00:00 0.01 71
USC00513117 2012-02-12 00:00:00 0.0 71
USC00513117 2012-02-13 00:00:00 0.01 71
USC00513117 2012-02-14 00:00:00 0.0 66
USC00513117 2012-02-15 00:00:00 0.0 67
USC00513117 2012-02-16 00:00:00 0.0 71
USC00513117 2012-02-17 00:00:00 0.12 71
USC00513117 2012-02-18 00:00:00 0.01 70
USC00513117 2012-02-19 00:00:00 0.07 69
USC00513117 2012-02-20 00:00:00 0.01 71
USC00513117 2012-02-21 00:00:00 0.0 71
USC00513117 2012-02-22 00:00:00 0.05 71
USC00513117 2012-02-23 00:00:00 0.04 71
USC00513117 2012-02-24 00:00:00 0.0 69
USC00513117 2012-02-25 00:00:00 0.01 68
USC00513117 2012-02-26 00:00:00 0.23 72
USC00513117 2012-02-27 00:00:00 0.0 71
USC00513117 2012-02-28 00:00:00 0.0 71
USC00513117 2012-02-29 00:00:00 0.0 72
USC00513117 2012-03-01 00:00:00 0.0 72
USC00513117 2012-03-02 00:00:00 0.0 67
USC00513117 2012-03-03 00:00:00 0.05 70
USC00513117 2012-03-04 00:00:00 0.03 70
USC00513117 2012-03-05 00:00:00 5.71 65
USC00513117 2012-03-06 00:00:00 2.33 67
USC00513117 2012-03-07 00:00:00 2.41 66
USC00513117 2012-03-08 00:00:00 0.59 67
USC00513117 2012-03-09 00:00:00 4.6 61
USC00513117 2012-03-10 00:00:00 0.4 72
USC00513117 2012-03-11 00:00:00 0.07 74
USC00513117 2012-03-12 00:00:00 0.1 70
USC00513117 2012-03-13 00:00:00 0.0 69
USC00513117 2012-03-14 00:00:00 0.0 70
USC00513117 2012-03-15 00:00:00 0.03 69
USC00513117 2012-03-16 00:00:00 0.01 70
USC00513117 2012-03-17 00:00:00 0.0 75
USC00513117 2012-03-18 00:00:00 0.05 68
USC00513117 2012-03-19 00:00:00 0.07 71
USC00513117 2012-03-20 00:00:00 0.0 65
USC00513117 2012-03-21 00:00:00 0.23 70
USC00513117 2012-03-22 00:00:00 0.13 70
USC00513117 2012-03-23 00:00:00 0.0 70
USC00513117 2012-03-24 00:00:00 0.06 71
USC00513117 2012-03-25 00:00:00 0.03 70
USC00513117 2012-03-26 00:00:00 0.03 70
USC00513117 2012-03-27 00:00:00 0.12 67
USC00513117 2012-03-28 00:00:00 0.01 69
USC00513117 2012-03-29 00:00:00 0.0 68
USC00513117 2012-03-30 00:00:00 0.0 71
USC00513117 2012-03-31 00:00:00 0.0 71
USC00513117 2012-04-01 00:00:00 0.0 75
USC00513117 2012-04-02 00:00:00 0.0 69
USC00513117 2012-04-03 00:00:00 0.0 71
USC00513117 2012-04-04 00:00:00 0.03 71
USC00513117 2012-04-05 00:00:00 0.02 72
USC00513117 2012-04-06 00:00:00 0.0 71
USC00513117 2012-04-07 00:00:00 0.15 72
USC00513117 2012-04-08 00:00:00 0.0 70
USC00513117 2012-04-09 00:00:00 0.11 69
USC00513117 2012-04-10 00:00:00 0.03 67
USC00513117 2012-04-11 00:00:00 0.17 70
USC00513117 2012-04-12 00:00:00 0.03 70
USC00513117 2012-04-13 00:00:00 0.02 66
USC00513117 2012-04-14 00:00:00 0.0 69
USC00513117 2012-04-15 00:00:00 0.05 70
USC00513117 2012-04-16 00:00:00 0.04 71
USC00513117 2012-04-17 00:00:00 0.0 72
USC00513117 2012-04-18 00:00:00 0.0 72
USC00513117 2012-04-19 00:00:00 0.0 72
USC00513117 2012-04-20 00:00:00 0.02 70
USC00513117 2012-04-21 00:00:00 0.02 70
USC00513117 2012-04-22 00:00:00 0.03 70
USC00513117 2012-04-23 00:00:00 0.11 70
USC00513117 2012-04-24 00:00:00 0.02 70
USC00513117 2012-04-25 00:00:00 0.02 69
USC00513117 2012-04-26 00:00:00 0.02 71
USC00513117 2012-04-27 00:00:00 0.28 68
USC00513117 2012-04-28 00:00:00 0.0 75
USC00513117 2012-04-29 00:00:00 0.0 71
USC00513117 2012-04-30 00:00:00 0.0 71
USC00513117 2012-05-01 00:00:00 0.02 71
USC00513117 2012-05-02 00:00:00 0.13 70
USC00513117 2012-05-03 00:00:00 0.11 70
USC00513117 2012-05-04 00:00:00 0.06 69
USC00513117 2012-05-05 00:00:00 0.1 71
USC00513117 2012-05-06 00:00:00 0.0 78
USC00513117 2012-05-07 00:00:00 0.05 71
USC00513117 2012-05-08 00:00:00 0.0 71
USC00513117 2012-05-09 00:00:00 0.0 71
USC00513117 2012-05-10 00:00:00 0.0 70
USC00513117 2012-05-11 00:00:00 0.04 70
USC00513117 2012-05-12 00:00:00 0.0 70
USC00513117 2012-05-13 00:00:00 0.0 67
USC00513117 2012-05-14 00:00:00 0.0 65
USC00513117 2012-05-15 00:00:00 0.0 67
USC00513117 2012-05-16 00:00:00 0.0 70
USC00513117 2012-05-17 00:00:00 0.02 73
USC00513117 2012-05-18 00:00:00 0.0 73
USC00513117 2012-05-19 00:00:00 0.0 74
USC00513117 2012-05-20 00:00:00 0.03 72
USC00513117 2012-05-21 00:00:00 0.17 72
USC00513117 2012-05-22 00:00:00 0.0 74
USC00513117 2012-05-23 00:00:00 0.0 73
USC00513117 2012-05-24 00:00:00 0.07 73
USC00513117 2012-05-25 00:00:00 0.0 73
USC00513117 2012-05-26 00:00:00 0.04 70
USC00513117 2012-05-27 00:00:00 0.02 73
USC00513117 2012-05-28 00:00:00 0.01 74
USC00513117 2012-05-29 00:00:00 0.0 72
USC00513117 2012-05-30 00:00:00 0.0 72
USC00513117 2012-05-31 00:00:00 0.05 72
USC00513117 2012-06-01 00:00:00 0.08 71
USC00513117 2012-06-02 00:00:00 0.03 71
USC00513117 2012-06-03 00:00:00 0.0 75
USC00513117 2012-06-04 00:00:00 0.0 72
USC00513117 2012-06-05 00:00:00 0.0 72
USC00513117 2012-06-06 00:00:00 0.03 73
USC00513117 2012-06-07 00:00:00 0.0 73
USC00513117 2012-06-08 00:00:00 0.0 73
USC00513117 2012-06-09 00:00:00 0.0 74
USC00513117 2012-06-10 00:00:00 0.0 73
USC00513117 2012-06-11 00:00:00 0.04 72
USC00513117 2012-06-12 00:00:00 0.02 72
USC00513117 2012-06-13 00:00:00 0.05 70

USC00513117 2012-06-14 00:00:00 0.08 72
USC00513117 2012-06-15 00:00:00 0.0 72
USC00513117 2012-06-16 00:00:00 0.0 72
USC00513117 2012-06-17 00:00:00 0.02 74
USC00513117 2012-06-18 00:00:00 0.0 73
USC00513117 2012-06-19 00:00:00 0.01 73
USC00513117 2012-06-20 00:00:00 0.14 70
USC00513117 2012-06-21 00:00:00 0.02 73
USC00513117 2012-06-22 00:00:00 0.01 72
USC00513117 2012-06-23 00:00:00 0.28 73
USC00513117 2012-06-24 00:00:00 0.27 69
USC00513117 2012-06-25 00:00:00 0.04 72
USC00513117 2012-06-26 00:00:00 0.22 71
USC00513117 2012-06-27 00:00:00 0.23 71
USC00513117 2012-06-28 00:00:00 0.0 73
USC00513117 2012-06-29 00:00:00 0.06 73
USC00513117 2012-06-30 00:00:00 0.0 72
USC00513117 2012-07-01 00:00:00 0.07 72
USC00513117 2012-07-02 00:00:00 0.05 71
USC00513117 2012-07-03 00:00:00 0.13 72
USC00513117 2012-07-04 00:00:00 0.13 71
USC00513117 2012-07-05 00:00:00 0.04 72
USC00513117 2012-07-06 00:00:00 0.11 73
USC00513117 2012-07-07 00:00:00 0.06 74
USC00513117 2012-07-08 00:00:00 0.01 73
USC00513117 2012-07-09 00:00:00 0.0 73
USC00513117 2012-07-10 00:00:00 0.01 73
USC00513117 2012-07-11 00:00:00 0.02 73
USC00513117 2012-07-12 00:00:00 0.0 73
USC00513117 2012-07-13 00:00:00 0.18 73
USC00513117 2012-07-14 00:00:00 0.08 75
USC00513117 2012-07-15 00:00:00 0.0 75
USC00513117 2012-07-16 00:00:00 0.08 73
USC00513117 2012-07-17 00:00:00 0.11 73
USC00513117 2012-07-18 00:00:00 0.03 74
USC00513117 2012-07-19 00:00:00 0.12 73
USC00513117 2012-07-20 00:00:00 0.8 70
USC00513117 2012-07-21 00:00:00 0.04 75
USC00513117 2012-07-22 00:00:00 0.0 74
USC00513117 2012-07-23 00:00:00 0.03 74
USC00513117 2012-07-24 00:00:00 0.0 74
USC00513117 2012-07-25 00:00:00 0.01 74
USC00513117 2012-07-26 00:00:00 0.01 73
USC00513117 2012-07-27 00:00:00 0.0 73
USC00513117 2012-07-28 00:00:00 0.43 75
USC00513117 2012-07-29 00:00:00 0.09 74
USC00513117 2012-07-30 00:00:00 0.08 74
USC00513117 2012-07-31 00:00:00 0.03 73
USC00513117 2012-08-01 00:00:00 0.0 75
USC00513117 2012-08-02 00:00:00 0.0 73
USC00513117 2012-08-03 00:00:00 0.0 74
USC00513117 2012-08-04 00:00:00 0.0 74
USC00513117 2012-08-05 00:00:00 0.1 74
USC00513117 2012-08-06 00:00:00 0.1 73
USC00513117 2012-08-07 00:00:00 0.02 74
USC00513117 2012-08-08 00:00:00 0.04 74
USC00513117 2012-08-09 00:00:00 0.02 75
USC00513117 2012-08-10 00:00:00 0.0 73
USC00513117 2012-08-11 00:00:00 0.02 72
USC00513117 2012-08-12 00:00:00 0.08 76
USC00513117 2012-08-13 00:00:00 0.06 75
USC00513117 2012-08-14 00:00:00 0.06 72
USC00513117 2012-08-15 00:00:00 0.01 75
USC00513117 2012-08-16 00:00:00 0.0 75
USC00513117 2012-08-17 00:00:00 0.0 75
USC00513117 2012-08-20 00:00:00 0.01 75
USC00513117 2012-08-21 00:00:00 0.03 74
USC00513117 2012-08-22 00:00:00 0.02 73
USC00513117 2012-08-23 00:00:00 0.03 75
USC00513117 2012-08-24 00:00:00 0.0 75
USC00513117 2012-08-25 00:00:00 0.0 75
USC00513117 2012-08-26 00:00:00 0.02 74
USC00513117 2012-08-27 00:00:00 0.0 75
USC00513117 2012-08-28 00:00:00 0.06 74
USC00513117 2012-08-29 00:00:00 0.08 72
USC00513117 2012-08-30 00:00:00 0.06 74
USC00513117 2012-08-31 00:00:00 0.04 76
USC00513117 2012-09-01 00:00:00 0.02 74
USC00513117 2012-09-02 00:00:00 0.08 72
USC00513117 2012-09-03 00:00:00 0.09 75
USC00513117 2012-09-04 00:00:00 0.0 74
USC00513117 2012-09-05 00:00:00 0.02 74
USC00513117 2012-09-06 00:00:00 0.02 74
USC00513117 2012-09-07 00:00:00 0.07 77
USC00513117 2012-09-08 00:00:00 0.14 74
USC00513117 2012-09-09 00:00:00 0.07 75
USC00513117 2012-09-10 00:00:00 0.0 75
USC00513117 2012-09-11 00:00:00 0.18 74
USC00513117 2012-09-12 00:00:00 0.04 74
USC00513117 2012-09-13 00:00:00 0.07 74
USC00513117 2012-09-14 00:00:00 0.04 75
USC00513117 2012-09-15 00:00:00 0.02 72
USC00513117 2012-09-16 00:00:00 0.0 72
USC00513117 2012-09-17 00:00:00 0.04 74
USC00513117 2012-09-18 00:00:00 0.0 73
USC00513117 2012-09-19 00:00:00 0.25 72
USC00513117 2012-09-20 00:00:00 0.55 71
USC00513117 2012-09-23 00:00:00 0.02 74
USC00513117 2012-09-24 00:00:00 0.07 75
USC00513117 2012-09-25 00:00:00 0.01 74
USC00513117 2012-09-26 00:00:00 0.0 74
USC00513117 2012-09-27 00:00:00 0.05 80
USC00513117 2012-09-28 00:00:00 0.01 75
USC00513117 2012-09-29 00:00:00 0.01 74
USC00513117 2012-09-30 00:00:00 0.0 73
USC00513117 2012-10-01 00:00:00 0.01 70
USC00513117 2012-10-02 00:00:00 0.0 72
USC00513117 2012-10-03 00:00:00 0.0 72
USC00513117 2012-10-04 00:00:00 0.0 73
USC00513117 2012-10-05 00:00:00 0.0 70
USC00513117 2012-10-06 00:00:00 0.0 71
USC00513117 2012-10-07 00:00:00 0.0 75
USC00513117 2012-10-08 00:00:00 0.04 75
USC00513117 2012-10-09 00:00:00 0.0 74
USC00513117 2012-10-10 00:00:00 0.0 72
USC00513117 2012-10-11 00:00:00 0.22 75
USC00513117 2012-10-12 00:00:00 0.0 74
USC00513117 2012-10-13 00:00:00 0.0 75
USC00513117 2012-10-14 00:00:00 0.07 74
USC00513117 2012-10-15 00:00:00 0.09 75
USC00513117 2012-10-16 00:00:00 0.07 73
USC00513117 2012-10-17 00:00:00 0.0 69
USC00513117 2012-10-18 00:00:00 0.0 70
USC00513117 2012-10-19 00:00:00 0.08 74
USC00513117 2012-10-20 00:00:00 0.0 74
USC00513117 2012-10-21 00:00:00 0.0 75
USC00513117 2012-10-22 00:00:00 0.0 75
USC00513117 2012-10-23 00:00:00 0.02 75
USC00513117 2012-10-24 00:00:00 0.01 73
USC00513117 2012-10-25 00:00:00 0.16 73
USC00513117 2012-10-26 00:00:00 0.0 72
USC00513117 2012-10-27 00:00:00 0.0 71
USC00513117 2012-10-28 00:00:00 0.02 74
USC00513117 2012-10-29 00:00:00 0.04 73
USC00513117 2012-10-30 00:00:00 0.01 74
USC00513117 2012-10-31 00:00:00 0.03 72
USC00513117 2012-11-01 00:00:00 0.0 67
USC00513117 2012-11-02 00:00:00 0.0 67
USC00513117 2012-11-03 00:00:00 0.0 74
USC00513117 2012-11-04 00:00:00 0.0 68
USC00513117 2012-11-05 00:00:00 0.0 69
USC00513117 2012-11-06 00:00:00 0.0 74
USC00513117 2012-11-07 00:00:00 0.07 74
USC00513117 2012-11-08 00:00:00 0.03 73
USC00513117 2012-11-09 00:00:00 0.03 74
USC00513117 2012-11-10 00:00:00 0.02 74
USC00513117 2012-11-11 00:00:00 0.0 74
USC00513117 2012-11-12 00:00:00 0.0 74
USC00513117 2012-11-13 00:00:00 0.08 73
USC00513117 2012-11-14 00:00:00 0.07 74
USC00513117 2012-11-15 00:00:00 0.05 73
USC00513117 2012-11-16 00:00:00 0.13 72
USC00513117 2012-11-17 00:00:00 0.03 73
USC00513117 2012-11-18 00:00:00 0.06 72
USC00513117 2012-11-19 00:00:00 0.06 76
USC00513117 2012-11-20 00:00:00 0.0 73
USC00513117 2012-11-21 00:00:00 0.01 71
USC00513117 2012-11-22 00:00:00 0.88 67
USC00513117 2012-11-23 00:00:00 0.0 68
USC00513117 2012-11-24 00:00:00 0.02 77
USC00513117 2012-11-25 00:00:00 0.0 69
USC00513117 2012-11-26 00:00:00 0.03 72
USC00513117 2012-11-27 00:00:00 0.0 71
USC00513117 2012-11-28 00:00:00 0.0 69
USC00513117 2012-11-29 00:00:00 0.0 65
USC00513117 2012-11-30 00:00:00 0.0 65
USC00513117 2012-12-01 00:00:00 0.0 65
USC00513117 2012-12-02 00:00:00 0.0 70
USC00513117 2012-12-03 00:00:00 0.0 76
USC00513117 2012-12-04 00:00:00 0.18 68
USC00513117 2012-12-05 00:00:00 0.07 71
USC00513117 2012-12-06 00:00:00 0.0 71
USC00513117 2012-12-07 00:00:00 0.0 68
USC00513117 2012-12-08 00:00:00 0.0 70
USC00513117 2012-12-09 00:00:00 0.0 73
USC00513117 2012-12-10 00:00:00 0.03 73
USC00513117 2012-12-11 00:00:00 0.0 72
USC00513117 2012-12-12 00:00:00 0.07 71
USC00513117 2012-12-13 00:00:00 0.1 70
USC00513117 2012-12-14 00:00:00 0.08 72
USC00513117 2012-12-15 00:00:00 0.1 71
USC00513117 2012-12-16 00:00:00 0.04 72
USC00513117 2012-12-17 00:00:00 0.02 72
USC00513117 2012-12-18 00:00:00 0.2 71
USC00513117 2012-12-19 00:00:00 0.24 70
USC00513117 2012-12-20 00:00:00 0.08 71
USC00513117 2012-12-21 00:00:00 0.06 71
USC00513117 2012-12-22 00:00:00 0.07 71
USC00513117 2012-12-23 00:00:00 0.02 66
USC00513117 2012-12-24 00:00:00 0.0 65
USC00513117 2012-12-25 00:00:00 0.0 73
USC00513117 2012-12-26 00:00:00 0.01 72
USC00513117 2012-12-27 00:00:00 0.0 72
USC00513117 2012-12-28 00:00:00 0.0 65
USC00513117 2012-12-29 00:00:00 0.0 65
USC00513117 2012-12-30 00:00:00 0.21 68
USC00513117 2012-12-31 00:00:00 0.17 67
USC00513117 2013-01-01 00:00:00 0.16 71
USC00513117 2013-01-02 00:00:00 0.07 69
USC00513117 2013-01-03 00:00:00 0.23 68
USC00513117 2013-01-04 00:00:00 0.06 71
USC00513117 2013-01-05 00:00:00 0.08 71
USC00513117 2013-01-06 00:00:00 0.19 71
USC00513117 2013-01-07 00:00:00 0.04 71
USC00513117 2013-01-08 00:00:00 0.04 70
USC00513117 2013-01-09 00:00:00 0.16 70
USC00513117 2013-01-10 00:00:00 0.05 71
USC00513117 2013-01-11 00:00:00 0.0 71
USC00513117 2013-01-14 00:00:00 0.0 74
USC00513117 2013-01-15 00:00:00 1.27 64
USC00513117 2013-01-16 00:00:00 0.0 60
USC00513117 2013-01-17 00:00:00 0.1 62
USC00513117 2013-01-18 00:00:00 0.0 62
USC00513117 2013-01-19 00:00:00 0.0 67
USC00513117 2013-01-20 00:00:00 0.0 68
USC00513117 2013-01-21 00:00:00 0.0 70
USC00513117 2013-01-22 00:00:00 0.0 70
USC00513117 2013-01-23 00:00:00 0.0 70
USC00513117 2013-01-24 00:00:00 0.71 67
USC00513117 2013-01-25 00:00:00 0.59 64
USC00513117 2013-01-26 00:00:00 0.0 65
USC00513117 2013-01-27 00:00:00 0.03 74
USC00513117 2013-01-28 00:00:00 2.6 64
USC00513117 2013-01-29 00:00:00 0.71 65
USC00513117 2013-01-30 00:00:00 0.0 64
USC00513117 2013-01-31 00:00:00 0.0 70
USC00513117 2013-02-01 00:00:00 0.0 69
USC00513117 2013-02-02 00:00:00 0.0 70
USC00513117 2013-02-03 00:00:00 0.0 67
USC00513117 2013-02-04 00:00:00 0.0 70
USC00513117 2013-02-05 00:00:00 0.0 70
USC00513117 2013-02-06 00:00:00 0.0 70
USC00513117 2013-02-07 00:00:00 0.16 70
USC00513117 2013-02-08 00:00:00 0.01 70
USC00513117 2013-02-09 00:00:00 0.0 69
USC00513117 2013-02-10 00:00:00 0.02 70
USC00513117 2013-02-11 00:00:00 0.07 69
USC00513117 2013-02-12 00:00:00 0.02 68
USC00513117 2013-02-13 00:00:00 0.02 68
USC00513117 2013-02-14 00:00:00 0.0 68
USC00513117 2013-02-15 00:00:00 0.0 69
USC00513117 2013-02-16 00:00:00 0.04 70
USC00513117 2013-02-17 00:00:00 0.0 68
USC00513117 2013-02-18 00:00:00 0.0 70
USC00513117 2013-02-19 00:00:00 0.12 69
USC00513117 2013-02-20 00:00:00 0.11 70
USC00513117 2013-02-21 00:00:00 0.05 69
USC00513117 2013-02-22 00:00:00 0.83 69
USC00513117 2013-02-23 00:00:00 0.23 69
USC00513117 2013-02-24 00:00:00 0.09 69
USC00513117 2013-02-25 00:00:00 0.02 68
USC00513117 2013-02-26 00:00:00 0.08 69
USC00513117 2013-02-27 00:00:00 0.03 70
USC00513117 2013-02-28 00:00:00 0.0 70
USC00513117 2013-03-01 00:00:00 0.0 69
USC00513117 2013-03-02 00:00:00 0.0 70
USC00513117 2013-03-03 00:00:00 0.0 70
USC00513117 2013-03-04 00:00:00 0.0 70
USC00513117 2013-03-05 00:00:00 0.0 70
USC00513117 2013-03-06 00:00:00 0.02 69
USC00513117 2013-03-07 00:00:00 0.06 66
USC00513117 2013-03-08 00:00:00 0.15 61
USC00513117 2013-03-09 00:00:00 0.1 70
USC00513117 2013-03-10 00:00:00 1.69 68
USC00513117 2013-03-11 00:00:00 0.8 62
USC00513117 2013-03-12 00:00:00 0.01 66
USC00513117 2013-03-13 00:00:00 0.03 64
USC00513117 2013-03-14 00:00:00 0.0 66
USC00513117 2013-03-15 00:00:00 0.0 62
USC00513117 2013-03-16 00:00:00 0.0 74
USC00513117 2013-03-17 00:00:00 0.0 63
USC00513117 2013-03-18 00:00:00 0.49 59
USC00513117 2013-03-19 00:00:00 0.0 63
USC00513117 2013-03-20 00:00:00 0.0 63
USC00513117 2013-03-21 00:00:00 0.0 76
USC00513117 2013-03-22 00:00:00 0.0 73
USC00513117 2013-03-23 00:00:00 0.11 66
USC00513117 2013-03-24 00:00:00 0.43 70
USC00513117 2013-03-25 00:00:00 0.8 67
USC00513117 2013-03-26 00:00:00 0.03 67
USC00513117 2013-03-27 00:00:00 0.0 70
USC00513117 2013-03-28 00:00:00 0.07 69
USC00513117 2013-03-29 00:00:00 0.07 69
USC00513117 2013-03-30 00:00:00 0.05 69
USC00513117 2013-03-31 00:00:00 0.02 64
USC00513117 2013-04-01 00:00:00 0.0 63
USC00513117 2013-04-02 00:00:00 0.0 63
USC00513117 2013-04-03 00:00:00 0.02 64
USC00513117 2013-04-04 00:00:00 0.07 65
USC00513117 2013-04-05 00:00:00 0.0 70
USC00513117 2013-04-06 00:00:00 0.0 72
USC00513117 2013-04-07 00:00:00 0.01 73
USC00513117 2013-04-08 00:00:00 0.0 71
USC00513117 2013-04-09 00:00:00 0.02 71
USC00513117 2013-04-10 00:00:00 0.03 71
USC00513117 2013-04-11 00:00:00 0.01 68
USC00513117 2013-04-12 00:00:00 0.0 73
USC00513117 2013-04-13 00:00:00 0.01 70
USC00513117 2013-04-14 00:00:00 0.0 75
USC00513117 2013-04-15 00:00:00 0.43 69
USC00513117 2013-04-16 00:00:00 0.19 65
USC00513117 2013-04-17 00:00:00 0.0 72
USC00513117 2013-04-18 00:00:00 0.0 72
USC00513117 2013-04-19 00:00:00 0.03 71
USC00513117 2013-04-20 00:00:00 0.11 77
USC00513117 2013-04-21 00:00:00 0.0 71
USC00513117 2013-04-22 00:00:00 0.44 70
USC00513117 2013-04-23 00:00:00 0.37 74
USC00513117 2013-04-24 00:00:00 0.76 67
USC00513117 2013-04-25 00:00:00 0.94 70
USC00513117 2013-04-26 00:00:00 0.0 72
USC00513117 2013-04-27 00:00:00 0.0 70
USC00513117 2013-04-28 00:00:00 0.0 68
USC00513117 2013-04-29 00:00:00 0.0 74
USC00513117 2013-04-30 00:00:00 0.0 70
USC00513117 2013-05-01 00:00:00 0.04 73
USC00513117 2013-05-02 00:00:00 0.0 73
USC00513117 2013-05-03 00:00:00 0.0 72
USC00513117 2013-05-04 00:00:00 0.0 70
USC00513117 2013-05-05 00:00:00 1.05 72
USC00513117 2013-05-06 00:00:00 0.09 69
USC00513117 2013-05-07 00:00:00 0.0 66
USC00513117 2013-05-08 00:00:00 0.0 69
USC00513117 2013-05-09 00:00:00 0.0 70
USC00513117 2013-05-10 00:00:00 0.1 70
USC00513117 2013-05-11 00:00:00 0.09 74
USC00513117 2013-05-12 00:00:00 0.22 68
USC00513117 2013-05-13 00:00:00 0.95 73
USC00513117 2013-05-14 00:00:00 0.01 73
USC00513117 2013-05-15 00:00:00 0.0 74
USC00513117 2013-05-16 00:00:00 0.0 74
USC00513117 2013-05-17 00:00:00 0.0 74
USC00513117 2013-05-18 00:00:00 0.0 79
USC00513117 2013-05-19 00:00:00 0.02 69
USC00513117 2013-05-20 00:00:00 0.54 68
USC00513117 2013-05-21 00:00:00 0.0 66
USC00513117 2013-05-22 00:00:00 0.0 69
USC00513117 2013-05-23 00:00:00 0.0 73
USC00513117 2013-05-24 00:00:00 0.0 75
USC00513117 2013-05-25 00:00:00 0.12 74
USC00513117 2013-05-26 00:00:00 0.18 75
USC00513117 2013-05-27 00:00:00 0.02 74
USC00513117 2013-05-28 00:00:00 0.06 73
USC00513117 2013-05-29 00:00:00 0.21 71
USC00513117 2013-05-30 00:00:00 0.74 77
USC00513117 2013-05-31 00:00:00 0.04 74
USC00513117 2013-06-01 00:00:00 0.05 75
USC00513117 2013-06-02 00:00:00 0.02 75
USC00513117 2013-06-03 00:00:00 0.02 75
USC00513117 2013-06-04 00:00:00 0.0 75
USC00513117 2013-06-05 00:00:00 0.0 74
USC00513117 2013-06-06 00:00:00 0.03 74
USC00513117 2013-06-07 00:00:00 0.0 74
USC00513117 2013-06-08 00:00:00 0.0 75
USC00513117 2013-06-09 00:00:00 0.0 75
USC00513117 2013-06-10 00:00:00 0.02 74
USC00513117 2013-06-11 00:00:00 0.0 75
USC00513117 2013-06-12 00:00:00 0.0 75
USC00513117 2013-06-13 00:00:00 0.02 74
USC00513117 2013-06-14 00:00:00 0.08 72
USC00513117 2013-06-15 00:00:00 0.01 74
USC00513117 2013-06-16 00:00:00 0.0 74
USC00513117 2013-06-17 00:00:00 0.01 74
USC00513117 2013-06-18 00:00:00 0.02 74
USC00513117 2013-06-19 00:00:00 0.0 74
USC00513117 2013-06-20 00:00:00 0.0 72
USC00513117 2013-06-21 00:00:00 0.22 70
USC00513117 2013-06-22 00:00:00 0.27 75
USC00513117 2013-06-23 00:00:00 0.03 74
USC00513117 2013-06-24 00:00:00 0.02 71
USC00513117 2013-06-25 00:00:00 0.05 71
USC00513117 2013-06-26 00:00:00 1.0 70
USC00513117 2013-06-27 00:00:00 0.1 73
USC00513117 2013-06-28 00:00:00 0.02 71
USC00513117 2013-06-29 00:00:00 0.22 71

USC00513117 2013-06-30 00:00:00 0.01 77
USC00513117 2013-07-02 00:00:00 0.02 75
USC00513117 2013-07-03 00:00:00 0.18 72
USC00513117 2013-07-04 00:00:00 0.01 75
USC00513117 2013-07-05 00:00:00 0.0 69
USC00513117 2013-07-06 00:00:00 0.0 72
USC00513117 2013-07-07 00:00:00 0.0 78
USC00513117 2013-07-08 00:00:00 0.03 75
USC00513117 2013-07-09 00:00:00 0.0 76
USC00513117 2013-07-10 00:00:00 0.15 75
USC00513117 2013-07-11 00:00:00 0.05 74
USC00513117 2013-07-12 00:00:00 0.06 74
USC00513117 2013-07-13 00:00:00 0.01 75
USC00513117 2013-07-14 00:00:00 0.0 77
USC00513117 2013-07-15 00:00:00 0.0 73
USC00513117 2013-07-16 00:00:00 0.0 75
USC00513117 2013-07-17 00:00:00 0.0 77
USC00513117 2013-07-18 00:00:00 0.03 75
USC00513117 2013-07-19 00:00:00 0.05 74
USC00513117 2013-07-20 00:00:00 0.05 75
USC00513117 2013-07-21 00:00:00 0.01 79
USC00513117 2013-07-22 00:00:00 0.3 74
USC00513117 2013-07-23 00:00:00 0.83 73
USC00513117 2013-07-24 00:00:00 0.0 76
USC00513117 2013-07-25 00:00:00 0.0 75
USC00513117 2013-07-26 00:00:00 0.0 75
USC00513117 2013-07-29 00:00:00 0.16 75
USC00513117 2013-07-30 00:00:00 0.08 78
USC00513117 2013-07-31 00:00:00 0.08 76
USC00513117 2013-08-01 00:00:00 0.06 75
USC00513117 2013-08-02 00:00:00 0.0 76
USC00513117 2013-08-03 00:00:00 0.04 77
USC00513117 2013-08-04 00:00:00 0.03 78
USC00513117 2013-08-05 00:00:00 0.02 76
USC00513117 2013-08-06 00:00:00 0.0 76
USC00513117 2013-08-07 00:00:00 0.0 81
USC00513117 2013-08-08 00:00:00 0.0 75
USC00513117 2013-08-09 00:00:00 0.01 72
USC00513117 2013-08-10 00:00:00 1.9 72
USC00513117 2013-08-11 00:00:00 1.09 76
USC00513117 2013-08-12 00:00:00 0.03 76
USC00513117 2013-08-13 00:00:00 0.0 76
USC00513117 2013-08-14 00:00:00 0.05 76
USC00513117 2013-08-15 00:00:00 0.0 76
USC00513117 2013-08-16 00:00:00 0.07 75
USC00513117 2013-08-17 00:00:00 0.0 77
USC00513117 2013-08-18 00:00:00 0.0 77
USC00513117 2013-08-19 00:00:00 0.0 74
USC00513117 2013-08-20 00:00:00 0.0 73
USC00513117 2013-08-21 00:00:00 0.57 73
USC00513117 2013-08-22 00:00:00 0.0 76
USC00513117 2013-08-23 00:00:00 0.0 77
USC00513117 2013-08-24 00:00:00 0.0 78
USC00513117 2013-08-25 00:00:00 0.0 77
USC00513117 2013-08-26 00:00:00 0.0 84
USC00513117 2013-08-27 00:00:00 0.0 76
USC00513117 2013-08-28 00:00:00 0.0 73
USC00513117 2013-08-29 00:00:00 0.05 72
USC00513117 2013-08-30 00:00:00 0.04 76
USC00513117 2013-08-31 00:00:00 0.0 83
USC00513117 2013-09-01 00:00:00 0.03 76
USC00513117 2013-09-02 00:00:00 0.01 76
USC00513117 2013-09-03 00:00:00 0.0 78
USC00513117 2013-09-04 00:00:00 0.16 75
USC00513117 2013-09-05 00:00:00 0.0 71
USC00513117 2013-09-06 00:00:00 0.0 73
USC00513117 2013-09-07 00:00:00 0.55 73
USC00513117 2013-09-08 00:00:00 0.1 77
USC00513117 2013-09-09 00:00:00 0.05 76
USC00513117 2013-09-10 00:00:00 0.0 76
USC00513117 2013-09-11 00:00:00 0.03 76
USC00513117 2013-09-12 00:00:00 0.0 75
USC00513117 2013-09-13 00:00:00 0.51 74
USC00513117 2013-09-14 00:00:00 0.18 76
USC00513117 2013-09-15 00:00:00 0.2 78
USC00513117 2013-09-16 00:00:00 0.0 78
USC00513117 2013-09-17 00:00:00 0.05 77
USC00513117 2013-09-18 00:00:00 0.06 78
USC00513117 2013-09-19 00:00:00 0.06 77
USC00513117 2013-09-20 00:00:00 0.01 76
USC00513117 2013-09-21 00:00:00 0.02 84
USC00513117 2013-09-22 00:00:00 0.07 77
USC00513117 2013-09-23 00:00:00 0.03 77
USC00513117 2013-09-24 00:00:00 0.1 77
USC00513117 2013-09-25 00:00:00 0.09 75
USC00513117 2013-09-26 00:00:00 0.05 75
USC00513117 2013-09-27 00:00:00 0.0 77
USC00513117 2013-09-28 00:00:00 0.0 78
USC00513117 2013-09-29 00:00:00 0.08 79
USC00513117 2013-09-30 00:00:00 0.06 76
USC00513117 2013-10-01 00:00:00 0.0 77
USC00513117 2013-10-02 00:00:00 0.0 77
USC00513117 2013-10-03 00:00:00 0.0 77
USC00513117 2013-10-04 00:00:00 0.01 76
USC00513117 2013-10-05 00:00:00 0.01 73
USC00513117 2013-10-06 00:00:00 0.33 76
USC00513117 2013-10-07 00:00:00 0.0 75
USC00513117 2013-10-08 00:00:00 0.04 76
USC00513117 2013-10-09 00:00:00 0.05 76
USC00513117 2013-10-10 00:00:00 0.15 72
USC00513117 2013-10-11 00:00:00 0.17 72
USC00513117 2013-10-12 00:00:00 0.63 76
USC00513117 2013-10-13 00:00:00 0.0 78
USC00513117 2013-10-14 00:00:00 0.16 73
USC00513117 2013-10-15 00:00:00 0.02 71
USC00513117 2013-10-16 00:00:00 0.27 71
USC00513117 2013-10-17 00:00:00 0.0 73
USC00513117 2013-10-18 00:00:00 0.02 73
USC00513117 2013-10-19 00:00:00 0.0 71
USC00513117 2013-10-20 00:00:00 0.0 72
USC00513117 2013-10-21 00:00:00 0.0 69
USC00513117 2013-10-22 00:00:00 0.0 71
USC00513117 2013-10-23 00:00:00 0.0 72
USC00513117 2013-10-24 00:00:00 0.02 73
USC00513117 2013-10-25 00:00:00 0.11 72
USC00513117 2013-10-26 00:00:00 0.0 75
USC00513117 2013-10-27 00:00:00 0.0 72
USC00513117 2013-10-28 00:00:00 0.7 72
USC00513117 2013-10-29 00:00:00 0.02 76
USC00513117 2013-10-30 00:00:00 0.0 73
USC00513117 2013-10-31 00:00:00 0.07 73
USC00513117 2013-11-01 00:00:00 0.0 76
USC00513117 2013-11-02 00:00:00 0.09 73
USC00513117 2013-11-03 00:00:00 0.0 77
USC00513117 2013-11-04 00:00:00 0.12 75
USC00513117 2013-11-05 00:00:00 0.01 72
USC00513117 2013-11-06 00:00:00 0.27 71
USC00513117 2013-11-07 00:00:00 0.16 69
USC00513117 2013-11-08 00:00:00 0.04 73
USC00513117 2013-11-09 00:00:00 0.76 74
USC00513117 2013-11-10 00:00:00 3.03 74
USC00513117 2013-11-11 00:00:00 0.27 76
USC00513117 2013-11-12 00:00:00 0.26 65
USC00513117 2013-11-13 00:00:00 0.12 65
USC00513117 2013-11-14 00:00:00 0.0 71
USC00513117 2013-11-15 00:00:00 0.76 72
USC00513117 2013-11-16 00:00:00 0.01 76
USC00513117 2013-11-17 00:00:00 0.0 73
USC00513117 2013-11-18 00:00:00 0.06 76
USC00513117 2013-11-19 00:00:00 0.0 70
USC00513117 2013-11-20 00:00:00 0.0 71
USC00513117 2013-11-21 00:00:00 0.0 72
USC00513117 2013-11-22 00:00:00 0.0 70
USC00513117 2013-11-23 00:00:00 0.1 74
USC00513117 2013-11-24 00:00:00 0.02 67
USC00513117 2013-11-25 00:00:00 0.0 74
USC00513117 2013-11-26 00:00:00 0.0 74
USC00513117 2013-11-27 00:00:00 0.0 70
USC00513117 2013-11-28 00:00:00 0.02 72
USC00513117 2013-11-29 00:00:00 0.13 73
USC00513117 2013-11-30 00:00:00 0.73 77
USC00513117 2013-12-01 00:00:00 0.0 76
USC00513117 2013-12-02 00:00:00 0.93 70
USC00513117 2013-12-03 00:00:00 0.8 71
USC00513117 2013-12-04 00:00:00 0.0 69
USC00513117 2013-12-05 00:00:00 0.0 67
USC00513117 2013-12-06 00:00:00 0.0 69
USC00513117 2013-12-07 00:00:00 0.0 71
USC00513117 2013-12-08 00:00:00 0.0 69
USC00513117 2013-12-09 00:00:00 0.0 72
USC00513117 2013-12-10 00:00:00 0.01 76
USC00513117 2013-12-11 00:00:00 0.13 75
USC00513117 2013-12-12 00:00:00 0.0 72
USC00513117 2013-12-13 00:00:00 0.01 75
USC00513117 2013-12-14 00:00:00 0.0 71
USC00513117 2013-12-15 00:00:00 0.0 69
USC00513117 2013-12-16 00:00:00 1.31 68
USC00513117 2013-12-17 00:00:00 0.01 68
USC00513117 2013-12-18 00:00:00 0.01 72
USC00513117 2013-12-19 00:00:00 1.0 70
USC00513117 2013-12-20 00:00:00 0.41 72
USC00513117 2013-12-21 00:00:00 0.01 75
USC00513117 2013-12-22 00:00:00 0.02 69
USC00513117 2013-12-23 00:00:00 0.02 72
USC00513117 2013-12-24 00:00:00 0.01 73
USC00513117 2013-12-25 00:00:00 0.02 73
USC00513117 2013-12-26 00:00:00 0.02 72
USC00513117 2013-12-27 00:00:00 0.0 73
USC00513117 2013-12-28 00:00:00 0.02 74
USC00513117 2013-12-29 00:00:00 0.03 73
USC00513117 2013-12-30 00:00:00 0.0 72
USC00513117 2013-12-31 00:00:00 0.09 68
USC00513117 2014-01-01 00:00:00 0.0 68
USC00513117 2014-01-02 00:00:00 0.0 75
USC00513117 2014-01-03 00:00:00 1.59 67
USC00513117 2014-01-04 00:00:00 0.01 71
USC00513117 2014-01-05 00:00:00 0.02 69
USC00513117 2014-01-06 00:00:00 0.19 66
USC00513117 2014-01-07 00:00:00 0.01 71
USC00513117 2014-01-08 00:00:00 0.0 71
USC00513117 2014-01-09 00:00:00 0.12 66
USC00513117 2014-01-10 00:00:00 0.0 72
USC00513117 2014-01-11 00:00:00 0.14 68
USC00513117 2014-01-12 00:00:00 0.0 79
USC00513117 2014-01-13 00:00:00 0.0 77
USC00513117 2014-01-14 00:00:00 0.89 72
USC00513117 2014-01-15 00:00:00 0.19 68
USC00513117 2014-01-16 00:00:00 0.04 72
USC00513117 2014-01-17 00:00:00 0.0 69
USC00513117 2014-01-18 00:00:00 0.03 67
USC00513117 2014-01-19 00:00:00 0.0 67
USC00513117 2014-01-20 00:00:00 0.02 66
USC00513117 2014-01-21 00:00:00 0.0 72
USC00513117 2014-01-22 00:00:00 0.65 71
USC00513117 2014-01-23 00:00:00 0.0 65
USC00513117 2014-01-24 00:00:00 0.0 62
USC00513117 2014-01-25 00:00:00 0.0 67
USC00513117 2014-01-26 00:00:00 0.0 75
USC00513117 2014-01-27 00:00:00 0.31 68
USC00513117 2014-01-28 00:00:00 0.43 70
USC00513117 2014-01-29 00:00:00 0.51 69
USC00513117 2014-01-30 00:00:00 0.2 66
USC00513117 2014-01-31 00:00:00 0.0 68
USC00513117 2014-02-01 00:00:00 0.12 74
USC00513117 2014-02-02 00:00:00 0.27 68
USC00513117 2014-02-03 00:00:00 0.0 69
USC00513117 2014-02-04 00:00:00 0.88 67
USC00513117 2014-02-05 00:00:00 0.39 71
USC00513117 2014-02-06 00:00:00 0.05 72
USC00513117 2014-02-07 00:00:00 0.06 70
USC00513117 2014-02-08 00:00:00 1.1 68
USC00513117 2014-02-09 00:00:00 0.36 72
USC00513117 2014-02-10 00:00:00 0.01 72
USC00513117 2014-02-11 00:00:00 0.0 69
USC00513117 2014-02-12 00:00:00 0.0 72
USC00513117 2014-02-13 00:00:00 0.0 70
USC00513117 2014-02-14 00:00:00 0.01 74
USC00513117 2014-02-15 00:00:00 0.33 73
USC00513117 2014-02-16 00:00:00 0.04 73
USC00513117 2014-02-17 00:00:00 0.29 74
USC00513117 2014-02-18 00:00:00 0.16 72
USC00513117 2014-02-19 00:00:00 0.81 71
USC00513117 2014-02-20 00:00:00 0.01 72
USC00513117 2014-02-21 00:00:00 0.12 70
USC00513117 2014-02-22 00:00:00 0.13 71
USC00513117 2014-02-23 00:00:00 0.0 81
USC00513117 2014-02-24 00:00:00 0.0 70
USC00513117 2014-02-25 00:00:00 0.01 67
USC00513117 2014-02-26 00:00:00 0.08 66
USC00513117 2014-02-27 00:00:00 0.09 69
USC00513117 2014-02-28 00:00:00 0.04 73
USC00513117 2014-03-01 00:00:00 0.16 72
USC00513117 2014-03-02 00:00:00 0.34 70
USC00513117 2014-03-03 00:00:00 0.26 66
USC00513117 2014-03-04 00:00:00 0.0 62
USC00513117 2014-03-05 00:00:00 0.0 66
USC00513117 2014-03-06 00:00:00 0.0 65
USC00513117 2014-03-07 00:00:00 0.12 74
USC00513117 2014-03-08 00:00:00 0.94 67
USC00513117 2014-03-09 00:00:00 0.34 72
USC00513117 2014-03-10 00:00:00 0.05 73
USC00513117 2014-03-11 00:00:00 0.05 72
USC00513117 2014-03-12 00:00:00 0.0 72
USC00513117 2014-03-13 00:00:00 0.0 73
USC00513117 2014-03-14 00:00:00 0.08 71
USC00513117 2014-03-15 00:00:00 0.1 70
USC00513117 2014-03-16 00:00:00 0.01 69
USC00513117 2014-03-17 00:00:00 0.04 68
USC00513117 2014-03-18 00:00:00 0.0 69
USC00513117 2014-03-19 00:00:00 0.01 71
USC00513117 2014-03-20 00:00:00 0.0 70
USC00513117 2014-03-21 00:00:00 0.02 72
USC00513117 2014-03-22 00:00:00 0.0 70
USC00513117 2014-03-23 00:00:00 0.0 72
USC00513117 2014-03-24 00:00:00 0.0 72
USC00513117 2014-03-25 00:00:00 0.02 71
USC00513117 2014-03-26 00:00:00 0.45 74
USC00513117 2014-03-27 00:00:00 0.4 72
USC00513117 2014-03-28 00:00:00 1.7 69
USC00513117 2014-03-29 00:00:00 1.6 70
USC00513117 2014-03-30 00:00:00 0.93 73
USC00513117 2014-03-31 00:00:00 0.03 78
USC00513117 2014-04-01 00:00:00 0.03 75
USC00513117 2014-04-02 00:00:00 0.2 73
USC00513117 2014-04-03 00:00:00 0.05 73
USC00513117 2014-04-04 00:00:00 0.01 78
USC00513117 2014-04-05 00:00:00 0.03 73
USC00513117 2014-04-06 00:00:00 0.1 67
USC00513117 2014-04-07 00:00:00 0.23 70
USC00513117 2014-04-08 00:00:00 0.02 69
USC00513117 2014-04-09 00:00:00 0.0 70
USC00513117 2014-04-10 00:00:00 0.0 69
USC00513117 2014-04-11 00:00:00 0.01 70
USC00513117 2014-04-12 00:00:00 0.39 70
USC00513117 2014-04-13 00:00:00 0.01 72
USC00513117 2014-04-14 00:00:00 0.01 72
USC00513117 2014-04-15 00:00:00 0.01 71
USC00513117 2014-04-16 00:00:00 0.06 72
USC00513117 2014-04-18 00:00:00 0.05 74
USC00513117 2014-04-19 00:00:00 0.14 74
USC00513117 2014-04-20 00:00:00 0.03 72
USC00513117 2014-04-21 00:00:00 0.09 69
USC00513117 2014-04-22 00:00:00 0.12 73
USC00513117 2014-04-23 00:00:00 0.0 74
USC00513117 2014-04-24 00:00:00 0.0 73
USC00513117 2014-04-25 00:00:00 0.26 72
USC00513117 2014-04-26 00:00:00 0.02 73
USC00513117 2014-04-27 00:00:00 0.2 70
USC00513117 2014-04-28 00:00:00 0.32 68
USC00513117 2014-04-29 00:00:00 0.0 72
USC00513117 2014-05-01 00:00:00 0.02 66
USC00513117 2014-05-02 00:00:00 0.57 69
USC00513117 2014-05-03 00:00:00 0.3 71
USC00513117 2014-05-04 00:00:00 0.01 72
USC00513117 2014-05-05 00:00:00 0.02 72
USC00513117 2014-05-06 00:00:00 0.19 72
USC00513117 2014-05-07 00:00:00 0.0 74
USC00513117 2014-05-08 00:00:00 0.02 71
USC00513117 2014-05-09 00:00:00 0.13 70
USC00513117 2014-05-10 00:00:00 0.09 73
USC00513117 2014-05-11 00:00:00 0.17 76
USC00513117 2014-05-12 00:00:00 0.48 73
USC00513117 2014-05-13 00:00:00 0.13 71
USC00513117 2014-05-14 00:00:00 0.0 69
USC00513117 2014-05-15 00:00:00 0.0 73
USC00513117 2014-05-16 00:00:00 0.55 70
USC00513117 2014-05-17 00:00:00 0.12 75
USC00513117 2014-05-18 00:00:00 0.2 79
USC00513117 2014-05-19 00:00:00 0.0 69
USC00513117 2014-05-20 00:00:00 0.05 72
USC00513117 2014-05-21 00:00:00 0.0 74
USC00513117 2014-05-22 00:00:00 0.0 74
USC00513117 2014-05-23 00:00:00 0.15 73
USC00513117 2014-05-24 00:00:00 0.01 74
USC00513117 2014-05-25 00:00:00 0.86 75
USC00513117 2014-05-26 00:00:00 0.28 75
USC00513117 2014-05-27 00:00:00 0.08 74
USC00513117 2014-05-28 00:00:00 0.14 76
USC00513117 2014-05-29 00:00:00 0.02 74
USC00513117 2014-05-30 00:00:00 0.05 74
USC00513117 2014-05-31 00:00:00 0.01 77
USC00513117 2014-06-01 00:00:00 0.0 77
USC00513117 2014-06-02 00:00:00 0.0 74
USC00513117 2014-06-03 00:00:00 0.0 73
USC00513117 2014-06-04 00:00:00 0.0 75
USC00513117 2014-06-05 00:00:00 0.0 75
USC00513117 2014-06-06 00:00:00 0.13 74
USC00513117 2014-06-07 00:00:00 0.01 74
USC00513117 2014-06-08 00:00:00 0.02 75
USC00513117 2014-06-09 00:00:00 0.02 75
USC00513117 2014-06-10 00:00:00 0.1 72
USC00513117 2014-06-11 00:00:00 0.15 74
USC00513117 2014-06-12 00:00:00 0.0 76
USC00513117 2014-06-13 00:00:00 0.0 76
USC00513117 2014-06-14 00:00:00 0.0 75
USC00513117 2014-06-15 00:00:00 0.01 75
USC00513117 2014-06-16 00:00:00 0.12 74
USC00513117 2014-06-17 00:00:00 0.05 72
USC00513117 2014-06-18 00:00:00 0.07 74
USC00513117 2014-06-19 00:00:00 0.0 75
USC00513117 2014-06-20 00:00:00 0.29 70
USC00513117 2014-06-21 00:00:00 0.06 71
USC00513117 2014-06-22 00:00:00 0.15 72
USC00513117 2014-06-23 00:00:00 0.15 71
USC00513117 2014-06-24 00:00:00 0.1 73
USC00513117 2014-06-25 00:00:00 0.04 74
USC00513117 2014-06-26 00:00:00 0.04 72
USC00513117 2014-06-27 00:00:00 0.02 74
USC00513117 2014-06-28 00:00:00 0.25 76
USC00513117 2014-06-29 00:00:00 0.18 72
USC00513117 2014-06-30 00:00:00 0.03 75
USC00513117 2014-07-01 00:00:00 0.01 75
USC00513117 2014-07-02 00:00:00 0.02 76
USC00513117 2014-07-03 00:00:00 0.19 77
USC00513117 2014-07-04 00:00:00 0.03 78
USC00513117 2014-07-05 00:00:00 0.02 73
USC00513117 2014-07-06 00:00:00 0.21 76
USC00513117 2014-07-07 00:00:00 0.12 76
USC00513117 2014-07-08 00:00:00 0.08 75
USC00513117 2014-07-09 00:00:00 0.01 73
USC00513117 2014-07-10 00:00:00 0.02 74
USC00513117 2014-07-11 00:00:00 0.04 73
USC00513117 2014-07-12 00:00:00 0.01 76
USC00513117 2014-07-13 00:00:00 0.05 77
USC00513117 2014-07-14 00:00:00 0.19 77

USC00513117 2014-07-15 00:00:00 0.03 76
USC00513117 2014-07-16 00:00:00 0.12 76
USC00513117 2014-07-17 00:00:00 0.01 75
USC00513117 2014-07-18 00:00:00 0.13 75
USC00513117 2014-07-19 00:00:00 0.0 76
USC00513117 2014-07-20 00:00:00 5.98 72
USC00513117 2014-07-21 00:00:00 0.05 82
USC00513117 2014-07-22 00:00:00 0.01 75
USC00513117 2014-07-23 00:00:00 0.31 76
USC00513117 2014-07-24 00:00:00 0.0 77
USC00513117 2014-07-25 00:00:00 0.0 75
USC00513117 2014-07-26 00:00:00 0.02 77
USC00513117 2014-07-27 00:00:00 0.04 78
USC00513117 2014-07-28 00:00:00 0.0 76
USC00513117 2014-07-29 00:00:00 0.0 76
USC00513117 2014-07-30 00:00:00 0.0 76
USC00513117 2014-07-31 00:00:00 0.0 76
USC00513117 2014-08-01 00:00:00 0.0 77
USC00513117 2014-08-02 00:00:00 0.1 77
USC00513117 2014-08-03 00:00:00 0.0 77
USC00513117 2014-08-04 00:00:00 0.0 78
USC00513117 2014-08-05 00:00:00 0.0 77
USC00513117 2014-08-06 00:00:00 0.04 74
USC00513117 2014-08-07 00:00:00 0.03 75
USC00513117 2014-08-08 00:00:00 0.08 76
USC00513117 2014-08-09 00:00:00 0.31 77
USC00513117 2014-08-10 00:00:00 0.06 79
USC00513117 2014-08-11 00:00:00 0.0 72
USC00513117 2014-08-12 00:00:00 0.0 75
USC00513117 2014-08-13 00:00:00 0.37 74
USC00513117 2014-08-14 00:00:00 0.0 78
USC00513117 2014-08-15 00:00:00 0.01 77
USC00513117 2014-08-16 00:00:00 0.03 76
USC00513117 2014-08-17 00:00:00 0.0 80
USC00513117 2014-08-18 00:00:00 0.06 77
USC00513117 2014-08-19 00:00:00 0.0 76
USC00513117 2014-08-20 00:00:00 0.08 76
USC00513117 2014-08-21 00:00:00 0.11 75
USC00513117 2014-08-22 00:00:00 0.18 77
USC00513117 2014-08-23 00:00:00 0.01 76
USC00513117 2014-08-24 00:00:00 0.19 84
USC00513117 2014-08-25 00:00:00 0.07 74
USC00513117 2014-08-26 00:00:00 0.33 72
USC00513117 2014-08-27 00:00:00 0.47 74
USC00513117 2014-08-28 00:00:00 0.01 73
USC00513117 2014-08-29 00:00:00 0.06 72
USC00513117 2014-08-30 00:00:00 0.27 84
USC00513117 2014-08-31 00:00:00 0.01 74
USC00513117 2014-09-01 00:00:00 0.02 75
USC00513117 2014-09-02 00:00:00 1.37 73
USC00513117 2014-09-03 00:00:00 0.02 77
USC00513117 2014-09-07 00:00:00 0.29 76
USC00513117 2014-09-08 00:00:00 0.0 76
USC00513117 2014-09-09 00:00:00 0.03 74
USC00513117 2014-09-10 00:00:00 0.04 77
USC00513117 2014-09-11 00:00:00 0.0 76
USC00513117 2014-09-12 00:00:00 0.01 73
USC00513117 2014-09-13 00:00:00 0.0 80
USC00513117 2014-09-14 00:00:00 0.0 85
USC00513117 2014-09-15 00:00:00 0.36 74
USC00513117 2014-09-16 00:00:00 0.0 78
USC00513117 2014-09-17 00:00:00 0.02 75
USC00513117 2014-09-18 00:00:00 0.2 74
USC00513117 2014-09-19 00:00:00 0.13 73
USC00513117 2014-09-20 00:00:00 0.23 76
USC00513117 2014-09-21 00:00:00 0.0 76
USC00513117 2014-09-22 00:00:00 0.01 78
USC00513117 2014-09-23 00:00:00 0.03 77
USC00513117 2014-09-24 00:00:00 0.0 78
USC00513117 2014-09-25 00:00:00 0.14 78
USC00513117 2014-09-26 00:00:00 0.3 77
USC00513117 2014-09-27 00:00:00 0.02 78
USC00513117 2014-09-28 00:00:00 0.23 74
USC00513117 2014-09-29 00:00:00 0.22 75
USC00513117 2014-09-30 00:00:00 0.31 73
USC00513117 2014-10-01 00:00:00 1.71 73
USC00513117 2014-10-02 00:00:00 0.01 75
USC00513117 2014-10-03 00:00:00 0.01 78
USC00513117 2014-10-04 00:00:00 0.33 74
USC00513117 2014-10-05 00:00:00 0.64 74
USC00513117 2014-10-06 00:00:00 0.26 74
USC00513117 2014-10-07 00:00:00 0.0 75
USC00513117 2014-10-08 00:00:00 0.13 74
USC00513117 2014-10-09 00:00:00 0.01 76
USC00513117 2014-10-10 00:00:00 0.08 78
USC00513117 2014-10-11 00:00:00 0.02 77
USC00513117 2014-10-13 00:00:00 0.0 78
USC00513117 2014-10-14 00:00:00 0.0 78
USC00513117 2014-10-15 00:00:00 0.1 76
USC00513117 2014-10-16 00:00:00 0.01 79
USC00513117 2014-10-17 00:00:00 0.02 76
USC00513117 2014-10-18 00:00:00 0.21 80
USC00513117 2014-10-19 00:00:00 2.06 74
USC00513117 2014-10-20 00:00:00 1.84 76
USC00513117 2014-10-21 00:00:00 0.0 75
USC00513117 2014-10-22 00:00:00 0.02 77
USC00513117 2014-10-23 00:00:00 0.0 74
USC00513117 2014-10-24 00:00:00 0.41 74
USC00513117 2014-10-25 00:00:00 0.05 77
USC00513117 2014-10-26 00:00:00 0.0 77
USC00513117 2014-10-27 00:00:00 0.0 77
USC00513117 2014-10-28 00:00:00 0.06 73
USC00513117 2014-10-29 00:00:00 0.0 77
USC00513117 2014-10-30 00:00:00 0.22 76
USC00513117 2014-10-31 00:00:00 0.02 76
USC00513117 2014-11-01 00:00:00 0.11 77
USC00513117 2014-11-02 00:00:00 0.11 75
USC00513117 2014-11-03 00:00:00 0.03 78
USC00513117 2014-11-04 00:00:00 0.0 74
USC00513117 2014-11-05 00:00:00 0.05 77
USC00513117 2014-11-06 00:00:00 0.18 76
USC00513117 2014-11-07 00:00:00 0.14 72
USC00513117 2014-11-08 00:00:00 0.46 74
USC00513117 2014-11-09 00:00:00 0.0 67
USC00513117 2014-11-10 00:00:00 0.0 68
USC00513117 2014-11-11 00:00:00 0.0 68
USC00513117 2014-11-12 00:00:00 0.41 70
USC00513117 2014-11-13 00:00:00 0.0 71
USC00513117 2014-11-14 00:00:00 0.09 75
USC00513117 2014-11-15 00:00:00 1.03 71
USC00513117 2014-11-16 00:00:00 0.09 72
USC00513117 2014-11-17 00:00:00 0.0 75
USC00513117 2014-11-18 00:00:00 0.0 76
USC00513117 2014-11-19 00:00:00 0.01 75
USC00513117 2014-11-20 00:00:00 0.01 76
USC00513117 2014-11-21 00:00:00 0.01 81
USC00513117 2014-11-22 00:00:00 0.0 76
USC00513117 2014-11-23 00:00:00 0.0 72
USC00513117 2014-11-24 00:00:00 0.13 71
USC00513117 2014-11-25 00:00:00 0.05 70
USC00513117 2014-11-26 00:00:00 0.01 73
USC00513117 2014-11-27 00:00:00 0.0 74
USC00513117 2014-11-28 00:00:00 0.01 73
USC00513117 2014-11-29 00:00:00 0.02 74
USC00513117 2014-11-30 00:00:00 0.15 73
USC00513117 2014-12-01 00:00:00 0.0 72
USC00513117 2014-12-02 00:00:00 0.0 71
USC00513117 2014-12-03 00:00:00 0.05 69
USC00513117 2014-12-04 00:00:00 1.35 67
USC00513117 2014-12-05 00:00:00 0.01 70
USC00513117 2014-12-06 00:00:00 0.0 72
USC00513117 2014-12-07 00:00:00 0.0 67
USC00513117 2014-12-08 00:00:00 0.0 67
USC00513117 2014-12-09 00:00:00 0.0 69
USC00513117 2014-12-10 00:00:00 0.0 67
USC00513117 2014-12-11 00:00:00 0.05 74
USC00513117 2014-12-12 00:00:00 0.12 70
USC00513117 2014-12-13 00:00:00 0.03 73
USC00513117 2014-12-14 00:00:00 0.11 71
USC00513117 2014-12-15 00:00:00 0.0 71
USC00513117 2014-12-16 00:00:00 0.03 71
USC00513117 2014-12-17 00:00:00 0.14 71
USC00513117 2014-12-18 00:00:00 0.09 72
USC00513117 2014-12-19 00:00:00 0.01 76
USC00513117 2014-12-20 00:00:00 0.0 78
USC00513117 2014-12-21 00:00:00 0.0 76
USC00513117 2014-12-22 00:00:00 0.0 73
USC00513117 2014-12-23 00:00:00 1.1 70
USC00513117 2014-12-24 00:00:00 1.24 68
USC00513117 2014-12-25 00:00:00 0.09 77
USC00513117 2014-12-26 00:00:00 0.0 66
USC00513117 2014-12-27 00:00:00 0.0 65
USC00513117 2014-12-28 00:00:00 0.0 69
USC00513117 2014-12-29 00:00:00 0.0 69
USC00513117 2014-12-30 00:00:00 0.0 66
USC00513117 2014-12-31 00:00:00 0.72 64
USC00513117 2015-01-01 00:00:00 0.01 64
USC00513117 2015-01-02 00:00:00 0.01 64
USC00513117 2015-01-03 00:00:00 1.46 63
USC00513117 2015-01-04 00:00:00 0.02 66
USC00513117 2015-01-05 00:00:00 0.0 60
USC00513117 2015-01-06 00:00:00 0.07 69
USC00513117 2015-01-07 00:00:00 0.0 68
USC00513117 2015-01-08 00:00:00 0.0 67
USC00513117 2015-01-09 00:00:00 0.0 68
USC00513117 2015-01-10 00:00:00 0.04 69
USC00513117 2015-01-11 00:00:00 0.0 66
USC00513117 2015-01-12 00:00:00 0.0 64
USC00513117 2015-01-13 00:00:00 0.0 64
USC00513117 2015-01-14 00:00:00 0.0 68
USC00513117 2015-01-15 00:00:00 0.0 69
USC00513117 2015-01-16 00:00:00 0.01 71
USC00513117 2015-01-17 00:00:00 0.0 70
USC00513117 2015-01-18 00:00:00 0.0 69
USC00513117 2015-01-19 00:00:00 0.0 70
USC00513117 2015-01-20 00:00:00 0.0 67
USC00513117 2015-01-21 00:00:00 0.0 68
USC00513117 2015-01-22 00:00:00 0.0 67
USC00513117 2015-01-23 00:00:00 0.0 74
USC00513117 2015-01-24 00:00:00 0.09 69
USC00513117 2015-01-25 00:00:00 0.46 67
USC00513117 2015-01-26 00:00:00 0.73 70
USC00513117 2015-01-27 00:00:00 0.01 71
USC00513117 2015-01-28 00:00:00 0.09 68
USC00513117 2015-01-29 00:00:00 0.0 72
USC00513117 2015-01-30 00:00:00 0.02 65
USC00513117 2015-01-31 00:00:00 0.0 66
USC00513117 2015-02-01 00:00:00 0.0 66
USC00513117 2015-02-02 00:00:00 0.0 72
USC00513117 2015-02-03 00:00:00 0.0 77
USC00513117 2015-02-04 00:00:00 0.77 74
USC00513117 2015-02-05 00:00:00 0.0 70
USC00513117 2015-02-06 00:00:00 0.0 68
USC00513117 2015-02-07 00:00:00 0.0 65
USC00513117 2015-02-08 00:00:00 0.0 62
USC00513117 2015-02-09 00:00:00 0.0 74
USC00513117 2015-02-10 00:00:00 0.1 70
USC00513117 2015-02-11 00:00:00 0.0 70
USC00513117 2015-02-12 00:00:00 0.0 65
USC00513117 2015-02-13 00:00:00 0.0 73
USC00513117 2015-02-14 00:00:00 0.13 76
USC00513117 2015-02-15 00:00:00 0.8 61
USC00513117 2015-02-16 00:00:00 0.0 64
USC00513117 2015-02-17 00:00:00 0.0 68
USC00513117 2015-02-18 00:00:00 0.0 68
USC00513117 2015-02-19 00:00:00 0.0 70
USC00513117 2015-02-20 00:00:00 0.02 70
USC00513117 2015-02-21 00:00:00 0.76 69
USC00513117 2015-02-22 00:00:00 0.0 70
USC00513117 2015-02-23 00:00:00 0.0 73
USC00513117 2015-02-24 00:00:00 0.0 71
USC00513117 2015-02-25 00:00:00 0.0 72
USC00513117 2015-02-26 00:00:00 0.06 71
USC00513117 2015-02-27 00:00:00 0.08 70
USC00513117 2015-02-28 00:00:00 0.25 69
USC00513117 2015-03-01 00:00:00 0.27 72
USC00513117 2015-03-02 00:00:00 0.04 72
USC00513117 2015-03-03 00:00:00 0.02 73
USC00513117 2015-03-04 00:00:00 0.06 72
USC00513117 2015-03-05 00:00:00 0.52 69
USC00513117 2015-03-06 00:00:00 0.06 68
USC00513117 2015-03-07 00:00:00 0.0 68
USC00513117 2015-03-08 00:00:00 0.01 65
USC00513117 2015-03-09 00:00:00 0.0 64
USC00513117 2015-03-10 00:00:00 0.03 63
USC00513117 2015-03-11 00:00:00 0.0 65
USC00513117 2015-03-12 00:00:00 0.0 65
USC00513117 2015-03-13 00:00:00 0.02 62
USC00513117 2015-03-14 00:00:00 0.0 67
USC00513117 2015-03-15 00:00:00 0.0 69
USC00513117 2015-03-16 00:00:00 0.01 65
USC00513117 2015-03-17 00:00:00 0.0 63
USC00513117 2015-03-18 00:00:00 0.0 65
USC00513117 2015-03-19 00:00:00 0.0 67
USC00513117 2015-03-20 00:00:00 0.11 70
USC00513117 2015-03-21 00:00:00 0.08 71
USC00513117 2015-03-22 00:00:00 0.05 73
USC00513117 2015-03-23 00:00:00 0.0 72
USC00513117 2015-03-24 00:00:00 0.0 68
USC00513117 2015-03-25 00:00:00 0.02 69
USC00513117 2015-03-26 00:00:00 0.06 70
USC00513117 2015-03-27 00:00:00 0.0 71
USC00513117 2015-03-28 00:00:00 0.0 74
USC00513117 2015-03-29 00:00:00 0.38 73
USC00513117 2015-03-30 00:00:00 0.02 71
USC00513117 2015-03-31 00:00:00 0.6 70
USC00513117 2015-04-01 00:00:00 0.24 73
USC00513117 2015-04-02 00:00:00 0.01 73
USC00513117 2015-04-03 00:00:00 0.0 74
USC00513117 2015-04-04 00:00:00 0.0 74
USC00513117 2015-04-05 00:00:00 0.06 74
USC00513117 2015-04-06 00:00:00 0.0 72
USC00513117 2015-04-07 00:00:00 0.0 73
USC00513117 2015-04-08 00:00:00 0.19 72
USC00513117 2015-04-09 00:00:00 0.03 72
USC00513117 2015-04-10 00:00:00 0.0 71
USC00513117 2015-04-11 00:00:00 0.0 74
USC00513117 2015-04-12 00:00:00 0.09 73
USC00513117 2015-04-13 00:00:00 0.03 72
USC00513117 2015-04-14 00:00:00 0.01 73
USC00513117 2015-04-15 00:00:00 0.05 74
USC00513117 2015-04-16 00:00:00 0.04 72
USC00513117 2015-04-17 00:00:00 0.01 73
USC00513117 2015-04-18 00:00:00 0.02 74
USC00513117 2015-04-19 00:00:00 0.0 73
USC00513117 2015-04-20 00:00:00 0.0 73
USC00513117 2015-04-21 00:00:00 0.04 73
USC00513117 2015-04-22 00:00:00 0.1 69
USC00513117 2015-04-23 00:00:00 0.02 71
USC00513117 2015-04-24 00:00:00 0.04 76
USC00513117 2015-04-25 00:00:00 0.01 74
USC00513117 2015-04-26 00:00:00 0.0 75
USC00513117 2015-04-27 00:00:00 0.17 73
USC00513117 2015-04-28 00:00:00 0.09 73
USC00513117 2015-04-29 00:00:00 0.09 75
USC00513117 2015-04-30 00:00:00 0.03 76
USC00513117 2015-05-01 00:00:00 0.05 74
USC00513117 2015-05-02 00:00:00 0.0 73
USC00513117 2015-05-05 00:00:00 0.02 75
USC00513117 2015-05-06 00:00:00 0.0 74
USC00513117 2015-05-07 00:00:00 0.0 75
USC00513117 2015-05-08 00:00:00 0.04 76
USC00513117 2015-05-09 00:00:00 0.13 74
USC00513117 2015-05-10 00:00:00 0.05 73
USC00513117 2015-05-11 00:00:00 0.02 74
USC00513117 2015-05-12 00:00:00 0.0 73
USC00513117 2015-05-13 00:00:00 0.0 72
USC00513117 2015-05-14 00:00:00 0.1 73
USC00513117 2015-05-15 00:00:00 0.02 72
USC00513117 2015-05-16 00:00:00 0.02 76
USC00513117 2015-05-17 00:00:00 0.01 73
USC00513117 2015-05-18 00:00:00 0.27 73
USC00513117 2015-05-19 00:00:00 0.02 73
USC00513117 2015-05-20 00:00:00 0.03 72
USC00513117 2015-05-21 00:00:00 0.06 68
USC00513117 2015-05-22 00:00:00 0.0 68
USC00513117 2015-05-23 00:00:00 0.8 68
USC00513117 2015-05-24 00:00:00 0.0 72
USC00513117 2015-05-25 00:00:00 0.01 72
USC00513117 2015-05-26 00:00:00 0.08 67
USC00513117 2015-05-27 00:00:00 0.07 67
USC00513117 2015-05-28 00:00:00 1.29 68
USC00513117 2015-05-29 00:00:00 0.01 68
USC00513117 2015-05-30 00:00:00 0.0 70
USC00513117 2015-05-31 00:00:00 0.34 74
USC00513117 2015-06-04 00:00:00 0.27 72
USC00513117 2015-06-05 00:00:00 0.0 70
USC00513117 2015-06-06 00:00:00 0.0 76
USC00513117 2015-06-07 00:00:00 0.0 78
USC00513117 2015-06-08 00:00:00 0.1 72
USC00513117 2015-06-09 00:00:00 0.05 74
USC00513117 2015-06-10 00:00:00 0.07 74
USC00513117 2015-06-11 00:00:00 0.1 72
USC00513117 2015-06-12 00:00:00 0.0 71
USC00513117 2015-06-13 00:00:00 0.0 79
USC00513117 2015-06-14 00:00:00 0.07 79
USC00513117 2015-06-15 00:00:00 0.0 76
USC00513117 2015-06-16 00:00:00 0.14 75
USC00513117 2015-06-17 00:00:00 0.25 72
USC00513117 2015-06-18 00:00:00 0.14 74
USC00513117 2015-06-19 00:00:00 0.02 76
USC00513117 2015-06-20 00:00:00 0.04 76
USC00513117 2015-06-21 00:00:00 0.01 77
USC00513117 2015-06-22 00:00:00 0.01 75
USC00513117 2015-06-23 00:00:00 0.03 76
USC00513117 2015-06-24 00:00:00 0.14 75
USC00513117 2015-06-25 00:00:00 0.2 75
USC00513117 2015-06-26 00:00:00 0.1 76
USC00513117 2015-06-27 00:00:00 0.06 76
USC00513117 2015-07-06 00:00:00 0.01 78
USC00513117 2015-07-09 00:00:00 0.05 79
USC00513117 2015-07-10 00:00:00 0.29 77
USC00513117 2015-07-11 00:00:00 0.33 78
USC00513117 2015-07-12 00:00:00 0.3 77
USC00513117 2015-07-13 00:00:00 0.2 79
USC00513117 2015-07-18 00:00:00 0.07 78
USC00513117 2015-07-19 00:00:00 0.03 77
USC00513117 2015-07-20 00:00:00 0.03 77
USC00513117 2015-08-01 00:00:00 0.05 79
USC00513117 2015-08-02 00:00:00 0.02 80
USC00513117 2015-08-03 00:00:00 0.02 81
USC00513117 2015-08-04 00:00:00 0.0 77
USC00513117 2015-08-05 00:00:00 0.02 77
USC00513117 2015-08-06 00:00:00 0.27 77
USC00513117 2015-08-07 00:00:00 0.3 77
USC00513117 2015-08-08 00:00:00 0.27 76
USC00513117 2015-08-10 00:00:00 0.01 79
USC00513117 2015-08-11 00:00:00 0.02 79
USC00513117 2015-08-12 00:00:00 0.09 79
USC00513117 2015-08-13 00:00:00 0.19 77
USC00513117 2015-08-14 00:00:00 0.21 78
USC00513117 2015-08-15 00:00:00 0.02 83
USC00513117 2015-08-17 00:00:00 0.51 74
USC00513117 2015-08-18 00:00:00 0.24 74
USC00513117 2015-08-19 00:00:00 0.02 76
USC00513117 2015-08-20 00:00:00 0.08 79
USC00513117 2015-08-21 00:00:00 0.05 83
USC00513117 2015-08-22 00:00:00 0.65 77
USC00513117 2015-08-23 00:00:00 0.33 73
USC00513117 2015-08-24 00:00:00 0.23 76
USC00513117 2015-08-25 00:00:00 0.52 76
USC00513117 2015-08-26 00:00:00 1.03 76
USC00513117 2015-08-27 00:00:00 0.0 78
USC00513117 2015-08-28 00:00:00 0.0 85

USC00513117 2015-08-29 00:00:00 0.25 81
USC00513117 2015-08-30 00:00:00 0.0 78
USC00513117 2015-09-01 00:00:00 0.32 78
USC00513117 2015-09-02 00:00:00 0.28 79
USC00513117 2015-09-03 00:00:00 1.55 79
USC00513117 2015-09-04 00:00:00 0.0 83
USC00513117 2015-09-05 00:00:00 0.0 82
USC00513117 2015-09-06 00:00:00 0.71 76
USC00513117 2015-09-07 00:00:00 0.19 77
USC00513117 2015-09-10 00:00:00 0.06 78
USC00513117 2015-09-11 00:00:00 0.09 78
USC00513117 2015-09-12 00:00:00 2.7 80
USC00513117 2015-09-13 00:00:00 0.16 80
USC00513117 2015-09-14 00:00:00 0.63 78
USC00513117 2015-09-15 00:00:00 0.56 76
USC00513117 2015-09-16 00:00:00 0.06 79
USC00513117 2015-09-17 00:00:00 0.06 75
USC00513117 2015-09-18 00:00:00 0.08 78
USC00513117 2015-09-19 00:00:00 0.0 80
USC00513117 2015-09-20 00:00:00 0.07 80
USC00513117 2015-09-21 00:00:00 0.07 80
USC00513117 2015-09-22 00:00:00 0.32 80
USC00513117 2015-09-23 00:00:00 0.3 78
USC00513117 2015-09-24 00:00:00 0.01 79
USC00513117 2015-09-25 00:00:00 0.0 79
USC00513117 2015-09-26 00:00:00 0.36 79
USC00513117 2015-09-27 00:00:00 0.18 77
USC00513117 2015-09-28 00:00:00 0.17 77
USC00513117 2015-09-29 00:00:00 0.07 77
USC00513117 2015-09-30 00:00:00 0.17 80
USC00513117 2015-10-01 00:00:00 0.0 79
USC00513117 2015-10-02 00:00:00 0.02 76
USC00513117 2015-10-03 00:00:00 0.0 75
USC00513117 2015-10-04 00:00:00 0.0 78
USC00513117 2015-10-05 00:00:00 0.4 76
USC00513117 2015-10-06 00:00:00 0.22 75
USC00513117 2015-10-07 00:00:00 0.22 75
USC00513117 2015-10-08 00:00:00 0.05 75
USC00513117 2015-10-09 00:00:00 0.03 75
USC00513117 2015-10-10 00:00:00 0.11 74
USC00513117 2015-10-11 00:00:00 0.09 81
USC00513117 2015-10-12 00:00:00 1.0 77
USC00513117 2015-10-13 00:00:00 1.7 75
USC00513117 2015-10-14 00:00:00 1.21 75
USC00513117 2015-10-15 00:00:00 0.81 74
USC00513117 2015-10-16 00:00:00 0.73 73
USC00513117 2015-10-17 00:00:00 0.1 79
USC00513117 2015-10-18 00:00:00 0.03 81
USC00513117 2015-10-19 00:00:00 0.18 75
USC00513117 2015-10-20 00:00:00 0.2 74
USC00513117 2015-10-21 00:00:00 0.02 76
USC00513117 2015-10-22 00:00:00 0.0 75
USC00513117 2015-10-23 00:00:00 0.03 78
USC00513117 2015-10-24 00:00:00 0.0 74
USC00513117 2015-10-25 00:00:00 0.03 75
USC00513117 2015-10-26 00:00:00 0.04 77
USC00513117 2015-10-27 00:00:00 0.06 77
USC00513117 2015-10-28 00:00:00 0.27 72
USC00513117 2015-10-29 00:00:00 0.02 74
USC00513117 2015-10-30 00:00:00 0.02 74
USC00513117 2015-10-31 00:00:00 0.22 78
USC00513117 2015-11-01 00:00:00 0.33 81
USC00513117 2015-11-02 00:00:00 0.0 75
USC00513117 2015-11-03 00:00:00 0.0 82
USC00513117 2015-11-04 00:00:00 0.03 78
USC00513117 2015-11-05 00:00:00 0.12 76
USC00513117 2015-11-06 00:00:00 0.12 77
USC00513117 2015-11-07 00:00:00 0.12 76
USC00513117 2015-11-08 00:00:00 0.3 77
USC00513117 2015-11-09 00:00:00 0.11 76
USC00513117 2015-11-10 00:00:00 0.06 78
USC00513117 2015-11-11 00:00:00 0.0 79
USC00513117 2015-11-12 00:00:00 0.3 76
USC00513117 2015-11-13 00:00:00 0.1 75
USC00513117 2015-11-14 00:00:00 0.53 79
USC00513117 2015-11-15 00:00:00 0.08 79
USC00513117 2015-11-16 00:00:00 0.0 75
USC00513117 2015-11-17 00:00:00 0.1 70
USC00513117 2015-11-18 00:00:00 0.1 81
USC00513117 2015-11-19 00:00:00 0.18 77
USC00513117 2015-11-20 00:00:00 0.68 73
USC00513117 2015-11-21 00:00:00 1.61 75
USC00513117 2015-11-22 00:00:00 0.8 73
USC00513117 2015-11-23 00:00:00 0.48 74
USC00513117 2015-11-24 00:00:00 1.7 74
USC00513117 2015-11-25 00:00:00 0.11 71
USC00513117 2015-11-26 00:00:00 0.36 73
USC00513117 2015-11-27 00:00:00 0.91 75
USC00513117 2015-11-28 00:00:00 0.07 77
USC00513117 2015-11-29 00:00:00 0.02 78
USC00513117 2015-11-30 00:00:00 0.03 76
USC00513117 2015-12-02 00:00:00 0.03 74
USC00513117 2015-12-03 00:00:00 0.08 75
USC00513117 2015-12-04 00:00:00 0.01 80
USC00513117 2015-12-05 00:00:00 0.28 72
USC00513117 2015-12-06 00:00:00 0.52 73
USC00513117 2015-12-07 00:00:00 0.0 70
USC00513117 2015-12-08 00:00:00 0.08 69
USC00513117 2015-12-09 00:00:00 0.1 77
USC00513117 2015-12-10 00:00:00 0.08 74
USC00513117 2015-12-11 00:00:00 0.0 77
USC00513117 2015-12-12 00:00:00 0.62 72
USC00513117 2015-12-13 00:00:00 0.0 69
USC00513117 2015-12-14 00:00:00 0.69 69
USC00513117 2015-12-15 00:00:00 0.24 75
USC00513117 2015-12-16 00:00:00 0.08 75
USC00513117 2015-12-17 00:00:00 0.13 72
USC00513117 2015-12-18 00:00:00 0.28 73
USC00513117 2015-12-19 00:00:00 0.36 78
USC00513117 2015-12-20 00:00:00 0.2 75
USC00513117 2015-12-21 00:00:00 0.03 75
USC00513117 2015-12-22 00:00:00 0.01 74
USC00513117 2015-12-23 00:00:00 0.11 73
USC00513117 2015-12-24 00:00:00 0.0 70
USC00513117 2015-12-25 00:00:00 0.52 70
USC00513117 2015-12-26 00:00:00 0.19 72
USC00513117 2015-12-27 00:00:00 0.25 74
USC00513117 2015-12-28 00:00:00 0.4 74
USC00513117 2015-12-29 00:00:00 0.11 67
USC00513117 2015-12-30 00:00:00 0.03 74
USC00513117 2015-12-31 00:00:00 0.06 70
USC00513117 2016-01-01 00:00:00 0.02 63
USC00513117 2016-01-02 00:00:00 0.01 73
USC00513117 2016-01-03 00:00:00 0.0 71
USC00513117 2016-01-04 00:00:00 0.0 72
USC00513117 2016-01-05 00:00:00 0.19 68
USC00513117 2016-01-06 00:00:00 0.3 70
USC00513117 2016-01-07 00:00:00 0.03 71
USC00513117 2016-01-08 00:00:00 0.01 69
USC00513117 2016-01-09 00:00:00 0.0 71
USC00513117 2016-01-10 00:00:00 0.01 72
USC00513117 2016-01-11 00:00:00 0.01 72
USC00513117 2016-01-12 00:00:00 0.03 66
USC00513117 2016-01-13 00:00:00 0.0 77
USC00513117 2016-01-14 00:00:00 0.0 66
USC00513117 2016-01-15 00:00:00 0.0 71
USC00513117 2016-01-16 00:00:00 0.03 72
USC00513117 2016-01-17 00:00:00 0.02 67
USC00513117 2016-01-18 00:00:00 0.0 67
USC00513117 2016-01-19 00:00:00 0.0 73
USC00513117 2016-01-20 00:00:00 0.02 67
USC00513117 2016-01-21 00:00:00 0.27 75
USC00513117 2016-01-22 00:00:00 0.01 70
USC00513117 2016-01-23 00:00:00 0.0 71
USC00513117 2016-01-24 00:00:00 0.0 70
USC00513117 2016-01-25 00:00:00 0.13 70
USC00513117 2016-01-26 00:00:00 0.16 77
USC00513117 2016-01-27 00:00:00 0.0 71
USC00513117 2016-01-28 00:00:00 0.0 68
USC00513117 2016-01-29 00:00:00 0.0 69
USC00513117 2016-01-30 00:00:00 0.0 67
USC00513117 2016-01-31 00:00:00 0.0 72
USC00513117 2016-02-01 00:00:00 0.0 78
USC00513117 2016-02-02 00:00:00 0.41 68
USC00513117 2016-02-03 00:00:00 0.25 71
USC00513117 2016-02-04 00:00:00 0.0 70
USC00513117 2016-02-05 00:00:00 0.0 70
USC00513117 2016-02-06 00:00:00 0.0 75
USC00513117 2016-02-07 00:00:00 0.16 71
USC00513117 2016-02-08 00:00:00 0.0 74
USC00513117 2016-02-09 00:00:00 0.0 66
USC00513117 2016-02-10 00:00:00 0.0 63
USC00513117 2016-02-11 00:00:00 0.0 72
USC00513117 2016-02-12 00:00:00 0.07 74
USC00513117 2016-02-13 00:00:00 0.02 75
USC00513117 2016-02-14 00:00:00 0.0 74
USC00513117 2016-02-15 00:00:00 0.0 79
USC00513117 2016-02-16 00:00:00 0.05 75
USC00513117 2016-02-17 00:00:00 0.1 73
USC00513117 2016-02-18 00:00:00 0.02 74
USC00513117 2016-02-19 00:00:00 0.11 69
USC00513117 2016-02-20 00:00:00 0.07 76
USC00513117 2016-02-21 00:00:00 0.09 74
USC00513117 2016-02-22 00:00:00 0.05 74
USC00513117 2016-02-23 00:00:00 0.0 65
USC00513117 2016-02-24 00:00:00 0.0 75
USC00513117 2016-02-25 00:00:00 0.0 72
USC00513117 2016-02-26 00:00:00 0.38 77
USC00513117 2016-02-27 00:00:00 0.08 76
USC00513117 2016-02-28 00:00:00 0.0 80
USC00513117 2016-02-29 00:00:00 0.0 79
USC00513117 2016-03-01 00:00:00 0.0 73
USC00513117 2016-03-02 00:00:00 0.0 71
USC00513117 2016-03-03 00:00:00 0.0 72
USC00513117 2016-03-04 00:00:00 0.0 67
USC00513117 2016-03-05 00:00:00 0.0 66
USC00513117 2016-03-06 00:00:00 0.0 69
USC00513117 2016-03-07 00:00:00 0.0 70
USC00513117 2016-03-08 00:00:00 0.02 75
USC00513117 2016-03-09 00:00:00 0.15 74
USC00513117 2016-03-10 00:00:00 0.0 70
USC00513117 2016-03-11 00:00:00 0.06 70
USC00513117 2016-03-12 00:00:00 0.0 73
USC00513117 2016-03-13 00:00:00 0.0 72
USC00513117 2016-03-14 00:00:00 0.0 72
USC00513117 2016-03-15 00:00:00 0.3 66
USC00513117 2016-03-16 00:00:00 0.41 71
USC00513117 2016-03-17 00:00:00 0.02 69
USC00513117 2016-03-18 00:00:00 0.03 70
USC00513117 2016-03-19 00:00:00 0.02 70
USC00513117 2016-03-20 00:00:00 0.0 72
USC00513117 2016-03-21 00:00:00 0.06 71
USC00513117 2016-03-22 00:00:00 0.0 69
USC00513117 2016-03-23 00:00:00 1.78 66
USC00513117 2016-03-24 00:00:00 0.02 68
USC00513117 2016-03-25 00:00:00 1.9 70
USC00513117 2016-03-26 00:00:00 0.87 67
USC00513117 2016-03-27 00:00:00 0.01 67
USC00513117 2016-03-28 00:00:00 0.0 68
USC00513117 2016-03-29 00:00:00 0.01 72
USC00513117 2016-03-30 00:00:00 0.02 66
USC00513117 2016-03-31 00:00:00 0.0 69
USC00513117 2016-04-01 00:00:00 0.0 71
USC00513117 2016-04-02 00:00:00 0.02 71
USC00513117 2016-04-03 00:00:00 0.0 73
USC00513117 2016-04-04 00:00:00 0.0 75
USC00513117 2016-04-05 00:00:00 0.2 69
USC00513117 2016-04-06 00:00:00 0.1 70
USC00513117 2016-04-07 00:00:00 0.12 68
USC00513117 2016-04-08 00:00:00 0.02 72
USC00513117 2016-04-09 00:00:00 0.66 72
USC00513117 2016-04-10 00:00:00 0.02 68
USC00513117 2016-04-11 00:00:00 0.08 72
USC00513117 2016-04-12 00:00:00 0.02 74
USC00513117 2016-04-13 00:00:00 0.05 75
USC00513117 2016-04-14 00:00:00 0.06 74
USC00513117 2016-04-15 00:00:00 0.0 75
USC00513117 2016-04-16 00:00:00 0.04 73
USC00513117 2016-04-17 00:00:00 0.17 69
USC00513117 2016-04-18 00:00:00 0.4 69
USC00513117 2016-04-19 00:00:00 0.02 70
USC00513117 2016-04-20 00:00:00 0.0 73
USC00513117 2016-04-21 00:00:00 0.01 73
USC00513117 2016-04-22 00:00:00 0.0 74
USC00513117 2016-04-23 00:00:00 0.21 71
USC00513117 2016-04-24 00:00:00 0.11 75
USC00513117 2016-04-25 00:00:00 0.06 76
USC00513117 2016-04-26 00:00:00 0.01 76
USC00513117 2016-04-27 00:00:00 0.05 74
USC00513117 2016-04-28 00:00:00 0.0 75
USC00513117 2016-04-29 00:00:00 0.0 75
USC00513117 2016-04-30 00:00:00 0.0 74
USC00513117 2016-05-01 00:00:00 0.04 75
USC00513117 2016-05-02 00:00:00 0.0 74
USC00513117 2016-05-03 00:00:00 0.02 74
USC00513117 2016-05-04 00:00:00 0.12 74
USC00513117 2016-05-05 00:00:00 0.6 77
USC00513117 2016-05-06 00:00:00 0.22 70
USC00513117 2016-05-07 00:00:00 1.53 69
USC00513117 2016-05-08 00:00:00 0.8 68
USC00513117 2016-05-09 00:00:00 0.1 73
USC00513117 2016-05-10 00:00:00 0.15 72
USC00513117 2016-05-11 00:00:00 0.02 72
USC00513117 2016-05-12 00:00:00 0.0 68
USC00513117 2016-05-13 00:00:00 0.0 68
USC00513117 2016-05-14 00:00:00 0.18 72
USC00513117 2016-05-15 00:00:00 0.02 74
USC00513117 2016-05-16 00:00:00 0.0 75
USC00513117 2016-05-17 00:00:00 0.03 75
USC00513117 2016-05-18 00:00:00 0.05 74
USC00513117 2016-05-19 00:00:00 0.05 75
USC00513117 2016-05-20 00:00:00 0.15 75
USC00513117 2016-05-21 00:00:00 0.08 75
USC00513117 2016-05-22 00:00:00 0.0 75
USC00513117 2016-05-23 00:00:00 0.0 75
USC00513117 2016-05-24 00:00:00 0.0 75
USC00513117 2016-05-25 00:00:00 0.0 74
USC00513117 2016-05-26 00:00:00 0.8 72
USC00513117 2016-05-27 00:00:00 0.05 76
USC00513117 2016-05-28 00:00:00 0.0 76
USC00513117 2016-05-29 00:00:00 0.0 71
USC00513117 2016-05-30 00:00:00 0.03 72
USC00513117 2016-05-31 00:00:00 0.18 72
USC00513117 2016-06-01 00:00:00 0.89 70
USC00513117 2016-06-02 00:00:00 0.15 69
USC00513117 2016-06-03 00:00:00 0.16 70
USC00513117 2016-06-04 00:00:00 0.0 68
USC00513117 2016-06-05 00:00:00 0.63 70
USC00513117 2016-06-06 00:00:00 0.36 74
USC00513117 2016-06-07 00:00:00 0.4 75
USC00513117 2016-06-08 00:00:00 0.0 74
USC00513117 2016-06-09 00:00:00 0.21 71
USC00513117 2016-06-10 00:00:00 0.06 73
USC00513117 2016-06-11 00:00:00 0.02 75
USC00513117 2016-06-12 00:00:00 0.04 74
USC00513117 2016-06-13 00:00:00 0.08 76
USC00513117 2016-06-14 00:00:00 0.06 76
USC00513117 2016-06-15 00:00:00 0.18 76
USC00513117 2016-06-16 00:00:00 0.03 76
USC00513117 2016-06-17 00:00:00 0.16 75
USC00513117 2016-06-18 00:00:00 0.3 75
USC00513117 2016-06-19 00:00:00 0.02 75
USC00513117 2016-06-20 00:00:00 0.16 74
USC00513117 2016-06-21 00:00:00 0.03 73
USC00513117 2016-06-22 00:00:00 0.01 76
USC00513117 2016-06-23 00:00:00 0.25 74
USC00513117 2016-06-24 00:00:00 0.02 78
USC00513117 2016-06-25 00:00:00 0.8 71
USC00513117 2016-06-26 00:00:00 0.06 75
USC00513117 2016-06-27 00:00:00 0.06 75
USC00513117 2016-06-28 00:00:00 0.02 74
USC00513117 2016-06-29 00:00:00 0.03 77
USC00513117 2016-06-30 00:00:00 0.0 77
USC00513117 2016-07-01 00:00:00 0.0 76
USC00513117 2016-07-02 00:00:00 0.0 77
USC00513117 2016-07-03 00:00:00 0.0 77
USC00513117 2016-07-04 00:00:00 0.14 76
USC00513117 2016-07-05 00:00:00 0.05 75
USC00513117 2016-07-06 00:00:00 0.49 74
USC00513117 2016-07-07 00:00:00 0.05 75
USC00513117 2016-07-08 00:00:00 0.03 76
USC00513117 2016-07-09 00:00:00 0.0 76
USC00513117 2016-07-10 00:00:00 0.14 75
USC00513117 2016-07-11 00:00:00 0.11 73
USC00513117 2016-07-12 00:00:00 0.05 77
USC00513117 2016-07-13 00:00:00 0.06 74
USC00513117 2016-07-14 00:00:00 0.43 75
USC00513117 2016-07-15 00:00:00 0.23 74
USC00513117 2016-07-16 00:00:00 0.44 75
USC00513117 2016-07-17 00:00:00 0.03 76
USC00513117 2016-07-18 00:00:00 0.26 76
USC00513117 2016-07-19 00:00:00 0.08 75
USC00513117 2016-07-20 00:00:00 0.0 78
USC00513117 2016-07-21 00:00:00 0.04 77
USC00513117 2016-07-22 00:00:00 0.06 77
USC00513117 2016-07-23 00:00:00 0.16 76
USC00513117 2016-07-24 00:00:00 0.15 78
USC00513117 2016-07-25 00:00:00 7.65 78
USC00513117 2016-07-26 00:00:00 0.0 77
USC00513117 2016-07-27 00:00:00 0.02 78
USC00513117 2016-07-28 00:00:00 0.0 78
USC00513117 2016-07-29 00:00:00 0.0 77
USC00513117 2016-07-30 00:00:00 0.03 76
USC00513117 2016-07-31 00:00:00 0.05 76
USC00513117 2016-08-01 00:00:00 2.35 76
USC00513117 2016-08-02 00:00:00 0.2 75
USC00513117 2016-08-03 00:00:00 0.02 76
USC00513117 2016-08-04 00:00:00 0.62 76
USC00513117 2016-08-05 00:00:00 0.03 78
USC00513117 2016-08-06 00:00:00 0.07 76
USC00513117 2016-08-07 00:00:00 0.3 77
USC00513117 2016-08-08 00:00:00 0.33 78
USC00513117 2016-08-09 00:00:00 0.0 77
USC00513117 2016-08-10 00:00:00 0.0 78
USC00513117 2016-08-11 00:00:00 0.04 77
USC00513117 2016-08-12 00:00:00 0.05 76
USC00513117 2016-08-13 00:00:00 0.0 77
USC00513117 2016-08-14 00:00:00 0.17 77
USC00513117 2016-08-15 00:00:00 0.17 77
USC00513117 2016-08-16 00:00:00 0.1 77
USC00513117 2016-08-17 00:00:00 0.0 73
USC00513117 2016-08-18 00:00:00 0.0 78
USC00513117 2016-08-19 00:00:00 0.14 77
USC00513117 2016-08-20 00:00:00 0.03 79
USC00513117 2016-08-21 00:00:00 0.32 76
USC00513117 2016-08-22 00:00:00 0.94 76
USC00513117 2016-08-23 00:00:00 0.15 76
USC00513117 2016-08-24 00:00:00 2.15 76
USC00513117 2016-08-25 00:00:00 0.08 77
USC00513117 2016-08-26 00:00:00 0.03 78
USC00513117 2016-08-27 00:00:00 0.18 73
USC00513117 2016-08-28 00:00:00 0.14 73
USC00513117 2016-08-29 00:00:00 0.17 78
USC00513117 2016-08-30 00:00:00 0.0 76
USC00513117 2016-08-31 00:00:00 0.1 77
USC00513117 2016-09-01 00:00:00 0.0 79
USC00513117 2016-09-02 00:00:00 0.02 78
USC00513117 2016-09-03 00:00:00 0.07 77
USC00513117 2016-09-04 00:00:00 0.03 75
USC00513117 2016-09-05 00:00:00 0.11 78
USC00513117 2016-09-06 00:00:00 0.05 74

USC00513117 2016-09-07 00:00:00 0.1 75
USC00513117 2016-09-08 00:00:00 0.22 77
USC00513117 2016-09-09 00:00:00 0.01 76
USC00513117 2016-09-10 00:00:00 0.01 76
USC00513117 2016-09-11 00:00:00 0.18 76
USC00513117 2016-09-12 00:00:00 0.04 76
USC00513117 2016-09-13 00:00:00 0.37 76
USC00513117 2016-09-14 00:00:00 0.9 76
USC00513117 2016-09-15 00:00:00 0.12 78
USC00513117 2016-09-16 00:00:00 0.01 78
USC00513117 2016-09-17 00:00:00 0.04 78
USC00513117 2016-09-18 00:00:00 0.0 78
USC00513117 2016-09-19 00:00:00 0.01 75
USC00513117 2016-09-20 00:00:00 0.09 78
USC00513117 2016-09-21 00:00:00 0.06 76
USC00513117 2016-09-22 00:00:00 0.09 77
USC00513117 2016-09-23 00:00:00 0.15 76
USC00513117 2016-09-24 00:00:00 0.0 79
USC00513117 2016-09-25 00:00:00 0.02 77
USC00513117 2016-09-26 00:00:00 0.06 77
USC00513117 2016-09-27 00:00:00 0.12 77
USC00513117 2016-09-28 00:00:00 0.08 77
USC00513117 2016-09-29 00:00:00 0.49 76
USC00513117 2016-09-30 00:00:00 0.31 77
USC00513117 2016-10-01 00:00:00 0.14 75
USC00513117 2016-10-02 00:00:00 0.02 77
USC00513117 2016-10-03 00:00:00 0.04 78
USC00513117 2016-10-04 00:00:00 0.0 78
USC00513117 2016-10-05 00:00:00 0.0 77
USC00513117 2016-10-06 00:00:00 0.05 76
USC00513117 2016-10-07 00:00:00 0.0 78
USC00513117 2016-10-08 00:00:00 0.0 76
USC00513117 2016-10-09 00:00:00 0.0 77
USC00513117 2016-10-10 00:00:00 0.0 75
USC00513117 2016-10-11 00:00:00 0.02 77
USC00513117 2016-10-12 00:00:00 0.03 75
USC00513117 2016-10-13 00:00:00 0.0 78
USC00513117 2016-10-14 00:00:00 0.0 77
USC00513117 2016-10-15 00:00:00 0.0 76
USC00513117 2016-10-16 00:00:00 0.0 75
USC00513117 2016-10-17 00:00:00 0.03 77
USC00513117 2016-10-18 00:00:00 0.05 77
USC00513117 2016-10-19 00:00:00 0.06 77
USC00513117 2016-10-20 00:00:00 0.0 76
USC00513117 2016-10-21 00:00:00 0.15 76
USC00513117 2016-10-22 00:00:00 0.1 77
USC00513117 2016-10-23 00:00:00 0.01 76
USC00513117 2016-10-24 00:00:00 0.0 76
USC00513117 2016-10-25 00:00:00 0.04 77
USC00513117 2016-10-26 00:00:00 0.06 74
USC00513117 2016-10-27 00:00:00 0.11 75
USC00513117 2016-10-28 00:00:00 0.02 77
USC00513117 2016-10-29 00:00:00 0.02 77
USC00513117 2016-10-30 00:00:00 0.1 78
USC00513117 2016-10-31 00:00:00 0.03 76
USC00513117 2016-11-01 00:00:00 0.01 77
USC00513117 2016-11-02 00:00:00 0.0 76
USC00513117 2016-11-03 00:00:00 0.0 74
USC00513117 2016-11-04 00:00:00 0.0 76
USC00513117 2016-11-05 00:00:00 0.02 72
USC00513117 2016-11-06 00:00:00 0.02 76
USC00513117 2016-11-07 00:00:00 0.0 69
USC00513117 2016-11-08 00:00:00 0.14 71
USC00513117 2016-11-09 00:00:00 0.08 70
USC00513117 2016-11-10 00:00:00 0.0 69
USC00513117 2016-11-11 00:00:00 0.0 71
USC00513117 2016-11-12 00:00:00 0.0 68
USC00513117 2016-11-13 00:00:00 0.0 72
USC00513117 2016-11-14 00:00:00 0.06 76
USC00513117 2016-11-15 00:00:00 0.0 78
USC00513117 2016-11-16 00:00:00 0.14 76
USC00513117 2016-11-17 00:00:00 0.03 75
USC00513117 2016-11-18 00:00:00 0.01 78
USC00513117 2016-11-19 00:00:00 0.11 73
USC00513117 2016-11-20 00:00:00 0.11 75
USC00513117 2016-11-21 00:00:00 0.02 75
USC00513117 2016-11-22 00:00:00 0.41 76
USC00513117 2016-11-23 00:00:00 0.03 75
USC00513117 2016-11-24 00:00:00 0.2 75
USC00513117 2016-11-25 00:00:00 0.05 76
USC00513117 2016-11-26 00:00:00 0.05 76
USC00513117 2016-11-27 00:00:00 0.06 75
USC00513117 2016-11-28 00:00:00 0.02 75
USC00513117 2016-11-29 00:00:00 0.04 74
USC00513117 2016-11-30 00:00:00 0.05 74
USC00513117 2016-12-01 00:00:00 0.33 73
USC00513117 2016-12-02 00:00:00 0.3 71
USC00513117 2016-12-03 00:00:00 0.04 71
USC00513117 2016-12-04 00:00:00 0.1 69
USC00513117 2016-12-05 00:00:00 0.34 68
USC00513117 2016-12-06 00:00:00 0.02 70
USC00513117 2016-12-07 00:00:00 0.17 71
USC00513117 2016-12-08 00:00:00 0.03 72
USC00513117 2016-12-09 00:00:00 0.34 70
USC00513117 2016-12-10 00:00:00 0.02 71
USC00513117 2016-12-11 00:00:00 0.02 72
USC00513117 2016-12-12 00:00:00 0.01 68
USC00513117 2016-12-13 00:00:00 0.1 68
USC00513117 2016-12-14 00:00:00 0.05 70
USC00513117 2016-12-15 00:00:00 0.02 70
USC00513117 2016-12-16 00:00:00 0.01 63
USC00513117 2016-12-17 00:00:00 0.11 71
USC00513117 2016-12-18 00:00:00 0.29 67
USC00513117 2016-12-19 00:00:00 0.21 69
USC00513117 2016-12-20 00:00:00 0.02 74
USC00513117 2016-12-21 00:00:00 0.03 72
USC00513117 2016-12-22 00:00:00 0.17 70
USC00513117 2016-12-23 00:00:00 0.1 69
USC00513117 2016-12-24 00:00:00 0.14 73
USC00513117 2016-12-25 00:00:00 0.03 74
USC00513117 2016-12-26 00:00:00 0.26 74
USC00513117 2016-12-27 00:00:00 0.03 73
USC00513117 2016-12-28 00:00:00 0.09 71
USC00513117 2016-12-29 00:00:00 0.18 72
USC00513117 2016-12-30 00:00:00 0.21 69
USC00513117 2016-12-31 00:00:00 0.62 71
USC00513117 2017-01-01 00:00:00 0.29 66
USC00513117 2017-01-02 00:00:00 0.0 66
USC00513117 2017-01-03 00:00:00 0.0 65
USC00513117 2017-01-04 00:00:00 0.0 64
USC00513117 2017-01-05 00:00:00 0.0 65
USC00513117 2017-01-06 00:00:00 0.0 70
USC00513117 2017-01-07 00:00:00 0.06 72
USC00513117 2017-01-08 00:00:00 0.0 62
USC00513117 2017-01-09 00:00:00 0.0 65
USC00513117 2017-01-10 00:00:00 0.0 66
USC00513117 2017-01-11 00:00:00 0.0 66
USC00513117 2017-01-12 00:00:00 0.0 67
USC00513117 2017-01-13 00:00:00 0.0 70
USC00513117 2017-01-14 00:00:00 0.0 66
USC00513117 2017-01-15 00:00:00 0.0 67
USC00513117 2017-01-16 00:00:00 0.0 69
USC00513117 2017-01-17 00:00:00 0.0 74
USC00513117 2017-01-18 00:00:00 0.0 73
USC00513117 2017-01-19 00:00:00 0.0 74
USC00513117 2017-01-20 00:00:00 0.0 73
USC00513117 2017-01-21 00:00:00 0.04 72
USC00513117 2017-01-22 00:00:00 0.01 71
USC00513117 2017-01-23 00:00:00 0.08 71
USC00513117 2017-01-24 00:00:00 0.15 71
USC00513117 2017-01-25 00:00:00 0.12 73
USC00513117 2017-01-26 00:00:00 0.0 72
USC00513117 2017-01-27 00:00:00 0.0 63
USC00513117 2017-01-28 00:00:00 0.14 71
USC00513117 2017-01-29 00:00:00 0.0 71
USC00513117 2017-01-30 00:00:00 0.0 69
USC00513117 2017-01-31 00:00:00 0.0 69
USC00513117 2017-02-01 00:00:00 0.0 69
USC00513117 2017-02-02 00:00:00 0.0 63
USC00513117 2017-02-03 00:00:00 0.0 64
USC00513117 2017-02-04 00:00:00 0.0 67
USC00513117 2017-02-05 00:00:00 0.0 75
USC00513117 2017-02-06 00:00:00 0.16 74
USC00513117 2017-02-07 00:00:00 1.08 67
USC00513117 2017-02-08 00:00:00 1.08 67
USC00513117 2017-02-09 00:00:00 0.02 64
USC00513117 2017-02-10 00:00:00 0.0 64
USC00513117 2017-02-11 00:00:00 1.0 65
USC00513117 2017-02-12 00:00:00 1.07 67
USC00513117 2017-02-13 00:00:00 2.9 69
USC00513117 2017-02-14 00:00:00 0.0 72
USC00513117 2017-02-15 00:00:00 0.0 76
USC00513117 2017-02-16 00:00:00 0.0 74
USC00513117 2017-02-17 00:00:00 0.8 67
USC00513117 2017-02-18 00:00:00 0.0 71
USC00513117 2017-02-19 00:00:00 0.0 70
USC00513117 2017-02-20 00:00:00 0.0 71
USC00513117 2017-02-21 00:00:00 0.0 70
USC00513117 2017-02-22 00:00:00 0.06 70
USC00513117 2017-02-23 00:00:00 0.0 70
USC00513117 2017-02-24 00:00:00 0.0 70
USC00513117 2017-02-25 00:00:00 0.0 63
USC00513117 2017-02-26 00:00:00 0.0 63
USC00513117 2017-02-27 00:00:00 0.0 66
USC00513117 2017-02-28 00:00:00 0.16 73
USC00513117 2017-03-01 00:00:00 2.2 72
USC00513117 2017-03-02 00:00:00 1.45 73
USC00513117 2017-03-03 00:00:00 0.54 73
USC00513117 2017-03-04 00:00:00 0.0 76
USC00513117 2017-03-05 00:00:00 0.1 70
USC00513117 2017-03-06 00:00:00 0.51 66
USC00513117 2017-03-07 00:00:00 0.0 65
USC00513117 2017-03-08 00:00:00 0.0 70
USC00513117 2017-03-09 00:00:00 0.8 67
USC00513117 2017-03-10 00:00:00 0.13 68
USC00513117 2017-03-11 00:00:00 0.03 68
USC00513117 2017-03-12 00:00:00 0.0 70
USC00513117 2017-03-13 00:00:00 0.0 70
USC00513117 2017-03-14 00:00:00 0.0 70
USC00513117 2017-03-15 00:00:00 0.0 71
USC00513117 2017-03-16 00:00:00 0.0 69
USC00513117 2017-03-17 00:00:00 0.19 69
USC00513117 2017-03-18 00:00:00 0.0 67
USC00513117 2017-03-19 00:00:00 0.0 72
USC00513117 2017-03-20 00:00:00 0.0 72
USC00513117 2017-03-21 00:00:00 0.0 73
USC00513117 2017-03-22 00:00:00 0.0 74
USC00513117 2017-03-23 00:00:00 0.0 74
USC00513117 2017-03-24 00:00:00 0.6 72
USC00513117 2017-03-25 00:00:00 0.13 72
USC00513117 2017-03-26 00:00:00 0.0 75
USC00513117 2017-03-27 00:00:00 0.0 74
USC00513117 2017-03-28 00:00:00 0.03 75
USC00513117 2017-03-29 00:00:00 0.0 73
USC00513117 2017-03-30 00:00:00 0.08 74
USC00513117 2017-03-31 00:00:00 0.0 74
USC00513117 2017-04-01 00:00:00 0.0 76
USC00513117 2017-04-02 00:00:00 0.0 74
USC00513117 2017-04-03 00:00:00 0.08 73
USC00513117 2017-04-04 00:00:00 0.04 72
USC00513117 2017-04-05 00:00:00 0.04 72
USC00513117 2017-04-06 00:00:00 0.0 73
USC00513117 2017-04-07 00:00:00 0.0 74
USC00513117 2017-04-08 00:00:00 0.0 73
USC00513117 2017-04-09 00:00:00 0.0 69
USC00513117 2017-04-10 00:00:00 0.01 71
USC00513117 2017-04-11 00:00:00 0.03 75
USC00513117 2017-04-12 00:00:00 0.03 74
USC00513117 2017-04-13 00:00:00 0.27 71
USC00513117 2017-04-14 00:00:00 0.69 70
USC00513117 2017-04-15 00:00:00 0.45 70
USC00513117 2017-04-16 00:00:00 0.49 69
USC00513117 2017-04-17 00:00:00 0.41 69
USC00513117 2017-04-18 00:00:00 0.08 70
USC00513117 2017-04-19 00:00:00 0.02 70
USC00513117 2017-04-20 00:00:00 0.33 75
USC00513117 2017-04-21 00:00:00 1.16 70
USC00513117 2017-04-22 00:00:00 1.01 74
USC00513117 2017-04-23 00:00:00 0.02 75
USC00513117 2017-04-24 00:00:00 0.0 76
USC00513117 2017-04-25 00:00:00 0.0 75
USC00513117 2017-04-26 00:00:00 0.0 78
USC00513117 2017-04-27 00:00:00 0.1 73
USC00513117 2017-04-28 00:00:00 2.6 70
USC00513117 2017-04-29 00:00:00 0.35 66
USC00513117 2017-04-30 00:00:00 1.21 61
USC00513117 2017-05-01 00:00:00 0.07 68
USC00513117 2017-05-02 00:00:00 0.03 73
USC00513117 2017-05-03 00:00:00 0.01 74
USC00513117 2017-05-04 00:00:00 0.0 77
USC00513117 2017-05-05 00:00:00 0.0 78
USC00513117 2017-05-06 00:00:00 0.0 75
USC00513117 2017-05-07 00:00:00 0.07 75
USC00513117 2017-05-08 00:00:00 0.22 71
USC00513117 2017-05-09 00:00:00 1.62 74
USC00513117 2017-05-10 00:00:00 0.05 75
USC00513117 2017-05-11 00:00:00 0.03 74
USC00513117 2017-05-12 00:00:00 0.04 74
USC00513117 2017-05-13 00:00:00 0.02 75
USC00513117 2017-05-14 00:00:00 0.05 75
USC00513117 2017-05-15 00:00:00 0.08 75
USC00513117 2017-05-16 00:00:00 0.03 75
USC00513117 2017-05-17 00:00:00 0.02 75
USC00513117 2017-05-18 00:00:00 0.09 70
USC00513117 2017-05-19 00:00:00 0.02 70
USC00513117 2017-05-20 00:00:00 0.0 72
USC00513117 2017-05-21 00:00:00 0.0 72
USC00513117 2017-05-22 00:00:00 0.0 76
USC00513117 2017-05-23 00:00:00 0.02 73
USC00513117 2017-05-24 00:00:00 0.58 75
USC00513117 2017-05-25 00:00:00 0.37 69
USC00513117 2017-05-26 00:00:00 0.02 73
USC00513117 2017-05-27 00:00:00 0.0 69
USC00513117 2017-05-28 00:00:00 0.29 71
USC00513117 2017-05-29 00:00:00 0.02 71
USC00513117 2017-05-30 00:00:00 0.2 74
USC00513117 2017-05-31 00:00:00 0.1 76
USC00513117 2017-06-01 00:00:00 0.03 76
USC00513117 2017-06-02 00:00:00 0.1 76
USC00513117 2017-06-03 00:00:00 0.2 76
USC00513117 2017-06-04 00:00:00 0.15 78
USC00513117 2017-06-05 00:00:00 0.0 76
USC00513117 2017-06-06 00:00:00 0.0 75
USC00513117 2017-06-07 00:00:00 0.0 75
USC00513117 2017-06-08 00:00:00 0.02 76
USC00513117 2017-06-09 00:00:00 0.02 78
USC00513117 2017-06-10 00:00:00 0.21 75
USC00513117 2017-06-11 00:00:00 0.24 73
USC00513117 2017-06-12 00:00:00 0.19 76
USC00513117 2017-06-13 00:00:00 0.36 76
USC00513117 2017-06-14 00:00:00 0.27 76
USC00513117 2017-06-15 00:00:00 0.17 77
USC00513117 2017-06-16 00:00:00 0.02 76
USC00513117 2017-06-17 00:00:00 0.35 77
USC00513117 2017-06-18 00:00:00 0.25 72
USC00513117 2017-06-19 00:00:00 0.05 77
USC00513117 2017-06-20 00:00:00 0.05 75
USC00513117 2017-06-21 00:00:00 0.02 82
USC00513117 2017-06-22 00:00:00 0.1 77
USC00513117 2017-06-23 00:00:00 0.0 76
USC00513117 2017-06-24 00:00:00 0.0 74
USC00513117 2017-06-25 00:00:00 0.08 73
USC00513117 2017-06-26 00:00:00 0.02 77
USC00513117 2017-06-27 00:00:00 0.0 77
USC00513117 2017-06-28 00:00:00 0.01 77
USC00513117 2017-06-29 00:00:00 0.03 76
USC00513117 2017-06-30 00:00:00 0.04 74
USC00513117 2017-07-01 00:00:00 0.06 76
USC00513117 2017-07-02 00:00:00 0.05 77
USC00513117 2017-07-03 00:00:00 0.13 77
USC00513117 2017-07-04 00:00:00 0.03 77
USC00513117 2017-07-05 00:00:00 0.0 77
USC00513117 2017-07-06 00:00:00 0.0 76
USC00513117 2017-07-07 00:00:00 0.02 77
USC00513117 2017-07-08 00:00:00 0.02 76
USC00513117 2017-07-09 00:00:00 0.09 76
USC00513117 2017-07-10 00:00:00 0.0 79
USC00513117 2017-07-11 00:00:00 0.01 76
USC00513117 2017-07-12 00:00:00 0.01 78
USC00513117 2017-07-13 00:00:00 0.33 76
USC00513117 2017-07-14 00:00:00 0.05 80
USC00513117 2017-07-15 00:00:00 0.03 79
USC00513117 2017-07-16 00:00:00 0.07 76
USC00513117 2017-07-17 00:00:00 0.12 75
USC00513117 2017-07-18 00:00:00 0.03 78
USC00513117 2017-07-19 00:00:00 0.0 78
USC00513117 2017-07-20 00:00:00 0.12 78
USC00513117 2017-07-21 00:00:00 0.0 78
USC00513117 2017-07-22 00:00:00 0.07 78
USC00513117 2017-07-23 00:00:00 0.06 75
USC00513117 2017-07-24 00:00:00 0.58 78
USC00513117 2017-07-25 00:00:00 0.03 78
USC00513117 2017-07-26 00:00:00 0.06 78
USC00513117 2017-07-27 00:00:00 0.0 77
USC00513117 2017-07-28 00:00:00 0.13 77
USC00513117 2017-07-29 00:00:00 0.06 78
USC00513117 2017-07-30 00:00:00 0.0 78
USC00513117 2017-07-31 00:00:00 0.0 77
USC00514830 KUALOA RANCH HEADQUARTERS 886.9, HI US
USC00514830 2010-03-01 00:00:00 0.01 67
USC00514830 2010-03-02 00:00:00 0.0 70
USC00514830 2010-03-03 00:00:00 0.01 68
USC00514830 2010-03-04 00:00:00 0.48 67
USC00514830 2010-03-05 00:00:00 0.22 67
USC00514830 2010-03-06 00:00:00 0.06 74
USC00514830 2010-03-09 00:00:00 0.03 70
USC00514830 2010-03-10 00:00:00 0.03 70
USC00514830 2010-03-11 00:00:00 0.32 72
USC00514830 2010-03-12 00:00:00 0.02 67
USC00514830 2010-03-14 00:00:00 0.0 70
USC00514830 2010-03-15 00:00:00 0.03 70
USC00514830 2010-03-18 00:00:00 0.54 66
USC00514830 2010-03-19 00:00:00 0.07 66
USC00514830 2010-03-20 00:00:00 0.0 68
USC00514830 2010-03-21 00:00:00 0.0 72
USC00514830 2010-03-22 00:00:00 0.0 71
USC00514830 2010-03-23 00:00:00 0.0 70
USC00514830 2010-03-24 00:00:00 0.02 72
USC00514830 2010-03-25 00:00:00 0.13 72
USC00514830 2010-03-26 00:00:00 0.03 70
USC00514830 2010-03-27 00:00:00 0.0 74
USC00514830 2010-03-28 00:00:00 0.0 72
USC00514830 2010-03-29 00:00:00 0.01 70
USC00514830 2010-03-30 00:00:00 0.03 71
USC00514830 2010-03-31 00:00:00 0.04 67
USC00514830 2010-04-01 00:00:00 0.02 69
USC00514830 2010-04-02 00:00:00 0.05 71
USC00514830 2010-04-05 00:00:00 0.1 70
USC00514830 2010-04-06 00:00:00 0.15 70
USC00514830 2010-04-07 00:00:00 0.05 71
USC00514830 2010-04-08 00:00:00 0.32 72
USC00514830 2010-04-09 00:00:00 0.04 71
USC00514830 2010-04-10 00:00:00 0.05 75
USC00514830 2010-04-11 00:00:00 0.09 68
USC00514830 2010-04-12 00:00:00 0.0 70
USC00514830 2010-04-13 00:00:00 0.02 68
USC00514830 2010-04-14 00:00:00 0.0 67
USC00514830 2010-04-15 00:00:00 0.0 68
USC00514830 2010-04-16 00:00:00 0.02 68
USC00514830 2010-04-17 00:00:00 0.0 70
USC00514830 2010-04-18 00:00:00 0.0 68
USC00514830 2010-04-19 00:00:00 0.0 70
USC00514830 2010-04-20 00:00:00 0.18 70
USC00514830 2010-04-21 00:00:00 0.06 71
USC00514830 2010-04-22 00:00:00 0.07 69
USC00514830 2010-04-23 00:00:00 0.05 72
USC00514830 2010-04-24 00:00:00 0.01 73
USC00514830 2010-04-25 00:00:00 0.0 73
USC00514830 2010-04-26 00:00:00 0.0 74

USC00514830 2010-04-27 00:00:00 0.02 73
USC00514830 2010-04-28 00:00:00 0.09 71
USC00514830 2010-04-29 00:00:00 0.01 72
USC00514830 2010-04-30 00:00:00 0.02 72
USC00514830 2010-05-01 00:00:00 0.24 72
USC00514830 2010-05-02 00:00:00 0.02 71
USC00514830 2010-05-03 00:00:00 0.75 70
USC00514830 2010-05-04 00:00:00 0.0 74
USC00514830 2010-05-05 00:00:00 0.0 72
USC00514830 2010-05-06 00:00:00 0.0 73
USC00514830 2010-05-09 00:00:00 0.0 73
USC00514830 2010-05-10 00:00:00 0.04 72
USC00514830 2010-05-11 00:00:00 0.01 74
USC00514830 2010-05-12 00:00:00 0.03 72
USC00514830 2010-05-13 00:00:00 0.02 71
USC00514830 2010-05-14 00:00:00 0.0 75
USC00514830 2010-05-15 00:00:00 0.1 75
USC00514830 2010-05-17 00:00:00 0.0 73
USC00514830 2010-05-18 00:00:00 0.0 73
USC00514830 2010-05-19 00:00:00 0.0 73
USC00514830 2010-05-22 00:00:00 0.01 76
USC00514830 2010-05-23 00:00:00 0.11 71
USC00514830 2010-05-24 00:00:00 0.12 73
USC00514830 2010-05-25 00:00:00 0.13 72
USC00514830 2010-05-26 00:00:00 0.11 72
USC00514830 2010-05-27 00:00:00 0.0 75
USC00514830 2010-05-28 00:00:00 0.0 74
USC00514830 2010-05-29 00:00:00 0.0 74
USC00514830 2010-05-30 00:00:00 0.04 73
USC00514830 2010-05-31 00:00:00 0.0 75
USC00514830 2010-06-01 00:00:00 0.01 73
USC00514830 2010-06-02 00:00:00 0.0 72
USC00514830 2010-06-03 00:00:00 0.0 74
USC00514830 2010-06-04 00:00:00 0.0 73
USC00514830 2010-06-05 00:00:00 0.0 72
USC00514830 2010-06-06 00:00:00 0.0 75
USC00514830 2010-06-07 00:00:00 0.09 74
USC00514830 2010-06-08 00:00:00 0.0 75
USC00514830 2010-06-09 00:00:00 0.0 73
USC00514830 2010-06-10 00:00:00 0.0 75
USC00514830 2010-06-11 00:00:00 0.0 76
USC00514830 2010-06-12 00:00:00 0.03 74
USC00514830 2010-06-13 00:00:00 0.0 74
USC00514830 2010-06-14 00:00:00 0.06 73
USC00514830 2010-06-15 00:00:00 0.03 73
USC00514830 2010-06-16 00:00:00 0.0 76
USC00514830 2010-06-17 00:00:00 0.0 75
USC00514830 2010-06-18 00:00:00 0.03 70
USC00514830 2010-06-19 00:00:00 0.04 75
USC00514830 2010-06-20 00:00:00 0.0 73
USC00514830 2010-06-21 00:00:00 0.0 74
USC00514830 2010-06-22 00:00:00 0.0 74
USC00514830 2010-06-23 00:00:00 0.0 74
USC00514830 2010-06-24 00:00:00 0.05 74
USC00514830 2010-06-25 00:00:00 0.12 70
USC00514830 2010-06-28 00:00:00 0.18 74
USC00514830 2010-06-29 00:00:00 0.06 73
USC00514830 2010-06-30 00:00:00 0.03 74
USC00514830 2010-07-01 00:00:00 0.02 71
USC00514830 2010-07-02 00:00:00 0.32 69
USC00514830 2010-07-03 00:00:00 0.16 73
USC00514830 2010-07-04 00:00:00 0.08 72
USC00514830 2010-07-05 00:00:00 0.0 76
USC00514830 2010-07-06 00:00:00 0.15 73
USC00514830 2010-07-07 00:00:00 0.09 71
USC00514830 2010-07-08 00:00:00 0.14 70
USC00514830 2010-07-09 00:00:00 0.01 74
USC00514830 2010-07-10 00:00:00 0.06 71
USC00514830 2010-07-12 00:00:00 0.0 73
USC00514830 2010-07-13 00:00:00 0.0 72
USC00514830 2010-07-14 00:00:00 0.03 72
USC00514830 2010-07-15 00:00:00 0.13 75
USC00514830 2010-07-16 00:00:00 0.02 74
USC00514830 2010-07-19 00:00:00 0.14 69
USC00514830 2010-07-20 00:00:00 0.17 75
USC00514830 2010-07-21 00:00:00 0.0 75
USC00514830 2010-07-22 00:00:00 0.11 75
USC00514830 2010-07-23 00:00:00 0.07 70
USC00514830 2010-07-26 00:00:00 0.0 75
USC00514830 2010-07-27 00:00:00 0.43 69
USC00514830 2010-07-28 00:00:00 0.03 74
USC00514830 2010-07-29 00:00:00 0.0 76
USC00514830 2010-07-30 00:00:00 0.06 75
USC00514830 2010-07-31 00:00:00 0.01 73
USC00514830 2010-08-01 00:00:00 0.25 71
USC00514830 2010-08-02 00:00:00 0.11 73
USC00514830 2010-08-03 00:00:00 0.04 71
USC00514830 2010-08-04 00:00:00 0.05 74
USC00514830 2010-08-05 00:00:00 0.29 72
USC00514830 2010-08-06 00:00:00 0.0 75
USC00514830 2010-08-07 00:00:00 0.09 76
USC00514830 2010-08-08 00:00:00 0.07 73
USC00514830 2010-08-09 00:00:00 0.04 74
USC00514830 2010-08-10 00:00:00 0.0 74
USC00514830 2010-08-11 00:00:00 0.01 73
USC00514830 2010-08-12 00:00:00 0.01 75
USC00514830 2010-08-13 00:00:00 0.01 76
USC00514830 2010-08-14 00:00:00 0.0 75
USC00514830 2010-08-15 00:00:00 0.0 75
USC00514830 2010-08-16 00:00:00 0.14 71
USC00514830 2010-08-17 00:00:00 0.0 73
USC00514830 2010-08-18 00:00:00 0.05 75
USC00514830 2010-08-19 00:00:00 0.13 76
USC00514830 2010-08-20 00:00:00 0.01 75
USC00514830 2010-08-21 00:00:00 0.0 74
USC00514830 2010-08-22 00:00:00 0.0 72
USC00514830 2010-08-23 00:00:00 0.0 77
USC00514830 2010-08-24 00:00:00 0.0 75
USC00514830 2010-08-25 00:00:00 0.02 75
USC00514830 2010-08-26 00:00:00 0.08 71
USC00514830 2010-08-27 00:00:00 0.15 75
USC00514830 2010-08-28 00:00:00 0.01 75
USC00514830 2010-08-29 00:00:00 0.1 74
USC00514830 2010-08-30 00:00:00 0.0 75
USC00514830 2010-08-31 00:00:00 0.0 73
USC00514830 2010-09-01 00:00:00 0.01 72
USC00514830 2010-09-02 00:00:00 0.06 71
USC00514830 2010-09-03 00:00:00 0.11 74
USC00514830 2010-09-04 00:00:00 0.0 76
USC00514830 2010-09-05 00:00:00 0.11 75
USC00514830 2010-09-06 00:00:00 0.03 77
USC00514830 2010-09-07 00:00:00 0.1 75
USC00514830 2010-09-08 00:00:00 0.05 75
USC00514830 2010-09-09 00:00:00 0.04 75
USC00514830 2010-09-10 00:00:00 0.01 75
USC00514830 2010-09-11 00:00:00 0.0 76
USC00514830 2010-09-12 00:00:00 0.0 76
USC00514830 2010-09-13 00:00:00 0.0 75
USC00514830 2010-09-14 00:00:00 0.04 75
USC00514830 2010-09-15 00:00:00 0.01 74
USC00514830 2010-09-16 00:00:00 0.02 76
USC00514830 2010-09-17 00:00:00 0.03 75
USC00514830 2010-09-18 00:00:00 0.0 75
USC00514830 2010-09-19 00:00:00 0.06 74
USC00514830 2010-09-20 00:00:00 0.03 74
USC00514830 2010-09-21 00:00:00 0.01 74
USC00514830 2010-09-22 00:00:00 0.41 71
USC00514830 2010-09-23 00:00:00 0.57 75
USC00514830 2010-09-24 00:00:00 0.0 76
USC00514830 2010-09-25 00:00:00 0.0 75
USC00514830 2010-09-26 00:00:00 0.0 75
USC00514830 2010-09-27 00:00:00 0.0 73
USC00514830 2010-09-28 00:00:00 0.01 76
USC00514830 2010-09-29 00:00:00 0.0 73
USC00514830 2010-09-30 00:00:00 0.03 73
USC00514830 2010-10-01 00:00:00 0.3 71
USC00514830 2010-10-02 00:00:00 0.09 75
USC00514830 2010-10-03 00:00:00 0.01 76
USC00514830 2010-10-04 00:00:00 0.11 74
USC00514830 2010-10-05 00:00:00 0.02 76
USC00514830 2010-10-06 00:00:00 0.0 75
USC00514830 2010-10-07 00:00:00 0.0 75
USC00514830 2010-10-08 00:00:00 0.0 75
USC00514830 2010-10-09 00:00:00 0.0 75
USC00514830 2010-10-10 00:00:00 0.03 74
USC00514830 2010-10-11 00:00:00 0.04 74
USC00514830 2010-10-12 00:00:00 0.03 74
USC00514830 2010-10-13 00:00:00 0.01 75
USC00514830 2010-10-14 00:00:00 0.0 75
USC00514830 2010-10-15 00:00:00 0.0 75
USC00514830 2010-10-18 00:00:00 0.0 74
USC00514830 2010-10-19 00:00:00 0.01 71
USC00514830 2010-10-20 00:00:00 0.0 73
USC00514830 2010-10-21 00:00:00 0.82 72
USC00514830 2010-10-22 00:00:00 0.0 76
USC00514830 2010-10-23 00:00:00 0.0 76
USC00514830 2010-10-24 00:00:00 0.0 76
USC00514830 2010-10-25 00:00:00 0.0 74
USC00514830 2010-10-26 00:00:00 0.04 71
USC00514830 2010-10-27 00:00:00 0.11 74
USC00514830 2010-10-28 00:00:00 0.12 74
USC00514830 2010-10-29 00:00:00 0.28 74
USC00514830 2010-11-02 00:00:00 0.03 72
USC00514830 2010-11-03 00:00:00 0.13 68
USC00514830 2010-11-04 00:00:00 0.18 70
USC00514830 2010-11-05 00:00:00 0.09 73
USC00514830 2010-11-06 00:00:00 0.35 70
USC00514830 2010-11-07 00:00:00 0.14 73
USC00514830 2010-11-08 00:00:00 0.0 73
USC00514830 2010-11-09 00:00:00 0.01 74
USC00514830 2010-11-10 00:00:00 0.0 73
USC00514830 2010-11-11 00:00:00 0.01 73
USC00514830 2010-11-12 00:00:00 0.01 74
USC00514830 2010-11-13 00:00:00 0.1 74
USC00514830 2010-11-14 00:00:00 0.01 73
USC00514830 2010-11-15 00:00:00 0.08 72
USC00514830 2010-11-16 00:00:00 0.0 73
USC00514830 2010-11-17 00:00:00 0.0 72
USC00514830 2010-11-18 00:00:00 0.0 71
USC00514830 2010-11-19 00:00:00 0.16 75
USC00514830 2010-11-20 00:00:00 0.01 70
USC00514830 2010-11-23 00:00:00 0.0 70
USC00514830 2010-11-24 00:00:00 0.0 74
USC00514830 2010-11-27 00:00:00 0.0 73
USC00514830 2010-11-28 00:00:00 0.54 71
USC00514830 2010-11-29 00:00:00 0.22 74
USC00514830 2010-11-30 00:00:00 0.01 73
USC00514830 2010-12-01 00:00:00 0.03 73
USC00514830 2010-12-02 00:00:00 0.06 73
USC00514830 2010-12-03 00:00:00 0.22 71
USC00514830 2010-12-04 00:00:00 0.0 72
USC00514830 2010-12-05 00:00:00 0.0 71
USC00514830 2010-12-06 00:00:00 0.0 64
USC00514830 2010-12-07 00:00:00 0.0 71
USC00514830 2010-12-08 00:00:00 0.0 62
USC00514830 2010-12-09 00:00:00 0.12 70
USC00514830 2010-12-10 00:00:00 2.01 64
USC00514830 2010-12-11 00:00:00 0.26 64
USC00514830 2010-12-12 00:00:00 0.01 70
USC00514830 2010-12-13 00:00:00 0.65 70
USC00514830 2010-12-14 00:00:00 0.0 69
USC00514830 2010-12-15 00:00:00 0.0 72
USC00514830 2010-12-16 00:00:00 0.0 68
USC00514830 2010-12-17 00:00:00 0.0 68
USC00514830 2010-12-18 00:00:00 0.0 65
USC00514830 2010-12-19 00:00:00 2.43 67
USC00514830 2010-12-20 00:00:00 2.55 68
USC00514830 2010-12-21 00:00:00 0.49 70
USC00514830 2010-12-22 00:00:00 0.05 67
USC00514830 2010-12-23 00:00:00 0.02 73
USC00514830 2010-12-24 00:00:00 0.0 70
USC00514830 2010-12-27 00:00:00 0.15 72
USC00514830 2010-12-28 00:00:00 0.96 69
USC00514830 2010-12-29 00:00:00 0.01 71
USC00514830 2010-12-30 00:00:00 0.05 70
USC00514830 2010-12-31 00:00:00 0.0 75
USC00514830 2011-01-01 00:00:00 0.14 75
USC00514830 2011-01-02 00:00:00 0.0 71
USC00514830 2011-01-03 00:00:00 0.04 73
USC00514830 2011-01-04 00:00:00 0.0 70
USC00514830 2011-01-05 00:00:00 0.0 64
USC00514830 2011-01-06 00:00:00 0.13 65
USC00514830 2011-01-07 00:00:00 0.0 65
USC00514830 2011-01-08 00:00:00 0.0 64
USC00514830 2011-01-09 00:00:00 0.08 59
USC00514830 2011-01-10 00:00:00 0.0 70
USC00514830 2011-01-11 00:00:00 0.61 58
USC00514830 2011-01-12 00:00:00 0.54 66
USC00514830 2011-01-13 00:00:00 3.91 68
USC00514830 2011-01-14 00:00:00 0.17 74
USC00514830 2011-01-16 00:00:00 0.0 67
USC00514830 2011-01-17 00:00:00 0.07 68
USC00514830 2011-01-18 00:00:00 0.0 66
USC00514830 2011-01-19 00:00:00 0.07 65
USC00514830 2011-01-20 00:00:00 0.03 70
USC00514830 2011-01-21 00:00:00 0.1 71
USC00514830 2011-01-22 00:00:00 0.0 73
USC00514830 2011-01-23 00:00:00 0.0 69
USC00514830 2011-01-24 00:00:00 0.0 70
USC00514830 2011-01-25 00:00:00 0.0 65
USC00514830 2011-01-26 00:00:00 0.0 67
USC00514830 2011-01-27 00:00:00 0.0 69
USC00514830 2011-01-28 00:00:00 0.0 70
USC00514830 2011-02-01 00:00:00 0.0 69
USC00514830 2011-02-02 00:00:00 0.0 70
USC00514830 2011-02-03 00:00:00 0.0 70
USC00514830 2011-02-04 00:00:00 0.0 66
USC00514830 2011-02-08 00:00:00 0.3 70
USC00514830 2011-02-09 00:00:00 0.0 70
USC00514830 2011-02-10 00:00:00 0.0 72
USC00514830 2011-02-11 00:00:00 0.34 66
USC00514830 2011-02-14 00:00:00 0.0 68
USC00514830 2011-02-15 00:00:00 0.0 70
USC00514830 2011-02-18 00:00:00 0.0 73
USC00514830 2011-02-21 00:00:00 0.0 75
USC00514830 2011-02-22 00:00:00 0.0 73
USC00514830 2011-02-23 00:00:00 0.0 71
USC00514830 2011-02-24 00:00:00 3.33 68
USC00514830 2011-02-25 00:00:00 0.0 71
USC00514830 2011-03-01 00:00:00 0.05 68
USC00514830 2011-03-02 00:00:00 0.0 70
USC00514830 2011-03-03 00:00:00 0.2 70
USC00514830 2011-03-04 00:00:00 1.45 73
USC00514830 2011-03-05 00:00:00 0.26 68
USC00514830 2011-03-06 00:00:00 0.64 75
USC00514830 2011-03-07 00:00:00 0.0 71
USC00514830 2011-03-08 00:00:00 0.03 73
USC00514830 2011-03-09 00:00:00 0.16 70
USC00514830 2011-03-10 00:00:00 1.4 68
USC00514830 2011-03-11 00:00:00 0.02 72
USC00514830 2011-03-15 00:00:00 0.0 72
USC00514830 2011-03-16 00:00:00 0.0 71
USC00514830 2011-03-17 00:00:00 0.07 72
USC00514830 2011-03-18 00:00:00 0.1 70
USC00514830 2011-03-19 00:00:00 0.14 71
USC00514830 2011-03-22 00:00:00 0.04 71
USC00514830 2011-03-23 00:00:00 0.0 70
USC00514830 2011-03-24 00:00:00 0.15 72
USC00514830 2011-03-29 00:00:00 0.0 72
USC00514830 2011-03-30 00:00:00 0.0 72
USC00514830 2011-03-31 00:00:00 0.0 75
USC00514830 2011-04-01 00:00:00 0.35 71
USC00514830 2011-04-05 00:00:00 0.0 71
USC00514830 2011-04-06 00:00:00 0.0 70
USC00514830 2011-04-07 00:00:00 0.59 67
USC00514830 2011-04-08 00:00:00 0.31 69
USC00514830 2011-04-11 00:00:00 0.0 72
USC00514830 2011-04-12 00:00:00 0.0 72
USC00514830 2011-04-13 00:00:00 0.0 69
USC00514830 2011-04-14 00:00:00 0.0 73
USC00514830 2011-04-15 00:00:00 0.0 76
USC00514830 2011-04-18 00:00:00 0.0 74
USC00514830 2011-04-19 00:00:00 0.0 73
USC00514830 2011-04-20 00:00:00 0.0 71
USC00514830 2011-04-21 00:00:00 0.0 74
USC00514830 2011-04-22 00:00:00 0.0 73
USC00514830 2011-04-23 00:00:00 0.04 77
USC00514830 2011-04-25 00:00:00 0.0 74
USC00514830 2011-04-26 00:00:00 0.0 74
USC00514830 2011-04-27 00:00:00 0.03 71
USC00514830 2011-04-28 00:00:00 0.0 74
USC00514830 2011-04-29 00:00:00 0.34 72
USC00514830 2011-04-30 00:00:00 0.12 75
USC00514830 2011-05-03 00:00:00 0.64 71
USC00514830 2011-05-04 00:00:00 0.11 73
USC00514830 2011-05-05 00:00:00 0.08 71
USC00514830 2011-05-06 00:00:00 0.4 69
USC00514830 2011-05-07 00:00:00 0.99 70
USC00514830 2011-05-10 00:00:00 0.38 73
USC00514830 2011-05-11 00:00:00 0.01 73
USC00514830 2011-05-12 00:00:00 0.0 73
USC00514830 2011-05-13 00:00:00 0.0 73
USC00514830 2011-05-16 00:00:00 0.0 74
USC00514830 2011-05-17 00:00:00 0.0 73
USC00514830 2011-05-18 00:00:00 0.56 68
USC00514830 2011-05-19 00:00:00 0.02 74
USC00514830 2011-05-20 00:00:00 0.0 74
USC00514830 2011-05-23 00:00:00 0.0 74
USC00514830 2011-05-24 00:00:00 0.0 74
USC00514830 2011-05-25 00:00:00 0.01 73
USC00514830 2011-05-26 00:00:00 0.02 73
USC00514830 2011-05-27 00:00:00 0.09 74
USC00514830 2011-05-31 00:00:00 0.0 74
USC00514830 2011-06-01 00:00:00 0.19 72
USC00514830 2011-06-02 00:00:00 0.04 73
USC00514830 2011-06-03 00:00:00 1.75 67
USC00514830 2011-06-04 00:00:00 1.14 69
USC00514830 2011-06-05 00:00:00 3.6 76
USC00514830 2011-06-06 00:00:00 0.0 73
USC00514830 2011-06-07 00:00:00 0.05 70
USC00514830 2011-06-08 00:00:00 0.17 72
USC00514830 2011-06-09 00:00:00 0.0 74
USC00514830 2011-06-10 00:00:00 0.02 72
USC00514830 2011-06-14 00:00:00 0.02 75
USC00514830 2011-06-15 00:00:00 0.0 73
USC00514830 2011-06-16 00:00:00 0.13 73
USC00514830 2011-06-17 00:00:00 0.0 72
USC00514830 2011-06-18 00:00:00 0.0 74
USC00514830 2011-06-19 00:00:00 0.12 76
USC00514830 2011-06-22 00:00:00 0.2 74
USC00514830 2011-06-23 00:00:00 0.09 70
USC00514830 2011-06-24 00:00:00 0.17 74
USC00514830 2011-06-25 00:00:00 0.03 74
USC00514830 2011-06-28 00:00:00 0.12 71
USC00514830 2011-07-01 00:00:00 0.01 74
USC00514830 2011-07-04 00:00:00 0.02 76
USC00514830 2011-07-05 00:00:00 0.14 73
USC00514830 2011-07-06 00:00:00 0.0 73
USC00514830 2011-07-07 00:00:00 0.06 73
USC00514830 2011-07-08 00:00:00 0.15 74
USC00514830 2011-07-09 00:00:00 0.07 74
USC00514830 2011-07-10 00:00:00 0.02 76
USC00514830 2011-07-13 00:00:00 0.03 75
USC00514830 2011-07-14 00:00:00 0.01 74
USC00514830 2011-07-15 00:00:00 0.13 76
USC00514830 2011-07-16 00:00:00 0.02 77
USC00514830 2011-07-19 00:00:00 0.01 75
USC00514830 2011-07-20 00:00:00 0.1 74
USC00514830 2011-07-21 00:00:00 0.0 76
USC00514830 2011-07-22 00:00:00 0.07 75
USC00514830 2011-07-26 00:00:00 0.01 73
USC00514830 2011-07-27 00:00:00 0.13 74
USC00514830 2011-07-28 00:00:00 0.0 74
USC00514830 2011-07-29 00:00:00 0.04 75
USC00514830 2011-07-30 00:00:00 0.39 76

USC00514830 2011-08-01 00:00:00 0.0 72
USC00514830 2011-08-02 00:00:00 0.03 74
USC00514830 2011-08-03 00:00:00 0.02 73
USC00514830 2011-08-04 00:00:00 0.01 74
USC00514830 2011-08-05 00:00:00 0.02 73
USC00514830 2011-08-07 00:00:00 0.0 78
USC00514830 2011-08-16 00:00:00 0.01 73
USC00514830 2011-08-17 00:00:00 0.0 74
USC00514830 2011-08-18 00:00:00 0.0 76
USC00514830 2011-08-26 00:00:00 0.06 76
USC00514830 2011-08-27 00:00:00 0.12 78
USC00514830 2011-08-30 00:00:00 0.11 75
USC00514830 2011-08-31 00:00:00 0.12 75
USC00514830 2011-09-01 00:00:00 0.03 75
USC00514830 2011-09-02 00:00:00 0.08 75
USC00514830 2011-09-03 00:00:00 0.07 76
USC00514830 2011-09-04 00:00:00 0.03 78
USC00514830 2011-09-07 00:00:00 0.0 74
USC00514830 2011-09-10 00:00:00 0.23 78
USC00514830 2011-09-13 00:00:00 0.05 74
USC00514830 2011-09-14 00:00:00 0.0 76
USC00514830 2011-09-15 00:00:00 0.02 75
USC00514830 2011-09-16 00:00:00 0.02 75
USC00514830 2011-09-17 00:00:00 0.04 78
USC00514830 2011-09-20 00:00:00 0.0 75
USC00514830 2011-09-21 00:00:00 0.06 75
USC00514830 2011-09-22 00:00:00 0.0 75
USC00514830 2011-09-23 00:00:00 0.03 74
USC00514830 2011-09-26 00:00:00 0.0 72
USC00514830 2011-09-27 00:00:00 0.0 75
USC00514830 2011-09-28 00:00:00 0.02 75
USC00514830 2011-09-29 00:00:00 0.0 74
USC00514830 2011-09-30 00:00:00 0.02 76
USC00514830 2011-10-01 00:00:00 0.19 77
USC00514830 2011-10-02 00:00:00 0.0 76
USC00514830 2011-10-03 00:00:00 0.0 76
USC00514830 2011-10-04 00:00:00 0.08 74
USC00514830 2011-10-05 00:00:00 0.03 76
USC00514830 2011-10-06 00:00:00 0.08 70
USC00514830 2011-10-07 00:00:00 0.02 73
USC00514830 2011-10-08 00:00:00 0.01 76
USC00514830 2011-10-11 00:00:00 0.07 75
USC00514830 2011-10-12 00:00:00 0.01 75
USC00514830 2011-10-13 00:00:00 0.11 74
USC00514830 2011-10-14 00:00:00 0.01 73
USC00514830 2011-10-15 00:00:00 0.08 74
USC00514830 2011-10-17 00:00:00 0.0 75
USC00514830 2011-10-18 00:00:00 0.0 72
USC00514830 2011-10-19 00:00:00 0.54 68
USC00514830 2011-10-20 00:00:00 0.07 73
USC00514830 2011-10-21 00:00:00 0.0 73
USC00514830 2011-10-22 00:00:00 0.0 77
USC00514830 2011-10-25 00:00:00 0.0 74
USC00514830 2011-10-26 00:00:00 0.0 73
USC00514830 2011-10-27 00:00:00 0.0 72
USC00514830 2011-10-28 00:00:00 0.08 73
USC00514830 2011-10-29 00:00:00 0.0 76
USC00514830 2011-10-30 00:00:00 0.27 75
USC00514830 2011-10-31 00:00:00 0.39 74
USC00514830 2011-11-01 00:00:00 0.7 74
USC00514830 2011-11-02 00:00:00 0.12 69
USC00514830 2011-11-03 00:00:00 0.12 72
USC00514830 2011-11-04 00:00:00 0.4 71
USC00514830 2011-11-05 00:00:00 0.06 74
USC00514830 2011-11-08 00:00:00 0.08 72
USC00514830 2011-11-09 00:00:00 0.02 71
USC00514830 2011-11-10 00:00:00 0.05 74
USC00514830 2011-11-11 00:00:00 0.07 75
USC00514830 2011-11-15 00:00:00 0.0 71
USC00514830 2011-11-16 00:00:00 0.0 72
USC00514830 2011-11-17 00:00:00 0.0 73
USC00514830 2011-11-18 00:00:00 0.21 72
USC00514830 2011-11-19 00:00:00 0.09 74
USC00514830 2011-11-22 00:00:00 0.04 72
USC00514830 2011-11-23 00:00:00 0.0 71
USC00514830 2011-11-25 00:00:00 0.0 74
USC00514830 2011-11-28 00:00:00 0.0 69
USC00514830 2011-11-29 00:00:00 0.0 67
USC00514830 2011-11-30 00:00:00 0.14 67
USC00514830 2011-12-01 00:00:00 0.04 70
USC00514830 2011-12-02 00:00:00 0.24 68
USC00514830 2011-12-03 00:00:00 0.02 73
USC00514830 2011-12-04 00:00:00 0.0 71
USC00514830 2011-12-05 00:00:00 0.0 71
USC00514830 2011-12-06 00:00:00 0.0 70
USC00514830 2011-12-07 00:00:00 0.04 70
USC00514830 2011-12-08 00:00:00 0.0 70
USC00514830 2011-12-09 00:00:00 0.02 70
USC00514830 2011-12-10 00:00:00 0.36 72
USC00514830 2011-12-13 00:00:00 0.47 71
USC00514830 2011-12-14 00:00:00 0.1 70
USC00514830 2011-12-15 00:00:00 0.04 70
USC00514830 2011-12-16 00:00:00 0.07 69
USC00514830 2011-12-19 00:00:00 0.16 70
USC00514830 2011-12-20 00:00:00 0.05 70
USC00514830 2011-12-21 00:00:00 0.25 72
USC00514830 2011-12-22 00:00:00 0.12 72
USC00514830 2011-12-27 00:00:00 0.03 72
USC00514830 2011-12-30 00:00:00 0.0 66
USC00514830 2011-12-31 00:00:00 0.08 71
USC00514830 2012-01-01 00:00:00 0.0 70
USC00514830 2012-01-03 00:00:00 0.0 67
USC00514830 2012-01-04 00:00:00 0.0 70
USC00514830 2012-01-05 00:00:00 0.0 70
USC00514830 2012-01-06 00:00:00 0.0 71
USC00514830 2012-01-07 00:00:00 0.0 71
USC00514830 2012-01-08 00:00:00 0.0 71
USC00514830 2012-01-09 00:00:00 0.0 73
USC00514830 2012-01-10 00:00:00 0.0 70
USC00514830 2012-01-11 00:00:00 0.0 67
USC00514830 2012-01-12 00:00:00 0.0 65
USC00514830 2012-01-13 00:00:00 0.0 66
USC00514830 2012-01-16 00:00:00 0.45 73
USC00514830 2012-01-17 00:00:00 0.12 73
USC00514830 2012-01-18 00:00:00 0.02 72
USC00514830 2012-01-19 00:00:00 0.0 66
USC00514830 2012-01-20 00:00:00 0.0 71
USC00514830 2012-01-24 00:00:00 0.0 64
USC00514830 2012-01-25 00:00:00 0.23 70
USC00514830 2012-01-26 00:00:00 0.0 71
USC00514830 2012-01-27 00:00:00 0.25 63
USC00514830 2012-01-29 00:00:00 0.0 74
USC00514830 2012-01-30 00:00:00 0.08 67
USC00514830 2012-01-31 00:00:00 0.01 67
USC00514830 2012-02-01 00:00:00 0.0 68
USC00514830 2012-02-02 00:00:00 0.0 70
USC00514830 2012-02-03 00:00:00 0.0 64
USC00514830 2012-02-06 00:00:00 0.01 70
USC00514830 2012-02-07 00:00:00 0.21 75
USC00514830 2012-02-08 00:00:00 0.07 66
USC00514830 2012-02-09 00:00:00 0.03 65
USC00514830 2012-02-10 00:00:00 0.01 68
USC00514830 2012-02-13 00:00:00 0.0 70
USC00514830 2012-02-14 00:00:00 0.11 69
USC00514830 2012-02-15 00:00:00 0.0 68
USC00514830 2012-02-16 00:00:00 0.0 70
USC00514830 2012-02-17 00:00:00 0.09 69
USC00514830 2012-02-18 00:00:00 0.1 72
USC00514830 2012-02-21 00:00:00 0.02 70
USC00514830 2012-02-22 00:00:00 0.04 70
USC00514830 2012-02-23 00:00:00 0.06 69
USC00514830 2012-02-24 00:00:00 0.01 68
USC00514830 2012-02-28 00:00:00 0.03 69
USC00514830 2012-02-29 00:00:00 0.0 70
USC00514830 2012-03-01 00:00:00 0.0 69
USC00514830 2012-03-02 00:00:00 0.0 71
USC00514830 2012-03-06 00:00:00 1.88 66
USC00514830 2012-03-07 00:00:00 1.01 65
USC00514830 2012-03-08 00:00:00 0.26 66
USC00514830 2012-03-09 00:00:00 0.64 63
USC00514830 2012-03-10 00:00:00 0.35 71
USC00514830 2012-03-11 00:00:00 0.11 70
USC00514830 2012-03-12 00:00:00 0.09 68
USC00514830 2012-03-13 00:00:00 0.0 67
USC00514830 2012-03-14 00:00:00 0.0 68
USC00514830 2012-03-15 00:00:00 0.0 68
USC00514830 2012-03-16 00:00:00 0.0 68
USC00514830 2012-03-27 00:00:00 0.14 66
USC00514830 2012-03-28 00:00:00 0.0 68
USC00514830 2012-03-29 00:00:00 0.0 69
USC00514830 2012-03-30 00:00:00 0.0 69
USC00514830 2012-04-04 00:00:00 0.0 70
USC00514830 2012-04-05 00:00:00 0.01 70
USC00514830 2012-04-06 00:00:00 0.0 70
USC00514830 2012-04-10 00:00:00 0.14 65
USC00514830 2012-04-11 00:00:00 0.03 68
USC00514830 2012-04-12 00:00:00 0.01 70
USC00514830 2012-04-13 00:00:00 0.0 69
USC00514830 2012-04-14 00:00:00 0.0 72
USC00514830 2012-04-15 00:00:00 0.02 72
USC00514830 2012-04-16 00:00:00 0.0 73
USC00514830 2012-04-17 00:00:00 0.0 71
USC00514830 2012-04-18 00:00:00 0.0 69
USC00514830 2012-04-19 00:00:00 0.0 70
USC00514830 2012-04-20 00:00:00 0.0 70
USC00514830 2012-04-24 00:00:00 0.0 69
USC00514830 2012-04-25 00:00:00 0.07 67
USC00514830 2012-04-26 00:00:00 0.01 70
USC00514830 2012-04-27 00:00:00 0.07 71
USC00514830 2012-06-21 00:00:00 0.08 75
USC00514830 2012-06-22 00:00:00 0.01 75
USC00514830 2012-06-25 00:00:00 0.12 77
USC00514830 2012-06-26 00:00:00 0.03 75
USC00514830 2012-06-27 00:00:00 0.2 74
USC00514830 2012-06-28 00:00:00 0.0 75
USC00514830 2012-06-29 00:00:00 0.23 76
USC00514830 2012-06-30 00:00:00 0.02 78
USC00514830 2012-07-01 00:00:00 0.02 78
USC00514830 2012-07-02 00:00:00 0.0 76
USC00514830 2012-07-03 00:00:00 0.05 75
USC00514830 2012-07-04 00:00:00 0.19 75
USC00514830 2012-07-05 00:00:00 0.11 76
USC00514830 2012-07-06 00:00:00 0.04 75
USC00514830 2012-07-07 00:00:00 0.1 77
USC00514830 2012-07-08 00:00:00 0.0 78
USC00514830 2012-07-09 00:00:00 0.01 77
USC00514830 2012-07-10 00:00:00 0.03 74
USC00514830 2012-07-11 00:00:00 0.0 76
USC00514830 2012-07-12 00:00:00 0.02 71
USC00514830 2012-07-13 00:00:00 0.12 77
USC00514830 2012-07-14 00:00:00 0.03 79
USC00514830 2012-07-15 00:00:00 0.13 72
USC00514830 2012-07-16 00:00:00 0.17 76
USC00514830 2012-07-17 00:00:00 0.1 77
USC00514830 2012-07-18 00:00:00 0.05 77
USC00514830 2012-07-19 00:00:00 0.16 76
USC00514830 2012-07-20 00:00:00 0.05 73
USC00514830 2012-07-21 00:00:00 0.12 79
USC00514830 2012-07-22 00:00:00 0.0 79
USC00514830 2012-07-23 00:00:00 0.01 77
USC00514830 2012-07-24 00:00:00 0.0 76
USC00514830 2012-07-25 00:00:00 0.0 79
USC00514830 2012-07-26 00:00:00 0.01 77
USC00514830 2012-07-27 00:00:00 0.11 77
USC00514830 2012-07-28 00:00:00 0.21 79
USC00514830 2012-07-29 00:00:00 0.1 77
USC00514830 2012-07-30 00:00:00 0.0 77
USC00514830 2012-07-31 00:00:00 0.1 76
USC00514830 2012-08-14 00:00:00 0.06 75
USC00514830 2012-08-15 00:00:00 0.01 76
USC00514830 2012-08-16 00:00:00 0.02 77
USC00514830 2012-08-17 00:00:00 0.0 73
USC00514830 2012-08-21 00:00:00 0.01 79
USC00514830 2012-08-22 00:00:00 0.03 77
USC00514830 2012-08-23 00:00:00 0.02 78
USC00514830 2012-08-24 00:00:00 0.0 78
USC00514830 2012-08-28 00:00:00 0.23 75
USC00514830 2012-08-29 00:00:00 0.0 74
USC00514830 2012-08-30 00:00:00 0.13 77
USC00514830 2012-08-31 00:00:00 0.0 76
USC00514830 2012-09-01 00:00:00 0.0 79
USC00514830 2012-09-04 00:00:00 0.02 77
USC00514830 2012-09-05 00:00:00 0.05 73
USC00514830 2012-09-06 00:00:00 0.07 76
USC00514830 2012-09-07 00:00:00 0.14 76
USC00514830 2012-09-11 00:00:00 0.16 77
USC00514830 2012-09-12 00:00:00 0.0 75
USC00514830 2012-09-13 00:00:00 0.0 76
USC00514830 2012-09-14 00:00:00 0.0 77
USC00514830 2012-09-18 00:00:00 0.04 72
USC00514830 2012-09-19 00:00:00 0.05 78
USC00514830 2012-09-20 00:00:00 0.17 76
USC00514830 2012-09-21 00:00:00 0.05 76
USC00514830 2012-09-22 00:00:00 0.03 79
USC00514830 2012-09-23 00:00:00 0.04 75
USC00514830 2012-09-24 00:00:00 0.06 76
USC00514830 2012-09-25 00:00:00 0.0 77
USC00514830 2012-09-26 00:00:00 0.0 76
USC00514830 2012-09-27 00:00:00 0.0 77
USC00514830 2012-09-28 00:00:00 0.15 77
USC00514830 2012-09-29 00:00:00 0.08 80
USC00514830 2012-10-02 00:00:00 0.0 76
USC00514830 2012-10-03 00:00:00 0.0 77
USC00514830 2012-10-04 00:00:00 0.0 78
USC00514830 2012-10-05 00:00:00 0.0 76
USC00514830 2012-10-06 00:00:00 0.0 79
USC00514830 2012-10-07 00:00:00 0.0 81
USC00514830 2012-10-08 00:00:00 0.04 80
USC00514830 2012-10-09 00:00:00 0.0 79
USC00514830 2012-10-10 00:00:00 0.0 74
USC00514830 2012-10-11 00:00:00 0.0 80
USC00514830 2012-10-12 00:00:00 0.0 78
USC00514830 2012-10-15 00:00:00 0.06 80
USC00514830 2012-10-16 00:00:00 0.01 76
USC00514830 2012-10-17 00:00:00 0.14 73
USC00514830 2012-10-18 00:00:00 0.06 74
USC00514830 2012-10-19 00:00:00 0.0 77
USC00514830 2012-10-20 00:00:00 0.0 76
USC00514830 2012-10-23 00:00:00 0.0 78
USC00514830 2012-10-24 00:00:00 0.11 74
USC00514830 2012-10-25 00:00:00 0.72 75
USC00514830 2012-10-26 00:00:00 0.0 75
USC00514830 2012-10-27 00:00:00 0.0 80
USC00514830 2012-10-30 00:00:00 0.03 77
USC00514830 2012-10-31 00:00:00 0.02 74
USC00514830 2012-11-01 00:00:00 0.0 77
USC00514830 2012-11-02 00:00:00 0.0 76
USC00514830 2012-11-03 00:00:00 0.0 81
USC00514830 2012-11-04 00:00:00 0.0 78
USC00514830 2012-11-05 00:00:00 0.0 75
USC00514830 2012-11-06 00:00:00 0.11 76
USC00514830 2012-11-07 00:00:00 0.05 78
USC00514830 2012-11-08 00:00:00 0.0 76
USC00514830 2012-11-09 00:00:00 0.01 77
USC00514830 2012-11-12 00:00:00 0.0 80
USC00514830 2012-11-13 00:00:00 0.08 76
USC00514830 2012-11-14 00:00:00 0.05 75
USC00514830 2012-11-15 00:00:00 0.48 75
USC00514830 2012-11-16 00:00:00 0.07 72
USC00514830 2012-11-17 00:00:00 0.09 75
USC00514830 2012-11-18 00:00:00 0.06 73
USC00514830 2012-11-19 00:00:00 0.03 75
USC00514830 2012-11-20 00:00:00 0.02 75
USC00514830 2012-11-21 00:00:00 0.0 73
USC00514830 2012-11-28 00:00:00 0.0 72
USC00514830 2012-11-29 00:00:00 0.0 72
USC00514830 2012-11-30 00:00:00 0.0 69
USC00514830 2012-12-01 00:00:00 0.0 68
USC00514830 2012-12-04 00:00:00 0.0 76
USC00514830 2012-12-05 00:00:00 0.08 73
USC00514830 2012-12-06 00:00:00 0.0 75
USC00514830 2012-12-07 00:00:00 0.0 71
USC00514830 2012-12-11 00:00:00 0.0 74
USC00514830 2012-12-12 00:00:00 0.03 73
USC00514830 2012-12-13 00:00:00 0.25 73
USC00514830 2012-12-14 00:00:00 0.22 74
USC00514830 2012-12-18 00:00:00 0.22 72
USC00514830 2012-12-19 00:00:00 0.29 76
USC00514830 2012-12-22 00:00:00 0.0 77
USC00514830 2013-01-03 00:00:00 0.28 70
USC00514830 2013-01-04 00:00:00 0.07 73
USC00514830 2013-01-05 00:00:00 0.2 72
USC00514830 2013-01-08 00:00:00 0.02 72
USC00514830 2013-01-09 00:00:00 0.44 74
USC00514830 2013-01-10 00:00:00 0.09 73
USC00514830 2013-01-11 00:00:00 0.0 72
USC00514830 2013-01-15 00:00:00 0.77 69
USC00514830 2013-01-16 00:00:00 0.0 66
USC00514830 2013-01-17 00:00:00 0.02 67
USC00514830 2013-01-18 00:00:00 0.0 75
USC00514830 2013-01-19 00:00:00 0.03 72
USC00514830 2013-01-22 00:00:00 0.0 71
USC00514830 2013-01-23 00:00:00 0.0 71
USC00514830 2013-01-24 00:00:00 0.45 70
USC00514830 2013-01-25 00:00:00 0.09 70
USC00514830 2013-01-26 00:00:00 0.0 75
USC00514830 2013-01-29 00:00:00 0.68 64
USC00514830 2013-01-30 00:00:00 0.02 72
USC00514830 2013-01-31 00:00:00 0.01 71
USC00514830 2013-02-01 00:00:00 0.0 74
USC00514830 2013-02-04 00:00:00 0.0 71
USC00514830 2013-02-05 00:00:00 0.06 72
USC00514830 2013-02-06 00:00:00 0.03 70
USC00514830 2013-02-07 00:00:00 0.39 73
USC00514830 2013-02-08 00:00:00 0.0 72
USC00514830 2013-02-12 00:00:00 0.01 70
USC00514830 2013-02-13 00:00:00 0.0 70
USC00514830 2013-02-14 00:00:00 0.0 70
USC00514830 2013-02-15 00:00:00 0.0 72
USC00514830 2013-02-16 00:00:00 0.06 74
USC00514830 2013-02-19 00:00:00 0.0 70
USC00514830 2013-02-20 00:00:00 0.34 72
USC00514830 2013-02-21 00:00:00 0.22 68
USC00514830 2013-02-22 00:00:00 1.4 70
USC00514830 2013-02-23 00:00:00 0.21 74
USC00514830 2013-02-26 00:00:00 0.25 71
USC00514830 2013-02-27 00:00:00 0.03 73
USC00514830 2013-02-28 00:00:00 0.0 72
USC00514830 2013-03-01 00:00:00 0.0 71
USC00514830 2013-03-02 00:00:00 0.0 72
USC00514830 2013-03-05 00:00:00 0.0 70
USC00514830 2013-03-06 00:00:00 0.0 72
USC00514830 2013-03-07 00:00:00 0.02 66
USC00514830 2013-03-08 00:00:00 0.13 67
USC00514830 2013-03-11 00:00:00 0.27 67
USC00514830 2013-03-12 00:00:00 0.0 69
USC00514830 2013-03-13 00:00:00 0.0 71
USC00514830 2013-03-14 00:00:00 0.0 69
USC00514830 2013-03-19 00:00:00 0.19 70
USC00514830 2013-03-20 00:00:00 0.0 74
USC00514830 2013-03-21 00:00:00 0.0 74
USC00514830 2013-03-28 00:00:00 0.28 75
USC00514830 2013-03-29 00:00:00 0.04 73
USC00514830 2013-04-02 00:00:00 0.0 68
USC00514830 2013-04-03 00:00:00 0.0 71
USC00514830 2013-04-04 00:00:00 0.0 73
USC00514830 2013-04-08 00:00:00 0.0 75
USC00514830 2013-04-09 00:00:00 0.2 75
USC00514830 2013-04-10 00:00:00 0.0 76
USC00514830 2013-04-11 00:00:00 0.01 76
USC00514830 2013-04-12 00:00:00 0.05 74
USC00514830 2013-04-13 00:00:00 0.0 73
USC00514830 2013-04-14 00:00:00 0.0 81
USC00514830 2013-04-15 00:00:00 0.57 75
USC00514830 2013-04-16 00:00:00 0.07 74

USC00514830 2013-04-17 00:00:00 0.0 76
USC00514830 2013-04-18 00:00:00 0.0 76
USC00514830 2013-04-19 00:00:00 0.22 73
USC00514830 2013-04-20 00:00:00 0.05 77
USC00514830 2013-04-23 00:00:00 0.32 77
USC00514830 2013-04-24 00:00:00 1.52 69
USC00514830 2013-04-25 00:00:00 0.01 77
USC00514830 2013-04-26 00:00:00 0.0 76
USC00514830 2013-04-30 00:00:00 0.0 76
USC00514830 2013-05-01 00:00:00 0.0 77
USC00514830 2013-05-02 00:00:00 0.01 76
USC00514830 2013-05-03 00:00:00 0.0 77
USC00514830 2013-05-06 00:00:00 0.29 73
USC00514830 2013-05-07 00:00:00 0.0 75
USC00514830 2013-05-08 00:00:00 0.0 74
USC00514830 2013-05-09 00:00:00 0.0 75
USC00514830 2013-05-10 00:00:00 0.04 72
USC00514830 2013-05-13 00:00:00 0.06 76
USC00514830 2013-05-14 00:00:00 0.0 77
USC00514830 2013-05-15 00:00:00 0.0 78
USC00514830 2013-05-16 00:00:00 0.1 75
USC00514830 2013-05-17 00:00:00 0.03 75
USC00514830 2013-05-21 00:00:00 0.0 73
USC00514830 2013-05-22 00:00:00 0.0 76
USC00514830 2013-05-23 00:00:00 0.0 77
USC00514830 2013-05-24 00:00:00 0.0 77
USC00514830 2013-05-25 00:00:00 0.08 76
USC00514830 2013-05-28 00:00:00 0.09 76
USC00514830 2013-05-29 00:00:00 0.63 74
USC00514830 2013-05-30 00:00:00 1.07 77
USC00514830 2013-05-31 00:00:00 0.0 76
USC00514830 2013-06-04 00:00:00 0.0 76
USC00514830 2013-06-05 00:00:00 0.0 78
USC00514830 2013-06-06 00:00:00 0.0 76
USC00514830 2013-06-07 00:00:00 0.01 76
USC00514830 2013-06-08 00:00:00 0.0 78
USC00514830 2013-06-09 00:00:00 0.01 79
USC00514830 2013-06-10 00:00:00 0.0 77
USC00514830 2013-06-11 00:00:00 0.0 76
USC00514830 2013-06-12 00:00:00 0.04 77
USC00514830 2013-06-13 00:00:00 0.08 77
USC00514830 2013-06-14 00:00:00 0.03 76
USC00514830 2013-06-17 00:00:00 0.04 76
USC00514830 2013-06-18 00:00:00 0.04 76
USC00514830 2013-06-19 00:00:00 0.08 77
USC00514830 2013-06-20 00:00:00 0.01 71
USC00514830 2013-06-26 00:00:00 0.17 72
USC00514830 2013-06-27 00:00:00 0.0 77
USC00514830 2013-07-01 00:00:00 0.0 76
USC00514830 2013-07-02 00:00:00 0.14 75
USC00514830 2013-07-03 00:00:00 0.03 75
USC00514830 2013-07-04 00:00:00 0.0 79
USC00514830 2013-07-05 00:00:00 0.0 75
USC00514830 2013-07-06 00:00:00 0.0 79
USC00514830 2013-07-09 00:00:00 0.0 79
USC00514830 2013-07-10 00:00:00 0.12 74
USC00514830 2013-07-11 00:00:00 0.01 76
USC00514830 2013-07-12 00:00:00 0.12 76
USC00514830 2013-07-13 00:00:00 0.15 78
USC00514830 2013-07-14 00:00:00 0.0 80
USC00514830 2013-07-15 00:00:00 0.0 78
USC00514830 2013-07-16 00:00:00 0.0 77
USC00514830 2013-07-17 00:00:00 0.0 77
USC00514830 2013-07-18 00:00:00 0.0 76
USC00514830 2013-07-19 00:00:00 0.05 78
USC00514830 2013-07-20 00:00:00 0.08 79
USC00514830 2013-07-23 00:00:00 0.14 76
USC00514830 2013-07-24 00:00:00 0.0 77
USC00514830 2013-07-25 00:00:00 0.0 77
USC00514830 2013-07-26 00:00:00 0.0 77
USC00514830 2013-07-27 00:00:00 0.0 79
USC00514830 2013-07-30 00:00:00 0.11 78
USC00514830 2013-07-31 00:00:00 0.05 74
USC00514830 2013-08-20 00:00:00 0.0 76
USC00514830 2013-08-21 00:00:00 0.43 77
USC00514830 2013-08-22 00:00:00 0.0 79
USC00514830 2013-08-23 00:00:00 0.0 76
USC00514830 2013-08-26 00:00:00 0.0 79
USC00514830 2013-08-27 00:00:00 0.0 78
USC00514830 2013-08-28 00:00:00 0.0 80
USC00514830 2013-08-29 00:00:00 0.01 77
USC00514830 2013-08-30 00:00:00 0.04 80
USC00514830 2013-08-31 00:00:00 0.0 81
USC00514830 2013-09-03 00:00:00 0.0 79
USC00514830 2013-09-04 00:00:00 0.01 78
USC00514830 2013-09-05 00:00:00 0.0 78
USC00514830 2013-09-06 00:00:00 0.0 78
USC00514830 2013-09-07 00:00:00 0.36 81
USC00514830 2013-09-10 00:00:00 0.0 79
USC00514830 2013-09-11 00:00:00 0.08 76
USC00514830 2013-09-12 00:00:00 0.0 77
USC00514830 2013-09-13 00:00:00 0.85 74
USC00514830 2013-09-14 00:00:00 0.02 82
USC00514830 2013-09-17 00:00:00 0.21 75
USC00514830 2013-09-18 00:00:00 0.03 80
USC00514830 2013-09-19 00:00:00 0.0 79
USC00514830 2013-09-20 00:00:00 0.0 78
USC00514830 2013-09-23 00:00:00 0.04 76
USC00514830 2013-09-24 00:00:00 0.17 78
USC00514830 2013-09-25 00:00:00 0.12 78
USC00514830 2013-09-26 00:00:00 0.19 77
USC00514830 2013-09-27 00:00:00 0.0 78
USC00514830 2013-09-28 00:00:00 0.0 81
USC00514830 2013-10-01 00:00:00 0.05 78
USC00514830 2013-10-02 00:00:00 0.0 80
USC00514830 2013-10-03 00:00:00 0.0 79
USC00514830 2013-10-04 00:00:00 0.0 77
USC00514830 2013-10-07 00:00:00 0.24 78
USC00514830 2013-10-08 00:00:00 0.01 78
USC00514830 2013-10-09 00:00:00 0.31 76
USC00514830 2013-10-10 00:00:00 0.0 78
USC00514830 2013-10-11 00:00:00 1.95 77
USC00514830 2013-10-15 00:00:00 0.09 76
USC00514830 2013-10-16 00:00:00 0.02 76
USC00514830 2013-10-17 00:00:00 0.0 77
USC00514830 2013-10-18 00:00:00 0.01 76
USC00514830 2013-10-19 00:00:00 0.05 73
USC00514830 2013-10-20 00:00:00 0.0 77
USC00514830 2013-10-21 00:00:00 0.0 75
USC00514830 2013-10-22 00:00:00 0.0 76
USC00514830 2013-10-23 00:00:00 0.0 77
USC00514830 2013-10-24 00:00:00 0.0 76
USC00514830 2013-10-25 00:00:00 0.0 76
USC00514830 2013-10-26 00:00:00 0.0 80
USC00514830 2013-10-29 00:00:00 0.0 78
USC00514830 2013-10-30 00:00:00 0.0 78
USC00514830 2013-10-31 00:00:00 0.1 77
USC00514830 2013-11-01 00:00:00 0.0 77
USC00514830 2013-11-05 00:00:00 0.0 74
USC00514830 2013-11-06 00:00:00 0.14 73
USC00514830 2013-11-07 00:00:00 0.62 74
USC00514830 2013-11-08 00:00:00 1.55 74
USC00514830 2013-11-09 00:00:00 0.87 73
USC00514830 2013-11-10 00:00:00 2.77 77
USC00514830 2013-11-11 00:00:00 0.32 74
USC00514830 2013-11-12 00:00:00 0.03 70
USC00514830 2013-11-13 00:00:00 0.0 65
USC00514830 2013-11-14 00:00:00 0.0 73
USC00514830 2013-11-15 00:00:00 0.47 75
USC00514830 2013-11-16 00:00:00 0.0 79
USC00514830 2013-11-17 00:00:00 0.0 78
USC00514830 2013-11-18 00:00:00 0.04 74
USC00514830 2013-11-19 00:00:00 0.0 75
USC00514830 2013-11-20 00:00:00 0.0 74
USC00514830 2013-11-21 00:00:00 0.0 74
USC00514830 2013-11-22 00:00:00 0.0 73
USC00514830 2013-11-23 00:00:00 0.09 75
USC00514830 2013-11-26 00:00:00 0.0 77
USC00514830 2013-11-27 00:00:00 0.0 77
USC00514830 2013-11-30 00:00:00 0.26 79
USC00514830 2013-12-03 00:00:00 0.2 75
USC00514830 2013-12-04 00:00:00 0.0 73
USC00514830 2013-12-05 00:00:00 0.0 73
USC00514830 2013-12-06 00:00:00 0.05 74
USC00514830 2013-12-07 00:00:00 0.04 78
USC00514830 2013-12-08 00:00:00 0.0 78
USC00514830 2013-12-09 00:00:00 0.0 78
USC00514830 2013-12-10 00:00:00 0.05 75
USC00514830 2013-12-11 00:00:00 0.0 75
USC00514830 2013-12-12 00:00:00 0.0 75
USC00514830 2013-12-13 00:00:00 0.07 74
USC00514830 2013-12-14 00:00:00 0.0 77
USC00514830 2013-12-17 00:00:00 0.0 72
USC00514830 2013-12-18 00:00:00 0.02 73
USC00514830 2013-12-19 00:00:00 0.52 71
USC00514830 2013-12-20 00:00:00 0.1 75
USC00514830 2013-12-21 00:00:00 0.07 76
USC00514830 2013-12-24 00:00:00 0.0 75
USC00514830 2013-12-27 00:00:00 0.03 75
USC00514830 2013-12-28 00:00:00 0.01 73
USC00514830 2013-12-29 00:00:00 0.0 72
USC00514830 2013-12-30 00:00:00 0.0 72
USC00514830 2013-12-31 00:00:00 0.23 75
USC00514830 2014-01-03 00:00:00 0.35 71
USC00514830 2014-01-04 00:00:00 0.0 73
USC00514830 2014-01-07 00:00:00 0.0 71
USC00514830 2014-01-08 00:00:00 0.0 71
USC00514830 2014-01-09 00:00:00 0.01 70
USC00514830 2014-01-10 00:00:00 0.03 74
USC00514830 2014-01-11 00:00:00 0.62 75
USC00514830 2014-01-14 00:00:00 0.59 74
USC00514830 2014-01-15 00:00:00 0.0 74
USC00514830 2014-01-16 00:00:00 0.01 73
USC00514830 2014-01-17 00:00:00 0.0 75
USC00514830 2014-01-18 00:00:00 0.0 74
USC00514830 2014-01-21 00:00:00 0.0 72
USC00514830 2014-01-24 00:00:00 0.0 66
USC00514830 2014-01-28 00:00:00 0.13 69
USC00514830 2014-01-29 00:00:00 0.24 69
USC00514830 2014-01-30 00:00:00 0.19 70
USC00514830 2014-01-31 00:00:00 0.0 71
USC00514830 2014-02-04 00:00:00 1.12 65
USC00514830 2014-02-05 00:00:00 0.08 75
USC00514830 2014-02-06 00:00:00 0.18 71
USC00514830 2014-02-07 00:00:00 0.25 70
USC00514830 2014-02-11 00:00:00 0.0 68
USC00514830 2014-02-12 00:00:00 0.0 73
USC00514830 2014-02-13 00:00:00 0.0 71
USC00514830 2014-02-14 00:00:00 0.02 72
USC00514830 2014-02-15 00:00:00 0.16 71
USC00514830 2014-02-18 00:00:00 0.03 74
USC00514830 2014-02-19 00:00:00 0.13 71
USC00514830 2014-02-26 00:00:00 0.0 70
USC00514830 2014-02-27 00:00:00 0.02 70
USC00514830 2014-02-28 00:00:00 0.02 76
USC00514830 2014-03-01 00:00:00 0.23 76
USC00514830 2014-03-02 00:00:00 0.23 67
USC00514830 2014-03-03 00:00:00 0.16 72
USC00514830 2014-03-04 00:00:00 0.0 71
USC00514830 2014-03-05 00:00:00 0.0 69
USC00514830 2014-03-06 00:00:00 0.0 75
USC00514830 2014-03-07 00:00:00 0.0 75
USC00514830 2014-03-08 00:00:00 0.42 69
USC00514830 2014-03-11 00:00:00 0.0 74
USC00514830 2014-03-12 00:00:00 0.0 74
USC00514830 2014-03-13 00:00:00 0.0 75
USC00514830 2014-03-14 00:00:00 0.0 75
USC00514830 2014-03-17 00:00:00 0.03 70
USC00514830 2014-03-18 00:00:00 0.0 70
USC00514830 2014-03-19 00:00:00 0.0 73
USC00514830 2014-03-20 00:00:00 0.0 75
USC00514830 2014-03-21 00:00:00 0.0 72
USC00514830 2014-03-31 00:00:00 0.11 74
USC00514830 2014-04-01 00:00:00 0.0 76
USC00514830 2014-04-02 00:00:00 0.13 74
USC00514830 2014-04-03 00:00:00 0.04 75
USC00514830 2014-04-04 00:00:00 0.0 74
USC00514830 2014-04-05 00:00:00 0.0 75
USC00514830 2014-04-06 00:00:00 0.19 76
USC00514830 2014-04-07 00:00:00 0.31 70
USC00514830 2014-04-08 00:00:00 0.0 71
USC00514830 2014-04-09 00:00:00 0.0 72
USC00514830 2014-04-10 00:00:00 0.0 71
USC00514830 2014-04-11 00:00:00 0.0 75
USC00514830 2014-04-12 00:00:00 0.04 70
USC00514830 2014-04-13 00:00:00 0.0 73
USC00514830 2014-04-14 00:00:00 0.0 75
USC00514830 2014-04-15 00:00:00 0.02 74
USC00514830 2014-04-16 00:00:00 0.0 73
USC00514830 2014-04-17 00:00:00 0.06 76
USC00514830 2014-04-18 00:00:00 0.03 74
USC00514830 2014-04-21 00:00:00 0.12 73
USC00514830 2014-04-22 00:00:00 0.09 76
USC00514830 2014-04-23 00:00:00 0.0 74
USC00514830 2014-04-24 00:00:00 0.0 75
USC00514830 2014-04-25 00:00:00 0.25 76
USC00514830 2014-04-29 00:00:00 0.0 72
USC00514830 2014-04-30 00:00:00 0.21 71
USC00514830 2014-05-01 00:00:00 0.0 71
USC00514830 2014-05-02 00:00:00 0.09 72
USC00514830 2014-05-03 00:00:00 0.01 77
USC00514830 2014-05-04 00:00:00 0.0 78
USC00514830 2014-05-05 00:00:00 0.0 77
USC00514830 2014-05-06 00:00:00 0.01 78
USC00514830 2014-05-07 00:00:00 0.0 75
USC00514830 2014-05-08 00:00:00 0.02 77
USC00514830 2014-05-09 00:00:00 0.22 78
USC00514830 2014-05-13 00:00:00 0.0 73
USC00514830 2014-05-14 00:00:00 0.01 72
USC00514830 2014-05-15 00:00:00 0.0 77
USC00514830 2014-05-16 00:00:00 0.37 75
USC00514830 2014-05-17 00:00:00 0.01 76
USC00514830 2014-05-20 00:00:00 0.07 77
USC00514830 2014-05-21 00:00:00 0.0 77
USC00514830 2014-05-22 00:00:00 0.04 77
USC00514830 2014-05-23 00:00:00 0.0 78
USC00514830 2014-05-27 00:00:00 0.9 77
USC00514830 2014-05-28 00:00:00 0.09 77
USC00514830 2014-05-29 00:00:00 0.02 78
USC00514830 2014-05-30 00:00:00 0.0 77
USC00514830 2014-06-02 00:00:00 0.02 78
USC00514830 2014-06-03 00:00:00 0.0 77
USC00514830 2014-06-04 00:00:00 0.0 77
USC00514830 2014-06-05 00:00:00 0.0 76
USC00514830 2014-06-06 00:00:00 0.13 75
USC00514830 2014-06-07 00:00:00 0.04 79
USC00514830 2014-06-10 00:00:00 0.16 73
USC00514830 2014-06-11 00:00:00 0.17 76
USC00514830 2014-06-12 00:00:00 0.0 78
USC00514830 2014-06-13 00:00:00 0.0 77
USC00514830 2014-06-14 00:00:00 0.0 78
USC00514830 2014-06-17 00:00:00 0.39 75
USC00514830 2014-06-18 00:00:00 0.08 76
USC00514830 2014-06-19 00:00:00 0.14 77
USC00514830 2014-06-20 00:00:00 0.07 74
USC00514830 2014-06-21 00:00:00 0.11 78
USC00514830 2014-06-24 00:00:00 0.03 77
USC00514830 2014-06-25 00:00:00 0.1 74
USC00514830 2014-06-26 00:00:00 0.08 74
USC00514830 2014-06-27 00:00:00 0.08 78
USC00514830 2014-06-30 00:00:00 0.04 79
USC00514830 2014-07-01 00:00:00 0.0 76
USC00514830 2014-07-02 00:00:00 0.03 79
USC00514830 2014-07-03 00:00:00 0.05 78
USC00514830 2014-07-04 00:00:00 0.03 77
USC00514830 2014-07-05 00:00:00 0.01 78
USC00514830 2014-07-06 00:00:00 0.05 79
USC00514830 2014-07-07 00:00:00 0.0 77
USC00514830 2014-07-08 00:00:00 0.02 76
USC00514830 2014-07-09 00:00:00 0.09 78
USC00514830 2014-07-10 00:00:00 0.03 78
USC00514830 2014-07-11 00:00:00 0.0 75
USC00514830 2014-07-12 00:00:00 0.01 81
USC00514830 2014-07-13 00:00:00 0.14 78
USC00514830 2014-07-14 00:00:00 0.15 78
USC00514830 2014-07-15 00:00:00 0.01 78
USC00514830 2014-07-16 00:00:00 0.32 78
USC00514830 2014-07-17 00:00:00 0.04 78
USC00514830 2014-07-18 00:00:00 0.09 79
USC00514830 2014-07-19 00:00:00 0.0 80
USC00514830 2014-07-20 00:00:00 11.53 76
USC00514830 2014-07-21 00:00:00 0.57 78
USC00514830 2014-07-22 00:00:00 0.05 78
USC00514830 2014-07-23 00:00:00 0.26 77
USC00514830 2014-07-24 00:00:00 0.02 78
USC00514830 2014-07-25 00:00:00 0.02 79
USC00514830 2014-07-28 00:00:00 0.0 79
USC00514830 2014-07-29 00:00:00 0.0 79
USC00514830 2014-07-30 00:00:00 0.0 79
USC00514830 2014-07-31 00:00:00 0.0 78
USC00514830 2014-08-01 00:00:00 0.0 79
USC00514830 2014-08-02 00:00:00 0.09 78
USC00514830 2014-08-05 00:00:00 0.0 79
USC00514830 2014-08-06 00:00:00 0.01 78
USC00514830 2014-08-07 00:00:00 0.29 79
USC00514830 2014-08-08 00:00:00 0.56 76
USC00514830 2014-08-09 00:00:00 0.72 79
USC00514830 2014-08-12 00:00:00 0.01 79
USC00514830 2014-08-13 00:00:00 0.1 79
USC00514830 2014-08-14 00:00:00 0.0 78
USC00514830 2014-08-15 00:00:00 0.0 78
USC00514830 2014-08-18 00:00:00 0.0 79
USC00514830 2014-08-19 00:00:00 0.0 78
USC00514830 2014-08-20 00:00:00 0.14 78
USC00514830 2014-08-21 00:00:00 0.0 77
USC00514830 2014-08-22 00:00:00 0.08 76
USC00514830 2014-08-25 00:00:00 0.0 80
USC00514830 2014-08-26 00:00:00 0.19 80
USC00514830 2014-08-27 00:00:00 0.05 80
USC00514830 2014-08-28 00:00:00 0.09 80
USC00514830 2014-08-29 00:00:00 0.04 80
USC00514830 2014-08-30 00:00:00 0.05 80
USC00514830 2014-09-02 00:00:00 0.47 80
USC00514830 2014-09-03 00:00:00 0.0 79
USC00514830 2014-09-04 00:00:00 0.01 82
USC00514830 2014-09-05 00:00:00 0.09 79
USC00514830 2014-09-08 00:00:00 0.0 79
USC00514830 2014-09-09 00:00:00 0.0 80
USC00514830 2014-09-10 00:00:00 0.01 81
USC00514830 2014-09-11 00:00:00 0.0 80
USC00514830 2014-09-12 00:00:00 0.3 80
USC00514830 2014-09-16 00:00:00 0.0 81
USC00514830 2014-09-17 00:00:00 0.09 80
USC00514830 2014-10-03 00:00:00 0.02 80
USC00514830 2014-10-04 00:00:00 0.0 81
USC00514830 2014-10-07 00:00:00 0.07 80
USC00514830 2014-10-08 00:00:00 0.0 80
USC00514830 2014-10-09 00:00:00 0.0 79
USC00514830 2014-10-10 00:00:00 0.01 80
USC00514830 2014-10-11 00:00:00 0.13 80
USC00514830 2014-10-12 00:00:00 0.0 82
USC00514830 2014-10-13 00:00:00 0.11 81
USC00514830 2014-10-14 00:00:00 0.02 79
USC00514830 2014-10-15 00:00:00 0.01 79
USC00514830 2014-10-16 00:00:00 0.0 81
USC00514830 2014-10-17 00:00:00 0.08 79
USC00514830 2014-10-18 00:00:00 0.12 81
USC00514830 2014-10-19 00:00:00 3.48 76
USC00514830 2014-10-20 00:00:00 1.0 80
USC00514830 2014-10-23 00:00:00 0.16 81
USC00514830 2014-10-24 00:00:00 0.12 79
USC00514830 2014-10-27 00:00:00 0.0 80
USC00514830 2014-10-28 00:00:00 0.07 78
USC00514830 2014-10-29 00:00:00 0.18 75
USC00514830 2014-10-30 00:00:00 0.06 79

USC00514830 2014-10-31 00:00:00 0.0 77
USC00514830 2014-11-01 00:00:00 0.4 81
USC00514830 2014-11-02 00:00:00 0.13 80
USC00514830 2014-11-03 00:00:00 0.1 79
USC00514830 2014-11-04 00:00:00 0.0 81
USC00514830 2014-11-05 00:00:00 0.43 74
USC00514830 2014-11-08 00:00:00 0.3 75
USC00514830 2014-11-09 00:00:00 0.0 77
USC00514830 2014-11-10 00:00:00 0.0 75
USC00514830 2014-11-11 00:00:00 0.0 77
USC00514830 2014-11-12 00:00:00 0.15 71
USC00514830 2014-11-15 00:00:00 0.21 75
USC00514830 2014-11-16 00:00:00 0.72 76
USC00514830 2014-11-17 00:00:00 0.0 77
USC00514830 2014-11-18 00:00:00 0.0 76
USC00514830 2014-11-19 00:00:00 0.0 76
USC00514830 2014-11-20 00:00:00 0.0 77
USC00514830 2014-11-21 00:00:00 0.01 78
USC00514830 2014-11-22 00:00:00 0.0 80
USC00514830 2014-11-23 00:00:00 0.0 80
USC00514830 2014-11-24 00:00:00 0.34 72
USC00514830 2014-11-25 00:00:00 0.02 74
USC00514830 2014-11-26 00:00:00 0.0 74
USC00514830 2014-11-27 00:00:00 0.0 75
USC00514830 2014-11-28 00:00:00 0.0 76
USC00514830 2014-11-29 00:00:00 0.07 75
USC00514830 2014-11-30 00:00:00 0.24 78
USC00514830 2014-12-01 00:00:00 0.0 74
USC00514830 2014-12-02 00:00:00 0.0 74
USC00514830 2014-12-03 00:00:00 0.24 72
USC00514830 2014-12-04 00:00:00 1.51 73
USC00514830 2014-12-05 00:00:00 0.26 70
USC00514830 2014-12-06 00:00:00 0.48 76
USC00514830 2014-12-09 00:00:00 0.0 76
USC00514830 2014-12-10 00:00:00 0.0 78
USC00514830 2014-12-11 00:00:00 0.1 74
USC00514830 2014-12-12 00:00:00 0.07 71
USC00514830 2014-12-13 00:00:00 0.0 78
USC00514830 2014-12-16 00:00:00 0.0 74
USC00514830 2014-12-17 00:00:00 0.01 74
USC00514830 2014-12-18 00:00:00 0.03 75
USC00514830 2014-12-19 00:00:00 0.01 76
USC00514830 2014-12-20 00:00:00 0.0 78
USC00514830 2014-12-23 00:00:00 0.58 73
USC00514830 2015-01-01 00:00:00 0.0 71
USC00514830 2015-01-02 00:00:00 0.0 72
USC00514830 2015-01-03 00:00:00 0.68 72
USC00514830 2015-01-04 00:00:00 0.04 72
USC00514830 2015-01-05 00:00:00 0.0 73
USC00514830 2015-01-06 00:00:00 0.06 72
USC00514830 2015-01-07 00:00:00 0.0 70
USC00514830 2015-01-08 00:00:00 0.0 74
USC00514830 2015-01-09 00:00:00 0.0 75
USC00514830 2015-01-12 00:00:00 0.0 73
USC00514830 2015-01-13 00:00:00 0.0 71
USC00514830 2015-01-14 00:00:00 0.0 68
USC00514830 2015-01-15 00:00:00 0.0 75
USC00514830 2015-01-16 00:00:00 0.0 73
USC00514830 2015-01-17 00:00:00 0.02 73
USC00514830 2015-01-20 00:00:00 0.0 77
USC00514830 2015-01-21 00:00:00 0.0 71
USC00514830 2015-01-22 00:00:00 0.0 75
USC00514830 2015-01-23 00:00:00 0.0 79
USC00514830 2015-01-24 00:00:00 0.39 67
USC00514830 2015-01-30 00:00:00 0.01 73
USC00514830 2015-01-31 00:00:00 0.0 72
USC00514830 2015-02-03 00:00:00 0.05 75
USC00514830 2015-02-04 00:00:00 0.17 72
USC00514830 2015-02-05 00:00:00 0.02 74
USC00514830 2015-02-06 00:00:00 0.0 77
USC00514830 2015-02-10 00:00:00 0.02 76
USC00514830 2015-02-11 00:00:00 0.0 69
USC00514830 2015-02-12 00:00:00 0.0 72
USC00514830 2015-02-13 00:00:00 0.0 75
USC00514830 2015-02-14 00:00:00 0.9 73
USC00514830 2015-02-18 00:00:00 0.0 70
USC00514830 2015-02-19 00:00:00 0.0 76
USC00514830 2015-02-20 00:00:00 0.26 67
USC00514830 2015-02-21 00:00:00 0.1 73
USC00514830 2015-02-22 00:00:00 0.0 76
USC00514830 2015-02-23 00:00:00 0.0 76
USC00514830 2015-02-24 00:00:00 0.0 76
USC00514830 2015-02-25 00:00:00 0.0 75
USC00514830 2015-02-26 00:00:00 0.41 74
USC00514830 2015-03-02 00:00:00 0.04 77
USC00514830 2015-03-03 00:00:00 0.0 75
USC00514830 2015-03-04 00:00:00 0.02 73
USC00514830 2015-03-05 00:00:00 0.42 72
USC00514830 2015-03-06 00:00:00 0.09 72
USC00514830 2015-03-07 00:00:00 0.0 71
USC00514830 2015-03-12 00:00:00 0.01 67
USC00514830 2015-03-13 00:00:00 0.13 70
USC00514830 2015-03-17 00:00:00 0.0 73
USC00514830 2015-03-18 00:00:00 0.0 73
USC00514830 2015-03-19 00:00:00 0.0 70
USC00514830 2015-03-20 00:00:00 0.02 72
USC00514830 2015-03-23 00:00:00 0.0 76
USC00514830 2015-03-24 00:00:00 0.13 75
USC00514830 2015-03-25 00:00:00 0.08 75
USC00514830 2015-03-26 00:00:00 0.05 71
USC00514830 2015-03-30 00:00:00 0.14 76
USC00514830 2015-03-31 00:00:00 0.35 77
USC00514830 2015-04-01 00:00:00 0.03 75
USC00514830 2015-04-02 00:00:00 0.0 75
USC00514830 2015-04-03 00:00:00 0.0 77
USC00514830 2015-04-06 00:00:00 0.06 76
USC00514830 2015-04-07 00:00:00 0.0 75
USC00514830 2015-04-08 00:00:00 0.08 76
USC00514830 2015-04-09 00:00:00 0.14 77
USC00514830 2015-04-10 00:00:00 0.0 75
USC00514830 2015-04-11 00:00:00 0.0 74
USC00514830 2015-04-12 00:00:00 0.01 76
USC00514830 2015-04-13 00:00:00 0.08 75
USC00514830 2015-04-14 00:00:00 0.09 74
USC00514830 2015-04-15 00:00:00 0.21 73
USC00514830 2015-04-16 00:00:00 0.02 77
USC00514830 2015-04-17 00:00:00 0.06 77
USC00514830 2015-04-20 00:00:00 0.0 76
USC00514830 2015-04-23 00:00:00 0.0 77
USC00514830 2015-04-24 00:00:00 0.08 77
USC00514830 2015-04-25 00:00:00 0.0 83
USC00514830 2015-04-26 00:00:00 0.0 80
USC00514830 2015-04-27 00:00:00 0.65 76
USC00514830 2015-04-28 00:00:00 0.08 73
USC00514830 2015-04-29 00:00:00 0.03 75
USC00514830 2015-04-30 00:00:00 0.01 77
USC00514830 2015-05-01 00:00:00 0.12 75
USC00514830 2015-05-04 00:00:00 0.0 76
USC00514830 2015-05-05 00:00:00 0.0 75
USC00514830 2015-05-06 00:00:00 0.0 76
USC00514830 2015-05-07 00:00:00 0.0 78
USC00514830 2015-05-08 00:00:00 0.04 75
USC00514830 2015-05-09 00:00:00 0.03 78
USC00514830 2015-05-10 00:00:00 0.06 76
USC00514830 2015-05-11 00:00:00 0.02 79
USC00514830 2015-05-12 00:00:00 0.0 76
USC00514830 2015-05-13 00:00:00 0.0 77
USC00514830 2015-05-14 00:00:00 0.09 76
USC00514830 2015-05-15 00:00:00 0.1 75
USC00514830 2015-05-16 00:00:00 0.16 79
USC00514830 2015-05-17 00:00:00 0.06 74
USC00514830 2015-05-18 00:00:00 0.0 77
USC00514830 2015-05-19 00:00:00 0.0 77
USC00514830 2015-05-20 00:00:00 0.08 72
USC00514830 2015-05-21 00:00:00 0.0 75
USC00514830 2015-05-22 00:00:00 0.0 74
USC00514830 2015-05-23 00:00:00 1.44 71
USC00514830 2015-05-24 00:00:00 0.0 73
USC00514830 2015-05-25 00:00:00 0.0 72
USC00514830 2015-05-26 00:00:00 0.06 74
USC00514830 2015-05-27 00:00:00 0.05 72
USC00514830 2015-05-28 00:00:00 0.64 77
USC00514830 2015-05-29 00:00:00 0.0 75
USC00514830 2015-05-30 00:00:00 0.14 78
USC00514830 2015-06-01 00:00:00 0.05 78
USC00514830 2015-06-03 00:00:00 0.0 75
USC00514830 2015-06-04 00:00:00 0.22 76
USC00514830 2015-06-05 00:00:00 0.0 78
USC00514830 2015-06-06 00:00:00 0.0 78
USC00514830 2015-06-09 00:00:00 0.0 78
USC00514830 2015-06-10 00:00:00 0.0 77
USC00514830 2015-06-11 00:00:00 0.0 76
USC00514830 2015-06-12 00:00:00 0.03 78
USC00514830 2015-06-15 00:00:00 0.0 78
USC00514830 2015-06-16 00:00:00 0.0 78
USC00514830 2015-06-17 00:00:00 0.16 74
USC00514830 2015-06-18 00:00:00 0.04 79
USC00514830 2015-06-19 00:00:00 0.02 77
USC00514830 2015-06-20 00:00:00 0.06 73
USC00514830 2015-06-21 00:00:00 0.0 79
USC00514830 2015-06-22 00:00:00 0.04 79
USC00514830 2015-06-23 00:00:00 0.02 78
USC00514830 2015-06-24 00:00:00 0.01 77
USC00514830 2015-06-25 00:00:00 0.2 78
USC00514830 2015-06-26 00:00:00 0.11 78
USC00514830 2015-06-27 00:00:00 0.09 80
USC00514830 2015-06-28 00:00:00 0.0 80
USC00514830 2015-06-29 00:00:00 0.11 79
USC00514830 2015-06-30 00:00:00 1.1 74
USC00514830 2015-07-01 00:00:00 0.0 80
USC00514830 2015-07-12 00:00:00 0.15 82
USC00514830 2015-07-13 00:00:00 0.06 77
USC00514830 2015-07-14 00:00:00 0.11 79
USC00514830 2015-07-15 00:00:00 0.04 80
USC00514830 2015-07-16 00:00:00 0.21 76
USC00514830 2015-07-17 00:00:00 1.24 80
USC00514830 2015-07-18 00:00:00 0.01 81
USC00514830 2015-07-21 00:00:00 0.0 81
USC00514830 2015-07-22 00:00:00 0.0 80
USC00514830 2015-07-23 00:00:00 0.0 81
USC00514830 2015-07-24 00:00:00 0.03 80
USC00514830 2015-07-25 00:00:00 0.2 81
USC00514830 2015-07-26 00:00:00 0.0 82
USC00514830 2015-07-27 00:00:00 0.0 81
USC00514830 2015-07-28 00:00:00 0.0 82
USC00514830 2015-07-29 00:00:00 0.0 81
USC00514830 2015-07-30 00:00:00 0.01 80
USC00514830 2015-08-12 00:00:00 0.0 83
USC00514830 2015-08-13 00:00:00 0.0 80
USC00514830 2015-08-14 00:00:00 0.09 80
USC00514830 2015-08-15 00:00:00 0.33 82
USC00514830 2015-08-18 00:00:00 0.2 81
USC00514830 2015-08-19 00:00:00 0.2 75
USC00514830 2015-08-20 00:00:00 0.0 81
USC00514830 2015-08-21 00:00:00 0.0 83
USC00514830 2015-08-22 00:00:00 0.0 83
USC00514830 2015-08-23 00:00:00 0.62 84
USC00514830 2015-08-24 00:00:00 3.7 75
USC00514830 2015-08-25 00:00:00 0.13 82
USC00514830 2015-08-26 00:00:00 0.11 81
USC00514830 2015-08-27 00:00:00 0.05 80
USC00514830 2015-08-28 00:00:00 0.0 83
USC00514830 2015-08-29 00:00:00 0.0 85
USC00514830 2015-09-01 00:00:00 0.22 82
USC00514830 2015-09-02 00:00:00 0.0 79
USC00514830 2015-09-03 00:00:00 0.19 76
USC00514830 2015-09-04 00:00:00 0.24 82
USC00514830 2015-09-05 00:00:00 0.0 82
USC00514830 2015-09-08 00:00:00 0.4 80
USC00514830 2015-09-15 00:00:00 0.75 77
USC00514830 2015-09-16 00:00:00 0.04 79
USC00514830 2015-09-17 00:00:00 0.0 83
USC00514830 2015-09-18 00:00:00 0.23 79
USC00514830 2015-09-22 00:00:00 0.07 80
USC00514830 2015-09-23 00:00:00 0.07 79
USC00514830 2015-09-24 00:00:00 0.11 79
USC00514830 2015-09-25 00:00:00 0.08 76
USC00514830 2015-09-26 00:00:00 0.39 79
USC00514830 2015-09-27 00:00:00 0.41 75
USC00514830 2015-09-28 00:00:00 0.3 80
USC00514830 2015-09-29 00:00:00 0.03 78
USC00514830 2015-09-30 00:00:00 0.06 79
USC00514830 2015-10-01 00:00:00 0.05 79
USC00514830 2015-10-02 00:00:00 0.0 76
USC00514830 2015-10-03 00:00:00 0.0 80
USC00514830 2015-10-04 00:00:00 0.08 78
USC00514830 2015-10-07 00:00:00 0.04 77
USC00514830 2015-10-08 00:00:00 0.0 78
USC00514830 2015-10-09 00:00:00 2.15 74
USC00514830 2015-10-10 00:00:00 0.0 81
USC00514830 2015-10-11 00:00:00 0.38 80
USC00514830 2015-10-12 00:00:00 3.85 76
USC00514830 2015-10-13 00:00:00 1.8 75
USC00514830 2015-10-14 00:00:00 0.41 75
USC00514830 2015-10-15 00:00:00 0.31 78
USC00514830 2015-10-16 00:00:00 0.0 76
USC00514830 2015-10-19 00:00:00 0.0 81
USC00514830 2015-10-20 00:00:00 0.32 79
USC00514830 2015-10-21 00:00:00 0.0 81
USC00514830 2015-10-22 00:00:00 0.07 81
USC00514830 2015-10-23 00:00:00 0.0 78
USC00514830 2015-10-24 00:00:00 0.0 80
USC00514830 2015-10-25 00:00:00 0.0 80
USC00514830 2015-10-26 00:00:00 0.02 81
USC00514830 2015-10-27 00:00:00 0.09 78
USC00514830 2015-10-28 00:00:00 0.01 77
USC00514830 2015-10-29 00:00:00 1.05 81
USC00514830 2015-10-30 00:00:00 0.0 79
USC00514830 2015-10-31 00:00:00 0.09 80
USC00514830 2015-11-01 00:00:00 0.05 83
USC00514830 2015-11-02 00:00:00 0.0 80
USC00514830 2015-11-03 00:00:00 0.0 81
USC00514830 2015-11-04 00:00:00 0.0 79
USC00514830 2015-11-05 00:00:00 0.11 76
USC00514830 2015-11-06 00:00:00 0.05 81
USC00514830 2015-11-09 00:00:00 0.2 81
USC00514830 2015-11-10 00:00:00 0.04 79
USC00514830 2015-11-11 00:00:00 0.0 78
USC00514830 2015-11-12 00:00:00 0.02 78
USC00514830 2015-11-13 00:00:00 0.17 77
USC00514830 2015-11-14 00:00:00 0.2 80
USC00514830 2015-11-15 00:00:00 0.02 79
USC00514830 2015-11-16 00:00:00 0.01 79
USC00514830 2015-11-17 00:00:00 0.0 79
USC00514830 2015-11-18 00:00:00 0.31 74
USC00514830 2015-11-19 00:00:00 0.01 78
USC00514830 2015-11-20 00:00:00 1.92 75
USC00514830 2015-11-21 00:00:00 0.58 80
USC00514830 2015-11-22 00:00:00 0.12 79
USC00514830 2015-11-23 00:00:00 1.75 74
USC00514830 2015-11-24 00:00:00 0.08 75
USC00514830 2015-11-25 00:00:00 0.01 73
USC00514830 2015-11-26 00:00:00 0.27 75
USC00514830 2015-11-27 00:00:00 0.66 78
USC00514830 2015-11-28 00:00:00 0.05 79
USC00514830 2015-12-01 00:00:00 0.0 78
USC00514830 2015-12-02 00:00:00 0.0 76
USC00514830 2015-12-03 00:00:00 0.17 76
USC00514830 2015-12-04 00:00:00 0.03 77
USC00514830 2015-12-08 00:00:00 0.05 73
USC00514830 2015-12-09 00:00:00 0.02 79
USC00514830 2015-12-10 00:00:00 0.12 77
USC00514830 2015-12-11 00:00:00 0.03 78
USC00514830 2015-12-12 00:00:00 0.17 76
USC00514830 2015-12-13 00:00:00 0.0 78
USC00514830 2015-12-14 00:00:00 0.05 77
USC00514830 2015-12-15 00:00:00 0.0 79
USC00514830 2015-12-16 00:00:00 0.05 75
USC00514830 2015-12-17 00:00:00 0.13 77
USC00514830 2015-12-18 00:00:00 0.08 76
USC00514830 2015-12-19 00:00:00 0.18 78
USC00514830 2015-12-22 00:00:00 0.13 77
USC00514830 2015-12-23 00:00:00 0.1 78
USC00514830 2015-12-28 00:00:00 0.21 75
USC00514830 2015-12-29 00:00:00 0.01 72
USC00514830 2016-01-01 00:00:00 0.0 73
USC00514830 2016-01-02 00:00:00 0.05 73
USC00514830 2016-01-03 00:00:00 0.0 75
USC00514830 2016-01-04 00:00:00 0.0 76
USC00514830 2016-01-05 00:00:00 0.1 74
USC00514830 2016-01-06 00:00:00 0.04 74
USC00514830 2016-01-07 00:00:00 0.03 73
USC00514830 2016-01-08 00:00:00 0.0 74
USC00514830 2016-01-09 00:00:00 0.0 78
USC00514830 2016-01-12 00:00:00 0.32 74
USC00514830 2016-01-13 00:00:00 0.0 66
USC00514830 2016-01-14 00:00:00 0.0 75
USC00514830 2016-01-15 00:00:00 0.15 70
USC00514830 2016-01-16 00:00:00 0.05 75
USC00514830 2016-01-17 00:00:00 0.0 76
USC00514830 2016-01-18 00:00:00 0.0 76
USC00514830 2016-01-19 00:00:00 0.0 73
USC00514830 2016-01-20 00:00:00 0.05 68
USC00514830 2016-01-21 00:00:00 0.23 73
USC00514830 2016-01-22 00:00:00 0.0 75
USC00514830 2016-01-23 00:00:00 0.0 77
USC00514830 2016-01-24 00:00:00 0.0 77
USC00514830 2016-01-25 00:00:00 0.01 73
USC00514830 2016-01-26 00:00:00 0.0 75
USC00514830 2016-01-27 00:00:00 0.0 70
USC00514830 2016-01-28 00:00:00 0.0 77
USC00514830 2016-01-29 00:00:00 0.13 76
USC00514830 2016-01-30 00:00:00 0.0 76
USC00514830 2016-02-02 00:00:00 0.2 71
USC00514830 2016-02-04 00:00:00 0.0 76
USC00514830 2016-02-05 00:00:00 0.0 74
USC00514830 2016-02-06 00:00:00 0.0 73
USC00514830 2016-02-07 00:00:00 0.56 72
USC00514830 2016-02-08 00:00:00 0.0 70
USC00514830 2016-02-09 00:00:00 0.0 70
USC00514830 2016-02-10 00:00:00 0.0 63
USC00514830 2016-02-11 00:00:00 0.0 74
USC00514830 2016-02-12 00:00:00 0.0 78
USC00514830 2016-02-13 00:00:00 0.0 76
USC00514830 2016-02-14 00:00:00 0.0 79
USC00514830 2016-02-15 00:00:00 0.23 77
USC00514830 2016-02-16 00:00:00 0.03 75
USC00514830 2016-02-17 00:00:00 0.13 72
USC00514830 2016-02-18 00:00:00 0.0 74
USC00514830 2016-02-19 00:00:00 0.09 72
USC00514830 2016-02-20 00:00:00 0.09 74
USC00514830 2016-02-23 00:00:00 0.0 71
USC00514830 2016-02-24 00:00:00 0.0 70
USC00514830 2016-02-25 00:00:00 0.0 73
USC00514830 2016-02-26 00:00:00 0.36 75
USC00514830 2016-02-27 00:00:00 0.0 77
USC00514830 2016-02-28 00:00:00 0.0 76
USC00514830 2016-02-29 00:00:00 0.05 73
USC00514830 2016-03-01 00:00:00 0.07 73
USC00514830 2016-03-02 00:00:00 0.0 70
USC00514830 2016-03-03 00:00:00 0.0 71
USC00514830 2016-03-04 00:00:00 0.0 72
USC00514830 2016-03-05 00:00:00 0.0 76
USC00514830 2016-03-06 00:00:00 0.0 76
USC00514830 2016-03-07 00:00:00 0.0 78
USC00514830 2016-03-08 00:00:00 0.0 78
USC00514830 2016-03-09 00:00:00 0.22 68
USC00514830 2016-03-10 00:00:00 0.0 69
USC00514830 2016-03-11 00:00:00 0.01 72
USC00514830 2016-03-12 00:00:00 0.0 73
USC00514830 2016-03-15 00:00:00 1.08 71
USC00514830 2016-03-16 00:00:00 0.06 71
USC00514830 2016-03-17 00:00:00 0.0 69
USC00514830 2016-03-18 00:00:00 0.13 71

USC00514830 2016-03-19 00:00:00 0.03 72
USC00514830 2016-03-20 00:00:00 0.0 75
USC00514830 2016-03-21 00:00:00 0.0 74
USC00514830 2016-03-22 00:00:00 0.0 76
USC00514830 2016-03-23 00:00:00 0.72 74
USC00514830 2016-03-24 00:00:00 0.0 76
USC00514830 2016-03-25 00:00:00 0.04 75
USC00514830 2016-03-26 00:00:00 0.02 75
USC00514830 2016-03-29 00:00:00 0.0 77
USC00514830 2016-03-30 00:00:00 0.0 68
USC00514830 2016-03-31 00:00:00 0.0 74
USC00514830 2016-04-01 00:00:00 0.0 77
USC00514830 2016-04-02 00:00:00 0.0 77
USC00514830 2016-04-03 00:00:00 0.0 76
USC00514830 2016-04-04 00:00:00 0.0 78
USC00514830 2016-04-05 00:00:00 0.04 77
USC00514830 2016-04-06 00:00:00 0.08 71
USC00514830 2016-04-07 00:00:00 0.06 71
USC00514830 2016-04-08 00:00:00 0.0 77
USC00514830 2016-04-09 00:00:00 0.14 75
USC00514830 2016-04-10 00:00:00 0.06 76
USC00514830 2016-04-11 00:00:00 0.04 78
USC00514830 2016-04-12 00:00:00 0.0 77
USC00514830 2016-04-13 00:00:00 0.03 76
USC00514830 2016-04-14 00:00:00 0.02 77
USC00514830 2016-04-15 00:00:00 0.03 78
USC00514830 2016-04-18 00:00:00 0.46 73
USC00514830 2016-04-19 00:00:00 0.0 74
USC00514830 2016-04-20 00:00:00 0.03 74
USC00514830 2016-04-21 00:00:00 0.02 74
USC00514830 2016-04-22 00:00:00 0.0 75
USC00514830 2016-04-23 00:00:00 0.1 77
USC00514830 2016-04-24 00:00:00 0.01 76
USC00514830 2016-04-25 00:00:00 0.0 79
USC00514830 2016-04-26 00:00:00 0.01 77
USC00514830 2016-04-27 00:00:00 0.1 75
USC00514830 2016-04-28 00:00:00 0.0 77
USC00514830 2016-04-29 00:00:00 0.0 77
USC00514830 2016-04-30 00:00:00 0.08 77
USC00514830 2016-05-01 00:00:00 0.01 79
USC00514830 2016-05-02 00:00:00 0.11 77
USC00514830 2016-05-03 00:00:00 0.03 73
USC00514830 2016-05-04 00:00:00 0.36 73
USC00514830 2016-05-05 00:00:00 0.41 76
USC00514830 2016-05-10 00:00:00 0.15 73
USC00514830 2016-05-11 00:00:00 0.0 73
USC00514830 2016-05-12 00:00:00 0.0 74
USC00514830 2016-05-13 00:00:00 0.0 74
USC00514830 2016-05-16 00:00:00 0.0 78
USC00514830 2016-05-17 00:00:00 0.0 78
USC00514830 2016-05-18 00:00:00 0.36 74
USC00514830 2016-05-19 00:00:00 0.0 78
USC00514830 2016-05-20 00:00:00 0.04 78
USC00514830 2016-05-21 00:00:00 0.04 78
USC00514830 2016-05-22 00:00:00 0.04 79
USC00514830 2016-05-23 00:00:00 0.11 79
USC00514830 2016-05-24 00:00:00 0.0 78
USC00514830 2016-05-25 00:00:00 0.05 76
USC00514830 2016-05-26 00:00:00 0.35 78
USC00514830 2016-05-27 00:00:00 0.09 79
USC00514830 2016-05-28 00:00:00 0.04 79
USC00514830 2016-05-29 00:00:00 0.0 78
USC00514830 2016-05-30 00:00:00 0.0 74
USC00514830 2016-05-31 00:00:00 0.42 72
USC00514830 2016-06-01 00:00:00 0.22 71
USC00514830 2016-06-02 00:00:00 0.35 74
USC00514830 2016-06-03 00:00:00 0.02 75
USC00514830 2016-06-08 00:00:00 0.0 74
USC00514830 2016-06-09 00:00:00 0.12 76
USC00514830 2016-06-10 00:00:00 0.13 75
USC00514830 2016-06-11 00:00:00 0.01 77
USC00514830 2016-06-12 00:00:00 0.26 77
USC00514830 2016-06-13 00:00:00 0.01 79
USC00514830 2016-06-14 00:00:00 0.0 79
USC00514830 2016-06-15 00:00:00 0.18 78
USC00514830 2016-06-16 00:00:00 0.06 79
USC00514830 2016-06-17 00:00:00 0.17 73
USC00514830 2016-06-18 00:00:00 0.03 78
USC00514830 2016-06-19 00:00:00 0.03 79
USC00514830 2016-06-20 00:00:00 0.47 80
USC00514830 2016-06-21 00:00:00 0.0 76
USC00514830 2016-06-22 00:00:00 0.08 79
USC00514830 2016-06-23 00:00:00 0.1 79
USC00514830 2016-06-24 00:00:00 0.03 77
USC00514830 2016-06-25 00:00:00 0.44 80
USC00514830 2016-06-26 00:00:00 0.03 79
USC00514830 2016-06-27 00:00:00 0.0 78
USC00514830 2016-06-28 00:00:00 0.0 78
USC00514830 2016-06-29 00:00:00 0.06 79
USC00514830 2016-06-30 00:00:00 0.0 78
USC00514830 2016-07-01 00:00:00 0.0 78
USC00514830 2016-07-05 00:00:00 0.0 79
USC00514830 2016-07-06 00:00:00 0.2 77
USC00514830 2016-07-07 00:00:00 0.19 77
USC00514830 2016-07-08 00:00:00 0.05 78
USC00514830 2016-07-09 00:00:00 0.0 81
USC00514830 2016-07-10 00:00:00 0.12 77
USC00514830 2016-07-11 00:00:00 0.0 80
USC00514830 2016-07-12 00:00:00 0.03 80
USC00514830 2016-07-13 00:00:00 0.05 78
USC00514830 2016-07-14 00:00:00 0.38 80
USC00514830 2016-07-15 00:00:00 0.43 78
USC00514830 2016-07-16 00:00:00 0.65 80
USC00514830 2016-07-19 00:00:00 0.43 80
USC00514830 2016-07-20 00:00:00 0.0 79
USC00514830 2016-07-22 00:00:00 0.0 78
USC00514830 2016-07-27 00:00:00 0.0 82
USC00514830 2016-07-28 00:00:00 0.05 81
USC00514830 2016-07-29 00:00:00 0.01 76
USC00514830 2016-08-02 00:00:00 0.55 80
USC00514830 2016-08-03 00:00:00 0.0 82
USC00514830 2016-08-07 00:00:00 0.48 83
USC00514830 2016-08-08 00:00:00 0.01 82
USC00514830 2016-08-09 00:00:00 0.0 81
USC00514830 2016-08-10 00:00:00 0.0 81
USC00514830 2016-08-11 00:00:00 0.0 79
USC00514830 2016-08-12 00:00:00 0.12 81
USC00514830 2016-08-13 00:00:00 0.0 83
USC00514830 2016-08-16 00:00:00 0.02 81
USC00514830 2016-08-17 00:00:00 0.0 79
USC00514830 2016-08-18 00:00:00 0.01 79
USC00514830 2016-08-19 00:00:00 0.07 80
USC00514830 2016-08-20 00:00:00 0.0 81
USC00514830 2016-08-23 00:00:00 0.05 80
USC00514830 2016-08-24 00:00:00 2.28 80
USC00514830 2016-08-25 00:00:00 0.0 81
USC00514830 2016-08-26 00:00:00 0.02 81
USC00514830 2016-08-27 00:00:00 0.02 81
USC00514830 2016-08-28 00:00:00 0.14 81
USC00514830 2016-08-29 00:00:00 0.04 80
USC00514830 2016-09-01 00:00:00 0.0 82
USC00514830 2016-09-02 00:00:00 0.19 81
USC00514830 2016-09-06 00:00:00 0.04 80
USC00514830 2016-09-07 00:00:00 0.23 80
USC00514830 2016-09-08 00:00:00 0.01 81
USC00514830 2016-09-09 00:00:00 0.29 77
USC00514830 2016-09-13 00:00:00 0.32 79
USC00514830 2016-09-14 00:00:00 1.84 79
USC00514830 2016-09-15 00:00:00 0.07 81
USC00514830 2016-09-16 00:00:00 0.07 79
USC00514830 2016-09-20 00:00:00 0.25 80
USC00514830 2016-09-21 00:00:00 0.02 80
USC00514830 2016-09-22 00:00:00 0.17 78
USC00514830 2016-09-23 00:00:00 0.15 81
USC00514830 2016-09-24 00:00:00 0.0 82
USC00514830 2016-09-25 00:00:00 0.0 82
USC00514830 2016-09-26 00:00:00 0.02 80
USC00514830 2016-09-27 00:00:00 0.0 79
USC00514830 2016-09-28 00:00:00 0.0 80
USC00514830 2016-09-29 00:00:00 0.2 79
USC00514830 2016-09-30 00:00:00 0.06 80
USC00514830 2016-10-01 00:00:00 0.08 80
USC00514830 2016-10-02 00:00:00 0.03 80
USC00514830 2016-10-03 00:00:00 0.03 80
USC00514830 2016-10-04 00:00:00 0.0 81
USC00514830 2016-10-05 00:00:00 0.0 80
USC00514830 2016-10-06 00:00:00 0.0 80
USC00514830 2016-10-07 00:00:00 0.0 79
USC00514830 2016-10-11 00:00:00 0.04 80
USC00514830 2016-10-12 00:00:00 0.0 80
USC00514830 2016-10-13 00:00:00 0.02 81
USC00514830 2016-10-14 00:00:00 0.0 79
USC00514830 2016-10-15 00:00:00 0.02 81
USC00514830 2016-10-18 00:00:00 0.03 80
USC00514830 2016-10-19 00:00:00 0.0 79
USC00514830 2016-10-20 00:00:00 0.01 77
USC00514830 2016-10-21 00:00:00 0.03 78
USC00514830 2016-10-24 00:00:00 0.01 77
USC00514830 2016-10-25 00:00:00 0.0 81
USC00514830 2016-10-27 00:00:00 0.2 78
USC00514830 2016-10-28 00:00:00 0.07 78
USC00514830 2016-10-29 00:00:00 0.26 76
USC00514830 2016-10-30 00:00:00 0.14 78
USC00514830 2016-10-31 00:00:00 0.0 77
USC00514830 2016-11-01 00:00:00 0.0 77
USC00514830 2016-11-02 00:00:00 0.0 78
USC00514830 2016-11-03 00:00:00 0.0 77
USC00514830 2016-11-04 00:00:00 0.0 77
USC00514830 2016-11-05 00:00:00 0.0 77
USC00514830 2016-11-06 00:00:00 0.0 78
USC00514830 2016-11-07 00:00:00 0.13 72
USC00514830 2016-11-08 00:00:00 0.02 73
USC00514830 2016-11-09 00:00:00 0.17 74
USC00514830 2016-11-10 00:00:00 0.0 75
USC00514830 2016-11-11 00:00:00 0.0 77
USC00514830 2016-11-12 00:00:00 0.0 78
USC00514830 2016-11-13 00:00:00 0.0 78
USC00514830 2016-11-14 00:00:00 0.05 79
USC00514830 2016-11-15 00:00:00 0.0 77
USC00514830 2016-11-16 00:00:00 0.18 78
USC00514830 2016-11-17 00:00:00 0.0 77
USC00514830 2016-11-26 00:00:00 0.02 78
USC00514830 2016-11-27 00:00:00 0.03 76
USC00514830 2016-11-28 00:00:00 0.0 76
USC00514830 2016-11-29 00:00:00 0.04 75
USC00514830 2016-11-30 00:00:00 0.03 76
USC00514830 2016-12-01 00:00:00 0.07 75
USC00514830 2016-12-02 00:00:00 0.4 77
USC00514830 2016-12-03 00:00:00 0.26 75
USC00514830 2016-12-04 00:00:00 0.0 77
USC00514830 2016-12-05 00:00:00 0.2 76
USC00514830 2016-12-08 00:00:00 0.02 75
USC00514830 2016-12-09 00:00:00 0.26 72
USC00514830 2016-12-10 00:00:00 0.0 76
USC00514830 2016-12-13 00:00:00 0.34 72
USC00514830 2016-12-14 00:00:00 0.12 72
USC00514830 2016-12-15 00:00:00 0.07 75
USC00514830 2016-12-16 00:00:00 0.0 69
USC00514830 2016-12-17 00:00:00 0.0 75
USC00514830 2016-12-18 00:00:00 0.04 74
USC00514830 2016-12-19 00:00:00 0.0 78
USC00514830 2016-12-20 00:00:00 0.0 77
USC00514830 2016-12-21 00:00:00 0.09 76
USC00514830 2016-12-22 00:00:00 0.05 72
USC00514830 2016-12-23 00:00:00 0.03 73
USC00514830 2016-12-24 00:00:00 0.13 74
USC00514830 2016-12-27 00:00:00 0.02 74
USC00514830 2016-12-28 00:00:00 0.01 73
USC00514830 2016-12-29 00:00:00 0.56 73
USC00514830 2016-12-30 00:00:00 0.29 71
USC00514830 2016-12-31 00:00:00 0.36 72
USC00514830 2017-01-01 00:00:00 0.0 74
USC00514830 2017-01-02 00:00:00 0.01 74
USC00514830 2017-01-03 00:00:00 0.0 70
USC00514830 2017-01-04 00:00:00 0.0 71
USC00514830 2017-01-05 00:00:00 0.0 72
USC00514830 2017-01-06 00:00:00 0.59 71
USC00514830 2017-01-07 00:00:00 0.0 71
USC00514830 2017-01-08 00:00:00 0.03 74
USC00514830 2017-01-09 00:00:00 0.0 72
USC00514830 2017-01-10 00:00:00 0.0 72
USC00514830 2017-01-11 00:00:00 0.0 76
USC00514830 2017-01-14 00:00:00 0.0 77
USC00514830 2017-01-17 00:00:00 0.0 75
USC00514830 2017-01-18 00:00:00 0.0 75
USC00514830 2017-01-19 00:00:00 0.0 77
USC00514830 2017-01-20 00:00:00 0.0 74
USC00514830 2017-01-21 00:00:00 0.02 73
USC00514830 2017-01-26 00:00:00 0.01 74
USC00514830 2017-01-27 00:00:00 0.0 74
USC00514830 2017-01-28 00:00:00 0.0 76
USC00514830 2017-01-31 00:00:00 0.0 70
USC00514830 2017-02-01 00:00:00 0.0 72
USC00514830 2017-02-02 00:00:00 0.0 72
USC00514830 2017-02-03 00:00:00 0.0 73
USC00514830 2017-02-06 00:00:00 0.04 77
USC00514830 2017-02-07 00:00:00 0.9 76
USC00514830 2017-02-08 00:00:00 0.0 67
USC00514830 2017-02-09 00:00:00 0.0 71
USC00514830 2017-02-10 00:00:00 0.0 73
USC00514830 2017-02-11 00:00:00 2.39 69
USC00514830 2017-02-12 00:00:00 1.91 76
USC00514830 2017-02-13 00:00:00 0.0 80
USC00514830 2017-02-14 00:00:00 0.0 79
USC00514830 2017-02-15 00:00:00 0.0 76
USC00514830 2017-02-16 00:00:00 0.62 73
USC00514830 2017-02-17 00:00:00 0.06 77
USC00514830 2017-02-21 00:00:00 0.0 71
USC00514830 2017-02-22 00:00:00 0.11 72
USC00514830 2017-02-23 00:00:00 0.0 75
USC00514830 2017-02-24 00:00:00 0.0 71
USC00514830 2017-02-27 00:00:00 0.0 71
USC00514830 2017-02-28 00:00:00 0.04 73
USC00514830 2017-03-01 00:00:00 1.12 71
USC00514830 2017-03-07 00:00:00 0.0 74
USC00514830 2017-03-08 00:00:00 0.0 74
USC00514830 2017-03-09 00:00:00 0.5 69
USC00514830 2017-03-10 00:00:00 0.13 75
USC00514830 2017-03-13 00:00:00 0.0 77
USC00514830 2017-03-14 00:00:00 0.0 77
USC00514830 2017-03-17 00:00:00 0.06 72
USC00514830 2017-03-18 00:00:00 0.0 76
USC00514830 2017-03-21 00:00:00 0.0 76
USC00514830 2017-03-22 00:00:00 0.0 76
USC00514830 2017-03-23 00:00:00 0.0 78
USC00514830 2017-03-24 00:00:00 0.15 75
USC00514830 2017-03-28 00:00:00 0.0 78
USC00514830 2017-03-29 00:00:00 0.03 77
USC00514830 2017-03-30 00:00:00 0.03 78
USC00514830 2017-03-31 00:00:00 0.0 77
USC00514830 2017-04-01 00:00:00 0.0 78
USC00514830 2017-04-02 00:00:00 0.0 77
USC00514830 2017-04-03 00:00:00 0.09 77
USC00514830 2017-04-04 00:00:00 0.0 76
USC00514830 2017-04-05 00:00:00 0.07 77
USC00514830 2017-04-06 00:00:00 0.0 76
USC00514830 2017-04-07 00:00:00 0.0 76
USC00514830 2017-04-10 00:00:00 0.0 79
USC00514830 2017-04-11 00:00:00 0.16 77
USC00514830 2017-04-12 00:00:00 0.29 77
USC00514830 2017-04-13 00:00:00 0.0 77
USC00514830 2017-04-14 00:00:00 0.29 77
USC00514830 2017-04-18 00:00:00 0.12 76
USC00514830 2017-04-19 00:00:00 0.0 83
USC00514830 2017-04-20 00:00:00 0.0 74
USC00514830 2017-04-21 00:00:00 1.05 70
USC00514830 2017-04-22 00:00:00 0.7 74
USC00514830 2017-04-25 00:00:00 0.0 77
USC00514830 2017-04-26 00:00:00 0.14 78
USC00514830 2017-04-27 00:00:00 0.02 78
USC00514830 2017-04-28 00:00:00 0.09 77
USC00514830 2017-04-29 00:00:00 0.95 71
USC00514830 2017-04-30 00:00:00 1.17 63
USC00514830 2017-05-01 00:00:00 0.03 78
USC00514830 2017-05-02 00:00:00 0.01 76
USC00514830 2017-05-03 00:00:00 0.01 78
USC00514830 2017-05-04 00:00:00 0.08 77
USC00514830 2017-05-05 00:00:00 0.28 78
USC00514830 2017-05-06 00:00:00 0.06 78
USC00514830 2017-05-08 00:00:00 0.95 73
USC00514830 2017-05-09 00:00:00 0.52 79
USC00514830 2017-05-10 00:00:00 0.0 76
USC00514830 2017-05-16 00:00:00 0.05 77
USC00514830 2017-05-17 00:00:00 0.0 78
USC00514830 2017-05-18 00:00:00 0.16 78
USC00514830 2017-05-19 00:00:00 0.01 79
USC00514830 2017-05-20 00:00:00 0.01 79
USC00514830 2017-05-23 00:00:00 0.11 78
USC00514830 2017-05-24 00:00:00 0.1 76
USC00514830 2017-05-25 00:00:00 0.07 79
USC00514830 2017-05-26 00:00:00 0.0 79
USC00514830 2017-05-27 00:00:00 0.0 79
USC00514830 2017-05-28 00:00:00 0.02 77
USC00514830 2017-05-29 00:00:00 0.0 79
USC00514830 2017-05-30 00:00:00 0.04 81
USC00514830 2017-05-31 00:00:00 0.0 81
USC00514830 2017-06-01 00:00:00 0.0 81
USC00514830 2017-06-02 00:00:00 0.15 78
USC00514830 2017-06-03 00:00:00 0.16 80
USC00514830 2017-06-04 00:00:00 0.05 79
USC00514830 2017-06-05 00:00:00 0.02 81
USC00514830 2017-06-06 00:00:00 0.0 80
USC00514830 2017-06-07 00:00:00 0.0 81
USC00514830 2017-06-08 00:00:00 0.01 79
USC00514830 2017-06-09 00:00:00 0.0 81
USC00514830 2017-06-10 00:00:00 0.53 78
USC00514830 2017-06-11 00:00:00 0.14 79
USC00514830 2017-06-12 00:00:00 0.35 79
USC00514830 2017-06-13 00:00:00 0.1 75
USC00514830 2017-06-14 00:00:00 0.21 79
USC00514830 2017-06-15 00:00:00 0.3 78
USC00514830 2017-06-16 00:00:00 0.02 80
USC00514830 2017-06-17 00:00:00 0.02 78
USC00514830 2017-06-18 00:00:00 0.18 77
USC00514830 2017-06-19 00:00:00 0.19 78
USC00514830 2017-06-20 00:00:00 0.17 79
USC00514830 2017-06-30 00:00:00 0.0 81
USC00514830 2017-07-08 00:00:00 0.06 81
USC00514830 2017-07-09 00:00:00 0.0 82
USC00514830 2017-07-10 00:00:00 0.0 80
USC00514830 2017-07-11 00:00:00 0.0 79
USC00514830 2017-07-12 00:00:00 0.02 81
USC00514830 2017-07-13 00:00:00 0.3 81
USC00514830 2017-07-14 00:00:00 0.0 80
USC00514830 2017-07-15 00:00:00 0.01 82
USC00514830 2017-07-16 00:00:00 0.12 79
USC00514830 2017-07-17 00:00:00 0.16 82
USC00514830 2017-07-18 00:00:00 0.0 82
USC00514830 2017-07-19 00:00:00 0.09 80
USC00514830 2017-07-20 00:00:00 0.0 79
USC00514830 2017-07-21 00:00:00 0.0 79
USC00514830 2017-07-22 00:00:00 0.12 80
USC00514830 2017-07-23 00:00:00 0.07 82
USC00514830 2017-07-24 00:00:00 1.19 79
USC00514830 2017-07-25 00:00:00 0.12 80
USC00514830 2017-07-26 00:00:00 0.02 79
USC00514830 2017-07-27 00:00:00 0.0 80
USC00514830 2017-07-28 00:00:00 0.14 81
USC00514830 2017-07-29 00:00:00 0.02 82
USC00514830 2017-08-01 00:00:00 0.12 74
USC00514830 2017-08-02 00:00:00 0.05 80
USC00514830 2017-08-03 00:00:00 0.01 81
USC00514830 2017-08-04 00:00:00 0.04 81
USC00514830 2017-08-06 00:00:00 0.0 82
USC00514830 2017-08-07 00:00:00 0.0 81

USC00514830 2017-08-08 00:00:00 0.1 78
USC00514830 2017-08-09 00:00:00 0.0 81
USC00514830 2017-08-10 00:00:00 0.0 81
USC00514830 2017-08-11 00:00:00 0.0 81
USC00514830 2017-08-14 00:00:00 0.01 81
USC00514830 2017-08-15 00:00:00 0.0 82
USC00514830 2017-08-16 00:00:00 0.0 82
USC00514830 2017-08-17 00:00:00 0.0 78
USC00514830 2017-08-18 00:00:00 0.0 77
USC00514830 2017-08-19 00:00:00 0.0 80
USC00514830 2017-08-20 00:00:00 0.01 80
USC00514830 2017-08-21 00:00:00 0.02 79
USC00514830 2017-08-23 00:00:00 0.0 82
USC00517948 PEARL CITY, HI US
USC00517948 2010-05-04 00:00:00 0.0 76
USC00517948 2010-05-05 00:00:00 0.02 75
USC00517948 2010-05-06 00:00:00 0.0 74
USC00517948 2010-05-07 00:00:00 0.08 75
USC00517948 2010-05-10 00:00:00 0.0 76
USC00517948 2010-05-11 00:00:00 0.0 73
USC00517948 2010-05-12 00:00:00 0.0 75
USC00517948 2010-05-14 00:00:00 0.0 77
USC00517948 2010-05-18 00:00:00 0.0 78
USC00517948 2010-05-19 00:00:00 0.0 77
USC00517948 2010-05-20 00:00:00 0.02 77
USC00517948 2010-05-21 00:00:00 0.03 76
USC00517948 2010-05-25 00:00:00 0.0 76
USC00517948 2010-05-26 00:00:00 0.0 77
USC00517948 2010-05-27 00:00:00 0.0 76
USC00517948 2010-05-28 00:00:00 0.0 77
USC00517948 2010-06-01 00:00:00 0.0 77
USC00517948 2010-06-02 00:00:00 0.0 76
USC00517948 2010-06-03 00:00:00 0.14 77
USC00517948 2010-06-04 00:00:00 0.0 75
USC00517948 2010-06-07 00:00:00 0.0 76
USC00517948 2010-06-08 00:00:00 0.0 79
USC00517948 2010-06-09 00:00:00 0.0 79
USC00517948 2010-06-10 00:00:00 0.0 77
USC00517948 2010-06-15 00:00:00 0.0 76
USC00517948 2010-06-16 00:00:00 0.0 77
USC00517948 2010-06-17 00:00:00 0.0 76
USC00517948 2010-06-18 00:00:00 0.05 73
USC00517948 2010-06-21 00:00:00 0.0 76
USC00517948 2010-06-22 00:00:00 0.02 77
USC00517948 2010-06-23 00:00:00 0.0 77
USC00517948 2010-06-24 00:00:00 0.02 78
USC00517948 2010-06-25 00:00:00 0.1 77
USC00517948 2010-06-28 00:00:00 0.0 76
USC00517948 2010-06-29 00:00:00 0.0 78
USC00517948 2010-06-30 00:00:00 0.0 78
USC00517948 2010-07-01 00:00:00 0.0 73
USC00517948 2010-07-02 00:00:00 0.02 74
USC00517948 2010-07-07 00:00:00 0.03 76
USC00517948 2010-07-08 00:00:00 0.05 75
USC00517948 2010-07-09 00:00:00 0.08 73
USC00517948 2010-07-14 00:00:00 0.0 74
USC00517948 2010-07-15 00:00:00 0.0 74
USC00517948 2010-07-16 00:00:00 0.0 78
USC00517948 2010-07-19 00:00:00 0.0 72
USC00517948 2010-07-20 00:00:00 0.07 74
USC00517948 2010-07-21 00:00:00 0.0 78
USC00517948 2010-07-22 00:00:00 0.0 77
USC00517948 2010-07-23 00:00:00 0.0 76
USC00517948 2010-08-02 00:00:00 0.0 74
USC00517948 2010-08-03 00:00:00 0.23 73
USC00517948 2010-08-04 00:00:00 0.04 73
USC00517948 2010-08-05 00:00:00 0.09 73
USC00517948 2010-08-06 00:00:00 0.02 75
USC00517948 2010-08-09 00:00:00 0.0 77
USC00517948 2010-08-10 00:00:00 0.0 79
USC00517948 2010-08-11 00:00:00 0.0 74
USC00517948 2010-08-12 00:00:00 0.05 75
USC00517948 2010-08-13 00:00:00 0.0 76
USC00517948 2010-08-16 00:00:00 0.0 75
USC00517948 2010-08-17 00:00:00 0.0 75
USC00517948 2010-08-18 00:00:00 0.0 75
USC00517948 2010-08-19 00:00:00 0.0 79
USC00517948 2010-08-23 00:00:00 0.0 77
USC00517948 2010-08-24 00:00:00 0.0 74
USC00517948 2010-08-25 00:00:00 0.04 74
USC00517948 2010-08-26 00:00:00 0.04 75
USC00517948 2010-08-27 00:00:00 0.06 76
USC00517948 2010-08-30 00:00:00 0.0 74
USC00517948 2010-08-31 00:00:00 0.0 75
USC00517948 2010-09-01 00:00:00 0.0 73
USC00517948 2010-09-02 00:00:00 0.05 74
USC00517948 2010-09-03 00:00:00 0.08 75
USC00517948 2010-09-07 00:00:00 0.0 77
USC00517948 2010-09-08 00:00:00 0.0 75
USC00517948 2010-09-09 00:00:00 0.0 78
USC00517948 2010-09-10 00:00:00 0.0 76
USC00517948 2010-09-13 00:00:00 0.0 77
USC00517948 2010-09-14 00:00:00 0.0 78
USC00517948 2010-09-15 00:00:00 0.0 78
USC00517948 2010-09-16 00:00:00 0.02 78
USC00517948 2010-09-17 00:00:00 0.0 78
USC00517948 2010-09-20 00:00:00 0.01 78
USC00517948 2010-09-21 00:00:00 0.26 77
USC00517948 2010-09-22 00:00:00 0.04 74
USC00517948 2010-09-23 00:00:00 0.01 74
USC00517948 2010-09-24 00:00:00 0.0 75
USC00517948 2010-09-27 00:00:00 0.0 76
USC00517948 2010-09-28 00:00:00 0.0 74
USC00517948 2010-10-04 00:00:00 0.01 71
USC00517948 2010-10-05 00:00:00 0.0 80
USC00517948 2010-10-06 00:00:00 0.0 79
USC00517948 2010-10-07 00:00:00 0.0 80
USC00517948 2010-10-08 00:00:00 0.0 80
USC00517948 2010-10-12 00:00:00 0.04 80
USC00517948 2010-10-13 00:00:00 0.0 77
USC00517948 2010-10-14 00:00:00 0.0 76
USC00517948 2010-10-15 00:00:00 0.0 76
USC00517948 2010-10-18 00:00:00 0.0 74
USC00517948 2010-10-19 00:00:00 0.0 74
USC00517948 2010-10-20 00:00:00 0.0 74
USC00517948 2010-10-21 00:00:00 0.0 74
USC00517948 2010-10-22 00:00:00 0.0 72
USC00517948 2010-10-25 00:00:00 0.0 77
USC00517948 2010-10-26 00:00:00 0.03 76
USC00517948 2010-10-27 00:00:00 0.0 77
USC00517948 2010-10-28 00:00:00 0.0 78
USC00517948 2010-10-29 00:00:00 0.0 75
USC00517948 2010-11-04 00:00:00 0.0 73
USC00517948 2010-11-05 00:00:00 0.0 73
USC00517948 2010-11-08 00:00:00 0.0 73
USC00517948 2010-11-09 00:00:00 0.01 72
USC00517948 2010-11-10 00:00:00 0.04 72
USC00517948 2010-11-12 00:00:00 0.0 76
USC00517948 2010-11-16 00:00:00 0.02 74
USC00517948 2010-11-17 00:00:00 0.0 70
USC00517948 2010-11-18 00:00:00 0.0 72
USC00517948 2010-11-19 00:00:00 0.35 70
USC00517948 2010-11-22 00:00:00 0.0 68
USC00517948 2010-11-23 00:00:00 0.0 71
USC00517948 2010-11-24 00:00:00 0.01 73
USC00517948 2010-11-29 00:00:00 0.0 71
USC00517948 2010-11-30 00:00:00 0.23 73
USC00517948 2010-12-01 00:00:00 0.7 72
USC00517948 2010-12-02 00:00:00 0.26 75
USC00517948 2010-12-06 00:00:00 0.0 66
USC00517948 2010-12-07 00:00:00 0.0 66
USC00517948 2010-12-08 00:00:00 0.0 67
USC00517948 2010-12-09 00:00:00 0.02 76
USC00517948 2010-12-10 00:00:00 1.75 68
USC00517948 2010-12-13 00:00:00 0.0 69
USC00517948 2010-12-14 00:00:00 0.0 71
USC00517948 2010-12-15 00:00:00 0.0 70
USC00517948 2010-12-16 00:00:00 0.0 68
USC00517948 2010-12-17 00:00:00 0.0 66
USC00517948 2011-01-04 00:00:00 0.0 70
USC00517948 2011-01-05 00:00:00 0.0 70
USC00517948 2011-01-06 00:00:00 0.0 72
USC00517948 2011-01-07 00:00:00 0.02 65
USC00517948 2011-01-10 00:00:00 0.0 67
USC00517948 2011-01-11 00:00:00 0.1 58
USC00517948 2011-01-18 00:00:00 0.27 65
USC00517948 2011-01-19 00:00:00 0.0 66
USC00517948 2011-01-20 00:00:00 0.03 61
USC00517948 2011-01-21 00:00:00 0.02 73
USC00517948 2011-01-24 00:00:00 0.0 68
USC00517948 2011-01-25 00:00:00 0.0 64
USC00517948 2011-01-26 00:00:00 0.0 64
USC00517948 2011-01-27 00:00:00 0.0 65
USC00517948 2011-01-28 00:00:00 0.0 73
USC00517948 2011-01-31 00:00:00 0.0 64
USC00517948 2011-02-08 00:00:00 1.6 69
USC00517948 2011-02-09 00:00:00 0.0 67
USC00517948 2011-02-10 00:00:00 0.02 67
USC00517948 2011-02-11 00:00:00 0.57 69
USC00517948 2011-02-15 00:00:00 0.0 68
USC00517948 2011-02-16 00:00:00 0.0 75
USC00517948 2011-02-17 00:00:00 0.0 73
USC00517948 2011-02-18 00:00:00 0.0 75
USC00517948 2011-03-30 00:00:00 0.0 73
USC00517948 2011-03-31 00:00:00 0.0 74
USC00517948 2011-04-01 00:00:00 0.0 76
USC00517948 2011-04-04 00:00:00 0.0 74
USC00517948 2011-04-05 00:00:00 0.0 71
USC00517948 2011-04-06 00:00:00 0.0 71
USC00517948 2011-04-07 00:00:00 1.09 69
USC00517948 2011-04-12 00:00:00 0.0 74
USC00517948 2011-04-13 00:00:00 0.0 75
USC00517948 2011-04-14 00:00:00 0.01 74
USC00517948 2011-04-15 00:00:00 0.0 75
USC00517948 2011-04-18 00:00:00 0.0 74
USC00517948 2011-04-19 00:00:00 0.0 72
USC00517948 2011-04-20 00:00:00 0.0 73
USC00517948 2011-04-21 00:00:00 0.0 66
USC00517948 2011-04-25 00:00:00 0.0 73
USC00517948 2011-04-26 00:00:00 0.0 76
USC00517948 2011-04-27 00:00:00 0.05 76
USC00517948 2011-04-28 00:00:00 0.0 75
USC00517948 2011-05-04 00:00:00 0.08 72
USC00517948 2011-05-05 00:00:00 0.06 73
USC00517948 2011-05-06 00:00:00 1.8 74
USC00517948 2011-05-23 00:00:00 0.0 77
USC00517948 2011-05-24 00:00:00 0.0 76
USC00517948 2011-05-25 00:00:00 0.01 76
USC00517948 2011-05-26 00:00:00 0.0 77
USC00517948 2011-05-27 00:00:00 0.01 78
USC00517948 2011-05-31 00:00:00 0.0 75
USC00517948 2011-06-02 00:00:00 0.0 77
USC00517948 2011-06-03 00:00:00 1.71 65
USC00517948 2011-06-06 00:00:00 0.0 76
USC00517948 2011-06-07 00:00:00 0.0 74
USC00517948 2011-06-08 00:00:00 0.05 76
USC00517948 2011-06-09 00:00:00 0.0 76
USC00517948 2011-06-13 00:00:00 0.0 77
USC00517948 2011-06-14 00:00:00 0.0 77
USC00517948 2011-06-21 00:00:00 0.25 74
USC00517948 2011-06-22 00:00:00 0.08 76
USC00517948 2011-06-23 00:00:00 0.22 73
USC00517948 2011-06-24 00:00:00 0.1 75
USC00517948 2011-06-30 00:00:00 0.0 75
USC00517948 2011-07-01 00:00:00 0.0 75
USC00517948 2011-07-26 00:00:00 0.0 77
USC00517948 2011-07-27 00:00:00 0.02 77
USC00517948 2011-07-28 00:00:00 0.0 75
USC00517948 2011-08-03 00:00:00 0.0 76
USC00517948 2011-08-08 00:00:00 0.0 78
USC00517948 2011-08-09 00:00:00 0.0 78
USC00517948 2011-08-10 00:00:00 0.0 77
USC00517948 2011-08-11 00:00:00 0.0 77
USC00517948 2011-08-12 00:00:00 0.0 77
USC00517948 2011-08-15 00:00:00 0.0 78
USC00517948 2011-08-16 00:00:00 0.05 76
USC00517948 2011-08-17 00:00:00 0.02 78
USC00517948 2011-08-23 00:00:00 0.0 78
USC00517948 2011-08-24 00:00:00 0.0 77
USC00517948 2011-09-06 00:00:00 0.0 73
USC00517948 2011-09-07 00:00:00 0.0 75
USC00517948 2011-09-08 00:00:00 0.0 74
USC00517948 2011-09-09 00:00:00 0.0 77
USC00517948 2011-09-13 00:00:00 0.0 77
USC00517948 2011-09-14 00:00:00 0.0 77
USC00517948 2011-09-15 00:00:00 0.0 75
USC00517948 2011-09-16 00:00:00 0.08 79
USC00517948 2011-09-20 00:00:00 0.01 78
USC00517948 2011-09-26 00:00:00 0.0 75
USC00517948 2011-09-27 00:00:00 0.0 76
USC00517948 2011-09-28 00:00:00 0.0 76
USC00517948 2011-09-29 00:00:00 0.0 77
USC00517948 2011-09-30 00:00:00 0.0 76
USC00517948 2011-10-03 00:00:00 0.0 77
USC00517948 2011-10-04 00:00:00 0.05 75
USC00517948 2011-10-05 00:00:00 0.06 79
USC00517948 2011-10-06 00:00:00 0.0 74
USC00517948 2011-10-07 00:00:00 0.0 77
USC00517948 2011-10-10 00:00:00 0.0 77
USC00517948 2011-10-11 00:00:00 0.0 76
USC00517948 2011-10-12 00:00:00 0.0 73
USC00517948 2011-10-13 00:00:00 0.0 77
USC00517948 2011-10-14 00:00:00 0.08 73
USC00517948 2011-10-17 00:00:00 0.0 79
USC00517948 2011-10-18 00:00:00 0.0 76
USC00517948 2011-10-19 00:00:00 0.12 73
USC00517948 2011-10-20 00:00:00 0.0 76
USC00517948 2011-11-08 00:00:00 0.08 76
USC00517948 2011-11-09 00:00:00 0.17 74
USC00517948 2011-11-10 00:00:00 0.1 76
USC00517948 2011-11-17 00:00:00 0.0 74
USC00517948 2011-11-18 00:00:00 0.0 73
USC00517948 2011-11-21 00:00:00 0.0 74
USC00517948 2011-11-29 00:00:00 0.0 72
USC00517948 2011-11-30 00:00:00 0.12 72
USC00517948 2011-12-01 00:00:00 0.0 69
USC00517948 2011-12-02 00:00:00 0.0 69
USC00517948 2011-12-05 00:00:00 0.0 71
USC00517948 2011-12-06 00:00:00 0.0 72
USC00517948 2011-12-07 00:00:00 0.07 69
USC00517948 2011-12-08 00:00:00 0.05 72
USC00517948 2011-12-09 00:00:00 0.16 70
USC00517948 2011-12-13 00:00:00 2.8 69
USC00517948 2011-12-14 00:00:00 0.86 71
USC00517948 2011-12-15 00:00:00 0.02 72
USC00517948 2012-01-04 00:00:00 0.0 76
USC00517948 2012-01-05 00:00:00 0.0 74
USC00517948 2012-01-06 00:00:00 0.0 65
USC00517948 2012-01-09 00:00:00 0.0 64
USC00517948 2012-01-10 00:00:00 0.0 66
USC00517948 2012-01-17 00:00:00 0.0 69
USC00517948 2012-01-18 00:00:00 0.0 73
USC00517948 2012-01-19 00:00:00 0.0 73
USC00517948 2012-01-20 00:00:00 0.0 73
USC00517948 2012-01-23 00:00:00 0.0 69
USC00517948 2012-01-24 00:00:00 0.0 72
USC00517948 2012-01-25 00:00:00 0.0 68
USC00517948 2012-01-26 00:00:00 0.0 74
USC00517948 2012-01-27 00:00:00 0.33 66
USC00517948 2012-01-31 00:00:00 0.0 71
USC00517948 2012-02-01 00:00:00 0.0 63
USC00517948 2012-02-02 00:00:00 0.0 74
USC00517948 2012-02-03 00:00:00 0.0 65
USC00517948 2012-02-07 00:00:00 0.48 69
USC00517948 2012-02-08 00:00:00 0.32 66
USC00517948 2012-02-09 00:00:00 0.0 68
USC00517948 2012-02-10 00:00:00 0.0 70
USC00517948 2012-02-14 00:00:00 0.0 72
USC00517948 2012-02-15 00:00:00 0.0 68
USC00517948 2012-02-22 00:00:00 0.0 73
USC00517948 2012-02-23 00:00:00 0.0 74
USC00517948 2012-02-24 00:00:00 0.0 75
USC00517948 2012-02-28 00:00:00 0.0 73
USC00517948 2012-03-20 00:00:00 0.0 72
USC00517948 2012-03-23 00:00:00 0.02 71
USC00517948 2012-04-03 00:00:00 0.0 72
USC00517948 2012-04-04 00:00:00 0.0 71
USC00517948 2012-04-05 00:00:00 0.0 73
USC00517948 2012-04-10 00:00:00 0.14 68
USC00517948 2012-04-11 00:00:00 0.07 71
USC00517948 2012-04-12 00:00:00 0.0 73
USC00517948 2012-04-13 00:00:00 0.0 72
USC00517948 2012-04-17 00:00:00 0.0 74
USC00517948 2012-04-23 00:00:00 0.26 70
USC00517948 2012-05-04 00:00:00 0.07 73
USC00517948 2012-05-08 00:00:00 0.0 75
USC00517948 2012-05-11 00:00:00 0.0 74
USC00517948 2012-05-14 00:00:00 0.0 69
USC00517948 2012-05-15 00:00:00 0.0 72
USC00517948 2012-05-16 00:00:00 0.0 73
USC00517948 2012-05-22 00:00:00 0.0 75
USC00517948 2012-05-23 00:00:00 0.0 76
USC00517948 2012-05-24 00:00:00 0.02 76
USC00517948 2012-05-25 00:00:00 0.0 77
USC00517948 2012-05-30 00:00:00 0.0 75
USC00517948 2012-05-31 00:00:00 0.02 73
USC00517948 2012-06-01 00:00:00 0.04 74
USC00517948 2012-06-05 00:00:00 0.0 74
USC00517948 2012-06-08 00:00:00 0.0 76
USC00517948 2012-06-13 00:00:00 0.0 77
USC00517948 2012-06-14 00:00:00 0.25 78
USC00517948 2012-06-19 00:00:00 0.02 72
USC00517948 2012-06-20 00:00:00 0.05 76
USC00517948 2012-06-21 00:00:00 0.0 76
USC00517948 2012-06-22 00:00:00 0.0 73
USC00517948 2012-06-28 00:00:00 0.0 76
USC00517948 2012-06-29 00:00:00 0.0 76
USC00517948 2012-07-11 00:00:00 0.0 76
USC00517948 2012-07-12 00:00:00 0.0 74
USC00517948 2012-07-13 00:00:00 0.0 77
USC00517948 2012-07-17 00:00:00 0.0 77
USC00517948 2012-07-20 00:00:00 0.0 75
USC00517948 2012-07-23 00:00:00 0.0 78
USC00517948 2012-07-24 00:00:00 0.0 77
USC00517948 2012-11-01 00:00:00 0.0 76
USC00517948 2012-11-07 00:00:00 0.01 78
USC00517948 2012-11-19 00:00:00 0.03 72
USC00517948 2012-12-03 00:00:00 0.0 78
USC00517948 2012-12-04 00:00:00 0.0 73
USC00517948 2012-12-05 00:00:00 0.02 74
USC00517948 2012-12-10 00:00:00 0.0 76
USC00517948 2012-12-11 00:00:00 0.0 75
USC00517948 2012-12-12 00:00:00 0.0 74
USC00517948 2012-12-13 00:00:00 0.04 73
USC00517948 2012-12-14 00:00:00 0.07 73
USC00517948 2013-02-01 00:00:00 0.0 69
USC00517948 2013-02-04 00:00:00 0.0 71
USC00517948 2013-02-22 00:00:00 1.5 70
USC00517948 2013-02-25 00:00:00 0.0 71
USC00517948 2013-02-28 00:00:00 0.0 75
USC00517948 2013-03-01 00:00:00 0.0 72
USC00517948 2013-03-05 00:00:00 0.0 70
USC00517948 2013-03-06 00:00:00 0.0 68
USC00517948 2013-03-07 00:00:00 0.0 68
USC00517948 2013-03-11 00:00:00 1.48 71
USC00517948 2013-03-12 00:00:00 0.02 68
USC00517948 2013-03-13 00:00:00 0.0 66
USC00517948 2013-03-14 00:00:00 0.03 68
USC00517948 2013-03-15 00:00:00 0.0 70
USC00517948 2013-04-01 00:00:00 0.0 66
USC00517948 2013-04-02 00:00:00 0.0 68
USC00517948 2013-04-03 00:00:00 0.0 67
USC00517948 2013-04-04 00:00:00 0.02 71
USC00517948 2013-04-05 00:00:00 0.0 70
USC00517948 2013-04-09 00:00:00 0.02 74

USC00517948 2013-04-10 00:00:00 0.02 73
USC00517948 2013-04-11 00:00:00 0.0 74
USC00517948 2013-04-12 00:00:00 0.0 76
USC00517948 2013-04-18 00:00:00 0.0 76
USC00517948 2013-04-19 00:00:00 0.0 75
USC00517948 2013-04-25 00:00:00 0.06 76
USC00517948 2013-04-26 00:00:00 0.0 77
USC00517948 2013-05-01 00:00:00 0.12 75
USC00517948 2013-05-02 00:00:00 0.02 75
USC00517948 2013-05-06 00:00:00 0.02 74
USC00517948 2013-05-09 00:00:00 0.0 76
USC00517948 2013-05-10 00:00:00 0.0 77
USC00517948 2013-05-16 00:00:00 0.17 79
USC00517948 2013-05-17 00:00:00 0.0 76
USC00517948 2013-05-21 00:00:00 0.02 74
USC00517948 2013-05-22 00:00:00 0.02 77
USC00517948 2013-05-23 00:00:00 0.0 80
USC00517948 2013-05-24 00:00:00 0.0 73
USC00517948 2013-06-05 00:00:00 0.02 78
USC00517948 2013-06-06 00:00:00 0.0 78
USC00517948 2013-06-07 00:00:00 0.0 75
USC00517948 2013-06-10 00:00:00 0.0 77
USC00517948 2013-06-18 00:00:00 0.08 77
USC00517948 2013-06-19 00:00:00 0.0 80
USC00517948 2013-06-20 00:00:00 0.04 70
USC00517948 2013-06-21 00:00:00 0.08 78
USC00517948 2013-06-27 00:00:00 0.01 72
USC00517948 2013-07-01 00:00:00 0.03 76
USC00517948 2013-07-02 00:00:00 0.04 75
USC00517948 2013-07-03 00:00:00 0.08 77
USC00517948 2013-07-12 00:00:00 0.04 72
USC00517948 2013-07-16 00:00:00 0.0 78
USC00517948 2013-07-17 00:00:00 0.02 79
USC00517948 2013-07-23 00:00:00 0.26 80
USC00517948 2013-07-24 00:00:00 0.02 79
USC00517948 2013-07-25 00:00:00 0.01 80
USC00517948 2013-08-01 00:00:00 0.5 78
USC00517948 2013-08-02 00:00:00 0.02 76
USC00517948 2013-08-08 00:00:00 0.0 81
USC00517948 2013-08-09 00:00:00 0.0 76
USC00517948 2013-08-13 00:00:00 0.0 75
USC00517948 2013-08-14 00:00:00 0.04 79
USC00517948 2013-08-15 00:00:00 0.0 79
USC00517948 2013-08-27 00:00:00 0.0 80
USC00517948 2013-08-28 00:00:00 0.0 77
USC00517948 2013-08-29 00:00:00 0.05 75
USC00517948 2013-09-04 00:00:00 0.0 76
USC00517948 2013-09-05 00:00:00 0.0 77
USC00517948 2013-09-06 00:00:00 0.0 79
USC00517948 2013-09-10 00:00:00 0.0 76
USC00517948 2013-09-11 00:00:00 0.0 80
USC00517948 2013-09-12 00:00:00 0.0 79
USC00517948 2013-09-13 00:00:00 0.3 79
USC00517948 2013-09-20 00:00:00 0.0 80
USC00517948 2013-09-26 00:00:00 0.2 76
USC00517948 2013-09-27 00:00:00 0.03 78
USC00517948 2013-10-03 00:00:00 0.0 79
USC00517948 2013-10-08 00:00:00 0.0 76
USC00517948 2013-10-11 00:00:00 0.0 80
USC00517948 2013-10-16 00:00:00 0.05 73
USC00517948 2013-10-17 00:00:00 0.0 75
USC00517948 2013-10-18 00:00:00 0.0 73
USC00517948 2013-10-22 00:00:00 0.0 74
USC00517948 2013-10-23 00:00:00 0.0 75
USC00517948 2013-10-24 00:00:00 0.0 72
USC00517948 2013-10-29 00:00:00 0.0 79
USC00517948 2013-10-30 00:00:00 0.0 76
USC00517948 2013-10-31 00:00:00 0.0 79
USC00517948 2013-11-01 00:00:00 0.0 75
USC00517948 2013-11-05 00:00:00 0.0 76
USC00517948 2013-11-06 00:00:00 0.0 76
USC00517948 2013-11-07 00:00:00 0.0 75
USC00517948 2013-11-14 00:00:00 0.0 74
USC00517948 2013-11-15 00:00:00 0.2 73
USC00517948 2013-11-21 00:00:00 0.0 73
USC00517948 2013-11-22 00:00:00 0.0 71
USC00517948 2013-11-26 00:00:00 0.0 76
USC00517948 2013-11-27 00:00:00 0.0 74
USC00517948 2013-12-05 00:00:00 0.0 67
USC00517948 2013-12-06 00:00:00 0.02 69
USC00517948 2013-12-10 00:00:00 0.0 75
USC00517948 2013-12-11 00:00:00 0.0 74
USC00517948 2013-12-12 00:00:00 0.0 72
USC00517948 2013-12-13 00:00:00 0.0 71
USC00517948 2013-12-17 00:00:00 0.02 74
USC00517948 2013-12-27 00:00:00 0.0 71
USC00517948 2014-01-03 00:00:00 0.63 67
USC00517948 2014-01-07 00:00:00 0.0 68
USC00517948 2014-01-08 00:00:00 0.0 66
USC00517948 2014-01-22 00:00:00 0.25 73
USC00517948 2014-01-23 00:00:00 0.0 61
USC00517948 2014-01-28 00:00:00 0.14 70
USC00517948 2014-01-29 00:00:00 0.47 70
USC00517948 2014-01-30 00:00:00 0.05 66
USC00517948 2014-02-05 00:00:00 0.35 69
USC00517948 2014-02-12 00:00:00 0.0 67
USC00517948 2014-02-13 00:00:00 0.0 68
USC00517948 2014-02-19 00:00:00 0.02 72
USC00517948 2014-02-20 00:00:00 0.0 68
USC00517948 2014-02-21 00:00:00 0.0 70
USC00517948 2014-02-25 00:00:00 0.0 70
USC00517948 2014-02-26 00:00:00 0.0 72
USC00517948 2014-02-28 00:00:00 0.03 72
USC00517948 2014-03-04 00:00:00 0.0 67
USC00517948 2014-03-05 00:00:00 0.0 70
USC00517948 2014-03-06 00:00:00 0.0 72
USC00517948 2014-03-10 00:00:00 1.65 73
USC00517948 2014-03-11 00:00:00 0.78 70
USC00517948 2014-03-28 00:00:00 0.0 78
USC00517948 2014-04-01 00:00:00 0.13 70
USC00517948 2014-04-02 00:00:00 0.02 77
USC00517948 2014-04-03 00:00:00 0.03 75
USC00517948 2014-04-04 00:00:00 0.0 74
USC00517948 2014-04-08 00:00:00 0.0 71
USC00517948 2014-04-09 00:00:00 0.0 70
USC00517948 2014-04-10 00:00:00 0.0 68
USC00517948 2014-04-11 00:00:00 0.0 72
USC00517948 2014-04-16 00:00:00 0.06 74
USC00517948 2014-04-22 00:00:00 0.09 77
USC00517948 2014-04-23 00:00:00 0.0 77
USC00517948 2014-04-24 00:00:00 0.0 76
USC00517948 2014-05-02 00:00:00 0.0 78
USC00517948 2014-05-06 00:00:00 0.72 76
USC00517948 2014-05-07 00:00:00 0.03 76
USC00517948 2014-05-14 00:00:00 0.0 75
USC00517948 2014-05-15 00:00:00 0.0 76
USC00517948 2014-05-16 00:00:00 0.0 78
USC00517948 2014-05-20 00:00:00 0.01 78
USC00517948 2014-05-21 00:00:00 0.26 77
USC00517948 2014-05-22 00:00:00 0.0 80
USC00517948 2014-05-23 00:00:00 0.0 77
USC00517948 2014-06-03 00:00:00 0.0 79
USC00517948 2014-06-10 00:00:00 0.0 79
USC00517948 2014-06-13 00:00:00 0.0 79
USC00517948 2014-06-17 00:00:00 0.2 79
USC00517948 2014-06-18 00:00:00 0.0 78
USC00517948 2014-06-19 00:00:00 0.01 80
USC00517948 2014-06-20 00:00:00 0.14 81
USC00517948 2014-06-27 00:00:00 0.0 81
USC00517948 2014-07-15 00:00:00 0.0 82
USC00517948 2014-07-16 00:00:00 0.0 81
USC00517948 2014-07-17 00:00:00 0.02 81
USC00517948 2014-07-18 00:00:00 0.0 81
USC00517948 2014-07-25 00:00:00 0.0 80
USC00517948 2014-07-29 00:00:00 0.0 81
USC00517948 2014-07-30 00:00:00 0.0 83
USC00517948 2014-08-12 00:00:00 0.0 81
USC00517948 2014-08-13 00:00:00 0.02 80
USC00517948 2014-08-14 00:00:00 0.0 80
USC00517948 2014-08-19 00:00:00 0.0 76
USC00517948 2014-08-20 00:00:00 0.0 80
USC00517948 2014-08-21 00:00:00 0.0 82
USC00517948 2014-08-22 00:00:00 0.0 80
USC00517948 2014-08-27 00:00:00 0.05 77
USC00517948 2014-09-02 00:00:00 0.0 83
USC00517948 2014-09-03 00:00:00 0.0 83
USC00517948 2014-09-04 00:00:00 0.0 80
USC00517948 2014-09-09 00:00:00 0.0 83
USC00517948 2014-09-10 00:00:00 0.0 84
USC00517948 2014-09-11 00:00:00 0.0 81
USC00517948 2014-09-12 00:00:00 0.0 80
USC00517948 2014-09-18 00:00:00 0.0 82
USC00517948 2014-09-19 00:00:00 0.12 81
USC00517948 2014-09-22 00:00:00 0.0 80
USC00517948 2014-09-23 00:00:00 0.02 82
USC00517948 2014-09-30 00:00:00 0.0 83
USC00517948 2014-10-01 00:00:00 0.0 80
USC00517948 2014-10-02 00:00:00 0.05 81
USC00517948 2014-10-03 00:00:00 0.0 81
USC00517948 2014-10-17 00:00:00 0.0 80
USC00517948 2014-10-21 00:00:00 0.03 81
USC00517948 2014-10-22 00:00:00 0.03 81
USC00517948 2014-11-18 00:00:00 0.0 79
USC00517948 2014-11-19 00:00:00 0.0 81
USC00517948 2014-12-01 00:00:00 0.28 74
USC00517948 2014-12-02 00:00:00 0.0 75
USC00517948 2014-12-03 00:00:00 0.05 74
USC00517948 2014-12-04 00:00:00 0.15 77
USC00517948 2014-12-10 00:00:00 0.0 76
USC00517948 2014-12-11 00:00:00 0.06 75
USC00517948 2014-12-15 00:00:00 0.1 77
USC00517948 2014-12-22 00:00:00 0.04 77
USC00517948 2014-12-23 00:00:00 0.1 76
USC00517948 2014-12-24 00:00:00 0.02 69
USC00517948 2014-12-26 00:00:00 0.0 70
USC00517948 2014-12-30 00:00:00 0.0 75
USC00517948 2015-01-06 00:00:00 0.0 65
USC00517948 2015-01-07 00:00:00 0.0 70
USC00517948 2015-01-08 00:00:00 0.0 72
USC00517948 2015-01-09 00:00:00 0.0 70
USC00517948 2015-01-30 00:00:00 0.0 68
USC00517948 2015-02-03 00:00:00 0.03 75
USC00517948 2015-02-04 00:00:00 0.16 73
USC00517948 2015-02-10 00:00:00 0.1 76
USC00517948 2015-02-11 00:00:00 0.0 79
USC00517948 2015-02-12 00:00:00 0.0 78
USC00517948 2015-02-13 00:00:00 0.0 78
USC00517948 2015-02-24 00:00:00 0.0 71
USC00517948 2015-02-25 00:00:00 0.0 74
USC00517948 2015-02-26 00:00:00 0.0 72
USC00517948 2015-03-03 00:00:00 0.0 76
USC00517948 2015-03-04 00:00:00 0.0 73
USC00517948 2015-03-10 00:00:00 0.0 65
USC00517948 2015-03-11 00:00:00 0.0 66
USC00517948 2015-03-12 00:00:00 0.0 67
USC00517948 2015-03-13 00:00:00 0.0 65
USC00517948 2015-03-25 00:00:00 0.0 77
USC00517948 2015-03-27 00:00:00 0.0 74
USC00517948 2015-03-31 00:00:00 0.03 79
USC00517948 2015-06-10 00:00:00 0.04 78
USC00517948 2015-06-12 00:00:00 0.0 77
USC00517948 2015-06-16 00:00:00 0.0 79
USC00517948 2015-06-17 00:00:00 0.01 77
USC00517948 2015-06-18 00:00:00 0.0 79
USC00517948 2015-06-19 00:00:00 0.0 80
USC00517948 2015-06-23 00:00:00 0.04 78
USC00517948 2015-06-24 00:00:00 0.09 79
USC00517948 2015-07-02 00:00:00 0.0 81
USC00517948 2015-07-09 00:00:00 0.1 83
USC00517948 2015-07-14 00:00:00 0.05 80
USC00517948 2015-07-15 00:00:00 0.08 79
USC00517948 2015-07-16 00:00:00 0.05 80
USC00517948 2015-08-07 00:00:00 0.05 81
USC00517948 2015-08-10 00:00:00 0.0 80
USC00517948 2015-08-11 00:00:00 0.0 81
USC00517948 2015-08-12 00:00:00 0.0 81
USC00517948 2015-08-26 00:00:00 1.5 80
USC00517948 2015-09-01 00:00:00 0.0 82
USC00517948 2015-09-02 00:00:00 0.0 80
USC00517948 2015-09-03 00:00:00 0.16 76
USC00517948 2015-09-09 00:00:00 0.0 81
USC00517948 2015-09-10 00:00:00 0.0 83
USC00517948 2015-09-11 00:00:00 0.2 79
USC00517948 2015-09-16 00:00:00 0.22 81
USC00517948 2015-09-17 00:00:00 0.0 79
USC00517948 2015-09-18 00:00:00 0.0 79
USC00517948 2015-11-04 00:00:00 0.28 80
USC00517948 2015-11-05 00:00:00 0.04 78
USC00517948 2015-12-02 00:00:00 0.28 65
USC00517948 2015-12-18 00:00:00 0.11 75
USC00517948 2016-01-20 00:00:00 0.0 77
USC00517948 2016-02-10 00:00:00 0.0 64
USC00517948 2016-03-16 00:00:00 0.0 73
USC00517948 2016-04-01 00:00:00 0.0 71
USC00517948 2016-04-04 00:00:00 0.0 76
USC00517948 2016-04-05 00:00:00 0.04 78
USC00517948 2016-04-08 00:00:00 0.0 76
USC00517948 2016-05-03 00:00:00 0.0 78
USC00517948 2016-05-13 00:00:00 0.44 73
USC00517948 2016-06-15 00:00:00 0.02 78
USC00517948 2016-06-16 00:00:00 0.1 76
USC00517948 2016-06-17 00:00:00 0.38 73
USC00517948 2016-06-20 00:00:00 0.1 74
USC00517948 2016-07-19 00:00:00 0.5 79
USC00517948 2016-07-26 00:00:00 0.01 82
USC00517948 2016-08-02 00:00:00 0.0 77
USC00517948 2016-08-03 00:00:00 0.02 79
USC00517948 2016-08-04 00:00:00 0.13 81
USC00517948 2016-08-05 00:00:00 0.03 77
USC00517948 2016-08-16 00:00:00 0.0 81
USC00517948 2016-08-17 00:00:00 0.0 81
USC00517948 2016-08-18 00:00:00 0.0 81
USC00517948 2016-08-25 00:00:00 0.0 81
USC00517948 2016-08-26 00:00:00 0.04 81
USC00517948 2016-08-30 00:00:00 0.02 79
USC00517948 2016-09-16 00:00:00 0.0 79
USC00517948 2016-09-20 00:00:00 0.0 73
USC00517948 2016-09-22 00:00:00 0.06 76
USC00517948 2016-09-23 00:00:00 0.0 80
USC00517948 2016-09-28 00:00:00 0.0 79
USC00517948 2016-09-29 00:00:00 0.04 80
USC00517948 2016-10-06 00:00:00 0.07 79
USC00517948 2016-10-25 00:00:00 0.4 77
USC00517948 2016-10-26 00:00:00 0.2 73
USC00517948 2016-11-09 00:00:00 0.0 76
USC00517948 2016-11-14 00:00:00 0.02 79
USC00517948 2016-12-08 00:00:00 0.27 70
USC00517948 2016-12-12 00:00:00 0.02 70
USC00517948 2016-12-21 00:00:00 0.06 73
USC00517948 2017-01-17 00:00:00 0.0 70
USC00517948 2017-01-18 00:00:00 0.0 73
USC00517948 2017-01-26 00:00:00 0.0 70
USC00517948 2017-01-27 00:00:00 0.0 65
USC00517948 2017-01-30 00:00:00 0.05 68
USC00517948 2017-01-31 00:00:00 0.0 68
USC00517948 2017-02-01 00:00:00 0.0 62
USC00517948 2017-02-02 00:00:00 0.0 70
USC00517948 2017-02-03 00:00:00 0.0 72
USC00517948 2017-02-07 00:00:00 0.0 67
USC00517948 2017-02-08 00:00:00 0.0 64
USC00517948 2017-02-09 00:00:00 0.0 64
USC00517948 2017-02-10 00:00:00 0.0 64
USC00517948 2017-02-14 00:00:00 0.0 76
USC00517948 2017-02-17 00:00:00 0.0 69
USC00517948 2017-02-22 00:00:00 0.17 72
USC00517948 2017-02-23 00:00:00 0.0 72
USC00517948 2017-02-24 00:00:00 0.0 68
USC00517948 2017-03-01 00:00:00 2.4 66
USC00517948 2017-03-02 00:00:00 0.44 73
USC00517948 2017-03-03 00:00:00 0.14 70
USC00517948 2017-03-09 00:00:00 0.0 68
USC00517948 2017-03-10 00:00:00 0.0 68
USC00517948 2017-03-14 00:00:00 0.06 73
USC00517948 2017-03-15 00:00:00 0.0 75
USC00517948 2017-03-31 00:00:00 0.0 78
USC00517948 2017-04-04 00:00:00 0.0 75
USC00517948 2017-04-05 00:00:00 0.0 73
USC00517948 2017-04-06 00:00:00 0.0 73
USC00517948 2017-04-07 00:00:00 0.0 76
USC00517948 2017-04-18 00:00:00 0.0 75
USC00517948 2017-06-22 00:00:00 0.0 81
USC00517948 2017-06-23 00:00:00 0.0 76
USC00517948 2017-06-27 00:00:00 0.0 80
USC00517948 2017-06-28 00:00:00 0.0 80
USC00517948 2017-06-29 00:00:00 0.0 79
USC00517948 2017-06-30 00:00:00 0.12 74
USC00517948 2017-07-18 00:00:00 0.0 78
USC00517948 2017-07-19 00:00:00 0.0 81
USC00517948 2017-07-20 00:00:00 0.0 80
USC00517948 2017-07-21 00:00:00 0.0 81
USC00517948 2017-07-25 00:00:00 0.0 81
USC00517948 2017-07-28 00:00:00 0.01 80
USC00518838 UPPER WAHIAWA 874.3, HI US
USC00518838 2010-01-01 00:00:00 0.21 72
USC00518838 2010-01-02 00:00:00 0.02 73
USC00518838 2010-01-03 00:00:00 0.0 67
USC00518838 2010-01-04 00:00:00 0.01 76
USC00518838 2010-01-05 00:00:00 0.02 73
USC00518838 2010-01-08 00:00:00 0.03 73
USC00518838 2010-01-09 00:00:00 0.01 69
USC00518838 2010-01-10 00:00:00 0.01 70
USC00518838 2010-01-11 00:00:00 0.14 72
USC00518838 2010-01-12 00:00:00 0.02 60
USC00518838 2010-01-13 00:00:00 0.02 68
USC00518838 2010-01-14 00:00:00 0.0 67
USC00518838 2010-01-19 00:00:00 0.0 70
USC00518838 2010-01-20 00:00:00 0.0 68
USC00518838 2010-01-26 00:00:00 0.13 74
USC00518838 2010-01-27 00:00:00 0.21 70
USC00518838 2010-01-28 00:00:00 0.01 70
USC00518838 2010-02-03 00:00:00 0.87 65
USC00518838 2010-02-04 00:00:00 0.01 66
USC00518838 2010-02-05 00:00:00 0.01 59
USC00518838 2010-02-06 00:00:00 0.02 73
USC00518838 2010-02-07 00:00:00 0.01 62
USC00518838 2010-02-09 00:00:00 0.0 70
USC00518838 2010-02-10 00:00:00 0.0 74
USC00518838 2010-02-13 00:00:00 0.06 67
USC00518838 2010-02-14 00:00:00 0.01 67
USC00518838 2010-02-15 00:00:00 0.0 70
USC00518838 2010-02-16 00:00:00 0.0 71
USC00518838 2010-02-17 00:00:00 0.01 65
USC00518838 2010-02-20 00:00:00 0.1 70
USC00518838 2010-02-21 00:00:00 0.01 68
USC00518838 2010-02-24 00:00:00 0.01 72
USC00518838 2010-02-25 00:00:00 0.02 72
USC00518838 2010-03-02 00:00:00 0.0 69
USC00518838 2010-03-06 00:00:00 1.08 63
USC00518838 2010-03-07 00:00:00 0.17 67
USC00518838 2010-03-08 00:00:00 0.64 66
USC00518838 2010-03-09 00:00:00 0.23 67
USC00518838 2010-03-12 00:00:00 0.04 69
USC00518838 2010-03-13 00:00:00 0.03 62
USC00518838 2010-03-14 00:00:00 0.02 62
USC00518838 2010-03-15 00:00:00 0.13 65
USC00518838 2010-03-16 00:00:00 0.46 63
USC00518838 2010-03-29 00:00:00 0.13 69
USC00518838 2010-03-30 00:00:00 0.04 69
USC00518838 2010-04-03 00:00:00 0.53 67
USC00518838 2010-04-04 00:00:00 0.87 66
USC00518838 2010-04-05 00:00:00 1.8 67
USC00518838 2010-04-06 00:00:00 0.3 70
USC00518838 2010-04-07 00:00:00 2.12 72
USC00518838 2010-04-08 00:00:00 0.47 74
USC00518838 2010-04-09 00:00:00 0.8 71
USC00518838 2010-04-14 00:00:00 0.03 67

USC00518838 2010-04-17 00:00:00 0.01 65
USC00518838 2010-04-18 00:00:00 0.2 70
USC00518838 2010-04-22 00:00:00 0.54 72
USC00518838 2010-04-23 00:00:00 0.1 67
USC00518838 2010-04-24 00:00:00 0.01 69
USC00518838 2010-04-25 00:00:00 0.01 74
USC00518838 2010-04-26 00:00:00 0.0 73
USC00518838 2010-05-01 00:00:00 0.29 69
USC00518838 2010-05-02 00:00:00 0.0 71
USC00518838 2010-05-03 00:00:00 0.87 67
USC00518838 2010-05-04 00:00:00 0.04 69
USC00518838 2010-05-05 00:00:00 0.03 71
USC00518838 2010-05-09 00:00:00 0.25 72
USC00518838 2010-05-10 00:00:00 0.06 72
USC00518838 2010-05-11 00:00:00 0.07 73
USC00518838 2010-05-12 00:00:00 0.06 79
USC00518838 2010-05-13 00:00:00 0.04 78
USC00518838 2010-05-14 00:00:00 0.02 75
USC00518838 2010-05-16 00:00:00 0.0 77
USC00518838 2010-05-17 00:00:00 0.03 79
USC00518838 2010-05-20 00:00:00 0.56 71
USC00518838 2010-05-21 00:00:00 0.45 70
USC00518838 2010-05-22 00:00:00 0.04 74
USC00518838 2010-05-23 00:00:00 0.6 70
USC00518838 2010-05-24 00:00:00 0.15 71
USC00518838 2010-05-25 00:00:00 0.04 73
USC00518838 2010-05-26 00:00:00 0.02 73
USC00518838 2010-06-02 00:00:00 0.03 70
USC00518838 2010-06-03 00:00:00 0.0 67
USC00518838 2010-06-04 00:00:00 0.0 70
USC00518838 2010-06-05 00:00:00 0.0 73
USC00518838 2010-06-06 00:00:00 0.0 73
USC00518838 2010-06-10 00:00:00 0.0 72
USC00518838 2010-06-11 00:00:00 0.0 77
USC00518838 2010-06-12 00:00:00 0.0 70
USC00518838 2010-06-13 00:00:00 0.01 78
USC00518838 2010-06-17 00:00:00 0.0 75
USC00518838 2010-06-18 00:00:00 0.3 70
USC00518838 2010-06-19 00:00:00 0.02 74
USC00518838 2010-06-20 00:00:00 0.03 77
USC00518838 2010-06-23 00:00:00 0.11 73
USC00518838 2010-06-24 00:00:00 0.28 73
USC00518838 2010-06-25 00:00:00 0.3 74
USC00518838 2010-06-29 00:00:00 0.1 72
USC00518838 2010-06-30 00:00:00 0.04 75
USC00518838 2010-07-01 00:00:00 0.09 73
USC00518838 2010-07-02 00:00:00 0.2 70
USC00518838 2010-07-03 00:00:00 0.84 73
USC00518838 2010-07-04 00:00:00 0.09 76
USC00518838 2010-07-05 00:00:00 0.03 75
USC00518838 2010-07-06 00:00:00 0.41 71
USC00518838 2010-07-07 00:00:00 0.11 73
USC00518838 2010-07-10 00:00:00 0.44 71
USC00518838 2010-07-11 00:00:00 0.01 72
USC00518838 2010-07-16 00:00:00 0.04 73
USC00518838 2010-07-28 00:00:00 0.01 80
USC00518838 2010-08-03 00:00:00 0.01 73
USC00518838 2010-08-04 00:00:00 0.25 72
USC00518838 2010-08-05 00:00:00 0.36 73
USC00518838 2010-08-06 00:00:00 0.03 74
USC00518838 2010-08-07 00:00:00 0.06 74
USC00518838 2010-08-10 00:00:00 0.03 73
USC00518838 2010-08-11 00:00:00 0.12 72
USC00518838 2010-08-18 00:00:00 0.02 79
USC00518838 2010-08-19 00:00:00 0.01 76
USC00518838 2010-08-20 00:00:00 0.0 76
USC00518838 2010-08-26 00:00:00 0.12 72
USC00518838 2010-08-29 00:00:00 0.38 74
USC00518838 2010-08-30 00:00:00 0.25 75
USC00518838 2010-08-31 00:00:00 0.12 74
USC00518838 2010-09-01 00:00:00 0.03 77
USC00518838 2010-09-04 00:00:00 0.04 73
USC00518838 2010-09-05 00:00:00 0.02 78
USC00518838 2010-09-06 00:00:00 0.0 76
USC00518838 2010-09-07 00:00:00 0.04 76
USC00518838 2010-09-10 00:00:00 0.02 76
USC00518838 2010-09-13 00:00:00 0.02 76
USC00518838 2010-09-14 00:00:00 0.0 79
USC00518838 2010-09-15 00:00:00 0.0 75
USC00518838 2010-09-16 00:00:00 0.01 75
USC00518838 2010-09-17 00:00:00 0.0 77
USC00518838 2010-09-18 00:00:00 0.03 78
USC00518838 2010-09-22 00:00:00 0.11 74
USC00518838 2010-09-23 00:00:00 0.05 74
USC00518838 2010-09-24 00:00:00 0.0 77
USC00518838 2010-09-27 00:00:00 0.0 83
USC00518838 2010-09-28 00:00:00 0.0 77
USC00518838 2010-10-01 00:00:00 0.25 71
USC00518838 2010-10-02 00:00:00 0.02 78
USC00518838 2010-10-03 00:00:00 0.03 70
USC00518838 2010-10-04 00:00:00 0.53 77
USC00518838 2010-10-05 00:00:00 0.02 71
USC00518838 2010-10-06 00:00:00 0.01 79
USC00518838 2010-10-07 00:00:00 0.03 77
USC00518838 2010-10-08 00:00:00 0.01 74
USC00518838 2010-10-25 00:00:00 0.0 77
USC00518838 2010-10-26 00:00:00 1.1 73
USC00518838 2010-10-27 00:00:00 0.4 75
USC00518838 2010-10-28 00:00:00 0.38 73
USC00518838 2010-10-29 00:00:00 0.1 71
USC00518838 2010-10-30 00:00:00 0.07 77
USC00518838 2010-10-31 00:00:00 0.0 76
USC00518838 2010-11-01 00:00:00 0.21 72
USC00518838 2010-11-02 00:00:00 0.03 77
USC00518838 2010-11-03 00:00:00 0.25 70
USC00518838 2010-11-04 00:00:00 0.12 72
USC00518838 2010-11-05 00:00:00 0.08 73
USC00518838 2010-11-16 00:00:00 0.08 76
USC00518838 2010-11-18 00:00:00 0.0 75
USC00518838 2010-11-19 00:00:00 0.35 72
USC00518838 2010-11-23 00:00:00 0.07 77
USC00518838 2010-11-24 00:00:00 0.16 76
USC00518838 2010-12-03 00:00:00 0.78 70
USC00518838 2010-12-06 00:00:00 0.02 78
USC00518838 2010-12-07 00:00:00 0.02 76
USC00518838 2010-12-08 00:00:00 0.33 73
USC00518838 2010-12-09 00:00:00 1.43 74
USC00518838 2010-12-10 00:00:00 2.5 63
USC00518838 2010-12-11 00:00:00 1.5 72
USC00518838 2010-12-14 00:00:00 0.13 74
USC00518838 2010-12-15 00:00:00 0.1 72
USC00518838 2010-12-16 00:00:00 0.05 68
USC00518838 2011-01-05 00:00:00 0.15 71
USC00518838 2011-01-06 00:00:00 0.14 65
USC00518838 2011-01-07 00:00:00 0.0 64
USC00518838 2011-01-11 00:00:00 0.73 74
USC00518838 2011-01-12 00:00:00 1.15 66
USC00518838 2011-01-13 00:00:00 6.3 66
USC00518838 2011-01-14 00:00:00 0.7 71
USC00518838 2011-01-19 00:00:00 0.03 67
USC00518838 2011-01-20 00:00:00 0.07 72
USC00518838 2011-01-21 00:00:00 0.0 70
USC00518838 2011-01-25 00:00:00 0.02 73
USC00518838 2011-01-26 00:00:00 0.08 70
USC00518838 2011-01-27 00:00:00 0.03 75
USC00518838 2011-01-28 00:00:00 0.04 73
USC00518838 2011-02-01 00:00:00 0.02 73
USC00518838 2011-02-02 00:00:00 0.0 75
USC00518838 2011-02-03 00:00:00 0.0 76
USC00518838 2011-02-04 00:00:00 0.02 72
USC00518838 2011-02-10 00:00:00 0.08 69
USC00518838 2011-02-11 00:00:00 1.0 69
USC00518838 2011-02-15 00:00:00 0.06 73
USC00518838 2011-02-16 00:00:00 0.01 76
USC00518838 2011-02-17 00:00:00 0.09 77
USC00518838 2011-02-18 00:00:00 0.01 72
USC00518838 2011-02-23 00:00:00 0.16 76
USC00518838 2011-02-24 00:00:00 0.03 72
USC00518838 2011-02-25 00:00:00 0.01 72
USC00518838 2011-03-01 00:00:00 0.02 74
USC00518838 2011-03-02 00:00:00 0.0 71
USC00518838 2011-03-03 00:00:00 0.89 74
USC00518838 2011-03-04 00:00:00 1.42 73
USC00518838 2011-03-08 00:00:00 0.11 73
USC00518838 2011-03-09 00:00:00 0.66 69
USC00518838 2011-03-10 00:00:00 0.36 71
USC00518838 2011-03-22 00:00:00 0.32 73
USC00518838 2011-03-23 00:00:00 0.34 74
USC00518838 2011-03-24 00:00:00 0.39 74
USC00518838 2011-03-30 00:00:00 0.03 73
USC00518838 2011-03-31 00:00:00 0.02 75
USC00518838 2011-04-01 00:00:00 0.34 74
USC00518838 2011-04-07 00:00:00 2.4 70
USC00518838 2011-04-08 00:00:00 0.57 68
USC00518838 2011-04-12 00:00:00 0.06 74
USC00518838 2011-04-13 00:00:00 0.01 77
USC00518838 2011-04-14 00:00:00 0.08 78
USC00518838 2011-04-15 00:00:00 0.11 71
USC00518838 2011-04-19 00:00:00 0.02 75
USC00518838 2011-04-20 00:00:00 0.03 74
USC00518838 2011-04-21 00:00:00 0.19 75
USC00518838 2011-04-25 00:00:00 0.0 75
USC00518838 2011-04-26 00:00:00 0.1 74
USC00518838 2011-04-27 00:00:00 0.2 72
USC00518838 2011-04-28 00:00:00 0.06 75
USC00518838 2011-04-29 00:00:00 0.02 74
USC00518838 2011-05-03 00:00:00 0.53 71
USC00518838 2011-05-04 00:00:00 2.1 71
USC00518838 2011-05-05 00:00:00 0.52 72
USC00518838 2011-05-06 00:00:00 0.04 73
USC00518838 2011-05-10 00:00:00 0.35 72
USC00518838 2011-05-11 00:00:00 0.1 73
USC00518838 2011-05-12 00:00:00 0.03 75
USC00518838 2011-05-16 00:00:00 0.0 75
USC00518838 2011-05-17 00:00:00 0.01 77
USC00518838 2011-05-18 00:00:00 0.01 76
USC00518838 2011-05-19 00:00:00 0.02 75
USC00518838 2011-05-20 00:00:00 0.0 75
USC00518838 2011-05-24 00:00:00 0.03 76
USC00518838 2011-05-25 00:00:00 0.0 74
USC00518838 2011-06-09 00:00:00 0.04 76
USC00518838 2011-06-13 00:00:00 0.08 76
USC00518838 2011-06-14 00:00:00 0.09 73
USC00518838 2011-06-15 00:00:00 0.06 76
USC00518838 2011-06-16 00:00:00 0.07 76
USC00518838 2011-06-21 00:00:00 0.05 75
USC00518838 2011-06-22 00:00:00 0.82 77
USC00518838 2011-07-06 00:00:00 0.05 72
USC00518838 2011-07-07 00:00:00 0.74 73
USC00518838 2011-08-24 00:00:00 0.0 72
USC00518838 2011-09-01 00:00:00 0.01 73
USC00518838 2011-09-02 00:00:00 0.08 77
USC00518838 2011-09-07 00:00:00 0.0 76
USC00518838 2011-09-09 00:00:00 0.0 73
USC00518838 2011-10-20 00:00:00 0.0 75
USC00518838 2011-11-04 00:00:00 0.6 72
USC00518838 2012-01-05 00:00:00 0.1 72
USC00518838 2012-01-09 00:00:00 0.0 74
USC00518838 2012-01-10 00:00:00 0.0 62
USC00518838 2012-01-11 00:00:00 0.01 73
USC00518838 2012-01-12 00:00:00 0.1 74
USC00518838 2012-01-14 00:00:00 0.0 58
USC00518838 2012-01-17 00:00:00 0.26 69
USC00518838 2012-01-18 00:00:00 1.26 73
USC00518838 2012-01-19 00:00:00 0.0 78
USC00518838 2012-01-20 00:00:00 0.0 78
USC00518838 2012-01-24 00:00:00 0.0 77
USC00518838 2012-01-25 00:00:00 0.0 74
USC00518838 2012-01-26 00:00:00 0.06 71
USC00518838 2012-01-27 00:00:00 1.03 72
USC00518838 2012-01-28 00:00:00 0.05 73
USC00518838 2012-01-29 00:00:00 0.05 71
USC00518838 2012-02-10 00:00:00 0.0 71
USC00518838 2012-02-15 00:00:00 0.0 74
USC00518838 2012-03-01 00:00:00 0.0 71
USC00518838 2012-03-03 00:00:00 0.22 65
USC00518838 2012-03-04 00:00:00 2.7 65
USC00518838 2012-03-05 00:00:00 0.92 62
USC00518838 2012-04-05 00:00:00 0.3 69
USC00518838 2012-05-18 00:00:00 0.3 76
USC00518838 2012-05-25 00:00:00 0.2 77
USC00518838 2012-05-28 00:00:00 0.15 74
USC00518838 2012-06-01 00:00:00 0.03 75
USC00518838 2012-07-20 00:00:00 0.05 72
USC00518838 2012-07-22 00:00:00 0.4 78
USC00518838 2012-07-23 00:00:00 0.03 79
USC00518838 2012-07-24 00:00:00 0.22 75
USC00518838 2012-07-25 00:00:00 0.2 77
USC00518838 2012-07-31 00:00:00 0.02 76
USC00518838 2012-08-01 00:00:00 0.0 79
USC00518838 2012-08-03 00:00:00 0.0 77
USC00518838 2012-08-06 00:00:00 0.26 78
USC00518838 2012-10-05 00:00:00 0.0 74
USC00518838 2012-10-11 00:00:00 0.08 78
USC00518838 2012-10-12 00:00:00 0.01 80
USC00518838 2012-10-16 00:00:00 0.11 77
USC00518838 2012-10-17 00:00:00 0.0 75
USC00518838 2012-10-18 00:00:00 0.02 76
USC00518838 2012-11-16 00:00:00 0.45 74
USC00518838 2012-11-27 00:00:00 0.0 71
USC00518838 2013-01-10 00:00:00 0.0 74
USC00518838 2013-01-24 00:00:00 0.3 67
USC00518838 2013-01-25 00:00:00 0.9 74
USC00518838 2013-02-07 00:00:00 0.0 72
USC00518838 2013-02-08 00:00:00 0.05 73
USC00518838 2013-02-15 00:00:00 0.0 70
USC00518838 2013-04-03 00:00:00 0.05 70
USC00518838 2013-04-05 00:00:00 0.0 73
USC00518838 2013-08-05 00:00:00 0.01 79
USC00518838 2013-08-06 00:00:00 0.02 80
USC00518838 2013-08-07 00:00:00 0.0 80
USC00518838 2013-08-08 00:00:00 0.0 72
USC00518838 2013-08-09 00:00:00 0.0 80
USC00518838 2013-08-19 00:00:00 0.0 78
USC00518838 2013-08-21 00:00:00 0.0 78
USC00518838 2013-08-22 00:00:00 0.01 74
USC00518838 2013-08-23 00:00:00 0.01 80
USC00518838 2013-08-27 00:00:00 0.0 79
USC00518838 2013-08-30 00:00:00 0.0 80
USC00518838 2013-09-06 00:00:00 0.01 78
USC00518838 2013-10-18 00:00:00 0.0 77
USC00518838 2013-12-20 00:00:00 0.16 73
USC00518838 2014-01-14 00:00:00 0.41 75
USC00518838 2014-02-03 00:00:00 0.0 64
USC00518838 2014-02-07 00:00:00 0.0 69
USC00518838 2014-02-12 00:00:00 0.0 72
USC00518838 2014-02-13 00:00:00 0.0 72
USC00518838 2014-02-16 00:00:00 0.1 68
USC00518838 2014-02-26 00:00:00 0.0 65
USC00518838 2015-05-19 00:00:00 0.0 75
USC00518838 2015-05-21 00:00:00 0.0 72
USC00518838 2015-05-26 00:00:00 0.0 70
USC00518838 2015-05-28 00:00:00 0.0 71
USC00518838 2015-09-21 00:00:00 0.0 76
USC00518838 2015-09-28 00:00:00 0.0 77
USC00518838 2015-09-29 00:00:00 0.0 73
USC00518838 2015-10-13 00:00:00 0.0 73
USC00518838 2015-10-16 00:00:00 0.0 79
USC00518838 2015-10-20 00:00:00 0.0 74
USC00519523 WAIMANALO EXPERIMENTAL FARM, HI US
USC00519523 2010-01-01 00:00:00 0.15 75
USC00519523 2010-01-02 00:00:00 0.0 75
USC00519523 2010-01-03 00:00:00 0.0 77
USC00519523 2010-01-04 00:00:00 0.0 75
USC00519523 2010-01-05 00:00:00 0.01 75
USC00519523 2010-01-06 00:00:00 0.11 72
USC00519523 2010-01-07 00:00:00 0.7 68
USC00519523 2010-01-08 00:00:00 0.02 63
USC00519523 2010-01-09 00:00:00 0.01 69
USC00519523 2010-01-10 00:00:00 0.0 72
USC00519523 2010-01-11 00:00:00 0.48 68
USC00519523 2010-01-12 00:00:00 0.0 61
USC00519523 2010-01-13 00:00:00 0.0 60
USC00519523 2010-01-14 00:00:00 0.0 65
USC00519523 2010-01-15 00:00:00 0.0 68
USC00519523 2010-01-16 00:00:00 0.0 68
USC00519523 2010-01-17 00:00:00 0.0 70
USC00519523 2010-01-18 00:00:00 0.0 77
USC00519523 2010-01-19 00:00:00 0.0 74
USC00519523 2010-01-20 00:00:00 0.0 67
USC00519523 2010-01-21 00:00:00 0.13 70
USC00519523 2010-01-22 00:00:00 0.0 66
USC00519523 2010-01-23 00:00:00 0.0 75
USC00519523 2010-01-24 00:00:00 0.0 72
USC00519523 2010-01-25 00:00:00 0.0 65
USC00519523 2010-01-26 00:00:00 0.01 76
USC00519523 2010-01-27 00:00:00 0.28 69
USC00519523 2010-01-28 00:00:00 0.09 71
USC00519523 2010-01-29 00:00:00 1.15 65
USC00519523 2010-01-30 00:00:00 2.75 69
USC00519523 2010-01-31 00:00:00 0.05 72
USC00519523 2010-02-01 00:00:00 0.0 68
USC00519523 2010-02-02 00:00:00 0.0 66
USC00519523 2010-02-03 00:00:00 0.44 65
USC00519523 2010-02-04 00:00:00 0.0 68
USC00519523 2010-02-05 00:00:00 0.04 65
USC00519523 2010-02-06 00:00:00 0.0 76
USC00519523 2010-02-07 00:00:00 0.0 63
USC00519523 2010-02-08 00:00:00 0.0 71
USC00519523 2010-02-09 00:00:00 0.0 70
USC00519523 2010-02-10 00:00:00 0.0 66
USC00519523 2010-02-11 00:00:00 0.0 71
USC00519523 2010-02-12 00:00:00 0.07 70
USC00519523 2010-02-13 00:00:00 0.0 71
USC00519523 2010-02-14 00:00:00 0.0 73
USC00519523 2010-02-15 00:00:00 0.0 73
USC00519523 2010-02-16 00:00:00 0.0 59
USC00519523 2010-02-17 00:00:00 0.01 68
USC00519523 2010-02-18 00:00:00 0.0 67
USC00519523 2010-02-19 00:00:00 0.2 63
USC00519523 2010-02-20 00:00:00 0.19 74
USC00519523 2010-02-21 00:00:00 0.16 66
USC00519523 2010-02-22 00:00:00 0.14 63
USC00519523 2010-02-23 00:00:00 0.03 63
USC00519523 2010-02-24 00:00:00 0.0 62
USC00519523 2010-02-25 00:00:00 0.0 69
USC00519523 2010-02-26 00:00:00 0.0 73
USC00519523 2010-02-27 00:00:00 0.01 73
USC00519523 2010-02-28 00:00:00 0.19 69
USC00519523 2010-03-01 00:00:00 0.01 69
USC00519523 2010-03-02 00:00:00 0.0 71
USC00519523 2010-03-03 00:00:00 0.0 71
USC00519523 2010-03-04 00:00:00 0.15 69
USC00519523 2010-03-05 00:00:00 0.12 70
USC00519523 2010-03-06 00:00:00 0.02 72
USC00519523 2010-03-07 00:00:00 0.0 72
USC00519523 2010-03-08 00:00:00 0.02 70
USC00519523 2010-03-09 00:00:00 0.0 69
USC00519523 2010-03-10 00:00:00 0.12 72
USC00519523 2010-03-11 00:00:00 0.04 72
USC00519523 2010-03-12 00:00:00 0.0 69
USC00519523 2010-03-13 00:00:00 0.0 76
USC00519523 2010-03-14 00:00:00 0.0 75
USC00519523 2010-03-15 00:00:00 0.13 71
USC00519523 2010-03-16 00:00:00 0.35 71
USC00519523 2010-03-17 00:00:00 0.05 69
USC00519523 2010-03-18 00:00:00 0.74 67
USC00519523 2010-03-19 00:00:00 0.03 68
USC00519523 2010-03-20 00:00:00 0.0 71
USC00519523 2010-03-21 00:00:00 0.0 70
USC00519523 2010-03-22 00:00:00 0.0 73
USC00519523 2010-03-23 00:00:00 0.0 67
USC00519523 2010-03-24 00:00:00 0.01 77
USC00519523 2010-03-25 00:00:00 0.12 73
USC00519523 2010-03-26 00:00:00 0.02 74

USC00519523 2010-03-27 00:00:00 0.02 77
USC00519523 2010-03-28 00:00:00 0.05 76
USC00519523 2010-03-29 00:00:00 0.0 73
USC00519523 2010-03-30 00:00:00 0.01 73
USC00519523 2010-03-31 00:00:00 0.0 73
USC00519523 2010-04-01 00:00:00 0.03 72
USC00519523 2010-04-02 00:00:00 0.0 72
USC00519523 2010-04-03 00:00:00 0.19 72
USC00519523 2010-04-04 00:00:00 0.12 72
USC00519523 2010-04-05 00:00:00 0.1 72
USC00519523 2010-04-06 00:00:00 0.03 73
USC00519523 2010-04-07 00:00:00 0.2 73
USC00519523 2010-04-08 00:00:00 0.0 73
USC00519523 2010-04-09 00:00:00 0.0 73
USC00519523 2010-04-10 00:00:00 0.0 76
USC00519523 2010-04-11 00:00:00 0.01 75
USC00519523 2010-04-12 00:00:00 0.0 71
USC00519523 2010-04-13 00:00:00 0.13 71
USC00519523 2010-04-14 00:00:00 0.02 69
USC00519523 2010-04-15 00:00:00 0.0 70
USC00519523 2010-04-16 00:00:00 0.02 64
USC00519523 2010-04-17 00:00:00 0.02 69
USC00519523 2010-04-18 00:00:00 0.0 70
USC00519523 2010-04-19 00:00:00 0.0 72
USC00519523 2010-04-20 00:00:00 0.12 72
USC00519523 2010-04-21 00:00:00 0.1 72
USC00519523 2010-04-22 00:00:00 0.04 73
USC00519523 2010-04-23 00:00:00 0.14 72
USC00519523 2010-04-24 00:00:00 0.02 74
USC00519523 2010-04-25 00:00:00 0.0 76
USC00519523 2010-04-26 00:00:00 0.0 73
USC00519523 2010-04-27 00:00:00 0.0 74
USC00519523 2010-04-28 00:00:00 0.03 74
USC00519523 2010-04-29 00:00:00 0.03 73
USC00519523 2010-04-30 00:00:00 0.0 74
USC00519523 2010-05-01 00:00:00 0.0 76
USC00519523 2010-05-02 00:00:00 0.12 71
USC00519523 2010-05-03 00:00:00 0.46 72
USC00519523 2010-05-04 00:00:00 0.07 77
USC00519523 2010-05-05 00:00:00 0.0 75
USC00519523 2010-05-06 00:00:00 0.0 74
USC00519523 2010-05-07 00:00:00 0.01 71
USC00519523 2010-05-08 00:00:00 0.05 76
USC00519523 2010-05-09 00:00:00 0.0 76
USC00519523 2010-05-10 00:00:00 0.0 78
USC00519523 2010-05-11 00:00:00 0.0 78
USC00519523 2010-05-12 00:00:00 0.08 78
USC00519523 2010-05-14 00:00:00 0.0 75
USC00519523 2010-05-15 00:00:00 0.05 71
USC00519523 2010-05-16 00:00:00 0.06 73
USC00519523 2010-05-17 00:00:00 0.03 74
USC00519523 2010-05-18 00:00:00 0.0 75
USC00519523 2010-05-19 00:00:00 0.0 78
USC00519523 2010-05-20 00:00:00 0.01 75
USC00519523 2010-05-21 00:00:00 0.0 74
USC00519523 2010-05-22 00:00:00 0.0 75
USC00519523 2010-05-23 00:00:00 0.05 75
USC00519523 2010-05-24 00:00:00 0.06 75
USC00519523 2010-05-25 00:00:00 0.0 76
USC00519523 2010-05-26 00:00:00 0.08 78
USC00519523 2010-05-27 00:00:00 0.0 80
USC00519523 2010-05-29 00:00:00 0.0 78
USC00519523 2010-05-30 00:00:00 0.0 76
USC00519523 2010-05-31 00:00:00 0.0 81
USC00519523 2010-06-01 00:00:00 0.03 76
USC00519523 2010-06-02 00:00:00 0.0 76
USC00519523 2010-06-03 00:00:00 0.0 76
USC00519523 2010-06-04 00:00:00 0.0 73
USC00519523 2010-06-05 00:00:00 0.0 78
USC00519523 2010-06-06 00:00:00 0.0 77
USC00519523 2010-06-07 00:00:00 0.0 77
USC00519523 2010-06-08 00:00:00 0.01 77
USC00519523 2010-06-09 00:00:00 0.0 78
USC00519523 2010-06-10 00:00:00 0.0 78
USC00519523 2010-06-11 00:00:00 0.0 76
USC00519523 2010-06-12 00:00:00 0.0 76
USC00519523 2010-06-13 00:00:00 0.0 79
USC00519523 2010-06-14 00:00:00 0.0 74
USC00519523 2010-06-15 00:00:00 0.0 75
USC00519523 2010-06-16 00:00:00 0.0 76
USC00519523 2010-06-17 00:00:00 0.0 75
USC00519523 2010-06-18 00:00:00 0.14 73
USC00519523 2010-06-19 00:00:00 0.0 76
USC00519523 2010-06-20 00:00:00 0.0 78
USC00519523 2010-06-21 00:00:00 0.0 76
USC00519523 2010-06-22 00:00:00 0.0 79
USC00519523 2010-06-23 00:00:00 0.0 77
USC00519523 2010-06-24 00:00:00 0.0 76
USC00519523 2010-06-25 00:00:00 0.08 74
USC00519523 2010-06-26 00:00:00 0.08 75
USC00519523 2010-06-28 00:00:00 0.0 76
USC00519523 2010-06-29 00:00:00 0.0 76
USC00519523 2010-06-30 00:00:00 0.0 76
USC00519523 2010-07-01 00:00:00 0.13 74
USC00519523 2010-07-02 00:00:00 0.14 74
USC00519523 2010-07-03 00:00:00 0.09 76
USC00519523 2010-07-04 00:00:00 0.05 79
USC00519523 2010-07-05 00:00:00 0.01 79
USC00519523 2010-07-06 00:00:00 0.08 73
USC00519523 2010-07-07 00:00:00 0.21 73
USC00519523 2010-07-08 00:00:00 0.02 76
USC00519523 2010-07-09 00:00:00 0.06 72
USC00519523 2010-07-10 00:00:00 0.1 76
USC00519523 2010-07-11 00:00:00 0.0 81
USC00519523 2010-07-12 00:00:00 0.0 75
USC00519523 2010-07-13 00:00:00 0.0 76
USC00519523 2010-07-14 00:00:00 0.04 74
USC00519523 2010-07-15 00:00:00 0.03 76
USC00519523 2010-07-16 00:00:00 0.03 80
USC00519523 2010-07-17 00:00:00 0.08 74
USC00519523 2010-07-18 00:00:00 0.07 77
USC00519523 2010-07-19 00:00:00 0.0 76
USC00519523 2010-07-20 00:00:00 0.0 77
USC00519523 2010-07-21 00:00:00 0.06 74
USC00519523 2010-07-22 00:00:00 0.0 76
USC00519523 2010-07-23 00:00:00 0.0 73
USC00519523 2010-07-24 00:00:00 0.0 77
USC00519523 2010-07-25 00:00:00 0.0 77
USC00519523 2010-07-26 00:00:00 0.0 76
USC00519523 2010-07-27 00:00:00 0.0 81
USC00519523 2010-07-28 00:00:00 0.0 76
USC00519523 2010-07-29 00:00:00 0.0 77
USC00519523 2010-07-30 00:00:00 0.0 73
USC00519523 2010-07-31 00:00:00 0.09 76
USC00519523 2010-08-01 00:00:00 0.16 77
USC00519523 2010-08-02 00:00:00 0.19 74
USC00519523 2010-08-03 00:00:00 0.08 74
USC00519523 2010-08-04 00:00:00 0.26 76
USC00519523 2010-08-05 00:00:00 0.09 73
USC00519523 2010-08-06 00:00:00 0.09 76
USC00519523 2010-08-07 00:00:00 0.01 78
USC00519523 2010-08-08 00:00:00 0.0 76
USC00519523 2010-08-09 00:00:00 0.0 77
USC00519523 2010-08-10 00:00:00 0.0 77
USC00519523 2010-08-11 00:00:00 0.06 74
USC00519523 2010-08-12 00:00:00 0.0 75
USC00519523 2010-08-13 00:00:00 0.04 79
USC00519523 2010-08-14 00:00:00 0.0 78
USC00519523 2010-08-15 00:00:00 0.02 76
USC00519523 2010-08-16 00:00:00 0.08 72
USC00519523 2010-08-17 00:00:00 0.0 74
USC00519523 2010-08-18 00:00:00 0.02 77
USC00519523 2010-08-19 00:00:00 0.04 77
USC00519523 2010-08-20 00:00:00 0.02 77
USC00519523 2010-08-21 00:00:00 0.01 79
USC00519523 2010-08-22 00:00:00 0.01 78
USC00519523 2010-08-23 00:00:00 0.0 77
USC00519523 2010-08-24 00:00:00 0.0 76
USC00519523 2010-08-25 00:00:00 0.06 76
USC00519523 2010-08-26 00:00:00 0.06 77
USC00519523 2010-08-27 00:00:00 0.01 77
USC00519523 2010-08-28 00:00:00 0.0 82
USC00519523 2010-08-29 00:00:00 0.05 77
USC00519523 2010-08-30 00:00:00 0.0 76
USC00519523 2010-08-31 00:00:00 0.02 76
USC00519523 2010-09-01 00:00:00 0.0 76
USC00519523 2010-09-02 00:00:00 0.14 73
USC00519523 2010-09-03 00:00:00 0.27 76
USC00519523 2010-09-04 00:00:00 0.02 80
USC00519523 2010-09-05 00:00:00 0.01 78
USC00519523 2010-09-06 00:00:00 0.02 78
USC00519523 2010-09-07 00:00:00 0.23 75
USC00519523 2010-09-08 00:00:00 0.07 77
USC00519523 2010-09-09 00:00:00 0.02 77
USC00519523 2010-09-10 00:00:00 0.17 75
USC00519523 2010-09-11 00:00:00 0.18 81
USC00519523 2010-09-12 00:00:00 0.01 78
USC00519523 2010-09-13 00:00:00 0.0 77
USC00519523 2010-09-14 00:00:00 0.0 76
USC00519523 2010-09-15 00:00:00 0.0 76
USC00519523 2010-09-16 00:00:00 0.0 77
USC00519523 2010-09-17 00:00:00 0.0 77
USC00519523 2010-09-18 00:00:00 0.01 77
USC00519523 2010-09-19 00:00:00 0.07 76
USC00519523 2010-09-20 00:00:00 0.06 76
USC00519523 2010-09-21 00:00:00 0.04 76
USC00519523 2010-09-22 00:00:00 0.22 74
USC00519523 2010-09-23 00:00:00 0.18 76
USC00519523 2010-09-24 00:00:00 0.06 75
USC00519523 2010-09-25 00:00:00 0.05 76
USC00519523 2010-09-26 00:00:00 0.0 77
USC00519523 2010-09-27 00:00:00 0.0 75
USC00519523 2010-09-28 00:00:00 0.0 73
USC00519523 2010-09-29 00:00:00 0.0 71
USC00519523 2010-09-30 00:00:00 0.24 72
USC00519523 2010-10-01 00:00:00 0.43 76
USC00519523 2010-10-02 00:00:00 0.05 80
USC00519523 2010-10-03 00:00:00 0.01 78
USC00519523 2010-10-04 00:00:00 0.0 77
USC00519523 2010-10-05 00:00:00 0.0 77
USC00519523 2010-10-06 00:00:00 0.0 77
USC00519523 2010-10-07 00:00:00 0.0 77
USC00519523 2010-10-08 00:00:00 0.0 81
USC00519523 2010-10-09 00:00:00 0.0 77
USC00519523 2010-10-10 00:00:00 0.01 80
USC00519523 2010-10-11 00:00:00 0.01 76
USC00519523 2010-10-12 00:00:00 0.13 72
USC00519523 2010-10-13 00:00:00 0.0 76
USC00519523 2010-10-14 00:00:00 0.0 76
USC00519523 2010-10-15 00:00:00 0.0 76
USC00519523 2010-10-16 00:00:00 0.0 77
USC00519523 2010-10-17 00:00:00 0.06 76
USC00519523 2010-10-18 00:00:00 0.0 72
USC00519523 2010-10-19 00:00:00 0.0 73
USC00519523 2010-10-20 00:00:00 0.0 74
USC00519523 2010-10-21 00:00:00 0.0 77
USC00519523 2010-10-22 00:00:00 0.0 76
USC00519523 2010-10-23 00:00:00 0.0 77
USC00519523 2010-10-24 00:00:00 0.0 80
USC00519523 2010-10-25 00:00:00 0.0 76
USC00519523 2010-10-26 00:00:00 0.11 75
USC00519523 2010-10-27 00:00:00 0.09 76
USC00519523 2010-10-28 00:00:00 0.02 77
USC00519523 2010-10-29 00:00:00 0.03 75
USC00519523 2010-10-30 00:00:00 0.26 81
USC00519523 2010-10-31 00:00:00 0.0 77
USC00519523 2010-11-01 00:00:00 0.24 74
USC00519523 2010-11-02 00:00:00 0.0 75
USC00519523 2010-11-03 00:00:00 0.42 70
USC00519523 2010-11-04 00:00:00 1.34 72
USC00519523 2010-11-05 00:00:00 0.03 74
USC00519523 2010-11-06 00:00:00 0.16 74
USC00519523 2010-11-07 00:00:00 0.01 76
USC00519523 2010-11-08 00:00:00 0.0 76
USC00519523 2010-11-09 00:00:00 0.0 73
USC00519523 2010-11-10 00:00:00 0.0 75
USC00519523 2010-11-11 00:00:00 0.0 75
USC00519523 2010-11-12 00:00:00 0.0 76
USC00519523 2010-11-13 00:00:00 0.0 76
USC00519523 2010-11-14 00:00:00 0.0 76
USC00519523 2010-11-15 00:00:00 0.03 75
USC00519523 2010-11-16 00:00:00 0.0 75
USC00519523 2010-11-17 00:00:00 0.0 66
USC00519523 2010-11-18 00:00:00 0.0 74
USC00519523 2010-11-19 00:00:00 0.13 68
USC00519523 2010-11-20 00:00:00 0.0 79
USC00519523 2010-11-21 00:00:00 0.05 77
USC00519523 2010-11-22 00:00:00 0.0 67
USC00519523 2010-11-23 00:00:00 0.0 69
USC00519523 2010-11-24 00:00:00 0.0 76
USC00519523 2010-11-25 00:00:00 0.02 76
USC00519523 2010-11-26 00:00:00 0.0 77
USC00519523 2010-11-27 00:00:00 0.01 76
USC00519523 2010-11-28 00:00:00 0.64 76
USC00519523 2010-11-29 00:00:00 0.03 73
USC00519523 2010-11-30 00:00:00 0.0 76
USC00519523 2010-12-01 00:00:00 0.03 78
USC00519523 2010-12-02 00:00:00 0.02 74
USC00519523 2010-12-03 00:00:00 0.01 74
USC00519523 2010-12-04 00:00:00 0.0 78
USC00519523 2010-12-05 00:00:00 0.0 78
USC00519523 2010-12-06 00:00:00 0.0 61
USC00519523 2010-12-07 00:00:00 0.0 69
USC00519523 2010-12-08 00:00:00 0.15 65
USC00519523 2010-12-09 00:00:00 0.03 77
USC00519523 2010-12-10 00:00:00 2.02 67
USC00519523 2010-12-11 00:00:00 0.3 69
USC00519523 2010-12-12 00:00:00 0.09 75
USC00519523 2010-12-13 00:00:00 0.02 67
USC00519523 2010-12-14 00:00:00 0.04 71
USC00519523 2010-12-15 00:00:00 0.0 74
USC00519523 2010-12-16 00:00:00 0.0 66
USC00519523 2010-12-17 00:00:00 0.0 66
USC00519523 2010-12-18 00:00:00 0.0 77
USC00519523 2010-12-19 00:00:00 2.86 70
USC00519523 2010-12-20 00:00:00 4.95 73
USC00519523 2010-12-21 00:00:00 0.63 71
USC00519523 2010-12-22 00:00:00 0.58 71
USC00519523 2010-12-23 00:00:00 0.11 71
USC00519523 2010-12-24 00:00:00 0.02 67
USC00519523 2010-12-25 00:00:00 0.02 71
USC00519523 2010-12-26 00:00:00 0.74 74
USC00519523 2010-12-27 00:00:00 0.09 76
USC00519523 2010-12-28 00:00:00 0.07 72
USC00519523 2010-12-29 00:00:00 0.04 74
USC00519523 2010-12-30 00:00:00 0.27 75
USC00519523 2010-12-31 00:00:00 0.01 69
USC00519523 2011-01-01 00:00:00 0.03 69
USC00519523 2011-01-02 00:00:00 0.0 74
USC00519523 2011-01-03 00:00:00 0.0 74
USC00519523 2011-01-04 00:00:00 0.0 73
USC00519523 2011-01-05 00:00:00 0.0 62
USC00519523 2011-01-06 00:00:00 0.15 68
USC00519523 2011-01-07 00:00:00 0.02 66
USC00519523 2011-01-08 00:00:00 0.0 73
USC00519523 2011-01-09 00:00:00 0.0 73
USC00519523 2011-01-10 00:00:00 0.0 73
USC00519523 2011-01-11 00:00:00 0.43 58
USC00519523 2011-01-12 00:00:00 1.34 71
USC00519523 2011-01-13 00:00:00 3.62 70
USC00519523 2011-01-14 00:00:00 0.1 76
USC00519523 2011-01-15 00:00:00 0.0 66
USC00519523 2011-01-16 00:00:00 0.0 70
USC00519523 2011-01-17 00:00:00 0.19 70
USC00519523 2011-01-18 00:00:00 0.0 63
USC00519523 2011-01-19 00:00:00 0.07 63
USC00519523 2011-01-20 00:00:00 0.0 70
USC00519523 2011-01-21 00:00:00 0.0 74
USC00519523 2011-01-22 00:00:00 0.0 75
USC00519523 2011-01-23 00:00:00 0.0 76
USC00519523 2011-01-24 00:00:00 0.0 72
USC00519523 2011-01-25 00:00:00 0.0 62
USC00519523 2011-01-26 00:00:00 0.0 65
USC00519523 2011-01-27 00:00:00 0.0 71
USC00519523 2011-01-28 00:00:00 0.0 72
USC00519523 2011-01-29 00:00:00 0.01 76
USC00519523 2011-01-30 00:00:00 0.0 67
USC00519523 2011-01-31 00:00:00 0.15 66
USC00519523 2011-02-01 00:00:00 0.0 70
USC00519523 2011-02-02 00:00:00 0.0 70
USC00519523 2011-02-03 00:00:00 0.0 66
USC00519523 2011-02-04 00:00:00 0.0 61
USC00519523 2011-02-05 00:00:00 0.0 73
USC00519523 2011-02-06 00:00:00 0.0 75
USC00519523 2011-02-07 00:00:00 0.95 67
USC00519523 2011-02-08 00:00:00 0.18 71
USC00519523 2011-02-09 00:00:00 0.0 74
USC00519523 2011-02-10 00:00:00 0.04 69
USC00519523 2011-02-11 00:00:00 0.29 68
USC00519523 2011-02-12 00:00:00 1.82 72
USC00519523 2011-02-13 00:00:00 0.71 76
USC00519523 2011-02-15 00:00:00 0.0 73
USC00519523 2011-02-16 00:00:00 0.0 73
USC00519523 2011-02-17 00:00:00 0.0 72
USC00519523 2011-02-18 00:00:00 0.01 76
USC00519523 2011-02-19 00:00:00 0.0 76
USC00519523 2011-02-20 00:00:00 0.3 73
USC00519523 2011-02-21 00:00:00 0.02 76
USC00519523 2011-02-22 00:00:00 0.01 73
USC00519523 2011-02-23 00:00:00 0.01 73
USC00519523 2011-02-24 00:00:00 1.44 68
USC00519523 2011-02-25 00:00:00 0.0 66
USC00519523 2011-02-26 00:00:00 0.05 77
USC00519523 2011-02-27 00:00:00 0.0 75
USC00519523 2011-02-28 00:00:00 0.02 70
USC00519523 2011-03-01 00:00:00 0.18 67
USC00519523 2011-03-02 00:00:00 0.01 72
USC00519523 2011-03-03 00:00:00 0.06 71
USC00519523 2011-03-04 00:00:00 1.7 72
USC00519523 2011-03-05 00:00:00 0.22 69
USC00519523 2011-03-06 00:00:00 0.27 74
USC00519523 2011-03-07 00:00:00 0.03 73
USC00519523 2011-03-08 00:00:00 0.01 73
USC00519523 2011-03-09 00:00:00 0.9 70
USC00519523 2011-03-10 00:00:00 0.27 72
USC00519523 2011-03-11 00:00:00 0.2 71
USC00519523 2011-03-12 00:00:00 0.01 75
USC00519523 2011-03-13 00:00:00 0.0 77
USC00519523 2011-03-14 00:00:00 0.0 70
USC00519523 2011-03-15 00:00:00 0.0 73
USC00519523 2011-03-16 00:00:00 0.0 74
USC00519523 2011-03-17 00:00:00 0.07 73
USC00519523 2011-03-18 00:00:00 0.05 72
USC00519523 2011-03-19 00:00:00 0.08 73
USC00519523 2011-03-20 00:00:00 0.23 74
USC00519523 2011-03-21 00:00:00 0.0 74
USC00519523 2011-03-22 00:00:00 0.17 73
USC00519523 2011-03-23 00:00:00 0.0 74
USC00519523 2011-03-24 00:00:00 0.19 76
USC00519523 2011-03-25 00:00:00 0.02 76
USC00519523 2011-03-26 00:00:00 0.0 74
USC00519523 2011-03-27 00:00:00 0.0 74
USC00519523 2011-03-29 00:00:00 0.0 73
USC00519523 2011-03-30 00:00:00 0.0 73
USC00519523 2011-03-31 00:00:00 0.0 73
USC00519523 2011-04-01 00:00:00 0.07 73
USC00519523 2011-04-02 00:00:00 0.0 79
USC00519523 2011-04-03 00:00:00 0.0 78
USC00519523 2011-04-04 00:00:00 0.0 73
USC00519523 2011-04-05 00:00:00 0.0 73
USC00519523 2011-04-06 00:00:00 0.11 72
USC00519523 2011-04-07 00:00:00 0.5 67
USC00519523 2011-04-08 00:00:00 0.68 69
USC00519523 2011-04-09 00:00:00 0.02 76
USC00519523 2011-04-10 00:00:00 0.01 75

USC00519523 2011-04-11 00:00:00 0.0 74
USC00519523 2011-04-12 00:00:00 0.0 74
USC00519523 2011-04-13 00:00:00 0.0 69
USC00519523 2011-04-14 00:00:00 0.2 75
USC00519523 2011-04-15 00:00:00 0.0 73
USC00519523 2011-04-16 00:00:00 0.22 75
USC00519523 2011-04-17 00:00:00 0.0 73
USC00519523 2011-04-18 00:00:00 0.0 73
USC00519523 2011-04-19 00:00:00 0.0 74
USC00519523 2011-04-20 00:00:00 0.0 71
USC00519523 2011-04-21 00:00:00 0.0 74
USC00519523 2011-04-22 00:00:00 0.0 76
USC00519523 2011-04-23 00:00:00 0.0 79
USC00519523 2011-04-24 00:00:00 0.0 79
USC00519523 2011-04-25 00:00:00 0.0 75
USC00519523 2011-04-26 00:00:00 0.0 77
USC00519523 2011-04-27 00:00:00 0.0 78
USC00519523 2011-04-28 00:00:00 0.0 79
USC00519523 2011-04-29 00:00:00 0.07 75
USC00519523 2011-04-30 00:00:00 0.0 75
USC00519523 2011-05-01 00:00:00 0.0 75
USC00519523 2011-05-02 00:00:00 0.0 79
USC00519523 2011-05-03 00:00:00 1.03 73
USC00519523 2011-05-04 00:00:00 0.06 75
USC00519523 2011-05-05 00:00:00 0.0 74
USC00519523 2011-05-06 00:00:00 0.19 72
USC00519523 2011-05-07 00:00:00 0.2 74
USC00519523 2011-05-08 00:00:00 0.51 75
USC00519523 2011-05-09 00:00:00 0.1 75
USC00519523 2011-05-10 00:00:00 0.05 73
USC00519523 2011-05-11 00:00:00 0.15 71
USC00519523 2011-05-12 00:00:00 0.01 77
USC00519523 2011-05-13 00:00:00 0.01 75
USC00519523 2011-05-14 00:00:00 0.0 78
USC00519523 2011-05-15 00:00:00 0.0 75
USC00519523 2011-05-16 00:00:00 0.0 76
USC00519523 2011-05-17 00:00:00 0.0 76
USC00519523 2011-05-18 00:00:00 0.0 73
USC00519523 2011-05-19 00:00:00 0.01 78
USC00519523 2011-05-20 00:00:00 0.0 76
USC00519523 2011-05-21 00:00:00 0.0 79
USC00519523 2011-05-22 00:00:00 0.02 76
USC00519523 2011-05-23 00:00:00 0.0 76
USC00519523 2011-05-24 00:00:00 0.0 76
USC00519523 2011-05-25 00:00:00 0.0 75
USC00519523 2011-05-26 00:00:00 0.0 75
USC00519523 2011-05-27 00:00:00 0.1 76
USC00519523 2011-05-28 00:00:00 0.01 75
USC00519523 2011-05-29 00:00:00 0.03 75
USC00519523 2011-05-30 00:00:00 0.01 76
USC00519523 2011-05-31 00:00:00 0.08 76
USC00519523 2011-06-01 00:00:00 0.15 79
USC00519523 2011-06-02 00:00:00 0.01 76
USC00519523 2011-06-03 00:00:00 0.09 72
USC00519523 2011-06-04 00:00:00 0.51 71
USC00519523 2011-06-05 00:00:00 0.25 72
USC00519523 2011-06-06 00:00:00 0.03 76
USC00519523 2011-06-07 00:00:00 0.03 74
USC00519523 2011-06-08 00:00:00 0.0 75
USC00519523 2011-06-09 00:00:00 0.0 76
USC00519523 2011-06-10 00:00:00 0.0 77
USC00519523 2011-06-11 00:00:00 0.0 76
USC00519523 2011-06-12 00:00:00 0.09 75
USC00519523 2011-06-13 00:00:00 0.0 76
USC00519523 2011-06-14 00:00:00 0.0 76
USC00519523 2011-06-15 00:00:00 0.0 76
USC00519523 2011-06-16 00:00:00 0.09 75
USC00519523 2011-06-17 00:00:00 0.0 76
USC00519523 2011-06-18 00:00:00 0.0 76
USC00519523 2011-06-19 00:00:00 0.17 79
USC00519523 2011-06-20 00:00:00 0.14 74
USC00519523 2011-06-21 00:00:00 0.38 73
USC00519523 2011-06-22 00:00:00 0.17 75
USC00519523 2011-06-23 00:00:00 0.05 74
USC00519523 2011-06-24 00:00:00 0.03 75
USC00519523 2011-06-25 00:00:00 0.0 76
USC00519523 2011-06-26 00:00:00 0.12 72
USC00519523 2011-06-27 00:00:00 0.02 74
USC00519523 2011-06-28 00:00:00 0.02 74
USC00519523 2011-06-29 00:00:00 0.0 75
USC00519523 2011-06-30 00:00:00 0.0 75
USC00519523 2011-07-01 00:00:00 0.01 81
USC00519523 2011-07-02 00:00:00 0.01 76
USC00519523 2011-07-03 00:00:00 0.12 76
USC00519523 2011-07-04 00:00:00 0.06 76
USC00519523 2011-07-05 00:00:00 0.04 75
USC00519523 2011-07-06 00:00:00 0.08 79
USC00519523 2011-07-07 00:00:00 0.06 73
USC00519523 2011-07-08 00:00:00 0.04 75
USC00519523 2011-07-09 00:00:00 0.01 79
USC00519523 2011-07-10 00:00:00 0.01 77
USC00519523 2011-07-11 00:00:00 0.01 76
USC00519523 2011-07-12 00:00:00 0.0 76
USC00519523 2011-07-13 00:00:00 0.0 74
USC00519523 2011-07-14 00:00:00 0.0 76
USC00519523 2011-07-15 00:00:00 0.0 76
USC00519523 2011-07-16 00:00:00 0.0 77
USC00519523 2011-07-17 00:00:00 0.06 78
USC00519523 2011-07-18 00:00:00 0.0 75
USC00519523 2011-07-19 00:00:00 0.0 75
USC00519523 2011-07-20 00:00:00 0.16 71
USC00519523 2011-07-21 00:00:00 0.0 77
USC00519523 2011-07-22 00:00:00 0.09 75
USC00519523 2011-07-23 00:00:00 0.08 77
USC00519523 2011-07-24 00:00:00 0.0 74
USC00519523 2011-07-25 00:00:00 0.12 76
USC00519523 2011-07-26 00:00:00 0.0 76
USC00519523 2011-07-27 00:00:00 0.06 75
USC00519523 2011-07-28 00:00:00 0.04 76
USC00519523 2011-07-29 00:00:00 0.02 77
USC00519523 2011-07-30 00:00:00 0.2 76
USC00519523 2011-07-31 00:00:00 0.01 78
USC00519523 2011-08-01 00:00:00 0.0 76
USC00519523 2011-08-02 00:00:00 0.0 76
USC00519523 2011-08-03 00:00:00 0.0 77
USC00519523 2011-08-04 00:00:00 0.0 77
USC00519523 2011-08-05 00:00:00 0.0 77
USC00519523 2011-08-06 00:00:00 0.0 76
USC00519523 2011-08-07 00:00:00 0.12 77
USC00519523 2011-08-08 00:00:00 0.0 76
USC00519523 2011-08-09 00:00:00 0.19 78
USC00519523 2011-08-10 00:00:00 0.0 76
USC00519523 2011-08-11 00:00:00 0.0 76
USC00519523 2011-08-12 00:00:00 0.0 76
USC00519523 2011-08-13 00:00:00 0.0 77
USC00519523 2011-08-14 00:00:00 0.0 80
USC00519523 2011-08-15 00:00:00 0.5 76
USC00519523 2011-08-16 00:00:00 0.01 76
USC00519523 2011-08-17 00:00:00 0.0 76
USC00519523 2011-08-18 00:00:00 0.05 75
USC00519523 2011-08-19 00:00:00 0.02 83
USC00519523 2011-08-20 00:00:00 0.0 82
USC00519523 2011-08-21 00:00:00 0.02 78
USC00519523 2011-08-22 00:00:00 0.0 76
USC00519523 2011-08-23 00:00:00 0.22 75
USC00519523 2011-08-24 00:00:00 0.0 77
USC00519523 2011-08-25 00:00:00 0.08 75
USC00519523 2011-08-26 00:00:00 0.0 77
USC00519523 2011-08-27 00:00:00 0.0 81
USC00519523 2011-08-28 00:00:00 0.0 79
USC00519523 2011-08-29 00:00:00 0.15 76
USC00519523 2011-08-30 00:00:00 0.13 76
USC00519523 2011-08-31 00:00:00 0.01 76
USC00519523 2011-09-01 00:00:00 0.09 77
USC00519523 2011-09-02 00:00:00 0.03 77
USC00519523 2011-09-03 00:00:00 0.0 78
USC00519523 2011-09-04 00:00:00 0.0 81
USC00519523 2011-09-05 00:00:00 0.0 78
USC00519523 2011-09-07 00:00:00 0.0 70
USC00519523 2011-09-08 00:00:00 0.0 72
USC00519523 2011-09-09 00:00:00 0.0 78
USC00519523 2011-09-10 00:00:00 0.0 79
USC00519523 2011-09-11 00:00:00 0.0 75
USC00519523 2011-09-12 00:00:00 0.0 77
USC00519523 2011-09-13 00:00:00 0.09 73
USC00519523 2011-09-14 00:00:00 0.0 75
USC00519523 2011-09-15 00:00:00 0.0 78
USC00519523 2011-09-16 00:00:00 0.17 80
USC00519523 2011-09-17 00:00:00 0.0 76
USC00519523 2011-09-18 00:00:00 0.2 77
USC00519523 2011-09-19 00:00:00 0.03 77
USC00519523 2011-09-20 00:00:00 0.0 77
USC00519523 2011-09-21 00:00:00 0.04 76
USC00519523 2011-09-22 00:00:00 0.03 77
USC00519523 2011-09-23 00:00:00 0.0 75
USC00519523 2011-09-24 00:00:00 0.0 78
USC00519523 2011-09-25 00:00:00 0.0 81
USC00519523 2011-09-26 00:00:00 0.0 69
USC00519523 2011-09-27 00:00:00 0.0 76
USC00519523 2011-09-28 00:00:00 0.04 75
USC00519523 2011-09-29 00:00:00 0.0 77
USC00519523 2011-09-30 00:00:00 0.0 82
USC00519523 2011-10-01 00:00:00 0.0 77
USC00519523 2011-10-02 00:00:00 0.0 80
USC00519523 2011-10-03 00:00:00 0.0 84
USC00519523 2011-10-04 00:00:00 0.13 75
USC00519523 2011-10-05 00:00:00 0.0 76
USC00519523 2011-10-06 00:00:00 0.0 75
USC00519523 2011-10-07 00:00:00 0.02 72
USC00519523 2011-10-08 00:00:00 0.0 82
USC00519523 2011-10-09 00:00:00 0.14 77
USC00519523 2011-10-10 00:00:00 0.0 75
USC00519523 2011-10-11 00:00:00 0.14 76
USC00519523 2011-10-12 00:00:00 0.0 80
USC00519523 2011-10-13 00:00:00 0.0 80
USC00519523 2011-10-14 00:00:00 0.07 79
USC00519523 2011-10-15 00:00:00 0.26 79
USC00519523 2011-10-16 00:00:00 0.0 79
USC00519523 2011-10-17 00:00:00 0.2 70
USC00519523 2011-10-18 00:00:00 0.12 72
USC00519523 2011-10-19 00:00:00 0.01 68
USC00519523 2011-10-20 00:00:00 0.0 78
USC00519523 2011-10-21 00:00:00 0.01 77
USC00519523 2011-10-22 00:00:00 0.0 76
USC00519523 2011-10-23 00:00:00 0.0 77
USC00519523 2011-10-24 00:00:00 0.29 73
USC00519523 2011-10-25 00:00:00 0.0 77
USC00519523 2011-10-26 00:00:00 0.0 79
USC00519523 2011-10-27 00:00:00 0.0 73
USC00519523 2011-10-28 00:00:00 0.1 76
USC00519523 2011-10-29 00:00:00 0.05 80
USC00519523 2011-10-30 00:00:00 0.03 72
USC00519523 2011-10-31 00:00:00 0.0 75
USC00519523 2011-11-01 00:00:00 0.54 74
USC00519523 2011-11-02 00:00:00 0.03 73
USC00519523 2011-11-03 00:00:00 0.02 78
USC00519523 2011-11-04 00:00:00 0.05 73
USC00519523 2011-11-05 00:00:00 0.0 78
USC00519523 2011-11-06 00:00:00 0.0 81
USC00519523 2011-11-07 00:00:00 0.0 75
USC00519523 2011-11-08 00:00:00 0.01 74
USC00519523 2011-11-09 00:00:00 0.05 74
USC00519523 2011-11-10 00:00:00 0.0 75
USC00519523 2011-11-11 00:00:00 0.12 75
USC00519523 2011-11-12 00:00:00 0.0 77
USC00519523 2011-11-13 00:00:00 0.0 79
USC00519523 2011-11-14 00:00:00 0.0 78
USC00519523 2011-11-15 00:00:00 0.0 77
USC00519523 2011-11-16 00:00:00 0.0 78
USC00519523 2011-11-17 00:00:00 0.05 75
USC00519523 2011-11-18 00:00:00 0.0 76
USC00519523 2011-11-19 00:00:00 0.01 74
USC00519523 2011-11-20 00:00:00 0.02 75
USC00519523 2011-11-21 00:00:00 0.0 76
USC00519523 2011-11-22 00:00:00 0.1 72
USC00519523 2011-11-23 00:00:00 0.01 72
USC00519523 2011-11-24 00:00:00 0.0 72
USC00519523 2011-11-25 00:00:00 0.0 73
USC00519523 2011-11-26 00:00:00 0.0 77
USC00519523 2011-11-27 00:00:00 0.0 75
USC00519523 2011-11-28 00:00:00 0.0 71
USC00519523 2011-11-29 00:00:00 0.0 69
USC00519523 2011-11-30 00:00:00 0.22 66
USC00519523 2011-12-01 00:00:00 0.12 69
USC00519523 2011-12-02 00:00:00 0.42 69
USC00519523 2011-12-03 00:00:00 0.02 75
USC00519523 2011-12-04 00:00:00 0.0 73
USC00519523 2011-12-05 00:00:00 0.0 73
USC00519523 2011-12-06 00:00:00 0.01 72
USC00519523 2011-12-07 00:00:00 0.0 72
USC00519523 2011-12-08 00:00:00 0.0 72
USC00519523 2011-12-09 00:00:00 0.08 74
USC00519523 2011-12-10 00:00:00 0.07 72
USC00519523 2011-12-11 00:00:00 0.55 73
USC00519523 2011-12-12 00:00:00 0.21 73
USC00519523 2011-12-13 00:00:00 0.39 73
USC00519523 2011-12-14 00:00:00 0.02 73
USC00519523 2011-12-15 00:00:00 0.09 74
USC00519523 2011-12-16 00:00:00 0.02 73
USC00519523 2011-12-17 00:00:00 0.25 71
USC00519523 2011-12-18 00:00:00 0.08 72
USC00519523 2011-12-19 00:00:00 0.1 73
USC00519523 2011-12-20 00:00:00 0.24 74
USC00519523 2011-12-21 00:00:00 0.19 72
USC00519523 2011-12-22 00:00:00 0.02 73
USC00519523 2011-12-23 00:00:00 0.01 73
USC00519523 2011-12-24 00:00:00 0.1 71
USC00519523 2011-12-25 00:00:00 0.07 73
USC00519523 2011-12-26 00:00:00 0.05 75
USC00519523 2011-12-27 00:00:00 0.04 71
USC00519523 2011-12-28 00:00:00 0.0 72
USC00519523 2011-12-29 00:00:00 0.01 73
USC00519523 2011-12-30 00:00:00 0.0 71
USC00519523 2011-12-31 00:00:00 0.0 65
USC00519523 2012-01-01 00:00:00 0.0 70
USC00519523 2012-01-02 00:00:00 0.0 63
USC00519523 2012-01-03 00:00:00 0.0 64
USC00519523 2012-01-04 00:00:00 0.0 72
USC00519523 2012-01-05 00:00:00 0.0 73
USC00519523 2012-01-06 00:00:00 0.0 71
USC00519523 2012-01-07 00:00:00 0.0 73
USC00519523 2012-01-08 00:00:00 0.0 64
USC00519523 2012-01-09 00:00:00 0.08 70
USC00519523 2012-01-10 00:00:00 0.0 71
USC00519523 2012-01-11 00:00:00 0.0 69
USC00519523 2012-01-12 00:00:00 0.0 67
USC00519523 2012-01-13 00:00:00 0.0 65
USC00519523 2012-01-14 00:00:00 0.0 74
USC00519523 2012-01-15 00:00:00 0.0 75
USC00519523 2012-01-16 00:00:00 0.0 75
USC00519523 2012-01-17 00:00:00 0.13 75
USC00519523 2012-01-18 00:00:00 0.07 75
USC00519523 2012-01-19 00:00:00 0.0 66
USC00519523 2012-01-20 00:00:00 0.0 72
USC00519523 2012-01-21 00:00:00 0.0 76
USC00519523 2012-01-22 00:00:00 0.0 75
USC00519523 2012-01-23 00:00:00 0.0 63
USC00519523 2012-01-24 00:00:00 0.0 64
USC00519523 2012-01-25 00:00:00 0.0 69
USC00519523 2012-01-26 00:00:00 0.0 74
USC00519523 2012-01-27 00:00:00 0.08 66
USC00519523 2012-01-28 00:00:00 0.0 74
USC00519523 2012-01-29 00:00:00 0.09 76
USC00519523 2012-01-30 00:00:00 0.01 69
USC00519523 2012-01-31 00:00:00 0.1 70
USC00519523 2012-02-01 00:00:00 0.0 63
USC00519523 2012-02-02 00:00:00 0.0 72
USC00519523 2012-02-03 00:00:00 0.0 63
USC00519523 2012-02-04 00:00:00 0.0 63
USC00519523 2012-02-05 00:00:00 0.0 76
USC00519523 2012-02-06 00:00:00 0.29 65
USC00519523 2012-02-07 00:00:00 0.49 72
USC00519523 2012-02-08 00:00:00 0.41 61
USC00519523 2012-02-09 00:00:00 0.03 63
USC00519523 2012-02-10 00:00:00 0.0 70
USC00519523 2012-02-11 00:00:00 0.0 75
USC00519523 2012-02-12 00:00:00 0.0 76
USC00519523 2012-02-13 00:00:00 0.09 72
USC00519523 2012-02-14 00:00:00 0.0 69
USC00519523 2012-02-15 00:00:00 0.04 66
USC00519523 2012-02-16 00:00:00 0.0 73
USC00519523 2012-02-17 00:00:00 0.0 75
USC00519523 2012-02-18 00:00:00 0.09 74
USC00519523 2012-02-19 00:00:00 0.03 77
USC00519523 2012-02-20 00:00:00 0.01 74
USC00519523 2012-02-21 00:00:00 0.0 72
USC00519523 2012-02-22 00:00:00 0.0 73
USC00519523 2012-02-23 00:00:00 0.0 73
USC00519523 2012-02-24 00:00:00 0.0 71
USC00519523 2012-02-25 00:00:00 0.1 73
USC00519523 2012-02-26 00:00:00 0.07 74
USC00519523 2012-02-27 00:00:00 0.0 72
USC00519523 2012-02-28 00:00:00 0.0 72
USC00519523 2012-02-29 00:00:00 0.0 73
USC00519523 2012-03-01 00:00:00 0.0 73
USC00519523 2012-03-02 00:00:00 0.0 68
USC00519523 2012-03-03 00:00:00 0.11 73
USC00519523 2012-03-04 00:00:00 0.1 73
USC00519523 2012-03-05 00:00:00 2.71 67
USC00519523 2012-03-06 00:00:00 6.38 69
USC00519523 2012-03-07 00:00:00 5.32 68
USC00519523 2012-03-08 00:00:00 0.22 69
USC00519523 2012-03-09 00:00:00 0.16 67
USC00519523 2012-03-10 00:00:00 0.17 75
USC00519523 2012-03-11 00:00:00 0.05 75
USC00519523 2012-03-12 00:00:00 0.15 71
USC00519523 2012-03-13 00:00:00 0.02 70
USC00519523 2012-03-14 00:00:00 0.0 71
USC00519523 2012-03-15 00:00:00 0.05 69
USC00519523 2012-03-16 00:00:00 0.0 71
USC00519523 2012-03-17 00:00:00 0.01 73
USC00519523 2012-03-18 00:00:00 0.08 71
USC00519523 2012-03-19 00:00:00 0.04 72
USC00519523 2012-03-20 00:00:00 0.0 71
USC00519523 2012-03-21 00:00:00 0.0 71
USC00519523 2012-03-22 00:00:00 0.02 73
USC00519523 2012-03-23 00:00:00 0.0 72
USC00519523 2012-03-24 00:00:00 0.0 75
USC00519523 2012-03-25 00:00:00 0.0 71
USC00519523 2012-03-26 00:00:00 0.03 73
USC00519523 2012-03-27 00:00:00 0.02 70
USC00519523 2012-03-28 00:00:00 0.18 69
USC00519523 2012-03-29 00:00:00 0.0 70
USC00519523 2012-03-30 00:00:00 0.0 72
USC00519523 2012-03-31 00:00:00 0.0 74
USC00519523 2012-04-01 00:00:00 0.0 75
USC00519523 2012-04-02 00:00:00 0.0 70
USC00519523 2012-04-03 00:00:00 0.0 72
USC00519523 2012-04-04 00:00:00 0.0 72
USC00519523 2012-04-05 00:00:00 0.0 73
USC00519523 2012-04-06 00:00:00 0.0 73
USC00519523 2012-04-07 00:00:00 0.03 73
USC00519523 2012-04-08 00:00:00 0.0 75
USC00519523 2012-04-09 00:00:00 0.12 71
USC00519523 2012-04-10 00:00:00 0.01 69
USC00519523 2012-04-11 00:00:00 0.1 71
USC00519523 2012-04-12 00:00:00 0.0 72
USC00519523 2012-04-13 00:00:00 0.0 66
USC00519523 2012-04-14 00:00:00 0.0 75
USC00519523 2012-04-15 00:00:00 0.08 74
USC00519523 2012-04-16 00:00:00 0.0 73
USC00519523 2012-04-17 00:00:00 0.0 73
USC00519523 2012-04-18 00:00:00 0.0 73
USC00519523 2012-04-19 00:00:00 0.0 73

USC00519523 2012-04-20 00:00:00 0.0 73
USC00519523 2012-04-21 00:00:00 0.0 73
USC00519523 2012-04-22 00:00:00 0.1 69
USC00519523 2012-04-23 00:00:00 0.1 72
USC00519523 2012-04-24 00:00:00 0.0 72
USC00519523 2012-04-25 00:00:00 0.02 71
USC00519523 2012-04-26 00:00:00 0.0 73
USC00519523 2012-04-27 00:00:00 0.13 69
USC00519523 2012-04-28 00:00:00 0.0 76
USC00519523 2012-04-29 00:00:00 0.0 74
USC00519523 2012-04-30 00:00:00 0.0 74
USC00519523 2012-05-01 00:00:00 0.0 73
USC00519523 2012-05-02 00:00:00 0.0 72
USC00519523 2012-05-03 00:00:00 0.06 75
USC00519523 2012-05-04 00:00:00 0.01 74
USC00519523 2012-05-05 00:00:00 0.1 76
USC00519523 2012-05-06 00:00:00 0.02 73
USC00519523 2012-05-07 00:00:00 0.0 74
USC00519523 2012-05-08 00:00:00 0.0 77
USC00519523 2012-05-09 00:00:00 0.0 75
USC00519523 2012-05-10 00:00:00 0.0 76
USC00519523 2012-05-11 00:00:00 0.0 77
USC00519523 2012-05-12 00:00:00 0.0 79
USC00519523 2012-05-13 00:00:00 0.0 77
USC00519523 2012-05-14 00:00:00 0.0 76
USC00519523 2012-05-15 00:00:00 0.0 66
USC00519523 2012-05-16 00:00:00 0.0 72
USC00519523 2012-05-17 00:00:00 0.01 74
USC00519523 2012-05-18 00:00:00 0.0 74
USC00519523 2012-05-19 00:00:00 0.0 76
USC00519523 2012-05-20 00:00:00 0.0 77
USC00519523 2012-05-21 00:00:00 0.0 75
USC00519523 2012-05-22 00:00:00 0.0 75
USC00519523 2012-05-23 00:00:00 0.0 77
USC00519523 2012-05-24 00:00:00 0.0 75
USC00519523 2012-05-25 00:00:00 0.0 75
USC00519523 2012-05-26 00:00:00 0.01 75
USC00519523 2012-05-27 00:00:00 0.01 78
USC00519523 2012-05-28 00:00:00 0.0 78
USC00519523 2012-05-29 00:00:00 0.0 74
USC00519523 2012-05-30 00:00:00 0.0 73
USC00519523 2012-05-31 00:00:00 0.15 73
USC00519523 2012-06-01 00:00:00 0.0 74
USC00519523 2012-06-02 00:00:00 0.0 75
USC00519523 2012-06-03 00:00:00 0.0 77
USC00519523 2012-06-04 00:00:00 0.0 75
USC00519523 2012-06-05 00:00:00 0.0 74
USC00519523 2012-06-06 00:00:00 0.12 75
USC00519523 2012-06-07 00:00:00 0.0 74
USC00519523 2012-06-08 00:00:00 0.0 75
USC00519523 2012-06-09 00:00:00 0.0 73
USC00519523 2012-06-10 00:00:00 0.0 75
USC00519523 2012-06-11 00:00:00 0.0 76
USC00519523 2012-06-12 00:00:00 0.01 76
USC00519523 2012-06-13 00:00:00 0.01 76
USC00519523 2012-06-14 00:00:00 0.0 79
USC00519523 2012-06-15 00:00:00 0.0 74
USC00519523 2012-06-16 00:00:00 0.0 78
USC00519523 2012-06-17 00:00:00 0.0 80
USC00519523 2012-06-18 00:00:00 0.0 75
USC00519523 2012-06-19 00:00:00 0.25 72
USC00519523 2012-06-20 00:00:00 0.25 72
USC00519523 2012-06-21 00:00:00 0.0 74
USC00519523 2012-06-22 00:00:00 0.0 78
USC00519523 2012-06-23 00:00:00 0.1 76
USC00519523 2012-06-24 00:00:00 0.0 77
USC00519523 2012-06-25 00:00:00 0.51 72
USC00519523 2012-06-26 00:00:00 0.19 72
USC00519523 2012-06-27 00:00:00 0.15 73
USC00519523 2012-06-28 00:00:00 0.0 75
USC00519523 2012-06-29 00:00:00 0.06 79
USC00519523 2012-06-30 00:00:00 0.0 81
USC00519523 2012-07-01 00:00:00 0.0 78
USC00519523 2012-07-02 00:00:00 0.0 76
USC00519523 2012-07-03 00:00:00 0.2 76
USC00519523 2012-07-04 00:00:00 0.0 75
USC00519523 2012-07-05 00:00:00 0.13 77
USC00519523 2012-07-06 00:00:00 0.07 79
USC00519523 2012-07-07 00:00:00 0.07 76
USC00519523 2012-07-08 00:00:00 0.01 81
USC00519523 2012-07-09 00:00:00 0.0 75
USC00519523 2012-07-10 00:00:00 0.0 79
USC00519523 2012-07-11 00:00:00 0.0 75
USC00519523 2012-07-12 00:00:00 0.0 74
USC00519523 2012-07-13 00:00:00 0.0 78
USC00519523 2012-07-14 00:00:00 0.02 82
USC00519523 2012-07-15 00:00:00 0.0 80
USC00519523 2012-07-16 00:00:00 0.01 76
USC00519523 2012-07-17 00:00:00 0.02 78
USC00519523 2012-07-18 00:00:00 0.02 77
USC00519523 2012-07-19 00:00:00 0.07 74
USC00519523 2012-07-20 00:00:00 0.05 74
USC00519523 2012-07-21 00:00:00 0.0 80
USC00519523 2012-07-22 00:00:00 0.0 79
USC00519523 2012-07-23 00:00:00 0.03 76
USC00519523 2012-07-24 00:00:00 0.0 76
USC00519523 2012-07-25 00:00:00 0.0 76
USC00519523 2012-07-26 00:00:00 0.0 76
USC00519523 2012-07-27 00:00:00 0.0 75
USC00519523 2012-07-28 00:00:00 0.05 79
USC00519523 2012-07-29 00:00:00 0.0 75
USC00519523 2012-07-30 00:00:00 0.02 76
USC00519523 2012-07-31 00:00:00 0.0 77
USC00519523 2012-08-01 00:00:00 0.0 76
USC00519523 2012-08-02 00:00:00 0.0 78
USC00519523 2012-08-03 00:00:00 0.0 76
USC00519523 2012-08-04 00:00:00 0.0 80
USC00519523 2012-08-05 00:00:00 0.05 82
USC00519523 2012-08-06 00:00:00 0.02 78
USC00519523 2012-08-07 00:00:00 0.0 76
USC00519523 2012-08-08 00:00:00 0.01 76
USC00519523 2012-08-09 00:00:00 0.03 77
USC00519523 2012-08-10 00:00:00 0.0 75
USC00519523 2012-08-11 00:00:00 0.19 73
USC00519523 2012-08-12 00:00:00 0.0 81
USC00519523 2012-08-13 00:00:00 0.0 81
USC00519523 2012-08-14 00:00:00 0.09 76
USC00519523 2012-08-15 00:00:00 0.0 77
USC00519523 2012-08-16 00:00:00 0.0 76
USC00519523 2012-08-17 00:00:00 0.0 81
USC00519523 2012-08-18 00:00:00 0.03 75
USC00519523 2012-08-19 00:00:00 0.05 73
USC00519523 2012-08-20 00:00:00 0.0 76
USC00519523 2012-08-21 00:00:00 0.02 76
USC00519523 2012-08-22 00:00:00 0.01 75
USC00519523 2012-08-23 00:00:00 0.0 78
USC00519523 2012-08-24 00:00:00 0.0 76
USC00519523 2012-08-25 00:00:00 0.0 79
USC00519523 2012-08-26 00:00:00 0.01 78
USC00519523 2012-08-27 00:00:00 0.04 77
USC00519523 2012-08-28 00:00:00 0.03 75
USC00519523 2012-08-29 00:00:00 0.05 75
USC00519523 2012-08-30 00:00:00 0.04 76
USC00519523 2012-08-31 00:00:00 0.0 77
USC00519523 2012-09-01 00:00:00 0.0 80
USC00519523 2012-09-02 00:00:00 0.0 80
USC00519523 2012-09-03 00:00:00 0.0 82
USC00519523 2012-09-04 00:00:00 0.0 74
USC00519523 2012-09-05 00:00:00 0.0 75
USC00519523 2012-09-06 00:00:00 0.07 76
USC00519523 2012-09-07 00:00:00 0.02 82
USC00519523 2012-09-08 00:00:00 0.14 79
USC00519523 2012-09-09 00:00:00 0.02 76
USC00519523 2012-09-10 00:00:00 0.0 76
USC00519523 2012-09-11 00:00:00 0.0 76
USC00519523 2012-09-12 00:00:00 0.05 76
USC00519523 2012-09-13 00:00:00 0.0 77
USC00519523 2012-09-14 00:00:00 0.19 76
USC00519523 2012-09-15 00:00:00 0.0 78
USC00519523 2012-09-16 00:00:00 0.0 76
USC00519523 2012-09-17 00:00:00 0.0 78
USC00519523 2012-09-18 00:00:00 0.13 69
USC00519523 2012-09-19 00:00:00 0.27 75
USC00519523 2012-09-20 00:00:00 0.21 69
USC00519523 2012-09-21 00:00:00 0.05 72
USC00519523 2012-09-22 00:00:00 0.0 77
USC00519523 2012-09-23 00:00:00 0.09 75
USC00519523 2012-09-24 00:00:00 0.1 74
USC00519523 2012-09-25 00:00:00 0.03 74
USC00519523 2012-09-26 00:00:00 0.01 76
USC00519523 2012-09-27 00:00:00 0.0 75
USC00519523 2012-09-28 00:00:00 0.0 76
USC00519523 2012-09-29 00:00:00 0.0 74
USC00519523 2012-09-30 00:00:00 0.04 77
USC00519523 2012-10-01 00:00:00 0.01 70
USC00519523 2012-10-02 00:00:00 0.0 75
USC00519523 2012-10-03 00:00:00 0.0 77
USC00519523 2012-10-04 00:00:00 0.0 76
USC00519523 2012-10-05 00:00:00 0.0 70
USC00519523 2012-10-06 00:00:00 0.0 75
USC00519523 2012-10-07 00:00:00 0.0 81
USC00519523 2012-10-08 00:00:00 0.0 77
USC00519523 2012-10-09 00:00:00 0.0 78
USC00519523 2012-10-10 00:00:00 0.0 73
USC00519523 2012-10-11 00:00:00 0.03 77
USC00519523 2012-10-12 00:00:00 0.0 76
USC00519523 2012-10-13 00:00:00 0.0 76
USC00519523 2012-10-14 00:00:00 0.0 77
USC00519523 2012-10-15 00:00:00 0.2 76
USC00519523 2012-10-16 00:00:00 0.0 74
USC00519523 2012-10-17 00:00:00 0.0 69
USC00519523 2012-10-18 00:00:00 0.14 73
USC00519523 2012-10-19 00:00:00 0.03 76
USC00519523 2012-10-20 00:00:00 0.0 79
USC00519523 2012-10-21 00:00:00 0.0 78
USC00519523 2012-10-22 00:00:00 0.0 77
USC00519523 2012-10-23 00:00:00 0.0 79
USC00519523 2012-10-24 00:00:00 0.0 81
USC00519523 2012-10-25 00:00:00 0.82 73
USC00519523 2012-10-26 00:00:00 0.0 72
USC00519523 2012-10-27 00:00:00 0.0 78
USC00519523 2012-10-28 00:00:00 0.05 79
USC00519523 2012-10-29 00:00:00 0.11 75
USC00519523 2012-10-30 00:00:00 0.12 74
USC00519523 2012-11-02 00:00:00 0.0 65
USC00519523 2012-11-03 00:00:00 0.0 73
USC00519523 2012-11-04 00:00:00 0.0 69
USC00519523 2012-11-05 00:00:00 0.0 70
USC00519523 2012-11-06 00:00:00 0.0 77
USC00519523 2012-11-07 00:00:00 0.1 76
USC00519523 2012-11-08 00:00:00 0.0 75
USC00519523 2012-11-09 00:00:00 0.0 75
USC00519523 2012-11-10 00:00:00 0.0 74
USC00519523 2012-11-11 00:00:00 0.0 79
USC00519523 2012-11-12 00:00:00 0.0 76
USC00519523 2012-11-13 00:00:00 0.03 73
USC00519523 2012-11-14 00:00:00 0.1 74
USC00519523 2012-11-15 00:00:00 0.0 74
USC00519523 2012-11-17 00:00:00 0.1 73
USC00519523 2012-11-18 00:00:00 0.0 76
USC00519523 2012-11-19 00:00:00 0.0 74
USC00519523 2012-11-20 00:00:00 0.0 75
USC00519523 2012-11-21 00:00:00 0.0 72
USC00519523 2012-11-22 00:00:00 0.0 66
USC00519523 2012-11-23 00:00:00 0.0 80
USC00519523 2012-11-24 00:00:00 0.0 75
USC00519523 2012-11-25 00:00:00 0.0 73
USC00519523 2012-11-26 00:00:00 0.16 72
USC00519523 2012-11-27 00:00:00 0.0 70
USC00519523 2012-11-28 00:00:00 0.0 66
USC00519523 2012-11-29 00:00:00 0.0 63
USC00519523 2012-11-30 00:00:00 0.0 63
USC00519523 2012-12-01 00:00:00 0.0 77
USC00519523 2012-12-02 00:00:00 0.0 72
USC00519523 2012-12-03 00:00:00 0.0 78
USC00519523 2012-12-04 00:00:00 0.08 71
USC00519523 2012-12-05 00:00:00 1.02 72
USC00519523 2012-12-06 00:00:00 0.01 71
USC00519523 2012-12-07 00:00:00 0.0 72
USC00519523 2012-12-08 00:00:00 0.0 76
USC00519523 2012-12-09 00:00:00 0.0 75
USC00519523 2012-12-10 00:00:00 0.0 75
USC00519523 2012-12-11 00:00:00 0.0 76
USC00519523 2012-12-12 00:00:00 0.04 73
USC00519523 2012-12-13 00:00:00 0.13 72
USC00519523 2012-12-14 00:00:00 0.09 74
USC00519523 2012-12-15 00:00:00 0.12 74
USC00519523 2012-12-16 00:00:00 0.04 74
USC00519523 2012-12-17 00:00:00 0.09 73
USC00519523 2012-12-18 00:00:00 0.22 77
USC00519523 2012-12-19 00:00:00 0.04 73
USC00519523 2012-12-20 00:00:00 0.1 70
USC00519523 2012-12-21 00:00:00 0.02 72
USC00519523 2012-12-22 00:00:00 0.0 76
USC00519523 2012-12-23 00:00:00 0.0 65
USC00519523 2012-12-24 00:00:00 0.0 74
USC00519523 2012-12-25 00:00:00 0.1 73
USC00519523 2012-12-26 00:00:00 0.03 77
USC00519523 2012-12-27 00:00:00 0.0 76
USC00519523 2012-12-28 00:00:00 0.0 69
USC00519523 2012-12-29 00:00:00 0.0 78
USC00519523 2012-12-30 00:00:00 0.03 76
USC00519523 2012-12-31 00:00:00 0.0 68
USC00519523 2013-01-01 00:00:00 0.38 72
USC00519523 2013-01-02 00:00:00 0.13 73
USC00519523 2013-01-03 00:00:00 0.43 69
USC00519523 2013-01-04 00:00:00 0.05 72
USC00519523 2013-01-05 00:00:00 0.23 72
USC00519523 2013-01-06 00:00:00 0.11 73
USC00519523 2013-01-07 00:00:00 0.02 73
USC00519523 2013-01-08 00:00:00 0.06 72
USC00519523 2013-01-09 00:00:00 0.17 72
USC00519523 2013-01-10 00:00:00 0.01 73
USC00519523 2013-01-11 00:00:00 0.0 72
USC00519523 2013-01-12 00:00:00 0.08 71
USC00519523 2013-01-13 00:00:00 0.06 76
USC00519523 2013-01-14 00:00:00 0.0 75
USC00519523 2013-01-15 00:00:00 1.07 73
USC00519523 2013-01-16 00:00:00 0.0 56
USC00519523 2013-01-17 00:00:00 0.0 63
USC00519523 2013-01-18 00:00:00 0.01 61
USC00519523 2013-01-19 00:00:00 0.05 70
USC00519523 2013-01-20 00:00:00 0.0 70
USC00519523 2013-01-21 00:00:00 0.0 71
USC00519523 2013-01-22 00:00:00 0.0 70
USC00519523 2013-01-25 00:00:00 0.43 63
USC00519523 2013-01-26 00:00:00 0.01 72
USC00519523 2013-01-27 00:00:00 0.02 74
USC00519523 2013-01-28 00:00:00 2.48 65
USC00519523 2013-01-29 00:00:00 0.61 66
USC00519523 2013-01-30 00:00:00 0.03 63
USC00519523 2013-01-31 00:00:00 0.02 70
USC00519523 2013-02-01 00:00:00 0.01 74
USC00519523 2013-02-02 00:00:00 0.0 76
USC00519523 2013-02-03 00:00:00 0.0 69
USC00519523 2013-02-04 00:00:00 0.01 72
USC00519523 2013-02-05 00:00:00 0.01 70
USC00519523 2013-02-06 00:00:00 0.0 69
USC00519523 2013-02-07 00:00:00 0.09 73
USC00519523 2013-02-08 00:00:00 0.0 71
USC00519523 2013-02-09 00:00:00 0.06 74
USC00519523 2013-02-10 00:00:00 0.0 70
USC00519523 2013-02-11 00:00:00 0.08 69
USC00519523 2013-02-12 00:00:00 0.06 68
USC00519523 2013-02-13 00:00:00 0.0 70
USC00519523 2013-02-14 00:00:00 0.0 71
USC00519523 2013-02-15 00:00:00 0.0 70
USC00519523 2013-02-16 00:00:00 0.03 71
USC00519523 2013-02-17 00:00:00 0.0 72
USC00519523 2013-02-18 00:00:00 0.0 72
USC00519523 2013-02-19 00:00:00 0.16 70
USC00519523 2013-02-20 00:00:00 0.03 71
USC00519523 2013-02-21 00:00:00 0.13 70
USC00519523 2013-02-22 00:00:00 0.25 71
USC00519523 2013-02-23 00:00:00 0.05 76
USC00519523 2013-02-24 00:00:00 0.0 75
USC00519523 2013-02-25 00:00:00 0.07 70
USC00519523 2013-02-26 00:00:00 0.03 71
USC00519523 2013-02-27 00:00:00 0.0 70
USC00519523 2013-02-28 00:00:00 0.0 71
USC00519523 2013-03-01 00:00:00 0.0 70
USC00519523 2013-03-02 00:00:00 0.03 74
USC00519523 2013-03-03 00:00:00 0.0 71
USC00519523 2013-03-04 00:00:00 0.0 69
USC00519523 2013-03-05 00:00:00 0.0 72
USC00519523 2013-03-06 00:00:00 0.0 70
USC00519523 2013-03-07 00:00:00 0.04 67
USC00519523 2013-03-08 00:00:00 0.0 59
USC00519523 2013-03-09 00:00:00 0.13 73
USC00519523 2013-03-10 00:00:00 1.11 68
USC00519523 2013-03-11 00:00:00 1.02 60
USC00519523 2013-03-12 00:00:00 0.02 65
USC00519523 2013-03-13 00:00:00 0.06 67
USC00519523 2013-03-14 00:00:00 0.13 72
USC00519523 2013-03-15 00:00:00 0.0 58
USC00519523 2013-03-16 00:00:00 0.0 70
USC00519523 2013-03-17 00:00:00 0.0 74
USC00519523 2013-03-18 00:00:00 0.09 57
USC00519523 2013-03-19 00:00:00 0.0 62
USC00519523 2013-03-20 00:00:00 0.0 67
USC00519523 2013-03-21 00:00:00 0.0 73
USC00519523 2013-03-22 00:00:00 0.0 73
USC00519523 2013-03-23 00:00:00 0.59 67
USC00519523 2013-03-26 00:00:00 0.0 69
USC00519523 2013-03-27 00:00:00 0.12 72
USC00519523 2013-03-28 00:00:00 0.03 74
USC00519523 2013-03-29 00:00:00 0.15 73
USC00519523 2013-03-30 00:00:00 0.03 71
USC00519523 2013-03-31 00:00:00 0.02 69
USC00519523 2013-04-01 00:00:00 0.0 66
USC00519523 2013-04-02 00:00:00 0.01 66
USC00519523 2013-04-03 00:00:00 0.0 67
USC00519523 2013-04-04 00:00:00 0.02 72
USC00519523 2013-04-05 00:00:00 0.0 74
USC00519523 2013-04-06 00:00:00 0.0 77
USC00519523 2013-04-07 00:00:00 0.0 76
USC00519523 2013-04-08 00:00:00 0.0 77
USC00519523 2013-04-09 00:00:00 0.0 74
USC00519523 2013-04-10 00:00:00 0.0 73
USC00519523 2013-04-11 00:00:00 0.0 74
USC00519523 2013-04-12 00:00:00 0.0 74
USC00519523 2013-04-13 00:00:00 0.0 74
USC00519523 2013-04-14 00:00:00 0.0 78
USC00519523 2013-04-15 00:00:00 0.44 71
USC00519523 2013-04-16 00:00:00 0.01 66
USC00519523 2013-04-17 00:00:00 0.0 74
USC00519523 2013-04-18 00:00:00 0.0 74
USC00519523 2013-04-19 00:00:00 0.01 74
USC00519523 2013-04-20 00:00:00 0.0 70
USC00519523 2013-04-21 00:00:00 0.0 75
USC00519523 2013-04-22 00:00:00 0.35 71
USC00519523 2013-04-23 00:00:00 0.34 75
USC00519523 2013-04-24 00:00:00 2.05 69
USC00519523 2013-04-27 00:00:00 0.0 69
USC00519523 2013-04-28 00:00:00 0.0 79
USC00519523 2013-04-29 00:00:00 0.0 76
USC00519523 2013-04-30 00:00:00 0.0 78
USC00519523 2013-05-01 00:00:00 0.0 78
USC00519523 2013-05-02 00:00:00 0.0 77
USC00519523 2013-05-03 00:00:00 0.0 78
USC00519523 2013-05-04 00:00:00 0.0 72
USC00519523 2013-05-05 00:00:00 0.15 71
USC00519523 2013-05-06 00:00:00 1.24 72
USC00519523 2013-05-07 00:00:00 0.04 74
USC00519523 2013-05-08 00:00:00 0.0 76

USC00519523 2013-05-09 00:00:00 0.0 72
USC00519523 2013-05-10 00:00:00 0.26 72
USC00519523 2013-05-11 00:00:00 0.16 74
USC00519523 2013-05-12 00:00:00 0.4 70
USC00519523 2013-05-13 00:00:00 0.12 74
USC00519523 2013-05-14 00:00:00 0.02 80
USC00519523 2013-05-15 00:00:00 0.0 74
USC00519523 2013-05-16 00:00:00 0.0 75
USC00519523 2013-05-17 00:00:00 0.0 76
USC00519523 2013-05-18 00:00:00 0.13 78
USC00519523 2013-05-19 00:00:00 0.06 74
USC00519523 2013-05-20 00:00:00 1.96 70
USC00519523 2013-05-21 00:00:00 0.0 72
USC00519523 2013-05-22 00:00:00 0.0 78
USC00519523 2013-05-23 00:00:00 0.03 77
USC00519523 2013-05-24 00:00:00 0.0 76
USC00519523 2013-05-25 00:00:00 0.08 77
USC00519523 2013-05-26 00:00:00 0.06 75
USC00519523 2013-05-27 00:00:00 0.0 77
USC00519523 2013-05-28 00:00:00 0.1 78
USC00519523 2013-05-29 00:00:00 0.0 72
USC00519523 2013-05-30 00:00:00 0.0 76
USC00519523 2013-05-31 00:00:00 0.0 77
USC00519523 2013-06-01 00:00:00 0.0 76
USC00519523 2013-06-02 00:00:00 0.08 76
USC00519523 2013-06-03 00:00:00 0.02 77
USC00519523 2013-06-04 00:00:00 0.0 78
USC00519523 2013-06-05 00:00:00 0.0 79
USC00519523 2013-06-06 00:00:00 0.0 79
USC00519523 2013-06-07 00:00:00 0.07 75
USC00519523 2013-06-08 00:00:00 0.0 79
USC00519523 2013-06-09 00:00:00 0.0 79
USC00519523 2013-06-10 00:00:00 0.0 75
USC00519523 2013-06-11 00:00:00 0.0 77
USC00519523 2013-06-12 00:00:00 0.0 81
USC00519523 2013-06-13 00:00:00 0.0 76
USC00519523 2013-06-14 00:00:00 0.28 75
USC00519523 2013-06-15 00:00:00 0.0 78
USC00519523 2013-06-16 00:00:00 0.0 81
USC00519523 2013-06-17 00:00:00 0.0 76
USC00519523 2013-06-18 00:00:00 0.0 76
USC00519523 2013-06-19 00:00:00 0.0 76
USC00519523 2013-06-20 00:00:00 0.07 72
USC00519523 2013-06-21 00:00:00 0.32 73
USC00519523 2013-06-22 00:00:00 0.13 74
USC00519523 2013-06-23 00:00:00 0.08 74
USC00519523 2013-06-24 00:00:00 0.01 75
USC00519523 2013-06-25 00:00:00 0.18 73
USC00519523 2013-06-26 00:00:00 0.42 73
USC00519523 2013-06-27 00:00:00 0.02 76
USC00519523 2013-06-29 00:00:00 0.05 73
USC00519523 2013-06-30 00:00:00 0.0 79
USC00519523 2013-07-01 00:00:00 0.0 75
USC00519523 2013-07-02 00:00:00 0.16 73
USC00519523 2013-07-03 00:00:00 0.0 76
USC00519523 2013-07-04 00:00:00 0.0 78
USC00519523 2013-07-05 00:00:00 0.0 71
USC00519523 2013-07-06 00:00:00 0.0 73
USC00519523 2013-07-07 00:00:00 0.0 77
USC00519523 2013-07-08 00:00:00 0.02 77
USC00519523 2013-07-09 00:00:00 0.0 78
USC00519523 2013-07-10 00:00:00 0.07 77
USC00519523 2013-07-11 00:00:00 0.06 76
USC00519523 2013-07-12 00:00:00 0.02 76
USC00519523 2013-07-13 00:00:00 0.0 76
USC00519523 2013-07-14 00:00:00 0.0 81
USC00519523 2013-07-15 00:00:00 0.0 76
USC00519523 2013-07-16 00:00:00 0.0 78
USC00519523 2013-07-17 00:00:00 0.0 77
USC00519523 2013-07-18 00:00:00 0.0 76
USC00519523 2013-07-19 00:00:00 0.0 78
USC00519523 2013-07-20 00:00:00 0.0 79
USC00519523 2013-07-21 00:00:00 0.0 79
USC00519523 2013-07-22 00:00:00 0.2 75
USC00519523 2013-07-23 00:00:00 0.2 74
USC00519523 2013-07-24 00:00:00 0.01 77
USC00519523 2013-07-25 00:00:00 0.0 81
USC00519523 2013-07-26 00:00:00 0.0 79
USC00519523 2013-07-29 00:00:00 0.2 77
USC00519523 2013-07-30 00:00:00 0.27 79
USC00519523 2013-07-31 00:00:00 0.08 78
USC00519523 2013-08-01 00:00:00 0.15 77
USC00519523 2013-08-02 00:00:00 0.04 76
USC00519523 2013-08-03 00:00:00 0.0 77
USC00519523 2013-08-04 00:00:00 0.0 79
USC00519523 2013-08-05 00:00:00 0.0 77
USC00519523 2013-08-06 00:00:00 0.0 77
USC00519523 2013-08-07 00:00:00 0.0 76
USC00519523 2013-08-08 00:00:00 0.0 77
USC00519523 2013-08-09 00:00:00 0.0 76
USC00519523 2013-08-10 00:00:00 1.67 73
USC00519523 2013-08-11 00:00:00 0.42 82
USC00519523 2013-08-12 00:00:00 0.01 77
USC00519523 2013-08-13 00:00:00 0.0 77
USC00519523 2013-08-14 00:00:00 0.05 77
USC00519523 2013-08-15 00:00:00 0.0 76
USC00519523 2013-08-16 00:00:00 0.05 77
USC00519523 2013-08-17 00:00:00 0.0 79
USC00519523 2013-08-18 00:00:00 0.0 82
USC00519523 2013-08-19 00:00:00 0.0 73
USC00519523 2013-08-20 00:00:00 0.0 73
USC00519523 2013-08-21 00:00:00 0.43 73
USC00519523 2013-08-22 00:00:00 0.0 78
USC00519523 2013-08-23 00:00:00 0.0 74
USC00519523 2013-08-24 00:00:00 0.05 78
USC00519523 2013-08-25 00:00:00 0.0 80
USC00519523 2013-08-26 00:00:00 0.0 78
USC00519523 2013-08-27 00:00:00 0.0 77
USC00519523 2013-08-28 00:00:00 0.0 74
USC00519523 2013-08-29 00:00:00 0.19 72
USC00519523 2013-09-01 00:00:00 0.09 78
USC00519523 2013-09-02 00:00:00 0.0 79
USC00519523 2013-09-03 00:00:00 0.05 75
USC00519523 2013-09-04 00:00:00 0.04 71
USC00519523 2013-09-05 00:00:00 0.0 68
USC00519523 2013-09-06 00:00:00 0.0 79
USC00519523 2013-09-07 00:00:00 0.53 78
USC00519523 2013-09-10 00:00:00 0.0 77
USC00519523 2013-09-11 00:00:00 0.25 76
USC00519523 2013-09-12 00:00:00 0.05 76
USC00519523 2013-09-13 00:00:00 0.32 76
USC00519523 2013-09-14 00:00:00 0.09 81
USC00519523 2013-09-15 00:00:00 0.15 78
USC00519523 2013-09-16 00:00:00 0.02 78
USC00519523 2013-09-17 00:00:00 0.07 76
USC00519523 2013-09-18 00:00:00 0.06 78
USC00519523 2013-09-19 00:00:00 0.04 78
USC00519523 2013-09-20 00:00:00 0.0 78
USC00519523 2013-09-23 00:00:00 0.0 81
USC00519523 2013-09-26 00:00:00 0.49 78
USC00519523 2013-09-27 00:00:00 0.02 78
USC00519523 2013-09-28 00:00:00 0.0 78
USC00519523 2013-09-29 00:00:00 0.07 79
USC00519523 2013-09-30 00:00:00 0.13 78
USC00519523 2013-10-01 00:00:00 0.0 78
USC00519523 2013-10-02 00:00:00 0.0 77
USC00519523 2013-10-03 00:00:00 0.0 76
USC00519523 2013-10-04 00:00:00 0.0 77
USC00519523 2013-10-07 00:00:00 0.0 77
USC00519523 2013-10-08 00:00:00 0.0 77
USC00519523 2013-10-09 00:00:00 0.0 78
USC00519523 2013-10-10 00:00:00 0.07 78
USC00519523 2013-10-11 00:00:00 0.0 75
USC00519523 2013-10-12 00:00:00 0.06 76
USC00519523 2013-10-13 00:00:00 0.0 72
USC00519523 2013-10-14 00:00:00 0.68 74
USC00519523 2013-10-15 00:00:00 0.0 74
USC00519523 2013-10-16 00:00:00 0.0 75
USC00519523 2013-10-17 00:00:00 0.0 78
USC00519523 2013-10-18 00:00:00 0.05 69
USC00519523 2013-10-19 00:00:00 0.0 66
USC00519523 2013-10-20 00:00:00 0.01 69
USC00519523 2013-10-21 00:00:00 0.0 68
USC00519523 2013-10-22 00:00:00 0.0 74
USC00519523 2013-10-23 00:00:00 0.0 81
USC00519523 2013-10-24 00:00:00 0.11 73
USC00519523 2013-10-25 00:00:00 0.0 76
USC00519523 2013-10-26 00:00:00 0.0 79
USC00519523 2013-10-29 00:00:00 0.0 76
USC00519523 2013-10-30 00:00:00 0.0 76
USC00519523 2013-10-31 00:00:00 0.0 74
USC00519523 2013-11-01 00:00:00 0.0 76
USC00519523 2013-11-02 00:00:00 0.07 75
USC00519523 2013-11-03 00:00:00 0.0 78
USC00519523 2013-11-04 00:00:00 0.0 82
USC00519523 2013-11-05 00:00:00 0.0 74
USC00519523 2013-11-06 00:00:00 0.05 73
USC00519523 2013-11-07 00:00:00 0.2 74
USC00519523 2013-11-08 00:00:00 0.02 74
USC00519523 2013-11-09 00:00:00 0.04 74
USC00519523 2013-11-10 00:00:00 4.76 73
USC00519523 2013-11-11 00:00:00 0.03 76
USC00519523 2013-11-12 00:00:00 0.24 62
USC00519523 2013-11-13 00:00:00 0.0 64
USC00519523 2013-11-14 00:00:00 0.05 72
USC00519523 2013-11-15 00:00:00 0.78 73
USC00519523 2013-11-21 00:00:00 0.0 70
USC00519523 2013-11-22 00:00:00 0.0 71
USC00519523 2013-11-23 00:00:00 0.0 76
USC00519523 2013-11-24 00:00:00 0.0 70
USC00519523 2013-11-25 00:00:00 0.0 73
USC00519523 2013-11-26 00:00:00 0.0 74
USC00519523 2013-11-27 00:00:00 0.0 73
USC00519523 2013-11-28 00:00:00 0.0 73
USC00519523 2013-11-29 00:00:00 0.0 73
USC00519523 2013-11-30 00:00:00 0.38 78
USC00519523 2013-12-01 00:00:00 0.09 76
USC00519523 2013-12-02 00:00:00 2.25 68
USC00519523 2013-12-03 00:00:00 0.09 79
USC00519523 2013-12-04 00:00:00 0.0 69
USC00519523 2013-12-05 00:00:00 0.0 64
USC00519523 2013-12-06 00:00:00 0.0 70
USC00519523 2013-12-07 00:00:00 0.0 69
USC00519523 2013-12-08 00:00:00 0.0 73
USC00519523 2013-12-09 00:00:00 0.0 70
USC00519523 2013-12-10 00:00:00 0.03 74
USC00519523 2013-12-11 00:00:00 0.0 76
USC00519523 2013-12-12 00:00:00 0.02 76
USC00519523 2013-12-13 00:00:00 0.02 69
USC00519523 2013-12-14 00:00:00 0.0 73
USC00519523 2013-12-15 00:00:00 0.1 73
USC00519523 2013-12-16 00:00:00 0.88 65
USC00519523 2013-12-17 00:00:00 0.0 70
USC00519523 2013-12-18 00:00:00 0.0 72
USC00519523 2013-12-19 00:00:00 0.35 72
USC00519523 2013-12-20 00:00:00 0.01 75
USC00519523 2013-12-21 00:00:00 0.0 74
USC00519523 2013-12-22 00:00:00 0.01 69
USC00519523 2013-12-23 00:00:00 0.08 73
USC00519523 2013-12-24 00:00:00 0.04 75
USC00519523 2013-12-25 00:00:00 0.0 76
USC00519523 2013-12-26 00:00:00 0.0 74
USC00519523 2013-12-27 00:00:00 0.0 73
USC00519523 2013-12-28 00:00:00 0.06 74
USC00519523 2013-12-29 00:00:00 0.16 71
USC00519523 2013-12-30 00:00:00 0.01 72
USC00519523 2013-12-31 00:00:00 0.17 73
USC00519523 2014-01-01 00:00:00 0.01 75
USC00519523 2014-01-02 00:00:00 0.15 75
USC00519523 2014-01-03 00:00:00 0.92 68
USC00519523 2014-01-04 00:00:00 0.0 70
USC00519523 2014-01-05 00:00:00 0.0 69
USC00519523 2014-01-06 00:00:00 0.23 68
USC00519523 2014-01-07 00:00:00 0.0 71
USC00519523 2014-01-08 00:00:00 0.0 71
USC00519523 2014-01-09 00:00:00 0.12 70
USC00519523 2014-01-10 00:00:00 0.01 72
USC00519523 2014-01-11 00:00:00 0.0 75
USC00519523 2014-01-12 00:00:00 0.0 68
USC00519523 2014-01-13 00:00:00 0.0 66
USC00519523 2014-01-14 00:00:00 0.44 75
USC00519523 2014-01-15 00:00:00 0.28 72
USC00519523 2014-01-16 00:00:00 0.3 65
USC00519523 2014-01-17 00:00:00 0.15 66
USC00519523 2014-01-18 00:00:00 0.13 65
USC00519523 2014-01-19 00:00:00 0.0 70
USC00519523 2014-01-20 00:00:00 0.17 72
USC00519523 2014-01-21 00:00:00 0.0 72
USC00519523 2014-01-22 00:00:00 0.31 69
USC00519523 2014-01-25 00:00:00 0.0 72
USC00519523 2014-01-28 00:00:00 0.44 69
USC00519523 2014-01-29 00:00:00 0.21 69
USC00519523 2014-01-30 00:00:00 0.08 65
USC00519523 2014-01-31 00:00:00 0.0 65
USC00519523 2014-02-01 00:00:00 0.95 74
USC00519523 2014-02-02 00:00:00 0.57 69
USC00519523 2014-02-03 00:00:00 0.02 70
USC00519523 2014-02-04 00:00:00 1.48 67
USC00519523 2014-02-05 00:00:00 0.55 75
USC00519523 2014-02-06 00:00:00 0.15 74
USC00519523 2014-02-07 00:00:00 0.17 70
USC00519523 2014-02-08 00:00:00 1.81 68
USC00519523 2014-02-09 00:00:00 0.44 74
USC00519523 2014-02-10 00:00:00 0.03 68
USC00519523 2014-02-11 00:00:00 0.0 65
USC00519523 2014-02-12 00:00:00 0.05 71
USC00519523 2014-02-13 00:00:00 0.0 65
USC00519523 2014-02-14 00:00:00 0.0 73
USC00519523 2014-02-15 00:00:00 0.4 73
USC00519523 2014-02-16 00:00:00 0.03 72
USC00519523 2014-02-17 00:00:00 0.33 74
USC00519523 2014-02-18 00:00:00 0.14 71
USC00519523 2014-02-19 00:00:00 0.0 69
USC00519523 2014-02-20 00:00:00 0.0 71
USC00519523 2014-02-21 00:00:00 0.34 68
USC00519523 2014-02-22 00:00:00 0.0 72
USC00519523 2014-02-23 00:00:00 0.0 69
USC00519523 2014-02-24 00:00:00 0.0 72
USC00519523 2014-02-25 00:00:00 0.05 67
USC00519523 2014-02-26 00:00:00 0.14 62
USC00519523 2014-02-27 00:00:00 0.13 68
USC00519523 2014-02-28 00:00:00 0.21 73
USC00519523 2014-03-01 00:00:00 0.24 72
USC00519523 2014-03-04 00:00:00 0.03 66
USC00519523 2014-03-05 00:00:00 0.0 63
USC00519523 2014-03-06 00:00:00 0.0 62
USC00519523 2014-03-07 00:00:00 0.33 69
USC00519523 2014-03-08 00:00:00 0.91 67
USC00519523 2014-03-09 00:00:00 0.44 72
USC00519523 2014-03-10 00:00:00 0.03 73
USC00519523 2014-03-11 00:00:00 0.0 71
USC00519523 2014-03-12 00:00:00 0.0 71
USC00519523 2014-03-13 00:00:00 0.0 73
USC00519523 2014-03-14 00:00:00 0.0 73
USC00519523 2014-03-15 00:00:00 0.58 69
USC00519523 2014-03-16 00:00:00 0.08 69
USC00519523 2014-03-17 00:00:00 0.03 67
USC00519523 2014-03-18 00:00:00 0.03 69
USC00519523 2014-03-19 00:00:00 0.0 70
USC00519523 2014-03-20 00:00:00 0.0 76
USC00519523 2014-03-21 00:00:00 0.0 72
USC00519523 2014-03-22 00:00:00 0.03 70
USC00519523 2014-03-23 00:00:00 0.0 72
USC00519523 2014-03-24 00:00:00 0.0 73
USC00519523 2014-03-25 00:00:00 0.11 70
USC00519523 2014-03-26 00:00:00 0.41 77
USC00519523 2014-03-27 00:00:00 0.18 69
USC00519523 2014-03-28 00:00:00 0.0 73
USC00519523 2014-03-29 00:00:00 0.95 74
USC00519523 2014-03-30 00:00:00 0.37 76
USC00519523 2014-03-31 00:00:00 0.07 73
USC00519523 2014-04-01 00:00:00 0.0 75
USC00519523 2014-04-02 00:00:00 0.02 74
USC00519523 2014-04-03 00:00:00 0.1 76
USC00519523 2014-04-04 00:00:00 0.0 77
USC00519523 2014-04-05 00:00:00 0.0 74
USC00519523 2014-04-06 00:00:00 0.0 67
USC00519523 2014-04-07 00:00:00 0.2 70
USC00519523 2014-04-08 00:00:00 0.23 70
USC00519523 2014-04-11 00:00:00 0.01 68
USC00519523 2014-04-12 00:00:00 0.17 71
USC00519523 2014-04-13 00:00:00 0.01 73
USC00519523 2014-04-14 00:00:00 0.02 73
USC00519523 2014-04-15 00:00:00 0.05 72
USC00519523 2014-04-16 00:00:00 0.15 73
USC00519523 2014-04-17 00:00:00 0.0 74
USC00519523 2014-04-18 00:00:00 0.0 75
USC00519523 2014-04-19 00:00:00 0.09 75
USC00519523 2014-04-20 00:00:00 0.0 73
USC00519523 2014-04-21 00:00:00 0.21 73
USC00519523 2014-04-22 00:00:00 0.13 74
USC00519523 2014-04-25 00:00:00 0.0 73
USC00519523 2014-04-26 00:00:00 0.0 74
USC00519523 2014-04-27 00:00:00 0.3 76
USC00519523 2014-04-28 00:00:00 0.04 71
USC00519523 2014-04-29 00:00:00 0.0 72
USC00519523 2014-05-01 00:00:00 0.0 73
USC00519523 2014-05-02 00:00:00 0.09 73
USC00519523 2014-05-03 00:00:00 0.03 71
USC00519523 2014-05-04 00:00:00 0.0 77
USC00519523 2014-05-10 00:00:00 0.0 75
USC00519523 2014-05-11 00:00:00 0.0 77
USC00519523 2014-05-12 00:00:00 0.55 74
USC00519523 2014-05-13 00:00:00 0.0 73
USC00519523 2014-05-14 00:00:00 0.0 75
USC00519523 2014-05-15 00:00:00 0.0 79
USC00519523 2014-05-16 00:00:00 0.34 73
USC00519523 2014-05-17 00:00:00 0.0 79
USC00519523 2014-05-18 00:00:00 0.0 72
USC00519523 2014-05-19 00:00:00 0.0 75
USC00519523 2014-05-20 00:00:00 0.01 73
USC00519523 2014-05-21 00:00:00 0.0 73
USC00519523 2014-05-22 00:00:00 0.0 76
USC00519523 2014-05-23 00:00:00 0.0 76
USC00519523 2014-05-24 00:00:00 0.14 77
USC00519523 2014-05-25 00:00:00 0.45 73
USC00519523 2014-05-26 00:00:00 0.01 74
USC00519523 2014-05-29 00:00:00 0.0 76
USC00519523 2014-05-30 00:00:00 0.07 76
USC00519523 2014-05-31 00:00:00 0.0 77
USC00519523 2014-06-01 00:00:00 0.0 78
USC00519523 2014-06-02 00:00:00 0.1 76
USC00519523 2014-06-05 00:00:00 0.0 76
USC00519523 2014-06-06 00:00:00 0.0 77
USC00519523 2014-06-07 00:00:00 0.0 79
USC00519523 2014-06-08 00:00:00 0.0 80
USC00519523 2014-06-09 00:00:00 0.0 78
USC00519523 2014-06-10 00:00:00 0.0 76
USC00519523 2014-06-11 00:00:00 0.13 78
USC00519523 2014-06-12 00:00:00 0.0 78
USC00519523 2014-06-13 00:00:00 0.0 77
USC00519523 2014-06-14 00:00:00 0.0 79
USC00519523 2014-06-15 00:00:00 0.0 79
USC00519523 2014-06-16 00:00:00 0.0 75
USC00519523 2014-06-19 00:00:00 0.0 77
USC00519523 2014-06-20 00:00:00 0.51 74
USC00519523 2014-06-21 00:00:00 0.0 77
USC00519523 2014-06-22 00:00:00 0.01 76
USC00519523 2014-06-23 00:00:00 0.23 76
USC00519523 2014-06-24 00:00:00 0.01 75
USC00519523 2014-06-25 00:00:00 0.07 74
USC00519523 2014-06-26 00:00:00 0.1 79
USC00519523 2014-06-29 00:00:00 0.01 74
USC00519523 2014-06-30 00:00:00 0.07 76
USC00519523 2014-07-01 00:00:00 0.0 79

USC00519523 2014-07-02 00:00:00 0.0 82
USC00519523 2014-07-03 00:00:00 0.1 76
USC00519523 2014-07-04 00:00:00 0.0 80
USC00519523 2014-07-05 00:00:00 0.05 74
USC00519523 2014-07-06 00:00:00 0.07 77
USC00519523 2014-07-07 00:00:00 0.1 77
USC00519523 2014-07-08 00:00:00 0.0 77
USC00519523 2014-07-09 00:00:00 0.07 74
USC00519523 2014-07-10 00:00:00 0.0 81
USC00519523 2014-07-11 00:00:00 0.0 81
USC00519523 2014-07-12 00:00:00 0.0 81
USC00519523 2014-07-13 00:00:00 0.06 81
USC00519523 2014-07-14 00:00:00 0.0 80
USC00519523 2014-07-15 00:00:00 0.0 77
USC00519523 2014-07-16 00:00:00 0.1 76
USC00519523 2014-07-17 00:00:00 0.0 77
USC00519523 2014-07-18 00:00:00 0.0 78
USC00519523 2014-07-19 00:00:00 0.0 78
USC00519523 2014-07-20 00:00:00 5.54 76
USC00519523 2014-07-21 00:00:00 0.07 79
USC00519523 2014-07-22 00:00:00 0.41 78
USC00519523 2014-07-23 00:00:00 0.0 78
USC00519523 2014-07-24 00:00:00 0.0 80
USC00519523 2014-07-28 00:00:00 0.0 78
USC00519523 2014-08-01 00:00:00 0.0 83
USC00519523 2014-08-02 00:00:00 0.0 81
USC00519523 2014-08-03 00:00:00 0.0 80
USC00519523 2014-08-04 00:00:00 0.0 80
USC00519523 2014-08-05 00:00:00 0.0 78
USC00519523 2014-08-06 00:00:00 0.36 78
USC00519523 2014-08-09 00:00:00 0.12 81
USC00519523 2014-08-12 00:00:00 0.0 76
USC00519523 2014-08-13 00:00:00 0.27 76
USC00519523 2014-08-14 00:00:00 0.0 80
USC00519523 2014-08-15 00:00:00 0.0 80
USC00519523 2014-08-16 00:00:00 0.15 82
USC00519523 2014-08-17 00:00:00 0.05 75
USC00519523 2014-08-18 00:00:00 0.01 81
USC00519523 2014-08-19 00:00:00 0.0 81
USC00519523 2014-08-20 00:00:00 0.0 77
USC00519523 2014-08-21 00:00:00 0.17 80
USC00519523 2014-08-22 00:00:00 0.02 77
USC00519523 2014-08-25 00:00:00 0.0 78
USC00519523 2014-08-26 00:00:00 0.19 75
USC00519523 2014-08-27 00:00:00 0.02 80
USC00519523 2014-08-28 00:00:00 0.03 80
USC00519523 2014-08-29 00:00:00 0.0 78
USC00519523 2014-08-30 00:00:00 0.17 76
USC00519523 2014-08-31 00:00:00 0.0 79
USC00519523 2014-09-01 00:00:00 0.0 80
USC00519523 2014-09-02 00:00:00 0.39 79
USC00519523 2014-09-03 00:00:00 0.0 82
USC00519523 2014-09-04 00:00:00 0.04 74
USC00519523 2014-09-05 00:00:00 0.09 76
USC00519523 2014-09-06 00:00:00 0.22 77
USC00519523 2014-09-07 00:00:00 0.0 80
USC00519523 2014-09-08 00:00:00 0.0 78
USC00519523 2014-09-09 00:00:00 0.0 78
USC00519523 2014-09-10 00:00:00 0.0 79
USC00519523 2014-09-11 00:00:00 0.0 81
USC00519523 2014-09-12 00:00:00 0.0 80
USC00519523 2014-09-13 00:00:00 0.0 78
USC00519523 2014-09-14 00:00:00 0.0 80
USC00519523 2014-09-15 00:00:00 0.3 76
USC00519523 2014-09-16 00:00:00 0.0 76
USC00519523 2014-09-17 00:00:00 0.19 76
USC00519523 2014-09-18 00:00:00 0.39 75
USC00519523 2014-09-25 00:00:00 0.08 79
USC00519523 2014-09-26 00:00:00 0.17 81
USC00519523 2014-09-27 00:00:00 0.08 79
USC00519523 2014-09-28 00:00:00 0.0 82
USC00519523 2014-09-29 00:00:00 0.36 76
USC00519523 2014-09-30 00:00:00 0.04 73
USC00519523 2014-10-01 00:00:00 0.87 75
USC00519523 2014-10-02 00:00:00 0.02 75
USC00519523 2014-10-03 00:00:00 0.0 80
USC00519523 2014-10-04 00:00:00 0.0 79
USC00519523 2014-10-05 00:00:00 0.26 71
USC00519523 2014-10-06 00:00:00 0.2 73
USC00519523 2014-10-07 00:00:00 0.0 74
USC00519523 2014-10-08 00:00:00 0.04 75
USC00519523 2014-10-11 00:00:00 0.0 81
USC00519523 2014-10-12 00:00:00 0.0 79
USC00519523 2014-10-13 00:00:00 0.0 81
USC00519523 2014-10-14 00:00:00 0.0 79
USC00519523 2014-10-15 00:00:00 0.0 79
USC00519523 2014-10-16 00:00:00 0.0 79
USC00519523 2014-10-17 00:00:00 0.04 77
USC00519523 2014-10-18 00:00:00 0.1 81
USC00519523 2014-10-19 00:00:00 2.61 77
USC00519523 2014-10-20 00:00:00 1.38 79
USC00519523 2014-10-21 00:00:00 0.0 80
USC00519523 2014-10-22 00:00:00 0.04 78
USC00519523 2014-10-23 00:00:00 0.6 82
USC00519523 2014-10-24 00:00:00 0.03 79
USC00519523 2014-10-28 00:00:00 0.0 77
USC00519523 2014-10-29 00:00:00 0.1 77
USC00519523 2014-10-30 00:00:00 0.0 77
USC00519523 2014-10-31 00:00:00 0.0 75
USC00519523 2014-11-01 00:00:00 0.09 79
USC00519523 2014-11-02 00:00:00 0.05 78
USC00519523 2014-11-03 00:00:00 0.01 78
USC00519523 2014-11-04 00:00:00 0.0 77
USC00519523 2014-11-05 00:00:00 0.07 76
USC00519523 2014-11-08 00:00:00 0.9 73
USC00519523 2014-11-09 00:00:00 0.02 71
USC00519523 2014-11-10 00:00:00 0.0 65
USC00519523 2014-11-11 00:00:00 0.0 75
USC00519523 2014-11-12 00:00:00 0.0 67
USC00519523 2014-11-13 00:00:00 0.0 74
USC00519523 2014-11-14 00:00:00 0.0 70
USC00519523 2014-11-15 00:00:00 0.65 76
USC00519523 2014-11-16 00:00:00 0.36 73
USC00519523 2014-11-17 00:00:00 0.01 75
USC00519523 2014-11-21 00:00:00 0.0 76
USC00519523 2014-11-22 00:00:00 0.0 74
USC00519523 2014-11-23 00:00:00 0.0 69
USC00519523 2014-11-24 00:00:00 0.1 71
USC00519523 2014-11-27 00:00:00 0.0 74
USC00519523 2014-11-28 00:00:00 0.0 75
USC00519523 2014-11-29 00:00:00 0.01 75
USC00519523 2014-11-30 00:00:00 0.0 75
USC00519523 2014-12-01 00:00:00 0.0 72
USC00519523 2014-12-02 00:00:00 0.0 72
USC00519523 2014-12-03 00:00:00 0.02 73
USC00519523 2014-12-04 00:00:00 1.02 72
USC00519523 2014-12-05 00:00:00 0.0 75
USC00519523 2014-12-06 00:00:00 0.0 76
USC00519523 2014-12-07 00:00:00 0.0 67
USC00519523 2014-12-08 00:00:00 0.0 69
USC00519523 2014-12-09 00:00:00 0.0 70
USC00519523 2014-12-10 00:00:00 0.0 75
USC00519523 2014-12-11 00:00:00 0.16 74
USC00519523 2014-12-12 00:00:00 0.08 71
USC00519523 2014-12-13 00:00:00 0.11 74
USC00519523 2014-12-14 00:00:00 0.2 71
USC00519523 2014-12-15 00:00:00 0.05 72
USC00519523 2014-12-16 00:00:00 0.05 74
USC00519523 2014-12-17 00:00:00 0.09 75
USC00519523 2014-12-18 00:00:00 0.0 73
USC00519523 2014-12-19 00:00:00 0.0 75
USC00519523 2014-12-20 00:00:00 0.0 76
USC00519523 2014-12-23 00:00:00 1.52 71
USC00519523 2014-12-24 00:00:00 1.01 68
USC00519523 2014-12-25 00:00:00 0.53 66
USC00519523 2014-12-26 00:00:00 0.0 63
USC00519523 2014-12-27 00:00:00 0.0 62
USC00519523 2014-12-28 00:00:00 0.0 67
USC00519523 2014-12-29 00:00:00 0.0 68
USC00519523 2014-12-30 00:00:00 0.0 63
USC00519523 2014-12-31 00:00:00 0.63 56
USC00519523 2015-01-01 00:00:00 0.0 65
USC00519523 2015-01-02 00:00:00 0.0 68
USC00519523 2015-01-03 00:00:00 1.23 69
USC00519523 2015-01-04 00:00:00 0.03 72
USC00519523 2015-01-05 00:00:00 0.0 61
USC00519523 2015-01-06 00:00:00 0.0 68
USC00519523 2015-01-07 00:00:00 0.0 69
USC00519523 2015-01-08 00:00:00 0.0 67
USC00519523 2015-01-09 00:00:00 0.0 69
USC00519523 2015-01-10 00:00:00 0.0 74
USC00519523 2015-01-11 00:00:00 0.0 72
USC00519523 2015-01-12 00:00:00 0.0 64
USC00519523 2015-01-13 00:00:00 0.0 65
USC00519523 2015-01-14 00:00:00 0.0 67
USC00519523 2015-01-15 00:00:00 0.0 74
USC00519523 2015-01-16 00:00:00 0.01 74
USC00519523 2015-01-17 00:00:00 0.0 74
USC00519523 2015-01-18 00:00:00 0.0 67
USC00519523 2015-01-19 00:00:00 0.0 69
USC00519523 2015-01-20 00:00:00 0.0 64
USC00519523 2015-01-21 00:00:00 0.0 65
USC00519523 2015-01-22 00:00:00 0.0 64
USC00519523 2015-01-23 00:00:00 0.0 73
USC00519523 2015-01-24 00:00:00 0.47 72
USC00519523 2015-01-25 00:00:00 0.59 67
USC00519523 2015-01-26 00:00:00 0.19 71
USC00519523 2015-01-27 00:00:00 0.0 72
USC00519523 2015-01-28 00:00:00 0.1 69
USC00519523 2015-01-29 00:00:00 0.0 73
USC00519523 2015-01-30 00:00:00 0.01 63
USC00519523 2015-01-31 00:00:00 0.0 66
USC00519523 2015-02-01 00:00:00 0.04 66
USC00519523 2015-02-02 00:00:00 0.0 76
USC00519523 2015-02-05 00:00:00 0.05 70
USC00519523 2015-02-06 00:00:00 0.0 67
USC00519523 2015-02-07 00:00:00 0.0 69
USC00519523 2015-02-08 00:00:00 0.0 69
USC00519523 2015-02-09 00:00:00 0.0 72
USC00519523 2015-02-10 00:00:00 0.15 71
USC00519523 2015-02-11 00:00:00 0.0 64
USC00519523 2015-02-12 00:00:00 0.0 62
USC00519523 2015-02-13 00:00:00 0.0 74
USC00519523 2015-02-14 00:00:00 0.22 74
USC00519523 2015-02-15 00:00:00 0.97 67
USC00519523 2015-02-16 00:00:00 0.01 69
USC00519523 2015-02-17 00:00:00 0.0 69
USC00519523 2015-02-18 00:00:00 0.0 71
USC00519523 2015-02-21 00:00:00 0.73 73
USC00519523 2015-02-22 00:00:00 0.0 75
USC00519523 2015-02-23 00:00:00 0.0 73
USC00519523 2015-02-24 00:00:00 0.0 74
USC00519523 2015-02-25 00:00:00 0.0 73
USC00519523 2015-02-26 00:00:00 0.03 71
USC00519523 2015-02-27 00:00:00 0.0 72
USC00519523 2015-02-28 00:00:00 1.08 71
USC00519523 2015-03-01 00:00:00 0.02 72
USC00519523 2015-03-02 00:00:00 0.11 72
USC00519523 2015-03-03 00:00:00 0.01 73
USC00519523 2015-03-04 00:00:00 0.01 72
USC00519523 2015-03-05 00:00:00 0.16 71
USC00519523 2015-03-06 00:00:00 0.1 68
USC00519523 2015-03-07 00:00:00 0.01 69
USC00519523 2015-03-08 00:00:00 0.0 69
USC00519523 2015-03-09 00:00:00 0.03 63
USC00519523 2015-03-10 00:00:00 0.01 65
USC00519523 2015-03-11 00:00:00 0.0 72
USC00519523 2015-03-14 00:00:00 0.0 68
USC00519523 2015-03-15 00:00:00 0.0 67
USC00519523 2015-03-16 00:00:00 0.0 61
USC00519523 2015-03-17 00:00:00 0.0 66
USC00519523 2015-03-18 00:00:00 0.0 60
USC00519523 2015-03-19 00:00:00 0.0 65
USC00519523 2015-03-20 00:00:00 0.0 72
USC00519523 2015-03-21 00:00:00 0.12 75
USC00519523 2015-03-22 00:00:00 0.1 74
USC00519523 2015-03-23 00:00:00 0.0 73
USC00519523 2015-03-26 00:00:00 0.0 70
USC00519523 2015-03-27 00:00:00 0.0 74
USC00519523 2015-03-28 00:00:00 0.0 74
USC00519523 2015-03-29 00:00:00 1.94 75
USC00519523 2015-03-30 00:00:00 0.02 76
USC00519523 2015-03-31 00:00:00 0.15 72
USC00519523 2015-04-01 00:00:00 0.25 78
USC00519523 2015-04-02 00:00:00 0.0 77
USC00519523 2015-04-03 00:00:00 0.0 77
USC00519523 2015-04-04 00:00:00 0.0 77
USC00519523 2015-04-05 00:00:00 0.0 80
USC00519523 2015-04-06 00:00:00 0.0 73
USC00519523 2015-04-07 00:00:00 0.0 75
USC00519523 2015-04-08 00:00:00 0.02 73
USC00519523 2015-04-09 00:00:00 0.0 73
USC00519523 2015-04-12 00:00:00 0.0 76
USC00519523 2015-04-13 00:00:00 0.0 76
USC00519523 2015-04-14 00:00:00 0.07 74
USC00519523 2015-04-15 00:00:00 0.02 76
USC00519523 2015-04-16 00:00:00 0.0 74
USC00519523 2015-04-17 00:00:00 0.07 75
USC00519523 2015-04-18 00:00:00 0.0 76
USC00519523 2015-04-19 00:00:00 0.03 74
USC00519523 2015-04-20 00:00:00 0.0 74
USC00519523 2015-04-21 00:00:00 0.0 76
USC00519523 2015-04-22 00:00:00 0.0 69
USC00519523 2015-04-23 00:00:00 0.15 75
USC00519523 2015-04-24 00:00:00 0.25 75
USC00519523 2015-04-25 00:00:00 0.05 81
USC00519523 2015-04-26 00:00:00 0.02 81
USC00519523 2015-04-27 00:00:00 3.62 73
USC00519523 2015-04-30 00:00:00 0.0 75
USC00519523 2015-05-01 00:00:00 0.05 75
USC00519523 2015-05-02 00:00:00 0.0 75
USC00519523 2015-05-03 00:00:00 0.0 74
USC00519523 2015-05-04 00:00:00 0.0 75
USC00519523 2015-05-05 00:00:00 0.0 75
USC00519523 2015-05-06 00:00:00 0.0 75
USC00519523 2015-05-07 00:00:00 0.0 77
USC00519523 2015-05-08 00:00:00 0.13 72
USC00519523 2015-05-09 00:00:00 0.0 75
USC00519523 2015-05-10 00:00:00 0.0 78
USC00519523 2015-05-11 00:00:00 0.0 74
USC00519523 2015-05-12 00:00:00 0.0 74
USC00519523 2015-05-13 00:00:00 0.0 77
USC00519523 2015-05-14 00:00:00 0.0 74
USC00519523 2015-05-15 00:00:00 0.0 74
USC00519523 2015-05-16 00:00:00 0.0 76
USC00519523 2015-05-17 00:00:00 0.0 78
USC00519523 2015-05-18 00:00:00 0.0 78
USC00519523 2015-05-19 00:00:00 0.0 77
USC00519523 2015-05-20 00:00:00 0.0 73
USC00519523 2015-05-21 00:00:00 0.17 72
USC00519523 2015-05-22 00:00:00 0.0 71
USC00519523 2015-05-23 00:00:00 1.32 75
USC00519523 2015-05-24 00:00:00 0.0 72
USC00519523 2015-05-25 00:00:00 0.0 73
USC00519523 2015-05-26 00:00:00 0.0 73
USC00519523 2015-05-27 00:00:00 0.13 71
USC00519523 2015-05-28 00:00:00 0.68 73
USC00519523 2015-05-29 00:00:00 0.0 72
USC00519523 2015-05-30 00:00:00 0.01 73
USC00519523 2015-05-31 00:00:00 0.0 76
USC00519523 2015-06-01 00:00:00 0.13 77
USC00519523 2015-06-02 00:00:00 0.0 78
USC00519523 2015-06-03 00:00:00 0.0 77
USC00519523 2015-06-04 00:00:00 0.07 75
USC00519523 2015-06-05 00:00:00 0.01 75
USC00519523 2015-06-06 00:00:00 0.0 80
USC00519523 2015-06-07 00:00:00 0.0 77
USC00519523 2015-06-08 00:00:00 0.01 77
USC00519523 2015-06-09 00:00:00 0.01 77
USC00519523 2015-06-10 00:00:00 0.0 80
USC00519523 2015-06-11 00:00:00 0.0 76
USC00519523 2015-06-12 00:00:00 0.0 78
USC00519523 2015-06-13 00:00:00 0.0 77
USC00519523 2015-06-14 00:00:00 0.0 79
USC00519523 2015-06-15 00:00:00 0.0 79
USC00519523 2015-06-16 00:00:00 0.0 77
USC00519523 2015-06-17 00:00:00 0.05 75
USC00519523 2015-06-18 00:00:00 0.18 76
USC00519523 2015-06-19 00:00:00 0.0 78
USC00519523 2015-06-20 00:00:00 0.0 78
USC00519523 2015-06-21 00:00:00 0.0 80
USC00519523 2015-06-22 00:00:00 0.0 78
USC00519523 2015-06-23 00:00:00 0.05 79
USC00519523 2015-06-24 00:00:00 0.0 79
USC00519523 2015-06-25 00:00:00 0.14 77
USC00519523 2015-06-26 00:00:00 0.0 77
USC00519523 2015-06-27 00:00:00 0.0 81
USC00519523 2015-06-30 00:00:00 0.0 72
USC00519523 2015-07-01 00:00:00 0.0 71
USC00519523 2015-07-02 00:00:00 0.0 80
USC00519523 2015-07-07 00:00:00 0.0 82
USC00519523 2015-07-08 00:00:00 0.26 79
USC00519523 2015-07-09 00:00:00 0.0 79
USC00519523 2015-07-10 00:00:00 0.3 78
USC00519523 2015-07-11 00:00:00 0.22 77
USC00519523 2015-07-12 00:00:00 0.43 78
USC00519523 2015-07-13 00:00:00 0.06 78
USC00519523 2015-07-14 00:00:00 0.05 78
USC00519523 2015-07-15 00:00:00 0.0 78
USC00519523 2015-07-16 00:00:00 0.0 78
USC00519523 2015-07-17 00:00:00 0.13 79
USC00519523 2015-07-18 00:00:00 0.0 80
USC00519523 2015-07-19 00:00:00 0.11 82
USC00519523 2015-07-20 00:00:00 0.0 80
USC00519523 2015-07-21 00:00:00 0.0 83
USC00519523 2015-07-24 00:00:00 0.18 78
USC00519523 2015-07-25 00:00:00 0.0 79
USC00519523 2015-07-26 00:00:00 0.03 77
USC00519523 2015-07-27 00:00:00 0.0 80
USC00519523 2015-07-28 00:00:00 0.0 80
USC00519523 2015-07-29 00:00:00 0.0 81
USC00519523 2015-07-30 00:00:00 0.0 82
USC00519523 2015-07-31 00:00:00 0.0 79
USC00519523 2015-08-01 00:00:00 0.16 79
USC00519523 2015-08-02 00:00:00 0.01 84
USC00519523 2015-08-03 00:00:00 0.0 79
USC00519523 2015-08-04 00:00:00 0.0 78
USC00519523 2015-08-05 00:00:00 0.1 81
USC00519523 2015-08-06 00:00:00 0.13 80
USC00519523 2015-08-07 00:00:00 0.0 82
USC00519523 2015-08-08 00:00:00 0.0 82
USC00519523 2015-08-09 00:00:00 0.09 77
USC00519523 2015-08-10 00:00:00 0.01 80
USC00519523 2015-08-11 00:00:00 0.0 81
USC00519523 2015-08-12 00:00:00 0.0 81
USC00519523 2015-08-13 00:00:00 0.06 83
USC00519523 2015-08-14 00:00:00 0.0 80
USC00519523 2015-08-15 00:00:00 0.0 81
USC00519523 2015-08-16 00:00:00 0.0 81
USC00519523 2015-08-17 00:00:00 0.12 75
USC00519523 2015-08-18 00:00:00 1.14 76
USC00519523 2015-08-19 00:00:00 0.42 75
USC00519523 2015-08-20 00:00:00 1.05 75
USC00519523 2015-08-23 00:00:00 0.07 81
USC00519523 2015-08-24 00:00:00 3.43 74
USC00519523 2015-08-25 00:00:00 0.12 80
USC00519523 2015-08-26 00:00:00 0.5 76
USC00519523 2015-08-27 00:00:00 2.29 76
USC00519523 2015-08-28 00:00:00 0.12 79
USC00519523 2015-08-29 00:00:00 0.0 82
USC00519523 2015-08-30 00:00:00 0.02 80
USC00519523 2015-08-31 00:00:00 0.0 80
USC00519523 2015-09-01 00:00:00 0.09 79
USC00519523 2015-09-04 00:00:00 0.81 84
USC00519523 2015-09-07 00:00:00 0.48 80

USC00519523 2015-09-08 00:00:00 1.16 77
USC00519523 2015-09-09 00:00:00 0.0 74
USC00519523 2015-09-10 00:00:00 0.0 80
USC00519523 2015-09-11 00:00:00 0.55 82
USC00519523 2015-09-12 00:00:00 2.28 83
USC00519523 2015-09-13 00:00:00 0.07 80
USC00519523 2015-09-14 00:00:00 0.31 77
USC00519523 2015-09-15 00:00:00 1.17 77
USC00519523 2015-09-16 00:00:00 0.01 80
USC00519523 2015-09-17 00:00:00 0.0 80
USC00519523 2015-09-18 00:00:00 0.0 81
USC00519523 2015-09-19 00:00:00 0.0 81
USC00519523 2015-09-20 00:00:00 0.0 82
USC00519523 2015-09-21 00:00:00 0.01 80
USC00519523 2015-09-22 00:00:00 0.11 80
USC00519523 2015-09-23 00:00:00 0.03 79
USC00519523 2015-09-24 00:00:00 0.08 78
USC00519523 2015-09-25 00:00:00 0.05 78
USC00519523 2015-09-26 00:00:00 0.01 80
USC00519523 2015-09-27 00:00:00 0.18 76
USC00519523 2015-09-28 00:00:00 0.14 78
USC00519523 2015-09-29 00:00:00 0.01 78
USC00519523 2015-10-03 00:00:00 0.0 79
USC00519523 2015-10-04 00:00:00 0.0 78
USC00519523 2015-10-05 00:00:00 0.65 76
USC00519523 2015-10-06 00:00:00 0.55 77
USC00519523 2015-10-07 00:00:00 0.12 73
USC00519523 2015-10-08 00:00:00 0.0 72
USC00519523 2015-10-09 00:00:00 0.01 76
USC00519523 2015-10-12 00:00:00 0.56 76
USC00519523 2015-10-13 00:00:00 2.24 76
USC00519523 2015-10-14 00:00:00 1.42 75
USC00519523 2015-10-15 00:00:00 0.75 74
USC00519523 2015-10-16 00:00:00 0.11 75
USC00519523 2015-10-17 00:00:00 0.15 79
USC00519523 2015-10-18 00:00:00 0.05 81
USC00519523 2015-10-21 00:00:00 0.25 75
USC00519523 2015-10-22 00:00:00 0.07 76
USC00519523 2015-10-23 00:00:00 0.0 74
USC00519523 2015-10-24 00:00:00 0.0 77
USC00519523 2015-10-25 00:00:00 0.0 69
USC00519523 2015-10-26 00:00:00 0.01 77
USC00519523 2015-10-27 00:00:00 0.33 77
USC00519523 2015-10-28 00:00:00 0.0 75
USC00519523 2015-10-29 00:00:00 0.64 70
USC00519523 2015-10-30 00:00:00 0.11 73
USC00519523 2015-10-31 00:00:00 0.04 80
USC00519523 2015-11-01 00:00:00 0.17 81
USC00519523 2015-11-02 00:00:00 0.0 74
USC00519523 2015-11-03 00:00:00 0.0 78
USC00519523 2015-11-04 00:00:00 0.13 76
USC00519523 2015-11-05 00:00:00 0.15 76
USC00519523 2015-11-06 00:00:00 0.0 77
USC00519523 2015-11-07 00:00:00 0.21 76
USC00519523 2015-11-08 00:00:00 0.05 81
USC00519523 2015-11-09 00:00:00 0.07 77
USC00519523 2015-11-12 00:00:00 0.03 80
USC00519523 2015-11-13 00:00:00 0.1 76
USC00519523 2015-11-14 00:00:00 0.12 77
USC00519523 2015-11-15 00:00:00 0.0 76
USC00519523 2015-11-16 00:00:00 0.0 77
USC00519523 2015-11-17 00:00:00 0.0 68
USC00519523 2015-11-18 00:00:00 0.23 74
USC00519523 2015-11-19 00:00:00 0.07 76
USC00519523 2015-11-20 00:00:00 1.75 73
USC00519523 2015-11-21 00:00:00 2.3 79
USC00519523 2015-11-22 00:00:00 1.84 76
USC00519523 2015-11-23 00:00:00 1.1 75
USC00519523 2015-11-24 00:00:00 1.12 73
USC00519523 2015-11-25 00:00:00 0.13 73
USC00519523 2015-11-26 00:00:00 0.58 76
USC00519523 2015-11-27 00:00:00 0.49 76
USC00519523 2015-11-28 00:00:00 0.02 78
USC00519523 2015-11-29 00:00:00 0.14 79
USC00519523 2015-11-30 00:00:00 0.01 76
USC00519523 2015-12-03 00:00:00 0.03 75
USC00519523 2015-12-04 00:00:00 0.0 74
USC00519523 2015-12-05 00:00:00 0.0 76
USC00519523 2015-12-08 00:00:00 0.04 71
USC00519523 2015-12-09 00:00:00 0.13 72
USC00519523 2015-12-10 00:00:00 0.14 74
USC00519523 2015-12-11 00:00:00 0.06 75
USC00519523 2015-12-12 00:00:00 0.41 72
USC00519523 2015-12-13 00:00:00 0.01 78
USC00519523 2015-12-14 00:00:00 0.03 69
USC00519523 2015-12-15 00:00:00 0.28 75
USC00519523 2015-12-16 00:00:00 0.0 75
USC00519523 2015-12-17 00:00:00 0.06 74
USC00519523 2015-12-18 00:00:00 0.12 74
USC00519523 2015-12-19 00:00:00 0.24 76
USC00519523 2015-12-20 00:00:00 0.04 73
USC00519523 2015-12-23 00:00:00 0.0 75
USC00519523 2015-12-24 00:00:00 0.0 74
USC00519523 2015-12-25 00:00:00 0.23 79
USC00519523 2015-12-26 00:00:00 0.15 75
USC00519523 2015-12-27 00:00:00 0.48 76
USC00519523 2015-12-28 00:00:00 0.05 76
USC00519523 2015-12-29 00:00:00 0.01 69
USC00519523 2016-01-01 00:00:00 0.0 64
USC00519523 2016-01-02 00:00:00 0.13 73
USC00519523 2016-01-03 00:00:00 0.0 69
USC00519523 2016-01-06 00:00:00 0.0 74
USC00519523 2016-01-07 00:00:00 0.0 68
USC00519523 2016-01-08 00:00:00 0.0 65
USC00519523 2016-01-09 00:00:00 0.0 77
USC00519523 2016-01-10 00:00:00 0.0 71
USC00519523 2016-01-11 00:00:00 0.0 66
USC00519523 2016-01-12 00:00:00 0.0 68
USC00519523 2016-01-13 00:00:00 0.0 64
USC00519523 2016-01-14 00:00:00 0.0 62
USC00519523 2016-01-15 00:00:00 0.0 67
USC00519523 2016-01-16 00:00:00 0.0 69
USC00519523 2016-01-17 00:00:00 0.0 67
USC00519523 2016-01-18 00:00:00 0.0 71
USC00519523 2016-01-21 00:00:00 0.39 70
USC00519523 2016-01-22 00:00:00 0.0 67
USC00519523 2016-01-25 00:00:00 0.24 70
USC00519523 2016-01-26 00:00:00 0.0 67
USC00519523 2016-01-31 00:00:00 0.0 73
USC00519523 2016-02-01 00:00:00 0.0 69
USC00519523 2016-02-02 00:00:00 0.39 70
USC00519523 2016-02-03 00:00:00 0.03 73
USC00519523 2016-02-04 00:00:00 0.0 70
USC00519523 2016-02-05 00:00:00 0.0 69
USC00519523 2016-02-08 00:00:00 0.0 61
USC00519523 2016-02-09 00:00:00 0.0 59
USC00519523 2016-02-10 00:00:00 0.0 70
USC00519523 2016-02-11 00:00:00 0.0 73
USC00519523 2016-02-12 00:00:00 0.0 73
USC00519523 2016-02-16 00:00:00 0.04 72
USC00519523 2016-02-17 00:00:00 0.22 72
USC00519523 2016-02-18 00:00:00 0.0 72
USC00519523 2016-02-19 00:00:00 0.2 68
USC00519523 2016-02-20 00:00:00 0.05 65
USC00519523 2016-02-21 00:00:00 0.01 74
USC00519523 2016-02-22 00:00:00 0.0 74
USC00519523 2016-02-23 00:00:00 0.0 63
USC00519523 2016-02-24 00:00:00 0.0 66
USC00519523 2016-02-25 00:00:00 0.0 67
USC00519523 2016-02-26 00:00:00 0.0 71
USC00519523 2016-02-27 00:00:00 0.0 69
USC00519523 2016-02-28 00:00:00 0.0 67
USC00519523 2016-02-29 00:00:00 0.0 67
USC00519523 2016-03-01 00:00:00 0.33 73
USC00519523 2016-03-02 00:00:00 0.0 70
USC00519523 2016-03-03 00:00:00 0.0 68
USC00519523 2016-03-04 00:00:00 0.0 75
USC00519523 2016-03-05 00:00:00 0.0 73
USC00519523 2016-03-06 00:00:00 0.0 69
USC00519523 2016-03-07 00:00:00 0.0 68
USC00519523 2016-03-08 00:00:00 0.02 75
USC00519523 2016-03-09 00:00:00 0.3 68
USC00519523 2016-03-10 00:00:00 0.0 70
USC00519523 2016-03-11 00:00:00 0.0 72
USC00519523 2016-03-12 00:00:00 0.0 72
USC00519523 2016-03-17 00:00:00 0.0 69
USC00519523 2016-03-18 00:00:00 0.0 70
USC00519523 2016-03-22 00:00:00 0.0 69
USC00519523 2016-03-23 00:00:00 1.05 70
USC00519523 2016-03-24 00:00:00 0.0 73
USC00519523 2016-03-25 00:00:00 0.03 75
USC00519523 2016-03-26 00:00:00 0.03 77
USC00519523 2016-03-27 00:00:00 0.0 76
USC00519523 2016-03-28 00:00:00 0.0 73
USC00519523 2016-03-29 00:00:00 0.04 75
USC00519523 2016-03-30 00:00:00 0.0 69
USC00519523 2016-03-31 00:00:00 0.01 69
USC00519523 2016-04-01 00:00:00 0.0 76
USC00519523 2016-04-02 00:00:00 0.0 76
USC00519523 2016-04-03 00:00:00 0.0 78
USC00519523 2016-04-04 00:00:00 0.0 78
USC00519523 2016-04-07 00:00:00 0.0 72
USC00519523 2016-04-08 00:00:00 0.0 75
USC00519523 2016-04-09 00:00:00 0.0 76
USC00519523 2016-04-10 00:00:00 0.0 76
USC00519523 2016-04-11 00:00:00 0.0 75
USC00519523 2016-04-12 00:00:00 0.0 77
USC00519523 2016-04-13 00:00:00 0.18 77
USC00519523 2016-04-14 00:00:00 0.08 77
USC00519523 2016-04-15 00:00:00 0.04 79
USC00519523 2016-04-16 00:00:00 0.0 76
USC00519523 2016-04-17 00:00:00 0.09 72
USC00519523 2016-04-18 00:00:00 0.46 73
USC00519523 2016-04-21 00:00:00 0.0 75
USC00519523 2016-04-22 00:00:00 0.0 77
USC00519523 2016-04-23 00:00:00 0.04 77
USC00519523 2016-04-24 00:00:00 0.29 75
USC00519523 2016-04-25 00:00:00 0.0 79
USC00519523 2016-04-26 00:00:00 0.0 76
USC00519523 2016-04-27 00:00:00 0.0 79
USC00519523 2016-04-28 00:00:00 0.0 79
USC00519523 2016-04-29 00:00:00 0.0 77
USC00519523 2016-04-30 00:00:00 0.0 77
USC00519523 2016-05-01 00:00:00 0.09 78
USC00519523 2016-05-02 00:00:00 0.07 75
USC00519523 2016-05-03 00:00:00 0.0 78
USC00519523 2016-05-04 00:00:00 0.0 75
USC00519523 2016-05-05 00:00:00 0.27 77
USC00519523 2016-05-06 00:00:00 0.0 73
USC00519523 2016-05-07 00:00:00 1.8 71
USC00519523 2016-05-08 00:00:00 0.75 71
USC00519523 2016-05-09 00:00:00 0.02 73
USC00519523 2016-05-10 00:00:00 0.0 74
USC00519523 2016-05-11 00:00:00 0.0 74
USC00519523 2016-05-12 00:00:00 0.0 73
USC00519523 2016-05-13 00:00:00 0.0 75
USC00519523 2016-05-14 00:00:00 0.06 74
USC00519523 2016-05-15 00:00:00 0.0 79
USC00519523 2016-05-16 00:00:00 0.0 78
USC00519523 2016-05-17 00:00:00 0.0 78
USC00519523 2016-05-18 00:00:00 0.0 77
USC00519523 2016-05-19 00:00:00 0.0 77
USC00519523 2016-05-20 00:00:00 0.0 78
USC00519523 2016-05-21 00:00:00 0.0 78
USC00519523 2016-05-22 00:00:00 0.0 78
USC00519523 2016-05-23 00:00:00 0.0 79
USC00519523 2016-05-24 00:00:00 0.0 77
USC00519523 2016-05-25 00:00:00 0.0 77
USC00519523 2016-05-26 00:00:00 0.01 81
USC00519523 2016-05-27 00:00:00 0.0 80
USC00519523 2016-05-28 00:00:00 0.36 79
USC00519523 2016-05-29 00:00:00 0.0 78
USC00519523 2016-05-30 00:00:00 0.05 78
USC00519523 2016-05-31 00:00:00 1.18 71
USC00519523 2016-06-01 00:00:00 0.38 75
USC00519523 2016-06-02 00:00:00 0.03 75
USC00519523 2016-06-03 00:00:00 0.47 75
USC00519523 2016-06-04 00:00:00 0.02 75
USC00519523 2016-06-05 00:00:00 0.14 73
USC00519523 2016-06-06 00:00:00 0.17 78
USC00519523 2016-06-07 00:00:00 0.07 77
USC00519523 2016-06-08 00:00:00 0.0 80
USC00519523 2016-06-09 00:00:00 0.15 72
USC00519523 2016-06-10 00:00:00 0.23 78
USC00519523 2016-06-11 00:00:00 0.0 78
USC00519523 2016-06-12 00:00:00 0.12 77
USC00519523 2016-06-13 00:00:00 0.1 78
USC00519523 2016-06-14 00:00:00 0.0 79
USC00519523 2016-06-15 00:00:00 0.25 80
USC00519523 2016-06-18 00:00:00 0.0 77
USC00519523 2016-06-19 00:00:00 0.06 79
USC00519523 2016-06-20 00:00:00 0.03 79
USC00519523 2016-06-21 00:00:00 0.03 77
USC00519523 2016-06-22 00:00:00 0.0 79
USC00519523 2016-06-23 00:00:00 0.0 80
USC00519523 2016-06-24 00:00:00 0.0 80
USC00519523 2016-06-25 00:00:00 0.21 77
USC00519523 2016-06-26 00:00:00 0.0 79
USC00519523 2016-06-27 00:00:00 0.0 81
USC00519523 2016-06-28 00:00:00 0.0 78
USC00519523 2016-06-29 00:00:00 0.0 80
USC00519523 2016-06-30 00:00:00 0.0 79
USC00519523 2016-07-03 00:00:00 0.17 76
USC00519523 2016-07-04 00:00:00 0.03 81
USC00519523 2016-07-05 00:00:00 0.12 76
USC00519523 2016-07-06 00:00:00 0.1 76
USC00519523 2016-07-07 00:00:00 0.02 80
USC00519523 2016-07-08 00:00:00 0.01 80
USC00519523 2016-07-09 00:00:00 0.0 78
USC00519523 2016-07-10 00:00:00 0.37 78
USC00519523 2016-07-11 00:00:00 0.07 78
USC00519523 2016-07-12 00:00:00 0.0 80
USC00519523 2016-07-15 00:00:00 0.42 80
USC00519523 2016-07-16 00:00:00 0.2 79
USC00519523 2016-07-17 00:00:00 0.0 82
USC00519523 2016-07-18 00:00:00 0.38 76
USC00519523 2016-07-19 00:00:00 0.11 80
USC00519523 2016-07-20 00:00:00 0.02 82
USC00519523 2016-07-21 00:00:00 0.06 80
USC00519523 2016-07-24 00:00:00 0.18 78
USC00519523 2016-07-25 00:00:00 3.01 80
USC00519523 2016-07-26 00:00:00 0.0 80
USC00519523 2016-07-27 00:00:00 0.0 83
USC00519523 2016-07-28 00:00:00 0.0 82
USC00519523 2016-07-29 00:00:00 0.0 82
USC00519523 2016-07-30 00:00:00 0.08 77
USC00519523 2016-07-31 00:00:00 0.79 80
USC00519523 2016-08-01 00:00:00 0.54 77
USC00519523 2016-08-02 00:00:00 0.07 78
USC00519523 2016-08-03 00:00:00 0.0 81
USC00519523 2016-08-04 00:00:00 0.25 80
USC00519523 2016-08-05 00:00:00 0.0 80
USC00519523 2016-08-06 00:00:00 0.04 79
USC00519523 2016-08-07 00:00:00 0.4 79
USC00519523 2016-08-08 00:00:00 0.0 83
USC00519523 2016-08-09 00:00:00 0.01 80
USC00519523 2016-08-10 00:00:00 0.0 82
USC00519523 2016-08-11 00:00:00 0.0 80
USC00519523 2016-08-12 00:00:00 0.0 77
USC00519523 2016-08-13 00:00:00 0.01 81
USC00519523 2016-08-14 00:00:00 0.0 82
USC00519523 2016-08-15 00:00:00 0.0 81
USC00519523 2016-08-16 00:00:00 0.0 80
USC00519523 2016-08-17 00:00:00 0.0 78
USC00519523 2016-08-18 00:00:00 0.0 81
USC00519523 2016-08-19 00:00:00 0.0 79
USC00519523 2016-08-20 00:00:00 0.0 81
USC00519523 2016-08-21 00:00:00 0.41 80
USC00519523 2016-08-22 00:00:00 0.4 80
USC00519523 2016-08-23 00:00:00 0.02 80
USC00519523 2016-08-24 00:00:00 1.22 79
USC00519523 2016-08-25 00:00:00 0.21 80
USC00519523 2016-08-26 00:00:00 0.0 84
USC00519523 2016-08-27 00:00:00 0.0 81
USC00519523 2016-08-28 00:00:00 0.14 80
USC00519523 2016-08-29 00:00:00 0.0 79
USC00519523 2016-08-30 00:00:00 0.0 78
USC00519523 2016-08-31 00:00:00 0.25 78
USC00519523 2016-09-03 00:00:00 0.08 78
USC00519523 2016-09-04 00:00:00 0.74 84
USC00519523 2016-09-05 00:00:00 0.02 84
USC00519523 2016-09-06 00:00:00 0.03 78
USC00519523 2016-09-07 00:00:00 0.11 76
USC00519523 2016-09-08 00:00:00 0.01 79
USC00519523 2016-09-09 00:00:00 0.23 77
USC00519523 2016-09-10 00:00:00 0.14 78
USC00519523 2016-09-11 00:00:00 0.12 83
USC00519523 2016-09-12 00:00:00 0.15 78
USC00519523 2016-09-13 00:00:00 0.46 77
USC00519523 2016-09-14 00:00:00 1.19 77
USC00519523 2016-09-15 00:00:00 0.17 79
USC00519523 2016-09-16 00:00:00 0.01 78
USC00519523 2016-09-17 00:00:00 0.0 81
USC00519523 2016-09-18 00:00:00 0.04 81
USC00519523 2016-09-19 00:00:00 0.05 78
USC00519523 2016-09-20 00:00:00 0.04 77
USC00519523 2016-09-21 00:00:00 0.0 79
USC00519523 2016-09-22 00:00:00 0.01 79
USC00519523 2016-09-23 00:00:00 0.0 80
USC00519523 2016-09-24 00:00:00 0.0 83
USC00519523 2016-09-25 00:00:00 0.0 82
USC00519523 2016-09-26 00:00:00 0.34 78
USC00519523 2016-09-27 00:00:00 0.05 78
USC00519523 2016-09-28 00:00:00 0.0 78
USC00519523 2016-09-29 00:00:00 0.18 82
USC00519523 2016-09-30 00:00:00 0.15 78
USC00519523 2016-10-01 00:00:00 0.07 79
USC00519523 2016-10-02 00:00:00 0.0 81
USC00519523 2016-10-03 00:00:00 0.0 79
USC00519523 2016-10-04 00:00:00 0.0 80
USC00519523 2016-10-05 00:00:00 0.0 80
USC00519523 2016-10-06 00:00:00 0.0 80
USC00519523 2016-10-07 00:00:00 0.0 79
USC00519523 2016-10-08 00:00:00 0.0 82
USC00519523 2016-10-09 00:00:00 0.0 80
USC00519523 2016-10-10 00:00:00 0.0 78
USC00519523 2016-10-11 00:00:00 0.0 81
USC00519523 2016-10-12 00:00:00 0.0 81
USC00519523 2016-10-13 00:00:00 0.0 79
USC00519523 2016-10-14 00:00:00 0.0 80
USC00519523 2016-10-15 00:00:00 0.0 79
USC00519523 2016-10-16 00:00:00 0.0 81
USC00519523 2016-10-17 00:00:00 0.12 80
USC00519523 2016-10-18 00:00:00 0.02 80
USC00519523 2016-10-19 00:00:00 0.0 78
USC00519523 2016-10-22 00:00:00 0.0 80
USC00519523 2016-10-23 00:00:00 0.0 81
USC00519523 2016-10-24 00:00:00 0.0 75
USC00519523 2016-10-25 00:00:00 0.12 77
USC00519523 2016-10-26 00:00:00 0.02 78
USC00519523 2016-10-27 00:00:00 0.08 78
USC00519523 2016-10-28 00:00:00 0.06 78
USC00519523 2016-10-29 00:00:00 0.01 78
USC00519523 2016-10-30 00:00:00 0.0 79
USC00519523 2016-10-31 00:00:00 0.13 78
USC00519523 2016-11-01 00:00:00 0.01 79
USC00519523 2016-11-02 00:00:00 0.0 76
USC00519523 2016-11-03 00:00:00 0.0 77
USC00519523 2016-11-04 00:00:00 0.0 76
USC00519523 2016-11-05 00:00:00 0.02 78
USC00519523 2016-11-06 00:00:00 0.0 78
USC00519523 2016-11-07 00:00:00 0.0 76
USC00519523 2016-11-08 00:00:00 0.15 77
USC00519523 2016-11-09 00:00:00 0.0 75

USC00519523 2016-11-10 00:00:00 0.0 72
USC00519523 2016-11-11 00:00:00 0.0 73
USC00519523 2016-11-12 00:00:00 0.0 79
USC00519523 2016-11-13 00:00:00 0.0 79
USC00519523 2016-11-14 00:00:00 0.0 78
USC00519523 2016-11-15 00:00:00 0.0 77
USC00519523 2016-11-16 00:00:00 0.07 77
USC00519523 2016-11-17 00:00:00 0.0 77
USC00519523 2016-11-18 00:00:00 0.02 77
USC00519523 2016-11-19 00:00:00 0.13 76
USC00519523 2016-11-20 00:00:00 0.4 80
USC00519523 2016-11-21 00:00:00 0.07 75
USC00519523 2016-11-22 00:00:00 0.31 76
USC00519523 2016-11-23 00:00:00 0.03 75
USC00519523 2016-11-24 00:00:00 0.21 75
USC00519523 2016-11-25 00:00:00 0.11 76
USC00519523 2016-11-26 00:00:00 0.03 78
USC00519523 2016-11-27 00:00:00 0.0 78
USC00519523 2016-11-28 00:00:00 0.0 77
USC00519523 2016-11-29 00:00:00 0.06 76
USC00519523 2016-11-30 00:00:00 0.0 76
USC00519523 2016-12-01 00:00:00 0.16 76
USC00519523 2016-12-02 00:00:00 0.01 75
USC00519523 2016-12-03 00:00:00 0.02 75
USC00519523 2016-12-04 00:00:00 0.32 75
USC00519523 2016-12-05 00:00:00 0.45 70
USC00519523 2016-12-06 00:00:00 0.0 70
USC00519523 2016-12-07 00:00:00 0.07 74
USC00519523 2016-12-08 00:00:00 0.01 73
USC00519523 2016-12-11 00:00:00 0.06 78
USC00519523 2016-12-12 00:00:00 0.0 67
USC00519523 2016-12-13 00:00:00 0.15 69
USC00519523 2016-12-14 00:00:00 0.05 71
USC00519523 2016-12-15 00:00:00 0.0 74
USC00519523 2016-12-16 00:00:00 0.0 63
USC00519523 2016-12-17 00:00:00 0.16 76
USC00519523 2016-12-18 00:00:00 0.27 76
USC00519523 2016-12-19 00:00:00 0.02 71
USC00519523 2016-12-20 00:00:00 0.01 76
USC00519523 2016-12-21 00:00:00 0.06 77
USC00519523 2016-12-22 00:00:00 0.14 73
USC00519523 2016-12-23 00:00:00 0.02 71
USC00519523 2016-12-24 00:00:00 0.06 78
USC00519523 2016-12-25 00:00:00 0.0 78
USC00519523 2016-12-26 00:00:00 0.06 75
USC00519523 2016-12-27 00:00:00 0.0 75
USC00519523 2016-12-28 00:00:00 0.06 72
USC00519523 2016-12-29 00:00:00 0.05 77
USC00519523 2016-12-30 00:00:00 0.07 72
USC00519523 2017-01-04 00:00:00 0.18 73
USC00519523 2017-01-05 00:00:00 0.42 71
USC00519523 2017-01-06 00:00:00 0.01 74
USC00519523 2017-01-07 00:00:00 0.0 72
USC00519523 2017-01-08 00:00:00 0.0 74
USC00519523 2017-01-09 00:00:00 0.0 77
USC00519523 2017-01-10 00:00:00 0.0 75
USC00519523 2017-01-16 00:00:00 0.0 80
USC00519523 2017-01-19 00:00:00 0.0 78
USC00519523 2017-01-20 00:00:00 0.0 73
USC00519523 2017-01-21 00:00:00 0.11 74
USC00519523 2017-01-22 00:00:00 0.04 74
USC00519523 2017-01-23 00:00:00 0.0 74
USC00519523 2017-01-24 00:00:00 0.08 74
USC00519523 2017-01-25 00:00:00 0.0 72
USC00519523 2017-01-26 00:00:00 0.0 74
USC00519523 2017-01-27 00:00:00 0.0 74
USC00519523 2017-01-30 00:00:00 0.0 70
USC00519523 2017-01-31 00:00:00 0.0 70
USC00519523 2017-02-01 00:00:00 0.0 70
USC00519523 2017-02-02 00:00:00 0.0 64
USC00519523 2017-02-03 00:00:00 0.0 62
USC00519523 2017-02-04 00:00:00 0.0 76
USC00519523 2017-02-05 00:00:00 0.0 77
USC00519523 2017-02-06 00:00:00 0.0 76
USC00519523 2017-02-07 00:00:00 1.8 72
USC00519523 2017-02-08 00:00:00 0.0 74
USC00519523 2017-02-09 00:00:00 0.0 60
USC00519523 2017-02-10 00:00:00 0.0 74
USC00519523 2017-02-11 00:00:00 5.04 70
USC00519523 2017-02-12 00:00:00 0.07 73
USC00519523 2017-02-13 00:00:00 0.0 78
USC00519523 2017-02-16 00:00:00 0.67 72
USC00519523 2017-02-17 00:00:00 0.06 75
USC00519523 2017-02-18 00:00:00 0.01 67
USC00519523 2017-02-22 00:00:00 0.13 72
USC00519523 2017-02-23 00:00:00 0.0 73
USC00519523 2017-02-24 00:00:00 0.0 70
USC00519523 2017-02-27 00:00:00 0.0 77
USC00519523 2017-02-28 00:00:00 0.0 73
USC00519523 2017-03-01 00:00:00 0.59 73
USC00519523 2017-03-02 00:00:00 1.48 75
USC00519523 2017-03-03 00:00:00 0.25 74
USC00519523 2017-03-04 00:00:00 0.0 77
USC00519523 2017-03-10 00:00:00 0.0 69
USC00519523 2017-03-11 00:00:00 0.0 81
USC00519523 2017-03-12 00:00:00 0.0 74
USC00519523 2017-03-13 00:00:00 0.0 69
USC00519523 2017-03-14 00:00:00 0.0 74
USC00519523 2017-03-15 00:00:00 0.0 71
USC00519523 2017-03-16 00:00:00 0.0 69
USC00519523 2017-03-17 00:00:00 0.35 70
USC00519523 2017-03-18 00:00:00 0.0 74
USC00519523 2017-03-19 00:00:00 0.0 74
USC00519523 2017-03-20 00:00:00 0.0 75
USC00519523 2017-03-21 00:00:00 0.0 75
USC00519523 2017-03-22 00:00:00 0.0 75
USC00519523 2017-03-23 00:00:00 0.02 75
USC00519523 2017-03-24 00:00:00 0.07 76
USC00519523 2017-03-25 00:00:00 0.43 75
USC00519523 2017-03-26 00:00:00 0.0 80
USC00519523 2017-03-27 00:00:00 0.0 76
USC00519523 2017-03-28 00:00:00 0.0 76
USC00519523 2017-03-29 00:00:00 0.08 74
USC00519523 2017-03-30 00:00:00 0.0 78
USC00519523 2017-03-31 00:00:00 0.0 75
USC00519523 2017-04-01 00:00:00 0.0 80
USC00519523 2017-04-02 00:00:00 0.0 79
USC00519523 2017-04-03 00:00:00 0.0 76
USC00519523 2017-04-04 00:00:00 0.0 78
USC00519523 2017-04-05 00:00:00 0.0 77
USC00519523 2017-04-06 00:00:00 0.0 76
USC00519523 2017-04-07 00:00:00 0.0 78
USC00519523 2017-04-10 00:00:00 0.0 75
USC00519523 2017-04-11 00:00:00 0.0 82
USC00519523 2017-04-12 00:00:00 0.0 80
USC00519523 2017-04-13 00:00:00 0.0 79
USC00519523 2017-04-14 00:00:00 0.36 75
USC00519523 2017-04-15 00:00:00 0.0 79
USC00519523 2017-04-16 00:00:00 0.0 74
USC00519523 2017-04-17 00:00:00 0.3 71
USC00519523 2017-04-18 00:00:00 0.15 76
USC00519523 2017-04-19 00:00:00 0.0 74
USC00519523 2017-04-20 00:00:00 0.35 76
USC00519523 2017-04-21 00:00:00 2.36 70
USC00519523 2017-04-25 00:00:00 0.0 76
USC00519523 2017-04-26 00:00:00 0.01 81
USC00519523 2017-04-27 00:00:00 0.0 76
USC00519523 2017-04-28 00:00:00 0.0 76
USC00519523 2017-04-29 00:00:00 6.25 70
USC00519523 2017-04-30 00:00:00 1.31 64
USC00519523 2017-05-01 00:00:00 0.07 73
USC00519523 2017-05-02 00:00:00 0.0 78
USC00519523 2017-05-03 00:00:00 0.0 78
USC00519523 2017-05-04 00:00:00 0.0 77
USC00519523 2017-05-05 00:00:00 0.0 79
USC00519523 2017-05-06 00:00:00 0.0 80
USC00519523 2017-05-07 00:00:00 0.0 78
USC00519523 2017-05-08 00:00:00 0.0 80
USC00519523 2017-05-09 00:00:00 0.68 75
USC00519523 2017-05-10 00:00:00 0.06 76
USC00519523 2017-05-11 00:00:00 0.0 78
USC00519523 2017-05-12 00:00:00 0.0 77
USC00519523 2017-05-13 00:00:00 0.0 76
USC00519523 2017-05-14 00:00:00 0.0 78
USC00519523 2017-05-15 00:00:00 0.06 77
USC00519523 2017-05-16 00:00:00 0.0 76
USC00519523 2017-05-17 00:00:00 0.0 77
USC00519523 2017-05-18 00:00:00 0.46 71
USC00519523 2017-05-21 00:00:00 0.0 80
USC00519523 2017-05-22 00:00:00 0.0 76
USC00519523 2017-05-23 00:00:00 0.0 76
USC00519523 2017-05-24 00:00:00 0.61 76
USC00519523 2017-05-25 00:00:00 0.55 75
USC00519523 2017-05-26 00:00:00 0.0 77
USC00519523 2017-05-27 00:00:00 0.0 79
USC00519523 2017-05-28 00:00:00 0.0 82
USC00519523 2017-05-29 00:00:00 0.0 80
USC00519523 2017-05-30 00:00:00 0.11 78
USC00519523 2017-05-31 00:00:00 0.0 79
USC00519523 2017-06-01 00:00:00 0.0 79
USC00519523 2017-06-02 00:00:00 0.0 81
USC00519523 2017-06-03 00:00:00 0.15 79
USC00519523 2017-06-04 00:00:00 0.0 81
USC00519523 2017-06-05 00:00:00 0.0 78
USC00519523 2017-06-06 00:00:00 0.0 78
USC00519523 2017-06-07 00:00:00 0.0 78
USC00519523 2017-06-08 00:00:00 0.0 77
USC00519523 2017-06-09 00:00:00 0.0 78
USC00519523 2017-06-10 00:00:00 0.13 75
USC00519523 2017-06-11 00:00:00 0.25 81
USC00519523 2017-06-12 00:00:00 0.14 80
USC00519523 2017-06-13 00:00:00 0.03 77
USC00519523 2017-06-14 00:00:00 0.06 80
USC00519523 2017-06-15 00:00:00 0.0 78
USC00519523 2017-06-16 00:00:00 0.0 80
USC00519523 2017-06-17 00:00:00 0.0 77
USC00519523 2017-06-18 00:00:00 0.0 78
USC00519523 2017-06-19 00:00:00 0.01 78
USC00519523 2017-06-22 00:00:00 0.0 80
USC00519523 2017-06-23 00:00:00 0.05 79
USC00519523 2017-06-24 00:00:00 0.0 82
USC00519523 2017-06-25 00:00:00 0.0 80
USC00519523 2017-06-26 00:00:00 0.0 81
USC00519523 2017-06-27 00:00:00 0.0 81
USC00519523 2017-06-28 00:00:00 0.0 79
USC00519523 2017-06-29 00:00:00 0.0 78
USC00519523 2017-06-30 00:00:00 0.07 75
USC00519523 2017-07-03 00:00:00 0.02 81
USC00519523 2017-07-06 00:00:00 0.0 79
USC00519523 2017-07-07 00:00:00 0.0 79
USC00519523 2017-07-08 00:00:00 0.0 77
USC00519523 2017-07-09 00:00:00 0.0 82
USC00519523 2017-07-10 00:00:00 0.0 82
USC00519523 2017-07-11 00:00:00 0.0 79
USC00519523 2017-07-12 00:00:00 0.0 82
USC00519523 2017-07-13 00:00:00 0.11 79
USC00519523 2017-07-14 00:00:00 0.0 80
USC00519523 2017-07-15 00:00:00 0.0 82
USC00519523 2017-07-16 00:00:00 0.0 82
USC00519523 2017-07-17 00:00:00 0.0 82
USC00519523 2017-07-18 00:00:00 0.0 83
USC00519523 2017-07-19 00:00:00 0.0 80
USC00519523 2017-07-20 00:00:00 0.33 80
USC00519523 2017-07-21 00:00:00 0.0 80
USC00519523 2017-07-22 00:00:00 0.0 78
USC00519523 2017-07-25 00:00:00 0.05 80
USC00519523 2017-07-26 00:00:00 0.0 84
USC00519523 2017-07-27 00:00:00 0.0 80
USC00519523 2017-07-28 00:00:00 0.0 81
USC00519523 2017-07-29 00:00:00 0.0 83
USC00519523 2017-07-30 00:00:00 0.0 84
USC00519523 2017-07-31 00:00:00 0.0 82
USC00519523 2017-08-01 00:00:00 0.0 75
USC00519523 2017-08-02 00:00:00 0.0 83
USC00519523 2017-08-03 00:00:00 0.0 80
USC00519523 2017-08-04 00:00:00 0.0 82
USC00519523 2017-08-06 00:00:00 0.0 83
USC00519523 2017-08-07 00:00:00 0.0 83
USC00519523 2017-08-08 00:00:00 0.0 82
USC00519523 2017-08-10 00:00:00 0.0 80
USC00519523 2017-08-11 00:00:00 0.0 81
USC00519523 2017-08-12 00:00:00 0.0 83
USC00519523 2017-08-13 00:00:00 0.0 84
USC00519523 2017-08-14 00:00:00 0.08 75
USC00519523 2017-08-15 00:00:00 0.06 79
USC00519523 2017-08-16 00:00:00 0.07 79
USC00519523 2017-08-17 00:00:00 0.05 83
USC00519523 2017-08-22 00:00:00 0.0 82
USC00519523 2017-08-23 00:00:00 0.08 82
USC00519281 WAIHEE 837.5, HI US
USC00519281 2010-01-01 00:00:00 0.15 70
USC00519281 2010-01-02 00:00:00 0.0 62
USC00519281 2010-01-03 00:00:00 0.0 74
USC00519281 2010-01-04 00:00:00 0.0 75
USC00519281 2010-01-05 00:00:00 0.0 74
USC00519281 2010-01-06 00:00:00 0.01 76
USC00519281 2010-01-07 00:00:00 0.17 69
USC00519281 2010-01-08 00:00:00 0.0 66
USC00519281 2010-01-09 00:00:00 0.0 70
USC00519281 2010-01-10 00:00:00 0.0 75
USC00519281 2010-01-11 00:00:00 0.03 64
USC00519281 2010-01-12 00:00:00 0.0 60
USC00519281 2010-01-13 00:00:00 0.0 61
USC00519281 2010-01-14 00:00:00 0.0 68
USC00519281 2010-01-15 00:00:00 0.0 64
USC00519281 2010-01-16 00:00:00 0.0 66
USC00519281 2010-01-17 00:00:00 0.0 67
USC00519281 2010-01-18 00:00:00 0.0 70
USC00519281 2010-01-19 00:00:00 0.0 67
USC00519281 2010-01-20 00:00:00 0.0 67
USC00519281 2010-01-21 00:00:00 0.16 69
USC00519281 2010-01-22 00:00:00 0.0 60
USC00519281 2010-01-23 00:00:00 0.0 75
USC00519281 2010-01-24 00:00:00 0.0 75
USC00519281 2010-01-25 00:00:00 0.0 65
USC00519281 2010-01-26 00:00:00 0.01 75
USC00519281 2010-01-27 00:00:00 0.31 69
USC00519281 2010-01-28 00:00:00 0.37 67
USC00519281 2010-01-29 00:00:00 0.75 66
USC00519281 2010-01-30 00:00:00 2.17 69
USC00519281 2010-01-31 00:00:00 0.69 72
USC00519281 2010-02-01 00:00:00 0.02 67
USC00519281 2010-02-02 00:00:00 0.0 65
USC00519281 2010-02-03 00:00:00 0.37 64
USC00519281 2010-02-04 00:00:00 0.0 67
USC00519281 2010-02-05 00:00:00 0.02 67
USC00519281 2010-02-06 00:00:00 0.0 68
USC00519281 2010-02-07 00:00:00 0.0 69
USC00519281 2010-02-08 00:00:00 0.0 66
USC00519281 2010-02-09 00:00:00 0.0 69
USC00519281 2010-02-10 00:00:00 0.0 61
USC00519281 2010-02-11 00:00:00 0.0 71
USC00519281 2010-02-12 00:00:00 0.08 70
USC00519281 2010-02-13 00:00:00 0.06 70
USC00519281 2010-02-14 00:00:00 0.0 66
USC00519281 2010-02-15 00:00:00 0.0 71
USC00519281 2010-02-16 00:00:00 0.0 61
USC00519281 2010-02-17 00:00:00 0.0 68
USC00519281 2010-02-18 00:00:00 0.0 67
USC00519281 2010-02-19 00:00:00 0.02 62
USC00519281 2010-02-20 00:00:00 0.57 65
USC00519281 2010-02-21 00:00:00 0.01 69
USC00519281 2010-02-22 00:00:00 0.22 63
USC00519281 2010-02-23 00:00:00 0.0 62
USC00519281 2010-02-24 00:00:00 0.0 61
USC00519281 2010-02-25 00:00:00 0.0 64
USC00519281 2010-02-26 00:00:00 0.01 72
USC00519281 2010-02-27 00:00:00 0.0 68
USC00519281 2010-02-28 00:00:00 0.12 68
USC00519281 2010-03-01 00:00:00 0.01 68
USC00519281 2010-03-02 00:00:00 0.0 71
USC00519281 2010-03-03 00:00:00 0.0 69
USC00519281 2010-03-04 00:00:00 0.4 65
USC00519281 2010-03-05 00:00:00 0.33 67
USC00519281 2010-03-06 00:00:00 0.51 71
USC00519281 2010-03-07 00:00:00 0.08 70
USC00519281 2010-03-08 00:00:00 0.53 69
USC00519281 2010-03-09 00:00:00 0.04 69
USC00519281 2010-03-10 00:00:00 0.45 70
USC00519281 2010-03-11 00:00:00 0.01 69
USC00519281 2010-03-12 00:00:00 0.12 70
USC00519281 2010-03-13 00:00:00 0.0 73
USC00519281 2010-03-14 00:00:00 0.0 74
USC00519281 2010-03-15 00:00:00 0.23 67
USC00519281 2010-03-16 00:00:00 0.5 68
USC00519281 2010-03-17 00:00:00 0.19 64
USC00519281 2010-03-18 00:00:00 0.69 65
USC00519281 2010-03-19 00:00:00 0.19 68
USC00519281 2010-03-20 00:00:00 0.0 68
USC00519281 2010-03-21 00:00:00 0.05 72
USC00519281 2010-03-22 00:00:00 0.0 67
USC00519281 2010-03-23 00:00:00 0.0 64
USC00519281 2010-03-24 00:00:00 0.02 71
USC00519281 2010-03-25 00:00:00 0.06 70
USC00519281 2010-03-26 00:00:00 0.12 72
USC00519281 2010-03-27 00:00:00 0.0 73
USC00519281 2010-03-28 00:00:00 0.0 74
USC00519281 2010-03-29 00:00:00 0.01 69
USC00519281 2010-03-30 00:00:00 0.03 71
USC00519281 2010-03-31 00:00:00 0.0 72
USC00519281 2010-04-01 00:00:00 0.03 71
USC00519281 2010-04-02 00:00:00 0.11 74
USC00519281 2010-04-03 00:00:00 0.18 73
USC00519281 2010-04-04 00:00:00 0.11 71
USC00519281 2010-04-05 00:00:00 0.57 71
USC00519281 2010-04-06 00:00:00 0.16 69
USC00519281 2010-04-07 00:00:00 3.99 69
USC00519281 2010-04-08 00:00:00 0.1 72
USC00519281 2010-04-09 00:00:00 0.01 68
USC00519281 2010-04-10 00:00:00 0.14 75
USC00519281 2010-04-11 00:00:00 0.02 69
USC00519281 2010-04-12 00:00:00 0.0 65
USC00519281 2010-04-13 00:00:00 0.02 68
USC00519281 2010-04-14 00:00:00 0.14 65
USC00519281 2010-04-15 00:00:00 0.0 66
USC00519281 2010-04-16 00:00:00 0.0 64
USC00519281 2010-04-17 00:00:00 0.03 69
USC00519281 2010-04-18 00:00:00 0.0 69
USC00519281 2010-04-19 00:00:00 0.0 70
USC00519281 2010-04-20 00:00:00 0.02 69
USC00519281 2010-04-21 00:00:00 0.13 69
USC00519281 2010-04-22 00:00:00 0.02 69
USC00519281 2010-04-23 00:00:00 0.18 70
USC00519281 2010-04-24 00:00:00 0.0 77
USC00519281 2010-04-25 00:00:00 0.0 77
USC00519281 2010-04-26 00:00:00 0.0 71
USC00519281 2010-04-27 00:00:00 0.0 71
USC00519281 2010-04-28 00:00:00 0.04 70
USC00519281 2010-04-29 00:00:00 0.07 70
USC00519281 2010-04-30 00:00:00 0.17 72
USC00519281 2010-05-01 00:00:00 0.39 73
USC00519281 2010-05-02 00:00:00 0.11 71
USC00519281 2010-05-03 00:00:00 1.06 70
USC00519281 2010-05-04 00:00:00 0.11 72
USC00519281 2010-05-05 00:00:00 0.0 73
USC00519281 2010-05-06 00:00:00 0.01 72
USC00519281 2010-05-07 00:00:00 0.16 68
USC00519281 2010-05-08 00:00:00 0.01 76
USC00519281 2010-05-09 00:00:00 0.0 77
USC00519281 2010-05-10 00:00:00 0.0 73
USC00519281 2010-05-11 00:00:00 0.06 69
USC00519281 2010-05-12 00:00:00 0.02 71
USC00519281 2010-05-13 00:00:00 0.06 73
USC00519281 2010-05-14 00:00:00 0.0 73
USC00519281 2010-05-15 00:00:00 0.14 77
USC00519281 2010-05-16 00:00:00 0.13 73

USC00519281 2010-05-17 00:00:00 0.01 73
USC00519281 2010-05-18 00:00:00 0.0 72
USC00519281 2010-05-19 00:00:00 0.0 72
USC00519281 2010-05-20 00:00:00 0.28 71
USC00519281 2010-05-21 00:00:00 0.02 73
USC00519281 2010-05-22 00:00:00 0.18 72
USC00519281 2010-05-23 00:00:00 0.28 72
USC00519281 2010-05-24 00:00:00 0.22 72
USC00519281 2010-05-25 00:00:00 0.33 72
USC00519281 2010-05-26 00:00:00 0.09 73
USC00519281 2010-05-27 00:00:00 0.0 69
USC00519281 2010-05-28 00:00:00 0.0 69
USC00519281 2010-05-29 00:00:00 0.8 75
USC00519281 2010-05-30 00:00:00 0.01 74
USC00519281 2010-05-31 00:00:00 0.04 75
USC00519281 2010-06-01 00:00:00 0.0 71
USC00519281 2010-06-02 00:00:00 0.03 71
USC00519281 2010-06-03 00:00:00 0.0 72
USC00519281 2010-06-04 00:00:00 0.0 72
USC00519281 2010-06-05 00:00:00 0.0 76
USC00519281 2010-06-06 00:00:00 0.0 77
USC00519281 2010-06-07 00:00:00 0.12 71
USC00519281 2010-06-08 00:00:00 0.0 73
USC00519281 2010-06-09 00:00:00 0.0 73
USC00519281 2010-06-10 00:00:00 0.0 75
USC00519281 2010-06-11 00:00:00 0.0 81
USC00519281 2010-06-12 00:00:00 0.0 74
USC00519281 2010-06-13 00:00:00 0.04 77
USC00519281 2010-06-14 00:00:00 0.06 70
USC00519281 2010-06-15 00:00:00 0.11 69
USC00519281 2010-06-16 00:00:00 0.0 70
USC00519281 2010-06-17 00:00:00 0.02 72
USC00519281 2010-06-18 00:00:00 0.19 71
USC00519281 2010-06-19 00:00:00 0.33 77
USC00519281 2010-06-20 00:00:00 0.0 76
USC00519281 2010-06-21 00:00:00 0.0 74
USC00519281 2010-06-22 00:00:00 0.0 74
USC00519281 2010-06-23 00:00:00 0.02 74
USC00519281 2010-06-24 00:00:00 0.07 74
USC00519281 2010-06-25 00:00:00 0.09 71
USC00519281 2010-06-26 00:00:00 0.41 80
USC00519281 2010-06-27 00:00:00 0.05 77
USC00519281 2010-06-28 00:00:00 0.0 72
USC00519281 2010-06-29 00:00:00 0.05 72
USC00519281 2010-06-30 00:00:00 0.0 73
USC00519281 2010-07-01 00:00:00 0.0 73
USC00519281 2010-07-02 00:00:00 0.23 71
USC00519281 2010-07-03 00:00:00 0.38 72
USC00519281 2010-07-04 00:00:00 0.38 73
USC00519281 2010-07-05 00:00:00 0.08 74
USC00519281 2010-07-06 00:00:00 0.14 70
USC00519281 2010-07-07 00:00:00 0.21 70
USC00519281 2010-07-08 00:00:00 0.06 73
USC00519281 2010-07-09 00:00:00 0.02 74
USC00519281 2010-07-10 00:00:00 0.19 74
USC00519281 2010-07-11 00:00:00 0.0 77
USC00519281 2010-07-12 00:00:00 0.0 70
USC00519281 2010-07-13 00:00:00 0.62 69
USC00519281 2010-07-14 00:00:00 0.2 70
USC00519281 2010-07-15 00:00:00 0.14 70
USC00519281 2010-07-16 00:00:00 0.01 76
USC00519281 2010-07-17 00:00:00 0.04 72
USC00519281 2010-07-18 00:00:00 0.31 74
USC00519281 2010-07-19 00:00:00 0.02 73
USC00519281 2010-07-20 00:00:00 0.1 74
USC00519281 2010-07-21 00:00:00 0.0 72
USC00519281 2010-07-22 00:00:00 0.19 74
USC00519281 2010-07-23 00:00:00 0.07 72
USC00519281 2010-07-24 00:00:00 0.35 74
USC00519281 2010-07-25 00:00:00 0.0 74
USC00519281 2010-07-26 00:00:00 0.0 72
USC00519281 2010-07-27 00:00:00 0.01 69
USC00519281 2010-07-28 00:00:00 0.16 71
USC00519281 2010-07-29 00:00:00 0.02 72
USC00519281 2010-07-30 00:00:00 0.0 74
USC00519281 2010-07-31 00:00:00 0.04 77
USC00519281 2010-08-01 00:00:00 0.14 72
USC00519281 2010-08-02 00:00:00 0.27 71
USC00519281 2010-08-03 00:00:00 0.02 74
USC00519281 2010-08-04 00:00:00 0.28 74
USC00519281 2010-08-05 00:00:00 0.11 70
USC00519281 2010-08-06 00:00:00 0.16 73
USC00519281 2010-08-07 00:00:00 0.17 78
USC00519281 2010-08-08 00:00:00 0.12 74
USC00519281 2010-08-09 00:00:00 0.12 72
USC00519281 2010-08-10 00:00:00 0.0 74
USC00519281 2010-08-11 00:00:00 0.0 74
USC00519281 2010-08-12 00:00:00 0.02 74
USC00519281 2010-08-13 00:00:00 0.08 72
USC00519281 2010-08-14 00:00:00 0.0 78
USC00519281 2010-08-15 00:00:00 0.0 76
USC00519281 2010-08-16 00:00:00 0.21 80
USC00519281 2010-08-17 00:00:00 0.31 79
USC00519281 2010-08-18 00:00:00 0.05 78
USC00519281 2010-08-19 00:00:00 0.43 78
USC00519281 2010-08-20 00:00:00 0.02 78
USC00519281 2010-08-21 00:00:00 0.0 77
USC00519281 2010-08-22 00:00:00 0.0 75
USC00519281 2010-08-23 00:00:00 0.0 75
USC00519281 2010-08-24 00:00:00 0.0 80
USC00519281 2010-08-25 00:00:00 0.19 74
USC00519281 2010-08-26 00:00:00 0.05 73
USC00519281 2010-08-27 00:00:00 0.12 73
USC00519281 2010-08-28 00:00:00 0.0 78
USC00519281 2010-08-29 00:00:00 0.19 78
USC00519281 2010-08-30 00:00:00 0.01 72
USC00519281 2010-08-31 00:00:00 0.16 70
USC00519281 2010-09-01 00:00:00 0.01 72
USC00519281 2010-09-02 00:00:00 0.16 70
USC00519281 2010-09-03 00:00:00 0.26 71
USC00519281 2010-09-04 00:00:00 0.04 82
USC00519281 2010-09-05 00:00:00 0.16 71
USC00519281 2010-09-06 00:00:00 0.11 75
USC00519281 2010-09-07 00:00:00 0.16 70
USC00519281 2010-09-08 00:00:00 0.15 72
USC00519281 2010-09-09 00:00:00 0.01 73
USC00519281 2010-09-10 00:00:00 0.01 72
USC00519281 2010-09-11 00:00:00 0.05 79
USC00519281 2010-09-12 00:00:00 0.0 79
USC00519281 2010-09-13 00:00:00 0.0 78
USC00519281 2010-09-14 00:00:00 0.06 70
USC00519281 2010-09-15 00:00:00 0.02 75
USC00519281 2010-09-16 00:00:00 0.0 75
USC00519281 2010-09-17 00:00:00 0.0 75
USC00519281 2010-09-18 00:00:00 0.04 77
USC00519281 2010-09-19 00:00:00 0.19 76
USC00519281 2010-09-20 00:00:00 0.05 75
USC00519281 2010-09-21 00:00:00 0.0 73
USC00519281 2010-09-22 00:00:00 0.39 74
USC00519281 2010-09-23 00:00:00 0.89 70
USC00519281 2010-09-24 00:00:00 0.0 70
USC00519281 2010-09-25 00:00:00 0.0 75
USC00519281 2010-09-26 00:00:00 0.0 77
USC00519281 2010-09-27 00:00:00 0.02 68
USC00519281 2010-09-28 00:00:00 0.0 68
USC00519281 2010-09-29 00:00:00 0.0 68
USC00519281 2010-09-30 00:00:00 0.44 68
USC00519281 2010-10-01 00:00:00 0.77 71
USC00519281 2010-10-02 00:00:00 1.15 74
USC00519281 2010-10-03 00:00:00 0.09 78
USC00519281 2010-10-04 00:00:00 0.08 74
USC00519281 2010-10-05 00:00:00 0.22 75
USC00519281 2010-10-06 00:00:00 0.16 71
USC00519281 2010-10-07 00:00:00 0.0 69
USC00519281 2010-10-08 00:00:00 0.0 69
USC00519281 2010-10-09 00:00:00 0.0 79
USC00519281 2010-10-10 00:00:00 0.05 76
USC00519281 2010-10-11 00:00:00 0.02 75
USC00519281 2010-10-12 00:00:00 0.0 74
USC00519281 2010-10-13 00:00:00 0.06 71
USC00519281 2010-10-14 00:00:00 0.0 71
USC00519281 2010-10-15 00:00:00 0.0 70
USC00519281 2010-10-16 00:00:00 0.0 74
USC00519281 2010-10-17 00:00:00 0.0 76
USC00519281 2010-10-18 00:00:00 0.03 67
USC00519281 2010-10-19 00:00:00 0.2 70
USC00519281 2010-10-20 00:00:00 0.0 67
USC00519281 2010-10-21 00:00:00 1.91 72
USC00519281 2010-10-22 00:00:00 1.16 72
USC00519281 2010-10-23 00:00:00 0.02 74
USC00519281 2010-10-24 00:00:00 0.0 77
USC00519281 2010-10-25 00:00:00 0.0 75
USC00519281 2010-10-26 00:00:00 0.27 74
USC00519281 2010-10-27 00:00:00 0.09 76
USC00519281 2010-10-28 00:00:00 0.18 75
USC00519281 2010-10-29 00:00:00 0.03 73
USC00519281 2010-10-30 00:00:00 0.41 74
USC00519281 2010-10-31 00:00:00 0.13 73
USC00519281 2010-11-01 00:00:00 0.13 71
USC00519281 2010-11-03 00:00:00 1.13 69
USC00519281 2010-11-04 00:00:00 1.21 70
USC00519281 2010-11-05 00:00:00 0.57 73
USC00519281 2010-11-06 00:00:00 0.61 73
USC00519281 2010-11-07 00:00:00 0.47 76
USC00519281 2010-11-08 00:00:00 0.0 73
USC00519281 2010-11-09 00:00:00 0.0 74
USC00519281 2010-11-10 00:00:00 0.07 72
USC00519281 2010-11-11 00:00:00 0.0 75
USC00519281 2010-11-12 00:00:00 0.03 73
USC00519281 2010-11-13 00:00:00 0.18 74
USC00519281 2010-11-14 00:00:00 0.01 72
USC00519281 2010-11-15 00:00:00 0.85 74
USC00519281 2010-11-16 00:00:00 0.13 68
USC00519281 2010-11-17 00:00:00 0.0 68
USC00519281 2010-11-18 00:00:00 0.0 66
USC00519281 2010-11-19 00:00:00 0.19 73
USC00519281 2010-11-20 00:00:00 0.0 76
USC00519281 2010-11-21 00:00:00 0.03 72
USC00519281 2010-11-22 00:00:00 0.01 65
USC00519281 2010-11-23 00:00:00 0.0 65
USC00519281 2010-11-24 00:00:00 0.0 73
USC00519281 2010-11-25 00:00:00 0.13 76
USC00519281 2010-11-26 00:00:00 0.0 76
USC00519281 2010-11-27 00:00:00 0.01 73
USC00519281 2010-11-28 00:00:00 0.43 72
USC00519281 2010-11-29 00:00:00 0.23 69
USC00519281 2010-11-30 00:00:00 0.02 72
USC00519281 2010-12-01 00:00:00 1.35 72
USC00519281 2010-12-02 00:00:00 0.16 71
USC00519281 2010-12-03 00:00:00 0.47 72
USC00519281 2010-12-04 00:00:00 0.0 74
USC00519281 2010-12-05 00:00:00 0.0 66
USC00519281 2010-12-06 00:00:00 0.0 61
USC00519281 2010-12-07 00:00:00 0.0 58
USC00519281 2010-12-08 00:00:00 0.0 60
USC00519281 2010-12-09 00:00:00 0.07 71
USC00519281 2010-12-10 00:00:00 1.72 65
USC00519281 2010-12-11 00:00:00 0.89 72
USC00519281 2010-12-12 00:00:00 0.31 70
USC00519281 2010-12-13 00:00:00 0.22 68
USC00519281 2010-12-14 00:00:00 0.02 67
USC00519281 2010-12-15 00:00:00 0.0 71
USC00519281 2010-12-16 00:00:00 0.0 65
USC00519281 2010-12-17 00:00:00 0.0 64
USC00519281 2010-12-18 00:00:00 0.0 65
USC00519281 2010-12-19 00:00:00 2.77 69
USC00519281 2010-12-20 00:00:00 3.06 70
USC00519281 2010-12-21 00:00:00 0.71 70
USC00519281 2010-12-22 00:00:00 0.02 68
USC00519281 2010-12-23 00:00:00 0.23 69
USC00519281 2010-12-24 00:00:00 0.02 71
USC00519281 2010-12-25 00:00:00 3.14 70
USC00519281 2010-12-26 00:00:00 2.49 71
USC00519281 2010-12-27 00:00:00 0.13 76
USC00519281 2010-12-28 00:00:00 0.58 71
USC00519281 2010-12-29 00:00:00 0.06 72
USC00519281 2010-12-30 00:00:00 0.04 73
USC00519281 2010-12-31 00:00:00 0.1 77
USC00519281 2011-01-01 00:00:00 0.38 77
USC00519281 2011-01-02 00:00:00 0.01 72
USC00519281 2011-01-03 00:00:00 0.07 72
USC00519281 2011-01-04 00:00:00 0.0 71
USC00519281 2011-01-05 00:00:00 0.08 65
USC00519281 2011-01-06 00:00:00 0.16 67
USC00519281 2011-01-07 00:00:00 0.0 63
USC00519281 2011-01-08 00:00:00 0.01 64
USC00519281 2011-01-09 00:00:00 0.0 60
USC00519281 2011-01-10 00:00:00 0.0 71
USC00519281 2011-01-11 00:00:00 0.34 57
USC00519281 2011-01-12 00:00:00 0.02 67
USC00519281 2011-01-13 00:00:00 8.81 68
USC00519281 2011-01-14 00:00:00 0.55 75
USC00519281 2011-01-15 00:00:00 0.02 73
USC00519281 2011-01-16 00:00:00 0.0 67
USC00519281 2011-01-17 00:00:00 0.13 75
USC00519281 2011-01-18 00:00:00 0.0 62
USC00519281 2011-01-19 00:00:00 0.07 64
USC00519281 2011-01-20 00:00:00 0.1 67
USC00519281 2011-01-21 00:00:00 0.04 72
USC00519281 2011-01-22 00:00:00 0.0 76
USC00519281 2011-01-23 00:00:00 0.0 67
USC00519281 2011-01-24 00:00:00 0.0 71
USC00519281 2011-01-25 00:00:00 0.03 62
USC00519281 2011-01-26 00:00:00 0.0 66
USC00519281 2011-01-27 00:00:00 0.0 65
USC00519281 2011-01-28 00:00:00 0.0 71
USC00519281 2011-01-29 00:00:00 0.02 65
USC00519281 2011-01-30 00:00:00 0.0 75
USC00519281 2011-01-31 00:00:00 0.07 60
USC00519281 2011-02-01 00:00:00 0.0 62
USC00519281 2011-02-02 00:00:00 0.0 67
USC00519281 2011-02-03 00:00:00 0.0 68
USC00519281 2011-02-04 00:00:00 0.0 62
USC00519281 2011-02-05 00:00:00 0.0 65
USC00519281 2011-02-06 00:00:00 0.0 75
USC00519281 2011-02-07 00:00:00 1.33 67
USC00519281 2011-02-08 00:00:00 1.43 70
USC00519281 2011-02-09 00:00:00 0.0 69
USC00519281 2011-02-10 00:00:00 0.0 67
USC00519281 2011-02-11 00:00:00 0.98 71
USC00519281 2011-02-12 00:00:00 0.98 68
USC00519281 2011-02-13 00:00:00 1.47 72
USC00519281 2011-02-14 00:00:00 0.0 67
USC00519281 2011-02-15 00:00:00 0.0 69
USC00519281 2011-02-16 00:00:00 0.84 73
USC00519281 2011-02-17 00:00:00 0.07 72
USC00519281 2011-02-18 00:00:00 0.53 74
USC00519281 2011-02-19 00:00:00 0.0 73
USC00519281 2011-02-20 00:00:00 2.69 73
USC00519281 2011-02-21 00:00:00 0.01 67
USC00519281 2011-02-22 00:00:00 0.03 70
USC00519281 2011-02-23 00:00:00 0.0 69
USC00519281 2011-02-24 00:00:00 1.06 67
USC00519281 2011-02-25 00:00:00 0.03 63
USC00519281 2011-02-26 00:00:00 0.0 73
USC00519281 2011-02-27 00:00:00 0.01 74
USC00519281 2011-02-28 00:00:00 0.0 66

USC00519281 2011-03-01 00:00:00 0.03 66
USC00519281 2011-03-02 00:00:00 0.0 68
USC00519281 2011-03-03 00:00:00 0.69 69
USC00519281 2011-03-04 00:00:00 1.25 70
USC00519281 2011-03-05 00:00:00 0.26 67
USC00519281 2011-03-06 00:00:00 1.51 74
USC00519281 2011-03-07 00:00:00 0.01 73
USC00519281 2011-03-08 00:00:00 0.39 69
USC00519281 2011-03-09 00:00:00 0.01 72
USC00519281 2011-03-10 00:00:00 2.39 70
USC00519281 2011-03-11 00:00:00 0.34 70
USC00519281 2011-03-12 00:00:00 0.01 76
USC00519281 2011-03-13 00:00:00 0.01 72
USC00519281 2011-03-14 00:00:00 0.0 65
USC00519281 2011-03-15 00:00:00 0.0 67
USC00519281 2011-03-16 00:00:00 0.0 73
USC00519281 2011-03-17 00:00:00 0.04 71
USC00519281 2011-03-18 00:00:00 0.09 73
USC00519281 2011-03-19 00:00:00 0.17 71
USC00519281 2011-03-20 00:00:00 0.17 72
USC00519281 2011-03-21 00:00:00 0.0 71
USC00519281 2011-03-22 00:00:00 0.1 70
USC00519281 2011-03-23 00:00:00 0.17 72
USC00519281 2011-03-24 00:00:00 0.21 71
USC00519281 2011-03-25 00:00:00 0.02 74
USC00519281 2011-03-26 00:00:00 0.02 73
USC00519281 2011-03-27 00:00:00 0.1 73
USC00519281 2011-03-28 00:00:00 0.0 71
USC00519281 2011-03-29 00:00:00 0.09 70
USC00519281 2011-03-30 00:00:00 0.04 76
USC00519281 2011-03-31 00:00:00 0.0 71
USC00519281 2011-04-01 00:00:00 0.4 71
USC00519281 2011-04-02 00:00:00 0.09 68
USC00519281 2011-04-03 00:00:00 0.01 73
USC00519281 2011-04-04 00:00:00 0.01 72
USC00519281 2011-04-05 00:00:00 0.01 71
USC00519281 2011-04-06 00:00:00 0.25 68
USC00519281 2011-04-07 00:00:00 0.95 66
USC00519281 2011-04-08 00:00:00 0.5 67
USC00519281 2011-04-09 00:00:00 0.32 76
USC00519281 2011-04-10 00:00:00 0.0 74
USC00519281 2011-04-11 00:00:00 0.0 73
USC00519281 2011-04-12 00:00:00 0.0 72
USC00519281 2011-04-13 00:00:00 0.03 65
USC00519281 2011-04-14 00:00:00 0.18 70
USC00519281 2011-04-15 00:00:00 0.06 67
USC00519281 2011-04-16 00:00:00 0.12 71
USC00519281 2011-04-17 00:00:00 0.0 76
USC00519281 2011-04-18 00:00:00 0.0 69
USC00519281 2011-04-19 00:00:00 0.0 67
USC00519281 2011-04-20 00:00:00 0.0 67
USC00519281 2011-04-21 00:00:00 0.0 67
USC00519281 2011-04-22 00:00:00 0.0 76
USC00519281 2011-04-23 00:00:00 0.0 71
USC00519281 2011-04-24 00:00:00 0.02 77
USC00519281 2011-04-25 00:00:00 0.0 73
USC00519281 2011-04-26 00:00:00 0.15 69
USC00519281 2011-04-27 00:00:00 0.05 71
USC00519281 2011-04-28 00:00:00 0.0 73
USC00519281 2011-04-29 00:00:00 0.06 69
USC00519281 2011-04-30 00:00:00 0.41 68
USC00519281 2011-05-01 00:00:00 0.03 71
USC00519281 2011-05-02 00:00:00 1.58 70
USC00519281 2011-05-03 00:00:00 0.4 69
USC00519281 2011-05-04 00:00:00 0.14 72
USC00519281 2011-05-05 00:00:00 0.16 71
USC00519281 2011-05-06 00:00:00 0.94 68
USC00519281 2011-05-07 00:00:00 1.5 70
USC00519281 2011-05-08 00:00:00 3.14 73
USC00519281 2011-05-09 00:00:00 1.18 73
USC00519281 2011-05-10 00:00:00 0.36 74
USC00519281 2011-05-11 00:00:00 1.33 72
USC00519281 2011-05-12 00:00:00 0.14 70
USC00519281 2011-05-13 00:00:00 0.02 74
USC00519281 2011-05-14 00:00:00 0.0 79
USC00519281 2011-05-15 00:00:00 0.0 75
USC00519281 2011-05-16 00:00:00 0.0 73
USC00519281 2011-05-17 00:00:00 0.05 68
USC00519281 2011-05-18 00:00:00 0.64 69
USC00519281 2011-05-19 00:00:00 0.11 67
USC00519281 2011-05-20 00:00:00 0.01 73
USC00519281 2011-05-21 00:00:00 0.09 72
USC00519281 2011-05-22 00:00:00 0.06 76
USC00519281 2011-05-23 00:00:00 0.1 72
USC00519281 2011-05-24 00:00:00 0.0 73
USC00519281 2011-05-25 00:00:00 0.01 72
USC00519281 2011-05-26 00:00:00 0.01 73
USC00519281 2011-05-27 00:00:00 0.23 73
USC00519281 2011-05-28 00:00:00 0.03 74
USC00519281 2011-05-29 00:00:00 0.08 78
USC00519281 2011-05-30 00:00:00 0.02 72
USC00519281 2011-05-31 00:00:00 0.01 72
USC00519281 2011-06-01 00:00:00 0.22 72
USC00519281 2011-06-02 00:00:00 0.42 73
USC00519281 2011-06-03 00:00:00 0.33 73
USC00519281 2011-06-08 00:00:00 0.03 77
USC00519281 2011-06-09 00:00:00 0.05 76
USC00519281 2011-06-10 00:00:00 0.03 79
USC00519281 2011-06-11 00:00:00 0.03 78
USC00519281 2011-06-12 00:00:00 0.32 82
USC00519281 2011-06-13 00:00:00 0.05 79
USC00519281 2011-06-14 00:00:00 0.16 76
USC00519281 2011-06-15 00:00:00 0.0 74
USC00519281 2011-06-16 00:00:00 0.06 74
USC00519281 2011-06-17 00:00:00 0.03 73
USC00519281 2011-06-18 00:00:00 0.01 79
USC00519281 2011-06-19 00:00:00 0.14 77
USC00519281 2011-06-20 00:00:00 0.05 73
USC00519281 2011-06-21 00:00:00 0.57 72
USC00519281 2011-06-22 00:00:00 0.61 72
USC00519281 2011-06-23 00:00:00 0.06 73
USC00519281 2011-06-24 00:00:00 0.81 74
USC00519281 2011-06-25 00:00:00 0.01 77
USC00519281 2011-06-26 00:00:00 0.11 73
USC00519281 2011-06-27 00:00:00 0.09 73
USC00519281 2011-06-28 00:00:00 0.12 72
USC00519281 2011-06-29 00:00:00 0.08 72
USC00519281 2011-06-30 00:00:00 0.03 67
USC00519281 2011-07-01 00:00:00 0.02 72
USC00519281 2011-07-02 00:00:00 0.02 75
USC00519281 2011-07-03 00:00:00 0.0 76
USC00519281 2011-07-04 00:00:00 0.02 76
USC00519281 2011-07-05 00:00:00 0.06 77
USC00519281 2011-07-06 00:00:00 0.03 73
USC00519281 2011-07-07 00:00:00 0.15 72
USC00519281 2011-07-08 00:00:00 0.09 74
USC00519281 2011-07-09 00:00:00 0.05 79
USC00519281 2011-07-10 00:00:00 0.04 77
USC00519281 2011-07-11 00:00:00 0.08 71
USC00519281 2011-07-12 00:00:00 0.01 72
USC00519281 2011-07-13 00:00:00 0.01 73
USC00519281 2011-07-14 00:00:00 0.06 72
USC00519281 2011-07-15 00:00:00 0.22 72
USC00519281 2011-07-16 00:00:00 0.05 75
USC00519281 2011-07-17 00:00:00 0.17 77
USC00519281 2011-07-18 00:00:00 0.04 73
USC00519281 2011-07-19 00:00:00 0.0 73
USC00519281 2011-07-20 00:00:00 0.06 71
USC00519281 2011-07-21 00:00:00 0.28 73
USC00519281 2011-07-22 00:00:00 0.12 74
USC00519281 2011-07-23 00:00:00 0.01 79
USC00519281 2011-07-24 00:00:00 0.02 77
USC00519281 2011-07-25 00:00:00 0.24 69
USC00519281 2011-07-26 00:00:00 0.02 73
USC00519281 2011-07-27 00:00:00 0.25 73
USC00519281 2011-07-28 00:00:00 0.09 73
USC00519281 2011-07-29 00:00:00 0.07 72
USC00519281 2011-07-30 00:00:00 0.85 77
USC00519281 2011-07-31 00:00:00 0.0 76
USC00519281 2011-08-01 00:00:00 0.0 73
USC00519281 2011-08-02 00:00:00 0.08 74
USC00519281 2011-08-03 00:00:00 0.05 77
USC00519281 2011-08-04 00:00:00 0.12 75
USC00519281 2011-08-05 00:00:00 0.07 75
USC00519281 2011-08-06 00:00:00 0.02 78
USC00519281 2011-08-07 00:00:00 0.08 79
USC00519281 2011-08-08 00:00:00 0.0 78
USC00519281 2011-08-09 00:00:00 0.42 73
USC00519281 2011-08-10 00:00:00 0.01 79
USC00519281 2011-08-11 00:00:00 0.0 80
USC00519281 2011-08-12 00:00:00 0.02 78
USC00519281 2011-08-13 00:00:00 0.11 73
USC00519281 2011-08-14 00:00:00 0.08 77
USC00519281 2011-08-15 00:00:00 0.01 80
USC00519281 2011-08-16 00:00:00 0.05 77
USC00519281 2011-08-17 00:00:00 0.05 77
USC00519281 2011-08-18 00:00:00 0.0 77
USC00519281 2011-08-19 00:00:00 0.04 78
USC00519281 2011-08-20 00:00:00 0.07 81
USC00519281 2011-08-21 00:00:00 0.25 75
USC00519281 2011-08-22 00:00:00 0.18 75
USC00519281 2011-08-23 00:00:00 0.17 76
USC00519281 2011-08-24 00:00:00 0.03 75
USC00519281 2011-08-25 00:00:00 0.01 79
USC00519281 2011-08-26 00:00:00 0.04 78
USC00519281 2011-08-27 00:00:00 0.03 78
USC00519281 2011-08-28 00:00:00 0.41 78
USC00519281 2011-08-29 00:00:00 0.07 78
USC00519281 2011-08-30 00:00:00 0.17 76
USC00519281 2011-08-31 00:00:00 0.07 77
USC00519281 2011-09-01 00:00:00 0.09 81
USC00519281 2011-09-02 00:00:00 0.14 78
USC00519281 2011-09-03 00:00:00 0.0 78
USC00519281 2011-09-04 00:00:00 0.0 80
USC00519281 2011-09-05 00:00:00 0.03 77
USC00519281 2011-09-06 00:00:00 0.03 70
USC00519281 2011-09-07 00:00:00 0.0 67
USC00519281 2011-09-08 00:00:00 0.08 68
USC00519281 2011-09-09 00:00:00 0.0 71
USC00519281 2011-09-10 00:00:00 0.36 70
USC00519281 2011-09-11 00:00:00 0.18 77
USC00519281 2011-09-12 00:00:00 0.0 72
USC00519281 2011-09-13 00:00:00 0.01 70
USC00519281 2011-09-14 00:00:00 0.11 71
USC00519281 2011-09-15 00:00:00 0.09 73
USC00519281 2011-09-16 00:00:00 1.25 74
USC00519281 2011-09-17 00:00:00 0.09 74
USC00519281 2011-09-18 00:00:00 0.42 76
USC00519281 2011-09-19 00:00:00 0.14 74
USC00519281 2011-09-20 00:00:00 0.03 74
USC00519281 2011-09-21 00:00:00 0.02 74
USC00519281 2011-09-22 00:00:00 0.16 70
USC00519281 2011-09-23 00:00:00 0.0 72
USC00519281 2011-09-24 00:00:00 0.02 79
USC00519281 2011-09-25 00:00:00 0.0 73
USC00519281 2011-09-26 00:00:00 0.0 66
USC00519281 2011-09-27 00:00:00 0.0 69
USC00519281 2011-09-28 00:00:00 0.1 72
USC00519281 2011-09-29 00:00:00 0.03 73
USC00519281 2011-09-30 00:00:00 0.08 71
USC00519281 2011-10-01 00:00:00 0.01 77
USC00519281 2011-10-02 00:00:00 0.0 77

USC00519281 2011-10-03 00:00:00 0.0 74
USC00519281 2011-10-04 00:00:00 0.05 73
USC00519281 2011-10-05 00:00:00 0.14 74
USC00519281 2011-10-06 00:00:00 0.02 71
USC00519281 2011-10-07 00:00:00 0.15 74
USC00519281 2011-10-08 00:00:00 0.13 75
USC00519281 2011-10-09 00:00:00 0.07 73
USC00519281 2011-10-10 00:00:00 0.0 73
USC00519281 2011-10-11 00:00:00 0.08 71
USC00519281 2011-10-12 00:00:00 0.01 68
USC00519281 2011-10-13 00:00:00 0.06 69
USC00519281 2011-10-14 00:00:00 0.01 71
USC00519281 2011-10-15 00:00:00 0.22 75
USC00519281 2011-10-16 00:00:00 0.06 74
USC00519281 2011-10-17 00:00:00 0.0 68
USC00519281 2011-10-18 00:00:00 0.01 67
USC00519281 2011-10-19 00:00:00 0.38 67
USC00519281 2011-10-20 00:00:00 0.13 69
USC00519281 2011-10-21 00:00:00 0.0 73
USC00519281 2011-10-22 00:00:00 0.34 71
USC00519281 2011-10-23 00:00:00 1.48 72
USC00519281 2011-10-24 00:00:00 2.4 69
USC00519281 2011-10-25 00:00:00 0.03 71
USC00519281 2011-10-26 00:00:00 0.0 71
USC00519281 2011-10-27 00:00:00 0.0 69
USC00519281 2011-10-28 00:00:00 0.3 69
USC00519281 2011-10-29 00:00:00 0.09 71
USC00519281 2011-10-30 00:00:00 0.03 70
USC00519281 2011-10-31 00:00:00 0.55 69
USC00519281 2011-11-01 00:00:00 1.68 75
USC00519281 2011-11-02 00:00:00 0.03 72
USC00519281 2011-11-03 00:00:00 0.29 72
USC00519281 2011-11-04 00:00:00 1.27 71
USC00519281 2011-11-05 00:00:00 0.1 73
USC00519281 2011-11-06 00:00:00 0.12 75
USC00519281 2011-11-07 00:00:00 0.05 71
USC00519281 2011-11-08 00:00:00 0.08 71
USC00519281 2011-11-09 00:00:00 0.06 71
USC00519281 2011-11-10 00:00:00 0.0 71
USC00519281 2011-11-11 00:00:00 0.0 70
USC00519281 2011-11-12 00:00:00 0.02 73
USC00519281 2011-11-13 00:00:00 0.08 71
USC00519281 2011-11-14 00:00:00 0.01 68
USC00519281 2011-11-15 00:00:00 0.0 68
USC00519281 2011-11-16 00:00:00 0.0 70
USC00519281 2011-11-17 00:00:00 0.01 71
USC00519281 2011-11-18 00:00:00 0.04 73
USC00519281 2011-11-19 00:00:00 0.26 74
USC00519281 2011-11-20 00:00:00 0.06 72
USC00519281 2011-11-21 00:00:00 0.22 71
USC00519281 2011-11-22 00:00:00 0.05 70
USC00519281 2011-11-23 00:00:00 0.01 72
USC00519281 2011-11-24 00:00:00 0.0 72
USC00519281 2011-11-25 00:00:00 0.0 70
USC00519281 2011-11-26 00:00:00 0.0 73
USC00519281 2011-11-27 00:00:00 0.01 71
USC00519281 2011-11-28 00:00:00 0.0 69
USC00519281 2011-11-29 00:00:00 0.01 67
USC00519281 2011-11-30 00:00:00 0.54 68
USC00519281 2011-12-01 00:00:00 0.05 67
USC00519281 2011-12-02 00:00:00 0.29 69
USC00519281 2011-12-03 00:00:00 0.07 72
USC00519281 2011-12-04 00:00:00 0.02 74
USC00519281 2011-12-05 00:00:00 0.01 71
USC00519281 2011-12-06 00:00:00 0.0 70
USC00519281 2011-12-07 00:00:00 0.05 68
USC00519281 2011-12-08 00:00:00 0.0 70
USC00519281 2011-12-09 00:00:00 0.1 66
USC00519281 2011-12-10 00:00:00 0.23 72
USC00519281 2011-12-11 00:00:00 1.16 70
USC00519281 2011-12-12 00:00:00 0.65 70
USC00519281 2011-12-13 00:00:00 1.02 70
USC00519281 2011-12-14 00:00:00 0.07 70
USC00519281 2011-12-15 00:00:00 0.3 73
USC00519281 2011-12-16 00:00:00 0.03 71
USC00519281 2011-12-17 00:00:00 0.38 69
USC00519281 2011-12-18 00:00:00 0.1 73
USC00519281 2011-12-19 00:00:00 0.29 72
USC00519281 2011-12-20 00:00:00 0.01 71
USC00519281 2011-12-21 00:00:00 0.58 69
USC00519281 2011-12-22 00:00:00 0.11 70
USC00519281 2011-12-23 00:00:00 0.12 69
USC00519281 2011-12-24 00:00:00 0.11 70
USC00519281 2011-12-25 00:00:00 0.04 75
USC00519281 2011-12-26 00:00:00 0.0 71
USC00519281 2011-12-27 00:00:00 0.05 70
USC00519281 2011-12-28 00:00:00 0.02 69
USC00519281 2011-12-29 00:00:00 0.0 71
USC00519281 2011-12-30 00:00:00 0.01 65
USC00519281 2011-12-31 00:00:00 0.1 67
USC00519281 2012-01-01 00:00:00 0.05 71
USC00519281 2012-01-02 00:00:00 0.15 71
USC00519281 2012-01-03 00:00:00 0.0 63
USC00519281 2012-01-04 00:00:00 0.0 68
USC00519281 2012-01-05 00:00:00 0.05 70
USC00519281 2012-01-06 00:00:00 0.0 66
USC00519281 2012-01-07 00:00:00 0.0 71
USC00519281 2012-01-08 00:00:00 0.0 63
USC00519281 2012-01-09 00:00:00 0.03 65
USC00519281 2012-01-10 00:00:00 0.0 69
USC00519281 2012-01-11 00:00:00 0.0 67
USC00519281 2012-01-12 00:00:00 0.07 62
USC00519281 2012-01-13 00:00:00 0.0 66
USC00519281 2012-01-14 00:00:00 0.0 64
USC00519281 2012-01-15 00:00:00 0.0 74
USC00519281 2012-01-16 00:00:00 0.46 73
USC00519281 2012-01-17 00:00:00 0.08 74
USC00519281 2012-01-18 00:00:00 0.01 75
USC00519281 2012-01-19 00:00:00 0.01 71
USC00519281 2012-01-20 00:00:00 0.0 66
USC00519281 2012-01-21 00:00:00 0.0 73
USC00519281 2012-01-22 00:00:00 0.0 72
USC00519281 2012-01-23 00:00:00 0.24 64
USC00519281 2012-01-24 00:00:00 0.0 61
USC00519281 2012-01-25 00:00:00 1.67 68
USC00519281 2012-01-26 00:00:00 0.0 72
USC00519281 2012-01-27 00:00:00 0.0 72
USC00519281 2012-01-28 00:00:00 0.17 73
USC00519281 2012-01-29 00:00:00 0.05 73
USC00519281 2012-01-30 00:00:00 0.14 63
USC00519281 2012-01-31 00:00:00 0.01 67
USC00519281 2012-02-01 00:00:00 0.0 63
USC00519281 2012-02-02 00:00:00 0.0 68
USC00519281 2012-02-03 00:00:00 0.0 61
USC00519281 2012-02-04 00:00:00 0.0 72
USC00519281 2012-02-05 00:00:00 0.0 71
USC00519281 2012-02-06 00:00:00 0.0 66
USC00519281 2012-02-07 00:00:00 0.62 70
USC00519281 2012-02-08 00:00:00 0.49 61
USC00519281 2012-02-09 00:00:00 0.01 60
USC00519281 2012-02-10 00:00:00 0.0 63
USC00519281 2012-02-11 00:00:00 0.0 70
USC00519281 2012-02-12 00:00:00 0.0 72
USC00519281 2012-02-13 00:00:00 0.02 70
USC00519281 2012-02-14 00:00:00 0.0 67
USC00519281 2012-02-15 00:00:00 0.01 66
USC00519281 2012-02-16 00:00:00 0.0 71
USC00519281 2012-02-17 00:00:00 0.04 69
USC00519281 2012-02-18 00:00:00 0.12 70
USC00519281 2012-02-19 00:00:00 0.6 69
USC00519281 2012-02-20 00:00:00 0.0 73
USC00519281 2012-02-21 00:00:00 0.0 71
USC00519281 2012-02-22 00:00:00 0.03 70
USC00519281 2012-02-23 00:00:00 0.19 70
USC00519281 2012-02-24 00:00:00 0.05 69
USC00519281 2012-02-25 00:00:00 0.0 71
USC00519281 2012-02-26 00:00:00 0.85 70
USC00519281 2012-02-27 00:00:00 0.02 69
USC00519281 2012-02-28 00:00:00 0.05 70
USC00519281 2012-02-29 00:00:00 0.04 70
USC00519281 2012-03-01 00:00:00 0.0 71
USC00519281 2012-03-02 00:00:00 0.0 68
USC00519281 2012-03-03 00:00:00 4.68 71
USC00519281 2012-03-04 00:00:00 0.07 69
USC00519281 2012-03-05 00:00:00 6.24 65
USC00519281 2012-03-06 00:00:00 2.59 66
USC00519281 2012-03-07 00:00:00 1.68 66
USC00519281 2012-03-08 00:00:00 0.53 68
USC00519281 2012-03-09 00:00:00 1.44 68
USC00519281 2012-03-10 00:00:00 3.47 73
USC00519281 2012-03-11 00:00:00 0.14 72
USC00519281 2012-03-12 00:00:00 0.23 70
USC00519281 2012-03-13 00:00:00 0.0 69
USC00519281 2012-03-14 00:00:00 0.02 69
USC00519281 2012-03-15 00:00:00 0.0 68
USC00519281 2012-03-16 00:00:00 0.04 70
USC00519281 2012-03-17 00:00:00 0.02 75
USC00519281 2012-03-18 00:00:00 0.1 69
USC00519281 2012-03-19 00:00:00 0.29 69
USC00519281 2012-03-20 00:00:00 0.12 64
USC00519281 2012-03-21 00:00:00 0.0 68
USC00519281 2012-03-22 00:00:00 0.2 68
USC00519281 2012-03-23 00:00:00 0.01 69
USC00519281 2012-03-24 00:00:00 0.12 72
USC00519281 2012-03-25 00:00:00 0.32 70
USC00519281 2012-03-26 00:00:00 0.1 70
USC00519281 2012-03-27 00:00:00 0.06 66
USC00519281 2012-03-28 00:00:00 0.0 66
USC00519281 2012-03-29 00:00:00 0.0 67
USC00519281 2012-03-30 00:00:00 0.02 68
USC00519281 2012-03-31 00:00:00 0.0 73
USC00519281 2012-04-01 00:00:00 0.0 75
USC00519281 2012-04-02 00:00:00 0.0 67
USC00519281 2012-04-03 00:00:00 0.0 66
USC00519281 2012-04-04 00:00:00 0.06 69
USC00519281 2012-04-05 00:00:00 0.11 71
USC00519281 2012-04-06 00:00:00 0.0 75
USC00519281 2012-04-07 00:00:00 0.16 73
USC00519281 2012-04-08 00:00:00 0.02 74
USC00519281 2012-04-09 00:00:00 0.22 68
USC00519281 2012-04-10 00:00:00 0.73 65
USC00519281 2012-04-11 00:00:00 0.43 65
USC00519281 2012-04-12 00:00:00 0.47 68
USC00519281 2012-04-13 00:00:00 0.37 64
USC00519281 2012-04-14 00:00:00 0.01 76
USC00519281 2012-04-15 00:00:00 0.04 68
USC00519281 2012-04-16 00:00:00 0.05 71
USC00519281 2012-04-17 00:00:00 0.0 71
USC00519281 2012-04-18 00:00:00 0.0 71
USC00519281 2012-04-19 00:00:00 0.0 71
USC00519281 2012-04-20 00:00:00 0.02 70
USC00519281 2012-04-21 00:00:00 0.0 75
USC00519281 2012-04-22 00:00:00 0.19 70
USC00519281 2012-04-23 00:00:00 0.16 69
USC00519281 2012-04-24 00:00:00 0.01 69
USC00519281 2012-04-25 00:00:00 0.02 67
USC00519281 2012-04-26 00:00:00 0.02 70
USC00519281 2012-04-27 00:00:00 0.38 67
USC00519281 2012-04-28 00:00:00 0.12 77
USC00519281 2012-04-29 00:00:00 0.0 74
USC00519281 2012-04-30 00:00:00 0.05 71
USC00519281 2012-05-01 00:00:00 0.0 70
USC00519281 2012-05-02 00:00:00 0.18 70
USC00519281 2012-05-03 00:00:00 0.14 70
USC00519281 2012-05-04 00:00:00 0.18 70
USC00519281 2012-05-05 00:00:00 0.18 75
USC00519281 2012-05-06 00:00:00 0.01 74
USC00519281 2012-05-07 00:00:00 0.06 71
USC00519281 2012-05-08 00:00:00 0.02 71
USC00519281 2012-05-09 00:00:00 0.01 69
USC00519281 2012-05-10 00:00:00 0.0 76
USC00519281 2012-05-11 00:00:00 0.06 76
USC00519281 2012-05-12 00:00:00 0.0 77
USC00519281 2012-05-13 00:00:00 0.0 74
USC00519281 2012-05-14 00:00:00 0.0 77
USC00519281 2012-05-15 00:00:00 0.0 63
USC00519281 2012-05-16 00:00:00 0.01 69
USC00519281 2012-05-17 00:00:00 0.02 72
USC00519281 2012-05-18 00:00:00 0.05 72
USC00519281 2012-05-19 00:00:00 0.16 76
USC00519281 2012-05-20 00:00:00 0.0 78
USC00519281 2012-05-21 00:00:00 0.08 71
USC00519281 2012-05-22 00:00:00 0.0 70
USC00519281 2012-05-23 00:00:00 0.0 73
USC00519281 2012-05-24 00:00:00 0.01 73
USC00519281 2012-05-25 00:00:00 0.02 71
USC00519281 2012-05-26 00:00:00 0.08 74
USC00519281 2012-05-27 00:00:00 0.02 74
USC00519281 2012-05-28 00:00:00 0.06 75
USC00519281 2012-05-29 00:00:00 0.0 72
USC00519281 2012-05-30 00:00:00 0.01 71
USC00519281 2012-05-31 00:00:00 0.02 71
USC00519281 2012-06-01 00:00:00 0.02 71
USC00519281 2012-06-02 00:00:00 0.08 73
USC00519281 2012-06-03 00:00:00 0.0 78
USC00519281 2012-06-04 00:00:00 0.0 71
USC00519281 2012-06-05 00:00:00 0.0 72
USC00519281 2012-06-06 00:00:00 0.1 70
USC00519281 2012-06-07 00:00:00 0.07 72
USC00519281 2012-06-08 00:00:00 0.01 73
USC00519281 2012-06-09 00:00:00 0.0 74
USC00519281 2012-06-10 00:00:00 0.0 81
USC00519281 2012-06-11 00:00:00 0.11 72
USC00519281 2012-06-12 00:00:00 0.16 77
USC00519281 2012-06-13 00:00:00 0.07 69
USC00519281 2012-06-14 00:00:00 0.21 69
USC00519281 2012-06-15 00:00:00 0.0 69
USC00519281 2012-06-16 00:00:00 0.0 78
USC00519281 2012-06-17 00:00:00 0.02 78
USC00519281 2012-06-18 00:00:00 0.0 73
USC00519281 2012-06-19 00:00:00 0.02 72
USC00519281 2012-06-20 00:00:00 0.33 71
USC00519281 2012-06-21 00:00:00 0.26 72
USC00519281 2012-06-22 00:00:00 0.03 72
USC00519281 2012-06-23 00:00:00 0.35 73
USC00519281 2012-06-24 00:00:00 0.14 71
USC00519281 2012-06-25 00:00:00 0.13 70
USC00519281 2012-06-26 00:00:00 0.22 71
USC00519281 2012-06-27 00:00:00 0.43 68
USC00519281 2012-06-28 00:00:00 0.01 72
USC00519281 2012-06-29 00:00:00 0.14 71
USC00519281 2012-06-30 00:00:00 0.01 78
USC00519281 2012-07-01 00:00:00 0.14 77
USC00519281 2012-07-02 00:00:00 0.23 73
USC00519281 2012-07-03 00:00:00 0.55 71
USC00519281 2012-07-04 00:00:00 0.3 74
USC00519281 2012-07-05 00:00:00 0.18 76
USC00519281 2012-07-06 00:00:00 0.14 76
USC00519281 2012-07-07 00:00:00 0.21 74
USC00519281 2012-07-08 00:00:00 0.0 77
USC00519281 2012-07-09 00:00:00 0.0 73
USC00519281 2012-07-10 00:00:00 0.01 71
USC00519281 2012-07-11 00:00:00 0.01 71
USC00519281 2012-07-12 00:00:00 0.0 72
USC00519281 2012-07-13 00:00:00 0.23 72
USC00519281 2012-07-14 00:00:00 0.14 73
USC00519281 2012-07-15 00:00:00 0.02 80
USC00519281 2012-07-16 00:00:00 0.13 72
USC00519281 2012-07-17 00:00:00 0.21 72
USC00519281 2012-07-18 00:00:00 0.12 73
USC00519281 2012-07-19 00:00:00 0.13 72
USC00519281 2012-07-20 00:00:00 0.08 69
USC00519281 2012-07-21 00:00:00 0.23 69
USC00519281 2012-07-22 00:00:00 0.03 75
USC00519281 2012-07-23 00:00:00 0.18 72
USC00519281 2012-07-24 00:00:00 0.01 73
USC00519281 2012-07-25 00:00:00 0.04 73
USC00519281 2012-07-26 00:00:00 0.0 72
USC00519281 2012-07-27 00:00:00 0.0 71
USC00519281 2012-07-28 00:00:00 0.42 73
USC00519281 2012-07-29 00:00:00 0.24 72
USC00519281 2012-07-30 00:00:00 0.12 73
USC00519281 2012-07-31 00:00:00 0.09 74
USC00519281 2012-08-01 00:00:00 0.0 75
USC00519281 2012-08-02 00:00:00 0.0 71
USC00519281 2012-08-03 00:00:00 0.0 73
USC00519281 2012-08-04 00:00:00 0.02 74
USC00519281 2012-08-05 00:00:00 0.18 75
USC00519281 2012-08-06 00:00:00 0.0 70
USC00519281 2012-08-07 00:00:00 0.04 74
USC00519281 2012-08-08 00:00:00 0.01 72
USC00519281 2012-08-09 00:00:00 0.04 74
USC00519281 2012-08-10 00:00:00 0.01 72
USC00519281 2012-08-11 00:00:00 0.11 75
USC00519281 2012-08-12 00:00:00 0.07 74
USC00519281 2012-08-13 00:00:00 0.01 74
USC00519281 2012-08-14 00:00:00 0.03 73
USC00519281 2012-08-15 00:00:00 0.0 74
USC00519281 2012-08-16 00:00:00 0.01 82
USC00519281 2012-08-17 00:00:00 0.0 72
USC00519281 2012-08-18 00:00:00 0.28 77
USC00519281 2012-08-19 00:00:00 0.04 73
USC00519281 2012-08-20 00:00:00 0.02 73
USC00519281 2012-08-21 00:00:00 0.0 73
USC00519281 2012-08-22 00:00:00 0.68 71
USC00519281 2012-08-23 00:00:00 0.06 74
USC00519281 2012-08-24 00:00:00 0.01 73
USC00519281 2012-08-25 00:00:00 0.0 75
USC00519281 2012-08-26 00:00:00 0.0 82
USC00519281 2012-08-27 00:00:00 0.03 73
USC00519281 2012-08-28 00:00:00 0.76 79
USC00519281 2012-08-29 00:00:00 0.3 72
USC00519281 2012-08-30 00:00:00 0.32 77
USC00519281 2012-08-31 00:00:00 0.03 76
USC00519281 2012-09-01 00:00:00 0.02 73
USC00519281 2012-09-02 00:00:00 0.33 78
USC00519281 2012-09-03 00:00:00 0.07 77
USC00519281 2012-09-04 00:00:00 0.02 76
USC00519281 2012-09-05 00:00:00 0.06 73
USC00519281 2012-09-06 00:00:00 0.06 75
USC00519281 2012-09-07 00:00:00 0.13 75
USC00519281 2012-09-08 00:00:00 0.05 73
USC00519281 2012-09-09 00:00:00 0.29 75
USC00519281 2012-09-10 00:00:00 0.43 75
USC00519281 2012-09-11 00:00:00 0.2 71
USC00519281 2012-09-12 00:00:00 0.03 73
USC00519281 2012-09-13 00:00:00 0.0 75
USC00519281 2012-09-14 00:00:00 0.1 74
USC00519281 2012-09-15 00:00:00 0.09 76
USC00519281 2012-09-16 00:00:00 0.14 74
USC00519281 2012-09-17 00:00:00 0.01 76
USC00519281 2012-09-18 00:00:00 0.0 70
USC00519281 2012-09-19 00:00:00 0.53 73
USC00519281 2012-09-20 00:00:00 0.39 73
USC00519281 2012-09-21 00:00:00 0.73 76
USC00519281 2012-09-22 00:00:00 0.0 73
USC00519281 2012-09-23 00:00:00 0.06 74
USC00519281 2012-09-24 00:00:00 0.15 75
USC00519281 2012-09-25 00:00:00 0.05 74
USC00519281 2012-09-26 00:00:00 0.02 74
USC00519281 2012-09-27 00:00:00 0.0 75
USC00519281 2012-09-28 00:00:00 0.1 75
USC00519281 2012-09-29 00:00:00 0.02 72
USC00519281 2012-09-30 00:00:00 0.01 73
USC00519281 2012-10-01 00:00:00 0.12 70
USC00519281 2012-10-02 00:00:00 0.12 71
USC00519281 2012-10-03 00:00:00 0.0 70
USC00519281 2012-10-04 00:00:00 0.0 69
USC00519281 2012-10-05 00:00:00 0.0 67
USC00519281 2012-10-06 00:00:00 0.0 70
USC00519281 2012-10-07 00:00:00 0.0 72
USC00519281 2012-10-08 00:00:00 0.12 74
USC00519281 2012-10-09 00:00:00 0.01 74
USC00519281 2012-10-10 00:00:00 0.0 69
USC00519281 2012-10-11 00:00:00 0.05 74

USC00519281 2012-10-12 00:00:00 0.0 71
USC00519281 2012-10-13 00:00:00 0.0 76
USC00519281 2012-10-14 00:00:00 0.04 75
USC00519281 2012-10-15 00:00:00 0.23 72
USC00519281 2012-10-16 00:00:00 0.03 72
USC00519281 2012-10-17 00:00:00 0.23 68
USC00519281 2012-10-18 00:00:00 0.03 69
USC00519281 2012-10-19 00:00:00 0.09 73
USC00519281 2012-10-20 00:00:00 0.0 77
USC00519281 2012-10-21 00:00:00 0.12 76
USC00519281 2012-10-22 00:00:00 0.0 73
USC00519281 2012-10-23 00:00:00 0.0 77
USC00519281 2012-10-24 00:00:00 0.02 72
USC00519281 2012-10-25 00:00:00 0.28 71
USC00519281 2012-10-26 00:00:00 0.01 68
USC00519281 2012-10-27 00:00:00 0.0 73
USC00519281 2012-10-28 00:00:00 0.09 75
USC00519281 2012-10-29 00:00:00 0.04 72
USC00519281 2012-10-30 00:00:00 0.03 71
USC00519281 2012-10-31 00:00:00 0.05 71
USC00519281 2012-11-01 00:00:00 0.04 65
USC00519281 2012-11-02 00:00:00 0.0 64
USC00519281 2012-11-03 00:00:00 0.0 74
USC00519281 2012-11-04 00:00:00 0.0 65
USC00519281 2012-11-05 00:00:00 0.0 64
USC00519281 2012-11-06 00:00:00 0.13 74
USC00519281 2012-11-07 00:00:00 0.24 72
USC00519281 2012-11-08 00:00:00 0.01 72
USC00519281 2012-11-09 00:00:00 0.08 73
USC00519281 2012-11-10 00:00:00 0.07 72
USC00519281 2012-11-11 00:00:00 0.0 74
USC00519281 2012-11-12 00:00:00 0.0 73
USC00519281 2012-11-13 00:00:00 0.02 73
USC00519281 2012-11-14 00:00:00 0.12 73
USC00519281 2012-11-15 00:00:00 0.11 71
USC00519281 2012-11-16 00:00:00 0.17 68
USC00519281 2012-11-17 00:00:00 0.13 69
USC00519281 2012-11-18 00:00:00 0.19 75
USC00519281 2012-11-19 00:00:00 0.19 71
USC00519281 2012-11-20 00:00:00 0.0 72
USC00519281 2012-11-21 00:00:00 0.0 69
USC00519281 2012-11-22 00:00:00 0.2 65
USC00519281 2012-11-23 00:00:00 0.02 66
USC00519281 2012-11-24 00:00:00 0.06 74
USC00519281 2012-11-25 00:00:00 0.01 71
USC00519281 2012-11-26 00:00:00 0.0 73
USC00519281 2012-11-27 00:00:00 0.0 70
USC00519281 2012-11-28 00:00:00 0.0 63
USC00519281 2012-11-29 00:00:00 0.0 62
USC00519281 2012-11-30 00:00:00 0.01 61
USC00519281 2012-12-01 00:00:00 0.0 72
USC00519281 2012-12-02 00:00:00 0.0 67
USC00519281 2012-12-03 00:00:00 0.0 76
USC00519281 2012-12-04 00:00:00 0.02 67
USC00519281 2012-12-05 00:00:00 0.32 72
USC00519281 2012-12-06 00:00:00 0.01 69
USC00519281 2012-12-07 00:00:00 0.0 66
USC00519281 2012-12-08 00:00:00 0.0 75
USC00519281 2012-12-09 00:00:00 0.0 74
USC00519281 2012-12-10 00:00:00 0.08 72
USC00519281 2012-12-11 00:00:00 0.0 72
USC00519281 2012-12-12 00:00:00 0.02 72
USC00519281 2012-12-13 00:00:00 0.13 68
USC00519281 2012-12-14 00:00:00 0.25 74
USC00519281 2012-12-15 00:00:00 0.21 73
USC00519281 2012-12-16 00:00:00 0.08 73
USC00519281 2012-12-17 00:00:00 0.14 72
USC00519281 2012-12-18 00:00:00 0.46 70
USC00519281 2012-12-19 00:00:00 0.25 70
USC00519281 2012-12-20 00:00:00 0.34 71
USC00519281 2012-12-21 00:00:00 0.05 70
USC00519281 2012-12-22 00:00:00 0.01 72
USC00519281 2012-12-23 00:00:00 0.1 65
USC00519281 2012-12-24 00:00:00 0.0 62
USC00519281 2012-12-25 00:00:00 0.04 73
USC00519281 2012-12-26 00:00:00 0.0 71
USC00519281 2012-12-27 00:00:00 0.0 70
USC00519281 2012-12-28 00:00:00 0.0 62
USC00519281 2012-12-29 00:00:00 0.01 69
USC00519281 2012-12-30 00:00:00 0.35 69
USC00519281 2012-12-31 00:00:00 0.42 66
USC00519281 2013-01-01 00:00:00 0.36 70
USC00519281 2013-01-02 00:00:00 0.19 69
USC00519281 2013-01-03 00:00:00 0.71 69
USC00519281 2013-01-04 00:00:00 0.26 69
USC00519281 2013-01-05 00:00:00 0.19 71
USC00519281 2013-01-06 00:00:00 0.25 72
USC00519281 2013-01-07 00:00:00 0.11 70
USC00519281 2013-01-08 00:00:00 0.16 70
USC00519281 2013-01-09 00:00:00 0.58 69
USC00519281 2013-01-10 00:00:00 0.14 68
USC00519281 2013-01-11 00:00:00 0.01 70
USC00519281 2013-01-12 00:00:00 0.13 69
USC00519281 2013-01-13 00:00:00 0.03 72
USC00519281 2013-01-14 00:00:00 0.02 72
USC00519281 2013-01-15 00:00:00 0.88 63
USC00519281 2013-01-16 00:00:00 0.02 54
USC00519281 2013-01-17 00:00:00 0.04 61
USC00519281 2013-01-18 00:00:00 0.0 59
USC00519281 2013-01-19 00:00:00 0.01 72
USC00519281 2013-01-20 00:00:00 0.0 66
USC00519281 2013-01-21 00:00:00 0.0 71
USC00519281 2013-01-22 00:00:00 0.0 69
USC00519281 2013-01-23 00:00:00 0.99 68
USC00519281 2013-01-24 00:00:00 0.97 65
USC00519281 2013-01-25 00:00:00 0.02 70
USC00519281 2013-01-26 00:00:00 0.06 71
USC00519281 2013-01-27 00:00:00 0.06 71
USC00519281 2013-01-28 00:00:00 2.84 65
USC00519281 2013-01-29 00:00:00 1.16 65
USC00519281 2013-01-30 00:00:00 0.13 63
USC00519281 2013-01-31 00:00:00 0.02 68
USC00519281 2013-02-01 00:00:00 0.02 69
USC00519281 2013-02-02 00:00:00 0.0 74
USC00519281 2013-02-03 00:00:00 0.0 66
USC00519281 2013-02-04 00:00:00 0.0 70
USC00519281 2013-02-05 00:00:00 0.02 70
USC00519281 2013-02-06 00:00:00 0.0 70
USC00519281 2013-02-07 00:00:00 0.26 69
USC00519281 2013-02-08 00:00:00 0.07 69
USC00519281 2013-02-09 00:00:00 0.0 67
USC00519281 2013-02-10 00:00:00 0.0 73
USC00519281 2013-02-11 00:00:00 0.14 71
USC00519281 2013-02-12 00:00:00 0.06 68
USC00519281 2013-02-13 00:00:00 0.05 68
USC00519281 2013-02-14 00:00:00 0.0 67
USC00519281 2013-02-15 00:00:00 0.01 70
USC00519281 2013-02-16 00:00:00 0.06 70
USC00519281 2013-02-17 00:00:00 0.0 71
USC00519281 2013-02-18 00:00:00 0.0 71
USC00519281 2013-02-19 00:00:00 0.06 72
USC00519281 2013-02-20 00:00:00 0.29 72
USC00519281 2013-02-21 00:00:00 0.14 69
USC00519281 2013-02-22 00:00:00 1.02 69
USC00519281 2013-02-23 00:00:00 0.43 69
USC00519281 2013-02-24 00:00:00 0.24 70
USC00519281 2013-02-25 00:00:00 0.01 71
USC00519281 2013-02-26 00:00:00 0.24 70
USC00519281 2013-02-27 00:00:00 0.01 72
USC00519281 2013-02-28 00:00:00 0.0 70
USC00519281 2013-03-01 00:00:00 0.03 71
USC00519281 2013-03-02 00:00:00 0.0 70
USC00519281 2013-03-03 00:00:00 0.0 70
USC00519281 2013-03-04 00:00:00 0.0 68
USC00519281 2013-03-05 00:00:00 0.0 71
USC00519281 2013-03-06 00:00:00 0.0 70
USC00519281 2013-03-07 00:00:00 0.08 73
USC00519281 2013-03-08 00:00:00 0.01 71
USC00519281 2013-03-09 00:00:00 0.01 74
USC00519281 2013-03-10 00:00:00 2.25 68
USC00519281 2013-03-11 00:00:00 1.48 62
USC00519281 2013-03-12 00:00:00 0.01 64
USC00519281 2013-03-13 00:00:00 0.04 68
USC00519281 2013-03-14 00:00:00 0.0 66
USC00519281 2013-03-15 00:00:00 0.0 66
USC00519281 2013-03-16 00:00:00 0.0 66
USC00519281 2013-03-17 00:00:00 0.0 64
USC00519281 2013-03-18 00:00:00 0.0 62
USC00519281 2013-03-19 00:00:00 0.0 67
USC00519281 2013-03-20 00:00:00 0.0 67
USC00519281 2013-03-21 00:00:00 0.0 63
USC00519281 2013-03-22 00:00:00 0.09 74
USC00519281 2013-03-23 00:00:00 0.16 69
USC00519281 2013-03-24 00:00:00 0.86 68
USC00519281 2013-03-25 00:00:00 1.03 69
USC00519281 2013-03-26 00:00:00 0.02 70
USC00519281 2013-03-27 00:00:00 0.04 71
USC00519281 2013-03-28 00:00:00 0.52 70
USC00519281 2013-03-29 00:00:00 0.28 70
USC00519281 2013-03-30 00:00:00 0.18 72
USC00519281 2013-03-31 00:00:00 0.04 62
USC00519281 2013-04-01 00:00:00 0.0 68
USC00519281 2013-04-02 00:00:00 0.02 66
USC00519281 2013-04-03 00:00:00 0.0 72
USC00519281 2013-04-04 00:00:00 0.11 71
USC00519281 2013-04-05 00:00:00 0.0 73
USC00519281 2013-04-06 00:00:00 0.17 73
USC00519281 2013-04-07 00:00:00 0.03 75
USC00519281 2013-04-08 00:00:00 0.0 71
USC00519281 2013-04-09 00:00:00 0.0 71
USC00519281 2013-04-10 00:00:00 0.04 75
USC00519281 2013-04-11 00:00:00 0.02 74
USC00519281 2013-04-12 00:00:00 0.2 73
USC00519281 2013-04-13 00:00:00 0.09 74
USC00519281 2013-04-14 00:00:00 0.01 70
USC00519281 2013-04-15 00:00:00 0.79 70
USC00519281 2013-04-16 00:00:00 0.12 63
USC00519281 2013-04-17 00:00:00 0.0 70
USC00519281 2013-04-18 00:00:00 0.02 71
USC00519281 2013-04-19 00:00:00 0.13 72
USC00519281 2013-04-20 00:00:00 0.59 68
USC00519281 2013-04-21 00:00:00 0.01 76
USC00519281 2013-04-22 00:00:00 0.41 70
USC00519281 2013-04-23 00:00:00 0.08 74
USC00519281 2013-04-24 00:00:00 1.39 68
USC00519281 2013-04-25 00:00:00 0.98 71
USC00519281 2013-04-26 00:00:00 0.01 71
USC00519281 2013-04-27 00:00:00 0.0 75
USC00519281 2013-04-28 00:00:00 0.0 79
USC00519281 2013-04-29 00:00:00 0.0 74
USC00519281 2013-04-30 00:00:00 0.0 67
USC00519281 2013-05-01 00:00:00 0.0 70
USC00519281 2013-05-02 00:00:00 0.0 73
USC00519281 2013-05-03 00:00:00 0.02 70
USC00519281 2013-05-04 00:00:00 0.0 76
USC00519281 2013-05-05 00:00:00 1.95 75
USC00519281 2013-05-06 00:00:00 0.36 69
USC00519281 2013-05-07 00:00:00 0.02 64
USC00519281 2013-05-08 00:00:00 0.0 65
USC00519281 2013-05-09 00:00:00 0.0 67
USC00519281 2013-05-10 00:00:00 0.0 71
USC00519281 2013-05-11 00:00:00 1.57 74
USC00519281 2013-05-12 00:00:00 1.33 71
USC00519281 2013-05-13 00:00:00 3.88 73
USC00519281 2013-05-14 00:00:00 0.08 73
USC00519281 2013-05-15 00:00:00 0.01 74
USC00519281 2013-05-16 00:00:00 0.18 73
USC00519281 2013-05-17 00:00:00 0.01 73
USC00519281 2013-05-18 00:00:00 0.05 81
USC00519281 2013-05-19 00:00:00 0.11 78
USC00519281 2013-05-20 00:00:00 0.14 69
USC00519281 2013-05-21 00:00:00 0.0 69
USC00519281 2013-05-22 00:00:00 0.0 75
USC00519281 2013-05-23 00:00:00 0.0 73
USC00519281 2013-05-24 00:00:00 0.0 74
USC00519281 2013-05-25 00:00:00 0.13 78
USC00519281 2013-05-26 00:00:00 0.03 78
USC00519281 2013-05-27 00:00:00 0.05 79
USC00519281 2013-05-28 00:00:00 0.04 74
USC00519281 2013-05-29 00:00:00 1.87 71
USC00519281 2013-05-30 00:00:00 4.07 74
USC00519281 2013-05-31 00:00:00 0.01 72
USC00519281 2013-06-01 00:00:00 0.06 81
USC00519281 2013-06-02 00:00:00 0.17 74
USC00519281 2013-06-03 00:00:00 0.08 74
USC00519281 2013-06-04 00:00:00 0.0 73
USC00519281 2013-06-05 00:00:00 0.0 73
USC00519281 2013-06-06 00:00:00 0.0 72
USC00519281 2013-06-07 00:00:00 0.0 73
USC00519281 2013-06-08 00:00:00 0.0 77
USC00519281 2013-06-09 00:00:00 0.0 73
USC00519281 2013-06-10 00:00:00 0.01 73
USC00519281 2013-06-11 00:00:00 0.02 75
USC00519281 2013-06-12 00:00:00 0.0 72
USC00519281 2013-06-13 00:00:00 0.1 72
USC00519281 2013-06-14 00:00:00 0.16 73
USC00519281 2013-06-15 00:00:00 0.1 73
USC00519281 2013-06-16 00:00:00 0.03 75
USC00519281 2013-06-17 00:00:00 0.05 72
USC00519281 2013-06-18 00:00:00 0.04 73
USC00519281 2013-06-19 00:00:00 0.01 70
USC00519281 2013-06-20 00:00:00 0.02 69
USC00519281 2013-06-21 00:00:00 0.53 68
USC00519281 2013-06-22 00:00:00 0.88 75
USC00519281 2013-06-23 00:00:00 0.03 74
USC00519281 2013-06-24 00:00:00 0.22 73
USC00519281 2013-06-25 00:00:00 0.36 70
USC00519281 2013-06-26 00:00:00 0.82 70
USC00519281 2013-06-27 00:00:00 0.07 71
USC00519281 2013-06-28 00:00:00 0.04 70
USC00519281 2013-06-29 00:00:00 0.43 70
USC00519281 2013-06-30 00:00:00 0.71 75
USC00519281 2013-07-01 00:00:00 0.0 72
USC00519281 2013-07-02 00:00:00 0.09 71
USC00519281 2013-07-03 00:00:00 0.38 69
USC00519281 2013-07-04 00:00:00 0.12 76
USC00519281 2013-07-05 00:00:00 0.0 66
USC00519281 2013-07-06 00:00:00 0.01 77
USC00519281 2013-07-07 00:00:00 0.0 75
USC00519281 2013-07-08 00:00:00 0.01 75
USC00519281 2013-07-09 00:00:00 0.0 75
USC00519281 2013-07-10 00:00:00 0.12 72
USC00519281 2013-07-11 00:00:00 0.04 74
USC00519281 2013-07-12 00:00:00 0.09 72
USC00519281 2013-07-13 00:00:00 0.07 78
USC00519281 2013-07-14 00:00:00 0.0 78
USC00519281 2013-07-15 00:00:00 0.0 72
USC00519281 2013-07-16 00:00:00 0.02 72
USC00519281 2013-07-17 00:00:00 0.0 74
USC00519281 2013-07-18 00:00:00 0.0 74
USC00519281 2013-07-19 00:00:00 0.1 70
USC00519281 2013-07-20 00:00:00 0.31 78
USC00519281 2013-07-21 00:00:00 0.24 78
USC00519281 2013-07-22 00:00:00 0.0 72
USC00519281 2013-07-23 00:00:00 0.58 73
USC00519281 2013-07-24 00:00:00 0.0 75
USC00519281 2013-07-25 00:00:00 0.0 69
USC00519281 2013-07-26 00:00:00 0.01 72
USC00519281 2013-07-27 00:00:00 0.0 81
USC00519281 2013-07-28 00:00:00 0.02 75
USC00519281 2013-07-29 00:00:00 0.23 78
USC00519281 2013-07-30 00:00:00 0.12 76
USC00519281 2013-07-31 00:00:00 0.4 76
USC00519281 2013-08-01 00:00:00 0.1 76
USC00519281 2013-08-02 00:00:00 0.13 72
USC00519281 2013-08-03 00:00:00 0.11 77
USC00519281 2013-08-04 00:00:00 0.02 78
USC00519281 2013-08-05 00:00:00 0.12 71
USC00519281 2013-08-06 00:00:00 0.09 74
USC00519281 2013-08-07 00:00:00 0.0 72
USC00519281 2013-08-08 00:00:00 0.0 72
USC00519281 2013-08-09 00:00:00 0.2 70
USC00519281 2013-08-10 00:00:00 3.79 71
USC00519281 2013-08-11 00:00:00 1.26 74
USC00519281 2013-08-12 00:00:00 0.09 74
USC00519281 2013-08-13 00:00:00 0.03 75
USC00519281 2013-08-14 00:00:00 0.18 75
USC00519281 2013-08-15 00:00:00 0.0 74
USC00519281 2013-08-16 00:00:00 0.04 71
USC00519281 2013-08-17 00:00:00 0.0 75
USC00519281 2013-08-18 00:00:00 0.0 76
USC00519281 2013-08-19 00:00:00 0.0 70
USC00519281 2013-08-20 00:00:00 0.0 71
USC00519281 2013-08-21 00:00:00 0.67 71
USC00519281 2013-08-22 00:00:00 0.0 72
USC00519281 2013-08-23 00:00:00 0.0 74
USC00519281 2013-08-24 00:00:00 0.02 77
USC00519281 2013-08-25 00:00:00 0.0 77
USC00519281 2013-08-26 00:00:00 0.0 75
USC00519281 2013-08-27 00:00:00 0.0 75
USC00519281 2013-08-28 00:00:00 0.0 70
USC00519281 2013-08-29 00:00:00 0.02 70
USC00519281 2013-08-30 00:00:00 0.04 71
USC00519281 2013-08-31 00:00:00 0.19 78
USC00519281 2013-09-01 00:00:00 0.06 75
USC00519281 2013-09-02 00:00:00 0.0 78
USC00519281 2013-09-03 00:00:00 0.0 72
USC00519281 2013-09-04 00:00:00 0.0 69
USC00519281 2013-09-05 00:00:00 0.0 67
USC00519281 2013-09-06 00:00:00 0.01 68
USC00519281 2013-09-07 00:00:00 0.49 74
USC00519281 2013-09-08 00:00:00 0.18 74
USC00519281 2013-09-09 00:00:00 0.0 81
USC00519281 2013-09-10 00:00:00 0.0 73
USC00519281 2013-09-11 00:00:00 0.02 73
USC00519281 2013-09-12 00:00:00 0.02 70
USC00519281 2013-09-13 00:00:00 1.88 73
USC00519281 2013-09-14 00:00:00 0.5 72
USC00519281 2013-09-15 00:00:00 0.25 75
USC00519281 2013-09-16 00:00:00 0.01 77
USC00519281 2013-09-17 00:00:00 0.23 75
USC00519281 2013-09-18 00:00:00 0.37 71
USC00519281 2013-09-19 00:00:00 0.04 74
USC00519281 2013-09-20 00:00:00 0.0 74
USC00519281 2013-09-21 00:00:00 0.01 77
USC00519281 2013-09-22 00:00:00 0.22 76
USC00519281 2013-09-23 00:00:00 0.02 72
USC00519281 2013-09-24 00:00:00 0.08 74
USC00519281 2013-09-25 00:00:00 0.09 71
USC00519281 2013-09-26 00:00:00 0.42 72
USC00519281 2013-09-27 00:00:00 0.01 72
USC00519281 2013-09-28 00:00:00 0.0 79
USC00519281 2013-09-29 00:00:00 0.0 75
USC00519281 2013-09-30 00:00:00 0.04 67
USC00519281 2013-10-01 00:00:00 0.67 74
USC00519281 2013-10-02 00:00:00 0.01 73
USC00519281 2013-10-03 00:00:00 0.01 78
USC00519281 2013-10-04 00:00:00 0.03 76
USC00519281 2013-10-05 00:00:00 0.03 74
USC00519281 2013-10-06 00:00:00 0.18 71
USC00519281 2013-10-07 00:00:00 0.04 73
USC00519281 2013-10-08 00:00:00 0.09 71
USC00519281 2013-10-09 00:00:00 0.17 75
USC00519281 2013-10-10 00:00:00 0.1 72
USC00519281 2013-10-11 00:00:00 0.18 71
USC00519281 2013-10-12 00:00:00 1.77 70
USC00519281 2013-10-13 00:00:00 0.02 70
USC00519281 2013-10-14 00:00:00 0.44 70
USC00519281 2013-10-15 00:00:00 0.62 70
USC00519281 2013-10-16 00:00:00 0.7 71
USC00519281 2013-10-17 00:00:00 0.17 71
USC00519281 2013-10-18 00:00:00 0.01 67
USC00519281 2013-10-19 00:00:00 0.01 65
USC00519281 2013-10-20 00:00:00 0.04 68
USC00519281 2013-10-21 00:00:00 0.01 66

USC00519281 2013-10-22 00:00:00 0.01 66
USC00519281 2013-10-23 00:00:00 0.05 69
USC00519281 2013-10-24 00:00:00 0.12 71
USC00519281 2013-10-25 00:00:00 0.16 69
USC00519281 2013-10-26 00:00:00 0.32 70
USC00519281 2013-10-27 00:00:00 0.01 81
USC00519281 2013-10-28 00:00:00 0.18 70
USC00519281 2013-10-29 00:00:00 0.04 75
USC00519281 2013-10-30 00:00:00 0.0 68
USC00519281 2013-10-31 00:00:00 0.23 76
USC00519281 2013-11-01 00:00:00 0.02 76
USC00519281 2013-11-02 00:00:00 0.27 76
USC00519281 2013-11-03 00:00:00 0.0 78
USC00519281 2013-11-04 00:00:00 0.12 69
USC00519281 2013-11-05 00:00:00 0.24 70
USC00519281 2013-11-06 00:00:00 0.8 70
USC00519281 2013-11-07 00:00:00 0.12 67
USC00519281 2013-11-08 00:00:00 1.42 70
USC00519281 2013-11-09 00:00:00 2.21 74
USC00519281 2013-11-10 00:00:00 5.54 71
USC00519281 2013-11-11 00:00:00 0.3 72
USC00519281 2013-11-12 00:00:00 0.23 67
USC00519281 2013-11-13 00:00:00 0.02 61
USC00519281 2013-11-14 00:00:00 0.02 68
USC00519281 2013-11-15 00:00:00 0.47 70
USC00519281 2013-11-16 00:00:00 0.03 71
USC00519281 2013-11-17 00:00:00 0.01 76
USC00519281 2013-11-18 00:00:00 0.04 68
USC00519281 2013-11-19 00:00:00 0.01 64
USC00519281 2013-11-20 00:00:00 0.0 67
USC00519281 2013-11-21 00:00:00 0.0 68
USC00519281 2013-11-22 00:00:00 0.01 65
USC00519281 2013-11-23 00:00:00 0.11 70
USC00519281 2013-11-24 00:00:00 0.0 66
USC00519281 2013-11-25 00:00:00 0.0 71
USC00519281 2013-11-26 00:00:00 0.0 72
USC00519281 2013-11-27 00:00:00 0.0 67
USC00519281 2013-11-28 00:00:00 0.03 74
USC00519281 2013-11-29 00:00:00 0.84 69
USC00519281 2013-11-30 00:00:00 0.88 76
USC00519281 2013-12-01 00:00:00 0.12 72
USC00519281 2013-12-02 00:00:00 1.71 73
USC00519281 2013-12-03 00:00:00 0.57 70
USC00519281 2013-12-04 00:00:00 0.01 66
USC00519281 2013-12-05 00:00:00 0.0 64
USC00519281 2013-12-06 00:00:00 0.0 65
USC00519281 2013-12-07 00:00:00 0.01 73
USC00519281 2013-12-08 00:00:00 0.0 74
USC00519281 2013-12-09 00:00:00 0.0 67
USC00519281 2013-12-10 00:00:00 0.04 73
USC00519281 2013-12-11 00:00:00 0.17 70
USC00519281 2013-12-12 00:00:00 0.03 67
USC00519281 2013-12-13 00:00:00 0.04 71
USC00519281 2013-12-14 00:00:00 0.08 78
USC00519281 2013-12-15 00:00:00 0.06 69
USC00519281 2013-12-16 00:00:00 1.97 63
USC00519281 2013-12-17 00:00:00 0.02 64
USC00519281 2013-12-18 00:00:00 0.02 66
USC00519281 2013-12-19 00:00:00 0.77 69
USC00519281 2013-12-20 00:00:00 1.14 69
USC00519281 2013-12-21 00:00:00 0.07 71
USC00519281 2013-12-22 00:00:00 0.03 72
USC00519281 2013-12-23 00:00:00 0.06 69
USC00519281 2013-12-24 00:00:00 0.09 70
USC00519281 2013-12-25 00:00:00 0.03 73
USC00519281 2013-12-26 00:00:00 0.05 68
USC00519281 2013-12-27 00:00:00 0.01 69
USC00519281 2013-12-28 00:00:00 0.01 73
USC00519281 2013-12-29 00:00:00 0.0 73
USC00519281 2013-12-30 00:00:00 0.0 70
USC00519281 2013-12-31 00:00:00 0.08 65
USC00519281 2014-01-01 00:00:00 0.0 72
USC00519281 2014-01-02 00:00:00 0.01 74
USC00519281 2014-01-03 00:00:00 1.62 66
USC00519281 2014-01-04 00:00:00 0.0 68
USC00519281 2014-01-05 00:00:00 0.0 62
USC00519281 2014-01-06 00:00:00 0.12 64
USC00519281 2014-01-07 00:00:00 0.0 68
USC00519281 2014-01-08 00:00:00 0.0 69
USC00519281 2014-01-09 00:00:00 0.09 61
USC00519281 2014-01-10 00:00:00 0.04 66
USC00519281 2014-01-11 00:00:00 0.71 66
USC00519281 2014-01-12 00:00:00 0.02 71
USC00519281 2014-01-13 00:00:00 0.0 65
USC00519281 2014-01-14 00:00:00 1.76 73
USC00519281 2014-01-15 00:00:00 0.01 62
USC00519281 2014-01-16 00:00:00 0.03 68
USC00519281 2014-01-17 00:00:00 0.06 66
USC00519281 2014-01-18 00:00:00 0.03 66
USC00519281 2014-01-19 00:00:00 0.01 67
USC00519281 2014-01-20 00:00:00 0.19 65
USC00519281 2014-01-21 00:00:00 0.0 71
USC00519281 2014-01-22 00:00:00 0.47 68
USC00519281 2014-01-23 00:00:00 0.0 58
USC00519281 2014-01-24 00:00:00 0.0 58
USC00519281 2014-01-25 00:00:00 0.0 73
USC00519281 2014-01-26 00:00:00 0.0 75
USC00519281 2014-01-27 00:00:00 0.48 66
USC00519281 2014-01-28 00:00:00 0.69 66
USC00519281 2014-01-29 00:00:00 0.77 67
USC00519281 2014-01-30 00:00:00 0.49 64
USC00519281 2014-01-31 00:00:00 0.0 65
USC00519281 2014-02-01 00:00:00 0.87 70
USC00519281 2014-02-02 00:00:00 0.26 66
USC00519281 2014-02-03 00:00:00 0.01 66
USC00519281 2014-02-04 00:00:00 0.67 66
USC00519281 2014-02-05 00:00:00 0.41 67
USC00519281 2014-02-06 00:00:00 0.15 70
USC00519281 2014-02-07 00:00:00 0.03 68
USC00519281 2014-02-08 00:00:00 0.64 67
USC00519281 2014-02-09 00:00:00 1.14 72
USC00519281 2014-02-10 00:00:00 0.05 69
USC00519281 2014-02-11 00:00:00 0.0 62
USC00519281 2014-02-12 00:00:00 0.01 66
USC00519281 2014-02-13 00:00:00 0.0 66
USC00519281 2014-02-14 00:00:00 0.1 71
USC00519281 2014-02-15 00:00:00 0.43 71
USC00519281 2014-02-16 00:00:00 0.63 71
USC00519281 2014-02-17 00:00:00 0.31 73
USC00519281 2014-02-18 00:00:00 0.11 74
USC00519281 2014-02-19 00:00:00 0.0 72
USC00519281 2014-02-20 00:00:00 0.01 68
USC00519281 2014-02-21 00:00:00 0.0 68
USC00519281 2014-02-22 00:00:00 0.53 67
USC00519281 2014-02-23 00:00:00 0.06 71
USC00519281 2014-02-24 00:00:00 0.01 64
USC00519281 2014-02-25 00:00:00 0.01 64
USC00519281 2014-02-26 00:00:00 0.01 62
USC00519281 2014-02-27 00:00:00 0.03 63
USC00519281 2014-02-28 00:00:00 0.02 67
USC00519281 2014-03-01 00:00:00 0.35 70
USC00519281 2014-03-02 00:00:00 0.28 68
USC00519281 2014-03-03 00:00:00 0.28 62
USC00519281 2014-03-04 00:00:00 0.0 57
USC00519281 2014-03-05 00:00:00 0.0 61
USC00519281 2014-03-06 00:00:00 0.0 60
USC00519281 2014-03-07 00:00:00 0.19 71
USC00519281 2014-03-08 00:00:00 0.54 65
USC00519281 2014-03-09 00:00:00 1.72 69
USC00519281 2014-03-10 00:00:00 0.32 69
USC00519281 2014-03-11 00:00:00 0.28 66
USC00519281 2014-03-12 00:00:00 0.0 68
USC00519281 2014-03-13 00:00:00 0.0 71
USC00519281 2014-03-14 00:00:00 0.07 69
USC00519281 2014-03-15 00:00:00 0.62 67
USC00519281 2014-03-16 00:00:00 0.14 68
USC00519281 2014-03-17 00:00:00 0.06 65
USC00519281 2014-03-18 00:00:00 0.03 64
USC00519281 2014-03-19 00:00:00 0.0 69
USC00519281 2014-03-20 00:00:00 0.0 66
USC00519281 2014-03-21 00:00:00 0.0 71
USC00519281 2014-03-22 00:00:00 0.03 68
USC00519281 2014-03-23 00:00:00 0.0 72
USC00519281 2014-03-24 00:00:00 0.0 70
USC00519281 2014-03-25 00:00:00 0.0 70
USC00519281 2014-03-26 00:00:00 0.75 73
USC00519281 2014-03-27 00:00:00 0.27 70
USC00519281 2014-03-28 00:00:00 3.86 67
USC00519281 2014-03-29 00:00:00 0.26 73
USC00519281 2014-03-30 00:00:00 1.23 72
USC00519281 2014-03-31 00:00:00 0.03 71
USC00519281 2014-04-01 00:00:00 0.03 72
USC00519281 2014-04-02 00:00:00 0.66 71
USC00519281 2014-04-03 00:00:00 0.1 72
USC00519281 2014-04-04 00:00:00 0.0 71
USC00519281 2014-04-05 00:00:00 0.0 76
USC00519281 2014-04-06 00:00:00 0.03 76
USC00519281 2014-04-07 00:00:00 0.3 66
USC00519281 2014-04-08 00:00:00 0.32 73
USC00519281 2014-04-09 00:00:00 0.0 69
USC00519281 2014-04-10 00:00:00 0.02 66
USC00519281 2014-04-11 00:00:00 0.0 69
USC00519281 2014-04-12 00:00:00 0.37 71
USC00519281 2014-04-13 00:00:00 0.11 72
USC00519281 2014-04-14 00:00:00 0.0 70
USC00519281 2014-04-15 00:00:00 0.1 68
USC00519281 2014-04-16 00:00:00 0.02 71
USC00519281 2014-04-17 00:00:00 0.12 69
USC00519281 2014-04-18 00:00:00 0.14 74
USC00519281 2014-04-19 00:00:00 0.01 73
USC00519281 2014-04-20 00:00:00 0.12 73
USC00519281 2014-04-21 00:00:00 0.22 72
USC00519281 2014-04-22 00:00:00 0.24 71
USC00519281 2014-04-23 00:00:00 0.0 71
USC00519281 2014-04-24 00:00:00 0.22 69
USC00519281 2014-04-25 00:00:00 0.2 71
USC00519281 2014-04-26 00:00:00 0.03 69
USC00519281 2014-04-27 00:00:00 0.68 70
USC00519281 2014-04-28 00:00:00 0.42 66
USC00519281 2014-04-29 00:00:00 0.01 67
USC00519281 2014-04-30 00:00:00 0.22 68
USC00519281 2014-05-01 00:00:00 0.06 68
USC00519281 2014-05-02 00:00:00 0.36 69
USC00519281 2014-05-03 00:00:00 0.57 76
USC00519281 2014-05-04 00:00:00 0.03 71
USC00519281 2014-05-05 00:00:00 0.11 70
USC00519281 2014-05-06 00:00:00 0.08 70
USC00519281 2014-05-07 00:00:00 0.0 72
USC00519281 2014-05-08 00:00:00 0.33 67
USC00519281 2014-05-09 00:00:00 0.04 68
USC00519281 2014-05-10 00:00:00 0.09 75
USC00519281 2014-05-11 00:00:00 0.08 74
USC00519281 2014-05-12 00:00:00 1.02 70
USC00519281 2014-05-13 00:00:00 0.11 68
USC00519281 2014-05-14 00:00:00 0.0 66
USC00519281 2014-05-15 00:00:00 0.13 71
USC00519281 2014-05-16 00:00:00 0.43 69
USC00519281 2014-05-17 00:00:00 0.07 77
USC00519281 2014-05-18 00:00:00 0.1 73
USC00519281 2014-05-19 00:00:00 0.03 65
USC00519281 2014-05-20 00:00:00 0.14 68
USC00519281 2014-05-21 00:00:00 0.0 68
USC00519281 2014-05-22 00:00:00 0.1 72
USC00519281 2014-05-23 00:00:00 0.33 81
USC00519281 2014-05-24 00:00:00 0.07 72
USC00519281 2014-05-25 00:00:00 1.37 71
USC00519281 2014-05-26 00:00:00 0.46 72
USC00519281 2014-05-27 00:00:00 0.35 72
USC00519281 2014-05-28 00:00:00 0.12 73
USC00519281 2014-05-29 00:00:00 0.02 74
USC00519281 2014-05-30 00:00:00 0.14 73
USC00519281 2014-05-31 00:00:00 0.07 73
USC00519281 2014-06-01 00:00:00 0.07 74
USC00519281 2014-06-02 00:00:00 0.06 72
USC00519281 2014-06-03 00:00:00 0.0 74
USC00519281 2014-06-04 00:00:00 0.01 73
USC00519281 2014-06-05 00:00:00 0.01 73
USC00519281 2014-06-06 00:00:00 0.19 70
USC00519281 2014-06-07 00:00:00 0.2 73
USC00519281 2014-06-08 00:00:00 0.18 75
USC00519281 2014-06-09 00:00:00 0.04 73
USC00519281 2014-06-10 00:00:00 0.22 69
USC00519281 2014-06-11 00:00:00 0.37 80
USC00519281 2014-06-12 00:00:00 0.02 73
USC00519281 2014-06-13 00:00:00 0.0 72
USC00519281 2014-06-14 00:00:00 0.02 80
USC00519281 2014-06-15 00:00:00 0.02 80
USC00519281 2014-06-16 00:00:00 0.03 69
USC00519281 2014-06-17 00:00:00 0.29 70
USC00519281 2014-06-18 00:00:00 0.17 69
USC00519281 2014-06-19 00:00:00 0.04 72
USC00519281 2014-06-20 00:00:00 0.16 68
USC00519281 2014-06-21 00:00:00 0.22 74
USC00519281 2014-06-22 00:00:00 0.04 75
USC00519281 2014-06-23 00:00:00 0.31 70
USC00519281 2014-06-24 00:00:00 0.08 70
USC00519281 2014-06-25 00:00:00 0.23 72
USC00519281 2014-06-26 00:00:00 0.31 71
USC00519281 2014-06-27 00:00:00 0.12 70
USC00519281 2014-06-28 00:00:00 0.6 77
USC00519281 2014-06-29 00:00:00 0.48 73
USC00519281 2014-06-30 00:00:00 0.01 71
USC00519281 2014-07-01 00:00:00 0.0 79
USC00519281 2014-07-02 00:00:00 0.05 73
USC00519281 2014-07-03 00:00:00 0.16 73
USC00519281 2014-07-04 00:00:00 0.07 78
USC00519281 2014-07-05 00:00:00 0.0 73
USC00519281 2014-07-06 00:00:00 0.37 72
USC00519281 2014-07-07 00:00:00 0.12 71
USC00519281 2014-07-08 00:00:00 0.08 73
USC00519281 2014-07-09 00:00:00 0.19 73
USC00519281 2014-07-10 00:00:00 0.16 73
USC00519281 2014-07-11 00:00:00 0.05 73
USC00519281 2014-07-12 00:00:00 0.0 75
USC00519281 2014-07-13 00:00:00 0.18 78
USC00519281 2014-07-14 00:00:00 0.33 75
USC00519281 2014-07-15 00:00:00 0.15 74
USC00519281 2014-07-16 00:00:00 0.67 76
USC00519281 2014-07-17 00:00:00 0.01 75
USC00519281 2014-07-18 00:00:00 0.14 74
USC00519281 2014-07-19 00:00:00 0.0 75
USC00519281 2014-07-20 00:00:00 7.97 73
USC00519281 2014-07-21 00:00:00 0.17 74
USC00519281 2014-07-22 00:00:00 0.49 73
USC00519281 2014-07-23 00:00:00 0.06 75
USC00519281 2014-07-24 00:00:00 0.02 75
USC00519281 2014-07-25 00:00:00 0.0 72
USC00519281 2014-07-26 00:00:00 0.13 74
USC00519281 2014-07-27 00:00:00 0.16 77
USC00519281 2014-07-28 00:00:00 0.0 72
USC00519281 2014-07-29 00:00:00 0.0 71
USC00519281 2014-07-30 00:00:00 0.0 72
USC00519281 2014-07-31 00:00:00 0.0 73
USC00519281 2014-08-01 00:00:00 0.0 75
USC00519281 2014-08-02 00:00:00 0.31 74
USC00519281 2014-08-03 00:00:00 0.07 75
USC00519281 2014-08-04 00:00:00 0.02 74
USC00519281 2014-08-05 00:00:00 0.0 74
USC00519281 2014-08-06 00:00:00 0.0 75
USC00519281 2014-08-07 00:00:00 0.02 76
USC00519281 2014-08-08 00:00:00 0.29 78
USC00519281 2014-08-09 00:00:00 0.79 76
USC00519281 2014-08-10 00:00:00 0.03 73
USC00519281 2014-08-11 00:00:00 0.0 68
USC00519281 2014-08-12 00:00:00 0.0 72
USC00519281 2014-08-13 00:00:00 0.17 72
USC00519281 2014-08-14 00:00:00 0.04 73
USC00519281 2014-08-15 00:00:00 0.02 72
USC00519281 2014-08-16 00:00:00 0.0 76
USC00519281 2014-08-17 00:00:00 0.0 75
USC00519281 2014-08-18 00:00:00 0.2 74
USC00519281 2014-08-19 00:00:00 0.03 72
USC00519281 2014-08-20 00:00:00 0.12 70
USC00519281 2014-08-21 00:00:00 0.05 73
USC00519281 2014-08-22 00:00:00 0.14 74
USC00519281 2014-08-23 00:00:00 0.02 75
USC00519281 2014-08-24 00:00:00 0.17 75
USC00519281 2014-08-25 00:00:00 0.01 73
USC00519281 2014-08-26 00:00:00 0.38 71
USC00519281 2014-08-27 00:00:00 0.22 71
USC00519281 2014-08-28 00:00:00 0.01 76
USC00519281 2014-08-29 00:00:00 0.06 72
USC00519281 2014-08-30 00:00:00 0.11 75
USC00519281 2014-08-31 00:00:00 0.0 76
USC00519281 2014-09-01 00:00:00 0.0 76
USC00519281 2014-09-02 00:00:00 2.29 75
USC00519281 2014-09-03 00:00:00 0.02 72
USC00519281 2014-09-04 00:00:00 0.0 73
USC00519281 2014-09-05 00:00:00 0.06 71
USC00519281 2014-09-06 00:00:00 0.61 74
USC00519281 2014-09-07 00:00:00 0.01 76
USC00519281 2014-09-08 00:00:00 0.0 72
USC00519281 2014-09-09 00:00:00 0.0 71
USC00519281 2014-09-10 00:00:00 0.0 72
USC00519281 2014-09-11 00:00:00 0.02 71
USC00519281 2014-09-12 00:00:00 0.09 75
USC00519281 2014-09-13 00:00:00 0.0 74
USC00519281 2014-09-14 00:00:00 0.0 75
USC00519281 2014-09-15 00:00:00 0.53 74
USC00519281 2014-09-16 00:00:00 0.0 73
USC00519281 2014-09-17 00:00:00 0.47 73
USC00519281 2014-09-18 00:00:00 0.04 71
USC00519281 2014-09-19 00:00:00 0.18 74
USC00519281 2014-09-20 00:00:00 0.14 76
USC00519281 2014-09-21 00:00:00 1.21 77
USC00519281 2014-09-22 00:00:00 0.06 73
USC00519281 2014-09-23 00:00:00 0.01 77
USC00519281 2014-09-24 00:00:00 0.0 74
USC00519281 2014-09-25 00:00:00 0.12 74
USC00519281 2014-09-26 00:00:00 0.38 75
USC00519281 2014-09-27 00:00:00 0.09 75
USC00519281 2014-09-28 00:00:00 0.26 73
USC00519281 2014-09-29 00:00:00 0.55 73
USC00519281 2014-09-30 00:00:00 0.3 71
USC00519281 2014-10-01 00:00:00 4.0 70
USC00519281 2014-10-02 00:00:00 0.02 72
USC00519281 2014-10-03 00:00:00 0.37 73
USC00519281 2014-10-04 00:00:00 0.4 72
USC00519281 2014-10-05 00:00:00 0.95 69
USC00519281 2014-10-06 00:00:00 0.1 70
USC00519281 2014-10-07 00:00:00 0.03 70
USC00519281 2014-10-08 00:00:00 0.15 71
USC00519281 2014-10-09 00:00:00 0.06 74
USC00519281 2014-10-10 00:00:00 0.13 73
USC00519281 2014-10-11 00:00:00 0.07 74
USC00519281 2014-10-12 00:00:00 0.0 73
USC00519281 2014-10-13 00:00:00 0.04 74
USC00519281 2014-10-14 00:00:00 0.22 72
USC00519281 2014-10-15 00:00:00 0.3 73
USC00519281 2014-10-16 00:00:00 0.01 75
USC00519281 2014-10-17 00:00:00 0.0 73
USC00519281 2014-10-18 00:00:00 0.63 78
USC00519281 2014-10-19 00:00:00 2.45 73
USC00519281 2014-10-20 00:00:00 2.75 74
USC00519281 2014-10-21 00:00:00 0.01 72
USC00519281 2014-10-22 00:00:00 0.17 75
USC00519281 2014-10-23 00:00:00 0.78 73
USC00519281 2014-10-24 00:00:00 0.29 72
USC00519281 2014-10-25 00:00:00 0.22 72
USC00519281 2014-10-26 00:00:00 0.15 78
USC00519281 2014-10-27 00:00:00 0.0 71
USC00519281 2014-10-28 00:00:00 0.13 70
USC00519281 2014-10-29 00:00:00 0.24 72
USC00519281 2014-10-30 00:00:00 0.28 73
USC00519281 2014-10-31 00:00:00 0.03 75

USC00519281 2014-11-01 00:00:00 0.12 75
USC00519281 2014-11-02 00:00:00 0.48 76
USC00519281 2014-11-03 00:00:00 0.12 73
USC00519281 2014-11-04 00:00:00 0.07 75
USC00519281 2014-11-05 00:00:00 0.03 73
USC00519281 2014-11-06 00:00:00 0.12 69
USC00519281 2014-11-07 00:00:00 0.01 70
USC00519281 2014-11-08 00:00:00 0.67 70
USC00519281 2014-11-09 00:00:00 0.01 67
USC00519281 2014-11-10 00:00:00 0.0 63
USC00519281 2014-11-11 00:00:00 0.0 74
USC00519281 2014-11-12 00:00:00 0.77 68
USC00519281 2014-11-13 00:00:00 0.0 67
USC00519281 2014-11-14 00:00:00 0.0 74
USC00519281 2014-11-15 00:00:00 0.95 72
USC00519281 2014-11-16 00:00:00 0.15 69
USC00519281 2014-11-17 00:00:00 0.0 71
USC00519281 2014-11-18 00:00:00 0.0 73
USC00519281 2014-11-19 00:00:00 0.0 74
USC00519281 2014-11-20 00:00:00 0.02 73
USC00519281 2014-11-21 00:00:00 0.0 71
USC00519281 2014-11-22 00:00:00 0.01 71
USC00519281 2014-11-23 00:00:00 0.0 72
USC00519281 2014-11-24 00:00:00 0.0 74
USC00519281 2014-11-25 00:00:00 0.21 66
USC00519281 2014-11-26 00:00:00 0.0 69
USC00519281 2014-11-27 00:00:00 0.0 73
USC00519281 2014-11-28 00:00:00 0.0 72
USC00519281 2014-11-29 00:00:00 0.05 71
USC00519281 2014-11-30 00:00:00 0.62 70
USC00519281 2014-12-01 00:00:00 0.0 70
USC00519281 2014-12-02 00:00:00 0.0 68
USC00519281 2014-12-03 00:00:00 0.41 68
USC00519281 2014-12-04 00:00:00 1.56 66
USC00519281 2014-12-05 00:00:00 0.04 68
USC00519281 2014-12-06 00:00:00 0.63 65
USC00519281 2014-12-07 00:00:00 0.01 62
USC00519281 2014-12-08 00:00:00 0.0 62
USC00519281 2014-12-09 00:00:00 0.0 65
USC00519281 2014-12-10 00:00:00 0.0 61
USC00519281 2014-12-11 00:00:00 0.21 70
USC00519281 2014-12-12 00:00:00 0.07 68
USC00519281 2014-12-13 00:00:00 0.01 67
USC00519281 2014-12-14 00:00:00 0.13 68
USC00519281 2014-12-15 00:00:00 0.0 71
USC00519281 2014-12-16 00:00:00 0.08 69
USC00519281 2014-12-17 00:00:00 0.07 71
USC00519281 2014-12-18 00:00:00 0.11 71
USC00519281 2014-12-19 00:00:00 0.08 71
USC00519281 2014-12-20 00:00:00 0.0 72
USC00519281 2014-12-21 00:00:00 0.0 72
USC00519281 2014-12-22 00:00:00 0.0 68
USC00519281 2014-12-23 00:00:00 1.07 69
USC00519281 2014-12-24 00:00:00 1.1 66
USC00519281 2014-12-25 00:00:00 0.36 60
USC00519281 2014-12-26 00:00:00 0.0 63
USC00519281 2014-12-27 00:00:00 0.0 68
USC00519281 2014-12-28 00:00:00 0.0 64
USC00519281 2014-12-29 00:00:00 0.0 63
USC00519281 2014-12-30 00:00:00 0.0 63
USC00519281 2014-12-31 00:00:00 0.66 59
USC00519281 2015-01-01 00:00:00 0.0 66
USC00519281 2015-01-02 00:00:00 0.0 60
USC00519281 2015-01-03 00:00:00 1.55 67
USC00519281 2015-01-04 00:00:00 0.05 65
USC00519281 2015-01-05 00:00:00 0.0 56
USC00519281 2015-01-06 00:00:00 0.06 64
USC00519281 2015-01-07 00:00:00 0.0 64
USC00519281 2015-01-08 00:00:00 0.0 62
USC00519281 2015-01-09 00:00:00 0.0 64
USC00519281 2015-01-10 00:00:00 0.05 66
USC00519281 2015-01-11 00:00:00 0.0 69
USC00519281 2015-01-12 00:00:00 0.0 60
USC00519281 2015-01-13 00:00:00 0.0 58
USC00519281 2015-01-14 00:00:00 0.0 63
USC00519281 2015-01-15 00:00:00 0.0 65
USC00519281 2015-01-16 00:00:00 0.01 68
USC00519281 2015-01-17 00:00:00 0.0 70
USC00519281 2015-01-18 00:00:00 0.0 67
USC00519281 2015-01-19 00:00:00 0.0 71
USC00519281 2015-01-20 00:00:00 0.0 68
USC00519281 2015-01-21 00:00:00 0.0 62
USC00519281 2015-01-22 00:00:00 0.0 61
USC00519281 2015-01-23 00:00:00 0.0 72
USC00519281 2015-01-24 00:00:00 0.18 66
USC00519281 2015-01-25 00:00:00 0.78 65
USC00519281 2015-01-26 00:00:00 0.77 65
USC00519281 2015-01-27 00:00:00 0.0 65
USC00519281 2015-01-28 00:00:00 0.06 66
USC00519281 2015-01-29 00:00:00 0.0 69
USC00519281 2015-01-30 00:00:00 0.09 63
USC00519281 2015-01-31 00:00:00 0.0 69
USC00519281 2015-02-01 00:00:00 0.02 62
USC00519281 2015-02-02 00:00:00 0.0 67
USC00519281 2015-02-03 00:00:00 0.0 76
USC00519281 2015-02-04 00:00:00 1.29 74
USC00519281 2015-02-05 00:00:00 0.0 66
USC00519281 2015-02-06 00:00:00 0.0 58
USC00519281 2015-02-07 00:00:00 0.0 70
USC00519281 2015-02-08 00:00:00 0.0 66
USC00519281 2015-02-09 00:00:00 0.0 72
USC00519281 2015-02-10 00:00:00 0.24 68
USC00519281 2015-02-11 00:00:00 0.0 64
USC00519281 2015-02-12 00:00:00 0.0 60
USC00519281 2015-02-13 00:00:00 0.0 71
USC00519281 2015-02-14 00:00:00 0.21 73
USC00519281 2015-02-15 00:00:00 1.42 56
USC00519281 2015-02-16 00:00:00 0.01 68
USC00519281 2015-02-17 00:00:00 0.0 63
USC00519281 2015-02-18 00:00:00 0.0 64
USC00519281 2015-02-19 00:00:00 0.0 66
USC00519281 2015-02-20 00:00:00 0.0 69
USC00519281 2015-02-21 00:00:00 0.61 72
USC00519281 2015-02-22 00:00:00 0.0 74
USC00519281 2015-02-23 00:00:00 0.0 77
USC00519281 2015-02-24 00:00:00 0.0 65
USC00519281 2015-02-25 00:00:00 0.01 71
USC00519281 2015-02-26 00:00:00 0.12 69
USC00519281 2015-02-27 00:00:00 0.07 66
USC00519281 2015-02-28 00:00:00 0.28 69
USC00519281 2015-03-01 00:00:00 0.18 71
USC00519281 2015-03-02 00:00:00 0.09 68
USC00519281 2015-03-03 00:00:00 0.17 71
USC00519281 2015-03-04 00:00:00 0.22 67
USC00519281 2015-03-05 00:00:00 1.08 65
USC00519281 2015-03-06 00:00:00 0.57 62
USC00519281 2015-03-07 00:00:00 0.01 67
USC00519281 2015-03-08 00:00:00 0.0 65
USC00519281 2015-03-09 00:00:00 0.0 57
USC00519281 2015-03-10 00:00:00 0.19 57
USC00519281 2015-03-11 00:00:00 0.0 61
USC00519281 2015-03-12 00:00:00 0.0 62
USC00519281 2015-03-13 00:00:00 0.06 56
USC00519281 2015-03-14 00:00:00 0.0 69
USC00519281 2015-03-15 00:00:00 0.0 72
USC00519281 2015-03-16 00:00:00 0.01 63
USC00519281 2015-03-17 00:00:00 0.0 57
USC00519281 2015-03-18 00:00:00 0.0 60
USC00519281 2015-03-19 00:00:00 0.0 62
USC00519281 2015-03-20 00:00:00 0.02 70
USC00519281 2015-03-21 00:00:00 0.2 72
USC00519281 2015-03-22 00:00:00 0.08 73
USC00519281 2015-03-23 00:00:00 0.0 68
USC00519281 2015-03-24 00:00:00 0.0 62
USC00519281 2015-03-25 00:00:00 0.02 63
USC00519281 2015-03-26 00:00:00 0.03 70
USC00519281 2015-03-27 00:00:00 0.0 70
USC00519281 2015-03-28 00:00:00 0.0 74
USC00519281 2015-03-29 00:00:00 0.49 74
USC00519281 2015-03-30 00:00:00 0.42 70
USC00519281 2015-03-31 00:00:00 0.61 70
USC00519281 2015-04-01 00:00:00 0.64 70
USC00519281 2015-04-02 00:00:00 0.0 72
USC00519281 2015-04-03 00:00:00 0.0 74
USC00519281 2015-04-04 00:00:00 0.0 74
USC00519281 2015-04-05 00:00:00 0.03 73
USC00519281 2015-04-06 00:00:00 0.0 70
USC00519281 2015-04-07 00:00:00 0.0 70
USC00519281 2015-04-08 00:00:00 0.39 70
USC00519281 2015-04-09 00:00:00 0.0 71
USC00519281 2015-04-10 00:00:00 0.0 67
USC00519281 2015-04-11 00:00:00 0.0 72
USC00519281 2015-04-12 00:00:00 0.18 69
USC00519281 2015-04-13 00:00:00 0.05 69
USC00519281 2015-04-14 00:00:00 0.07 70
USC00519281 2015-04-15 00:00:00 0.19 71
USC00519281 2015-04-16 00:00:00 0.02 70
USC00519281 2015-04-17 00:00:00 0.1 71
USC00519281 2015-04-18 00:00:00 0.01 74
USC00519281 2015-04-19 00:00:00 0.01 75
USC00519281 2015-04-20 00:00:00 0.0 72
USC00519281 2015-04-21 00:00:00 0.03 72
USC00519281 2015-04-22 00:00:00 0.07 67
USC00519281 2015-04-23 00:00:00 0.32 67
USC00519281 2015-04-24 00:00:00 0.14 69
USC00519281 2015-04-25 00:00:00 0.01 73
USC00519281 2015-04-26 00:00:00 0.0 78
USC00519281 2015-04-27 00:00:00 0.62 69
USC00519281 2015-04-28 00:00:00 0.47 71
USC00519281 2015-04-29 00:00:00 0.14 73
USC00519281 2015-04-30 00:00:00 0.0 72
USC00519281 2015-05-01 00:00:00 0.18 69
USC00519281 2015-05-02 00:00:00 0.0 73
USC00519281 2015-05-03 00:00:00 0.0 76
USC00519281 2015-05-04 00:00:00 0.01 72
USC00519281 2015-05-05 00:00:00 0.0 72
USC00519281 2015-05-06 00:00:00 0.0 72
USC00519281 2015-05-07 00:00:00 0.09 72
USC00519281 2015-05-08 00:00:00 0.15 70
USC00519281 2015-05-09 00:00:00 0.4 73
USC00519281 2015-05-10 00:00:00 0.29 69
USC00519281 2015-05-11 00:00:00 0.03 72
USC00519281 2015-05-12 00:00:00 0.0 72
USC00519281 2015-05-13 00:00:00 0.0 71
USC00519281 2015-05-14 00:00:00 0.09 71
USC00519281 2015-05-15 00:00:00 0.02 66
USC00519281 2015-05-16 00:00:00 0.06 78
USC00519281 2015-05-17 00:00:00 0.06 74
USC00519281 2015-05-18 00:00:00 0.17 70
USC00519281 2015-05-19 00:00:00 0.0 72
USC00519281 2015-05-20 00:00:00 0.06 69
USC00519281 2015-05-21 00:00:00 0.4 65
USC00519281 2015-05-22 00:00:00 0.0 64
USC00519281 2015-05-23 00:00:00 0.85 75
USC00519281 2015-05-24 00:00:00 0.0 69
USC00519281 2015-05-25 00:00:00 0.0 71
USC00519281 2015-05-26 00:00:00 0.07 65
USC00519281 2015-05-27 00:00:00 0.36 65
USC00519281 2015-05-28 00:00:00 0.72 67
USC00519281 2015-05-29 00:00:00 0.04 64
USC00519281 2015-05-30 00:00:00 0.01 72
USC00519281 2015-05-31 00:00:00 0.59 72
USC00519281 2015-06-01 00:00:00 0.46 76
USC00519281 2015-06-02 00:00:00 0.02 68
USC00519281 2015-06-03 00:00:00 0.0 71
USC00519281 2015-06-04 00:00:00 1.24 70
USC00519281 2015-06-05 00:00:00 0.06 68
USC00519281 2015-06-06 00:00:00 0.0 79
USC00519281 2015-06-07 00:00:00 0.07 75
USC00519281 2015-06-08 00:00:00 0.01 71
USC00519281 2015-06-09 00:00:00 0.34 69
USC00519281 2015-06-10 00:00:00 0.03 71
USC00519281 2015-06-11 00:00:00 0.03 72
USC00519281 2015-06-12 00:00:00 0.08 69
USC00519281 2015-06-13 00:00:00 0.01 72
USC00519281 2015-06-14 00:00:00 0.05 75
USC00519281 2015-06-15 00:00:00 0.03 71
USC00519281 2015-06-16 00:00:00 0.01 72
USC00519281 2015-06-17 00:00:00 0.15 70
USC00519281 2015-06-18 00:00:00 0.45 71
USC00519281 2015-06-19 00:00:00 0.19 72
USC00519281 2015-06-20 00:00:00 0.13 75
USC00519281 2015-06-21 00:00:00 0.05 75
USC00519281 2015-06-22 00:00:00 0.05 71
USC00519281 2015-06-23 00:00:00 0.03 73
USC00519281 2015-06-24 00:00:00 0.17 71
USC00519281 2015-06-25 00:00:00 0.21 71
USC00519281 2015-06-26 00:00:00 0.02 74
USC00519281 2015-06-27 00:00:00 0.21 74
USC00519281 2015-06-28 00:00:00 0.02 78
USC00519281 2015-06-29 00:00:00 0.27 72
USC00519281 2015-06-30 00:00:00 0.16 69
USC00519281 2015-07-01 00:00:00 0.01 68
USC00519281 2015-07-02 00:00:00 0.0 68
USC00519281 2015-07-03 00:00:00 0.28 73
USC00519281 2015-07-04 00:00:00 0.0 77
USC00519281 2015-07-05 00:00:00 0.0 78
USC00519281 2015-07-06 00:00:00 0.0 74
USC00519281 2015-07-07 00:00:00 0.01 75
USC00519281 2015-07-08 00:00:00 0.32 75
USC00519281 2015-07-09 00:00:00 0.04 74
USC00519281 2015-07-10 00:00:00 0.48 76
USC00519281 2015-07-11 00:00:00 0.57 77
USC00519281 2015-07-12 00:00:00 0.27 82
USC00519281 2015-07-13 00:00:00 0.06 77
USC00519281 2015-07-14 00:00:00 0.47 73
USC00519281 2015-07-15 00:00:00 0.23 73
USC00519281 2015-07-16 00:00:00 0.41 74
USC00519281 2015-07-17 00:00:00 0.69 75
USC00519281 2015-07-18 00:00:00 0.27 83
USC00519281 2015-07-19 00:00:00 0.05 72
USC00519281 2015-07-20 00:00:00 0.01 71
USC00519281 2015-07-21 00:00:00 0.26 73
USC00519281 2015-07-22 00:00:00 0.31 76
USC00519281 2015-07-23 00:00:00 0.02 74
USC00519281 2015-07-24 00:00:00 0.03 75
USC00519281 2015-07-25 00:00:00 0.1 78
USC00519281 2015-07-26 00:00:00 0.0 72
USC00519281 2015-07-27 00:00:00 0.0 75
USC00519281 2015-07-28 00:00:00 0.14 74
USC00519281 2015-07-29 00:00:00 0.02 77
USC00519281 2015-07-30 00:00:00 0.0 74
USC00519281 2015-07-31 00:00:00 0.01 77
USC00519281 2015-08-01 00:00:00 0.0 78
USC00519281 2015-08-02 00:00:00 0.01 79
USC00519281 2015-08-03 00:00:00 0.0 75
USC00519281 2015-08-04 00:00:00 0.01 69
USC00519281 2015-08-05 00:00:00 0.02 76
USC00519281 2015-08-06 00:00:00 0.47 74
USC00519281 2015-08-07 00:00:00 0.02 73
USC00519281 2015-08-08 00:00:00 0.16 80
USC00519281 2015-08-09 00:00:00 0.06 74
USC00519281 2015-08-10 00:00:00 0.04 75
USC00519281 2015-08-11 00:00:00 0.04 75
USC00519281 2015-08-12 00:00:00 0.01 76
USC00519281 2015-08-13 00:00:00 0.07 76
USC00519281 2015-08-14 00:00:00 0.43 75
USC00519281 2015-08-15 00:00:00 0.18 76
USC00519281 2015-08-16 00:00:00 0.04 74
USC00519281 2015-08-17 00:00:00 0.24 78
USC00519281 2015-08-18 00:00:00 0.89 76
USC00519281 2015-08-19 00:00:00 0.03 74
USC00519281 2015-08-20 00:00:00 0.0 72
USC00519281 2015-08-21 00:00:00 1.62 77
USC00519281 2015-08-22 00:00:00 0.03 80
USC00519281 2015-08-23 00:00:00 2.86 80
USC00519281 2015-08-24 00:00:00 3.62 72
USC00519281 2015-08-25 00:00:00 0.31 79
USC00519281 2015-08-26 00:00:00 0.6 72
USC00519281 2015-08-27 00:00:00 2.96 75
USC00519281 2015-08-28 00:00:00 0.05 77
USC00519281 2015-08-29 00:00:00 0.01 82
USC00519281 2015-08-30 00:00:00 0.05 77
USC00519281 2015-08-31 00:00:00 0.02 76
USC00519281 2015-09-01 00:00:00 0.3 76
USC00519281 2015-09-02 00:00:00 0.01 73
USC00519281 2015-09-03 00:00:00 0.0 74
USC00519281 2015-09-04 00:00:00 1.35 75
USC00519281 2015-09-05 00:00:00 0.0 83
USC00519281 2015-09-06 00:00:00 0.0 76
USC00519281 2015-09-07 00:00:00 0.97 81
USC00519281 2015-09-08 00:00:00 0.74 81
USC00519281 2015-09-09 00:00:00 0.0 84
USC00519281 2015-09-10 00:00:00 0.09 85
USC00519281 2015-09-11 00:00:00 0.69 80
USC00519281 2015-09-12 00:00:00 3.1 79
USC00519281 2015-09-13 00:00:00 0.26 81
USC00519281 2015-09-14 00:00:00 0.52 79
USC00519281 2015-09-15 00:00:00 1.61 76
USC00519281 2015-09-16 00:00:00 0.41 80
USC00519281 2015-09-17 00:00:00 0.07 80
USC00519281 2015-09-18 00:00:00 0.42 80
USC00519281 2015-09-19 00:00:00 0.07 78
USC00519281 2015-09-20 00:00:00 0.25 79
USC00519281 2015-09-21 00:00:00 0.63 80
USC00519281 2015-09-22 00:00:00 0.37 80
USC00519281 2015-09-23 00:00:00 0.48 77
USC00519281 2015-09-24 00:00:00 0.11 77
USC00519281 2015-09-25 00:00:00 0.2 74
USC00519281 2015-09-26 00:00:00 0.49 75
USC00519281 2015-09-27 00:00:00 0.45 74
USC00519281 2015-09-28 00:00:00 0.77 77
USC00519281 2015-09-29 00:00:00 0.8 78
USC00519281 2015-09-30 00:00:00 0.14 80
USC00519281 2015-10-01 00:00:00 0.0 77
USC00519281 2015-10-02 00:00:00 0.06 73
USC00519281 2015-10-03 00:00:00 0.0 76
USC00519281 2015-10-04 00:00:00 0.09 74
USC00519281 2015-10-05 00:00:00 1.46 75
USC00519281 2015-10-06 00:00:00 0.19 75
USC00519281 2015-10-07 00:00:00 0.01 68
USC00519281 2015-10-08 00:00:00 0.09 66
USC00519281 2015-10-09 00:00:00 0.04 73
USC00519281 2015-10-11 00:00:00 0.8 76
USC00519281 2015-10-12 00:00:00 0.41 75
USC00519281 2015-10-13 00:00:00 1.53 73
USC00519281 2015-10-14 00:00:00 0.39 72
USC00519281 2015-10-15 00:00:00 1.02 77
USC00519281 2015-10-16 00:00:00 1.33 71
USC00519281 2015-10-17 00:00:00 0.51 79
USC00519281 2015-10-18 00:00:00 0.07 80
USC00519281 2015-10-19 00:00:00 0.0 73
USC00519281 2015-10-20 00:00:00 0.14 74
USC00519281 2015-10-21 00:00:00 0.33 76
USC00519281 2015-10-22 00:00:00 0.08 73
USC00519281 2015-10-23 00:00:00 0.0 70
USC00519281 2015-10-24 00:00:00 0.01 76
USC00519281 2015-10-25 00:00:00 0.0 80
USC00519281 2015-10-26 00:00:00 0.01 72
USC00519281 2015-10-27 00:00:00 0.16 75
USC00519281 2015-10-28 00:00:00 0.0 76
USC00519281 2015-10-29 00:00:00 0.07 71
USC00519281 2015-10-30 00:00:00 0.0 71
USC00519281 2015-10-31 00:00:00 0.38 78
USC00519281 2015-11-01 00:00:00 0.78 79
USC00519281 2015-11-02 00:00:00 0.02 73
USC00519281 2015-11-03 00:00:00 0.0 75
USC00519281 2015-11-04 00:00:00 0.04 77
USC00519281 2015-11-05 00:00:00 0.18 73
USC00519281 2015-11-06 00:00:00 0.29 73
USC00519281 2015-11-07 00:00:00 0.46 74
USC00519281 2015-11-08 00:00:00 0.36 79
USC00519281 2015-11-09 00:00:00 0.3 72
USC00519281 2015-11-10 00:00:00 0.47 76

USC00519281 2015-11-11 00:00:00 0.08 76
USC00519281 2015-11-12 00:00:00 0.34 72
USC00519281 2015-11-13 00:00:00 0.17 73
USC00519281 2015-11-14 00:00:00 0.23 73
USC00519281 2015-11-15 00:00:00 0.0 77
USC00519281 2015-11-16 00:00:00 0.1 71
USC00519281 2015-11-17 00:00:00 0.0 66
USC00519281 2015-11-18 00:00:00 0.34 67
USC00519281 2015-11-19 00:00:00 0.2 73
USC00519281 2015-11-20 00:00:00 1.87 71
USC00519281 2015-11-21 00:00:00 2.17 72
USC00519281 2015-11-22 00:00:00 0.85 78
USC00519281 2015-11-23 00:00:00 1.17 73
USC00519281 2015-11-24 00:00:00 0.98 70
USC00519281 2015-11-25 00:00:00 0.12 70
USC00519281 2015-11-26 00:00:00 0.82 75
USC00519281 2015-11-27 00:00:00 0.72 74
USC00519281 2015-11-28 00:00:00 0.08 76
USC00519281 2015-11-29 00:00:00 0.08 72
USC00519281 2015-11-30 00:00:00 0.04 75
USC00519281 2015-12-01 00:00:00 0.02 73
USC00519281 2015-12-02 00:00:00 0.02 74
USC00519281 2015-12-03 00:00:00 0.22 75
USC00519281 2015-12-04 00:00:00 0.03 75
USC00519281 2015-12-05 00:00:00 0.0 70
USC00519281 2015-12-06 00:00:00 0.1 72
USC00519281 2015-12-07 00:00:00 0.02 69
USC00519281 2015-12-08 00:00:00 0.02 68
USC00519281 2015-12-09 00:00:00 0.08 74
USC00519281 2015-12-10 00:00:00 0.1 72
USC00519281 2015-12-11 00:00:00 0.15 75
USC00519281 2015-12-12 00:00:00 0.31 79
USC00519281 2015-12-13 00:00:00 0.03 69
USC00519281 2015-12-14 00:00:00 0.13 67
USC00519281 2015-12-15 00:00:00 0.35 73
USC00519281 2015-12-16 00:00:00 0.03 74
USC00519281 2015-12-17 00:00:00 0.09 75
USC00519281 2015-12-18 00:00:00 0.17 72
USC00519281 2015-12-19 00:00:00 0.13 76
USC00519281 2015-12-20 00:00:00 0.05 74
USC00519281 2015-12-21 00:00:00 0.15 75
USC00519281 2015-12-22 00:00:00 0.04 74
USC00519281 2015-12-23 00:00:00 0.1 74
USC00519281 2015-12-24 00:00:00 0.45 76
USC00519281 2015-12-25 00:00:00 0.47 74
USC00519281 2015-12-26 00:00:00 0.22 75
USC00519281 2015-12-27 00:00:00 0.8 75
USC00519281 2015-12-28 00:00:00 0.0 73
USC00519281 2015-12-29 00:00:00 0.16 76
USC00519281 2015-12-30 00:00:00 0.5 74
USC00519281 2015-12-31 00:00:00 0.09 73
USC00519281 2016-01-01 00:00:00 0.02 74
USC00519281 2016-01-02 00:00:00 0.03 72
USC00519281 2016-01-03 00:00:00 0.0 68
USC00519281 2016-01-04 00:00:00 0.0 69
USC00519281 2016-01-05 00:00:00 0.18 70
USC00519281 2016-01-06 00:00:00 0.35 69
USC00519281 2016-01-07 00:00:00 0.35 76
USC00519281 2016-01-08 00:00:00 0.02 75
USC00519281 2016-01-09 00:00:00 0.02 74
USC00519281 2016-01-10 00:00:00 0.02 74
USC00519281 2016-01-11 00:00:00 0.0 73
USC00519281 2016-01-12 00:00:00 0.02 75
USC00519281 2016-01-13 00:00:00 0.0 74
USC00519281 2016-01-14 00:00:00 0.0 66
USC00519281 2016-01-15 00:00:00 0.02 71
USC00519281 2016-01-16 00:00:00 0.05 73
USC00519281 2016-01-17 00:00:00 0.0 75
USC00519281 2016-01-18 00:00:00 0.0 63
USC00519281 2016-01-19 00:00:00 0.0 61
USC00519281 2016-01-20 00:00:00 0.01 62
USC00519281 2016-01-21 00:00:00 0.42 65
USC00519281 2016-01-22 00:00:00 0.0 65
USC00519281 2016-01-23 00:00:00 0.0 75
USC00519281 2016-01-24 00:00:00 0.0 78
USC00519281 2016-01-25 00:00:00 0.07 69
USC00519281 2016-01-26 00:00:00 0.74 65
USC00519281 2016-01-27 00:00:00 0.01 69
USC00519281 2016-01-28 00:00:00 0.0 64
USC00519281 2016-01-29 00:00:00 0.02 68
USC00519281 2016-01-30 00:00:00 0.01 73
USC00519281 2016-01-31 00:00:00 0.02 74
USC00519281 2016-02-01 00:00:00 0.07 69
USC00519281 2016-02-02 00:00:00 0.42 68
USC00519281 2016-02-03 00:00:00 0.2 69
USC00519281 2016-02-04 00:00:00 0.04 65
USC00519281 2016-02-05 00:00:00 0.0 67
USC00519281 2016-02-06 00:00:00 0.0 69
USC00519281 2016-02-07 00:00:00 0.05 70
USC00519281 2016-02-08 00:00:00 0.0 56
USC00519281 2016-02-09 00:00:00 0.0 57
USC00519281 2016-02-10 00:00:00 0.0 58
USC00519281 2016-02-11 00:00:00 0.0 61
USC00519281 2016-02-12 00:00:00 0.01 71
USC00519281 2016-02-13 00:00:00 0.22 74
USC00519281 2016-02-14 00:00:00 0.0 71
USC00519281 2016-02-15 00:00:00 0.0 75
USC00519281 2016-02-16 00:00:00 0.03 72
USC00519281 2016-02-17 00:00:00 0.11 71
USC00519281 2016-02-18 00:00:00 0.02 72
USC00519281 2016-02-19 00:00:00 0.0 69
USC00519281 2016-02-20 00:00:00 0.06 71
USC00519281 2016-02-21 00:00:00 0.08 72
USC00519281 2016-02-22 00:00:00 0.04 60
USC00519281 2016-02-23 00:00:00 0.0 69
USC00519281 2016-02-24 00:00:00 0.0 67
USC00519281 2016-02-25 00:00:00 0.0 64
USC00519281 2016-02-26 00:00:00 0.3 69
USC00519281 2016-02-27 00:00:00 0.0 69
USC00519281 2016-02-28 00:00:00 0.0 71
USC00519281 2016-02-29 00:00:00 0.0 69
USC00519281 2016-03-01 00:00:00 0.01 72
USC00519281 2016-03-02 00:00:00 0.0 63
USC00519281 2016-03-03 00:00:00 0.0 63
USC00519281 2016-03-04 00:00:00 0.0 62
USC00519281 2016-03-05 00:00:00 0.0 70
USC00519281 2016-03-06 00:00:00 0.0 72
USC00519281 2016-03-07 00:00:00 0.0 67
USC00519281 2016-03-08 00:00:00 0.0 74
USC00519281 2016-03-09 00:00:00 0.34 66
USC00519281 2016-03-10 00:00:00 0.01 68
USC00519281 2016-03-11 00:00:00 0.02 68
USC00519281 2016-03-12 00:00:00 0.0 72
USC00519281 2016-03-13 00:00:00 0.03 72
USC00519281 2016-03-14 00:00:00 0.03 71
USC00519281 2016-03-15 00:00:00 0.82 70
USC00519281 2016-03-16 00:00:00 0.23 68
USC00519281 2016-03-17 00:00:00 0.01 68
USC00519281 2016-03-18 00:00:00 0.08 68
USC00519281 2016-03-19 00:00:00 0.16 68
USC00519281 2016-03-20 00:00:00 0.0 71
USC00519281 2016-03-21 00:00:00 0.0 66
USC00519281 2016-03-22 00:00:00 0.1 65
USC00519281 2016-03-23 00:00:00 0.31 63
USC00519281 2016-03-24 00:00:00 0.0 64
USC00519281 2016-03-25 00:00:00 0.38 72
USC00519281 2016-03-26 00:00:00 0.06 76
USC00519281 2016-03-27 00:00:00 0.08 76
USC00519281 2016-03-28 00:00:00 0.0 73
USC00519281 2016-03-29 00:00:00 0.02 72
USC00519281 2016-03-30 00:00:00 0.04 62
USC00519281 2016-03-31 00:00:00 0.0 65
USC00519281 2016-04-01 00:00:00 0.0 68
USC00519281 2016-04-02 00:00:00 0.0 74
USC00519281 2016-04-03 00:00:00 0.0 74
USC00519281 2016-04-04 00:00:00 0.0 74
USC00519281 2016-04-05 00:00:00 0.01 65
USC00519281 2016-04-06 00:00:00 0.34 69
USC00519281 2016-04-07 00:00:00 0.43 65
USC00519281 2016-04-08 00:00:00 1.26 68
USC00519281 2016-04-09 00:00:00 0.27 74
USC00519281 2016-04-10 00:00:00 0.11 70
USC00519281 2016-04-11 00:00:00 0.05 71
USC00519281 2016-04-12 00:00:00 0.11 74
USC00519281 2016-04-13 00:00:00 0.04 75
USC00519281 2016-04-14 00:00:00 0.05 73
USC00519281 2016-04-15 00:00:00 0.01 74
USC00519281 2016-04-16 00:00:00 0.06 76
USC00519281 2016-04-17 00:00:00 0.32 71
USC00519281 2016-04-18 00:00:00 0.83 68
USC00519281 2016-04-19 00:00:00 0.18 67
USC00519281 2016-04-20 00:00:00 0.06 72
USC00519281 2016-04-21 00:00:00 0.0 73
USC00519281 2016-04-22 00:00:00 0.07 73
USC00519281 2016-04-23 00:00:00 0.23 75
USC00519281 2016-04-24 00:00:00 0.21 75
USC00519281 2016-04-25 00:00:00 0.03 74
USC00519281 2016-04-26 00:00:00 0.01 74
USC00519281 2016-04-27 00:00:00 0.01 74
USC00519281 2016-04-28 00:00:00 0.04 73
USC00519281 2016-04-29 00:00:00 0.0 74
USC00519281 2016-04-30 00:00:00 0.1 74
USC00519281 2016-05-01 00:00:00 0.03 75
USC00519281 2016-05-02 00:00:00 0.12 73
USC00519281 2016-05-03 00:00:00 0.0 74
USC00519281 2016-05-04 00:00:00 0.31 72
USC00519281 2016-05-05 00:00:00 0.91 68
USC00519281 2016-05-06 00:00:00 0.15 66
USC00519281 2016-05-07 00:00:00 1.02 69
USC00519281 2016-05-08 00:00:00 0.38 67
USC00519281 2016-05-09 00:00:00 0.13 68
USC00519281 2016-05-10 00:00:00 0.43 68
USC00519281 2016-05-11 00:00:00 0.16 67
USC00519281 2016-05-12 00:00:00 0.07 65
USC00519281 2016-05-13 00:00:00 0.01 68
USC00519281 2016-05-14 00:00:00 0.01 70
USC00519281 2016-05-15 00:00:00 0.17 76
USC00519281 2016-05-16 00:00:00 0.0 75
USC00519281 2016-05-17 00:00:00 0.0 75
USC00519281 2016-05-18 00:00:00 0.08 72
USC00519281 2016-05-19 00:00:00 0.22 75
USC00519281 2016-05-20 00:00:00 0.11 72
USC00519281 2016-05-21 00:00:00 0.16 76
USC00519281 2016-05-22 00:00:00 0.04 76
USC00519281 2016-05-23 00:00:00 0.0 74
USC00519281 2016-05-24 00:00:00 0.0 69
USC00519281 2016-05-25 00:00:00 0.03 71
USC00519281 2016-05-26 00:00:00 1.04 74
USC00519281 2016-05-27 00:00:00 0.1 75
USC00519281 2016-05-28 00:00:00 0.05 72
USC00519281 2016-05-29 00:00:00 0.0 74
USC00519281 2016-05-30 00:00:00 0.0 70
USC00519281 2016-05-31 00:00:00 0.85 70
USC00519281 2016-06-01 00:00:00 1.39 69
USC00519281 2016-06-02 00:00:00 0.5 67
USC00519281 2016-06-03 00:00:00 0.02 68
USC00519281 2016-06-04 00:00:00 0.0 65
USC00519281 2016-06-05 00:00:00 0.22 70
USC00519281 2016-06-06 00:00:00 0.52 72
USC00519281 2016-06-07 00:00:00 0.35 74
USC00519281 2016-06-08 00:00:00 0.0 73
USC00519281 2016-06-09 00:00:00 0.29 71
USC00519281 2016-06-10 00:00:00 0.62 75
USC00519281 2016-06-11 00:00:00 0.13 72
USC00519281 2016-06-12 00:00:00 0.28 75
USC00519281 2016-06-13 00:00:00 0.02 76
USC00519281 2016-06-14 00:00:00 0.2 75
USC00519281 2016-06-15 00:00:00 0.68 76
USC00519281 2016-06-16 00:00:00 0.05 75
USC00519281 2016-06-17 00:00:00 0.29 71
USC00519281 2016-06-18 00:00:00 0.4 75
USC00519281 2016-06-19 00:00:00 0.05 75
USC00519281 2016-06-20 00:00:00 0.4 72
USC00519281 2016-06-21 00:00:00 0.04 72
USC00519281 2016-06-22 00:00:00 0.13 75
USC00519281 2016-06-23 00:00:00 0.39 73
USC00519281 2016-06-24 00:00:00 0.12 76
USC00519281 2016-06-25 00:00:00 0.75 74
USC00519281 2016-06-26 00:00:00 0.03 77
USC00519281 2016-06-27 00:00:00 0.37 72
USC00519281 2016-06-28 00:00:00 0.23 71
USC00519281 2016-06-29 00:00:00 0.1 76
USC00519281 2016-06-30 00:00:00 0.01 77
USC00519281 2016-07-01 00:00:00 0.0 76
USC00519281 2016-07-02 00:00:00 0.0 79
USC00519281 2016-07-03 00:00:00 0.03 76
USC00519281 2016-07-04 00:00:00 0.27 79
USC00519281 2016-07-05 00:00:00 0.22 75
USC00519281 2016-07-06 00:00:00 0.8 74
USC00519281 2016-07-07 00:00:00 0.14 73
USC00519281 2016-07-08 00:00:00 0.02 78
USC00519281 2016-07-09 00:00:00 0.04 80
USC00519281 2016-07-10 00:00:00 0.63 72
USC00519281 2016-07-11 00:00:00 0.14 79
USC00519281 2016-07-12 00:00:00 0.0 80
USC00519281 2016-07-13 00:00:00 0.07 76
USC00519281 2016-07-14 00:00:00 0.8 80
USC00519281 2016-07-15 00:00:00 0.14 80
USC00519281 2016-07-16 00:00:00 0.92 73
USC00519281 2016-07-17 00:00:00 0.15 77
USC00519281 2016-07-18 00:00:00 0.23 78
USC00519281 2016-07-19 00:00:00 0.73 79
USC00519281 2016-07-20 00:00:00 0.02 80
USC00519281 2016-07-21 00:00:00 0.01 79
USC00519281 2016-07-22 00:00:00 0.13 78
USC00519281 2016-07-23 00:00:00 0.07 75
USC00519281 2016-07-24 00:00:00 0.45 76
USC00519281 2016-07-25 00:00:00 9.64 78
USC00519281 2016-07-26 00:00:00 0.9 78
USC00519281 2016-07-27 00:00:00 0.06 80
USC00519281 2016-07-28 00:00:00 0.0 81
USC00519281 2016-07-29 00:00:00 0.0 80
USC00519281 2016-07-30 00:00:00 0.01 77
USC00519281 2016-07-31 00:00:00 0.12 75
USC00519281 2016-08-01 00:00:00 3.53 76
USC00519281 2016-08-02 00:00:00 0.83 76
USC00519281 2016-08-03 00:00:00 0.01 77
USC00519281 2016-08-04 00:00:00 0.77 77
USC00519281 2016-08-05 00:00:00 0.27 81
USC00519281 2016-08-06 00:00:00 0.14 78
USC00519281 2016-08-07 00:00:00 0.47 78
USC00519281 2016-08-08 00:00:00 0.28 81
USC00519281 2016-08-09 00:00:00 0.02 81
USC00519281 2016-08-10 00:00:00 0.0 82
USC00519281 2016-08-11 00:00:00 0.01 80
USC00519281 2016-08-12 00:00:00 0.02 76
USC00519281 2016-08-13 00:00:00 0.08 80
USC00519281 2016-08-14 00:00:00 0.1 76
USC00519281 2016-08-15 00:00:00 0.23 75
USC00519281 2016-08-16 00:00:00 0.12 74
USC00519281 2016-08-17 00:00:00 0.31 82
USC00519281 2016-08-18 00:00:00 0.0 80
USC00519281 2016-08-19 00:00:00 0.31 79
USC00519281 2016-08-20 00:00:00 0.13 81
USC00519281 2016-08-21 00:00:00 0.08 79
USC00519281 2016-08-22 00:00:00 2.32 78
USC00519281 2016-08-23 00:00:00 1.79 77
USC00519281 2016-08-24 00:00:00 2.15 77
USC00519281 2016-08-25 00:00:00 0.06 80
USC00519281 2016-08-26 00:00:00 0.01 80
USC00519281 2016-08-27 00:00:00 0.12 75
USC00519281 2016-08-28 00:00:00 0.6 73
USC00519281 2016-08-29 00:00:00 0.35 78
USC00519281 2016-08-30 00:00:00 0.0 77
USC00519281 2016-08-31 00:00:00 0.24 78
USC00519281 2016-09-01 00:00:00 0.02 80
USC00519281 2016-09-02 00:00:00 0.01 80
USC00519281 2016-09-03 00:00:00 0.12 78
USC00519281 2016-09-04 00:00:00 0.14 78
USC00519281 2016-09-05 00:00:00 0.03 78
USC00519281 2016-09-06 00:00:00 0.11 73
USC00519281 2016-09-07 00:00:00 0.16 74
USC00519281 2016-09-08 00:00:00 0.07 80
USC00519281 2016-09-09 00:00:00 0.16 79
USC00519281 2016-09-10 00:00:00 0.09 77
USC00519281 2016-09-11 00:00:00 0.3 80
USC00519281 2016-09-12 00:00:00 0.31 76
USC00519281 2016-09-13 00:00:00 0.34 79
USC00519281 2016-09-14 00:00:00 2.33 75
USC00519281 2016-09-15 00:00:00 0.83 79
USC00519281 2016-09-16 00:00:00 0.06 78
USC00519281 2016-09-17 00:00:00 0.36 79
USC00519281 2016-09-18 00:00:00 0.07 78
USC00519281 2016-09-19 00:00:00 0.01 78
USC00519281 2016-09-20 00:00:00 0.22 76
USC00519281 2016-09-21 00:00:00 0.07 74
USC00519281 2016-09-22 00:00:00 0.34 77
USC00519281 2016-09-23 00:00:00 0.94 78
USC00519281 2016-09-24 00:00:00 0.01 79
USC00519281 2016-09-25 00:00:00 0.03 79
USC00519281 2016-09-26 00:00:00 0.17 77
USC00519281 2016-09-27 00:00:00 0.17 80
USC00519281 2016-09-28 00:00:00 0.0 78
USC00519281 2016-09-29 00:00:00 0.59 78
USC00519281 2016-09-30 00:00:00 0.25 78
USC00519281 2016-10-01 00:00:00 0.14 77
USC00519281 2016-10-02 00:00:00 0.06 79
USC00519281 2016-10-03 00:00:00 0.16 79
USC00519281 2016-10-04 00:00:00 0.03 79
USC00519281 2016-10-05 00:00:00 0.01 79
USC00519281 2016-10-06 00:00:00 0.0 75
USC00519281 2016-10-07 00:00:00 0.0 76
USC00519281 2016-10-08 00:00:00 0.0 73
USC00519281 2016-10-09 00:00:00 0.0 72
USC00519281 2016-10-10 00:00:00 0.0 71
USC00519281 2016-10-11 00:00:00 0.28 77
USC00519281 2016-10-12 00:00:00 0.03 79
USC00519281 2016-10-13 00:00:00 0.0 78
USC00519281 2016-10-14 00:00:00 0.0 79
USC00519281 2016-10-15 00:00:00 0.04 77
USC00519281 2016-10-16 00:00:00 0.0 79
USC00519281 2016-10-17 00:00:00 0.01 77
USC00519281 2016-10-18 00:00:00 0.02 78
USC00519281 2016-10-19 00:00:00 0.11 78
USC00519281 2016-10-20 00:00:00 0.0 78
USC00519281 2016-10-21 00:00:00 0.0 78
USC00519281 2016-10-22 00:00:00 0.15 77
USC00519281 2016-10-23 00:00:00 0.02 74
USC00519281 2016-10-24 00:00:00 0.08 75
USC00519281 2016-10-25 00:00:00 0.11 76
USC00519281 2016-10-26 00:00:00 0.01 73
USC00519281 2016-10-27 00:00:00 0.22 76
USC00519281 2016-10-28 00:00:00 0.05 74
USC00519281 2016-10-29 00:00:00 0.1 77
USC00519281 2016-10-30 00:00:00 0.16 76
USC00519281 2016-10-31 00:00:00 0.07 76
USC00519281 2016-11-01 00:00:00 0.1 74
USC00519281 2016-11-02 00:00:00 0.0 75
USC00519281 2016-11-03 00:00:00 0.0 75
USC00519281 2016-11-04 00:00:00 0.0 75
USC00519281 2016-11-05 00:00:00 0.03 75
USC00519281 2016-11-06 00:00:00 0.01 71
USC00519281 2016-11-07 00:00:00 0.0 63
USC00519281 2016-11-08 00:00:00 0.21 70
USC00519281 2016-11-09 00:00:00 0.11 68
USC00519281 2016-11-10 00:00:00 0.0 67
USC00519281 2016-11-11 00:00:00 0.0 77
USC00519281 2016-11-12 00:00:00 0.0 74
USC00519281 2016-11-13 00:00:00 0.0 77
USC00519281 2016-11-14 00:00:00 0.0 76
USC00519281 2016-11-15 00:00:00 0.0 76
USC00519281 2016-11-16 00:00:00 0.24 75
USC00519281 2016-11-17 00:00:00 0.01 76
USC00519281 2016-11-18 00:00:00 0.0 75
USC00519281 2016-11-19 00:00:00 0.11 73

USC00519281 2016-11-20 00:00:00 0.39 75
USC00519281 2016-11-21 00:00:00 0.11 73
USC00519281 2016-11-22 00:00:00 2.05 75
USC00519281 2016-11-23 00:00:00 0.25 74
USC00519281 2016-11-24 00:00:00 0.3 75
USC00519281 2016-11-25 00:00:00 0.08 74
USC00519281 2016-11-26 00:00:00 0.06 75
USC00519281 2016-11-27 00:00:00 0.17 73
USC00519281 2016-11-28 00:00:00 0.0 75
USC00519281 2016-11-29 00:00:00 0.09 73
USC00519281 2016-11-30 00:00:00 0.05 73
USC00519281 2016-12-01 00:00:00 0.37 74
USC00519281 2016-12-02 00:00:00 0.35 70
USC00519281 2016-12-03 00:00:00 0.77 72
USC00519281 2016-12-04 00:00:00 0.04 70
USC00519281 2016-12-05 00:00:00 0.22 67
USC00519281 2016-12-06 00:00:00 0.0 67
USC00519281 2016-12-07 00:00:00 0.12 69
USC00519281 2016-12-08 00:00:00 0.07 70
USC00519281 2016-12-09 00:00:00 0.31 68
USC00519281 2016-12-10 00:00:00 0.02 69
USC00519281 2016-12-11 00:00:00 0.0 69
USC00519281 2016-12-12 00:00:00 0.0 66
USC00519281 2016-12-13 00:00:00 0.04 65
USC00519281 2016-12-14 00:00:00 0.92 68
USC00519281 2016-12-15 00:00:00 0.14 62
USC00519281 2016-12-16 00:00:00 0.03 75
USC00519281 2016-12-17 00:00:00 0.07 70
USC00519281 2016-12-18 00:00:00 0.16 69
USC00519281 2016-12-19 00:00:00 0.03 76
USC00519281 2016-12-20 00:00:00 0.0 76
USC00519281 2016-12-21 00:00:00 0.11 74
USC00519281 2016-12-22 00:00:00 0.86 73
USC00519281 2016-12-23 00:00:00 0.24 71
USC00519281 2016-12-24 00:00:00 0.2 74
USC00519281 2016-12-25 00:00:00 0.02 74
USC00519281 2016-12-26 00:00:00 0.22 72
USC00519281 2016-12-27 00:00:00 0.05 71
USC00519281 2016-12-28 00:00:00 0.09 72
USC00519281 2016-12-29 00:00:00 0.52 74
USC00519281 2016-12-30 00:00:00 0.29 69
USC00519281 2016-12-31 00:00:00 0.25 67
USC00519281 2017-01-01 00:00:00 0.03 72
USC00519281 2017-01-02 00:00:00 0.01 70
USC00519281 2017-01-03 00:00:00 0.0 64
USC00519281 2017-01-04 00:00:00 0.0 63
USC00519281 2017-01-05 00:00:00 0.06 63
USC00519281 2017-01-06 00:00:00 0.1 62
USC00519281 2017-01-07 00:00:00 0.0 70
USC00519281 2017-01-08 00:00:00 0.0 70
USC00519281 2017-01-09 00:00:00 0.0 62
USC00519281 2017-01-10 00:00:00 0.0 62
USC00519281 2017-01-11 00:00:00 0.0 63
USC00519281 2017-01-12 00:00:00 0.0 65
USC00519281 2017-01-13 00:00:00 0.0 69
USC00519281 2017-01-14 00:00:00 0.01 77
USC00519281 2017-01-15 00:00:00 0.0 70
USC00519281 2017-01-16 00:00:00 0.0 74
USC00519281 2017-01-17 00:00:00 0.0 69
USC00519281 2017-01-18 00:00:00 0.0 72
USC00519281 2017-01-19 00:00:00 0.02 71
USC00519281 2017-01-20 00:00:00 0.0 69
USC00519281 2017-01-21 00:00:00 0.03 71
USC00519281 2017-01-22 00:00:00 0.09 71
USC00519281 2017-01-23 00:00:00 0.01 72
USC00519281 2017-01-24 00:00:00 0.13 72
USC00519281 2017-01-25 00:00:00 0.79 69
USC00519281 2017-01-26 00:00:00 0.0 70
USC00519281 2017-01-27 00:00:00 0.03 66
USC00519281 2017-01-28 00:00:00 0.0 65
USC00519281 2017-01-29 00:00:00 0.26 69
USC00519281 2017-01-30 00:00:00 0.0 68
USC00519281 2017-01-31 00:00:00 0.0 68
USC00519281 2017-02-01 00:00:00 0.0 68
USC00519281 2017-02-02 00:00:00 0.0 59
USC00519281 2017-02-03 00:00:00 0.0 60
USC00519281 2017-02-04 00:00:00 0.0 70
USC00519281 2017-02-05 00:00:00 0.0 73
USC00519281 2017-02-06 00:00:00 0.18 75
USC00519281 2017-02-07 00:00:00 1.32 64
USC00519281 2017-02-08 00:00:00 0.0 59
USC00519281 2017-02-09 00:00:00 0.0 59
USC00519281 2017-02-10 00:00:00 0.0 62
USC00519281 2017-02-11 00:00:00 1.73 68
USC00519281 2017-02-12 00:00:00 2.98 70
USC00519281 2017-02-13 00:00:00 0.01 73
USC00519281 2017-02-14 00:00:00 0.0 79
USC00519281 2017-02-15 00:00:00 0.01 75
USC00519281 2017-02-16 00:00:00 0.73 65
USC00519281 2017-02-17 00:00:00 0.13 70
USC00519281 2017-02-18 00:00:00 0.0 74
USC00519281 2017-02-19 00:00:00 0.09 70
USC00519281 2017-02-20 00:00:00 0.0 70
USC00519281 2017-02-21 00:00:00 0.0 71
USC00519281 2017-02-22 00:00:00 0.06 71
USC00519281 2017-02-23 00:00:00 0.0 71
USC00519281 2017-02-24 00:00:00 0.0 69
USC00519281 2017-02-25 00:00:00 0.0 61
USC00519281 2017-02-26 00:00:00 0.0 67
USC00519281 2017-02-27 00:00:00 0.0 65
USC00519281 2017-02-28 00:00:00 0.04 72
USC00519281 2017-03-01 00:00:00 2.12 71
USC00519281 2017-03-02 00:00:00 1.88 73
USC00519281 2017-03-03 00:00:00 0.27 72
USC00519281 2017-03-04 00:00:00 0.0 77
USC00519281 2017-03-05 00:00:00 0.41 73
USC00519281 2017-03-06 00:00:00 0.03 67
USC00519281 2017-03-07 00:00:00 0.0 62
USC00519281 2017-03-08 00:00:00 0.0 64
USC00519281 2017-03-09 00:00:00 0.65 67
USC00519281 2017-03-10 00:00:00 0.03 66
USC00519281 2017-03-11 00:00:00 0.01 81
USC00519281 2017-03-12 00:00:00 0.0 69
USC00519281 2017-03-13 00:00:00 0.0 66
USC00519281 2017-03-14 00:00:00 0.0 67
USC00519281 2017-03-15 00:00:00 0.06 69
USC00519281 2017-03-16 00:00:00 0.0 66
USC00519281 2017-03-17 00:00:00 0.12 68
USC00519281 2017-03-18 00:00:00 0.0 65
USC00519281 2017-03-19 00:00:00 0.0 74
USC00519281 2017-03-20 00:00:00 0.02 69
USC00519281 2017-03-21 00:00:00 0.09 72
USC00519281 2017-03-22 00:00:00 0.0 73
USC00519281 2017-03-23 00:00:00 0.0 72
USC00519281 2017-03-24 00:00:00 0.12 71
USC00519281 2017-03-25 00:00:00 0.93 76
USC00519281 2017-03-26 00:00:00 0.0 77
USC00519281 2017-03-27 00:00:00 0.01 76
USC00519281 2017-03-28 00:00:00 0.0 74
USC00519281 2017-03-29 00:00:00 0.01 68
USC00519281 2017-03-30 00:00:00 0.04 73
USC00519281 2017-03-31 00:00:00 0.01 71
USC00519281 2017-04-01 00:00:00 0.21 74
USC00519281 2017-04-02 00:00:00 0.0 75
USC00519281 2017-04-03 00:00:00 0.26 70
USC00519281 2017-04-04 00:00:00 0.09 67
USC00519281 2017-04-05 00:00:00 0.1 71
USC00519281 2017-04-06 00:00:00 0.06 67
USC00519281 2017-04-07 00:00:00 0.0 74
USC00519281 2017-04-08 00:00:00 0.0 77
USC00519281 2017-04-09 00:00:00 0.0 78
USC00519281 2017-04-10 00:00:00 0.01 67
USC00519281 2017-04-11 00:00:00 0.03 70
USC00519281 2017-04-12 00:00:00 0.11 69
USC00519281 2017-04-13 00:00:00 0.59 69
USC00519281 2017-04-14 00:00:00 2.3 74
USC00519281 2017-04-15 00:00:00 0.38 78
USC00519281 2017-04-16 00:00:00 0.47 71
USC00519281 2017-04-17 00:00:00 1.04 67
USC00519281 2017-04-18 00:00:00 2.03 68
USC00519281 2017-04-19 00:00:00 0.02 67
USC00519281 2017-04-20 00:00:00 0.05 76
USC00519281 2017-04-21 00:00:00 1.74 69
USC00519281 2017-04-22 00:00:00 1.58 72
USC00519281 2017-04-23 00:00:00 0.06 76
USC00519281 2017-04-24 00:00:00 0.01 68
USC00519281 2017-04-25 00:00:00 0.0 72
USC00519281 2017-04-26 00:00:00 0.02 74
USC00519281 2017-04-27 00:00:00 0.19 70
USC00519281 2017-04-28 00:00:00 0.76 67
USC00519281 2017-04-29 00:00:00 0.37 72
USC00519281 2017-04-30 00:00:00 1.04 60
USC00519281 2017-05-01 00:00:00 0.13 65
USC00519281 2017-05-02 00:00:00 0.01 75
USC00519281 2017-05-03 00:00:00 0.01 70
USC00519281 2017-05-04 00:00:00 0.0 75
USC00519281 2017-05-05 00:00:00 0.0 70
USC00519281 2017-05-06 00:00:00 0.0 79
USC00519281 2017-05-07 00:00:00 0.02 75
USC00519281 2017-05-08 00:00:00 0.73 70
USC00519281 2017-05-09 00:00:00 1.58 67
USC00519281 2017-05-10 00:00:00 0.2 74
USC00519281 2017-05-11 00:00:00 0.12 70
USC00519281 2017-05-12 00:00:00 0.02 75
USC00519281 2017-05-13 00:00:00 0.12 76
USC00519281 2017-05-14 00:00:00 0.17 77
USC00519281 2017-05-15 00:00:00 0.09 74
USC00519281 2017-05-16 00:00:00 0.03 74
USC00519281 2017-05-17 00:00:00 0.07 74
USC00519281 2017-05-18 00:00:00 0.13 69
USC00519281 2017-05-19 00:00:00 0.01 68
USC00519281 2017-05-20 00:00:00 0.02 76
USC00519281 2017-05-21 00:00:00 0.01 74
USC00519281 2017-05-22 00:00:00 0.06 71
USC00519281 2017-05-23 00:00:00 0.06 71
USC00519281 2017-05-24 00:00:00 0.3 74
USC00519281 2017-05-25 00:00:00 0.2 74
USC00519281 2017-05-26 00:00:00 0.0 74
USC00519281 2017-05-27 00:00:00 0.0 74
USC00519281 2017-05-28 00:00:00 0.08 80
USC00519281 2017-05-29 00:00:00 0.4 74
USC00519281 2017-05-30 00:00:00 1.12 72
USC00519281 2017-05-31 00:00:00 0.25 75
USC00519281 2017-06-01 00:00:00 0.0 80
USC00519281 2017-06-02 00:00:00 0.09 76
USC00519281 2017-06-03 00:00:00 0.08 76
USC00519281 2017-06-04 00:00:00 0.13 77
USC00519281 2017-06-05 00:00:00 0.05 75
USC00519281 2017-06-06 00:00:00 0.0 75
USC00519281 2017-06-07 00:00:00 0.0 75
USC00519281 2017-06-08 00:00:00 0.0 75
USC00519281 2017-06-09 00:00:00 0.02 72
USC00519281 2017-06-10 00:00:00 0.62 74
USC00519281 2017-06-11 00:00:00 0.74 74
USC00519281 2017-06-12 00:00:00 0.24 74
USC00519281 2017-06-13 00:00:00 0.24 76
USC00519281 2017-06-14 00:00:00 0.22 74
USC00519281 2017-06-15 00:00:00 0.55 75
USC00519281 2017-06-16 00:00:00 0.06 73
USC00519281 2017-06-17 00:00:00 0.07 79
USC00519281 2017-06-18 00:00:00 0.24 75
USC00519281 2017-06-19 00:00:00 0.08 72
USC00519281 2017-06-20 00:00:00 0.0 72
USC00519281 2017-06-21 00:00:00 0.19 74
USC00519281 2017-06-22 00:00:00 0.06 72
USC00519281 2017-06-23 00:00:00 0.12 72
USC00519281 2017-06-24 00:00:00 0.36 77
USC00519281 2017-06-25 00:00:00 0.02 71
USC00519281 2017-06-26 00:00:00 0.06 73
USC00519281 2017-06-27 00:00:00 0.01 76
USC00519281 2017-06-28 00:00:00 0.0 77
USC00519281 2017-06-29 00:00:00 0.0 76
USC00519281 2017-06-30 00:00:00 0.01 76
USC00519281 2017-07-01 00:00:00 0.08 79
USC00519281 2017-07-02 00:00:00 0.15 81
USC00519281 2017-07-03 00:00:00 0.15 76
USC00519281 2017-07-04 00:00:00 0.08 78
USC00519281 2017-07-05 00:00:00 0.0 77
USC00519281 2017-07-06 00:00:00 0.0 74
USC00519281 2017-07-07 00:00:00 0.18 75
USC00519281 2017-07-08 00:00:00 0.0 78
USC00519281 2017-07-09 00:00:00 0.11 78
USC00519281 2017-07-10 00:00:00 0.02 69
USC00519281 2017-07-11 00:00:00 0.02 72
USC00519281 2017-07-12 00:00:00 0.28 74
USC00519281 2017-07-13 00:00:00 0.32 74
USC00519281 2017-07-14 00:00:00 0.2 76
USC00519281 2017-07-15 00:00:00 0.05 80
USC00519281 2017-07-16 00:00:00 0.1 80
USC00519281 2017-07-17 00:00:00 0.21 76
USC00519281 2017-07-18 00:00:00 0.05 76
USC00519281 2017-07-19 00:00:00 0.05 76
USC00519281 2017-07-20 00:00:00 0.06 77
USC00519281 2017-07-21 00:00:00 0.03 77
USC00519281 2017-07-22 00:00:00 0.2 77
USC00519281 2017-07-23 00:00:00 0.2 82
USC00519281 2017-07-24 00:00:00 0.61 75
USC00519281 2017-07-25 00:00:00 0.11 77
USC00519281 2017-07-26 00:00:00 0.12 75
USC00519281 2017-07-27 00:00:00 0.01 76
USC00519281 2017-07-28 00:00:00 0.09 81
USC00519281 2017-07-29 00:00:00 0.23 82
USC00519281 2017-07-30 00:00:00 0.0 81
USC00519281 2017-07-31 00:00:00 0.0 76
USC00519281 2017-08-04 00:00:00 0.0 77
USC00519281 2017-08-05 00:00:00 0.06 82
USC00519281 2017-08-06 00:00:00 0.0 83
USC00519281 2017-08-13 00:00:00 0.0 77
USC00519281 2017-08-14 00:00:00 0.0 77
USC00519281 2017-08-15 00:00:00 0.32 77
USC00519281 2017-08-16 00:00:00 0.12 76
USC00519281 2017-08-17 00:00:00 0.01 76
USC00519281 2017-08-18 00:00:00 0.06 79
USC00511918 HONOLULU OBSERVATORY 702.2, HI US
USC00511918 2010-01-01 00:00:00 0.05 66
USC00511918 2010-01-02 00:00:00 0.0 70
USC00511918 2010-01-03 00:00:00 0.0 75
USC00511918 2010-01-04 00:00:00 0.0 75
USC00511918 2010-01-05 00:00:00 0.0 75
USC00511918 2010-01-06 00:00:00 0.08 72
USC00511918 2010-01-07 00:00:00 0.04 70
USC00511918 2010-01-08 00:00:00 0.0 63
USC00511918 2010-01-09 00:00:00 0.0 68
USC00511918 2010-01-10 00:00:00 0.0 74
USC00511918 2010-01-11 00:00:00 0.05 64
USC00511918 2010-01-12 00:00:00 0.0 57
USC00511918 2010-01-13 00:00:00 0.0 57
USC00511918 2010-01-14 00:00:00 0.0 65
USC00511918 2010-01-15 00:00:00 0.0 56
USC00511918 2010-01-16 00:00:00 0.0 66
USC00511918 2010-01-18 00:00:00 0.0 73
USC00511918 2010-01-19 00:00:00 0.0 61
USC00511918 2010-01-20 00:00:00 0.0 66
USC00511918 2010-01-21 00:00:00 0.0 68
USC00511918 2010-01-22 00:00:00 0.0 60
USC00511918 2010-01-23 00:00:00 0.0 78
USC00511918 2010-01-24 00:00:00 0.0 71
USC00511918 2010-01-25 00:00:00 0.0 68
USC00511918 2010-01-26 00:00:00 0.03 76
USC00511918 2010-01-27 00:00:00 0.25 69
USC00511918 2010-01-29 00:00:00 0.0 65
USC00511918 2010-01-30 00:00:00 0.4 77
USC00511918 2010-01-31 00:00:00 0.01 71
USC00511918 2010-02-01 00:00:00 0.0 64
USC00511918 2010-02-02 00:00:00 0.0 65
USC00511918 2010-02-03 00:00:00 0.55 64
USC00511918 2010-02-04 00:00:00 0.0 64
USC00511918 2010-02-05 00:00:00 0.0 63
USC00511918 2010-02-06 00:00:00 0.0 67
USC00511918 2010-02-08 00:00:00 0.0 60
USC00511918 2010-02-09 00:00:00 0.0 61
USC00511918 2010-02-10 00:00:00 0.0 60
USC00511918 2010-02-11 00:00:00 0.0 70
USC00511918 2010-02-12 00:00:00 0.0 68
USC00511918 2010-02-13 00:00:00 0.03 67
USC00511918 2010-02-14 00:00:00 0.0 69
USC00511918 2010-02-15 00:00:00 0.0 72
USC00511918 2010-02-16 00:00:00 0.0 65
USC00511918 2010-02-17 00:00:00 0.0 66
USC00511918 2010-02-18 00:00:00 0.0 63
USC00511918 2010-02-19 00:00:00 0.0 62
USC00511918 2010-02-20 00:00:00 0.0 63
USC00511918 2010-02-21 00:00:00 0.0 68
USC00511918 2010-02-22 00:00:00 0.0 64
USC00511918 2010-02-23 00:00:00 0.0 63
USC00511918 2010-02-24 00:00:00 0.0 63
USC00511918 2010-02-25 00:00:00 0.0 64
USC00511918 2010-02-26 00:00:00 0.0 72
USC00511918 2010-03-01 00:00:00 0.0 68
USC00511918 2010-03-02 00:00:00 0.0 69
USC00511918 2010-03-03 00:00:00 0.0 70
USC00511918 2010-03-04 00:00:00 0.04 67
USC00511918 2010-03-05 00:00:00 0.03 69
USC00511918 2010-03-06 00:00:00 0.0 74
USC00511918 2010-03-07 00:00:00 0.0 68
USC00511918 2010-03-08 00:00:00 0.08 64
USC00511918 2010-03-09 00:00:00 0.06 68
USC00511918 2010-03-10 00:00:00 0.01 71
USC00511918 2010-03-11 00:00:00 0.0 70
USC00511918 2010-03-12 00:00:00 0.0 71
USC00511918 2010-03-14 00:00:00 0.0 76
USC00511918 2010-03-15 00:00:00 0.01 66
USC00511918 2010-03-16 00:00:00 0.06 65
USC00511918 2010-03-17 00:00:00 0.0 63
USC00511918 2010-03-18 00:00:00 0.01 65
USC00511918 2010-03-19 00:00:00 0.0 67
USC00511918 2010-03-20 00:00:00 0.0 73
USC00511918 2010-03-21 00:00:00 0.0 60
USC00511918 2010-03-22 00:00:00 0.0 65
USC00511918 2010-03-23 00:00:00 0.01 65
USC00511918 2010-03-24 00:00:00 0.0 71
USC00511918 2010-03-25 00:00:00 0.0 71
USC00511918 2010-03-26 00:00:00 0.0 66
USC00511918 2010-03-27 00:00:00 0.0 73
USC00511918 2010-03-28 00:00:00 0.0 73
USC00511918 2010-03-29 00:00:00 0.0 73
USC00511918 2010-03-30 00:00:00 0.01 73
USC00511918 2010-03-31 00:00:00 0.0 73
USC00511918 2010-04-01 00:00:00 0.0 73
USC00511918 2010-04-02 00:00:00 0.0 71
USC00511918 2010-04-03 00:00:00 0.0 78
USC00511918 2010-04-04 00:00:00 0.12 71
USC00511918 2010-04-05 00:00:00 0.01 73
USC00511918 2010-04-06 00:00:00 0.0 70
USC00511918 2010-04-07 00:00:00 0.01 71
USC00511918 2010-04-08 00:00:00 0.87 68
USC00511918 2010-04-09 00:00:00 0.01 68
USC00511918 2010-04-10 00:00:00 0.0 74
USC00511918 2010-04-11 00:00:00 0.0 77
USC00511918 2010-04-12 00:00:00 0.01 66
USC00511918 2010-04-13 00:00:00 0.0 68
USC00511918 2010-04-14 00:00:00 0.0 72
USC00511918 2010-04-15 00:00:00 0.0 61
USC00511918 2010-04-16 00:00:00 0.0 65
USC00511918 2010-04-17 00:00:00 0.0 70
USC00511918 2010-04-18 00:00:00 0.0 71
USC00511918 2010-04-19 00:00:00 0.0 70
USC00511918 2010-04-20 00:00:00 0.0 71
USC00511918 2010-04-21 00:00:00 0.0 71
USC00511918 2010-04-22 00:00:00 0.0 75
USC00511918 2010-04-23 00:00:00 0.01 66
USC00511918 2010-04-24 00:00:00 0.0 77
USC00511918 2010-04-25 00:00:00 0.0 77
USC00511918 2010-04-26 00:00:00 0.0 67
USC00511918 2010-04-27 00:00:00 0.0 69

USC00511918 2010-04-28 00:00:00 0.0 72
USC00511918 2010-04-29 00:00:00 0.08 73
USC00511918 2010-04-30 00:00:00 0.04 69
USC00511918 2010-05-01 00:00:00 0.0 75
USC00511918 2010-05-02 00:00:00 0.15 71
USC00511918 2010-05-03 00:00:00 0.98 71
USC00511918 2010-05-04 00:00:00 0.01 65
USC00511918 2010-05-05 00:00:00 0.0 78
USC00511918 2010-05-06 00:00:00 0.01 74
USC00511918 2010-05-07 00:00:00 0.01 71
USC00511918 2010-05-08 00:00:00 0.02 79
USC00511918 2010-05-09 00:00:00 0.0 78
USC00511918 2010-05-10 00:00:00 0.0 70
USC00511918 2010-05-11 00:00:00 0.0 70
USC00511918 2010-05-12 00:00:00 0.0 77
USC00511918 2010-05-13 00:00:00 0.0 73
USC00511918 2010-05-14 00:00:00 0.0 71
USC00511918 2010-05-15 00:00:00 0.0 68
USC00511918 2010-05-16 00:00:00 0.02 71
USC00511918 2010-05-17 00:00:00 0.0 71
USC00511918 2010-05-18 00:00:00 0.0 79
USC00511918 2010-05-19 00:00:00 0.0 71
USC00511918 2010-05-20 00:00:00 0.03 71
USC00511918 2010-05-21 00:00:00 0.01 74
USC00511918 2010-05-22 00:00:00 0.0 80
USC00511918 2010-05-23 00:00:00 0.0 74
USC00511918 2010-05-24 00:00:00 0.0 74
USC00511918 2010-05-25 00:00:00 0.0 73
USC00511918 2010-05-26 00:00:00 0.01 73
USC00511918 2010-05-27 00:00:00 0.0 67
USC00511918 2010-05-28 00:00:00 0.0 67
USC00511918 2010-05-31 00:00:00 0.0 79
USC00511918 2010-06-01 00:00:00 0.0 74
USC00511918 2010-06-02 00:00:00 0.0 76
USC00511918 2010-06-03 00:00:00 0.0 78
USC00511918 2010-06-04 00:00:00 0.0 74
USC00511918 2010-06-05 00:00:00 0.0 79
USC00511918 2010-06-06 00:00:00 0.0 79
USC00511918 2010-06-07 00:00:00 0.05 69
USC00511918 2010-06-08 00:00:00 0.0 77
USC00511918 2010-06-09 00:00:00 0.0 80
USC00511918 2010-06-10 00:00:00 0.0 75
USC00511918 2010-06-11 00:00:00 0.0 75
USC00511918 2010-06-12 00:00:00 0.0 78
USC00511918 2010-06-14 00:00:00 0.0 71
USC00511918 2010-06-15 00:00:00 0.0 76
USC00511918 2010-06-16 00:00:00 0.0 74
USC00511918 2010-06-17 00:00:00 0.0 78
USC00511918 2010-06-18 00:00:00 0.04 72
USC00511918 2010-06-19 00:00:00 0.05 78
USC00511918 2010-06-20 00:00:00 0.0 85
USC00511918 2010-06-21 00:00:00 0.0 77
USC00511918 2010-06-22 00:00:00 0.0 76
USC00511918 2010-06-23 00:00:00 0.0 76
USC00511918 2010-06-24 00:00:00 0.0 75
USC00511918 2010-06-25 00:00:00 0.02 71
USC00511918 2010-06-26 00:00:00 0.0 70
USC00511918 2010-06-27 00:00:00 0.09 80
USC00511918 2010-06-28 00:00:00 0.0 77
USC00511918 2010-06-29 00:00:00 0.02 70
USC00511918 2010-06-30 00:00:00 0.03 73
USC00511918 2010-07-04 00:00:00 0.0 78
USC00511918 2010-07-05 00:00:00 0.01 78
USC00511918 2010-07-06 00:00:00 0.1 71
USC00511918 2010-07-07 00:00:00 0.02 70
USC00511918 2010-07-08 00:00:00 0.03 74
USC00511918 2010-07-09 00:00:00 0.15 72
USC00511918 2010-07-10 00:00:00 0.01 76
USC00511918 2010-07-13 00:00:00 0.0 80
USC00511918 2010-07-14 00:00:00 0.01 77
USC00511918 2010-07-15 00:00:00 0.01 79
USC00511918 2010-07-16 00:00:00 0.0 79
USC00511918 2010-07-17 00:00:00 0.02 74
USC00511918 2010-07-18 00:00:00 0.0 76
USC00511918 2010-07-19 00:00:00 0.01 70
USC00511918 2010-07-20 00:00:00 0.02 74
USC00511918 2010-07-21 00:00:00 0.0 79
USC00511918 2010-07-22 00:00:00 0.0 80
USC00511918 2010-07-23 00:00:00 0.0 72
USC00511918 2010-07-24 00:00:00 0.0 80
USC00511918 2010-07-25 00:00:00 0.0 79
USC00511918 2010-07-26 00:00:00 0.0 71
USC00511918 2010-07-27 00:00:00 0.0 68
USC00511918 2010-07-28 00:00:00 0.0 69
USC00511918 2010-07-29 00:00:00 0.0 77
USC00511918 2010-07-30 00:00:00 0.0 80
USC00511918 2010-07-31 00:00:00 0.0 78
USC00511918 2010-08-01 00:00:00 0.0 74
USC00511918 2010-08-02 00:00:00 0.0 71
USC00511918 2010-08-03 00:00:00 0.0 72
USC00511918 2010-08-04 00:00:00 0.0 72
USC00511918 2010-08-05 00:00:00 0.04 69
USC00511918 2010-08-06 00:00:00 0.01 77
USC00511918 2010-08-07 00:00:00 0.0 73
USC00511918 2010-08-08 00:00:00 0.01 78
USC00511918 2010-08-09 00:00:00 0.0 79
USC00511918 2010-08-10 00:00:00 0.0 83
USC00511918 2010-08-11 00:00:00 0.1 74
USC00511918 2010-08-12 00:00:00 0.0 77
USC00511918 2010-08-13 00:00:00 0.0 80
USC00511918 2010-08-14 00:00:00 0.0 78
USC00511918 2010-08-15 00:00:00 0.0 79
USC00511918 2010-08-16 00:00:00 0.0 71
USC00511918 2010-08-17 00:00:00 0.02 73
USC00511918 2010-08-18 00:00:00 0.0 70
USC00511918 2010-08-19 00:00:00 0.0 70
USC00511918 2010-08-20 00:00:00 0.0 77
USC00511918 2010-08-21 00:00:00 0.0 81
USC00511918 2010-08-22 00:00:00 0.0 82
USC00511918 2010-08-23 00:00:00 0.0 74
USC00511918 2010-08-24 00:00:00 0.0 72
USC00511918 2010-08-25 00:00:00 0.01 70
USC00511918 2010-08-26 00:00:00 0.0 71
USC00511918 2010-08-27 00:00:00 0.0 75
USC00511918 2010-08-28 00:00:00 0.0 81
USC00511918 2010-08-29 00:00:00 0.0 77
USC00511918 2010-08-30 00:00:00 0.0 68
USC00511918 2010-08-31 00:00:00 0.0 67
USC00511918 2010-09-01 00:00:00 0.0 69
USC00511918 2010-09-02 00:00:00 0.0 67
USC00511918 2010-09-03 00:00:00 0.0 77
USC00511918 2010-09-05 00:00:00 0.0 82
USC00511918 2010-09-06 00:00:00 0.0 80
USC00511918 2010-09-07 00:00:00 0.02 70
USC00511918 2010-09-08 00:00:00 0.0 67
USC00511918 2010-09-09 00:00:00 0.0 69
USC00511918 2010-09-10 00:00:00 0.0 72
USC00511918 2010-09-11 00:00:00 0.0 78
USC00511918 2010-09-12 00:00:00 0.0 80
USC00511918 2010-09-13 00:00:00 0.0 72
USC00511918 2010-09-14 00:00:00 0.0 69
USC00511918 2010-09-15 00:00:00 0.0 78
USC00511918 2010-09-16 00:00:00 0.0 75
USC00511918 2010-09-17 00:00:00 0.0 75
USC00511918 2010-09-18 00:00:00 0.0 74
USC00511918 2010-09-19 00:00:00 0.0 87
USC00511918 2010-09-20 00:00:00 0.02 73
USC00511918 2010-09-21 00:00:00 0.0 67
USC00511918 2010-09-22 00:00:00 0.08 72
USC00511918 2010-09-23 00:00:00 0.35 67
USC00511918 2010-09-24 00:00:00 0.0 74
USC00511918 2010-09-25 00:00:00 0.0 77
USC00511918 2010-09-26 00:00:00 0.0 79
USC00511918 2010-09-27 00:00:00 0.0 68
USC00511918 2010-09-28 00:00:00 0.0 67
USC00511918 2010-09-30 00:00:00 0.0 70
USC00511918 2010-10-01 00:00:00 0.19 72
USC00511918 2010-10-02 00:00:00 0.0 80
USC00511918 2010-10-03 00:00:00 0.0 78
USC00511918 2010-10-04 00:00:00 0.01 75
USC00511918 2010-10-05 00:00:00 0.0 76
USC00511918 2010-10-06 00:00:00 0.0 72
USC00511918 2010-10-07 00:00:00 0.0 68
USC00511918 2010-10-08 00:00:00 0.0 78
USC00511918 2010-10-09 00:00:00 0.0 78
USC00511918 2010-10-10 00:00:00 0.0 80
USC00511918 2010-10-11 00:00:00 0.0 79
USC00511918 2010-10-12 00:00:00 0.0 72
USC00511918 2010-10-13 00:00:00 0.0 75
USC00511918 2010-10-14 00:00:00 0.0 67
USC00511918 2010-10-15 00:00:00 0.0 82
USC00511918 2010-10-16 00:00:00 0.0 76
USC00511918 2010-10-17 00:00:00 0.0 76
USC00511918 2010-10-18 00:00:00 0.0 65
USC00511918 2010-10-19 00:00:00 0.0 67
USC00511918 2010-10-20 00:00:00 0.0 68
USC00511918 2010-10-21 00:00:00 0.0 73
USC00511918 2010-10-22 00:00:00 0.0 68
USC00511918 2010-10-23 00:00:00 0.0 73
USC00511918 2010-10-24 00:00:00 0.0 76
USC00511918 2010-10-25 00:00:00 0.0 76
USC00511918 2010-10-26 00:00:00 0.02 76
USC00511918 2010-10-27 00:00:00 0.01 76
USC00511918 2010-10-28 00:00:00 0.01 75
USC00511918 2010-10-29 00:00:00 0.0 73
USC00511918 2010-10-30 00:00:00 0.02 78
USC00511918 2010-10-31 00:00:00 0.01 80
USC00511918 2010-11-01 00:00:00 0.01 70
USC00511918 2010-11-02 00:00:00 0.03 65
USC00511918 2010-11-03 00:00:00 0.0 70
USC00511918 2010-11-04 00:00:00 0.1 73
USC00511918 2010-11-05 00:00:00 0.0 75
USC00511918 2010-11-06 00:00:00 0.0 76
USC00511918 2010-11-07 00:00:00 0.0 80
USC00511918 2010-11-08 00:00:00 0.0 77
USC00511918 2010-11-09 00:00:00 0.0 80
USC00511918 2010-11-10 00:00:00 0.0 68
USC00511918 2010-11-11 00:00:00 0.01 73
USC00511918 2010-11-12 00:00:00 0.0 72
USC00511918 2010-11-13 00:00:00 0.0 74
USC00511918 2010-11-14 00:00:00 0.0 73
USC00511918 2010-11-15 00:00:00 0.01 70
USC00511918 2010-11-16 00:00:00 0.04 63
USC00511918 2010-11-17 00:00:00 0.02 66
USC00511918 2010-11-18 00:00:00 0.0 68
USC00511918 2010-11-19 00:00:00 0.34 67
USC00511918 2010-11-20 00:00:00 0.0 70
USC00511918 2010-11-21 00:00:00 0.0 76
USC00511918 2010-11-22 00:00:00 0.02 68
USC00511918 2010-11-23 00:00:00 0.0 64
USC00511918 2010-11-24 00:00:00 0.0 72
USC00511918 2010-11-25 00:00:00 0.01 75
USC00511918 2010-11-26 00:00:00 0.0 78
USC00511918 2010-11-27 00:00:00 0.0 76
USC00511918 2010-11-28 00:00:00 0.06 73
USC00511918 2010-11-29 00:00:00 0.02 65
USC00511918 2010-11-30 00:00:00 0.0 67
USC00511918 2010-12-01 00:00:00 0.13 70
USC00511918 2010-12-02 00:00:00 0.0 74
USC00511918 2010-12-03 00:00:00 0.01 74
USC00511918 2010-12-04 00:00:00 0.0 75
USC00511918 2010-12-05 00:00:00 0.0 69
USC00511918 2010-12-06 00:00:00 0.0 65
USC00511918 2010-12-07 00:00:00 0.0 66
USC00511918 2010-12-08 00:00:00 0.0 68
USC00511918 2010-12-09 00:00:00 0.04 77
USC00511918 2010-12-10 00:00:00 1.8 65
USC00511918 2010-12-11 00:00:00 0.8 72
USC00511918 2010-12-12 00:00:00 0.01 65
USC00511918 2010-12-13 00:00:00 0.0 66
USC00511918 2010-12-14 00:00:00 0.01 74
USC00511918 2010-12-15 00:00:00 0.0 66
USC00511918 2010-12-16 00:00:00 0.0 63
USC00511918 2010-12-17 00:00:00 0.0 63
USC00511918 2010-12-18 00:00:00 0.0 69
USC00511918 2010-12-19 00:00:00 4.0 69
USC00511918 2010-12-20 00:00:00 3.05 73
USC00511918 2010-12-21 00:00:00 0.17 72
USC00511918 2010-12-22 00:00:00 0.04 68
USC00511918 2010-12-23 00:00:00 0.0 67
USC00511918 2010-12-24 00:00:00 0.05 69
USC00511918 2010-12-25 00:00:00 0.01 74
USC00511918 2010-12-26 00:00:00 3.0 72
USC00511918 2010-12-27 00:00:00 0.01 76
USC00511918 2010-12-28 00:00:00 1.67 70
USC00511918 2010-12-29 00:00:00 0.0 73
USC00511918 2010-12-30 00:00:00 0.02 70
USC00511918 2010-12-31 00:00:00 0.0 76
USC00511918 2011-01-01 00:00:00 0.0 72
USC00511918 2011-01-02 00:00:00 0.0 71
USC00511918 2011-01-03 00:00:00 0.0 70
USC00511918 2011-01-04 00:00:00 0.0 62
USC00511918 2011-01-05 00:00:00 0.0 61
USC00511918 2011-01-07 00:00:00 0.0 67
USC00511918 2011-01-08 00:00:00 0.0 66
USC00511918 2011-01-09 00:00:00 0.0 68
USC00511918 2011-01-10 00:00:00 0.0 72
USC00511918 2011-01-11 00:00:00 0.08 58
USC00511918 2011-01-12 00:00:00 0.44 71
USC00511918 2011-01-13 00:00:00 3.44 66
USC00511918 2011-01-14 00:00:00 0.31 75
USC00511918 2011-01-16 00:00:00 0.02 68
USC00511918 2011-01-17 00:00:00 0.03 66
USC00511918 2011-01-18 00:00:00 0.0 63
USC00511918 2011-01-19 00:00:00 0.01 63
USC00511918 2011-01-20 00:00:00 0.0 62
USC00511918 2011-01-21 00:00:00 0.0 70
USC00511918 2011-01-22 00:00:00 0.0 65
USC00511918 2011-01-23 00:00:00 0.0 64
USC00511918 2011-01-24 00:00:00 0.0 69
USC00511918 2011-01-25 00:00:00 0.0 61
USC00511918 2011-01-26 00:00:00 0.0 61
USC00511918 2011-01-27 00:00:00 0.0 67
USC00511918 2011-01-28 00:00:00 0.0 72
USC00511918 2011-01-29 00:00:00 0.0 69
USC00511918 2011-01-30 00:00:00 0.0 61
USC00511918 2011-01-31 00:00:00 0.2 64
USC00511918 2011-02-01 00:00:00 0.23 56
USC00511918 2011-02-02 00:00:00 0.01 61
USC00511918 2011-02-03 00:00:00 0.0 62
USC00511918 2011-02-04 00:00:00 0.0 61
USC00511918 2011-02-05 00:00:00 0.0 63
USC00511918 2011-02-06 00:00:00 0.29 70
USC00511918 2011-02-07 00:00:00 1.14 67
USC00511918 2011-02-08 00:00:00 0.15 65
USC00511918 2011-02-09 00:00:00 0.0 62
USC00511918 2011-02-10 00:00:00 0.23 68
USC00511918 2011-02-11 00:00:00 0.02 68
USC00511918 2011-02-12 00:00:00 0.35 66
USC00511918 2011-02-13 00:00:00 0.04 73
USC00511918 2011-02-14 00:00:00 0.13 69
USC00511918 2011-02-15 00:00:00 0.02 65
USC00511918 2011-02-16 00:00:00 0.01 73
USC00511918 2011-02-17 00:00:00 0.0 66
USC00511918 2011-02-18 00:00:00 0.0 75
USC00511918 2011-02-19 00:00:00 0.0 71
USC00511918 2011-02-20 00:00:00 0.0 74
USC00511918 2011-02-21 00:00:00 0.0 75
USC00511918 2011-02-22 00:00:00 0.1 65
USC00511918 2011-02-23 00:00:00 0.01 65
USC00511918 2011-02-24 00:00:00 0.05 65
USC00511918 2011-02-25 00:00:00 0.0 63
USC00511918 2011-02-26 00:00:00 0.18 69
USC00511918 2011-02-27 00:00:00 0.0 67
USC00511918 2011-02-28 00:00:00 0.0 65
USC00511918 2011-03-01 00:00:00 0.0 64
USC00511918 2011-03-02 00:00:00 0.0 61
USC00511918 2011-03-03 00:00:00 0.03 72
USC00511918 2011-03-04 00:00:00 0.6 73
USC00511918 2011-03-06 00:00:00 0.0 73
USC00511918 2011-03-07 00:00:00 0.03 76
USC00511918 2011-03-08 00:00:00 0.0 66
USC00511918 2011-03-09 00:00:00 0.01 69
USC00511918 2011-03-10 00:00:00 0.1 69
USC00511918 2011-03-11 00:00:00 0.04 79
USC00511918 2011-03-12 00:00:00 0.0 77
USC00511918 2011-03-13 00:00:00 0.01 72
USC00511918 2011-03-14 00:00:00 0.0 63
USC00511918 2011-03-15 00:00:00 0.0 73
USC00511918 2011-03-16 00:00:00 0.0 75
USC00511918 2011-03-18 00:00:00 0.0 72
USC00511918 2011-03-19 00:00:00 0.0 75
USC00511918 2011-03-20 00:00:00 0.06 73
USC00511918 2011-03-21 00:00:00 0.0 69
USC00511918 2011-03-22 00:00:00 0.01 70
USC00511918 2011-03-23 00:00:00 0.0 72
USC00511918 2011-03-24 00:00:00 0.0 71
USC00511918 2011-03-25 00:00:00 0.0 71
USC00511918 2011-03-26 00:00:00 0.0 75
USC00511918 2011-03-27 00:00:00 0.04 73
USC00511918 2011-03-28 00:00:00 0.0 66
USC00511918 2011-03-29 00:00:00 0.0 75
USC00511918 2011-03-30 00:00:00 0.0 75
USC00511918 2011-03-31 00:00:00 0.0 61
USC00511918 2011-04-01 00:00:00 0.0 75
USC00511918 2011-04-02 00:00:00 0.01 73
USC00511918 2011-04-03 00:00:00 0.0 76
USC00511918 2011-04-04 00:00:00 0.0 64
USC00511918 2011-04-05 00:00:00 0.0 72
USC00511918 2011-04-06 00:00:00 0.0 71
USC00511918 2011-04-07 00:00:00 0.37 67
USC00511918 2011-04-08 00:00:00 0.4 69
USC00511918 2011-04-09 00:00:00 0.04 77
USC00511918 2011-04-10 00:00:00 0.0 76
USC00511918 2011-04-11 00:00:00 0.0 74
USC00511918 2011-04-12 00:00:00 0.0 72
USC00511918 2011-04-13 00:00:00 0.0 64
USC00511918 2011-04-14 00:00:00 0.0 74
USC00511918 2011-04-15 00:00:00 0.0 71
USC00511918 2011-04-16 00:00:00 0.12 79
USC00511918 2011-04-17 00:00:00 0.0 75
USC00511918 2011-04-18 00:00:00 0.0 67
USC00511918 2011-04-19 00:00:00 0.0 66
USC00511918 2011-04-20 00:00:00 0.0 66
USC00511918 2011-04-21 00:00:00 0.0 71
USC00511918 2011-04-22 00:00:00 0.0 84
USC00511918 2011-04-23 00:00:00 0.0 76
USC00511918 2011-04-24 00:00:00 0.0 77
USC00511918 2011-04-25 00:00:00 0.0 69
USC00511918 2011-04-26 00:00:00 0.03 68
USC00511918 2011-04-27 00:00:00 0.0 69
USC00511918 2011-04-28 00:00:00 0.0 72
USC00511918 2011-04-29 00:00:00 0.0 78
USC00511918 2011-04-30 00:00:00 0.2 74
USC00511918 2011-05-01 00:00:00 0.0 76
USC00511918 2011-05-02 00:00:00 0.0 65
USC00511918 2011-05-03 00:00:00 0.76 69
USC00511918 2011-05-04 00:00:00 0.1 70
USC00511918 2011-05-05 00:00:00 0.02 71
USC00511918 2011-05-06 00:00:00 0.03 69
USC00511918 2011-05-07 00:00:00 0.6 72
USC00511918 2011-05-08 00:00:00 0.72 70
USC00511918 2011-05-09 00:00:00 0.53 70
USC00511918 2011-05-10 00:00:00 0.03 74
USC00511918 2011-05-11 00:00:00 0.01 70
USC00511918 2011-05-12 00:00:00 0.04 70
USC00511918 2011-05-13 00:00:00 0.03 71
USC00511918 2011-05-14 00:00:00 0.0 79
USC00511918 2011-05-15 00:00:00 0.0 78
USC00511918 2011-05-16 00:00:00 0.0 71
USC00511918 2011-05-17 00:00:00 0.0 68
USC00511918 2011-05-18 00:00:00 0.0 68
USC00511918 2011-05-19 00:00:00 0.03 66
USC00511918 2011-05-20 00:00:00 0.0 70
USC00511918 2011-05-21 00:00:00 0.0 77

USC00511918 2011-05-22 00:00:00 0.0 76
USC00511918 2011-05-23 00:00:00 0.01 75
USC00511918 2011-05-24 00:00:00 0.0 73
USC00511918 2011-05-25 00:00:00 0.0 75
USC00511918 2011-05-26 00:00:00 0.0 76
USC00511918 2011-05-27 00:00:00 0.0 77
USC00511918 2011-05-28 00:00:00 0.0 77
USC00511918 2011-05-29 00:00:00 0.0 77
USC00511918 2011-05-30 00:00:00 0.0 79
USC00511918 2011-05-31 00:00:00 0.0 73
USC00511918 2011-06-01 00:00:00 0.02 73
USC00511918 2011-06-02 00:00:00 0.0 76
USC00511918 2011-06-03 00:00:00 0.03 70
USC00511918 2011-06-04 00:00:00 0.58 71
USC00511918 2011-06-05 00:00:00 0.02 80
USC00511918 2011-06-06 00:00:00 0.0 70
USC00511918 2011-06-07 00:00:00 0.0 68
USC00511918 2011-06-08 00:00:00 0.1 74
USC00511918 2011-06-09 00:00:00 0.0 75
USC00511918 2011-06-10 00:00:00 0.0 75
USC00511918 2011-06-11 00:00:00 0.0 78
USC00511918 2011-06-12 00:00:00 0.02 76
USC00511918 2011-06-13 00:00:00 0.0 69
USC00511918 2011-06-14 00:00:00 0.0 73
USC00511918 2011-06-15 00:00:00 0.0 76
USC00511918 2011-06-16 00:00:00 0.01 72
USC00511918 2011-06-17 00:00:00 0.0 72
USC00511918 2011-06-18 00:00:00 0.0 80
USC00511918 2011-06-19 00:00:00 0.0 76
USC00511918 2011-06-20 00:00:00 0.01 71
USC00511918 2011-06-21 00:00:00 0.03 68
USC00511918 2011-06-22 00:00:00 0.1 71
USC00511918 2011-06-23 00:00:00 0.01 72
USC00511918 2011-06-24 00:00:00 0.0 75
USC00511918 2011-06-25 00:00:00 0.0 80
USC00511918 2011-06-26 00:00:00 0.0 75
USC00511918 2011-06-27 00:00:00 0.0 74
USC00511918 2011-06-28 00:00:00 0.0 74
USC00511918 2011-06-29 00:00:00 0.0 69
USC00511918 2011-06-30 00:00:00 0.0 70
USC00511918 2011-07-01 00:00:00 0.0 68
USC00511918 2011-07-02 00:00:00 0.02 79
USC00511918 2011-07-03 00:00:00 0.0 77
USC00511918 2011-07-04 00:00:00 0.0 77
USC00511918 2011-07-05 00:00:00 0.0 70
USC00511918 2011-07-06 00:00:00 0.0 74
USC00511918 2011-07-07 00:00:00 0.03 71
USC00511918 2011-07-08 00:00:00 0.0 75
USC00511918 2011-07-09 00:00:00 0.0 76
USC00511918 2011-07-10 00:00:00 0.02 79
USC00511918 2011-07-11 00:00:00 0.0 71
USC00511918 2011-07-12 00:00:00 0.0 67
USC00511918 2011-07-13 00:00:00 0.0 72
USC00511918 2011-07-14 00:00:00 0.0 67
USC00511918 2011-07-15 00:00:00 0.0 76
USC00511918 2011-07-16 00:00:00 0.0 78
USC00511918 2011-07-17 00:00:00 0.02 79
USC00511918 2011-07-18 00:00:00 0.0 75
USC00511918 2011-07-19 00:00:00 0.0 73
USC00511918 2011-07-20 00:00:00 0.0 72
USC00511918 2011-07-21 00:00:00 0.0 75
USC00511918 2011-07-22 00:00:00 0.01 74
USC00511918 2011-07-23 00:00:00 0.0 77
USC00511918 2011-07-24 00:00:00 0.0 78
USC00511918 2011-07-25 00:00:00 0.0 79
USC00511918 2011-07-26 00:00:00 0.0 80
USC00511918 2011-07-27 00:00:00 0.31 75
USC00511918 2011-07-28 00:00:00 0.01 76
USC00511918 2011-07-29 00:00:00 0.07 70
USC00511918 2011-07-30 00:00:00 0.14 77
USC00511918 2011-07-31 00:00:00 0.0 79
USC00511918 2011-08-01 00:00:00 0.0 67
USC00511918 2011-08-02 00:00:00 0.01 70
USC00511918 2011-08-03 00:00:00 0.0 75
USC00511918 2011-08-04 00:00:00 0.0 75
USC00511918 2011-08-05 00:00:00 0.0 79
USC00511918 2011-08-06 00:00:00 0.0 72
USC00511918 2011-08-07 00:00:00 0.0 79
USC00511918 2011-08-08 00:00:00 0.0 70
USC00511918 2011-08-09 00:00:00 0.0 71
USC00511918 2011-08-10 00:00:00 0.0 71
USC00511918 2011-08-11 00:00:00 0.0 74
USC00511918 2011-08-12 00:00:00 0.0 67
USC00511918 2011-08-13 00:00:00 0.0 78
USC00511918 2011-08-14 00:00:00 0.0 78
USC00511918 2011-08-15 00:00:00 0.0 75
USC00511918 2011-08-16 00:00:00 0.01 73
USC00511918 2011-08-17 00:00:00 0.03 71
USC00511918 2011-08-18 00:00:00 0.0 72
USC00511918 2011-08-19 00:00:00 0.01 79
USC00511918 2011-08-21 00:00:00 0.05 77
USC00511918 2011-08-22 00:00:00 0.0 74
USC00511918 2011-08-23 00:00:00 0.0 70
USC00511918 2011-08-24 00:00:00 0.0 74
USC00511918 2011-08-25 00:00:00 0.0 79
USC00511918 2011-08-26 00:00:00 0.0 74
USC00511918 2011-08-27 00:00:00 0.0 77
USC00511918 2011-08-28 00:00:00 0.08 80
USC00511918 2011-08-29 00:00:00 0.14 70
USC00511918 2011-08-30 00:00:00 0.0 71
USC00511918 2011-08-31 00:00:00 0.0 69
USC00511918 2011-09-01 00:00:00 0.01 79
USC00511918 2011-09-02 00:00:00 0.0 75
USC00511918 2011-09-03 00:00:00 0.0 80
USC00511918 2011-09-04 00:00:00 0.0 79
USC00511918 2011-09-05 00:00:00 0.0 75
USC00511918 2011-09-06 00:00:00 0.08 66
USC00511918 2011-09-07 00:00:00 0.02 64
USC00511918 2011-09-08 00:00:00 0.0 66
USC00511918 2011-09-09 00:00:00 0.0 68
USC00511918 2011-09-10 00:00:00 0.0 79
USC00511918 2011-09-11 00:00:00 0.0 79
USC00511918 2011-09-12 00:00:00 0.0 71
USC00511918 2011-09-13 00:00:00 0.0 68
USC00511918 2011-09-14 00:00:00 0.0 69
USC00511918 2011-09-15 00:00:00 0.0 73
USC00511918 2011-09-16 00:00:00 0.0 75
USC00511918 2011-09-17 00:00:00 0.0 79
USC00511918 2011-09-18 00:00:00 0.01 78
USC00511918 2011-09-19 00:00:00 0.0 72
USC00511918 2011-09-20 00:00:00 0.0 74
USC00511918 2011-09-21 00:00:00 0.0 72
USC00511918 2011-09-22 00:00:00 0.0 77
USC00511918 2011-09-23 00:00:00 0.0 73
USC00511918 2011-09-24 00:00:00 0.0 78
USC00511918 2011-09-25 00:00:00 0.0 72
USC00511918 2011-09-26 00:00:00 0.0 66
USC00511918 2011-09-27 00:00:00 0.0 69
USC00511918 2011-09-28 00:00:00 0.01 68
USC00511918 2011-09-29 00:00:00 0.0 74
USC00511918 2011-09-30 00:00:00 0.0 69
USC00511918 2011-10-01 00:00:00 0.0 80
USC00511918 2011-10-02 00:00:00 0.0 82
USC00511918 2011-10-03 00:00:00 0.0 74
USC00511918 2011-10-04 00:00:00 0.0 75
USC00511918 2011-10-05 00:00:00 0.01 76
USC00511918 2011-10-06 00:00:00 0.0 77
USC00511918 2011-10-07 00:00:00 0.0 81
USC00511918 2011-10-08 00:00:00 0.0 86
USC00511918 2011-10-09 00:00:00 0.0 79
USC00511918 2011-10-10 00:00:00 0.0 76
USC00511918 2011-10-11 00:00:00 0.01 69
USC00511918 2011-10-12 00:00:00 0.0 65
USC00511918 2011-10-13 00:00:00 0.0 65
USC00511918 2011-10-14 00:00:00 0.0 68
USC00511918 2011-10-15 00:00:00 0.01 73
USC00511918 2011-10-16 00:00:00 0.0 81
USC00511918 2011-10-17 00:00:00 0.0 65
USC00511918 2011-10-18 00:00:00 0.0 65
USC00511918 2011-10-19 00:00:00 0.01 65
USC00511918 2011-10-20 00:00:00 0.0 67
USC00511918 2011-10-21 00:00:00 0.0 74
USC00511918 2011-10-22 00:00:00 0.01 75
USC00511918 2011-10-23 00:00:00 0.0 80
USC00511918 2011-10-24 00:00:00 0.65 75
USC00511918 2011-10-25 00:00:00 0.02 68
USC00511918 2011-10-26 00:00:00 0.01 69
USC00511918 2011-10-27 00:00:00 0.0 64
USC00511918 2011-10-28 00:00:00 0.0 68
USC00511918 2011-10-29 00:00:00 0.0 73
USC00511918 2011-10-30 00:00:00 0.0 76
USC00511918 2011-10-31 00:00:00 0.0 67
USC00511918 2011-11-01 00:00:00 0.08 69
USC00511918 2011-11-02 00:00:00 0.26 74
USC00511918 2011-11-03 00:00:00 0.02 74
USC00511918 2011-11-04 00:00:00 0.0 82
USC00511918 2011-11-05 00:00:00 0.0 76
USC00511918 2011-11-07 00:00:00 0.0 78
USC00511918 2011-11-08 00:00:00 0.0 71
USC00511918 2011-11-09 00:00:00 0.01 73
USC00511918 2011-11-10 00:00:00 0.0 73
USC00511918 2011-11-11 00:00:00 0.09 70
USC00511918 2011-11-12 00:00:00 0.0 73
USC00511918 2011-11-13 00:00:00 0.0 71
USC00511918 2011-11-14 00:00:00 0.0 73
USC00511918 2011-11-15 00:00:00 0.0 65
USC00511918 2011-11-16 00:00:00 0.0 67
USC00511918 2011-11-17 00:00:00 0.0 74
USC00511918 2011-11-18 00:00:00 0.0 78
USC00511918 2011-11-19 00:00:00 0.0 75
USC00511918 2011-11-20 00:00:00 0.0 75
USC00511918 2011-11-21 00:00:00 0.0 75
USC00511918 2011-11-22 00:00:00 0.0 72
USC00511918 2011-11-23 00:00:00 0.01 72
USC00511918 2011-11-24 00:00:00 0.0 68
USC00511918 2011-11-25 00:00:00 0.0 67
USC00511918 2011-11-26 00:00:00 0.0 77
USC00511918 2011-11-27 00:00:00 0.05 74
USC00511918 2011-11-28 00:00:00 0.0 71
USC00511918 2011-11-29 00:00:00 0.0 69
USC00511918 2011-11-30 00:00:00 0.02 64
USC00511918 2011-12-01 00:00:00 0.0 66
USC00511918 2011-12-02 00:00:00 0.01 69
USC00511918 2011-12-03 00:00:00 0.0 69
USC00511918 2011-12-04 00:00:00 0.0 70
USC00511918 2011-12-05 00:00:00 0.0 71
USC00511918 2011-12-06 00:00:00 0.0 73
USC00511918 2011-12-07 00:00:00 0.0 65
USC00511918 2011-12-08 00:00:00 0.0 71
USC00511918 2011-12-09 00:00:00 0.05 65
USC00511918 2011-12-10 00:00:00 0.03 75
USC00511918 2011-12-11 00:00:00 0.29 72
USC00511918 2011-12-12 00:00:00 0.03 74
USC00511918 2011-12-13 00:00:00 0.1 67
USC00511918 2011-12-14 00:00:00 0.06 65
USC00511918 2011-12-15 00:00:00 0.01 68
USC00511918 2011-12-16 00:00:00 0.01 66
USC00511918 2011-12-17 00:00:00 0.0 73
USC00511918 2011-12-18 00:00:00 0.0 74
USC00511918 2011-12-19 00:00:00 0.0 76
USC00511918 2011-12-20 00:00:00 0.0 72
USC00511918 2011-12-21 00:00:00 0.03 69
USC00511918 2011-12-22 00:00:00 0.02 71
USC00511918 2011-12-23 00:00:00 0.01 70
USC00511918 2011-12-24 00:00:00 0.01 70
USC00511918 2011-12-25 00:00:00 0.0 73
USC00511918 2011-12-26 00:00:00 0.0 71
USC00511918 2011-12-27 00:00:00 0.0 76
USC00511918 2011-12-28 00:00:00 0.0 72
USC00511918 2011-12-29 00:00:00 0.0 77
USC00511918 2011-12-30 00:00:00 0.0 70
USC00511918 2011-12-31 00:00:00 0.01 65
USC00511918 2012-01-01 00:00:00 0.0 67
USC00511918 2012-01-03 00:00:00 0.0 64
USC00511918 2012-01-04 00:00:00 0.0 75
USC00511918 2012-01-05 00:00:00 0.0 64
USC00511918 2012-01-06 00:00:00 0.0 69
USC00511918 2012-01-07 00:00:00 0.0 62
USC00511918 2012-01-08 00:00:00 0.0 61
USC00511918 2012-01-09 00:00:00 0.0 62
USC00511918 2012-01-10 00:00:00 0.0 63
USC00511918 2012-01-11 00:00:00 0.0 64
USC00511918 2012-01-12 00:00:00 0.0 65
USC00511918 2012-01-13 00:00:00 0.0 63
USC00511918 2012-01-14 00:00:00 0.0 63
USC00511918 2012-01-15 00:00:00 0.0 74
USC00511918 2012-01-16 00:00:00 0.02 75
USC00511918 2012-01-17 00:00:00 0.0 75
USC00511918 2012-01-18 00:00:00 0.0 74
USC00511918 2012-01-19 00:00:00 0.0 66
USC00511918 2012-01-20 00:00:00 0.0 62
USC00511918 2012-01-21 00:00:00 0.0 71
USC00511918 2012-01-22 00:00:00 0.0 73
USC00511918 2012-01-23 00:00:00 0.01 62
USC00511918 2012-01-24 00:00:00 0.0 69
USC00511918 2012-01-25 00:00:00 0.0 62
USC00511918 2012-01-26 00:00:00 0.0 74
USC00511918 2012-01-27 00:00:00 0.33 65
USC00511918 2012-01-28 00:00:00 0.0 62
USC00511918 2012-01-29 00:00:00 0.01 73
USC00511918 2012-01-30 00:00:00 0.01 69
USC00511918 2012-01-31 00:00:00 0.0 71
USC00511918 2012-02-01 00:00:00 0.0 63
USC00511918 2012-02-02 00:00:00 0.0 69
USC00511918 2012-02-03 00:00:00 0.0 60
USC00511918 2012-02-04 00:00:00 0.0 62
USC00511918 2012-02-05 00:00:00 0.0 68
USC00511918 2012-02-06 00:00:00 0.15 66
USC00511918 2012-02-07 00:00:00 0.3 72
USC00511918 2012-02-08 00:00:00 0.39 56
USC00511918 2012-02-09 00:00:00 0.0 59
USC00511918 2012-02-10 00:00:00 0.0 56
USC00511918 2012-02-11 00:00:00 0.0 78
USC00511918 2012-02-12 00:00:00 0.0 66
USC00511918 2012-02-13 00:00:00 0.0 63
USC00511918 2012-02-14 00:00:00 0.0 62
USC00511918 2012-02-15 00:00:00 0.0 64
USC00511918 2012-02-16 00:00:00 0.0 70
USC00511918 2012-02-17 00:00:00 0.0 70
USC00511918 2012-02-18 00:00:00 0.0 73
USC00511918 2012-02-19 00:00:00 0.01 70
USC00511918 2012-02-20 00:00:00 0.0 73
USC00511918 2012-02-21 00:00:00 0.0 70
USC00511918 2012-02-22 00:00:00 0.0 71
USC00511918 2012-02-23 00:00:00 0.05 70
USC00511918 2012-02-24 00:00:00 0.0 67
USC00511918 2012-02-25 00:00:00 0.0 70
USC00511918 2012-02-26 00:00:00 0.01 70
USC00511918 2012-02-27 00:00:00 0.38 64
USC00511918 2012-02-28 00:00:00 0.0 66
USC00511918 2012-02-29 00:00:00 0.01 74
USC00511918 2012-03-01 00:00:00 0.0 74
USC00511918 2012-03-02 00:00:00 0.0 73
USC00511918 2012-03-03 00:00:00 0.0 72
USC00511918 2012-03-04 00:00:00 0.05 66
USC00511918 2012-03-05 00:00:00 0.7 64
USC00511918 2012-03-06 00:00:00 2.83 70
USC00511918 2012-03-07 00:00:00 0.91 65
USC00511918 2012-03-08 00:00:00 0.0 66
USC00511918 2012-03-09 00:00:00 0.0 66
USC00511918 2012-03-10 00:00:00 0.19 72
USC00511918 2012-03-11 00:00:00 0.0 74
USC00511918 2012-03-12 00:00:00 0.0 68
USC00511918 2012-03-13 00:00:00 0.0 65
USC00511918 2012-03-14 00:00:00 0.0 68
USC00511918 2012-03-15 00:00:00 0.0 67
USC00511918 2012-03-16 00:00:00 0.02 70
USC00511918 2012-03-17 00:00:00 0.0 74
USC00511918 2012-03-18 00:00:00 0.02 69
USC00511918 2012-03-19 00:00:00 0.02 65
USC00511918 2012-03-20 00:00:00 0.0 63
USC00511918 2012-03-21 00:00:00 0.0 65
USC00511918 2012-03-22 00:00:00 0.0 70
USC00511918 2012-03-23 00:00:00 0.0 69
USC00511918 2012-03-24 00:00:00 0.0 73
USC00511918 2012-03-25 00:00:00 0.0 72
USC00511918 2012-03-26 00:00:00 0.03 74
USC00511918 2012-03-27 00:00:00 0.0 63
USC00511918 2012-03-28 00:00:00 0.0 59
USC00511918 2012-03-29 00:00:00 0.0 58
USC00511918 2012-03-30 00:00:00 0.0 71
USC00511918 2012-03-31 00:00:00 0.0 74
USC00511918 2012-04-01 00:00:00 0.0 72
USC00511918 2012-04-02 00:00:00 0.0 66
USC00511918 2012-04-03 00:00:00 0.0 61
USC00511918 2012-04-04 00:00:00 0.0 66
USC00511918 2012-04-05 00:00:00 0.0 71
USC00511918 2012-04-06 00:00:00 0.0 71
USC00511918 2012-04-07 00:00:00 0.04 74
USC00511918 2012-04-08 00:00:00 0.0 77
USC00511918 2012-04-09 00:00:00 0.03 68
USC00511918 2012-04-10 00:00:00 0.19 65
USC00511918 2012-04-11 00:00:00 0.06 74
USC00511918 2012-04-12 00:00:00 0.0 75
USC00511918 2012-04-13 00:00:00 0.0 64
USC00511918 2012-04-14 00:00:00 0.0 75
USC00511918 2012-04-15 00:00:00 0.0 74
USC00511918 2012-04-16 00:00:00 0.0 71
USC00511918 2012-04-17 00:00:00 0.0 72
USC00511918 2012-04-18 00:00:00 0.0 72
USC00511918 2012-04-19 00:00:00 0.0 72
USC00511918 2012-04-20 00:00:00 0.0 64
USC00511918 2012-04-21 00:00:00 0.0 75
USC00511918 2012-04-22 00:00:00 0.08 65
USC00511918 2012-04-23 00:00:00 0.02 69
USC00511918 2012-04-24 00:00:00 0.0 70
USC00511918 2012-04-25 00:00:00 0.0 69
USC00511918 2012-04-26 00:00:00 0.0 66
USC00511918 2012-04-27 00:00:00 0.0 65
USC00511918 2012-04-28 00:00:00 0.0 78
USC00511918 2012-04-29 00:00:00 0.0 74
USC00511918 2012-04-30 00:00:00 0.0 77
USC00511918 2012-05-01 00:00:00 0.0 70
USC00511918 2012-05-02 00:00:00 0.01 69
USC00511918 2012-05-03 00:00:00 0.03 68
USC00511918 2012-05-04 00:00:00 0.0 70
USC00511918 2012-05-05 00:00:00 0.02 76
USC00511918 2012-05-06 00:00:00 0.0 74
USC00511918 2012-05-07 00:00:00 0.0 68
USC00511918 2012-05-08 00:00:00 0.0 71
USC00511918 2012-05-09 00:00:00 0.0 68
USC00511918 2012-05-10 00:00:00 0.0 64
USC00511918 2012-05-11 00:00:00 0.0 65
USC00511918 2012-05-12 00:00:00 0.0 74
USC00511918 2012-05-13 00:00:00 0.0 75
USC00511918 2012-05-14 00:00:00 0.0 63
USC00511918 2012-05-15 00:00:00 0.0 64
USC00511918 2012-05-16 00:00:00 0.01 71
USC00511918 2012-05-17 00:00:00 0.0 72
USC00511918 2012-05-18 00:00:00 0.0 71
USC00511918 2012-05-19 00:00:00 0.0 76
USC00511918 2012-05-20 00:00:00 0.0 79
USC00511918 2012-05-21 00:00:00 0.0 68
USC00511918 2012-05-22 00:00:00 0.0 71
USC00511918 2012-05-23 00:00:00 0.0 73
USC00511918 2012-05-24 00:00:00 0.01 75
USC00511918 2012-05-25 00:00:00 0.0 74
USC00511918 2012-05-26 00:00:00 0.0 76
USC00511918 2012-05-27 00:00:00 0.0 78
USC00511918 2012-05-28 00:00:00 0.0 76
USC00511918 2012-05-29 00:00:00 0.0 77
USC00511918 2012-05-30 00:00:00 0.0 74
USC00511918 2012-05-31 00:00:00 0.0 71
USC00511918 2012-06-01 00:00:00 0.01 73
USC00511918 2012-06-02 00:00:00 0.02 76

USC00511918 2012-06-03 00:00:00 0.0 76
USC00511918 2012-06-04 00:00:00 0.0 74
USC00511918 2012-06-05 00:00:00 0.0 71
USC00511918 2012-06-06 00:00:00 0.01 72
USC00511918 2012-06-07 00:00:00 0.0 73
USC00511918 2012-06-08 00:00:00 0.0 77
USC00511918 2012-06-09 00:00:00 0.0 77
USC00511918 2012-06-10 00:00:00 0.0 77
USC00511918 2012-06-11 00:00:00 0.0 79
USC00511918 2012-06-12 00:00:00 0.0 77
USC00511918 2012-06-13 00:00:00 0.03 77
USC00511918 2012-06-14 00:00:00 0.0 78
USC00511918 2012-06-17 00:00:00 0.0 81
USC00511918 2012-06-18 00:00:00 0.0 76
USC00511918 2012-06-19 00:00:00 0.0 74
USC00511918 2012-06-20 00:00:00 0.02 71
USC00511918 2012-06-21 00:00:00 0.0 78
USC00511918 2012-06-22 00:00:00 0.0 71
USC00511918 2012-06-23 00:00:00 0.1 76
USC00511918 2012-06-24 00:00:00 0.0 81
USC00511918 2012-06-25 00:00:00 0.01 73
USC00511918 2012-06-26 00:00:00 0.0 72
USC00511918 2012-06-27 00:00:00 0.01 72
USC00511918 2012-06-28 00:00:00 0.0 74
USC00511918 2012-06-29 00:00:00 0.0 72
USC00511918 2012-06-30 00:00:00 0.0 79
USC00511918 2012-07-01 00:00:00 0.0 77
USC00511918 2012-07-02 00:00:00 0.0 73
USC00511918 2012-07-03 00:00:00 0.0 73
USC00511918 2012-07-04 00:00:00 0.2 79
USC00511918 2012-07-05 00:00:00 0.01 74
USC00511918 2012-07-06 00:00:00 0.0 74
USC00511918 2012-07-08 00:00:00 0.0 79
USC00511918 2012-07-09 00:00:00 0.0 73
USC00511918 2012-07-10 00:00:00 0.0 72
USC00511918 2012-07-11 00:00:00 0.0 77
USC00511918 2012-07-12 00:00:00 0.0 71
USC00511918 2012-07-13 00:00:00 0.0 75
USC00511918 2012-07-14 00:00:00 0.0 81
USC00511918 2012-07-15 00:00:00 0.0 81
USC00511918 2012-07-16 00:00:00 0.03 73
USC00511918 2012-07-17 00:00:00 0.0 74
USC00511918 2012-07-18 00:00:00 0.0 81
USC00511918 2012-07-19 00:00:00 0.0 79
USC00511918 2012-07-20 00:00:00 0.0 77
USC00511918 2012-07-21 00:00:00 0.15 76
USC00511918 2012-07-22 00:00:00 0.04 69
USC00511918 2012-07-23 00:00:00 0.0 78
USC00511918 2012-07-24 00:00:00 0.0 81
USC00511918 2012-07-25 00:00:00 0.0 84
USC00511918 2012-07-26 00:00:00 0.0 86
USC00511918 2012-07-27 00:00:00 0.0 80
USC00511918 2012-07-28 00:00:00 0.0 76
USC00511918 2012-07-29 00:00:00 0.03 74
USC00511918 2012-07-30 00:00:00 0.0 80
USC00511918 2012-07-31 00:00:00 0.0 76
USC00511918 2012-08-01 00:00:00 0.0 76
USC00511918 2012-08-02 00:00:00 0.0 68
USC00511918 2012-08-03 00:00:00 0.0 72
USC00511918 2012-08-04 00:00:00 0.0 80
USC00511918 2012-08-05 00:00:00 0.0 80
USC00511918 2012-08-06 00:00:00 0.01 67
USC00511918 2012-08-07 00:00:00 0.0 74
USC00511918 2012-08-08 00:00:00 0.0 73
USC00511918 2012-08-09 00:00:00 0.0 69
USC00511918 2012-08-10 00:00:00 0.0 65
USC00511918 2012-08-11 00:00:00 0.0 78
USC00511918 2012-08-12 00:00:00 0.0 79
USC00511918 2012-08-13 00:00:00 0.0 75
USC00511918 2012-08-14 00:00:00 0.06 72
USC00511918 2012-08-15 00:00:00 0.0 75
USC00511918 2012-08-16 00:00:00 0.0 75
USC00511918 2012-08-17 00:00:00 0.0 70
USC00511918 2012-08-18 00:00:00 0.0 80
USC00511918 2012-08-19 00:00:00 0.0 81
USC00511918 2012-08-20 00:00:00 0.0 72
USC00511918 2012-08-21 00:00:00 0.0 67
USC00511918 2012-08-22 00:00:00 0.0 69
USC00511918 2012-08-23 00:00:00 0.0 67
USC00511918 2012-08-24 00:00:00 0.0 71
USC00511918 2012-08-25 00:00:00 0.0 78
USC00511918 2012-08-26 00:00:00 0.0 81
USC00511918 2012-08-27 00:00:00 0.0 72
USC00511918 2012-08-28 00:00:00 0.04 73
USC00511918 2012-08-29 00:00:00 0.0 78
USC00511918 2012-08-30 00:00:00 0.0 73
USC00511918 2012-08-31 00:00:00 0.0 69
USC00511918 2012-09-01 00:00:00 0.0 80
USC00511918 2012-09-02 00:00:00 0.0 76
USC00511918 2012-09-03 00:00:00 0.0 77
USC00511918 2012-09-04 00:00:00 0.0 74
USC00511918 2012-09-05 00:00:00 0.01 77
USC00511918 2012-09-06 00:00:00 0.0 81
USC00511918 2012-09-07 00:00:00 0.03 71
USC00511918 2012-09-08 00:00:00 0.1 79
USC00511918 2012-09-09 00:00:00 0.0 73
USC00511918 2012-09-10 00:00:00 0.03 74
USC00511918 2012-09-11 00:00:00 0.0 73
USC00511918 2012-09-12 00:00:00 0.0 68
USC00511918 2012-09-13 00:00:00 0.0 72
USC00511918 2012-09-14 00:00:00 0.0 72
USC00511918 2012-09-15 00:00:00 0.0 74
USC00511918 2012-09-16 00:00:00 0.0 81
USC00511918 2012-09-17 00:00:00 0.0 68
USC00511918 2012-09-18 00:00:00 0.0 67
USC00511918 2012-09-19 00:00:00 0.03 68
USC00511918 2012-09-20 00:00:00 0.16 71
USC00511918 2012-09-21 00:00:00 0.08 68
USC00511918 2012-09-22 00:00:00 0.0 81
USC00511918 2012-09-23 00:00:00 0.02 75
USC00511918 2012-09-24 00:00:00 0.0 75
USC00511918 2012-09-25 00:00:00 0.0 75
USC00511918 2012-09-26 00:00:00 0.0 68
USC00511918 2012-09-27 00:00:00 0.0 72
USC00511918 2012-09-28 00:00:00 0.0 74
USC00511918 2012-09-29 00:00:00 0.0 73
USC00511918 2012-09-30 00:00:00 0.0 80
USC00511918 2012-10-01 00:00:00 0.0 69
USC00511918 2012-10-02 00:00:00 0.0 70
USC00511918 2012-10-03 00:00:00 0.0 66
USC00511918 2012-10-04 00:00:00 0.0 67
USC00511918 2012-10-05 00:00:00 0.0 79
USC00511918 2012-10-06 00:00:00 0.0 77
USC00511918 2012-10-07 00:00:00 0.01 76
USC00511918 2012-10-08 00:00:00 0.0 79
USC00511918 2012-10-09 00:00:00 0.0 69
USC00511918 2012-10-10 00:00:00 0.0 77
USC00511918 2012-10-11 00:00:00 0.0 74
USC00511918 2012-10-12 00:00:00 0.0 80
USC00511918 2012-10-13 00:00:00 0.0 79
USC00511918 2012-10-14 00:00:00 0.02 79
USC00511918 2012-10-15 00:00:00 0.02 74
USC00511918 2012-10-16 00:00:00 0.0 69
USC00511918 2012-10-17 00:00:00 0.0 67
USC00511918 2012-10-18 00:00:00 0.0 70
USC00511918 2012-10-19 00:00:00 0.0 73
USC00511918 2012-10-20 00:00:00 0.0 78
USC00511918 2012-10-21 00:00:00 0.0 82
USC00511918 2012-10-22 00:00:00 0.0 71
USC00511918 2012-10-23 00:00:00 0.0 68
USC00511918 2012-10-24 00:00:00 0.0 70
USC00511918 2012-10-25 00:00:00 0.0 72
USC00511918 2012-10-26 00:00:00 0.0 80
USC00511918 2012-10-27 00:00:00 0.01 78
USC00511918 2012-10-28 00:00:00 0.0 79
USC00511918 2012-10-29 00:00:00 0.02 73
USC00511918 2012-10-30 00:00:00 0.01 77
USC00511918 2012-10-31 00:00:00 0.01 69
USC00511918 2012-11-01 00:00:00 0.0 81
USC00511918 2012-11-02 00:00:00 0.0 70
USC00511918 2012-11-03 00:00:00 0.0 76
USC00511918 2012-11-04 00:00:00 0.0 75
USC00511918 2012-11-05 00:00:00 0.0 66
USC00511918 2012-11-06 00:00:00 0.0 72
USC00511918 2012-11-07 00:00:00 0.0 69
USC00511918 2012-11-08 00:00:00 0.0 67
USC00511918 2012-11-09 00:00:00 0.0 77
USC00511918 2012-11-10 00:00:00 0.0 75
USC00511918 2012-11-11 00:00:00 0.0 76
USC00511918 2012-11-12 00:00:00 0.0 76
USC00511918 2012-11-13 00:00:00 0.02 68
USC00511918 2012-11-14 00:00:00 0.0 72
USC00511918 2012-11-15 00:00:00 0.05 70
USC00511918 2012-11-16 00:00:00 0.01 74
USC00511918 2012-11-17 00:00:00 0.0 71
USC00511918 2012-11-18 00:00:00 0.15 70
USC00511918 2012-11-19 00:00:00 0.0 69
USC00511918 2012-11-20 00:00:00 0.0 68
USC00511918 2012-11-21 00:00:00 0.0 66
USC00511918 2012-11-22 00:00:00 0.0 72
USC00511918 2012-11-23 00:00:00 0.07 77
USC00511918 2012-11-24 00:00:00 0.25 69
USC00511918 2012-11-26 00:00:00 0.03 67
USC00511918 2012-11-27 00:00:00 0.03 69
USC00511918 2012-11-28 00:00:00 0.0 62
USC00511918 2012-11-29 00:00:00 0.0 66
USC00511918 2012-11-30 00:00:00 0.0 63
USC00511918 2012-12-02 00:00:00 0.0 72
USC00511918 2012-12-03 00:00:00 0.0 75
USC00511918 2012-12-04 00:00:00 0.0 68
USC00511918 2012-12-05 00:00:00 0.08 72
USC00511918 2012-12-06 00:00:00 0.01 64
USC00511918 2012-12-07 00:00:00 0.0 75
USC00511918 2012-12-08 00:00:00 0.0 69
USC00511918 2012-12-09 00:00:00 0.0 80
USC00511918 2012-12-10 00:00:00 0.0 73
USC00511918 2012-12-11 00:00:00 0.0 73
USC00511918 2012-12-12 00:00:00 0.0 73
USC00511918 2012-12-13 00:00:00 0.0 72
USC00511918 2012-12-14 00:00:00 0.15 73
USC00511918 2012-12-15 00:00:00 0.0 75
USC00511918 2012-12-16 00:00:00 0.0 76
USC00511918 2012-12-17 00:00:00 0.0 74
USC00511918 2012-12-18 00:00:00 0.02 72
USC00511918 2012-12-19 00:00:00 0.0 72
USC00511918 2012-12-20 00:00:00 0.0 70
USC00511918 2012-12-21 00:00:00 0.0 70
USC00511918 2012-12-22 00:00:00 0.01 71
USC00511918 2012-12-23 00:00:00 0.0 61
USC00511918 2012-12-24 00:00:00 0.0 65
USC00511918 2012-12-25 00:00:00 0.0 74
USC00511918 2012-12-26 00:00:00 0.0 71
USC00511918 2012-12-27 00:00:00 0.0 63
USC00511918 2012-12-28 00:00:00 0.0 64
USC00511918 2012-12-29 00:00:00 0.0 66
USC00511918 2012-12-30 00:00:00 0.0 68
USC00511918 2012-12-31 00:00:00 0.0 66
USC00511918 2013-01-01 00:00:00 0.0 69
USC00511918 2013-01-02 00:00:00 0.01 70
USC00511918 2013-01-03 00:00:00 0.13 67
USC00511918 2013-01-04 00:00:00 0.01 71
USC00511918 2013-01-05 00:00:00 0.0 73
USC00511918 2013-01-06 00:00:00 0.0 73
USC00511918 2013-01-07 00:00:00 0.01 70
USC00511918 2013-01-08 00:00:00 0.0 71
USC00511918 2013-01-09 00:00:00 0.01 70
USC00511918 2013-01-10 00:00:00 0.0 70
USC00511918 2013-01-11 00:00:00 0.0 70
USC00511918 2013-01-12 00:00:00 0.0 66
USC00511918 2013-01-13 00:00:00 0.0 70
USC00511918 2013-01-14 00:00:00 0.01 74
USC00511918 2013-01-15 00:00:00 0.53 66
USC00511918 2013-01-16 00:00:00 0.0 57
USC00511918 2013-01-17 00:00:00 0.0 61
USC00511918 2013-01-18 00:00:00 0.0 57
USC00511918 2013-01-19 00:00:00 0.0 62
USC00511918 2013-01-20 00:00:00 0.0 64
USC00511918 2013-01-22 00:00:00 0.0 68
USC00511918 2013-01-23 00:00:00 0.0 69
USC00511918 2013-01-24 00:00:00 0.03 67
USC00511918 2013-01-25 00:00:00 0.1 61
USC00511918 2013-01-26 00:00:00 0.08 72
USC00511918 2013-01-27 00:00:00 0.2 74
USC00511918 2013-01-28 00:00:00 1.57 65
USC00511918 2013-01-29 00:00:00 0.03 64
USC00511918 2013-01-30 00:00:00 0.04 62
USC00511918 2013-01-31 00:00:00 0.0 63
USC00511918 2013-02-01 00:00:00 0.0 62
USC00511918 2013-02-02 00:00:00 0.0 74
USC00511918 2013-02-03 00:00:00 0.0 58
USC00511918 2013-02-04 00:00:00 0.0 69
USC00511918 2013-02-05 00:00:00 0.0 69
USC00511918 2013-02-06 00:00:00 0.0 67
USC00511918 2013-02-07 00:00:00 0.0 67
USC00511918 2013-02-08 00:00:00 0.0 64
USC00511918 2013-02-09 00:00:00 0.0 63
USC00511918 2013-02-10 00:00:00 0.0 70
USC00511918 2013-02-11 00:00:00 0.0 69
USC00511918 2013-02-12 00:00:00 0.0 65
USC00511918 2013-02-13 00:00:00 0.0 58
USC00511918 2013-02-14 00:00:00 0.0 62
USC00511918 2013-02-15 00:00:00 0.0 75
USC00511918 2013-02-16 00:00:00 0.0 72
USC00511918 2013-02-17 00:00:00 0.0 73
USC00511918 2013-02-18 00:00:00 0.0 71
USC00511918 2013-02-19 00:00:00 0.0 70
USC00511918 2013-02-20 00:00:00 0.03 67
USC00511918 2013-02-21 00:00:00 0.01 66
USC00511918 2013-02-22 00:00:00 0.15 68
USC00511918 2013-02-23 00:00:00 0.0 69
USC00511918 2013-02-24 00:00:00 0.12 74
USC00511918 2013-02-25 00:00:00 0.0 68
USC00511918 2013-02-26 00:00:00 0.0 69
USC00511918 2013-02-27 00:00:00 0.0 69
USC00511918 2013-02-28 00:00:00 0.0 70
USC00511918 2013-03-01 00:00:00 0.0 70
USC00511918 2013-03-02 00:00:00 0.0 72
USC00511918 2013-03-03 00:00:00 0.0 72
USC00511918 2013-03-04 00:00:00 0.0 69
USC00511918 2013-03-05 00:00:00 0.0 60
USC00511918 2013-03-06 00:00:00 0.0 66
USC00511918 2013-03-07 00:00:00 0.0 60
USC00511918 2013-03-08 00:00:00 0.0 67
USC00511918 2013-03-09 00:00:00 0.0 73
USC00511918 2013-03-10 00:00:00 2.25 67
USC00511918 2013-03-11 00:00:00 0.93 60
USC00511918 2013-03-12 00:00:00 0.0 65
USC00511918 2013-03-13 00:00:00 0.0 60
USC00511918 2013-03-14 00:00:00 0.0 63
USC00511918 2013-03-15 00:00:00 0.0 59
USC00511918 2013-03-16 00:00:00 0.01 66
USC00511918 2013-03-17 00:00:00 0.0 69
USC00511918 2013-03-18 00:00:00 0.0 57
USC00511918 2013-03-19 00:00:00 0.0 60
USC00511918 2013-03-20 00:00:00 0.0 63
USC00511918 2013-03-21 00:00:00 0.0 77
USC00511918 2013-03-22 00:00:00 0.0 74
USC00511918 2013-03-23 00:00:00 0.0 69
USC00511918 2013-03-24 00:00:00 0.01 70
USC00511918 2013-03-25 00:00:00 0.5 69
USC00511918 2013-03-26 00:00:00 0.05 64
USC00511918 2013-03-27 00:00:00 0.04 68
USC00511918 2013-03-28 00:00:00 0.2 65
USC00511918 2013-03-29 00:00:00 0.01 67
USC00511918 2013-03-30 00:00:00 0.0 68
USC00511918 2013-03-31 00:00:00 0.0 63
USC00511918 2013-04-01 00:00:00 0.0 61
USC00511918 2013-04-02 00:00:00 0.0 53
USC00511918 2013-04-03 00:00:00 0.0 55
USC00511918 2013-04-04 00:00:00 0.0 58
USC00511918 2013-04-05 00:00:00 0.0 61
USC00511918 2013-04-06 00:00:00 0.0 73
USC00511918 2013-04-07 00:00:00 0.0 74
USC00511918 2013-04-08 00:00:00 0.0 69
USC00511918 2013-04-09 00:00:00 0.0 62
USC00511918 2013-04-10 00:00:00 0.0 66
USC00511918 2013-04-11 00:00:00 0.0 66
USC00511918 2013-04-12 00:00:00 0.0 71
USC00511918 2013-04-13 00:00:00 0.0 75
USC00511918 2013-04-14 00:00:00 0.1 78
USC00511918 2013-04-15 00:00:00 0.5 68
USC00511918 2013-04-16 00:00:00 0.1 77
USC00511918 2013-04-17 00:00:00 0.0 65
USC00511918 2013-04-18 00:00:00 0.0 71
USC00511918 2013-04-19 00:00:00 0.0 65
USC00511918 2013-04-20 00:00:00 0.01 79
USC00511918 2013-04-21 00:00:00 0.0 72
USC00511918 2013-04-22 00:00:00 0.87 69
USC00511918 2013-04-23 00:00:00 0.07 75
USC00511918 2013-04-24 00:00:00 0.32 69
USC00511918 2013-04-25 00:00:00 0.02 68
USC00511918 2013-04-26 00:00:00 0.0 73
USC00511918 2013-04-27 00:00:00 0.0 78
USC00511918 2013-04-28 00:00:00 0.0 76
USC00511918 2013-04-29 00:00:00 0.0 75
USC00511918 2013-04-30 00:00:00 0.0 73
USC00511918 2013-05-01 00:00:00 0.0 67
USC00511918 2013-05-02 00:00:00 0.0 68
USC00511918 2013-05-03 00:00:00 0.0 67
USC00511918 2013-05-04 00:00:00 0.0 78
USC00511918 2013-05-05 00:00:00 0.03 72
USC00511918 2013-05-06 00:00:00 0.11 70
USC00511918 2013-05-07 00:00:00 0.0 67
USC00511918 2013-05-08 00:00:00 0.0 65
USC00511918 2013-05-09 00:00:00 0.0 69
USC00511918 2013-05-10 00:00:00 0.0 72
USC00511918 2013-05-11 00:00:00 0.0 77
USC00511918 2013-05-12 00:00:00 0.0 74
USC00511918 2013-05-13 00:00:00 0.01 71
USC00511918 2013-05-14 00:00:00 0.0 74
USC00511918 2013-05-15 00:00:00 0.0 74
USC00511918 2013-05-16 00:00:00 0.0 75
USC00511918 2013-05-17 00:00:00 0.0 70
USC00511918 2013-05-18 00:00:00 0.05 78
USC00511918 2013-05-19 00:00:00 0.06 77
USC00511918 2013-05-20 00:00:00 0.0 76
USC00511918 2013-05-21 00:00:00 0.0 64
USC00511918 2013-05-22 00:00:00 0.0 66
USC00511918 2013-05-23 00:00:00 0.0 68
USC00511918 2013-05-24 00:00:00 0.0 73
USC00511918 2013-05-25 00:00:00 0.0 78
USC00511918 2013-05-26 00:00:00 0.0 82
USC00511918 2013-05-27 00:00:00 0.0 79
USC00511918 2013-05-28 00:00:00 0.0 70
USC00511918 2013-05-29 00:00:00 0.0 71
USC00511918 2013-05-30 00:00:00 0.0 69
USC00511918 2013-05-31 00:00:00 0.0 70
USC00511918 2013-06-01 00:00:00 0.0 80
USC00511918 2013-06-02 00:00:00 0.0 81
USC00511918 2013-06-03 00:00:00 0.0 75
USC00511918 2013-06-04 00:00:00 0.0 80
USC00511918 2013-06-05 00:00:00 0.0 73
USC00511918 2013-06-06 00:00:00 0.0 74
USC00511918 2013-06-07 00:00:00 0.0 73
USC00511918 2013-06-08 00:00:00 0.0 81
USC00511918 2013-06-09 00:00:00 0.0 79
USC00511918 2013-06-10 00:00:00 0.0 78
USC00511918 2013-06-11 00:00:00 0.0 74
USC00511918 2013-06-12 00:00:00 0.0 74
USC00511918 2013-06-13 00:00:00 0.0 73
USC00511918 2013-06-14 00:00:00 0.07 73
USC00511918 2013-06-15 00:00:00 0.0 77
USC00511918 2013-06-16 00:00:00 0.0 77
USC00511918 2013-06-17 00:00:00 0.0 74
USC00511918 2013-06-18 00:00:00 0.0 73

USC00511918 2013-06-19 00:00:00 0.0 70
USC00511918 2013-06-20 00:00:00 0.0 69
USC00511918 2013-06-21 00:00:00 0.05 72
USC00511918 2013-06-22 00:00:00 0.0 79
USC00511918 2013-06-23 00:00:00 0.0 77
USC00511918 2013-06-24 00:00:00 0.0 70
USC00511918 2013-06-25 00:00:00 0.02 71
USC00511918 2013-06-26 00:00:00 0.06 67
USC00511918 2013-06-27 00:00:00 0.0 66
USC00511918 2013-06-28 00:00:00 0.0 78
USC00511918 2013-06-29 00:00:00 0.08 80
USC00511918 2013-06-30 00:00:00 0.0 80
USC00511918 2013-07-01 00:00:00 0.0 68
USC00511918 2013-07-02 00:00:00 0.0 72
USC00511918 2013-07-03 00:00:00 0.04 69
USC00511918 2013-07-04 00:00:00 0.0 78
USC00511918 2013-07-05 00:00:00 0.0 76
USC00511918 2013-07-06 00:00:00 0.0 79
USC00511918 2013-07-07 00:00:00 0.0 75
USC00511918 2013-07-08 00:00:00 0.0 70
USC00511918 2013-07-09 00:00:00 0.0 81
USC00511918 2013-07-10 00:00:00 0.0 77
USC00511918 2013-07-11 00:00:00 0.0 76
USC00511918 2013-07-12 00:00:00 0.0 72
USC00511918 2013-07-13 00:00:00 0.0 75
USC00511918 2013-07-14 00:00:00 0.0 81
USC00511918 2013-07-15 00:00:00 0.0 72
USC00511918 2013-07-16 00:00:00 0.0 71
USC00511918 2013-07-17 00:00:00 0.0 71
USC00511918 2013-07-18 00:00:00 0.0 73
USC00511918 2013-07-19 00:00:00 0.0 81
USC00511918 2013-07-21 00:00:00 0.0 80
USC00511918 2013-07-22 00:00:00 0.0 73
USC00511918 2013-07-23 00:00:00 0.0 75
USC00511918 2013-07-24 00:00:00 0.0 69
USC00511918 2013-07-25 00:00:00 0.0 67
USC00511918 2013-07-26 00:00:00 0.0 71
USC00511918 2013-07-27 00:00:00 0.0 78
USC00511918 2013-07-28 00:00:00 0.02 77
USC00511918 2013-07-29 00:00:00 0.02 75
USC00511918 2013-07-30 00:00:00 0.5 79
USC00511918 2013-07-31 00:00:00 0.01 78
USC00511918 2013-08-01 00:00:00 0.0 76
USC00511918 2013-08-02 00:00:00 0.0 74
USC00511918 2013-08-03 00:00:00 0.0 79
USC00511918 2013-08-04 00:00:00 0.0 79
USC00511918 2013-08-05 00:00:00 0.0 69
USC00511918 2013-08-06 00:00:00 0.0 74
USC00511918 2013-08-07 00:00:00 0.0 72
USC00511918 2013-08-08 00:00:00 0.0 68
USC00511918 2013-08-09 00:00:00 0.0 75
USC00511918 2013-08-10 00:00:00 0.07 73
USC00511918 2013-08-11 00:00:00 0.0 81
USC00511918 2013-08-12 00:00:00 0.0 77
USC00511918 2013-08-13 00:00:00 0.0 74
USC00511918 2013-08-14 00:00:00 0.0 75
USC00511918 2013-08-15 00:00:00 0.0 69
USC00511918 2013-08-16 00:00:00 0.01 82
USC00511918 2013-08-17 00:00:00 0.0 80
USC00511918 2013-08-18 00:00:00 0.0 84
USC00511918 2013-08-19 00:00:00 0.0 69
USC00511918 2013-08-20 00:00:00 0.0 68
USC00511918 2013-08-21 00:00:00 0.0 71
USC00511918 2013-08-22 00:00:00 0.0 70
USC00511918 2013-08-23 00:00:00 0.0 71
USC00511918 2013-08-24 00:00:00 0.0 80
USC00511918 2013-08-25 00:00:00 0.0 81
USC00511918 2013-08-26 00:00:00 0.0 76
USC00511918 2013-08-27 00:00:00 0.0 75
USC00511918 2013-08-28 00:00:00 0.0 71
USC00511918 2013-08-29 00:00:00 0.06 70
USC00511918 2013-08-30 00:00:00 0.0 80
USC00511918 2013-08-31 00:00:00 0.0 85
USC00511918 2013-09-01 00:00:00 0.35 78
USC00511918 2013-09-02 00:00:00 0.0 81
USC00511918 2013-09-03 00:00:00 0.0 69
USC00511918 2013-09-04 00:00:00 0.0 70
USC00511918 2013-09-05 00:00:00 0.0 66
USC00511918 2013-09-06 00:00:00 0.0 68
USC00511918 2013-09-07 00:00:00 0.05 74
USC00511918 2013-09-08 00:00:00 0.01 81
USC00511918 2013-09-09 00:00:00 0.0 73
USC00511918 2013-09-10 00:00:00 0.0 67
USC00511918 2013-09-11 00:00:00 0.0 72
USC00511918 2013-09-12 00:00:00 0.0 70
USC00511918 2013-09-13 00:00:00 0.22 73
USC00511918 2013-09-14 00:00:00 0.14 78
USC00511918 2013-09-15 00:00:00 0.16 81
USC00511918 2013-09-16 00:00:00 0.0 86
USC00511918 2013-09-17 00:00:00 0.0 77
USC00511918 2013-09-18 00:00:00 0.0 84
USC00511918 2013-09-19 00:00:00 0.0 81
USC00511918 2013-09-20 00:00:00 0.0 83
USC00511918 2013-09-21 00:00:00 0.0 78
USC00511918 2013-09-22 00:00:00 0.0 81
USC00511918 2013-09-23 00:00:00 0.0 69
USC00511918 2013-09-24 00:00:00 0.0 74
USC00511918 2013-09-25 00:00:00 0.1 71
USC00511918 2013-09-26 00:00:00 0.01 69
USC00511918 2013-09-27 00:00:00 0.04 80
USC00511918 2013-09-28 00:00:00 0.0 84
USC00511918 2013-09-29 00:00:00 0.1 75
USC00511918 2013-09-30 00:00:00 0.0 72
USC00511918 2013-10-01 00:00:00 0.01 71
USC00511918 2013-10-02 00:00:00 0.0 73
USC00511918 2013-10-03 00:00:00 0.0 72
USC00511918 2013-10-04 00:00:00 0.0 68
USC00511918 2013-10-05 00:00:00 0.0 82
USC00511918 2013-10-06 00:00:00 0.0 81
USC00511918 2013-10-07 00:00:00 0.01 68
USC00511918 2013-10-08 00:00:00 0.0 74
USC00511918 2013-10-09 00:00:00 0.03 75
USC00511918 2013-10-10 00:00:00 0.0 73
USC00511918 2013-10-11 00:00:00 0.0 69
USC00511918 2013-10-12 00:00:00 0.0 77
USC00511918 2013-10-13 00:00:00 0.0 78
USC00511918 2013-10-14 00:00:00 0.0 71
USC00511918 2013-10-15 00:00:00 0.38 67
USC00511918 2013-10-16 00:00:00 0.08 67
USC00511918 2013-10-17 00:00:00 0.01 67
USC00511918 2013-10-18 00:00:00 0.0 81
USC00511918 2013-10-19 00:00:00 0.01 76
USC00511918 2013-10-20 00:00:00 0.01 74
USC00511918 2013-10-21 00:00:00 0.0 67
USC00511918 2013-10-22 00:00:00 0.0 68
USC00511918 2013-10-23 00:00:00 0.0 66
USC00511918 2013-10-24 00:00:00 0.0 76
USC00511918 2013-10-25 00:00:00 0.0 76
USC00511918 2013-10-26 00:00:00 0.0 75
USC00511918 2013-10-27 00:00:00 0.0 76
USC00511918 2013-10-28 00:00:00 0.0 69
USC00511918 2013-10-29 00:00:00 0.0 68
USC00511918 2013-10-30 00:00:00 0.0 67
USC00511918 2013-10-31 00:00:00 0.0 70
USC00511918 2013-11-01 00:00:00 0.01 79
USC00511918 2013-11-02 00:00:00 0.0 81
USC00511918 2013-11-03 00:00:00 0.0 80
USC00511918 2013-11-04 00:00:00 0.0 70
USC00511918 2013-11-05 00:00:00 0.0 74
USC00511918 2013-11-06 00:00:00 0.0 67
USC00511918 2013-11-07 00:00:00 0.0 69
USC00511918 2013-11-08 00:00:00 0.0 69
USC00511918 2013-11-09 00:00:00 0.01 79
USC00511918 2013-11-10 00:00:00 0.93 72
USC00511918 2013-11-11 00:00:00 0.01 75
USC00511918 2013-11-12 00:00:00 0.0 62
USC00511918 2013-11-13 00:00:00 0.0 63
USC00511918 2013-11-14 00:00:00 0.01 73
USC00511918 2013-11-15 00:00:00 0.27 76
USC00511918 2013-11-16 00:00:00 0.0 72
USC00511918 2013-11-17 00:00:00 0.0 70
USC00511918 2013-11-18 00:00:00 0.0 67
USC00511918 2013-11-19 00:00:00 0.0 65
USC00511918 2013-11-20 00:00:00 0.0 68
USC00511918 2013-11-21 00:00:00 0.0 72
USC00511918 2013-11-22 00:00:00 0.0 66
USC00511918 2013-11-23 00:00:00 0.0 77
USC00511918 2013-11-24 00:00:00 0.0 68
USC00511918 2013-11-25 00:00:00 0.0 63
USC00511918 2013-11-26 00:00:00 0.0 67
USC00511918 2013-11-27 00:00:00 0.0 63
USC00511918 2013-11-28 00:00:00 0.0 80
USC00511918 2013-11-29 00:00:00 0.0 69
USC00511918 2013-11-30 00:00:00 0.42 78
USC00511918 2013-12-01 00:00:00 0.46 70
USC00511918 2013-12-02 00:00:00 0.87 68
USC00511918 2013-12-03 00:00:00 0.0 68
USC00511918 2013-12-04 00:00:00 0.01 66
USC00511918 2013-12-05 00:00:00 0.01 75
USC00511918 2013-12-06 00:00:00 0.0 67
USC00511918 2013-12-07 00:00:00 0.0 70
USC00511918 2013-12-08 00:00:00 0.0 72
USC00511918 2013-12-09 00:00:00 0.0 69
USC00511918 2013-12-10 00:00:00 0.0 72
USC00511918 2013-12-11 00:00:00 0.0 69
USC00511918 2013-12-12 00:00:00 0.02 65
USC00511918 2013-12-13 00:00:00 0.0 71
USC00511918 2013-12-14 00:00:00 0.0 73
USC00511918 2013-12-15 00:00:00 0.06 69
USC00511918 2013-12-16 00:00:00 2.4 69
USC00511918 2013-12-17 00:00:00 0.01 63
USC00511918 2013-12-18 00:00:00 0.01 63
USC00511918 2013-12-19 00:00:00 0.05 71
USC00511918 2013-12-20 00:00:00 0.0 79
USC00511918 2013-12-21 00:00:00 0.0 67
USC00511918 2013-12-22 00:00:00 0.0 67
USC00511918 2013-12-23 00:00:00 0.08 64
USC00511918 2013-12-24 00:00:00 0.0 63
USC00511918 2013-12-25 00:00:00 0.0 68
USC00511918 2013-12-26 00:00:00 0.0 77
USC00511918 2013-12-27 00:00:00 0.0 79
USC00511918 2013-12-28 00:00:00 0.0 74
USC00511918 2013-12-29 00:00:00 0.0 68
USC00511918 2013-12-30 00:00:00 0.0 64
USC00511918 2014-01-01 00:00:00 0.0 66
USC00511918 2014-01-02 00:00:00 0.3 77
USC00511918 2014-01-03 00:00:00 1.05 73
USC00511918 2014-01-04 00:00:00 0.0 65
USC00511918 2014-01-05 00:00:00 0.0 61
USC00511918 2014-01-06 00:00:00 0.0 61
USC00511918 2014-01-07 00:00:00 0.0 60
USC00511918 2014-01-08 00:00:00 0.0 63
USC00511918 2014-01-09 00:00:00 0.01 63
USC00511918 2014-01-10 00:00:00 0.0 65
USC00511918 2014-01-11 00:00:00 0.06 64
USC00511918 2014-01-12 00:00:00 0.19 80
USC00511918 2014-01-13 00:00:00 0.42 66
USC00511918 2014-01-14 00:00:00 0.31 67
USC00511918 2014-01-15 00:00:00 0.0 63
USC00511918 2014-01-16 00:00:00 0.02 66
USC00511918 2014-01-17 00:00:00 0.0 65
USC00511918 2014-01-18 00:00:00 0.01 66
USC00511918 2014-01-19 00:00:00 0.0 66
USC00511918 2014-01-20 00:00:00 0.0 76
USC00511918 2014-01-21 00:00:00 0.0 63
USC00511918 2014-01-22 00:00:00 0.5 69
USC00511918 2014-01-23 00:00:00 0.0 57
USC00511918 2014-01-24 00:00:00 0.0 58
USC00511918 2014-01-25 00:00:00 0.0 75
USC00511918 2014-01-26 00:00:00 0.0 74
USC00511918 2014-01-27 00:00:00 0.14 67
USC00511918 2014-01-29 00:00:00 0.12 70
USC00511918 2014-01-30 00:00:00 0.0 64
USC00511918 2014-01-31 00:00:00 0.0 64
USC00511918 2014-02-01 00:00:00 0.03 72
USC00511918 2014-02-02 00:00:00 0.1 67
USC00511918 2014-02-03 00:00:00 0.0 66
USC00511918 2014-02-04 00:00:00 0.38 66
USC00511918 2014-02-05 00:00:00 0.42 74
USC00511918 2014-02-06 00:00:00 0.01 74
USC00511918 2014-02-07 00:00:00 0.01 69
USC00511918 2014-02-08 00:00:00 0.0 69
USC00511918 2014-02-09 00:00:00 0.0 69
USC00511918 2014-02-10 00:00:00 0.0 72
USC00511918 2014-02-11 00:00:00 0.0 68
USC00511918 2014-02-12 00:00:00 0.0 66
USC00511918 2014-02-13 00:00:00 0.0 66
USC00511918 2014-02-14 00:00:00 0.0 72
USC00511918 2014-02-15 00:00:00 0.01 74
USC00511918 2014-02-16 00:00:00 0.12 70
USC00511918 2014-02-17 00:00:00 0.27 73
USC00511918 2014-02-18 00:00:00 0.03 69
USC00511918 2014-02-19 00:00:00 0.01 68
USC00511918 2014-02-20 00:00:00 0.0 64
USC00511918 2014-02-21 00:00:00 0.0 65
USC00511918 2014-02-22 00:00:00 0.0 72
USC00511918 2014-02-23 00:00:00 0.0 69
USC00511918 2014-02-24 00:00:00 0.0 63
USC00511918 2014-02-25 00:00:00 0.0 67
USC00511918 2014-02-26 00:00:00 0.0 65
USC00511918 2014-02-27 00:00:00 0.0 58
USC00511918 2014-02-28 00:00:00 0.04 74
USC00511918 2014-03-01 00:00:00 0.5 69
USC00511918 2014-03-02 00:00:00 0.33 68
USC00511918 2014-03-03 00:00:00 0.15 63
USC00511918 2014-03-04 00:00:00 0.0 57
USC00511918 2014-03-05 00:00:00 0.0 63
USC00511918 2014-03-06 00:00:00 0.0 62
USC00511918 2014-03-07 00:00:00 0.05 67
USC00511918 2014-03-08 00:00:00 0.78 67
USC00511918 2014-03-09 00:00:00 0.38 75
USC00511918 2014-03-10 00:00:00 0.01 64
USC00511918 2014-03-11 00:00:00 0.04 64
USC00511918 2014-03-12 00:00:00 0.0 62
USC00511918 2014-03-13 00:00:00 0.0 67
USC00511918 2014-03-14 00:00:00 0.01 70
USC00511918 2014-03-15 00:00:00 0.0 69
USC00511918 2014-03-16 00:00:00 0.0 70
USC00511918 2014-03-17 00:00:00 0.0 66
USC00511918 2014-03-18 00:00:00 0.0 62
USC00511918 2014-03-19 00:00:00 0.0 60
USC00511918 2014-03-20 00:00:00 0.0 62
USC00511918 2014-03-21 00:00:00 0.0 64
USC00511918 2014-03-22 00:00:00 0.0 74
USC00511918 2014-03-23 00:00:00 0.0 73
USC00511918 2014-03-24 00:00:00 0.0 64
USC00511918 2014-03-25 00:00:00 0.0 67
USC00511918 2014-03-26 00:00:00 0.1 68
USC00511918 2014-03-27 00:00:00 0.0 68
USC00511918 2014-03-28 00:00:00 0.0 67
USC00511918 2014-03-29 00:00:00 0.38 73
USC00511918 2014-03-30 00:00:00 0.15 72
USC00511918 2014-03-31 00:00:00 0.0 71
USC00511918 2014-04-01 00:00:00 0.0 70
USC00511918 2014-04-04 00:00:00 0.0 72
USC00511918 2014-04-05 00:00:00 0.0 76
USC00511918 2014-04-06 00:00:00 0.0 76
USC00511918 2014-04-07 00:00:00 0.03 67
USC00511918 2014-04-08 00:00:00 0.0 68
USC00511918 2014-04-09 00:00:00 0.0 69
USC00511918 2014-04-10 00:00:00 0.0 68
USC00511918 2014-04-11 00:00:00 0.0 69
USC00511918 2014-04-12 00:00:00 0.1 69
USC00511918 2014-04-13 00:00:00 0.0 75
USC00511918 2014-04-14 00:00:00 0.01 71
USC00511918 2014-04-15 00:00:00 0.0 71
USC00511918 2014-04-16 00:00:00 0.01 70
USC00511918 2014-04-17 00:00:00 0.0 70
USC00511918 2014-04-18 00:00:00 0.0 74
USC00511918 2014-04-19 00:00:00 0.0 76
USC00511918 2014-04-20 00:00:00 0.0 80
USC00511918 2014-04-21 00:00:00 0.03 71
USC00511918 2014-04-22 00:00:00 0.01 74
USC00511918 2014-04-23 00:00:00 0.0 73
USC00511918 2014-04-24 00:00:00 0.0 72
USC00511918 2014-04-25 00:00:00 0.0 72
USC00511918 2014-04-26 00:00:00 0.0 80
USC00511918 2014-04-27 00:00:00 0.07 72
USC00511918 2014-04-28 00:00:00 0.15 63
USC00511918 2014-04-29 00:00:00 0.02 68
USC00511918 2014-04-30 00:00:00 0.0 66
USC00511918 2014-05-01 00:00:00 0.0 65
USC00511918 2014-05-02 00:00:00 0.0 69
USC00511918 2014-05-03 00:00:00 0.06 78
USC00511918 2014-05-04 00:00:00 0.0 78
USC00511918 2014-05-05 00:00:00 0.0 68
USC00511918 2014-05-06 00:00:00 0.51 69
USC00511918 2014-05-07 00:00:00 0.0 68
USC00511918 2014-05-08 00:00:00 0.0 68
USC00511918 2014-05-09 00:00:00 0.0 68
USC00511918 2014-05-10 00:00:00 0.0 78
USC00511918 2014-05-11 00:00:00 0.02 76
USC00511918 2014-05-12 00:00:00 0.03 69
USC00511918 2014-05-13 00:00:00 0.0 68
USC00511918 2014-05-14 00:00:00 0.0 65
USC00511918 2014-05-15 00:00:00 0.0 65
USC00511918 2014-05-16 00:00:00 0.0 80
USC00511918 2014-05-17 00:00:00 0.0 79
USC00511918 2014-05-19 00:00:00 0.03 68
USC00511918 2014-05-20 00:00:00 0.12 70
USC00511918 2014-05-21 00:00:00 0.14 66
USC00511918 2014-05-22 00:00:00 0.0 67
USC00511918 2014-05-23 00:00:00 0.04 77
USC00511918 2014-05-24 00:00:00 0.23 75
USC00511918 2014-05-25 00:00:00 0.04 78
USC00511918 2014-05-27 00:00:00 0.85 72
USC00511918 2014-05-28 00:00:00 0.0 69
USC00511918 2014-05-29 00:00:00 0.0 73
USC00511918 2014-05-30 00:00:00 0.0 71
USC00511918 2014-05-31 00:00:00 0.29 79
USC00511918 2014-06-01 00:00:00 0.0 79
USC00511918 2014-06-02 00:00:00 0.0 68
USC00511918 2014-06-03 00:00:00 0.0 67
USC00511918 2014-06-04 00:00:00 0.0 71
USC00511918 2014-06-07 00:00:00 0.0 79
USC00511918 2014-06-08 00:00:00 0.0 80
USC00511918 2014-06-09 00:00:00 0.0 72
USC00511918 2014-06-10 00:00:00 0.0 68
USC00511918 2014-06-11 00:00:00 0.0 84
USC00511918 2014-06-12 00:00:00 0.0 82
USC00511918 2014-06-13 00:00:00 0.0 79
USC00511918 2014-06-14 00:00:00 0.0 78
USC00511918 2014-06-15 00:00:00 0.0 81
USC00511918 2014-06-16 00:00:00 0.0 77
USC00511918 2014-06-17 00:00:00 0.17 71
USC00511918 2014-06-18 00:00:00 0.01 69
USC00511918 2014-06-19 00:00:00 0.0 73
USC00511918 2014-06-20 00:00:00 0.03 68
USC00511918 2014-06-21 00:00:00 0.0 75
USC00511918 2014-06-22 00:00:00 0.0 79
USC00511918 2014-06-23 00:00:00 0.05 70
USC00511918 2014-06-24 00:00:00 0.05 70
USC00511918 2014-06-25 00:00:00 0.05 73
USC00511918 2014-06-26 00:00:00 0.03 71
USC00511918 2014-06-27 00:00:00 0.02 68
USC00511918 2014-06-29 00:00:00 0.05 78
USC00511918 2014-06-30 00:00:00 0.0 69
USC00511918 2014-07-01 00:00:00 0.0 70
USC00511918 2014-07-02 00:00:00 0.01 68
USC00511918 2014-07-03 00:00:00 0.02 73
USC00511918 2014-07-04 00:00:00 0.0 81
USC00511918 2014-07-05 00:00:00 0.0 73
USC00511918 2014-07-06 00:00:00 0.1 72
USC00511918 2014-07-07 00:00:00 0.02 72

USC00511918 2014-07-08 00:00:00 0.02 69
USC00511918 2014-07-09 00:00:00 0.0 72
USC00511918 2014-07-10 00:00:00 0.0 76
USC00511918 2014-07-11 00:00:00 0.01 75
USC00511918 2014-07-12 00:00:00 0.0 81
USC00511918 2014-07-13 00:00:00 0.05 80
USC00511918 2014-07-14 00:00:00 0.0 76
USC00511918 2014-07-15 00:00:00 0.04 75
USC00511918 2014-07-16 00:00:00 0.0 75
USC00511918 2014-07-17 00:00:00 0.0 75
USC00511918 2014-07-18 00:00:00 0.0 74
USC00511918 2014-07-19 00:00:00 0.0 83
USC00511918 2014-07-20 00:00:00 1.0 74
USC00511918 2014-07-21 00:00:00 0.01 73
USC00511918 2014-07-22 00:00:00 0.0 74
USC00511918 2014-07-23 00:00:00 0.01 75
USC00511918 2014-07-24 00:00:00 0.0 74
USC00511918 2014-07-25 00:00:00 0.0 76
USC00511918 2014-07-26 00:00:00 0.0 82
USC00511918 2014-07-27 00:00:00 0.1 75
USC00511918 2014-07-28 00:00:00 0.0 73
USC00511918 2014-07-29 00:00:00 0.0 70
USC00511918 2014-07-30 00:00:00 0.0 74
USC00511918 2014-07-31 00:00:00 0.0 83
USC00511918 2014-08-01 00:00:00 0.0 75
USC00511918 2014-08-02 00:00:00 0.0 81
USC00511918 2014-08-03 00:00:00 0.0 83
USC00511918 2014-08-04 00:00:00 0.0 83
USC00511918 2014-08-05 00:00:00 0.0 76
USC00511918 2014-08-06 00:00:00 0.03 73
USC00511918 2014-08-07 00:00:00 0.02 81
USC00511918 2014-08-08 00:00:00 0.08 79
USC00511918 2014-08-09 00:00:00 0.42 74
USC00511918 2014-08-10 00:00:00 0.01 82
USC00511918 2014-08-11 00:00:00 0.0 69
USC00511918 2014-08-12 00:00:00 0.0 70
USC00511918 2014-08-13 00:00:00 0.0 71
USC00511918 2014-08-14 00:00:00 0.0 71
USC00511918 2014-08-15 00:00:00 0.0 70
USC00511918 2014-08-16 00:00:00 0.0 83
USC00511918 2014-08-17 00:00:00 0.0 80
USC00511918 2014-08-18 00:00:00 0.0 70
USC00511918 2014-08-19 00:00:00 0.0 70
USC00511918 2014-08-20 00:00:00 0.0 69
USC00511918 2014-08-21 00:00:00 0.0 69
USC00511918 2014-08-22 00:00:00 0.0 73
USC00511918 2014-08-25 00:00:00 0.07 73
USC00511918 2014-08-26 00:00:00 0.08 71
USC00511918 2014-08-27 00:00:00 0.0 68
USC00511918 2014-08-28 00:00:00 0.0 67
USC00511918 2014-08-29 00:00:00 0.0 80
USC00511918 2014-08-30 00:00:00 0.0 80
USC00511918 2014-08-31 00:00:00 0.0 80
USC00511918 2014-09-01 00:00:00 0.0 82
USC00511918 2014-09-02 00:00:00 0.0 80
USC00511918 2014-09-03 00:00:00 0.0 71
USC00511918 2014-09-04 00:00:00 0.0 71
USC00511918 2014-09-05 00:00:00 0.0 73
USC00511918 2014-09-06 00:00:00 0.0 81
USC00511918 2014-09-07 00:00:00 0.0 81
USC00511918 2014-09-08 00:00:00 0.0 72
USC00511918 2014-09-09 00:00:00 0.0 80
USC00511918 2014-09-10 00:00:00 0.0 80
USC00511918 2014-09-11 00:00:00 0.0 70
USC00511918 2014-09-12 00:00:00 0.0 68
USC00511918 2014-09-13 00:00:00 0.0 82
USC00511918 2014-09-14 00:00:00 0.0 80
USC00511918 2014-09-15 00:00:00 0.01 75
USC00511918 2014-09-18 00:00:00 0.02 73
USC00511918 2014-09-19 00:00:00 0.54 71
USC00511918 2014-09-20 00:00:00 0.0 77
USC00511918 2014-09-21 00:00:00 0.0 79
USC00511918 2014-09-22 00:00:00 0.0 72
USC00511918 2014-09-23 00:00:00 0.0 79
USC00511918 2014-09-24 00:00:00 0.0 85
USC00511918 2014-09-25 00:00:00 0.05 71
USC00511918 2014-09-26 00:00:00 0.07 75
USC00511918 2014-09-27 00:00:00 0.09 77
USC00511918 2014-09-28 00:00:00 0.02 80
USC00511918 2014-09-29 00:00:00 0.02 74
USC00511918 2014-09-30 00:00:00 0.0 72
USC00511918 2014-10-01 00:00:00 0.03 71
USC00511918 2014-10-02 00:00:00 0.0 70
USC00511918 2014-10-03 00:00:00 0.0 74
USC00511918 2014-10-04 00:00:00 0.0 82
USC00511918 2014-10-05 00:00:00 0.0 81
USC00511918 2014-10-06 00:00:00 0.38 70
USC00511918 2014-10-07 00:00:00 0.24 72
USC00511918 2014-10-08 00:00:00 0.0 72
USC00511918 2014-10-09 00:00:00 0.0 73
USC00511918 2014-10-10 00:00:00 0.0 80
USC00511918 2014-10-11 00:00:00 0.0 84
USC00511918 2014-10-12 00:00:00 0.0 80
USC00511918 2014-10-13 00:00:00 0.0 75
USC00511918 2014-10-14 00:00:00 0.0 76
USC00511918 2014-10-15 00:00:00 0.03 80
USC00511918 2014-10-16 00:00:00 0.0 80
USC00511918 2014-10-17 00:00:00 0.0 82
USC00511918 2014-10-18 00:00:00 0.07 83
USC00511918 2014-10-19 00:00:00 4.0 74
USC00511918 2014-10-20 00:00:00 1.7 76
USC00511918 2014-10-21 00:00:00 0.0 69
USC00511918 2014-10-22 00:00:00 0.0 72
USC00511918 2014-10-23 00:00:00 0.08 76
USC00511918 2014-10-24 00:00:00 0.0 70
USC00511918 2014-10-25 00:00:00 0.0 74
USC00511918 2014-10-26 00:00:00 0.01 80
USC00511918 2014-10-27 00:00:00 0.0 68
USC00511918 2014-10-28 00:00:00 0.0 68
USC00511918 2014-10-29 00:00:00 0.0 73
USC00511918 2014-10-30 00:00:00 0.0 74
USC00511918 2014-10-31 00:00:00 0.0 76
USC00511918 2014-11-02 00:00:00 0.01 78
USC00511918 2014-11-03 00:00:00 0.03 73
USC00511918 2014-11-04 00:00:00 0.0 70
USC00511918 2014-11-05 00:00:00 0.0 72
USC00511918 2014-11-06 00:00:00 0.04 66
USC00511918 2014-11-07 00:00:00 0.03 75
USC00511918 2014-11-08 00:00:00 0.04 75
USC00511918 2014-11-09 00:00:00 0.0 76
USC00511918 2014-11-10 00:00:00 0.0 71
USC00511918 2014-11-11 00:00:00 0.0 78
USC00511918 2014-11-12 00:00:00 0.0 68
USC00511918 2014-11-13 00:00:00 0.0 67
USC00511918 2014-11-14 00:00:00 0.0 69
USC00511918 2014-11-15 00:00:00 0.41 75
USC00511918 2014-11-16 00:00:00 0.1 76
USC00511918 2014-11-17 00:00:00 0.0 64
USC00511918 2014-11-18 00:00:00 0.0 74
USC00511918 2014-11-20 00:00:00 0.01 78
USC00511918 2014-11-21 00:00:00 0.0 74
USC00511918 2014-11-22 00:00:00 0.0 75
USC00511918 2014-11-23 00:00:00 0.0 70
USC00511918 2014-11-24 00:00:00 0.0 72
USC00511918 2014-11-25 00:00:00 0.0 69
USC00511918 2014-11-26 00:00:00 0.0 68
USC00511918 2014-11-27 00:00:00 0.0 73
USC00511918 2014-11-28 00:00:00 0.0 77
USC00511918 2014-11-29 00:00:00 0.0 75
USC00511918 2014-11-30 00:00:00 0.0 77
USC00511918 2014-12-01 00:00:00 0.0 70
USC00511918 2014-12-02 00:00:00 0.0 62
USC00511918 2014-12-03 00:00:00 0.17 68
USC00511918 2014-12-04 00:00:00 0.09 67
USC00511918 2014-12-05 00:00:00 0.0 70
USC00511918 2014-12-06 00:00:00 0.0 66
USC00511918 2014-12-07 00:00:00 0.0 64
USC00511918 2014-12-08 00:00:00 0.01 62
USC00511918 2014-12-09 00:00:00 0.0 64
USC00511918 2014-12-10 00:00:00 0.0 63
USC00511918 2014-12-11 00:00:00 0.01 69
USC00511918 2014-12-12 00:00:00 0.0 64
USC00511918 2014-12-15 00:00:00 0.0 72
USC00511918 2014-12-16 00:00:00 0.0 72
USC00511918 2014-12-17 00:00:00 0.03 64
USC00511918 2014-12-18 00:00:00 0.0 71
USC00511918 2014-12-19 00:00:00 0.0 68
USC00511918 2014-12-20 00:00:00 0.0 81
USC00511918 2014-12-21 00:00:00 0.0 78
USC00511918 2014-12-22 00:00:00 0.01 69
USC00511918 2014-12-23 00:00:00 0.1 72
USC00511918 2014-12-24 00:00:00 0.0 70
USC00511918 2014-12-25 00:00:00 0.0 62
USC00511918 2014-12-26 00:00:00 0.0 76
USC00511918 2014-12-27 00:00:00 0.0 72
USC00511918 2014-12-28 00:00:00 0.0 76
USC00511918 2014-12-29 00:00:00 0.0 57
USC00511918 2014-12-30 00:00:00 0.0 64
USC00511918 2014-12-31 00:00:00 0.7 57
USC00511918 2015-01-01 00:00:00 0.0 66
USC00511918 2015-01-02 00:00:00 0.0 65
USC00511918 2015-01-03 00:00:00 0.75 69
USC00511918 2015-01-04 00:00:00 0.0 62
USC00511918 2015-01-05 00:00:00 0.0 56
USC00511918 2015-01-06 00:00:00 0.01 63
USC00511918 2015-01-07 00:00:00 0.0 57
USC00511918 2015-01-08 00:00:00 0.0 57
USC00511918 2015-01-09 00:00:00 0.0 62
USC00511918 2015-01-10 00:00:00 0.0 77
USC00511918 2015-01-11 00:00:00 0.0 66
USC00511918 2015-01-12 00:00:00 0.01 63
USC00511918 2015-01-13 00:00:00 0.0 60
USC00511918 2015-01-14 00:00:00 0.0 72
USC00511918 2015-01-15 00:00:00 0.0 74
USC00511918 2015-01-16 00:00:00 0.01 69
USC00511918 2015-01-17 00:00:00 0.03 70
USC00511918 2015-01-18 00:00:00 0.0 74
USC00511918 2015-01-19 00:00:00 0.0 63
USC00511918 2015-01-20 00:00:00 0.0 67
USC00511918 2015-01-21 00:00:00 0.0 61
USC00511918 2015-01-22 00:00:00 0.0 66
USC00511918 2015-01-23 00:00:00 0.0 67
USC00511918 2015-01-24 00:00:00 0.0 72
USC00511918 2015-01-25 00:00:00 0.0 68
USC00511918 2015-01-26 00:00:00 0.0 66
USC00511918 2015-01-27 00:00:00 0.0 59
USC00511918 2015-01-28 00:00:00 0.0 68
USC00511918 2015-01-29 00:00:00 0.01 74
USC00511918 2015-01-30 00:00:00 0.07 60
USC00511918 2015-01-31 00:00:00 0.0 65
USC00511918 2015-02-01 00:00:00 0.0 72
USC00511918 2015-02-03 00:00:00 0.0 76
USC00511918 2015-02-06 00:00:00 0.0 75
USC00511918 2015-02-07 00:00:00 0.0 73
USC00511918 2015-02-08 00:00:00 0.0 64
USC00511918 2015-02-09 00:00:00 0.0 75
USC00511918 2015-02-10 00:00:00 0.08 71
USC00511918 2015-02-11 00:00:00 0.0 71
USC00511918 2015-02-12 00:00:00 0.0 62
USC00511918 2015-02-15 00:00:00 0.02 63
USC00511918 2015-02-16 00:00:00 0.0 68
USC00511918 2015-02-17 00:00:00 0.01 62
USC00511918 2015-02-18 00:00:00 0.0 63
USC00511918 2015-02-19 00:00:00 0.0 65
USC00511918 2015-02-20 00:00:00 0.0 69
USC00511918 2015-02-21 00:00:00 0.28 63
USC00511918 2015-02-22 00:00:00 0.0 73
USC00511918 2015-02-23 00:00:00 0.0 66
USC00511918 2015-02-24 00:00:00 0.0 63
USC00511918 2015-02-25 00:00:00 0.0 69
USC00511918 2015-02-26 00:00:00 0.0 65
USC00511918 2015-03-03 00:00:00 0.0 75
USC00511918 2015-03-04 00:00:00 0.0 71
USC00511918 2015-03-05 00:00:00 0.17 73
USC00511918 2015-03-06 00:00:00 0.0 67
USC00511918 2015-03-07 00:00:00 0.0 71
USC00511918 2015-03-08 00:00:00 0.0 68
USC00511918 2015-03-09 00:00:00 0.0 69
USC00511918 2015-03-12 00:00:00 0.02 73
USC00511918 2015-03-13 00:00:00 0.0 69
USC00511918 2015-03-14 00:00:00 0.0 71
USC00511918 2015-03-15 00:00:00 0.0 66
USC00511918 2015-03-18 00:00:00 0.0 76
USC00511918 2015-04-03 00:00:00 0.0 77
USC00511918 2015-04-07 00:00:00 0.0 63
USC00511918 2015-04-08 00:00:00 0.0 70
USC00511918 2015-04-09 00:00:00 0.0 64
USC00511918 2015-04-10 00:00:00 0.0 64
USC00511918 2015-04-14 00:00:00 0.1 71
USC00511918 2015-04-15 00:00:00 0.0 70
USC00511918 2015-04-16 00:00:00 0.0 70
USC00511918 2015-04-17 00:00:00 0.0 71
USC00511918 2015-04-21 00:00:00 0.0 73
USC00511918 2015-04-22 00:00:00 0.05 66
USC00511918 2015-04-23 00:00:00 0.0 69
USC00511918 2015-04-24 00:00:00 0.0 69
USC00511918 2015-04-30 00:00:00 0.0 73
USC00511918 2015-05-01 00:00:00 0.0 72
USC00511918 2015-05-05 00:00:00 0.0 72
USC00511918 2015-05-06 00:00:00 0.0 74
USC00511918 2015-05-07 00:00:00 0.0 69
USC00511918 2015-05-08 00:00:00 0.09 75
USC00511918 2015-05-12 00:00:00 0.0 72
USC00511918 2015-05-13 00:00:00 0.0 72
USC00511918 2015-05-14 00:00:00 0.0 79
USC00511918 2015-05-15 00:00:00 0.0 78
USC00511918 2015-05-19 00:00:00 0.0 70
USC00511918 2015-05-20 00:00:00 0.0 77
USC00511918 2015-05-21 00:00:00 0.0 67
USC00511918 2015-05-22 00:00:00 0.0 74
USC00511918 2015-05-27 00:00:00 0.0 67
USC00511918 2015-05-28 00:00:00 0.0 70
USC00511918 2015-05-29 00:00:00 0.0 66
USC00511918 2015-06-01 00:00:00 0.01 70
USC00511918 2015-06-02 00:00:00 0.0 67
USC00511918 2015-06-03 00:00:00 0.0 68
USC00511918 2015-06-04 00:00:00 0.0 68
USC00511918 2015-06-05 00:00:00 0.0 71
USC00511918 2015-06-09 00:00:00 0.0 69
USC00511918 2015-06-12 00:00:00 0.0 66
USC00511918 2015-06-16 00:00:00 0.2 69
USC00511918 2015-06-17 00:00:00 0.0 72
USC00511918 2015-06-18 00:00:00 0.0 72
USC00511918 2015-06-19 00:00:00 0.0 72
USC00511918 2015-06-23 00:00:00 0.0 75
USC00511918 2015-06-24 00:00:00 0.0 73
USC00511918 2015-06-25 00:00:00 0.01 70
USC00511918 2015-06-26 00:00:00 0.01 71
USC00511918 2015-07-09 00:00:00 0.0 76
USC00511918 2015-07-10 00:00:00 0.0 73
USC00511918 2015-07-14 00:00:00 0.0 75
USC00511918 2015-07-15 00:00:00 0.0 71
USC00511918 2015-07-16 00:00:00 0.0 75
USC00511918 2015-07-17 00:00:00 0.0 75
USC00511918 2015-07-22 00:00:00 0.0 77
USC00511918 2015-07-23 00:00:00 0.0 71
USC00511918 2015-07-24 00:00:00 0.0 77
USC00511918 2015-07-28 00:00:00 0.0 74
USC00511918 2015-07-31 00:00:00 0.0 82
USC00511918 2015-08-04 00:00:00 0.0 84
USC00511918 2015-08-05 00:00:00 0.1 76
USC00511918 2015-08-06 00:00:00 0.0 76
USC00511918 2015-08-14 00:00:00 0.0 78
USC00511918 2015-08-20 00:00:00 0.1 75
USC00511918 2015-08-25 00:00:00 1.3 79
USC00511918 2015-08-26 00:00:00 0.8 76
USC00511918 2015-09-01 00:00:00 0.0 78
USC00511918 2015-09-02 00:00:00 0.0 76
USC00511918 2015-09-03 00:00:00 0.2 76
USC00511918 2015-09-04 00:00:00 0.7 73
USC00511918 2015-09-17 00:00:00 0.0 71
USC00511918 2015-09-18 00:00:00 0.0 74
USC00511918 2015-09-22 00:00:00 0.0 76
USC00511918 2015-09-23 00:00:00 0.0 77
USC00511918 2015-09-24 00:00:00 0.0 76
USC00511918 2015-09-25 00:00:00 0.0 77
USC00511918 2015-10-08 00:00:00 0.0 83
USC00511918 2015-10-09 00:00:00 0.0 84
USC00511918 2015-10-12 00:00:00 0.0 73
USC00511918 2015-10-13 00:00:00 0.4 72
USC00511918 2015-10-14 00:00:00 0.0 72
USC00511918 2015-10-15 00:00:00 0.0 72
USC00511918 2015-10-16 00:00:00 0.0 72
USC00511918 2015-10-19 00:00:00 0.0 71
USC00511918 2015-10-20 00:00:00 0.3 75
USC00511918 2015-10-21 00:00:00 0.0 71
USC00511918 2015-10-22 00:00:00 0.15 71
USC00511918 2015-10-25 00:00:00 0.0 74
USC00511918 2015-10-26 00:00:00 0.1 72
USC00511918 2015-10-28 00:00:00 0.0 82
USC00511918 2015-10-29 00:00:00 0.0 68
USC00511918 2015-10-30 00:00:00 0.0 64
USC00516128 MANOA LYON ARBO 785.2, HI US
USC00516128 2010-01-01 00:00:00 0.14 73
USC00516128 2010-01-02 00:00:00 0.0 61
USC00516128 2010-01-03 00:00:00 0.0 76
USC00516128 2010-01-04 00:00:00 0.0 72
USC00516128 2010-01-05 00:00:00 0.0 74
USC00516128 2010-01-06 00:00:00 0.36 71
USC00516128 2010-01-07 00:00:00 0.3 74
USC00516128 2010-01-08 00:00:00 0.0 64
USC00516128 2010-01-09 00:00:00 0.0 67
USC00516128 2010-01-10 00:00:00 0.01 71
USC00516128 2010-01-11 00:00:00 0.14 68
USC00516128 2010-01-12 00:00:00 0.0 68
USC00516128 2010-01-13 00:00:00 0.0 59
USC00516128 2010-01-14 00:00:00 0.0 69
USC00516128 2010-01-15 00:00:00 0.0 67
USC00516128 2010-01-16 00:00:00 0.0 65
USC00516128 2010-01-17 00:00:00 0.0 70
USC00516128 2010-01-18 00:00:00 0.0 76
USC00516128 2010-01-19 00:00:00 0.0 75
USC00516128 2010-01-20 00:00:00 0.0 69
USC00516128 2010-01-21 00:00:00 0.32 71
USC00516128 2010-01-22 00:00:00 0.0 63
USC00516128 2010-01-23 00:00:00 0.0 75
USC00516128 2010-01-24 00:00:00 0.01 76
USC00516128 2010-01-25 00:00:00 0.0 65
USC00516128 2010-01-26 00:00:00 0.03 69
USC00516128 2010-01-27 00:00:00 0.31 65
USC00516128 2010-01-28 00:00:00 0.07 71
USC00516128 2010-01-29 00:00:00 0.1 65
USC00516128 2010-01-30 00:00:00 0.33 69
USC00516128 2010-01-31 00:00:00 1.1 74
USC00516128 2010-02-01 00:00:00 0.01 65
USC00516128 2010-02-02 00:00:00 0.05 69
USC00516128 2010-02-03 00:00:00 0.67 63
USC00516128 2010-02-04 00:00:00 0.0 70
USC00516128 2010-02-05 00:00:00 0.09 66
USC00516128 2010-02-06 00:00:00 0.04 62
USC00516128 2010-02-08 00:00:00 0.0 69
USC00516128 2010-02-09 00:00:00 0.0 72
USC00516128 2010-02-10 00:00:00 0.0 69
USC00516128 2010-02-11 00:00:00 0.0 69
USC00516128 2010-02-12 00:00:00 0.65 66
USC00516128 2010-02-13 00:00:00 0.62 70
USC00516128 2010-02-14 00:00:00 0.02 73
USC00516128 2010-02-15 00:00:00 0.0 73
USC00516128 2010-02-16 00:00:00 0.0 74
USC00516128 2010-02-17 00:00:00 0.02 69
USC00516128 2010-02-18 00:00:00 0.0 65
USC00516128 2010-02-19 00:00:00 0.42 60
USC00516128 2010-02-20 00:00:00 0.55 74
USC00516128 2010-02-23 00:00:00 0.0 71
USC00516128 2010-02-24 00:00:00 0.0 62
USC00516128 2010-02-25 00:00:00 0.0 72

USC00516128 2010-02-26 00:00:00 0.01 71
USC00516128 2010-02-27 00:00:00 0.02 75
USC00516128 2010-02-28 00:00:00 0.2 67
USC00516128 2010-03-01 00:00:00 0.12 66
USC00516128 2010-03-02 00:00:00 0.0 67
USC00516128 2010-03-03 00:00:00 0.12 66
USC00516128 2010-03-04 00:00:00 1.41 65
USC00516128 2010-03-05 00:00:00 1.33 65
USC00516128 2010-03-06 00:00:00 0.9 68
USC00516128 2010-03-07 00:00:00 0.35 69
USC00516128 2010-03-08 00:00:00 0.7 65
USC00516128 2010-03-09 00:00:00 0.24 72
USC00516128 2010-03-10 00:00:00 0.14 66
USC00516128 2010-03-11 00:00:00 0.68 71
USC00516128 2010-03-12 00:00:00 0.03 66
USC00516128 2010-03-13 00:00:00 0.1 74
USC00516128 2010-03-14 00:00:00 0.1 74
USC00516128 2010-03-15 00:00:00 0.83 66
USC00516128 2010-03-16 00:00:00 2.2 69
USC00516128 2010-03-17 00:00:00 1.32 65
USC00516128 2010-03-18 00:00:00 0.11 70
USC00516128 2010-03-19 00:00:00 0.01 67
USC00516128 2010-03-20 00:00:00 0.18 65
USC00516128 2010-03-21 00:00:00 1.0 74
USC00516128 2010-03-22 00:00:00 0.0 77
USC00516128 2010-03-23 00:00:00 0.0 74
USC00516128 2010-03-24 00:00:00 0.07 71
USC00516128 2010-03-25 00:00:00 0.35 67
USC00516128 2010-03-26 00:00:00 0.91 71
USC00516128 2010-03-27 00:00:00 0.0 72
USC00516128 2010-03-28 00:00:00 0.0 74
USC00516128 2010-03-29 00:00:00 0.02 70
USC00516128 2010-03-30 00:00:00 0.49 68
USC00516128 2010-03-31 00:00:00 0.08 70
USC00516128 2010-04-01 00:00:00 0.04 73
USC00516128 2010-04-02 00:00:00 0.19 73
USC00516128 2010-04-03 00:00:00 0.92 67
USC00516128 2010-04-04 00:00:00 2.56 67
USC00516128 2010-04-05 00:00:00 0.87 69
USC00516128 2010-04-06 00:00:00 1.83 69
USC00516128 2010-04-07 00:00:00 1.43 68
USC00516128 2010-04-08 00:00:00 0.35 76
USC00516128 2010-04-09 00:00:00 0.5 68
USC00516128 2010-04-10 00:00:00 0.4 67
USC00516128 2010-04-11 00:00:00 1.04 73
USC00516128 2010-04-12 00:00:00 0.02 68
USC00516128 2010-04-13 00:00:00 0.93 71
USC00516128 2010-04-14 00:00:00 0.0 68
USC00516128 2010-04-15 00:00:00 0.0 67
USC00516128 2010-04-16 00:00:00 0.06 65
USC00516128 2010-04-17 00:00:00 0.03 70
USC00516128 2010-04-18 00:00:00 0.03 71
USC00516128 2010-04-19 00:00:00 0.01 71
USC00516128 2010-04-20 00:00:00 0.68 71
USC00516128 2010-04-21 00:00:00 0.17 71
USC00516128 2010-04-24 00:00:00 0.17 75
USC00516128 2010-04-25 00:00:00 0.08 78
USC00516128 2010-04-26 00:00:00 0.0 72
USC00516128 2010-04-27 00:00:00 0.0 75
USC00516128 2010-04-28 00:00:00 0.49 76
USC00516128 2010-04-29 00:00:00 1.29 69
USC00516128 2010-04-30 00:00:00 0.92 72
USC00516128 2010-05-01 00:00:00 0.31 73
USC00516128 2010-05-02 00:00:00 0.37 74
USC00516128 2010-05-03 00:00:00 0.14 75
USC00516128 2010-05-04 00:00:00 0.21 77
USC00516128 2010-05-05 00:00:00 0.01 72
USC00516128 2010-05-06 00:00:00 0.08 71
USC00516128 2010-05-07 00:00:00 0.24 69
USC00516128 2010-05-08 00:00:00 0.06 75
USC00516128 2010-05-09 00:00:00 0.0 74
USC00516128 2010-05-10 00:00:00 0.55 71
USC00516128 2010-05-13 00:00:00 0.32 70
USC00516128 2010-05-14 00:00:00 0.0 73
USC00516128 2010-05-15 00:00:00 0.25 73
USC00516128 2010-05-16 00:00:00 0.61 73
USC00516128 2010-05-17 00:00:00 0.1 71
USC00516128 2010-05-18 00:00:00 0.0 71
USC00516128 2010-05-19 00:00:00 0.0 71
USC00516128 2010-05-20 00:00:00 0.67 71
USC00516128 2010-05-21 00:00:00 0.38 71
USC00516128 2010-05-22 00:00:00 0.01 77
USC00516128 2010-05-25 00:00:00 0.83 71
USC00516128 2010-05-26 00:00:00 0.27 71
USC00516128 2010-05-27 00:00:00 0.05 72
USC00516128 2010-05-28 00:00:00 0.0 74
USC00516128 2010-06-01 00:00:00 0.08 70
USC00516128 2010-06-02 00:00:00 0.0 78
USC00516128 2010-06-03 00:00:00 0.1 73
USC00516128 2010-06-04 00:00:00 0.01 68
USC00516128 2010-06-05 00:00:00 0.09 79
USC00516128 2010-06-06 00:00:00 0.13 74
USC00516128 2010-06-07 00:00:00 0.44 75
USC00516128 2010-06-08 00:00:00 0.27 71
USC00516128 2010-06-09 00:00:00 0.0 75
USC00516128 2010-06-17 00:00:00 0.05 73
USC00516128 2010-06-23 00:00:00 0.04 72
USC00516128 2010-06-24 00:00:00 0.26 72
USC00516128 2010-06-25 00:00:00 0.79 70
USC00516128 2010-06-26 00:00:00 0.88 69
USC00516128 2010-06-27 00:00:00 0.37 73
USC00516128 2010-06-28 00:00:00 0.16 71
USC00516128 2010-06-29 00:00:00 0.02 73
USC00516128 2010-06-30 00:00:00 0.71 72
USC00516128 2010-07-01 00:00:00 0.44 70
USC00516128 2010-07-02 00:00:00 0.7 69
USC00516128 2010-07-03 00:00:00 1.81 69
USC00516128 2010-07-04 00:00:00 0.44 72
USC00516128 2010-07-05 00:00:00 0.14 72
USC00516128 2010-07-06 00:00:00 1.01 69
USC00516128 2010-07-07 00:00:00 1.05 69
USC00516128 2010-07-08 00:00:00 0.9 69
USC00516128 2010-07-09 00:00:00 0.75 68
USC00516128 2010-07-10 00:00:00 0.75 68
USC00516128 2010-07-11 00:00:00 0.31 71
USC00516128 2010-07-12 00:00:00 0.25 70
USC00516128 2010-07-13 00:00:00 0.0 72
USC00516128 2010-07-14 00:00:00 0.48 69
USC00516128 2010-07-15 00:00:00 0.24 68
USC00516128 2010-07-16 00:00:00 0.19 70
USC00516128 2010-07-17 00:00:00 0.46 70
USC00516128 2010-07-18 00:00:00 2.14 74
USC00516128 2010-07-19 00:00:00 0.35 69
USC00516128 2010-07-20 00:00:00 1.23 70
USC00516128 2010-07-21 00:00:00 0.05 72
USC00516128 2010-07-22 00:00:00 0.07 72
USC00516128 2010-07-23 00:00:00 1.0 71
USC00516128 2010-07-24 00:00:00 0.04 73
USC00516128 2010-07-25 00:00:00 0.0 74
USC00516128 2010-07-26 00:00:00 0.0 73
USC00516128 2010-07-27 00:00:00 0.1 70
USC00516128 2010-07-28 00:00:00 0.02 71
USC00516128 2010-07-29 00:00:00 0.38 72
USC00516128 2010-07-30 00:00:00 0.29 69
USC00516128 2010-07-31 00:00:00 0.05 73
USC00516128 2010-08-01 00:00:00 0.52 71
USC00516128 2010-08-02 00:00:00 1.45 70
USC00516128 2010-08-03 00:00:00 0.58 70
USC00516128 2010-08-04 00:00:00 1.89 69
USC00516128 2010-08-05 00:00:00 0.93 69
USC00516128 2010-08-06 00:00:00 0.35 70
USC00516128 2010-08-07 00:00:00 0.18 72
USC00516128 2010-08-08 00:00:00 0.82 71
USC00516128 2010-08-09 00:00:00 0.09 72
USC00516128 2010-08-10 00:00:00 0.03 72
USC00516128 2010-08-11 00:00:00 0.13 69
USC00516128 2010-08-12 00:00:00 0.03 71
USC00516128 2010-08-13 00:00:00 0.14 71
USC00516128 2010-08-14 00:00:00 0.0 71
USC00516128 2010-08-15 00:00:00 0.0 72
USC00516128 2010-08-16 00:00:00 0.42 69
USC00516128 2010-08-17 00:00:00 0.88 69
USC00516128 2010-08-18 00:00:00 0.08 72
USC00516128 2010-08-19 00:00:00 0.12 74
USC00516128 2010-08-20 00:00:00 0.24 71
USC00516128 2010-08-21 00:00:00 0.06 72
USC00516128 2010-08-22 00:00:00 0.02 71
USC00516128 2010-08-23 00:00:00 0.06 73
USC00516128 2010-08-24 00:00:00 0.41 70
USC00516128 2010-08-25 00:00:00 0.45 69
USC00516128 2010-08-26 00:00:00 0.61 71
USC00516128 2010-08-27 00:00:00 1.13 73
USC00516128 2010-08-28 00:00:00 0.41 73
USC00516128 2010-08-29 00:00:00 1.0 71
USC00516128 2010-08-30 00:00:00 0.18 73
USC00516128 2010-08-31 00:00:00 0.21 70
USC00516128 2010-09-01 00:00:00 0.21 69
USC00516128 2010-09-02 00:00:00 0.54 72
USC00516128 2010-09-03 00:00:00 0.52 69
USC00516128 2010-09-04 00:00:00 0.32 68
USC00516128 2010-09-05 00:00:00 0.07 72
USC00516128 2010-09-06 00:00:00 0.38 68
USC00516128 2010-09-07 00:00:00 1.51 69
USC00516128 2010-09-08 00:00:00 0.28 70
USC00516128 2010-09-09 00:00:00 0.01 72
USC00516128 2010-09-10 00:00:00 0.18 71
USC00516128 2010-09-11 00:00:00 0.24 74
USC00516128 2010-09-12 00:00:00 0.0 73
USC00516128 2010-09-13 00:00:00 0.0 72
USC00516128 2010-09-14 00:00:00 0.27 74
USC00516128 2010-09-15 00:00:00 0.04 72
USC00516128 2010-09-16 00:00:00 0.21 72
USC00516128 2010-09-17 00:00:00 0.0 73
USC00516128 2010-09-18 00:00:00 0.19 71
USC00516128 2010-09-19 00:00:00 0.58 74
USC00516128 2010-09-20 00:00:00 0.26 74
USC00516128 2010-09-21 00:00:00 0.04 73
USC00516128 2010-09-22 00:00:00 0.42 72
USC00516128 2010-09-23 00:00:00 0.86 73
USC00516128 2010-09-24 00:00:00 0.0 74
USC00516128 2010-09-25 00:00:00 0.57 71
USC00516128 2010-09-26 00:00:00 0.0 72
USC00516128 2010-09-27 00:00:00 0.0 72
USC00516128 2010-09-28 00:00:00 0.0 77
USC00516128 2010-09-29 00:00:00 0.0 72
USC00516128 2010-09-30 00:00:00 1.18 70
USC00516128 2010-10-01 00:00:00 3.14 73
USC00516128 2010-10-02 00:00:00 1.27 73
USC00516128 2010-10-03 00:00:00 0.03 73
USC00516128 2010-10-04 00:00:00 0.24 71
USC00516128 2010-10-05 00:00:00 0.21 76
USC00516128 2010-10-06 00:00:00 0.0 74
USC00516128 2010-10-07 00:00:00 0.0 73
USC00516128 2010-10-08 00:00:00 0.0 74
USC00516128 2010-10-09 00:00:00 0.0 72
USC00516128 2010-10-10 00:00:00 0.0 73
USC00516128 2010-10-11 00:00:00 0.41 71
USC00516128 2010-10-12 00:00:00 0.25 71
USC00516128 2010-10-13 00:00:00 0.05 71
USC00516128 2010-10-14 00:00:00 0.04 72
USC00516128 2010-10-15 00:00:00 0.01 72
USC00516128 2010-10-16 00:00:00 0.08 72
USC00516128 2010-10-17 00:00:00 0.21 74
USC00516128 2010-10-18 00:00:00 0.07 74
USC00516128 2010-10-19 00:00:00 4.01 69
USC00516128 2010-10-20 00:00:00 0.0 75
USC00516128 2010-10-21 00:00:00 0.39 73
USC00516128 2010-10-22 00:00:00 0.21 74
USC00516128 2010-10-23 00:00:00 0.0 73
USC00516128 2010-10-24 00:00:00 0.0 74
USC00516128 2010-10-25 00:00:00 0.0 74
USC00516128 2010-10-26 00:00:00 0.68 71
USC00516128 2010-10-27 00:00:00 1.06 71
USC00516128 2010-10-28 00:00:00 0.7 76
USC00516128 2010-10-29 00:00:00 0.24 70
USC00516128 2010-10-30 00:00:00 1.9 70
USC00516128 2010-10-31 00:00:00 0.28 74
USC00516128 2010-11-01 00:00:00 2.03 72
USC00516128 2010-11-02 00:00:00 0.47 75
USC00516128 2010-11-03 00:00:00 0.06 68
USC00516128 2010-11-04 00:00:00 3.79 69
USC00516128 2010-11-05 00:00:00 2.64 71
USC00516128 2010-11-06 00:00:00 4.56 73
USC00516128 2010-11-07 00:00:00 0.54 72
USC00516128 2010-11-08 00:00:00 0.01 73
USC00516128 2010-11-09 00:00:00 0.01 69
USC00516128 2010-11-10 00:00:00 0.76 69
USC00516128 2010-11-11 00:00:00 0.15 80
USC00516128 2010-11-12 00:00:00 0.1 72
USC00516128 2010-11-13 00:00:00 0.21 79
USC00516128 2010-11-14 00:00:00 0.31 77
USC00516128 2010-11-15 00:00:00 0.6 71
USC00516128 2010-11-16 00:00:00 0.62 73
USC00516128 2010-11-17 00:00:00 0.01 65
USC00516128 2010-11-18 00:00:00 0.0 68
USC00516128 2010-11-19 00:00:00 0.22 67
USC00516128 2010-11-20 00:00:00 0.0 69
USC00516128 2010-11-21 00:00:00 0.08 71
USC00516128 2010-11-22 00:00:00 0.0 68
USC00516128 2010-11-23 00:00:00 0.0 68
USC00516128 2010-11-24 00:00:00 0.1 71
USC00516128 2010-11-25 00:00:00 0.46 73
USC00516128 2010-11-26 00:00:00 0.1 71
USC00516128 2010-11-27 00:00:00 0.15 69
USC00516128 2010-11-28 00:00:00 1.09 69
USC00516128 2010-11-29 00:00:00 0.64 69
USC00516128 2010-11-30 00:00:00 0.06 71
USC00516128 2010-12-01 00:00:00 1.48 71
USC00516128 2010-12-02 00:00:00 0.18 70
USC00516128 2010-12-03 00:00:00 1.59 67
USC00516128 2010-12-04 00:00:00 0.19 77
USC00516128 2010-12-05 00:00:00 0.0 69
USC00516128 2010-12-06 00:00:00 0.0 61
USC00516128 2010-12-07 00:00:00 0.0 62
USC00516128 2010-12-08 00:00:00 0.0 63
USC00516128 2010-12-09 00:00:00 0.0 73
USC00516128 2010-12-10 00:00:00 1.86 64
USC00516128 2010-12-11 00:00:00 0.58 67
USC00516128 2010-12-12 00:00:00 0.45 69
USC00516128 2010-12-13 00:00:00 0.18 80
USC00516128 2010-12-14 00:00:00 0.0 71
USC00516128 2010-12-15 00:00:00 0.0 73
USC00516128 2010-12-16 00:00:00 0.0 65
USC00516128 2010-12-17 00:00:00 0.0 68
USC00516128 2010-12-18 00:00:00 0.0 68
USC00516128 2010-12-19 00:00:00 2.15 69
USC00516128 2010-12-20 00:00:00 5.04 72
USC00516128 2010-12-21 00:00:00 1.44 69
USC00516128 2010-12-22 00:00:00 0.04 69
USC00516128 2010-12-23 00:00:00 0.0 67
USC00516128 2010-12-24 00:00:00 0.15 69
USC00516128 2010-12-25 00:00:00 0.0 73
USC00516128 2010-12-26 00:00:00 0.99 71
USC00516128 2010-12-27 00:00:00 0.02 71
USC00516128 2010-12-28 00:00:00 0.04 70
USC00516128 2010-12-29 00:00:00 0.19 71
USC00516128 2010-12-30 00:00:00 0.3 70
USC00516128 2010-12-31 00:00:00 0.01 75
USC00516128 2011-01-01 00:00:00 0.07 74
USC00516128 2011-01-02 00:00:00 0.03 70
USC00516128 2011-01-03 00:00:00 0.35 69
USC00516128 2011-01-04 00:00:00 0.05 70
USC00516128 2011-01-05 00:00:00 0.09 67
USC00516128 2011-01-06 00:00:00 0.22 67
USC00516128 2011-01-07 00:00:00 0.0 65
USC00516128 2011-01-08 00:00:00 0.0 66
USC00516128 2011-01-09 00:00:00 0.0 58
USC00516128 2011-01-10 00:00:00 0.0 64
USC00516128 2011-01-11 00:00:00 0.09 58
USC00516128 2011-01-12 00:00:00 0.54 68
USC00516128 2011-01-13 00:00:00 2.27 65
USC00516128 2011-01-14 00:00:00 0.12 72
USC00516128 2011-01-15 00:00:00 0.02 66
USC00516128 2011-01-16 00:00:00 0.0 68
USC00516128 2011-01-17 00:00:00 0.07 70
USC00516128 2011-01-18 00:00:00 0.0 62
USC00516128 2011-01-19 00:00:00 0.03 62
USC00516128 2011-01-20 00:00:00 0.01 71
USC00516128 2011-01-21 00:00:00 0.43 70
USC00516128 2011-01-22 00:00:00 0.02 69
USC00516128 2011-01-23 00:00:00 0.19 67
USC00516128 2011-01-24 00:00:00 0.05 69
USC00516128 2011-01-25 00:00:00 0.0 61
USC00516128 2011-01-26 00:00:00 0.0 67
USC00516128 2011-01-27 00:00:00 0.0 68
USC00516128 2011-01-28 00:00:00 0.0 69
USC00516128 2011-01-29 00:00:00 0.18 64
USC00516128 2011-01-30 00:00:00 0.0 62
USC00516128 2011-01-31 00:00:00 0.2 66
USC00516128 2011-02-01 00:00:00 0.0 69
USC00516128 2011-02-02 00:00:00 0.0 66
USC00516128 2011-02-03 00:00:00 0.0 65
USC00516128 2011-02-04 00:00:00 0.0 61
USC00516128 2011-02-05 00:00:00 0.0 62
USC00516128 2011-02-06 00:00:00 0.0 72
USC00516128 2011-02-07 00:00:00 1.11 67
USC00516128 2011-02-08 00:00:00 1.49 70
USC00516128 2011-02-11 00:00:00 0.13 68
USC00516128 2011-02-12 00:00:00 0.1 69
USC00516128 2011-02-13 00:00:00 0.1 66
USC00516128 2011-02-14 00:00:00 0.0 67
USC00516128 2011-02-15 00:00:00 0.0 67
USC00516128 2011-02-16 00:00:00 0.2 71
USC00516128 2011-02-17 00:00:00 0.0 68
USC00516128 2011-02-18 00:00:00 0.01 77
USC00516128 2011-02-19 00:00:00 0.0 75
USC00516128 2011-02-20 00:00:00 1.79 76
USC00516128 2011-02-21 00:00:00 0.0 75
USC00516128 2011-02-22 00:00:00 0.08 72
USC00516128 2011-02-23 00:00:00 0.01 70
USC00516128 2011-02-24 00:00:00 0.6 66
USC00516128 2011-02-25 00:00:00 0.01 64
USC00516128 2011-02-26 00:00:00 0.0 78
USC00516128 2011-02-27 00:00:00 0.16 75
USC00516128 2011-02-28 00:00:00 0.0 75
USC00516128 2011-03-01 00:00:00 0.22 68
USC00516128 2011-03-02 00:00:00 0.0 69
USC00516128 2011-03-03 00:00:00 0.0 72
USC00516128 2011-03-04 00:00:00 0.94 69
USC00516128 2011-03-05 00:00:00 0.29 69
USC00516128 2011-03-06 00:00:00 0.24 69
USC00516128 2011-03-07 00:00:00 0.29 70
USC00516128 2011-03-08 00:00:00 1.11 70
USC00516128 2011-03-09 00:00:00 1.5 67
USC00516128 2011-03-10 00:00:00 0.82 68
USC00516128 2011-03-11 00:00:00 0.47 67
USC00516128 2011-03-12 00:00:00 0.0 73
USC00516128 2011-03-13 00:00:00 0.0 77
USC00516128 2011-03-14 00:00:00 0.0 71
USC00516128 2011-03-15 00:00:00 0.0 70
USC00516128 2011-03-16 00:00:00 0.0 71
USC00516128 2011-03-17 00:00:00 0.16 69
USC00516128 2011-03-18 00:00:00 0.15 68
USC00516128 2011-03-19 00:00:00 0.46 69
USC00516128 2011-03-20 00:00:00 1.16 67
USC00516128 2011-03-21 00:00:00 0.0 69
USC00516128 2011-03-22 00:00:00 0.85 67
USC00516128 2011-03-23 00:00:00 0.06 69
USC00516128 2011-03-24 00:00:00 1.35 72
USC00516128 2011-03-25 00:00:00 0.13 71
USC00516128 2011-03-26 00:00:00 0.62 67
USC00516128 2011-03-27 00:00:00 0.38 74
USC00516128 2011-03-28 00:00:00 0.26 68
USC00516128 2011-03-29 00:00:00 0.11 68

USC00516128 2011-03-30 00:00:00 0.18 74
USC00516128 2011-03-31 00:00:00 0.0 72
USC00516128 2011-04-01 00:00:00 1.16 67
USC00516128 2011-04-02 00:00:00 1.15 74
USC00516128 2011-04-03 00:00:00 0.59 71
USC00516128 2011-04-04 00:00:00 0.05 73
USC00516128 2011-04-05 00:00:00 0.42 69
USC00516128 2011-04-06 00:00:00 0.18 69
USC00516128 2011-04-07 00:00:00 3.35 71
USC00516128 2011-04-08 00:00:00 0.34 71
USC00516128 2011-04-09 00:00:00 0.03 75
USC00516128 2011-04-10 00:00:00 0.09 72
USC00516128 2011-04-11 00:00:00 0.35 70
USC00516128 2011-04-12 00:00:00 0.25 72
USC00516128 2011-04-13 00:00:00 0.0 69
USC00516128 2011-04-14 00:00:00 0.08 71
USC00516128 2011-04-15 00:00:00 0.01 73
USC00516128 2011-04-16 00:00:00 0.38 81
USC00516128 2011-04-17 00:00:00 0.0 77
USC00516128 2011-04-18 00:00:00 0.28 73
USC00516128 2011-04-19 00:00:00 0.0 73
USC00516128 2011-04-21 00:00:00 0.0 78
USC00516128 2011-04-22 00:00:00 0.0 82
USC00516128 2011-04-23 00:00:00 0.0 78
USC00516128 2011-04-24 00:00:00 0.04 71
USC00516128 2011-04-25 00:00:00 0.23 69
USC00516128 2011-04-26 00:00:00 0.46 71
USC00516128 2011-04-27 00:00:00 0.09 71
USC00516128 2011-04-28 00:00:00 0.34 70
USC00516128 2011-04-29 00:00:00 0.9 71
USC00516128 2011-05-01 00:00:00 1.21 72
USC00516128 2011-05-02 00:00:00 0.35 73
USC00516128 2011-05-03 00:00:00 3.05 70
USC00516128 2011-05-05 00:00:00 0.34 70
USC00516128 2011-05-06 00:00:00 2.07 67
USC00516128 2011-05-07 00:00:00 1.91 67
USC00516128 2011-05-08 00:00:00 2.26 70
USC00516128 2011-05-09 00:00:00 0.31 73
USC00516128 2011-05-10 00:00:00 0.04 73
USC00516128 2011-05-11 00:00:00 0.74 72
USC00516128 2011-05-12 00:00:00 0.1 73
USC00516128 2011-05-13 00:00:00 0.29 71
USC00516128 2011-05-14 00:00:00 0.06 72
USC00516128 2011-05-15 00:00:00 0.0 72
USC00516128 2011-05-16 00:00:00 0.01 72
USC00516128 2011-05-17 00:00:00 0.03 70
USC00516128 2011-05-18 00:00:00 0.19 75
USC00516128 2011-05-19 00:00:00 0.15 70
USC00516128 2011-05-20 00:00:00 0.0 74
USC00516128 2011-05-21 00:00:00 0.01 71
USC00516128 2011-05-22 00:00:00 0.71 69
USC00516128 2011-05-23 00:00:00 0.17 72
USC00516128 2011-05-24 00:00:00 0.02 71
USC00516128 2011-05-25 00:00:00 0.09 71
USC00516128 2011-05-26 00:00:00 0.0 72
USC00516128 2011-05-27 00:00:00 0.09 71
USC00516128 2011-05-28 00:00:00 0.01 72
USC00516128 2011-05-29 00:00:00 0.17 70
USC00516128 2011-05-30 00:00:00 0.16 71
USC00516128 2011-05-31 00:00:00 0.15 70
USC00516128 2011-06-01 00:00:00 0.61 69
USC00516128 2011-06-02 00:00:00 0.22 72
USC00516128 2011-06-03 00:00:00 2.0 66
USC00516128 2011-06-04 00:00:00 2.45 67
USC00516128 2011-06-05 00:00:00 0.76 71
USC00516128 2011-06-06 00:00:00 0.1 71
USC00516128 2011-06-07 00:00:00 0.19 72
USC00516128 2011-06-08 00:00:00 0.23 72
USC00516128 2011-06-09 00:00:00 0.1 71
USC00516128 2011-06-10 00:00:00 0.11 71
USC00516128 2011-06-11 00:00:00 0.17 71
USC00516128 2011-06-12 00:00:00 1.5 69
USC00516128 2011-06-13 00:00:00 0.41 68
USC00516128 2011-06-14 00:00:00 0.14 71
USC00516128 2011-06-15 00:00:00 0.01 73
USC00516128 2011-06-16 00:00:00 0.83 72
USC00516128 2011-06-17 00:00:00 0.18 74
USC00516128 2011-06-18 00:00:00 0.07 70
USC00516128 2011-06-19 00:00:00 1.84 72
USC00516128 2011-06-20 00:00:00 0.91 71
USC00516128 2011-06-21 00:00:00 1.03 71
USC00516128 2011-06-22 00:00:00 1.65 70
USC00516128 2011-06-23 00:00:00 0.68 70
USC00516128 2011-06-24 00:00:00 1.16 69
USC00516128 2011-06-25 00:00:00 0.06 74
USC00516128 2011-06-26 00:00:00 0.29 69
USC00516128 2011-06-27 00:00:00 0.98 72
USC00516128 2011-06-28 00:00:00 0.25 70
USC00516128 2011-06-29 00:00:00 0.06 72
USC00516128 2011-06-30 00:00:00 0.0 72
USC00516128 2011-07-01 00:00:00 0.15 70
USC00516128 2011-07-02 00:00:00 0.1 73
USC00516128 2011-07-03 00:00:00 0.31 71
USC00516128 2011-07-04 00:00:00 0.17 70
USC00516128 2011-07-05 00:00:00 0.24 71
USC00516128 2011-07-06 00:00:00 0.15 69
USC00516128 2011-07-11 00:00:00 0.12 70
USC00516128 2011-07-14 00:00:00 0.27 71
USC00516128 2011-07-15 00:00:00 0.4 70
USC00516128 2011-07-16 00:00:00 0.3 74
USC00516128 2011-07-17 00:00:00 0.66 74
USC00516128 2011-07-18 00:00:00 0.18 72
USC00516128 2011-07-19 00:00:00 0.1 76
USC00516128 2011-07-20 00:00:00 0.72 69
USC00516128 2011-07-21 00:00:00 0.0 73
USC00516128 2011-07-22 00:00:00 1.34 70
USC00516128 2011-07-23 00:00:00 0.11 71
USC00516128 2011-07-24 00:00:00 0.3 72
USC00516128 2011-07-25 00:00:00 0.23 74
USC00516128 2011-07-26 00:00:00 0.35 74
USC00516128 2011-07-27 00:00:00 2.12 75
USC00516128 2011-07-28 00:00:00 0.02 73
USC00516128 2011-07-29 00:00:00 0.7 71
USC00516128 2011-08-01 00:00:00 0.0 73
USC00516128 2011-08-02 00:00:00 0.26 70
USC00516128 2011-08-03 00:00:00 0.17 71
USC00516128 2011-08-04 00:00:00 0.26 77
USC00516128 2011-08-05 00:00:00 0.51 77
USC00516128 2011-08-06 00:00:00 0.04 74
USC00516128 2011-08-07 00:00:00 0.18 76
USC00516128 2011-08-08 00:00:00 0.01 74
USC00516128 2011-08-09 00:00:00 1.25 73
USC00516128 2011-08-10 00:00:00 0.03 74
USC00516128 2011-08-11 00:00:00 0.16 73
USC00516128 2011-08-12 00:00:00 0.07 73
USC00516128 2011-08-13 00:00:00 0.01 73
USC00516128 2011-08-14 00:00:00 0.53 74
USC00516128 2011-08-15 00:00:00 0.1 74
USC00516128 2011-08-16 00:00:00 0.13 72
USC00516128 2011-08-17 00:00:00 0.55 74
USC00516128 2011-08-18 00:00:00 0.15 70
USC00516128 2011-08-19 00:00:00 0.08 71
USC00516128 2011-08-20 00:00:00 0.36 71
USC00516128 2011-08-23 00:00:00 0.02 73
USC00516128 2011-08-24 00:00:00 0.29 71
USC00516128 2011-08-25 00:00:00 0.39 71
USC00516128 2011-08-26 00:00:00 0.2 71
USC00516128 2011-08-27 00:00:00 0.6 70
USC00516128 2011-08-28 00:00:00 0.41 71
USC00516128 2011-08-29 00:00:00 1.11 70
USC00516128 2011-08-30 00:00:00 0.56 72
USC00516128 2011-08-31 00:00:00 0.57 74
USC00516128 2011-09-01 00:00:00 0.25 75
USC00516128 2011-09-02 00:00:00 0.3 76
USC00516128 2011-09-03 00:00:00 0.0 72
USC00516128 2011-09-04 00:00:00 0.18 80
USC00516128 2011-09-05 00:00:00 0.02 70
USC00516128 2011-09-06 00:00:00 0.11 75
USC00516128 2011-09-07 00:00:00 0.0 74
USC00516128 2011-09-08 00:00:00 0.0 77
USC00516128 2011-09-09 00:00:00 0.09 75
USC00516128 2011-09-10 00:00:00 0.25 76
USC00516128 2011-09-11 00:00:00 0.21 71
USC00516128 2011-09-12 00:00:00 0.38 70
USC00516128 2011-09-13 00:00:00 0.5 72
USC00516128 2011-09-14 00:00:00 0.19 73
USC00516128 2011-09-15 00:00:00 0.41 74
USC00516128 2011-09-16 00:00:00 0.95 73
USC00516128 2011-09-17 00:00:00 0.21 70
USC00516128 2011-09-18 00:00:00 0.88 71
USC00516128 2011-09-19 00:00:00 0.18 73
USC00516128 2011-09-20 00:00:00 0.1 72
USC00516128 2011-09-21 00:00:00 0.19 73
USC00516128 2011-09-22 00:00:00 0.21 72
USC00516128 2011-09-23 00:00:00 0.39 71
USC00516128 2011-09-24 00:00:00 0.01 76
USC00516128 2011-09-25 00:00:00 0.0 73
USC00516128 2011-09-26 00:00:00 0.0 76
USC00516128 2011-09-27 00:00:00 0.0 73
USC00516128 2011-09-28 00:00:00 0.1 73
USC00516128 2011-09-29 00:00:00 0.09 73
USC00516128 2011-09-30 00:00:00 0.0 75
USC00516128 2011-10-01 00:00:00 0.0 72
USC00516128 2011-10-02 00:00:00 0.03 71
USC00516128 2011-10-03 00:00:00 0.0 74
USC00516128 2011-10-04 00:00:00 0.57 71
USC00516128 2011-10-05 00:00:00 0.06 76
USC00516128 2011-10-06 00:00:00 0.65 73
USC00516128 2011-10-07 00:00:00 0.44 77
USC00516128 2011-10-14 00:00:00 0.57 72
USC00516128 2011-10-15 00:00:00 1.72 77
USC00516128 2011-10-16 00:00:00 0.0 77
USC00516128 2011-10-17 00:00:00 0.43 70
USC00516128 2011-10-18 00:00:00 0.44 70
USC00516128 2011-10-19 00:00:00 0.29 72
USC00516128 2011-10-20 00:00:00 0.22 68
USC00516128 2011-10-21 00:00:00 0.46 71
USC00516128 2011-10-26 00:00:00 0.03 74
USC00516128 2011-10-29 00:00:00 0.01 69
USC00516128 2011-10-30 00:00:00 0.3 71
USC00516128 2011-10-31 00:00:00 0.76 70
USC00516128 2011-11-01 00:00:00 2.24 73
USC00516128 2011-11-02 00:00:00 0.93 71
USC00516128 2011-11-03 00:00:00 0.58 70
USC00516128 2011-11-04 00:00:00 1.06 71
USC00516128 2011-11-05 00:00:00 0.17 69
USC00516128 2011-11-06 00:00:00 0.1 73
USC00516128 2011-11-07 00:00:00 0.11 71
USC00516128 2011-11-08 00:00:00 0.27 73
USC00516128 2011-11-09 00:00:00 0.28 71
USC00516128 2011-11-10 00:00:00 0.17 71
USC00516128 2011-11-11 00:00:00 1.96 68
USC00516128 2011-11-12 00:00:00 0.42 67
USC00516128 2011-11-13 00:00:00 0.07 70
USC00516128 2011-11-14 00:00:00 0.07 71
USC00516128 2011-11-15 00:00:00 0.0 75
USC00516128 2011-11-16 00:00:00 0.0 71
USC00516128 2011-11-17 00:00:00 0.08 71
USC00516128 2011-11-18 00:00:00 0.03 72
USC00516128 2011-11-19 00:00:00 0.29 76
USC00516128 2011-11-20 00:00:00 0.4 70
USC00516128 2011-11-21 00:00:00 1.15 72
USC00516128 2011-11-22 00:00:00 1.13 69
USC00516128 2011-11-23 00:00:00 0.04 70
USC00516128 2011-11-24 00:00:00 0.03 75
USC00516128 2011-11-25 00:00:00 0.21 67
USC00516128 2011-11-26 00:00:00 0.0 71
USC00516128 2011-11-27 00:00:00 0.16 70
USC00516128 2011-11-28 00:00:00 0.01 71
USC00516128 2011-11-29 00:00:00 0.1 67
USC00516128 2011-11-30 00:00:00 0.32 68
USC00516128 2011-12-01 00:00:00 0.16 71
USC00516128 2011-12-02 00:00:00 0.46 73
USC00516128 2011-12-03 00:00:00 0.11 71
USC00516128 2011-12-04 00:00:00 0.03 71
USC00516128 2011-12-05 00:00:00 0.22 68
USC00516128 2011-12-06 00:00:00 0.12 67
USC00516128 2011-12-07 00:00:00 0.26 70
USC00516128 2011-12-08 00:00:00 0.53 67
USC00516128 2011-12-11 00:00:00 1.35 71
USC00516128 2011-12-12 00:00:00 1.71 69
USC00516128 2011-12-13 00:00:00 6.42 69
USC00516128 2011-12-14 00:00:00 1.37 68
USC00516128 2011-12-15 00:00:00 1.18 69
USC00516128 2011-12-16 00:00:00 1.09 69
USC00516128 2011-12-17 00:00:00 0.63 67
USC00516128 2011-12-18 00:00:00 0.3 69
USC00516128 2011-12-19 00:00:00 0.87 68
USC00516128 2011-12-20 00:00:00 0.16 70
USC00516128 2011-12-21 00:00:00 1.52 68
USC00516128 2011-12-22 00:00:00 0.27 69
USC00516128 2011-12-23 00:00:00 0.42 71
USC00516128 2011-12-24 00:00:00 0.8 65
USC00516128 2011-12-25 00:00:00 0.58 69
USC00516128 2011-12-26 00:00:00 0.05 69
USC00516128 2011-12-27 00:00:00 0.06 69
USC00516128 2011-12-28 00:00:00 0.06 69
USC00516128 2011-12-29 00:00:00 0.0 70
USC00516128 2011-12-30 00:00:00 0.05 73
USC00516128 2011-12-31 00:00:00 0.25 67
USC00516128 2012-01-01 00:00:00 0.01 71
USC00516128 2012-01-02 00:00:00 0.0 64
USC00516128 2012-01-03 00:00:00 0.0 70
USC00516128 2012-01-04 00:00:00 0.1 71
USC00516128 2012-01-05 00:00:00 0.2 70
USC00516128 2012-01-06 00:00:00 0.0 72
USC00516128 2012-01-10 00:00:00 0.08 69
USC00516128 2012-01-11 00:00:00 0.1 71
USC00516128 2012-01-12 00:00:00 0.11 72
USC00516128 2012-01-13 00:00:00 0.02 68
USC00516128 2012-01-14 00:00:00 0.0 61
USC00516128 2012-01-15 00:00:00 0.0 76
USC00516128 2012-01-16 00:00:00 0.14 74
USC00516128 2012-01-17 00:00:00 0.01 73
USC00516128 2012-01-18 00:00:00 0.0 71
USC00516128 2012-01-19 00:00:00 0.0 69
USC00516128 2012-01-20 00:00:00 0.0 70
USC00516128 2012-01-21 00:00:00 0.0 71
USC00516128 2012-01-22 00:00:00 0.03 71
USC00516128 2012-01-23 00:00:00 0.01 66
USC00516128 2012-01-24 00:00:00 0.0 76
USC00516128 2012-01-25 00:00:00 0.06 67
USC00516128 2012-01-26 00:00:00 0.0 71
USC00516128 2012-01-27 00:00:00 0.05 66
USC00516128 2012-01-28 00:00:00 0.0 70
USC00516128 2012-01-29 00:00:00 0.67 69
USC00516128 2012-01-30 00:00:00 0.35 66
USC00516128 2012-01-31 00:00:00 0.04 67
USC00516128 2012-02-01 00:00:00 0.01 66
USC00516128 2012-02-02 00:00:00 0.0 72
USC00516128 2012-02-03 00:00:00 0.0 75
USC00516128 2012-02-04 00:00:00 0.0 61
USC00516128 2012-02-05 00:00:00 0.0 66
USC00516128 2012-02-06 00:00:00 0.0 69
USC00516128 2012-02-07 00:00:00 0.7 70
USC00516128 2012-02-08 00:00:00 0.44 66
USC00516128 2012-02-09 00:00:00 0.0 66
USC00516128 2012-02-10 00:00:00 0.0 68
USC00516128 2012-02-11 00:00:00 0.0 69
USC00516128 2012-02-12 00:00:00 0.07 69
USC00516128 2012-02-13 00:00:00 1.26 67
USC00516128 2012-02-14 00:00:00 0.02 71
USC00516128 2012-02-15 00:00:00 0.0 70
USC00516128 2012-02-16 00:00:00 0.0 70
USC00516128 2012-02-17 00:00:00 0.3 69
USC00516128 2012-02-18 00:00:00 0.67 69
USC00516128 2012-02-19 00:00:00 1.29 72
USC00516128 2012-02-20 00:00:00 0.03 69
USC00516128 2012-02-21 00:00:00 0.0 70
USC00516128 2012-02-22 00:00:00 0.0 70
USC00516128 2012-02-23 00:00:00 1.31 67
USC00516128 2012-02-24 00:00:00 0.77 74
USC00516128 2012-02-25 00:00:00 0.02 64
USC00516128 2012-02-26 00:00:00 0.3 71
USC00516128 2012-02-27 00:00:00 0.44 69
USC00516128 2012-02-28 00:00:00 0.4 69
USC00516128 2012-02-29 00:00:00 0.55 69
USC00516128 2012-03-01 00:00:00 0.64 67
USC00516128 2012-03-02 00:00:00 0.26 66
USC00516128 2012-03-03 00:00:00 1.1 66
USC00516128 2012-03-04 00:00:00 2.0 67
USC00516128 2012-03-05 00:00:00 5.37 64
USC00516128 2012-03-06 00:00:00 2.61 67
USC00516128 2012-03-07 00:00:00 2.63 69
USC00516128 2012-03-08 00:00:00 2.09 66
USC00516128 2012-03-09 00:00:00 3.23 64
USC00516128 2012-03-10 00:00:00 0.15 70
USC00516128 2012-03-11 00:00:00 0.31 71
USC00516128 2012-03-12 00:00:00 1.6 67
USC00516128 2012-03-13 00:00:00 0.45 67
USC00516128 2012-03-14 00:00:00 0.01 65
USC00516128 2012-03-15 00:00:00 0.03 66
USC00516128 2012-03-16 00:00:00 0.08 66
USC00516128 2012-03-17 00:00:00 0.02 68
USC00516128 2012-03-18 00:00:00 0.65 66
USC00516128 2012-03-19 00:00:00 1.61 69
USC00516128 2012-03-20 00:00:00 0.0 68
USC00516128 2012-03-21 00:00:00 0.43 65
USC00516128 2012-03-22 00:00:00 0.48 69
USC00516128 2012-03-23 00:00:00 0.05 68
USC00516128 2012-03-24 00:00:00 0.06 67
USC00516128 2012-03-25 00:00:00 1.92 68
USC00516128 2012-03-26 00:00:00 0.37 66
USC00516128 2012-03-27 00:00:00 0.57 66
USC00516128 2012-03-28 00:00:00 0.02 74
USC00516128 2012-03-29 00:00:00 0.0 74
USC00516128 2012-03-30 00:00:00 0.0 72
USC00516128 2012-03-31 00:00:00 0.0 70
USC00516128 2012-04-01 00:00:00 0.04 71
USC00516128 2012-04-02 00:00:00 0.0 71
USC00516128 2012-04-03 00:00:00 0.0 71
USC00516128 2012-04-04 00:00:00 0.03 69
USC00516128 2012-04-05 00:00:00 0.89 69
USC00516128 2012-04-06 00:00:00 0.1 68
USC00516128 2012-04-07 00:00:00 1.75 70
USC00516128 2012-04-08 00:00:00 0.02 69
USC00516128 2012-04-09 00:00:00 3.27 64
USC00516128 2012-04-10 00:00:00 1.32 64
USC00516128 2012-04-11 00:00:00 1.47 69
USC00516128 2012-04-12 00:00:00 0.15 69
USC00516128 2012-04-13 00:00:00 0.01 70
USC00516128 2012-04-14 00:00:00 0.01 68
USC00516128 2012-04-15 00:00:00 0.18 69
USC00516128 2012-04-16 00:00:00 0.12 72
USC00516128 2012-04-17 00:00:00 0.01 71
USC00516128 2012-04-18 00:00:00 0.01 71
USC00516128 2012-04-19 00:00:00 0.03 69
USC00516128 2012-04-20 00:00:00 0.04 67
USC00516128 2012-04-23 00:00:00 1.62 65
USC00516128 2012-04-24 00:00:00 0.2 68
USC00516128 2012-04-25 00:00:00 0.3 66
USC00516128 2012-04-26 00:00:00 0.61 76
USC00516128 2012-04-27 00:00:00 0.02 68
USC00516128 2012-04-28 00:00:00 0.65 68
USC00516128 2012-04-29 00:00:00 0.2 70
USC00516128 2012-04-30 00:00:00 0.12 70
USC00516128 2012-05-01 00:00:00 0.03 70
USC00516128 2012-05-02 00:00:00 0.57 67
USC00516128 2012-05-03 00:00:00 0.16 70
USC00516128 2012-05-04 00:00:00 1.21 66
USC00516128 2012-05-05 00:00:00 0.9 67
USC00516128 2012-05-06 00:00:00 0.14 67
USC00516128 2012-05-07 00:00:00 0.54 68
USC00516128 2012-05-08 00:00:00 0.02 69
USC00516128 2012-05-09 00:00:00 0.04 70

USC00516128 2012-05-10 00:00:00 0.0 69
USC00516128 2012-05-11 00:00:00 0.23 69
USC00516128 2012-05-12 00:00:00 0.01 73
USC00516128 2012-05-13 00:00:00 0.0 68
USC00516128 2012-05-14 00:00:00 0.0 75
USC00516128 2012-05-15 00:00:00 0.0 73
USC00516128 2012-05-16 00:00:00 0.03 68
USC00516128 2012-05-17 00:00:00 0.02 71
USC00516128 2012-05-18 00:00:00 0.05 72
USC00516128 2012-05-19 00:00:00 0.0 69
USC00516128 2012-05-20 00:00:00 0.02 68
USC00516128 2012-05-21 00:00:00 0.2 73
USC00516128 2012-05-22 00:00:00 0.0 72
USC00516128 2012-05-23 00:00:00 0.0 70
USC00516128 2012-05-24 00:00:00 0.07 72
USC00516128 2012-05-25 00:00:00 0.13 71
USC00516128 2012-05-26 00:00:00 0.37 74
USC00516128 2012-05-27 00:00:00 0.67 73
USC00516128 2012-05-28 00:00:00 0.13 73
USC00516128 2012-05-29 00:00:00 0.03 71
USC00516128 2012-05-30 00:00:00 0.01 70
USC00516128 2012-05-31 00:00:00 0.62 68
USC00516128 2012-06-01 00:00:00 0.26 69
USC00516128 2012-06-02 00:00:00 0.22 73
USC00516128 2012-06-03 00:00:00 0.0 71
USC00516128 2012-06-04 00:00:00 0.02 72
USC00516128 2012-06-05 00:00:00 0.0 71
USC00516128 2012-06-06 00:00:00 0.72 72
USC00516128 2012-06-07 00:00:00 0.12 71
USC00516128 2012-06-08 00:00:00 0.3 74
USC00516128 2012-06-09 00:00:00 0.0 74
USC00516128 2012-06-10 00:00:00 0.08 75
USC00516128 2012-06-11 00:00:00 0.08 69
USC00516128 2012-06-12 00:00:00 0.14 75
USC00516128 2012-06-13 00:00:00 0.48 70
USC00516128 2012-06-14 00:00:00 0.21 73
USC00516128 2012-06-15 00:00:00 0.0 72
USC00516128 2012-06-16 00:00:00 0.0 70
USC00516128 2012-06-17 00:00:00 0.1 73
USC00516128 2012-06-18 00:00:00 0.0 71
USC00516128 2012-06-19 00:00:00 0.38 70
USC00516128 2012-06-20 00:00:00 1.84 69
USC00516128 2012-06-21 00:00:00 0.34 71
USC00516128 2012-06-23 00:00:00 0.94 68
USC00516128 2012-06-24 00:00:00 1.13 68
USC00516128 2012-06-25 00:00:00 0.89 68
USC00516128 2012-06-26 00:00:00 0.92 69
USC00516128 2012-06-27 00:00:00 0.73 69
USC00516128 2012-06-28 00:00:00 0.37 69
USC00516128 2012-06-29 00:00:00 0.79 71
USC00516128 2012-07-02 00:00:00 0.05 75
USC00516128 2012-07-03 00:00:00 1.04 68
USC00516128 2012-07-04 00:00:00 0.85 70
USC00516128 2012-07-05 00:00:00 0.98 71
USC00516128 2012-07-06 00:00:00 1.08 70
USC00516128 2012-07-07 00:00:00 0.86 70
USC00516128 2012-07-08 00:00:00 0.05 72
USC00516128 2012-07-09 00:00:00 0.01 71
USC00516128 2012-07-10 00:00:00 0.12 70
USC00516128 2012-07-11 00:00:00 0.39 70
USC00516128 2012-07-12 00:00:00 0.0 70
USC00516128 2012-07-13 00:00:00 0.52 72
USC00516128 2012-07-14 00:00:00 0.29 74
USC00516128 2012-07-15 00:00:00 0.06 72
USC00516128 2012-07-16 00:00:00 0.83 72
USC00516128 2012-07-17 00:00:00 0.71 75
USC00516128 2012-07-18 00:00:00 1.0 72
USC00516128 2012-07-19 00:00:00 0.34 68
USC00516128 2012-07-20 00:00:00 0.13 71
USC00516128 2012-07-21 00:00:00 0.03 74
USC00516128 2012-07-22 00:00:00 0.04 69
USC00516128 2012-07-23 00:00:00 0.29 73
USC00516128 2012-07-24 00:00:00 0.0 74
USC00516128 2012-07-25 00:00:00 0.18 72
USC00516128 2012-07-26 00:00:00 0.0 72
USC00516128 2012-07-27 00:00:00 0.23 69
USC00516128 2012-07-28 00:00:00 0.5 70
USC00516128 2012-07-29 00:00:00 2.87 69
USC00516128 2012-07-30 00:00:00 0.36 72
USC00516128 2012-07-31 00:00:00 0.59 73
USC00516128 2012-08-01 00:00:00 0.05 71
USC00516128 2012-08-02 00:00:00 0.0 73
USC00516128 2012-08-03 00:00:00 0.09 72
USC00516128 2012-08-04 00:00:00 0.06 72
USC00516128 2012-08-05 00:00:00 0.44 70
USC00516128 2012-08-06 00:00:00 0.3 69
USC00516128 2012-08-07 00:00:00 0.22 71
USC00516128 2012-08-08 00:00:00 0.44 71
USC00516128 2012-08-09 00:00:00 0.14 75
USC00516128 2012-08-10 00:00:00 0.02 75
USC00516128 2012-08-11 00:00:00 0.26 67
USC00516128 2012-08-12 00:00:00 0.23 69
USC00516128 2012-08-13 00:00:00 0.03 73
USC00516128 2012-08-14 00:00:00 0.26 73
USC00516128 2012-08-15 00:00:00 0.02 73
USC00516128 2012-08-16 00:00:00 0.0 72
USC00516128 2012-08-17 00:00:00 0.24 72
USC00516128 2012-08-20 00:00:00 0.38 72
USC00516128 2012-08-21 00:00:00 0.41 71
USC00516128 2012-08-22 00:00:00 0.24 73
USC00516128 2012-08-23 00:00:00 0.09 74
USC00516128 2012-08-24 00:00:00 0.53 72
USC00516128 2012-08-25 00:00:00 0.0 78
USC00516128 2012-08-28 00:00:00 1.19 69
USC00516128 2012-08-29 00:00:00 0.9 72
USC00516128 2012-08-30 00:00:00 0.44 72
USC00516128 2012-08-31 00:00:00 0.26 70
USC00516128 2012-09-01 00:00:00 0.1 71
USC00516128 2012-09-02 00:00:00 0.46 67
USC00516128 2012-09-03 00:00:00 0.19 69
USC00516128 2012-09-04 00:00:00 0.05 73
USC00516128 2012-09-05 00:00:00 0.59 69
USC00516128 2012-09-06 00:00:00 0.2 70
USC00516128 2012-09-07 00:00:00 1.24 69
USC00516128 2012-09-08 00:00:00 2.48 69
USC00516128 2012-09-09 00:00:00 2.57 71
USC00516128 2012-09-10 00:00:00 0.19 72
USC00516128 2012-09-11 00:00:00 0.0 72
USC00516128 2012-09-12 00:00:00 0.23 71
USC00516128 2012-09-13 00:00:00 0.04 70
USC00516128 2012-09-14 00:00:00 0.52 69
USC00516128 2012-09-15 00:00:00 0.41 67
USC00516128 2012-09-16 00:00:00 0.62 70
USC00516128 2012-09-17 00:00:00 0.3 69
USC00516128 2012-09-18 00:00:00 0.38 68
USC00516128 2012-09-19 00:00:00 0.35 70
USC00516128 2012-09-20 00:00:00 0.16 73
USC00516128 2012-09-21 00:00:00 0.39 70
USC00516128 2012-09-22 00:00:00 0.17 69
USC00516128 2012-09-23 00:00:00 0.99 71
USC00516128 2012-09-24 00:00:00 1.58 69
USC00516128 2012-09-25 00:00:00 0.56 69
USC00516128 2012-09-26 00:00:00 0.3 69
USC00516128 2012-09-27 00:00:00 0.12 72
USC00516128 2012-09-28 00:00:00 0.31 70
USC00516128 2012-10-09 00:00:00 0.0 73
USC00516128 2012-10-10 00:00:00 0.0 71
USC00516128 2012-10-11 00:00:00 0.4 76
USC00516128 2012-10-12 00:00:00 0.0 77
USC00516128 2012-10-23 00:00:00 0.08 71
USC00516128 2012-10-24 00:00:00 0.0 69
USC00516128 2012-10-25 00:00:00 0.0 70
USC00516128 2012-10-26 00:00:00 0.01 71
USC00516128 2012-10-27 00:00:00 0.0 76
USC00516128 2012-10-28 00:00:00 0.49 71
USC00516128 2012-10-29 00:00:00 0.53 74
USC00516128 2012-10-30 00:00:00 0.2 68
USC00516128 2012-10-31 00:00:00 0.2 70
USC00516128 2012-11-01 00:00:00 0.0 70
USC00516128 2012-11-02 00:00:00 0.0 69
USC00516128 2012-11-03 00:00:00 0.0 66
USC00516128 2012-11-04 00:00:00 0.0 66
USC00516128 2012-11-05 00:00:00 0.02 70
USC00516128 2012-11-06 00:00:00 0.64 69
USC00516128 2012-11-07 00:00:00 0.09 73
USC00516128 2012-11-08 00:00:00 0.51 69
USC00516128 2012-11-09 00:00:00 0.27 72
USC00516128 2012-11-10 00:00:00 0.15 69
USC00516128 2012-11-11 00:00:00 0.02 71
USC00516128 2012-11-12 00:00:00 0.28 75
USC00516128 2012-11-13 00:00:00 0.42 69
USC00516128 2012-11-14 00:00:00 0.2 71
USC00516128 2012-11-15 00:00:00 0.64 71
USC00516128 2012-11-16 00:00:00 0.74 67
USC00516128 2012-11-17 00:00:00 0.18 67
USC00516128 2012-11-20 00:00:00 0.36 68
USC00516128 2012-11-21 00:00:00 0.11 70
USC00516128 2012-11-22 00:00:00 0.0 72
USC00516128 2012-11-23 00:00:00 0.0 67
USC00516128 2012-11-24 00:00:00 0.0 75
USC00516128 2012-11-25 00:00:00 0.0 71
USC00516128 2012-11-26 00:00:00 0.53 70
USC00516128 2012-11-27 00:00:00 0.01 69
USC00516128 2012-11-28 00:00:00 0.01 75
USC00516128 2012-11-29 00:00:00 0.0 67
USC00516128 2012-11-30 00:00:00 0.0 65
USC00516128 2012-12-01 00:00:00 0.0 74
USC00516128 2012-12-02 00:00:00 0.01 77
USC00516128 2012-12-03 00:00:00 0.0 74
USC00516128 2012-12-04 00:00:00 0.0 73
USC00516128 2012-12-05 00:00:00 0.04 71
USC00516128 2012-12-06 00:00:00 0.0 73
USC00516128 2012-12-07 00:00:00 0.0 68
USC00516128 2012-12-08 00:00:00 0.01 69
USC00516128 2012-12-09 00:00:00 0.04 71
USC00516128 2012-12-10 00:00:00 0.12 72
USC00516128 2012-12-11 00:00:00 0.0 72
USC00516128 2012-12-12 00:00:00 0.24 67
USC00516128 2012-12-13 00:00:00 0.44 67
USC00516128 2012-12-14 00:00:00 0.72 69
USC00516128 2012-12-15 00:00:00 0.44 66
USC00516128 2012-12-16 00:00:00 0.48 66
USC00516128 2012-12-17 00:00:00 0.54 69
USC00516128 2012-12-18 00:00:00 2.25 66
USC00516128 2012-12-19 00:00:00 0.34 68
USC00516128 2012-12-20 00:00:00 1.8 65
USC00516128 2012-12-21 00:00:00 0.67 68
USC00516128 2012-12-22 00:00:00 0.12 67
USC00516128 2012-12-23 00:00:00 0.0 71
USC00516128 2012-12-24 00:00:00 0.0 65
USC00516128 2012-12-25 00:00:00 0.0 71
USC00516128 2012-12-26 00:00:00 0.21 69
USC00516128 2012-12-27 00:00:00 0.02 69
USC00516128 2012-12-28 00:00:00 0.0 62
USC00516128 2012-12-29 00:00:00 0.0 62
USC00516128 2012-12-30 00:00:00 0.1 67
USC00516128 2012-12-31 00:00:00 0.04 65
USC00516128 2013-01-01 00:00:00 0.24 70
USC00516128 2013-01-02 00:00:00 2.13 67
USC00516128 2013-01-03 00:00:00 5.96 66
USC00516128 2013-01-04 00:00:00 2.92 67
USC00516128 2013-01-05 00:00:00 1.34 67
USC00516128 2013-01-06 00:00:00 0.76 67
USC00516128 2013-01-07 00:00:00 0.51 67
USC00516128 2013-01-08 00:00:00 0.53 68
USC00516128 2013-01-09 00:00:00 3.01 67
USC00516128 2013-01-10 00:00:00 0.14 69
USC00516128 2013-01-11 00:00:00 0.11 68
USC00516128 2013-01-12 00:00:00 0.19 67
USC00516128 2013-01-13 00:00:00 1.05 68
USC00516128 2013-01-14 00:00:00 0.02 70
USC00516128 2013-01-15 00:00:00 0.86 69
USC00516128 2013-01-16 00:00:00 0.0 64
USC00516128 2013-01-17 00:00:00 0.0 64
USC00516128 2013-01-18 00:00:00 0.0 65
USC00516128 2013-01-19 00:00:00 0.0 70
USC00516128 2013-01-20 00:00:00 0.0 67
USC00516128 2013-01-21 00:00:00 0.0 69
USC00516128 2013-01-22 00:00:00 0.0 68
USC00516128 2013-01-23 00:00:00 0.27 65
USC00516128 2013-01-24 00:00:00 1.38 66
USC00516128 2013-01-25 00:00:00 0.71 66
USC00516128 2013-01-26 00:00:00 0.04 62
USC00516128 2013-01-27 00:00:00 0.02 69
USC00516128 2013-01-28 00:00:00 1.84 66
USC00516128 2013-01-29 00:00:00 0.03 67
USC00516128 2013-01-30 00:00:00 0.0 62
USC00516128 2013-01-31 00:00:00 0.02 69
USC00516128 2013-02-01 00:00:00 0.06 69
USC00516128 2013-02-02 00:00:00 0.0 70
USC00516128 2013-02-03 00:00:00 0.0 67
USC00516128 2013-02-04 00:00:00 0.0 69
USC00516128 2013-02-05 00:00:00 0.16 71
USC00516128 2013-02-06 00:00:00 0.96 66
USC00516128 2013-02-07 00:00:00 0.86 67
USC00516128 2013-02-08 00:00:00 1.19 69
USC00516128 2013-02-09 00:00:00 0.0 69
USC00516128 2013-02-10 00:00:00 0.0 69
USC00516128 2013-02-11 00:00:00 0.39 66
USC00516128 2013-02-12 00:00:00 1.65 64
USC00516128 2013-02-13 00:00:00 0.02 65
USC00516128 2013-02-14 00:00:00 0.01 66
USC00516128 2013-02-15 00:00:00 0.08 66
USC00516128 2013-02-16 00:00:00 0.17 70
USC00516128 2013-02-17 00:00:00 0.0 67
USC00516128 2013-02-18 00:00:00 0.0 68
USC00516128 2013-02-19 00:00:00 0.58 67
USC00516128 2013-02-20 00:00:00 0.66 66
USC00516128 2013-02-21 00:00:00 0.73 66
USC00516128 2013-02-22 00:00:00 2.81 66
USC00516128 2013-02-23 00:00:00 1.85 67
USC00516128 2013-02-24 00:00:00 1.0 65
USC00516128 2013-02-25 00:00:00 0.11 67
USC00516128 2013-02-26 00:00:00 0.21 68
USC00516128 2013-02-27 00:00:00 0.12 68
USC00516128 2013-02-28 00:00:00 0.13 67
USC00516128 2013-03-01 00:00:00 0.0 67
USC00516128 2013-03-02 00:00:00 0.04 66
USC00516128 2013-03-03 00:00:00 0.0 67
USC00516128 2013-03-06 00:00:00 0.04 67
USC00516128 2013-03-07 00:00:00 0.06 73
USC00516128 2013-03-08 00:00:00 0.0 69
USC00516128 2013-03-09 00:00:00 0.04 71
USC00516128 2013-03-10 00:00:00 2.14 66
USC00516128 2013-03-11 00:00:00 0.79 65
USC00516128 2013-03-12 00:00:00 0.0 67
USC00516128 2013-03-13 00:00:00 0.0 64
USC00516128 2013-03-14 00:00:00 0.0 66
USC00516128 2013-03-15 00:00:00 0.0 62
USC00516128 2013-03-16 00:00:00 0.0 65
USC00516128 2013-03-17 00:00:00 0.0 64
USC00516128 2013-03-18 00:00:00 0.0 69
USC00516128 2013-03-19 00:00:00 0.0 67
USC00516128 2013-03-20 00:00:00 0.0 64
USC00516128 2013-03-21 00:00:00 0.0 67
USC00516128 2013-03-22 00:00:00 0.0 72
USC00516128 2013-03-23 00:00:00 0.22 67
USC00516128 2013-03-24 00:00:00 0.42 67
USC00516128 2013-03-25 00:00:00 0.45 69
USC00516128 2013-03-26 00:00:00 0.0 69
USC00516128 2013-03-27 00:00:00 0.01 68
USC00516128 2013-03-28 00:00:00 0.86 68
USC00516128 2013-03-29 00:00:00 1.58 66
USC00516128 2013-03-30 00:00:00 0.56 71
USC00516128 2013-04-02 00:00:00 0.0 67
USC00516128 2013-04-03 00:00:00 0.0 67
USC00516128 2013-04-04 00:00:00 0.36 66
USC00516128 2013-04-05 00:00:00 0.0 69
USC00516128 2013-04-08 00:00:00 0.0 72
USC00516128 2013-04-09 00:00:00 0.06 70
USC00516128 2013-04-10 00:00:00 0.63 69
USC00516128 2013-04-11 00:00:00 0.08 71
USC00516128 2013-04-12 00:00:00 0.01 71
USC00516128 2013-04-13 00:00:00 0.02 72
USC00516128 2013-04-14 00:00:00 0.0 72
USC00516128 2013-04-15 00:00:00 0.83 72
USC00516128 2013-04-16 00:00:00 0.08 68
USC00516128 2013-04-17 00:00:00 0.0 72
USC00516128 2013-04-18 00:00:00 0.07 69
USC00516128 2013-04-19 00:00:00 0.57 69
USC00516128 2013-04-20 00:00:00 1.4 75
USC00516128 2013-04-21 00:00:00 0.01 69
USC00516128 2013-04-22 00:00:00 0.06 71
USC00516128 2013-04-23 00:00:00 0.0 70
USC00516128 2013-04-24 00:00:00 0.91 78
USC00516128 2013-04-25 00:00:00 0.7 72
USC00516128 2013-04-26 00:00:00 0.01 73
USC00516128 2013-04-29 00:00:00 0.0 74
USC00516128 2013-04-30 00:00:00 0.0 74
USC00516128 2013-05-01 00:00:00 0.53 70
USC00516128 2013-05-02 00:00:00 0.6 73
USC00516128 2013-05-03 00:00:00 0.11 78
USC00516128 2013-05-04 00:00:00 0.02 69
USC00516128 2013-05-05 00:00:00 0.42 69
USC00516128 2013-05-06 00:00:00 0.56 70
USC00516128 2013-05-07 00:00:00 0.0 70
USC00516128 2013-05-08 00:00:00 0.0 74
USC00516128 2013-05-09 00:00:00 0.0 73
USC00516128 2013-05-10 00:00:00 0.0 73
USC00516128 2013-05-11 00:00:00 0.21 70
USC00516128 2013-05-12 00:00:00 0.43 69
USC00516128 2013-05-13 00:00:00 3.7 70
USC00516128 2013-05-14 00:00:00 1.22 71
USC00516128 2013-05-15 00:00:00 0.02 72
USC00516128 2013-05-16 00:00:00 0.32 70
USC00516128 2013-05-17 00:00:00 0.15 71
USC00516128 2013-05-18 00:00:00 0.15 70
USC00516128 2013-05-19 00:00:00 0.35 76
USC00516128 2013-05-20 00:00:00 0.12 73
USC00516128 2013-05-21 00:00:00 0.0 69
USC00516128 2013-05-22 00:00:00 0.0 75
USC00516128 2013-05-23 00:00:00 0.0 75
USC00516128 2013-05-24 00:00:00 0.0 73
USC00516128 2013-05-25 00:00:00 0.28 71
USC00516128 2013-05-26 00:00:00 0.98 71
USC00516128 2013-05-27 00:00:00 0.06 72
USC00516128 2013-05-28 00:00:00 1.73 69
USC00516128 2013-05-29 00:00:00 2.41 72
USC00516128 2013-05-30 00:00:00 0.39 72
USC00516128 2013-05-31 00:00:00 0.27 71
USC00516128 2013-06-01 00:00:00 0.71 78
USC00516128 2013-06-02 00:00:00 0.81 72
USC00516128 2013-06-03 00:00:00 0.49 73
USC00516128 2013-06-04 00:00:00 0.03 71
USC00516128 2013-06-05 00:00:00 0.0 72
USC00516128 2013-06-06 00:00:00 0.14 72
USC00516128 2013-06-07 00:00:00 0.07 71
USC00516128 2013-06-08 00:00:00 0.08 74
USC00516128 2013-06-09 00:00:00 0.02 71
USC00516128 2013-06-10 00:00:00 0.02 72
USC00516128 2013-06-11 00:00:00 0.05 72
USC00516128 2013-06-12 00:00:00 0.28 74
USC00516128 2013-06-13 00:00:00 0.47 72
USC00516128 2013-06-14 00:00:00 2.56 69
USC00516128 2013-06-15 00:00:00 0.11 70
USC00516128 2013-06-16 00:00:00 0.3 76
USC00516128 2013-06-17 00:00:00 0.43 70
USC00516128 2013-06-18 00:00:00 0.44 71
USC00516128 2013-06-19 00:00:00 0.05 73
USC00516128 2013-06-20 00:00:00 0.18 68
USC00516128 2013-06-21 00:00:00 1.53 68
USC00516128 2013-06-22 00:00:00 1.96 69
USC00516128 2013-06-23 00:00:00 0.67 70
USC00516128 2013-06-24 00:00:00 0.62 69
USC00516128 2013-06-25 00:00:00 2.03 69

USC00516128 2013-06-26 00:00:00 2.8 70
USC00516128 2013-06-27 00:00:00 0.06 71
USC00516128 2013-06-28 00:00:00 0.34 70
USC00516128 2013-06-29 00:00:00 0.53 67
USC00516128 2013-06-30 00:00:00 0.83 72
USC00516128 2013-07-01 00:00:00 0.0 73
USC00516128 2013-07-02 00:00:00 0.43 69
USC00516128 2013-07-03 00:00:00 0.51 72
USC00516128 2013-07-04 00:00:00 0.22 73
USC00516128 2013-07-05 00:00:00 0.0 67
USC00516128 2013-07-06 00:00:00 0.0 73
USC00516128 2013-07-07 00:00:00 0.0 70
USC00516128 2013-07-08 00:00:00 0.01 72
USC00516128 2013-07-09 00:00:00 0.24 74
USC00516128 2013-07-10 00:00:00 0.21 70
USC00516128 2013-07-11 00:00:00 0.26 71
USC00516128 2013-07-12 00:00:00 0.43 71
USC00516128 2013-07-15 00:00:00 0.2 73
USC00516128 2013-07-16 00:00:00 0.26 71
USC00516128 2013-07-23 00:00:00 0.63 73
USC00516128 2013-07-26 00:00:00 0.0 71
USC00516128 2013-07-27 00:00:00 0.07 72
USC00516128 2013-07-28 00:00:00 0.53 72
USC00516128 2013-07-31 00:00:00 0.53 72
USC00516128 2013-08-03 00:00:00 0.06 72
USC00516128 2013-08-04 00:00:00 0.29 69
USC00516128 2013-08-05 00:00:00 0.34 72
USC00516128 2013-08-06 00:00:00 0.23 74
USC00516128 2013-08-07 00:00:00 0.0 74
USC00516128 2013-08-08 00:00:00 0.0 73
USC00516128 2013-08-09 00:00:00 0.1 71
USC00516128 2013-08-10 00:00:00 4.32 75
USC00516128 2013-08-11 00:00:00 0.96 72
USC00516128 2013-08-12 00:00:00 0.36 74
USC00516128 2013-08-13 00:00:00 0.0 73
USC00516128 2013-08-14 00:00:00 0.22 73
USC00516128 2013-08-17 00:00:00 0.0 74
USC00516128 2013-08-18 00:00:00 0.0 73
USC00516128 2013-08-19 00:00:00 0.03 73
USC00516128 2013-08-20 00:00:00 0.02 78
USC00516128 2013-08-21 00:00:00 0.09 73
USC00516128 2013-08-24 00:00:00 0.17 77
USC00516128 2013-08-27 00:00:00 0.0 76
USC00516128 2013-08-28 00:00:00 0.0 78
USC00516128 2013-08-29 00:00:00 0.45 72
USC00516128 2013-08-30 00:00:00 0.04 73
USC00516128 2013-08-31 00:00:00 0.1 74
USC00516128 2013-09-01 00:00:00 0.44 79
USC00516128 2013-09-02 00:00:00 0.07 71
USC00516128 2013-09-03 00:00:00 0.13 71
USC00516128 2013-09-04 00:00:00 0.06 74
USC00516128 2013-09-05 00:00:00 0.02 75
USC00516128 2013-09-06 00:00:00 0.0 71
USC00516128 2013-09-07 00:00:00 1.01 71
USC00516128 2013-09-08 00:00:00 0.18 73
USC00516128 2013-09-09 00:00:00 0.02 74
USC00516128 2013-09-10 00:00:00 0.01 76
USC00516128 2013-09-11 00:00:00 0.19 76
USC00516128 2013-09-12 00:00:00 0.0 73
USC00516128 2013-09-13 00:00:00 0.88 71
USC00516128 2013-09-14 00:00:00 0.98 72
USC00516128 2013-09-15 00:00:00 0.2 75
USC00516128 2013-09-16 00:00:00 0.0 75
USC00516128 2013-09-17 00:00:00 0.36 71
USC00516128 2013-09-18 00:00:00 0.62 71
USC00516128 2013-09-19 00:00:00 0.07 72
USC00516128 2013-09-20 00:00:00 0.0 75
USC00516128 2013-09-21 00:00:00 0.01 74
USC00516128 2013-09-22 00:00:00 0.22 70
USC00516128 2013-09-23 00:00:00 0.29 71
USC00516128 2013-09-24 00:00:00 0.07 71
USC00516128 2013-09-25 00:00:00 0.77 73
USC00516128 2013-09-28 00:00:00 0.11 76
USC00516128 2013-09-29 00:00:00 0.46 72
USC00516128 2013-09-30 00:00:00 0.7 74
USC00516128 2013-10-01 00:00:00 0.55 73
USC00516128 2013-10-02 00:00:00 0.24 75
USC00516128 2013-10-03 00:00:00 0.07 74
USC00516128 2013-10-04 00:00:00 0.07 72
USC00516128 2013-10-05 00:00:00 0.72 71
USC00516128 2013-10-06 00:00:00 0.22 74
USC00516128 2013-10-07 00:00:00 0.37 75
USC00516128 2013-10-08 00:00:00 0.09 72
USC00516128 2013-10-09 00:00:00 0.48 73
USC00516128 2013-10-10 00:00:00 0.54 71
USC00516128 2013-10-11 00:00:00 0.45 75
USC00516128 2013-10-12 00:00:00 0.01 73
USC00516128 2013-10-13 00:00:00 0.0 84
USC00516128 2013-10-14 00:00:00 2.15 74
USC00516128 2013-10-15 00:00:00 1.02 76
USC00516128 2013-10-16 00:00:00 0.3 70
USC00516128 2013-10-17 00:00:00 0.02 76
USC00516128 2013-10-18 00:00:00 0.0 67
USC00516128 2013-10-19 00:00:00 0.0 70
USC00516128 2013-10-20 00:00:00 0.0 70
USC00516128 2013-10-21 00:00:00 0.05 77
USC00516128 2013-10-22 00:00:00 0.0 72
USC00516128 2013-10-25 00:00:00 0.1 74
USC00516128 2013-10-26 00:00:00 0.0 80
USC00516128 2013-10-29 00:00:00 0.03 73
USC00516128 2013-10-30 00:00:00 0.12 72
USC00516128 2013-10-31 00:00:00 0.54 75
USC00516128 2013-11-01 00:00:00 0.09 72
USC00516128 2013-11-02 00:00:00 0.38 70
USC00516128 2013-11-03 00:00:00 0.02 72
USC00516128 2013-11-06 00:00:00 0.54 74
USC00516128 2013-11-07 00:00:00 0.12 72
USC00516128 2013-11-08 00:00:00 0.39 75
USC00516128 2013-11-09 00:00:00 0.77 70
USC00516128 2013-11-10 00:00:00 8.06 70
USC00516128 2013-11-11 00:00:00 1.7 71
USC00516128 2013-11-14 00:00:00 0.0 71
USC00516128 2013-11-15 00:00:00 0.72 72
USC00516128 2013-11-16 00:00:00 0.0 75
USC00516128 2013-11-17 00:00:00 0.0 73
USC00516128 2013-11-18 00:00:00 0.03 66
USC00516128 2013-11-19 00:00:00 0.0 69
USC00516128 2013-11-20 00:00:00 0.0 69
USC00516128 2013-11-21 00:00:00 0.0 69
USC00516128 2013-11-24 00:00:00 0.0 75
USC00516128 2013-11-27 00:00:00 0.0 73
USC00516128 2013-11-28 00:00:00 0.07 72
USC00516128 2013-11-29 00:00:00 0.0 72
USC00516128 2013-11-30 00:00:00 0.63 74
USC00516128 2013-12-01 00:00:00 0.14 68
USC00516128 2013-12-02 00:00:00 2.02 67
USC00516128 2013-12-03 00:00:00 0.15 75
USC00516128 2013-12-04 00:00:00 0.0 68
USC00516128 2013-12-05 00:00:00 0.0 68
USC00516128 2013-12-06 00:00:00 0.0 70
USC00516128 2013-12-09 00:00:00 0.0 68
USC00516128 2013-12-10 00:00:00 0.35 70
USC00516128 2013-12-11 00:00:00 0.37 70
USC00516128 2013-12-12 00:00:00 0.09 68
USC00516128 2013-12-13 00:00:00 0.39 76
USC00516128 2013-12-14 00:00:00 0.54 72
USC00516128 2013-12-15 00:00:00 0.01 68
USC00516128 2013-12-16 00:00:00 1.13 64
USC00516128 2013-12-17 00:00:00 0.0 72
USC00516128 2013-12-18 00:00:00 0.03 72
USC00516128 2013-12-19 00:00:00 2.0 68
USC00516128 2013-12-20 00:00:00 1.02 70
USC00516128 2013-12-21 00:00:00 1.14 69
USC00516128 2013-12-24 00:00:00 0.03 70
USC00516128 2013-12-25 00:00:00 0.41 67
USC00516128 2013-12-26 00:00:00 0.14 70
USC00516128 2013-12-27 00:00:00 0.0 70
USC00516128 2013-12-28 00:00:00 0.03 71
USC00516128 2013-12-29 00:00:00 0.47 70
USC00516128 2013-12-30 00:00:00 0.02 69
USC00516128 2013-12-31 00:00:00 0.0 71
USC00516128 2014-01-01 00:00:00 0.0 65
USC00516128 2014-01-02 00:00:00 0.04 69
USC00516128 2014-01-03 00:00:00 2.41 69
USC00516128 2014-01-04 00:00:00 0.0 69
USC00516128 2014-01-05 00:00:00 0.02 66
USC00516128 2014-01-06 00:00:00 0.06 67
USC00516128 2014-01-07 00:00:00 0.0 69
USC00516128 2014-01-08 00:00:00 0.0 69
USC00516128 2014-01-09 00:00:00 0.11 69
USC00516128 2014-01-10 00:00:00 0.1 70
USC00516128 2014-01-11 00:00:00 0.09 67
USC00516128 2014-01-12 00:00:00 0.02 69
USC00516128 2014-01-13 00:00:00 0.0 67
USC00516128 2014-01-14 00:00:00 0.8 73
USC00516128 2014-01-15 00:00:00 0.01 69
USC00516128 2014-01-16 00:00:00 0.01 68
USC00516128 2014-01-17 00:00:00 0.0 73
USC00516128 2014-01-18 00:00:00 0.01 69
USC00516128 2014-01-19 00:00:00 0.0 66
USC00516128 2014-01-20 00:00:00 0.0 66
USC00516128 2014-01-21 00:00:00 0.02 65
USC00516128 2014-01-22 00:00:00 0.75 68
USC00516128 2014-01-23 00:00:00 0.0 68
USC00516128 2014-01-24 00:00:00 0.0 68
USC00516128 2014-01-25 00:00:00 0.0 70
USC00516128 2014-01-26 00:00:00 0.32 70
USC00516128 2014-01-27 00:00:00 0.22 64
USC00516128 2014-01-28 00:00:00 0.28 65
USC00516128 2014-01-29 00:00:00 2.0 66
USC00516128 2014-01-30 00:00:00 1.32 65
USC00516128 2014-01-31 00:00:00 0.02 67
USC00516128 2014-02-01 00:00:00 0.51 68
USC00516128 2014-02-02 00:00:00 0.61 67
USC00516128 2014-02-03 00:00:00 0.0 68
USC00516128 2014-02-04 00:00:00 0.38 66
USC00516128 2014-02-05 00:00:00 0.31 69
USC00516128 2014-02-06 00:00:00 0.07 72
USC00516128 2014-02-07 00:00:00 0.02 72
USC00516128 2014-02-08 00:00:00 0.13 70
USC00516128 2014-02-09 00:00:00 0.22 69
USC00516128 2014-02-10 00:00:00 0.01 68
USC00516128 2014-02-11 00:00:00 0.0 77
USC00516128 2014-02-12 00:00:00 0.0 71
USC00516128 2014-02-13 00:00:00 0.0 71
USC00516128 2014-02-14 00:00:00 0.12 69
USC00516128 2014-02-15 00:00:00 2.97 69
USC00516128 2014-02-16 00:00:00 0.76 69
USC00516128 2014-02-17 00:00:00 0.36 68
USC00516128 2014-02-18 00:00:00 0.26 68
USC00516128 2014-02-19 00:00:00 0.02 77
USC00516128 2014-02-22 00:00:00 0.02 83
USC00516128 2014-02-23 00:00:00 0.08 66
USC00516128 2014-02-24 00:00:00 0.05 68
USC00516128 2014-02-25 00:00:00 0.01 67
USC00516128 2014-02-26 00:00:00 0.0 62
USC00516128 2014-02-27 00:00:00 0.05 67
USC00516128 2014-02-28 00:00:00 0.15 68
USC00516128 2014-03-01 00:00:00 0.42 69
USC00516128 2014-03-02 00:00:00 0.79 66
USC00516128 2014-03-03 00:00:00 0.14 60
USC00516128 2014-03-04 00:00:00 0.0 70
USC00516128 2014-03-05 00:00:00 0.0 68
USC00516128 2014-03-06 00:00:00 0.0 65
USC00516128 2014-03-07 00:00:00 0.4 69
USC00516128 2014-03-08 00:00:00 0.78 65
USC00516128 2014-03-09 00:00:00 3.4 68
USC00516128 2014-03-10 00:00:00 2.14 68
USC00516128 2014-03-11 00:00:00 0.02 69
USC00516128 2014-03-12 00:00:00 0.01 70
USC00516128 2014-03-13 00:00:00 0.02 70
USC00516128 2014-03-16 00:00:00 0.49 66
USC00516128 2014-03-26 00:00:00 1.47 77
USC00516128 2014-03-27 00:00:00 0.39 69
USC00516128 2014-03-28 00:00:00 0.36 71
USC00516128 2014-03-29 00:00:00 1.48 70
USC00516128 2014-04-01 00:00:00 0.79 69
USC00516128 2014-04-02 00:00:00 0.77 71
USC00516128 2014-04-03 00:00:00 0.44 71
USC00516128 2014-04-04 00:00:00 0.02 70
USC00516128 2014-04-05 00:00:00 0.0 74
USC00516128 2014-04-06 00:00:00 0.0 71
USC00516128 2014-04-07 00:00:00 1.26 66
USC00516128 2014-04-08 00:00:00 0.38 66
USC00516128 2014-04-09 00:00:00 0.0 67
USC00516128 2014-04-10 00:00:00 0.08 64
USC00516128 2014-04-11 00:00:00 0.02 69
USC00516128 2014-04-12 00:00:00 1.18 65
USC00516128 2014-04-13 00:00:00 0.53 67
USC00516128 2014-04-14 00:00:00 0.72 68
USC00516128 2014-04-15 00:00:00 0.05 69
USC00516128 2014-04-16 00:00:00 0.88 70
USC00516128 2014-04-17 00:00:00 0.08 72
USC00516128 2014-04-18 00:00:00 0.78 70
USC00516128 2014-04-19 00:00:00 0.44 72
USC00516128 2014-04-20 00:00:00 0.21 69
USC00516128 2014-04-21 00:00:00 1.9 68
USC00516128 2014-04-22 00:00:00 1.56 71
USC00516128 2014-04-23 00:00:00 0.07 69
USC00516128 2014-04-24 00:00:00 0.23 71

USC00516128 2014-04-25 00:00:00 0.81 70
USC00516128 2014-04-26 00:00:00 0.1 68
USC00516128 2014-04-27 00:00:00 2.44 67
USC00516128 2014-04-28 00:00:00 1.06 66
USC00516128 2014-04-29 00:00:00 0.09 69
USC00516128 2014-04-30 00:00:00 0.22 67
USC00516128 2014-05-01 00:00:00 0.52 67
USC00516128 2014-05-02 00:00:00 0.15 69
USC00516128 2014-05-03 00:00:00 1.14 71
USC00516128 2014-05-04 00:00:00 0.0 70
USC00516128 2014-05-05 00:00:00 0.03 67
USC00516128 2014-05-06 00:00:00 0.24 70
USC00516128 2014-05-07 00:00:00 0.31 69
USC00516128 2014-05-08 00:00:00 0.03 68
USC00516128 2014-05-09 00:00:00 0.23 70
USC00516128 2014-05-12 00:00:00 2.79 69
USC00516128 2014-05-13 00:00:00 0.17 69
USC00516128 2014-05-14 00:00:00 0.0 69
USC00516128 2014-05-15 00:00:00 0.05 75
USC00516128 2014-05-16 00:00:00 0.18 71
USC00516128 2014-05-17 00:00:00 0.04 69
USC00516128 2014-05-18 00:00:00 0.0 74
USC00516128 2014-05-19 00:00:00 0.15 68
USC00516128 2014-05-20 00:00:00 0.24 70
USC00516128 2014-05-21 00:00:00 0.04 73
USC00516128 2014-05-22 00:00:00 0.0 77
USC00516128 2014-05-23 00:00:00 0.0 76
USC00516128 2014-05-24 00:00:00 0.05 73
USC00516128 2014-05-25 00:00:00 0.51 77
USC00516128 2014-05-26 00:00:00 2.2 70
USC00516128 2014-05-27 00:00:00 0.11 71
USC00516128 2014-05-28 00:00:00 0.41 71
USC00516128 2014-05-29 00:00:00 0.19 70
USC00516128 2014-05-30 00:00:00 0.41 73
USC00516128 2014-06-01 00:00:00 0.26 72
USC00516128 2014-06-02 00:00:00 0.68 75
USC00516128 2014-06-03 00:00:00 0.19 73
USC00516128 2014-06-04 00:00:00 0.09 73
USC00516128 2014-06-05 00:00:00 0.03 72
USC00516128 2014-06-06 00:00:00 0.88 71
USC00516128 2014-06-07 00:00:00 0.15 77
USC00516128 2014-06-08 00:00:00 0.29 73
USC00516128 2014-06-09 00:00:00 1.0 70
USC00516128 2014-06-10 00:00:00 0.11 70
USC00516128 2014-06-11 00:00:00 0.57 76
USC00516128 2014-06-12 00:00:00 0.02 72
USC00516128 2014-06-13 00:00:00 0.01 73
USC00516128 2014-06-14 00:00:00 0.0 77
USC00516128 2014-06-15 00:00:00 0.03 73
USC00516128 2014-06-16 00:00:00 0.38 70
USC00516128 2014-06-17 00:00:00 1.45 68
USC00516128 2014-06-18 00:00:00 0.32 69
USC00516128 2014-06-19 00:00:00 0.2 70
USC00516128 2014-06-20 00:00:00 0.75 70
USC00516128 2014-06-21 00:00:00 0.09 73
USC00516128 2014-06-22 00:00:00 0.03 70
USC00516128 2014-06-23 00:00:00 0.74 69
USC00516128 2014-06-24 00:00:00 0.07 71
USC00516128 2014-06-25 00:00:00 0.97 70
USC00516128 2014-06-26 00:00:00 0.42 70
USC00516128 2014-06-27 00:00:00 0.9 72
USC00516128 2014-06-28 00:00:00 1.29 71
USC00516128 2014-06-29 00:00:00 1.29 70
USC00516128 2014-07-02 00:00:00 0.42 71
USC00516128 2014-07-03 00:00:00 1.1 71
USC00516128 2014-07-04 00:00:00 0.07 77
USC00516128 2014-07-05 00:00:00 0.12 71
USC00516128 2014-07-06 00:00:00 1.34 71
USC00516128 2014-07-07 00:00:00 0.57 69
USC00516128 2014-07-08 00:00:00 0.42 73
USC00516128 2014-07-09 00:00:00 0.55 70
USC00516128 2014-07-10 00:00:00 0.33 74
USC00516128 2014-07-11 00:00:00 0.16 75
USC00516128 2014-07-12 00:00:00 0.16 73
USC00516128 2014-07-13 00:00:00 1.23 72
USC00516128 2014-07-14 00:00:00 1.01 73
USC00516128 2014-07-15 00:00:00 1.18 75
USC00516128 2014-07-18 00:00:00 1.04 73
USC00516128 2014-07-19 00:00:00 0.01 74
USC00516128 2014-07-20 00:00:00 4.3 72
USC00516128 2014-07-21 00:00:00 0.72 73
USC00516128 2014-07-22 00:00:00 0.14 75
USC00516128 2014-07-23 00:00:00 0.93 75
USC00516128 2014-07-24 00:00:00 0.13 73
USC00516128 2014-07-25 00:00:00 0.05 72
USC00516128 2014-07-26 00:00:00 0.26 74
USC00516128 2014-07-27 00:00:00 1.43 75
USC00516128 2014-07-28 00:00:00 0.0 74
USC00516128 2014-07-29 00:00:00 0.0 75
USC00516128 2014-07-30 00:00:00 0.0 73
USC00516128 2014-07-31 00:00:00 0.02 74
USC00516128 2014-08-01 00:00:00 0.06 73
USC00516128 2014-08-02 00:00:00 0.95 73
USC00516128 2014-08-03 00:00:00 0.03 74
USC00516128 2014-08-06 00:00:00 0.26 71
USC00516128 2014-08-07 00:00:00 0.02 74
USC00516128 2014-08-08 00:00:00 1.1 73
USC00516128 2014-08-09 00:00:00 1.2 73
USC00516128 2014-08-10 00:00:00 0.41 74
USC00516128 2014-08-13 00:00:00 0.11 74
USC00516128 2014-08-14 00:00:00 0.07 76
USC00516128 2014-08-15 00:00:00 0.11 71
USC00516128 2014-08-16 00:00:00 0.16 71
USC00516128 2014-08-17 00:00:00 0.29 71
USC00516128 2014-08-20 00:00:00 0.16 75
USC00516128 2014-08-21 00:00:00 0.52 73
USC00516128 2014-08-22 00:00:00 0.88 73
USC00516128 2014-08-23 00:00:00 0.09 75
USC00516128 2014-08-24 00:00:00 0.37 72
USC00516128 2014-08-25 00:00:00 0.71 70
USC00516128 2014-08-26 00:00:00 1.14 72
USC00516128 2014-08-27 00:00:00 0.37 72
USC00516128 2014-09-01 00:00:00 0.01 73
USC00516128 2014-09-02 00:00:00 0.06 75
USC00516128 2014-09-03 00:00:00 0.03 75
USC00516128 2014-09-04 00:00:00 0.24 74
USC00516128 2014-09-05 00:00:00 0.44 75
USC00516128 2014-09-06 00:00:00 0.93 74
USC00516128 2014-09-07 00:00:00 0.14 72
USC00516128 2014-09-14 00:00:00 0.0 74
USC00516128 2014-09-15 00:00:00 0.19 72
USC00516128 2014-09-16 00:00:00 0.01 78
USC00516128 2014-09-19 00:00:00 0.0 80
USC00516128 2014-09-20 00:00:00 0.02 78
USC00516128 2014-09-21 00:00:00 0.01 77
USC00516128 2014-09-22 00:00:00 0.08 77
USC00516128 2014-09-23 00:00:00 0.05 77
USC00516128 2014-09-24 00:00:00 0.0 76
USC00516128 2014-09-25 00:00:00 0.85 77
USC00516128 2014-09-26 00:00:00 1.8 75
USC00516128 2014-09-27 00:00:00 1.3 74
USC00516128 2014-09-28 00:00:00 0.3 72
USC00516128 2014-09-29 00:00:00 0.55 74
USC00516128 2014-09-30 00:00:00 0.12 75
USC00516128 2014-10-01 00:00:00 1.19 74
USC00516128 2014-10-02 00:00:00 0.07 75
USC00516128 2014-10-03 00:00:00 0.03 75
USC00516128 2014-10-04 00:00:00 0.69 74
USC00516128 2014-10-05 00:00:00 0.27 81
USC00516128 2014-10-06 00:00:00 0.58 73
USC00516128 2014-10-07 00:00:00 0.06 80
USC00516128 2014-10-10 00:00:00 0.1 76
USC00516128 2014-10-11 00:00:00 0.16 76
USC00516128 2014-10-12 00:00:00 0.04 74
USC00516128 2014-10-13 00:00:00 0.03 73
USC00516128 2014-10-14 00:00:00 0.29 72
USC00516128 2014-10-15 00:00:00 0.3 73
USC00516128 2014-10-16 00:00:00 0.06 75
USC00516128 2014-10-17 00:00:00 0.26 75
USC00516128 2014-10-18 00:00:00 1.88 78
USC00516128 2014-10-19 00:00:00 2.98 73
USC00516128 2014-10-20 00:00:00 2.31 75
USC00516128 2014-10-21 00:00:00 0.0 76
USC00516128 2014-10-22 00:00:00 0.61 76
USC00516128 2014-10-23 00:00:00 2.31 75
USC00516128 2014-10-24 00:00:00 0.68 72
USC00516128 2014-10-25 00:00:00 0.51 74
USC00516128 2014-10-26 00:00:00 0.31 74
USC00516128 2014-10-27 00:00:00 0.02 74
USC00516128 2014-10-28 00:00:00 0.48 74
USC00516128 2014-10-29 00:00:00 0.76 75
USC00516128 2014-10-30 00:00:00 0.69 73
USC00516128 2014-10-31 00:00:00 0.3 73
USC00516128 2014-11-01 00:00:00 0.59 76
USC00516128 2014-11-02 00:00:00 0.79 71
USC00516128 2014-11-03 00:00:00 1.25 71
USC00516128 2014-11-04 00:00:00 0.13 74
USC00516128 2014-11-05 00:00:00 0.73 71
USC00516128 2014-11-06 00:00:00 0.6 75
USC00516128 2014-11-07 00:00:00 0.17 76
USC00516128 2014-11-08 00:00:00 0.58 69
USC00516128 2014-11-09 00:00:00 0.01 70
USC00516128 2014-11-10 00:00:00 0.0 69
USC00516128 2014-11-13 00:00:00 0.0 69
USC00516128 2014-11-14 00:00:00 0.0 72
USC00516128 2014-11-15 00:00:00 1.11 71
USC00516128 2014-11-16 00:00:00 0.21 74
USC00516128 2014-11-17 00:00:00 0.0 72
USC00516128 2014-11-20 00:00:00 0.61 71
USC00516128 2014-11-21 00:00:00 0.03 74
USC00516128 2014-11-22 00:00:00 0.44 74
USC00516128 2014-11-23 00:00:00 0.0 70
USC00516128 2014-11-26 00:00:00 0.01 71
USC00516128 2014-11-27 00:00:00 0.0 72
USC00516128 2014-11-28 00:00:00 0.02 70
USC00516128 2014-11-29 00:00:00 1.21 68
USC00516128 2014-11-30 00:00:00 0.94 66
USC00516128 2014-12-01 00:00:00 0.0 68
USC00516128 2014-12-02 00:00:00 0.07 70
USC00516128 2014-12-03 00:00:00 1.82 67
USC00516128 2014-12-04 00:00:00 1.41 70
USC00516128 2014-12-05 00:00:00 0.0 73
USC00516128 2014-12-06 00:00:00 0.11 70
USC00516128 2014-12-07 00:00:00 0.0 66
USC00516128 2014-12-10 00:00:00 0.0 72
USC00516128 2014-12-11 00:00:00 1.09 71
USC00516128 2014-12-12 00:00:00 0.83 68
USC00516128 2014-12-13 00:00:00 0.0 71
USC00516128 2014-12-14 00:00:00 1.75 67
USC00516128 2014-12-15 00:00:00 0.55 65
USC00516128 2014-12-16 00:00:00 0.58 66
USC00516128 2014-12-17 00:00:00 0.8 70
USC00516128 2014-12-18 00:00:00 0.21 69
USC00516128 2014-12-19 00:00:00 0.51 70
USC00516128 2014-12-22 00:00:00 0.59 67
USC00516128 2014-12-23 00:00:00 4.03 68
USC00516128 2014-12-24 00:00:00 0.4 64
USC00516128 2014-12-25 00:00:00 0.03 66
USC00516128 2014-12-26 00:00:00 0.0 65
USC00516128 2014-12-27 00:00:00 0.0 62
USC00516128 2014-12-28 00:00:00 0.0 68
USC00516128 2014-12-29 00:00:00 0.0 67
USC00516128 2015-01-02 00:00:00 0.02 64
USC00516128 2015-01-03 00:00:00 0.85 63
USC00516128 2015-01-04 00:00:00 0.02 58
USC00516128 2015-01-05 00:00:00 0.0 58
USC00516128 2015-01-06 00:00:00 0.06 66
USC00516128 2015-01-07 00:00:00 0.0 66
USC00516128 2015-01-08 00:00:00 0.0 59
USC00516128 2015-01-09 00:00:00 0.0 63
USC00516128 2015-01-12 00:00:00 0.03 62
USC00516128 2015-01-13 00:00:00 0.01 70
USC00516128 2015-01-14 00:00:00 0.0 66
USC00516128 2015-01-15 00:00:00 0.0 68
USC00516128 2015-01-16 00:00:00 0.01 68
USC00516128 2015-01-17 00:00:00 0.0 66
USC00516128 2015-01-18 00:00:00 0.0 67
USC00516128 2015-01-19 00:00:00 0.0 66
USC00516128 2015-01-20 00:00:00 0.01 67
USC00516128 2015-01-21 00:00:00 0.0 64
USC00516128 2015-01-22 00:00:00 0.0 65
USC00516128 2015-01-23 00:00:00 0.0 72
USC00516128 2015-01-24 00:00:00 0.22 66
USC00516128 2015-01-25 00:00:00 0.33 64
USC00516128 2015-01-26 00:00:00 0.29 67
USC00516128 2015-02-03 00:00:00 0.03 72
USC00516128 2015-02-04 00:00:00 0.1 72
USC00516128 2015-02-05 00:00:00 0.03 63
USC00516128 2015-02-06 00:00:00 0.0 59
USC00516128 2015-02-07 00:00:00 0.0 60
USC00516128 2015-02-08 00:00:00 0.0 60
USC00516128 2015-02-11 00:00:00 0.0 62
USC00516128 2015-02-12 00:00:00 0.0 63
USC00516128 2015-02-13 00:00:00 0.0 67
USC00516128 2015-02-18 00:00:00 0.01 64
USC00516128 2015-02-19 00:00:00 0.0 68
USC00516128 2015-02-20 00:00:00 0.03 69
USC00516128 2015-02-21 00:00:00 0.26 68
USC00516128 2015-02-22 00:00:00 0.0 69

USC00516128 2015-02-23 00:00:00 0.03 71
USC00516128 2015-02-24 00:00:00 0.03 71
USC00516128 2015-02-25 00:00:00 0.1 69
USC00516128 2015-02-26 00:00:00 0.25 68
USC00516128 2015-02-27 00:00:00 0.01 67
USC00516128 2015-02-28 00:00:00 0.03 70
USC00516128 2015-03-01 00:00:00 0.12 68
USC00516128 2015-03-02 00:00:00 0.32 76
USC00516128 2015-03-03 00:00:00 0.03 70
USC00516128 2015-03-04 00:00:00 0.08 69
USC00516128 2015-03-05 00:00:00 2.07 65
USC00516128 2015-03-06 00:00:00 0.92 65
USC00516128 2015-03-07 00:00:00 0.02 66
USC00516128 2015-03-08 00:00:00 0.0 64
USC00516128 2015-03-09 00:00:00 0.01 61
USC00516128 2015-03-10 00:00:00 0.0 63
USC00516128 2015-03-11 00:00:00 0.0 62
USC00516128 2015-03-12 00:00:00 0.0 66
USC00516128 2015-03-13 00:00:00 0.01 64
USC00516128 2015-03-14 00:00:00 0.0 65
USC00516128 2015-03-15 00:00:00 0.0 63
USC00516128 2015-03-16 00:00:00 0.01 60
USC00516128 2015-03-17 00:00:00 0.0 64
USC00516128 2015-03-18 00:00:00 0.0 64
USC00516128 2015-03-19 00:00:00 0.0 69
USC00516128 2015-03-20 00:00:00 0.3 67
USC00516128 2015-03-23 00:00:00 0.1 74
USC00516128 2015-03-24 00:00:00 0.0 69
USC00516128 2015-03-25 00:00:00 0.0 70
USC00516128 2015-03-26 00:00:00 0.56 66
USC00516128 2015-03-27 00:00:00 0.07 69
USC00516128 2015-03-28 00:00:00 0.0 70
USC00516128 2015-03-29 00:00:00 2.02 68
USC00516128 2015-03-30 00:00:00 0.72 67
USC00516128 2015-03-31 00:00:00 1.5 68
USC00516128 2015-04-01 00:00:00 0.48 69
USC00516128 2015-04-02 00:00:00 0.47 68
USC00516128 2015-04-05 00:00:00 0.32 70
USC00516128 2015-04-08 00:00:00 0.23 70
USC00516128 2015-04-09 00:00:00 0.08 69
USC00516128 2015-04-10 00:00:00 0.0 72
USC00516128 2015-04-11 00:00:00 0.09 69
USC00516128 2015-04-12 00:00:00 0.73 69
USC00516128 2015-04-13 00:00:00 0.28 69
USC00516128 2015-04-14 00:00:00 0.74 69
USC00516128 2015-04-15 00:00:00 0.62 68
USC00516128 2015-04-16 00:00:00 0.17 70
USC00516128 2015-04-17 00:00:00 1.2 70
USC00516128 2015-04-18 00:00:00 0.05 72
USC00516128 2015-04-19 00:00:00 0.09 68
USC00516128 2015-04-22 00:00:00 1.68 73
USC00516128 2015-04-23 00:00:00 0.06 71
USC00516128 2015-04-24 00:00:00 0.37 72
USC00516128 2015-04-25 00:00:00 0.04 73
USC00516128 2015-04-26 00:00:00 0.05 70
USC00516128 2015-04-27 00:00:00 0.63 68
USC00516128 2015-04-28 00:00:00 3.26 69
USC00516128 2015-04-29 00:00:00 0.45 71
USC00516128 2015-04-30 00:00:00 0.14 69
USC00516128 2015-05-01 00:00:00 1.79 69
USC00516128 2015-05-02 00:00:00 0.0 71
USC00516128 2015-05-03 00:00:00 0.0 70
USC00516128 2015-05-04 00:00:00 0.21 77
USC00516128 2015-05-05 00:00:00 1.27 68
USC00516128 2015-05-06 00:00:00 0.02 70
USC00516128 2015-05-07 00:00:00 0.04 69
USC00516128 2015-05-08 00:00:00 1.88 67
USC00516128 2015-05-09 00:00:00 0.67 69
USC00516128 2015-05-10 00:00:00 0.92 68
USC00516128 2015-05-11 00:00:00 0.27 71
USC00516128 2015-05-12 00:00:00 0.08 70
USC00516128 2015-05-13 00:00:00 0.02 70
USC00516128 2015-05-14 00:00:00 0.84 72
USC00516128 2015-05-15 00:00:00 0.58 72
USC00516128 2015-05-16 00:00:00 0.12 72
USC00516128 2015-05-17 00:00:00 0.0 70
USC00516128 2015-05-18 00:00:00 0.22 70
USC00516128 2015-05-19 00:00:00 0.0 71
USC00516128 2015-05-20 00:00:00 0.41 69
USC00516128 2015-05-21 00:00:00 0.3 76
USC00516128 2015-05-22 00:00:00 0.0 73
USC00516128 2015-05-23 00:00:00 0.19 69
USC00516128 2015-05-24 00:00:00 0.0 69
USC00516128 2015-05-25 00:00:00 0.0 68
USC00516128 2015-05-26 00:00:00 0.04 68
USC00516128 2015-05-27 00:00:00 0.03 73
USC00516128 2015-05-28 00:00:00 0.03 71
USC00516128 2015-05-29 00:00:00 0.0 74
USC00516128 2015-05-30 00:00:00 0.01 72
USC00516128 2015-05-31 00:00:00 1.12 69
USC00516128 2015-06-01 00:00:00 2.47 69
USC00516128 2015-06-02 00:00:00 0.27 72
USC00516128 2015-06-03 00:00:00 0.01 72
USC00516128 2015-06-04 00:00:00 1.12 71
USC00516128 2015-06-05 00:00:00 0.16 76
USC00516128 2015-06-06 00:00:00 0.0 71
USC00516128 2015-06-07 00:00:00 0.01 72
USC00516128 2015-06-08 00:00:00 0.34 70
USC00516128 2015-06-09 00:00:00 0.26 72
USC00516128 2015-06-10 00:00:00 0.04 72
USC00516128 2015-06-13 00:00:00 0.0 72
USC00516128 2015-06-14 00:00:00 0.47 69
USC00516128 2015-06-15 00:00:00 0.67 70
USC00516128 2015-06-16 00:00:00 0.94 73
USC00516128 2015-06-17 00:00:00 0.48 70
USC00516128 2015-06-18 00:00:00 0.54 72
USC00516128 2015-06-19 00:00:00 0.69 72
USC00516128 2015-06-20 00:00:00 0.13 71
USC00516128 2015-06-21 00:00:00 0.1 73
USC00516128 2015-06-22 00:00:00 0.19 72
USC00516128 2015-06-23 00:00:00 0.31 73
USC00516128 2015-06-24 00:00:00 0.78 72
USC00516128 2015-06-25 00:00:00 1.36 71
USC00516128 2015-06-26 00:00:00 0.4 70
USC00516128 2015-06-27 00:00:00 0.17 75
USC00516128 2015-06-28 00:00:00 0.16 72
USC00516128 2015-06-29 00:00:00 1.62 70
USC00516128 2015-06-30 00:00:00 0.0 72
USC00516128 2015-07-01 00:00:00 0.0 75
USC00516128 2015-07-02 00:00:00 0.0 79
USC00516128 2015-07-03 00:00:00 0.0 76
USC00516128 2015-07-04 00:00:00 0.0 75
USC00516128 2015-07-05 00:00:00 0.0 74
USC00516128 2015-07-06 00:00:00 0.04 74
USC00516128 2015-07-07 00:00:00 0.13 74
USC00516128 2015-07-08 00:00:00 1.26 73
USC00516128 2015-07-09 00:00:00 0.13 75
USC00516128 2015-07-10 00:00:00 2.23 73
USC00516128 2015-07-11 00:00:00 1.57 76
USC00516128 2015-07-12 00:00:00 0.49 78
USC00516128 2015-07-13 00:00:00 2.59 74
USC00516128 2015-07-14 00:00:00 0.4 72
USC00516128 2015-07-15 00:00:00 0.68 74
USC00516128 2015-07-16 00:00:00 0.25 75
USC00516128 2015-07-17 00:00:00 0.47 76
USC00516128 2015-07-18 00:00:00 0.44 75
USC00516128 2015-07-19 00:00:00 0.74 72
USC00516128 2015-07-22 00:00:00 2.44 72
USC00516128 2015-07-23 00:00:00 0.07 75
USC00516128 2015-07-24 00:00:00 0.25 75
USC00516128 2015-07-25 00:00:00 0.1 72
USC00516128 2015-07-26 00:00:00 0.0 73
USC00516128 2015-07-27 00:00:00 0.09 74
USC00516128 2015-07-28 00:00:00 0.42 76
USC00516128 2015-07-29 00:00:00 0.12 77
USC00516128 2015-07-30 00:00:00 0.06 75
USC00516128 2015-07-31 00:00:00 0.11 75
USC00516128 2015-08-01 00:00:00 0.54 73
USC00516128 2015-08-02 00:00:00 0.0 76
USC00516128 2015-08-03 00:00:00 0.03 76
USC00516128 2015-08-04 00:00:00 0.0 76
USC00516128 2015-08-05 00:00:00 0.59 74
USC00516128 2015-08-06 00:00:00 0.5 76
USC00516128 2015-08-07 00:00:00 0.09 75
USC00516128 2015-08-08 00:00:00 0.01 77
USC00516128 2015-08-09 00:00:00 0.54 73
USC00516128 2015-08-10 00:00:00 0.41 75
USC00516128 2015-08-11 00:00:00 0.23 73
USC00516128 2015-08-12 00:00:00 0.39 77
USC00516128 2015-08-13 00:00:00 0.44 75
USC00516128 2015-08-14 00:00:00 0.92 74
USC00516128 2015-08-15 00:00:00 1.28 73
USC00516128 2015-08-16 00:00:00 0.29 75
USC00516128 2015-08-17 00:00:00 0.08 75
USC00516128 2015-08-18 00:00:00 1.59 76
USC00516128 2015-08-19 00:00:00 0.08 76
USC00516128 2015-08-20 00:00:00 0.11 77
USC00516128 2015-08-21 00:00:00 0.17 75
USC00516128 2015-08-22 00:00:00 0.11 79
USC00516128 2015-08-23 00:00:00 0.43 75
USC00516128 2015-08-24 00:00:00 4.81 72
USC00516128 2015-08-25 00:00:00 0.1 77
USC00516128 2015-08-26 00:00:00 0.79 76
USC00516128 2015-08-27 00:00:00 2.67 77
USC00516128 2015-08-28 00:00:00 0.19 76
USC00516128 2015-08-29 00:00:00 0.0 75
USC00516128 2015-08-30 00:00:00 0.04 77
USC00516128 2015-08-31 00:00:00 0.26 78
USC00516128 2015-09-01 00:00:00 0.07 77
USC00516128 2015-09-02 00:00:00 0.0 77
USC00516128 2015-09-03 00:00:00 0.16 74
USC00516128 2015-09-04 00:00:00 1.04 75
USC00516128 2015-09-05 00:00:00 0.06 79
USC00516128 2015-09-06 00:00:00 0.02 74
USC00516128 2015-09-07 00:00:00 0.32 76
USC00516128 2015-09-08 00:00:00 0.29 79
USC00516128 2015-09-09 00:00:00 0.0 78
USC00516128 2015-09-10 00:00:00 0.0 76
USC00516128 2015-09-11 00:00:00 0.52 75
USC00516128 2015-09-12 00:00:00 2.44 76
USC00516128 2015-09-13 00:00:00 0.79 76
USC00516128 2015-09-14 00:00:00 2.57 75
USC00516128 2015-09-15 00:00:00 6.83 73
USC00516128 2015-09-16 00:00:00 2.5 76
USC00516128 2015-09-17 00:00:00 0.28 75
USC00516128 2015-09-18 00:00:00 0.37 75
USC00516128 2015-09-19 00:00:00 0.21 76
USC00516128 2015-09-20 00:00:00 0.26 74
USC00516128 2015-09-21 00:00:00 1.43 75
USC00516128 2015-09-22 00:00:00 1.29 76
USC00516128 2015-09-23 00:00:00 0.58 73
USC00516128 2015-09-24 00:00:00 1.3 72
USC00516128 2015-09-25 00:00:00 0.54 73
USC00516128 2015-09-26 00:00:00 1.02 76
USC00516128 2015-09-27 00:00:00 1.72 73
USC00516128 2015-09-28 00:00:00 4.18 72
USC00516128 2015-09-29 00:00:00 0.65 73
USC00516128 2015-09-30 00:00:00 1.4 72
USC00516128 2015-10-01 00:00:00 0.41 71
USC00516128 2015-10-02 00:00:00 0.17 72
USC00516128 2015-10-03 00:00:00 0.02 73
USC00516128 2015-10-04 00:00:00 0.23 74
USC00516128 2015-10-05 00:00:00 0.51 74
USC00516128 2015-10-06 00:00:00 0.41 73
USC00516128 2015-10-07 00:00:00 0.15 73
USC00516128 2015-10-08 00:00:00 0.03 74
USC00516128 2015-10-09 00:00:00 0.0 76
USC00516128 2015-10-10 00:00:00 0.0 75
USC00516128 2015-10-13 00:00:00 0.31 73
USC00516128 2015-10-14 00:00:00 0.59 73
USC00516128 2015-10-15 00:00:00 1.77 71
USC00516128 2015-10-16 00:00:00 0.33 73
USC00516128 2015-10-17 00:00:00 1.8 76
USC00516128 2015-10-21 00:00:00 0.32 73
USC00516128 2015-10-22 00:00:00 0.28 74
USC00516128 2015-10-23 00:00:00 0.32 74
USC00516128 2015-10-24 00:00:00 0.04 79
USC00516128 2015-10-25 00:00:00 0.0 74
USC00516128 2015-10-26 00:00:00 0.01 71
USC00516128 2015-10-27 00:00:00 2.0 71
USC00516128 2015-10-28 00:00:00 0.22 74
USC00516128 2015-10-29 00:00:00 0.02 78
USC00516128 2015-10-30 00:00:00 0.0 76
USC00516128 2015-10-31 00:00:00 2.45 75
USC00516128 2015-11-01 00:00:00 1.2 77
USC00516128 2015-11-04 00:00:00 0.18 73
USC00516128 2015-11-05 00:00:00 1.09 72
USC00516128 2015-11-06 00:00:00 0.76 75
USC00516128 2015-11-07 00:00:00 1.08 72
USC00516128 2015-11-08 00:00:00 0.32 74
USC00516128 2015-11-09 00:00:00 1.42 73
USC00516128 2015-11-10 00:00:00 0.43 72
USC00516128 2015-11-11 00:00:00 0.37 72
USC00516128 2015-11-12 00:00:00 0.43 75
USC00516128 2015-11-13 00:00:00 0.68 72
USC00516128 2015-11-14 00:00:00 1.73 73
USC00516128 2015-11-15 00:00:00 0.05 72
USC00516128 2015-11-18 00:00:00 0.6 72
USC00516128 2015-11-19 00:00:00 0.34 73
USC00516128 2015-11-20 00:00:00 3.38 70
USC00516128 2015-11-21 00:00:00 1.66 73
USC00516128 2015-11-22 00:00:00 1.16 73
USC00516128 2015-11-23 00:00:00 1.97 72
USC00516128 2015-11-24 00:00:00 1.46 72
USC00516128 2015-11-25 00:00:00 0.11 72
USC00516128 2015-11-26 00:00:00 3.68 72
USC00516128 2015-11-27 00:00:00 3.26 73
USC00516128 2015-11-28 00:00:00 0.16 73
USC00516128 2015-11-29 00:00:00 0.19 72
USC00516128 2015-11-30 00:00:00 0.04 71
USC00516128 2015-12-01 00:00:00 0.03 73
USC00516128 2015-12-02 00:00:00 0.08 70
USC00516128 2015-12-03 00:00:00 0.57 71
USC00516128 2015-12-04 00:00:00 0.01 71
USC00516128 2015-12-05 00:00:00 0.05 70
USC00516128 2015-12-06 00:00:00 0.05 71
USC00516128 2015-12-07 00:00:00 0.04 69
USC00516128 2015-12-08 00:00:00 0.12 70
USC00516128 2015-12-09 00:00:00 0.36 73
USC00516128 2015-12-10 00:00:00 0.9 70
USC00516128 2015-12-11 00:00:00 0.13 72
USC00516128 2015-12-12 00:00:00 0.21 71
USC00516128 2015-12-13 00:00:00 0.0 69
USC00516128 2015-12-16 00:00:00 0.07 73
USC00516128 2015-12-17 00:00:00 0.43 69
USC00516128 2015-12-18 00:00:00 0.59 71
USC00516128 2015-12-19 00:00:00 1.19 68
USC00516128 2015-12-20 00:00:00 0.43 72
USC00516128 2015-12-23 00:00:00 1.56 70
USC00516128 2015-12-24 00:00:00 0.01 72
USC00516128 2015-12-25 00:00:00 1.19 71
USC00516128 2015-12-26 00:00:00 0.81 69
USC00516128 2015-12-27 00:00:00 2.21 71
USC00516128 2015-12-30 00:00:00 0.03 71
USC00516128 2015-12-31 00:00:00 0.1 69
USC00516128 2016-01-01 00:00:00 0.0 73
USC00516128 2016-01-02 00:00:00 0.13 69
USC00516128 2016-01-03 00:00:00 0.0 65
USC00516128 2016-01-04 00:00:00 0.0 62
USC00516128 2016-01-05 00:00:00 0.0 69
USC00516128 2016-01-06 00:00:00 1.49 68
USC00516128 2016-01-07 00:00:00 1.32 64
USC00516128 2016-01-08 00:00:00 0.0 69
USC00516128 2016-01-09 00:00:00 0.0 70
USC00516128 2016-01-10 00:00:00 0.0 64
USC00516128 2016-01-11 00:00:00 0.0 65
USC00516128 2016-01-12 00:00:00 0.0 65
USC00516128 2016-01-13 00:00:00 0.0 63
USC00516128 2016-01-14 00:00:00 0.0 66
USC00516128 2016-01-15 00:00:00 0.0 74
USC00516128 2016-01-18 00:00:00 0.0 62
USC00516128 2016-01-19 00:00:00 0.0 63
USC00516128 2016-01-20 00:00:00 0.01 67
USC00516128 2016-01-21 00:00:00 0.1 69
USC00516128 2016-01-22 00:00:00 0.0 71
USC00516128 2016-01-23 00:00:00 0.0 70
USC00516128 2016-01-24 00:00:00 0.0 67
USC00516128 2016-01-25 00:00:00 0.07 68
USC00516128 2016-01-26 00:00:00 0.38 68
USC00516128 2016-01-27 00:00:00 0.0 69
USC00516128 2016-01-28 00:00:00 0.0 67
USC00516128 2016-01-31 00:00:00 0.08 68
USC00516128 2016-02-01 00:00:00 0.15 65
USC00516128 2016-02-02 00:00:00 0.33 69
USC00516128 2016-02-03 00:00:00 0.26 69
USC00516128 2016-02-04 00:00:00 0.0 73
USC00516128 2016-02-05 00:00:00 0.08 67
USC00516128 2016-02-06 00:00:00 0.0 67
USC00516128 2016-02-07 00:00:00 0.11 65
USC00516128 2016-02-08 00:00:00 0.0 63
USC00516128 2016-02-09 00:00:00 0.0 62
USC00516128 2016-02-10 00:00:00 0.0 65
USC00516128 2016-02-11 00:00:00 0.0 69
USC00516128 2016-02-12 00:00:00 0.19 70
USC00516128 2016-02-13 00:00:00 0.22 69
USC00516128 2016-02-14 00:00:00 0.11 68
USC00516128 2016-02-15 00:00:00 0.05 68
USC00516128 2016-02-16 00:00:00 0.01 70
USC00516128 2016-02-19 00:00:00 0.58 66
USC00516128 2016-02-20 00:00:00 0.1 67
USC00516128 2016-02-21 00:00:00 0.0 70
USC00516128 2016-02-24 00:00:00 0.0 65
USC00516128 2016-02-25 00:00:00 0.0 70
USC00516128 2016-02-26 00:00:00 0.04 72
USC00516128 2016-02-27 00:00:00 0.0 69
USC00516128 2016-02-28 00:00:00 0.0 66
USC00516128 2016-02-29 00:00:00 0.0 68
USC00516128 2016-03-01 00:00:00 0.02 68
USC00516128 2016-03-02 00:00:00 0.0 69
USC00516128 2016-03-03 00:00:00 0.0 69
USC00516128 2016-03-07 00:00:00 0.0 63
USC00516128 2016-03-08 00:00:00 0.0 72
USC00516128 2016-03-09 00:00:00 0.19 66
USC00516128 2016-03-10 00:00:00 0.0 67
USC00516128 2016-03-11 00:00:00 0.16 66
USC00516128 2016-03-12 00:00:00 0.0 70
USC00516128 2016-03-13 00:00:00 0.1 69
USC00516128 2016-03-14 00:00:00 0.16 67
USC00516128 2016-03-15 00:00:00 0.57 67
USC00516128 2016-03-16 00:00:00 0.37 78
USC00516128 2016-03-17 00:00:00 0.0 65
USC00516128 2016-03-18 00:00:00 0.07 66
USC00516128 2016-03-19 00:00:00 0.22 67
USC00516128 2016-03-20 00:00:00 0.0 68
USC00516128 2016-03-21 00:00:00 0.0 70
USC00516128 2016-03-22 00:00:00 0.0 72
USC00516128 2016-03-23 00:00:00 0.0 71
USC00516128 2016-03-24 00:00:00 0.0 73
USC00516128 2016-03-25 00:00:00 0.1 69
USC00516128 2016-03-26 00:00:00 0.09 71
USC00516128 2016-03-27 00:00:00 0.0 68
USC00516128 2016-03-28 00:00:00 0.0 68
USC00516128 2016-03-29 00:00:00 0.04 69
USC00516128 2016-03-30 00:00:00 0.02 74
USC00516128 2016-03-31 00:00:00 0.0 69
USC00516128 2016-04-01 00:00:00 0.02 69
USC00516128 2016-04-02 00:00:00 0.0 72
USC00516128 2016-04-03 00:00:00 0.0 71
USC00516128 2016-04-04 00:00:00 0.29 69
USC00516128 2016-04-05 00:00:00 0.0 74
USC00516128 2016-04-06 00:00:00 0.73 67
USC00516128 2016-04-07 00:00:00 0.56 67
USC00516128 2016-04-08 00:00:00 0.29 70
USC00516128 2016-04-09 00:00:00 0.14 71
USC00516128 2016-04-10 00:00:00 0.06 72

USC00516128 2016-04-11 00:00:00 0.38 67
USC00516128 2016-04-12 00:00:00 0.8 70
USC00516128 2016-04-13 00:00:00 0.33 71
USC00516128 2016-04-14 00:00:00 0.72 71
USC00516128 2016-04-15 00:00:00 0.51 70
USC00516128 2016-04-16 00:00:00 0.3 72
USC00516128 2016-04-17 00:00:00 0.51 66
USC00516128 2016-04-18 00:00:00 5.09 72
USC00516128 2016-04-19 00:00:00 0.01 70
USC00516128 2016-04-20 00:00:00 0.19 69
USC00516128 2016-04-21 00:00:00 0.14 68
USC00516128 2016-04-22 00:00:00 0.23 69
USC00516128 2016-04-23 00:00:00 0.77 68
USC00516128 2016-04-24 00:00:00 0.99 69
USC00516128 2016-04-27 00:00:00 0.15 73
USC00516128 2016-04-28 00:00:00 0.04 77
USC00516128 2016-04-29 00:00:00 0.25 73
USC00516128 2016-04-30 00:00:00 0.1 72
USC00516128 2016-05-01 00:00:00 0.36 71
USC00516128 2016-05-02 00:00:00 0.5 72
USC00516128 2016-05-03 00:00:00 0.0 72
USC00516128 2016-05-04 00:00:00 1.04 69
USC00516128 2016-05-05 00:00:00 1.35 70
USC00516128 2016-05-08 00:00:00 0.1 68
USC00516128 2016-05-09 00:00:00 0.02 71
USC00516128 2016-05-10 00:00:00 0.58 68
USC00516128 2016-05-13 00:00:00 0.0 70
USC00516128 2016-05-14 00:00:00 0.02 71
USC00516128 2016-05-15 00:00:00 0.27 73
USC00516128 2016-05-16 00:00:00 0.08 71
USC00516128 2016-05-17 00:00:00 0.05 71
USC00516128 2016-05-18 00:00:00 0.58 70
USC00516128 2016-05-19 00:00:00 0.4 71
USC00516128 2016-05-20 00:00:00 0.71 71
USC00516128 2016-05-24 00:00:00 0.1 70
USC00516128 2016-05-25 00:00:00 0.5 69
USC00516128 2016-05-26 00:00:00 1.68 71
USC00516128 2016-05-31 00:00:00 0.8 69
USC00516128 2016-06-01 00:00:00 1.4 70
USC00516128 2016-06-02 00:00:00 0.74 71
USC00516128 2016-06-03 00:00:00 0.1 70
USC00516128 2016-06-06 00:00:00 0.47 72
USC00516128 2016-06-07 00:00:00 1.26 71
USC00516128 2016-06-08 00:00:00 0.01 71
USC00516128 2016-06-09 00:00:00 1.7 69
USC00516128 2016-06-10 00:00:00 1.4 70
USC00516128 2016-06-11 00:00:00 0.65 73
USC00516128 2016-06-12 00:00:00 0.55 75
USC00516128 2016-06-13 00:00:00 0.08 73
USC00516128 2016-06-14 00:00:00 0.19 72
USC00516128 2016-06-15 00:00:00 1.38 70
USC00516128 2016-06-16 00:00:00 0.12 70
USC00516128 2016-06-17 00:00:00 1.27 69
USC00516128 2016-06-18 00:00:00 0.72 73
USC00516128 2016-06-19 00:00:00 0.79 74
USC00516128 2016-06-20 00:00:00 0.52 72
USC00516128 2016-06-21 00:00:00 0.78 71
USC00516128 2016-06-22 00:00:00 0.2 73
USC00516128 2016-06-23 00:00:00 0.9 72
USC00516128 2016-06-26 00:00:00 0.7 74
USC00516128 2016-06-27 00:00:00 0.3 72
USC00516128 2016-06-28 00:00:00 0.25 74
USC00516128 2016-06-29 00:00:00 0.35 72
USC00516128 2016-07-05 00:00:00 0.45 71
USC00516128 2016-07-06 00:00:00 1.46 71
USC00516128 2016-07-07 00:00:00 0.92 73
USC00516128 2016-07-08 00:00:00 0.31 73
USC00516128 2016-07-09 00:00:00 0.15 71
USC00516128 2016-07-10 00:00:00 1.15 76
USC00516128 2016-07-11 00:00:00 0.11 72
USC00516128 2016-07-12 00:00:00 0.03 75
USC00516128 2016-07-13 00:00:00 0.14 75
USC00516128 2016-07-14 00:00:00 1.15 73
USC00516128 2016-07-15 00:00:00 1.7 71
USC00516128 2016-07-16 00:00:00 2.05 77
USC00516128 2016-07-17 00:00:00 0.55 74
USC00516128 2016-07-18 00:00:00 0.23 72
USC00516128 2016-07-19 00:00:00 0.41 73
USC00516128 2016-07-20 00:00:00 0.08 74
USC00516128 2016-07-24 00:00:00 2.75 75
USC00516128 2016-07-25 00:00:00 5.35 81
USC00516128 2016-07-26 00:00:00 0.03 76
USC00516128 2016-07-27 00:00:00 0.04 76
USC00516128 2016-07-28 00:00:00 0.0 76
USC00516128 2016-07-29 00:00:00 0.05 74
USC00516128 2016-07-30 00:00:00 0.4 76
USC00516128 2016-07-31 00:00:00 2.9 75
USC00516128 2016-08-01 00:00:00 2.21 73
USC00516128 2016-08-02 00:00:00 1.14 72
USC00516128 2016-08-07 00:00:00 1.3 79
USC00516128 2016-08-08 00:00:00 0.02 75
USC00516128 2016-08-09 00:00:00 0.56 73
USC00516128 2016-08-10 00:00:00 0.0 76
USC00516128 2016-08-11 00:00:00 0.04 74
USC00516128 2016-08-12 00:00:00 0.39 71
USC00516128 2016-08-13 00:00:00 0.45 74
USC00516128 2016-08-14 00:00:00 0.75 72
USC00516128 2016-08-15 00:00:00 0.95 72
USC00516128 2016-08-16 00:00:00 0.85 72
USC00516128 2016-08-17 00:00:00 0.3 77
USC00516128 2016-08-18 00:00:00 0.21 73
USC00516128 2016-08-19 00:00:00 2.3 73
USC00516128 2016-08-20 00:00:00 0.2 76
USC00516128 2016-08-21 00:00:00 1.08 74
USC00516128 2016-08-22 00:00:00 1.2 72
USC00516128 2016-08-23 00:00:00 0.7 74
USC00516128 2016-08-24 00:00:00 1.45 74
USC00516128 2016-08-25 00:00:00 0.11 77
USC00516128 2016-08-28 00:00:00 2.07 71
USC00516128 2016-08-29 00:00:00 0.9 78
USC00516128 2016-08-30 00:00:00 0.05 75
USC00516128 2016-08-31 00:00:00 2.46 76
USC00516128 2016-09-01 00:00:00 0.01 77
USC00516128 2016-09-02 00:00:00 0.03 75
USC00516128 2016-09-03 00:00:00 1.0 75
USC00516128 2016-09-04 00:00:00 0.44 73
USC00516128 2016-09-05 00:00:00 0.18 76
USC00516128 2016-09-06 00:00:00 1.0 73
USC00516128 2016-09-07 00:00:00 1.35 74
USC00516128 2016-09-08 00:00:00 0.15 74
USC00516128 2016-09-09 00:00:00 0.35 75
USC00516128 2016-09-10 00:00:00 1.16 75
USC00516128 2016-09-11 00:00:00 0.6 71
USC00516128 2016-09-12 00:00:00 1.04 72
USC00516128 2016-09-13 00:00:00 1.2 75
USC00516128 2016-09-14 00:00:00 6.7 73
USC00516128 2016-09-15 00:00:00 3.35 73
USC00516128 2016-09-16 00:00:00 0.61 73
USC00516128 2016-09-17 00:00:00 0.23 76
USC00516128 2016-09-18 00:00:00 0.42 75
USC00516128 2016-09-19 00:00:00 0.25 70
USC00516128 2016-09-20 00:00:00 0.43 70
USC00516128 2016-09-21 00:00:00 1.02 73
USC00516128 2016-09-22 00:00:00 0.75 73
USC00516128 2016-09-23 00:00:00 0.33 73
USC00516128 2016-09-24 00:00:00 0.27 77
USC00516128 2016-09-25 00:00:00 0.04 76
USC00516128 2016-09-26 00:00:00 1.02 74
USC00516128 2016-09-27 00:00:00 1.0 74
USC00516128 2016-09-28 00:00:00 0.05 77
USC00516128 2016-09-29 00:00:00 1.49 77
USC00516128 2016-09-30 00:00:00 0.38 73
USC00516128 2016-10-01 00:00:00 1.02 74
USC00516128 2016-10-02 00:00:00 0.61 73
USC00516128 2016-10-03 00:00:00 0.46 76
USC00516128 2016-10-04 00:00:00 3.46 74
USC00516128 2016-10-05 00:00:00 0.81 75
USC00516128 2016-10-06 00:00:00 0.04 75
USC00516128 2016-10-07 00:00:00 0.01 73
USC00516128 2016-10-08 00:00:00 0.04 74
USC00516128 2016-10-09 00:00:00 0.0 77
USC00516128 2016-10-10 00:00:00 0.0 74
USC00516128 2016-10-11 00:00:00 0.35 74
USC00516128 2016-10-12 00:00:00 0.02 78
USC00516128 2016-10-13 00:00:00 0.06 75
USC00516128 2016-10-14 00:00:00 0.0 73
USC00516128 2016-10-15 00:00:00 0.33 74
USC00516128 2016-10-16 00:00:00 0.0 77
USC00516128 2016-10-17 00:00:00 0.38 70
USC00516128 2016-10-18 00:00:00 0.48 74
USC00516128 2016-10-19 00:00:00 0.0 70
USC00516128 2016-10-20 00:00:00 1.0 73
USC00516128 2016-10-21 00:00:00 0.09 74
USC00516128 2016-10-22 00:00:00 1.37 75
USC00516128 2016-10-23 00:00:00 0.24 72
USC00516128 2016-10-24 00:00:00 0.7 71
USC00516128 2016-10-25 00:00:00 0.4 74
USC00516128 2016-10-26 00:00:00 0.0 75
USC00516128 2016-10-27 00:00:00 1.25 71
USC00516128 2016-10-28 00:00:00 0.37 68
USC00516128 2016-10-29 00:00:00 0.25 71
USC00516128 2016-10-30 00:00:00 0.95 76
USC00516128 2016-10-31 00:00:00 1.35 69
USC00516128 2016-11-01 00:00:00 0.09 73
USC00516128 2016-11-02 00:00:00 0.04 76
USC00516128 2016-11-03 00:00:00 0.02 74
USC00516128 2016-11-04 00:00:00 0.06 74
USC00516128 2016-11-05 00:00:00 0.38 69
USC00516128 2016-11-06 00:00:00 0.05 77
USC00516128 2016-11-07 00:00:00 0.05 71
USC00516128 2016-11-08 00:00:00 0.53 71
USC00516128 2016-11-09 00:00:00 0.04 71
USC00516128 2016-11-10 00:00:00 0.01 71
USC00516128 2016-11-11 00:00:00 0.0 67
USC00516128 2016-11-12 00:00:00 0.0 73
USC00516128 2016-11-13 00:00:00 0.0 72
USC00516128 2016-11-14 00:00:00 0.02 74
USC00516128 2016-11-15 00:00:00 0.05 72
USC00516128 2016-11-16 00:00:00 0.91 72
USC00516128 2016-11-17 00:00:00 0.02 75
USC00516128 2016-11-21 00:00:00 2.87 71
USC00516128 2016-11-22 00:00:00 2.11 73
USC00516128 2016-11-23 00:00:00 0.22 69
USC00516128 2016-11-24 00:00:00 0.72 69
USC00516128 2016-11-25 00:00:00 1.03 69
USC00516128 2016-11-26 00:00:00 0.3 70
USC00516128 2016-11-27 00:00:00 0.29 69
USC00516128 2016-11-28 00:00:00 0.69 71
USC00516128 2016-11-29 00:00:00 0.2 67
USC00516128 2016-11-30 00:00:00 0.79 72
USC00516128 2016-12-01 00:00:00 0.72 71
USC00516128 2016-12-02 00:00:00 1.27 71
USC00516128 2016-12-03 00:00:00 1.62 67
USC00516128 2016-12-04 00:00:00 0.31 76
USC00516128 2016-12-05 00:00:00 1.6 67
USC00516128 2016-12-06 00:00:00 0.0 67
USC00516128 2016-12-07 00:00:00 0.02 68
USC00516128 2016-12-08 00:00:00 0.03 71
USC00516128 2016-12-09 00:00:00 0.42 68
USC00516128 2016-12-10 00:00:00 0.04 68
USC00516128 2016-12-11 00:00:00 0.13 69
USC00516128 2016-12-12 00:00:00 0.01 65
USC00516128 2016-12-13 00:00:00 0.09 70
USC00516128 2016-12-14 00:00:00 0.33 69
USC00516128 2016-12-15 00:00:00 0.03 64
USC00516128 2016-12-16 00:00:00 0.0 60
USC00516128 2016-12-19 00:00:00 0.15 72
USC00516128 2016-12-20 00:00:00 0.0 73
USC00516128 2016-12-21 00:00:00 0.55 70
USC00516128 2016-12-22 00:00:00 1.24 68
USC00516128 2016-12-23 00:00:00 0.83 69
USC00516128 2016-12-24 00:00:00 1.08 69
USC00516128 2016-12-25 00:00:00 0.38 69
USC00516128 2016-12-26 00:00:00 1.48 71
USC00516128 2016-12-27 00:00:00 0.14 71
USC00516128 2016-12-28 00:00:00 0.14 71
USC00516128 2016-12-29 00:00:00 1.03 69
USC00516128 2016-12-30 00:00:00 2.37 65
USC00516128 2016-12-31 00:00:00 0.9 65
USC00516128 2017-01-01 00:00:00 0.03 68
USC00516128 2017-01-02 00:00:00 0.0 70
USC00516128 2017-01-03 00:00:00 0.0 71
USC00516128 2017-01-04 00:00:00 0.0 70
USC00516128 2017-01-05 00:00:00 0.47 71
USC00516128 2017-01-06 00:00:00 0.1 65
USC00516128 2017-01-07 00:00:00 0.0 70
USC00516128 2017-01-08 00:00:00 0.03 66
USC00516128 2017-01-09 00:00:00 0.0 69
USC00516128 2017-01-10 00:00:00 0.0 64
USC00516128 2017-01-11 00:00:00 0.0 66
USC00516128 2017-01-12 00:00:00 0.0 68
USC00516128 2017-01-13 00:00:00 0.0 67
USC00516128 2017-01-14 00:00:00 0.0 70
USC00516128 2017-01-15 00:00:00 0.01 68
USC00516128 2017-01-16 00:00:00 0.0 68
USC00516128 2017-01-17 00:00:00 0.0 69
USC00516128 2017-01-18 00:00:00 0.07 73
USC00516128 2017-01-19 00:00:00 0.0 71
USC00516128 2017-01-20 00:00:00 0.0 67
USC00516128 2017-01-21 00:00:00 0.08 67
USC00516128 2017-01-22 00:00:00 0.72 68
USC00516128 2017-01-23 00:00:00 0.85 70
USC00516128 2017-01-24 00:00:00 1.85 67
USC00516128 2017-01-25 00:00:00 2.64 69
USC00516128 2017-01-26 00:00:00 0.1 67
USC00516128 2017-01-27 00:00:00 0.03 69
USC00516128 2017-01-28 00:00:00 0.0 64
USC00516128 2017-01-29 00:00:00 0.55 67
USC00516128 2017-01-30 00:00:00 0.0 66
USC00516128 2017-01-31 00:00:00 0.0 65
USC00516128 2017-02-01 00:00:00 0.0 65
USC00516128 2017-02-02 00:00:00 0.0 60
USC00516128 2017-02-05 00:00:00 0.0 69
USC00516128 2017-02-06 00:00:00 0.0 73
USC00516128 2017-02-07 00:00:00 1.79 68
USC00516128 2017-02-08 00:00:00 0.0 68
USC00516128 2017-02-09 00:00:00 0.0 64
USC00516128 2017-02-10 00:00:00 0.0 70
USC00516128 2017-02-11 00:00:00 0.73 66
USC00516128 2017-02-12 00:00:00 1.83 65
USC00516128 2017-02-13 00:00:00 0.0 68
USC00516128 2017-02-14 00:00:00 0.01 79
USC00516128 2017-02-15 00:00:00 0.07 71
USC00516128 2017-02-16 00:00:00 0.13 72
USC00516128 2017-02-19 00:00:00 0.1 68
USC00516128 2017-02-20 00:00:00 0.0 69
USC00516128 2017-02-21 00:00:00 0.07 65
USC00516128 2017-02-22 00:00:00 0.32 69
USC00516128 2017-02-23 00:00:00 0.0 72
USC00516128 2017-02-24 00:00:00 0.0 68
USC00516128 2017-02-25 00:00:00 0.12 66
USC00516128 2017-02-26 00:00:00 0.0 64
USC00516128 2017-02-27 00:00:00 0.0 69
USC00516128 2017-02-28 00:00:00 0.58 69
USC00516128 2017-03-01 00:00:00 2.0 64
USC00516128 2017-03-02 00:00:00 0.58 72
USC00516128 2017-03-03 00:00:00 0.56 78
USC00516128 2017-03-04 00:00:00 0.0 70
USC00516128 2017-03-05 00:00:00 0.35 68
USC00516128 2017-03-06 00:00:00 0.0 76
USC00516128 2017-03-07 00:00:00 0.0 72
USC00516128 2017-03-08 00:00:00 0.0 68
USC00516128 2017-03-09 00:00:00 0.01 72
USC00516128 2017-03-10 00:00:00 0.0 65
USC00516128 2017-03-11 00:00:00 0.0 82
USC00516128 2017-03-14 00:00:00 0.0 75
USC00516128 2017-03-15 00:00:00 0.0 76
USC00516128 2017-03-16 00:00:00 0.0 77
USC00516128 2017-03-19 00:00:00 0.0 74
USC00516128 2017-03-20 00:00:00 0.0 74
USC00516128 2017-03-21 00:00:00 0.0 72
USC00516128 2017-03-22 00:00:00 0.0 72
USC00516128 2017-03-23 00:00:00 0.03 70
USC00516128 2017-03-24 00:00:00 0.17 70
USC00516128 2017-03-25 00:00:00 0.48 72
USC00516128 2017-03-26 00:00:00 0.0 72
USC00516128 2017-03-27 00:00:00 0.0 74
USC00516128 2017-03-28 00:00:00 0.68 69
USC00516128 2017-03-29 00:00:00 0.07 69
USC00516128 2017-04-01 00:00:00 0.2 69
USC00516128 2017-04-02 00:00:00 0.0 71
USC00516128 2017-04-03 00:00:00 0.23 73
USC00516128 2017-04-04 00:00:00 0.02 75
USC00516128 2017-04-05 00:00:00 0.45 69
USC00516128 2017-04-06 00:00:00 0.0 72
USC00516128 2017-04-09 00:00:00 0.0 70
USC00516128 2017-04-10 00:00:00 0.0 72
USC00516128 2017-04-11 00:00:00 0.25 71
USC00516128 2017-04-12 00:00:00 0.65 70
USC00516128 2017-04-13 00:00:00 0.23 73
USC00516128 2017-04-14 00:00:00 2.82 72
USC00516128 2017-04-15 00:00:00 0.9 70
USC00516128 2017-04-16 00:00:00 0.11 71
USC00516128 2017-04-17 00:00:00 1.3 69
USC00516128 2017-04-18 00:00:00 0.98 71
USC00516128 2017-04-19 00:00:00 0.14 71
USC00516128 2017-04-20 00:00:00 0.0 69
USC00516128 2017-04-21 00:00:00 1.84 70
USC00516128 2017-04-22 00:00:00 1.35 73
USC00516128 2017-04-23 00:00:00 0.35 70
USC00516128 2017-04-24 00:00:00 0.05 75
USC00516128 2017-04-25 00:00:00 0.0 74
USC00516128 2017-04-26 00:00:00 0.22 77
USC00516128 2017-04-27 00:00:00 0.11 76
USC00516128 2017-04-28 00:00:00 0.79 71
USC00516128 2017-04-29 00:00:00 0.0 68
USC00516128 2017-04-30 00:00:00 0.8 58
USC00516128 2017-05-01 00:00:00 0.25 73
USC00516128 2017-05-02 00:00:00 0.0 79
USC00516128 2017-05-05 00:00:00 0.1 74
USC00516128 2017-05-06 00:00:00 0.0 74
USC00516128 2017-05-07 00:00:00 0.03 70
USC00516128 2017-05-08 00:00:00 1.11 66
USC00516128 2017-05-09 00:00:00 0.23 72
USC00516128 2017-05-10 00:00:00 0.55 72
USC00516128 2017-05-11 00:00:00 0.44 78
USC00516128 2017-05-12 00:00:00 0.1 70
USC00516128 2017-05-13 00:00:00 0.1 71
USC00516128 2017-05-14 00:00:00 1.0 70
USC00516128 2017-05-15 00:00:00 0.6 72
USC00516128 2017-05-16 00:00:00 0.3 71
USC00516128 2017-05-17 00:00:00 0.06 71
USC00516128 2017-05-18 00:00:00 0.0 69
USC00516128 2017-05-21 00:00:00 0.0 69
USC00516128 2017-05-22 00:00:00 0.3 72
USC00516128 2017-05-23 00:00:00 0.44 69
USC00516128 2017-05-24 00:00:00 2.17 70
USC00516128 2017-05-25 00:00:00 0.88 75
USC00516128 2017-05-26 00:00:00 0.0 72
USC00516128 2017-05-27 00:00:00 0.5 72
USC00516128 2017-05-28 00:00:00 0.0 73
USC00516128 2017-06-01 00:00:00 0.01 74
USC00516128 2017-06-04 00:00:00 0.82 77
USC00516128 2017-06-05 00:00:00 0.01 74
USC00516128 2017-06-06 00:00:00 0.0 74
USC00516128 2017-06-07 00:00:00 0.01 79
USC00516128 2017-06-08 00:00:00 0.0 75
USC00516128 2017-06-11 00:00:00 0.7 76
USC00516128 2017-06-12 00:00:00 0.81 74
USC00516128 2017-06-13 00:00:00 0.65 73
USC00516128 2017-06-14 00:00:00 0.81 74
USC00516128 2017-06-15 00:00:00 1.69 77
USC00516128 2017-06-16 00:00:00 0.1 74
USC00516128 2017-06-17 00:00:00 0.1 72
USC00516128 2017-06-18 00:00:00 0.7 77

USC00516128 2017-06-19 00:00:00 0.4 76
USC00516128 2017-06-20 00:00:00 0.31 74
USC00516128 2017-06-21 00:00:00 0.3 75
USC00516128 2017-06-22 00:00:00 0.28 76
USC00516128 2017-06-23 00:00:00 0.5 71
USC00516128 2017-06-24 00:00:00 0.22 73
USC00516128 2017-06-25 00:00:00 0.5 79
USC00516128 2017-06-26 00:00:00 0.02 79
USC00516128 2017-06-27 00:00:00 0.1 74
USC00516128 2017-06-28 00:00:00 0.02 74
USC00516128 2017-06-29 00:00:00 0.04 76
USC00516128 2017-06-30 00:00:00 0.2 75
USC00516128 2017-07-01 00:00:00 0.1 74
USC00516128 2017-07-02 00:00:00 0.5 78
USC00516128 2017-07-03 00:00:00 0.4 77
USC00516128 2017-07-04 00:00:00 0.0 77
USC00516128 2017-07-05 00:00:00 0.0 75
USC00516128 2017-07-06 00:00:00 0.02 74
USC00516128 2017-07-07 00:00:00 0.3 74
USC00516128 2017-07-08 00:00:00 0.02 71
USC00516128 2017-07-09 00:00:00 0.0 78
USC00516128 2017-07-10 00:00:00 0.02 77
USC00516128 2017-07-11 00:00:00 0.0 74
USC00516128 2017-07-12 00:00:00 0.05 72
USC00516128 2017-07-13 00:00:00 0.68 77
USC00516128 2017-07-14 00:00:00 0.68 76
USC00516128 2017-07-15 00:00:00 0.1 78
USC00516128 2017-07-16 00:00:00 0.5 75
USC00516128 2017-07-17 00:00:00 0.39 72
USC00516128 2017-07-18 00:00:00 2.4 77
USC00516128 2017-07-19 00:00:00 0.27 74
USC00516128 2017-07-20 00:00:00 0.7 75
USC00516128 2017-07-21 00:00:00 0.1 72
USC00516128 2017-07-22 00:00:00 4.0 72
USC00516128 2017-07-23 00:00:00 0.8 78
USC00516128 2017-07-24 00:00:00 0.84 77
USC00516128 2017-07-25 00:00:00 0.3 79
USC00516128 2017-07-26 00:00:00 0.3 73
USC00516128 2017-07-27 00:00:00 0.0 75
USC00516128 2017-07-28 00:00:00 0.4 73
USC00516128 2017-07-29 00:00:00 0.3 77
USC00516128 2017-07-30 00:00:00 0.3 79
USC00516128 2017-07-31 00:00:00 0.0 74
USC00516128 2017-08-02 00:00:00 0.25 80
USC00516128 2017-08-03 00:00:00 0.06 76
USC00516128 2017-08-07 00:00:00 0.05 78
USC00516128 2017-08-08 00:00:00 0.34 74
USC00516128 2017-08-09 00:00:00 0.15 71
USC00516128 2017-08-10 00:00:00 0.07 75
USC00516128 2017-08-12 00:00:00 0.14 74
USC00516128 2017-08-14 00:00:00 0.22 79
USC00516128 2017-08-15 00:00:00 0.42 70
USC00516128 2017-08-16 00:00:00 0.42 71
USC00516128 2017-08-17 00:00:00 0.13 72
USC00516128 2017-08-19 00:00:00 0.09 71
USC00516128 2017-08-21 00:00:00 0.56 76
USC00516128 2017-08-22 00:00:00 0.5 76
USC00516128 2017-08-23 00:00:00 0.45 76

In [11]:
sess.commit()

2018-05-08 18:31:12,228 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2018-05-08 18:31:12,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,248 INFO sqlalchemy.engine.base.Engine ('2010-01-01 00:00:00.000000', 0.28, 67)
2018-05-08 18:31:12,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,256 INFO sqlalchemy.engine.base.Engine ('2010-01-02 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:12,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,260 INFO sqlalchemy.engine.base.Engine ('2010-01-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,262 INFO sqlalchemy.engine.base.Engine ('2010-01-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,264 INFO sqlalchemy.engine.base.Engine ('2010-01-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,266 INFO sqlalchemy.engine.base.Engine ('2010-01-06 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:12,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,268 INFO sqlalchemy.engine.base.Engine ('2010-01-07 00:00:00.000000', 0.38, 70)
2018-05-08 18:31:12,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,273 INFO sqlalchemy.engine.base.Engine ('2010-01-08 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:12,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,281 INFO sqlalchemy.engine.base.Engine ('2010-01-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:12,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,285 INFO sqlalchemy.engine.base.Engine ('2010-01-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,287 INFO sqlalchemy.engine.base.Engine ('2010-01-11 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:12,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,290 INFO sqlalchemy.engine.base.Engine ('2010-01-12 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:12,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,293 INFO sqlalchemy.engine.base.Engine ('2010-01-13 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:12,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,296 INFO sqlalchemy.engine.base.Engine ('2010-01-14 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:12,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,298 INFO sqlalchemy.engine.base.Engine ('2010-01-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:12,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,300 INFO sqlalchemy.engine.base.Engine ('2010-01-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,302 INFO sqlalchemy.engine.base.Engine ('2010-01-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:12,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,303 INFO sqlalchemy.engine.base.Engine ('2010-01-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,305 INFO sqlalchemy.engine.base.Engine ('2010-01-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,307 INFO sqlalchemy.engine.base.Engine ('2010-01-20 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:12,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,310 INFO sqlalchemy.engine.base.Engine ('2010-01-21 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:12,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,321 INFO sqlalchemy.engine.base.Engine ('2010-01-22 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:12,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,324 INFO sqlalchemy.engine.base.Engine ('2010-01-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,327 INFO sqlalchemy.engine.base.Engine ('2010-01-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,329 INFO sqlalchemy.engine.base.Engine ('2010-01-25 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:12,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,331 INFO sqlalchemy.engine.base.Engine ('2010-01-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:12,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,334 INFO sqlalchemy.engine.base.Engine ('2010-01-27 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:12,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,336 INFO sqlalchemy.engine.base.Engine ('2010-01-28 00:00:00.000000', 0.19, 68)
2018-05-08 18:31:12,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,338 INFO sqlalchemy.engine.base.Engine ('2010-01-29 00:00:00.000000', 0.19, 68)
2018-05-08 18:31:12,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,340 INFO sqlalchemy.engine.base.Engine ('2010-01-30 00:00:00.000000', 1.7, 69)
2018-05-08 18:31:12,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,342 INFO sqlalchemy.engine.base.Engine ('2010-01-31 00:00:00.000000', 0.28, 73)
2018-05-08 18:31:12,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,344 INFO sqlalchemy.engine.base.Engine ('2010-02-01 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:12,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,346 INFO sqlalchemy.engine.base.Engine ('2010-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,348 INFO sqlalchemy.engine.base.Engine ('2010-02-03 00:00:00.000000', 0.31, 66)
2018-05-08 18:31:12,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,350 INFO sqlalchemy.engine.base.Engine ('2010-02-04 00:00:00.000000', 0.0, 69)

2018-05-08 18:31:12,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,353 INFO sqlalchemy.engine.base.Engine ('2010-02-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,358 INFO sqlalchemy.engine.base.Engine ('2010-02-06 00:00:00.000000', 0.06, 66)
2018-05-08 18:31:12,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,362 INFO sqlalchemy.engine.base.Engine ('2010-02-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:12,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,364 INFO sqlalchemy.engine.base.Engine ('2010-02-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,366 INFO sqlalchemy.engine.base.Engine ('2010-02-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,368 INFO sqlalchemy.engine.base.Engine ('2010-02-10 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:12,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,370 INFO sqlalchemy.engine.base.Engine ('2010-02-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:12,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,374 INFO sqlalchemy.engine.base.Engine ('2010-02-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,377 INFO sqlalchemy.engine.base.Engine ('2010-02-16 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:12,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,380 INFO sqlalchemy.engine.base.Engine ('2010-02-17 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:12,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,382 INFO sqlalchemy.engine.base.Engine ('2010-02-18 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:12,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,383 INFO sqlalchemy.engine.base.Engine ('2010-02-19 00:00:00.000000', 0.05, 63)
2018-05-08 18:31:12,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,385 INFO sqlalchemy.engine.base.Engine ('2010-02-20 00:00:00.000000', 0.17, 66)
2018-05-08 18:31:12,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,387 INFO sqlalchemy.engine.base.Engine ('2010-02-21 00:00:00.000000', 0.04, 66)
2018-05-08 18:31:12,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,389 INFO sqlalchemy.engine.base.Engine ('2010-02-22 00:00:00.000000', 0.87, 66)
2018-05-08 18:31:12,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,390 INFO sqlalchemy.engine.base.Engine ('2010-02-23 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:12,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,392 INFO sqlalchemy.engine.base.Engine ('2010-02-24 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:12,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,430 INFO sqlalchemy.engine.base.Engine ('2010-02-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,434 INFO sqlalchemy.engine.base.Engine ('2010-02-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,437 INFO sqlalchemy.engine.base.Engine ('2010-02-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,439 INFO sqlalchemy.engine.base.Engine ('2010-02-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,441 INFO sqlalchemy.engine.base.Engine ('2010-03-01 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:12,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,445 INFO sqlalchemy.engine.base.Engine ('2010-03-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,447 INFO sqlalchemy.engine.base.Engine ('2010-03-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,449 INFO sqlalchemy.engine.base.Engine ('2010-03-04 00:00:00.000000', 0.33, 68)
2018-05-08 18:31:12,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,451 INFO sqlalchemy.engine.base.Engine ('2010-03-05 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:12,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,453 INFO sqlalchemy.engine.base.Engine ('2010-03-06 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:12,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,455 INFO sqlalchemy.engine.base.Engine ('2010-03-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,457 INFO sqlalchemy.engine.base.Engine ('2010-03-08 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:12,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,459 INFO sqlalchemy.engine.base.Engine ('2010-03-09 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:12,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,461 INFO sqlalchemy.engine.base.Engine ('2010-03-10 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:12,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,462 INFO sqlalchemy.engine.base.Engine ('2010-03-11 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:12,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,465 INFO sqlalchemy.engine.base.Engine ('2010-03-12 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:12,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,467 INFO sqlalchemy.engine.base.Engine ('2010-03-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:12,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,468 INFO sqlalchemy.engine.base.Engine ('2010-03-14 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:12,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,470 INFO sqlalchemy.engine.base.Engine ('2010-03-15 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:12,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,471 INFO sqlalchemy.engine.base.Engine ('2010-03-16 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:12,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,473 INFO sqlalchemy.engine.base.Engine ('2010-03-17 00:00:00.000000', 0.4, 66)
2018-05-08 18:31:12,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,475 INFO sqlalchemy.engine.base.Engine ('2010-03-18 00:00:00.000000', 0.44, 66)
2018-05-08 18:31:12,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,477 INFO sqlalchemy.engine.base.Engine ('2010-03-19 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:12,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,478 INFO sqlalchemy.engine.base.Engine ('2010-03-20 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:12,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,480 INFO sqlalchemy.engine.base.Engine ('2010-03-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,481 INFO sqlalchemy.engine.base.Engine ('2010-03-22 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:12,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,483 INFO sqlalchemy.engine.base.Engine ('2010-03-23 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:12,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,485 INFO sqlalchemy.engine.base.Engine ('2010-03-24 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:12,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,486 INFO sqlalchemy.engine.base.Engine ('2010-03-25 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:12,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,488 INFO sqlalchemy.engine.base.Engine ('2010-03-26 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:12,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,490 INFO sqlalchemy.engine.base.Engine ('2010-03-27 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:12,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,492 INFO sqlalchemy.engine.base.Engine ('2010-03-28 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:12,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,495 INFO sqlalchemy.engine.base.Engine ('2010-03-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,498 INFO sqlalchemy.engine.base.Engine ('2010-03-30 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:12,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,501 INFO sqlalchemy.engine.base.Engine ('2010-03-31 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:12,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,504 INFO sqlalchemy.engine.base.Engine ('2010-04-01 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:12,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,506 INFO sqlalchemy.engine.base.Engine ('2010-04-02 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:12,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,508 INFO sqlalchemy.engine.base.Engine ('2010-04-03 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:12,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,512 INFO sqlalchemy.engine.base.Engine ('2010-04-04 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:12,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,513 INFO sqlalchemy.engine.base.Engine ('2010-04-05 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:12,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,515 INFO sqlalchemy.engine.base.Engine ('2010-04-06 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:12,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,517 INFO sqlalchemy.engine.base.Engine ('2010-04-07 00:00:00.000000', 0.51, 70)
2018-05-08 18:31:12,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,519 INFO sqlalchemy.engine.base.Engine ('2010-04-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,521 INFO sqlalchemy.engine.base.Engine ('2010-04-09 00:00:00.000000', 0.24, 69)
2018-05-08 18:31:12,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,522 INFO sqlalchemy.engine.base.Engine ('2010-04-10 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:12,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,524 INFO sqlalchemy.engine.base.Engine ('2010-04-11 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:12,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,526 INFO sqlalchemy.engine.base.Engine ('2010-04-12 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:12,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,527 INFO sqlalchemy.engine.base.Engine ('2010-04-13 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:12,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,529 INFO sqlalchemy.engine.base.Engine ('2010-04-14 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:12,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,531 INFO sqlalchemy.engine.base.Engine ('2010-04-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:12,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,533 INFO sqlalchemy.engine.base.Engine ('2010-04-16 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:12,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,534 INFO sqlalchemy.engine.base.Engine ('2010-04-17 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:12,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,536 INFO sqlalchemy.engine.base.Engine ('2010-04-18 00:00:00.000000', 0.0, 70)

2018-05-08 18:31:12,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,538 INFO sqlalchemy.engine.base.Engine ('2010-04-19 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:12,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,540 INFO sqlalchemy.engine.base.Engine ('2010-04-20 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:12,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,541 INFO sqlalchemy.engine.base.Engine ('2010-04-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,543 INFO sqlalchemy.engine.base.Engine ('2010-04-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,545 INFO sqlalchemy.engine.base.Engine ('2010-04-23 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:12,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,547 INFO sqlalchemy.engine.base.Engine ('2010-04-24 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:12,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,550 INFO sqlalchemy.engine.base.Engine ('2010-04-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,552 INFO sqlalchemy.engine.base.Engine ('2010-04-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,555 INFO sqlalchemy.engine.base.Engine ('2010-04-27 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:12,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,559 INFO sqlalchemy.engine.base.Engine ('2010-04-28 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:12,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,562 INFO sqlalchemy.engine.base.Engine ('2010-04-29 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:12,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,564 INFO sqlalchemy.engine.base.Engine ('2010-04-30 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:12,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,566 INFO sqlalchemy.engine.base.Engine ('2010-05-01 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:12,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,569 INFO sqlalchemy.engine.base.Engine ('2010-05-02 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:12,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,570 INFO sqlalchemy.engine.base.Engine ('2010-05-03 00:00:00.000000', 0.89, 72)
2018-05-08 18:31:12,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,573 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:12,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,574 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,576 INFO sqlalchemy.engine.base.Engine ('2010-05-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,578 INFO sqlalchemy.engine.base.Engine ('2010-05-07 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:12,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,579 INFO sqlalchemy.engine.base.Engine ('2010-05-08 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:12,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,581 INFO sqlalchemy.engine.base.Engine ('2010-05-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,583 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,584 INFO sqlalchemy.engine.base.Engine ('2010-05-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,586 INFO sqlalchemy.engine.base.Engine ('2010-05-12 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:12,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,588 INFO sqlalchemy.engine.base.Engine ('2010-05-13 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:12,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,589 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,591 INFO sqlalchemy.engine.base.Engine ('2010-05-15 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:12,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,593 INFO sqlalchemy.engine.base.Engine ('2010-05-16 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:12,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,594 INFO sqlalchemy.engine.base.Engine ('2010-05-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,596 INFO sqlalchemy.engine.base.Engine ('2010-05-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,598 INFO sqlalchemy.engine.base.Engine ('2010-05-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,600 INFO sqlalchemy.engine.base.Engine ('2010-05-20 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:12,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,601 INFO sqlalchemy.engine.base.Engine ('2010-05-21 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:12,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,603 INFO sqlalchemy.engine.base.Engine ('2010-05-22 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:12,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,605 INFO sqlalchemy.engine.base.Engine ('2010-05-23 00:00:00.000000', 0.04, 74)

2018-05-08 18:31:12,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,607 INFO sqlalchemy.engine.base.Engine ('2010-05-24 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:12,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,608 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:12,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,610 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:12,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,612 INFO sqlalchemy.engine.base.Engine ('2010-05-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,614 INFO sqlalchemy.engine.base.Engine ('2010-05-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,615 INFO sqlalchemy.engine.base.Engine ('2010-05-29 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:12,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,617 INFO sqlalchemy.engine.base.Engine ('2010-05-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,618 INFO sqlalchemy.engine.base.Engine ('2010-05-31 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,620 INFO sqlalchemy.engine.base.Engine ('2010-06-01 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:12,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,622 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,623 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,625 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,680 INFO sqlalchemy.engine.base.Engine ('2010-06-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,682 INFO sqlalchemy.engine.base.Engine ('2010-06-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,684 INFO sqlalchemy.engine.base.Engine ('2010-06-07 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,685 INFO sqlalchemy.engine.base.Engine ('2010-06-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,687 INFO sqlalchemy.engine.base.Engine ('2010-06-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,690 INFO sqlalchemy.engine.base.Engine ('2010-06-10 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,693 INFO sqlalchemy.engine.base.Engine ('2010-06-11 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:12,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,695 INFO sqlalchemy.engine.base.Engine ('2010-06-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,697 INFO sqlalchemy.engine.base.Engine ('2010-06-13 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:12,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,699 INFO sqlalchemy.engine.base.Engine ('2010-06-14 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:12,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,701 INFO sqlalchemy.engine.base.Engine ('2010-06-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,702 INFO sqlalchemy.engine.base.Engine ('2010-06-16 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:12,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,704 INFO sqlalchemy.engine.base.Engine ('2010-06-17 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,706 INFO sqlalchemy.engine.base.Engine ('2010-06-18 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:12,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,707 INFO sqlalchemy.engine.base.Engine ('2010-06-19 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:12,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,711 INFO sqlalchemy.engine.base.Engine ('2010-06-20 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,713 INFO sqlalchemy.engine.base.Engine ('2010-06-21 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:12,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,715 INFO sqlalchemy.engine.base.Engine ('2010-06-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,717 INFO sqlalchemy.engine.base.Engine ('2010-06-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,720 INFO sqlalchemy.engine.base.Engine ('2010-06-24 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:12,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,722 INFO sqlalchemy.engine.base.Engine ('2010-06-25 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:12,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,724 INFO sqlalchemy.engine.base.Engine ('2010-06-26 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:12,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,726 INFO sqlalchemy.engine.base.Engine ('2010-06-27 00:00:00.000000', 0.03, 76)

2018-05-08 18:31:12,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,729 INFO sqlalchemy.engine.base.Engine ('2010-06-28 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:12,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,730 INFO sqlalchemy.engine.base.Engine ('2010-06-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,732 INFO sqlalchemy.engine.base.Engine ('2010-06-30 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:12,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,734 INFO sqlalchemy.engine.base.Engine ('2010-07-01 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:12,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,736 INFO sqlalchemy.engine.base.Engine ('2010-07-02 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:12,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,737 INFO sqlalchemy.engine.base.Engine ('2010-07-03 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:12,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,739 INFO sqlalchemy.engine.base.Engine ('2010-07-04 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:12,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,741 INFO sqlalchemy.engine.base.Engine ('2010-07-05 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:12,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,742 INFO sqlalchemy.engine.base.Engine ('2010-07-06 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:12,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,744 INFO sqlalchemy.engine.base.Engine ('2010-07-07 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:12,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,746 INFO sqlalchemy.engine.base.Engine ('2010-07-08 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:12,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,748 INFO sqlalchemy.engine.base.Engine ('2010-07-09 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:12,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,751 INFO sqlalchemy.engine.base.Engine ('2010-07-10 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:12,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,753 INFO sqlalchemy.engine.base.Engine ('2010-07-11 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:12,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,755 INFO sqlalchemy.engine.base.Engine ('2010-07-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,757 INFO sqlalchemy.engine.base.Engine ('2010-07-13 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:12,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,758 INFO sqlalchemy.engine.base.Engine ('2010-07-14 00:00:00.000000', 0.45, 70)
2018-05-08 18:31:12,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,761 INFO sqlalchemy.engine.base.Engine ('2010-07-15 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:12,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,763 INFO sqlalchemy.engine.base.Engine ('2010-07-16 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:12,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,764 INFO sqlalchemy.engine.base.Engine ('2010-07-17 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:12,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,766 INFO sqlalchemy.engine.base.Engine ('2010-07-18 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:12,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,767 INFO sqlalchemy.engine.base.Engine ('2010-07-19 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:12,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,769 INFO sqlalchemy.engine.base.Engine ('2010-07-20 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:12,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,771 INFO sqlalchemy.engine.base.Engine ('2010-07-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,772 INFO sqlalchemy.engine.base.Engine ('2010-07-22 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:12,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,774 INFO sqlalchemy.engine.base.Engine ('2010-07-23 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:12,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,776 INFO sqlalchemy.engine.base.Engine ('2010-07-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:12,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,778 INFO sqlalchemy.engine.base.Engine ('2010-07-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:12,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,782 INFO sqlalchemy.engine.base.Engine ('2010-07-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,784 INFO sqlalchemy.engine.base.Engine ('2010-07-27 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:12,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,786 INFO sqlalchemy.engine.base.Engine ('2010-07-28 00:00:00.000000', 0.46, 75)
2018-05-08 18:31:12,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,788 INFO sqlalchemy.engine.base.Engine ('2010-07-29 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,790 INFO sqlalchemy.engine.base.Engine ('2010-07-30 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:12,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,792 INFO sqlalchemy.engine.base.Engine ('2010-07-31 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:12,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,794 INFO sqlalchemy.engine.base.Engine ('2010-08-01 00:00:00.000000', 0.16, 72)

2018-05-08 18:31:12,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,796 INFO sqlalchemy.engine.base.Engine ('2010-08-02 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:12,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,797 INFO sqlalchemy.engine.base.Engine ('2010-08-03 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:12,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,799 INFO sqlalchemy.engine.base.Engine ('2010-08-04 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:12,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,800 INFO sqlalchemy.engine.base.Engine ('2010-08-05 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:12,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,802 INFO sqlalchemy.engine.base.Engine ('2010-08-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,803 INFO sqlalchemy.engine.base.Engine ('2010-08-07 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:12,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,805 INFO sqlalchemy.engine.base.Engine ('2010-08-08 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:12,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,807 INFO sqlalchemy.engine.base.Engine ('2010-08-09 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:12,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,809 INFO sqlalchemy.engine.base.Engine ('2010-08-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,811 INFO sqlalchemy.engine.base.Engine ('2010-08-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,813 INFO sqlalchemy.engine.base.Engine ('2010-08-12 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:12,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,814 INFO sqlalchemy.engine.base.Engine ('2010-08-13 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:12,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,816 INFO sqlalchemy.engine.base.Engine ('2010-08-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,818 INFO sqlalchemy.engine.base.Engine ('2010-08-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,820 INFO sqlalchemy.engine.base.Engine ('2010-08-16 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:12,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,821 INFO sqlalchemy.engine.base.Engine ('2010-08-17 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:12,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,823 INFO sqlalchemy.engine.base.Engine ('2010-08-18 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:12,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,826 INFO sqlalchemy.engine.base.Engine ('2010-08-19 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:12,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,827 INFO sqlalchemy.engine.base.Engine ('2010-08-20 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:12,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,829 INFO sqlalchemy.engine.base.Engine ('2010-08-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,831 INFO sqlalchemy.engine.base.Engine ('2010-08-22 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,834 INFO sqlalchemy.engine.base.Engine ('2010-08-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,836 INFO sqlalchemy.engine.base.Engine ('2010-08-24 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:12,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,838 INFO sqlalchemy.engine.base.Engine ('2010-08-25 00:00:00.000000', 0.25, 73)
2018-05-08 18:31:12,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,840 INFO sqlalchemy.engine.base.Engine ('2010-08-26 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:12,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,843 INFO sqlalchemy.engine.base.Engine ('2010-08-27 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:12,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,845 INFO sqlalchemy.engine.base.Engine ('2010-08-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,846 INFO sqlalchemy.engine.base.Engine ('2010-08-29 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:12,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,848 INFO sqlalchemy.engine.base.Engine ('2010-08-30 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:12,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,850 INFO sqlalchemy.engine.base.Engine ('2010-08-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,851 INFO sqlalchemy.engine.base.Engine ('2010-09-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,853 INFO sqlalchemy.engine.base.Engine ('2010-09-02 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:12,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,855 INFO sqlalchemy.engine.base.Engine ('2010-09-03 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:12,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,856 INFO sqlalchemy.engine.base.Engine ('2010-09-04 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:12,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,858 INFO sqlalchemy.engine.base.Engine ('2010-09-05 00:00:00.000000', 0.08, 74)

2018-05-08 18:31:12,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,860 INFO sqlalchemy.engine.base.Engine ('2010-09-06 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:12,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,862 INFO sqlalchemy.engine.base.Engine ('2010-09-07 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:12,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,864 INFO sqlalchemy.engine.base.Engine ('2010-09-08 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:12,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,865 INFO sqlalchemy.engine.base.Engine ('2010-09-09 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:12,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,867 INFO sqlalchemy.engine.base.Engine ('2010-09-10 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:12,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,869 INFO sqlalchemy.engine.base.Engine ('2010-09-11 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:12,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,871 INFO sqlalchemy.engine.base.Engine ('2010-09-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,920 INFO sqlalchemy.engine.base.Engine ('2010-09-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,922 INFO sqlalchemy.engine.base.Engine ('2010-09-14 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:12,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,924 INFO sqlalchemy.engine.base.Engine ('2010-09-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,926 INFO sqlalchemy.engine.base.Engine ('2010-09-16 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:12,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,928 INFO sqlalchemy.engine.base.Engine ('2010-09-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,929 INFO sqlalchemy.engine.base.Engine ('2010-09-18 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:12,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,931 INFO sqlalchemy.engine.base.Engine ('2010-09-19 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:12,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,933 INFO sqlalchemy.engine.base.Engine ('2010-09-20 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:12,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,935 INFO sqlalchemy.engine.base.Engine ('2010-09-21 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:12,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,938 INFO sqlalchemy.engine.base.Engine ('2010-09-22 00:00:00.000000', 0.5, 74)
2018-05-08 18:31:12,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,940 INFO sqlalchemy.engine.base.Engine ('2010-09-23 00:00:00.000000', 0.33, 75)
2018-05-08 18:31:12,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,943 INFO sqlalchemy.engine.base.Engine ('2010-09-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:12,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,945 INFO sqlalchemy.engine.base.Engine ('2010-09-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,947 INFO sqlalchemy.engine.base.Engine ('2010-09-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,948 INFO sqlalchemy.engine.base.Engine ('2010-09-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:12,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,950 INFO sqlalchemy.engine.base.Engine ('2010-09-30 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:12,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,952 INFO sqlalchemy.engine.base.Engine ('2010-10-01 00:00:00.000000', 0.43, 72)
2018-05-08 18:31:12,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,953 INFO sqlalchemy.engine.base.Engine ('2010-10-02 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:12,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,955 INFO sqlalchemy.engine.base.Engine ('2010-10-03 00:00:00.000000', 0.07, 82)
2018-05-08 18:31:12,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,957 INFO sqlalchemy.engine.base.Engine ('2010-10-04 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:12,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,958 INFO sqlalchemy.engine.base.Engine ('2010-10-05 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:12,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,960 INFO sqlalchemy.engine.base.Engine ('2010-10-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,962 INFO sqlalchemy.engine.base.Engine ('2010-10-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,964 INFO sqlalchemy.engine.base.Engine ('2010-10-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,965 INFO sqlalchemy.engine.base.Engine ('2010-10-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,967 INFO sqlalchemy.engine.base.Engine ('2010-10-10 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:12,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,969 INFO sqlalchemy.engine.base.Engine ('2010-10-11 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:12,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,970 INFO sqlalchemy.engine.base.Engine ('2010-10-12 00:00:00.000000', 0.06, 71)

2018-05-08 18:31:12,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,972 INFO sqlalchemy.engine.base.Engine ('2010-10-13 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:12,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,974 INFO sqlalchemy.engine.base.Engine ('2010-10-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,977 INFO sqlalchemy.engine.base.Engine ('2010-10-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:12,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,979 INFO sqlalchemy.engine.base.Engine ('2010-10-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,981 INFO sqlalchemy.engine.base.Engine ('2010-10-17 00:00:00.000000', 0.16, 77)
2018-05-08 18:31:12,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,983 INFO sqlalchemy.engine.base.Engine ('2010-10-18 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:12,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,985 INFO sqlalchemy.engine.base.Engine ('2010-10-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:12,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,987 INFO sqlalchemy.engine.base.Engine ('2010-10-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:12,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,989 INFO sqlalchemy.engine.base.Engine ('2010-10-21 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:12,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,991 INFO sqlalchemy.engine.base.Engine ('2010-10-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,993 INFO sqlalchemy.engine.base.Engine ('2010-10-23 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:12,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,995 INFO sqlalchemy.engine.base.Engine ('2010-10-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:12,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,997 INFO sqlalchemy.engine.base.Engine ('2010-10-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:12,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:12,998 INFO sqlalchemy.engine.base.Engine ('2010-10-26 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:12,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,000 INFO sqlalchemy.engine.base.Engine ('2010-10-27 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:13,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,001 INFO sqlalchemy.engine.base.Engine ('2010-10-28 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:13,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,003 INFO sqlalchemy.engine.base.Engine ('2010-10-29 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:13,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,005 INFO sqlalchemy.engine.base.Engine ('2010-10-30 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:13,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,006 INFO sqlalchemy.engine.base.Engine ('2010-10-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,008 INFO sqlalchemy.engine.base.Engine ('2010-11-01 00:00:00.000000', 0.42, 73)
2018-05-08 18:31:13,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,010 INFO sqlalchemy.engine.base.Engine ('2010-11-02 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:13,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,012 INFO sqlalchemy.engine.base.Engine ('2010-11-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,013 INFO sqlalchemy.engine.base.Engine ('2010-11-04 00:00:00.000000', 0.39, 73)
2018-05-08 18:31:13,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,015 INFO sqlalchemy.engine.base.Engine ('2010-11-05 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:13,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,016 INFO sqlalchemy.engine.base.Engine ('2010-11-06 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:13,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,018 INFO sqlalchemy.engine.base.Engine ('2010-11-07 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:13,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,020 INFO sqlalchemy.engine.base.Engine ('2010-11-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,021 INFO sqlalchemy.engine.base.Engine ('2010-11-09 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:13,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,023 INFO sqlalchemy.engine.base.Engine ('2010-11-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,026 INFO sqlalchemy.engine.base.Engine ('2010-11-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,029 INFO sqlalchemy.engine.base.Engine ('2010-11-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,031 INFO sqlalchemy.engine.base.Engine ('2010-11-13 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:13,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,032 INFO sqlalchemy.engine.base.Engine ('2010-11-14 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,034 INFO sqlalchemy.engine.base.Engine ('2010-11-15 00:00:00.000000', 0.35, 75)
2018-05-08 18:31:13,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,036 INFO sqlalchemy.engine.base.Engine ('2010-11-16 00:00:00.000000', 0.01, 74)

2018-05-08 18:31:13,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,038 INFO sqlalchemy.engine.base.Engine ('2010-11-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,040 INFO sqlalchemy.engine.base.Engine ('2010-11-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,042 INFO sqlalchemy.engine.base.Engine ('2010-11-19 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:13,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,045 INFO sqlalchemy.engine.base.Engine ('2010-11-20 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:13,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,048 INFO sqlalchemy.engine.base.Engine ('2010-11-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,049 INFO sqlalchemy.engine.base.Engine ('2010-11-22 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:13,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,051 INFO sqlalchemy.engine.base.Engine ('2010-11-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:13,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,053 INFO sqlalchemy.engine.base.Engine ('2010-11-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,055 INFO sqlalchemy.engine.base.Engine ('2010-11-25 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:13,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,057 INFO sqlalchemy.engine.base.Engine ('2010-11-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,059 INFO sqlalchemy.engine.base.Engine ('2010-11-27 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,061 INFO sqlalchemy.engine.base.Engine ('2010-11-28 00:00:00.000000', 0.49, 71)
2018-05-08 18:31:13,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,063 INFO sqlalchemy.engine.base.Engine ('2010-11-29 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:13,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,065 INFO sqlalchemy.engine.base.Engine ('2010-11-30 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:13,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,068 INFO sqlalchemy.engine.base.Engine ('2010-12-01 00:00:00.000000', 0.76, 73)
2018-05-08 18:31:13,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,070 INFO sqlalchemy.engine.base.Engine ('2010-12-02 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:13,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,073 INFO sqlalchemy.engine.base.Engine ('2010-12-03 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:13,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,074 INFO sqlalchemy.engine.base.Engine ('2010-12-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,077 INFO sqlalchemy.engine.base.Engine ('2010-12-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,079 INFO sqlalchemy.engine.base.Engine ('2010-12-06 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:13,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,080 INFO sqlalchemy.engine.base.Engine ('2010-12-07 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:13,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,082 INFO sqlalchemy.engine.base.Engine ('2010-12-08 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:13,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,083 INFO sqlalchemy.engine.base.Engine ('2010-12-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,085 INFO sqlalchemy.engine.base.Engine ('2010-12-10 00:00:00.000000', 1.95, 65)
2018-05-08 18:31:13,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,087 INFO sqlalchemy.engine.base.Engine ('2010-12-11 00:00:00.000000', 0.62, 69)
2018-05-08 18:31:13,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,088 INFO sqlalchemy.engine.base.Engine ('2010-12-12 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:13,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,090 INFO sqlalchemy.engine.base.Engine ('2010-12-13 00:00:00.000000', 0.47, 69)
2018-05-08 18:31:13,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,092 INFO sqlalchemy.engine.base.Engine ('2010-12-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:13,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,095 INFO sqlalchemy.engine.base.Engine ('2010-12-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,098 INFO sqlalchemy.engine.base.Engine ('2010-12-16 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:13,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,100 INFO sqlalchemy.engine.base.Engine ('2010-12-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:13,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,102 INFO sqlalchemy.engine.base.Engine ('2010-12-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,104 INFO sqlalchemy.engine.base.Engine ('2010-12-19 00:00:00.000000', 3.18, 70)
2018-05-08 18:31:13,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,105 INFO sqlalchemy.engine.base.Engine ('2010-12-20 00:00:00.000000', 4.94, 71)
2018-05-08 18:31:13,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,107 INFO sqlalchemy.engine.base.Engine ('2010-12-21 00:00:00.000000', 0.43, 71)

2018-05-08 18:31:13,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,110 INFO sqlalchemy.engine.base.Engine ('2010-12-22 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:13,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,111 INFO sqlalchemy.engine.base.Engine ('2010-12-23 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:13,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,166 INFO sqlalchemy.engine.base.Engine ('2010-12-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:13,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,168 INFO sqlalchemy.engine.base.Engine ('2010-12-25 00:00:00.000000', 2.95, 69)
2018-05-08 18:31:13,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,169 INFO sqlalchemy.engine.base.Engine ('2010-12-26 00:00:00.000000', 0.99, 72)
2018-05-08 18:31:13,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,171 INFO sqlalchemy.engine.base.Engine ('2010-12-27 00:00:00.000000', 0.46, 76)
2018-05-08 18:31:13,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,173 INFO sqlalchemy.engine.base.Engine ('2010-12-28 00:00:00.000000', 0.63, 72)
2018-05-08 18:31:13,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,175 INFO sqlalchemy.engine.base.Engine ('2010-12-29 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:13,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,177 INFO sqlalchemy.engine.base.Engine ('2010-12-30 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:13,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,178 INFO sqlalchemy.engine.base.Engine ('2010-12-31 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:13,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,180 INFO sqlalchemy.engine.base.Engine ('2011-01-01 00:00:00.000000', 0.42, 69)
2018-05-08 18:31:13,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,182 INFO sqlalchemy.engine.base.Engine ('2011-01-02 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:13,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,183 INFO sqlalchemy.engine.base.Engine ('2011-01-03 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,185 INFO sqlalchemy.engine.base.Engine ('2011-01-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,187 INFO sqlalchemy.engine.base.Engine ('2011-01-05 00:00:00.000000', 0.04, 67)
2018-05-08 18:31:13,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,188 INFO sqlalchemy.engine.base.Engine ('2011-01-06 00:00:00.000000', 0.21, 67)
2018-05-08 18:31:13,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,190 INFO sqlalchemy.engine.base.Engine ('2011-01-07 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:13,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,192 INFO sqlalchemy.engine.base.Engine ('2011-01-08 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:13,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,195 INFO sqlalchemy.engine.base.Engine ('2011-01-09 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:13,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,197 INFO sqlalchemy.engine.base.Engine ('2011-01-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,200 INFO sqlalchemy.engine.base.Engine ('2011-01-11 00:00:00.000000', 0.11, 61)
2018-05-08 18:31:13,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,202 INFO sqlalchemy.engine.base.Engine ('2011-01-12 00:00:00.000000', 0.46, 71)
2018-05-08 18:31:13,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,204 INFO sqlalchemy.engine.base.Engine ('2011-01-13 00:00:00.000000', 5.21, 70)
2018-05-08 18:31:13,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,205 INFO sqlalchemy.engine.base.Engine ('2011-01-14 00:00:00.000000', 0.22, 76)
2018-05-08 18:31:13,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,207 INFO sqlalchemy.engine.base.Engine ('2011-01-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:13,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,210 INFO sqlalchemy.engine.base.Engine ('2011-01-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:13,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,212 INFO sqlalchemy.engine.base.Engine ('2011-01-17 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:13,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,213 INFO sqlalchemy.engine.base.Engine ('2011-01-18 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:13,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,215 INFO sqlalchemy.engine.base.Engine ('2011-01-19 00:00:00.000000', 0.05, 64)
2018-05-08 18:31:13,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,217 INFO sqlalchemy.engine.base.Engine ('2011-01-20 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:13,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,219 INFO sqlalchemy.engine.base.Engine ('2011-01-21 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:13,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,220 INFO sqlalchemy.engine.base.Engine ('2011-01-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,222 INFO sqlalchemy.engine.base.Engine ('2011-01-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,225 INFO sqlalchemy.engine.base.Engine ('2011-01-24 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:13,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,228 INFO sqlalchemy.engine.base.Engine ('2011-01-25 00:00:00.000000', 0.0, 65)

2018-05-08 18:31:13,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,230 INFO sqlalchemy.engine.base.Engine ('2011-01-26 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:13,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,232 INFO sqlalchemy.engine.base.Engine ('2011-01-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,235 INFO sqlalchemy.engine.base.Engine ('2011-01-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,237 INFO sqlalchemy.engine.base.Engine ('2011-01-29 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:13,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,239 INFO sqlalchemy.engine.base.Engine ('2011-01-30 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:13,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,242 INFO sqlalchemy.engine.base.Engine ('2011-01-31 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:13,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,245 INFO sqlalchemy.engine.base.Engine ('2011-02-01 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:13,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,247 INFO sqlalchemy.engine.base.Engine ('2011-02-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,249 INFO sqlalchemy.engine.base.Engine ('2011-02-03 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:13,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,251 INFO sqlalchemy.engine.base.Engine ('2011-02-04 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:13,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,254 INFO sqlalchemy.engine.base.Engine ('2011-02-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,256 INFO sqlalchemy.engine.base.Engine ('2011-02-06 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:13,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,260 INFO sqlalchemy.engine.base.Engine ('2011-02-07 00:00:00.000000', 1.06, 68)
2018-05-08 18:31:13,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,262 INFO sqlalchemy.engine.base.Engine ('2011-02-08 00:00:00.000000', 0.52, 70)
2018-05-08 18:31:13,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,263 INFO sqlalchemy.engine.base.Engine ('2011-02-09 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:13,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,265 INFO sqlalchemy.engine.base.Engine ('2011-02-10 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:13,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,267 INFO sqlalchemy.engine.base.Engine ('2011-02-11 00:00:00.000000', 0.33, 71)
2018-05-08 18:31:13,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,268 INFO sqlalchemy.engine.base.Engine ('2011-02-12 00:00:00.000000', 1.54, 68)
2018-05-08 18:31:13,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,270 INFO sqlalchemy.engine.base.Engine ('2011-02-13 00:00:00.000000', 0.19, 67)
2018-05-08 18:31:13,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,272 INFO sqlalchemy.engine.base.Engine ('2011-02-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,273 INFO sqlalchemy.engine.base.Engine ('2011-02-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,278 INFO sqlalchemy.engine.base.Engine ('2011-02-16 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:13,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,281 INFO sqlalchemy.engine.base.Engine ('2011-02-17 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:13,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,283 INFO sqlalchemy.engine.base.Engine ('2011-02-18 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:13,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,284 INFO sqlalchemy.engine.base.Engine ('2011-02-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,286 INFO sqlalchemy.engine.base.Engine ('2011-02-20 00:00:00.000000', 4.88, 71)
2018-05-08 18:31:13,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,288 INFO sqlalchemy.engine.base.Engine ('2011-02-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:13,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,290 INFO sqlalchemy.engine.base.Engine ('2011-02-22 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:13,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,292 INFO sqlalchemy.engine.base.Engine ('2011-02-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,294 INFO sqlalchemy.engine.base.Engine ('2011-02-24 00:00:00.000000', 3.3, 67)
2018-05-08 18:31:13,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,296 INFO sqlalchemy.engine.base.Engine ('2011-02-25 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:13,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,298 INFO sqlalchemy.engine.base.Engine ('2011-02-26 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:13,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,300 INFO sqlalchemy.engine.base.Engine ('2011-02-27 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:13,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,302 INFO sqlalchemy.engine.base.Engine ('2011-02-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,304 INFO sqlalchemy.engine.base.Engine ('2011-03-01 00:00:00.000000', 0.14, 66)

2018-05-08 18:31:13,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,305 INFO sqlalchemy.engine.base.Engine ('2011-03-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,308 INFO sqlalchemy.engine.base.Engine ('2011-03-03 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:13,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,310 INFO sqlalchemy.engine.base.Engine ('2011-03-04 00:00:00.000000', 1.05, 71)
2018-05-08 18:31:13,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,313 INFO sqlalchemy.engine.base.Engine ('2011-03-05 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:13,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,315 INFO sqlalchemy.engine.base.Engine ('2011-03-06 00:00:00.000000', 1.16, 72)
2018-05-08 18:31:13,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,317 INFO sqlalchemy.engine.base.Engine ('2011-03-07 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:13,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,320 INFO sqlalchemy.engine.base.Engine ('2011-03-08 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:13,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,322 INFO sqlalchemy.engine.base.Engine ('2011-03-09 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:13,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,324 INFO sqlalchemy.engine.base.Engine ('2011-03-10 00:00:00.000000', 1.33, 72)
2018-05-08 18:31:13,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,326 INFO sqlalchemy.engine.base.Engine ('2011-03-11 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:13,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,328 INFO sqlalchemy.engine.base.Engine ('2011-03-12 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:13,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,330 INFO sqlalchemy.engine.base.Engine ('2011-03-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,333 INFO sqlalchemy.engine.base.Engine ('2011-03-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,335 INFO sqlalchemy.engine.base.Engine ('2011-03-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,337 INFO sqlalchemy.engine.base.Engine ('2011-03-16 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,338 INFO sqlalchemy.engine.base.Engine ('2011-03-17 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:13,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,340 INFO sqlalchemy.engine.base.Engine ('2011-03-18 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:13,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,342 INFO sqlalchemy.engine.base.Engine ('2011-03-19 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:13,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,344 INFO sqlalchemy.engine.base.Engine ('2011-03-20 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:13,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,346 INFO sqlalchemy.engine.base.Engine ('2011-03-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,349 INFO sqlalchemy.engine.base.Engine ('2011-03-22 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:13,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,352 INFO sqlalchemy.engine.base.Engine ('2011-03-23 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:13,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,354 INFO sqlalchemy.engine.base.Engine ('2011-03-24 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:13,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,356 INFO sqlalchemy.engine.base.Engine ('2011-03-25 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:13,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,358 INFO sqlalchemy.engine.base.Engine ('2011-03-26 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:13,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,361 INFO sqlalchemy.engine.base.Engine ('2011-03-27 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:13,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,363 INFO sqlalchemy.engine.base.Engine ('2011-03-28 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:13,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,365 INFO sqlalchemy.engine.base.Engine ('2011-03-29 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:13,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,366 INFO sqlalchemy.engine.base.Engine ('2011-03-30 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:13,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,368 INFO sqlalchemy.engine.base.Engine ('2011-03-31 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,370 INFO sqlalchemy.engine.base.Engine ('2011-04-01 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:13,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,372 INFO sqlalchemy.engine.base.Engine ('2011-04-02 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:13,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,417 INFO sqlalchemy.engine.base.Engine ('2011-04-03 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:13,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,419 INFO sqlalchemy.engine.base.Engine ('2011-04-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,421 INFO sqlalchemy.engine.base.Engine ('2011-04-05 00:00:00.000000', 0.0, 71)

2018-05-08 18:31:13,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,423 INFO sqlalchemy.engine.base.Engine ('2011-04-06 00:00:00.000000', 0.09, 70)
2018-05-08 18:31:13,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,426 INFO sqlalchemy.engine.base.Engine ('2011-04-07 00:00:00.000000', 0.68, 67)
2018-05-08 18:31:13,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,428 INFO sqlalchemy.engine.base.Engine ('2011-04-08 00:00:00.000000', 0.39, 68)
2018-05-08 18:31:13,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,430 INFO sqlalchemy.engine.base.Engine ('2011-04-09 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,433 INFO sqlalchemy.engine.base.Engine ('2011-04-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,436 INFO sqlalchemy.engine.base.Engine ('2011-04-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,438 INFO sqlalchemy.engine.base.Engine ('2011-04-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,439 INFO sqlalchemy.engine.base.Engine ('2011-04-13 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:13,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,441 INFO sqlalchemy.engine.base.Engine ('2011-04-14 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:13,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,444 INFO sqlalchemy.engine.base.Engine ('2011-04-15 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:13,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,446 INFO sqlalchemy.engine.base.Engine ('2011-04-16 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:13,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,447 INFO sqlalchemy.engine.base.Engine ('2011-04-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,449 INFO sqlalchemy.engine.base.Engine ('2011-04-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,451 INFO sqlalchemy.engine.base.Engine ('2011-04-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,452 INFO sqlalchemy.engine.base.Engine ('2011-04-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,454 INFO sqlalchemy.engine.base.Engine ('2011-04-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,457 INFO sqlalchemy.engine.base.Engine ('2011-04-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,460 INFO sqlalchemy.engine.base.Engine ('2011-04-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,462 INFO sqlalchemy.engine.base.Engine ('2011-04-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,464 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,466 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:13,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,468 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,469 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,471 INFO sqlalchemy.engine.base.Engine ('2011-04-29 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:13,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,473 INFO sqlalchemy.engine.base.Engine ('2011-04-30 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:13,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,474 INFO sqlalchemy.engine.base.Engine ('2011-05-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,477 INFO sqlalchemy.engine.base.Engine ('2011-05-02 00:00:00.000000', 0.22, 74)
2018-05-08 18:31:13,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,479 INFO sqlalchemy.engine.base.Engine ('2011-05-03 00:00:00.000000', 0.42, 71)
2018-05-08 18:31:13,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,481 INFO sqlalchemy.engine.base.Engine ('2011-05-04 00:00:00.000000', 0.25, 73)
2018-05-08 18:31:13,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,482 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:13,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,484 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:13,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,486 INFO sqlalchemy.engine.base.Engine ('2011-05-07 00:00:00.000000', 0.86, 72)
2018-05-08 18:31:13,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,488 INFO sqlalchemy.engine.base.Engine ('2011-05-08 00:00:00.000000', 1.76, 68)
2018-05-08 18:31:13,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,491 INFO sqlalchemy.engine.base.Engine ('2011-05-09 00:00:00.000000', 0.73, 74)
2018-05-08 18:31:13,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,494 INFO sqlalchemy.engine.base.Engine ('2011-05-10 00:00:00.000000', 0.24, 72)

2018-05-08 18:31:13,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,496 INFO sqlalchemy.engine.base.Engine ('2011-05-11 00:00:00.000000', 0.92, 71)
2018-05-08 18:31:13,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,498 INFO sqlalchemy.engine.base.Engine ('2011-05-12 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,500 INFO sqlalchemy.engine.base.Engine ('2011-05-13 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,502 INFO sqlalchemy.engine.base.Engine ('2011-05-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,503 INFO sqlalchemy.engine.base.Engine ('2011-05-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,505 INFO sqlalchemy.engine.base.Engine ('2011-05-16 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,507 INFO sqlalchemy.engine.base.Engine ('2011-05-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,509 INFO sqlalchemy.engine.base.Engine ('2011-05-18 00:00:00.000000', 0.3, 70)
2018-05-08 18:31:13,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,511 INFO sqlalchemy.engine.base.Engine ('2011-05-19 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:13,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,512 INFO sqlalchemy.engine.base.Engine ('2011-05-20 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,514 INFO sqlalchemy.engine.base.Engine ('2011-05-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,516 INFO sqlalchemy.engine.base.Engine ('2011-05-22 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:13,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,517 INFO sqlalchemy.engine.base.Engine ('2011-05-23 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:13,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,520 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,522 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,524 INFO sqlalchemy.engine.base.Engine ('2011-05-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,527 INFO sqlalchemy.engine.base.Engine ('2011-05-27 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,529 INFO sqlalchemy.engine.base.Engine ('2011-05-28 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:13,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,531 INFO sqlalchemy.engine.base.Engine ('2011-05-29 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:13,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,533 INFO sqlalchemy.engine.base.Engine ('2011-05-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,534 INFO sqlalchemy.engine.base.Engine ('2011-05-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,536 INFO sqlalchemy.engine.base.Engine ('2011-06-01 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,538 INFO sqlalchemy.engine.base.Engine ('2011-06-02 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:13,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,539 INFO sqlalchemy.engine.base.Engine ('2011-06-03 00:00:00.000000', 0.63, 71)
2018-05-08 18:31:13,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,541 INFO sqlalchemy.engine.base.Engine ('2011-06-04 00:00:00.000000', 4.43, 69)
2018-05-08 18:31:13,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,544 INFO sqlalchemy.engine.base.Engine ('2011-06-05 00:00:00.000000', 4.02, 69)
2018-05-08 18:31:13,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,545 INFO sqlalchemy.engine.base.Engine ('2011-06-06 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,547 INFO sqlalchemy.engine.base.Engine ('2011-06-07 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:13,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,549 INFO sqlalchemy.engine.base.Engine ('2011-06-08 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,550 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,552 INFO sqlalchemy.engine.base.Engine ('2011-06-10 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:13,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,554 INFO sqlalchemy.engine.base.Engine ('2011-06-11 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:13,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,556 INFO sqlalchemy.engine.base.Engine ('2011-06-12 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:13,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,558 INFO sqlalchemy.engine.base.Engine ('2011-06-13 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:13,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,560 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.0, 75)

2018-05-08 18:31:13,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,562 INFO sqlalchemy.engine.base.Engine ('2011-06-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,564 INFO sqlalchemy.engine.base.Engine ('2011-06-16 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:13,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,566 INFO sqlalchemy.engine.base.Engine ('2011-06-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,568 INFO sqlalchemy.engine.base.Engine ('2011-06-18 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:13,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,571 INFO sqlalchemy.engine.base.Engine ('2011-06-19 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:13,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,573 INFO sqlalchemy.engine.base.Engine ('2011-06-20 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:13,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,575 INFO sqlalchemy.engine.base.Engine ('2011-06-21 00:00:00.000000', 0.54, 72)
2018-05-08 18:31:13,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,577 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 0.22, 74)
2018-05-08 18:31:13,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,579 INFO sqlalchemy.engine.base.Engine ('2011-06-23 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:13,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,581 INFO sqlalchemy.engine.base.Engine ('2011-06-24 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:13,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,582 INFO sqlalchemy.engine.base.Engine ('2011-06-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,584 INFO sqlalchemy.engine.base.Engine ('2011-06-26 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,587 INFO sqlalchemy.engine.base.Engine ('2011-06-27 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,589 INFO sqlalchemy.engine.base.Engine ('2011-06-28 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:13,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,591 INFO sqlalchemy.engine.base.Engine ('2011-06-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,593 INFO sqlalchemy.engine.base.Engine ('2011-06-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,595 INFO sqlalchemy.engine.base.Engine ('2011-07-01 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:13,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,597 INFO sqlalchemy.engine.base.Engine ('2011-07-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,599 INFO sqlalchemy.engine.base.Engine ('2011-07-03 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:13,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,601 INFO sqlalchemy.engine.base.Engine ('2011-07-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,603 INFO sqlalchemy.engine.base.Engine ('2011-07-05 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,606 INFO sqlalchemy.engine.base.Engine ('2011-07-06 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:13,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,608 INFO sqlalchemy.engine.base.Engine ('2011-07-07 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:13,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,610 INFO sqlalchemy.engine.base.Engine ('2011-07-08 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:13,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,612 INFO sqlalchemy.engine.base.Engine ('2011-07-09 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:13,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,614 INFO sqlalchemy.engine.base.Engine ('2011-07-10 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:13,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,615 INFO sqlalchemy.engine.base.Engine ('2011-07-11 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,656 INFO sqlalchemy.engine.base.Engine ('2011-07-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,657 INFO sqlalchemy.engine.base.Engine ('2011-07-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,660 INFO sqlalchemy.engine.base.Engine ('2011-07-14 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:13,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,662 INFO sqlalchemy.engine.base.Engine ('2011-07-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,664 INFO sqlalchemy.engine.base.Engine ('2011-07-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,665 INFO sqlalchemy.engine.base.Engine ('2011-07-17 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:13,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,668 INFO sqlalchemy.engine.base.Engine ('2011-07-18 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,671 INFO sqlalchemy.engine.base.Engine ('2011-07-19 00:00:00.000000', 0.0, 74)

2018-05-08 18:31:13,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,673 INFO sqlalchemy.engine.base.Engine ('2011-07-20 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:13,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,675 INFO sqlalchemy.engine.base.Engine ('2011-07-21 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:13,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,677 INFO sqlalchemy.engine.base.Engine ('2011-07-22 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:13,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,679 INFO sqlalchemy.engine.base.Engine ('2011-07-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,680 INFO sqlalchemy.engine.base.Engine ('2011-07-24 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:13,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,682 INFO sqlalchemy.engine.base.Engine ('2011-07-25 00:00:00.000000', 0.22, 74)
2018-05-08 18:31:13,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,684 INFO sqlalchemy.engine.base.Engine ('2011-07-26 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,686 INFO sqlalchemy.engine.base.Engine ('2011-07-27 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:13,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,687 INFO sqlalchemy.engine.base.Engine ('2011-07-28 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:13,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,689 INFO sqlalchemy.engine.base.Engine ('2011-07-29 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:13,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,691 INFO sqlalchemy.engine.base.Engine ('2011-07-30 00:00:00.000000', 0.61, 75)
2018-05-08 18:31:13,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,693 INFO sqlalchemy.engine.base.Engine ('2011-07-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,694 INFO sqlalchemy.engine.base.Engine ('2011-08-01 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:13,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,696 INFO sqlalchemy.engine.base.Engine ('2011-08-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,698 INFO sqlalchemy.engine.base.Engine ('2011-08-03 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:13,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,700 INFO sqlalchemy.engine.base.Engine ('2011-08-04 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,703 INFO sqlalchemy.engine.base.Engine ('2011-08-05 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:13,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,705 INFO sqlalchemy.engine.base.Engine ('2011-08-06 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,707 INFO sqlalchemy.engine.base.Engine ('2011-08-07 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:13,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,710 INFO sqlalchemy.engine.base.Engine ('2011-08-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,712 INFO sqlalchemy.engine.base.Engine ('2011-08-09 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:13,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,714 INFO sqlalchemy.engine.base.Engine ('2011-08-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,716 INFO sqlalchemy.engine.base.Engine ('2011-08-11 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:13,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,717 INFO sqlalchemy.engine.base.Engine ('2011-08-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,719 INFO sqlalchemy.engine.base.Engine ('2011-08-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,721 INFO sqlalchemy.engine.base.Engine ('2011-08-14 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:13,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,723 INFO sqlalchemy.engine.base.Engine ('2011-08-15 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:13,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,725 INFO sqlalchemy.engine.base.Engine ('2011-08-16 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:13,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,726 INFO sqlalchemy.engine.base.Engine ('2011-08-17 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:13,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,728 INFO sqlalchemy.engine.base.Engine ('2011-08-18 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:13,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,730 INFO sqlalchemy.engine.base.Engine ('2011-08-19 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:13,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,732 INFO sqlalchemy.engine.base.Engine ('2011-08-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,733 INFO sqlalchemy.engine.base.Engine ('2011-08-21 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:13,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,735 INFO sqlalchemy.engine.base.Engine ('2011-08-22 00:00:00.000000', 0.28, 72)
2018-05-08 18:31:13,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,737 INFO sqlalchemy.engine.base.Engine ('2011-08-23 00:00:00.000000', 0.21, 74)

2018-05-08 18:31:13,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,738 INFO sqlalchemy.engine.base.Engine ('2011-08-24 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:13,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,740 INFO sqlalchemy.engine.base.Engine ('2011-08-25 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,742 INFO sqlalchemy.engine.base.Engine ('2011-08-26 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:13,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,744 INFO sqlalchemy.engine.base.Engine ('2011-08-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:13,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,746 INFO sqlalchemy.engine.base.Engine ('2011-08-28 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:13,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,750 INFO sqlalchemy.engine.base.Engine ('2011-08-29 00:00:00.000000', 0.24, 76)
2018-05-08 18:31:13,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,752 INFO sqlalchemy.engine.base.Engine ('2011-08-30 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:13,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,754 INFO sqlalchemy.engine.base.Engine ('2011-08-31 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:13,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,757 INFO sqlalchemy.engine.base.Engine ('2011-09-01 00:00:00.000000', 0.13, 78)
2018-05-08 18:31:13,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,760 INFO sqlalchemy.engine.base.Engine ('2011-09-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:13,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,763 INFO sqlalchemy.engine.base.Engine ('2011-09-18 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:13,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,766 INFO sqlalchemy.engine.base.Engine ('2011-09-19 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:13,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,768 INFO sqlalchemy.engine.base.Engine ('2011-09-20 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:13,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,771 INFO sqlalchemy.engine.base.Engine ('2011-09-21 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:13,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,773 INFO sqlalchemy.engine.base.Engine ('2011-09-22 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:13,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,777 INFO sqlalchemy.engine.base.Engine ('2011-09-23 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:13,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,781 INFO sqlalchemy.engine.base.Engine ('2011-09-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:13,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,783 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,785 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,787 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,789 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:13,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,792 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:13,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,793 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,795 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:13,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,797 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:13,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,799 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:13,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,801 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:13,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,803 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:13,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,805 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:13,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,810 INFO sqlalchemy.engine.base.Engine ('2011-10-08 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:13,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,812 INFO sqlalchemy.engine.base.Engine ('2011-10-09 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:13,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,813 INFO sqlalchemy.engine.base.Engine ('2011-10-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,824 INFO sqlalchemy.engine.base.Engine ('2011-10-11 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:13,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,828 INFO sqlalchemy.engine.base.Engine ('2011-10-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,830 INFO sqlalchemy.engine.base.Engine ('2011-10-13 00:00:00.000000', 0.11, 74)

2018-05-08 18:31:13,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,832 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:13,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,833 INFO sqlalchemy.engine.base.Engine ('2011-10-15 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:13,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,835 INFO sqlalchemy.engine.base.Engine ('2011-10-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,836 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:13,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,838 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.32, 70)
2018-05-08 18:31:13,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,839 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.08, 68)
2018-05-08 18:31:13,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,841 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,844 INFO sqlalchemy.engine.base.Engine ('2011-10-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,845 INFO sqlalchemy.engine.base.Engine ('2011-10-22 00:00:00.000000', 0.3, 73)
2018-05-08 18:31:13,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,847 INFO sqlalchemy.engine.base.Engine ('2011-10-23 00:00:00.000000', 1.56, 72)
2018-05-08 18:31:13,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,849 INFO sqlalchemy.engine.base.Engine ('2011-10-24 00:00:00.000000', 4.47, 70)
2018-05-08 18:31:13,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,853 INFO sqlalchemy.engine.base.Engine ('2011-10-25 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:13,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,855 INFO sqlalchemy.engine.base.Engine ('2011-10-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:13,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,857 INFO sqlalchemy.engine.base.Engine ('2011-10-27 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:13,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,860 INFO sqlalchemy.engine.base.Engine ('2011-10-28 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,861 INFO sqlalchemy.engine.base.Engine ('2011-10-29 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:13,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,863 INFO sqlalchemy.engine.base.Engine ('2011-10-30 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:13,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,865 INFO sqlalchemy.engine.base.Engine ('2011-10-31 00:00:00.000000', 0.33, 71)
2018-05-08 18:31:13,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,866 INFO sqlalchemy.engine.base.Engine ('2011-11-01 00:00:00.000000', 0.8, 72)
2018-05-08 18:31:13,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,868 INFO sqlalchemy.engine.base.Engine ('2011-11-02 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:13,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,869 INFO sqlalchemy.engine.base.Engine ('2011-11-03 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:13,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,871 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 0.62, 75)
2018-05-08 18:31:13,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,909 INFO sqlalchemy.engine.base.Engine ('2011-11-05 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:13,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,911 INFO sqlalchemy.engine.base.Engine ('2011-11-06 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:13,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,913 INFO sqlalchemy.engine.base.Engine ('2011-11-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:13,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,915 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:13,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,918 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,920 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,921 INFO sqlalchemy.engine.base.Engine ('2011-11-11 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:13,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,923 INFO sqlalchemy.engine.base.Engine ('2011-11-12 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:13,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,925 INFO sqlalchemy.engine.base.Engine ('2011-11-13 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:13,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,926 INFO sqlalchemy.engine.base.Engine ('2011-11-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,928 INFO sqlalchemy.engine.base.Engine ('2011-11-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:13,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,930 INFO sqlalchemy.engine.base.Engine ('2011-11-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,931 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.01, 75)

2018-05-08 18:31:13,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,933 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:13,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,935 INFO sqlalchemy.engine.base.Engine ('2011-11-19 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,936 INFO sqlalchemy.engine.base.Engine ('2011-11-20 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:13,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,938 INFO sqlalchemy.engine.base.Engine ('2011-11-21 00:00:00.000000', 0.38, 74)
2018-05-08 18:31:13,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,939 INFO sqlalchemy.engine.base.Engine ('2011-11-22 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,941 INFO sqlalchemy.engine.base.Engine ('2011-11-23 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:13,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,943 INFO sqlalchemy.engine.base.Engine ('2011-11-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,944 INFO sqlalchemy.engine.base.Engine ('2011-11-25 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:13,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,946 INFO sqlalchemy.engine.base.Engine ('2011-11-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:13,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,948 INFO sqlalchemy.engine.base.Engine ('2011-11-27 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:13,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,949 INFO sqlalchemy.engine.base.Engine ('2011-11-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,951 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:13,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,952 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.36, 66)
2018-05-08 18:31:13,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,954 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.11, 69)
2018-05-08 18:31:13,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,956 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:13,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,959 INFO sqlalchemy.engine.base.Engine ('2011-12-03 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:13,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,961 INFO sqlalchemy.engine.base.Engine ('2011-12-04 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:13,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,963 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:13,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,965 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,966 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:13,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,968 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:13,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,969 INFO sqlalchemy.engine.base.Engine ('2011-12-09 00:00:00.000000', 0.07, 68)
2018-05-08 18:31:13,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,971 INFO sqlalchemy.engine.base.Engine ('2011-12-10 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:13,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,972 INFO sqlalchemy.engine.base.Engine ('2011-12-11 00:00:00.000000', 0.76, 71)
2018-05-08 18:31:13,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,974 INFO sqlalchemy.engine.base.Engine ('2011-12-12 00:00:00.000000', 0.58, 72)
2018-05-08 18:31:13,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,976 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 1.55, 71)
2018-05-08 18:31:13,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,977 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:13,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,979 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:13,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,981 INFO sqlalchemy.engine.base.Engine ('2011-12-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:13,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,984 INFO sqlalchemy.engine.base.Engine ('2011-12-17 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:13,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,986 INFO sqlalchemy.engine.base.Engine ('2011-12-18 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:13,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,987 INFO sqlalchemy.engine.base.Engine ('2011-12-19 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:13,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,989 INFO sqlalchemy.engine.base.Engine ('2011-12-20 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:13,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,991 INFO sqlalchemy.engine.base.Engine ('2011-12-21 00:00:00.000000', 0.24, 69)
2018-05-08 18:31:13,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,992 INFO sqlalchemy.engine.base.Engine ('2011-12-22 00:00:00.000000', 0.06, 71)

2018-05-08 18:31:13,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,994 INFO sqlalchemy.engine.base.Engine ('2011-12-23 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:13,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,995 INFO sqlalchemy.engine.base.Engine ('2011-12-24 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:13,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,997 INFO sqlalchemy.engine.base.Engine ('2011-12-25 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:13,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:13,998 INFO sqlalchemy.engine.base.Engine ('2011-12-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:13,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,000 INFO sqlalchemy.engine.base.Engine ('2011-12-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,001 INFO sqlalchemy.engine.base.Engine ('2011-12-28 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:14,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,004 INFO sqlalchemy.engine.base.Engine ('2011-12-29 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:14,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,005 INFO sqlalchemy.engine.base.Engine ('2011-12-30 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:14,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,007 INFO sqlalchemy.engine.base.Engine ('2011-12-31 00:00:00.000000', 0.04, 67)
2018-05-08 18:31:14,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,009 INFO sqlalchemy.engine.base.Engine ('2012-01-01 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:14,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,012 INFO sqlalchemy.engine.base.Engine ('2012-01-02 00:00:00.000000', 0.04, 65)
2018-05-08 18:31:14,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,014 INFO sqlalchemy.engine.base.Engine ('2012-01-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:14,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,016 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,018 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:14,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,019 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,020 INFO sqlalchemy.engine.base.Engine ('2012-01-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,022 INFO sqlalchemy.engine.base.Engine ('2012-01-08 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,023 INFO sqlalchemy.engine.base.Engine ('2012-01-09 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,025 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,026 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:14,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,028 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.04, 66)
2018-05-08 18:31:14,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,029 INFO sqlalchemy.engine.base.Engine ('2012-01-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,031 INFO sqlalchemy.engine.base.Engine ('2012-01-14 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:14,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,033 INFO sqlalchemy.engine.base.Engine ('2012-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,034 INFO sqlalchemy.engine.base.Engine ('2012-01-16 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:14,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,037 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:14,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,039 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,042 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,043 INFO sqlalchemy.engine.base.Engine ('2012-01-21 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:14,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,045 INFO sqlalchemy.engine.base.Engine ('2012-01-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,047 INFO sqlalchemy.engine.base.Engine ('2012-01-23 00:00:00.000000', 0.03, 65)
2018-05-08 18:31:14,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,049 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,050 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:14,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,052 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,053 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.1, 69)

2018-05-08 18:31:14,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,055 INFO sqlalchemy.engine.base.Engine ('2012-01-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,057 INFO sqlalchemy.engine.base.Engine ('2012-01-29 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:14,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,059 INFO sqlalchemy.engine.base.Engine ('2012-01-30 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:14,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,061 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,062 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:14,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,064 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,066 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:14,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,067 INFO sqlalchemy.engine.base.Engine ('2012-02-04 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:14,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,069 INFO sqlalchemy.engine.base.Engine ('2012-02-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,070 INFO sqlalchemy.engine.base.Engine ('2012-02-06 00:00:00.000000', 0.04, 66)
2018-05-08 18:31:14,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,072 INFO sqlalchemy.engine.base.Engine ('2012-02-07 00:00:00.000000', 0.28, 70)
2018-05-08 18:31:14,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,074 INFO sqlalchemy.engine.base.Engine ('2012-02-08 00:00:00.000000', 0.5, 63)
2018-05-08 18:31:14,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,076 INFO sqlalchemy.engine.base.Engine ('2012-02-09 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:14,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,078 INFO sqlalchemy.engine.base.Engine ('2012-02-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,080 INFO sqlalchemy.engine.base.Engine ('2012-02-11 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,082 INFO sqlalchemy.engine.base.Engine ('2012-02-12 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,084 INFO sqlalchemy.engine.base.Engine ('2012-02-13 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,128 INFO sqlalchemy.engine.base.Engine ('2012-02-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:14,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,131 INFO sqlalchemy.engine.base.Engine ('2012-02-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,133 INFO sqlalchemy.engine.base.Engine ('2012-02-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,135 INFO sqlalchemy.engine.base.Engine ('2012-02-17 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:14,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,137 INFO sqlalchemy.engine.base.Engine ('2012-02-18 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:14,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,138 INFO sqlalchemy.engine.base.Engine ('2012-02-19 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:14,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,140 INFO sqlalchemy.engine.base.Engine ('2012-02-20 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,142 INFO sqlalchemy.engine.base.Engine ('2012-02-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,144 INFO sqlalchemy.engine.base.Engine ('2012-02-22 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:14,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,146 INFO sqlalchemy.engine.base.Engine ('2012-02-23 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:14,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,147 INFO sqlalchemy.engine.base.Engine ('2012-02-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,149 INFO sqlalchemy.engine.base.Engine ('2012-02-25 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:14,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,152 INFO sqlalchemy.engine.base.Engine ('2012-02-26 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:14,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,153 INFO sqlalchemy.engine.base.Engine ('2012-02-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,155 INFO sqlalchemy.engine.base.Engine ('2012-02-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,157 INFO sqlalchemy.engine.base.Engine ('2012-02-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,159 INFO sqlalchemy.engine.base.Engine ('2012-03-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,161 INFO sqlalchemy.engine.base.Engine ('2012-03-02 00:00:00.000000', 0.0, 67)

2018-05-08 18:31:14,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,163 INFO sqlalchemy.engine.base.Engine ('2012-03-03 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:14,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,166 INFO sqlalchemy.engine.base.Engine ('2012-03-04 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:14,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,168 INFO sqlalchemy.engine.base.Engine ('2012-03-05 00:00:00.000000', 5.71, 65)
2018-05-08 18:31:14,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,170 INFO sqlalchemy.engine.base.Engine ('2012-03-06 00:00:00.000000', 2.33, 67)
2018-05-08 18:31:14,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,171 INFO sqlalchemy.engine.base.Engine ('2012-03-07 00:00:00.000000', 2.41, 66)
2018-05-08 18:31:14,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,173 INFO sqlalchemy.engine.base.Engine ('2012-03-08 00:00:00.000000', 0.59, 67)
2018-05-08 18:31:14,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,175 INFO sqlalchemy.engine.base.Engine ('2012-03-09 00:00:00.000000', 4.6, 61)
2018-05-08 18:31:14,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,177 INFO sqlalchemy.engine.base.Engine ('2012-03-10 00:00:00.000000', 0.4, 72)
2018-05-08 18:31:14,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,178 INFO sqlalchemy.engine.base.Engine ('2012-03-11 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:14,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,180 INFO sqlalchemy.engine.base.Engine ('2012-03-12 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:14,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,182 INFO sqlalchemy.engine.base.Engine ('2012-03-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,183 INFO sqlalchemy.engine.base.Engine ('2012-03-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,185 INFO sqlalchemy.engine.base.Engine ('2012-03-15 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:14,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,187 INFO sqlalchemy.engine.base.Engine ('2012-03-16 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:14,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,189 INFO sqlalchemy.engine.base.Engine ('2012-03-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,191 INFO sqlalchemy.engine.base.Engine ('2012-03-18 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:14,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,193 INFO sqlalchemy.engine.base.Engine ('2012-03-19 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:14,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,194 INFO sqlalchemy.engine.base.Engine ('2012-03-20 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,196 INFO sqlalchemy.engine.base.Engine ('2012-03-21 00:00:00.000000', 0.23, 70)
2018-05-08 18:31:14,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,198 INFO sqlalchemy.engine.base.Engine ('2012-03-22 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:14,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,201 INFO sqlalchemy.engine.base.Engine ('2012-03-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,204 INFO sqlalchemy.engine.base.Engine ('2012-03-24 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:14,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,206 INFO sqlalchemy.engine.base.Engine ('2012-03-25 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:14,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,208 INFO sqlalchemy.engine.base.Engine ('2012-03-26 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:14,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,210 INFO sqlalchemy.engine.base.Engine ('2012-03-27 00:00:00.000000', 0.12, 67)
2018-05-08 18:31:14,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,212 INFO sqlalchemy.engine.base.Engine ('2012-03-28 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:14,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,214 INFO sqlalchemy.engine.base.Engine ('2012-03-29 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,215 INFO sqlalchemy.engine.base.Engine ('2012-03-30 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,217 INFO sqlalchemy.engine.base.Engine ('2012-03-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,219 INFO sqlalchemy.engine.base.Engine ('2012-04-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,221 INFO sqlalchemy.engine.base.Engine ('2012-04-02 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,223 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,225 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:14,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,227 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:14,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,229 INFO sqlalchemy.engine.base.Engine ('2012-04-06 00:00:00.000000', 0.0, 71)

2018-05-08 18:31:14,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,230 INFO sqlalchemy.engine.base.Engine ('2012-04-07 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:14,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,232 INFO sqlalchemy.engine.base.Engine ('2012-04-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,233 INFO sqlalchemy.engine.base.Engine ('2012-04-09 00:00:00.000000', 0.11, 69)
2018-05-08 18:31:14,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,235 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:14,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,237 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:14,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,239 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:14,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,241 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:14,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,243 INFO sqlalchemy.engine.base.Engine ('2012-04-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,247 INFO sqlalchemy.engine.base.Engine ('2012-04-15 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:14,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,249 INFO sqlalchemy.engine.base.Engine ('2012-04-16 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:14,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,251 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,253 INFO sqlalchemy.engine.base.Engine ('2012-04-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,255 INFO sqlalchemy.engine.base.Engine ('2012-04-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,257 INFO sqlalchemy.engine.base.Engine ('2012-04-20 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:14,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,259 INFO sqlalchemy.engine.base.Engine ('2012-04-21 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:14,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,261 INFO sqlalchemy.engine.base.Engine ('2012-04-22 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:14,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,264 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:14,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,266 INFO sqlalchemy.engine.base.Engine ('2012-04-24 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:14,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,268 INFO sqlalchemy.engine.base.Engine ('2012-04-25 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:14,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,270 INFO sqlalchemy.engine.base.Engine ('2012-04-26 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:14,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,272 INFO sqlalchemy.engine.base.Engine ('2012-04-27 00:00:00.000000', 0.28, 68)
2018-05-08 18:31:14,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,274 INFO sqlalchemy.engine.base.Engine ('2012-04-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,276 INFO sqlalchemy.engine.base.Engine ('2012-04-29 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,278 INFO sqlalchemy.engine.base.Engine ('2012-04-30 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,280 INFO sqlalchemy.engine.base.Engine ('2012-05-01 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:14,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,281 INFO sqlalchemy.engine.base.Engine ('2012-05-02 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:14,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,283 INFO sqlalchemy.engine.base.Engine ('2012-05-03 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:14,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,285 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:14,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,290 INFO sqlalchemy.engine.base.Engine ('2012-05-05 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:14,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,293 INFO sqlalchemy.engine.base.Engine ('2012-05-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:14,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,295 INFO sqlalchemy.engine.base.Engine ('2012-05-07 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:14,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,297 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,298 INFO sqlalchemy.engine.base.Engine ('2012-05-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,300 INFO sqlalchemy.engine.base.Engine ('2012-05-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,302 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.04, 70)

2018-05-08 18:31:14,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,303 INFO sqlalchemy.engine.base.Engine ('2012-05-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,305 INFO sqlalchemy.engine.base.Engine ('2012-05-13 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,309 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,312 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,314 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,316 INFO sqlalchemy.engine.base.Engine ('2012-05-17 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:14,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,318 INFO sqlalchemy.engine.base.Engine ('2012-05-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,320 INFO sqlalchemy.engine.base.Engine ('2012-05-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,322 INFO sqlalchemy.engine.base.Engine ('2012-05-20 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:14,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,324 INFO sqlalchemy.engine.base.Engine ('2012-05-21 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:14,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,326 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,328 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,381 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:14,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,383 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,385 INFO sqlalchemy.engine.base.Engine ('2012-05-26 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:14,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,387 INFO sqlalchemy.engine.base.Engine ('2012-05-27 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:14,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,389 INFO sqlalchemy.engine.base.Engine ('2012-05-28 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:14,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,391 INFO sqlalchemy.engine.base.Engine ('2012-05-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,392 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,394 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:14,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,396 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:14,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,397 INFO sqlalchemy.engine.base.Engine ('2012-06-02 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:14,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,399 INFO sqlalchemy.engine.base.Engine ('2012-06-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,401 INFO sqlalchemy.engine.base.Engine ('2012-06-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,402 INFO sqlalchemy.engine.base.Engine ('2012-06-05 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,405 INFO sqlalchemy.engine.base.Engine ('2012-06-06 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:14,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,407 INFO sqlalchemy.engine.base.Engine ('2012-06-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,409 INFO sqlalchemy.engine.base.Engine ('2012-06-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,411 INFO sqlalchemy.engine.base.Engine ('2012-06-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,413 INFO sqlalchemy.engine.base.Engine ('2012-06-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,414 INFO sqlalchemy.engine.base.Engine ('2012-06-11 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:14,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,416 INFO sqlalchemy.engine.base.Engine ('2012-06-12 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:14,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,418 INFO sqlalchemy.engine.base.Engine ('2012-06-13 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:14,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,419 INFO sqlalchemy.engine.base.Engine ('2012-06-14 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:14,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,421 INFO sqlalchemy.engine.base.Engine ('2012-06-15 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:14,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,422 INFO sqlalchemy.engine.base.Engine ('2012-06-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,424 INFO sqlalchemy.engine.base.Engine ('2012-06-17 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,425 INFO sqlalchemy.engine.base.Engine ('2012-06-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,427 INFO sqlalchemy.engine.base.Engine ('2012-06-19 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:14,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,428 INFO sqlalchemy.engine.base.Engine ('2012-06-20 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:14,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,430 INFO sqlalchemy.engine.base.Engine ('2012-06-21 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:14,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,432 INFO sqlalchemy.engine.base.Engine ('2012-06-22 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:14,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,433 INFO sqlalchemy.engine.base.Engine ('2012-06-23 00:00:00.000000', 0.28, 73)
2018-05-08 18:31:14,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,435 INFO sqlalchemy.engine.base.Engine ('2012-06-24 00:00:00.000000', 0.27, 69)
2018-05-08 18:31:14,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,437 INFO sqlalchemy.engine.base.Engine ('2012-06-25 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:14,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,438 INFO sqlalchemy.engine.base.Engine ('2012-06-26 00:00:00.000000', 0.22, 71)
2018-05-08 18:31:14,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,440 INFO sqlalchemy.engine.base.Engine ('2012-06-27 00:00:00.000000', 0.23, 71)
2018-05-08 18:31:14,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,442 INFO sqlalchemy.engine.base.Engine ('2012-06-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,443 INFO sqlalchemy.engine.base.Engine ('2012-06-29 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:14,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,445 INFO sqlalchemy.engine.base.Engine ('2012-06-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,448 INFO sqlalchemy.engine.base.Engine ('2012-07-01 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:14,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,450 INFO sqlalchemy.engine.base.Engine ('2012-07-02 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:14,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,452 INFO sqlalchemy.engine.base.Engine ('2012-07-03 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:14,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,454 INFO sqlalchemy.engine.base.Engine ('2012-07-04 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:14,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,456 INFO sqlalchemy.engine.base.Engine ('2012-07-05 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:14,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,458 INFO sqlalchemy.engine.base.Engine ('2012-07-06 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:14,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,459 INFO sqlalchemy.engine.base.Engine ('2012-07-07 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:14,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,461 INFO sqlalchemy.engine.base.Engine ('2012-07-08 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:14,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,462 INFO sqlalchemy.engine.base.Engine ('2012-07-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,464 INFO sqlalchemy.engine.base.Engine ('2012-07-10 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:14,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,466 INFO sqlalchemy.engine.base.Engine ('2012-07-11 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:14,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,467 INFO sqlalchemy.engine.base.Engine ('2012-07-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,469 INFO sqlalchemy.engine.base.Engine ('2012-07-13 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:14,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,470 INFO sqlalchemy.engine.base.Engine ('2012-07-14 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:14,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,472 INFO sqlalchemy.engine.base.Engine ('2012-07-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,475 INFO sqlalchemy.engine.base.Engine ('2012-07-16 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:14,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,478 INFO sqlalchemy.engine.base.Engine ('2012-07-17 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:14,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,479 INFO sqlalchemy.engine.base.Engine ('2012-07-18 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:14,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,481 INFO sqlalchemy.engine.base.Engine ('2012-07-19 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:14,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,483 INFO sqlalchemy.engine.base.Engine ('2012-07-20 00:00:00.000000', 0.8, 70)

2018-05-08 18:31:14,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,484 INFO sqlalchemy.engine.base.Engine ('2012-07-21 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:14,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,486 INFO sqlalchemy.engine.base.Engine ('2012-07-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,487 INFO sqlalchemy.engine.base.Engine ('2012-07-23 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:14,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,489 INFO sqlalchemy.engine.base.Engine ('2012-07-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,490 INFO sqlalchemy.engine.base.Engine ('2012-07-25 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:14,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,492 INFO sqlalchemy.engine.base.Engine ('2012-07-26 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:14,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,494 INFO sqlalchemy.engine.base.Engine ('2012-07-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,495 INFO sqlalchemy.engine.base.Engine ('2012-07-28 00:00:00.000000', 0.43, 75)
2018-05-08 18:31:14,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,497 INFO sqlalchemy.engine.base.Engine ('2012-07-29 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:14,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,498 INFO sqlalchemy.engine.base.Engine ('2012-07-30 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:14,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,500 INFO sqlalchemy.engine.base.Engine ('2012-07-31 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:14,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,503 INFO sqlalchemy.engine.base.Engine ('2012-08-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,505 INFO sqlalchemy.engine.base.Engine ('2012-08-02 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,507 INFO sqlalchemy.engine.base.Engine ('2012-08-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,509 INFO sqlalchemy.engine.base.Engine ('2012-08-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,512 INFO sqlalchemy.engine.base.Engine ('2012-08-05 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:14,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,513 INFO sqlalchemy.engine.base.Engine ('2012-08-06 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:14,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,515 INFO sqlalchemy.engine.base.Engine ('2012-08-07 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,516 INFO sqlalchemy.engine.base.Engine ('2012-08-08 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:14,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,518 INFO sqlalchemy.engine.base.Engine ('2012-08-09 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:14,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,519 INFO sqlalchemy.engine.base.Engine ('2012-08-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,521 INFO sqlalchemy.engine.base.Engine ('2012-08-11 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:14,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,522 INFO sqlalchemy.engine.base.Engine ('2012-08-12 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:14,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,524 INFO sqlalchemy.engine.base.Engine ('2012-08-13 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:14,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,526 INFO sqlalchemy.engine.base.Engine ('2012-08-14 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:14,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,528 INFO sqlalchemy.engine.base.Engine ('2012-08-15 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:14,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,529 INFO sqlalchemy.engine.base.Engine ('2012-08-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,531 INFO sqlalchemy.engine.base.Engine ('2012-08-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,534 INFO sqlalchemy.engine.base.Engine ('2012-08-20 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:14,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,536 INFO sqlalchemy.engine.base.Engine ('2012-08-21 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:14,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,538 INFO sqlalchemy.engine.base.Engine ('2012-08-22 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:14,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,540 INFO sqlalchemy.engine.base.Engine ('2012-08-23 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:14,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,542 INFO sqlalchemy.engine.base.Engine ('2012-08-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,544 INFO sqlalchemy.engine.base.Engine ('2012-08-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,545 INFO sqlalchemy.engine.base.Engine ('2012-08-26 00:00:00.000000', 0.02, 74)

2018-05-08 18:31:14,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,547 INFO sqlalchemy.engine.base.Engine ('2012-08-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,548 INFO sqlalchemy.engine.base.Engine ('2012-08-28 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:14,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,549 INFO sqlalchemy.engine.base.Engine ('2012-08-29 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:14,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,551 INFO sqlalchemy.engine.base.Engine ('2012-08-30 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:14,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,552 INFO sqlalchemy.engine.base.Engine ('2012-08-31 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:14,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,554 INFO sqlalchemy.engine.base.Engine ('2012-09-01 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,555 INFO sqlalchemy.engine.base.Engine ('2012-09-02 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:14,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,599 INFO sqlalchemy.engine.base.Engine ('2012-09-03 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:14,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,601 INFO sqlalchemy.engine.base.Engine ('2012-09-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,603 INFO sqlalchemy.engine.base.Engine ('2012-09-05 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,605 INFO sqlalchemy.engine.base.Engine ('2012-09-06 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,606 INFO sqlalchemy.engine.base.Engine ('2012-09-07 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:14,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,608 INFO sqlalchemy.engine.base.Engine ('2012-09-08 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:14,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,610 INFO sqlalchemy.engine.base.Engine ('2012-09-09 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:14,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,612 INFO sqlalchemy.engine.base.Engine ('2012-09-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,613 INFO sqlalchemy.engine.base.Engine ('2012-09-11 00:00:00.000000', 0.18, 74)
2018-05-08 18:31:14,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,615 INFO sqlalchemy.engine.base.Engine ('2012-09-12 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:14,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,616 INFO sqlalchemy.engine.base.Engine ('2012-09-13 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:14,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,618 INFO sqlalchemy.engine.base.Engine ('2012-09-14 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:14,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,620 INFO sqlalchemy.engine.base.Engine ('2012-09-15 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:14,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,621 INFO sqlalchemy.engine.base.Engine ('2012-09-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,623 INFO sqlalchemy.engine.base.Engine ('2012-09-17 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:14,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,626 INFO sqlalchemy.engine.base.Engine ('2012-09-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,628 INFO sqlalchemy.engine.base.Engine ('2012-09-19 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:14,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,629 INFO sqlalchemy.engine.base.Engine ('2012-09-20 00:00:00.000000', 0.55, 71)
2018-05-08 18:31:14,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,631 INFO sqlalchemy.engine.base.Engine ('2012-09-23 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,633 INFO sqlalchemy.engine.base.Engine ('2012-09-24 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:14,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,635 INFO sqlalchemy.engine.base.Engine ('2012-09-25 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:14,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,636 INFO sqlalchemy.engine.base.Engine ('2012-09-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,638 INFO sqlalchemy.engine.base.Engine ('2012-09-27 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:14,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,639 INFO sqlalchemy.engine.base.Engine ('2012-09-28 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:14,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,641 INFO sqlalchemy.engine.base.Engine ('2012-09-29 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:14,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,643 INFO sqlalchemy.engine.base.Engine ('2012-09-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,644 INFO sqlalchemy.engine.base.Engine ('2012-10-01 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:14,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,646 INFO sqlalchemy.engine.base.Engine ('2012-10-02 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:14,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,648 INFO sqlalchemy.engine.base.Engine ('2012-10-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,649 INFO sqlalchemy.engine.base.Engine ('2012-10-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,651 INFO sqlalchemy.engine.base.Engine ('2012-10-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,654 INFO sqlalchemy.engine.base.Engine ('2012-10-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,656 INFO sqlalchemy.engine.base.Engine ('2012-10-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,658 INFO sqlalchemy.engine.base.Engine ('2012-10-08 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:14,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,660 INFO sqlalchemy.engine.base.Engine ('2012-10-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,662 INFO sqlalchemy.engine.base.Engine ('2012-10-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,663 INFO sqlalchemy.engine.base.Engine ('2012-10-11 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:14,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,665 INFO sqlalchemy.engine.base.Engine ('2012-10-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,666 INFO sqlalchemy.engine.base.Engine ('2012-10-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,668 INFO sqlalchemy.engine.base.Engine ('2012-10-14 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:14,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,669 INFO sqlalchemy.engine.base.Engine ('2012-10-15 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:14,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,670 INFO sqlalchemy.engine.base.Engine ('2012-10-16 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:14,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,672 INFO sqlalchemy.engine.base.Engine ('2012-10-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,673 INFO sqlalchemy.engine.base.Engine ('2012-10-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,675 INFO sqlalchemy.engine.base.Engine ('2012-10-19 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:14,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,677 INFO sqlalchemy.engine.base.Engine ('2012-10-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,679 INFO sqlalchemy.engine.base.Engine ('2012-10-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,680 INFO sqlalchemy.engine.base.Engine ('2012-10-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:14,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,682 INFO sqlalchemy.engine.base.Engine ('2012-10-23 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:14,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,684 INFO sqlalchemy.engine.base.Engine ('2012-10-24 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:14,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,687 INFO sqlalchemy.engine.base.Engine ('2012-10-25 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:14,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,689 INFO sqlalchemy.engine.base.Engine ('2012-10-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,690 INFO sqlalchemy.engine.base.Engine ('2012-10-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,692 INFO sqlalchemy.engine.base.Engine ('2012-10-28 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,694 INFO sqlalchemy.engine.base.Engine ('2012-10-29 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:14,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,696 INFO sqlalchemy.engine.base.Engine ('2012-10-30 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:14,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,697 INFO sqlalchemy.engine.base.Engine ('2012-10-31 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:14,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,699 INFO sqlalchemy.engine.base.Engine ('2012-11-01 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,700 INFO sqlalchemy.engine.base.Engine ('2012-11-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,702 INFO sqlalchemy.engine.base.Engine ('2012-11-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,703 INFO sqlalchemy.engine.base.Engine ('2012-11-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,705 INFO sqlalchemy.engine.base.Engine ('2012-11-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,707 INFO sqlalchemy.engine.base.Engine ('2012-11-06 00:00:00.000000', 0.0, 74)

2018-05-08 18:31:14,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,708 INFO sqlalchemy.engine.base.Engine ('2012-11-07 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:14,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,710 INFO sqlalchemy.engine.base.Engine ('2012-11-08 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:14,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,712 INFO sqlalchemy.engine.base.Engine ('2012-11-09 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:14,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,713 INFO sqlalchemy.engine.base.Engine ('2012-11-10 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:14,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,715 INFO sqlalchemy.engine.base.Engine ('2012-11-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,716 INFO sqlalchemy.engine.base.Engine ('2012-11-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,718 INFO sqlalchemy.engine.base.Engine ('2012-11-13 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:14,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,719 INFO sqlalchemy.engine.base.Engine ('2012-11-14 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:14,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,721 INFO sqlalchemy.engine.base.Engine ('2012-11-15 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:14,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,722 INFO sqlalchemy.engine.base.Engine ('2012-11-16 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:14,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,724 INFO sqlalchemy.engine.base.Engine ('2012-11-17 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:14,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,727 INFO sqlalchemy.engine.base.Engine ('2012-11-18 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:14,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,730 INFO sqlalchemy.engine.base.Engine ('2012-11-19 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:14,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,731 INFO sqlalchemy.engine.base.Engine ('2012-11-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,733 INFO sqlalchemy.engine.base.Engine ('2012-11-21 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:14,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,735 INFO sqlalchemy.engine.base.Engine ('2012-11-22 00:00:00.000000', 0.88, 67)
2018-05-08 18:31:14,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,736 INFO sqlalchemy.engine.base.Engine ('2012-11-23 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,738 INFO sqlalchemy.engine.base.Engine ('2012-11-24 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:14,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,740 INFO sqlalchemy.engine.base.Engine ('2012-11-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,742 INFO sqlalchemy.engine.base.Engine ('2012-11-26 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:14,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,743 INFO sqlalchemy.engine.base.Engine ('2012-11-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,745 INFO sqlalchemy.engine.base.Engine ('2012-11-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,747 INFO sqlalchemy.engine.base.Engine ('2012-11-29 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,748 INFO sqlalchemy.engine.base.Engine ('2012-11-30 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,749 INFO sqlalchemy.engine.base.Engine ('2012-12-01 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,751 INFO sqlalchemy.engine.base.Engine ('2012-12-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,752 INFO sqlalchemy.engine.base.Engine ('2012-12-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:14,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,754 INFO sqlalchemy.engine.base.Engine ('2012-12-04 00:00:00.000000', 0.18, 68)
2018-05-08 18:31:14,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,756 INFO sqlalchemy.engine.base.Engine ('2012-12-05 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:14,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,759 INFO sqlalchemy.engine.base.Engine ('2012-12-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,761 INFO sqlalchemy.engine.base.Engine ('2012-12-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,763 INFO sqlalchemy.engine.base.Engine ('2012-12-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,764 INFO sqlalchemy.engine.base.Engine ('2012-12-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,766 INFO sqlalchemy.engine.base.Engine ('2012-12-10 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:14,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,767 INFO sqlalchemy.engine.base.Engine ('2012-12-11 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:14,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,769 INFO sqlalchemy.engine.base.Engine ('2012-12-12 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:14,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,770 INFO sqlalchemy.engine.base.Engine ('2012-12-13 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:14,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,824 INFO sqlalchemy.engine.base.Engine ('2012-12-14 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:14,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,825 INFO sqlalchemy.engine.base.Engine ('2012-12-15 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:14,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,827 INFO sqlalchemy.engine.base.Engine ('2012-12-16 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:14,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,828 INFO sqlalchemy.engine.base.Engine ('2012-12-17 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:14,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,830 INFO sqlalchemy.engine.base.Engine ('2012-12-18 00:00:00.000000', 0.2, 71)
2018-05-08 18:31:14,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,832 INFO sqlalchemy.engine.base.Engine ('2012-12-19 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:14,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,833 INFO sqlalchemy.engine.base.Engine ('2012-12-20 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:14,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,835 INFO sqlalchemy.engine.base.Engine ('2012-12-21 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:14,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,836 INFO sqlalchemy.engine.base.Engine ('2012-12-22 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:14,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,838 INFO sqlalchemy.engine.base.Engine ('2012-12-23 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:14,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,839 INFO sqlalchemy.engine.base.Engine ('2012-12-24 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,842 INFO sqlalchemy.engine.base.Engine ('2012-12-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,844 INFO sqlalchemy.engine.base.Engine ('2012-12-26 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:14,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,846 INFO sqlalchemy.engine.base.Engine ('2012-12-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:14,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,848 INFO sqlalchemy.engine.base.Engine ('2012-12-28 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,850 INFO sqlalchemy.engine.base.Engine ('2012-12-29 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,852 INFO sqlalchemy.engine.base.Engine ('2012-12-30 00:00:00.000000', 0.21, 68)
2018-05-08 18:31:14,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,853 INFO sqlalchemy.engine.base.Engine ('2012-12-31 00:00:00.000000', 0.17, 67)
2018-05-08 18:31:14,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,855 INFO sqlalchemy.engine.base.Engine ('2013-01-01 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:14,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,856 INFO sqlalchemy.engine.base.Engine ('2013-01-02 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:14,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,858 INFO sqlalchemy.engine.base.Engine ('2013-01-03 00:00:00.000000', 0.23, 68)
2018-05-08 18:31:14,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,859 INFO sqlalchemy.engine.base.Engine ('2013-01-04 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:14,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,861 INFO sqlalchemy.engine.base.Engine ('2013-01-05 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:14,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,863 INFO sqlalchemy.engine.base.Engine ('2013-01-06 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:14,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,864 INFO sqlalchemy.engine.base.Engine ('2013-01-07 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:14,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,866 INFO sqlalchemy.engine.base.Engine ('2013-01-08 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:14,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,867 INFO sqlalchemy.engine.base.Engine ('2013-01-09 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:14,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,870 INFO sqlalchemy.engine.base.Engine ('2013-01-10 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:14,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,872 INFO sqlalchemy.engine.base.Engine ('2013-01-11 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:14,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,873 INFO sqlalchemy.engine.base.Engine ('2013-01-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,874 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,875 INFO sqlalchemy.engine.base.Engine ('2013-01-15 00:00:00.000000', 1.27, 64)
2018-05-08 18:31:14,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,876 INFO sqlalchemy.engine.base.Engine ('2013-01-16 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:14,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,878 INFO sqlalchemy.engine.base.Engine ('2013-01-17 00:00:00.000000', 0.1, 62)

2018-05-08 18:31:14,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,879 INFO sqlalchemy.engine.base.Engine ('2013-01-18 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:14,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,881 INFO sqlalchemy.engine.base.Engine ('2013-01-19 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,883 INFO sqlalchemy.engine.base.Engine ('2013-01-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,885 INFO sqlalchemy.engine.base.Engine ('2013-01-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,886 INFO sqlalchemy.engine.base.Engine ('2013-01-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,888 INFO sqlalchemy.engine.base.Engine ('2013-01-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,891 INFO sqlalchemy.engine.base.Engine ('2013-01-24 00:00:00.000000', 0.71, 67)
2018-05-08 18:31:14,892 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,893 INFO sqlalchemy.engine.base.Engine ('2013-01-25 00:00:00.000000', 0.59, 64)
2018-05-08 18:31:14,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,895 INFO sqlalchemy.engine.base.Engine ('2013-01-26 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:14,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,897 INFO sqlalchemy.engine.base.Engine ('2013-01-27 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:14,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,899 INFO sqlalchemy.engine.base.Engine ('2013-01-28 00:00:00.000000', 2.6, 64)
2018-05-08 18:31:14,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,900 INFO sqlalchemy.engine.base.Engine ('2013-01-29 00:00:00.000000', 0.71, 65)
2018-05-08 18:31:14,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,902 INFO sqlalchemy.engine.base.Engine ('2013-01-30 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:14,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,903 INFO sqlalchemy.engine.base.Engine ('2013-01-31 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,905 INFO sqlalchemy.engine.base.Engine ('2013-02-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,907 INFO sqlalchemy.engine.base.Engine ('2013-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,909 INFO sqlalchemy.engine.base.Engine ('2013-02-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:14,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,910 INFO sqlalchemy.engine.base.Engine ('2013-02-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,912 INFO sqlalchemy.engine.base.Engine ('2013-02-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,914 INFO sqlalchemy.engine.base.Engine ('2013-02-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,915 INFO sqlalchemy.engine.base.Engine ('2013-02-07 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:14,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,918 INFO sqlalchemy.engine.base.Engine ('2013-02-08 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:14,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,920 INFO sqlalchemy.engine.base.Engine ('2013-02-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,922 INFO sqlalchemy.engine.base.Engine ('2013-02-10 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:14,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,924 INFO sqlalchemy.engine.base.Engine ('2013-02-11 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:14,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,926 INFO sqlalchemy.engine.base.Engine ('2013-02-12 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:14,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,927 INFO sqlalchemy.engine.base.Engine ('2013-02-13 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:14,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,929 INFO sqlalchemy.engine.base.Engine ('2013-02-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,930 INFO sqlalchemy.engine.base.Engine ('2013-02-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,932 INFO sqlalchemy.engine.base.Engine ('2013-02-16 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:14,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,933 INFO sqlalchemy.engine.base.Engine ('2013-02-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:14,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,935 INFO sqlalchemy.engine.base.Engine ('2013-02-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,937 INFO sqlalchemy.engine.base.Engine ('2013-02-19 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:14,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,938 INFO sqlalchemy.engine.base.Engine ('2013-02-20 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:14,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,940 INFO sqlalchemy.engine.base.Engine ('2013-02-21 00:00:00.000000', 0.05, 69)

2018-05-08 18:31:14,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,942 INFO sqlalchemy.engine.base.Engine ('2013-02-22 00:00:00.000000', 0.83, 69)
2018-05-08 18:31:14,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,944 INFO sqlalchemy.engine.base.Engine ('2013-02-23 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:14,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,946 INFO sqlalchemy.engine.base.Engine ('2013-02-24 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:14,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,948 INFO sqlalchemy.engine.base.Engine ('2013-02-25 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:14,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,950 INFO sqlalchemy.engine.base.Engine ('2013-02-26 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:14,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,953 INFO sqlalchemy.engine.base.Engine ('2013-02-27 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:14,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,955 INFO sqlalchemy.engine.base.Engine ('2013-02-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,956 INFO sqlalchemy.engine.base.Engine ('2013-03-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:14,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,958 INFO sqlalchemy.engine.base.Engine ('2013-03-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,960 INFO sqlalchemy.engine.base.Engine ('2013-03-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,962 INFO sqlalchemy.engine.base.Engine ('2013-03-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,963 INFO sqlalchemy.engine.base.Engine ('2013-03-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:14,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,965 INFO sqlalchemy.engine.base.Engine ('2013-03-06 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:14,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,966 INFO sqlalchemy.engine.base.Engine ('2013-03-07 00:00:00.000000', 0.06, 66)
2018-05-08 18:31:14,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,968 INFO sqlalchemy.engine.base.Engine ('2013-03-08 00:00:00.000000', 0.15, 61)
2018-05-08 18:31:14,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,969 INFO sqlalchemy.engine.base.Engine ('2013-03-09 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:14,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,971 INFO sqlalchemy.engine.base.Engine ('2013-03-10 00:00:00.000000', 1.69, 68)
2018-05-08 18:31:14,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,973 INFO sqlalchemy.engine.base.Engine ('2013-03-11 00:00:00.000000', 0.8, 62)
2018-05-08 18:31:14,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,974 INFO sqlalchemy.engine.base.Engine ('2013-03-12 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:14,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,976 INFO sqlalchemy.engine.base.Engine ('2013-03-13 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:14,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,978 INFO sqlalchemy.engine.base.Engine ('2013-03-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:14,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,979 INFO sqlalchemy.engine.base.Engine ('2013-03-15 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:14,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,981 INFO sqlalchemy.engine.base.Engine ('2013-03-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:14,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,982 INFO sqlalchemy.engine.base.Engine ('2013-03-17 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:14,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,983 INFO sqlalchemy.engine.base.Engine ('2013-03-18 00:00:00.000000', 0.49, 59)
2018-05-08 18:31:14,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,985 INFO sqlalchemy.engine.base.Engine ('2013-03-19 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:14,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,987 INFO sqlalchemy.engine.base.Engine ('2013-03-20 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:14,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,989 INFO sqlalchemy.engine.base.Engine ('2013-03-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:14,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,992 INFO sqlalchemy.engine.base.Engine ('2013-03-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:14,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,994 INFO sqlalchemy.engine.base.Engine ('2013-03-23 00:00:00.000000', 0.11, 66)
2018-05-08 18:31:14,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,996 INFO sqlalchemy.engine.base.Engine ('2013-03-24 00:00:00.000000', 0.43, 70)
2018-05-08 18:31:14,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:14,998 INFO sqlalchemy.engine.base.Engine ('2013-03-25 00:00:00.000000', 0.8, 67)
2018-05-08 18:31:15,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,050 INFO sqlalchemy.engine.base.Engine ('2013-03-26 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:15,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,051 INFO sqlalchemy.engine.base.Engine ('2013-03-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,053 INFO sqlalchemy.engine.base.Engine ('2013-03-28 00:00:00.000000', 0.07, 69)

2018-05-08 18:31:15,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,054 INFO sqlalchemy.engine.base.Engine ('2013-03-29 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:15,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,056 INFO sqlalchemy.engine.base.Engine ('2013-03-30 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:15,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,058 INFO sqlalchemy.engine.base.Engine ('2013-03-31 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:15,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,059 INFO sqlalchemy.engine.base.Engine ('2013-04-01 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:15,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,061 INFO sqlalchemy.engine.base.Engine ('2013-04-02 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:15,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,063 INFO sqlalchemy.engine.base.Engine ('2013-04-03 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:15,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,065 INFO sqlalchemy.engine.base.Engine ('2013-04-04 00:00:00.000000', 0.07, 65)
2018-05-08 18:31:15,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,067 INFO sqlalchemy.engine.base.Engine ('2013-04-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,070 INFO sqlalchemy.engine.base.Engine ('2013-04-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,072 INFO sqlalchemy.engine.base.Engine ('2013-04-07 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:15,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,073 INFO sqlalchemy.engine.base.Engine ('2013-04-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,075 INFO sqlalchemy.engine.base.Engine ('2013-04-09 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:15,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,077 INFO sqlalchemy.engine.base.Engine ('2013-04-10 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:15,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,078 INFO sqlalchemy.engine.base.Engine ('2013-04-11 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:15,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,080 INFO sqlalchemy.engine.base.Engine ('2013-04-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,081 INFO sqlalchemy.engine.base.Engine ('2013-04-13 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:15,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,083 INFO sqlalchemy.engine.base.Engine ('2013-04-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,084 INFO sqlalchemy.engine.base.Engine ('2013-04-15 00:00:00.000000', 0.43, 69)
2018-05-08 18:31:15,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,086 INFO sqlalchemy.engine.base.Engine ('2013-04-16 00:00:00.000000', 0.19, 65)
2018-05-08 18:31:15,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,087 INFO sqlalchemy.engine.base.Engine ('2013-04-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,089 INFO sqlalchemy.engine.base.Engine ('2013-04-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,091 INFO sqlalchemy.engine.base.Engine ('2013-04-19 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:15,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,092 INFO sqlalchemy.engine.base.Engine ('2013-04-20 00:00:00.000000', 0.11, 77)
2018-05-08 18:31:15,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,094 INFO sqlalchemy.engine.base.Engine ('2013-04-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,095 INFO sqlalchemy.engine.base.Engine ('2013-04-22 00:00:00.000000', 0.44, 70)
2018-05-08 18:31:15,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,097 INFO sqlalchemy.engine.base.Engine ('2013-04-23 00:00:00.000000', 0.37, 74)
2018-05-08 18:31:15,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,100 INFO sqlalchemy.engine.base.Engine ('2013-04-24 00:00:00.000000', 0.76, 67)
2018-05-08 18:31:15,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,102 INFO sqlalchemy.engine.base.Engine ('2013-04-25 00:00:00.000000', 0.94, 70)
2018-05-08 18:31:15,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,104 INFO sqlalchemy.engine.base.Engine ('2013-04-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,106 INFO sqlalchemy.engine.base.Engine ('2013-04-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,107 INFO sqlalchemy.engine.base.Engine ('2013-04-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:15,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,109 INFO sqlalchemy.engine.base.Engine ('2013-04-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,111 INFO sqlalchemy.engine.base.Engine ('2013-04-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,112 INFO sqlalchemy.engine.base.Engine ('2013-05-01 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:15,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,114 INFO sqlalchemy.engine.base.Engine ('2013-05-02 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:15,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,115 INFO sqlalchemy.engine.base.Engine ('2013-05-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,117 INFO sqlalchemy.engine.base.Engine ('2013-05-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,118 INFO sqlalchemy.engine.base.Engine ('2013-05-05 00:00:00.000000', 1.05, 72)
2018-05-08 18:31:15,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,120 INFO sqlalchemy.engine.base.Engine ('2013-05-06 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:15,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,122 INFO sqlalchemy.engine.base.Engine ('2013-05-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:15,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,123 INFO sqlalchemy.engine.base.Engine ('2013-05-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,125 INFO sqlalchemy.engine.base.Engine ('2013-05-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,126 INFO sqlalchemy.engine.base.Engine ('2013-05-10 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:15,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,128 INFO sqlalchemy.engine.base.Engine ('2013-05-11 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:15,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,130 INFO sqlalchemy.engine.base.Engine ('2013-05-12 00:00:00.000000', 0.22, 68)
2018-05-08 18:31:15,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,131 INFO sqlalchemy.engine.base.Engine ('2013-05-13 00:00:00.000000', 0.95, 73)
2018-05-08 18:31:15,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,133 INFO sqlalchemy.engine.base.Engine ('2013-05-14 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:15,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,135 INFO sqlalchemy.engine.base.Engine ('2013-05-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,137 INFO sqlalchemy.engine.base.Engine ('2013-05-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,140 INFO sqlalchemy.engine.base.Engine ('2013-05-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,142 INFO sqlalchemy.engine.base.Engine ('2013-05-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:15,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,144 INFO sqlalchemy.engine.base.Engine ('2013-05-19 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:15,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,146 INFO sqlalchemy.engine.base.Engine ('2013-05-20 00:00:00.000000', 0.54, 68)
2018-05-08 18:31:15,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,148 INFO sqlalchemy.engine.base.Engine ('2013-05-21 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:15,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,149 INFO sqlalchemy.engine.base.Engine ('2013-05-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,151 INFO sqlalchemy.engine.base.Engine ('2013-05-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,152 INFO sqlalchemy.engine.base.Engine ('2013-05-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,154 INFO sqlalchemy.engine.base.Engine ('2013-05-25 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:15,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,156 INFO sqlalchemy.engine.base.Engine ('2013-05-26 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:15,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,158 INFO sqlalchemy.engine.base.Engine ('2013-05-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:15,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,161 INFO sqlalchemy.engine.base.Engine ('2013-05-28 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:15,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,164 INFO sqlalchemy.engine.base.Engine ('2013-05-29 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:15,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,165 INFO sqlalchemy.engine.base.Engine ('2013-05-30 00:00:00.000000', 0.74, 77)
2018-05-08 18:31:15,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,167 INFO sqlalchemy.engine.base.Engine ('2013-05-31 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:15,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,168 INFO sqlalchemy.engine.base.Engine ('2013-06-01 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:15,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,170 INFO sqlalchemy.engine.base.Engine ('2013-06-02 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:15,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,172 INFO sqlalchemy.engine.base.Engine ('2013-06-03 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:15,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,174 INFO sqlalchemy.engine.base.Engine ('2013-06-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,177 INFO sqlalchemy.engine.base.Engine ('2013-06-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,180 INFO sqlalchemy.engine.base.Engine ('2013-06-06 00:00:00.000000', 0.03, 74)

2018-05-08 18:31:15,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,182 INFO sqlalchemy.engine.base.Engine ('2013-06-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,184 INFO sqlalchemy.engine.base.Engine ('2013-06-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,185 INFO sqlalchemy.engine.base.Engine ('2013-06-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,187 INFO sqlalchemy.engine.base.Engine ('2013-06-10 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:15,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,188 INFO sqlalchemy.engine.base.Engine ('2013-06-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,190 INFO sqlalchemy.engine.base.Engine ('2013-06-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,192 INFO sqlalchemy.engine.base.Engine ('2013-06-13 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:15,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,194 INFO sqlalchemy.engine.base.Engine ('2013-06-14 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:15,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,195 INFO sqlalchemy.engine.base.Engine ('2013-06-15 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:15,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,198 INFO sqlalchemy.engine.base.Engine ('2013-06-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,200 INFO sqlalchemy.engine.base.Engine ('2013-06-17 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:15,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,202 INFO sqlalchemy.engine.base.Engine ('2013-06-18 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:15,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,204 INFO sqlalchemy.engine.base.Engine ('2013-06-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,205 INFO sqlalchemy.engine.base.Engine ('2013-06-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,207 INFO sqlalchemy.engine.base.Engine ('2013-06-21 00:00:00.000000', 0.22, 70)
2018-05-08 18:31:15,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,209 INFO sqlalchemy.engine.base.Engine ('2013-06-22 00:00:00.000000', 0.27, 75)
2018-05-08 18:31:15,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,210 INFO sqlalchemy.engine.base.Engine ('2013-06-23 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:15,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,212 INFO sqlalchemy.engine.base.Engine ('2013-06-24 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:15,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,213 INFO sqlalchemy.engine.base.Engine ('2013-06-25 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:15,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,215 INFO sqlalchemy.engine.base.Engine ('2013-06-26 00:00:00.000000', 1.0, 70)
2018-05-08 18:31:15,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,216 INFO sqlalchemy.engine.base.Engine ('2013-06-27 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:15,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,218 INFO sqlalchemy.engine.base.Engine ('2013-06-28 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:15,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,219 INFO sqlalchemy.engine.base.Engine ('2013-06-29 00:00:00.000000', 0.22, 71)
2018-05-08 18:31:15,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,221 INFO sqlalchemy.engine.base.Engine ('2013-06-30 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:15,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,223 INFO sqlalchemy.engine.base.Engine ('2013-07-02 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:15,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,224 INFO sqlalchemy.engine.base.Engine ('2013-07-03 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:15,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,228 INFO sqlalchemy.engine.base.Engine ('2013-07-04 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:15,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,270 INFO sqlalchemy.engine.base.Engine ('2013-07-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,272 INFO sqlalchemy.engine.base.Engine ('2013-07-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,273 INFO sqlalchemy.engine.base.Engine ('2013-07-07 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:15,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,275 INFO sqlalchemy.engine.base.Engine ('2013-07-08 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:15,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,277 INFO sqlalchemy.engine.base.Engine ('2013-07-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,278 INFO sqlalchemy.engine.base.Engine ('2013-07-10 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:15,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,280 INFO sqlalchemy.engine.base.Engine ('2013-07-11 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:15,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,281 INFO sqlalchemy.engine.base.Engine ('2013-07-12 00:00:00.000000', 0.06, 74)

2018-05-08 18:31:15,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,282 INFO sqlalchemy.engine.base.Engine ('2013-07-13 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:15,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,284 INFO sqlalchemy.engine.base.Engine ('2013-07-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,286 INFO sqlalchemy.engine.base.Engine ('2013-07-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,287 INFO sqlalchemy.engine.base.Engine ('2013-07-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,289 INFO sqlalchemy.engine.base.Engine ('2013-07-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,291 INFO sqlalchemy.engine.base.Engine ('2013-07-18 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:15,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,292 INFO sqlalchemy.engine.base.Engine ('2013-07-19 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:15,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,294 INFO sqlalchemy.engine.base.Engine ('2013-07-20 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:15,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,296 INFO sqlalchemy.engine.base.Engine ('2013-07-21 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:15,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,297 INFO sqlalchemy.engine.base.Engine ('2013-07-22 00:00:00.000000', 0.3, 74)
2018-05-08 18:31:15,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,299 INFO sqlalchemy.engine.base.Engine ('2013-07-23 00:00:00.000000', 0.83, 73)
2018-05-08 18:31:15,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,302 INFO sqlalchemy.engine.base.Engine ('2013-07-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,304 INFO sqlalchemy.engine.base.Engine ('2013-07-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,306 INFO sqlalchemy.engine.base.Engine ('2013-07-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,308 INFO sqlalchemy.engine.base.Engine ('2013-07-29 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:15,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,310 INFO sqlalchemy.engine.base.Engine ('2013-07-30 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:15,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,311 INFO sqlalchemy.engine.base.Engine ('2013-07-31 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:15,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,313 INFO sqlalchemy.engine.base.Engine ('2013-08-01 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:15,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,315 INFO sqlalchemy.engine.base.Engine ('2013-08-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,317 INFO sqlalchemy.engine.base.Engine ('2013-08-03 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:15,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,318 INFO sqlalchemy.engine.base.Engine ('2013-08-04 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:15,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,320 INFO sqlalchemy.engine.base.Engine ('2013-08-05 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:15,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,323 INFO sqlalchemy.engine.base.Engine ('2013-08-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,325 INFO sqlalchemy.engine.base.Engine ('2013-08-07 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:15,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,327 INFO sqlalchemy.engine.base.Engine ('2013-08-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,328 INFO sqlalchemy.engine.base.Engine ('2013-08-09 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,330 INFO sqlalchemy.engine.base.Engine ('2013-08-10 00:00:00.000000', 1.9, 72)
2018-05-08 18:31:15,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,331 INFO sqlalchemy.engine.base.Engine ('2013-08-11 00:00:00.000000', 1.09, 76)
2018-05-08 18:31:15,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,333 INFO sqlalchemy.engine.base.Engine ('2013-08-12 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:15,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,335 INFO sqlalchemy.engine.base.Engine ('2013-08-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,336 INFO sqlalchemy.engine.base.Engine ('2013-08-14 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:15,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,338 INFO sqlalchemy.engine.base.Engine ('2013-08-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,340 INFO sqlalchemy.engine.base.Engine ('2013-08-16 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:15,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,343 INFO sqlalchemy.engine.base.Engine ('2013-08-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,345 INFO sqlalchemy.engine.base.Engine ('2013-08-18 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:15,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,347 INFO sqlalchemy.engine.base.Engine ('2013-08-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,348 INFO sqlalchemy.engine.base.Engine ('2013-08-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,350 INFO sqlalchemy.engine.base.Engine ('2013-08-21 00:00:00.000000', 0.57, 73)
2018-05-08 18:31:15,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,352 INFO sqlalchemy.engine.base.Engine ('2013-08-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,354 INFO sqlalchemy.engine.base.Engine ('2013-08-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,356 INFO sqlalchemy.engine.base.Engine ('2013-08-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:15,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,357 INFO sqlalchemy.engine.base.Engine ('2013-08-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,359 INFO sqlalchemy.engine.base.Engine ('2013-08-26 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:15,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,361 INFO sqlalchemy.engine.base.Engine ('2013-08-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,364 INFO sqlalchemy.engine.base.Engine ('2013-08-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,367 INFO sqlalchemy.engine.base.Engine ('2013-08-29 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:15,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,369 INFO sqlalchemy.engine.base.Engine ('2013-08-30 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:15,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,371 INFO sqlalchemy.engine.base.Engine ('2013-08-31 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:15,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,372 INFO sqlalchemy.engine.base.Engine ('2013-09-01 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:15,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,375 INFO sqlalchemy.engine.base.Engine ('2013-09-02 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:15,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,376 INFO sqlalchemy.engine.base.Engine ('2013-09-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:15,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,378 INFO sqlalchemy.engine.base.Engine ('2013-09-04 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:15,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,380 INFO sqlalchemy.engine.base.Engine ('2013-09-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,381 INFO sqlalchemy.engine.base.Engine ('2013-09-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,383 INFO sqlalchemy.engine.base.Engine ('2013-09-07 00:00:00.000000', 0.55, 73)
2018-05-08 18:31:15,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,385 INFO sqlalchemy.engine.base.Engine ('2013-09-08 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:15,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,387 INFO sqlalchemy.engine.base.Engine ('2013-09-09 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:15,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,389 INFO sqlalchemy.engine.base.Engine ('2013-09-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,390 INFO sqlalchemy.engine.base.Engine ('2013-09-11 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:15,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,393 INFO sqlalchemy.engine.base.Engine ('2013-09-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,395 INFO sqlalchemy.engine.base.Engine ('2013-09-13 00:00:00.000000', 0.51, 74)
2018-05-08 18:31:15,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,398 INFO sqlalchemy.engine.base.Engine ('2013-09-14 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:15,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,400 INFO sqlalchemy.engine.base.Engine ('2013-09-15 00:00:00.000000', 0.2, 78)
2018-05-08 18:31:15,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,402 INFO sqlalchemy.engine.base.Engine ('2013-09-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:15,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,404 INFO sqlalchemy.engine.base.Engine ('2013-09-17 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:15,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,406 INFO sqlalchemy.engine.base.Engine ('2013-09-18 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:15,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,408 INFO sqlalchemy.engine.base.Engine ('2013-09-19 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:15,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,409 INFO sqlalchemy.engine.base.Engine ('2013-09-20 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:15,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,411 INFO sqlalchemy.engine.base.Engine ('2013-09-21 00:00:00.000000', 0.02, 84)
2018-05-08 18:31:15,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,413 INFO sqlalchemy.engine.base.Engine ('2013-09-22 00:00:00.000000', 0.07, 77)

2018-05-08 18:31:15,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,414 INFO sqlalchemy.engine.base.Engine ('2013-09-23 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:15,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,421 INFO sqlalchemy.engine.base.Engine ('2013-09-24 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:15,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,422 INFO sqlalchemy.engine.base.Engine ('2013-09-25 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:15,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,424 INFO sqlalchemy.engine.base.Engine ('2013-09-26 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:15,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,426 INFO sqlalchemy.engine.base.Engine ('2013-09-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,428 INFO sqlalchemy.engine.base.Engine ('2013-09-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:15,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,431 INFO sqlalchemy.engine.base.Engine ('2013-09-29 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:15,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,433 INFO sqlalchemy.engine.base.Engine ('2013-09-30 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:15,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,435 INFO sqlalchemy.engine.base.Engine ('2013-10-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,437 INFO sqlalchemy.engine.base.Engine ('2013-10-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,439 INFO sqlalchemy.engine.base.Engine ('2013-10-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,441 INFO sqlalchemy.engine.base.Engine ('2013-10-04 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:15,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,442 INFO sqlalchemy.engine.base.Engine ('2013-10-05 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:15,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,445 INFO sqlalchemy.engine.base.Engine ('2013-10-06 00:00:00.000000', 0.33, 76)
2018-05-08 18:31:15,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,447 INFO sqlalchemy.engine.base.Engine ('2013-10-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,449 INFO sqlalchemy.engine.base.Engine ('2013-10-08 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:15,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,450 INFO sqlalchemy.engine.base.Engine ('2013-10-09 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:15,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,452 INFO sqlalchemy.engine.base.Engine ('2013-10-10 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:15,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,454 INFO sqlalchemy.engine.base.Engine ('2013-10-11 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:15,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,456 INFO sqlalchemy.engine.base.Engine ('2013-10-12 00:00:00.000000', 0.63, 76)
2018-05-08 18:31:15,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,458 INFO sqlalchemy.engine.base.Engine ('2013-10-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:15,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,460 INFO sqlalchemy.engine.base.Engine ('2013-10-14 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:15,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,512 INFO sqlalchemy.engine.base.Engine ('2013-10-15 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:15,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,514 INFO sqlalchemy.engine.base.Engine ('2013-10-16 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:15,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,516 INFO sqlalchemy.engine.base.Engine ('2013-10-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,517 INFO sqlalchemy.engine.base.Engine ('2013-10-18 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:15,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,519 INFO sqlalchemy.engine.base.Engine ('2013-10-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,521 INFO sqlalchemy.engine.base.Engine ('2013-10-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,523 INFO sqlalchemy.engine.base.Engine ('2013-10-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,525 INFO sqlalchemy.engine.base.Engine ('2013-10-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,527 INFO sqlalchemy.engine.base.Engine ('2013-10-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,530 INFO sqlalchemy.engine.base.Engine ('2013-10-24 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:15,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,532 INFO sqlalchemy.engine.base.Engine ('2013-10-25 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:15,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,534 INFO sqlalchemy.engine.base.Engine ('2013-10-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,536 INFO sqlalchemy.engine.base.Engine ('2013-10-27 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:15,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,538 INFO sqlalchemy.engine.base.Engine ('2013-10-28 00:00:00.000000', 0.7, 72)
2018-05-08 18:31:15,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,540 INFO sqlalchemy.engine.base.Engine ('2013-10-29 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:15,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,542 INFO sqlalchemy.engine.base.Engine ('2013-10-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,544 INFO sqlalchemy.engine.base.Engine ('2013-10-31 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:15,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,546 INFO sqlalchemy.engine.base.Engine ('2013-11-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:15,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,547 INFO sqlalchemy.engine.base.Engine ('2013-11-02 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:15,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,549 INFO sqlalchemy.engine.base.Engine ('2013-11-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,552 INFO sqlalchemy.engine.base.Engine ('2013-11-04 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:15,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,554 INFO sqlalchemy.engine.base.Engine ('2013-11-05 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,556 INFO sqlalchemy.engine.base.Engine ('2013-11-06 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:15,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,558 INFO sqlalchemy.engine.base.Engine ('2013-11-07 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:15,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,560 INFO sqlalchemy.engine.base.Engine ('2013-11-08 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:15,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,563 INFO sqlalchemy.engine.base.Engine ('2013-11-09 00:00:00.000000', 0.76, 74)
2018-05-08 18:31:15,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,565 INFO sqlalchemy.engine.base.Engine ('2013-11-10 00:00:00.000000', 3.03, 74)
2018-05-08 18:31:15,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,567 INFO sqlalchemy.engine.base.Engine ('2013-11-11 00:00:00.000000', 0.27, 76)
2018-05-08 18:31:15,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,569 INFO sqlalchemy.engine.base.Engine ('2013-11-12 00:00:00.000000', 0.26, 65)
2018-05-08 18:31:15,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,571 INFO sqlalchemy.engine.base.Engine ('2013-11-13 00:00:00.000000', 0.12, 65)
2018-05-08 18:31:15,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,573 INFO sqlalchemy.engine.base.Engine ('2013-11-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,575 INFO sqlalchemy.engine.base.Engine ('2013-11-15 00:00:00.000000', 0.76, 72)
2018-05-08 18:31:15,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,577 INFO sqlalchemy.engine.base.Engine ('2013-11-16 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:15,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,579 INFO sqlalchemy.engine.base.Engine ('2013-11-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,580 INFO sqlalchemy.engine.base.Engine ('2013-11-18 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:15,581 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,582 INFO sqlalchemy.engine.base.Engine ('2013-11-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,584 INFO sqlalchemy.engine.base.Engine ('2013-11-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,586 INFO sqlalchemy.engine.base.Engine ('2013-11-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,588 INFO sqlalchemy.engine.base.Engine ('2013-11-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,590 INFO sqlalchemy.engine.base.Engine ('2013-11-23 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:15,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,592 INFO sqlalchemy.engine.base.Engine ('2013-11-24 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:15,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,595 INFO sqlalchemy.engine.base.Engine ('2013-11-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,597 INFO sqlalchemy.engine.base.Engine ('2013-11-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,600 INFO sqlalchemy.engine.base.Engine ('2013-11-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,603 INFO sqlalchemy.engine.base.Engine ('2013-11-28 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:15,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,605 INFO sqlalchemy.engine.base.Engine ('2013-11-29 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:15,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,607 INFO sqlalchemy.engine.base.Engine ('2013-11-30 00:00:00.000000', 0.73, 77)
2018-05-08 18:31:15,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,608 INFO sqlalchemy.engine.base.Engine ('2013-12-01 00:00:00.000000', 0.0, 76)

2018-05-08 18:31:15,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,610 INFO sqlalchemy.engine.base.Engine ('2013-12-02 00:00:00.000000', 0.93, 70)
2018-05-08 18:31:15,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,612 INFO sqlalchemy.engine.base.Engine ('2013-12-03 00:00:00.000000', 0.8, 71)
2018-05-08 18:31:15,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,613 INFO sqlalchemy.engine.base.Engine ('2013-12-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,615 INFO sqlalchemy.engine.base.Engine ('2013-12-05 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:15,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,616 INFO sqlalchemy.engine.base.Engine ('2013-12-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,618 INFO sqlalchemy.engine.base.Engine ('2013-12-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,621 INFO sqlalchemy.engine.base.Engine ('2013-12-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,624 INFO sqlalchemy.engine.base.Engine ('2013-12-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,626 INFO sqlalchemy.engine.base.Engine ('2013-12-10 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:15,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,628 INFO sqlalchemy.engine.base.Engine ('2013-12-11 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:15,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,629 INFO sqlalchemy.engine.base.Engine ('2013-12-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,631 INFO sqlalchemy.engine.base.Engine ('2013-12-13 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:15,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,633 INFO sqlalchemy.engine.base.Engine ('2013-12-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,635 INFO sqlalchemy.engine.base.Engine ('2013-12-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,637 INFO sqlalchemy.engine.base.Engine ('2013-12-16 00:00:00.000000', 1.31, 68)
2018-05-08 18:31:15,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,639 INFO sqlalchemy.engine.base.Engine ('2013-12-17 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:15,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,641 INFO sqlalchemy.engine.base.Engine ('2013-12-18 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,643 INFO sqlalchemy.engine.base.Engine ('2013-12-19 00:00:00.000000', 1.0, 70)
2018-05-08 18:31:15,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,646 INFO sqlalchemy.engine.base.Engine ('2013-12-20 00:00:00.000000', 0.41, 72)
2018-05-08 18:31:15,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,649 INFO sqlalchemy.engine.base.Engine ('2013-12-21 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:15,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,651 INFO sqlalchemy.engine.base.Engine ('2013-12-22 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:15,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,653 INFO sqlalchemy.engine.base.Engine ('2013-12-23 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:15,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,654 INFO sqlalchemy.engine.base.Engine ('2013-12-24 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:15,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,655 INFO sqlalchemy.engine.base.Engine ('2013-12-25 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:15,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,657 INFO sqlalchemy.engine.base.Engine ('2013-12-26 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:15,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,659 INFO sqlalchemy.engine.base.Engine ('2013-12-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,661 INFO sqlalchemy.engine.base.Engine ('2013-12-28 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:15,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,664 INFO sqlalchemy.engine.base.Engine ('2013-12-29 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:15,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,666 INFO sqlalchemy.engine.base.Engine ('2013-12-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,667 INFO sqlalchemy.engine.base.Engine ('2013-12-31 00:00:00.000000', 0.09, 68)
2018-05-08 18:31:15,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,669 INFO sqlalchemy.engine.base.Engine ('2014-01-01 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:15,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,673 INFO sqlalchemy.engine.base.Engine ('2014-01-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,675 INFO sqlalchemy.engine.base.Engine ('2014-01-03 00:00:00.000000', 1.59, 67)
2018-05-08 18:31:15,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,677 INFO sqlalchemy.engine.base.Engine ('2014-01-04 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:15,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,679 INFO sqlalchemy.engine.base.Engine ('2014-01-05 00:00:00.000000', 0.02, 69)

2018-05-08 18:31:15,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,680 INFO sqlalchemy.engine.base.Engine ('2014-01-06 00:00:00.000000', 0.19, 66)
2018-05-08 18:31:15,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,682 INFO sqlalchemy.engine.base.Engine ('2014-01-07 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:15,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,683 INFO sqlalchemy.engine.base.Engine ('2014-01-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:15,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,686 INFO sqlalchemy.engine.base.Engine ('2014-01-09 00:00:00.000000', 0.12, 66)
2018-05-08 18:31:15,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,687 INFO sqlalchemy.engine.base.Engine ('2014-01-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,689 INFO sqlalchemy.engine.base.Engine ('2014-01-11 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:15,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,692 INFO sqlalchemy.engine.base.Engine ('2014-01-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:15,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,694 INFO sqlalchemy.engine.base.Engine ('2014-01-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:15,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,697 INFO sqlalchemy.engine.base.Engine ('2014-01-14 00:00:00.000000', 0.89, 72)
2018-05-08 18:31:15,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,699 INFO sqlalchemy.engine.base.Engine ('2014-01-15 00:00:00.000000', 0.19, 68)
2018-05-08 18:31:15,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,701 INFO sqlalchemy.engine.base.Engine ('2014-01-16 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:15,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,702 INFO sqlalchemy.engine.base.Engine ('2014-01-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,704 INFO sqlalchemy.engine.base.Engine ('2014-01-18 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:15,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,705 INFO sqlalchemy.engine.base.Engine ('2014-01-19 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:15,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,708 INFO sqlalchemy.engine.base.Engine ('2014-01-20 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:15,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,710 INFO sqlalchemy.engine.base.Engine ('2014-01-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,712 INFO sqlalchemy.engine.base.Engine ('2014-01-22 00:00:00.000000', 0.65, 71)
2018-05-08 18:31:15,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,767 INFO sqlalchemy.engine.base.Engine ('2014-01-23 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:15,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,769 INFO sqlalchemy.engine.base.Engine ('2014-01-24 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:15,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,771 INFO sqlalchemy.engine.base.Engine ('2014-01-25 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:15,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,772 INFO sqlalchemy.engine.base.Engine ('2014-01-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:15,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,775 INFO sqlalchemy.engine.base.Engine ('2014-01-27 00:00:00.000000', 0.31, 68)
2018-05-08 18:31:15,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,777 INFO sqlalchemy.engine.base.Engine ('2014-01-28 00:00:00.000000', 0.43, 70)
2018-05-08 18:31:15,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,779 INFO sqlalchemy.engine.base.Engine ('2014-01-29 00:00:00.000000', 0.51, 69)
2018-05-08 18:31:15,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,781 INFO sqlalchemy.engine.base.Engine ('2014-01-30 00:00:00.000000', 0.2, 66)
2018-05-08 18:31:15,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,782 INFO sqlalchemy.engine.base.Engine ('2014-01-31 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:15,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,784 INFO sqlalchemy.engine.base.Engine ('2014-02-01 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:15,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,786 INFO sqlalchemy.engine.base.Engine ('2014-02-02 00:00:00.000000', 0.27, 68)
2018-05-08 18:31:15,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,788 INFO sqlalchemy.engine.base.Engine ('2014-02-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,790 INFO sqlalchemy.engine.base.Engine ('2014-02-04 00:00:00.000000', 0.88, 67)
2018-05-08 18:31:15,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,791 INFO sqlalchemy.engine.base.Engine ('2014-02-05 00:00:00.000000', 0.39, 71)
2018-05-08 18:31:15,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,793 INFO sqlalchemy.engine.base.Engine ('2014-02-06 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:15,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,795 INFO sqlalchemy.engine.base.Engine ('2014-02-07 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:15,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,797 INFO sqlalchemy.engine.base.Engine ('2014-02-08 00:00:00.000000', 1.1, 68)
2018-05-08 18:31:15,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,798 INFO sqlalchemy.engine.base.Engine ('2014-02-09 00:00:00.000000', 0.36, 72)

2018-05-08 18:31:15,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,800 INFO sqlalchemy.engine.base.Engine ('2014-02-10 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,801 INFO sqlalchemy.engine.base.Engine ('2014-02-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,803 INFO sqlalchemy.engine.base.Engine ('2014-02-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,805 INFO sqlalchemy.engine.base.Engine ('2014-02-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,807 INFO sqlalchemy.engine.base.Engine ('2014-02-14 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:15,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,809 INFO sqlalchemy.engine.base.Engine ('2014-02-15 00:00:00.000000', 0.33, 73)
2018-05-08 18:31:15,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,812 INFO sqlalchemy.engine.base.Engine ('2014-02-16 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:15,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,814 INFO sqlalchemy.engine.base.Engine ('2014-02-17 00:00:00.000000', 0.29, 74)
2018-05-08 18:31:15,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,816 INFO sqlalchemy.engine.base.Engine ('2014-02-18 00:00:00.000000', 0.16, 72)
2018-05-08 18:31:15,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,819 INFO sqlalchemy.engine.base.Engine ('2014-02-19 00:00:00.000000', 0.81, 71)
2018-05-08 18:31:15,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,820 INFO sqlalchemy.engine.base.Engine ('2014-02-20 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,822 INFO sqlalchemy.engine.base.Engine ('2014-02-21 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:15,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,824 INFO sqlalchemy.engine.base.Engine ('2014-02-22 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:15,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,826 INFO sqlalchemy.engine.base.Engine ('2014-02-23 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:15,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,828 INFO sqlalchemy.engine.base.Engine ('2014-02-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,830 INFO sqlalchemy.engine.base.Engine ('2014-02-25 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:15,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,832 INFO sqlalchemy.engine.base.Engine ('2014-02-26 00:00:00.000000', 0.08, 66)
2018-05-08 18:31:15,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,833 INFO sqlalchemy.engine.base.Engine ('2014-02-27 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:15,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,835 INFO sqlalchemy.engine.base.Engine ('2014-02-28 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:15,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,837 INFO sqlalchemy.engine.base.Engine ('2014-03-01 00:00:00.000000', 0.16, 72)
2018-05-08 18:31:15,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,838 INFO sqlalchemy.engine.base.Engine ('2014-03-02 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:15,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,841 INFO sqlalchemy.engine.base.Engine ('2014-03-03 00:00:00.000000', 0.26, 66)
2018-05-08 18:31:15,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,843 INFO sqlalchemy.engine.base.Engine ('2014-03-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:15,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,845 INFO sqlalchemy.engine.base.Engine ('2014-03-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:15,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,846 INFO sqlalchemy.engine.base.Engine ('2014-03-06 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:15,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,848 INFO sqlalchemy.engine.base.Engine ('2014-03-07 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:15,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,850 INFO sqlalchemy.engine.base.Engine ('2014-03-08 00:00:00.000000', 0.94, 67)
2018-05-08 18:31:15,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,852 INFO sqlalchemy.engine.base.Engine ('2014-03-09 00:00:00.000000', 0.34, 72)
2018-05-08 18:31:15,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,853 INFO sqlalchemy.engine.base.Engine ('2014-03-10 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:15,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,856 INFO sqlalchemy.engine.base.Engine ('2014-03-11 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:15,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,859 INFO sqlalchemy.engine.base.Engine ('2014-03-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,862 INFO sqlalchemy.engine.base.Engine ('2014-03-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,864 INFO sqlalchemy.engine.base.Engine ('2014-03-14 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:15,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,865 INFO sqlalchemy.engine.base.Engine ('2014-03-15 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:15,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,867 INFO sqlalchemy.engine.base.Engine ('2014-03-16 00:00:00.000000', 0.01, 69)

2018-05-08 18:31:15,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,868 INFO sqlalchemy.engine.base.Engine ('2014-03-17 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:15,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,870 INFO sqlalchemy.engine.base.Engine ('2014-03-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,871 INFO sqlalchemy.engine.base.Engine ('2014-03-19 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:15,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,874 INFO sqlalchemy.engine.base.Engine ('2014-03-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,876 INFO sqlalchemy.engine.base.Engine ('2014-03-21 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:15,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,879 INFO sqlalchemy.engine.base.Engine ('2014-03-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,881 INFO sqlalchemy.engine.base.Engine ('2014-03-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,883 INFO sqlalchemy.engine.base.Engine ('2014-03-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,884 INFO sqlalchemy.engine.base.Engine ('2014-03-25 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:15,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,886 INFO sqlalchemy.engine.base.Engine ('2014-03-26 00:00:00.000000', 0.45, 74)
2018-05-08 18:31:15,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,887 INFO sqlalchemy.engine.base.Engine ('2014-03-27 00:00:00.000000', 0.4, 72)
2018-05-08 18:31:15,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,890 INFO sqlalchemy.engine.base.Engine ('2014-03-28 00:00:00.000000', 1.7, 69)
2018-05-08 18:31:15,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,892 INFO sqlalchemy.engine.base.Engine ('2014-03-29 00:00:00.000000', 1.6, 70)
2018-05-08 18:31:15,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,894 INFO sqlalchemy.engine.base.Engine ('2014-03-30 00:00:00.000000', 0.93, 73)
2018-05-08 18:31:15,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,895 INFO sqlalchemy.engine.base.Engine ('2014-03-31 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:15,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,898 INFO sqlalchemy.engine.base.Engine ('2014-04-01 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:15,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,900 INFO sqlalchemy.engine.base.Engine ('2014-04-02 00:00:00.000000', 0.2, 73)
2018-05-08 18:31:15,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,901 INFO sqlalchemy.engine.base.Engine ('2014-04-03 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:15,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,903 INFO sqlalchemy.engine.base.Engine ('2014-04-04 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:15,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,905 INFO sqlalchemy.engine.base.Engine ('2014-04-05 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:15,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,908 INFO sqlalchemy.engine.base.Engine ('2014-04-06 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:15,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,909 INFO sqlalchemy.engine.base.Engine ('2014-04-07 00:00:00.000000', 0.23, 70)
2018-05-08 18:31:15,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,911 INFO sqlalchemy.engine.base.Engine ('2014-04-08 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:15,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,913 INFO sqlalchemy.engine.base.Engine ('2014-04-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:15,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,915 INFO sqlalchemy.engine.base.Engine ('2014-04-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:15,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,916 INFO sqlalchemy.engine.base.Engine ('2014-04-11 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:15,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,918 INFO sqlalchemy.engine.base.Engine ('2014-04-12 00:00:00.000000', 0.39, 70)
2018-05-08 18:31:15,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,920 INFO sqlalchemy.engine.base.Engine ('2014-04-13 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,922 INFO sqlalchemy.engine.base.Engine ('2014-04-14 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:15,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,924 INFO sqlalchemy.engine.base.Engine ('2014-04-15 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:15,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,926 INFO sqlalchemy.engine.base.Engine ('2014-04-16 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:15,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,928 INFO sqlalchemy.engine.base.Engine ('2014-04-18 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:15,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,930 INFO sqlalchemy.engine.base.Engine ('2014-04-19 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:15,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,932 INFO sqlalchemy.engine.base.Engine ('2014-04-20 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:15,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,934 INFO sqlalchemy.engine.base.Engine ('2014-04-21 00:00:00.000000', 0.09, 69)

2018-05-08 18:31:15,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,935 INFO sqlalchemy.engine.base.Engine ('2014-04-22 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:15,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,937 INFO sqlalchemy.engine.base.Engine ('2014-04-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:15,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,939 INFO sqlalchemy.engine.base.Engine ('2014-04-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:15,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,941 INFO sqlalchemy.engine.base.Engine ('2014-04-25 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:15,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,943 INFO sqlalchemy.engine.base.Engine ('2014-04-26 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:15,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,944 INFO sqlalchemy.engine.base.Engine ('2014-04-27 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:15,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,946 INFO sqlalchemy.engine.base.Engine ('2014-04-28 00:00:00.000000', 0.32, 68)
2018-05-08 18:31:15,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,947 INFO sqlalchemy.engine.base.Engine ('2014-04-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:15,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,950 INFO sqlalchemy.engine.base.Engine ('2014-05-01 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:15,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,951 INFO sqlalchemy.engine.base.Engine ('2014-05-02 00:00:00.000000', 0.57, 69)
2018-05-08 18:31:15,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,953 INFO sqlalchemy.engine.base.Engine ('2014-05-03 00:00:00.000000', 0.3, 71)
2018-05-08 18:31:15,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:15,956 INFO sqlalchemy.engine.base.Engine ('2014-05-04 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:16,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,011 INFO sqlalchemy.engine.base.Engine ('2014-05-05 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:16,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,012 INFO sqlalchemy.engine.base.Engine ('2014-05-06 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:16,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,014 INFO sqlalchemy.engine.base.Engine ('2014-05-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,016 INFO sqlalchemy.engine.base.Engine ('2014-05-08 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:16,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,017 INFO sqlalchemy.engine.base.Engine ('2014-05-09 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:16,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,019 INFO sqlalchemy.engine.base.Engine ('2014-05-10 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:16,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,021 INFO sqlalchemy.engine.base.Engine ('2014-05-11 00:00:00.000000', 0.17, 76)
2018-05-08 18:31:16,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,023 INFO sqlalchemy.engine.base.Engine ('2014-05-12 00:00:00.000000', 0.48, 73)
2018-05-08 18:31:16,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,025 INFO sqlalchemy.engine.base.Engine ('2014-05-13 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:16,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,027 INFO sqlalchemy.engine.base.Engine ('2014-05-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,029 INFO sqlalchemy.engine.base.Engine ('2014-05-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,031 INFO sqlalchemy.engine.base.Engine ('2014-05-16 00:00:00.000000', 0.55, 70)
2018-05-08 18:31:16,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,033 INFO sqlalchemy.engine.base.Engine ('2014-05-17 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:16,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,035 INFO sqlalchemy.engine.base.Engine ('2014-05-18 00:00:00.000000', 0.2, 79)
2018-05-08 18:31:16,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,037 INFO sqlalchemy.engine.base.Engine ('2014-05-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,038 INFO sqlalchemy.engine.base.Engine ('2014-05-20 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:16,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,041 INFO sqlalchemy.engine.base.Engine ('2014-05-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,043 INFO sqlalchemy.engine.base.Engine ('2014-05-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,045 INFO sqlalchemy.engine.base.Engine ('2014-05-23 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:16,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,046 INFO sqlalchemy.engine.base.Engine ('2014-05-24 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:16,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,048 INFO sqlalchemy.engine.base.Engine ('2014-05-25 00:00:00.000000', 0.86, 75)
2018-05-08 18:31:16,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,049 INFO sqlalchemy.engine.base.Engine ('2014-05-26 00:00:00.000000', 0.28, 75)
2018-05-08 18:31:16,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,051 INFO sqlalchemy.engine.base.Engine ('2014-05-27 00:00:00.000000', 0.08, 74)

2018-05-08 18:31:16,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,053 INFO sqlalchemy.engine.base.Engine ('2014-05-28 00:00:00.000000', 0.14, 76)
2018-05-08 18:31:16,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,055 INFO sqlalchemy.engine.base.Engine ('2014-05-29 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:16,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,057 INFO sqlalchemy.engine.base.Engine ('2014-05-30 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:16,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,060 INFO sqlalchemy.engine.base.Engine ('2014-05-31 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:16,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,062 INFO sqlalchemy.engine.base.Engine ('2014-06-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,064 INFO sqlalchemy.engine.base.Engine ('2014-06-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,065 INFO sqlalchemy.engine.base.Engine ('2014-06-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,066 INFO sqlalchemy.engine.base.Engine ('2014-06-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,068 INFO sqlalchemy.engine.base.Engine ('2014-06-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,070 INFO sqlalchemy.engine.base.Engine ('2014-06-06 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:16,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,072 INFO sqlalchemy.engine.base.Engine ('2014-06-07 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:16,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,075 INFO sqlalchemy.engine.base.Engine ('2014-06-08 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:16,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,077 INFO sqlalchemy.engine.base.Engine ('2014-06-09 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:16,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,079 INFO sqlalchemy.engine.base.Engine ('2014-06-10 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:16,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,081 INFO sqlalchemy.engine.base.Engine ('2014-06-11 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:16,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,083 INFO sqlalchemy.engine.base.Engine ('2014-06-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,084 INFO sqlalchemy.engine.base.Engine ('2014-06-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,086 INFO sqlalchemy.engine.base.Engine ('2014-06-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,088 INFO sqlalchemy.engine.base.Engine ('2014-06-15 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:16,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,090 INFO sqlalchemy.engine.base.Engine ('2014-06-16 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:16,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,093 INFO sqlalchemy.engine.base.Engine ('2014-06-17 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:16,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,094 INFO sqlalchemy.engine.base.Engine ('2014-06-18 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:16,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,096 INFO sqlalchemy.engine.base.Engine ('2014-06-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,098 INFO sqlalchemy.engine.base.Engine ('2014-06-20 00:00:00.000000', 0.29, 70)
2018-05-08 18:31:16,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,100 INFO sqlalchemy.engine.base.Engine ('2014-06-21 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:16,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,102 INFO sqlalchemy.engine.base.Engine ('2014-06-22 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:16,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,103 INFO sqlalchemy.engine.base.Engine ('2014-06-23 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:16,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,105 INFO sqlalchemy.engine.base.Engine ('2014-06-24 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:16,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,107 INFO sqlalchemy.engine.base.Engine ('2014-06-25 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:16,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,109 INFO sqlalchemy.engine.base.Engine ('2014-06-26 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:16,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,111 INFO sqlalchemy.engine.base.Engine ('2014-06-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:16,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,115 INFO sqlalchemy.engine.base.Engine ('2014-06-28 00:00:00.000000', 0.25, 76)
2018-05-08 18:31:16,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,116 INFO sqlalchemy.engine.base.Engine ('2014-06-29 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:16,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,118 INFO sqlalchemy.engine.base.Engine ('2014-06-30 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:16,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,120 INFO sqlalchemy.engine.base.Engine ('2014-07-01 00:00:00.000000', 0.01, 75)

2018-05-08 18:31:16,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,121 INFO sqlalchemy.engine.base.Engine ('2014-07-02 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:16,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,124 INFO sqlalchemy.engine.base.Engine ('2014-07-03 00:00:00.000000', 0.19, 77)
2018-05-08 18:31:16,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,125 INFO sqlalchemy.engine.base.Engine ('2014-07-04 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:16,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,128 INFO sqlalchemy.engine.base.Engine ('2014-07-05 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:16,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,130 INFO sqlalchemy.engine.base.Engine ('2014-07-06 00:00:00.000000', 0.21, 76)
2018-05-08 18:31:16,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,132 INFO sqlalchemy.engine.base.Engine ('2014-07-07 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:16,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,133 INFO sqlalchemy.engine.base.Engine ('2014-07-08 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:16,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,136 INFO sqlalchemy.engine.base.Engine ('2014-07-09 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,137 INFO sqlalchemy.engine.base.Engine ('2014-07-10 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:16,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,139 INFO sqlalchemy.engine.base.Engine ('2014-07-11 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:16,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,142 INFO sqlalchemy.engine.base.Engine ('2014-07-12 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:16,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,145 INFO sqlalchemy.engine.base.Engine ('2014-07-13 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:16,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,146 INFO sqlalchemy.engine.base.Engine ('2014-07-14 00:00:00.000000', 0.19, 77)
2018-05-08 18:31:16,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,148 INFO sqlalchemy.engine.base.Engine ('2014-07-15 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:16,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,150 INFO sqlalchemy.engine.base.Engine ('2014-07-16 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:16,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,152 INFO sqlalchemy.engine.base.Engine ('2014-07-17 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:16,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,154 INFO sqlalchemy.engine.base.Engine ('2014-07-18 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:16,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,156 INFO sqlalchemy.engine.base.Engine ('2014-07-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,161 INFO sqlalchemy.engine.base.Engine ('2014-07-20 00:00:00.000000', 5.98, 72)
2018-05-08 18:31:16,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,163 INFO sqlalchemy.engine.base.Engine ('2014-07-21 00:00:00.000000', 0.05, 82)
2018-05-08 18:31:16,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,164 INFO sqlalchemy.engine.base.Engine ('2014-07-22 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:16,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,165 INFO sqlalchemy.engine.base.Engine ('2014-07-23 00:00:00.000000', 0.31, 76)
2018-05-08 18:31:16,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,167 INFO sqlalchemy.engine.base.Engine ('2014-07-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,169 INFO sqlalchemy.engine.base.Engine ('2014-07-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,171 INFO sqlalchemy.engine.base.Engine ('2014-07-26 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:16,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,172 INFO sqlalchemy.engine.base.Engine ('2014-07-27 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:16,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,174 INFO sqlalchemy.engine.base.Engine ('2014-07-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,177 INFO sqlalchemy.engine.base.Engine ('2014-07-29 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,179 INFO sqlalchemy.engine.base.Engine ('2014-07-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,181 INFO sqlalchemy.engine.base.Engine ('2014-07-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,183 INFO sqlalchemy.engine.base.Engine ('2014-08-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,184 INFO sqlalchemy.engine.base.Engine ('2014-08-02 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:16,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,187 INFO sqlalchemy.engine.base.Engine ('2014-08-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,188 INFO sqlalchemy.engine.base.Engine ('2014-08-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,191 INFO sqlalchemy.engine.base.Engine ('2014-08-05 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:16,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,193 INFO sqlalchemy.engine.base.Engine ('2014-08-06 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:16,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,195 INFO sqlalchemy.engine.base.Engine ('2014-08-07 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:16,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,197 INFO sqlalchemy.engine.base.Engine ('2014-08-08 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:16,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,198 INFO sqlalchemy.engine.base.Engine ('2014-08-09 00:00:00.000000', 0.31, 77)
2018-05-08 18:31:16,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,200 INFO sqlalchemy.engine.base.Engine ('2014-08-10 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:16,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,201 INFO sqlalchemy.engine.base.Engine ('2014-08-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,249 INFO sqlalchemy.engine.base.Engine ('2014-08-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,250 INFO sqlalchemy.engine.base.Engine ('2014-08-13 00:00:00.000000', 0.37, 74)
2018-05-08 18:31:16,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,252 INFO sqlalchemy.engine.base.Engine ('2014-08-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,254 INFO sqlalchemy.engine.base.Engine ('2014-08-15 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:16,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,256 INFO sqlalchemy.engine.base.Engine ('2014-08-16 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:16,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,258 INFO sqlalchemy.engine.base.Engine ('2014-08-17 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:16,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,260 INFO sqlalchemy.engine.base.Engine ('2014-08-18 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:16,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,262 INFO sqlalchemy.engine.base.Engine ('2014-08-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,264 INFO sqlalchemy.engine.base.Engine ('2014-08-20 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:16,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,266 INFO sqlalchemy.engine.base.Engine ('2014-08-21 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:16,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,268 INFO sqlalchemy.engine.base.Engine ('2014-08-22 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:16,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,270 INFO sqlalchemy.engine.base.Engine ('2014-08-23 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:16,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,272 INFO sqlalchemy.engine.base.Engine ('2014-08-24 00:00:00.000000', 0.19, 84)
2018-05-08 18:31:16,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,274 INFO sqlalchemy.engine.base.Engine ('2014-08-25 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:16,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,276 INFO sqlalchemy.engine.base.Engine ('2014-08-26 00:00:00.000000', 0.33, 72)
2018-05-08 18:31:16,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,278 INFO sqlalchemy.engine.base.Engine ('2014-08-27 00:00:00.000000', 0.47, 74)
2018-05-08 18:31:16,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,280 INFO sqlalchemy.engine.base.Engine ('2014-08-28 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,281 INFO sqlalchemy.engine.base.Engine ('2014-08-29 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:16,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,282 INFO sqlalchemy.engine.base.Engine ('2014-08-30 00:00:00.000000', 0.27, 84)
2018-05-08 18:31:16,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,284 INFO sqlalchemy.engine.base.Engine ('2014-08-31 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:16,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,286 INFO sqlalchemy.engine.base.Engine ('2014-09-01 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:16,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,287 INFO sqlalchemy.engine.base.Engine ('2014-09-02 00:00:00.000000', 1.37, 73)
2018-05-08 18:31:16,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,290 INFO sqlalchemy.engine.base.Engine ('2014-09-03 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:16,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,291 INFO sqlalchemy.engine.base.Engine ('2014-09-07 00:00:00.000000', 0.29, 76)
2018-05-08 18:31:16,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,293 INFO sqlalchemy.engine.base.Engine ('2014-09-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,295 INFO sqlalchemy.engine.base.Engine ('2014-09-09 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:16,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,297 INFO sqlalchemy.engine.base.Engine ('2014-09-10 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:16,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,299 INFO sqlalchemy.engine.base.Engine ('2014-09-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,301 INFO sqlalchemy.engine.base.Engine ('2014-09-12 00:00:00.000000', 0.01, 73)

2018-05-08 18:31:16,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,303 INFO sqlalchemy.engine.base.Engine ('2014-09-13 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:16,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,305 INFO sqlalchemy.engine.base.Engine ('2014-09-14 00:00:00.000000', 0.0, 85)
2018-05-08 18:31:16,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,307 INFO sqlalchemy.engine.base.Engine ('2014-09-15 00:00:00.000000', 0.36, 74)
2018-05-08 18:31:16,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,310 INFO sqlalchemy.engine.base.Engine ('2014-09-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,312 INFO sqlalchemy.engine.base.Engine ('2014-09-17 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:16,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,314 INFO sqlalchemy.engine.base.Engine ('2014-09-18 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:16,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,316 INFO sqlalchemy.engine.base.Engine ('2014-09-19 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:16,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,318 INFO sqlalchemy.engine.base.Engine ('2014-09-20 00:00:00.000000', 0.23, 76)
2018-05-08 18:31:16,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,320 INFO sqlalchemy.engine.base.Engine ('2014-09-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,322 INFO sqlalchemy.engine.base.Engine ('2014-09-22 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:16,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,324 INFO sqlalchemy.engine.base.Engine ('2014-09-23 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:16,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,326 INFO sqlalchemy.engine.base.Engine ('2014-09-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,327 INFO sqlalchemy.engine.base.Engine ('2014-09-25 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:16,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,329 INFO sqlalchemy.engine.base.Engine ('2014-09-26 00:00:00.000000', 0.3, 77)
2018-05-08 18:31:16,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,330 INFO sqlalchemy.engine.base.Engine ('2014-09-27 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:16,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,332 INFO sqlalchemy.engine.base.Engine ('2014-09-28 00:00:00.000000', 0.23, 74)
2018-05-08 18:31:16,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,334 INFO sqlalchemy.engine.base.Engine ('2014-09-29 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:16,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,335 INFO sqlalchemy.engine.base.Engine ('2014-09-30 00:00:00.000000', 0.31, 73)
2018-05-08 18:31:16,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,337 INFO sqlalchemy.engine.base.Engine ('2014-10-01 00:00:00.000000', 1.71, 73)
2018-05-08 18:31:16,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,338 INFO sqlalchemy.engine.base.Engine ('2014-10-02 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:16,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,340 INFO sqlalchemy.engine.base.Engine ('2014-10-03 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:16,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,341 INFO sqlalchemy.engine.base.Engine ('2014-10-04 00:00:00.000000', 0.33, 74)
2018-05-08 18:31:16,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,343 INFO sqlalchemy.engine.base.Engine ('2014-10-05 00:00:00.000000', 0.64, 74)
2018-05-08 18:31:16,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,346 INFO sqlalchemy.engine.base.Engine ('2014-10-06 00:00:00.000000', 0.26, 74)
2018-05-08 18:31:16,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,347 INFO sqlalchemy.engine.base.Engine ('2014-10-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,349 INFO sqlalchemy.engine.base.Engine ('2014-10-08 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:16,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,350 INFO sqlalchemy.engine.base.Engine ('2014-10-09 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:16,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,352 INFO sqlalchemy.engine.base.Engine ('2014-10-10 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:16,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,354 INFO sqlalchemy.engine.base.Engine ('2014-10-11 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:16,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,356 INFO sqlalchemy.engine.base.Engine ('2014-10-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,357 INFO sqlalchemy.engine.base.Engine ('2014-10-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,359 INFO sqlalchemy.engine.base.Engine ('2014-10-15 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:16,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,360 INFO sqlalchemy.engine.base.Engine ('2014-10-16 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:16,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,361 INFO sqlalchemy.engine.base.Engine ('2014-10-17 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:16,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,363 INFO sqlalchemy.engine.base.Engine ('2014-10-18 00:00:00.000000', 0.21, 80)

2018-05-08 18:31:16,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,365 INFO sqlalchemy.engine.base.Engine ('2014-10-19 00:00:00.000000', 2.06, 74)
2018-05-08 18:31:16,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,367 INFO sqlalchemy.engine.base.Engine ('2014-10-20 00:00:00.000000', 1.84, 76)
2018-05-08 18:31:16,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,368 INFO sqlalchemy.engine.base.Engine ('2014-10-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,370 INFO sqlalchemy.engine.base.Engine ('2014-10-22 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:16,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,371 INFO sqlalchemy.engine.base.Engine ('2014-10-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,372 INFO sqlalchemy.engine.base.Engine ('2014-10-24 00:00:00.000000', 0.41, 74)
2018-05-08 18:31:16,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,374 INFO sqlalchemy.engine.base.Engine ('2014-10-25 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:16,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,375 INFO sqlalchemy.engine.base.Engine ('2014-10-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,377 INFO sqlalchemy.engine.base.Engine ('2014-10-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,378 INFO sqlalchemy.engine.base.Engine ('2014-10-28 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:16,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,379 INFO sqlalchemy.engine.base.Engine ('2014-10-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,381 INFO sqlalchemy.engine.base.Engine ('2014-10-30 00:00:00.000000', 0.22, 76)
2018-05-08 18:31:16,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,382 INFO sqlalchemy.engine.base.Engine ('2014-10-31 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:16,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,385 INFO sqlalchemy.engine.base.Engine ('2014-11-01 00:00:00.000000', 0.11, 77)
2018-05-08 18:31:16,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,388 INFO sqlalchemy.engine.base.Engine ('2014-11-02 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:16,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,390 INFO sqlalchemy.engine.base.Engine ('2014-11-03 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:16,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,391 INFO sqlalchemy.engine.base.Engine ('2014-11-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,393 INFO sqlalchemy.engine.base.Engine ('2014-11-05 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:16,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,395 INFO sqlalchemy.engine.base.Engine ('2014-11-06 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:16,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,396 INFO sqlalchemy.engine.base.Engine ('2014-11-07 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:16,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,397 INFO sqlalchemy.engine.base.Engine ('2014-11-08 00:00:00.000000', 0.46, 74)
2018-05-08 18:31:16,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,398 INFO sqlalchemy.engine.base.Engine ('2014-11-09 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,400 INFO sqlalchemy.engine.base.Engine ('2014-11-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,401 INFO sqlalchemy.engine.base.Engine ('2014-11-11 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,403 INFO sqlalchemy.engine.base.Engine ('2014-11-12 00:00:00.000000', 0.41, 70)
2018-05-08 18:31:16,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,405 INFO sqlalchemy.engine.base.Engine ('2014-11-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,406 INFO sqlalchemy.engine.base.Engine ('2014-11-14 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:16,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,408 INFO sqlalchemy.engine.base.Engine ('2014-11-15 00:00:00.000000', 1.03, 71)
2018-05-08 18:31:16,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,411 INFO sqlalchemy.engine.base.Engine ('2014-11-16 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:16,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,413 INFO sqlalchemy.engine.base.Engine ('2014-11-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,415 INFO sqlalchemy.engine.base.Engine ('2014-11-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,417 INFO sqlalchemy.engine.base.Engine ('2014-11-19 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:16,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,419 INFO sqlalchemy.engine.base.Engine ('2014-11-20 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:16,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,422 INFO sqlalchemy.engine.base.Engine ('2014-11-21 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:16,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,424 INFO sqlalchemy.engine.base.Engine ('2014-11-22 00:00:00.000000', 0.0, 76)

2018-05-08 18:31:16,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,426 INFO sqlalchemy.engine.base.Engine ('2014-11-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,474 INFO sqlalchemy.engine.base.Engine ('2014-11-24 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:16,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,476 INFO sqlalchemy.engine.base.Engine ('2014-11-25 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:16,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,478 INFO sqlalchemy.engine.base.Engine ('2014-11-26 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,480 INFO sqlalchemy.engine.base.Engine ('2014-11-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,483 INFO sqlalchemy.engine.base.Engine ('2014-11-28 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,485 INFO sqlalchemy.engine.base.Engine ('2014-11-29 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:16,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,486 INFO sqlalchemy.engine.base.Engine ('2014-11-30 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:16,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,488 INFO sqlalchemy.engine.base.Engine ('2014-12-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,491 INFO sqlalchemy.engine.base.Engine ('2014-12-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,493 INFO sqlalchemy.engine.base.Engine ('2014-12-03 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:16,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,495 INFO sqlalchemy.engine.base.Engine ('2014-12-04 00:00:00.000000', 1.35, 67)
2018-05-08 18:31:16,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,497 INFO sqlalchemy.engine.base.Engine ('2014-12-05 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:16,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,498 INFO sqlalchemy.engine.base.Engine ('2014-12-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,500 INFO sqlalchemy.engine.base.Engine ('2014-12-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,501 INFO sqlalchemy.engine.base.Engine ('2014-12-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,503 INFO sqlalchemy.engine.base.Engine ('2014-12-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,505 INFO sqlalchemy.engine.base.Engine ('2014-12-10 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,507 INFO sqlalchemy.engine.base.Engine ('2014-12-11 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:16,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,508 INFO sqlalchemy.engine.base.Engine ('2014-12-12 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:16,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,510 INFO sqlalchemy.engine.base.Engine ('2014-12-13 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:16,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,512 INFO sqlalchemy.engine.base.Engine ('2014-12-14 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:16,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,514 INFO sqlalchemy.engine.base.Engine ('2014-12-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,516 INFO sqlalchemy.engine.base.Engine ('2014-12-16 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:16,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,518 INFO sqlalchemy.engine.base.Engine ('2014-12-17 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:16,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,520 INFO sqlalchemy.engine.base.Engine ('2014-12-18 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:16,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,523 INFO sqlalchemy.engine.base.Engine ('2014-12-19 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:16,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,525 INFO sqlalchemy.engine.base.Engine ('2014-12-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,527 INFO sqlalchemy.engine.base.Engine ('2014-12-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,529 INFO sqlalchemy.engine.base.Engine ('2014-12-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,531 INFO sqlalchemy.engine.base.Engine ('2014-12-23 00:00:00.000000', 1.1, 70)
2018-05-08 18:31:16,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,532 INFO sqlalchemy.engine.base.Engine ('2014-12-24 00:00:00.000000', 1.24, 68)
2018-05-08 18:31:16,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,533 INFO sqlalchemy.engine.base.Engine ('2014-12-25 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:16,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,535 INFO sqlalchemy.engine.base.Engine ('2014-12-26 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:16,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,537 INFO sqlalchemy.engine.base.Engine ('2014-12-27 00:00:00.000000', 0.0, 65)

2018-05-08 18:31:16,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,538 INFO sqlalchemy.engine.base.Engine ('2014-12-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,540 INFO sqlalchemy.engine.base.Engine ('2014-12-29 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,542 INFO sqlalchemy.engine.base.Engine ('2014-12-30 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:16,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,544 INFO sqlalchemy.engine.base.Engine ('2014-12-31 00:00:00.000000', 0.72, 64)
2018-05-08 18:31:16,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,546 INFO sqlalchemy.engine.base.Engine ('2015-01-01 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:16,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,547 INFO sqlalchemy.engine.base.Engine ('2015-01-02 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:16,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,549 INFO sqlalchemy.engine.base.Engine ('2015-01-03 00:00:00.000000', 1.46, 63)
2018-05-08 18:31:16,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,551 INFO sqlalchemy.engine.base.Engine ('2015-01-04 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:16,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,552 INFO sqlalchemy.engine.base.Engine ('2015-01-05 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:16,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,554 INFO sqlalchemy.engine.base.Engine ('2015-01-06 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:16,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,556 INFO sqlalchemy.engine.base.Engine ('2015-01-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,559 INFO sqlalchemy.engine.base.Engine ('2015-01-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,561 INFO sqlalchemy.engine.base.Engine ('2015-01-09 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,563 INFO sqlalchemy.engine.base.Engine ('2015-01-10 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:16,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,565 INFO sqlalchemy.engine.base.Engine ('2015-01-11 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:16,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,567 INFO sqlalchemy.engine.base.Engine ('2015-01-12 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:16,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,569 INFO sqlalchemy.engine.base.Engine ('2015-01-13 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:16,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,571 INFO sqlalchemy.engine.base.Engine ('2015-01-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,575 INFO sqlalchemy.engine.base.Engine ('2015-01-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,577 INFO sqlalchemy.engine.base.Engine ('2015-01-16 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:16,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,579 INFO sqlalchemy.engine.base.Engine ('2015-01-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,581 INFO sqlalchemy.engine.base.Engine ('2015-01-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,583 INFO sqlalchemy.engine.base.Engine ('2015-01-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,585 INFO sqlalchemy.engine.base.Engine ('2015-01-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,587 INFO sqlalchemy.engine.base.Engine ('2015-01-21 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,591 INFO sqlalchemy.engine.base.Engine ('2015-01-22 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,594 INFO sqlalchemy.engine.base.Engine ('2015-01-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,596 INFO sqlalchemy.engine.base.Engine ('2015-01-24 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:16,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,598 INFO sqlalchemy.engine.base.Engine ('2015-01-25 00:00:00.000000', 0.46, 67)
2018-05-08 18:31:16,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,600 INFO sqlalchemy.engine.base.Engine ('2015-01-26 00:00:00.000000', 0.73, 70)
2018-05-08 18:31:16,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,602 INFO sqlalchemy.engine.base.Engine ('2015-01-27 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:16,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,604 INFO sqlalchemy.engine.base.Engine ('2015-01-28 00:00:00.000000', 0.09, 68)
2018-05-08 18:31:16,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,606 INFO sqlalchemy.engine.base.Engine ('2015-01-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,608 INFO sqlalchemy.engine.base.Engine ('2015-01-30 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:16,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,610 INFO sqlalchemy.engine.base.Engine ('2015-01-31 00:00:00.000000', 0.0, 66)

2018-05-08 18:31:16,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,612 INFO sqlalchemy.engine.base.Engine ('2015-02-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:16,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,615 INFO sqlalchemy.engine.base.Engine ('2015-02-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,616 INFO sqlalchemy.engine.base.Engine ('2015-02-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:16,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,618 INFO sqlalchemy.engine.base.Engine ('2015-02-04 00:00:00.000000', 0.77, 74)
2018-05-08 18:31:16,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,620 INFO sqlalchemy.engine.base.Engine ('2015-02-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,623 INFO sqlalchemy.engine.base.Engine ('2015-02-06 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,625 INFO sqlalchemy.engine.base.Engine ('2015-02-07 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:16,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,627 INFO sqlalchemy.engine.base.Engine ('2015-02-08 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:16,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,629 INFO sqlalchemy.engine.base.Engine ('2015-02-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,630 INFO sqlalchemy.engine.base.Engine ('2015-02-10 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:16,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,632 INFO sqlalchemy.engine.base.Engine ('2015-02-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,634 INFO sqlalchemy.engine.base.Engine ('2015-02-12 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:16,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,636 INFO sqlalchemy.engine.base.Engine ('2015-02-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,639 INFO sqlalchemy.engine.base.Engine ('2015-02-14 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:16,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,641 INFO sqlalchemy.engine.base.Engine ('2015-02-15 00:00:00.000000', 0.8, 61)
2018-05-08 18:31:16,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,644 INFO sqlalchemy.engine.base.Engine ('2015-02-16 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:16,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,646 INFO sqlalchemy.engine.base.Engine ('2015-02-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,647 INFO sqlalchemy.engine.base.Engine ('2015-02-18 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,649 INFO sqlalchemy.engine.base.Engine ('2015-02-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,650 INFO sqlalchemy.engine.base.Engine ('2015-02-20 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:16,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,652 INFO sqlalchemy.engine.base.Engine ('2015-02-21 00:00:00.000000', 0.76, 69)
2018-05-08 18:31:16,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,654 INFO sqlalchemy.engine.base.Engine ('2015-02-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,657 INFO sqlalchemy.engine.base.Engine ('2015-02-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,659 INFO sqlalchemy.engine.base.Engine ('2015-02-24 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,661 INFO sqlalchemy.engine.base.Engine ('2015-02-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,662 INFO sqlalchemy.engine.base.Engine ('2015-02-26 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:16,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,664 INFO sqlalchemy.engine.base.Engine ('2015-02-27 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:16,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,666 INFO sqlalchemy.engine.base.Engine ('2015-02-28 00:00:00.000000', 0.25, 69)
2018-05-08 18:31:16,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,669 INFO sqlalchemy.engine.base.Engine ('2015-03-01 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:16,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,671 INFO sqlalchemy.engine.base.Engine ('2015-03-02 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:16,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,673 INFO sqlalchemy.engine.base.Engine ('2015-03-03 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:16,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,728 INFO sqlalchemy.engine.base.Engine ('2015-03-04 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:16,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,729 INFO sqlalchemy.engine.base.Engine ('2015-03-05 00:00:00.000000', 0.52, 69)
2018-05-08 18:31:16,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,731 INFO sqlalchemy.engine.base.Engine ('2015-03-06 00:00:00.000000', 0.06, 68)
2018-05-08 18:31:16,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,732 INFO sqlalchemy.engine.base.Engine ('2015-03-07 00:00:00.000000', 0.0, 68)

2018-05-08 18:31:16,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,734 INFO sqlalchemy.engine.base.Engine ('2015-03-08 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:16,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,735 INFO sqlalchemy.engine.base.Engine ('2015-03-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:16,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,737 INFO sqlalchemy.engine.base.Engine ('2015-03-10 00:00:00.000000', 0.03, 63)
2018-05-08 18:31:16,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,739 INFO sqlalchemy.engine.base.Engine ('2015-03-11 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:16,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,741 INFO sqlalchemy.engine.base.Engine ('2015-03-12 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:16,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,743 INFO sqlalchemy.engine.base.Engine ('2015-03-13 00:00:00.000000', 0.02, 62)
2018-05-08 18:31:16,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,745 INFO sqlalchemy.engine.base.Engine ('2015-03-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,747 INFO sqlalchemy.engine.base.Engine ('2015-03-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:16,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,748 INFO sqlalchemy.engine.base.Engine ('2015-03-16 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:16,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,750 INFO sqlalchemy.engine.base.Engine ('2015-03-17 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:16,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,752 INFO sqlalchemy.engine.base.Engine ('2015-03-18 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:16,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,753 INFO sqlalchemy.engine.base.Engine ('2015-03-19 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:16,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,755 INFO sqlalchemy.engine.base.Engine ('2015-03-20 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:16,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,757 INFO sqlalchemy.engine.base.Engine ('2015-03-21 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:16,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,759 INFO sqlalchemy.engine.base.Engine ('2015-03-22 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:16,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,760 INFO sqlalchemy.engine.base.Engine ('2015-03-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,763 INFO sqlalchemy.engine.base.Engine ('2015-03-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,765 INFO sqlalchemy.engine.base.Engine ('2015-03-25 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:16,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,767 INFO sqlalchemy.engine.base.Engine ('2015-03-26 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:16,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,769 INFO sqlalchemy.engine.base.Engine ('2015-03-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,771 INFO sqlalchemy.engine.base.Engine ('2015-03-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,774 INFO sqlalchemy.engine.base.Engine ('2015-03-29 00:00:00.000000', 0.38, 73)
2018-05-08 18:31:16,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,775 INFO sqlalchemy.engine.base.Engine ('2015-03-30 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:16,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,777 INFO sqlalchemy.engine.base.Engine ('2015-03-31 00:00:00.000000', 0.6, 70)
2018-05-08 18:31:16,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,779 INFO sqlalchemy.engine.base.Engine ('2015-04-01 00:00:00.000000', 0.24, 73)
2018-05-08 18:31:16,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,781 INFO sqlalchemy.engine.base.Engine ('2015-04-02 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,782 INFO sqlalchemy.engine.base.Engine ('2015-04-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,784 INFO sqlalchemy.engine.base.Engine ('2015-04-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,786 INFO sqlalchemy.engine.base.Engine ('2015-04-05 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:16,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,787 INFO sqlalchemy.engine.base.Engine ('2015-04-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,789 INFO sqlalchemy.engine.base.Engine ('2015-04-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,791 INFO sqlalchemy.engine.base.Engine ('2015-04-08 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:16,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,793 INFO sqlalchemy.engine.base.Engine ('2015-04-09 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:16,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,795 INFO sqlalchemy.engine.base.Engine ('2015-04-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,798 INFO sqlalchemy.engine.base.Engine ('2015-04-11 00:00:00.000000', 0.0, 74)

2018-05-08 18:31:16,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,799 INFO sqlalchemy.engine.base.Engine ('2015-04-12 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:16,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,801 INFO sqlalchemy.engine.base.Engine ('2015-04-13 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:16,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,803 INFO sqlalchemy.engine.base.Engine ('2015-04-14 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,804 INFO sqlalchemy.engine.base.Engine ('2015-04-15 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:16,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,807 INFO sqlalchemy.engine.base.Engine ('2015-04-16 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:16,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,809 INFO sqlalchemy.engine.base.Engine ('2015-04-17 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,811 INFO sqlalchemy.engine.base.Engine ('2015-04-18 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:16,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,812 INFO sqlalchemy.engine.base.Engine ('2015-04-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,814 INFO sqlalchemy.engine.base.Engine ('2015-04-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,816 INFO sqlalchemy.engine.base.Engine ('2015-04-21 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:16,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,818 INFO sqlalchemy.engine.base.Engine ('2015-04-22 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:16,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,819 INFO sqlalchemy.engine.base.Engine ('2015-04-23 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:16,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,821 INFO sqlalchemy.engine.base.Engine ('2015-04-24 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:16,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,825 INFO sqlalchemy.engine.base.Engine ('2015-04-25 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:16,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,828 INFO sqlalchemy.engine.base.Engine ('2015-04-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,830 INFO sqlalchemy.engine.base.Engine ('2015-04-27 00:00:00.000000', 0.17, 73)
2018-05-08 18:31:16,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,831 INFO sqlalchemy.engine.base.Engine ('2015-04-28 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:16,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,833 INFO sqlalchemy.engine.base.Engine ('2015-04-29 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:16,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,834 INFO sqlalchemy.engine.base.Engine ('2015-04-30 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:16,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,836 INFO sqlalchemy.engine.base.Engine ('2015-05-01 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:16,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,838 INFO sqlalchemy.engine.base.Engine ('2015-05-02 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,840 INFO sqlalchemy.engine.base.Engine ('2015-05-05 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:16,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,842 INFO sqlalchemy.engine.base.Engine ('2015-05-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:16,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,844 INFO sqlalchemy.engine.base.Engine ('2015-05-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:16,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,846 INFO sqlalchemy.engine.base.Engine ('2015-05-08 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:16,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,848 INFO sqlalchemy.engine.base.Engine ('2015-05-09 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:16,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,849 INFO sqlalchemy.engine.base.Engine ('2015-05-10 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:16,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,851 INFO sqlalchemy.engine.base.Engine ('2015-05-11 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:16,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,853 INFO sqlalchemy.engine.base.Engine ('2015-05-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:16,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,855 INFO sqlalchemy.engine.base.Engine ('2015-05-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,857 INFO sqlalchemy.engine.base.Engine ('2015-05-14 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:16,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,859 INFO sqlalchemy.engine.base.Engine ('2015-05-15 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:16,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,862 INFO sqlalchemy.engine.base.Engine ('2015-05-16 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:16,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,864 INFO sqlalchemy.engine.base.Engine ('2015-05-17 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:16,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,866 INFO sqlalchemy.engine.base.Engine ('2015-05-18 00:00:00.000000', 0.27, 73)

2018-05-08 18:31:16,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,868 INFO sqlalchemy.engine.base.Engine ('2015-05-19 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:16,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,870 INFO sqlalchemy.engine.base.Engine ('2015-05-20 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:16,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,872 INFO sqlalchemy.engine.base.Engine ('2015-05-21 00:00:00.000000', 0.06, 68)
2018-05-08 18:31:16,874 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,874 INFO sqlalchemy.engine.base.Engine ('2015-05-22 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:16,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,876 INFO sqlalchemy.engine.base.Engine ('2015-05-23 00:00:00.000000', 0.8, 68)
2018-05-08 18:31:16,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,878 INFO sqlalchemy.engine.base.Engine ('2015-05-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:16,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,880 INFO sqlalchemy.engine.base.Engine ('2015-05-25 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:16,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,881 INFO sqlalchemy.engine.base.Engine ('2015-05-26 00:00:00.000000', 0.08, 67)
2018-05-08 18:31:16,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,883 INFO sqlalchemy.engine.base.Engine ('2015-05-27 00:00:00.000000', 0.07, 67)
2018-05-08 18:31:16,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,885 INFO sqlalchemy.engine.base.Engine ('2015-05-28 00:00:00.000000', 1.29, 68)
2018-05-08 18:31:16,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,886 INFO sqlalchemy.engine.base.Engine ('2015-05-29 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:16,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,888 INFO sqlalchemy.engine.base.Engine ('2015-05-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,890 INFO sqlalchemy.engine.base.Engine ('2015-05-31 00:00:00.000000', 0.34, 74)
2018-05-08 18:31:16,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,892 INFO sqlalchemy.engine.base.Engine ('2015-06-04 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:16,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,894 INFO sqlalchemy.engine.base.Engine ('2015-06-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:16,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,896 INFO sqlalchemy.engine.base.Engine ('2015-06-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,897 INFO sqlalchemy.engine.base.Engine ('2015-06-07 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:16,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,899 INFO sqlalchemy.engine.base.Engine ('2015-06-08 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:16,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,900 INFO sqlalchemy.engine.base.Engine ('2015-06-09 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:16,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,902 INFO sqlalchemy.engine.base.Engine ('2015-06-10 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:16,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,903 INFO sqlalchemy.engine.base.Engine ('2015-06-11 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:16,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,905 INFO sqlalchemy.engine.base.Engine ('2015-06-12 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:16,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,910 INFO sqlalchemy.engine.base.Engine ('2015-06-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:16,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,912 INFO sqlalchemy.engine.base.Engine ('2015-06-14 00:00:00.000000', 0.07, 79)
2018-05-08 18:31:16,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,914 INFO sqlalchemy.engine.base.Engine ('2015-06-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:16,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,916 INFO sqlalchemy.engine.base.Engine ('2015-06-16 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:16,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,965 INFO sqlalchemy.engine.base.Engine ('2015-06-17 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:16,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,967 INFO sqlalchemy.engine.base.Engine ('2015-06-18 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:16,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,969 INFO sqlalchemy.engine.base.Engine ('2015-06-19 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:16,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,971 INFO sqlalchemy.engine.base.Engine ('2015-06-20 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:16,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,974 INFO sqlalchemy.engine.base.Engine ('2015-06-21 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:16,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,976 INFO sqlalchemy.engine.base.Engine ('2015-06-22 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:16,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,977 INFO sqlalchemy.engine.base.Engine ('2015-06-23 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:16,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,979 INFO sqlalchemy.engine.base.Engine ('2015-06-24 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:16,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,980 INFO sqlalchemy.engine.base.Engine ('2015-06-25 00:00:00.000000', 0.2, 75)

2018-05-08 18:31:16,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,982 INFO sqlalchemy.engine.base.Engine ('2015-06-26 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:16,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,984 INFO sqlalchemy.engine.base.Engine ('2015-06-27 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:16,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,985 INFO sqlalchemy.engine.base.Engine ('2015-07-06 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:16,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,987 INFO sqlalchemy.engine.base.Engine ('2015-07-09 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:16,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,989 INFO sqlalchemy.engine.base.Engine ('2015-07-10 00:00:00.000000', 0.29, 77)
2018-05-08 18:31:16,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,991 INFO sqlalchemy.engine.base.Engine ('2015-07-11 00:00:00.000000', 0.33, 78)
2018-05-08 18:31:16,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,993 INFO sqlalchemy.engine.base.Engine ('2015-07-12 00:00:00.000000', 0.3, 77)
2018-05-08 18:31:16,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,995 INFO sqlalchemy.engine.base.Engine ('2015-07-13 00:00:00.000000', 0.2, 79)
2018-05-08 18:31:16,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,996 INFO sqlalchemy.engine.base.Engine ('2015-07-18 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:16,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:16,999 INFO sqlalchemy.engine.base.Engine ('2015-07-19 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:17,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,001 INFO sqlalchemy.engine.base.Engine ('2015-07-20 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:17,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,002 INFO sqlalchemy.engine.base.Engine ('2015-08-01 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:17,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,004 INFO sqlalchemy.engine.base.Engine ('2015-08-02 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:17,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,007 INFO sqlalchemy.engine.base.Engine ('2015-08-03 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:17,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,009 INFO sqlalchemy.engine.base.Engine ('2015-08-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,011 INFO sqlalchemy.engine.base.Engine ('2015-08-05 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:17,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,012 INFO sqlalchemy.engine.base.Engine ('2015-08-06 00:00:00.000000', 0.27, 77)
2018-05-08 18:31:17,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,014 INFO sqlalchemy.engine.base.Engine ('2015-08-07 00:00:00.000000', 0.3, 77)
2018-05-08 18:31:17,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,016 INFO sqlalchemy.engine.base.Engine ('2015-08-08 00:00:00.000000', 0.27, 76)
2018-05-08 18:31:17,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,017 INFO sqlalchemy.engine.base.Engine ('2015-08-10 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:17,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,019 INFO sqlalchemy.engine.base.Engine ('2015-08-11 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:17,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,021 INFO sqlalchemy.engine.base.Engine ('2015-08-12 00:00:00.000000', 0.09, 79)
2018-05-08 18:31:17,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,023 INFO sqlalchemy.engine.base.Engine ('2015-08-13 00:00:00.000000', 0.19, 77)
2018-05-08 18:31:17,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,024 INFO sqlalchemy.engine.base.Engine ('2015-08-14 00:00:00.000000', 0.21, 78)
2018-05-08 18:31:17,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,026 INFO sqlalchemy.engine.base.Engine ('2015-08-15 00:00:00.000000', 0.02, 83)
2018-05-08 18:31:17,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,029 INFO sqlalchemy.engine.base.Engine ('2015-08-17 00:00:00.000000', 0.51, 74)
2018-05-08 18:31:17,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,030 INFO sqlalchemy.engine.base.Engine ('2015-08-18 00:00:00.000000', 0.24, 74)
2018-05-08 18:31:17,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,032 INFO sqlalchemy.engine.base.Engine ('2015-08-19 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:17,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,034 INFO sqlalchemy.engine.base.Engine ('2015-08-20 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:17,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,036 INFO sqlalchemy.engine.base.Engine ('2015-08-21 00:00:00.000000', 0.05, 83)
2018-05-08 18:31:17,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,038 INFO sqlalchemy.engine.base.Engine ('2015-08-22 00:00:00.000000', 0.65, 77)
2018-05-08 18:31:17,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,040 INFO sqlalchemy.engine.base.Engine ('2015-08-23 00:00:00.000000', 0.33, 73)
2018-05-08 18:31:17,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,042 INFO sqlalchemy.engine.base.Engine ('2015-08-24 00:00:00.000000', 0.23, 76)
2018-05-08 18:31:17,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,045 INFO sqlalchemy.engine.base.Engine ('2015-08-25 00:00:00.000000', 0.52, 76)
2018-05-08 18:31:17,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,046 INFO sqlalchemy.engine.base.Engine ('2015-08-26 00:00:00.000000', 1.03, 76)

2018-05-08 18:31:17,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,048 INFO sqlalchemy.engine.base.Engine ('2015-08-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,050 INFO sqlalchemy.engine.base.Engine ('2015-08-28 00:00:00.000000', 0.0, 85)
2018-05-08 18:31:17,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,051 INFO sqlalchemy.engine.base.Engine ('2015-08-29 00:00:00.000000', 0.25, 81)
2018-05-08 18:31:17,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,053 INFO sqlalchemy.engine.base.Engine ('2015-08-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,054 INFO sqlalchemy.engine.base.Engine ('2015-09-01 00:00:00.000000', 0.32, 78)
2018-05-08 18:31:17,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,056 INFO sqlalchemy.engine.base.Engine ('2015-09-02 00:00:00.000000', 0.28, 79)
2018-05-08 18:31:17,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,058 INFO sqlalchemy.engine.base.Engine ('2015-09-03 00:00:00.000000', 1.55, 79)
2018-05-08 18:31:17,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,060 INFO sqlalchemy.engine.base.Engine ('2015-09-04 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:17,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,062 INFO sqlalchemy.engine.base.Engine ('2015-09-05 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:17,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,064 INFO sqlalchemy.engine.base.Engine ('2015-09-06 00:00:00.000000', 0.71, 76)
2018-05-08 18:31:17,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,065 INFO sqlalchemy.engine.base.Engine ('2015-09-07 00:00:00.000000', 0.19, 77)
2018-05-08 18:31:17,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,068 INFO sqlalchemy.engine.base.Engine ('2015-09-10 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:17,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,069 INFO sqlalchemy.engine.base.Engine ('2015-09-11 00:00:00.000000', 0.09, 78)
2018-05-08 18:31:17,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,071 INFO sqlalchemy.engine.base.Engine ('2015-09-12 00:00:00.000000', 2.7, 80)
2018-05-08 18:31:17,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,073 INFO sqlalchemy.engine.base.Engine ('2015-09-13 00:00:00.000000', 0.16, 80)
2018-05-08 18:31:17,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,076 INFO sqlalchemy.engine.base.Engine ('2015-09-14 00:00:00.000000', 0.63, 78)
2018-05-08 18:31:17,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,078 INFO sqlalchemy.engine.base.Engine ('2015-09-15 00:00:00.000000', 0.56, 76)
2018-05-08 18:31:17,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,081 INFO sqlalchemy.engine.base.Engine ('2015-09-16 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:17,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,083 INFO sqlalchemy.engine.base.Engine ('2015-09-17 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:17,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,085 INFO sqlalchemy.engine.base.Engine ('2015-09-18 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:17,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,087 INFO sqlalchemy.engine.base.Engine ('2015-09-19 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:17,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,090 INFO sqlalchemy.engine.base.Engine ('2015-09-20 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:17,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,092 INFO sqlalchemy.engine.base.Engine ('2015-09-21 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:17,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,094 INFO sqlalchemy.engine.base.Engine ('2015-09-22 00:00:00.000000', 0.32, 80)
2018-05-08 18:31:17,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,096 INFO sqlalchemy.engine.base.Engine ('2015-09-23 00:00:00.000000', 0.3, 78)
2018-05-08 18:31:17,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,097 INFO sqlalchemy.engine.base.Engine ('2015-09-24 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:17,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,099 INFO sqlalchemy.engine.base.Engine ('2015-09-25 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,101 INFO sqlalchemy.engine.base.Engine ('2015-09-26 00:00:00.000000', 0.36, 79)
2018-05-08 18:31:17,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,102 INFO sqlalchemy.engine.base.Engine ('2015-09-27 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:17,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,104 INFO sqlalchemy.engine.base.Engine ('2015-09-28 00:00:00.000000', 0.17, 77)
2018-05-08 18:31:17,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,106 INFO sqlalchemy.engine.base.Engine ('2015-09-29 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:17,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,108 INFO sqlalchemy.engine.base.Engine ('2015-09-30 00:00:00.000000', 0.17, 80)
2018-05-08 18:31:17,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,110 INFO sqlalchemy.engine.base.Engine ('2015-10-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,112 INFO sqlalchemy.engine.base.Engine ('2015-10-02 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:17,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,114 INFO sqlalchemy.engine.base.Engine ('2015-10-03 00:00:00.000000', 0.0, 75)

2018-05-08 18:31:17,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,116 INFO sqlalchemy.engine.base.Engine ('2015-10-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,118 INFO sqlalchemy.engine.base.Engine ('2015-10-05 00:00:00.000000', 0.4, 76)
2018-05-08 18:31:17,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,119 INFO sqlalchemy.engine.base.Engine ('2015-10-06 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:17,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,121 INFO sqlalchemy.engine.base.Engine ('2015-10-07 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:17,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,123 INFO sqlalchemy.engine.base.Engine ('2015-10-08 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:17,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,125 INFO sqlalchemy.engine.base.Engine ('2015-10-09 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:17,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,126 INFO sqlalchemy.engine.base.Engine ('2015-10-10 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:17,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,128 INFO sqlalchemy.engine.base.Engine ('2015-10-11 00:00:00.000000', 0.09, 81)
2018-05-08 18:31:17,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,129 INFO sqlalchemy.engine.base.Engine ('2015-10-12 00:00:00.000000', 1.0, 77)
2018-05-08 18:31:17,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,131 INFO sqlalchemy.engine.base.Engine ('2015-10-13 00:00:00.000000', 1.7, 75)
2018-05-08 18:31:17,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,132 INFO sqlalchemy.engine.base.Engine ('2015-10-14 00:00:00.000000', 1.21, 75)
2018-05-08 18:31:17,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,135 INFO sqlalchemy.engine.base.Engine ('2015-10-15 00:00:00.000000', 0.81, 74)
2018-05-08 18:31:17,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,136 INFO sqlalchemy.engine.base.Engine ('2015-10-16 00:00:00.000000', 0.73, 73)
2018-05-08 18:31:17,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,138 INFO sqlalchemy.engine.base.Engine ('2015-10-17 00:00:00.000000', 0.1, 79)
2018-05-08 18:31:17,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,141 INFO sqlalchemy.engine.base.Engine ('2015-10-18 00:00:00.000000', 0.03, 81)
2018-05-08 18:31:17,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,143 INFO sqlalchemy.engine.base.Engine ('2015-10-19 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:17,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,145 INFO sqlalchemy.engine.base.Engine ('2015-10-20 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:17,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,146 INFO sqlalchemy.engine.base.Engine ('2015-10-21 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:17,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,148 INFO sqlalchemy.engine.base.Engine ('2015-10-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,150 INFO sqlalchemy.engine.base.Engine ('2015-10-23 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:17,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,152 INFO sqlalchemy.engine.base.Engine ('2015-10-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,248 INFO sqlalchemy.engine.base.Engine ('2015-10-25 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:17,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,250 INFO sqlalchemy.engine.base.Engine ('2015-10-26 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:17,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,252 INFO sqlalchemy.engine.base.Engine ('2015-10-27 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:17,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,255 INFO sqlalchemy.engine.base.Engine ('2015-10-28 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:17,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,258 INFO sqlalchemy.engine.base.Engine ('2015-10-29 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,260 INFO sqlalchemy.engine.base.Engine ('2015-10-30 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,262 INFO sqlalchemy.engine.base.Engine ('2015-10-31 00:00:00.000000', 0.22, 78)
2018-05-08 18:31:17,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,264 INFO sqlalchemy.engine.base.Engine ('2015-11-01 00:00:00.000000', 0.33, 81)
2018-05-08 18:31:17,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,266 INFO sqlalchemy.engine.base.Engine ('2015-11-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,268 INFO sqlalchemy.engine.base.Engine ('2015-11-03 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:17,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,271 INFO sqlalchemy.engine.base.Engine ('2015-11-04 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:17,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,274 INFO sqlalchemy.engine.base.Engine ('2015-11-05 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:17,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,276 INFO sqlalchemy.engine.base.Engine ('2015-11-06 00:00:00.000000', 0.12, 77)
2018-05-08 18:31:17,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,278 INFO sqlalchemy.engine.base.Engine ('2015-11-07 00:00:00.000000', 0.12, 76)

2018-05-08 18:31:17,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,280 INFO sqlalchemy.engine.base.Engine ('2015-11-08 00:00:00.000000', 0.3, 77)
2018-05-08 18:31:17,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,282 INFO sqlalchemy.engine.base.Engine ('2015-11-09 00:00:00.000000', 0.11, 76)
2018-05-08 18:31:17,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,285 INFO sqlalchemy.engine.base.Engine ('2015-11-10 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:17,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,287 INFO sqlalchemy.engine.base.Engine ('2015-11-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,289 INFO sqlalchemy.engine.base.Engine ('2015-11-12 00:00:00.000000', 0.3, 76)
2018-05-08 18:31:17,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,291 INFO sqlalchemy.engine.base.Engine ('2015-11-13 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:17,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,293 INFO sqlalchemy.engine.base.Engine ('2015-11-14 00:00:00.000000', 0.53, 79)
2018-05-08 18:31:17,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,296 INFO sqlalchemy.engine.base.Engine ('2015-11-15 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:17,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,298 INFO sqlalchemy.engine.base.Engine ('2015-11-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,301 INFO sqlalchemy.engine.base.Engine ('2015-11-17 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:17,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,303 INFO sqlalchemy.engine.base.Engine ('2015-11-18 00:00:00.000000', 0.1, 81)
2018-05-08 18:31:17,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,306 INFO sqlalchemy.engine.base.Engine ('2015-11-19 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:17,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,309 INFO sqlalchemy.engine.base.Engine ('2015-11-20 00:00:00.000000', 0.68, 73)
2018-05-08 18:31:17,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,311 INFO sqlalchemy.engine.base.Engine ('2015-11-21 00:00:00.000000', 1.61, 75)
2018-05-08 18:31:17,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,313 INFO sqlalchemy.engine.base.Engine ('2015-11-22 00:00:00.000000', 0.8, 73)
2018-05-08 18:31:17,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,315 INFO sqlalchemy.engine.base.Engine ('2015-11-23 00:00:00.000000', 0.48, 74)
2018-05-08 18:31:17,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,317 INFO sqlalchemy.engine.base.Engine ('2015-11-24 00:00:00.000000', 1.7, 74)
2018-05-08 18:31:17,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,319 INFO sqlalchemy.engine.base.Engine ('2015-11-25 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:17,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,321 INFO sqlalchemy.engine.base.Engine ('2015-11-26 00:00:00.000000', 0.36, 73)
2018-05-08 18:31:17,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,325 INFO sqlalchemy.engine.base.Engine ('2015-11-27 00:00:00.000000', 0.91, 75)
2018-05-08 18:31:17,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,328 INFO sqlalchemy.engine.base.Engine ('2015-11-28 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:17,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,330 INFO sqlalchemy.engine.base.Engine ('2015-11-29 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:17,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,332 INFO sqlalchemy.engine.base.Engine ('2015-11-30 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:17,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,338 INFO sqlalchemy.engine.base.Engine ('2015-12-02 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:17,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,340 INFO sqlalchemy.engine.base.Engine ('2015-12-03 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:17,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,342 INFO sqlalchemy.engine.base.Engine ('2015-12-04 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:17,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,344 INFO sqlalchemy.engine.base.Engine ('2015-12-05 00:00:00.000000', 0.28, 72)
2018-05-08 18:31:17,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,347 INFO sqlalchemy.engine.base.Engine ('2015-12-06 00:00:00.000000', 0.52, 73)
2018-05-08 18:31:17,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,349 INFO sqlalchemy.engine.base.Engine ('2015-12-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,351 INFO sqlalchemy.engine.base.Engine ('2015-12-08 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:17,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,353 INFO sqlalchemy.engine.base.Engine ('2015-12-09 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:17,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,355 INFO sqlalchemy.engine.base.Engine ('2015-12-10 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:17,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,357 INFO sqlalchemy.engine.base.Engine ('2015-12-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,359 INFO sqlalchemy.engine.base.Engine ('2015-12-12 00:00:00.000000', 0.62, 72)
2018-05-08 18:31:17,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,360 INFO sqlalchemy.engine.base.Engine ('2015-12-13 00:00:00.000000', 0.0, 69)

2018-05-08 18:31:17,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,362 INFO sqlalchemy.engine.base.Engine ('2015-12-14 00:00:00.000000', 0.69, 69)
2018-05-08 18:31:17,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,364 INFO sqlalchemy.engine.base.Engine ('2015-12-15 00:00:00.000000', 0.24, 75)
2018-05-08 18:31:17,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,366 INFO sqlalchemy.engine.base.Engine ('2015-12-16 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:17,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,368 INFO sqlalchemy.engine.base.Engine ('2015-12-17 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:17,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,370 INFO sqlalchemy.engine.base.Engine ('2015-12-18 00:00:00.000000', 0.28, 73)
2018-05-08 18:31:17,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,371 INFO sqlalchemy.engine.base.Engine ('2015-12-19 00:00:00.000000', 0.36, 78)
2018-05-08 18:31:17,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,374 INFO sqlalchemy.engine.base.Engine ('2015-12-20 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:17,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,375 INFO sqlalchemy.engine.base.Engine ('2015-12-21 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:17,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,377 INFO sqlalchemy.engine.base.Engine ('2015-12-22 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:17,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,379 INFO sqlalchemy.engine.base.Engine ('2015-12-23 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:17,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,380 INFO sqlalchemy.engine.base.Engine ('2015-12-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,382 INFO sqlalchemy.engine.base.Engine ('2015-12-25 00:00:00.000000', 0.52, 70)
2018-05-08 18:31:17,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,384 INFO sqlalchemy.engine.base.Engine ('2015-12-26 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:17,385 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,385 INFO sqlalchemy.engine.base.Engine ('2015-12-27 00:00:00.000000', 0.25, 74)
2018-05-08 18:31:17,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,388 INFO sqlalchemy.engine.base.Engine ('2015-12-28 00:00:00.000000', 0.4, 74)
2018-05-08 18:31:17,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,390 INFO sqlalchemy.engine.base.Engine ('2015-12-29 00:00:00.000000', 0.11, 67)
2018-05-08 18:31:17,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,392 INFO sqlalchemy.engine.base.Engine ('2015-12-30 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:17,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,394 INFO sqlalchemy.engine.base.Engine ('2015-12-31 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:17,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,396 INFO sqlalchemy.engine.base.Engine ('2016-01-01 00:00:00.000000', 0.02, 63)
2018-05-08 18:31:17,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,397 INFO sqlalchemy.engine.base.Engine ('2016-01-02 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:17,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,399 INFO sqlalchemy.engine.base.Engine ('2016-01-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,401 INFO sqlalchemy.engine.base.Engine ('2016-01-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,403 INFO sqlalchemy.engine.base.Engine ('2016-01-05 00:00:00.000000', 0.19, 68)
2018-05-08 18:31:17,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,404 INFO sqlalchemy.engine.base.Engine ('2016-01-06 00:00:00.000000', 0.3, 70)
2018-05-08 18:31:17,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,406 INFO sqlalchemy.engine.base.Engine ('2016-01-07 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:17,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,407 INFO sqlalchemy.engine.base.Engine ('2016-01-08 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:17,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,409 INFO sqlalchemy.engine.base.Engine ('2016-01-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,410 INFO sqlalchemy.engine.base.Engine ('2016-01-10 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:17,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,412 INFO sqlalchemy.engine.base.Engine ('2016-01-11 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:17,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,414 INFO sqlalchemy.engine.base.Engine ('2016-01-12 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:17,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,415 INFO sqlalchemy.engine.base.Engine ('2016-01-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,417 INFO sqlalchemy.engine.base.Engine ('2016-01-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:17,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,419 INFO sqlalchemy.engine.base.Engine ('2016-01-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,420 INFO sqlalchemy.engine.base.Engine ('2016-01-16 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:17,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,422 INFO sqlalchemy.engine.base.Engine ('2016-01-17 00:00:00.000000', 0.02, 67)

2018-05-08 18:31:17,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,423 INFO sqlalchemy.engine.base.Engine ('2016-01-18 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:17,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,425 INFO sqlalchemy.engine.base.Engine ('2016-01-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:17,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,427 INFO sqlalchemy.engine.base.Engine ('2016-01-20 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:17,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,428 INFO sqlalchemy.engine.base.Engine ('2016-01-21 00:00:00.000000', 0.27, 75)
2018-05-08 18:31:17,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,430 INFO sqlalchemy.engine.base.Engine ('2016-01-22 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:17,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,432 INFO sqlalchemy.engine.base.Engine ('2016-01-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,433 INFO sqlalchemy.engine.base.Engine ('2016-01-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,435 INFO sqlalchemy.engine.base.Engine ('2016-01-25 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:17,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,437 INFO sqlalchemy.engine.base.Engine ('2016-01-26 00:00:00.000000', 0.16, 77)
2018-05-08 18:31:17,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,439 INFO sqlalchemy.engine.base.Engine ('2016-01-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,440 INFO sqlalchemy.engine.base.Engine ('2016-01-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:17,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,442 INFO sqlalchemy.engine.base.Engine ('2016-01-29 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:17,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,444 INFO sqlalchemy.engine.base.Engine ('2016-01-30 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:17,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,446 INFO sqlalchemy.engine.base.Engine ('2016-01-31 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,447 INFO sqlalchemy.engine.base.Engine ('2016-02-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,449 INFO sqlalchemy.engine.base.Engine ('2016-02-02 00:00:00.000000', 0.41, 68)
2018-05-08 18:31:17,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,499 INFO sqlalchemy.engine.base.Engine ('2016-02-03 00:00:00.000000', 0.25, 71)
2018-05-08 18:31:17,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,500 INFO sqlalchemy.engine.base.Engine ('2016-02-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,502 INFO sqlalchemy.engine.base.Engine ('2016-02-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,504 INFO sqlalchemy.engine.base.Engine ('2016-02-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,506 INFO sqlalchemy.engine.base.Engine ('2016-02-07 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:17,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,507 INFO sqlalchemy.engine.base.Engine ('2016-02-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,509 INFO sqlalchemy.engine.base.Engine ('2016-02-09 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:17,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,511 INFO sqlalchemy.engine.base.Engine ('2016-02-10 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:17,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,512 INFO sqlalchemy.engine.base.Engine ('2016-02-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,514 INFO sqlalchemy.engine.base.Engine ('2016-02-12 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:17,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,515 INFO sqlalchemy.engine.base.Engine ('2016-02-13 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:17,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,517 INFO sqlalchemy.engine.base.Engine ('2016-02-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,518 INFO sqlalchemy.engine.base.Engine ('2016-02-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,520 INFO sqlalchemy.engine.base.Engine ('2016-02-16 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:17,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,522 INFO sqlalchemy.engine.base.Engine ('2016-02-17 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:17,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,523 INFO sqlalchemy.engine.base.Engine ('2016-02-18 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,525 INFO sqlalchemy.engine.base.Engine ('2016-02-19 00:00:00.000000', 0.11, 69)
2018-05-08 18:31:17,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,527 INFO sqlalchemy.engine.base.Engine ('2016-02-20 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:17,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,528 INFO sqlalchemy.engine.base.Engine ('2016-02-21 00:00:00.000000', 0.09, 74)

2018-05-08 18:31:17,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,530 INFO sqlalchemy.engine.base.Engine ('2016-02-22 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:17,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,531 INFO sqlalchemy.engine.base.Engine ('2016-02-23 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:17,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,533 INFO sqlalchemy.engine.base.Engine ('2016-02-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,535 INFO sqlalchemy.engine.base.Engine ('2016-02-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,537 INFO sqlalchemy.engine.base.Engine ('2016-02-26 00:00:00.000000', 0.38, 77)
2018-05-08 18:31:17,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,538 INFO sqlalchemy.engine.base.Engine ('2016-02-27 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:17,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,540 INFO sqlalchemy.engine.base.Engine ('2016-02-28 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:17,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,542 INFO sqlalchemy.engine.base.Engine ('2016-02-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,543 INFO sqlalchemy.engine.base.Engine ('2016-03-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:17,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,545 INFO sqlalchemy.engine.base.Engine ('2016-03-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,547 INFO sqlalchemy.engine.base.Engine ('2016-03-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,548 INFO sqlalchemy.engine.base.Engine ('2016-03-04 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:17,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,550 INFO sqlalchemy.engine.base.Engine ('2016-03-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:17,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,552 INFO sqlalchemy.engine.base.Engine ('2016-03-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:17,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,554 INFO sqlalchemy.engine.base.Engine ('2016-03-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,556 INFO sqlalchemy.engine.base.Engine ('2016-03-08 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:17,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,557 INFO sqlalchemy.engine.base.Engine ('2016-03-09 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:17,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,559 INFO sqlalchemy.engine.base.Engine ('2016-03-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:17,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,561 INFO sqlalchemy.engine.base.Engine ('2016-03-11 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:17,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,563 INFO sqlalchemy.engine.base.Engine ('2016-03-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:17,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,565 INFO sqlalchemy.engine.base.Engine ('2016-03-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,566 INFO sqlalchemy.engine.base.Engine ('2016-03-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,568 INFO sqlalchemy.engine.base.Engine ('2016-03-15 00:00:00.000000', 0.3, 66)
2018-05-08 18:31:17,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,570 INFO sqlalchemy.engine.base.Engine ('2016-03-16 00:00:00.000000', 0.41, 71)
2018-05-08 18:31:17,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,572 INFO sqlalchemy.engine.base.Engine ('2016-03-17 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:17,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,573 INFO sqlalchemy.engine.base.Engine ('2016-03-18 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:17,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,575 INFO sqlalchemy.engine.base.Engine ('2016-03-19 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:17,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,577 INFO sqlalchemy.engine.base.Engine ('2016-03-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:17,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,578 INFO sqlalchemy.engine.base.Engine ('2016-03-21 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:17,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,580 INFO sqlalchemy.engine.base.Engine ('2016-03-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:17,581 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,582 INFO sqlalchemy.engine.base.Engine ('2016-03-23 00:00:00.000000', 1.78, 66)
2018-05-08 18:31:17,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,584 INFO sqlalchemy.engine.base.Engine ('2016-03-24 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:17,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,586 INFO sqlalchemy.engine.base.Engine ('2016-03-25 00:00:00.000000', 1.9, 70)
2018-05-08 18:31:17,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,587 INFO sqlalchemy.engine.base.Engine ('2016-03-26 00:00:00.000000', 0.87, 67)
2018-05-08 18:31:17,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,589 INFO sqlalchemy.engine.base.Engine ('2016-03-27 00:00:00.000000', 0.01, 67)

2018-05-08 18:31:17,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,591 INFO sqlalchemy.engine.base.Engine ('2016-03-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:17,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,592 INFO sqlalchemy.engine.base.Engine ('2016-03-29 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:17,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,594 INFO sqlalchemy.engine.base.Engine ('2016-03-30 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:17,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,596 INFO sqlalchemy.engine.base.Engine ('2016-03-31 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:17,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,597 INFO sqlalchemy.engine.base.Engine ('2016-04-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,599 INFO sqlalchemy.engine.base.Engine ('2016-04-02 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:17,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,601 INFO sqlalchemy.engine.base.Engine ('2016-04-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:17,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,602 INFO sqlalchemy.engine.base.Engine ('2016-04-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,604 INFO sqlalchemy.engine.base.Engine ('2016-04-05 00:00:00.000000', 0.2, 69)
2018-05-08 18:31:17,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,606 INFO sqlalchemy.engine.base.Engine ('2016-04-06 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:17,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,607 INFO sqlalchemy.engine.base.Engine ('2016-04-07 00:00:00.000000', 0.12, 68)
2018-05-08 18:31:17,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,609 INFO sqlalchemy.engine.base.Engine ('2016-04-08 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:17,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,610 INFO sqlalchemy.engine.base.Engine ('2016-04-09 00:00:00.000000', 0.66, 72)
2018-05-08 18:31:17,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,612 INFO sqlalchemy.engine.base.Engine ('2016-04-10 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:17,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,614 INFO sqlalchemy.engine.base.Engine ('2016-04-11 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:17,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,616 INFO sqlalchemy.engine.base.Engine ('2016-04-12 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,619 INFO sqlalchemy.engine.base.Engine ('2016-04-13 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:17,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,620 INFO sqlalchemy.engine.base.Engine ('2016-04-14 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:17,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,622 INFO sqlalchemy.engine.base.Engine ('2016-04-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,623 INFO sqlalchemy.engine.base.Engine ('2016-04-16 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:17,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,625 INFO sqlalchemy.engine.base.Engine ('2016-04-17 00:00:00.000000', 0.17, 69)
2018-05-08 18:31:17,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,626 INFO sqlalchemy.engine.base.Engine ('2016-04-18 00:00:00.000000', 0.4, 69)
2018-05-08 18:31:17,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,628 INFO sqlalchemy.engine.base.Engine ('2016-04-19 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:17,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,630 INFO sqlalchemy.engine.base.Engine ('2016-04-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:17,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,631 INFO sqlalchemy.engine.base.Engine ('2016-04-21 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:17,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,633 INFO sqlalchemy.engine.base.Engine ('2016-04-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,635 INFO sqlalchemy.engine.base.Engine ('2016-04-23 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:17,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,637 INFO sqlalchemy.engine.base.Engine ('2016-04-24 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:17,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,638 INFO sqlalchemy.engine.base.Engine ('2016-04-25 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:17,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,640 INFO sqlalchemy.engine.base.Engine ('2016-04-26 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:17,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,641 INFO sqlalchemy.engine.base.Engine ('2016-04-27 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:17,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,643 INFO sqlalchemy.engine.base.Engine ('2016-04-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,644 INFO sqlalchemy.engine.base.Engine ('2016-04-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,646 INFO sqlalchemy.engine.base.Engine ('2016-04-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,647 INFO sqlalchemy.engine.base.Engine ('2016-05-01 00:00:00.000000', 0.04, 75)

2018-05-08 18:31:17,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,649 INFO sqlalchemy.engine.base.Engine ('2016-05-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,651 INFO sqlalchemy.engine.base.Engine ('2016-05-03 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,653 INFO sqlalchemy.engine.base.Engine ('2016-05-04 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:17,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,654 INFO sqlalchemy.engine.base.Engine ('2016-05-05 00:00:00.000000', 0.6, 77)
2018-05-08 18:31:17,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,656 INFO sqlalchemy.engine.base.Engine ('2016-05-06 00:00:00.000000', 0.22, 70)
2018-05-08 18:31:17,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,658 INFO sqlalchemy.engine.base.Engine ('2016-05-07 00:00:00.000000', 1.53, 69)
2018-05-08 18:31:17,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,660 INFO sqlalchemy.engine.base.Engine ('2016-05-08 00:00:00.000000', 0.8, 68)
2018-05-08 18:31:17,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,662 INFO sqlalchemy.engine.base.Engine ('2016-05-09 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:17,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,663 INFO sqlalchemy.engine.base.Engine ('2016-05-10 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:17,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,665 INFO sqlalchemy.engine.base.Engine ('2016-05-11 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:17,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,666 INFO sqlalchemy.engine.base.Engine ('2016-05-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:17,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,714 INFO sqlalchemy.engine.base.Engine ('2016-05-13 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:17,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,716 INFO sqlalchemy.engine.base.Engine ('2016-05-14 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:17,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,718 INFO sqlalchemy.engine.base.Engine ('2016-05-15 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,719 INFO sqlalchemy.engine.base.Engine ('2016-05-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,721 INFO sqlalchemy.engine.base.Engine ('2016-05-17 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:17,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,723 INFO sqlalchemy.engine.base.Engine ('2016-05-18 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:17,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,724 INFO sqlalchemy.engine.base.Engine ('2016-05-19 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:17,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,726 INFO sqlalchemy.engine.base.Engine ('2016-05-20 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:17,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,728 INFO sqlalchemy.engine.base.Engine ('2016-05-21 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:17,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,729 INFO sqlalchemy.engine.base.Engine ('2016-05-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,731 INFO sqlalchemy.engine.base.Engine ('2016-05-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,733 INFO sqlalchemy.engine.base.Engine ('2016-05-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:17,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,734 INFO sqlalchemy.engine.base.Engine ('2016-05-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,736 INFO sqlalchemy.engine.base.Engine ('2016-05-26 00:00:00.000000', 0.8, 72)
2018-05-08 18:31:17,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,738 INFO sqlalchemy.engine.base.Engine ('2016-05-27 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:17,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,739 INFO sqlalchemy.engine.base.Engine ('2016-05-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:17,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,741 INFO sqlalchemy.engine.base.Engine ('2016-05-29 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:17,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,742 INFO sqlalchemy.engine.base.Engine ('2016-05-30 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:17,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,744 INFO sqlalchemy.engine.base.Engine ('2016-05-31 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:17,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,747 INFO sqlalchemy.engine.base.Engine ('2016-06-01 00:00:00.000000', 0.89, 70)
2018-05-08 18:31:17,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,748 INFO sqlalchemy.engine.base.Engine ('2016-06-02 00:00:00.000000', 0.15, 69)
2018-05-08 18:31:17,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,750 INFO sqlalchemy.engine.base.Engine ('2016-06-03 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:17,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,752 INFO sqlalchemy.engine.base.Engine ('2016-06-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:17,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,753 INFO sqlalchemy.engine.base.Engine ('2016-06-05 00:00:00.000000', 0.63, 70)

2018-05-08 18:31:17,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,755 INFO sqlalchemy.engine.base.Engine ('2016-06-06 00:00:00.000000', 0.36, 74)
2018-05-08 18:31:17,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,757 INFO sqlalchemy.engine.base.Engine ('2016-06-07 00:00:00.000000', 0.4, 75)
2018-05-08 18:31:17,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,758 INFO sqlalchemy.engine.base.Engine ('2016-06-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:17,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,760 INFO sqlalchemy.engine.base.Engine ('2016-06-09 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:17,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,761 INFO sqlalchemy.engine.base.Engine ('2016-06-10 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:17,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,763 INFO sqlalchemy.engine.base.Engine ('2016-06-11 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:17,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,765 INFO sqlalchemy.engine.base.Engine ('2016-06-12 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:17,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,766 INFO sqlalchemy.engine.base.Engine ('2016-06-13 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:17,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,768 INFO sqlalchemy.engine.base.Engine ('2016-06-14 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:17,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,770 INFO sqlalchemy.engine.base.Engine ('2016-06-15 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:17,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,771 INFO sqlalchemy.engine.base.Engine ('2016-06-16 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:17,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,773 INFO sqlalchemy.engine.base.Engine ('2016-06-17 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:17,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,774 INFO sqlalchemy.engine.base.Engine ('2016-06-18 00:00:00.000000', 0.3, 75)
2018-05-08 18:31:17,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,776 INFO sqlalchemy.engine.base.Engine ('2016-06-19 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:17,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,778 INFO sqlalchemy.engine.base.Engine ('2016-06-20 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:17,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,779 INFO sqlalchemy.engine.base.Engine ('2016-06-21 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:17,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,781 INFO sqlalchemy.engine.base.Engine ('2016-06-22 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:17,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,783 INFO sqlalchemy.engine.base.Engine ('2016-06-23 00:00:00.000000', 0.25, 74)
2018-05-08 18:31:17,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,784 INFO sqlalchemy.engine.base.Engine ('2016-06-24 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:17,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,786 INFO sqlalchemy.engine.base.Engine ('2016-06-25 00:00:00.000000', 0.8, 71)
2018-05-08 18:31:17,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,788 INFO sqlalchemy.engine.base.Engine ('2016-06-26 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:17,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,790 INFO sqlalchemy.engine.base.Engine ('2016-06-27 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:17,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,792 INFO sqlalchemy.engine.base.Engine ('2016-06-28 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:17,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,793 INFO sqlalchemy.engine.base.Engine ('2016-06-29 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:17,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,795 INFO sqlalchemy.engine.base.Engine ('2016-06-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,797 INFO sqlalchemy.engine.base.Engine ('2016-07-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:17,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,798 INFO sqlalchemy.engine.base.Engine ('2016-07-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,800 INFO sqlalchemy.engine.base.Engine ('2016-07-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,802 INFO sqlalchemy.engine.base.Engine ('2016-07-04 00:00:00.000000', 0.14, 76)
2018-05-08 18:31:17,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,803 INFO sqlalchemy.engine.base.Engine ('2016-07-05 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:17,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,805 INFO sqlalchemy.engine.base.Engine ('2016-07-06 00:00:00.000000', 0.49, 74)
2018-05-08 18:31:17,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,807 INFO sqlalchemy.engine.base.Engine ('2016-07-07 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:17,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,808 INFO sqlalchemy.engine.base.Engine ('2016-07-08 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:17,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,810 INFO sqlalchemy.engine.base.Engine ('2016-07-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:17,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,811 INFO sqlalchemy.engine.base.Engine ('2016-07-10 00:00:00.000000', 0.14, 75)

2018-05-08 18:31:17,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,813 INFO sqlalchemy.engine.base.Engine ('2016-07-11 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:17,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,815 INFO sqlalchemy.engine.base.Engine ('2016-07-12 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:17,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,817 INFO sqlalchemy.engine.base.Engine ('2016-07-13 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:17,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,818 INFO sqlalchemy.engine.base.Engine ('2016-07-14 00:00:00.000000', 0.43, 75)
2018-05-08 18:31:17,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,820 INFO sqlalchemy.engine.base.Engine ('2016-07-15 00:00:00.000000', 0.23, 74)
2018-05-08 18:31:17,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,822 INFO sqlalchemy.engine.base.Engine ('2016-07-16 00:00:00.000000', 0.44, 75)
2018-05-08 18:31:17,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,824 INFO sqlalchemy.engine.base.Engine ('2016-07-17 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:17,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,825 INFO sqlalchemy.engine.base.Engine ('2016-07-18 00:00:00.000000', 0.26, 76)
2018-05-08 18:31:17,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,827 INFO sqlalchemy.engine.base.Engine ('2016-07-19 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:17,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,828 INFO sqlalchemy.engine.base.Engine ('2016-07-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,830 INFO sqlalchemy.engine.base.Engine ('2016-07-21 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:17,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,831 INFO sqlalchemy.engine.base.Engine ('2016-07-22 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:17,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,833 INFO sqlalchemy.engine.base.Engine ('2016-07-23 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:17,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,835 INFO sqlalchemy.engine.base.Engine ('2016-07-24 00:00:00.000000', 0.15, 78)
2018-05-08 18:31:17,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,836 INFO sqlalchemy.engine.base.Engine ('2016-07-25 00:00:00.000000', 7.65, 78)
2018-05-08 18:31:17,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,838 INFO sqlalchemy.engine.base.Engine ('2016-07-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,840 INFO sqlalchemy.engine.base.Engine ('2016-07-27 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:17,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,841 INFO sqlalchemy.engine.base.Engine ('2016-07-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,843 INFO sqlalchemy.engine.base.Engine ('2016-07-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,844 INFO sqlalchemy.engine.base.Engine ('2016-07-30 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:17,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,847 INFO sqlalchemy.engine.base.Engine ('2016-07-31 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:17,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,849 INFO sqlalchemy.engine.base.Engine ('2016-08-01 00:00:00.000000', 2.35, 76)
2018-05-08 18:31:17,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,850 INFO sqlalchemy.engine.base.Engine ('2016-08-02 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:17,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,852 INFO sqlalchemy.engine.base.Engine ('2016-08-03 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:17,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,854 INFO sqlalchemy.engine.base.Engine ('2016-08-04 00:00:00.000000', 0.62, 76)
2018-05-08 18:31:17,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,855 INFO sqlalchemy.engine.base.Engine ('2016-08-05 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:17,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,857 INFO sqlalchemy.engine.base.Engine ('2016-08-06 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:17,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,859 INFO sqlalchemy.engine.base.Engine ('2016-08-07 00:00:00.000000', 0.3, 77)
2018-05-08 18:31:17,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,860 INFO sqlalchemy.engine.base.Engine ('2016-08-08 00:00:00.000000', 0.33, 78)
2018-05-08 18:31:17,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,862 INFO sqlalchemy.engine.base.Engine ('2016-08-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,863 INFO sqlalchemy.engine.base.Engine ('2016-08-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,865 INFO sqlalchemy.engine.base.Engine ('2016-08-11 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:17,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,867 INFO sqlalchemy.engine.base.Engine ('2016-08-12 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:17,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,868 INFO sqlalchemy.engine.base.Engine ('2016-08-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:17,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,870 INFO sqlalchemy.engine.base.Engine ('2016-08-14 00:00:00.000000', 0.17, 77)

2018-05-08 18:31:17,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,871 INFO sqlalchemy.engine.base.Engine ('2016-08-15 00:00:00.000000', 0.17, 77)
2018-05-08 18:31:17,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,873 INFO sqlalchemy.engine.base.Engine ('2016-08-16 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:17,874 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,875 INFO sqlalchemy.engine.base.Engine ('2016-08-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:17,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,876 INFO sqlalchemy.engine.base.Engine ('2016-08-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:17,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,878 INFO sqlalchemy.engine.base.Engine ('2016-08-19 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:17,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,880 INFO sqlalchemy.engine.base.Engine ('2016-08-20 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:17,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,929 INFO sqlalchemy.engine.base.Engine ('2016-08-21 00:00:00.000000', 0.32, 76)
2018-05-08 18:31:17,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,931 INFO sqlalchemy.engine.base.Engine ('2016-08-22 00:00:00.000000', 0.94, 76)
2018-05-08 18:31:17,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,933 INFO sqlalchemy.engine.base.Engine ('2016-08-23 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:17,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,934 INFO sqlalchemy.engine.base.Engine ('2016-08-24 00:00:00.000000', 2.15, 76)
2018-05-08 18:31:17,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,936 INFO sqlalchemy.engine.base.Engine ('2016-08-25 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:17,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,938 INFO sqlalchemy.engine.base.Engine ('2016-08-26 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:17,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,939 INFO sqlalchemy.engine.base.Engine ('2016-08-27 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:17,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,941 INFO sqlalchemy.engine.base.Engine ('2016-08-28 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:17,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,943 INFO sqlalchemy.engine.base.Engine ('2016-08-29 00:00:00.000000', 0.17, 78)
2018-05-08 18:31:17,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,944 INFO sqlalchemy.engine.base.Engine ('2016-08-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:17,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,946 INFO sqlalchemy.engine.base.Engine ('2016-08-31 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:17,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,948 INFO sqlalchemy.engine.base.Engine ('2016-09-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,949 INFO sqlalchemy.engine.base.Engine ('2016-09-02 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:17,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,951 INFO sqlalchemy.engine.base.Engine ('2016-09-03 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:17,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,953 INFO sqlalchemy.engine.base.Engine ('2016-09-04 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:17,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,955 INFO sqlalchemy.engine.base.Engine ('2016-09-05 00:00:00.000000', 0.11, 78)
2018-05-08 18:31:17,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,957 INFO sqlalchemy.engine.base.Engine ('2016-09-06 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:17,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,958 INFO sqlalchemy.engine.base.Engine ('2016-09-07 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:17,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,960 INFO sqlalchemy.engine.base.Engine ('2016-09-08 00:00:00.000000', 0.22, 77)
2018-05-08 18:31:17,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,961 INFO sqlalchemy.engine.base.Engine ('2016-09-09 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:17,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,963 INFO sqlalchemy.engine.base.Engine ('2016-09-10 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:17,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,964 INFO sqlalchemy.engine.base.Engine ('2016-09-11 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:17,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,966 INFO sqlalchemy.engine.base.Engine ('2016-09-12 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:17,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,968 INFO sqlalchemy.engine.base.Engine ('2016-09-13 00:00:00.000000', 0.37, 76)
2018-05-08 18:31:17,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,970 INFO sqlalchemy.engine.base.Engine ('2016-09-14 00:00:00.000000', 0.9, 76)
2018-05-08 18:31:17,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,971 INFO sqlalchemy.engine.base.Engine ('2016-09-15 00:00:00.000000', 0.12, 78)
2018-05-08 18:31:17,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,973 INFO sqlalchemy.engine.base.Engine ('2016-09-16 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:17,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,974 INFO sqlalchemy.engine.base.Engine ('2016-09-17 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:17,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,976 INFO sqlalchemy.engine.base.Engine ('2016-09-18 00:00:00.000000', 0.0, 78)

2018-05-08 18:31:17,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,978 INFO sqlalchemy.engine.base.Engine ('2016-09-19 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:17,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,979 INFO sqlalchemy.engine.base.Engine ('2016-09-20 00:00:00.000000', 0.09, 78)
2018-05-08 18:31:17,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,981 INFO sqlalchemy.engine.base.Engine ('2016-09-21 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:17,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,983 INFO sqlalchemy.engine.base.Engine ('2016-09-22 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:17,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,984 INFO sqlalchemy.engine.base.Engine ('2016-09-23 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:17,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,986 INFO sqlalchemy.engine.base.Engine ('2016-09-24 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:17,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,987 INFO sqlalchemy.engine.base.Engine ('2016-09-25 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:17,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,989 INFO sqlalchemy.engine.base.Engine ('2016-09-26 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:17,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,991 INFO sqlalchemy.engine.base.Engine ('2016-09-27 00:00:00.000000', 0.12, 77)
2018-05-08 18:31:17,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,992 INFO sqlalchemy.engine.base.Engine ('2016-09-28 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:17,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,994 INFO sqlalchemy.engine.base.Engine ('2016-09-29 00:00:00.000000', 0.49, 76)
2018-05-08 18:31:17,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,996 INFO sqlalchemy.engine.base.Engine ('2016-09-30 00:00:00.000000', 0.31, 77)
2018-05-08 18:31:17,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,997 INFO sqlalchemy.engine.base.Engine ('2016-10-01 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:17,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:17,999 INFO sqlalchemy.engine.base.Engine ('2016-10-02 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,000 INFO sqlalchemy.engine.base.Engine ('2016-10-03 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:18,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,002 INFO sqlalchemy.engine.base.Engine ('2016-10-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,004 INFO sqlalchemy.engine.base.Engine ('2016-10-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,005 INFO sqlalchemy.engine.base.Engine ('2016-10-06 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:18,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,007 INFO sqlalchemy.engine.base.Engine ('2016-10-07 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,009 INFO sqlalchemy.engine.base.Engine ('2016-10-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,011 INFO sqlalchemy.engine.base.Engine ('2016-10-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,013 INFO sqlalchemy.engine.base.Engine ('2016-10-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,015 INFO sqlalchemy.engine.base.Engine ('2016-10-11 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,016 INFO sqlalchemy.engine.base.Engine ('2016-10-12 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:18,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,018 INFO sqlalchemy.engine.base.Engine ('2016-10-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,020 INFO sqlalchemy.engine.base.Engine ('2016-10-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,021 INFO sqlalchemy.engine.base.Engine ('2016-10-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,023 INFO sqlalchemy.engine.base.Engine ('2016-10-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,025 INFO sqlalchemy.engine.base.Engine ('2016-10-17 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:18,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,026 INFO sqlalchemy.engine.base.Engine ('2016-10-18 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:18,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,028 INFO sqlalchemy.engine.base.Engine ('2016-10-19 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:18,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,030 INFO sqlalchemy.engine.base.Engine ('2016-10-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,031 INFO sqlalchemy.engine.base.Engine ('2016-10-21 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:18,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,033 INFO sqlalchemy.engine.base.Engine ('2016-10-22 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:18,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,035 INFO sqlalchemy.engine.base.Engine ('2016-10-23 00:00:00.000000', 0.01, 76)

2018-05-08 18:31:18,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,037 INFO sqlalchemy.engine.base.Engine ('2016-10-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,038 INFO sqlalchemy.engine.base.Engine ('2016-10-25 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:18,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,040 INFO sqlalchemy.engine.base.Engine ('2016-10-26 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:18,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,042 INFO sqlalchemy.engine.base.Engine ('2016-10-27 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:18,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,043 INFO sqlalchemy.engine.base.Engine ('2016-10-28 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,045 INFO sqlalchemy.engine.base.Engine ('2016-10-29 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,046 INFO sqlalchemy.engine.base.Engine ('2016-10-30 00:00:00.000000', 0.1, 78)
2018-05-08 18:31:18,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,048 INFO sqlalchemy.engine.base.Engine ('2016-10-31 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:18,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,050 INFO sqlalchemy.engine.base.Engine ('2016-11-01 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:18,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,051 INFO sqlalchemy.engine.base.Engine ('2016-11-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,053 INFO sqlalchemy.engine.base.Engine ('2016-11-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,054 INFO sqlalchemy.engine.base.Engine ('2016-11-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,056 INFO sqlalchemy.engine.base.Engine ('2016-11-05 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:18,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,058 INFO sqlalchemy.engine.base.Engine ('2016-11-06 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:18,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,059 INFO sqlalchemy.engine.base.Engine ('2016-11-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,061 INFO sqlalchemy.engine.base.Engine ('2016-11-08 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:18,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,063 INFO sqlalchemy.engine.base.Engine ('2016-11-09 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:18,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,064 INFO sqlalchemy.engine.base.Engine ('2016-11-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,066 INFO sqlalchemy.engine.base.Engine ('2016-11-11 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,067 INFO sqlalchemy.engine.base.Engine ('2016-11-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:18,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,069 INFO sqlalchemy.engine.base.Engine ('2016-11-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,071 INFO sqlalchemy.engine.base.Engine ('2016-11-14 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:18,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,073 INFO sqlalchemy.engine.base.Engine ('2016-11-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,075 INFO sqlalchemy.engine.base.Engine ('2016-11-16 00:00:00.000000', 0.14, 76)
2018-05-08 18:31:18,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,076 INFO sqlalchemy.engine.base.Engine ('2016-11-17 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:18,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,078 INFO sqlalchemy.engine.base.Engine ('2016-11-18 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:18,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,080 INFO sqlalchemy.engine.base.Engine ('2016-11-19 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:18,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,081 INFO sqlalchemy.engine.base.Engine ('2016-11-20 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:18,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,083 INFO sqlalchemy.engine.base.Engine ('2016-11-21 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,085 INFO sqlalchemy.engine.base.Engine ('2016-11-22 00:00:00.000000', 0.41, 76)
2018-05-08 18:31:18,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,086 INFO sqlalchemy.engine.base.Engine ('2016-11-23 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:18,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,088 INFO sqlalchemy.engine.base.Engine ('2016-11-24 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:18,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,089 INFO sqlalchemy.engine.base.Engine ('2016-11-25 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:18,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,091 INFO sqlalchemy.engine.base.Engine ('2016-11-26 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:18,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,093 INFO sqlalchemy.engine.base.Engine ('2016-11-27 00:00:00.000000', 0.06, 75)

2018-05-08 18:31:18,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,094 INFO sqlalchemy.engine.base.Engine ('2016-11-28 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,140 INFO sqlalchemy.engine.base.Engine ('2016-11-29 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:18,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,142 INFO sqlalchemy.engine.base.Engine ('2016-11-30 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:18,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,143 INFO sqlalchemy.engine.base.Engine ('2016-12-01 00:00:00.000000', 0.33, 73)
2018-05-08 18:31:18,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,145 INFO sqlalchemy.engine.base.Engine ('2016-12-02 00:00:00.000000', 0.3, 71)
2018-05-08 18:31:18,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,147 INFO sqlalchemy.engine.base.Engine ('2016-12-03 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:18,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,149 INFO sqlalchemy.engine.base.Engine ('2016-12-04 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:18,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,152 INFO sqlalchemy.engine.base.Engine ('2016-12-05 00:00:00.000000', 0.34, 68)
2018-05-08 18:31:18,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,153 INFO sqlalchemy.engine.base.Engine ('2016-12-06 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:18,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,155 INFO sqlalchemy.engine.base.Engine ('2016-12-07 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:18,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,157 INFO sqlalchemy.engine.base.Engine ('2016-12-08 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:18,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,159 INFO sqlalchemy.engine.base.Engine ('2016-12-09 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:18,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,160 INFO sqlalchemy.engine.base.Engine ('2016-12-10 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:18,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,162 INFO sqlalchemy.engine.base.Engine ('2016-12-11 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:18,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,164 INFO sqlalchemy.engine.base.Engine ('2016-12-12 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:18,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,165 INFO sqlalchemy.engine.base.Engine ('2016-12-13 00:00:00.000000', 0.1, 68)
2018-05-08 18:31:18,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,167 INFO sqlalchemy.engine.base.Engine ('2016-12-14 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:18,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,169 INFO sqlalchemy.engine.base.Engine ('2016-12-15 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:18,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,171 INFO sqlalchemy.engine.base.Engine ('2016-12-16 00:00:00.000000', 0.01, 63)
2018-05-08 18:31:18,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,173 INFO sqlalchemy.engine.base.Engine ('2016-12-17 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:18,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,175 INFO sqlalchemy.engine.base.Engine ('2016-12-18 00:00:00.000000', 0.29, 67)
2018-05-08 18:31:18,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,176 INFO sqlalchemy.engine.base.Engine ('2016-12-19 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:18,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,178 INFO sqlalchemy.engine.base.Engine ('2016-12-20 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:18,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,180 INFO sqlalchemy.engine.base.Engine ('2016-12-21 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:18,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,181 INFO sqlalchemy.engine.base.Engine ('2016-12-22 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:18,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,183 INFO sqlalchemy.engine.base.Engine ('2016-12-23 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:18,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,185 INFO sqlalchemy.engine.base.Engine ('2016-12-24 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:18,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,186 INFO sqlalchemy.engine.base.Engine ('2016-12-25 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:18,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,188 INFO sqlalchemy.engine.base.Engine ('2016-12-26 00:00:00.000000', 0.26, 74)
2018-05-08 18:31:18,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,190 INFO sqlalchemy.engine.base.Engine ('2016-12-27 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:18,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,191 INFO sqlalchemy.engine.base.Engine ('2016-12-28 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:18,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,193 INFO sqlalchemy.engine.base.Engine ('2016-12-29 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:18,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,195 INFO sqlalchemy.engine.base.Engine ('2016-12-30 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:18,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,196 INFO sqlalchemy.engine.base.Engine ('2016-12-31 00:00:00.000000', 0.62, 71)
2018-05-08 18:31:18,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,198 INFO sqlalchemy.engine.base.Engine ('2017-01-01 00:00:00.000000', 0.29, 66)

2018-05-08 18:31:18,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,200 INFO sqlalchemy.engine.base.Engine ('2017-01-02 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,201 INFO sqlalchemy.engine.base.Engine ('2017-01-03 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:18,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,203 INFO sqlalchemy.engine.base.Engine ('2017-01-04 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:18,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,204 INFO sqlalchemy.engine.base.Engine ('2017-01-05 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:18,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,206 INFO sqlalchemy.engine.base.Engine ('2017-01-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,208 INFO sqlalchemy.engine.base.Engine ('2017-01-07 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:18,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,209 INFO sqlalchemy.engine.base.Engine ('2017-01-08 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:18,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,211 INFO sqlalchemy.engine.base.Engine ('2017-01-09 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:18,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,213 INFO sqlalchemy.engine.base.Engine ('2017-01-10 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,215 INFO sqlalchemy.engine.base.Engine ('2017-01-11 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,216 INFO sqlalchemy.engine.base.Engine ('2017-01-12 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:18,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,218 INFO sqlalchemy.engine.base.Engine ('2017-01-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,220 INFO sqlalchemy.engine.base.Engine ('2017-01-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,221 INFO sqlalchemy.engine.base.Engine ('2017-01-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:18,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,224 INFO sqlalchemy.engine.base.Engine ('2017-01-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,226 INFO sqlalchemy.engine.base.Engine ('2017-01-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,227 INFO sqlalchemy.engine.base.Engine ('2017-01-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,229 INFO sqlalchemy.engine.base.Engine ('2017-01-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,231 INFO sqlalchemy.engine.base.Engine ('2017-01-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,233 INFO sqlalchemy.engine.base.Engine ('2017-01-21 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:18,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,234 INFO sqlalchemy.engine.base.Engine ('2017-01-22 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:18,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,236 INFO sqlalchemy.engine.base.Engine ('2017-01-23 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:18,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,238 INFO sqlalchemy.engine.base.Engine ('2017-01-24 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:18,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,240 INFO sqlalchemy.engine.base.Engine ('2017-01-25 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:18,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,241 INFO sqlalchemy.engine.base.Engine ('2017-01-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,243 INFO sqlalchemy.engine.base.Engine ('2017-01-27 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:18,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,245 INFO sqlalchemy.engine.base.Engine ('2017-01-28 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:18,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,246 INFO sqlalchemy.engine.base.Engine ('2017-01-29 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,248 INFO sqlalchemy.engine.base.Engine ('2017-01-30 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,249 INFO sqlalchemy.engine.base.Engine ('2017-01-31 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,251 INFO sqlalchemy.engine.base.Engine ('2017-02-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,253 INFO sqlalchemy.engine.base.Engine ('2017-02-02 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:18,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,254 INFO sqlalchemy.engine.base.Engine ('2017-02-03 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:18,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,256 INFO sqlalchemy.engine.base.Engine ('2017-02-04 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:18,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,258 INFO sqlalchemy.engine.base.Engine ('2017-02-05 00:00:00.000000', 0.0, 75)

2018-05-08 18:31:18,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,259 INFO sqlalchemy.engine.base.Engine ('2017-02-06 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:18,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,261 INFO sqlalchemy.engine.base.Engine ('2017-02-07 00:00:00.000000', 1.08, 67)
2018-05-08 18:31:18,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,262 INFO sqlalchemy.engine.base.Engine ('2017-02-08 00:00:00.000000', 1.08, 67)
2018-05-08 18:31:18,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,264 INFO sqlalchemy.engine.base.Engine ('2017-02-09 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:18,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,266 INFO sqlalchemy.engine.base.Engine ('2017-02-10 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:18,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,267 INFO sqlalchemy.engine.base.Engine ('2017-02-11 00:00:00.000000', 1.0, 65)
2018-05-08 18:31:18,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,270 INFO sqlalchemy.engine.base.Engine ('2017-02-12 00:00:00.000000', 1.07, 67)
2018-05-08 18:31:18,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,272 INFO sqlalchemy.engine.base.Engine ('2017-02-13 00:00:00.000000', 2.9, 69)
2018-05-08 18:31:18,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,274 INFO sqlalchemy.engine.base.Engine ('2017-02-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,275 INFO sqlalchemy.engine.base.Engine ('2017-02-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,277 INFO sqlalchemy.engine.base.Engine ('2017-02-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,279 INFO sqlalchemy.engine.base.Engine ('2017-02-17 00:00:00.000000', 0.8, 67)
2018-05-08 18:31:18,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,280 INFO sqlalchemy.engine.base.Engine ('2017-02-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,282 INFO sqlalchemy.engine.base.Engine ('2017-02-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,283 INFO sqlalchemy.engine.base.Engine ('2017-02-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,285 INFO sqlalchemy.engine.base.Engine ('2017-02-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,287 INFO sqlalchemy.engine.base.Engine ('2017-02-22 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:18,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,289 INFO sqlalchemy.engine.base.Engine ('2017-02-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,291 INFO sqlalchemy.engine.base.Engine ('2017-02-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,292 INFO sqlalchemy.engine.base.Engine ('2017-02-25 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:18,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,294 INFO sqlalchemy.engine.base.Engine ('2017-02-26 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:18,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,295 INFO sqlalchemy.engine.base.Engine ('2017-02-27 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,298 INFO sqlalchemy.engine.base.Engine ('2017-02-28 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:18,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,299 INFO sqlalchemy.engine.base.Engine ('2017-03-01 00:00:00.000000', 2.2, 72)
2018-05-08 18:31:18,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,301 INFO sqlalchemy.engine.base.Engine ('2017-03-02 00:00:00.000000', 1.45, 73)
2018-05-08 18:31:18,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,304 INFO sqlalchemy.engine.base.Engine ('2017-03-03 00:00:00.000000', 0.54, 73)
2018-05-08 18:31:18,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,307 INFO sqlalchemy.engine.base.Engine ('2017-03-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,309 INFO sqlalchemy.engine.base.Engine ('2017-03-05 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:18,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,311 INFO sqlalchemy.engine.base.Engine ('2017-03-06 00:00:00.000000', 0.51, 66)
2018-05-08 18:31:18,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,313 INFO sqlalchemy.engine.base.Engine ('2017-03-07 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:18,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,315 INFO sqlalchemy.engine.base.Engine ('2017-03-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,365 INFO sqlalchemy.engine.base.Engine ('2017-03-09 00:00:00.000000', 0.8, 67)
2018-05-08 18:31:18,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,367 INFO sqlalchemy.engine.base.Engine ('2017-03-10 00:00:00.000000', 0.13, 68)
2018-05-08 18:31:18,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,369 INFO sqlalchemy.engine.base.Engine ('2017-03-11 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:18,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,370 INFO sqlalchemy.engine.base.Engine ('2017-03-12 00:00:00.000000', 0.0, 70)

2018-05-08 18:31:18,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,372 INFO sqlalchemy.engine.base.Engine ('2017-03-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,374 INFO sqlalchemy.engine.base.Engine ('2017-03-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,376 INFO sqlalchemy.engine.base.Engine ('2017-03-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,378 INFO sqlalchemy.engine.base.Engine ('2017-03-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,380 INFO sqlalchemy.engine.base.Engine ('2017-03-17 00:00:00.000000', 0.19, 69)
2018-05-08 18:31:18,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,381 INFO sqlalchemy.engine.base.Engine ('2017-03-18 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:18,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,383 INFO sqlalchemy.engine.base.Engine ('2017-03-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,385 INFO sqlalchemy.engine.base.Engine ('2017-03-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,386 INFO sqlalchemy.engine.base.Engine ('2017-03-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,388 INFO sqlalchemy.engine.base.Engine ('2017-03-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,390 INFO sqlalchemy.engine.base.Engine ('2017-03-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,392 INFO sqlalchemy.engine.base.Engine ('2017-03-24 00:00:00.000000', 0.6, 72)
2018-05-08 18:31:18,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,394 INFO sqlalchemy.engine.base.Engine ('2017-03-25 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:18,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,396 INFO sqlalchemy.engine.base.Engine ('2017-03-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,398 INFO sqlalchemy.engine.base.Engine ('2017-03-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,399 INFO sqlalchemy.engine.base.Engine ('2017-03-28 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:18,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,401 INFO sqlalchemy.engine.base.Engine ('2017-03-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,403 INFO sqlalchemy.engine.base.Engine ('2017-03-30 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:18,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,405 INFO sqlalchemy.engine.base.Engine ('2017-03-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,407 INFO sqlalchemy.engine.base.Engine ('2017-04-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,409 INFO sqlalchemy.engine.base.Engine ('2017-04-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,412 INFO sqlalchemy.engine.base.Engine ('2017-04-03 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:18,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,414 INFO sqlalchemy.engine.base.Engine ('2017-04-04 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:18,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,415 INFO sqlalchemy.engine.base.Engine ('2017-04-05 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:18,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,417 INFO sqlalchemy.engine.base.Engine ('2017-04-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,419 INFO sqlalchemy.engine.base.Engine ('2017-04-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,421 INFO sqlalchemy.engine.base.Engine ('2017-04-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,423 INFO sqlalchemy.engine.base.Engine ('2017-04-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,425 INFO sqlalchemy.engine.base.Engine ('2017-04-10 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:18,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,427 INFO sqlalchemy.engine.base.Engine ('2017-04-11 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:18,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,429 INFO sqlalchemy.engine.base.Engine ('2017-04-12 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:18,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,430 INFO sqlalchemy.engine.base.Engine ('2017-04-13 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:18,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,432 INFO sqlalchemy.engine.base.Engine ('2017-04-14 00:00:00.000000', 0.69, 70)
2018-05-08 18:31:18,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,434 INFO sqlalchemy.engine.base.Engine ('2017-04-15 00:00:00.000000', 0.45, 70)
2018-05-08 18:31:18,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,436 INFO sqlalchemy.engine.base.Engine ('2017-04-16 00:00:00.000000', 0.49, 69)

2018-05-08 18:31:18,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,438 INFO sqlalchemy.engine.base.Engine ('2017-04-17 00:00:00.000000', 0.41, 69)
2018-05-08 18:31:18,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,440 INFO sqlalchemy.engine.base.Engine ('2017-04-18 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:18,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,442 INFO sqlalchemy.engine.base.Engine ('2017-04-19 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:18,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,444 INFO sqlalchemy.engine.base.Engine ('2017-04-20 00:00:00.000000', 0.33, 75)
2018-05-08 18:31:18,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,445 INFO sqlalchemy.engine.base.Engine ('2017-04-21 00:00:00.000000', 1.16, 70)
2018-05-08 18:31:18,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,447 INFO sqlalchemy.engine.base.Engine ('2017-04-22 00:00:00.000000', 1.01, 74)
2018-05-08 18:31:18,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,449 INFO sqlalchemy.engine.base.Engine ('2017-04-23 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,451 INFO sqlalchemy.engine.base.Engine ('2017-04-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,452 INFO sqlalchemy.engine.base.Engine ('2017-04-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,455 INFO sqlalchemy.engine.base.Engine ('2017-04-26 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,457 INFO sqlalchemy.engine.base.Engine ('2017-04-27 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:18,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,459 INFO sqlalchemy.engine.base.Engine ('2017-04-28 00:00:00.000000', 2.6, 70)
2018-05-08 18:31:18,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,461 INFO sqlalchemy.engine.base.Engine ('2017-04-29 00:00:00.000000', 0.35, 66)
2018-05-08 18:31:18,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,463 INFO sqlalchemy.engine.base.Engine ('2017-04-30 00:00:00.000000', 1.21, 61)
2018-05-08 18:31:18,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,465 INFO sqlalchemy.engine.base.Engine ('2017-05-01 00:00:00.000000', 0.07, 68)
2018-05-08 18:31:18,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,468 INFO sqlalchemy.engine.base.Engine ('2017-05-02 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:18,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,469 INFO sqlalchemy.engine.base.Engine ('2017-05-03 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:18,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,471 INFO sqlalchemy.engine.base.Engine ('2017-05-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,473 INFO sqlalchemy.engine.base.Engine ('2017-05-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,475 INFO sqlalchemy.engine.base.Engine ('2017-05-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,477 INFO sqlalchemy.engine.base.Engine ('2017-05-07 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:18,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,479 INFO sqlalchemy.engine.base.Engine ('2017-05-08 00:00:00.000000', 0.22, 71)
2018-05-08 18:31:18,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,481 INFO sqlalchemy.engine.base.Engine ('2017-05-09 00:00:00.000000', 1.62, 74)
2018-05-08 18:31:18,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,482 INFO sqlalchemy.engine.base.Engine ('2017-05-10 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:18,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,484 INFO sqlalchemy.engine.base.Engine ('2017-05-11 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:18,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,486 INFO sqlalchemy.engine.base.Engine ('2017-05-12 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:18,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,488 INFO sqlalchemy.engine.base.Engine ('2017-05-13 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,490 INFO sqlalchemy.engine.base.Engine ('2017-05-14 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:18,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,492 INFO sqlalchemy.engine.base.Engine ('2017-05-15 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:18,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,495 INFO sqlalchemy.engine.base.Engine ('2017-05-16 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:18,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,496 INFO sqlalchemy.engine.base.Engine ('2017-05-17 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,498 INFO sqlalchemy.engine.base.Engine ('2017-05-18 00:00:00.000000', 0.09, 70)
2018-05-08 18:31:18,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,500 INFO sqlalchemy.engine.base.Engine ('2017-05-19 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:18,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,501 INFO sqlalchemy.engine.base.Engine ('2017-05-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,503 INFO sqlalchemy.engine.base.Engine ('2017-05-21 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:18,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,505 INFO sqlalchemy.engine.base.Engine ('2017-05-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,507 INFO sqlalchemy.engine.base.Engine ('2017-05-23 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:18,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,508 INFO sqlalchemy.engine.base.Engine ('2017-05-24 00:00:00.000000', 0.58, 75)
2018-05-08 18:31:18,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,511 INFO sqlalchemy.engine.base.Engine ('2017-05-25 00:00:00.000000', 0.37, 69)
2018-05-08 18:31:18,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,513 INFO sqlalchemy.engine.base.Engine ('2017-05-26 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:18,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,515 INFO sqlalchemy.engine.base.Engine ('2017-05-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,517 INFO sqlalchemy.engine.base.Engine ('2017-05-28 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:18,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,518 INFO sqlalchemy.engine.base.Engine ('2017-05-29 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:18,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,520 INFO sqlalchemy.engine.base.Engine ('2017-05-30 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:18,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,522 INFO sqlalchemy.engine.base.Engine ('2017-05-31 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:18,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,523 INFO sqlalchemy.engine.base.Engine ('2017-06-01 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:18,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,525 INFO sqlalchemy.engine.base.Engine ('2017-06-02 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:18,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,528 INFO sqlalchemy.engine.base.Engine ('2017-06-03 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:18,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,529 INFO sqlalchemy.engine.base.Engine ('2017-06-04 00:00:00.000000', 0.15, 78)
2018-05-08 18:31:18,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,531 INFO sqlalchemy.engine.base.Engine ('2017-06-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,533 INFO sqlalchemy.engine.base.Engine ('2017-06-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,534 INFO sqlalchemy.engine.base.Engine ('2017-06-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,536 INFO sqlalchemy.engine.base.Engine ('2017-06-08 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:18,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,538 INFO sqlalchemy.engine.base.Engine ('2017-06-09 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:18,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,540 INFO sqlalchemy.engine.base.Engine ('2017-06-10 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:18,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,541 INFO sqlalchemy.engine.base.Engine ('2017-06-11 00:00:00.000000', 0.24, 73)
2018-05-08 18:31:18,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,544 INFO sqlalchemy.engine.base.Engine ('2017-06-12 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:18,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,546 INFO sqlalchemy.engine.base.Engine ('2017-06-13 00:00:00.000000', 0.36, 76)
2018-05-08 18:31:18,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,547 INFO sqlalchemy.engine.base.Engine ('2017-06-14 00:00:00.000000', 0.27, 76)
2018-05-08 18:31:18,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,549 INFO sqlalchemy.engine.base.Engine ('2017-06-15 00:00:00.000000', 0.17, 77)
2018-05-08 18:31:18,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,551 INFO sqlalchemy.engine.base.Engine ('2017-06-16 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:18,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,596 INFO sqlalchemy.engine.base.Engine ('2017-06-17 00:00:00.000000', 0.35, 77)
2018-05-08 18:31:18,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,598 INFO sqlalchemy.engine.base.Engine ('2017-06-18 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:18,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,600 INFO sqlalchemy.engine.base.Engine ('2017-06-19 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:18,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,601 INFO sqlalchemy.engine.base.Engine ('2017-06-20 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:18,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,603 INFO sqlalchemy.engine.base.Engine ('2017-06-21 00:00:00.000000', 0.02, 82)
2018-05-08 18:31:18,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,605 INFO sqlalchemy.engine.base.Engine ('2017-06-22 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:18,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,607 INFO sqlalchemy.engine.base.Engine ('2017-06-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,609 INFO sqlalchemy.engine.base.Engine ('2017-06-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,611 INFO sqlalchemy.engine.base.Engine ('2017-06-25 00:00:00.000000', 0.08, 73)

2018-05-08 18:31:18,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,612 INFO sqlalchemy.engine.base.Engine ('2017-06-26 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,614 INFO sqlalchemy.engine.base.Engine ('2017-06-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,616 INFO sqlalchemy.engine.base.Engine ('2017-06-28 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:18,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,617 INFO sqlalchemy.engine.base.Engine ('2017-06-29 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:18,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,619 INFO sqlalchemy.engine.base.Engine ('2017-06-30 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:18,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,621 INFO sqlalchemy.engine.base.Engine ('2017-07-01 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:18,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,623 INFO sqlalchemy.engine.base.Engine ('2017-07-02 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:18,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,625 INFO sqlalchemy.engine.base.Engine ('2017-07-03 00:00:00.000000', 0.13, 77)
2018-05-08 18:31:18,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,627 INFO sqlalchemy.engine.base.Engine ('2017-07-04 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:18,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,629 INFO sqlalchemy.engine.base.Engine ('2017-07-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,631 INFO sqlalchemy.engine.base.Engine ('2017-07-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,633 INFO sqlalchemy.engine.base.Engine ('2017-07-07 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,634 INFO sqlalchemy.engine.base.Engine ('2017-07-08 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:18,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,636 INFO sqlalchemy.engine.base.Engine ('2017-07-09 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:18,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,638 INFO sqlalchemy.engine.base.Engine ('2017-07-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:18,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,641 INFO sqlalchemy.engine.base.Engine ('2017-07-11 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:18,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,644 INFO sqlalchemy.engine.base.Engine ('2017-07-12 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:18,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,645 INFO sqlalchemy.engine.base.Engine ('2017-07-13 00:00:00.000000', 0.33, 76)
2018-05-08 18:31:18,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,647 INFO sqlalchemy.engine.base.Engine ('2017-07-14 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:18,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,649 INFO sqlalchemy.engine.base.Engine ('2017-07-15 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:18,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,651 INFO sqlalchemy.engine.base.Engine ('2017-07-16 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:18,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,653 INFO sqlalchemy.engine.base.Engine ('2017-07-17 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:18,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,654 INFO sqlalchemy.engine.base.Engine ('2017-07-18 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:18,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,656 INFO sqlalchemy.engine.base.Engine ('2017-07-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,658 INFO sqlalchemy.engine.base.Engine ('2017-07-20 00:00:00.000000', 0.12, 78)
2018-05-08 18:31:18,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,660 INFO sqlalchemy.engine.base.Engine ('2017-07-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,662 INFO sqlalchemy.engine.base.Engine ('2017-07-22 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:18,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,664 INFO sqlalchemy.engine.base.Engine ('2017-07-23 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:18,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,666 INFO sqlalchemy.engine.base.Engine ('2017-07-24 00:00:00.000000', 0.58, 78)
2018-05-08 18:31:18,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,667 INFO sqlalchemy.engine.base.Engine ('2017-07-25 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:18,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,669 INFO sqlalchemy.engine.base.Engine ('2017-07-26 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:18,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,671 INFO sqlalchemy.engine.base.Engine ('2017-07-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,672 INFO sqlalchemy.engine.base.Engine ('2017-07-28 00:00:00.000000', 0.13, 77)
2018-05-08 18:31:18,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,674 INFO sqlalchemy.engine.base.Engine ('2017-07-29 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:18,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,677 INFO sqlalchemy.engine.base.Engine ('2017-07-30 00:00:00.000000', 0.0, 78)

2018-05-08 18:31:18,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00513117" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,678 INFO sqlalchemy.engine.base.Engine ('2017-07-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,684 INFO sqlalchemy.engine.base.Engine ('USC00519397', 'WAIKIKI 717.2, HI US', 21.2716, -157.8168, 3.0)
2018-05-08 18:31:18,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,685 INFO sqlalchemy.engine.base.Engine ('USC00513117', 'KANEOHE 838.1, HI US', 21.4234, -157.8015, 14.6)
2018-05-08 18:31:18,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,687 INFO sqlalchemy.engine.base.Engine ('USC00514830', 'KUALOA RANCH HEADQUARTERS 886.9, HI US', 21.5213, -157.8374, 7.0)
2018-05-08 18:31:18,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,689 INFO sqlalchemy.engine.base.Engine ('USC00517948', 'PEARL CITY, HI US', 21.3934, -157.9751, 11.9)
2018-05-08 18:31:18,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,690 INFO sqlalchemy.engine.base.Engine ('USC00518838', 'UPPER WAHIAWA 874.3, HI US', 21.4992, -158.0111, 306.6)
2018-05-08 18:31:18,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,693 INFO sqlalchemy.engine.base.Engine ('USC00519523', 'WAIMANALO EXPERIMENTAL FARM, HI US', 21.33556, -157.71139, 19.5)
2018-05-08 18:31:18,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,695 INFO sqlalchemy.engine.base.Engine ('USC00519281', 'WAIHEE 837.5, HI US', 21.45167, -157.84888999999995, 32.9)
2018-05-08 18:31:18,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,697 INFO sqlalchemy.engine.base.Engine ('USC00511918', 'HONOLULU OBSERVATORY 702.2, HI US', 21.3152, -157.9992, 0.9)
2018-05-08 18:31:18,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "Station" (station, name, latitude, longitude, elevation) VALUES (?, ?, ?, ?, ?)
2018-05-08 18:31:18,698 INFO sqlalchemy.engine.base.Engine ('USC00516128', 'MANOA LYON ARBO 785.2, HI US', 21.3331, -157.8025, 152.4)
2018-05-08 18:31:18,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,707 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,709 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,712 INFO sqlalchemy.engine.base.Engine ('2010-05-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,713 INFO sqlalchemy.engine.base.Engine ('2010-05-07 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:18,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,715 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,717 INFO sqlalchemy.engine.base.Engine ('2010-05-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,718 INFO sqlalchemy.engine.base.Engine ('2010-05-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,720 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,722 INFO sqlalchemy.engine.base.Engine ('2010-05-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,724 INFO sqlalchemy.engine.base.Engine ('2010-05-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,726 INFO sqlalchemy.engine.base.Engine ('2010-05-20 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,728 INFO sqlalchemy.engine.base.Engine ('2010-05-21 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:18,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,729 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,731 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,733 INFO sqlalchemy.engine.base.Engine ('2010-05-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,735 INFO sqlalchemy.engine.base.Engine ('2010-05-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,736 INFO sqlalchemy.engine.base.Engine ('2010-06-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,738 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,740 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:18,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,742 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,744 INFO sqlalchemy.engine.base.Engine ('2010-06-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,746 INFO sqlalchemy.engine.base.Engine ('2010-06-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:18,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,747 INFO sqlalchemy.engine.base.Engine ('2010-06-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:18,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:18,749 INFO sqlalchemy.engine.base.Engine ('2010-06-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,751 INFO sqlalchemy.engine.base.Engine ('2010-06-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,752 INFO sqlalchemy.engine.base.Engine ('2010-06-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,754 INFO sqlalchemy.engine.base.Engine ('2010-06-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,756 INFO sqlalchemy.engine.base.Engine ('2010-06-18 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:18,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,757 INFO sqlalchemy.engine.base.Engine ('2010-06-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,760 INFO sqlalchemy.engine.base.Engine ('2010-06-22 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:18,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,761 INFO sqlalchemy.engine.base.Engine ('2010-06-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,763 INFO sqlalchemy.engine.base.Engine ('2010-06-24 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:18,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,765 INFO sqlalchemy.engine.base.Engine ('2010-06-25 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:18,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,767 INFO sqlalchemy.engine.base.Engine ('2010-06-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,768 INFO sqlalchemy.engine.base.Engine ('2010-06-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,770 INFO sqlalchemy.engine.base.Engine ('2010-06-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,772 INFO sqlalchemy.engine.base.Engine ('2010-07-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,774 INFO sqlalchemy.engine.base.Engine ('2010-07-02 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:18,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,776 INFO sqlalchemy.engine.base.Engine ('2010-07-07 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:18,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,778 INFO sqlalchemy.engine.base.Engine ('2010-07-08 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:18,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,779 INFO sqlalchemy.engine.base.Engine ('2010-07-09 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:18,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,781 INFO sqlalchemy.engine.base.Engine ('2010-07-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,783 INFO sqlalchemy.engine.base.Engine ('2010-07-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,784 INFO sqlalchemy.engine.base.Engine ('2010-07-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,786 INFO sqlalchemy.engine.base.Engine ('2010-07-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,788 INFO sqlalchemy.engine.base.Engine ('2010-07-20 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:18,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,837 INFO sqlalchemy.engine.base.Engine ('2010-07-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,839 INFO sqlalchemy.engine.base.Engine ('2010-07-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,840 INFO sqlalchemy.engine.base.Engine ('2010-07-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,842 INFO sqlalchemy.engine.base.Engine ('2010-08-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,844 INFO sqlalchemy.engine.base.Engine ('2010-08-03 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:18,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,845 INFO sqlalchemy.engine.base.Engine ('2010-08-04 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:18,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,847 INFO sqlalchemy.engine.base.Engine ('2010-08-05 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:18,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,849 INFO sqlalchemy.engine.base.Engine ('2010-08-06 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:18,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,850 INFO sqlalchemy.engine.base.Engine ('2010-08-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,852 INFO sqlalchemy.engine.base.Engine ('2010-08-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:18,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,854 INFO sqlalchemy.engine.base.Engine ('2010-08-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,856 INFO sqlalchemy.engine.base.Engine ('2010-08-12 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:18,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:18,857 INFO sqlalchemy.engine.base.Engine ('2010-08-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,859 INFO sqlalchemy.engine.base.Engine ('2010-08-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,860 INFO sqlalchemy.engine.base.Engine ('2010-08-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,862 INFO sqlalchemy.engine.base.Engine ('2010-08-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,864 INFO sqlalchemy.engine.base.Engine ('2010-08-19 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:18,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,865 INFO sqlalchemy.engine.base.Engine ('2010-08-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,867 INFO sqlalchemy.engine.base.Engine ('2010-08-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,869 INFO sqlalchemy.engine.base.Engine ('2010-08-25 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:18,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,870 INFO sqlalchemy.engine.base.Engine ('2010-08-26 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:18,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,872 INFO sqlalchemy.engine.base.Engine ('2010-08-27 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:18,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,874 INFO sqlalchemy.engine.base.Engine ('2010-08-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,876 INFO sqlalchemy.engine.base.Engine ('2010-08-31 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,877 INFO sqlalchemy.engine.base.Engine ('2010-09-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,879 INFO sqlalchemy.engine.base.Engine ('2010-09-02 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:18,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,881 INFO sqlalchemy.engine.base.Engine ('2010-09-03 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:18,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,882 INFO sqlalchemy.engine.base.Engine ('2010-09-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,884 INFO sqlalchemy.engine.base.Engine ('2010-09-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,886 INFO sqlalchemy.engine.base.Engine ('2010-09-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,889 INFO sqlalchemy.engine.base.Engine ('2010-09-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,890 INFO sqlalchemy.engine.base.Engine ('2010-09-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,892 INFO sqlalchemy.engine.base.Engine ('2010-09-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,894 INFO sqlalchemy.engine.base.Engine ('2010-09-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,895 INFO sqlalchemy.engine.base.Engine ('2010-09-16 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:18,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,897 INFO sqlalchemy.engine.base.Engine ('2010-09-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,899 INFO sqlalchemy.engine.base.Engine ('2010-09-20 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:18,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,900 INFO sqlalchemy.engine.base.Engine ('2010-09-21 00:00:00.000000', 0.26, 77)
2018-05-08 18:31:18,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,902 INFO sqlalchemy.engine.base.Engine ('2010-09-22 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:18,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,904 INFO sqlalchemy.engine.base.Engine ('2010-09-23 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:18,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,909 INFO sqlalchemy.engine.base.Engine ('2010-09-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,911 INFO sqlalchemy.engine.base.Engine ('2010-09-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,913 INFO sqlalchemy.engine.base.Engine ('2010-09-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,915 INFO sqlalchemy.engine.base.Engine ('2010-10-04 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:18,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,917 INFO sqlalchemy.engine.base.Engine ('2010-10-05 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:18,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,918 INFO sqlalchemy.engine.base.Engine ('2010-10-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:18,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,920 INFO sqlalchemy.engine.base.Engine ('2010-10-07 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:18,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:18,924 INFO sqlalchemy.engine.base.Engine ('2010-10-08 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:18,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,926 INFO sqlalchemy.engine.base.Engine ('2010-10-12 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:18,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,927 INFO sqlalchemy.engine.base.Engine ('2010-10-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,929 INFO sqlalchemy.engine.base.Engine ('2010-10-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,931 INFO sqlalchemy.engine.base.Engine ('2010-10-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,933 INFO sqlalchemy.engine.base.Engine ('2010-10-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,936 INFO sqlalchemy.engine.base.Engine ('2010-10-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,937 INFO sqlalchemy.engine.base.Engine ('2010-10-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,940 INFO sqlalchemy.engine.base.Engine ('2010-10-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:18,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,941 INFO sqlalchemy.engine.base.Engine ('2010-10-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,943 INFO sqlalchemy.engine.base.Engine ('2010-10-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,944 INFO sqlalchemy.engine.base.Engine ('2010-10-26 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:18,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,946 INFO sqlalchemy.engine.base.Engine ('2010-10-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:18,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,948 INFO sqlalchemy.engine.base.Engine ('2010-10-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:18,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,950 INFO sqlalchemy.engine.base.Engine ('2010-10-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:18,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,952 INFO sqlalchemy.engine.base.Engine ('2010-11-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,954 INFO sqlalchemy.engine.base.Engine ('2010-11-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,956 INFO sqlalchemy.engine.base.Engine ('2010-11-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:18,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,958 INFO sqlalchemy.engine.base.Engine ('2010-11-09 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:18,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,960 INFO sqlalchemy.engine.base.Engine ('2010-11-10 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:18,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,961 INFO sqlalchemy.engine.base.Engine ('2010-11-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:18,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,963 INFO sqlalchemy.engine.base.Engine ('2010-11-16 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:18,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,965 INFO sqlalchemy.engine.base.Engine ('2010-11-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,966 INFO sqlalchemy.engine.base.Engine ('2010-11-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:18,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,968 INFO sqlalchemy.engine.base.Engine ('2010-11-19 00:00:00.000000', 0.35, 70)
2018-05-08 18:31:18,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,970 INFO sqlalchemy.engine.base.Engine ('2010-11-22 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:18,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,972 INFO sqlalchemy.engine.base.Engine ('2010-11-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,973 INFO sqlalchemy.engine.base.Engine ('2010-11-24 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:18,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,975 INFO sqlalchemy.engine.base.Engine ('2010-11-29 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,977 INFO sqlalchemy.engine.base.Engine ('2010-11-30 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:18,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,979 INFO sqlalchemy.engine.base.Engine ('2010-12-01 00:00:00.000000', 0.7, 72)
2018-05-08 18:31:18,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,980 INFO sqlalchemy.engine.base.Engine ('2010-12-02 00:00:00.000000', 0.26, 75)
2018-05-08 18:31:18,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,982 INFO sqlalchemy.engine.base.Engine ('2010-12-06 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,983 INFO sqlalchemy.engine.base.Engine ('2010-12-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,985 INFO sqlalchemy.engine.base.Engine ('2010-12-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:18,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:18,987 INFO sqlalchemy.engine.base.Engine ('2010-12-09 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:18,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,989 INFO sqlalchemy.engine.base.Engine ('2010-12-10 00:00:00.000000', 1.75, 68)
2018-05-08 18:31:18,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,991 INFO sqlalchemy.engine.base.Engine ('2010-12-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:18,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,993 INFO sqlalchemy.engine.base.Engine ('2010-12-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:18,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,995 INFO sqlalchemy.engine.base.Engine ('2010-12-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:18,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,996 INFO sqlalchemy.engine.base.Engine ('2010-12-16 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:18,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:18,998 INFO sqlalchemy.engine.base.Engine ('2010-12-17 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:18,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,000 INFO sqlalchemy.engine.base.Engine ('2011-01-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,001 INFO sqlalchemy.engine.base.Engine ('2011-01-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,003 INFO sqlalchemy.engine.base.Engine ('2011-01-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,005 INFO sqlalchemy.engine.base.Engine ('2011-01-07 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:19,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,007 INFO sqlalchemy.engine.base.Engine ('2011-01-10 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:19,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,009 INFO sqlalchemy.engine.base.Engine ('2011-01-11 00:00:00.000000', 0.1, 58)
2018-05-08 18:31:19,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,011 INFO sqlalchemy.engine.base.Engine ('2011-01-18 00:00:00.000000', 0.27, 65)
2018-05-08 18:31:19,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,012 INFO sqlalchemy.engine.base.Engine ('2011-01-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,014 INFO sqlalchemy.engine.base.Engine ('2011-01-20 00:00:00.000000', 0.03, 61)
2018-05-08 18:31:19,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,016 INFO sqlalchemy.engine.base.Engine ('2011-01-21 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:19,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,017 INFO sqlalchemy.engine.base.Engine ('2011-01-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,064 INFO sqlalchemy.engine.base.Engine ('2011-01-25 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:19,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,066 INFO sqlalchemy.engine.base.Engine ('2011-01-26 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:19,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,068 INFO sqlalchemy.engine.base.Engine ('2011-01-27 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:19,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,069 INFO sqlalchemy.engine.base.Engine ('2011-01-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,071 INFO sqlalchemy.engine.base.Engine ('2011-01-31 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:19,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,073 INFO sqlalchemy.engine.base.Engine ('2011-02-08 00:00:00.000000', 1.6, 69)
2018-05-08 18:31:19,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,075 INFO sqlalchemy.engine.base.Engine ('2011-02-09 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:19,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,077 INFO sqlalchemy.engine.base.Engine ('2011-02-10 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:19,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,079 INFO sqlalchemy.engine.base.Engine ('2011-02-11 00:00:00.000000', 0.57, 69)
2018-05-08 18:31:19,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,081 INFO sqlalchemy.engine.base.Engine ('2011-02-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,082 INFO sqlalchemy.engine.base.Engine ('2011-02-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,084 INFO sqlalchemy.engine.base.Engine ('2011-02-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,086 INFO sqlalchemy.engine.base.Engine ('2011-02-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,088 INFO sqlalchemy.engine.base.Engine ('2011-03-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,090 INFO sqlalchemy.engine.base.Engine ('2011-03-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,092 INFO sqlalchemy.engine.base.Engine ('2011-04-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,094 INFO sqlalchemy.engine.base.Engine ('2011-04-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,095 INFO sqlalchemy.engine.base.Engine ('2011-04-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,097 INFO sqlalchemy.engine.base.Engine ('2011-04-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,099 INFO sqlalchemy.engine.base.Engine ('2011-04-07 00:00:00.000000', 1.09, 69)
2018-05-08 18:31:19,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,101 INFO sqlalchemy.engine.base.Engine ('2011-04-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,102 INFO sqlalchemy.engine.base.Engine ('2011-04-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,104 INFO sqlalchemy.engine.base.Engine ('2011-04-14 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:19,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,106 INFO sqlalchemy.engine.base.Engine ('2011-04-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,107 INFO sqlalchemy.engine.base.Engine ('2011-04-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,110 INFO sqlalchemy.engine.base.Engine ('2011-04-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,112 INFO sqlalchemy.engine.base.Engine ('2011-04-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,113 INFO sqlalchemy.engine.base.Engine ('2011-04-21 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,115 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,117 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,118 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:19,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,120 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,122 INFO sqlalchemy.engine.base.Engine ('2011-05-04 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:19,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,124 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:19,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,126 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 1.8, 74)
2018-05-08 18:31:19,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,128 INFO sqlalchemy.engine.base.Engine ('2011-05-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,129 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,131 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:19,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,132 INFO sqlalchemy.engine.base.Engine ('2011-05-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,133 INFO sqlalchemy.engine.base.Engine ('2011-05-27 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:19,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,135 INFO sqlalchemy.engine.base.Engine ('2011-05-31 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,137 INFO sqlalchemy.engine.base.Engine ('2011-06-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,138 INFO sqlalchemy.engine.base.Engine ('2011-06-03 00:00:00.000000', 1.71, 65)
2018-05-08 18:31:19,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,140 INFO sqlalchemy.engine.base.Engine ('2011-06-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,141 INFO sqlalchemy.engine.base.Engine ('2011-06-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,143 INFO sqlalchemy.engine.base.Engine ('2011-06-08 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:19,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,145 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,147 INFO sqlalchemy.engine.base.Engine ('2011-06-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,148 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,150 INFO sqlalchemy.engine.base.Engine ('2011-06-21 00:00:00.000000', 0.25, 74)
2018-05-08 18:31:19,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,151 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:19,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,153 INFO sqlalchemy.engine.base.Engine ('2011-06-23 00:00:00.000000', 0.22, 73)
2018-05-08 18:31:19,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,155 INFO sqlalchemy.engine.base.Engine ('2011-06-24 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:19,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,157 INFO sqlalchemy.engine.base.Engine ('2011-06-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,159 INFO sqlalchemy.engine.base.Engine ('2011-07-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,161 INFO sqlalchemy.engine.base.Engine ('2011-07-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,162 INFO sqlalchemy.engine.base.Engine ('2011-07-27 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:19,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,164 INFO sqlalchemy.engine.base.Engine ('2011-07-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,165 INFO sqlalchemy.engine.base.Engine ('2011-08-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,167 INFO sqlalchemy.engine.base.Engine ('2011-08-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,168 INFO sqlalchemy.engine.base.Engine ('2011-08-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,171 INFO sqlalchemy.engine.base.Engine ('2011-08-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,172 INFO sqlalchemy.engine.base.Engine ('2011-08-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,174 INFO sqlalchemy.engine.base.Engine ('2011-08-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,176 INFO sqlalchemy.engine.base.Engine ('2011-08-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,179 INFO sqlalchemy.engine.base.Engine ('2011-08-16 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:19,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,180 INFO sqlalchemy.engine.base.Engine ('2011-08-17 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:19,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,181 INFO sqlalchemy.engine.base.Engine ('2011-08-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,183 INFO sqlalchemy.engine.base.Engine ('2011-08-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,184 INFO sqlalchemy.engine.base.Engine ('2011-09-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,187 INFO sqlalchemy.engine.base.Engine ('2011-09-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,189 INFO sqlalchemy.engine.base.Engine ('2011-09-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,191 INFO sqlalchemy.engine.base.Engine ('2011-09-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,192 INFO sqlalchemy.engine.base.Engine ('2011-09-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,194 INFO sqlalchemy.engine.base.Engine ('2011-09-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,196 INFO sqlalchemy.engine.base.Engine ('2011-09-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,198 INFO sqlalchemy.engine.base.Engine ('2011-09-16 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:19,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,200 INFO sqlalchemy.engine.base.Engine ('2011-09-20 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:19,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,202 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,203 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,205 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,206 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,208 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,210 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,212 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:19,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,214 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:19,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,215 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,217 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,218 INFO sqlalchemy.engine.base.Engine ('2011-10-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,220 INFO sqlalchemy.engine.base.Engine ('2011-10-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,222 INFO sqlalchemy.engine.base.Engine ('2011-10-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,223 INFO sqlalchemy.engine.base.Engine ('2011-10-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,225 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:19,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,227 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,228 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,230 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:19,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,232 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,233 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:19,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,235 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.17, 74)
2018-05-08 18:31:19,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,237 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:19,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,286 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,288 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,290 INFO sqlalchemy.engine.base.Engine ('2011-11-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,292 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,293 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:19,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,295 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:19,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,297 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:19,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,299 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,300 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,302 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:19,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,304 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:19,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,306 INFO sqlalchemy.engine.base.Engine ('2011-12-09 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:19,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,308 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 2.8, 69)
2018-05-08 18:31:19,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,310 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 0.86, 71)
2018-05-08 18:31:19,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,312 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:19,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,314 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,316 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,318 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:19,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,320 INFO sqlalchemy.engine.base.Engine ('2012-01-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:19,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,322 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,323 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:19,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,324 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,326 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,328 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,329 INFO sqlalchemy.engine.base.Engine ('2012-01-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:19,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,331 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,333 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,334 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,336 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.33, 66)
2018-05-08 18:31:19,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,338 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,339 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:19,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,341 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,342 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:19,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,344 INFO sqlalchemy.engine.base.Engine ('2012-02-07 00:00:00.000000', 0.48, 69)
2018-05-08 18:31:19,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,346 INFO sqlalchemy.engine.base.Engine ('2012-02-08 00:00:00.000000', 0.32, 66)
2018-05-08 18:31:19,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,347 INFO sqlalchemy.engine.base.Engine ('2012-02-09 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,349 INFO sqlalchemy.engine.base.Engine ('2012-02-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,351 INFO sqlalchemy.engine.base.Engine ('2012-02-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,353 INFO sqlalchemy.engine.base.Engine ('2012-02-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,355 INFO sqlalchemy.engine.base.Engine ('2012-02-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,356 INFO sqlalchemy.engine.base.Engine ('2012-02-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,358 INFO sqlalchemy.engine.base.Engine ('2012-02-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,359 INFO sqlalchemy.engine.base.Engine ('2012-02-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,361 INFO sqlalchemy.engine.base.Engine ('2012-03-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,363 INFO sqlalchemy.engine.base.Engine ('2012-03-23 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:19,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,364 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,366 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,368 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,370 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:19,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,372 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:19,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,373 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,375 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,376 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,378 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 0.26, 70)
2018-05-08 18:31:19,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,379 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:19,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,381 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,382 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,384 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:19,385 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,385 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,387 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,389 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,391 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,392 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:19,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,394 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,395 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,397 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:19,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,399 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:19,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,400 INFO sqlalchemy.engine.base.Engine ('2012-06-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,402 INFO sqlalchemy.engine.base.Engine ('2012-06-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,404 INFO sqlalchemy.engine.base.Engine ('2012-06-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,406 INFO sqlalchemy.engine.base.Engine ('2012-06-14 00:00:00.000000', 0.25, 78)
2018-05-08 18:31:19,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,408 INFO sqlalchemy.engine.base.Engine ('2012-06-19 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:19,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,409 INFO sqlalchemy.engine.base.Engine ('2012-06-20 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:19,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,411 INFO sqlalchemy.engine.base.Engine ('2012-06-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,412 INFO sqlalchemy.engine.base.Engine ('2012-06-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,413 INFO sqlalchemy.engine.base.Engine ('2012-06-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,415 INFO sqlalchemy.engine.base.Engine ('2012-06-29 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,417 INFO sqlalchemy.engine.base.Engine ('2012-07-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,419 INFO sqlalchemy.engine.base.Engine ('2012-07-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,421 INFO sqlalchemy.engine.base.Engine ('2012-07-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,422 INFO sqlalchemy.engine.base.Engine ('2012-07-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,424 INFO sqlalchemy.engine.base.Engine ('2012-07-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,426 INFO sqlalchemy.engine.base.Engine ('2012-07-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,427 INFO sqlalchemy.engine.base.Engine ('2012-07-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,429 INFO sqlalchemy.engine.base.Engine ('2012-11-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,431 INFO sqlalchemy.engine.base.Engine ('2012-11-07 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:19,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,432 INFO sqlalchemy.engine.base.Engine ('2012-11-19 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:19,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,434 INFO sqlalchemy.engine.base.Engine ('2012-12-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,435 INFO sqlalchemy.engine.base.Engine ('2012-12-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,437 INFO sqlalchemy.engine.base.Engine ('2012-12-05 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:19,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,439 INFO sqlalchemy.engine.base.Engine ('2012-12-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,440 INFO sqlalchemy.engine.base.Engine ('2012-12-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,442 INFO sqlalchemy.engine.base.Engine ('2012-12-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,444 INFO sqlalchemy.engine.base.Engine ('2012-12-13 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:19,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,446 INFO sqlalchemy.engine.base.Engine ('2012-12-14 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:19,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,447 INFO sqlalchemy.engine.base.Engine ('2013-02-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:19,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,449 INFO sqlalchemy.engine.base.Engine ('2013-02-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,450 INFO sqlalchemy.engine.base.Engine ('2013-02-22 00:00:00.000000', 1.5, 70)
2018-05-08 18:31:19,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,452 INFO sqlalchemy.engine.base.Engine ('2013-02-25 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,453 INFO sqlalchemy.engine.base.Engine ('2013-02-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,501 INFO sqlalchemy.engine.base.Engine ('2013-03-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,503 INFO sqlalchemy.engine.base.Engine ('2013-03-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,505 INFO sqlalchemy.engine.base.Engine ('2013-03-06 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,506 INFO sqlalchemy.engine.base.Engine ('2013-03-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,508 INFO sqlalchemy.engine.base.Engine ('2013-03-11 00:00:00.000000', 1.48, 71)
2018-05-08 18:31:19,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,510 INFO sqlalchemy.engine.base.Engine ('2013-03-12 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:19,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,511 INFO sqlalchemy.engine.base.Engine ('2013-03-13 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,513 INFO sqlalchemy.engine.base.Engine ('2013-03-14 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:19,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,514 INFO sqlalchemy.engine.base.Engine ('2013-03-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,516 INFO sqlalchemy.engine.base.Engine ('2013-04-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,517 INFO sqlalchemy.engine.base.Engine ('2013-04-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,518 INFO sqlalchemy.engine.base.Engine ('2013-04-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:19,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,521 INFO sqlalchemy.engine.base.Engine ('2013-04-04 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:19,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,522 INFO sqlalchemy.engine.base.Engine ('2013-04-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,524 INFO sqlalchemy.engine.base.Engine ('2013-04-09 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:19,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,526 INFO sqlalchemy.engine.base.Engine ('2013-04-10 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:19,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,528 INFO sqlalchemy.engine.base.Engine ('2013-04-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,529 INFO sqlalchemy.engine.base.Engine ('2013-04-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,531 INFO sqlalchemy.engine.base.Engine ('2013-04-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,532 INFO sqlalchemy.engine.base.Engine ('2013-04-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,534 INFO sqlalchemy.engine.base.Engine ('2013-04-25 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:19,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,536 INFO sqlalchemy.engine.base.Engine ('2013-04-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,538 INFO sqlalchemy.engine.base.Engine ('2013-05-01 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:19,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,539 INFO sqlalchemy.engine.base.Engine ('2013-05-02 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:19,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,541 INFO sqlalchemy.engine.base.Engine ('2013-05-06 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:19,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,543 INFO sqlalchemy.engine.base.Engine ('2013-05-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,544 INFO sqlalchemy.engine.base.Engine ('2013-05-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,547 INFO sqlalchemy.engine.base.Engine ('2013-05-16 00:00:00.000000', 0.17, 79)
2018-05-08 18:31:19,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,548 INFO sqlalchemy.engine.base.Engine ('2013-05-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,549 INFO sqlalchemy.engine.base.Engine ('2013-05-21 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:19,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,551 INFO sqlalchemy.engine.base.Engine ('2013-05-22 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:19,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,552 INFO sqlalchemy.engine.base.Engine ('2013-05-23 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,554 INFO sqlalchemy.engine.base.Engine ('2013-05-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,556 INFO sqlalchemy.engine.base.Engine ('2013-06-05 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:19,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,558 INFO sqlalchemy.engine.base.Engine ('2013-06-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,560 INFO sqlalchemy.engine.base.Engine ('2013-06-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,561 INFO sqlalchemy.engine.base.Engine ('2013-06-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,563 INFO sqlalchemy.engine.base.Engine ('2013-06-18 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:19,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,564 INFO sqlalchemy.engine.base.Engine ('2013-06-19 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,566 INFO sqlalchemy.engine.base.Engine ('2013-06-20 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:19,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,567 INFO sqlalchemy.engine.base.Engine ('2013-06-21 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:19,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,569 INFO sqlalchemy.engine.base.Engine ('2013-06-27 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:19,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,571 INFO sqlalchemy.engine.base.Engine ('2013-07-01 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:19,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,573 INFO sqlalchemy.engine.base.Engine ('2013-07-02 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:19,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,575 INFO sqlalchemy.engine.base.Engine ('2013-07-03 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:19,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,577 INFO sqlalchemy.engine.base.Engine ('2013-07-12 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:19,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,579 INFO sqlalchemy.engine.base.Engine ('2013-07-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,580 INFO sqlalchemy.engine.base.Engine ('2013-07-17 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:19,581 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,582 INFO sqlalchemy.engine.base.Engine ('2013-07-23 00:00:00.000000', 0.26, 80)
2018-05-08 18:31:19,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,583 INFO sqlalchemy.engine.base.Engine ('2013-07-24 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:19,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,585 INFO sqlalchemy.engine.base.Engine ('2013-07-25 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:19,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,587 INFO sqlalchemy.engine.base.Engine ('2013-08-01 00:00:00.000000', 0.5, 78)
2018-05-08 18:31:19,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,589 INFO sqlalchemy.engine.base.Engine ('2013-08-02 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:19,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,591 INFO sqlalchemy.engine.base.Engine ('2013-08-08 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,593 INFO sqlalchemy.engine.base.Engine ('2013-08-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,595 INFO sqlalchemy.engine.base.Engine ('2013-08-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,596 INFO sqlalchemy.engine.base.Engine ('2013-08-14 00:00:00.000000', 0.04, 79)
2018-05-08 18:31:19,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,598 INFO sqlalchemy.engine.base.Engine ('2013-08-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,599 INFO sqlalchemy.engine.base.Engine ('2013-08-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,601 INFO sqlalchemy.engine.base.Engine ('2013-08-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,602 INFO sqlalchemy.engine.base.Engine ('2013-08-29 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:19,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,603 INFO sqlalchemy.engine.base.Engine ('2013-09-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,605 INFO sqlalchemy.engine.base.Engine ('2013-09-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,607 INFO sqlalchemy.engine.base.Engine ('2013-09-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,609 INFO sqlalchemy.engine.base.Engine ('2013-09-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,611 INFO sqlalchemy.engine.base.Engine ('2013-09-11 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,612 INFO sqlalchemy.engine.base.Engine ('2013-09-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,614 INFO sqlalchemy.engine.base.Engine ('2013-09-13 00:00:00.000000', 0.3, 79)
2018-05-08 18:31:19,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,615 INFO sqlalchemy.engine.base.Engine ('2013-09-20 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,616 INFO sqlalchemy.engine.base.Engine ('2013-09-26 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:19,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,618 INFO sqlalchemy.engine.base.Engine ('2013-09-27 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:19,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,620 INFO sqlalchemy.engine.base.Engine ('2013-10-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,622 INFO sqlalchemy.engine.base.Engine ('2013-10-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,623 INFO sqlalchemy.engine.base.Engine ('2013-10-11 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,625 INFO sqlalchemy.engine.base.Engine ('2013-10-16 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:19,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,627 INFO sqlalchemy.engine.base.Engine ('2013-10-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,628 INFO sqlalchemy.engine.base.Engine ('2013-10-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,630 INFO sqlalchemy.engine.base.Engine ('2013-10-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,631 INFO sqlalchemy.engine.base.Engine ('2013-10-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,633 INFO sqlalchemy.engine.base.Engine ('2013-10-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,635 INFO sqlalchemy.engine.base.Engine ('2013-10-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,636 INFO sqlalchemy.engine.base.Engine ('2013-10-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,638 INFO sqlalchemy.engine.base.Engine ('2013-10-31 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,640 INFO sqlalchemy.engine.base.Engine ('2013-11-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,642 INFO sqlalchemy.engine.base.Engine ('2013-11-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,644 INFO sqlalchemy.engine.base.Engine ('2013-11-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,645 INFO sqlalchemy.engine.base.Engine ('2013-11-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,647 INFO sqlalchemy.engine.base.Engine ('2013-11-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,648 INFO sqlalchemy.engine.base.Engine ('2013-11-15 00:00:00.000000', 0.2, 73)
2018-05-08 18:31:19,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,650 INFO sqlalchemy.engine.base.Engine ('2013-11-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,651 INFO sqlalchemy.engine.base.Engine ('2013-11-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,653 INFO sqlalchemy.engine.base.Engine ('2013-11-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,717 INFO sqlalchemy.engine.base.Engine ('2013-12-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,719 INFO sqlalchemy.engine.base.Engine ('2014-01-03 00:00:00.000000', 0.63, 67)
2018-05-08 18:31:19,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,721 INFO sqlalchemy.engine.base.Engine ('2014-01-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,722 INFO sqlalchemy.engine.base.Engine ('2014-01-08 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,725 INFO sqlalchemy.engine.base.Engine ('2014-01-22 00:00:00.000000', 0.25, 73)
2018-05-08 18:31:19,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,727 INFO sqlalchemy.engine.base.Engine ('2014-01-23 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:19,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,728 INFO sqlalchemy.engine.base.Engine ('2014-01-28 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:19,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,730 INFO sqlalchemy.engine.base.Engine ('2014-01-29 00:00:00.000000', 0.47, 70)
2018-05-08 18:31:19,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,732 INFO sqlalchemy.engine.base.Engine ('2014-01-30 00:00:00.000000', 0.05, 66)
2018-05-08 18:31:19,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,733 INFO sqlalchemy.engine.base.Engine ('2014-02-05 00:00:00.000000', 0.35, 69)
2018-05-08 18:31:19,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,735 INFO sqlalchemy.engine.base.Engine ('2014-02-12 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:19,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,737 INFO sqlalchemy.engine.base.Engine ('2014-02-13 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,739 INFO sqlalchemy.engine.base.Engine ('2014-02-19 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:19,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,741 INFO sqlalchemy.engine.base.Engine ('2014-02-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,743 INFO sqlalchemy.engine.base.Engine ('2014-02-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,745 INFO sqlalchemy.engine.base.Engine ('2014-02-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,746 INFO sqlalchemy.engine.base.Engine ('2014-02-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,748 INFO sqlalchemy.engine.base.Engine ('2014-02-28 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:19,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,750 INFO sqlalchemy.engine.base.Engine ('2014-03-04 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:19,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,751 INFO sqlalchemy.engine.base.Engine ('2014-03-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,753 INFO sqlalchemy.engine.base.Engine ('2014-03-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,755 INFO sqlalchemy.engine.base.Engine ('2014-03-10 00:00:00.000000', 1.65, 73)
2018-05-08 18:31:19,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,757 INFO sqlalchemy.engine.base.Engine ('2014-03-11 00:00:00.000000', 0.78, 70)
2018-05-08 18:31:19,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,759 INFO sqlalchemy.engine.base.Engine ('2014-03-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,761 INFO sqlalchemy.engine.base.Engine ('2014-04-01 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:19,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,763 INFO sqlalchemy.engine.base.Engine ('2014-04-02 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:19,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,764 INFO sqlalchemy.engine.base.Engine ('2014-04-03 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:19,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,766 INFO sqlalchemy.engine.base.Engine ('2014-04-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,768 INFO sqlalchemy.engine.base.Engine ('2014-04-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,769 INFO sqlalchemy.engine.base.Engine ('2014-04-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,772 INFO sqlalchemy.engine.base.Engine ('2014-04-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,774 INFO sqlalchemy.engine.base.Engine ('2014-04-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,776 INFO sqlalchemy.engine.base.Engine ('2014-04-16 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:19,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,778 INFO sqlalchemy.engine.base.Engine ('2014-04-22 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:19,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,780 INFO sqlalchemy.engine.base.Engine ('2014-04-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,781 INFO sqlalchemy.engine.base.Engine ('2014-04-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,783 INFO sqlalchemy.engine.base.Engine ('2014-05-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,785 INFO sqlalchemy.engine.base.Engine ('2014-05-06 00:00:00.000000', 0.72, 76)
2018-05-08 18:31:19,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,786 INFO sqlalchemy.engine.base.Engine ('2014-05-07 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:19,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,788 INFO sqlalchemy.engine.base.Engine ('2014-05-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,790 INFO sqlalchemy.engine.base.Engine ('2014-05-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,792 INFO sqlalchemy.engine.base.Engine ('2014-05-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,794 INFO sqlalchemy.engine.base.Engine ('2014-05-20 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:19,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,796 INFO sqlalchemy.engine.base.Engine ('2014-05-21 00:00:00.000000', 0.26, 77)
2018-05-08 18:31:19,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,797 INFO sqlalchemy.engine.base.Engine ('2014-05-22 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,799 INFO sqlalchemy.engine.base.Engine ('2014-05-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,801 INFO sqlalchemy.engine.base.Engine ('2014-06-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,802 INFO sqlalchemy.engine.base.Engine ('2014-06-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,805 INFO sqlalchemy.engine.base.Engine ('2014-06-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,808 INFO sqlalchemy.engine.base.Engine ('2014-06-17 00:00:00.000000', 0.2, 79)
2018-05-08 18:31:19,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,810 INFO sqlalchemy.engine.base.Engine ('2014-06-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,812 INFO sqlalchemy.engine.base.Engine ('2014-06-19 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:19,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,813 INFO sqlalchemy.engine.base.Engine ('2014-06-20 00:00:00.000000', 0.14, 81)
2018-05-08 18:31:19,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,815 INFO sqlalchemy.engine.base.Engine ('2014-06-27 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,817 INFO sqlalchemy.engine.base.Engine ('2014-07-15 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:19,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,818 INFO sqlalchemy.engine.base.Engine ('2014-07-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,821 INFO sqlalchemy.engine.base.Engine ('2014-07-17 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:19,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,822 INFO sqlalchemy.engine.base.Engine ('2014-07-18 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,824 INFO sqlalchemy.engine.base.Engine ('2014-07-25 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,826 INFO sqlalchemy.engine.base.Engine ('2014-07-29 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,828 INFO sqlalchemy.engine.base.Engine ('2014-07-30 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:19,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,829 INFO sqlalchemy.engine.base.Engine ('2014-08-12 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,831 INFO sqlalchemy.engine.base.Engine ('2014-08-13 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:19,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,833 INFO sqlalchemy.engine.base.Engine ('2014-08-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,835 INFO sqlalchemy.engine.base.Engine ('2014-08-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,837 INFO sqlalchemy.engine.base.Engine ('2014-08-20 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,839 INFO sqlalchemy.engine.base.Engine ('2014-08-21 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:19,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,842 INFO sqlalchemy.engine.base.Engine ('2014-08-22 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,844 INFO sqlalchemy.engine.base.Engine ('2014-08-27 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:19,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,845 INFO sqlalchemy.engine.base.Engine ('2014-09-02 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:19,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,847 INFO sqlalchemy.engine.base.Engine ('2014-09-03 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:19,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,848 INFO sqlalchemy.engine.base.Engine ('2014-09-04 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,850 INFO sqlalchemy.engine.base.Engine ('2014-09-09 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:19,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,852 INFO sqlalchemy.engine.base.Engine ('2014-09-10 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:19,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,854 INFO sqlalchemy.engine.base.Engine ('2014-09-11 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,856 INFO sqlalchemy.engine.base.Engine ('2014-09-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,858 INFO sqlalchemy.engine.base.Engine ('2014-09-18 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:19,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,860 INFO sqlalchemy.engine.base.Engine ('2014-09-19 00:00:00.000000', 0.12, 81)
2018-05-08 18:31:19,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,861 INFO sqlalchemy.engine.base.Engine ('2014-09-22 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,863 INFO sqlalchemy.engine.base.Engine ('2014-09-23 00:00:00.000000', 0.02, 82)
2018-05-08 18:31:19,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,865 INFO sqlalchemy.engine.base.Engine ('2014-09-30 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:19,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,866 INFO sqlalchemy.engine.base.Engine ('2014-10-01 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,868 INFO sqlalchemy.engine.base.Engine ('2014-10-02 00:00:00.000000', 0.05, 81)
2018-05-08 18:31:19,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,870 INFO sqlalchemy.engine.base.Engine ('2014-10-03 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,872 INFO sqlalchemy.engine.base.Engine ('2014-10-17 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:19,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,874 INFO sqlalchemy.engine.base.Engine ('2014-10-21 00:00:00.000000', 0.03, 81)
2018-05-08 18:31:19,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,876 INFO sqlalchemy.engine.base.Engine ('2014-10-22 00:00:00.000000', 0.03, 81)
2018-05-08 18:31:19,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,877 INFO sqlalchemy.engine.base.Engine ('2014-11-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,879 INFO sqlalchemy.engine.base.Engine ('2014-11-19 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:19,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,881 INFO sqlalchemy.engine.base.Engine ('2014-12-01 00:00:00.000000', 0.28, 74)
2018-05-08 18:31:19,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,882 INFO sqlalchemy.engine.base.Engine ('2014-12-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,884 INFO sqlalchemy.engine.base.Engine ('2014-12-03 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:19,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,886 INFO sqlalchemy.engine.base.Engine ('2014-12-04 00:00:00.000000', 0.15, 77)
2018-05-08 18:31:19,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,888 INFO sqlalchemy.engine.base.Engine ('2014-12-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,890 INFO sqlalchemy.engine.base.Engine ('2014-12-11 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:19,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,892 INFO sqlalchemy.engine.base.Engine ('2014-12-15 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:19,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,893 INFO sqlalchemy.engine.base.Engine ('2014-12-22 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:19,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,895 INFO sqlalchemy.engine.base.Engine ('2014-12-23 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:19,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,897 INFO sqlalchemy.engine.base.Engine ('2014-12-24 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:19,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,899 INFO sqlalchemy.engine.base.Engine ('2014-12-26 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,948 INFO sqlalchemy.engine.base.Engine ('2014-12-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:19,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,950 INFO sqlalchemy.engine.base.Engine ('2015-01-06 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:19,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,951 INFO sqlalchemy.engine.base.Engine ('2015-01-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,954 INFO sqlalchemy.engine.base.Engine ('2015-01-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,956 INFO sqlalchemy.engine.base.Engine ('2015-01-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:19,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,958 INFO sqlalchemy.engine.base.Engine ('2015-01-30 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:19,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,960 INFO sqlalchemy.engine.base.Engine ('2015-02-03 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:19,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,961 INFO sqlalchemy.engine.base.Engine ('2015-02-04 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:19,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,963 INFO sqlalchemy.engine.base.Engine ('2015-02-10 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:19,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,965 INFO sqlalchemy.engine.base.Engine ('2015-02-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,966 INFO sqlalchemy.engine.base.Engine ('2015-02-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:19,968 INFO sqlalchemy.engine.base.Engine ('2015-02-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:19,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,970 INFO sqlalchemy.engine.base.Engine ('2015-02-24 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:19,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,972 INFO sqlalchemy.engine.base.Engine ('2015-02-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,974 INFO sqlalchemy.engine.base.Engine ('2015-02-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:19,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,976 INFO sqlalchemy.engine.base.Engine ('2015-03-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:19,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,977 INFO sqlalchemy.engine.base.Engine ('2015-03-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:19,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,979 INFO sqlalchemy.engine.base.Engine ('2015-03-10 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:19,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,981 INFO sqlalchemy.engine.base.Engine ('2015-03-11 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:19,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,982 INFO sqlalchemy.engine.base.Engine ('2015-03-12 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:19,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,984 INFO sqlalchemy.engine.base.Engine ('2015-03-13 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:19,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,985 INFO sqlalchemy.engine.base.Engine ('2015-03-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,987 INFO sqlalchemy.engine.base.Engine ('2015-03-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:19,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,989 INFO sqlalchemy.engine.base.Engine ('2015-03-31 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:19,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,990 INFO sqlalchemy.engine.base.Engine ('2015-06-10 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:19,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,992 INFO sqlalchemy.engine.base.Engine ('2015-06-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:19,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,994 INFO sqlalchemy.engine.base.Engine ('2015-06-16 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,995 INFO sqlalchemy.engine.base.Engine ('2015-06-17 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:19,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,997 INFO sqlalchemy.engine.base.Engine ('2015-06-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:19,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:19,999 INFO sqlalchemy.engine.base.Engine ('2015-06-19 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,000 INFO sqlalchemy.engine.base.Engine ('2015-06-23 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:20,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,002 INFO sqlalchemy.engine.base.Engine ('2015-06-24 00:00:00.000000', 0.09, 79)
2018-05-08 18:31:20,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,003 INFO sqlalchemy.engine.base.Engine ('2015-07-02 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,005 INFO sqlalchemy.engine.base.Engine ('2015-07-09 00:00:00.000000', 0.1, 83)
2018-05-08 18:31:20,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,007 INFO sqlalchemy.engine.base.Engine ('2015-07-14 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:20,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,008 INFO sqlalchemy.engine.base.Engine ('2015-07-15 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:20,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,010 INFO sqlalchemy.engine.base.Engine ('2015-07-16 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:20,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,011 INFO sqlalchemy.engine.base.Engine ('2015-08-07 00:00:00.000000', 0.05, 81)
2018-05-08 18:31:20,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,013 INFO sqlalchemy.engine.base.Engine ('2015-08-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,015 INFO sqlalchemy.engine.base.Engine ('2015-08-11 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,017 INFO sqlalchemy.engine.base.Engine ('2015-08-12 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,018 INFO sqlalchemy.engine.base.Engine ('2015-08-26 00:00:00.000000', 1.5, 80)
2018-05-08 18:31:20,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,020 INFO sqlalchemy.engine.base.Engine ('2015-09-01 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:20,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,022 INFO sqlalchemy.engine.base.Engine ('2015-09-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,023 INFO sqlalchemy.engine.base.Engine ('2015-09-03 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:20,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,025 INFO sqlalchemy.engine.base.Engine ('2015-09-09 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,027 INFO sqlalchemy.engine.base.Engine ('2015-09-10 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:20,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,028 INFO sqlalchemy.engine.base.Engine ('2015-09-11 00:00:00.000000', 0.2, 79)
2018-05-08 18:31:20,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,030 INFO sqlalchemy.engine.base.Engine ('2015-09-16 00:00:00.000000', 0.22, 81)
2018-05-08 18:31:20,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,032 INFO sqlalchemy.engine.base.Engine ('2015-09-17 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,034 INFO sqlalchemy.engine.base.Engine ('2015-09-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,036 INFO sqlalchemy.engine.base.Engine ('2015-11-04 00:00:00.000000', 0.28, 80)
2018-05-08 18:31:20,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,037 INFO sqlalchemy.engine.base.Engine ('2015-11-05 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:20,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,039 INFO sqlalchemy.engine.base.Engine ('2015-12-02 00:00:00.000000', 0.28, 65)
2018-05-08 18:31:20,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,041 INFO sqlalchemy.engine.base.Engine ('2015-12-18 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:20,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,042 INFO sqlalchemy.engine.base.Engine ('2016-01-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,044 INFO sqlalchemy.engine.base.Engine ('2016-02-10 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,046 INFO sqlalchemy.engine.base.Engine ('2016-03-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,047 INFO sqlalchemy.engine.base.Engine ('2016-04-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,049 INFO sqlalchemy.engine.base.Engine ('2016-04-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,050 INFO sqlalchemy.engine.base.Engine ('2016-04-05 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:20,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,052 INFO sqlalchemy.engine.base.Engine ('2016-04-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,054 INFO sqlalchemy.engine.base.Engine ('2016-05-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:20,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,055 INFO sqlalchemy.engine.base.Engine ('2016-05-13 00:00:00.000000', 0.44, 73)
2018-05-08 18:31:20,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,057 INFO sqlalchemy.engine.base.Engine ('2016-06-15 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:20,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,059 INFO sqlalchemy.engine.base.Engine ('2016-06-16 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:20,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,060 INFO sqlalchemy.engine.base.Engine ('2016-06-17 00:00:00.000000', 0.38, 73)
2018-05-08 18:31:20,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,062 INFO sqlalchemy.engine.base.Engine ('2016-06-20 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:20,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,063 INFO sqlalchemy.engine.base.Engine ('2016-07-19 00:00:00.000000', 0.5, 79)
2018-05-08 18:31:20,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,065 INFO sqlalchemy.engine.base.Engine ('2016-07-26 00:00:00.000000', 0.01, 82)
2018-05-08 18:31:20,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,066 INFO sqlalchemy.engine.base.Engine ('2016-08-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,068 INFO sqlalchemy.engine.base.Engine ('2016-08-03 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:20,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,070 INFO sqlalchemy.engine.base.Engine ('2016-08-04 00:00:00.000000', 0.13, 81)
2018-05-08 18:31:20,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,071 INFO sqlalchemy.engine.base.Engine ('2016-08-05 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:20,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,074 INFO sqlalchemy.engine.base.Engine ('2016-08-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,075 INFO sqlalchemy.engine.base.Engine ('2016-08-17 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,077 INFO sqlalchemy.engine.base.Engine ('2016-08-18 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,078 INFO sqlalchemy.engine.base.Engine ('2016-08-25 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,080 INFO sqlalchemy.engine.base.Engine ('2016-08-26 00:00:00.000000', 0.04, 81)
2018-05-08 18:31:20,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,081 INFO sqlalchemy.engine.base.Engine ('2016-08-30 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:20,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,083 INFO sqlalchemy.engine.base.Engine ('2016-09-16 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,085 INFO sqlalchemy.engine.base.Engine ('2016-09-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,086 INFO sqlalchemy.engine.base.Engine ('2016-09-22 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:20,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,088 INFO sqlalchemy.engine.base.Engine ('2016-09-23 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,089 INFO sqlalchemy.engine.base.Engine ('2016-09-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,091 INFO sqlalchemy.engine.base.Engine ('2016-09-29 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:20,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,092 INFO sqlalchemy.engine.base.Engine ('2016-10-06 00:00:00.000000', 0.07, 79)
2018-05-08 18:31:20,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,094 INFO sqlalchemy.engine.base.Engine ('2016-10-25 00:00:00.000000', 0.4, 77)
2018-05-08 18:31:20,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,096 INFO sqlalchemy.engine.base.Engine ('2016-10-26 00:00:00.000000', 0.2, 73)
2018-05-08 18:31:20,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,097 INFO sqlalchemy.engine.base.Engine ('2016-11-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,099 INFO sqlalchemy.engine.base.Engine ('2016-11-14 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:20,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,101 INFO sqlalchemy.engine.base.Engine ('2016-12-08 00:00:00.000000', 0.27, 70)
2018-05-08 18:31:20,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,102 INFO sqlalchemy.engine.base.Engine ('2016-12-12 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:20,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,104 INFO sqlalchemy.engine.base.Engine ('2016-12-21 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:20,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,105 INFO sqlalchemy.engine.base.Engine ('2017-01-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,107 INFO sqlalchemy.engine.base.Engine ('2017-01-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,108 INFO sqlalchemy.engine.base.Engine ('2017-01-26 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,110 INFO sqlalchemy.engine.base.Engine ('2017-01-27 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,112 INFO sqlalchemy.engine.base.Engine ('2017-01-30 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:20,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,113 INFO sqlalchemy.engine.base.Engine ('2017-01-31 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,162 INFO sqlalchemy.engine.base.Engine ('2017-02-01 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:20,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,164 INFO sqlalchemy.engine.base.Engine ('2017-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,165 INFO sqlalchemy.engine.base.Engine ('2017-02-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,167 INFO sqlalchemy.engine.base.Engine ('2017-02-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,168 INFO sqlalchemy.engine.base.Engine ('2017-02-08 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,170 INFO sqlalchemy.engine.base.Engine ('2017-02-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,172 INFO sqlalchemy.engine.base.Engine ('2017-02-10 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,173 INFO sqlalchemy.engine.base.Engine ('2017-02-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,175 INFO sqlalchemy.engine.base.Engine ('2017-02-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,177 INFO sqlalchemy.engine.base.Engine ('2017-02-22 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:20,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,178 INFO sqlalchemy.engine.base.Engine ('2017-02-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,180 INFO sqlalchemy.engine.base.Engine ('2017-02-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,181 INFO sqlalchemy.engine.base.Engine ('2017-03-01 00:00:00.000000', 2.4, 66)
2018-05-08 18:31:20,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,183 INFO sqlalchemy.engine.base.Engine ('2017-03-02 00:00:00.000000', 0.44, 73)
2018-05-08 18:31:20,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,184 INFO sqlalchemy.engine.base.Engine ('2017-03-03 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:20,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,186 INFO sqlalchemy.engine.base.Engine ('2017-03-09 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,187 INFO sqlalchemy.engine.base.Engine ('2017-03-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,189 INFO sqlalchemy.engine.base.Engine ('2017-03-14 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:20,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,191 INFO sqlalchemy.engine.base.Engine ('2017-03-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,192 INFO sqlalchemy.engine.base.Engine ('2017-03-31 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:20,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,194 INFO sqlalchemy.engine.base.Engine ('2017-04-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,195 INFO sqlalchemy.engine.base.Engine ('2017-04-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,197 INFO sqlalchemy.engine.base.Engine ('2017-04-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,199 INFO sqlalchemy.engine.base.Engine ('2017-04-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,200 INFO sqlalchemy.engine.base.Engine ('2017-04-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,202 INFO sqlalchemy.engine.base.Engine ('2017-06-22 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,204 INFO sqlalchemy.engine.base.Engine ('2017-06-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,205 INFO sqlalchemy.engine.base.Engine ('2017-06-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,207 INFO sqlalchemy.engine.base.Engine ('2017-06-28 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,209 INFO sqlalchemy.engine.base.Engine ('2017-06-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,210 INFO sqlalchemy.engine.base.Engine ('2017-06-30 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:20,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,212 INFO sqlalchemy.engine.base.Engine ('2017-07-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:20,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,214 INFO sqlalchemy.engine.base.Engine ('2017-07-19 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,215 INFO sqlalchemy.engine.base.Engine ('2017-07-20 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,217 INFO sqlalchemy.engine.base.Engine ('2017-07-21 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,218 INFO sqlalchemy.engine.base.Engine ('2017-07-25 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00517948" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,220 INFO sqlalchemy.engine.base.Engine ('2017-07-28 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:20,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,247 INFO sqlalchemy.engine.base.Engine ('2010-01-01 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:20,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,249 INFO sqlalchemy.engine.base.Engine ('2010-01-02 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:20,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,251 INFO sqlalchemy.engine.base.Engine ('2010-01-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,252 INFO sqlalchemy.engine.base.Engine ('2010-01-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,254 INFO sqlalchemy.engine.base.Engine ('2010-01-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,256 INFO sqlalchemy.engine.base.Engine ('2010-01-06 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:20,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,258 INFO sqlalchemy.engine.base.Engine ('2010-01-07 00:00:00.000000', 0.17, 69)
2018-05-08 18:31:20,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,259 INFO sqlalchemy.engine.base.Engine ('2010-01-08 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,261 INFO sqlalchemy.engine.base.Engine ('2010-01-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,263 INFO sqlalchemy.engine.base.Engine ('2010-01-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,265 INFO sqlalchemy.engine.base.Engine ('2010-01-11 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:20,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,267 INFO sqlalchemy.engine.base.Engine ('2010-01-12 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:20,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,268 INFO sqlalchemy.engine.base.Engine ('2010-01-13 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:20,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,270 INFO sqlalchemy.engine.base.Engine ('2010-01-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,272 INFO sqlalchemy.engine.base.Engine ('2010-01-15 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,273 INFO sqlalchemy.engine.base.Engine ('2010-01-16 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,275 INFO sqlalchemy.engine.base.Engine ('2010-01-17 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,276 INFO sqlalchemy.engine.base.Engine ('2010-01-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,278 INFO sqlalchemy.engine.base.Engine ('2010-01-19 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,280 INFO sqlalchemy.engine.base.Engine ('2010-01-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,281 INFO sqlalchemy.engine.base.Engine ('2010-01-21 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:20,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,283 INFO sqlalchemy.engine.base.Engine ('2010-01-22 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:20,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,284 INFO sqlalchemy.engine.base.Engine ('2010-01-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,286 INFO sqlalchemy.engine.base.Engine ('2010-01-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,288 INFO sqlalchemy.engine.base.Engine ('2010-01-25 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,289 INFO sqlalchemy.engine.base.Engine ('2010-01-26 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:20,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,291 INFO sqlalchemy.engine.base.Engine ('2010-01-27 00:00:00.000000', 0.31, 69)
2018-05-08 18:31:20,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,292 INFO sqlalchemy.engine.base.Engine ('2010-01-28 00:00:00.000000', 0.37, 67)
2018-05-08 18:31:20,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,294 INFO sqlalchemy.engine.base.Engine ('2010-01-29 00:00:00.000000', 0.75, 66)
2018-05-08 18:31:20,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,296 INFO sqlalchemy.engine.base.Engine ('2010-01-30 00:00:00.000000', 2.17, 69)
2018-05-08 18:31:20,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,298 INFO sqlalchemy.engine.base.Engine ('2010-01-31 00:00:00.000000', 0.69, 72)
2018-05-08 18:31:20,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,299 INFO sqlalchemy.engine.base.Engine ('2010-02-01 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:20,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,301 INFO sqlalchemy.engine.base.Engine ('2010-02-02 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,303 INFO sqlalchemy.engine.base.Engine ('2010-02-03 00:00:00.000000', 0.37, 64)
2018-05-08 18:31:20,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,305 INFO sqlalchemy.engine.base.Engine ('2010-02-04 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,307 INFO sqlalchemy.engine.base.Engine ('2010-02-05 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:20,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,309 INFO sqlalchemy.engine.base.Engine ('2010-02-06 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,311 INFO sqlalchemy.engine.base.Engine ('2010-02-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,312 INFO sqlalchemy.engine.base.Engine ('2010-02-08 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,314 INFO sqlalchemy.engine.base.Engine ('2010-02-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,315 INFO sqlalchemy.engine.base.Engine ('2010-02-10 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:20,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,317 INFO sqlalchemy.engine.base.Engine ('2010-02-11 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,319 INFO sqlalchemy.engine.base.Engine ('2010-02-12 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:20,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,321 INFO sqlalchemy.engine.base.Engine ('2010-02-13 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:20,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,323 INFO sqlalchemy.engine.base.Engine ('2010-02-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,324 INFO sqlalchemy.engine.base.Engine ('2010-02-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,326 INFO sqlalchemy.engine.base.Engine ('2010-02-16 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:20,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,328 INFO sqlalchemy.engine.base.Engine ('2010-02-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,329 INFO sqlalchemy.engine.base.Engine ('2010-02-18 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,331 INFO sqlalchemy.engine.base.Engine ('2010-02-19 00:00:00.000000', 0.02, 62)
2018-05-08 18:31:20,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,332 INFO sqlalchemy.engine.base.Engine ('2010-02-20 00:00:00.000000', 0.57, 65)
2018-05-08 18:31:20,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,334 INFO sqlalchemy.engine.base.Engine ('2010-02-21 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:20,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,336 INFO sqlalchemy.engine.base.Engine ('2010-02-22 00:00:00.000000', 0.22, 63)
2018-05-08 18:31:20,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,337 INFO sqlalchemy.engine.base.Engine ('2010-02-23 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:20,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,339 INFO sqlalchemy.engine.base.Engine ('2010-02-24 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:20,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,341 INFO sqlalchemy.engine.base.Engine ('2010-02-25 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,342 INFO sqlalchemy.engine.base.Engine ('2010-02-26 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:20,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,344 INFO sqlalchemy.engine.base.Engine ('2010-02-27 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,345 INFO sqlalchemy.engine.base.Engine ('2010-02-28 00:00:00.000000', 0.12, 68)
2018-05-08 18:31:20,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,347 INFO sqlalchemy.engine.base.Engine ('2010-03-01 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:20,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,349 INFO sqlalchemy.engine.base.Engine ('2010-03-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,350 INFO sqlalchemy.engine.base.Engine ('2010-03-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,352 INFO sqlalchemy.engine.base.Engine ('2010-03-04 00:00:00.000000', 0.4, 65)
2018-05-08 18:31:20,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,396 INFO sqlalchemy.engine.base.Engine ('2010-03-05 00:00:00.000000', 0.33, 67)
2018-05-08 18:31:20,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,398 INFO sqlalchemy.engine.base.Engine ('2010-03-06 00:00:00.000000', 0.51, 71)
2018-05-08 18:31:20,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,399 INFO sqlalchemy.engine.base.Engine ('2010-03-07 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:20,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,401 INFO sqlalchemy.engine.base.Engine ('2010-03-08 00:00:00.000000', 0.53, 69)
2018-05-08 18:31:20,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,402 INFO sqlalchemy.engine.base.Engine ('2010-03-09 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:20,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,404 INFO sqlalchemy.engine.base.Engine ('2010-03-10 00:00:00.000000', 0.45, 70)
2018-05-08 18:31:20,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,406 INFO sqlalchemy.engine.base.Engine ('2010-03-11 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:20,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,407 INFO sqlalchemy.engine.base.Engine ('2010-03-12 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:20,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,409 INFO sqlalchemy.engine.base.Engine ('2010-03-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,411 INFO sqlalchemy.engine.base.Engine ('2010-03-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,412 INFO sqlalchemy.engine.base.Engine ('2010-03-15 00:00:00.000000', 0.23, 67)
2018-05-08 18:31:20,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,414 INFO sqlalchemy.engine.base.Engine ('2010-03-16 00:00:00.000000', 0.5, 68)
2018-05-08 18:31:20,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,416 INFO sqlalchemy.engine.base.Engine ('2010-03-17 00:00:00.000000', 0.19, 64)
2018-05-08 18:31:20,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,417 INFO sqlalchemy.engine.base.Engine ('2010-03-18 00:00:00.000000', 0.69, 65)
2018-05-08 18:31:20,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,419 INFO sqlalchemy.engine.base.Engine ('2010-03-19 00:00:00.000000', 0.19, 68)
2018-05-08 18:31:20,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,420 INFO sqlalchemy.engine.base.Engine ('2010-03-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,422 INFO sqlalchemy.engine.base.Engine ('2010-03-21 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:20,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,424 INFO sqlalchemy.engine.base.Engine ('2010-03-22 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,425 INFO sqlalchemy.engine.base.Engine ('2010-03-23 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,427 INFO sqlalchemy.engine.base.Engine ('2010-03-24 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:20,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,429 INFO sqlalchemy.engine.base.Engine ('2010-03-25 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:20,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,431 INFO sqlalchemy.engine.base.Engine ('2010-03-26 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:20,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,432 INFO sqlalchemy.engine.base.Engine ('2010-03-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,434 INFO sqlalchemy.engine.base.Engine ('2010-03-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,436 INFO sqlalchemy.engine.base.Engine ('2010-03-29 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:20,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,437 INFO sqlalchemy.engine.base.Engine ('2010-03-30 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:20,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,439 INFO sqlalchemy.engine.base.Engine ('2010-03-31 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,441 INFO sqlalchemy.engine.base.Engine ('2010-04-01 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:20,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,442 INFO sqlalchemy.engine.base.Engine ('2010-04-02 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:20,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,444 INFO sqlalchemy.engine.base.Engine ('2010-04-03 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:20,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,445 INFO sqlalchemy.engine.base.Engine ('2010-04-04 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:20,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,447 INFO sqlalchemy.engine.base.Engine ('2010-04-05 00:00:00.000000', 0.57, 71)
2018-05-08 18:31:20,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,448 INFO sqlalchemy.engine.base.Engine ('2010-04-06 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:20,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,450 INFO sqlalchemy.engine.base.Engine ('2010-04-07 00:00:00.000000', 3.99, 69)
2018-05-08 18:31:20,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,452 INFO sqlalchemy.engine.base.Engine ('2010-04-08 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:20,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,453 INFO sqlalchemy.engine.base.Engine ('2010-04-09 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:20,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,455 INFO sqlalchemy.engine.base.Engine ('2010-04-10 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:20,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,456 INFO sqlalchemy.engine.base.Engine ('2010-04-11 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:20,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,458 INFO sqlalchemy.engine.base.Engine ('2010-04-12 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,460 INFO sqlalchemy.engine.base.Engine ('2010-04-13 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:20,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,461 INFO sqlalchemy.engine.base.Engine ('2010-04-14 00:00:00.000000', 0.14, 65)
2018-05-08 18:31:20,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,463 INFO sqlalchemy.engine.base.Engine ('2010-04-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,464 INFO sqlalchemy.engine.base.Engine ('2010-04-16 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,466 INFO sqlalchemy.engine.base.Engine ('2010-04-17 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:20,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,468 INFO sqlalchemy.engine.base.Engine ('2010-04-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,469 INFO sqlalchemy.engine.base.Engine ('2010-04-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,471 INFO sqlalchemy.engine.base.Engine ('2010-04-20 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:20,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,473 INFO sqlalchemy.engine.base.Engine ('2010-04-21 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:20,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,475 INFO sqlalchemy.engine.base.Engine ('2010-04-22 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:20,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,477 INFO sqlalchemy.engine.base.Engine ('2010-04-23 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:20,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,478 INFO sqlalchemy.engine.base.Engine ('2010-04-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,480 INFO sqlalchemy.engine.base.Engine ('2010-04-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,481 INFO sqlalchemy.engine.base.Engine ('2010-04-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,483 INFO sqlalchemy.engine.base.Engine ('2010-04-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,485 INFO sqlalchemy.engine.base.Engine ('2010-04-28 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:20,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,487 INFO sqlalchemy.engine.base.Engine ('2010-04-29 00:00:00.000000', 0.07, 70)
2018-05-08 18:31:20,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,488 INFO sqlalchemy.engine.base.Engine ('2010-04-30 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:20,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,490 INFO sqlalchemy.engine.base.Engine ('2010-05-01 00:00:00.000000', 0.39, 73)
2018-05-08 18:31:20,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,492 INFO sqlalchemy.engine.base.Engine ('2010-05-02 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:20,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,493 INFO sqlalchemy.engine.base.Engine ('2010-05-03 00:00:00.000000', 1.06, 70)
2018-05-08 18:31:20,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,495 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:20,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,497 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,498 INFO sqlalchemy.engine.base.Engine ('2010-05-06 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:20,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,500 INFO sqlalchemy.engine.base.Engine ('2010-05-07 00:00:00.000000', 0.16, 68)
2018-05-08 18:31:20,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,501 INFO sqlalchemy.engine.base.Engine ('2010-05-08 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:20,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,503 INFO sqlalchemy.engine.base.Engine ('2010-05-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,504 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,506 INFO sqlalchemy.engine.base.Engine ('2010-05-11 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:20,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,508 INFO sqlalchemy.engine.base.Engine ('2010-05-12 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:20,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,509 INFO sqlalchemy.engine.base.Engine ('2010-05-13 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:20,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,511 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,512 INFO sqlalchemy.engine.base.Engine ('2010-05-15 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:20,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,514 INFO sqlalchemy.engine.base.Engine ('2010-05-16 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:20,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,515 INFO sqlalchemy.engine.base.Engine ('2010-05-17 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:20,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,517 INFO sqlalchemy.engine.base.Engine ('2010-05-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,519 INFO sqlalchemy.engine.base.Engine ('2010-05-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,520 INFO sqlalchemy.engine.base.Engine ('2010-05-20 00:00:00.000000', 0.28, 71)
2018-05-08 18:31:20,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,522 INFO sqlalchemy.engine.base.Engine ('2010-05-21 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:20,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,524 INFO sqlalchemy.engine.base.Engine ('2010-05-22 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:20,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,525 INFO sqlalchemy.engine.base.Engine ('2010-05-23 00:00:00.000000', 0.28, 72)
2018-05-08 18:31:20,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,527 INFO sqlalchemy.engine.base.Engine ('2010-05-24 00:00:00.000000', 0.22, 72)
2018-05-08 18:31:20,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,529 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.33, 72)
2018-05-08 18:31:20,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,530 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:20,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,532 INFO sqlalchemy.engine.base.Engine ('2010-05-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,533 INFO sqlalchemy.engine.base.Engine ('2010-05-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,535 INFO sqlalchemy.engine.base.Engine ('2010-05-29 00:00:00.000000', 0.8, 75)
2018-05-08 18:31:20,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,537 INFO sqlalchemy.engine.base.Engine ('2010-05-30 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:20,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,538 INFO sqlalchemy.engine.base.Engine ('2010-05-31 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:20,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,540 INFO sqlalchemy.engine.base.Engine ('2010-06-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,541 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:20,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,543 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,545 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,546 INFO sqlalchemy.engine.base.Engine ('2010-06-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,548 INFO sqlalchemy.engine.base.Engine ('2010-06-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,549 INFO sqlalchemy.engine.base.Engine ('2010-06-07 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:20,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,551 INFO sqlalchemy.engine.base.Engine ('2010-06-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,553 INFO sqlalchemy.engine.base.Engine ('2010-06-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,554 INFO sqlalchemy.engine.base.Engine ('2010-06-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,556 INFO sqlalchemy.engine.base.Engine ('2010-06-11 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:20,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,558 INFO sqlalchemy.engine.base.Engine ('2010-06-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,606 INFO sqlalchemy.engine.base.Engine ('2010-06-13 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:20,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,607 INFO sqlalchemy.engine.base.Engine ('2010-06-14 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:20,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,609 INFO sqlalchemy.engine.base.Engine ('2010-06-15 00:00:00.000000', 0.11, 69)
2018-05-08 18:31:20,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,611 INFO sqlalchemy.engine.base.Engine ('2010-06-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,612 INFO sqlalchemy.engine.base.Engine ('2010-06-17 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:20,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,614 INFO sqlalchemy.engine.base.Engine ('2010-06-18 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:20,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,616 INFO sqlalchemy.engine.base.Engine ('2010-06-19 00:00:00.000000', 0.33, 77)
2018-05-08 18:31:20,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,617 INFO sqlalchemy.engine.base.Engine ('2010-06-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,619 INFO sqlalchemy.engine.base.Engine ('2010-06-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,621 INFO sqlalchemy.engine.base.Engine ('2010-06-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,622 INFO sqlalchemy.engine.base.Engine ('2010-06-23 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:20,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,625 INFO sqlalchemy.engine.base.Engine ('2010-06-24 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:20,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,626 INFO sqlalchemy.engine.base.Engine ('2010-06-25 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:20,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,628 INFO sqlalchemy.engine.base.Engine ('2010-06-26 00:00:00.000000', 0.41, 80)
2018-05-08 18:31:20,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,629 INFO sqlalchemy.engine.base.Engine ('2010-06-27 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:20,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,631 INFO sqlalchemy.engine.base.Engine ('2010-06-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,632 INFO sqlalchemy.engine.base.Engine ('2010-06-29 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:20,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,634 INFO sqlalchemy.engine.base.Engine ('2010-06-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,636 INFO sqlalchemy.engine.base.Engine ('2010-07-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,637 INFO sqlalchemy.engine.base.Engine ('2010-07-02 00:00:00.000000', 0.23, 71)
2018-05-08 18:31:20,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,639 INFO sqlalchemy.engine.base.Engine ('2010-07-03 00:00:00.000000', 0.38, 72)
2018-05-08 18:31:20,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,641 INFO sqlalchemy.engine.base.Engine ('2010-07-04 00:00:00.000000', 0.38, 73)
2018-05-08 18:31:20,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,642 INFO sqlalchemy.engine.base.Engine ('2010-07-05 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:20,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,644 INFO sqlalchemy.engine.base.Engine ('2010-07-06 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:20,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,645 INFO sqlalchemy.engine.base.Engine ('2010-07-07 00:00:00.000000', 0.21, 70)
2018-05-08 18:31:20,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,647 INFO sqlalchemy.engine.base.Engine ('2010-07-08 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:20,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,648 INFO sqlalchemy.engine.base.Engine ('2010-07-09 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:20,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,650 INFO sqlalchemy.engine.base.Engine ('2010-07-10 00:00:00.000000', 0.19, 74)
2018-05-08 18:31:20,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,652 INFO sqlalchemy.engine.base.Engine ('2010-07-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,653 INFO sqlalchemy.engine.base.Engine ('2010-07-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,655 INFO sqlalchemy.engine.base.Engine ('2010-07-13 00:00:00.000000', 0.62, 69)
2018-05-08 18:31:20,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,656 INFO sqlalchemy.engine.base.Engine ('2010-07-14 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:20,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,658 INFO sqlalchemy.engine.base.Engine ('2010-07-15 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:20,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,660 INFO sqlalchemy.engine.base.Engine ('2010-07-16 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:20,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,661 INFO sqlalchemy.engine.base.Engine ('2010-07-17 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:20,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,663 INFO sqlalchemy.engine.base.Engine ('2010-07-18 00:00:00.000000', 0.31, 74)
2018-05-08 18:31:20,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,665 INFO sqlalchemy.engine.base.Engine ('2010-07-19 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:20,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,666 INFO sqlalchemy.engine.base.Engine ('2010-07-20 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:20,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,668 INFO sqlalchemy.engine.base.Engine ('2010-07-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,669 INFO sqlalchemy.engine.base.Engine ('2010-07-22 00:00:00.000000', 0.19, 74)
2018-05-08 18:31:20,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,671 INFO sqlalchemy.engine.base.Engine ('2010-07-23 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:20,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,673 INFO sqlalchemy.engine.base.Engine ('2010-07-24 00:00:00.000000', 0.35, 74)
2018-05-08 18:31:20,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,674 INFO sqlalchemy.engine.base.Engine ('2010-07-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,676 INFO sqlalchemy.engine.base.Engine ('2010-07-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:20,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,677 INFO sqlalchemy.engine.base.Engine ('2010-07-27 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:20,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,679 INFO sqlalchemy.engine.base.Engine ('2010-07-28 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:20,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,680 INFO sqlalchemy.engine.base.Engine ('2010-07-29 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:20,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,682 INFO sqlalchemy.engine.base.Engine ('2010-07-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,684 INFO sqlalchemy.engine.base.Engine ('2010-07-31 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:20,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,686 INFO sqlalchemy.engine.base.Engine ('2010-08-01 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:20,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,687 INFO sqlalchemy.engine.base.Engine ('2010-08-02 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:20,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,689 INFO sqlalchemy.engine.base.Engine ('2010-08-03 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:20,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,691 INFO sqlalchemy.engine.base.Engine ('2010-08-04 00:00:00.000000', 0.28, 74)
2018-05-08 18:31:20,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,693 INFO sqlalchemy.engine.base.Engine ('2010-08-05 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:20,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,694 INFO sqlalchemy.engine.base.Engine ('2010-08-06 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:20,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,696 INFO sqlalchemy.engine.base.Engine ('2010-08-07 00:00:00.000000', 0.17, 78)
2018-05-08 18:31:20,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,697 INFO sqlalchemy.engine.base.Engine ('2010-08-08 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:20,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,699 INFO sqlalchemy.engine.base.Engine ('2010-08-09 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:20,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,701 INFO sqlalchemy.engine.base.Engine ('2010-08-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,702 INFO sqlalchemy.engine.base.Engine ('2010-08-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,704 INFO sqlalchemy.engine.base.Engine ('2010-08-12 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:20,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,706 INFO sqlalchemy.engine.base.Engine ('2010-08-13 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:20,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,708 INFO sqlalchemy.engine.base.Engine ('2010-08-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:20,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,709 INFO sqlalchemy.engine.base.Engine ('2010-08-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,711 INFO sqlalchemy.engine.base.Engine ('2010-08-16 00:00:00.000000', 0.21, 80)
2018-05-08 18:31:20,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,712 INFO sqlalchemy.engine.base.Engine ('2010-08-17 00:00:00.000000', 0.31, 79)
2018-05-08 18:31:20,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,714 INFO sqlalchemy.engine.base.Engine ('2010-08-18 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:20,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,716 INFO sqlalchemy.engine.base.Engine ('2010-08-19 00:00:00.000000', 0.43, 78)
2018-05-08 18:31:20,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,718 INFO sqlalchemy.engine.base.Engine ('2010-08-20 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:20,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,719 INFO sqlalchemy.engine.base.Engine ('2010-08-21 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,721 INFO sqlalchemy.engine.base.Engine ('2010-08-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,722 INFO sqlalchemy.engine.base.Engine ('2010-08-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,724 INFO sqlalchemy.engine.base.Engine ('2010-08-24 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:20,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,725 INFO sqlalchemy.engine.base.Engine ('2010-08-25 00:00:00.000000', 0.19, 74)
2018-05-08 18:31:20,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,727 INFO sqlalchemy.engine.base.Engine ('2010-08-26 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:20,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,729 INFO sqlalchemy.engine.base.Engine ('2010-08-27 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:20,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,730 INFO sqlalchemy.engine.base.Engine ('2010-08-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:20,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,732 INFO sqlalchemy.engine.base.Engine ('2010-08-29 00:00:00.000000', 0.19, 78)
2018-05-08 18:31:20,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,733 INFO sqlalchemy.engine.base.Engine ('2010-08-30 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:20,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,735 INFO sqlalchemy.engine.base.Engine ('2010-08-31 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:20,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,737 INFO sqlalchemy.engine.base.Engine ('2010-09-01 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:20,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,738 INFO sqlalchemy.engine.base.Engine ('2010-09-02 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:20,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,740 INFO sqlalchemy.engine.base.Engine ('2010-09-03 00:00:00.000000', 0.26, 71)
2018-05-08 18:31:20,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,741 INFO sqlalchemy.engine.base.Engine ('2010-09-04 00:00:00.000000', 0.04, 82)
2018-05-08 18:31:20,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,743 INFO sqlalchemy.engine.base.Engine ('2010-09-05 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:20,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,745 INFO sqlalchemy.engine.base.Engine ('2010-09-06 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:20,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,746 INFO sqlalchemy.engine.base.Engine ('2010-09-07 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:20,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,748 INFO sqlalchemy.engine.base.Engine ('2010-09-08 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:20,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,749 INFO sqlalchemy.engine.base.Engine ('2010-09-09 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:20,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,751 INFO sqlalchemy.engine.base.Engine ('2010-09-10 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:20,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,752 INFO sqlalchemy.engine.base.Engine ('2010-09-11 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:20,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,754 INFO sqlalchemy.engine.base.Engine ('2010-09-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,755 INFO sqlalchemy.engine.base.Engine ('2010-09-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:20,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,757 INFO sqlalchemy.engine.base.Engine ('2010-09-14 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:20,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,759 INFO sqlalchemy.engine.base.Engine ('2010-09-15 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:20,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,761 INFO sqlalchemy.engine.base.Engine ('2010-09-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,762 INFO sqlalchemy.engine.base.Engine ('2010-09-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,764 INFO sqlalchemy.engine.base.Engine ('2010-09-18 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:20,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,765 INFO sqlalchemy.engine.base.Engine ('2010-09-19 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:20,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,767 INFO sqlalchemy.engine.base.Engine ('2010-09-20 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:20,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,820 INFO sqlalchemy.engine.base.Engine ('2010-09-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,822 INFO sqlalchemy.engine.base.Engine ('2010-09-22 00:00:00.000000', 0.39, 74)
2018-05-08 18:31:20,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,823 INFO sqlalchemy.engine.base.Engine ('2010-09-23 00:00:00.000000', 0.89, 70)
2018-05-08 18:31:20,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,825 INFO sqlalchemy.engine.base.Engine ('2010-09-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,827 INFO sqlalchemy.engine.base.Engine ('2010-09-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,828 INFO sqlalchemy.engine.base.Engine ('2010-09-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,830 INFO sqlalchemy.engine.base.Engine ('2010-09-27 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:20,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,831 INFO sqlalchemy.engine.base.Engine ('2010-09-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,833 INFO sqlalchemy.engine.base.Engine ('2010-09-29 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,835 INFO sqlalchemy.engine.base.Engine ('2010-09-30 00:00:00.000000', 0.44, 68)
2018-05-08 18:31:20,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,836 INFO sqlalchemy.engine.base.Engine ('2010-10-01 00:00:00.000000', 0.77, 71)
2018-05-08 18:31:20,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,838 INFO sqlalchemy.engine.base.Engine ('2010-10-02 00:00:00.000000', 1.15, 74)
2018-05-08 18:31:20,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,839 INFO sqlalchemy.engine.base.Engine ('2010-10-03 00:00:00.000000', 0.09, 78)
2018-05-08 18:31:20,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,841 INFO sqlalchemy.engine.base.Engine ('2010-10-04 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:20,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,843 INFO sqlalchemy.engine.base.Engine ('2010-10-05 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:20,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,844 INFO sqlalchemy.engine.base.Engine ('2010-10-06 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:20,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,846 INFO sqlalchemy.engine.base.Engine ('2010-10-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,847 INFO sqlalchemy.engine.base.Engine ('2010-10-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:20,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,849 INFO sqlalchemy.engine.base.Engine ('2010-10-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:20,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,851 INFO sqlalchemy.engine.base.Engine ('2010-10-10 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:20,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,852 INFO sqlalchemy.engine.base.Engine ('2010-10-11 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:20,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,854 INFO sqlalchemy.engine.base.Engine ('2010-10-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,855 INFO sqlalchemy.engine.base.Engine ('2010-10-13 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:20,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,857 INFO sqlalchemy.engine.base.Engine ('2010-10-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,859 INFO sqlalchemy.engine.base.Engine ('2010-10-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:20,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,860 INFO sqlalchemy.engine.base.Engine ('2010-10-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,862 INFO sqlalchemy.engine.base.Engine ('2010-10-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,863 INFO sqlalchemy.engine.base.Engine ('2010-10-18 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:20,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,865 INFO sqlalchemy.engine.base.Engine ('2010-10-19 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:20,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,867 INFO sqlalchemy.engine.base.Engine ('2010-10-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:20,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,869 INFO sqlalchemy.engine.base.Engine ('2010-10-21 00:00:00.000000', 1.91, 72)
2018-05-08 18:31:20,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,870 INFO sqlalchemy.engine.base.Engine ('2010-10-22 00:00:00.000000', 1.16, 72)
2018-05-08 18:31:20,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,872 INFO sqlalchemy.engine.base.Engine ('2010-10-23 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:20,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,874 INFO sqlalchemy.engine.base.Engine ('2010-10-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:20,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,875 INFO sqlalchemy.engine.base.Engine ('2010-10-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,877 INFO sqlalchemy.engine.base.Engine ('2010-10-26 00:00:00.000000', 0.27, 74)
2018-05-08 18:31:20,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,879 INFO sqlalchemy.engine.base.Engine ('2010-10-27 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:20,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,880 INFO sqlalchemy.engine.base.Engine ('2010-10-28 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:20,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,882 INFO sqlalchemy.engine.base.Engine ('2010-10-29 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:20,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,883 INFO sqlalchemy.engine.base.Engine ('2010-10-30 00:00:00.000000', 0.41, 74)
2018-05-08 18:31:20,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,885 INFO sqlalchemy.engine.base.Engine ('2010-10-31 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:20,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,887 INFO sqlalchemy.engine.base.Engine ('2010-11-01 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:20,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,888 INFO sqlalchemy.engine.base.Engine ('2010-11-03 00:00:00.000000', 1.13, 69)
2018-05-08 18:31:20,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,890 INFO sqlalchemy.engine.base.Engine ('2010-11-04 00:00:00.000000', 1.21, 70)
2018-05-08 18:31:20,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,891 INFO sqlalchemy.engine.base.Engine ('2010-11-05 00:00:00.000000', 0.57, 73)
2018-05-08 18:31:20,892 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,893 INFO sqlalchemy.engine.base.Engine ('2010-11-06 00:00:00.000000', 0.61, 73)
2018-05-08 18:31:20,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,894 INFO sqlalchemy.engine.base.Engine ('2010-11-07 00:00:00.000000', 0.47, 76)
2018-05-08 18:31:20,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,896 INFO sqlalchemy.engine.base.Engine ('2010-11-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,898 INFO sqlalchemy.engine.base.Engine ('2010-11-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,899 INFO sqlalchemy.engine.base.Engine ('2010-11-10 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:20,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,901 INFO sqlalchemy.engine.base.Engine ('2010-11-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:20,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,903 INFO sqlalchemy.engine.base.Engine ('2010-11-12 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:20,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,904 INFO sqlalchemy.engine.base.Engine ('2010-11-13 00:00:00.000000', 0.18, 74)
2018-05-08 18:31:20,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,906 INFO sqlalchemy.engine.base.Engine ('2010-11-14 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:20,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,907 INFO sqlalchemy.engine.base.Engine ('2010-11-15 00:00:00.000000', 0.85, 74)
2018-05-08 18:31:20,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,909 INFO sqlalchemy.engine.base.Engine ('2010-11-16 00:00:00.000000', 0.13, 68)
2018-05-08 18:31:20,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,911 INFO sqlalchemy.engine.base.Engine ('2010-11-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:20,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,913 INFO sqlalchemy.engine.base.Engine ('2010-11-18 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,915 INFO sqlalchemy.engine.base.Engine ('2010-11-19 00:00:00.000000', 0.19, 73)
2018-05-08 18:31:20,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,916 INFO sqlalchemy.engine.base.Engine ('2010-11-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,918 INFO sqlalchemy.engine.base.Engine ('2010-11-21 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:20,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,920 INFO sqlalchemy.engine.base.Engine ('2010-11-22 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:20,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,921 INFO sqlalchemy.engine.base.Engine ('2010-11-23 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,924 INFO sqlalchemy.engine.base.Engine ('2010-11-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:20,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,925 INFO sqlalchemy.engine.base.Engine ('2010-11-25 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:20,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,927 INFO sqlalchemy.engine.base.Engine ('2010-11-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:20,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:20,929 INFO sqlalchemy.engine.base.Engine ('2010-11-27 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:20,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,931 INFO sqlalchemy.engine.base.Engine ('2010-11-28 00:00:00.000000', 0.43, 72)
2018-05-08 18:31:20,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,932 INFO sqlalchemy.engine.base.Engine ('2010-11-29 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:20,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,934 INFO sqlalchemy.engine.base.Engine ('2010-11-30 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:20,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,936 INFO sqlalchemy.engine.base.Engine ('2010-12-01 00:00:00.000000', 1.35, 72)
2018-05-08 18:31:20,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,937 INFO sqlalchemy.engine.base.Engine ('2010-12-02 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:20,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,939 INFO sqlalchemy.engine.base.Engine ('2010-12-03 00:00:00.000000', 0.47, 72)
2018-05-08 18:31:20,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,941 INFO sqlalchemy.engine.base.Engine ('2010-12-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:20,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,942 INFO sqlalchemy.engine.base.Engine ('2010-12-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:20,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,944 INFO sqlalchemy.engine.base.Engine ('2010-12-06 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:20,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,945 INFO sqlalchemy.engine.base.Engine ('2010-12-07 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:20,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,947 INFO sqlalchemy.engine.base.Engine ('2010-12-08 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:20,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,948 INFO sqlalchemy.engine.base.Engine ('2010-12-09 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:20,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,950 INFO sqlalchemy.engine.base.Engine ('2010-12-10 00:00:00.000000', 1.72, 65)
2018-05-08 18:31:20,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,951 INFO sqlalchemy.engine.base.Engine ('2010-12-11 00:00:00.000000', 0.89, 72)
2018-05-08 18:31:20,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,953 INFO sqlalchemy.engine.base.Engine ('2010-12-12 00:00:00.000000', 0.31, 70)
2018-05-08 18:31:20,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,954 INFO sqlalchemy.engine.base.Engine ('2010-12-13 00:00:00.000000', 0.22, 68)
2018-05-08 18:31:20,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,956 INFO sqlalchemy.engine.base.Engine ('2010-12-14 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:20,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,957 INFO sqlalchemy.engine.base.Engine ('2010-12-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:20,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,959 INFO sqlalchemy.engine.base.Engine ('2010-12-16 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,960 INFO sqlalchemy.engine.base.Engine ('2010-12-17 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:20,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,962 INFO sqlalchemy.engine.base.Engine ('2010-12-18 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:20,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,963 INFO sqlalchemy.engine.base.Engine ('2010-12-19 00:00:00.000000', 2.77, 69)
2018-05-08 18:31:20,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,965 INFO sqlalchemy.engine.base.Engine ('2010-12-20 00:00:00.000000', 3.06, 70)
2018-05-08 18:31:20,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,966 INFO sqlalchemy.engine.base.Engine ('2010-12-21 00:00:00.000000', 0.71, 70)
2018-05-08 18:31:20,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,968 INFO sqlalchemy.engine.base.Engine ('2010-12-22 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:20,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,970 INFO sqlalchemy.engine.base.Engine ('2010-12-23 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:20,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,971 INFO sqlalchemy.engine.base.Engine ('2010-12-24 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:20,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,973 INFO sqlalchemy.engine.base.Engine ('2010-12-25 00:00:00.000000', 3.14, 70)
2018-05-08 18:31:20,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,975 INFO sqlalchemy.engine.base.Engine ('2010-12-26 00:00:00.000000', 2.49, 71)
2018-05-08 18:31:20,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,976 INFO sqlalchemy.engine.base.Engine ('2010-12-27 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:20,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,978 INFO sqlalchemy.engine.base.Engine ('2010-12-28 00:00:00.000000', 0.58, 71)
2018-05-08 18:31:20,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,979 INFO sqlalchemy.engine.base.Engine ('2010-12-29 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:20,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:20,981 INFO sqlalchemy.engine.base.Engine ('2010-12-30 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:20,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,033 INFO sqlalchemy.engine.base.Engine ('2010-12-31 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:21,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,034 INFO sqlalchemy.engine.base.Engine ('2011-01-01 00:00:00.000000', 0.38, 77)
2018-05-08 18:31:21,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,036 INFO sqlalchemy.engine.base.Engine ('2011-01-02 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,037 INFO sqlalchemy.engine.base.Engine ('2011-01-03 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:21,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,039 INFO sqlalchemy.engine.base.Engine ('2011-01-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,041 INFO sqlalchemy.engine.base.Engine ('2011-01-05 00:00:00.000000', 0.08, 65)
2018-05-08 18:31:21,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,042 INFO sqlalchemy.engine.base.Engine ('2011-01-06 00:00:00.000000', 0.16, 67)
2018-05-08 18:31:21,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,044 INFO sqlalchemy.engine.base.Engine ('2011-01-07 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:21,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,045 INFO sqlalchemy.engine.base.Engine ('2011-01-08 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:21,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,047 INFO sqlalchemy.engine.base.Engine ('2011-01-09 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:21,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,048 INFO sqlalchemy.engine.base.Engine ('2011-01-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,050 INFO sqlalchemy.engine.base.Engine ('2011-01-11 00:00:00.000000', 0.34, 57)
2018-05-08 18:31:21,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,051 INFO sqlalchemy.engine.base.Engine ('2011-01-12 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:21,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,053 INFO sqlalchemy.engine.base.Engine ('2011-01-13 00:00:00.000000', 8.81, 68)
2018-05-08 18:31:21,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,054 INFO sqlalchemy.engine.base.Engine ('2011-01-14 00:00:00.000000', 0.55, 75)
2018-05-08 18:31:21,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,056 INFO sqlalchemy.engine.base.Engine ('2011-01-15 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:21,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,057 INFO sqlalchemy.engine.base.Engine ('2011-01-16 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,059 INFO sqlalchemy.engine.base.Engine ('2011-01-17 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:21,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,060 INFO sqlalchemy.engine.base.Engine ('2011-01-18 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:21,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,062 INFO sqlalchemy.engine.base.Engine ('2011-01-19 00:00:00.000000', 0.07, 64)
2018-05-08 18:31:21,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,063 INFO sqlalchemy.engine.base.Engine ('2011-01-20 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:21,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,064 INFO sqlalchemy.engine.base.Engine ('2011-01-21 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:21,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,066 INFO sqlalchemy.engine.base.Engine ('2011-01-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:21,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,068 INFO sqlalchemy.engine.base.Engine ('2011-01-23 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,069 INFO sqlalchemy.engine.base.Engine ('2011-01-24 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,071 INFO sqlalchemy.engine.base.Engine ('2011-01-25 00:00:00.000000', 0.03, 62)
2018-05-08 18:31:21,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,072 INFO sqlalchemy.engine.base.Engine ('2011-01-26 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,074 INFO sqlalchemy.engine.base.Engine ('2011-01-27 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:21,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,075 INFO sqlalchemy.engine.base.Engine ('2011-01-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,077 INFO sqlalchemy.engine.base.Engine ('2011-01-29 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:21,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,078 INFO sqlalchemy.engine.base.Engine ('2011-01-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:21,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,080 INFO sqlalchemy.engine.base.Engine ('2011-01-31 00:00:00.000000', 0.07, 60)
2018-05-08 18:31:21,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,081 INFO sqlalchemy.engine.base.Engine ('2011-02-01 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:21,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,083 INFO sqlalchemy.engine.base.Engine ('2011-02-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,084 INFO sqlalchemy.engine.base.Engine ('2011-02-03 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,085 INFO sqlalchemy.engine.base.Engine ('2011-02-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:21,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,087 INFO sqlalchemy.engine.base.Engine ('2011-02-05 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:21,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,089 INFO sqlalchemy.engine.base.Engine ('2011-02-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:21,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,090 INFO sqlalchemy.engine.base.Engine ('2011-02-07 00:00:00.000000', 1.33, 67)
2018-05-08 18:31:21,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,091 INFO sqlalchemy.engine.base.Engine ('2011-02-08 00:00:00.000000', 1.43, 70)
2018-05-08 18:31:21,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,093 INFO sqlalchemy.engine.base.Engine ('2011-02-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,095 INFO sqlalchemy.engine.base.Engine ('2011-02-10 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,096 INFO sqlalchemy.engine.base.Engine ('2011-02-11 00:00:00.000000', 0.98, 71)
2018-05-08 18:31:21,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,097 INFO sqlalchemy.engine.base.Engine ('2011-02-12 00:00:00.000000', 0.98, 68)
2018-05-08 18:31:21,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,099 INFO sqlalchemy.engine.base.Engine ('2011-02-13 00:00:00.000000', 1.47, 72)
2018-05-08 18:31:21,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,100 INFO sqlalchemy.engine.base.Engine ('2011-02-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,102 INFO sqlalchemy.engine.base.Engine ('2011-02-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,103 INFO sqlalchemy.engine.base.Engine ('2011-02-16 00:00:00.000000', 0.84, 73)
2018-05-08 18:31:21,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,105 INFO sqlalchemy.engine.base.Engine ('2011-02-17 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:21,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,107 INFO sqlalchemy.engine.base.Engine ('2011-02-18 00:00:00.000000', 0.53, 74)
2018-05-08 18:31:21,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,108 INFO sqlalchemy.engine.base.Engine ('2011-02-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,110 INFO sqlalchemy.engine.base.Engine ('2011-02-20 00:00:00.000000', 2.69, 73)
2018-05-08 18:31:21,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,111 INFO sqlalchemy.engine.base.Engine ('2011-02-21 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:21,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,112 INFO sqlalchemy.engine.base.Engine ('2011-02-22 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:21,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,114 INFO sqlalchemy.engine.base.Engine ('2011-02-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,115 INFO sqlalchemy.engine.base.Engine ('2011-02-24 00:00:00.000000', 1.06, 67)
2018-05-08 18:31:21,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,117 INFO sqlalchemy.engine.base.Engine ('2011-02-25 00:00:00.000000', 0.03, 63)
2018-05-08 18:31:21,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,119 INFO sqlalchemy.engine.base.Engine ('2011-02-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,121 INFO sqlalchemy.engine.base.Engine ('2011-02-27 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:21,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,122 INFO sqlalchemy.engine.base.Engine ('2011-02-28 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,124 INFO sqlalchemy.engine.base.Engine ('2011-03-01 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:21,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,125 INFO sqlalchemy.engine.base.Engine ('2011-03-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,127 INFO sqlalchemy.engine.base.Engine ('2011-03-03 00:00:00.000000', 0.69, 69)
2018-05-08 18:31:21,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,128 INFO sqlalchemy.engine.base.Engine ('2011-03-04 00:00:00.000000', 1.25, 70)
2018-05-08 18:31:21,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,130 INFO sqlalchemy.engine.base.Engine ('2011-03-05 00:00:00.000000', 0.26, 67)
2018-05-08 18:31:21,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,131 INFO sqlalchemy.engine.base.Engine ('2011-03-06 00:00:00.000000', 1.51, 74)
2018-05-08 18:31:21,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,133 INFO sqlalchemy.engine.base.Engine ('2011-03-07 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:21,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,134 INFO sqlalchemy.engine.base.Engine ('2011-03-08 00:00:00.000000', 0.39, 69)
2018-05-08 18:31:21,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,135 INFO sqlalchemy.engine.base.Engine ('2011-03-09 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,137 INFO sqlalchemy.engine.base.Engine ('2011-03-10 00:00:00.000000', 2.39, 70)
2018-05-08 18:31:21,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,138 INFO sqlalchemy.engine.base.Engine ('2011-03-11 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:21,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,140 INFO sqlalchemy.engine.base.Engine ('2011-03-12 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:21,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,141 INFO sqlalchemy.engine.base.Engine ('2011-03-13 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,142 INFO sqlalchemy.engine.base.Engine ('2011-03-14 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:21,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,144 INFO sqlalchemy.engine.base.Engine ('2011-03-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,145 INFO sqlalchemy.engine.base.Engine ('2011-03-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,146 INFO sqlalchemy.engine.base.Engine ('2011-03-17 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:21,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,148 INFO sqlalchemy.engine.base.Engine ('2011-03-18 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:21,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,150 INFO sqlalchemy.engine.base.Engine ('2011-03-19 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:21,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,151 INFO sqlalchemy.engine.base.Engine ('2011-03-20 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:21,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,152 INFO sqlalchemy.engine.base.Engine ('2011-03-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,154 INFO sqlalchemy.engine.base.Engine ('2011-03-22 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:21,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,155 INFO sqlalchemy.engine.base.Engine ('2011-03-23 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:21,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,157 INFO sqlalchemy.engine.base.Engine ('2011-03-24 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:21,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,158 INFO sqlalchemy.engine.base.Engine ('2011-03-25 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:21,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,161 INFO sqlalchemy.engine.base.Engine ('2011-03-26 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:21,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,162 INFO sqlalchemy.engine.base.Engine ('2011-03-27 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:21,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,164 INFO sqlalchemy.engine.base.Engine ('2011-03-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,165 INFO sqlalchemy.engine.base.Engine ('2011-03-29 00:00:00.000000', 0.09, 70)
2018-05-08 18:31:21,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,167 INFO sqlalchemy.engine.base.Engine ('2011-03-30 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:21,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,168 INFO sqlalchemy.engine.base.Engine ('2011-03-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,169 INFO sqlalchemy.engine.base.Engine ('2011-04-01 00:00:00.000000', 0.4, 71)
2018-05-08 18:31:21,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,171 INFO sqlalchemy.engine.base.Engine ('2011-04-02 00:00:00.000000', 0.09, 68)
2018-05-08 18:31:21,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,172 INFO sqlalchemy.engine.base.Engine ('2011-04-03 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:21,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,174 INFO sqlalchemy.engine.base.Engine ('2011-04-04 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,175 INFO sqlalchemy.engine.base.Engine ('2011-04-05 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,177 INFO sqlalchemy.engine.base.Engine ('2011-04-06 00:00:00.000000', 0.25, 68)
2018-05-08 18:31:21,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,178 INFO sqlalchemy.engine.base.Engine ('2011-04-07 00:00:00.000000', 0.95, 66)
2018-05-08 18:31:21,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,180 INFO sqlalchemy.engine.base.Engine ('2011-04-08 00:00:00.000000', 0.5, 67)
2018-05-08 18:31:21,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,182 INFO sqlalchemy.engine.base.Engine ('2011-04-09 00:00:00.000000', 0.32, 76)
2018-05-08 18:31:21,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,217 INFO sqlalchemy.engine.base.Engine ('2011-04-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:21,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,219 INFO sqlalchemy.engine.base.Engine ('2011-04-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,220 INFO sqlalchemy.engine.base.Engine ('2011-04-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,222 INFO sqlalchemy.engine.base.Engine ('2011-04-13 00:00:00.000000', 0.03, 65)
2018-05-08 18:31:21,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,224 INFO sqlalchemy.engine.base.Engine ('2011-04-14 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:21,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,225 INFO sqlalchemy.engine.base.Engine ('2011-04-15 00:00:00.000000', 0.06, 67)
2018-05-08 18:31:21,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,227 INFO sqlalchemy.engine.base.Engine ('2011-04-16 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:21,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,229 INFO sqlalchemy.engine.base.Engine ('2011-04-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:21,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,230 INFO sqlalchemy.engine.base.Engine ('2011-04-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,232 INFO sqlalchemy.engine.base.Engine ('2011-04-19 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,233 INFO sqlalchemy.engine.base.Engine ('2011-04-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,235 INFO sqlalchemy.engine.base.Engine ('2011-04-21 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,236 INFO sqlalchemy.engine.base.Engine ('2011-04-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:21,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,238 INFO sqlalchemy.engine.base.Engine ('2011-04-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,239 INFO sqlalchemy.engine.base.Engine ('2011-04-24 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:21,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,241 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,242 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.15, 69)
2018-05-08 18:31:21,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,244 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:21,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,245 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,247 INFO sqlalchemy.engine.base.Engine ('2011-04-29 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:21,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,248 INFO sqlalchemy.engine.base.Engine ('2011-04-30 00:00:00.000000', 0.41, 68)
2018-05-08 18:31:21,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,250 INFO sqlalchemy.engine.base.Engine ('2011-05-01 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:21,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,251 INFO sqlalchemy.engine.base.Engine ('2011-05-02 00:00:00.000000', 1.58, 70)
2018-05-08 18:31:21,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,253 INFO sqlalchemy.engine.base.Engine ('2011-05-03 00:00:00.000000', 0.4, 69)
2018-05-08 18:31:21,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,254 INFO sqlalchemy.engine.base.Engine ('2011-05-04 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:21,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,256 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:21,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,257 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 0.94, 68)
2018-05-08 18:31:21,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,259 INFO sqlalchemy.engine.base.Engine ('2011-05-07 00:00:00.000000', 1.5, 70)
2018-05-08 18:31:21,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,260 INFO sqlalchemy.engine.base.Engine ('2011-05-08 00:00:00.000000', 3.14, 73)
2018-05-08 18:31:21,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,262 INFO sqlalchemy.engine.base.Engine ('2011-05-09 00:00:00.000000', 1.18, 73)
2018-05-08 18:31:21,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,263 INFO sqlalchemy.engine.base.Engine ('2011-05-10 00:00:00.000000', 0.36, 74)
2018-05-08 18:31:21,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,265 INFO sqlalchemy.engine.base.Engine ('2011-05-11 00:00:00.000000', 1.33, 72)
2018-05-08 18:31:21,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,266 INFO sqlalchemy.engine.base.Engine ('2011-05-12 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:21,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,268 INFO sqlalchemy.engine.base.Engine ('2011-05-13 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:21,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,269 INFO sqlalchemy.engine.base.Engine ('2011-05-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:21,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,272 INFO sqlalchemy.engine.base.Engine ('2011-05-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:21,272 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,273 INFO sqlalchemy.engine.base.Engine ('2011-05-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,275 INFO sqlalchemy.engine.base.Engine ('2011-05-17 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:21,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,276 INFO sqlalchemy.engine.base.Engine ('2011-05-18 00:00:00.000000', 0.64, 69)
2018-05-08 18:31:21,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,278 INFO sqlalchemy.engine.base.Engine ('2011-05-19 00:00:00.000000', 0.11, 67)
2018-05-08 18:31:21,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,279 INFO sqlalchemy.engine.base.Engine ('2011-05-20 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:21,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,281 INFO sqlalchemy.engine.base.Engine ('2011-05-21 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:21,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,282 INFO sqlalchemy.engine.base.Engine ('2011-05-22 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:21,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,284 INFO sqlalchemy.engine.base.Engine ('2011-05-23 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:21,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,285 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,287 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,288 INFO sqlalchemy.engine.base.Engine ('2011-05-26 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:21,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,290 INFO sqlalchemy.engine.base.Engine ('2011-05-27 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:21,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,291 INFO sqlalchemy.engine.base.Engine ('2011-05-28 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:21,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,293 INFO sqlalchemy.engine.base.Engine ('2011-05-29 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:21,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,294 INFO sqlalchemy.engine.base.Engine ('2011-05-30 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:21,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,295 INFO sqlalchemy.engine.base.Engine ('2011-05-31 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,297 INFO sqlalchemy.engine.base.Engine ('2011-06-01 00:00:00.000000', 0.22, 72)
2018-05-08 18:31:21,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,298 INFO sqlalchemy.engine.base.Engine ('2011-06-02 00:00:00.000000', 0.42, 73)
2018-05-08 18:31:21,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,300 INFO sqlalchemy.engine.base.Engine ('2011-06-03 00:00:00.000000', 0.33, 73)
2018-05-08 18:31:21,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,301 INFO sqlalchemy.engine.base.Engine ('2011-06-08 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:21,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,303 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:21,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,305 INFO sqlalchemy.engine.base.Engine ('2011-06-10 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:21,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,308 INFO sqlalchemy.engine.base.Engine ('2011-06-11 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:21,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,309 INFO sqlalchemy.engine.base.Engine ('2011-06-12 00:00:00.000000', 0.32, 82)
2018-05-08 18:31:21,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,311 INFO sqlalchemy.engine.base.Engine ('2011-06-13 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:21,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,313 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:21,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,315 INFO sqlalchemy.engine.base.Engine ('2011-06-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:21,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,316 INFO sqlalchemy.engine.base.Engine ('2011-06-16 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:21,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,318 INFO sqlalchemy.engine.base.Engine ('2011-06-17 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:21,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,320 INFO sqlalchemy.engine.base.Engine ('2011-06-18 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:21,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,321 INFO sqlalchemy.engine.base.Engine ('2011-06-19 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:21,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,323 INFO sqlalchemy.engine.base.Engine ('2011-06-20 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:21,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,324 INFO sqlalchemy.engine.base.Engine ('2011-06-21 00:00:00.000000', 0.57, 72)
2018-05-08 18:31:21,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,326 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 0.61, 72)
2018-05-08 18:31:21,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,327 INFO sqlalchemy.engine.base.Engine ('2011-06-23 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:21,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,329 INFO sqlalchemy.engine.base.Engine ('2011-06-24 00:00:00.000000', 0.81, 74)
2018-05-08 18:31:21,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,330 INFO sqlalchemy.engine.base.Engine ('2011-06-25 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:21,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,331 INFO sqlalchemy.engine.base.Engine ('2011-06-26 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:21,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,333 INFO sqlalchemy.engine.base.Engine ('2011-06-27 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:21,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,334 INFO sqlalchemy.engine.base.Engine ('2011-06-28 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:21,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,336 INFO sqlalchemy.engine.base.Engine ('2011-06-29 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:21,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,338 INFO sqlalchemy.engine.base.Engine ('2011-06-30 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:21,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,339 INFO sqlalchemy.engine.base.Engine ('2011-07-01 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:21,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,340 INFO sqlalchemy.engine.base.Engine ('2011-07-02 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:21,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,342 INFO sqlalchemy.engine.base.Engine ('2011-07-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:21,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,344 INFO sqlalchemy.engine.base.Engine ('2011-07-04 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:21,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,346 INFO sqlalchemy.engine.base.Engine ('2011-07-05 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:21,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,347 INFO sqlalchemy.engine.base.Engine ('2011-07-06 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:21,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,349 INFO sqlalchemy.engine.base.Engine ('2011-07-07 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:21,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,350 INFO sqlalchemy.engine.base.Engine ('2011-07-08 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:21,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,352 INFO sqlalchemy.engine.base.Engine ('2011-07-09 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:21,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,354 INFO sqlalchemy.engine.base.Engine ('2011-07-10 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:21,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,355 INFO sqlalchemy.engine.base.Engine ('2011-07-11 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:21,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,357 INFO sqlalchemy.engine.base.Engine ('2011-07-12 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,359 INFO sqlalchemy.engine.base.Engine ('2011-07-13 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:21,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,360 INFO sqlalchemy.engine.base.Engine ('2011-07-14 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:21,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,361 INFO sqlalchemy.engine.base.Engine ('2011-07-15 00:00:00.000000', 0.22, 72)
2018-05-08 18:31:21,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,363 INFO sqlalchemy.engine.base.Engine ('2011-07-16 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:21,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,364 INFO sqlalchemy.engine.base.Engine ('2011-07-17 00:00:00.000000', 0.17, 77)
2018-05-08 18:31:21,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,366 INFO sqlalchemy.engine.base.Engine ('2011-07-18 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:21,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,367 INFO sqlalchemy.engine.base.Engine ('2011-07-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,369 INFO sqlalchemy.engine.base.Engine ('2011-07-20 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:21,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,370 INFO sqlalchemy.engine.base.Engine ('2011-07-21 00:00:00.000000', 0.28, 73)
2018-05-08 18:31:21,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,372 INFO sqlalchemy.engine.base.Engine ('2011-07-22 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:21,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,419 INFO sqlalchemy.engine.base.Engine ('2011-07-23 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:21,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,421 INFO sqlalchemy.engine.base.Engine ('2011-07-24 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:21,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,422 INFO sqlalchemy.engine.base.Engine ('2011-07-25 00:00:00.000000', 0.24, 69)
2018-05-08 18:31:21,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,423 INFO sqlalchemy.engine.base.Engine ('2011-07-26 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:21,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,425 INFO sqlalchemy.engine.base.Engine ('2011-07-27 00:00:00.000000', 0.25, 73)
2018-05-08 18:31:21,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,426 INFO sqlalchemy.engine.base.Engine ('2011-07-28 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:21,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,428 INFO sqlalchemy.engine.base.Engine ('2011-07-29 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:21,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,429 INFO sqlalchemy.engine.base.Engine ('2011-07-30 00:00:00.000000', 0.85, 77)
2018-05-08 18:31:21,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,431 INFO sqlalchemy.engine.base.Engine ('2011-07-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:21,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,432 INFO sqlalchemy.engine.base.Engine ('2011-08-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,434 INFO sqlalchemy.engine.base.Engine ('2011-08-02 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:21,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,436 INFO sqlalchemy.engine.base.Engine ('2011-08-03 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:21,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,438 INFO sqlalchemy.engine.base.Engine ('2011-08-04 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:21,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,439 INFO sqlalchemy.engine.base.Engine ('2011-08-05 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:21,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,441 INFO sqlalchemy.engine.base.Engine ('2011-08-06 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:21,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,442 INFO sqlalchemy.engine.base.Engine ('2011-08-07 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:21,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,444 INFO sqlalchemy.engine.base.Engine ('2011-08-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:21,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,445 INFO sqlalchemy.engine.base.Engine ('2011-08-09 00:00:00.000000', 0.42, 73)
2018-05-08 18:31:21,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,447 INFO sqlalchemy.engine.base.Engine ('2011-08-10 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:21,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,448 INFO sqlalchemy.engine.base.Engine ('2011-08-11 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:21,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,449 INFO sqlalchemy.engine.base.Engine ('2011-08-12 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:21,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,451 INFO sqlalchemy.engine.base.Engine ('2011-08-13 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:21,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,452 INFO sqlalchemy.engine.base.Engine ('2011-08-14 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:21,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,454 INFO sqlalchemy.engine.base.Engine ('2011-08-15 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:21,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,455 INFO sqlalchemy.engine.base.Engine ('2011-08-16 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:21,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,457 INFO sqlalchemy.engine.base.Engine ('2011-08-17 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:21,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,458 INFO sqlalchemy.engine.base.Engine ('2011-08-18 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:21,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,459 INFO sqlalchemy.engine.base.Engine ('2011-08-19 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:21,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,461 INFO sqlalchemy.engine.base.Engine ('2011-08-20 00:00:00.000000', 0.07, 81)
2018-05-08 18:31:21,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,462 INFO sqlalchemy.engine.base.Engine ('2011-08-21 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:21,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,464 INFO sqlalchemy.engine.base.Engine ('2011-08-22 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:21,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,465 INFO sqlalchemy.engine.base.Engine ('2011-08-23 00:00:00.000000', 0.17, 76)
2018-05-08 18:31:21,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,467 INFO sqlalchemy.engine.base.Engine ('2011-08-24 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:21,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,468 INFO sqlalchemy.engine.base.Engine ('2011-08-25 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:21,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,470 INFO sqlalchemy.engine.base.Engine ('2011-08-26 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:21,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,471 INFO sqlalchemy.engine.base.Engine ('2011-08-27 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:21,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,473 INFO sqlalchemy.engine.base.Engine ('2011-08-28 00:00:00.000000', 0.41, 78)
2018-05-08 18:31:21,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,474 INFO sqlalchemy.engine.base.Engine ('2011-08-29 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:21,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,475 INFO sqlalchemy.engine.base.Engine ('2011-08-30 00:00:00.000000', 0.17, 76)
2018-05-08 18:31:21,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,477 INFO sqlalchemy.engine.base.Engine ('2011-08-31 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:21,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,478 INFO sqlalchemy.engine.base.Engine ('2011-09-01 00:00:00.000000', 0.09, 81)
2018-05-08 18:31:21,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,480 INFO sqlalchemy.engine.base.Engine ('2011-09-02 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:21,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,481 INFO sqlalchemy.engine.base.Engine ('2011-09-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:21,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,483 INFO sqlalchemy.engine.base.Engine ('2011-09-04 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:21,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,484 INFO sqlalchemy.engine.base.Engine ('2011-09-05 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:21,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,486 INFO sqlalchemy.engine.base.Engine ('2011-09-06 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:21,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,487 INFO sqlalchemy.engine.base.Engine ('2011-09-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,489 INFO sqlalchemy.engine.base.Engine ('2011-09-08 00:00:00.000000', 0.08, 68)
2018-05-08 18:31:21,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,490 INFO sqlalchemy.engine.base.Engine ('2011-09-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,492 INFO sqlalchemy.engine.base.Engine ('2011-09-10 00:00:00.000000', 0.36, 70)
2018-05-08 18:31:21,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,494 INFO sqlalchemy.engine.base.Engine ('2011-09-11 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:21,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,495 INFO sqlalchemy.engine.base.Engine ('2011-09-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,497 INFO sqlalchemy.engine.base.Engine ('2011-09-13 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:21,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,498 INFO sqlalchemy.engine.base.Engine ('2011-09-14 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:21,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,500 INFO sqlalchemy.engine.base.Engine ('2011-09-15 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:21,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,502 INFO sqlalchemy.engine.base.Engine ('2011-09-16 00:00:00.000000', 1.25, 74)
2018-05-08 18:31:21,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,503 INFO sqlalchemy.engine.base.Engine ('2011-09-17 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:21,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,505 INFO sqlalchemy.engine.base.Engine ('2011-09-18 00:00:00.000000', 0.42, 76)
2018-05-08 18:31:21,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,507 INFO sqlalchemy.engine.base.Engine ('2011-09-19 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:21,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,508 INFO sqlalchemy.engine.base.Engine ('2011-09-20 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:21,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,510 INFO sqlalchemy.engine.base.Engine ('2011-09-21 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:21,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,512 INFO sqlalchemy.engine.base.Engine ('2011-09-22 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:21,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,513 INFO sqlalchemy.engine.base.Engine ('2011-09-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,515 INFO sqlalchemy.engine.base.Engine ('2011-09-24 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:21,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,516 INFO sqlalchemy.engine.base.Engine ('2011-09-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,517 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,520 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,521 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:21,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,523 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:21,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,525 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:21,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,526 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:21,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,528 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:21,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,529 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:21,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,531 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:21,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,532 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:21,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,534 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:21,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,535 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:21,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,537 INFO sqlalchemy.engine.base.Engine ('2011-10-08 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:21,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,538 INFO sqlalchemy.engine.base.Engine ('2011-10-09 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:21,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,540 INFO sqlalchemy.engine.base.Engine ('2011-10-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,541 INFO sqlalchemy.engine.base.Engine ('2011-10-11 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:21,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,543 INFO sqlalchemy.engine.base.Engine ('2011-10-12 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:21,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,544 INFO sqlalchemy.engine.base.Engine ('2011-10-13 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:21,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,546 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,547 INFO sqlalchemy.engine.base.Engine ('2011-10-15 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:21,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,549 INFO sqlalchemy.engine.base.Engine ('2011-10-16 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:21,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,551 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,552 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:21,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,554 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.38, 67)
2018-05-08 18:31:21,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,555 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:21,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,557 INFO sqlalchemy.engine.base.Engine ('2011-10-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,558 INFO sqlalchemy.engine.base.Engine ('2011-10-22 00:00:00.000000', 0.34, 71)
2018-05-08 18:31:21,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,560 INFO sqlalchemy.engine.base.Engine ('2011-10-23 00:00:00.000000', 1.48, 72)
2018-05-08 18:31:21,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,562 INFO sqlalchemy.engine.base.Engine ('2011-10-24 00:00:00.000000', 2.4, 69)
2018-05-08 18:31:21,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,563 INFO sqlalchemy.engine.base.Engine ('2011-10-25 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:21,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,565 INFO sqlalchemy.engine.base.Engine ('2011-10-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,566 INFO sqlalchemy.engine.base.Engine ('2011-10-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,567 INFO sqlalchemy.engine.base.Engine ('2011-10-28 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:21,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,569 INFO sqlalchemy.engine.base.Engine ('2011-10-29 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:21,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,571 INFO sqlalchemy.engine.base.Engine ('2011-10-30 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:21,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,609 INFO sqlalchemy.engine.base.Engine ('2011-10-31 00:00:00.000000', 0.55, 69)
2018-05-08 18:31:21,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,611 INFO sqlalchemy.engine.base.Engine ('2011-11-01 00:00:00.000000', 1.68, 75)
2018-05-08 18:31:21,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,613 INFO sqlalchemy.engine.base.Engine ('2011-11-02 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:21,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,614 INFO sqlalchemy.engine.base.Engine ('2011-11-03 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:21,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,616 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 1.27, 71)
2018-05-08 18:31:21,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,618 INFO sqlalchemy.engine.base.Engine ('2011-11-05 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:21,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,619 INFO sqlalchemy.engine.base.Engine ('2011-11-06 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:21,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,621 INFO sqlalchemy.engine.base.Engine ('2011-11-07 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:21,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,622 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:21,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,624 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:21,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,626 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,627 INFO sqlalchemy.engine.base.Engine ('2011-11-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,629 INFO sqlalchemy.engine.base.Engine ('2011-11-12 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:21,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,630 INFO sqlalchemy.engine.base.Engine ('2011-11-13 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:21,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,632 INFO sqlalchemy.engine.base.Engine ('2011-11-14 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:21,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,634 INFO sqlalchemy.engine.base.Engine ('2011-11-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,635 INFO sqlalchemy.engine.base.Engine ('2011-11-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,637 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,639 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:21,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,640 INFO sqlalchemy.engine.base.Engine ('2011-11-19 00:00:00.000000', 0.26, 74)
2018-05-08 18:31:21,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,642 INFO sqlalchemy.engine.base.Engine ('2011-11-20 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:21,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,643 INFO sqlalchemy.engine.base.Engine ('2011-11-21 00:00:00.000000', 0.22, 71)
2018-05-08 18:31:21,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,645 INFO sqlalchemy.engine.base.Engine ('2011-11-22 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:21,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,646 INFO sqlalchemy.engine.base.Engine ('2011-11-23 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:21,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,648 INFO sqlalchemy.engine.base.Engine ('2011-11-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,650 INFO sqlalchemy.engine.base.Engine ('2011-11-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,651 INFO sqlalchemy.engine.base.Engine ('2011-11-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,653 INFO sqlalchemy.engine.base.Engine ('2011-11-27 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,654 INFO sqlalchemy.engine.base.Engine ('2011-11-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,656 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:21,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,658 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.54, 68)
2018-05-08 18:31:21,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,659 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.05, 67)
2018-05-08 18:31:21,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,661 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.29, 69)
2018-05-08 18:31:21,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,662 INFO sqlalchemy.engine.base.Engine ('2011-12-03 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:21,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,664 INFO sqlalchemy.engine.base.Engine ('2011-12-04 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:21,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,666 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,667 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,669 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:21,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,670 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,672 INFO sqlalchemy.engine.base.Engine ('2011-12-09 00:00:00.000000', 0.1, 66)
2018-05-08 18:31:21,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,673 INFO sqlalchemy.engine.base.Engine ('2011-12-10 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:21,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,675 INFO sqlalchemy.engine.base.Engine ('2011-12-11 00:00:00.000000', 1.16, 70)
2018-05-08 18:31:21,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,677 INFO sqlalchemy.engine.base.Engine ('2011-12-12 00:00:00.000000', 0.65, 70)
2018-05-08 18:31:21,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,678 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 1.02, 70)
2018-05-08 18:31:21,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,680 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 0.07, 70)
2018-05-08 18:31:21,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,682 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 0.3, 73)
2018-05-08 18:31:21,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,683 INFO sqlalchemy.engine.base.Engine ('2011-12-16 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:21,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,685 INFO sqlalchemy.engine.base.Engine ('2011-12-17 00:00:00.000000', 0.38, 69)
2018-05-08 18:31:21,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,687 INFO sqlalchemy.engine.base.Engine ('2011-12-18 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:21,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,689 INFO sqlalchemy.engine.base.Engine ('2011-12-19 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:21,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,690 INFO sqlalchemy.engine.base.Engine ('2011-12-20 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,692 INFO sqlalchemy.engine.base.Engine ('2011-12-21 00:00:00.000000', 0.58, 69)
2018-05-08 18:31:21,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,694 INFO sqlalchemy.engine.base.Engine ('2011-12-22 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:21,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,695 INFO sqlalchemy.engine.base.Engine ('2011-12-23 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:21,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,697 INFO sqlalchemy.engine.base.Engine ('2011-12-24 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:21,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,699 INFO sqlalchemy.engine.base.Engine ('2011-12-25 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:21,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,701 INFO sqlalchemy.engine.base.Engine ('2011-12-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,704 INFO sqlalchemy.engine.base.Engine ('2011-12-27 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:21,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,705 INFO sqlalchemy.engine.base.Engine ('2011-12-28 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:21,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,707 INFO sqlalchemy.engine.base.Engine ('2011-12-29 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,709 INFO sqlalchemy.engine.base.Engine ('2011-12-30 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:21,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,710 INFO sqlalchemy.engine.base.Engine ('2011-12-31 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:21,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,712 INFO sqlalchemy.engine.base.Engine ('2012-01-01 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:21,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,713 INFO sqlalchemy.engine.base.Engine ('2012-01-02 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:21,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,715 INFO sqlalchemy.engine.base.Engine ('2012-01-03 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:21,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,717 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,718 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:21,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,720 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,721 INFO sqlalchemy.engine.base.Engine ('2012-01-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,723 INFO sqlalchemy.engine.base.Engine ('2012-01-08 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:21,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,725 INFO sqlalchemy.engine.base.Engine ('2012-01-09 00:00:00.000000', 0.03, 65)
2018-05-08 18:31:21,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,726 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,728 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,729 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.07, 62)
2018-05-08 18:31:21,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,731 INFO sqlalchemy.engine.base.Engine ('2012-01-13 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,733 INFO sqlalchemy.engine.base.Engine ('2012-01-14 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:21,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,734 INFO sqlalchemy.engine.base.Engine ('2012-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:21,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,736 INFO sqlalchemy.engine.base.Engine ('2012-01-16 00:00:00.000000', 0.46, 73)
2018-05-08 18:31:21,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,737 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:21,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,739 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:21,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,740 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:21,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,742 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,744 INFO sqlalchemy.engine.base.Engine ('2012-01-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,745 INFO sqlalchemy.engine.base.Engine ('2012-01-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,747 INFO sqlalchemy.engine.base.Engine ('2012-01-23 00:00:00.000000', 0.24, 64)
2018-05-08 18:31:21,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,748 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:21,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,750 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 1.67, 68)
2018-05-08 18:31:21,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,751 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,753 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,755 INFO sqlalchemy.engine.base.Engine ('2012-01-28 00:00:00.000000', 0.17, 73)
2018-05-08 18:31:21,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,756 INFO sqlalchemy.engine.base.Engine ('2012-01-29 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:21,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,758 INFO sqlalchemy.engine.base.Engine ('2012-01-30 00:00:00.000000', 0.14, 63)
2018-05-08 18:31:21,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,760 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:21,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,762 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:21,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,763 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,765 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:21,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,766 INFO sqlalchemy.engine.base.Engine ('2012-02-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,768 INFO sqlalchemy.engine.base.Engine ('2012-02-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,769 INFO sqlalchemy.engine.base.Engine ('2012-02-06 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,771 INFO sqlalchemy.engine.base.Engine ('2012-02-07 00:00:00.000000', 0.62, 70)
2018-05-08 18:31:21,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,813 INFO sqlalchemy.engine.base.Engine ('2012-02-08 00:00:00.000000', 0.49, 61)
2018-05-08 18:31:21,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,814 INFO sqlalchemy.engine.base.Engine ('2012-02-09 00:00:00.000000', 0.01, 60)
2018-05-08 18:31:21,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,816 INFO sqlalchemy.engine.base.Engine ('2012-02-10 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:21,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,817 INFO sqlalchemy.engine.base.Engine ('2012-02-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,819 INFO sqlalchemy.engine.base.Engine ('2012-02-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:21,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,820 INFO sqlalchemy.engine.base.Engine ('2012-02-13 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:21,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,821 INFO sqlalchemy.engine.base.Engine ('2012-02-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,823 INFO sqlalchemy.engine.base.Engine ('2012-02-15 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:21,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,824 INFO sqlalchemy.engine.base.Engine ('2012-02-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,826 INFO sqlalchemy.engine.base.Engine ('2012-02-17 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:21,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,827 INFO sqlalchemy.engine.base.Engine ('2012-02-18 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:21,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,829 INFO sqlalchemy.engine.base.Engine ('2012-02-19 00:00:00.000000', 0.6, 69)
2018-05-08 18:31:21,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,830 INFO sqlalchemy.engine.base.Engine ('2012-02-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,831 INFO sqlalchemy.engine.base.Engine ('2012-02-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,833 INFO sqlalchemy.engine.base.Engine ('2012-02-22 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:21,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,835 INFO sqlalchemy.engine.base.Engine ('2012-02-23 00:00:00.000000', 0.19, 70)
2018-05-08 18:31:21,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,836 INFO sqlalchemy.engine.base.Engine ('2012-02-24 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:21,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,838 INFO sqlalchemy.engine.base.Engine ('2012-02-25 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,839 INFO sqlalchemy.engine.base.Engine ('2012-02-26 00:00:00.000000', 0.85, 70)
2018-05-08 18:31:21,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,841 INFO sqlalchemy.engine.base.Engine ('2012-02-27 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:21,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,842 INFO sqlalchemy.engine.base.Engine ('2012-02-28 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:21,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,844 INFO sqlalchemy.engine.base.Engine ('2012-02-29 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:21,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,845 INFO sqlalchemy.engine.base.Engine ('2012-03-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,847 INFO sqlalchemy.engine.base.Engine ('2012-03-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,848 INFO sqlalchemy.engine.base.Engine ('2012-03-03 00:00:00.000000', 4.68, 71)
2018-05-08 18:31:21,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,850 INFO sqlalchemy.engine.base.Engine ('2012-03-04 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:21,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,851 INFO sqlalchemy.engine.base.Engine ('2012-03-05 00:00:00.000000', 6.24, 65)
2018-05-08 18:31:21,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,853 INFO sqlalchemy.engine.base.Engine ('2012-03-06 00:00:00.000000', 2.59, 66)
2018-05-08 18:31:21,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,854 INFO sqlalchemy.engine.base.Engine ('2012-03-07 00:00:00.000000', 1.68, 66)
2018-05-08 18:31:21,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,856 INFO sqlalchemy.engine.base.Engine ('2012-03-08 00:00:00.000000', 0.53, 68)
2018-05-08 18:31:21,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,857 INFO sqlalchemy.engine.base.Engine ('2012-03-09 00:00:00.000000', 1.44, 68)
2018-05-08 18:31:21,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,859 INFO sqlalchemy.engine.base.Engine ('2012-03-10 00:00:00.000000', 3.47, 73)
2018-05-08 18:31:21,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,860 INFO sqlalchemy.engine.base.Engine ('2012-03-11 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:21,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,861 INFO sqlalchemy.engine.base.Engine ('2012-03-12 00:00:00.000000', 0.23, 70)
2018-05-08 18:31:21,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,863 INFO sqlalchemy.engine.base.Engine ('2012-03-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:21,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,864 INFO sqlalchemy.engine.base.Engine ('2012-03-14 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:21,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,866 INFO sqlalchemy.engine.base.Engine ('2012-03-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,867 INFO sqlalchemy.engine.base.Engine ('2012-03-16 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:21,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,869 INFO sqlalchemy.engine.base.Engine ('2012-03-17 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:21,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,870 INFO sqlalchemy.engine.base.Engine ('2012-03-18 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:21,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,872 INFO sqlalchemy.engine.base.Engine ('2012-03-19 00:00:00.000000', 0.29, 69)
2018-05-08 18:31:21,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,874 INFO sqlalchemy.engine.base.Engine ('2012-03-20 00:00:00.000000', 0.12, 64)
2018-05-08 18:31:21,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,875 INFO sqlalchemy.engine.base.Engine ('2012-03-21 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:21,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,876 INFO sqlalchemy.engine.base.Engine ('2012-03-22 00:00:00.000000', 0.2, 68)
2018-05-08 18:31:21,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,878 INFO sqlalchemy.engine.base.Engine ('2012-03-23 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:21,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,879 INFO sqlalchemy.engine.base.Engine ('2012-03-24 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:21,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,881 INFO sqlalchemy.engine.base.Engine ('2012-03-25 00:00:00.000000', 0.32, 70)
2018-05-08 18:31:21,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,882 INFO sqlalchemy.engine.base.Engine ('2012-03-26 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:21,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,884 INFO sqlalchemy.engine.base.Engine ('2012-03-27 00:00:00.000000', 0.06, 66)
2018-05-08 18:31:21,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,886 INFO sqlalchemy.engine.base.Engine ('2012-03-28 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,888 INFO sqlalchemy.engine.base.Engine ('2012-03-29 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,889 INFO sqlalchemy.engine.base.Engine ('2012-03-30 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:21,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,891 INFO sqlalchemy.engine.base.Engine ('2012-03-31 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:21,892 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,892 INFO sqlalchemy.engine.base.Engine ('2012-04-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:21,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,894 INFO sqlalchemy.engine.base.Engine ('2012-04-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:21,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,896 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:21,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,897 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:21,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,899 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:21,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,900 INFO sqlalchemy.engine.base.Engine ('2012-04-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:21,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,902 INFO sqlalchemy.engine.base.Engine ('2012-04-07 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:21,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,903 INFO sqlalchemy.engine.base.Engine ('2012-04-08 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:21,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,905 INFO sqlalchemy.engine.base.Engine ('2012-04-09 00:00:00.000000', 0.22, 68)
2018-05-08 18:31:21,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,906 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 0.73, 65)
2018-05-08 18:31:21,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,908 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 0.43, 65)
2018-05-08 18:31:21,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,910 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.47, 68)
2018-05-08 18:31:21,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,911 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.37, 64)
2018-05-08 18:31:21,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,913 INFO sqlalchemy.engine.base.Engine ('2012-04-14 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:21,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,914 INFO sqlalchemy.engine.base.Engine ('2012-04-15 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:21,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,916 INFO sqlalchemy.engine.base.Engine ('2012-04-16 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:21,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,917 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,919 INFO sqlalchemy.engine.base.Engine ('2012-04-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,920 INFO sqlalchemy.engine.base.Engine ('2012-04-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:21,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,921 INFO sqlalchemy.engine.base.Engine ('2012-04-20 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:21,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,923 INFO sqlalchemy.engine.base.Engine ('2012-04-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:21,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,924 INFO sqlalchemy.engine.base.Engine ('2012-04-22 00:00:00.000000', 0.19, 70)
2018-05-08 18:31:21,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,926 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:21,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,927 INFO sqlalchemy.engine.base.Engine ('2012-04-24 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:21,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,929 INFO sqlalchemy.engine.base.Engine ('2012-04-25 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:21,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,930 INFO sqlalchemy.engine.base.Engine ('2012-04-26 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:21,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,932 INFO sqlalchemy.engine.base.Engine ('2012-04-27 00:00:00.000000', 0.38, 67)
2018-05-08 18:31:21,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,933 INFO sqlalchemy.engine.base.Engine ('2012-04-28 00:00:00.000000', 0.12, 77)
2018-05-08 18:31:21,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,935 INFO sqlalchemy.engine.base.Engine ('2012-04-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:21,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,937 INFO sqlalchemy.engine.base.Engine ('2012-04-30 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:21,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,938 INFO sqlalchemy.engine.base.Engine ('2012-05-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:21,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,940 INFO sqlalchemy.engine.base.Engine ('2012-05-02 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:21,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,941 INFO sqlalchemy.engine.base.Engine ('2012-05-03 00:00:00.000000', 0.14, 70)
2018-05-08 18:31:21,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,943 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:21,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,944 INFO sqlalchemy.engine.base.Engine ('2012-05-05 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:21,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,946 INFO sqlalchemy.engine.base.Engine ('2012-05-06 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:21,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,947 INFO sqlalchemy.engine.base.Engine ('2012-05-07 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:21,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,948 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:21,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:21,950 INFO sqlalchemy.engine.base.Engine ('2012-05-09 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:21,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,951 INFO sqlalchemy.engine.base.Engine ('2012-05-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:21,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,953 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:21,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,955 INFO sqlalchemy.engine.base.Engine ('2012-05-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:21,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,956 INFO sqlalchemy.engine.base.Engine ('2012-05-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:21,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,957 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:21,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,959 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:21,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,960 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:21,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:21,962 INFO sqlalchemy.engine.base.Engine ('2012-05-17 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:21,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,005 INFO sqlalchemy.engine.base.Engine ('2012-05-18 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:22,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,006 INFO sqlalchemy.engine.base.Engine ('2012-05-19 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:22,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,008 INFO sqlalchemy.engine.base.Engine ('2012-05-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:22,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,009 INFO sqlalchemy.engine.base.Engine ('2012-05-21 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:22,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,011 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,012 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,014 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,015 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:22,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,017 INFO sqlalchemy.engine.base.Engine ('2012-05-26 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:22,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,018 INFO sqlalchemy.engine.base.Engine ('2012-05-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:22,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,020 INFO sqlalchemy.engine.base.Engine ('2012-05-28 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:22,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,021 INFO sqlalchemy.engine.base.Engine ('2012-05-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,022 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:22,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,024 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:22,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,025 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:22,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,027 INFO sqlalchemy.engine.base.Engine ('2012-06-02 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:22,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,028 INFO sqlalchemy.engine.base.Engine ('2012-06-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:22,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,030 INFO sqlalchemy.engine.base.Engine ('2012-06-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,031 INFO sqlalchemy.engine.base.Engine ('2012-06-05 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,033 INFO sqlalchemy.engine.base.Engine ('2012-06-06 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:22,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,035 INFO sqlalchemy.engine.base.Engine ('2012-06-07 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:22,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,036 INFO sqlalchemy.engine.base.Engine ('2012-06-08 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,038 INFO sqlalchemy.engine.base.Engine ('2012-06-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,039 INFO sqlalchemy.engine.base.Engine ('2012-06-10 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:22,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,041 INFO sqlalchemy.engine.base.Engine ('2012-06-11 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:22,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,042 INFO sqlalchemy.engine.base.Engine ('2012-06-12 00:00:00.000000', 0.16, 77)
2018-05-08 18:31:22,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:22,044 INFO sqlalchemy.engine.base.Engine ('2012-06-13 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:22,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,045 INFO sqlalchemy.engine.base.Engine ('2012-06-14 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:22,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,047 INFO sqlalchemy.engine.base.Engine ('2012-06-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:22,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,049 INFO sqlalchemy.engine.base.Engine ('2012-06-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:22,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,050 INFO sqlalchemy.engine.base.Engine ('2012-06-17 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:22,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,052 INFO sqlalchemy.engine.base.Engine ('2012-06-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,053 INFO sqlalchemy.engine.base.Engine ('2012-06-19 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:22,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,055 INFO sqlalchemy.engine.base.Engine ('2012-06-20 00:00:00.000000', 0.33, 71)
2018-05-08 18:31:22,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,056 INFO sqlalchemy.engine.base.Engine ('2012-06-21 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:22,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,058 INFO sqlalchemy.engine.base.Engine ('2012-06-22 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:22,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,059 INFO sqlalchemy.engine.base.Engine ('2012-06-23 00:00:00.000000', 0.35, 73)
2018-05-08 18:31:22,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,061 INFO sqlalchemy.engine.base.Engine ('2012-06-24 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:22,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,063 INFO sqlalchemy.engine.base.Engine ('2012-06-25 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:22,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,065 INFO sqlalchemy.engine.base.Engine ('2012-06-26 00:00:00.000000', 0.22, 71)
2018-05-08 18:31:22,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,066 INFO sqlalchemy.engine.base.Engine ('2012-06-27 00:00:00.000000', 0.43, 68)
2018-05-08 18:31:22,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,068 INFO sqlalchemy.engine.base.Engine ('2012-06-28 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,069 INFO sqlalchemy.engine.base.Engine ('2012-06-29 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:22,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,071 INFO sqlalchemy.engine.base.Engine ('2012-06-30 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:22,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,072 INFO sqlalchemy.engine.base.Engine ('2012-07-01 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:22,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,074 INFO sqlalchemy.engine.base.Engine ('2012-07-02 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:22,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,075 INFO sqlalchemy.engine.base.Engine ('2012-07-03 00:00:00.000000', 0.55, 71)
2018-05-08 18:31:22,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,077 INFO sqlalchemy.engine.base.Engine ('2012-07-04 00:00:00.000000', 0.3, 74)
2018-05-08 18:31:22,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,078 INFO sqlalchemy.engine.base.Engine ('2012-07-05 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:22,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,080 INFO sqlalchemy.engine.base.Engine ('2012-07-06 00:00:00.000000', 0.14, 76)
2018-05-08 18:31:22,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,081 INFO sqlalchemy.engine.base.Engine ('2012-07-07 00:00:00.000000', 0.21, 74)
2018-05-08 18:31:22,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,083 INFO sqlalchemy.engine.base.Engine ('2012-07-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:22,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,084 INFO sqlalchemy.engine.base.Engine ('2012-07-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,086 INFO sqlalchemy.engine.base.Engine ('2012-07-10 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:22,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,087 INFO sqlalchemy.engine.base.Engine ('2012-07-11 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:22,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,089 INFO sqlalchemy.engine.base.Engine ('2012-07-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,091 INFO sqlalchemy.engine.base.Engine ('2012-07-13 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:22,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,092 INFO sqlalchemy.engine.base.Engine ('2012-07-14 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:22,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,094 INFO sqlalchemy.engine.base.Engine ('2012-07-15 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:22,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,095 INFO sqlalchemy.engine.base.Engine ('2012-07-16 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:22,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,096 INFO sqlalchemy.engine.base.Engine ('2012-07-17 00:00:00.000000', 0.21, 72)
2018-05-08 18:31:22,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:22,098 INFO sqlalchemy.engine.base.Engine ('2012-07-18 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:22,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,100 INFO sqlalchemy.engine.base.Engine ('2012-07-19 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:22,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,101 INFO sqlalchemy.engine.base.Engine ('2012-07-20 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:22,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,102 INFO sqlalchemy.engine.base.Engine ('2012-07-21 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:22,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,104 INFO sqlalchemy.engine.base.Engine ('2012-07-22 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:22,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,105 INFO sqlalchemy.engine.base.Engine ('2012-07-23 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:22,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,107 INFO sqlalchemy.engine.base.Engine ('2012-07-24 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,108 INFO sqlalchemy.engine.base.Engine ('2012-07-25 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:22,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,109 INFO sqlalchemy.engine.base.Engine ('2012-07-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,111 INFO sqlalchemy.engine.base.Engine ('2012-07-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,112 INFO sqlalchemy.engine.base.Engine ('2012-07-28 00:00:00.000000', 0.42, 73)
2018-05-08 18:31:22,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,114 INFO sqlalchemy.engine.base.Engine ('2012-07-29 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:22,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,115 INFO sqlalchemy.engine.base.Engine ('2012-07-30 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:22,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,117 INFO sqlalchemy.engine.base.Engine ('2012-07-31 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:22,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,118 INFO sqlalchemy.engine.base.Engine ('2012-08-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,120 INFO sqlalchemy.engine.base.Engine ('2012-08-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,121 INFO sqlalchemy.engine.base.Engine ('2012-08-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,123 INFO sqlalchemy.engine.base.Engine ('2012-08-04 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:22,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,124 INFO sqlalchemy.engine.base.Engine ('2012-08-05 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:22,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,125 INFO sqlalchemy.engine.base.Engine ('2012-08-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,127 INFO sqlalchemy.engine.base.Engine ('2012-08-07 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:22,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,128 INFO sqlalchemy.engine.base.Engine ('2012-08-08 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,130 INFO sqlalchemy.engine.base.Engine ('2012-08-09 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:22,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,132 INFO sqlalchemy.engine.base.Engine ('2012-08-10 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,134 INFO sqlalchemy.engine.base.Engine ('2012-08-11 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:22,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,135 INFO sqlalchemy.engine.base.Engine ('2012-08-12 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:22,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,136 INFO sqlalchemy.engine.base.Engine ('2012-08-13 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:22,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,138 INFO sqlalchemy.engine.base.Engine ('2012-08-14 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:22,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,140 INFO sqlalchemy.engine.base.Engine ('2012-08-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,141 INFO sqlalchemy.engine.base.Engine ('2012-08-16 00:00:00.000000', 0.01, 82)
2018-05-08 18:31:22,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,143 INFO sqlalchemy.engine.base.Engine ('2012-08-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,144 INFO sqlalchemy.engine.base.Engine ('2012-08-18 00:00:00.000000', 0.28, 77)
2018-05-08 18:31:22,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,146 INFO sqlalchemy.engine.base.Engine ('2012-08-19 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:22,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,147 INFO sqlalchemy.engine.base.Engine ('2012-08-20 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:22,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,149 INFO sqlalchemy.engine.base.Engine ('2012-08-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:22,150 INFO sqlalchemy.engine.base.Engine ('2012-08-22 00:00:00.000000', 0.68, 71)
2018-05-08 18:31:22,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,152 INFO sqlalchemy.engine.base.Engine ('2012-08-23 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:22,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,153 INFO sqlalchemy.engine.base.Engine ('2012-08-24 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,155 INFO sqlalchemy.engine.base.Engine ('2012-08-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,200 INFO sqlalchemy.engine.base.Engine ('2012-08-26 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:22,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,202 INFO sqlalchemy.engine.base.Engine ('2012-08-27 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:22,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,203 INFO sqlalchemy.engine.base.Engine ('2012-08-28 00:00:00.000000', 0.76, 79)
2018-05-08 18:31:22,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,205 INFO sqlalchemy.engine.base.Engine ('2012-08-29 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:22,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,206 INFO sqlalchemy.engine.base.Engine ('2012-08-30 00:00:00.000000', 0.32, 77)
2018-05-08 18:31:22,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,208 INFO sqlalchemy.engine.base.Engine ('2012-08-31 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:22,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,209 INFO sqlalchemy.engine.base.Engine ('2012-09-01 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:22,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,211 INFO sqlalchemy.engine.base.Engine ('2012-09-02 00:00:00.000000', 0.33, 78)
2018-05-08 18:31:22,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,212 INFO sqlalchemy.engine.base.Engine ('2012-09-03 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:22,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,214 INFO sqlalchemy.engine.base.Engine ('2012-09-04 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:22,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,215 INFO sqlalchemy.engine.base.Engine ('2012-09-05 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:22,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,217 INFO sqlalchemy.engine.base.Engine ('2012-09-06 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:22,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,218 INFO sqlalchemy.engine.base.Engine ('2012-09-07 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:22,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,220 INFO sqlalchemy.engine.base.Engine ('2012-09-08 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:22,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,221 INFO sqlalchemy.engine.base.Engine ('2012-09-09 00:00:00.000000', 0.29, 75)
2018-05-08 18:31:22,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,223 INFO sqlalchemy.engine.base.Engine ('2012-09-10 00:00:00.000000', 0.43, 75)
2018-05-08 18:31:22,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,224 INFO sqlalchemy.engine.base.Engine ('2012-09-11 00:00:00.000000', 0.2, 71)
2018-05-08 18:31:22,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,226 INFO sqlalchemy.engine.base.Engine ('2012-09-12 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:22,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,227 INFO sqlalchemy.engine.base.Engine ('2012-09-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,229 INFO sqlalchemy.engine.base.Engine ('2012-09-14 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:22,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,230 INFO sqlalchemy.engine.base.Engine ('2012-09-15 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:22,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,232 INFO sqlalchemy.engine.base.Engine ('2012-09-16 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:22,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,233 INFO sqlalchemy.engine.base.Engine ('2012-09-17 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:22,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,234 INFO sqlalchemy.engine.base.Engine ('2012-09-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,236 INFO sqlalchemy.engine.base.Engine ('2012-09-19 00:00:00.000000', 0.53, 73)
2018-05-08 18:31:22,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,237 INFO sqlalchemy.engine.base.Engine ('2012-09-20 00:00:00.000000', 0.39, 73)
2018-05-08 18:31:22,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,239 INFO sqlalchemy.engine.base.Engine ('2012-09-21 00:00:00.000000', 0.73, 76)
2018-05-08 18:31:22,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,240 INFO sqlalchemy.engine.base.Engine ('2012-09-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,242 INFO sqlalchemy.engine.base.Engine ('2012-09-23 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:22,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,243 INFO sqlalchemy.engine.base.Engine ('2012-09-24 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:22,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,245 INFO sqlalchemy.engine.base.Engine ('2012-09-25 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:22,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:22,246 INFO sqlalchemy.engine.base.Engine ('2012-09-26 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:22,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,248 INFO sqlalchemy.engine.base.Engine ('2012-09-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,249 INFO sqlalchemy.engine.base.Engine ('2012-09-28 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:22,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,251 INFO sqlalchemy.engine.base.Engine ('2012-09-29 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:22,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,252 INFO sqlalchemy.engine.base.Engine ('2012-09-30 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,254 INFO sqlalchemy.engine.base.Engine ('2012-10-01 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:22,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,256 INFO sqlalchemy.engine.base.Engine ('2012-10-02 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:22,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,257 INFO sqlalchemy.engine.base.Engine ('2012-10-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,259 INFO sqlalchemy.engine.base.Engine ('2012-10-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:22,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,260 INFO sqlalchemy.engine.base.Engine ('2012-10-05 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,261 INFO sqlalchemy.engine.base.Engine ('2012-10-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,263 INFO sqlalchemy.engine.base.Engine ('2012-10-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,264 INFO sqlalchemy.engine.base.Engine ('2012-10-08 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:22,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,266 INFO sqlalchemy.engine.base.Engine ('2012-10-09 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:22,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,267 INFO sqlalchemy.engine.base.Engine ('2012-10-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:22,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,269 INFO sqlalchemy.engine.base.Engine ('2012-10-11 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:22,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,485 INFO sqlalchemy.engine.base.Engine ('2013-01-25 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:22,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,486 INFO sqlalchemy.engine.base.Engine ('2013-01-26 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:22,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,488 INFO sqlalchemy.engine.base.Engine ('2013-01-27 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:22,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,489 INFO sqlalchemy.engine.base.Engine ('2013-01-28 00:00:00.000000', 2.84, 65)
2018-05-08 18:31:22,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,491 INFO sqlalchemy.engine.base.Engine ('2013-01-29 00:00:00.000000', 1.16, 65)
2018-05-08 18:31:22,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,493 INFO sqlalchemy.engine.base.Engine ('2013-01-30 00:00:00.000000', 0.13, 63)
2018-05-08 18:31:22,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,494 INFO sqlalchemy.engine.base.Engine ('2013-01-31 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:22,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,496 INFO sqlalchemy.engine.base.Engine ('2013-02-01 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:22,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,497 INFO sqlalchemy.engine.base.Engine ('2013-02-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,500 INFO sqlalchemy.engine.base.Engine ('2013-02-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:22,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,501 INFO sqlalchemy.engine.base.Engine ('2013-02-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,503 INFO sqlalchemy.engine.base.Engine ('2013-02-05 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:22,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,504 INFO sqlalchemy.engine.base.Engine ('2013-02-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,506 INFO sqlalchemy.engine.base.Engine ('2013-02-07 00:00:00.000000', 0.26, 69)
2018-05-08 18:31:22,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,508 INFO sqlalchemy.engine.base.Engine ('2013-02-08 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:22,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,509 INFO sqlalchemy.engine.base.Engine ('2013-02-09 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,511 INFO sqlalchemy.engine.base.Engine ('2013-02-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,513 INFO sqlalchemy.engine.base.Engine ('2013-02-11 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:22,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,514 INFO sqlalchemy.engine.base.Engine ('2013-02-12 00:00:00.000000', 0.06, 68)

2018-05-08 18:31:22,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,516 INFO sqlalchemy.engine.base.Engine ('2013-02-13 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:22,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,518 INFO sqlalchemy.engine.base.Engine ('2013-02-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,520 INFO sqlalchemy.engine.base.Engine ('2013-02-15 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:22,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,521 INFO sqlalchemy.engine.base.Engine ('2013-02-16 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:22,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,523 INFO sqlalchemy.engine.base.Engine ('2013-02-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,525 INFO sqlalchemy.engine.base.Engine ('2013-02-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,526 INFO sqlalchemy.engine.base.Engine ('2013-02-19 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:22,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,528 INFO sqlalchemy.engine.base.Engine ('2013-02-20 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:22,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,529 INFO sqlalchemy.engine.base.Engine ('2013-02-21 00:00:00.000000', 0.14, 69)
2018-05-08 18:31:22,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,531 INFO sqlalchemy.engine.base.Engine ('2013-02-22 00:00:00.000000', 1.02, 69)
2018-05-08 18:31:22,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,532 INFO sqlalchemy.engine.base.Engine ('2013-02-23 00:00:00.000000', 0.43, 69)
2018-05-08 18:31:22,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,534 INFO sqlalchemy.engine.base.Engine ('2013-02-24 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:22,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,535 INFO sqlalchemy.engine.base.Engine ('2013-02-25 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:22,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,537 INFO sqlalchemy.engine.base.Engine ('2013-02-26 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:22,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,539 INFO sqlalchemy.engine.base.Engine ('2013-02-27 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,541 INFO sqlalchemy.engine.base.Engine ('2013-02-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,542 INFO sqlalchemy.engine.base.Engine ('2013-03-01 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:22,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,544 INFO sqlalchemy.engine.base.Engine ('2013-03-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,546 INFO sqlalchemy.engine.base.Engine ('2013-03-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,547 INFO sqlalchemy.engine.base.Engine ('2013-03-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:22,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,549 INFO sqlalchemy.engine.base.Engine ('2013-03-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,551 INFO sqlalchemy.engine.base.Engine ('2013-03-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,552 INFO sqlalchemy.engine.base.Engine ('2013-03-07 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:22,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,554 INFO sqlalchemy.engine.base.Engine ('2013-03-08 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:22,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,556 INFO sqlalchemy.engine.base.Engine ('2013-03-09 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:22,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,557 INFO sqlalchemy.engine.base.Engine ('2013-03-10 00:00:00.000000', 2.25, 68)
2018-05-08 18:31:22,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,559 INFO sqlalchemy.engine.base.Engine ('2013-03-11 00:00:00.000000', 1.48, 62)
2018-05-08 18:31:22,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,561 INFO sqlalchemy.engine.base.Engine ('2013-03-12 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:22,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,563 INFO sqlalchemy.engine.base.Engine ('2013-03-13 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:22,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,612 INFO sqlalchemy.engine.base.Engine ('2013-03-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:22,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,613 INFO sqlalchemy.engine.base.Engine ('2013-03-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:22,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,615 INFO sqlalchemy.engine.base.Engine ('2013-03-16 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:22,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,617 INFO sqlalchemy.engine.base.Engine ('2013-03-17 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:22,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,618 INFO sqlalchemy.engine.base.Engine ('2013-03-18 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:22,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,620 INFO sqlalchemy.engine.base.Engine ('2013-03-19 00:00:00.000000', 0.0, 67)

2018-05-08 18:31:22,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,621 INFO sqlalchemy.engine.base.Engine ('2013-03-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,623 INFO sqlalchemy.engine.base.Engine ('2013-03-21 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:22,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,625 INFO sqlalchemy.engine.base.Engine ('2013-03-22 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:22,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,626 INFO sqlalchemy.engine.base.Engine ('2013-03-23 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:22,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,628 INFO sqlalchemy.engine.base.Engine ('2013-03-24 00:00:00.000000', 0.86, 68)
2018-05-08 18:31:22,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,629 INFO sqlalchemy.engine.base.Engine ('2013-03-25 00:00:00.000000', 1.03, 69)
2018-05-08 18:31:22,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,631 INFO sqlalchemy.engine.base.Engine ('2013-03-26 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:22,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,632 INFO sqlalchemy.engine.base.Engine ('2013-03-27 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:22,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,634 INFO sqlalchemy.engine.base.Engine ('2013-03-28 00:00:00.000000', 0.52, 70)
2018-05-08 18:31:22,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,636 INFO sqlalchemy.engine.base.Engine ('2013-03-29 00:00:00.000000', 0.28, 70)
2018-05-08 18:31:22,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,637 INFO sqlalchemy.engine.base.Engine ('2013-03-30 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:22,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,639 INFO sqlalchemy.engine.base.Engine ('2013-03-31 00:00:00.000000', 0.04, 62)
2018-05-08 18:31:22,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,640 INFO sqlalchemy.engine.base.Engine ('2013-04-01 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:22,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,642 INFO sqlalchemy.engine.base.Engine ('2013-04-02 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:22,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,644 INFO sqlalchemy.engine.base.Engine ('2013-04-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,646 INFO sqlalchemy.engine.base.Engine ('2013-04-04 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:22,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,647 INFO sqlalchemy.engine.base.Engine ('2013-04-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,649 INFO sqlalchemy.engine.base.Engine ('2013-04-06 00:00:00.000000', 0.17, 73)
2018-05-08 18:31:22,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,650 INFO sqlalchemy.engine.base.Engine ('2013-04-07 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:22,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,652 INFO sqlalchemy.engine.base.Engine ('2013-04-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,654 INFO sqlalchemy.engine.base.Engine ('2013-04-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,655 INFO sqlalchemy.engine.base.Engine ('2013-04-10 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:22,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,657 INFO sqlalchemy.engine.base.Engine ('2013-04-11 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:22,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,658 INFO sqlalchemy.engine.base.Engine ('2013-04-12 00:00:00.000000', 0.2, 73)
2018-05-08 18:31:22,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,660 INFO sqlalchemy.engine.base.Engine ('2013-04-13 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:22,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,662 INFO sqlalchemy.engine.base.Engine ('2013-04-14 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:22,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,663 INFO sqlalchemy.engine.base.Engine ('2013-04-15 00:00:00.000000', 0.79, 70)
2018-05-08 18:31:22,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,665 INFO sqlalchemy.engine.base.Engine ('2013-04-16 00:00:00.000000', 0.12, 63)
2018-05-08 18:31:22,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,666 INFO sqlalchemy.engine.base.Engine ('2013-04-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,668 INFO sqlalchemy.engine.base.Engine ('2013-04-18 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:22,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,670 INFO sqlalchemy.engine.base.Engine ('2013-04-19 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:22,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,671 INFO sqlalchemy.engine.base.Engine ('2013-04-20 00:00:00.000000', 0.59, 68)
2018-05-08 18:31:22,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,673 INFO sqlalchemy.engine.base.Engine ('2013-04-21 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:22,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,674 INFO sqlalchemy.engine.base.Engine ('2013-04-22 00:00:00.000000', 0.41, 70)
2018-05-08 18:31:22,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,676 INFO sqlalchemy.engine.base.Engine ('2013-04-23 00:00:00.000000', 0.08, 74)

2018-05-08 18:31:22,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,677 INFO sqlalchemy.engine.base.Engine ('2013-04-24 00:00:00.000000', 1.39, 68)
2018-05-08 18:31:22,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,679 INFO sqlalchemy.engine.base.Engine ('2013-04-25 00:00:00.000000', 0.98, 71)
2018-05-08 18:31:22,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,681 INFO sqlalchemy.engine.base.Engine ('2013-04-26 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:22,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,682 INFO sqlalchemy.engine.base.Engine ('2013-04-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,684 INFO sqlalchemy.engine.base.Engine ('2013-04-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:22,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,686 INFO sqlalchemy.engine.base.Engine ('2013-04-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,687 INFO sqlalchemy.engine.base.Engine ('2013-04-30 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,689 INFO sqlalchemy.engine.base.Engine ('2013-05-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,691 INFO sqlalchemy.engine.base.Engine ('2013-05-02 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,692 INFO sqlalchemy.engine.base.Engine ('2013-05-03 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:22,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,694 INFO sqlalchemy.engine.base.Engine ('2013-05-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:22,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,695 INFO sqlalchemy.engine.base.Engine ('2013-05-05 00:00:00.000000', 1.95, 75)
2018-05-08 18:31:22,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,697 INFO sqlalchemy.engine.base.Engine ('2013-05-06 00:00:00.000000', 0.36, 69)
2018-05-08 18:31:22,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,698 INFO sqlalchemy.engine.base.Engine ('2013-05-07 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:22,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,701 INFO sqlalchemy.engine.base.Engine ('2013-05-08 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:22,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,702 INFO sqlalchemy.engine.base.Engine ('2013-05-09 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,704 INFO sqlalchemy.engine.base.Engine ('2013-05-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,706 INFO sqlalchemy.engine.base.Engine ('2013-05-11 00:00:00.000000', 1.57, 74)
2018-05-08 18:31:22,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,707 INFO sqlalchemy.engine.base.Engine ('2013-05-12 00:00:00.000000', 1.33, 71)
2018-05-08 18:31:22,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,709 INFO sqlalchemy.engine.base.Engine ('2013-05-13 00:00:00.000000', 3.88, 73)
2018-05-08 18:31:22,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,711 INFO sqlalchemy.engine.base.Engine ('2013-05-14 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:22,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,712 INFO sqlalchemy.engine.base.Engine ('2013-05-15 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:22,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,714 INFO sqlalchemy.engine.base.Engine ('2013-05-16 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:22,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,715 INFO sqlalchemy.engine.base.Engine ('2013-05-17 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,717 INFO sqlalchemy.engine.base.Engine ('2013-05-18 00:00:00.000000', 0.05, 81)
2018-05-08 18:31:22,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,719 INFO sqlalchemy.engine.base.Engine ('2013-05-19 00:00:00.000000', 0.11, 78)
2018-05-08 18:31:22,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,721 INFO sqlalchemy.engine.base.Engine ('2013-05-20 00:00:00.000000', 0.14, 69)
2018-05-08 18:31:22,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,722 INFO sqlalchemy.engine.base.Engine ('2013-05-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:22,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,724 INFO sqlalchemy.engine.base.Engine ('2013-05-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,726 INFO sqlalchemy.engine.base.Engine ('2013-05-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,727 INFO sqlalchemy.engine.base.Engine ('2013-05-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,728 INFO sqlalchemy.engine.base.Engine ('2013-05-25 00:00:00.000000', 0.13, 78)
2018-05-08 18:31:22,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,730 INFO sqlalchemy.engine.base.Engine ('2013-05-26 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:22,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,732 INFO sqlalchemy.engine.base.Engine ('2013-05-27 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:22,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,734 INFO sqlalchemy.engine.base.Engine ('2013-05-28 00:00:00.000000', 0.04, 74)

2018-05-08 18:31:22,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,735 INFO sqlalchemy.engine.base.Engine ('2013-05-29 00:00:00.000000', 1.87, 71)
2018-05-08 18:31:22,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,737 INFO sqlalchemy.engine.base.Engine ('2013-05-30 00:00:00.000000', 4.07, 74)
2018-05-08 18:31:22,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,739 INFO sqlalchemy.engine.base.Engine ('2013-05-31 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,740 INFO sqlalchemy.engine.base.Engine ('2013-06-01 00:00:00.000000', 0.06, 81)
2018-05-08 18:31:22,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,742 INFO sqlalchemy.engine.base.Engine ('2013-06-02 00:00:00.000000', 0.17, 74)
2018-05-08 18:31:22,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,743 INFO sqlalchemy.engine.base.Engine ('2013-06-03 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:22,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,745 INFO sqlalchemy.engine.base.Engine ('2013-06-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,746 INFO sqlalchemy.engine.base.Engine ('2013-06-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,748 INFO sqlalchemy.engine.base.Engine ('2013-06-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,749 INFO sqlalchemy.engine.base.Engine ('2013-06-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,751 INFO sqlalchemy.engine.base.Engine ('2013-06-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:22,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,752 INFO sqlalchemy.engine.base.Engine ('2013-06-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:22,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,754 INFO sqlalchemy.engine.base.Engine ('2013-06-10 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:22,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,756 INFO sqlalchemy.engine.base.Engine ('2013-06-11 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:22,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,758 INFO sqlalchemy.engine.base.Engine ('2013-06-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,760 INFO sqlalchemy.engine.base.Engine ('2013-06-13 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:22,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,761 INFO sqlalchemy.engine.base.Engine ('2013-06-14 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:22,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,763 INFO sqlalchemy.engine.base.Engine ('2013-06-15 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:22,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,765 INFO sqlalchemy.engine.base.Engine ('2013-06-16 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:22,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,766 INFO sqlalchemy.engine.base.Engine ('2013-06-17 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:22,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,768 INFO sqlalchemy.engine.base.Engine ('2013-06-18 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:22,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,770 INFO sqlalchemy.engine.base.Engine ('2013-06-19 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:22,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,771 INFO sqlalchemy.engine.base.Engine ('2013-06-20 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:22,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,773 INFO sqlalchemy.engine.base.Engine ('2013-06-21 00:00:00.000000', 0.53, 68)
2018-05-08 18:31:22,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,825 INFO sqlalchemy.engine.base.Engine ('2013-06-22 00:00:00.000000', 0.88, 75)
2018-05-08 18:31:22,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,826 INFO sqlalchemy.engine.base.Engine ('2013-06-23 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:22,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,828 INFO sqlalchemy.engine.base.Engine ('2013-06-24 00:00:00.000000', 0.22, 73)
2018-05-08 18:31:22,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,829 INFO sqlalchemy.engine.base.Engine ('2013-06-25 00:00:00.000000', 0.36, 70)
2018-05-08 18:31:22,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,831 INFO sqlalchemy.engine.base.Engine ('2013-06-26 00:00:00.000000', 0.82, 70)
2018-05-08 18:31:22,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,832 INFO sqlalchemy.engine.base.Engine ('2013-06-27 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:22,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,834 INFO sqlalchemy.engine.base.Engine ('2013-06-28 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:22,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,835 INFO sqlalchemy.engine.base.Engine ('2013-06-29 00:00:00.000000', 0.43, 70)
2018-05-08 18:31:22,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,837 INFO sqlalchemy.engine.base.Engine ('2013-06-30 00:00:00.000000', 0.71, 75)
2018-05-08 18:31:22,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,839 INFO sqlalchemy.engine.base.Engine ('2013-07-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,840 INFO sqlalchemy.engine.base.Engine ('2013-07-02 00:00:00.000000', 0.09, 71)

2018-05-08 18:31:22,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,842 INFO sqlalchemy.engine.base.Engine ('2013-07-03 00:00:00.000000', 0.38, 69)
2018-05-08 18:31:22,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,844 INFO sqlalchemy.engine.base.Engine ('2013-07-04 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:22,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,845 INFO sqlalchemy.engine.base.Engine ('2013-07-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:22,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,847 INFO sqlalchemy.engine.base.Engine ('2013-07-06 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:22,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,849 INFO sqlalchemy.engine.base.Engine ('2013-07-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,850 INFO sqlalchemy.engine.base.Engine ('2013-07-08 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:22,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,852 INFO sqlalchemy.engine.base.Engine ('2013-07-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,854 INFO sqlalchemy.engine.base.Engine ('2013-07-10 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:22,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,855 INFO sqlalchemy.engine.base.Engine ('2013-07-11 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:22,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,857 INFO sqlalchemy.engine.base.Engine ('2013-07-12 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:22,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,859 INFO sqlalchemy.engine.base.Engine ('2013-07-13 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:22,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,860 INFO sqlalchemy.engine.base.Engine ('2013-07-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:22,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,862 INFO sqlalchemy.engine.base.Engine ('2013-07-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,863 INFO sqlalchemy.engine.base.Engine ('2013-07-16 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:22,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,865 INFO sqlalchemy.engine.base.Engine ('2013-07-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,867 INFO sqlalchemy.engine.base.Engine ('2013-07-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,868 INFO sqlalchemy.engine.base.Engine ('2013-07-19 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:22,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,870 INFO sqlalchemy.engine.base.Engine ('2013-07-20 00:00:00.000000', 0.31, 78)
2018-05-08 18:31:22,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,872 INFO sqlalchemy.engine.base.Engine ('2013-07-21 00:00:00.000000', 0.24, 78)
2018-05-08 18:31:22,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,874 INFO sqlalchemy.engine.base.Engine ('2013-07-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,875 INFO sqlalchemy.engine.base.Engine ('2013-07-23 00:00:00.000000', 0.58, 73)
2018-05-08 18:31:22,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,877 INFO sqlalchemy.engine.base.Engine ('2013-07-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,879 INFO sqlalchemy.engine.base.Engine ('2013-07-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:22,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,880 INFO sqlalchemy.engine.base.Engine ('2013-07-26 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,882 INFO sqlalchemy.engine.base.Engine ('2013-07-27 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:22,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,884 INFO sqlalchemy.engine.base.Engine ('2013-07-28 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:22,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,885 INFO sqlalchemy.engine.base.Engine ('2013-07-29 00:00:00.000000', 0.23, 78)
2018-05-08 18:31:22,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,887 INFO sqlalchemy.engine.base.Engine ('2013-07-30 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:22,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,888 INFO sqlalchemy.engine.base.Engine ('2013-07-31 00:00:00.000000', 0.4, 76)
2018-05-08 18:31:22,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,890 INFO sqlalchemy.engine.base.Engine ('2013-08-01 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:22,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,892 INFO sqlalchemy.engine.base.Engine ('2013-08-02 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:22,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,893 INFO sqlalchemy.engine.base.Engine ('2013-08-03 00:00:00.000000', 0.11, 77)
2018-05-08 18:31:22,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,895 INFO sqlalchemy.engine.base.Engine ('2013-08-04 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:22,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,897 INFO sqlalchemy.engine.base.Engine ('2013-08-05 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:22,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,898 INFO sqlalchemy.engine.base.Engine ('2013-08-06 00:00:00.000000', 0.09, 74)

2018-05-08 18:31:22,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,900 INFO sqlalchemy.engine.base.Engine ('2013-08-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,901 INFO sqlalchemy.engine.base.Engine ('2013-08-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,903 INFO sqlalchemy.engine.base.Engine ('2013-08-09 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:22,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,905 INFO sqlalchemy.engine.base.Engine ('2013-08-10 00:00:00.000000', 3.79, 71)
2018-05-08 18:31:22,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,906 INFO sqlalchemy.engine.base.Engine ('2013-08-11 00:00:00.000000', 1.26, 74)
2018-05-08 18:31:22,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,908 INFO sqlalchemy.engine.base.Engine ('2013-08-12 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:22,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,910 INFO sqlalchemy.engine.base.Engine ('2013-08-13 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:22,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,911 INFO sqlalchemy.engine.base.Engine ('2013-08-14 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:22,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,913 INFO sqlalchemy.engine.base.Engine ('2013-08-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,915 INFO sqlalchemy.engine.base.Engine ('2013-08-16 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:22,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,917 INFO sqlalchemy.engine.base.Engine ('2013-08-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,919 INFO sqlalchemy.engine.base.Engine ('2013-08-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:22,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,920 INFO sqlalchemy.engine.base.Engine ('2013-08-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,922 INFO sqlalchemy.engine.base.Engine ('2013-08-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:22,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,923 INFO sqlalchemy.engine.base.Engine ('2013-08-21 00:00:00.000000', 0.67, 71)
2018-05-08 18:31:22,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,925 INFO sqlalchemy.engine.base.Engine ('2013-08-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,927 INFO sqlalchemy.engine.base.Engine ('2013-08-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,929 INFO sqlalchemy.engine.base.Engine ('2013-08-24 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:22,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,931 INFO sqlalchemy.engine.base.Engine ('2013-08-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:22,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,933 INFO sqlalchemy.engine.base.Engine ('2013-08-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,934 INFO sqlalchemy.engine.base.Engine ('2013-08-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,936 INFO sqlalchemy.engine.base.Engine ('2013-08-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:22,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,938 INFO sqlalchemy.engine.base.Engine ('2013-08-29 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:22,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,939 INFO sqlalchemy.engine.base.Engine ('2013-08-30 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:22,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,941 INFO sqlalchemy.engine.base.Engine ('2013-08-31 00:00:00.000000', 0.19, 78)
2018-05-08 18:31:22,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,943 INFO sqlalchemy.engine.base.Engine ('2013-09-01 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:22,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,944 INFO sqlalchemy.engine.base.Engine ('2013-09-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:22,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,946 INFO sqlalchemy.engine.base.Engine ('2013-09-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:22,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,947 INFO sqlalchemy.engine.base.Engine ('2013-09-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:22,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,949 INFO sqlalchemy.engine.base.Engine ('2013-09-05 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:22,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,950 INFO sqlalchemy.engine.base.Engine ('2013-09-06 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:22,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,952 INFO sqlalchemy.engine.base.Engine ('2013-09-07 00:00:00.000000', 0.49, 74)
2018-05-08 18:31:22,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,954 INFO sqlalchemy.engine.base.Engine ('2013-09-08 00:00:00.000000', 0.18, 74)
2018-05-08 18:31:22,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,955 INFO sqlalchemy.engine.base.Engine ('2013-09-09 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:22,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,957 INFO sqlalchemy.engine.base.Engine ('2013-09-10 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:22,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,958 INFO sqlalchemy.engine.base.Engine ('2013-09-11 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:22,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,960 INFO sqlalchemy.engine.base.Engine ('2013-09-12 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:22,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,961 INFO sqlalchemy.engine.base.Engine ('2013-09-13 00:00:00.000000', 1.88, 73)
2018-05-08 18:31:22,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,963 INFO sqlalchemy.engine.base.Engine ('2013-09-14 00:00:00.000000', 0.5, 72)
2018-05-08 18:31:22,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,964 INFO sqlalchemy.engine.base.Engine ('2013-09-15 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:22,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,966 INFO sqlalchemy.engine.base.Engine ('2013-09-16 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:22,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,968 INFO sqlalchemy.engine.base.Engine ('2013-09-17 00:00:00.000000', 0.23, 75)
2018-05-08 18:31:22,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,969 INFO sqlalchemy.engine.base.Engine ('2013-09-18 00:00:00.000000', 0.37, 71)
2018-05-08 18:31:22,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,971 INFO sqlalchemy.engine.base.Engine ('2013-09-19 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:22,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,972 INFO sqlalchemy.engine.base.Engine ('2013-09-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:22,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,974 INFO sqlalchemy.engine.base.Engine ('2013-09-21 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:22,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,976 INFO sqlalchemy.engine.base.Engine ('2013-09-22 00:00:00.000000', 0.22, 76)
2018-05-08 18:31:22,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,977 INFO sqlalchemy.engine.base.Engine ('2013-09-23 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:22,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,979 INFO sqlalchemy.engine.base.Engine ('2013-09-24 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:22,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,981 INFO sqlalchemy.engine.base.Engine ('2013-09-25 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:22,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,982 INFO sqlalchemy.engine.base.Engine ('2013-09-26 00:00:00.000000', 0.42, 72)
2018-05-08 18:31:22,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,984 INFO sqlalchemy.engine.base.Engine ('2013-09-27 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:22,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,986 INFO sqlalchemy.engine.base.Engine ('2013-09-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:22,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:22,987 INFO sqlalchemy.engine.base.Engine ('2013-09-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:22,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,036 INFO sqlalchemy.engine.base.Engine ('2013-09-30 00:00:00.000000', 0.04, 67)
2018-05-08 18:31:23,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,038 INFO sqlalchemy.engine.base.Engine ('2013-10-01 00:00:00.000000', 0.67, 74)
2018-05-08 18:31:23,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,040 INFO sqlalchemy.engine.base.Engine ('2013-10-02 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:23,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,041 INFO sqlalchemy.engine.base.Engine ('2013-10-03 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:23,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,043 INFO sqlalchemy.engine.base.Engine ('2013-10-04 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:23,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,044 INFO sqlalchemy.engine.base.Engine ('2013-10-05 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:23,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,046 INFO sqlalchemy.engine.base.Engine ('2013-10-06 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:23,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,048 INFO sqlalchemy.engine.base.Engine ('2013-10-07 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:23,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,049 INFO sqlalchemy.engine.base.Engine ('2013-10-08 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:23,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,051 INFO sqlalchemy.engine.base.Engine ('2013-10-09 00:00:00.000000', 0.17, 75)
2018-05-08 18:31:23,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,053 INFO sqlalchemy.engine.base.Engine ('2013-10-10 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:23,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,054 INFO sqlalchemy.engine.base.Engine ('2013-10-11 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:23,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,056 INFO sqlalchemy.engine.base.Engine ('2013-10-12 00:00:00.000000', 1.77, 70)
2018-05-08 18:31:23,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,058 INFO sqlalchemy.engine.base.Engine ('2013-10-13 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:23,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,059 INFO sqlalchemy.engine.base.Engine ('2013-10-14 00:00:00.000000', 0.44, 70)
2018-05-08 18:31:23,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,061 INFO sqlalchemy.engine.base.Engine ('2013-10-15 00:00:00.000000', 0.62, 70)

2018-05-08 18:31:23,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,063 INFO sqlalchemy.engine.base.Engine ('2013-10-16 00:00:00.000000', 0.7, 71)
2018-05-08 18:31:23,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,064 INFO sqlalchemy.engine.base.Engine ('2013-10-17 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:23,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,066 INFO sqlalchemy.engine.base.Engine ('2013-10-18 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:23,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,068 INFO sqlalchemy.engine.base.Engine ('2013-10-19 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:23,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,069 INFO sqlalchemy.engine.base.Engine ('2013-10-20 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:23,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,071 INFO sqlalchemy.engine.base.Engine ('2013-10-21 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:23,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,073 INFO sqlalchemy.engine.base.Engine ('2013-10-22 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:23,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,074 INFO sqlalchemy.engine.base.Engine ('2013-10-23 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:23,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,076 INFO sqlalchemy.engine.base.Engine ('2013-10-24 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:23,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,077 INFO sqlalchemy.engine.base.Engine ('2013-10-25 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:23,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,079 INFO sqlalchemy.engine.base.Engine ('2013-10-26 00:00:00.000000', 0.32, 70)
2018-05-08 18:31:23,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,081 INFO sqlalchemy.engine.base.Engine ('2013-10-27 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:23,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,082 INFO sqlalchemy.engine.base.Engine ('2013-10-28 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:23,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,084 INFO sqlalchemy.engine.base.Engine ('2013-10-29 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:23,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,086 INFO sqlalchemy.engine.base.Engine ('2013-10-30 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,087 INFO sqlalchemy.engine.base.Engine ('2013-10-31 00:00:00.000000', 0.23, 76)
2018-05-08 18:31:23,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,089 INFO sqlalchemy.engine.base.Engine ('2013-11-01 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:23,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,091 INFO sqlalchemy.engine.base.Engine ('2013-11-02 00:00:00.000000', 0.27, 76)
2018-05-08 18:31:23,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,092 INFO sqlalchemy.engine.base.Engine ('2013-11-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:23,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,094 INFO sqlalchemy.engine.base.Engine ('2013-11-04 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:23,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,096 INFO sqlalchemy.engine.base.Engine ('2013-11-05 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:23,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,097 INFO sqlalchemy.engine.base.Engine ('2013-11-06 00:00:00.000000', 0.8, 70)
2018-05-08 18:31:23,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,098 INFO sqlalchemy.engine.base.Engine ('2013-11-07 00:00:00.000000', 0.12, 67)
2018-05-08 18:31:23,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,100 INFO sqlalchemy.engine.base.Engine ('2013-11-08 00:00:00.000000', 1.42, 70)
2018-05-08 18:31:23,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,102 INFO sqlalchemy.engine.base.Engine ('2013-11-09 00:00:00.000000', 2.21, 74)
2018-05-08 18:31:23,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,104 INFO sqlalchemy.engine.base.Engine ('2013-11-10 00:00:00.000000', 5.54, 71)
2018-05-08 18:31:23,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,105 INFO sqlalchemy.engine.base.Engine ('2013-11-11 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:23,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,107 INFO sqlalchemy.engine.base.Engine ('2013-11-12 00:00:00.000000', 0.23, 67)
2018-05-08 18:31:23,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,108 INFO sqlalchemy.engine.base.Engine ('2013-11-13 00:00:00.000000', 0.02, 61)
2018-05-08 18:31:23,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,110 INFO sqlalchemy.engine.base.Engine ('2013-11-14 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:23,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,111 INFO sqlalchemy.engine.base.Engine ('2013-11-15 00:00:00.000000', 0.47, 70)
2018-05-08 18:31:23,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,113 INFO sqlalchemy.engine.base.Engine ('2013-11-16 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:23,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,115 INFO sqlalchemy.engine.base.Engine ('2013-11-17 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:23,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,116 INFO sqlalchemy.engine.base.Engine ('2013-11-18 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:23,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,118 INFO sqlalchemy.engine.base.Engine ('2013-11-19 00:00:00.000000', 0.01, 64)

2018-05-08 18:31:23,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,120 INFO sqlalchemy.engine.base.Engine ('2013-11-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:23,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,121 INFO sqlalchemy.engine.base.Engine ('2013-11-21 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,122 INFO sqlalchemy.engine.base.Engine ('2013-11-22 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:23,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,124 INFO sqlalchemy.engine.base.Engine ('2013-11-23 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:23,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,125 INFO sqlalchemy.engine.base.Engine ('2013-11-24 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:23,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,127 INFO sqlalchemy.engine.base.Engine ('2013-11-25 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:23,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,129 INFO sqlalchemy.engine.base.Engine ('2013-11-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:23,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,131 INFO sqlalchemy.engine.base.Engine ('2013-11-27 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:23,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,132 INFO sqlalchemy.engine.base.Engine ('2013-11-28 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:23,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,134 INFO sqlalchemy.engine.base.Engine ('2013-11-29 00:00:00.000000', 0.84, 69)
2018-05-08 18:31:23,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,135 INFO sqlalchemy.engine.base.Engine ('2013-11-30 00:00:00.000000', 0.88, 76)
2018-05-08 18:31:23,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,136 INFO sqlalchemy.engine.base.Engine ('2013-12-01 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:23,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,138 INFO sqlalchemy.engine.base.Engine ('2013-12-02 00:00:00.000000', 1.71, 73)
2018-05-08 18:31:23,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,139 INFO sqlalchemy.engine.base.Engine ('2013-12-03 00:00:00.000000', 0.57, 70)
2018-05-08 18:31:23,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,142 INFO sqlalchemy.engine.base.Engine ('2013-12-04 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:23,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,144 INFO sqlalchemy.engine.base.Engine ('2013-12-05 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:23,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,145 INFO sqlalchemy.engine.base.Engine ('2013-12-06 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:23,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,147 INFO sqlalchemy.engine.base.Engine ('2013-12-07 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:23,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,149 INFO sqlalchemy.engine.base.Engine ('2013-12-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:23,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,150 INFO sqlalchemy.engine.base.Engine ('2013-12-09 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:23,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,152 INFO sqlalchemy.engine.base.Engine ('2013-12-10 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:23,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,153 INFO sqlalchemy.engine.base.Engine ('2013-12-11 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:23,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,155 INFO sqlalchemy.engine.base.Engine ('2013-12-12 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:23,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,156 INFO sqlalchemy.engine.base.Engine ('2013-12-13 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:23,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,158 INFO sqlalchemy.engine.base.Engine ('2013-12-14 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:23,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,160 INFO sqlalchemy.engine.base.Engine ('2013-12-15 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:23,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,162 INFO sqlalchemy.engine.base.Engine ('2013-12-16 00:00:00.000000', 1.97, 63)
2018-05-08 18:31:23,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,164 INFO sqlalchemy.engine.base.Engine ('2013-12-17 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:23,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,165 INFO sqlalchemy.engine.base.Engine ('2013-12-18 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:23,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,167 INFO sqlalchemy.engine.base.Engine ('2013-12-19 00:00:00.000000', 0.77, 69)
2018-05-08 18:31:23,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,169 INFO sqlalchemy.engine.base.Engine ('2013-12-20 00:00:00.000000', 1.14, 69)
2018-05-08 18:31:23,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,171 INFO sqlalchemy.engine.base.Engine ('2013-12-21 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:23,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,173 INFO sqlalchemy.engine.base.Engine ('2013-12-22 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:23,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,174 INFO sqlalchemy.engine.base.Engine ('2013-12-23 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:23,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,176 INFO sqlalchemy.engine.base.Engine ('2013-12-24 00:00:00.000000', 0.09, 70)

2018-05-08 18:31:23,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,177 INFO sqlalchemy.engine.base.Engine ('2013-12-25 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:23,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,179 INFO sqlalchemy.engine.base.Engine ('2013-12-26 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:23,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,180 INFO sqlalchemy.engine.base.Engine ('2013-12-27 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:23,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,182 INFO sqlalchemy.engine.base.Engine ('2013-12-28 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:23,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,183 INFO sqlalchemy.engine.base.Engine ('2013-12-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:23,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,185 INFO sqlalchemy.engine.base.Engine ('2013-12-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:23,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,187 INFO sqlalchemy.engine.base.Engine ('2013-12-31 00:00:00.000000', 0.08, 65)
2018-05-08 18:31:23,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,188 INFO sqlalchemy.engine.base.Engine ('2014-01-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:23,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,190 INFO sqlalchemy.engine.base.Engine ('2014-01-02 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:23,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,191 INFO sqlalchemy.engine.base.Engine ('2014-01-03 00:00:00.000000', 1.62, 66)
2018-05-08 18:31:23,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,193 INFO sqlalchemy.engine.base.Engine ('2014-01-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,195 INFO sqlalchemy.engine.base.Engine ('2014-01-05 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:23,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,196 INFO sqlalchemy.engine.base.Engine ('2014-01-06 00:00:00.000000', 0.12, 64)
2018-05-08 18:31:23,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,198 INFO sqlalchemy.engine.base.Engine ('2014-01-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,246 INFO sqlalchemy.engine.base.Engine ('2014-01-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:23,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,248 INFO sqlalchemy.engine.base.Engine ('2014-01-09 00:00:00.000000', 0.09, 61)
2018-05-08 18:31:23,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,249 INFO sqlalchemy.engine.base.Engine ('2014-01-10 00:00:00.000000', 0.04, 66)
2018-05-08 18:31:23,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,251 INFO sqlalchemy.engine.base.Engine ('2014-01-11 00:00:00.000000', 0.71, 66)
2018-05-08 18:31:23,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,252 INFO sqlalchemy.engine.base.Engine ('2014-01-12 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:23,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,254 INFO sqlalchemy.engine.base.Engine ('2014-01-13 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:23,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,256 INFO sqlalchemy.engine.base.Engine ('2014-01-14 00:00:00.000000', 1.76, 73)
2018-05-08 18:31:23,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,257 INFO sqlalchemy.engine.base.Engine ('2014-01-15 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:23,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,259 INFO sqlalchemy.engine.base.Engine ('2014-01-16 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:23,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,260 INFO sqlalchemy.engine.base.Engine ('2014-01-17 00:00:00.000000', 0.06, 66)
2018-05-08 18:31:23,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,262 INFO sqlalchemy.engine.base.Engine ('2014-01-18 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:23,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,264 INFO sqlalchemy.engine.base.Engine ('2014-01-19 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:23,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,265 INFO sqlalchemy.engine.base.Engine ('2014-01-20 00:00:00.000000', 0.19, 65)
2018-05-08 18:31:23,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,267 INFO sqlalchemy.engine.base.Engine ('2014-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:23,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,268 INFO sqlalchemy.engine.base.Engine ('2014-01-22 00:00:00.000000', 0.47, 68)
2018-05-08 18:31:23,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,270 INFO sqlalchemy.engine.base.Engine ('2014-01-23 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:23,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,272 INFO sqlalchemy.engine.base.Engine ('2014-01-24 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:23,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,273 INFO sqlalchemy.engine.base.Engine ('2014-01-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:23,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,275 INFO sqlalchemy.engine.base.Engine ('2014-01-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:23,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,277 INFO sqlalchemy.engine.base.Engine ('2014-01-27 00:00:00.000000', 0.48, 66)
2018-05-08 18:31:23,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,279 INFO sqlalchemy.engine.base.Engine ('2014-01-28 00:00:00.000000', 0.69, 66)

2018-05-08 18:31:23,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,280 INFO sqlalchemy.engine.base.Engine ('2014-01-29 00:00:00.000000', 0.77, 67)
2018-05-08 18:31:23,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,282 INFO sqlalchemy.engine.base.Engine ('2014-01-30 00:00:00.000000', 0.49, 64)
2018-05-08 18:31:23,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,284 INFO sqlalchemy.engine.base.Engine ('2014-01-31 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:23,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,286 INFO sqlalchemy.engine.base.Engine ('2014-02-01 00:00:00.000000', 0.87, 70)
2018-05-08 18:31:23,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,288 INFO sqlalchemy.engine.base.Engine ('2014-02-02 00:00:00.000000', 0.26, 66)
2018-05-08 18:31:23,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,290 INFO sqlalchemy.engine.base.Engine ('2014-02-03 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:23,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,291 INFO sqlalchemy.engine.base.Engine ('2014-02-04 00:00:00.000000', 0.67, 66)
2018-05-08 18:31:23,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,293 INFO sqlalchemy.engine.base.Engine ('2014-02-05 00:00:00.000000', 0.41, 67)
2018-05-08 18:31:23,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,294 INFO sqlalchemy.engine.base.Engine ('2014-02-06 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:23,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,296 INFO sqlalchemy.engine.base.Engine ('2014-02-07 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:23,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,297 INFO sqlalchemy.engine.base.Engine ('2014-02-08 00:00:00.000000', 0.64, 67)
2018-05-08 18:31:23,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,299 INFO sqlalchemy.engine.base.Engine ('2014-02-09 00:00:00.000000', 1.14, 72)
2018-05-08 18:31:23,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,300 INFO sqlalchemy.engine.base.Engine ('2014-02-10 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:23,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,302 INFO sqlalchemy.engine.base.Engine ('2014-02-11 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:23,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,303 INFO sqlalchemy.engine.base.Engine ('2014-02-12 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:23,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,305 INFO sqlalchemy.engine.base.Engine ('2014-02-13 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:23,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,307 INFO sqlalchemy.engine.base.Engine ('2014-02-14 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:23,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,309 INFO sqlalchemy.engine.base.Engine ('2014-02-15 00:00:00.000000', 0.43, 71)
2018-05-08 18:31:23,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,311 INFO sqlalchemy.engine.base.Engine ('2014-02-16 00:00:00.000000', 0.63, 71)
2018-05-08 18:31:23,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,313 INFO sqlalchemy.engine.base.Engine ('2014-02-17 00:00:00.000000', 0.31, 73)
2018-05-08 18:31:23,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,315 INFO sqlalchemy.engine.base.Engine ('2014-02-18 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:23,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,316 INFO sqlalchemy.engine.base.Engine ('2014-02-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:23,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,318 INFO sqlalchemy.engine.base.Engine ('2014-02-20 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:23,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,320 INFO sqlalchemy.engine.base.Engine ('2014-02-21 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,321 INFO sqlalchemy.engine.base.Engine ('2014-02-22 00:00:00.000000', 0.53, 67)
2018-05-08 18:31:23,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,323 INFO sqlalchemy.engine.base.Engine ('2014-02-23 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:23,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,324 INFO sqlalchemy.engine.base.Engine ('2014-02-24 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:23,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,326 INFO sqlalchemy.engine.base.Engine ('2014-02-25 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:23,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,328 INFO sqlalchemy.engine.base.Engine ('2014-02-26 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:23,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,329 INFO sqlalchemy.engine.base.Engine ('2014-02-27 00:00:00.000000', 0.03, 63)
2018-05-08 18:31:23,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,331 INFO sqlalchemy.engine.base.Engine ('2014-02-28 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:23,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,333 INFO sqlalchemy.engine.base.Engine ('2014-03-01 00:00:00.000000', 0.35, 70)
2018-05-08 18:31:23,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,335 INFO sqlalchemy.engine.base.Engine ('2014-03-02 00:00:00.000000', 0.28, 68)
2018-05-08 18:31:23,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,337 INFO sqlalchemy.engine.base.Engine ('2014-03-03 00:00:00.000000', 0.28, 62)
2018-05-08 18:31:23,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,338 INFO sqlalchemy.engine.base.Engine ('2014-03-04 00:00:00.000000', 0.0, 57)

2018-05-08 18:31:23,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,340 INFO sqlalchemy.engine.base.Engine ('2014-03-05 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:23,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,341 INFO sqlalchemy.engine.base.Engine ('2014-03-06 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:23,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,343 INFO sqlalchemy.engine.base.Engine ('2014-03-07 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:23,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,345 INFO sqlalchemy.engine.base.Engine ('2014-03-08 00:00:00.000000', 0.54, 65)
2018-05-08 18:31:23,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,346 INFO sqlalchemy.engine.base.Engine ('2014-03-09 00:00:00.000000', 1.72, 69)
2018-05-08 18:31:23,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,348 INFO sqlalchemy.engine.base.Engine ('2014-03-10 00:00:00.000000', 0.32, 69)
2018-05-08 18:31:23,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,350 INFO sqlalchemy.engine.base.Engine ('2014-03-11 00:00:00.000000', 0.28, 66)
2018-05-08 18:31:23,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,351 INFO sqlalchemy.engine.base.Engine ('2014-03-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,353 INFO sqlalchemy.engine.base.Engine ('2014-03-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:23,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,355 INFO sqlalchemy.engine.base.Engine ('2014-03-14 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:23,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,356 INFO sqlalchemy.engine.base.Engine ('2014-03-15 00:00:00.000000', 0.62, 67)
2018-05-08 18:31:23,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,358 INFO sqlalchemy.engine.base.Engine ('2014-03-16 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:23,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,359 INFO sqlalchemy.engine.base.Engine ('2014-03-17 00:00:00.000000', 0.06, 65)
2018-05-08 18:31:23,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,361 INFO sqlalchemy.engine.base.Engine ('2014-03-18 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:23,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,362 INFO sqlalchemy.engine.base.Engine ('2014-03-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:23,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,364 INFO sqlalchemy.engine.base.Engine ('2014-03-20 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:23,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,366 INFO sqlalchemy.engine.base.Engine ('2014-03-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:23,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,368 INFO sqlalchemy.engine.base.Engine ('2014-03-22 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:23,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,369 INFO sqlalchemy.engine.base.Engine ('2014-03-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:23,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,371 INFO sqlalchemy.engine.base.Engine ('2014-03-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:23,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,372 INFO sqlalchemy.engine.base.Engine ('2014-03-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:23,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,374 INFO sqlalchemy.engine.base.Engine ('2014-03-26 00:00:00.000000', 0.75, 73)
2018-05-08 18:31:23,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,376 INFO sqlalchemy.engine.base.Engine ('2014-03-27 00:00:00.000000', 0.27, 70)
2018-05-08 18:31:23,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,377 INFO sqlalchemy.engine.base.Engine ('2014-03-28 00:00:00.000000', 3.86, 67)
2018-05-08 18:31:23,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,379 INFO sqlalchemy.engine.base.Engine ('2014-03-29 00:00:00.000000', 0.26, 73)
2018-05-08 18:31:23,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,380 INFO sqlalchemy.engine.base.Engine ('2014-03-30 00:00:00.000000', 1.23, 72)
2018-05-08 18:31:23,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,382 INFO sqlalchemy.engine.base.Engine ('2014-03-31 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:23,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,383 INFO sqlalchemy.engine.base.Engine ('2014-04-01 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:23,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,385 INFO sqlalchemy.engine.base.Engine ('2014-04-02 00:00:00.000000', 0.66, 71)
2018-05-08 18:31:23,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,386 INFO sqlalchemy.engine.base.Engine ('2014-04-03 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:23,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,388 INFO sqlalchemy.engine.base.Engine ('2014-04-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:23,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,390 INFO sqlalchemy.engine.base.Engine ('2014-04-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:23,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,392 INFO sqlalchemy.engine.base.Engine ('2014-04-06 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:23,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,394 INFO sqlalchemy.engine.base.Engine ('2014-04-07 00:00:00.000000', 0.3, 66)
2018-05-08 18:31:23,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,395 INFO sqlalchemy.engine.base.Engine ('2014-04-08 00:00:00.000000', 0.32, 73)

2018-05-08 18:31:23,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,397 INFO sqlalchemy.engine.base.Engine ('2014-04-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:23,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,399 INFO sqlalchemy.engine.base.Engine ('2014-04-10 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:23,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,400 INFO sqlalchemy.engine.base.Engine ('2014-04-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:23,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,402 INFO sqlalchemy.engine.base.Engine ('2014-04-12 00:00:00.000000', 0.37, 71)
2018-05-08 18:31:23,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,403 INFO sqlalchemy.engine.base.Engine ('2014-04-13 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:23,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,405 INFO sqlalchemy.engine.base.Engine ('2014-04-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:23,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,407 INFO sqlalchemy.engine.base.Engine ('2014-04-15 00:00:00.000000', 0.1, 68)
2018-05-08 18:31:23,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,408 INFO sqlalchemy.engine.base.Engine ('2014-04-16 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:23,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,410 INFO sqlalchemy.engine.base.Engine ('2014-04-17 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:23,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,462 INFO sqlalchemy.engine.base.Engine ('2014-04-18 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:23,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,464 INFO sqlalchemy.engine.base.Engine ('2014-04-19 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:23,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,466 INFO sqlalchemy.engine.base.Engine ('2014-04-20 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:23,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,468 INFO sqlalchemy.engine.base.Engine ('2014-04-21 00:00:00.000000', 0.22, 72)
2018-05-08 18:31:23,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,469 INFO sqlalchemy.engine.base.Engine ('2014-04-22 00:00:00.000000', 0.24, 71)
2018-05-08 18:31:23,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,471 INFO sqlalchemy.engine.base.Engine ('2014-04-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:23,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,472 INFO sqlalchemy.engine.base.Engine ('2014-04-24 00:00:00.000000', 0.22, 69)
2018-05-08 18:31:23,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,474 INFO sqlalchemy.engine.base.Engine ('2014-04-25 00:00:00.000000', 0.2, 71)
2018-05-08 18:31:23,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,476 INFO sqlalchemy.engine.base.Engine ('2014-04-26 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:23,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,477 INFO sqlalchemy.engine.base.Engine ('2014-04-27 00:00:00.000000', 0.68, 70)
2018-05-08 18:31:23,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,478 INFO sqlalchemy.engine.base.Engine ('2014-04-28 00:00:00.000000', 0.42, 66)
2018-05-08 18:31:23,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,480 INFO sqlalchemy.engine.base.Engine ('2014-04-29 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:23,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,481 INFO sqlalchemy.engine.base.Engine ('2014-04-30 00:00:00.000000', 0.22, 68)
2018-05-08 18:31:23,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,483 INFO sqlalchemy.engine.base.Engine ('2014-05-01 00:00:00.000000', 0.06, 68)
2018-05-08 18:31:23,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,484 INFO sqlalchemy.engine.base.Engine ('2014-05-02 00:00:00.000000', 0.36, 69)
2018-05-08 18:31:23,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,486 INFO sqlalchemy.engine.base.Engine ('2014-05-03 00:00:00.000000', 0.57, 76)
2018-05-08 18:31:23,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,487 INFO sqlalchemy.engine.base.Engine ('2014-05-04 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:23,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,489 INFO sqlalchemy.engine.base.Engine ('2014-05-05 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:23,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,490 INFO sqlalchemy.engine.base.Engine ('2014-05-06 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:23,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,492 INFO sqlalchemy.engine.base.Engine ('2014-05-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:23,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,493 INFO sqlalchemy.engine.base.Engine ('2014-05-08 00:00:00.000000', 0.33, 67)
2018-05-08 18:31:23,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,495 INFO sqlalchemy.engine.base.Engine ('2014-05-09 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:23,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,496 INFO sqlalchemy.engine.base.Engine ('2014-05-10 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:23,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,498 INFO sqlalchemy.engine.base.Engine ('2014-05-11 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:23,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,500 INFO sqlalchemy.engine.base.Engine ('2014-05-12 00:00:00.000000', 1.02, 70)
2018-05-08 18:31:23,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,502 INFO sqlalchemy.engine.base.Engine ('2014-05-13 00:00:00.000000', 0.11, 68)

2018-05-08 18:31:23,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,504 INFO sqlalchemy.engine.base.Engine ('2014-05-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:23,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,505 INFO sqlalchemy.engine.base.Engine ('2014-05-15 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:23,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,507 INFO sqlalchemy.engine.base.Engine ('2014-05-16 00:00:00.000000', 0.43, 69)
2018-05-08 18:31:23,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,508 INFO sqlalchemy.engine.base.Engine ('2014-05-17 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:23,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,510 INFO sqlalchemy.engine.base.Engine ('2014-05-18 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:23,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,511 INFO sqlalchemy.engine.base.Engine ('2014-05-19 00:00:00.000000', 0.03, 65)
2018-05-08 18:31:23,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,513 INFO sqlalchemy.engine.base.Engine ('2014-05-20 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:23,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,514 INFO sqlalchemy.engine.base.Engine ('2014-05-21 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:23,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,516 INFO sqlalchemy.engine.base.Engine ('2014-05-22 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:23,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,517 INFO sqlalchemy.engine.base.Engine ('2014-05-23 00:00:00.000000', 0.33, 81)
2018-05-08 18:31:23,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,519 INFO sqlalchemy.engine.base.Engine ('2014-05-24 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:23,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,520 INFO sqlalchemy.engine.base.Engine ('2014-05-25 00:00:00.000000', 1.37, 71)
2018-05-08 18:31:23,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,522 INFO sqlalchemy.engine.base.Engine ('2014-05-26 00:00:00.000000', 0.46, 72)
2018-05-08 18:31:23,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,523 INFO sqlalchemy.engine.base.Engine ('2014-05-27 00:00:00.000000', 0.35, 72)
2018-05-08 18:31:23,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,524 INFO sqlalchemy.engine.base.Engine ('2014-05-28 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:23,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,526 INFO sqlalchemy.engine.base.Engine ('2014-05-29 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:23,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,528 INFO sqlalchemy.engine.base.Engine ('2014-05-30 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:23,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,529 INFO sqlalchemy.engine.base.Engine ('2014-05-31 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:23,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,531 INFO sqlalchemy.engine.base.Engine ('2014-06-01 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:23,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,533 INFO sqlalchemy.engine.base.Engine ('2014-06-02 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:23,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,534 INFO sqlalchemy.engine.base.Engine ('2014-06-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:23,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,536 INFO sqlalchemy.engine.base.Engine ('2014-06-04 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:23,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:23,538 INFO sqlalchemy.engine.base.Engine ('2014-06-05 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:24,278 INFO sqlalchemy.engine.base.Engine ('2015-06-27 00:00:00.000000', 0.21, 74)
2018-05-08 18:31:24,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,279 INFO sqlalchemy.engine.base.Engine ('2015-06-28 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:24,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,281 INFO sqlalchemy.engine.base.Engine ('2015-06-29 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:24,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,282 INFO sqlalchemy.engine.base.Engine ('2015-06-30 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:24,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,284 INFO sqlalchemy.engine.base.Engine ('2015-07-01 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:24,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,286 INFO sqlalchemy.engine.base.Engine ('2015-07-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:24,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,287 INFO sqlalchemy.engine.base.Engine ('2015-07-03 00:00:00.000000', 0.28, 73)
2018-05-08 18:31:24,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,289 INFO sqlalchemy.engine.base.Engine ('2015-07-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:24,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,291 INFO sqlalchemy.engine.base.Engine ('2015-07-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:24,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,292 INFO sqlalchemy.engine.base.Engine ('2015-07-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,294 INFO sqlalchemy.engine.base.Engine ('2015-07-07 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:24,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,296 INFO sqlalchemy.engine.base.Engine ('2015-07-08 00:00:00.000000', 0.32, 75)
2018-05-08 18:31:24,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:24,297 INFO sqlalchemy.engine.base.Engine ('2015-07-09 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:24,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,299 INFO sqlalchemy.engine.base.Engine ('2015-07-10 00:00:00.000000', 0.48, 76)
2018-05-08 18:31:24,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,300 INFO sqlalchemy.engine.base.Engine ('2015-07-11 00:00:00.000000', 0.57, 77)
2018-05-08 18:31:24,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,302 INFO sqlalchemy.engine.base.Engine ('2015-07-12 00:00:00.000000', 0.27, 82)
2018-05-08 18:31:24,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,304 INFO sqlalchemy.engine.base.Engine ('2015-07-13 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:24,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,306 INFO sqlalchemy.engine.base.Engine ('2015-07-14 00:00:00.000000', 0.47, 73)
2018-05-08 18:31:24,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,308 INFO sqlalchemy.engine.base.Engine ('2015-07-15 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:24,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,309 INFO sqlalchemy.engine.base.Engine ('2015-07-16 00:00:00.000000', 0.41, 74)
2018-05-08 18:31:24,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,311 INFO sqlalchemy.engine.base.Engine ('2015-07-17 00:00:00.000000', 0.69, 75)
2018-05-08 18:31:24,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,313 INFO sqlalchemy.engine.base.Engine ('2015-07-18 00:00:00.000000', 0.27, 83)
2018-05-08 18:31:24,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,315 INFO sqlalchemy.engine.base.Engine ('2015-07-19 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:24,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,317 INFO sqlalchemy.engine.base.Engine ('2015-07-20 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:24,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,318 INFO sqlalchemy.engine.base.Engine ('2015-07-21 00:00:00.000000', 0.26, 73)
2018-05-08 18:31:24,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,320 INFO sqlalchemy.engine.base.Engine ('2015-07-22 00:00:00.000000', 0.31, 76)
2018-05-08 18:31:24,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,323 INFO sqlalchemy.engine.base.Engine ('2015-07-23 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:24,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,324 INFO sqlalchemy.engine.base.Engine ('2015-07-24 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:24,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,326 INFO sqlalchemy.engine.base.Engine ('2015-07-25 00:00:00.000000', 0.1, 78)
2018-05-08 18:31:24,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,328 INFO sqlalchemy.engine.base.Engine ('2015-07-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:24,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,330 INFO sqlalchemy.engine.base.Engine ('2015-07-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,331 INFO sqlalchemy.engine.base.Engine ('2015-07-28 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:24,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,333 INFO sqlalchemy.engine.base.Engine ('2015-07-29 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:24,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,336 INFO sqlalchemy.engine.base.Engine ('2015-07-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,337 INFO sqlalchemy.engine.base.Engine ('2015-07-31 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:24,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,339 INFO sqlalchemy.engine.base.Engine ('2015-08-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:24,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,340 INFO sqlalchemy.engine.base.Engine ('2015-08-02 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:24,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,342 INFO sqlalchemy.engine.base.Engine ('2015-08-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,344 INFO sqlalchemy.engine.base.Engine ('2015-08-04 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:24,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,346 INFO sqlalchemy.engine.base.Engine ('2015-08-05 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:24,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,347 INFO sqlalchemy.engine.base.Engine ('2015-08-06 00:00:00.000000', 0.47, 74)
2018-05-08 18:31:24,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,349 INFO sqlalchemy.engine.base.Engine ('2015-08-07 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:24,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,351 INFO sqlalchemy.engine.base.Engine ('2015-08-08 00:00:00.000000', 0.16, 80)
2018-05-08 18:31:24,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,352 INFO sqlalchemy.engine.base.Engine ('2015-08-09 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:24,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,354 INFO sqlalchemy.engine.base.Engine ('2015-08-10 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:24,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,355 INFO sqlalchemy.engine.base.Engine ('2015-08-11 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:24,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,357 INFO sqlalchemy.engine.base.Engine ('2015-08-12 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:24,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:24,359 INFO sqlalchemy.engine.base.Engine ('2015-08-13 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:24,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,360 INFO sqlalchemy.engine.base.Engine ('2015-08-14 00:00:00.000000', 0.43, 75)
2018-05-08 18:31:24,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,362 INFO sqlalchemy.engine.base.Engine ('2015-08-15 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:24,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,363 INFO sqlalchemy.engine.base.Engine ('2015-08-16 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:24,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,365 INFO sqlalchemy.engine.base.Engine ('2015-08-17 00:00:00.000000', 0.24, 78)
2018-05-08 18:31:24,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,367 INFO sqlalchemy.engine.base.Engine ('2015-08-18 00:00:00.000000', 0.89, 76)
2018-05-08 18:31:24,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,368 INFO sqlalchemy.engine.base.Engine ('2015-08-19 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:24,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,370 INFO sqlalchemy.engine.base.Engine ('2015-08-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:24,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,372 INFO sqlalchemy.engine.base.Engine ('2015-08-21 00:00:00.000000', 1.62, 77)
2018-05-08 18:31:24,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,374 INFO sqlalchemy.engine.base.Engine ('2015-08-22 00:00:00.000000', 0.03, 80)
2018-05-08 18:31:24,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,375 INFO sqlalchemy.engine.base.Engine ('2015-08-23 00:00:00.000000', 2.86, 80)
2018-05-08 18:31:24,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,377 INFO sqlalchemy.engine.base.Engine ('2015-08-24 00:00:00.000000', 3.62, 72)
2018-05-08 18:31:24,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,378 INFO sqlalchemy.engine.base.Engine ('2015-08-25 00:00:00.000000', 0.31, 79)
2018-05-08 18:31:24,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,380 INFO sqlalchemy.engine.base.Engine ('2015-08-26 00:00:00.000000', 0.6, 72)
2018-05-08 18:31:24,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,382 INFO sqlalchemy.engine.base.Engine ('2015-08-27 00:00:00.000000', 2.96, 75)
2018-05-08 18:31:24,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,383 INFO sqlalchemy.engine.base.Engine ('2015-08-28 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:24,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,385 INFO sqlalchemy.engine.base.Engine ('2015-08-29 00:00:00.000000', 0.01, 82)
2018-05-08 18:31:24,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,386 INFO sqlalchemy.engine.base.Engine ('2015-08-30 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:24,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,435 INFO sqlalchemy.engine.base.Engine ('2015-08-31 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:24,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,437 INFO sqlalchemy.engine.base.Engine ('2015-09-01 00:00:00.000000', 0.3, 76)
2018-05-08 18:31:24,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,439 INFO sqlalchemy.engine.base.Engine ('2015-09-02 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:24,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,440 INFO sqlalchemy.engine.base.Engine ('2015-09-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,442 INFO sqlalchemy.engine.base.Engine ('2015-09-04 00:00:00.000000', 1.35, 75)
2018-05-08 18:31:24,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,443 INFO sqlalchemy.engine.base.Engine ('2015-09-05 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:24,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,445 INFO sqlalchemy.engine.base.Engine ('2015-09-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:24,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,447 INFO sqlalchemy.engine.base.Engine ('2015-09-07 00:00:00.000000', 0.97, 81)
2018-05-08 18:31:24,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,448 INFO sqlalchemy.engine.base.Engine ('2015-09-08 00:00:00.000000', 0.74, 81)
2018-05-08 18:31:24,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,450 INFO sqlalchemy.engine.base.Engine ('2015-09-09 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:24,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,452 INFO sqlalchemy.engine.base.Engine ('2015-09-10 00:00:00.000000', 0.09, 85)
2018-05-08 18:31:24,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,453 INFO sqlalchemy.engine.base.Engine ('2015-09-11 00:00:00.000000', 0.69, 80)
2018-05-08 18:31:24,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,455 INFO sqlalchemy.engine.base.Engine ('2015-09-12 00:00:00.000000', 3.1, 79)
2018-05-08 18:31:24,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,456 INFO sqlalchemy.engine.base.Engine ('2015-09-13 00:00:00.000000', 0.26, 81)
2018-05-08 18:31:24,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,458 INFO sqlalchemy.engine.base.Engine ('2015-09-14 00:00:00.000000', 0.52, 79)
2018-05-08 18:31:24,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,459 INFO sqlalchemy.engine.base.Engine ('2015-09-15 00:00:00.000000', 1.61, 76)
2018-05-08 18:31:24,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,461 INFO sqlalchemy.engine.base.Engine ('2015-09-16 00:00:00.000000', 0.41, 80)
2018-05-08 18:31:24,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:24,462 INFO sqlalchemy.engine.base.Engine ('2015-09-17 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:24,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,464 INFO sqlalchemy.engine.base.Engine ('2015-09-18 00:00:00.000000', 0.42, 80)
2018-05-08 18:31:24,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,465 INFO sqlalchemy.engine.base.Engine ('2015-09-19 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:24,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,467 INFO sqlalchemy.engine.base.Engine ('2015-09-20 00:00:00.000000', 0.25, 79)
2018-05-08 18:31:24,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,468 INFO sqlalchemy.engine.base.Engine ('2015-09-21 00:00:00.000000', 0.63, 80)
2018-05-08 18:31:24,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,470 INFO sqlalchemy.engine.base.Engine ('2015-09-22 00:00:00.000000', 0.37, 80)
2018-05-08 18:31:24,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,471 INFO sqlalchemy.engine.base.Engine ('2015-09-23 00:00:00.000000', 0.48, 77)
2018-05-08 18:31:24,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,473 INFO sqlalchemy.engine.base.Engine ('2015-09-24 00:00:00.000000', 0.11, 77)
2018-05-08 18:31:24,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,475 INFO sqlalchemy.engine.base.Engine ('2015-09-25 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:24,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,476 INFO sqlalchemy.engine.base.Engine ('2015-09-26 00:00:00.000000', 0.49, 75)
2018-05-08 18:31:24,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,478 INFO sqlalchemy.engine.base.Engine ('2015-09-27 00:00:00.000000', 0.45, 74)
2018-05-08 18:31:24,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,479 INFO sqlalchemy.engine.base.Engine ('2015-09-28 00:00:00.000000', 0.77, 77)
2018-05-08 18:31:24,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,481 INFO sqlalchemy.engine.base.Engine ('2015-09-29 00:00:00.000000', 0.8, 78)
2018-05-08 18:31:24,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,482 INFO sqlalchemy.engine.base.Engine ('2015-09-30 00:00:00.000000', 0.14, 80)
2018-05-08 18:31:24,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,484 INFO sqlalchemy.engine.base.Engine ('2015-10-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:24,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,485 INFO sqlalchemy.engine.base.Engine ('2015-10-02 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:24,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,487 INFO sqlalchemy.engine.base.Engine ('2015-10-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:24,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,488 INFO sqlalchemy.engine.base.Engine ('2015-10-04 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:24,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,489 INFO sqlalchemy.engine.base.Engine ('2015-10-05 00:00:00.000000', 1.46, 75)
2018-05-08 18:31:24,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,491 INFO sqlalchemy.engine.base.Engine ('2015-10-06 00:00:00.000000', 0.19, 75)
2018-05-08 18:31:24,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,492 INFO sqlalchemy.engine.base.Engine ('2015-10-07 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:24,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,494 INFO sqlalchemy.engine.base.Engine ('2015-10-08 00:00:00.000000', 0.09, 66)
2018-05-08 18:31:24,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,495 INFO sqlalchemy.engine.base.Engine ('2015-10-09 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:24,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,497 INFO sqlalchemy.engine.base.Engine ('2015-10-11 00:00:00.000000', 0.8, 76)
2018-05-08 18:31:24,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,498 INFO sqlalchemy.engine.base.Engine ('2015-10-12 00:00:00.000000', 0.41, 75)
2018-05-08 18:31:24,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,499 INFO sqlalchemy.engine.base.Engine ('2015-10-13 00:00:00.000000', 1.53, 73)
2018-05-08 18:31:24,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,501 INFO sqlalchemy.engine.base.Engine ('2015-10-14 00:00:00.000000', 0.39, 72)
2018-05-08 18:31:24,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,502 INFO sqlalchemy.engine.base.Engine ('2015-10-15 00:00:00.000000', 1.02, 77)
2018-05-08 18:31:24,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,504 INFO sqlalchemy.engine.base.Engine ('2015-10-16 00:00:00.000000', 1.33, 71)
2018-05-08 18:31:24,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,505 INFO sqlalchemy.engine.base.Engine ('2015-10-17 00:00:00.000000', 0.51, 79)
2018-05-08 18:31:24,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,507 INFO sqlalchemy.engine.base.Engine ('2015-10-18 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:24,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,508 INFO sqlalchemy.engine.base.Engine ('2015-10-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:24,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,510 INFO sqlalchemy.engine.base.Engine ('2015-10-20 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:24,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,512 INFO sqlalchemy.engine.base.Engine ('2015-10-21 00:00:00.000000', 0.33, 76)
2018-05-08 18:31:24,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,513 INFO sqlalchemy.engine.base.Engine ('2015-10-22 00:00:00.000000', 0.08, 73)

2018-05-08 18:31:24,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,515 INFO sqlalchemy.engine.base.Engine ('2015-10-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:24,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,517 INFO sqlalchemy.engine.base.Engine ('2015-10-24 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:24,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,518 INFO sqlalchemy.engine.base.Engine ('2015-10-25 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:24,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,520 INFO sqlalchemy.engine.base.Engine ('2015-10-26 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:24,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,521 INFO sqlalchemy.engine.base.Engine ('2015-10-27 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:24,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,523 INFO sqlalchemy.engine.base.Engine ('2015-10-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:24,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,524 INFO sqlalchemy.engine.base.Engine ('2015-10-29 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:24,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,526 INFO sqlalchemy.engine.base.Engine ('2015-10-30 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:24,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,528 INFO sqlalchemy.engine.base.Engine ('2015-10-31 00:00:00.000000', 0.38, 78)
2018-05-08 18:31:24,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,529 INFO sqlalchemy.engine.base.Engine ('2015-11-01 00:00:00.000000', 0.78, 79)
2018-05-08 18:31:24,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,530 INFO sqlalchemy.engine.base.Engine ('2015-11-02 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:24,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,532 INFO sqlalchemy.engine.base.Engine ('2015-11-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,533 INFO sqlalchemy.engine.base.Engine ('2015-11-04 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:24,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,535 INFO sqlalchemy.engine.base.Engine ('2015-11-05 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:24,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,536 INFO sqlalchemy.engine.base.Engine ('2015-11-06 00:00:00.000000', 0.29, 73)
2018-05-08 18:31:24,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,538 INFO sqlalchemy.engine.base.Engine ('2015-11-07 00:00:00.000000', 0.46, 74)
2018-05-08 18:31:24,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,540 INFO sqlalchemy.engine.base.Engine ('2015-11-08 00:00:00.000000', 0.36, 79)
2018-05-08 18:31:24,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,541 INFO sqlalchemy.engine.base.Engine ('2015-11-09 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:24,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,543 INFO sqlalchemy.engine.base.Engine ('2015-11-10 00:00:00.000000', 0.47, 76)
2018-05-08 18:31:24,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,544 INFO sqlalchemy.engine.base.Engine ('2015-11-11 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:24,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,546 INFO sqlalchemy.engine.base.Engine ('2015-11-12 00:00:00.000000', 0.34, 72)
2018-05-08 18:31:24,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,548 INFO sqlalchemy.engine.base.Engine ('2015-11-13 00:00:00.000000', 0.17, 73)
2018-05-08 18:31:24,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,550 INFO sqlalchemy.engine.base.Engine ('2015-11-14 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:24,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,551 INFO sqlalchemy.engine.base.Engine ('2015-11-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:24,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,553 INFO sqlalchemy.engine.base.Engine ('2015-11-16 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:24,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,554 INFO sqlalchemy.engine.base.Engine ('2015-11-17 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:24,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,556 INFO sqlalchemy.engine.base.Engine ('2015-11-18 00:00:00.000000', 0.34, 67)
2018-05-08 18:31:24,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,557 INFO sqlalchemy.engine.base.Engine ('2015-11-19 00:00:00.000000', 0.2, 73)
2018-05-08 18:31:24,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,559 INFO sqlalchemy.engine.base.Engine ('2015-11-20 00:00:00.000000', 1.87, 71)
2018-05-08 18:31:24,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,560 INFO sqlalchemy.engine.base.Engine ('2015-11-21 00:00:00.000000', 2.17, 72)
2018-05-08 18:31:24,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,563 INFO sqlalchemy.engine.base.Engine ('2015-11-22 00:00:00.000000', 0.85, 78)
2018-05-08 18:31:24,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,565 INFO sqlalchemy.engine.base.Engine ('2015-11-23 00:00:00.000000', 1.17, 73)
2018-05-08 18:31:24,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,566 INFO sqlalchemy.engine.base.Engine ('2015-11-24 00:00:00.000000', 0.98, 70)
2018-05-08 18:31:24,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,568 INFO sqlalchemy.engine.base.Engine ('2015-11-25 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:24,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,569 INFO sqlalchemy.engine.base.Engine ('2015-11-26 00:00:00.000000', 0.82, 75)

2018-05-08 18:31:24,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,571 INFO sqlalchemy.engine.base.Engine ('2015-11-27 00:00:00.000000', 0.72, 74)
2018-05-08 18:31:24,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,572 INFO sqlalchemy.engine.base.Engine ('2015-11-28 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:24,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,574 INFO sqlalchemy.engine.base.Engine ('2015-11-29 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:24,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,575 INFO sqlalchemy.engine.base.Engine ('2015-11-30 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:24,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,577 INFO sqlalchemy.engine.base.Engine ('2015-12-01 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:24,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,578 INFO sqlalchemy.engine.base.Engine ('2015-12-02 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:24,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,581 INFO sqlalchemy.engine.base.Engine ('2015-12-03 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:24,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,582 INFO sqlalchemy.engine.base.Engine ('2015-12-04 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:24,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,584 INFO sqlalchemy.engine.base.Engine ('2015-12-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:24,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,586 INFO sqlalchemy.engine.base.Engine ('2015-12-06 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:24,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,588 INFO sqlalchemy.engine.base.Engine ('2015-12-07 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:24,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,589 INFO sqlalchemy.engine.base.Engine ('2015-12-08 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:24,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,591 INFO sqlalchemy.engine.base.Engine ('2015-12-09 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:24,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,637 INFO sqlalchemy.engine.base.Engine ('2015-12-10 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:24,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,639 INFO sqlalchemy.engine.base.Engine ('2015-12-11 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:24,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,640 INFO sqlalchemy.engine.base.Engine ('2015-12-12 00:00:00.000000', 0.31, 79)
2018-05-08 18:31:24,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,642 INFO sqlalchemy.engine.base.Engine ('2015-12-13 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:24,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,643 INFO sqlalchemy.engine.base.Engine ('2015-12-14 00:00:00.000000', 0.13, 67)
2018-05-08 18:31:24,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,645 INFO sqlalchemy.engine.base.Engine ('2015-12-15 00:00:00.000000', 0.35, 73)
2018-05-08 18:31:24,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,646 INFO sqlalchemy.engine.base.Engine ('2015-12-16 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:24,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,648 INFO sqlalchemy.engine.base.Engine ('2015-12-17 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:24,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,649 INFO sqlalchemy.engine.base.Engine ('2015-12-18 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:24,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,651 INFO sqlalchemy.engine.base.Engine ('2015-12-19 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:24,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,652 INFO sqlalchemy.engine.base.Engine ('2015-12-20 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:24,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,655 INFO sqlalchemy.engine.base.Engine ('2015-12-21 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:24,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,656 INFO sqlalchemy.engine.base.Engine ('2015-12-22 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:24,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,657 INFO sqlalchemy.engine.base.Engine ('2015-12-23 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:24,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,659 INFO sqlalchemy.engine.base.Engine ('2015-12-24 00:00:00.000000', 0.45, 76)
2018-05-08 18:31:24,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,660 INFO sqlalchemy.engine.base.Engine ('2015-12-25 00:00:00.000000', 0.47, 74)
2018-05-08 18:31:24,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,662 INFO sqlalchemy.engine.base.Engine ('2015-12-26 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:24,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,663 INFO sqlalchemy.engine.base.Engine ('2015-12-27 00:00:00.000000', 0.8, 75)
2018-05-08 18:31:24,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,665 INFO sqlalchemy.engine.base.Engine ('2015-12-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:24,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,666 INFO sqlalchemy.engine.base.Engine ('2015-12-29 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:24,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,668 INFO sqlalchemy.engine.base.Engine ('2015-12-30 00:00:00.000000', 0.5, 74)
2018-05-08 18:31:24,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,669 INFO sqlalchemy.engine.base.Engine ('2015-12-31 00:00:00.000000', 0.09, 73)

2018-05-08 18:31:24,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,671 INFO sqlalchemy.engine.base.Engine ('2016-01-01 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:24,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,672 INFO sqlalchemy.engine.base.Engine ('2016-01-02 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:24,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,674 INFO sqlalchemy.engine.base.Engine ('2016-01-03 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:24,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,675 INFO sqlalchemy.engine.base.Engine ('2016-01-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,676 INFO sqlalchemy.engine.base.Engine ('2016-01-05 00:00:00.000000', 0.18, 70)
2018-05-08 18:31:24,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,678 INFO sqlalchemy.engine.base.Engine ('2016-01-06 00:00:00.000000', 0.35, 69)
2018-05-08 18:31:24,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,679 INFO sqlalchemy.engine.base.Engine ('2016-01-07 00:00:00.000000', 0.35, 76)
2018-05-08 18:31:24,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,681 INFO sqlalchemy.engine.base.Engine ('2016-01-08 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:24,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,682 INFO sqlalchemy.engine.base.Engine ('2016-01-09 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:24,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,684 INFO sqlalchemy.engine.base.Engine ('2016-01-10 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:24,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,686 INFO sqlalchemy.engine.base.Engine ('2016-01-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:24,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,687 INFO sqlalchemy.engine.base.Engine ('2016-01-12 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:24,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,688 INFO sqlalchemy.engine.base.Engine ('2016-01-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,690 INFO sqlalchemy.engine.base.Engine ('2016-01-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:24,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,691 INFO sqlalchemy.engine.base.Engine ('2016-01-15 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:24,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,693 INFO sqlalchemy.engine.base.Engine ('2016-01-16 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:24,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,694 INFO sqlalchemy.engine.base.Engine ('2016-01-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,696 INFO sqlalchemy.engine.base.Engine ('2016-01-18 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:24,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,698 INFO sqlalchemy.engine.base.Engine ('2016-01-19 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:24,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,699 INFO sqlalchemy.engine.base.Engine ('2016-01-20 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:24,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,701 INFO sqlalchemy.engine.base.Engine ('2016-01-21 00:00:00.000000', 0.42, 65)
2018-05-08 18:31:24,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,702 INFO sqlalchemy.engine.base.Engine ('2016-01-22 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:24,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,704 INFO sqlalchemy.engine.base.Engine ('2016-01-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,705 INFO sqlalchemy.engine.base.Engine ('2016-01-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:24,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,707 INFO sqlalchemy.engine.base.Engine ('2016-01-25 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:24,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,708 INFO sqlalchemy.engine.base.Engine ('2016-01-26 00:00:00.000000', 0.74, 65)
2018-05-08 18:31:24,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,710 INFO sqlalchemy.engine.base.Engine ('2016-01-27 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:24,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,712 INFO sqlalchemy.engine.base.Engine ('2016-01-28 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:24,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,713 INFO sqlalchemy.engine.base.Engine ('2016-01-29 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:24,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,715 INFO sqlalchemy.engine.base.Engine ('2016-01-30 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:24,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,716 INFO sqlalchemy.engine.base.Engine ('2016-01-31 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:24,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,718 INFO sqlalchemy.engine.base.Engine ('2016-02-01 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:24,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,719 INFO sqlalchemy.engine.base.Engine ('2016-02-02 00:00:00.000000', 0.42, 68)
2018-05-08 18:31:24,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,721 INFO sqlalchemy.engine.base.Engine ('2016-02-03 00:00:00.000000', 0.2, 69)
2018-05-08 18:31:24,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,723 INFO sqlalchemy.engine.base.Engine ('2016-02-04 00:00:00.000000', 0.04, 65)

2018-05-08 18:31:24,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,724 INFO sqlalchemy.engine.base.Engine ('2016-02-05 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:24,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,726 INFO sqlalchemy.engine.base.Engine ('2016-02-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,727 INFO sqlalchemy.engine.base.Engine ('2016-02-07 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:24,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,729 INFO sqlalchemy.engine.base.Engine ('2016-02-08 00:00:00.000000', 0.0, 56)
2018-05-08 18:31:24,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,730 INFO sqlalchemy.engine.base.Engine ('2016-02-09 00:00:00.000000', 0.0, 57)
2018-05-08 18:31:24,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,732 INFO sqlalchemy.engine.base.Engine ('2016-02-10 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:24,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,733 INFO sqlalchemy.engine.base.Engine ('2016-02-11 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:24,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,734 INFO sqlalchemy.engine.base.Engine ('2016-02-12 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:24,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,736 INFO sqlalchemy.engine.base.Engine ('2016-02-13 00:00:00.000000', 0.22, 74)
2018-05-08 18:31:24,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,738 INFO sqlalchemy.engine.base.Engine ('2016-02-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:24,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,739 INFO sqlalchemy.engine.base.Engine ('2016-02-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,741 INFO sqlalchemy.engine.base.Engine ('2016-02-16 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:24,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,743 INFO sqlalchemy.engine.base.Engine ('2016-02-17 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:24,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,744 INFO sqlalchemy.engine.base.Engine ('2016-02-18 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:24,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,746 INFO sqlalchemy.engine.base.Engine ('2016-02-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,747 INFO sqlalchemy.engine.base.Engine ('2016-02-20 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:24,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,749 INFO sqlalchemy.engine.base.Engine ('2016-02-21 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:24,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,751 INFO sqlalchemy.engine.base.Engine ('2016-02-22 00:00:00.000000', 0.04, 60)
2018-05-08 18:31:24,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,752 INFO sqlalchemy.engine.base.Engine ('2016-02-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,754 INFO sqlalchemy.engine.base.Engine ('2016-02-24 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:24,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,755 INFO sqlalchemy.engine.base.Engine ('2016-02-25 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:24,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,757 INFO sqlalchemy.engine.base.Engine ('2016-02-26 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:24,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,759 INFO sqlalchemy.engine.base.Engine ('2016-02-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,760 INFO sqlalchemy.engine.base.Engine ('2016-02-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:24,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,762 INFO sqlalchemy.engine.base.Engine ('2016-02-29 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,763 INFO sqlalchemy.engine.base.Engine ('2016-03-01 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:24,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,765 INFO sqlalchemy.engine.base.Engine ('2016-03-02 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:24,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,766 INFO sqlalchemy.engine.base.Engine ('2016-03-03 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:24,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,768 INFO sqlalchemy.engine.base.Engine ('2016-03-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:24,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,769 INFO sqlalchemy.engine.base.Engine ('2016-03-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:24,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,771 INFO sqlalchemy.engine.base.Engine ('2016-03-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:24,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,772 INFO sqlalchemy.engine.base.Engine ('2016-03-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:24,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,774 INFO sqlalchemy.engine.base.Engine ('2016-03-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,775 INFO sqlalchemy.engine.base.Engine ('2016-03-09 00:00:00.000000', 0.34, 66)
2018-05-08 18:31:24,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,777 INFO sqlalchemy.engine.base.Engine ('2016-03-10 00:00:00.000000', 0.01, 68)

2018-05-08 18:31:24,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,778 INFO sqlalchemy.engine.base.Engine ('2016-03-11 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:24,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,780 INFO sqlalchemy.engine.base.Engine ('2016-03-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:24,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,781 INFO sqlalchemy.engine.base.Engine ('2016-03-13 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:24,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,783 INFO sqlalchemy.engine.base.Engine ('2016-03-14 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:24,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,784 INFO sqlalchemy.engine.base.Engine ('2016-03-15 00:00:00.000000', 0.82, 70)
2018-05-08 18:31:24,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,787 INFO sqlalchemy.engine.base.Engine ('2016-03-16 00:00:00.000000', 0.23, 68)
2018-05-08 18:31:24,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,788 INFO sqlalchemy.engine.base.Engine ('2016-03-17 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:24,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,790 INFO sqlalchemy.engine.base.Engine ('2016-03-18 00:00:00.000000', 0.08, 68)
2018-05-08 18:31:24,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,823 INFO sqlalchemy.engine.base.Engine ('2016-03-19 00:00:00.000000', 0.16, 68)
2018-05-08 18:31:24,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,824 INFO sqlalchemy.engine.base.Engine ('2016-03-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:24,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,826 INFO sqlalchemy.engine.base.Engine ('2016-03-21 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:24,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,828 INFO sqlalchemy.engine.base.Engine ('2016-03-22 00:00:00.000000', 0.1, 65)
2018-05-08 18:31:24,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,829 INFO sqlalchemy.engine.base.Engine ('2016-03-23 00:00:00.000000', 0.31, 63)
2018-05-08 18:31:24,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,831 INFO sqlalchemy.engine.base.Engine ('2016-03-24 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:24,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,832 INFO sqlalchemy.engine.base.Engine ('2016-03-25 00:00:00.000000', 0.38, 72)
2018-05-08 18:31:24,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,834 INFO sqlalchemy.engine.base.Engine ('2016-03-26 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:24,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,835 INFO sqlalchemy.engine.base.Engine ('2016-03-27 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:24,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,836 INFO sqlalchemy.engine.base.Engine ('2016-03-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:24,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,838 INFO sqlalchemy.engine.base.Engine ('2016-03-29 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:24,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,839 INFO sqlalchemy.engine.base.Engine ('2016-03-30 00:00:00.000000', 0.04, 62)
2018-05-08 18:31:24,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,841 INFO sqlalchemy.engine.base.Engine ('2016-03-31 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:24,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,842 INFO sqlalchemy.engine.base.Engine ('2016-04-01 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:24,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,844 INFO sqlalchemy.engine.base.Engine ('2016-04-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,845 INFO sqlalchemy.engine.base.Engine ('2016-04-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,847 INFO sqlalchemy.engine.base.Engine ('2016-04-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,849 INFO sqlalchemy.engine.base.Engine ('2016-04-05 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:24,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,850 INFO sqlalchemy.engine.base.Engine ('2016-04-06 00:00:00.000000', 0.34, 69)
2018-05-08 18:31:24,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,852 INFO sqlalchemy.engine.base.Engine ('2016-04-07 00:00:00.000000', 0.43, 65)
2018-05-08 18:31:24,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,853 INFO sqlalchemy.engine.base.Engine ('2016-04-08 00:00:00.000000', 1.26, 68)
2018-05-08 18:31:24,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,855 INFO sqlalchemy.engine.base.Engine ('2016-04-09 00:00:00.000000', 0.27, 74)
2018-05-08 18:31:24,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,856 INFO sqlalchemy.engine.base.Engine ('2016-04-10 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:24,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,858 INFO sqlalchemy.engine.base.Engine ('2016-04-11 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:24,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,860 INFO sqlalchemy.engine.base.Engine ('2016-04-12 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:24,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,861 INFO sqlalchemy.engine.base.Engine ('2016-04-13 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:24,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,863 INFO sqlalchemy.engine.base.Engine ('2016-04-14 00:00:00.000000', 0.05, 73)

2018-05-08 18:31:24,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,864 INFO sqlalchemy.engine.base.Engine ('2016-04-15 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:24,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,865 INFO sqlalchemy.engine.base.Engine ('2016-04-16 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:24,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,867 INFO sqlalchemy.engine.base.Engine ('2016-04-17 00:00:00.000000', 0.32, 71)
2018-05-08 18:31:24,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,868 INFO sqlalchemy.engine.base.Engine ('2016-04-18 00:00:00.000000', 0.83, 68)
2018-05-08 18:31:24,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,870 INFO sqlalchemy.engine.base.Engine ('2016-04-19 00:00:00.000000', 0.18, 67)
2018-05-08 18:31:24,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,872 INFO sqlalchemy.engine.base.Engine ('2016-04-20 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:24,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,873 INFO sqlalchemy.engine.base.Engine ('2016-04-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:24,874 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,874 INFO sqlalchemy.engine.base.Engine ('2016-04-22 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:24,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,876 INFO sqlalchemy.engine.base.Engine ('2016-04-23 00:00:00.000000', 0.23, 75)
2018-05-08 18:31:24,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,878 INFO sqlalchemy.engine.base.Engine ('2016-04-24 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:24,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,879 INFO sqlalchemy.engine.base.Engine ('2016-04-25 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:24,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,881 INFO sqlalchemy.engine.base.Engine ('2016-04-26 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:24,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,882 INFO sqlalchemy.engine.base.Engine ('2016-04-27 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:24,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,884 INFO sqlalchemy.engine.base.Engine ('2016-04-28 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:24,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,885 INFO sqlalchemy.engine.base.Engine ('2016-04-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,887 INFO sqlalchemy.engine.base.Engine ('2016-04-30 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:24,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,888 INFO sqlalchemy.engine.base.Engine ('2016-05-01 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:24,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,890 INFO sqlalchemy.engine.base.Engine ('2016-05-02 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:24,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,891 INFO sqlalchemy.engine.base.Engine ('2016-05-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,892 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,893 INFO sqlalchemy.engine.base.Engine ('2016-05-04 00:00:00.000000', 0.31, 72)
2018-05-08 18:31:24,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,894 INFO sqlalchemy.engine.base.Engine ('2016-05-05 00:00:00.000000', 0.91, 68)
2018-05-08 18:31:24,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,896 INFO sqlalchemy.engine.base.Engine ('2016-05-06 00:00:00.000000', 0.15, 66)
2018-05-08 18:31:24,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,897 INFO sqlalchemy.engine.base.Engine ('2016-05-07 00:00:00.000000', 1.02, 69)
2018-05-08 18:31:24,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,899 INFO sqlalchemy.engine.base.Engine ('2016-05-08 00:00:00.000000', 0.38, 67)
2018-05-08 18:31:24,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,900 INFO sqlalchemy.engine.base.Engine ('2016-05-09 00:00:00.000000', 0.13, 68)
2018-05-08 18:31:24,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,902 INFO sqlalchemy.engine.base.Engine ('2016-05-10 00:00:00.000000', 0.43, 68)
2018-05-08 18:31:24,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,904 INFO sqlalchemy.engine.base.Engine ('2016-05-11 00:00:00.000000', 0.16, 67)
2018-05-08 18:31:24,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,905 INFO sqlalchemy.engine.base.Engine ('2016-05-12 00:00:00.000000', 0.07, 65)
2018-05-08 18:31:24,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,907 INFO sqlalchemy.engine.base.Engine ('2016-05-13 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:24,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,908 INFO sqlalchemy.engine.base.Engine ('2016-05-14 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:24,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,910 INFO sqlalchemy.engine.base.Engine ('2016-05-15 00:00:00.000000', 0.17, 76)
2018-05-08 18:31:24,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,911 INFO sqlalchemy.engine.base.Engine ('2016-05-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,913 INFO sqlalchemy.engine.base.Engine ('2016-05-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:24,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,914 INFO sqlalchemy.engine.base.Engine ('2016-05-18 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:24,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,916 INFO sqlalchemy.engine.base.Engine ('2016-05-19 00:00:00.000000', 0.22, 75)

2018-05-08 18:31:24,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,917 INFO sqlalchemy.engine.base.Engine ('2016-05-20 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:24,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,919 INFO sqlalchemy.engine.base.Engine ('2016-05-21 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:24,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,920 INFO sqlalchemy.engine.base.Engine ('2016-05-22 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:24,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,922 INFO sqlalchemy.engine.base.Engine ('2016-05-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,923 INFO sqlalchemy.engine.base.Engine ('2016-05-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:24,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,924 INFO sqlalchemy.engine.base.Engine ('2016-05-25 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:24,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,926 INFO sqlalchemy.engine.base.Engine ('2016-05-26 00:00:00.000000', 1.04, 74)
2018-05-08 18:31:24,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,927 INFO sqlalchemy.engine.base.Engine ('2016-05-27 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:24,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,929 INFO sqlalchemy.engine.base.Engine ('2016-05-28 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:24,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,930 INFO sqlalchemy.engine.base.Engine ('2016-05-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:24,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,932 INFO sqlalchemy.engine.base.Engine ('2016-05-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:24,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,933 INFO sqlalchemy.engine.base.Engine ('2016-05-31 00:00:00.000000', 0.85, 70)
2018-05-08 18:31:24,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,935 INFO sqlalchemy.engine.base.Engine ('2016-06-01 00:00:00.000000', 1.39, 69)
2018-05-08 18:31:24,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,936 INFO sqlalchemy.engine.base.Engine ('2016-06-02 00:00:00.000000', 0.5, 67)
2018-05-08 18:31:24,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,938 INFO sqlalchemy.engine.base.Engine ('2016-06-03 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:24,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,940 INFO sqlalchemy.engine.base.Engine ('2016-06-04 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:24,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,942 INFO sqlalchemy.engine.base.Engine ('2016-06-05 00:00:00.000000', 0.22, 70)
2018-05-08 18:31:24,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,943 INFO sqlalchemy.engine.base.Engine ('2016-06-06 00:00:00.000000', 0.52, 72)
2018-05-08 18:31:24,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,945 INFO sqlalchemy.engine.base.Engine ('2016-06-07 00:00:00.000000', 0.35, 74)
2018-05-08 18:31:24,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,946 INFO sqlalchemy.engine.base.Engine ('2016-06-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:24,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,948 INFO sqlalchemy.engine.base.Engine ('2016-06-09 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:24,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,950 INFO sqlalchemy.engine.base.Engine ('2016-06-10 00:00:00.000000', 0.62, 75)
2018-05-08 18:31:24,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,951 INFO sqlalchemy.engine.base.Engine ('2016-06-11 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:24,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,952 INFO sqlalchemy.engine.base.Engine ('2016-06-12 00:00:00.000000', 0.28, 75)
2018-05-08 18:31:24,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,954 INFO sqlalchemy.engine.base.Engine ('2016-06-13 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:24,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,955 INFO sqlalchemy.engine.base.Engine ('2016-06-14 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:24,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,958 INFO sqlalchemy.engine.base.Engine ('2016-06-15 00:00:00.000000', 0.68, 76)
2018-05-08 18:31:24,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,959 INFO sqlalchemy.engine.base.Engine ('2016-06-16 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:24,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,961 INFO sqlalchemy.engine.base.Engine ('2016-06-17 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:24,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,962 INFO sqlalchemy.engine.base.Engine ('2016-06-18 00:00:00.000000', 0.4, 75)
2018-05-08 18:31:24,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,964 INFO sqlalchemy.engine.base.Engine ('2016-06-19 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:24,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,966 INFO sqlalchemy.engine.base.Engine ('2016-06-20 00:00:00.000000', 0.4, 72)
2018-05-08 18:31:24,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,967 INFO sqlalchemy.engine.base.Engine ('2016-06-21 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:24,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,969 INFO sqlalchemy.engine.base.Engine ('2016-06-22 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:24,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,970 INFO sqlalchemy.engine.base.Engine ('2016-06-23 00:00:00.000000', 0.39, 73)

2018-05-08 18:31:24,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,972 INFO sqlalchemy.engine.base.Engine ('2016-06-24 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:24,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,973 INFO sqlalchemy.engine.base.Engine ('2016-06-25 00:00:00.000000', 0.75, 74)
2018-05-08 18:31:24,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:24,975 INFO sqlalchemy.engine.base.Engine ('2016-06-26 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:25,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,015 INFO sqlalchemy.engine.base.Engine ('2016-06-27 00:00:00.000000', 0.37, 72)
2018-05-08 18:31:25,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,017 INFO sqlalchemy.engine.base.Engine ('2016-06-28 00:00:00.000000', 0.23, 71)
2018-05-08 18:31:25,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,019 INFO sqlalchemy.engine.base.Engine ('2016-06-29 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:25,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,020 INFO sqlalchemy.engine.base.Engine ('2016-06-30 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:25,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,022 INFO sqlalchemy.engine.base.Engine ('2016-07-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:25,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,023 INFO sqlalchemy.engine.base.Engine ('2016-07-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:25,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,025 INFO sqlalchemy.engine.base.Engine ('2016-07-03 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:25,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,026 INFO sqlalchemy.engine.base.Engine ('2016-07-04 00:00:00.000000', 0.27, 79)
2018-05-08 18:31:25,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,028 INFO sqlalchemy.engine.base.Engine ('2016-07-05 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:25,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,029 INFO sqlalchemy.engine.base.Engine ('2016-07-06 00:00:00.000000', 0.8, 74)
2018-05-08 18:31:25,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,031 INFO sqlalchemy.engine.base.Engine ('2016-07-07 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:25,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,032 INFO sqlalchemy.engine.base.Engine ('2016-07-08 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:25,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,034 INFO sqlalchemy.engine.base.Engine ('2016-07-09 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:25,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,035 INFO sqlalchemy.engine.base.Engine ('2016-07-10 00:00:00.000000', 0.63, 72)
2018-05-08 18:31:25,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,037 INFO sqlalchemy.engine.base.Engine ('2016-07-11 00:00:00.000000', 0.14, 79)
2018-05-08 18:31:25,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,039 INFO sqlalchemy.engine.base.Engine ('2016-07-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:25,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,040 INFO sqlalchemy.engine.base.Engine ('2016-07-13 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:25,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,042 INFO sqlalchemy.engine.base.Engine ('2016-07-14 00:00:00.000000', 0.8, 80)
2018-05-08 18:31:25,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,043 INFO sqlalchemy.engine.base.Engine ('2016-07-15 00:00:00.000000', 0.14, 80)
2018-05-08 18:31:25,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,045 INFO sqlalchemy.engine.base.Engine ('2016-07-16 00:00:00.000000', 0.92, 73)
2018-05-08 18:31:25,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,046 INFO sqlalchemy.engine.base.Engine ('2016-07-17 00:00:00.000000', 0.15, 77)
2018-05-08 18:31:25,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,048 INFO sqlalchemy.engine.base.Engine ('2016-07-18 00:00:00.000000', 0.23, 78)
2018-05-08 18:31:25,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,049 INFO sqlalchemy.engine.base.Engine ('2016-07-19 00:00:00.000000', 0.73, 79)
2018-05-08 18:31:25,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,050 INFO sqlalchemy.engine.base.Engine ('2016-07-20 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:25,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,052 INFO sqlalchemy.engine.base.Engine ('2016-07-21 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:25,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,053 INFO sqlalchemy.engine.base.Engine ('2016-07-22 00:00:00.000000', 0.13, 78)
2018-05-08 18:31:25,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,055 INFO sqlalchemy.engine.base.Engine ('2016-07-23 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:25,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,056 INFO sqlalchemy.engine.base.Engine ('2016-07-24 00:00:00.000000', 0.45, 76)
2018-05-08 18:31:25,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,058 INFO sqlalchemy.engine.base.Engine ('2016-07-25 00:00:00.000000', 9.64, 78)
2018-05-08 18:31:25,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,059 INFO sqlalchemy.engine.base.Engine ('2016-07-26 00:00:00.000000', 0.9, 78)
2018-05-08 18:31:25,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,061 INFO sqlalchemy.engine.base.Engine ('2016-07-27 00:00:00.000000', 0.06, 80)
2018-05-08 18:31:25,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,062 INFO sqlalchemy.engine.base.Engine ('2016-07-28 00:00:00.000000', 0.0, 81)

2018-05-08 18:31:25,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,064 INFO sqlalchemy.engine.base.Engine ('2016-07-29 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:25,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,065 INFO sqlalchemy.engine.base.Engine ('2016-07-30 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:25,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,067 INFO sqlalchemy.engine.base.Engine ('2016-07-31 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:25,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,068 INFO sqlalchemy.engine.base.Engine ('2016-08-01 00:00:00.000000', 3.53, 76)
2018-05-08 18:31:25,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,070 INFO sqlalchemy.engine.base.Engine ('2016-08-02 00:00:00.000000', 0.83, 76)
2018-05-08 18:31:25,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,071 INFO sqlalchemy.engine.base.Engine ('2016-08-03 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:25,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,073 INFO sqlalchemy.engine.base.Engine ('2016-08-04 00:00:00.000000', 0.77, 77)
2018-05-08 18:31:25,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,074 INFO sqlalchemy.engine.base.Engine ('2016-08-05 00:00:00.000000', 0.27, 81)
2018-05-08 18:31:25,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,076 INFO sqlalchemy.engine.base.Engine ('2016-08-06 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:25,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,077 INFO sqlalchemy.engine.base.Engine ('2016-08-07 00:00:00.000000', 0.47, 78)
2018-05-08 18:31:25,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,079 INFO sqlalchemy.engine.base.Engine ('2016-08-08 00:00:00.000000', 0.28, 81)
2018-05-08 18:31:25,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,081 INFO sqlalchemy.engine.base.Engine ('2016-08-09 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:25,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,082 INFO sqlalchemy.engine.base.Engine ('2016-08-10 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:25,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,084 INFO sqlalchemy.engine.base.Engine ('2016-08-11 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:25,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,085 INFO sqlalchemy.engine.base.Engine ('2016-08-12 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:25,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,087 INFO sqlalchemy.engine.base.Engine ('2016-08-13 00:00:00.000000', 0.08, 80)
2018-05-08 18:31:25,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,089 INFO sqlalchemy.engine.base.Engine ('2016-08-14 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:25,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,090 INFO sqlalchemy.engine.base.Engine ('2016-08-15 00:00:00.000000', 0.23, 75)
2018-05-08 18:31:25,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,092 INFO sqlalchemy.engine.base.Engine ('2016-08-16 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:25,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,093 INFO sqlalchemy.engine.base.Engine ('2016-08-17 00:00:00.000000', 0.31, 82)
2018-05-08 18:31:25,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,095 INFO sqlalchemy.engine.base.Engine ('2016-08-18 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:25,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,096 INFO sqlalchemy.engine.base.Engine ('2016-08-19 00:00:00.000000', 0.31, 79)
2018-05-08 18:31:25,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,097 INFO sqlalchemy.engine.base.Engine ('2016-08-20 00:00:00.000000', 0.13, 81)
2018-05-08 18:31:25,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,099 INFO sqlalchemy.engine.base.Engine ('2016-08-21 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:25,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,100 INFO sqlalchemy.engine.base.Engine ('2016-08-22 00:00:00.000000', 2.32, 78)
2018-05-08 18:31:25,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,102 INFO sqlalchemy.engine.base.Engine ('2016-08-23 00:00:00.000000', 1.79, 77)
2018-05-08 18:31:25,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,103 INFO sqlalchemy.engine.base.Engine ('2016-08-24 00:00:00.000000', 2.15, 77)
2018-05-08 18:31:25,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,105 INFO sqlalchemy.engine.base.Engine ('2016-08-25 00:00:00.000000', 0.06, 80)
2018-05-08 18:31:25,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,106 INFO sqlalchemy.engine.base.Engine ('2016-08-26 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:25,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,108 INFO sqlalchemy.engine.base.Engine ('2016-08-27 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:25,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,109 INFO sqlalchemy.engine.base.Engine ('2016-08-28 00:00:00.000000', 0.6, 73)
2018-05-08 18:31:25,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,111 INFO sqlalchemy.engine.base.Engine ('2016-08-29 00:00:00.000000', 0.35, 78)
2018-05-08 18:31:25,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,112 INFO sqlalchemy.engine.base.Engine ('2016-08-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:25,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,114 INFO sqlalchemy.engine.base.Engine ('2016-08-31 00:00:00.000000', 0.24, 78)
2018-05-08 18:31:25,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,115 INFO sqlalchemy.engine.base.Engine ('2016-09-01 00:00:00.000000', 0.02, 80)

2018-05-08 18:31:25,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,116 INFO sqlalchemy.engine.base.Engine ('2016-09-02 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:25,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,118 INFO sqlalchemy.engine.base.Engine ('2016-09-03 00:00:00.000000', 0.12, 78)
2018-05-08 18:31:25,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,119 INFO sqlalchemy.engine.base.Engine ('2016-09-04 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:25,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,121 INFO sqlalchemy.engine.base.Engine ('2016-09-05 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:25,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,122 INFO sqlalchemy.engine.base.Engine ('2016-09-06 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:25,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,124 INFO sqlalchemy.engine.base.Engine ('2016-09-07 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:25,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,125 INFO sqlalchemy.engine.base.Engine ('2016-09-08 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:25,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,127 INFO sqlalchemy.engine.base.Engine ('2016-09-09 00:00:00.000000', 0.16, 79)
2018-05-08 18:31:25,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,128 INFO sqlalchemy.engine.base.Engine ('2016-09-10 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:25,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,130 INFO sqlalchemy.engine.base.Engine ('2016-09-11 00:00:00.000000', 0.3, 80)
2018-05-08 18:31:25,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,131 INFO sqlalchemy.engine.base.Engine ('2016-09-12 00:00:00.000000', 0.31, 76)
2018-05-08 18:31:25,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,133 INFO sqlalchemy.engine.base.Engine ('2016-09-13 00:00:00.000000', 0.34, 79)
2018-05-08 18:31:25,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,134 INFO sqlalchemy.engine.base.Engine ('2016-09-14 00:00:00.000000', 2.33, 75)
2018-05-08 18:31:25,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,136 INFO sqlalchemy.engine.base.Engine ('2016-09-15 00:00:00.000000', 0.83, 79)
2018-05-08 18:31:25,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,137 INFO sqlalchemy.engine.base.Engine ('2016-09-16 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:25,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,139 INFO sqlalchemy.engine.base.Engine ('2016-09-17 00:00:00.000000', 0.36, 79)
2018-05-08 18:31:25,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,140 INFO sqlalchemy.engine.base.Engine ('2016-09-18 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:25,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,142 INFO sqlalchemy.engine.base.Engine ('2016-09-19 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:25,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,143 INFO sqlalchemy.engine.base.Engine ('2016-09-20 00:00:00.000000', 0.22, 76)
2018-05-08 18:31:25,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,145 INFO sqlalchemy.engine.base.Engine ('2016-09-21 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:25,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,146 INFO sqlalchemy.engine.base.Engine ('2016-09-22 00:00:00.000000', 0.34, 77)
2018-05-08 18:31:25,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,148 INFO sqlalchemy.engine.base.Engine ('2016-09-23 00:00:00.000000', 0.94, 78)
2018-05-08 18:31:25,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,149 INFO sqlalchemy.engine.base.Engine ('2016-09-24 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:25,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,151 INFO sqlalchemy.engine.base.Engine ('2016-09-25 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:25,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,153 INFO sqlalchemy.engine.base.Engine ('2016-09-26 00:00:00.000000', 0.17, 77)
2018-05-08 18:31:25,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,154 INFO sqlalchemy.engine.base.Engine ('2016-09-27 00:00:00.000000', 0.17, 80)
2018-05-08 18:31:25,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,155 INFO sqlalchemy.engine.base.Engine ('2016-09-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:25,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,157 INFO sqlalchemy.engine.base.Engine ('2016-09-29 00:00:00.000000', 0.59, 78)
2018-05-08 18:31:25,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,158 INFO sqlalchemy.engine.base.Engine ('2016-09-30 00:00:00.000000', 0.25, 78)
2018-05-08 18:31:25,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,160 INFO sqlalchemy.engine.base.Engine ('2016-10-01 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:25,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,161 INFO sqlalchemy.engine.base.Engine ('2016-10-02 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:25,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,163 INFO sqlalchemy.engine.base.Engine ('2016-10-03 00:00:00.000000', 0.16, 79)
2018-05-08 18:31:25,164 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,165 INFO sqlalchemy.engine.base.Engine ('2016-10-04 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:25,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,213 INFO sqlalchemy.engine.base.Engine ('2016-10-05 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:25,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,215 INFO sqlalchemy.engine.base.Engine ('2016-10-06 00:00:00.000000', 0.0, 75)

2018-05-08 18:31:25,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,216 INFO sqlalchemy.engine.base.Engine ('2016-10-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:25,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,217 INFO sqlalchemy.engine.base.Engine ('2016-10-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:25,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,219 INFO sqlalchemy.engine.base.Engine ('2016-10-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:25,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,220 INFO sqlalchemy.engine.base.Engine ('2016-10-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:25,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,222 INFO sqlalchemy.engine.base.Engine ('2016-10-11 00:00:00.000000', 0.28, 77)
2018-05-08 18:31:25,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,224 INFO sqlalchemy.engine.base.Engine ('2016-10-12 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:25,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,225 INFO sqlalchemy.engine.base.Engine ('2016-10-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:25,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,226 INFO sqlalchemy.engine.base.Engine ('2016-10-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:25,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,228 INFO sqlalchemy.engine.base.Engine ('2016-10-15 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:25,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,230 INFO sqlalchemy.engine.base.Engine ('2016-10-16 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:25,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,231 INFO sqlalchemy.engine.base.Engine ('2016-10-17 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:25,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,233 INFO sqlalchemy.engine.base.Engine ('2016-10-18 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:25,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,234 INFO sqlalchemy.engine.base.Engine ('2016-10-19 00:00:00.000000', 0.11, 78)
2018-05-08 18:31:25,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,236 INFO sqlalchemy.engine.base.Engine ('2016-10-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:25,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,238 INFO sqlalchemy.engine.base.Engine ('2016-10-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:25,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,239 INFO sqlalchemy.engine.base.Engine ('2016-10-22 00:00:00.000000', 0.15, 77)
2018-05-08 18:31:25,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,240 INFO sqlalchemy.engine.base.Engine ('2016-10-23 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:25,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,242 INFO sqlalchemy.engine.base.Engine ('2016-10-24 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:25,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,243 INFO sqlalchemy.engine.base.Engine ('2016-10-25 00:00:00.000000', 0.11, 76)
2018-05-08 18:31:25,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,245 INFO sqlalchemy.engine.base.Engine ('2016-10-26 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:25,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,247 INFO sqlalchemy.engine.base.Engine ('2016-10-27 00:00:00.000000', 0.22, 76)
2018-05-08 18:31:25,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,248 INFO sqlalchemy.engine.base.Engine ('2016-10-28 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:25,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,250 INFO sqlalchemy.engine.base.Engine ('2016-10-29 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:25,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,251 INFO sqlalchemy.engine.base.Engine ('2016-10-30 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:25,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,253 INFO sqlalchemy.engine.base.Engine ('2016-10-31 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:25,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,254 INFO sqlalchemy.engine.base.Engine ('2016-11-01 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:25,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,255 INFO sqlalchemy.engine.base.Engine ('2016-11-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:25,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,257 INFO sqlalchemy.engine.base.Engine ('2016-11-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:25,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,258 INFO sqlalchemy.engine.base.Engine ('2016-11-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:25,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,260 INFO sqlalchemy.engine.base.Engine ('2016-11-05 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:25,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:25,261 INFO sqlalchemy.engine.base.Engine ('2016-11-06 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:25,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519281" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,039 INFO sqlalchemy.engine.base.Engine ('2010-04-29 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:26,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,041 INFO sqlalchemy.engine.base.Engine ('2010-04-30 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:26,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,043 INFO sqlalchemy.engine.base.Engine ('2010-05-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,044 INFO sqlalchemy.engine.base.Engine ('2010-05-02 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:26,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,045 INFO sqlalchemy.engine.base.Engine ('2010-05-03 00:00:00.000000', 0.98, 71)
2018-05-08 18:31:26,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,047 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:26,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,048 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,050 INFO sqlalchemy.engine.base.Engine ('2010-05-06 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:26,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,051 INFO sqlalchemy.engine.base.Engine ('2010-05-07 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:26,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,053 INFO sqlalchemy.engine.base.Engine ('2010-05-08 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:26,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,054 INFO sqlalchemy.engine.base.Engine ('2010-05-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,056 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,057 INFO sqlalchemy.engine.base.Engine ('2010-05-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,058 INFO sqlalchemy.engine.base.Engine ('2010-05-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,060 INFO sqlalchemy.engine.base.Engine ('2010-05-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,061 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,063 INFO sqlalchemy.engine.base.Engine ('2010-05-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,064 INFO sqlalchemy.engine.base.Engine ('2010-05-16 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:26,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,066 INFO sqlalchemy.engine.base.Engine ('2010-05-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,067 INFO sqlalchemy.engine.base.Engine ('2010-05-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,069 INFO sqlalchemy.engine.base.Engine ('2010-05-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,070 INFO sqlalchemy.engine.base.Engine ('2010-05-20 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:26,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,071 INFO sqlalchemy.engine.base.Engine ('2010-05-21 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:26,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,073 INFO sqlalchemy.engine.base.Engine ('2010-05-22 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,075 INFO sqlalchemy.engine.base.Engine ('2010-05-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,076 INFO sqlalchemy.engine.base.Engine ('2010-05-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,079 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,080 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:26,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,082 INFO sqlalchemy.engine.base.Engine ('2010-05-27 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,083 INFO sqlalchemy.engine.base.Engine ('2010-05-28 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,085 INFO sqlalchemy.engine.base.Engine ('2010-05-31 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,086 INFO sqlalchemy.engine.base.Engine ('2010-06-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,087 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,089 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,090 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,092 INFO sqlalchemy.engine.base.Engine ('2010-06-05 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,093 INFO sqlalchemy.engine.base.Engine ('2010-06-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,095 INFO sqlalchemy.engine.base.Engine ('2010-06-07 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:26,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,097 INFO sqlalchemy.engine.base.Engine ('2010-06-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,099 INFO sqlalchemy.engine.base.Engine ('2010-06-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,100 INFO sqlalchemy.engine.base.Engine ('2010-06-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,102 INFO sqlalchemy.engine.base.Engine ('2010-06-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,104 INFO sqlalchemy.engine.base.Engine ('2010-06-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,106 INFO sqlalchemy.engine.base.Engine ('2010-06-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,108 INFO sqlalchemy.engine.base.Engine ('2010-06-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,109 INFO sqlalchemy.engine.base.Engine ('2010-06-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,111 INFO sqlalchemy.engine.base.Engine ('2010-06-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,113 INFO sqlalchemy.engine.base.Engine ('2010-06-18 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:26,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,114 INFO sqlalchemy.engine.base.Engine ('2010-06-19 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:26,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,116 INFO sqlalchemy.engine.base.Engine ('2010-06-20 00:00:00.000000', 0.0, 85)
2018-05-08 18:31:26,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,118 INFO sqlalchemy.engine.base.Engine ('2010-06-21 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,120 INFO sqlalchemy.engine.base.Engine ('2010-06-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,122 INFO sqlalchemy.engine.base.Engine ('2010-06-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,123 INFO sqlalchemy.engine.base.Engine ('2010-06-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,124 INFO sqlalchemy.engine.base.Engine ('2010-06-25 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:26,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,126 INFO sqlalchemy.engine.base.Engine ('2010-06-26 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,127 INFO sqlalchemy.engine.base.Engine ('2010-06-27 00:00:00.000000', 0.09, 80)
2018-05-08 18:31:26,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,129 INFO sqlalchemy.engine.base.Engine ('2010-06-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,130 INFO sqlalchemy.engine.base.Engine ('2010-06-29 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:26,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,132 INFO sqlalchemy.engine.base.Engine ('2010-06-30 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:26,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,133 INFO sqlalchemy.engine.base.Engine ('2010-07-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,135 INFO sqlalchemy.engine.base.Engine ('2010-07-05 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:26,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,136 INFO sqlalchemy.engine.base.Engine ('2010-07-06 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:26,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,138 INFO sqlalchemy.engine.base.Engine ('2010-07-07 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:26,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,139 INFO sqlalchemy.engine.base.Engine ('2010-07-08 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:26,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,141 INFO sqlalchemy.engine.base.Engine ('2010-07-09 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:26,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,144 INFO sqlalchemy.engine.base.Engine ('2010-07-10 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:26,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,145 INFO sqlalchemy.engine.base.Engine ('2010-07-13 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,147 INFO sqlalchemy.engine.base.Engine ('2010-07-14 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:26,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,148 INFO sqlalchemy.engine.base.Engine ('2010-07-15 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:26,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,150 INFO sqlalchemy.engine.base.Engine ('2010-07-16 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,151 INFO sqlalchemy.engine.base.Engine ('2010-07-17 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:26,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,153 INFO sqlalchemy.engine.base.Engine ('2010-07-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,154 INFO sqlalchemy.engine.base.Engine ('2010-07-19 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:26,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,156 INFO sqlalchemy.engine.base.Engine ('2010-07-20 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:26,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,157 INFO sqlalchemy.engine.base.Engine ('2010-07-21 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,159 INFO sqlalchemy.engine.base.Engine ('2010-07-22 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,160 INFO sqlalchemy.engine.base.Engine ('2010-07-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,162 INFO sqlalchemy.engine.base.Engine ('2010-07-24 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,207 INFO sqlalchemy.engine.base.Engine ('2010-07-25 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,209 INFO sqlalchemy.engine.base.Engine ('2010-07-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,210 INFO sqlalchemy.engine.base.Engine ('2010-07-27 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,212 INFO sqlalchemy.engine.base.Engine ('2010-07-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:26,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,214 INFO sqlalchemy.engine.base.Engine ('2010-07-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,215 INFO sqlalchemy.engine.base.Engine ('2010-07-30 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,217 INFO sqlalchemy.engine.base.Engine ('2010-07-31 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,218 INFO sqlalchemy.engine.base.Engine ('2010-08-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,220 INFO sqlalchemy.engine.base.Engine ('2010-08-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,221 INFO sqlalchemy.engine.base.Engine ('2010-08-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,223 INFO sqlalchemy.engine.base.Engine ('2010-08-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,224 INFO sqlalchemy.engine.base.Engine ('2010-08-05 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:26,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,226 INFO sqlalchemy.engine.base.Engine ('2010-08-06 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:26,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,227 INFO sqlalchemy.engine.base.Engine ('2010-08-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,229 INFO sqlalchemy.engine.base.Engine ('2010-08-08 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:26,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,230 INFO sqlalchemy.engine.base.Engine ('2010-08-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,232 INFO sqlalchemy.engine.base.Engine ('2010-08-10 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:26,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,233 INFO sqlalchemy.engine.base.Engine ('2010-08-11 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:26,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,235 INFO sqlalchemy.engine.base.Engine ('2010-08-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,236 INFO sqlalchemy.engine.base.Engine ('2010-08-13 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,238 INFO sqlalchemy.engine.base.Engine ('2010-08-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,239 INFO sqlalchemy.engine.base.Engine ('2010-08-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,241 INFO sqlalchemy.engine.base.Engine ('2010-08-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,242 INFO sqlalchemy.engine.base.Engine ('2010-08-17 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:26,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,243 INFO sqlalchemy.engine.base.Engine ('2010-08-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,245 INFO sqlalchemy.engine.base.Engine ('2010-08-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,247 INFO sqlalchemy.engine.base.Engine ('2010-08-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,248 INFO sqlalchemy.engine.base.Engine ('2010-08-21 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:26,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,250 INFO sqlalchemy.engine.base.Engine ('2010-08-22 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:26,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,251 INFO sqlalchemy.engine.base.Engine ('2010-08-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,252 INFO sqlalchemy.engine.base.Engine ('2010-08-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,254 INFO sqlalchemy.engine.base.Engine ('2010-08-25 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:26,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,255 INFO sqlalchemy.engine.base.Engine ('2010-08-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,257 INFO sqlalchemy.engine.base.Engine ('2010-08-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,258 INFO sqlalchemy.engine.base.Engine ('2010-08-28 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:26,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,260 INFO sqlalchemy.engine.base.Engine ('2010-08-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,261 INFO sqlalchemy.engine.base.Engine ('2010-08-30 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,263 INFO sqlalchemy.engine.base.Engine ('2010-08-31 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,264 INFO sqlalchemy.engine.base.Engine ('2010-09-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:26,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,265 INFO sqlalchemy.engine.base.Engine ('2010-09-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,267 INFO sqlalchemy.engine.base.Engine ('2010-09-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,269 INFO sqlalchemy.engine.base.Engine ('2010-09-05 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:26,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,270 INFO sqlalchemy.engine.base.Engine ('2010-09-06 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,272 INFO sqlalchemy.engine.base.Engine ('2010-09-07 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:26,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,273 INFO sqlalchemy.engine.base.Engine ('2010-09-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,275 INFO sqlalchemy.engine.base.Engine ('2010-09-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:26,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,277 INFO sqlalchemy.engine.base.Engine ('2010-09-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,290 INFO sqlalchemy.engine.base.Engine ('2010-09-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,292 INFO sqlalchemy.engine.base.Engine ('2010-09-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,294 INFO sqlalchemy.engine.base.Engine ('2010-09-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,296 INFO sqlalchemy.engine.base.Engine ('2010-09-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:26,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,298 INFO sqlalchemy.engine.base.Engine ('2010-09-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,300 INFO sqlalchemy.engine.base.Engine ('2010-09-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,302 INFO sqlalchemy.engine.base.Engine ('2010-09-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,303 INFO sqlalchemy.engine.base.Engine ('2010-09-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,306 INFO sqlalchemy.engine.base.Engine ('2010-09-19 00:00:00.000000', 0.0, 87)
2018-05-08 18:31:26,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,308 INFO sqlalchemy.engine.base.Engine ('2010-09-20 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:26,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,309 INFO sqlalchemy.engine.base.Engine ('2010-09-21 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,311 INFO sqlalchemy.engine.base.Engine ('2010-09-22 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:26,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,313 INFO sqlalchemy.engine.base.Engine ('2010-09-23 00:00:00.000000', 0.35, 67)
2018-05-08 18:31:26,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,316 INFO sqlalchemy.engine.base.Engine ('2010-09-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,317 INFO sqlalchemy.engine.base.Engine ('2010-09-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,337 INFO sqlalchemy.engine.base.Engine ('2010-09-26 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,340 INFO sqlalchemy.engine.base.Engine ('2010-09-27 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,342 INFO sqlalchemy.engine.base.Engine ('2010-09-28 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,344 INFO sqlalchemy.engine.base.Engine ('2010-09-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,346 INFO sqlalchemy.engine.base.Engine ('2010-10-01 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:26,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,348 INFO sqlalchemy.engine.base.Engine ('2010-10-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,351 INFO sqlalchemy.engine.base.Engine ('2010-10-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,353 INFO sqlalchemy.engine.base.Engine ('2010-10-04 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:26,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,356 INFO sqlalchemy.engine.base.Engine ('2010-10-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,358 INFO sqlalchemy.engine.base.Engine ('2010-10-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,360 INFO sqlalchemy.engine.base.Engine ('2010-10-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,362 INFO sqlalchemy.engine.base.Engine ('2010-10-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,364 INFO sqlalchemy.engine.base.Engine ('2010-10-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,367 INFO sqlalchemy.engine.base.Engine ('2010-10-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,369 INFO sqlalchemy.engine.base.Engine ('2010-10-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:26,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,372 INFO sqlalchemy.engine.base.Engine ('2010-10-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,374 INFO sqlalchemy.engine.base.Engine ('2010-10-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,376 INFO sqlalchemy.engine.base.Engine ('2010-10-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,379 INFO sqlalchemy.engine.base.Engine ('2010-10-15 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:26,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,381 INFO sqlalchemy.engine.base.Engine ('2010-10-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,384 INFO sqlalchemy.engine.base.Engine ('2010-10-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,388 INFO sqlalchemy.engine.base.Engine ('2010-10-18 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:26,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,390 INFO sqlalchemy.engine.base.Engine ('2010-10-19 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,392 INFO sqlalchemy.engine.base.Engine ('2010-10-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,394 INFO sqlalchemy.engine.base.Engine ('2010-10-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,396 INFO sqlalchemy.engine.base.Engine ('2010-10-22 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,398 INFO sqlalchemy.engine.base.Engine ('2010-10-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,400 INFO sqlalchemy.engine.base.Engine ('2010-10-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,402 INFO sqlalchemy.engine.base.Engine ('2010-10-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,404 INFO sqlalchemy.engine.base.Engine ('2010-10-26 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:26,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,406 INFO sqlalchemy.engine.base.Engine ('2010-10-27 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:26,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,408 INFO sqlalchemy.engine.base.Engine ('2010-10-28 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:26,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,410 INFO sqlalchemy.engine.base.Engine ('2010-10-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,411 INFO sqlalchemy.engine.base.Engine ('2010-10-30 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:26,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,413 INFO sqlalchemy.engine.base.Engine ('2010-10-31 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:26,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,415 INFO sqlalchemy.engine.base.Engine ('2010-11-01 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:26,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,417 INFO sqlalchemy.engine.base.Engine ('2010-11-02 00:00:00.000000', 0.03, 65)
2018-05-08 18:31:26,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,419 INFO sqlalchemy.engine.base.Engine ('2010-11-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,450 INFO sqlalchemy.engine.base.Engine ('2010-11-04 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:26,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,451 INFO sqlalchemy.engine.base.Engine ('2010-11-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,453 INFO sqlalchemy.engine.base.Engine ('2010-11-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,454 INFO sqlalchemy.engine.base.Engine ('2010-11-07 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,456 INFO sqlalchemy.engine.base.Engine ('2010-11-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:26,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,458 INFO sqlalchemy.engine.base.Engine ('2010-11-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:26,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,459 INFO sqlalchemy.engine.base.Engine ('2010-11-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,461 INFO sqlalchemy.engine.base.Engine ('2010-11-11 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:26,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,462 INFO sqlalchemy.engine.base.Engine ('2010-11-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,464 INFO sqlalchemy.engine.base.Engine ('2010-11-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,466 INFO sqlalchemy.engine.base.Engine ('2010-11-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,467 INFO sqlalchemy.engine.base.Engine ('2010-11-15 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:26,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,469 INFO sqlalchemy.engine.base.Engine ('2010-11-16 00:00:00.000000', 0.04, 63)
2018-05-08 18:31:26,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,470 INFO sqlalchemy.engine.base.Engine ('2010-11-17 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:26,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,472 INFO sqlalchemy.engine.base.Engine ('2010-11-18 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,473 INFO sqlalchemy.engine.base.Engine ('2010-11-19 00:00:00.000000', 0.34, 67)
2018-05-08 18:31:26,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,475 INFO sqlalchemy.engine.base.Engine ('2010-11-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,477 INFO sqlalchemy.engine.base.Engine ('2010-11-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,479 INFO sqlalchemy.engine.base.Engine ('2010-11-22 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:26,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,481 INFO sqlalchemy.engine.base.Engine ('2010-11-23 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:26,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,482 INFO sqlalchemy.engine.base.Engine ('2010-11-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,483 INFO sqlalchemy.engine.base.Engine ('2010-11-25 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:26,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,485 INFO sqlalchemy.engine.base.Engine ('2010-11-26 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:26,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,487 INFO sqlalchemy.engine.base.Engine ('2010-11-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,488 INFO sqlalchemy.engine.base.Engine ('2010-11-28 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:26,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,490 INFO sqlalchemy.engine.base.Engine ('2010-11-29 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:26,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,491 INFO sqlalchemy.engine.base.Engine ('2010-11-30 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,494 INFO sqlalchemy.engine.base.Engine ('2010-12-01 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:26,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,496 INFO sqlalchemy.engine.base.Engine ('2010-12-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:26,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,497 INFO sqlalchemy.engine.base.Engine ('2010-12-03 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:26,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,499 INFO sqlalchemy.engine.base.Engine ('2010-12-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:26,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,501 INFO sqlalchemy.engine.base.Engine ('2010-12-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:26,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,503 INFO sqlalchemy.engine.base.Engine ('2010-12-06 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:26,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,505 INFO sqlalchemy.engine.base.Engine ('2010-12-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:26,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,507 INFO sqlalchemy.engine.base.Engine ('2010-12-08 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,509 INFO sqlalchemy.engine.base.Engine ('2010-12-09 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:26,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,511 INFO sqlalchemy.engine.base.Engine ('2010-12-10 00:00:00.000000', 1.8, 65)
2018-05-08 18:31:26,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,513 INFO sqlalchemy.engine.base.Engine ('2010-12-11 00:00:00.000000', 0.8, 72)
2018-05-08 18:31:26,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,514 INFO sqlalchemy.engine.base.Engine ('2010-12-12 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:26,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,516 INFO sqlalchemy.engine.base.Engine ('2010-12-13 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:26,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,518 INFO sqlalchemy.engine.base.Engine ('2010-12-14 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:26,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,520 INFO sqlalchemy.engine.base.Engine ('2010-12-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:26,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,522 INFO sqlalchemy.engine.base.Engine ('2010-12-16 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:26,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,523 INFO sqlalchemy.engine.base.Engine ('2010-12-17 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:26,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,525 INFO sqlalchemy.engine.base.Engine ('2010-12-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:26,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,526 INFO sqlalchemy.engine.base.Engine ('2010-12-19 00:00:00.000000', 4.0, 69)
2018-05-08 18:31:26,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,528 INFO sqlalchemy.engine.base.Engine ('2010-12-20 00:00:00.000000', 3.05, 73)
2018-05-08 18:31:26,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,530 INFO sqlalchemy.engine.base.Engine ('2010-12-21 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:26,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,531 INFO sqlalchemy.engine.base.Engine ('2010-12-22 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:26,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,533 INFO sqlalchemy.engine.base.Engine ('2010-12-23 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,536 INFO sqlalchemy.engine.base.Engine ('2010-12-24 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:26,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,538 INFO sqlalchemy.engine.base.Engine ('2010-12-25 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:26,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,539 INFO sqlalchemy.engine.base.Engine ('2010-12-26 00:00:00.000000', 3.0, 72)
2018-05-08 18:31:26,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,541 INFO sqlalchemy.engine.base.Engine ('2010-12-27 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:26,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,542 INFO sqlalchemy.engine.base.Engine ('2010-12-28 00:00:00.000000', 1.67, 70)
2018-05-08 18:31:26,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,544 INFO sqlalchemy.engine.base.Engine ('2010-12-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:26,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,545 INFO sqlalchemy.engine.base.Engine ('2010-12-30 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:26,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,547 INFO sqlalchemy.engine.base.Engine ('2010-12-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:26,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,549 INFO sqlalchemy.engine.base.Engine ('2011-01-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,550 INFO sqlalchemy.engine.base.Engine ('2011-01-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:26,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,553 INFO sqlalchemy.engine.base.Engine ('2011-01-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:26,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,555 INFO sqlalchemy.engine.base.Engine ('2011-01-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:26,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,557 INFO sqlalchemy.engine.base.Engine ('2011-01-05 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:26,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,559 INFO sqlalchemy.engine.base.Engine ('2011-01-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:26,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,560 INFO sqlalchemy.engine.base.Engine ('2011-01-08 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:26,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,562 INFO sqlalchemy.engine.base.Engine ('2011-01-09 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:26,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,563 INFO sqlalchemy.engine.base.Engine ('2011-01-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:26,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,565 INFO sqlalchemy.engine.base.Engine ('2011-01-11 00:00:00.000000', 0.08, 58)
2018-05-08 18:31:26,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:26,568 INFO sqlalchemy.engine.base.Engine ('2011-01-12 00:00:00.000000', 0.44, 71)
2018-05-08 18:31:26,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:26,570 INFO sqlalchemy.engine.base.Engine ('2011-01-13 00:00:00.000000', 3.44, 66)
2018-05-08 18:31:27,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,105 INFO sqlalchemy.engine.base.Engine ('2011-09-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,108 INFO sqlalchemy.engine.base.Engine ('2011-09-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,110 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,111 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,113 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:27,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,115 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,117 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,118 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,120 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:27,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,122 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,124 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,125 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:27,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,127 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,129 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,131 INFO sqlalchemy.engine.base.Engine ('2011-10-08 00:00:00.000000', 0.0, 86)
2018-05-08 18:31:27,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,133 INFO sqlalchemy.engine.base.Engine ('2011-10-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,135 INFO sqlalchemy.engine.base.Engine ('2011-10-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,137 INFO sqlalchemy.engine.base.Engine ('2011-10-11 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:27,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,139 INFO sqlalchemy.engine.base.Engine ('2011-10-12 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,140 INFO sqlalchemy.engine.base.Engine ('2011-10-13 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,142 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,144 INFO sqlalchemy.engine.base.Engine ('2011-10-15 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:27,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,146 INFO sqlalchemy.engine.base.Engine ('2011-10-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,147 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,149 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,151 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:27,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,153 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,155 INFO sqlalchemy.engine.base.Engine ('2011-10-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,157 INFO sqlalchemy.engine.base.Engine ('2011-10-22 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:27,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,158 INFO sqlalchemy.engine.base.Engine ('2011-10-23 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,160 INFO sqlalchemy.engine.base.Engine ('2011-10-24 00:00:00.000000', 0.65, 75)
2018-05-08 18:31:27,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,162 INFO sqlalchemy.engine.base.Engine ('2011-10-25 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:27,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,164 INFO sqlalchemy.engine.base.Engine ('2011-10-26 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:27,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,166 INFO sqlalchemy.engine.base.Engine ('2011-10-27 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,167 INFO sqlalchemy.engine.base.Engine ('2011-10-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,169 INFO sqlalchemy.engine.base.Engine ('2011-10-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,172 INFO sqlalchemy.engine.base.Engine ('2011-10-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,174 INFO sqlalchemy.engine.base.Engine ('2011-10-31 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,175 INFO sqlalchemy.engine.base.Engine ('2011-11-01 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:27,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,177 INFO sqlalchemy.engine.base.Engine ('2011-11-02 00:00:00.000000', 0.26, 74)
2018-05-08 18:31:27,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,179 INFO sqlalchemy.engine.base.Engine ('2011-11-03 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:27,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,180 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:27,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,182 INFO sqlalchemy.engine.base.Engine ('2011-11-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,184 INFO sqlalchemy.engine.base.Engine ('2011-11-07 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,186 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,188 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:27,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,190 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,191 INFO sqlalchemy.engine.base.Engine ('2011-11-11 00:00:00.000000', 0.09, 70)
2018-05-08 18:31:27,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,193 INFO sqlalchemy.engine.base.Engine ('2011-11-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,195 INFO sqlalchemy.engine.base.Engine ('2011-11-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,196 INFO sqlalchemy.engine.base.Engine ('2011-11-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,198 INFO sqlalchemy.engine.base.Engine ('2011-11-15 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,200 INFO sqlalchemy.engine.base.Engine ('2011-11-16 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,201 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,203 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,205 INFO sqlalchemy.engine.base.Engine ('2011-11-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,207 INFO sqlalchemy.engine.base.Engine ('2011-11-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,209 INFO sqlalchemy.engine.base.Engine ('2011-11-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,211 INFO sqlalchemy.engine.base.Engine ('2011-11-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,213 INFO sqlalchemy.engine.base.Engine ('2011-11-23 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:27,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,214 INFO sqlalchemy.engine.base.Engine ('2011-11-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,216 INFO sqlalchemy.engine.base.Engine ('2011-11-25 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,218 INFO sqlalchemy.engine.base.Engine ('2011-11-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,220 INFO sqlalchemy.engine.base.Engine ('2011-11-27 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:27,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,222 INFO sqlalchemy.engine.base.Engine ('2011-11-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,223 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,225 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:27,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,226 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,228 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:27,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,230 INFO sqlalchemy.engine.base.Engine ('2011-12-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,232 INFO sqlalchemy.engine.base.Engine ('2011-12-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,234 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,236 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,238 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,239 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,241 INFO sqlalchemy.engine.base.Engine ('2011-12-09 00:00:00.000000', 0.05, 65)
2018-05-08 18:31:27,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,242 INFO sqlalchemy.engine.base.Engine ('2011-12-10 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:27,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,244 INFO sqlalchemy.engine.base.Engine ('2011-12-11 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:27,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,246 INFO sqlalchemy.engine.base.Engine ('2011-12-12 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:27,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,248 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:27,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,250 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 0.06, 65)
2018-05-08 18:31:27,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,299 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:27,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,301 INFO sqlalchemy.engine.base.Engine ('2011-12-16 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:27,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,303 INFO sqlalchemy.engine.base.Engine ('2011-12-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,305 INFO sqlalchemy.engine.base.Engine ('2011-12-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,307 INFO sqlalchemy.engine.base.Engine ('2011-12-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,309 INFO sqlalchemy.engine.base.Engine ('2011-12-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,311 INFO sqlalchemy.engine.base.Engine ('2011-12-21 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:27,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,313 INFO sqlalchemy.engine.base.Engine ('2011-12-22 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:27,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,316 INFO sqlalchemy.engine.base.Engine ('2011-12-23 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:27,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,318 INFO sqlalchemy.engine.base.Engine ('2011-12-24 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:27,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,320 INFO sqlalchemy.engine.base.Engine ('2011-12-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,322 INFO sqlalchemy.engine.base.Engine ('2011-12-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,324 INFO sqlalchemy.engine.base.Engine ('2011-12-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,326 INFO sqlalchemy.engine.base.Engine ('2011-12-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,328 INFO sqlalchemy.engine.base.Engine ('2011-12-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,330 INFO sqlalchemy.engine.base.Engine ('2011-12-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,332 INFO sqlalchemy.engine.base.Engine ('2011-12-31 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:27,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,335 INFO sqlalchemy.engine.base.Engine ('2012-01-01 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,338 INFO sqlalchemy.engine.base.Engine ('2012-01-03 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,340 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,341 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,343 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,345 INFO sqlalchemy.engine.base.Engine ('2012-01-07 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,348 INFO sqlalchemy.engine.base.Engine ('2012-01-08 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:27,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,350 INFO sqlalchemy.engine.base.Engine ('2012-01-09 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,354 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,357 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,359 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,361 INFO sqlalchemy.engine.base.Engine ('2012-01-13 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,363 INFO sqlalchemy.engine.base.Engine ('2012-01-14 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,367 INFO sqlalchemy.engine.base.Engine ('2012-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,369 INFO sqlalchemy.engine.base.Engine ('2012-01-16 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:27,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,371 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,373 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,375 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,377 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,379 INFO sqlalchemy.engine.base.Engine ('2012-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,382 INFO sqlalchemy.engine.base.Engine ('2012-01-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,384 INFO sqlalchemy.engine.base.Engine ('2012-01-23 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:27,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,386 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,388 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,390 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,392 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.33, 65)
2018-05-08 18:31:27,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,394 INFO sqlalchemy.engine.base.Engine ('2012-01-28 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,396 INFO sqlalchemy.engine.base.Engine ('2012-01-29 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:27,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,398 INFO sqlalchemy.engine.base.Engine ('2012-01-30 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:27,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,400 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,403 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,406 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,408 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:27,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,410 INFO sqlalchemy.engine.base.Engine ('2012-02-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,412 INFO sqlalchemy.engine.base.Engine ('2012-02-05 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,416 INFO sqlalchemy.engine.base.Engine ('2012-02-06 00:00:00.000000', 0.15, 66)
2018-05-08 18:31:27,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,418 INFO sqlalchemy.engine.base.Engine ('2012-02-07 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:27,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,420 INFO sqlalchemy.engine.base.Engine ('2012-02-08 00:00:00.000000', 0.39, 56)
2018-05-08 18:31:27,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,422 INFO sqlalchemy.engine.base.Engine ('2012-02-09 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:27,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,425 INFO sqlalchemy.engine.base.Engine ('2012-02-10 00:00:00.000000', 0.0, 56)
2018-05-08 18:31:27,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,427 INFO sqlalchemy.engine.base.Engine ('2012-02-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,429 INFO sqlalchemy.engine.base.Engine ('2012-02-12 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,432 INFO sqlalchemy.engine.base.Engine ('2012-02-13 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,434 INFO sqlalchemy.engine.base.Engine ('2012-02-14 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:27,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,436 INFO sqlalchemy.engine.base.Engine ('2012-02-15 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,438 INFO sqlalchemy.engine.base.Engine ('2012-02-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,443 INFO sqlalchemy.engine.base.Engine ('2012-02-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,445 INFO sqlalchemy.engine.base.Engine ('2012-02-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,449 INFO sqlalchemy.engine.base.Engine ('2012-02-19 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:27,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,451 INFO sqlalchemy.engine.base.Engine ('2012-02-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,453 INFO sqlalchemy.engine.base.Engine ('2012-02-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,456 INFO sqlalchemy.engine.base.Engine ('2012-02-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,459 INFO sqlalchemy.engine.base.Engine ('2012-02-23 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:27,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,461 INFO sqlalchemy.engine.base.Engine ('2012-02-24 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,463 INFO sqlalchemy.engine.base.Engine ('2012-02-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,466 INFO sqlalchemy.engine.base.Engine ('2012-02-26 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:27,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,468 INFO sqlalchemy.engine.base.Engine ('2012-02-27 00:00:00.000000', 0.38, 64)
2018-05-08 18:31:27,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,471 INFO sqlalchemy.engine.base.Engine ('2012-02-28 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,473 INFO sqlalchemy.engine.base.Engine ('2012-02-29 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:27,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,476 INFO sqlalchemy.engine.base.Engine ('2012-03-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,478 INFO sqlalchemy.engine.base.Engine ('2012-03-02 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,481 INFO sqlalchemy.engine.base.Engine ('2012-03-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,484 INFO sqlalchemy.engine.base.Engine ('2012-03-04 00:00:00.000000', 0.05, 66)
2018-05-08 18:31:27,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,487 INFO sqlalchemy.engine.base.Engine ('2012-03-05 00:00:00.000000', 0.7, 64)
2018-05-08 18:31:27,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,489 INFO sqlalchemy.engine.base.Engine ('2012-03-06 00:00:00.000000', 2.83, 70)
2018-05-08 18:31:27,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,491 INFO sqlalchemy.engine.base.Engine ('2012-03-07 00:00:00.000000', 0.91, 65)
2018-05-08 18:31:27,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,493 INFO sqlalchemy.engine.base.Engine ('2012-03-08 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,495 INFO sqlalchemy.engine.base.Engine ('2012-03-09 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,497 INFO sqlalchemy.engine.base.Engine ('2012-03-10 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:27,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,499 INFO sqlalchemy.engine.base.Engine ('2012-03-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,501 INFO sqlalchemy.engine.base.Engine ('2012-03-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,503 INFO sqlalchemy.engine.base.Engine ('2012-03-13 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,505 INFO sqlalchemy.engine.base.Engine ('2012-03-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,507 INFO sqlalchemy.engine.base.Engine ('2012-03-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,508 INFO sqlalchemy.engine.base.Engine ('2012-03-16 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:27,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,510 INFO sqlalchemy.engine.base.Engine ('2012-03-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,512 INFO sqlalchemy.engine.base.Engine ('2012-03-18 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:27,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,514 INFO sqlalchemy.engine.base.Engine ('2012-03-19 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:27,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,517 INFO sqlalchemy.engine.base.Engine ('2012-03-20 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,518 INFO sqlalchemy.engine.base.Engine ('2012-03-21 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,520 INFO sqlalchemy.engine.base.Engine ('2012-03-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,522 INFO sqlalchemy.engine.base.Engine ('2012-03-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,524 INFO sqlalchemy.engine.base.Engine ('2012-03-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,567 INFO sqlalchemy.engine.base.Engine ('2012-03-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,569 INFO sqlalchemy.engine.base.Engine ('2012-03-26 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:27,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,570 INFO sqlalchemy.engine.base.Engine ('2012-03-27 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,572 INFO sqlalchemy.engine.base.Engine ('2012-03-28 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:27,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,573 INFO sqlalchemy.engine.base.Engine ('2012-03-29 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:27,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,575 INFO sqlalchemy.engine.base.Engine ('2012-03-30 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,576 INFO sqlalchemy.engine.base.Engine ('2012-03-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,578 INFO sqlalchemy.engine.base.Engine ('2012-04-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,579 INFO sqlalchemy.engine.base.Engine ('2012-04-02 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,581 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:27,581 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,582 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,583 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,585 INFO sqlalchemy.engine.base.Engine ('2012-04-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,586 INFO sqlalchemy.engine.base.Engine ('2012-04-07 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:27,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,588 INFO sqlalchemy.engine.base.Engine ('2012-04-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,589 INFO sqlalchemy.engine.base.Engine ('2012-04-09 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:27,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,591 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 0.19, 65)
2018-05-08 18:31:27,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,593 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:27,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,594 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,596 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,597 INFO sqlalchemy.engine.base.Engine ('2012-04-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,599 INFO sqlalchemy.engine.base.Engine ('2012-04-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,601 INFO sqlalchemy.engine.base.Engine ('2012-04-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,602 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,604 INFO sqlalchemy.engine.base.Engine ('2012-04-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,606 INFO sqlalchemy.engine.base.Engine ('2012-04-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,608 INFO sqlalchemy.engine.base.Engine ('2012-04-20 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,609 INFO sqlalchemy.engine.base.Engine ('2012-04-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,611 INFO sqlalchemy.engine.base.Engine ('2012-04-22 00:00:00.000000', 0.08, 65)
2018-05-08 18:31:27,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,613 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:27,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,614 INFO sqlalchemy.engine.base.Engine ('2012-04-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,616 INFO sqlalchemy.engine.base.Engine ('2012-04-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,618 INFO sqlalchemy.engine.base.Engine ('2012-04-26 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,619 INFO sqlalchemy.engine.base.Engine ('2012-04-27 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,621 INFO sqlalchemy.engine.base.Engine ('2012-04-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,622 INFO sqlalchemy.engine.base.Engine ('2012-04-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,624 INFO sqlalchemy.engine.base.Engine ('2012-04-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,625 INFO sqlalchemy.engine.base.Engine ('2012-05-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,627 INFO sqlalchemy.engine.base.Engine ('2012-05-02 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:27,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,628 INFO sqlalchemy.engine.base.Engine ('2012-05-03 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:27,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,629 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,631 INFO sqlalchemy.engine.base.Engine ('2012-05-05 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:27,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,632 INFO sqlalchemy.engine.base.Engine ('2012-05-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,634 INFO sqlalchemy.engine.base.Engine ('2012-05-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,636 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,637 INFO sqlalchemy.engine.base.Engine ('2012-05-09 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,639 INFO sqlalchemy.engine.base.Engine ('2012-05-10 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,640 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,642 INFO sqlalchemy.engine.base.Engine ('2012-05-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,644 INFO sqlalchemy.engine.base.Engine ('2012-05-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,645 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:27,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,647 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:27,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,648 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:27,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,650 INFO sqlalchemy.engine.base.Engine ('2012-05-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,651 INFO sqlalchemy.engine.base.Engine ('2012-05-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,653 INFO sqlalchemy.engine.base.Engine ('2012-05-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,654 INFO sqlalchemy.engine.base.Engine ('2012-05-20 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,655 INFO sqlalchemy.engine.base.Engine ('2012-05-21 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,657 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,659 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,661 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:27,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,662 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,664 INFO sqlalchemy.engine.base.Engine ('2012-05-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,665 INFO sqlalchemy.engine.base.Engine ('2012-05-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,667 INFO sqlalchemy.engine.base.Engine ('2012-05-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,669 INFO sqlalchemy.engine.base.Engine ('2012-05-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,670 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,672 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,673 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:27,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,675 INFO sqlalchemy.engine.base.Engine ('2012-06-02 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:27,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,676 INFO sqlalchemy.engine.base.Engine ('2012-06-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,678 INFO sqlalchemy.engine.base.Engine ('2012-06-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,680 INFO sqlalchemy.engine.base.Engine ('2012-06-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,681 INFO sqlalchemy.engine.base.Engine ('2012-06-06 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:27,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,683 INFO sqlalchemy.engine.base.Engine ('2012-06-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,685 INFO sqlalchemy.engine.base.Engine ('2012-06-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,686 INFO sqlalchemy.engine.base.Engine ('2012-06-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,688 INFO sqlalchemy.engine.base.Engine ('2012-06-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,689 INFO sqlalchemy.engine.base.Engine ('2012-06-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,691 INFO sqlalchemy.engine.base.Engine ('2012-06-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,693 INFO sqlalchemy.engine.base.Engine ('2012-06-13 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:27,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,694 INFO sqlalchemy.engine.base.Engine ('2012-06-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,696 INFO sqlalchemy.engine.base.Engine ('2012-06-17 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,697 INFO sqlalchemy.engine.base.Engine ('2012-06-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,698 INFO sqlalchemy.engine.base.Engine ('2012-06-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,700 INFO sqlalchemy.engine.base.Engine ('2012-06-20 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:27,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,701 INFO sqlalchemy.engine.base.Engine ('2012-06-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,703 INFO sqlalchemy.engine.base.Engine ('2012-06-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,705 INFO sqlalchemy.engine.base.Engine ('2012-06-23 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:27,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,706 INFO sqlalchemy.engine.base.Engine ('2012-06-24 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,708 INFO sqlalchemy.engine.base.Engine ('2012-06-25 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:27,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,709 INFO sqlalchemy.engine.base.Engine ('2012-06-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,711 INFO sqlalchemy.engine.base.Engine ('2012-06-27 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:27,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,712 INFO sqlalchemy.engine.base.Engine ('2012-06-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,714 INFO sqlalchemy.engine.base.Engine ('2012-06-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,715 INFO sqlalchemy.engine.base.Engine ('2012-06-30 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,717 INFO sqlalchemy.engine.base.Engine ('2012-07-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,718 INFO sqlalchemy.engine.base.Engine ('2012-07-02 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,720 INFO sqlalchemy.engine.base.Engine ('2012-07-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,721 INFO sqlalchemy.engine.base.Engine ('2012-07-04 00:00:00.000000', 0.2, 79)
2018-05-08 18:31:27,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,769 INFO sqlalchemy.engine.base.Engine ('2012-07-05 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:27,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,770 INFO sqlalchemy.engine.base.Engine ('2012-07-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,772 INFO sqlalchemy.engine.base.Engine ('2012-07-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,773 INFO sqlalchemy.engine.base.Engine ('2012-07-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,775 INFO sqlalchemy.engine.base.Engine ('2012-07-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,777 INFO sqlalchemy.engine.base.Engine ('2012-07-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,778 INFO sqlalchemy.engine.base.Engine ('2012-07-12 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,780 INFO sqlalchemy.engine.base.Engine ('2012-07-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,781 INFO sqlalchemy.engine.base.Engine ('2012-07-14 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,783 INFO sqlalchemy.engine.base.Engine ('2012-07-15 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,784 INFO sqlalchemy.engine.base.Engine ('2012-07-16 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:27,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,786 INFO sqlalchemy.engine.base.Engine ('2012-07-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,788 INFO sqlalchemy.engine.base.Engine ('2012-07-18 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,789 INFO sqlalchemy.engine.base.Engine ('2012-07-19 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,791 INFO sqlalchemy.engine.base.Engine ('2012-07-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,792 INFO sqlalchemy.engine.base.Engine ('2012-07-21 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:27,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,794 INFO sqlalchemy.engine.base.Engine ('2012-07-22 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:27,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,796 INFO sqlalchemy.engine.base.Engine ('2012-07-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,797 INFO sqlalchemy.engine.base.Engine ('2012-07-24 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,799 INFO sqlalchemy.engine.base.Engine ('2012-07-25 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:27,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,800 INFO sqlalchemy.engine.base.Engine ('2012-07-26 00:00:00.000000', 0.0, 86)
2018-05-08 18:31:27,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,802 INFO sqlalchemy.engine.base.Engine ('2012-07-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,803 INFO sqlalchemy.engine.base.Engine ('2012-07-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,805 INFO sqlalchemy.engine.base.Engine ('2012-07-29 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:27,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,807 INFO sqlalchemy.engine.base.Engine ('2012-07-30 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,808 INFO sqlalchemy.engine.base.Engine ('2012-07-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,810 INFO sqlalchemy.engine.base.Engine ('2012-08-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,811 INFO sqlalchemy.engine.base.Engine ('2012-08-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,813 INFO sqlalchemy.engine.base.Engine ('2012-08-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,815 INFO sqlalchemy.engine.base.Engine ('2012-08-04 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,815 INFO sqlalchemy.engine.base.Engine ('2012-08-05 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,818 INFO sqlalchemy.engine.base.Engine ('2012-08-06 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:27,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,819 INFO sqlalchemy.engine.base.Engine ('2012-08-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,821 INFO sqlalchemy.engine.base.Engine ('2012-08-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,822 INFO sqlalchemy.engine.base.Engine ('2012-08-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,824 INFO sqlalchemy.engine.base.Engine ('2012-08-10 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:27,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,825 INFO sqlalchemy.engine.base.Engine ('2012-08-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,827 INFO sqlalchemy.engine.base.Engine ('2012-08-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,828 INFO sqlalchemy.engine.base.Engine ('2012-08-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,830 INFO sqlalchemy.engine.base.Engine ('2012-08-14 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:27,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,831 INFO sqlalchemy.engine.base.Engine ('2012-08-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,833 INFO sqlalchemy.engine.base.Engine ('2012-08-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,834 INFO sqlalchemy.engine.base.Engine ('2012-08-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,836 INFO sqlalchemy.engine.base.Engine ('2012-08-18 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,837 INFO sqlalchemy.engine.base.Engine ('2012-08-19 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,838 INFO sqlalchemy.engine.base.Engine ('2012-08-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,840 INFO sqlalchemy.engine.base.Engine ('2012-08-21 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,841 INFO sqlalchemy.engine.base.Engine ('2012-08-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,843 INFO sqlalchemy.engine.base.Engine ('2012-08-23 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,844 INFO sqlalchemy.engine.base.Engine ('2012-08-24 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,846 INFO sqlalchemy.engine.base.Engine ('2012-08-25 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,847 INFO sqlalchemy.engine.base.Engine ('2012-08-26 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,849 INFO sqlalchemy.engine.base.Engine ('2012-08-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,850 INFO sqlalchemy.engine.base.Engine ('2012-08-28 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:27,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,852 INFO sqlalchemy.engine.base.Engine ('2012-08-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,854 INFO sqlalchemy.engine.base.Engine ('2012-08-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,856 INFO sqlalchemy.engine.base.Engine ('2012-08-31 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,857 INFO sqlalchemy.engine.base.Engine ('2012-09-01 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,859 INFO sqlalchemy.engine.base.Engine ('2012-09-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,860 INFO sqlalchemy.engine.base.Engine ('2012-09-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,861 INFO sqlalchemy.engine.base.Engine ('2012-09-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,863 INFO sqlalchemy.engine.base.Engine ('2012-09-05 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:27,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,864 INFO sqlalchemy.engine.base.Engine ('2012-09-06 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,866 INFO sqlalchemy.engine.base.Engine ('2012-09-07 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:27,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,868 INFO sqlalchemy.engine.base.Engine ('2012-09-08 00:00:00.000000', 0.1, 79)
2018-05-08 18:31:27,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,869 INFO sqlalchemy.engine.base.Engine ('2012-09-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,871 INFO sqlalchemy.engine.base.Engine ('2012-09-10 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:27,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,872 INFO sqlalchemy.engine.base.Engine ('2012-09-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,874 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,874 INFO sqlalchemy.engine.base.Engine ('2012-09-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,876 INFO sqlalchemy.engine.base.Engine ('2012-09-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,878 INFO sqlalchemy.engine.base.Engine ('2012-09-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,879 INFO sqlalchemy.engine.base.Engine ('2012-09-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,881 INFO sqlalchemy.engine.base.Engine ('2012-09-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,882 INFO sqlalchemy.engine.base.Engine ('2012-09-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,884 INFO sqlalchemy.engine.base.Engine ('2012-09-18 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,886 INFO sqlalchemy.engine.base.Engine ('2012-09-19 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:27,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,887 INFO sqlalchemy.engine.base.Engine ('2012-09-20 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:27,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,889 INFO sqlalchemy.engine.base.Engine ('2012-09-21 00:00:00.000000', 0.08, 68)
2018-05-08 18:31:27,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,890 INFO sqlalchemy.engine.base.Engine ('2012-09-22 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,892 INFO sqlalchemy.engine.base.Engine ('2012-09-23 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:27,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,893 INFO sqlalchemy.engine.base.Engine ('2012-09-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,895 INFO sqlalchemy.engine.base.Engine ('2012-09-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,896 INFO sqlalchemy.engine.base.Engine ('2012-09-26 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,898 INFO sqlalchemy.engine.base.Engine ('2012-09-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,899 INFO sqlalchemy.engine.base.Engine ('2012-09-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,900 INFO sqlalchemy.engine.base.Engine ('2012-09-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,902 INFO sqlalchemy.engine.base.Engine ('2012-09-30 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,903 INFO sqlalchemy.engine.base.Engine ('2012-10-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,905 INFO sqlalchemy.engine.base.Engine ('2012-10-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,906 INFO sqlalchemy.engine.base.Engine ('2012-10-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,908 INFO sqlalchemy.engine.base.Engine ('2012-10-04 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,909 INFO sqlalchemy.engine.base.Engine ('2012-10-05 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,911 INFO sqlalchemy.engine.base.Engine ('2012-10-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,912 INFO sqlalchemy.engine.base.Engine ('2012-10-07 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:27,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,914 INFO sqlalchemy.engine.base.Engine ('2012-10-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,915 INFO sqlalchemy.engine.base.Engine ('2012-10-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,917 INFO sqlalchemy.engine.base.Engine ('2012-10-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:27,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,918 INFO sqlalchemy.engine.base.Engine ('2012-10-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:27,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,920 INFO sqlalchemy.engine.base.Engine ('2012-10-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,922 INFO sqlalchemy.engine.base.Engine ('2012-10-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,961 INFO sqlalchemy.engine.base.Engine ('2012-10-14 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:27,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,962 INFO sqlalchemy.engine.base.Engine ('2012-10-15 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:27,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,964 INFO sqlalchemy.engine.base.Engine ('2012-10-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:27,965 INFO sqlalchemy.engine.base.Engine ('2012-10-17 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:27,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,967 INFO sqlalchemy.engine.base.Engine ('2012-10-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,968 INFO sqlalchemy.engine.base.Engine ('2012-10-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:27,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,970 INFO sqlalchemy.engine.base.Engine ('2012-10-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:27,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,971 INFO sqlalchemy.engine.base.Engine ('2012-10-21 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:27,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,973 INFO sqlalchemy.engine.base.Engine ('2012-10-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:27,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,974 INFO sqlalchemy.engine.base.Engine ('2012-10-23 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:27,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,976 INFO sqlalchemy.engine.base.Engine ('2012-10-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,977 INFO sqlalchemy.engine.base.Engine ('2012-10-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,979 INFO sqlalchemy.engine.base.Engine ('2012-10-26 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:27,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,981 INFO sqlalchemy.engine.base.Engine ('2012-10-27 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:27,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,982 INFO sqlalchemy.engine.base.Engine ('2012-10-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:27,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,984 INFO sqlalchemy.engine.base.Engine ('2012-10-29 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:27,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,985 INFO sqlalchemy.engine.base.Engine ('2012-10-30 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:27,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,987 INFO sqlalchemy.engine.base.Engine ('2012-10-31 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:27,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,988 INFO sqlalchemy.engine.base.Engine ('2012-11-01 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:27,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,990 INFO sqlalchemy.engine.base.Engine ('2012-11-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:27,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,991 INFO sqlalchemy.engine.base.Engine ('2012-11-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:27,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,993 INFO sqlalchemy.engine.base.Engine ('2012-11-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:27,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,994 INFO sqlalchemy.engine.base.Engine ('2012-11-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:27,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,996 INFO sqlalchemy.engine.base.Engine ('2012-11-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:27,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,998 INFO sqlalchemy.engine.base.Engine ('2012-11-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:27,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:27,999 INFO sqlalchemy.engine.base.Engine ('2012-11-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:28,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,001 INFO sqlalchemy.engine.base.Engine ('2012-11-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:28,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,002 INFO sqlalchemy.engine.base.Engine ('2012-11-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:28,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,004 INFO sqlalchemy.engine.base.Engine ('2012-11-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:28,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,005 INFO sqlalchemy.engine.base.Engine ('2012-11-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:28,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,007 INFO sqlalchemy.engine.base.Engine ('2012-11-13 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:28,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,008 INFO sqlalchemy.engine.base.Engine ('2012-11-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:28,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,009 INFO sqlalchemy.engine.base.Engine ('2012-11-15 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:28,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,011 INFO sqlalchemy.engine.base.Engine ('2012-11-16 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:28,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,013 INFO sqlalchemy.engine.base.Engine ('2012-11-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:28,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,014 INFO sqlalchemy.engine.base.Engine ('2012-11-18 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:28,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,016 INFO sqlalchemy.engine.base.Engine ('2012-11-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:28,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,017 INFO sqlalchemy.engine.base.Engine ('2012-11-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:28,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:28,018 INFO sqlalchemy.engine.base.Engine ('2012-11-21 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:28,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,020 INFO sqlalchemy.engine.base.Engine ('2012-11-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:28,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,021 INFO sqlalchemy.engine.base.Engine ('2012-11-23 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:28,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,023 INFO sqlalchemy.engine.base.Engine ('2012-11-24 00:00:00.000000', 0.25, 69)
2018-05-08 18:31:28,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,025 INFO sqlalchemy.engine.base.Engine ('2012-11-26 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:28,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,026 INFO sqlalchemy.engine.base.Engine ('2012-11-27 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:28,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,027 INFO sqlalchemy.engine.base.Engine ('2012-11-28 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:28,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,029 INFO sqlalchemy.engine.base.Engine ('2012-11-29 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:28,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,031 INFO sqlalchemy.engine.base.Engine ('2012-11-30 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:28,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,032 INFO sqlalchemy.engine.base.Engine ('2012-12-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:28,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,034 INFO sqlalchemy.engine.base.Engine ('2012-12-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:28,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,035 INFO sqlalchemy.engine.base.Engine ('2012-12-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:28,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,037 INFO sqlalchemy.engine.base.Engine ('2012-12-05 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:28,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,038 INFO sqlalchemy.engine.base.Engine ('2012-12-06 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:28,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,040 INFO sqlalchemy.engine.base.Engine ('2012-12-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:28,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,041 INFO sqlalchemy.engine.base.Engine ('2012-12-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:28,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,043 INFO sqlalchemy.engine.base.Engine ('2012-12-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:28,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,045 INFO sqlalchemy.engine.base.Engine ('2012-12-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:28,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,046 INFO sqlalchemy.engine.base.Engine ('2012-12-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:28,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,048 INFO sqlalchemy.engine.base.Engine ('2012-12-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:28,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,049 INFO sqlalchemy.engine.base.Engine ('2012-12-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:28,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,051 INFO sqlalchemy.engine.base.Engine ('2012-12-14 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:28,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,052 INFO sqlalchemy.engine.base.Engine ('2012-12-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:28,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,054 INFO sqlalchemy.engine.base.Engine ('2012-12-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:28,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,055 INFO sqlalchemy.engine.base.Engine ('2012-12-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:28,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,057 INFO sqlalchemy.engine.base.Engine ('2012-12-18 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:28,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,058 INFO sqlalchemy.engine.base.Engine ('2012-12-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:28,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,059 INFO sqlalchemy.engine.base.Engine ('2012-12-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:28,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,061 INFO sqlalchemy.engine.base.Engine ('2012-12-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:28,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,062 INFO sqlalchemy.engine.base.Engine ('2012-12-22 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:28,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,064 INFO sqlalchemy.engine.base.Engine ('2012-12-23 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:28,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,065 INFO sqlalchemy.engine.base.Engine ('2012-12-24 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:28,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,067 INFO sqlalchemy.engine.base.Engine ('2012-12-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:28,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,068 INFO sqlalchemy.engine.base.Engine ('2012-12-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:28,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,070 INFO sqlalchemy.engine.base.Engine ('2012-12-27 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:28,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:28,072 INFO sqlalchemy.engine.base.Engine ('2012-12-28 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:28,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,073 INFO sqlalchemy.engine.base.Engine ('2012-12-29 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:28,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,075 INFO sqlalchemy.engine.base.Engine ('2012-12-30 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:28,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,076 INFO sqlalchemy.engine.base.Engine ('2012-12-31 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:28,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,078 INFO sqlalchemy.engine.base.Engine ('2013-01-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:28,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,079 INFO sqlalchemy.engine.base.Engine ('2013-01-02 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:28,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,081 INFO sqlalchemy.engine.base.Engine ('2013-01-03 00:00:00.000000', 0.13, 67)
2018-05-08 18:31:28,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,082 INFO sqlalchemy.engine.base.Engine ('2013-01-04 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:28,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,083 INFO sqlalchemy.engine.base.Engine ('2013-01-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:28,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,085 INFO sqlalchemy.engine.base.Engine ('2013-01-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:28,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,087 INFO sqlalchemy.engine.base.Engine ('2013-01-07 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:28,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,089 INFO sqlalchemy.engine.base.Engine ('2013-01-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:28,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,090 INFO sqlalchemy.engine.base.Engine ('2013-01-09 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:28,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,092 INFO sqlalchemy.engine.base.Engine ('2013-01-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:28,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,094 INFO sqlalchemy.engine.base.Engine ('2013-01-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:28,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,095 INFO sqlalchemy.engine.base.Engine ('2013-01-12 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:28,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,096 INFO sqlalchemy.engine.base.Engine ('2013-01-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:28,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,098 INFO sqlalchemy.engine.base.Engine ('2013-01-14 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:28,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,099 INFO sqlalchemy.engine.base.Engine ('2013-01-15 00:00:00.000000', 0.53, 66)
2018-05-08 18:31:28,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,101 INFO sqlalchemy.engine.base.Engine ('2013-01-16 00:00:00.000000', 0.0, 57)
2018-05-08 18:31:28,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,102 INFO sqlalchemy.engine.base.Engine ('2013-01-17 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:28,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,104 INFO sqlalchemy.engine.base.Engine ('2013-01-18 00:00:00.000000', 0.0, 57)
2018-05-08 18:31:28,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,105 INFO sqlalchemy.engine.base.Engine ('2013-01-19 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:28,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,107 INFO sqlalchemy.engine.base.Engine ('2013-01-20 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:28,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,108 INFO sqlalchemy.engine.base.Engine ('2013-01-22 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:28,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,110 INFO sqlalchemy.engine.base.Engine ('2013-01-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:28,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,111 INFO sqlalchemy.engine.base.Engine ('2013-01-24 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:28,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,152 INFO sqlalchemy.engine.base.Engine ('2013-01-25 00:00:00.000000', 0.1, 61)
2018-05-08 18:31:28,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,153 INFO sqlalchemy.engine.base.Engine ('2013-01-26 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:28,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,155 INFO sqlalchemy.engine.base.Engine ('2013-01-27 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:28,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,156 INFO sqlalchemy.engine.base.Engine ('2013-01-28 00:00:00.000000', 1.57, 65)
2018-05-08 18:31:28,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,158 INFO sqlalchemy.engine.base.Engine ('2013-01-29 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:28,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,160 INFO sqlalchemy.engine.base.Engine ('2013-01-30 00:00:00.000000', 0.04, 62)
2018-05-08 18:31:28,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,161 INFO sqlalchemy.engine.base.Engine ('2013-01-31 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:28,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,163 INFO sqlalchemy.engine.base.Engine ('2013-02-01 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:28,164 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:28,164 INFO sqlalchemy.engine.base.Engine ('2013-02-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:28,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,166 INFO sqlalchemy.engine.base.Engine ('2013-02-03 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:28,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,167 INFO sqlalchemy.engine.base.Engine ('2013-02-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:28,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,169 INFO sqlalchemy.engine.base.Engine ('2013-02-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:28,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,170 INFO sqlalchemy.engine.base.Engine ('2013-02-06 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:28,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,172 INFO sqlalchemy.engine.base.Engine ('2013-02-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:28,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,173 INFO sqlalchemy.engine.base.Engine ('2013-02-08 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:28,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,175 INFO sqlalchemy.engine.base.Engine ('2013-02-09 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:28,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,177 INFO sqlalchemy.engine.base.Engine ('2013-02-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:28,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:28,179 INFO sqlalchemy.engine.base.Engine ('2013-02-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,113 INFO sqlalchemy.engine.base.Engine ('2014-06-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,115 INFO sqlalchemy.engine.base.Engine ('2014-06-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,117 INFO sqlalchemy.engine.base.Engine ('2014-06-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,118 INFO sqlalchemy.engine.base.Engine ('2014-06-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,120 INFO sqlalchemy.engine.base.Engine ('2014-06-07 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,122 INFO sqlalchemy.engine.base.Engine ('2014-06-08 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,123 INFO sqlalchemy.engine.base.Engine ('2014-06-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,125 INFO sqlalchemy.engine.base.Engine ('2014-06-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,126 INFO sqlalchemy.engine.base.Engine ('2014-06-11 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:29,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,128 INFO sqlalchemy.engine.base.Engine ('2014-06-12 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,130 INFO sqlalchemy.engine.base.Engine ('2014-06-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,131 INFO sqlalchemy.engine.base.Engine ('2014-06-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:29,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,133 INFO sqlalchemy.engine.base.Engine ('2014-06-15 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,134 INFO sqlalchemy.engine.base.Engine ('2014-06-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,136 INFO sqlalchemy.engine.base.Engine ('2014-06-17 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:29,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,184 INFO sqlalchemy.engine.base.Engine ('2014-06-18 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:29,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,186 INFO sqlalchemy.engine.base.Engine ('2014-06-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,188 INFO sqlalchemy.engine.base.Engine ('2014-06-20 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:29,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,190 INFO sqlalchemy.engine.base.Engine ('2014-06-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,191 INFO sqlalchemy.engine.base.Engine ('2014-06-22 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,193 INFO sqlalchemy.engine.base.Engine ('2014-06-23 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:29,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,194 INFO sqlalchemy.engine.base.Engine ('2014-06-24 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:29,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,196 INFO sqlalchemy.engine.base.Engine ('2014-06-25 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:29,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,198 INFO sqlalchemy.engine.base.Engine ('2014-06-26 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:29,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,199 INFO sqlalchemy.engine.base.Engine ('2014-06-27 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:29,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,201 INFO sqlalchemy.engine.base.Engine ('2014-06-29 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:29,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,202 INFO sqlalchemy.engine.base.Engine ('2014-06-30 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,204 INFO sqlalchemy.engine.base.Engine ('2014-07-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,205 INFO sqlalchemy.engine.base.Engine ('2014-07-02 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:29,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,207 INFO sqlalchemy.engine.base.Engine ('2014-07-03 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:29,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,208 INFO sqlalchemy.engine.base.Engine ('2014-07-04 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,210 INFO sqlalchemy.engine.base.Engine ('2014-07-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,211 INFO sqlalchemy.engine.base.Engine ('2014-07-06 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:29,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,213 INFO sqlalchemy.engine.base.Engine ('2014-07-07 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:29,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,215 INFO sqlalchemy.engine.base.Engine ('2014-07-08 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:29,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,216 INFO sqlalchemy.engine.base.Engine ('2014-07-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,218 INFO sqlalchemy.engine.base.Engine ('2014-07-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,219 INFO sqlalchemy.engine.base.Engine ('2014-07-11 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:29,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,221 INFO sqlalchemy.engine.base.Engine ('2014-07-12 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,223 INFO sqlalchemy.engine.base.Engine ('2014-07-13 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:29,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,224 INFO sqlalchemy.engine.base.Engine ('2014-07-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,226 INFO sqlalchemy.engine.base.Engine ('2014-07-15 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:29,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,228 INFO sqlalchemy.engine.base.Engine ('2014-07-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,230 INFO sqlalchemy.engine.base.Engine ('2014-07-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,231 INFO sqlalchemy.engine.base.Engine ('2014-07-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,233 INFO sqlalchemy.engine.base.Engine ('2014-07-19 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:29,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,235 INFO sqlalchemy.engine.base.Engine ('2014-07-20 00:00:00.000000', 1.0, 74)
2018-05-08 18:31:29,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,236 INFO sqlalchemy.engine.base.Engine ('2014-07-21 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:29,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,238 INFO sqlalchemy.engine.base.Engine ('2014-07-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,239 INFO sqlalchemy.engine.base.Engine ('2014-07-23 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:29,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,241 INFO sqlalchemy.engine.base.Engine ('2014-07-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,243 INFO sqlalchemy.engine.base.Engine ('2014-07-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,244 INFO sqlalchemy.engine.base.Engine ('2014-07-26 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,246 INFO sqlalchemy.engine.base.Engine ('2014-07-27 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:29,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,248 INFO sqlalchemy.engine.base.Engine ('2014-07-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,249 INFO sqlalchemy.engine.base.Engine ('2014-07-29 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,251 INFO sqlalchemy.engine.base.Engine ('2014-07-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,253 INFO sqlalchemy.engine.base.Engine ('2014-07-31 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:29,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,256 INFO sqlalchemy.engine.base.Engine ('2014-08-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,257 INFO sqlalchemy.engine.base.Engine ('2014-08-02 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,259 INFO sqlalchemy.engine.base.Engine ('2014-08-03 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:29,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,261 INFO sqlalchemy.engine.base.Engine ('2014-08-04 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:29,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,262 INFO sqlalchemy.engine.base.Engine ('2014-08-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,264 INFO sqlalchemy.engine.base.Engine ('2014-08-06 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:29,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,266 INFO sqlalchemy.engine.base.Engine ('2014-08-07 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:29,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,268 INFO sqlalchemy.engine.base.Engine ('2014-08-08 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:29,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,269 INFO sqlalchemy.engine.base.Engine ('2014-08-09 00:00:00.000000', 0.42, 74)
2018-05-08 18:31:29,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,271 INFO sqlalchemy.engine.base.Engine ('2014-08-10 00:00:00.000000', 0.01, 82)
2018-05-08 18:31:29,272 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,272 INFO sqlalchemy.engine.base.Engine ('2014-08-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,274 INFO sqlalchemy.engine.base.Engine ('2014-08-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,276 INFO sqlalchemy.engine.base.Engine ('2014-08-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,277 INFO sqlalchemy.engine.base.Engine ('2014-08-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,279 INFO sqlalchemy.engine.base.Engine ('2014-08-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,281 INFO sqlalchemy.engine.base.Engine ('2014-08-16 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:29,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,282 INFO sqlalchemy.engine.base.Engine ('2014-08-17 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,284 INFO sqlalchemy.engine.base.Engine ('2014-08-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,285 INFO sqlalchemy.engine.base.Engine ('2014-08-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,287 INFO sqlalchemy.engine.base.Engine ('2014-08-20 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,288 INFO sqlalchemy.engine.base.Engine ('2014-08-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,290 INFO sqlalchemy.engine.base.Engine ('2014-08-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,291 INFO sqlalchemy.engine.base.Engine ('2014-08-25 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:29,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,293 INFO sqlalchemy.engine.base.Engine ('2014-08-26 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:29,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,294 INFO sqlalchemy.engine.base.Engine ('2014-08-27 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,296 INFO sqlalchemy.engine.base.Engine ('2014-08-28 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,297 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,297 INFO sqlalchemy.engine.base.Engine ('2014-08-29 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,299 INFO sqlalchemy.engine.base.Engine ('2014-08-30 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,300 INFO sqlalchemy.engine.base.Engine ('2014-08-31 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,302 INFO sqlalchemy.engine.base.Engine ('2014-09-01 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,304 INFO sqlalchemy.engine.base.Engine ('2014-09-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,306 INFO sqlalchemy.engine.base.Engine ('2014-09-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,308 INFO sqlalchemy.engine.base.Engine ('2014-09-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,310 INFO sqlalchemy.engine.base.Engine ('2014-09-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,312 INFO sqlalchemy.engine.base.Engine ('2014-09-06 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,313 INFO sqlalchemy.engine.base.Engine ('2014-09-07 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,315 INFO sqlalchemy.engine.base.Engine ('2014-09-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,316 INFO sqlalchemy.engine.base.Engine ('2014-09-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,318 INFO sqlalchemy.engine.base.Engine ('2014-09-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,319 INFO sqlalchemy.engine.base.Engine ('2014-09-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,321 INFO sqlalchemy.engine.base.Engine ('2014-09-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,322 INFO sqlalchemy.engine.base.Engine ('2014-09-13 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,324 INFO sqlalchemy.engine.base.Engine ('2014-09-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,325 INFO sqlalchemy.engine.base.Engine ('2014-09-15 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:29,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,327 INFO sqlalchemy.engine.base.Engine ('2014-09-18 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:29,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,329 INFO sqlalchemy.engine.base.Engine ('2014-09-19 00:00:00.000000', 0.54, 71)
2018-05-08 18:31:29,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,330 INFO sqlalchemy.engine.base.Engine ('2014-09-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,332 INFO sqlalchemy.engine.base.Engine ('2014-09-21 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,334 INFO sqlalchemy.engine.base.Engine ('2014-09-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,335 INFO sqlalchemy.engine.base.Engine ('2014-09-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,337 INFO sqlalchemy.engine.base.Engine ('2014-09-24 00:00:00.000000', 0.0, 85)
2018-05-08 18:31:29,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,338 INFO sqlalchemy.engine.base.Engine ('2014-09-25 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:29,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,340 INFO sqlalchemy.engine.base.Engine ('2014-09-26 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:29,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,341 INFO sqlalchemy.engine.base.Engine ('2014-09-27 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:29,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,343 INFO sqlalchemy.engine.base.Engine ('2014-09-28 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:29,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,344 INFO sqlalchemy.engine.base.Engine ('2014-09-29 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:29,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,346 INFO sqlalchemy.engine.base.Engine ('2014-09-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,390 INFO sqlalchemy.engine.base.Engine ('2014-10-01 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:29,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,391 INFO sqlalchemy.engine.base.Engine ('2014-10-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,393 INFO sqlalchemy.engine.base.Engine ('2014-10-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,394 INFO sqlalchemy.engine.base.Engine ('2014-10-04 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,396 INFO sqlalchemy.engine.base.Engine ('2014-10-05 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,397 INFO sqlalchemy.engine.base.Engine ('2014-10-06 00:00:00.000000', 0.38, 70)
2018-05-08 18:31:29,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,399 INFO sqlalchemy.engine.base.Engine ('2014-10-07 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:29,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,400 INFO sqlalchemy.engine.base.Engine ('2014-10-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,402 INFO sqlalchemy.engine.base.Engine ('2014-10-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,404 INFO sqlalchemy.engine.base.Engine ('2014-10-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,405 INFO sqlalchemy.engine.base.Engine ('2014-10-11 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:29,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,406 INFO sqlalchemy.engine.base.Engine ('2014-10-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,408 INFO sqlalchemy.engine.base.Engine ('2014-10-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,410 INFO sqlalchemy.engine.base.Engine ('2014-10-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,411 INFO sqlalchemy.engine.base.Engine ('2014-10-15 00:00:00.000000', 0.03, 80)
2018-05-08 18:31:29,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,413 INFO sqlalchemy.engine.base.Engine ('2014-10-16 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:29,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,414 INFO sqlalchemy.engine.base.Engine ('2014-10-17 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,416 INFO sqlalchemy.engine.base.Engine ('2014-10-18 00:00:00.000000', 0.07, 83)
2018-05-08 18:31:29,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,417 INFO sqlalchemy.engine.base.Engine ('2014-10-19 00:00:00.000000', 4.0, 74)
2018-05-08 18:31:29,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,419 INFO sqlalchemy.engine.base.Engine ('2014-10-20 00:00:00.000000', 1.7, 76)
2018-05-08 18:31:29,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,420 INFO sqlalchemy.engine.base.Engine ('2014-10-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,422 INFO sqlalchemy.engine.base.Engine ('2014-10-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,423 INFO sqlalchemy.engine.base.Engine ('2014-10-23 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:29,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,424 INFO sqlalchemy.engine.base.Engine ('2014-10-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,426 INFO sqlalchemy.engine.base.Engine ('2014-10-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,428 INFO sqlalchemy.engine.base.Engine ('2014-10-26 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:29,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,429 INFO sqlalchemy.engine.base.Engine ('2014-10-27 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,430 INFO sqlalchemy.engine.base.Engine ('2014-10-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,432 INFO sqlalchemy.engine.base.Engine ('2014-10-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,433 INFO sqlalchemy.engine.base.Engine ('2014-10-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,435 INFO sqlalchemy.engine.base.Engine ('2014-10-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,436 INFO sqlalchemy.engine.base.Engine ('2014-11-02 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:29,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,438 INFO sqlalchemy.engine.base.Engine ('2014-11-03 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:29,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,439 INFO sqlalchemy.engine.base.Engine ('2014-11-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,441 INFO sqlalchemy.engine.base.Engine ('2014-11-05 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,442 INFO sqlalchemy.engine.base.Engine ('2014-11-06 00:00:00.000000', 0.04, 66)
2018-05-08 18:31:29,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,444 INFO sqlalchemy.engine.base.Engine ('2014-11-07 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:29,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,445 INFO sqlalchemy.engine.base.Engine ('2014-11-08 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:29,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,447 INFO sqlalchemy.engine.base.Engine ('2014-11-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,448 INFO sqlalchemy.engine.base.Engine ('2014-11-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,450 INFO sqlalchemy.engine.base.Engine ('2014-11-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:29,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,451 INFO sqlalchemy.engine.base.Engine ('2014-11-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,453 INFO sqlalchemy.engine.base.Engine ('2014-11-13 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,454 INFO sqlalchemy.engine.base.Engine ('2014-11-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,456 INFO sqlalchemy.engine.base.Engine ('2014-11-15 00:00:00.000000', 0.41, 75)
2018-05-08 18:31:29,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,458 INFO sqlalchemy.engine.base.Engine ('2014-11-16 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:29,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,459 INFO sqlalchemy.engine.base.Engine ('2014-11-17 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,461 INFO sqlalchemy.engine.base.Engine ('2014-11-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,463 INFO sqlalchemy.engine.base.Engine ('2014-11-20 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:29,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,464 INFO sqlalchemy.engine.base.Engine ('2014-11-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,466 INFO sqlalchemy.engine.base.Engine ('2014-11-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,467 INFO sqlalchemy.engine.base.Engine ('2014-11-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,469 INFO sqlalchemy.engine.base.Engine ('2014-11-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,471 INFO sqlalchemy.engine.base.Engine ('2014-11-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,473 INFO sqlalchemy.engine.base.Engine ('2014-11-26 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,474 INFO sqlalchemy.engine.base.Engine ('2014-11-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,475 INFO sqlalchemy.engine.base.Engine ('2014-11-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,477 INFO sqlalchemy.engine.base.Engine ('2014-11-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,479 INFO sqlalchemy.engine.base.Engine ('2014-11-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,480 INFO sqlalchemy.engine.base.Engine ('2014-12-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,482 INFO sqlalchemy.engine.base.Engine ('2014-12-02 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:29,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,483 INFO sqlalchemy.engine.base.Engine ('2014-12-03 00:00:00.000000', 0.17, 68)
2018-05-08 18:31:29,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,484 INFO sqlalchemy.engine.base.Engine ('2014-12-04 00:00:00.000000', 0.09, 67)
2018-05-08 18:31:29,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,486 INFO sqlalchemy.engine.base.Engine ('2014-12-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,487 INFO sqlalchemy.engine.base.Engine ('2014-12-06 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,489 INFO sqlalchemy.engine.base.Engine ('2014-12-07 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,490 INFO sqlalchemy.engine.base.Engine ('2014-12-08 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:29,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,491 INFO sqlalchemy.engine.base.Engine ('2014-12-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,493 INFO sqlalchemy.engine.base.Engine ('2014-12-10 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:29,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,495 INFO sqlalchemy.engine.base.Engine ('2014-12-11 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:29,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,496 INFO sqlalchemy.engine.base.Engine ('2014-12-12 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,497 INFO sqlalchemy.engine.base.Engine ('2014-12-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,499 INFO sqlalchemy.engine.base.Engine ('2014-12-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,500 INFO sqlalchemy.engine.base.Engine ('2014-12-17 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:29,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,502 INFO sqlalchemy.engine.base.Engine ('2014-12-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,503 INFO sqlalchemy.engine.base.Engine ('2014-12-19 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,505 INFO sqlalchemy.engine.base.Engine ('2014-12-20 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:29,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,506 INFO sqlalchemy.engine.base.Engine ('2014-12-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:29,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,508 INFO sqlalchemy.engine.base.Engine ('2014-12-22 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:29,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,509 INFO sqlalchemy.engine.base.Engine ('2014-12-23 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:29,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,511 INFO sqlalchemy.engine.base.Engine ('2014-12-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,512 INFO sqlalchemy.engine.base.Engine ('2014-12-25 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:29,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,514 INFO sqlalchemy.engine.base.Engine ('2014-12-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,516 INFO sqlalchemy.engine.base.Engine ('2014-12-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,517 INFO sqlalchemy.engine.base.Engine ('2014-12-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,519 INFO sqlalchemy.engine.base.Engine ('2014-12-29 00:00:00.000000', 0.0, 57)
2018-05-08 18:31:29,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,520 INFO sqlalchemy.engine.base.Engine ('2014-12-30 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,522 INFO sqlalchemy.engine.base.Engine ('2014-12-31 00:00:00.000000', 0.7, 57)
2018-05-08 18:31:29,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,523 INFO sqlalchemy.engine.base.Engine ('2015-01-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,525 INFO sqlalchemy.engine.base.Engine ('2015-01-02 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,527 INFO sqlalchemy.engine.base.Engine ('2015-01-03 00:00:00.000000', 0.75, 69)
2018-05-08 18:31:29,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,528 INFO sqlalchemy.engine.base.Engine ('2015-01-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:29,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,530 INFO sqlalchemy.engine.base.Engine ('2015-01-05 00:00:00.000000', 0.0, 56)
2018-05-08 18:31:29,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,531 INFO sqlalchemy.engine.base.Engine ('2015-01-06 00:00:00.000000', 0.01, 63)
2018-05-08 18:31:29,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,532 INFO sqlalchemy.engine.base.Engine ('2015-01-07 00:00:00.000000', 0.0, 57)
2018-05-08 18:31:29,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,534 INFO sqlalchemy.engine.base.Engine ('2015-01-08 00:00:00.000000', 0.0, 57)
2018-05-08 18:31:29,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,535 INFO sqlalchemy.engine.base.Engine ('2015-01-09 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:29,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,537 INFO sqlalchemy.engine.base.Engine ('2015-01-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,538 INFO sqlalchemy.engine.base.Engine ('2015-01-11 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,540 INFO sqlalchemy.engine.base.Engine ('2015-01-12 00:00:00.000000', 0.01, 63)
2018-05-08 18:31:29,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,578 INFO sqlalchemy.engine.base.Engine ('2015-01-13 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:29,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,579 INFO sqlalchemy.engine.base.Engine ('2015-01-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,581 INFO sqlalchemy.engine.base.Engine ('2015-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,582 INFO sqlalchemy.engine.base.Engine ('2015-01-16 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:29,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,584 INFO sqlalchemy.engine.base.Engine ('2015-01-17 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:29,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,585 INFO sqlalchemy.engine.base.Engine ('2015-01-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,587 INFO sqlalchemy.engine.base.Engine ('2015-01-19 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:29,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,588 INFO sqlalchemy.engine.base.Engine ('2015-01-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,590 INFO sqlalchemy.engine.base.Engine ('2015-01-21 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:29,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,591 INFO sqlalchemy.engine.base.Engine ('2015-01-22 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,593 INFO sqlalchemy.engine.base.Engine ('2015-01-23 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,594 INFO sqlalchemy.engine.base.Engine ('2015-01-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,596 INFO sqlalchemy.engine.base.Engine ('2015-01-25 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,597 INFO sqlalchemy.engine.base.Engine ('2015-01-26 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,599 INFO sqlalchemy.engine.base.Engine ('2015-01-27 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:29,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,600 INFO sqlalchemy.engine.base.Engine ('2015-01-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,602 INFO sqlalchemy.engine.base.Engine ('2015-01-29 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:29,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,604 INFO sqlalchemy.engine.base.Engine ('2015-01-30 00:00:00.000000', 0.07, 60)
2018-05-08 18:31:29,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,605 INFO sqlalchemy.engine.base.Engine ('2015-01-31 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,606 INFO sqlalchemy.engine.base.Engine ('2015-02-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,608 INFO sqlalchemy.engine.base.Engine ('2015-02-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,609 INFO sqlalchemy.engine.base.Engine ('2015-02-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,611 INFO sqlalchemy.engine.base.Engine ('2015-02-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,613 INFO sqlalchemy.engine.base.Engine ('2015-02-08 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,614 INFO sqlalchemy.engine.base.Engine ('2015-02-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,617 INFO sqlalchemy.engine.base.Engine ('2015-02-10 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:29,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,619 INFO sqlalchemy.engine.base.Engine ('2015-02-11 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,620 INFO sqlalchemy.engine.base.Engine ('2015-02-12 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:29,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,622 INFO sqlalchemy.engine.base.Engine ('2015-02-15 00:00:00.000000', 0.02, 63)
2018-05-08 18:31:29,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,624 INFO sqlalchemy.engine.base.Engine ('2015-02-16 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,625 INFO sqlalchemy.engine.base.Engine ('2015-02-17 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:29,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,626 INFO sqlalchemy.engine.base.Engine ('2015-02-18 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:29,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,628 INFO sqlalchemy.engine.base.Engine ('2015-02-19 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,629 INFO sqlalchemy.engine.base.Engine ('2015-02-20 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,630 INFO sqlalchemy.engine.base.Engine ('2015-02-21 00:00:00.000000', 0.28, 63)
2018-05-08 18:31:29,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,632 INFO sqlalchemy.engine.base.Engine ('2015-02-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,633 INFO sqlalchemy.engine.base.Engine ('2015-02-23 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,635 INFO sqlalchemy.engine.base.Engine ('2015-02-24 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:29,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,636 INFO sqlalchemy.engine.base.Engine ('2015-02-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,638 INFO sqlalchemy.engine.base.Engine ('2015-02-26 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,639 INFO sqlalchemy.engine.base.Engine ('2015-03-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,641 INFO sqlalchemy.engine.base.Engine ('2015-03-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,642 INFO sqlalchemy.engine.base.Engine ('2015-03-05 00:00:00.000000', 0.17, 73)
2018-05-08 18:31:29,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,644 INFO sqlalchemy.engine.base.Engine ('2015-03-06 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,645 INFO sqlalchemy.engine.base.Engine ('2015-03-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,646 INFO sqlalchemy.engine.base.Engine ('2015-03-08 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,648 INFO sqlalchemy.engine.base.Engine ('2015-03-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,650 INFO sqlalchemy.engine.base.Engine ('2015-03-12 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:29,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,651 INFO sqlalchemy.engine.base.Engine ('2015-03-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,653 INFO sqlalchemy.engine.base.Engine ('2015-03-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,654 INFO sqlalchemy.engine.base.Engine ('2015-03-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,656 INFO sqlalchemy.engine.base.Engine ('2015-03-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,657 INFO sqlalchemy.engine.base.Engine ('2015-04-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,659 INFO sqlalchemy.engine.base.Engine ('2015-04-07 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:29,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,660 INFO sqlalchemy.engine.base.Engine ('2015-04-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,662 INFO sqlalchemy.engine.base.Engine ('2015-04-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,663 INFO sqlalchemy.engine.base.Engine ('2015-04-10 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,665 INFO sqlalchemy.engine.base.Engine ('2015-04-14 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:29,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,666 INFO sqlalchemy.engine.base.Engine ('2015-04-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,668 INFO sqlalchemy.engine.base.Engine ('2015-04-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,669 INFO sqlalchemy.engine.base.Engine ('2015-04-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,671 INFO sqlalchemy.engine.base.Engine ('2015-04-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,672 INFO sqlalchemy.engine.base.Engine ('2015-04-22 00:00:00.000000', 0.05, 66)
2018-05-08 18:31:29,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,674 INFO sqlalchemy.engine.base.Engine ('2015-04-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,675 INFO sqlalchemy.engine.base.Engine ('2015-04-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,677 INFO sqlalchemy.engine.base.Engine ('2015-04-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,679 INFO sqlalchemy.engine.base.Engine ('2015-05-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,681 INFO sqlalchemy.engine.base.Engine ('2015-05-05 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,682 INFO sqlalchemy.engine.base.Engine ('2015-05-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,684 INFO sqlalchemy.engine.base.Engine ('2015-05-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,685 INFO sqlalchemy.engine.base.Engine ('2015-05-08 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:29,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,686 INFO sqlalchemy.engine.base.Engine ('2015-05-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,688 INFO sqlalchemy.engine.base.Engine ('2015-05-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,690 INFO sqlalchemy.engine.base.Engine ('2015-05-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:29,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,691 INFO sqlalchemy.engine.base.Engine ('2015-05-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:29,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,693 INFO sqlalchemy.engine.base.Engine ('2015-05-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,694 INFO sqlalchemy.engine.base.Engine ('2015-05-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,696 INFO sqlalchemy.engine.base.Engine ('2015-05-21 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,697 INFO sqlalchemy.engine.base.Engine ('2015-05-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,698 INFO sqlalchemy.engine.base.Engine ('2015-05-27 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,700 INFO sqlalchemy.engine.base.Engine ('2015-05-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:29,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,701 INFO sqlalchemy.engine.base.Engine ('2015-05-29 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,703 INFO sqlalchemy.engine.base.Engine ('2015-06-01 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:29,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,704 INFO sqlalchemy.engine.base.Engine ('2015-06-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,706 INFO sqlalchemy.engine.base.Engine ('2015-06-03 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,708 INFO sqlalchemy.engine.base.Engine ('2015-06-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,709 INFO sqlalchemy.engine.base.Engine ('2015-06-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,711 INFO sqlalchemy.engine.base.Engine ('2015-06-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,712 INFO sqlalchemy.engine.base.Engine ('2015-06-12 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,714 INFO sqlalchemy.engine.base.Engine ('2015-06-16 00:00:00.000000', 0.2, 69)
2018-05-08 18:31:29,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:29,715 INFO sqlalchemy.engine.base.Engine ('2015-06-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,716 INFO sqlalchemy.engine.base.Engine ('2015-06-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,718 INFO sqlalchemy.engine.base.Engine ('2015-06-19 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,719 INFO sqlalchemy.engine.base.Engine ('2015-06-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,721 INFO sqlalchemy.engine.base.Engine ('2015-06-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,722 INFO sqlalchemy.engine.base.Engine ('2015-06-25 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:29,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,724 INFO sqlalchemy.engine.base.Engine ('2015-06-26 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:29,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,725 INFO sqlalchemy.engine.base.Engine ('2015-07-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,727 INFO sqlalchemy.engine.base.Engine ('2015-07-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,728 INFO sqlalchemy.engine.base.Engine ('2015-07-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,768 INFO sqlalchemy.engine.base.Engine ('2015-07-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,770 INFO sqlalchemy.engine.base.Engine ('2015-07-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,771 INFO sqlalchemy.engine.base.Engine ('2015-07-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,773 INFO sqlalchemy.engine.base.Engine ('2015-07-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,774 INFO sqlalchemy.engine.base.Engine ('2015-07-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,776 INFO sqlalchemy.engine.base.Engine ('2015-07-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,777 INFO sqlalchemy.engine.base.Engine ('2015-07-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,779 INFO sqlalchemy.engine.base.Engine ('2015-07-31 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,780 INFO sqlalchemy.engine.base.Engine ('2015-08-04 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:29,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,782 INFO sqlalchemy.engine.base.Engine ('2015-08-05 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:29,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,783 INFO sqlalchemy.engine.base.Engine ('2015-08-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,785 INFO sqlalchemy.engine.base.Engine ('2015-08-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:29,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,787 INFO sqlalchemy.engine.base.Engine ('2015-08-20 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:29,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,788 INFO sqlalchemy.engine.base.Engine ('2015-08-25 00:00:00.000000', 1.3, 79)
2018-05-08 18:31:29,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,790 INFO sqlalchemy.engine.base.Engine ('2015-08-26 00:00:00.000000', 0.8, 76)
2018-05-08 18:31:29,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,792 INFO sqlalchemy.engine.base.Engine ('2015-09-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:29,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,794 INFO sqlalchemy.engine.base.Engine ('2015-09-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,796 INFO sqlalchemy.engine.base.Engine ('2015-09-03 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:29,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,797 INFO sqlalchemy.engine.base.Engine ('2015-09-04 00:00:00.000000', 0.7, 73)
2018-05-08 18:31:29,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,799 INFO sqlalchemy.engine.base.Engine ('2015-09-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,801 INFO sqlalchemy.engine.base.Engine ('2015-09-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,802 INFO sqlalchemy.engine.base.Engine ('2015-09-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,804 INFO sqlalchemy.engine.base.Engine ('2015-09-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,805 INFO sqlalchemy.engine.base.Engine ('2015-09-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,807 INFO sqlalchemy.engine.base.Engine ('2015-09-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:29,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,808 INFO sqlalchemy.engine.base.Engine ('2015-10-08 00:00:00.000000', 0.0, 83)

2018-05-08 18:31:29,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,810 INFO sqlalchemy.engine.base.Engine ('2015-10-09 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:29,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,811 INFO sqlalchemy.engine.base.Engine ('2015-10-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,813 INFO sqlalchemy.engine.base.Engine ('2015-10-13 00:00:00.000000', 0.4, 72)
2018-05-08 18:31:29,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,814 INFO sqlalchemy.engine.base.Engine ('2015-10-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,816 INFO sqlalchemy.engine.base.Engine ('2015-10-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,817 INFO sqlalchemy.engine.base.Engine ('2015-10-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,819 INFO sqlalchemy.engine.base.Engine ('2015-10-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,820 INFO sqlalchemy.engine.base.Engine ('2015-10-20 00:00:00.000000', 0.3, 75)
2018-05-08 18:31:29,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,821 INFO sqlalchemy.engine.base.Engine ('2015-10-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,823 INFO sqlalchemy.engine.base.Engine ('2015-10-22 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:29,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,825 INFO sqlalchemy.engine.base.Engine ('2015-10-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,826 INFO sqlalchemy.engine.base.Engine ('2015-10-26 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:29,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,828 INFO sqlalchemy.engine.base.Engine ('2015-10-28 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:29,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,830 INFO sqlalchemy.engine.base.Engine ('2015-10-29 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00511918" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,831 INFO sqlalchemy.engine.base.Engine ('2015-10-30 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,858 INFO sqlalchemy.engine.base.Engine ('2010-01-01 00:00:00.000000', 0.08, 65)
2018-05-08 18:31:29,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,860 INFO sqlalchemy.engine.base.Engine ('2010-01-02 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:29,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,862 INFO sqlalchemy.engine.base.Engine ('2010-01-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:29,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,863 INFO sqlalchemy.engine.base.Engine ('2010-01-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,865 INFO sqlalchemy.engine.base.Engine ('2010-01-07 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:29,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,867 INFO sqlalchemy.engine.base.Engine ('2010-01-08 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,869 INFO sqlalchemy.engine.base.Engine ('2010-01-09 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,871 INFO sqlalchemy.engine.base.Engine ('2010-01-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,872 INFO sqlalchemy.engine.base.Engine ('2010-01-11 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:29,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,874 INFO sqlalchemy.engine.base.Engine ('2010-01-12 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:29,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,876 INFO sqlalchemy.engine.base.Engine ('2010-01-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,877 INFO sqlalchemy.engine.base.Engine ('2010-01-15 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,879 INFO sqlalchemy.engine.base.Engine ('2010-01-16 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,881 INFO sqlalchemy.engine.base.Engine ('2010-01-17 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,882 INFO sqlalchemy.engine.base.Engine ('2010-01-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,884 INFO sqlalchemy.engine.base.Engine ('2010-01-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,885 INFO sqlalchemy.engine.base.Engine ('2010-01-20 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,886 INFO sqlalchemy.engine.base.Engine ('2010-01-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,888 INFO sqlalchemy.engine.base.Engine ('2010-01-22 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,889 INFO sqlalchemy.engine.base.Engine ('2010-01-23 00:00:00.000000', 0.0, 67)

2018-05-08 18:31:29,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,891 INFO sqlalchemy.engine.base.Engine ('2010-01-24 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:29,892 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,892 INFO sqlalchemy.engine.base.Engine ('2010-01-25 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,894 INFO sqlalchemy.engine.base.Engine ('2010-01-26 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:29,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,895 INFO sqlalchemy.engine.base.Engine ('2010-01-27 00:00:00.000000', 0.12, 68)
2018-05-08 18:31:29,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,897 INFO sqlalchemy.engine.base.Engine ('2010-01-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,898 INFO sqlalchemy.engine.base.Engine ('2010-01-31 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:29,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,901 INFO sqlalchemy.engine.base.Engine ('2010-02-01 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:29,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,902 INFO sqlalchemy.engine.base.Engine ('2010-02-04 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:29,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,904 INFO sqlalchemy.engine.base.Engine ('2010-02-05 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,905 INFO sqlalchemy.engine.base.Engine ('2010-02-06 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,907 INFO sqlalchemy.engine.base.Engine ('2010-02-07 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:29,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,909 INFO sqlalchemy.engine.base.Engine ('2010-02-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,910 INFO sqlalchemy.engine.base.Engine ('2010-02-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,912 INFO sqlalchemy.engine.base.Engine ('2010-02-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,913 INFO sqlalchemy.engine.base.Engine ('2010-02-12 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:29,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,915 INFO sqlalchemy.engine.base.Engine ('2010-02-13 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:29,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,916 INFO sqlalchemy.engine.base.Engine ('2010-02-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,918 INFO sqlalchemy.engine.base.Engine ('2010-02-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:29,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,919 INFO sqlalchemy.engine.base.Engine ('2010-02-16 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:29,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,921 INFO sqlalchemy.engine.base.Engine ('2010-02-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:29,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,922 INFO sqlalchemy.engine.base.Engine ('2010-02-20 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:29,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,924 INFO sqlalchemy.engine.base.Engine ('2010-02-21 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,925 INFO sqlalchemy.engine.base.Engine ('2010-02-22 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:29,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,927 INFO sqlalchemy.engine.base.Engine ('2010-02-23 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:29,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,928 INFO sqlalchemy.engine.base.Engine ('2010-02-24 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:29,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,930 INFO sqlalchemy.engine.base.Engine ('2010-02-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:29,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,931 INFO sqlalchemy.engine.base.Engine ('2010-02-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:29,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,933 INFO sqlalchemy.engine.base.Engine ('2010-02-28 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:29,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,934 INFO sqlalchemy.engine.base.Engine ('2010-03-01 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:29,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,936 INFO sqlalchemy.engine.base.Engine ('2010-03-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,937 INFO sqlalchemy.engine.base.Engine ('2010-03-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:29,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,938 INFO sqlalchemy.engine.base.Engine ('2010-03-04 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:29,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,940 INFO sqlalchemy.engine.base.Engine ('2010-03-05 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:29,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,941 INFO sqlalchemy.engine.base.Engine ('2010-03-06 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:29,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,943 INFO sqlalchemy.engine.base.Engine ('2010-03-07 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:29,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,945 INFO sqlalchemy.engine.base.Engine ('2010-03-08 00:00:00.000000', 0.43, 69)
2018-05-08 18:31:29,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,947 INFO sqlalchemy.engine.base.Engine ('2010-03-09 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:29,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,948 INFO sqlalchemy.engine.base.Engine ('2010-03-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:29,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:29,950 INFO sqlalchemy.engine.base.Engine ('2010-03-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:30,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,002 INFO sqlalchemy.engine.base.Engine ('2010-03-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:30,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,004 INFO sqlalchemy.engine.base.Engine ('2010-03-15 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:30,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,006 INFO sqlalchemy.engine.base.Engine ('2010-03-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:30,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,008 INFO sqlalchemy.engine.base.Engine ('2010-03-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:30,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,010 INFO sqlalchemy.engine.base.Engine ('2010-03-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:30,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,012 INFO sqlalchemy.engine.base.Engine ('2010-03-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:30,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,014 INFO sqlalchemy.engine.base.Engine ('2010-03-23 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:30,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,016 INFO sqlalchemy.engine.base.Engine ('2010-03-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:30,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,018 INFO sqlalchemy.engine.base.Engine ('2010-03-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:30,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,020 INFO sqlalchemy.engine.base.Engine ('2010-03-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:30,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,022 INFO sqlalchemy.engine.base.Engine ('2010-03-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:30,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,024 INFO sqlalchemy.engine.base.Engine ('2010-03-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:30,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,025 INFO sqlalchemy.engine.base.Engine ('2010-03-31 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:30,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,028 INFO sqlalchemy.engine.base.Engine ('2010-04-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:30,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,029 INFO sqlalchemy.engine.base.Engine ('2010-04-02 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:30,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,031 INFO sqlalchemy.engine.base.Engine ('2010-04-03 00:00:00.000000', 0.17, 74)
2018-05-08 18:31:30,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,033 INFO sqlalchemy.engine.base.Engine ('2010-04-04 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:30,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,035 INFO sqlalchemy.engine.base.Engine ('2010-04-05 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:30,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,037 INFO sqlalchemy.engine.base.Engine ('2010-04-06 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:30,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,039 INFO sqlalchemy.engine.base.Engine ('2010-04-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:30,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,043 INFO sqlalchemy.engine.base.Engine ('2010-04-09 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:30,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,045 INFO sqlalchemy.engine.base.Engine ('2010-04-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:30,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,047 INFO sqlalchemy.engine.base.Engine ('2010-04-11 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:30,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,050 INFO sqlalchemy.engine.base.Engine ('2010-04-12 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:30,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,052 INFO sqlalchemy.engine.base.Engine ('2010-04-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:30,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,054 INFO sqlalchemy.engine.base.Engine ('2010-04-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:30,055 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,056 INFO sqlalchemy.engine.base.Engine ('2010-04-16 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:30,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,058 INFO sqlalchemy.engine.base.Engine ('2010-04-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:30,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,060 INFO sqlalchemy.engine.base.Engine ('2010-04-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:30,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,062 INFO sqlalchemy.engine.base.Engine ('2010-04-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:30,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,065 INFO sqlalchemy.engine.base.Engine ('2010-04-20 00:00:00.000000', 0.04, 71)

2018-05-08 18:31:30,066 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,067 INFO sqlalchemy.engine.base.Engine ('2010-04-21 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:30,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,069 INFO sqlalchemy.engine.base.Engine ('2010-04-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,071 INFO sqlalchemy.engine.base.Engine ('2010-04-23 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:30,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,074 INFO sqlalchemy.engine.base.Engine ('2010-04-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:30,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,075 INFO sqlalchemy.engine.base.Engine ('2010-04-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,077 INFO sqlalchemy.engine.base.Engine ('2010-04-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,079 INFO sqlalchemy.engine.base.Engine ('2010-04-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,081 INFO sqlalchemy.engine.base.Engine ('2010-04-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,083 INFO sqlalchemy.engine.base.Engine ('2010-05-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,085 INFO sqlalchemy.engine.base.Engine ('2010-05-02 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:30,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,087 INFO sqlalchemy.engine.base.Engine ('2010-05-03 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:30,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,089 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:30,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,090 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:30,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,092 INFO sqlalchemy.engine.base.Engine ('2010-05-06 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:30,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,094 INFO sqlalchemy.engine.base.Engine ('2010-05-07 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:30,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,096 INFO sqlalchemy.engine.base.Engine ('2010-05-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,100 INFO sqlalchemy.engine.base.Engine ('2010-05-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,102 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,104 INFO sqlalchemy.engine.base.Engine ('2010-05-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,106 INFO sqlalchemy.engine.base.Engine ('2010-05-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,107 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,109 INFO sqlalchemy.engine.base.Engine ('2010-05-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:30,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,111 INFO sqlalchemy.engine.base.Engine ('2010-05-16 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:30,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,115 INFO sqlalchemy.engine.base.Engine ('2010-05-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,117 INFO sqlalchemy.engine.base.Engine ('2010-05-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,120 INFO sqlalchemy.engine.base.Engine ('2010-05-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,123 INFO sqlalchemy.engine.base.Engine ('2010-05-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,125 INFO sqlalchemy.engine.base.Engine ('2010-05-23 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:30,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,126 INFO sqlalchemy.engine.base.Engine ('2010-05-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,128 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,132 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:30,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,134 INFO sqlalchemy.engine.base.Engine ('2010-05-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,136 INFO sqlalchemy.engine.base.Engine ('2010-05-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:30,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,137 INFO sqlalchemy.engine.base.Engine ('2010-05-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,139 INFO sqlalchemy.engine.base.Engine ('2010-05-30 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:30,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,141 INFO sqlalchemy.engine.base.Engine ('2010-05-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,142 INFO sqlalchemy.engine.base.Engine ('2010-06-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,143 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:30,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,145 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,148 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:30,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,150 INFO sqlalchemy.engine.base.Engine ('2010-06-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,152 INFO sqlalchemy.engine.base.Engine ('2010-06-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,154 INFO sqlalchemy.engine.base.Engine ('2010-06-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,155 INFO sqlalchemy.engine.base.Engine ('2010-06-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,157 INFO sqlalchemy.engine.base.Engine ('2010-06-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,159 INFO sqlalchemy.engine.base.Engine ('2010-06-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:30,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,160 INFO sqlalchemy.engine.base.Engine ('2010-06-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,162 INFO sqlalchemy.engine.base.Engine ('2010-06-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,164 INFO sqlalchemy.engine.base.Engine ('2010-06-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,166 INFO sqlalchemy.engine.base.Engine ('2010-06-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:30,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,169 INFO sqlalchemy.engine.base.Engine ('2010-06-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:30,171 INFO sqlalchemy.engine.base.Engine ('2010-06-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:30,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,155 INFO sqlalchemy.engine.base.Engine ('2011-09-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,157 INFO sqlalchemy.engine.base.Engine ('2011-09-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,158 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,160 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,161 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,163 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,164 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,165 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,166 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:31,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,168 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,169 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:31,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,171 INFO sqlalchemy.engine.base.Engine ('2011-10-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:31,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,173 INFO sqlalchemy.engine.base.Engine ('2011-10-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,174 INFO sqlalchemy.engine.base.Engine ('2011-10-10 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:31,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,176 INFO sqlalchemy.engine.base.Engine ('2011-10-11 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:31,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,178 INFO sqlalchemy.engine.base.Engine ('2011-10-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,179 INFO sqlalchemy.engine.base.Engine ('2011-10-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,181 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:31,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,183 INFO sqlalchemy.engine.base.Engine ('2011-10-15 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:31,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,184 INFO sqlalchemy.engine.base.Engine ('2011-10-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,186 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:31,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,188 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:31,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,190 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,191 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,193 INFO sqlalchemy.engine.base.Engine ('2011-10-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,195 INFO sqlalchemy.engine.base.Engine ('2011-10-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,196 INFO sqlalchemy.engine.base.Engine ('2011-10-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,197 INFO sqlalchemy.engine.base.Engine ('2011-10-24 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:31,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,199 INFO sqlalchemy.engine.base.Engine ('2011-10-25 00:00:00.000000', 1.6, 77)
2018-05-08 18:31:31,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,201 INFO sqlalchemy.engine.base.Engine ('2011-10-26 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:31,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,202 INFO sqlalchemy.engine.base.Engine ('2011-10-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,204 INFO sqlalchemy.engine.base.Engine ('2011-10-28 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:31,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,205 INFO sqlalchemy.engine.base.Engine ('2011-10-29 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:31,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,207 INFO sqlalchemy.engine.base.Engine ('2011-10-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,208 INFO sqlalchemy.engine.base.Engine ('2011-10-31 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:31,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,210 INFO sqlalchemy.engine.base.Engine ('2011-11-01 00:00:00.000000', 0.58, 71)
2018-05-08 18:31:31,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,211 INFO sqlalchemy.engine.base.Engine ('2011-11-02 00:00:00.000000', 0.28, 77)
2018-05-08 18:31:31,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,213 INFO sqlalchemy.engine.base.Engine ('2011-11-03 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:31,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,215 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:31,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,216 INFO sqlalchemy.engine.base.Engine ('2011-11-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,218 INFO sqlalchemy.engine.base.Engine ('2011-11-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,220 INFO sqlalchemy.engine.base.Engine ('2011-11-07 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,221 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,223 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:31,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,225 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,227 INFO sqlalchemy.engine.base.Engine ('2011-11-11 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:31,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,229 INFO sqlalchemy.engine.base.Engine ('2011-11-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,230 INFO sqlalchemy.engine.base.Engine ('2011-11-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,232 INFO sqlalchemy.engine.base.Engine ('2011-11-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,234 INFO sqlalchemy.engine.base.Engine ('2011-11-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,235 INFO sqlalchemy.engine.base.Engine ('2011-11-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,237 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,239 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,241 INFO sqlalchemy.engine.base.Engine ('2011-11-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,243 INFO sqlalchemy.engine.base.Engine ('2011-11-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,245 INFO sqlalchemy.engine.base.Engine ('2011-11-21 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:31,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,246 INFO sqlalchemy.engine.base.Engine ('2011-11-22 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:31,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,248 INFO sqlalchemy.engine.base.Engine ('2011-11-23 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:31,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,249 INFO sqlalchemy.engine.base.Engine ('2011-11-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,251 INFO sqlalchemy.engine.base.Engine ('2011-11-25 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:31,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,252 INFO sqlalchemy.engine.base.Engine ('2011-11-26 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:31,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,254 INFO sqlalchemy.engine.base.Engine ('2011-11-27 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:31,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,255 INFO sqlalchemy.engine.base.Engine ('2011-11-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,257 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,258 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:31,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,260 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:31,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,262 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.08, 68)
2018-05-08 18:31:31,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,263 INFO sqlalchemy.engine.base.Engine ('2011-12-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,265 INFO sqlalchemy.engine.base.Engine ('2011-12-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,266 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,268 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,270 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,271 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,272 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,273 INFO sqlalchemy.engine.base.Engine ('2011-12-09 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:31,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,275 INFO sqlalchemy.engine.base.Engine ('2011-12-10 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:31,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,277 INFO sqlalchemy.engine.base.Engine ('2011-12-11 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:31,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,279 INFO sqlalchemy.engine.base.Engine ('2011-12-12 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:31,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,281 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 0.4, 72)
2018-05-08 18:31:31,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,283 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 0.7, 71)
2018-05-08 18:31:31,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,284 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,286 INFO sqlalchemy.engine.base.Engine ('2011-12-16 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:31,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,288 INFO sqlalchemy.engine.base.Engine ('2011-12-17 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:31,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,290 INFO sqlalchemy.engine.base.Engine ('2011-12-18 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:31,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,292 INFO sqlalchemy.engine.base.Engine ('2011-12-19 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:31,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,295 INFO sqlalchemy.engine.base.Engine ('2011-12-20 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:31,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,297 INFO sqlalchemy.engine.base.Engine ('2011-12-21 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:31,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,299 INFO sqlalchemy.engine.base.Engine ('2011-12-22 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:31,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,300 INFO sqlalchemy.engine.base.Engine ('2011-12-23 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:31,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,302 INFO sqlalchemy.engine.base.Engine ('2011-12-24 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:31,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,304 INFO sqlalchemy.engine.base.Engine ('2011-12-25 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:31,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,306 INFO sqlalchemy.engine.base.Engine ('2011-12-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,308 INFO sqlalchemy.engine.base.Engine ('2011-12-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,310 INFO sqlalchemy.engine.base.Engine ('2011-12-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,312 INFO sqlalchemy.engine.base.Engine ('2011-12-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,314 INFO sqlalchemy.engine.base.Engine ('2011-12-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,316 INFO sqlalchemy.engine.base.Engine ('2011-12-31 00:00:00.000000', 0.01, 63)
2018-05-08 18:31:31,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,318 INFO sqlalchemy.engine.base.Engine ('2012-01-01 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:31,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,367 INFO sqlalchemy.engine.base.Engine ('2012-01-02 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:31,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,369 INFO sqlalchemy.engine.base.Engine ('2012-01-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:31,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,370 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,372 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,373 INFO sqlalchemy.engine.base.Engine ('2012-01-07 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:31,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,375 INFO sqlalchemy.engine.base.Engine ('2012-01-08 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:31,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,376 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,378 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:31,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,379 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:31,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,381 INFO sqlalchemy.engine.base.Engine ('2012-01-14 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:31,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,382 INFO sqlalchemy.engine.base.Engine ('2012-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,384 INFO sqlalchemy.engine.base.Engine ('2012-01-16 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:31,385 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,385 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,387 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,388 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:31,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,390 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,391 INFO sqlalchemy.engine.base.Engine ('2012-01-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,393 INFO sqlalchemy.engine.base.Engine ('2012-01-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,394 INFO sqlalchemy.engine.base.Engine ('2012-01-23 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:31,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,396 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:31,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,398 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:31,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,399 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,401 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:31,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,402 INFO sqlalchemy.engine.base.Engine ('2012-01-28 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:31,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,404 INFO sqlalchemy.engine.base.Engine ('2012-01-29 00:00:00.000000', 1.03, 72)
2018-05-08 18:31:31,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,405 INFO sqlalchemy.engine.base.Engine ('2012-01-30 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:31,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,407 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,408 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:31,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,410 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,411 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:31,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,414 INFO sqlalchemy.engine.base.Engine ('2012-02-04 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:31,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,415 INFO sqlalchemy.engine.base.Engine ('2012-02-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:31,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,417 INFO sqlalchemy.engine.base.Engine ('2012-02-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,418 INFO sqlalchemy.engine.base.Engine ('2012-02-07 00:00:00.000000', 0.37, 71)
2018-05-08 18:31:31,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,420 INFO sqlalchemy.engine.base.Engine ('2012-02-08 00:00:00.000000', 0.28, 65)
2018-05-08 18:31:31,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,421 INFO sqlalchemy.engine.base.Engine ('2012-02-09 00:00:00.000000', 0.01, 61)
2018-05-08 18:31:31,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,422 INFO sqlalchemy.engine.base.Engine ('2012-02-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,424 INFO sqlalchemy.engine.base.Engine ('2012-02-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,425 INFO sqlalchemy.engine.base.Engine ('2012-02-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,427 INFO sqlalchemy.engine.base.Engine ('2012-02-13 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:31,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,428 INFO sqlalchemy.engine.base.Engine ('2012-02-14 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:31,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,430 INFO sqlalchemy.engine.base.Engine ('2012-02-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:31,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,431 INFO sqlalchemy.engine.base.Engine ('2012-02-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,433 INFO sqlalchemy.engine.base.Engine ('2012-02-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,435 INFO sqlalchemy.engine.base.Engine ('2012-02-18 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:31,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,436 INFO sqlalchemy.engine.base.Engine ('2012-02-19 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:31,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,438 INFO sqlalchemy.engine.base.Engine ('2012-02-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,440 INFO sqlalchemy.engine.base.Engine ('2012-02-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,442 INFO sqlalchemy.engine.base.Engine ('2012-02-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,443 INFO sqlalchemy.engine.base.Engine ('2012-02-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,445 INFO sqlalchemy.engine.base.Engine ('2012-02-24 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:31,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,447 INFO sqlalchemy.engine.base.Engine ('2012-02-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:31,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,448 INFO sqlalchemy.engine.base.Engine ('2012-02-26 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:31,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,450 INFO sqlalchemy.engine.base.Engine ('2012-02-27 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:31,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,451 INFO sqlalchemy.engine.base.Engine ('2012-02-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,454 INFO sqlalchemy.engine.base.Engine ('2012-02-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,455 INFO sqlalchemy.engine.base.Engine ('2012-03-01 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:31,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,457 INFO sqlalchemy.engine.base.Engine ('2012-03-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:31,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,459 INFO sqlalchemy.engine.base.Engine ('2012-03-03 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:31,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,460 INFO sqlalchemy.engine.base.Engine ('2012-03-04 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:31,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,462 INFO sqlalchemy.engine.base.Engine ('2012-03-05 00:00:00.000000', 1.08, 67)
2018-05-08 18:31:31,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,463 INFO sqlalchemy.engine.base.Engine ('2012-03-06 00:00:00.000000', 4.0, 69)
2018-05-08 18:31:31,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,465 INFO sqlalchemy.engine.base.Engine ('2012-03-07 00:00:00.000000', 2.42, 67)
2018-05-08 18:31:31,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,467 INFO sqlalchemy.engine.base.Engine ('2012-03-08 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:31,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,468 INFO sqlalchemy.engine.base.Engine ('2012-03-09 00:00:00.000000', 0.19, 66)
2018-05-08 18:31:31,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,469 INFO sqlalchemy.engine.base.Engine ('2012-03-10 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:31,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,471 INFO sqlalchemy.engine.base.Engine ('2012-03-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,472 INFO sqlalchemy.engine.base.Engine ('2012-03-12 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:31,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,474 INFO sqlalchemy.engine.base.Engine ('2012-03-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,475 INFO sqlalchemy.engine.base.Engine ('2012-03-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,477 INFO sqlalchemy.engine.base.Engine ('2012-03-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:31,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,478 INFO sqlalchemy.engine.base.Engine ('2012-03-16 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:31,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,480 INFO sqlalchemy.engine.base.Engine ('2012-03-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,481 INFO sqlalchemy.engine.base.Engine ('2012-03-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,483 INFO sqlalchemy.engine.base.Engine ('2012-03-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,484 INFO sqlalchemy.engine.base.Engine ('2012-03-20 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:31,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,486 INFO sqlalchemy.engine.base.Engine ('2012-03-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,487 INFO sqlalchemy.engine.base.Engine ('2012-03-22 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:31,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,489 INFO sqlalchemy.engine.base.Engine ('2012-03-23 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:31,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,490 INFO sqlalchemy.engine.base.Engine ('2012-03-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,492 INFO sqlalchemy.engine.base.Engine ('2012-03-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,493 INFO sqlalchemy.engine.base.Engine ('2012-03-26 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:31,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,495 INFO sqlalchemy.engine.base.Engine ('2012-03-27 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:31,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,496 INFO sqlalchemy.engine.base.Engine ('2012-03-28 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:31,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,498 INFO sqlalchemy.engine.base.Engine ('2012-03-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,500 INFO sqlalchemy.engine.base.Engine ('2012-03-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,501 INFO sqlalchemy.engine.base.Engine ('2012-03-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,503 INFO sqlalchemy.engine.base.Engine ('2012-04-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,504 INFO sqlalchemy.engine.base.Engine ('2012-04-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,506 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,507 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,509 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.19, 74)
2018-05-08 18:31:31,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,510 INFO sqlalchemy.engine.base.Engine ('2012-04-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,512 INFO sqlalchemy.engine.base.Engine ('2012-04-07 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:31,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,513 INFO sqlalchemy.engine.base.Engine ('2012-04-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,515 INFO sqlalchemy.engine.base.Engine ('2012-04-09 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:31,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,517 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:31,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,518 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:31,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,519 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:31,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,521 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:31,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,560 INFO sqlalchemy.engine.base.Engine ('2012-04-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:31,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,562 INFO sqlalchemy.engine.base.Engine ('2012-04-15 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:31,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,564 INFO sqlalchemy.engine.base.Engine ('2012-04-16 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:31,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,565 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,567 INFO sqlalchemy.engine.base.Engine ('2012-04-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,568 INFO sqlalchemy.engine.base.Engine ('2012-04-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,570 INFO sqlalchemy.engine.base.Engine ('2012-04-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,572 INFO sqlalchemy.engine.base.Engine ('2012-04-21 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:31,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,573 INFO sqlalchemy.engine.base.Engine ('2012-04-22 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:31,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,575 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:31,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,577 INFO sqlalchemy.engine.base.Engine ('2012-04-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:31,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,579 INFO sqlalchemy.engine.base.Engine ('2012-04-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,581 INFO sqlalchemy.engine.base.Engine ('2012-04-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,582 INFO sqlalchemy.engine.base.Engine ('2012-04-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,584 INFO sqlalchemy.engine.base.Engine ('2012-04-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,586 INFO sqlalchemy.engine.base.Engine ('2012-04-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,588 INFO sqlalchemy.engine.base.Engine ('2012-04-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,589 INFO sqlalchemy.engine.base.Engine ('2012-05-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,591 INFO sqlalchemy.engine.base.Engine ('2012-05-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,592 INFO sqlalchemy.engine.base.Engine ('2012-05-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,594 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,596 INFO sqlalchemy.engine.base.Engine ('2012-05-05 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:31,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,597 INFO sqlalchemy.engine.base.Engine ('2012-05-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,599 INFO sqlalchemy.engine.base.Engine ('2012-05-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,601 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,603 INFO sqlalchemy.engine.base.Engine ('2012-05-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,604 INFO sqlalchemy.engine.base.Engine ('2012-05-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,606 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,607 INFO sqlalchemy.engine.base.Engine ('2012-05-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,609 INFO sqlalchemy.engine.base.Engine ('2012-05-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:31,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,610 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:31,612 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:31,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,614 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,615 INFO sqlalchemy.engine.base.Engine ('2012-05-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,616 INFO sqlalchemy.engine.base.Engine ('2012-05-18 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,618 INFO sqlalchemy.engine.base.Engine ('2012-05-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,619 INFO sqlalchemy.engine.base.Engine ('2012-05-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,621 INFO sqlalchemy.engine.base.Engine ('2012-05-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,623 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,624 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,626 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:31,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,628 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,629 INFO sqlalchemy.engine.base.Engine ('2012-05-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,631 INFO sqlalchemy.engine.base.Engine ('2012-05-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,632 INFO sqlalchemy.engine.base.Engine ('2012-05-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,634 INFO sqlalchemy.engine.base.Engine ('2012-05-29 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,635 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:31,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,637 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:31,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,639 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:31,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,641 INFO sqlalchemy.engine.base.Engine ('2012-06-02 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:31,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,643 INFO sqlalchemy.engine.base.Engine ('2012-06-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:31,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:31,644 INFO sqlalchemy.engine.base.Engine ('2012-06-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:31,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,088 INFO sqlalchemy.engine.base.Engine ('2013-01-15 00:00:00.000000', 0.4, 63)
2018-05-08 18:31:32,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,090 INFO sqlalchemy.engine.base.Engine ('2013-01-16 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:32,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,092 INFO sqlalchemy.engine.base.Engine ('2013-01-17 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:32,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,094 INFO sqlalchemy.engine.base.Engine ('2013-01-18 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:32,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,096 INFO sqlalchemy.engine.base.Engine ('2013-01-19 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:32,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,098 INFO sqlalchemy.engine.base.Engine ('2013-01-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,100 INFO sqlalchemy.engine.base.Engine ('2013-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,101 INFO sqlalchemy.engine.base.Engine ('2013-01-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,103 INFO sqlalchemy.engine.base.Engine ('2013-01-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,105 INFO sqlalchemy.engine.base.Engine ('2013-01-24 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:32,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,107 INFO sqlalchemy.engine.base.Engine ('2013-01-25 00:00:00.000000', 0.43, 64)
2018-05-08 18:31:32,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,109 INFO sqlalchemy.engine.base.Engine ('2013-01-26 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:32,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,110 INFO sqlalchemy.engine.base.Engine ('2013-01-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,112 INFO sqlalchemy.engine.base.Engine ('2013-01-28 00:00:00.000000', 1.13, 66)

2018-05-08 18:31:32,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,116 INFO sqlalchemy.engine.base.Engine ('2013-01-29 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:32,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,119 INFO sqlalchemy.engine.base.Engine ('2013-01-30 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:32,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,121 INFO sqlalchemy.engine.base.Engine ('2013-01-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,123 INFO sqlalchemy.engine.base.Engine ('2013-02-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,125 INFO sqlalchemy.engine.base.Engine ('2013-02-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,127 INFO sqlalchemy.engine.base.Engine ('2013-02-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,129 INFO sqlalchemy.engine.base.Engine ('2013-02-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,131 INFO sqlalchemy.engine.base.Engine ('2013-02-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,134 INFO sqlalchemy.engine.base.Engine ('2013-02-06 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:32,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,136 INFO sqlalchemy.engine.base.Engine ('2013-02-07 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:32,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,138 INFO sqlalchemy.engine.base.Engine ('2013-02-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,140 INFO sqlalchemy.engine.base.Engine ('2013-02-09 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:32,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,142 INFO sqlalchemy.engine.base.Engine ('2013-02-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,144 INFO sqlalchemy.engine.base.Engine ('2013-02-11 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,146 INFO sqlalchemy.engine.base.Engine ('2013-02-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,151 INFO sqlalchemy.engine.base.Engine ('2013-02-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,158 INFO sqlalchemy.engine.base.Engine ('2013-02-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,160 INFO sqlalchemy.engine.base.Engine ('2013-02-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,163 INFO sqlalchemy.engine.base.Engine ('2013-02-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,164 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,165 INFO sqlalchemy.engine.base.Engine ('2013-02-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,214 INFO sqlalchemy.engine.base.Engine ('2013-02-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,216 INFO sqlalchemy.engine.base.Engine ('2013-02-19 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:32,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,219 INFO sqlalchemy.engine.base.Engine ('2013-02-20 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:32,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,221 INFO sqlalchemy.engine.base.Engine ('2013-02-21 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:32,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,223 INFO sqlalchemy.engine.base.Engine ('2013-02-22 00:00:00.000000', 0.31, 72)
2018-05-08 18:31:32,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,225 INFO sqlalchemy.engine.base.Engine ('2013-02-23 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:32,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,226 INFO sqlalchemy.engine.base.Engine ('2013-02-24 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:32,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,229 INFO sqlalchemy.engine.base.Engine ('2013-02-25 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,231 INFO sqlalchemy.engine.base.Engine ('2013-02-26 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:32,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,233 INFO sqlalchemy.engine.base.Engine ('2013-02-27 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:32,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,235 INFO sqlalchemy.engine.base.Engine ('2013-02-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,237 INFO sqlalchemy.engine.base.Engine ('2013-03-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,239 INFO sqlalchemy.engine.base.Engine ('2013-03-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,241 INFO sqlalchemy.engine.base.Engine ('2013-03-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,243 INFO sqlalchemy.engine.base.Engine ('2013-03-04 00:00:00.000000', 0.0, 70)

2018-05-08 18:31:32,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,245 INFO sqlalchemy.engine.base.Engine ('2013-03-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,247 INFO sqlalchemy.engine.base.Engine ('2013-03-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,249 INFO sqlalchemy.engine.base.Engine ('2013-03-07 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:32,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,251 INFO sqlalchemy.engine.base.Engine ('2013-03-08 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:32,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,253 INFO sqlalchemy.engine.base.Engine ('2013-03-09 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:32,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,255 INFO sqlalchemy.engine.base.Engine ('2013-03-10 00:00:00.000000', 1.29, 68)
2018-05-08 18:31:32,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,257 INFO sqlalchemy.engine.base.Engine ('2013-03-11 00:00:00.000000', 0.8, 63)
2018-05-08 18:31:32,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,259 INFO sqlalchemy.engine.base.Engine ('2013-03-12 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:32,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,260 INFO sqlalchemy.engine.base.Engine ('2013-03-13 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:32,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,262 INFO sqlalchemy.engine.base.Engine ('2013-03-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:32,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,264 INFO sqlalchemy.engine.base.Engine ('2013-03-15 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:32,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,266 INFO sqlalchemy.engine.base.Engine ('2013-03-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,268 INFO sqlalchemy.engine.base.Engine ('2013-03-17 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:32,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,269 INFO sqlalchemy.engine.base.Engine ('2013-03-18 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:32,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,271 INFO sqlalchemy.engine.base.Engine ('2013-03-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:32,272 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,273 INFO sqlalchemy.engine.base.Engine ('2013-03-20 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,274 INFO sqlalchemy.engine.base.Engine ('2013-03-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,276 INFO sqlalchemy.engine.base.Engine ('2013-03-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,278 INFO sqlalchemy.engine.base.Engine ('2013-03-23 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:32,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,280 INFO sqlalchemy.engine.base.Engine ('2013-03-24 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,282 INFO sqlalchemy.engine.base.Engine ('2013-03-25 00:00:00.000000', 0.32, 68)
2018-05-08 18:31:32,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,283 INFO sqlalchemy.engine.base.Engine ('2013-03-26 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,285 INFO sqlalchemy.engine.base.Engine ('2013-03-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,287 INFO sqlalchemy.engine.base.Engine ('2013-03-28 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:32,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,289 INFO sqlalchemy.engine.base.Engine ('2013-03-29 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:32,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,290 INFO sqlalchemy.engine.base.Engine ('2013-03-30 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:32,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,292 INFO sqlalchemy.engine.base.Engine ('2013-03-31 00:00:00.000000', 0.25, 64)
2018-05-08 18:31:32,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,295 INFO sqlalchemy.engine.base.Engine ('2013-04-01 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:32,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,296 INFO sqlalchemy.engine.base.Engine ('2013-04-02 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:32,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,298 INFO sqlalchemy.engine.base.Engine ('2013-04-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,300 INFO sqlalchemy.engine.base.Engine ('2013-04-04 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:32,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,302 INFO sqlalchemy.engine.base.Engine ('2013-04-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,306 INFO sqlalchemy.engine.base.Engine ('2013-04-06 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:32,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,308 INFO sqlalchemy.engine.base.Engine ('2013-04-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,310 INFO sqlalchemy.engine.base.Engine ('2013-04-08 00:00:00.000000', 0.0, 74)

2018-05-08 18:31:32,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,313 INFO sqlalchemy.engine.base.Engine ('2013-04-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,314 INFO sqlalchemy.engine.base.Engine ('2013-04-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,316 INFO sqlalchemy.engine.base.Engine ('2013-04-11 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:32,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,318 INFO sqlalchemy.engine.base.Engine ('2013-04-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,320 INFO sqlalchemy.engine.base.Engine ('2013-04-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,322 INFO sqlalchemy.engine.base.Engine ('2013-04-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,324 INFO sqlalchemy.engine.base.Engine ('2013-04-15 00:00:00.000000', 0.8, 72)
2018-05-08 18:31:32,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,326 INFO sqlalchemy.engine.base.Engine ('2013-04-16 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:32,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,328 INFO sqlalchemy.engine.base.Engine ('2013-04-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,330 INFO sqlalchemy.engine.base.Engine ('2013-04-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,332 INFO sqlalchemy.engine.base.Engine ('2013-04-19 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:32,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,334 INFO sqlalchemy.engine.base.Engine ('2013-04-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,336 INFO sqlalchemy.engine.base.Engine ('2013-04-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,338 INFO sqlalchemy.engine.base.Engine ('2013-04-22 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:32,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,340 INFO sqlalchemy.engine.base.Engine ('2013-04-23 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:32,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,342 INFO sqlalchemy.engine.base.Engine ('2013-04-24 00:00:00.000000', 0.55, 70)
2018-05-08 18:31:32,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,344 INFO sqlalchemy.engine.base.Engine ('2013-04-25 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:32,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,346 INFO sqlalchemy.engine.base.Engine ('2013-04-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,349 INFO sqlalchemy.engine.base.Engine ('2013-04-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,351 INFO sqlalchemy.engine.base.Engine ('2013-04-28 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,353 INFO sqlalchemy.engine.base.Engine ('2013-04-29 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,355 INFO sqlalchemy.engine.base.Engine ('2013-04-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,356 INFO sqlalchemy.engine.base.Engine ('2013-05-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,358 INFO sqlalchemy.engine.base.Engine ('2013-05-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,360 INFO sqlalchemy.engine.base.Engine ('2013-05-03 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:32,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,362 INFO sqlalchemy.engine.base.Engine ('2013-05-04 00:00:00.000000', 0.14, 69)
2018-05-08 18:31:32,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,364 INFO sqlalchemy.engine.base.Engine ('2013-05-05 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:32,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,366 INFO sqlalchemy.engine.base.Engine ('2013-05-06 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:32,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,368 INFO sqlalchemy.engine.base.Engine ('2013-05-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,370 INFO sqlalchemy.engine.base.Engine ('2013-05-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,371 INFO sqlalchemy.engine.base.Engine ('2013-05-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,373 INFO sqlalchemy.engine.base.Engine ('2013-05-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,375 INFO sqlalchemy.engine.base.Engine ('2013-05-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,377 INFO sqlalchemy.engine.base.Engine ('2013-05-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,379 INFO sqlalchemy.engine.base.Engine ('2013-05-13 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:32,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,381 INFO sqlalchemy.engine.base.Engine ('2013-05-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,383 INFO sqlalchemy.engine.base.Engine ('2013-05-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,385 INFO sqlalchemy.engine.base.Engine ('2013-05-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,387 INFO sqlalchemy.engine.base.Engine ('2013-05-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,389 INFO sqlalchemy.engine.base.Engine ('2013-05-18 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:32,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,391 INFO sqlalchemy.engine.base.Engine ('2013-05-19 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:32,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,392 INFO sqlalchemy.engine.base.Engine ('2013-05-20 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:32,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,396 INFO sqlalchemy.engine.base.Engine ('2013-05-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,398 INFO sqlalchemy.engine.base.Engine ('2013-05-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,400 INFO sqlalchemy.engine.base.Engine ('2013-05-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,402 INFO sqlalchemy.engine.base.Engine ('2013-05-24 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,404 INFO sqlalchemy.engine.base.Engine ('2013-05-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,406 INFO sqlalchemy.engine.base.Engine ('2013-05-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,407 INFO sqlalchemy.engine.base.Engine ('2013-05-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,409 INFO sqlalchemy.engine.base.Engine ('2013-05-28 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:32,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,456 INFO sqlalchemy.engine.base.Engine ('2013-05-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,458 INFO sqlalchemy.engine.base.Engine ('2013-05-30 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:32,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,460 INFO sqlalchemy.engine.base.Engine ('2013-05-31 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,461 INFO sqlalchemy.engine.base.Engine ('2013-06-01 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:32,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,463 INFO sqlalchemy.engine.base.Engine ('2013-06-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,465 INFO sqlalchemy.engine.base.Engine ('2013-06-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,467 INFO sqlalchemy.engine.base.Engine ('2013-06-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,469 INFO sqlalchemy.engine.base.Engine ('2013-06-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,470 INFO sqlalchemy.engine.base.Engine ('2013-06-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,472 INFO sqlalchemy.engine.base.Engine ('2013-06-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,473 INFO sqlalchemy.engine.base.Engine ('2013-06-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,475 INFO sqlalchemy.engine.base.Engine ('2013-06-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,477 INFO sqlalchemy.engine.base.Engine ('2013-06-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,479 INFO sqlalchemy.engine.base.Engine ('2013-06-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,480 INFO sqlalchemy.engine.base.Engine ('2013-06-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,482 INFO sqlalchemy.engine.base.Engine ('2013-06-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,483 INFO sqlalchemy.engine.base.Engine ('2013-06-14 00:00:00.000000', 0.37, 76)
2018-05-08 18:31:32,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,485 INFO sqlalchemy.engine.base.Engine ('2013-06-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,486 INFO sqlalchemy.engine.base.Engine ('2013-06-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,488 INFO sqlalchemy.engine.base.Engine ('2013-06-17 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:32,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,489 INFO sqlalchemy.engine.base.Engine ('2013-06-18 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:32,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,490 INFO sqlalchemy.engine.base.Engine ('2013-06-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,493 INFO sqlalchemy.engine.base.Engine ('2013-06-20 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:32,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,495 INFO sqlalchemy.engine.base.Engine ('2013-06-21 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:32,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,497 INFO sqlalchemy.engine.base.Engine ('2013-06-22 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:32,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,499 INFO sqlalchemy.engine.base.Engine ('2013-06-23 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:32,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,501 INFO sqlalchemy.engine.base.Engine ('2013-06-24 00:00:00.000000', 0.35, 76)
2018-05-08 18:31:32,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,502 INFO sqlalchemy.engine.base.Engine ('2013-06-25 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:32,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,504 INFO sqlalchemy.engine.base.Engine ('2013-06-26 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:32,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,505 INFO sqlalchemy.engine.base.Engine ('2013-06-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,507 INFO sqlalchemy.engine.base.Engine ('2013-06-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,508 INFO sqlalchemy.engine.base.Engine ('2013-06-29 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:32,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,510 INFO sqlalchemy.engine.base.Engine ('2013-06-30 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:32,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,512 INFO sqlalchemy.engine.base.Engine ('2013-07-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,515 INFO sqlalchemy.engine.base.Engine ('2013-07-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,516 INFO sqlalchemy.engine.base.Engine ('2013-07-03 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:32,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,518 INFO sqlalchemy.engine.base.Engine ('2013-07-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,519 INFO sqlalchemy.engine.base.Engine ('2013-07-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,520 INFO sqlalchemy.engine.base.Engine ('2013-07-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,522 INFO sqlalchemy.engine.base.Engine ('2013-07-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,523 INFO sqlalchemy.engine.base.Engine ('2013-07-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,525 INFO sqlalchemy.engine.base.Engine ('2013-07-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,526 INFO sqlalchemy.engine.base.Engine ('2013-07-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,528 INFO sqlalchemy.engine.base.Engine ('2013-07-11 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:32,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,530 INFO sqlalchemy.engine.base.Engine ('2013-07-12 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:32,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,532 INFO sqlalchemy.engine.base.Engine ('2013-07-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,533 INFO sqlalchemy.engine.base.Engine ('2013-07-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,536 INFO sqlalchemy.engine.base.Engine ('2013-07-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,537 INFO sqlalchemy.engine.base.Engine ('2013-07-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,539 INFO sqlalchemy.engine.base.Engine ('2013-07-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,541 INFO sqlalchemy.engine.base.Engine ('2013-07-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,542 INFO sqlalchemy.engine.base.Engine ('2013-07-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,544 INFO sqlalchemy.engine.base.Engine ('2013-07-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,546 INFO sqlalchemy.engine.base.Engine ('2013-07-21 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:32,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,547 INFO sqlalchemy.engine.base.Engine ('2013-07-22 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:32,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,550 INFO sqlalchemy.engine.base.Engine ('2013-07-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,551 INFO sqlalchemy.engine.base.Engine ('2013-07-25 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,553 INFO sqlalchemy.engine.base.Engine ('2013-07-26 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,554 INFO sqlalchemy.engine.base.Engine ('2013-07-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,556 INFO sqlalchemy.engine.base.Engine ('2013-07-28 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:32,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,558 INFO sqlalchemy.engine.base.Engine ('2013-07-29 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:32,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,560 INFO sqlalchemy.engine.base.Engine ('2013-07-30 00:00:00.000000', 0.74, 79)
2018-05-08 18:31:32,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,561 INFO sqlalchemy.engine.base.Engine ('2013-07-31 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:32,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,564 INFO sqlalchemy.engine.base.Engine ('2013-08-01 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:32,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,566 INFO sqlalchemy.engine.base.Engine ('2013-08-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,568 INFO sqlalchemy.engine.base.Engine ('2013-08-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,569 INFO sqlalchemy.engine.base.Engine ('2013-08-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,571 INFO sqlalchemy.engine.base.Engine ('2013-08-05 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,572 INFO sqlalchemy.engine.base.Engine ('2013-08-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,574 INFO sqlalchemy.engine.base.Engine ('2013-08-07 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,575 INFO sqlalchemy.engine.base.Engine ('2013-08-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,577 INFO sqlalchemy.engine.base.Engine ('2013-08-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,578 INFO sqlalchemy.engine.base.Engine ('2013-08-10 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:32,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,580 INFO sqlalchemy.engine.base.Engine ('2013-08-11 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:32,581 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,582 INFO sqlalchemy.engine.base.Engine ('2013-08-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,584 INFO sqlalchemy.engine.base.Engine ('2013-08-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,585 INFO sqlalchemy.engine.base.Engine ('2013-08-14 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:32,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,587 INFO sqlalchemy.engine.base.Engine ('2013-08-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,588 INFO sqlalchemy.engine.base.Engine ('2013-08-16 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:32,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,590 INFO sqlalchemy.engine.base.Engine ('2013-08-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,592 INFO sqlalchemy.engine.base.Engine ('2013-08-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,593 INFO sqlalchemy.engine.base.Engine ('2013-08-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,595 INFO sqlalchemy.engine.base.Engine ('2013-08-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,596 INFO sqlalchemy.engine.base.Engine ('2013-08-21 00:00:00.000000', 0.25, 77)
2018-05-08 18:31:32,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,598 INFO sqlalchemy.engine.base.Engine ('2013-08-22 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,600 INFO sqlalchemy.engine.base.Engine ('2013-08-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,601 INFO sqlalchemy.engine.base.Engine ('2013-08-24 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,603 INFO sqlalchemy.engine.base.Engine ('2013-08-25 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,605 INFO sqlalchemy.engine.base.Engine ('2013-08-26 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,606 INFO sqlalchemy.engine.base.Engine ('2013-08-27 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:32,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,608 INFO sqlalchemy.engine.base.Engine ('2013-08-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,609 INFO sqlalchemy.engine.base.Engine ('2013-08-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,611 INFO sqlalchemy.engine.base.Engine ('2013-08-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,613 INFO sqlalchemy.engine.base.Engine ('2013-08-31 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,615 INFO sqlalchemy.engine.base.Engine ('2013-09-01 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:32,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,617 INFO sqlalchemy.engine.base.Engine ('2013-09-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,618 INFO sqlalchemy.engine.base.Engine ('2013-09-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,620 INFO sqlalchemy.engine.base.Engine ('2013-09-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,621 INFO sqlalchemy.engine.base.Engine ('2013-09-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,623 INFO sqlalchemy.engine.base.Engine ('2013-09-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,671 INFO sqlalchemy.engine.base.Engine ('2013-09-07 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:32,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,673 INFO sqlalchemy.engine.base.Engine ('2013-09-08 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:32,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,674 INFO sqlalchemy.engine.base.Engine ('2013-09-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,676 INFO sqlalchemy.engine.base.Engine ('2013-09-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,678 INFO sqlalchemy.engine.base.Engine ('2013-09-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,680 INFO sqlalchemy.engine.base.Engine ('2013-09-12 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:32,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,682 INFO sqlalchemy.engine.base.Engine ('2013-09-13 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:32,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,684 INFO sqlalchemy.engine.base.Engine ('2013-09-14 00:00:00.000000', 0.14, 83)
2018-05-08 18:31:32,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,685 INFO sqlalchemy.engine.base.Engine ('2013-09-15 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:32,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,687 INFO sqlalchemy.engine.base.Engine ('2013-09-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,689 INFO sqlalchemy.engine.base.Engine ('2013-09-17 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:32,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,690 INFO sqlalchemy.engine.base.Engine ('2013-09-18 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:32,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,692 INFO sqlalchemy.engine.base.Engine ('2013-09-19 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:32,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,694 INFO sqlalchemy.engine.base.Engine ('2013-09-20 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,695 INFO sqlalchemy.engine.base.Engine ('2013-09-21 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:32,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,697 INFO sqlalchemy.engine.base.Engine ('2013-09-22 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:32,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,699 INFO sqlalchemy.engine.base.Engine ('2013-09-23 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:32,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,700 INFO sqlalchemy.engine.base.Engine ('2013-09-24 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:32,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,702 INFO sqlalchemy.engine.base.Engine ('2013-09-25 00:00:00.000000', 0.25, 79)
2018-05-08 18:31:32,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,703 INFO sqlalchemy.engine.base.Engine ('2013-09-26 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:32,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,705 INFO sqlalchemy.engine.base.Engine ('2013-09-27 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,706 INFO sqlalchemy.engine.base.Engine ('2013-09-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,708 INFO sqlalchemy.engine.base.Engine ('2013-09-29 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:32,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,709 INFO sqlalchemy.engine.base.Engine ('2013-09-30 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:32,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,711 INFO sqlalchemy.engine.base.Engine ('2013-10-01 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:32,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,713 INFO sqlalchemy.engine.base.Engine ('2013-10-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,714 INFO sqlalchemy.engine.base.Engine ('2013-10-03 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:32,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,716 INFO sqlalchemy.engine.base.Engine ('2013-10-04 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,718 INFO sqlalchemy.engine.base.Engine ('2013-10-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,719 INFO sqlalchemy.engine.base.Engine ('2013-10-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,721 INFO sqlalchemy.engine.base.Engine ('2013-10-07 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,722 INFO sqlalchemy.engine.base.Engine ('2013-10-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,724 INFO sqlalchemy.engine.base.Engine ('2013-10-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,725 INFO sqlalchemy.engine.base.Engine ('2013-10-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,727 INFO sqlalchemy.engine.base.Engine ('2013-10-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,729 INFO sqlalchemy.engine.base.Engine ('2013-10-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,731 INFO sqlalchemy.engine.base.Engine ('2013-10-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,733 INFO sqlalchemy.engine.base.Engine ('2013-10-14 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:32,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,734 INFO sqlalchemy.engine.base.Engine ('2013-10-15 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:32,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,736 INFO sqlalchemy.engine.base.Engine ('2013-10-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,737 INFO sqlalchemy.engine.base.Engine ('2013-10-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,739 INFO sqlalchemy.engine.base.Engine ('2013-10-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,741 INFO sqlalchemy.engine.base.Engine ('2013-10-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,742 INFO sqlalchemy.engine.base.Engine ('2013-10-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,744 INFO sqlalchemy.engine.base.Engine ('2013-10-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,746 INFO sqlalchemy.engine.base.Engine ('2013-10-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,747 INFO sqlalchemy.engine.base.Engine ('2013-10-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,749 INFO sqlalchemy.engine.base.Engine ('2013-10-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,751 INFO sqlalchemy.engine.base.Engine ('2013-10-25 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:32,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,752 INFO sqlalchemy.engine.base.Engine ('2013-10-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,754 INFO sqlalchemy.engine.base.Engine ('2013-10-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,755 INFO sqlalchemy.engine.base.Engine ('2013-10-28 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:32,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,757 INFO sqlalchemy.engine.base.Engine ('2013-10-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,759 INFO sqlalchemy.engine.base.Engine ('2013-10-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,761 INFO sqlalchemy.engine.base.Engine ('2013-10-31 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:32,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,762 INFO sqlalchemy.engine.base.Engine ('2013-11-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:32,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,764 INFO sqlalchemy.engine.base.Engine ('2013-11-02 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:32,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,766 INFO sqlalchemy.engine.base.Engine ('2013-11-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,768 INFO sqlalchemy.engine.base.Engine ('2013-11-04 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:32,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,769 INFO sqlalchemy.engine.base.Engine ('2013-11-05 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:32,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,770 INFO sqlalchemy.engine.base.Engine ('2013-11-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,772 INFO sqlalchemy.engine.base.Engine ('2013-11-07 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:32,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,773 INFO sqlalchemy.engine.base.Engine ('2013-11-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,775 INFO sqlalchemy.engine.base.Engine ('2013-11-09 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:32,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,777 INFO sqlalchemy.engine.base.Engine ('2013-11-10 00:00:00.000000', 1.98, 72)
2018-05-08 18:31:32,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,779 INFO sqlalchemy.engine.base.Engine ('2013-11-11 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:32,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,781 INFO sqlalchemy.engine.base.Engine ('2013-11-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:32,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,782 INFO sqlalchemy.engine.base.Engine ('2013-11-13 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,784 INFO sqlalchemy.engine.base.Engine ('2013-11-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,786 INFO sqlalchemy.engine.base.Engine ('2013-11-15 00:00:00.000000', 0.89, 75)
2018-05-08 18:31:32,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,788 INFO sqlalchemy.engine.base.Engine ('2013-11-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,789 INFO sqlalchemy.engine.base.Engine ('2013-11-17 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,791 INFO sqlalchemy.engine.base.Engine ('2013-11-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,792 INFO sqlalchemy.engine.base.Engine ('2013-11-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,795 INFO sqlalchemy.engine.base.Engine ('2013-11-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,796 INFO sqlalchemy.engine.base.Engine ('2013-11-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,798 INFO sqlalchemy.engine.base.Engine ('2013-11-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,799 INFO sqlalchemy.engine.base.Engine ('2013-11-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,802 INFO sqlalchemy.engine.base.Engine ('2013-11-24 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:32,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,803 INFO sqlalchemy.engine.base.Engine ('2013-11-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,805 INFO sqlalchemy.engine.base.Engine ('2013-11-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:32,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,806 INFO sqlalchemy.engine.base.Engine ('2013-11-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,808 INFO sqlalchemy.engine.base.Engine ('2013-11-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,810 INFO sqlalchemy.engine.base.Engine ('2013-11-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,811 INFO sqlalchemy.engine.base.Engine ('2013-11-30 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:32,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,813 INFO sqlalchemy.engine.base.Engine ('2013-12-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:32,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,814 INFO sqlalchemy.engine.base.Engine ('2013-12-02 00:00:00.000000', 2.01, 71)
2018-05-08 18:31:32,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,816 INFO sqlalchemy.engine.base.Engine ('2013-12-03 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:32,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,818 INFO sqlalchemy.engine.base.Engine ('2013-12-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,820 INFO sqlalchemy.engine.base.Engine ('2013-12-05 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:32,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,821 INFO sqlalchemy.engine.base.Engine ('2013-12-06 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:32,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,823 INFO sqlalchemy.engine.base.Engine ('2013-12-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,824 INFO sqlalchemy.engine.base.Engine ('2013-12-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,826 INFO sqlalchemy.engine.base.Engine ('2013-12-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,828 INFO sqlalchemy.engine.base.Engine ('2013-12-10 00:00:00.000000', 0.03, 76)

2018-05-08 18:31:32,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,830 INFO sqlalchemy.engine.base.Engine ('2013-12-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,832 INFO sqlalchemy.engine.base.Engine ('2013-12-12 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,834 INFO sqlalchemy.engine.base.Engine ('2013-12-13 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:32,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,836 INFO sqlalchemy.engine.base.Engine ('2013-12-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,838 INFO sqlalchemy.engine.base.Engine ('2013-12-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,888 INFO sqlalchemy.engine.base.Engine ('2013-12-16 00:00:00.000000', 1.1, 68)
2018-05-08 18:31:32,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,890 INFO sqlalchemy.engine.base.Engine ('2013-12-17 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:32,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,892 INFO sqlalchemy.engine.base.Engine ('2013-12-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,894 INFO sqlalchemy.engine.base.Engine ('2013-12-19 00:00:00.000000', 0.16, 69)
2018-05-08 18:31:32,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,895 INFO sqlalchemy.engine.base.Engine ('2013-12-20 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:32,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,897 INFO sqlalchemy.engine.base.Engine ('2013-12-21 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:32,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,899 INFO sqlalchemy.engine.base.Engine ('2013-12-22 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,901 INFO sqlalchemy.engine.base.Engine ('2013-12-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:32,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,903 INFO sqlalchemy.engine.base.Engine ('2013-12-24 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:32,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,904 INFO sqlalchemy.engine.base.Engine ('2013-12-25 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:32,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,906 INFO sqlalchemy.engine.base.Engine ('2013-12-26 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,908 INFO sqlalchemy.engine.base.Engine ('2013-12-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,909 INFO sqlalchemy.engine.base.Engine ('2013-12-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,911 INFO sqlalchemy.engine.base.Engine ('2013-12-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,913 INFO sqlalchemy.engine.base.Engine ('2013-12-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,915 INFO sqlalchemy.engine.base.Engine ('2013-12-31 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,916 INFO sqlalchemy.engine.base.Engine ('2014-01-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:32,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,918 INFO sqlalchemy.engine.base.Engine ('2014-01-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:32,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,920 INFO sqlalchemy.engine.base.Engine ('2014-01-03 00:00:00.000000', 0.76, 65)
2018-05-08 18:31:32,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,922 INFO sqlalchemy.engine.base.Engine ('2014-01-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,923 INFO sqlalchemy.engine.base.Engine ('2014-01-05 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:32,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,925 INFO sqlalchemy.engine.base.Engine ('2014-01-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,926 INFO sqlalchemy.engine.base.Engine ('2014-01-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,928 INFO sqlalchemy.engine.base.Engine ('2014-01-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,930 INFO sqlalchemy.engine.base.Engine ('2014-01-09 00:00:00.000000', 0.03, 65)
2018-05-08 18:31:32,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,932 INFO sqlalchemy.engine.base.Engine ('2014-01-12 00:00:00.000000', 0.35, 69)
2018-05-08 18:31:32,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,934 INFO sqlalchemy.engine.base.Engine ('2014-01-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,936 INFO sqlalchemy.engine.base.Engine ('2014-01-14 00:00:00.000000', 0.43, 70)
2018-05-08 18:31:32,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,938 INFO sqlalchemy.engine.base.Engine ('2014-01-15 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:32,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,939 INFO sqlalchemy.engine.base.Engine ('2014-01-16 00:00:00.000000', 0.25, 69)

2018-05-08 18:31:32,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,941 INFO sqlalchemy.engine.base.Engine ('2014-01-17 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,942 INFO sqlalchemy.engine.base.Engine ('2014-01-18 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:32,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,944 INFO sqlalchemy.engine.base.Engine ('2014-01-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:32,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,946 INFO sqlalchemy.engine.base.Engine ('2014-01-20 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:32,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,947 INFO sqlalchemy.engine.base.Engine ('2014-01-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,949 INFO sqlalchemy.engine.base.Engine ('2014-01-22 00:00:00.000000', 0.35, 69)
2018-05-08 18:31:32,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,951 INFO sqlalchemy.engine.base.Engine ('2014-01-23 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:32,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,953 INFO sqlalchemy.engine.base.Engine ('2014-01-24 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:32,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,955 INFO sqlalchemy.engine.base.Engine ('2014-01-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,956 INFO sqlalchemy.engine.base.Engine ('2014-01-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,958 INFO sqlalchemy.engine.base.Engine ('2014-01-27 00:00:00.000000', 0.14, 68)
2018-05-08 18:31:32,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,960 INFO sqlalchemy.engine.base.Engine ('2014-01-28 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:32,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,962 INFO sqlalchemy.engine.base.Engine ('2014-01-29 00:00:00.000000', 0.27, 70)
2018-05-08 18:31:32,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,964 INFO sqlalchemy.engine.base.Engine ('2014-01-30 00:00:00.000000', 0.04, 65)
2018-05-08 18:31:32,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,966 INFO sqlalchemy.engine.base.Engine ('2014-01-31 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:32,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,967 INFO sqlalchemy.engine.base.Engine ('2014-02-01 00:00:00.000000', 0.22, 74)
2018-05-08 18:31:32,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,969 INFO sqlalchemy.engine.base.Engine ('2014-02-02 00:00:00.000000', 0.38, 67)
2018-05-08 18:31:32,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,971 INFO sqlalchemy.engine.base.Engine ('2014-02-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,973 INFO sqlalchemy.engine.base.Engine ('2014-02-04 00:00:00.000000', 0.5, 68)
2018-05-08 18:31:32,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,974 INFO sqlalchemy.engine.base.Engine ('2014-02-05 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:32,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,976 INFO sqlalchemy.engine.base.Engine ('2014-02-06 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:32,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,977 INFO sqlalchemy.engine.base.Engine ('2014-02-07 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:32,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,979 INFO sqlalchemy.engine.base.Engine ('2014-02-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:32,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,981 INFO sqlalchemy.engine.base.Engine ('2014-02-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,983 INFO sqlalchemy.engine.base.Engine ('2014-02-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,984 INFO sqlalchemy.engine.base.Engine ('2014-02-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:32,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,987 INFO sqlalchemy.engine.base.Engine ('2014-02-12 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:32,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,989 INFO sqlalchemy.engine.base.Engine ('2014-02-13 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:32,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,991 INFO sqlalchemy.engine.base.Engine ('2014-02-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:32,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,992 INFO sqlalchemy.engine.base.Engine ('2014-02-15 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:32,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,994 INFO sqlalchemy.engine.base.Engine ('2014-02-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:32,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,996 INFO sqlalchemy.engine.base.Engine ('2014-02-17 00:00:00.000000', 0.35, 72)
2018-05-08 18:31:32,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,998 INFO sqlalchemy.engine.base.Engine ('2014-02-18 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:32,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:32,999 INFO sqlalchemy.engine.base.Engine ('2014-02-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:33,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,001 INFO sqlalchemy.engine.base.Engine ('2014-02-20 00:00:00.000000', 0.0, 70)

2018-05-08 18:31:33,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,003 INFO sqlalchemy.engine.base.Engine ('2014-02-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,006 INFO sqlalchemy.engine.base.Engine ('2014-02-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,007 INFO sqlalchemy.engine.base.Engine ('2014-02-23 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:33,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,009 INFO sqlalchemy.engine.base.Engine ('2014-02-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:33,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,011 INFO sqlalchemy.engine.base.Engine ('2014-02-25 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:33,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,013 INFO sqlalchemy.engine.base.Engine ('2014-02-26 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:33,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,014 INFO sqlalchemy.engine.base.Engine ('2014-02-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:33,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,017 INFO sqlalchemy.engine.base.Engine ('2014-02-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:33,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,019 INFO sqlalchemy.engine.base.Engine ('2014-03-01 00:00:00.000000', 0.25, 70)
2018-05-08 18:31:33,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,021 INFO sqlalchemy.engine.base.Engine ('2014-03-02 00:00:00.000000', 0.48, 71)
2018-05-08 18:31:33,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,023 INFO sqlalchemy.engine.base.Engine ('2014-03-03 00:00:00.000000', 0.16, 65)
2018-05-08 18:31:33,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,024 INFO sqlalchemy.engine.base.Engine ('2014-03-04 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:33,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,026 INFO sqlalchemy.engine.base.Engine ('2014-03-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,028 INFO sqlalchemy.engine.base.Engine ('2014-03-06 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:33,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,030 INFO sqlalchemy.engine.base.Engine ('2014-03-07 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:33,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,032 INFO sqlalchemy.engine.base.Engine ('2014-03-08 00:00:00.000000', 0.64, 68)
2018-05-08 18:31:33,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,034 INFO sqlalchemy.engine.base.Engine ('2014-03-09 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:33,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,037 INFO sqlalchemy.engine.base.Engine ('2014-03-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:33,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,039 INFO sqlalchemy.engine.base.Engine ('2014-03-11 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:33,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,041 INFO sqlalchemy.engine.base.Engine ('2014-03-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:33,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,043 INFO sqlalchemy.engine.base.Engine ('2014-03-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,045 INFO sqlalchemy.engine.base.Engine ('2014-03-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,047 INFO sqlalchemy.engine.base.Engine ('2014-03-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:33,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,048 INFO sqlalchemy.engine.base.Engine ('2014-03-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,051 INFO sqlalchemy.engine.base.Engine ('2014-03-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,052 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,053 INFO sqlalchemy.engine.base.Engine ('2014-03-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,055 INFO sqlalchemy.engine.base.Engine ('2014-03-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:33,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,056 INFO sqlalchemy.engine.base.Engine ('2014-03-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:33,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,058 INFO sqlalchemy.engine.base.Engine ('2014-03-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:33,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,060 INFO sqlalchemy.engine.base.Engine ('2014-03-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:33,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,062 INFO sqlalchemy.engine.base.Engine ('2014-03-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:33,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,064 INFO sqlalchemy.engine.base.Engine ('2014-03-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,066 INFO sqlalchemy.engine.base.Engine ('2014-03-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:33,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,067 INFO sqlalchemy.engine.base.Engine ('2014-03-26 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:33,068 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:33,069 INFO sqlalchemy.engine.base.Engine ('2014-03-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,115 INFO sqlalchemy.engine.base.Engine ('2014-03-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:33,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,117 INFO sqlalchemy.engine.base.Engine ('2014-03-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:33,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,119 INFO sqlalchemy.engine.base.Engine ('2014-03-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:33,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,121 INFO sqlalchemy.engine.base.Engine ('2014-03-31 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:33,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,122 INFO sqlalchemy.engine.base.Engine ('2014-04-01 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:33,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,124 INFO sqlalchemy.engine.base.Engine ('2014-04-02 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:33,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,125 INFO sqlalchemy.engine.base.Engine ('2014-04-03 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:33,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,127 INFO sqlalchemy.engine.base.Engine ('2014-04-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,129 INFO sqlalchemy.engine.base.Engine ('2014-04-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:33,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,130 INFO sqlalchemy.engine.base.Engine ('2014-04-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:33,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,132 INFO sqlalchemy.engine.base.Engine ('2014-04-07 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:33,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,135 INFO sqlalchemy.engine.base.Engine ('2014-04-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:33,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,137 INFO sqlalchemy.engine.base.Engine ('2014-04-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:33,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,138 INFO sqlalchemy.engine.base.Engine ('2014-04-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:33,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,140 INFO sqlalchemy.engine.base.Engine ('2014-04-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,141 INFO sqlalchemy.engine.base.Engine ('2014-04-12 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:33,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,142 INFO sqlalchemy.engine.base.Engine ('2014-04-13 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:33,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,145 INFO sqlalchemy.engine.base.Engine ('2014-04-14 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:33,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,146 INFO sqlalchemy.engine.base.Engine ('2014-04-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,148 INFO sqlalchemy.engine.base.Engine ('2014-04-16 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:33,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,150 INFO sqlalchemy.engine.base.Engine ('2014-04-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,152 INFO sqlalchemy.engine.base.Engine ('2014-04-18 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:33,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,154 INFO sqlalchemy.engine.base.Engine ('2014-04-19 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:33,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,155 INFO sqlalchemy.engine.base.Engine ('2014-04-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:33,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,157 INFO sqlalchemy.engine.base.Engine ('2014-04-21 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:33,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,159 INFO sqlalchemy.engine.base.Engine ('2014-04-22 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:33,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,160 INFO sqlalchemy.engine.base.Engine ('2014-04-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,162 INFO sqlalchemy.engine.base.Engine ('2014-04-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,164 INFO sqlalchemy.engine.base.Engine ('2014-04-25 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:33,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,166 INFO sqlalchemy.engine.base.Engine ('2014-04-26 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:33,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,168 INFO sqlalchemy.engine.base.Engine ('2014-04-27 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:33,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,170 INFO sqlalchemy.engine.base.Engine ('2014-04-28 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:33,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,171 INFO sqlalchemy.engine.base.Engine ('2014-04-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,173 INFO sqlalchemy.engine.base.Engine ('2014-04-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:33,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:33,174 INFO sqlalchemy.engine.base.Engine ('2014-05-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:33,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,176 INFO sqlalchemy.engine.base.Engine ('2014-05-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,178 INFO sqlalchemy.engine.base.Engine ('2014-05-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:33,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,179 INFO sqlalchemy.engine.base.Engine ('2014-05-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,181 INFO sqlalchemy.engine.base.Engine ('2014-05-05 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:33,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,183 INFO sqlalchemy.engine.base.Engine ('2014-05-06 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:33,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,184 INFO sqlalchemy.engine.base.Engine ('2014-05-07 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:33,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,186 INFO sqlalchemy.engine.base.Engine ('2014-05-10 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:33,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,188 INFO sqlalchemy.engine.base.Engine ('2014-05-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:33,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,190 INFO sqlalchemy.engine.base.Engine ('2014-05-12 00:00:00.000000', 0.45, 74)
2018-05-08 18:31:33,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,192 INFO sqlalchemy.engine.base.Engine ('2014-05-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:33,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,194 INFO sqlalchemy.engine.base.Engine ('2014-05-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,196 INFO sqlalchemy.engine.base.Engine ('2014-05-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:33,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,198 INFO sqlalchemy.engine.base.Engine ('2014-05-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:33,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,200 INFO sqlalchemy.engine.base.Engine ('2014-05-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:33,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,201 INFO sqlalchemy.engine.base.Engine ('2014-05-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:33,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,203 INFO sqlalchemy.engine.base.Engine ('2014-05-19 00:00:00.000000', 0.43, 75)
2018-05-08 18:31:33,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,204 INFO sqlalchemy.engine.base.Engine ('2014-05-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:33,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,205 INFO sqlalchemy.engine.base.Engine ('2014-05-21 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:33,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,207 INFO sqlalchemy.engine.base.Engine ('2014-05-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:33,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,209 INFO sqlalchemy.engine.base.Engine ('2014-05-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:33,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,212 INFO sqlalchemy.engine.base.Engine ('2014-05-25 00:00:00.000000', 0.76, 74)
2018-05-08 18:31:33,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,213 INFO sqlalchemy.engine.base.Engine ('2014-05-26 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:33,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,215 INFO sqlalchemy.engine.base.Engine ('2014-05-27 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:33,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,217 INFO sqlalchemy.engine.base.Engine ('2014-05-28 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:33,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,220 INFO sqlalchemy.engine.base.Engine ('2014-05-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:33,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,221 INFO sqlalchemy.engine.base.Engine ('2014-05-30 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:33,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,223 INFO sqlalchemy.engine.base.Engine ('2014-05-31 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:33,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:33,224 INFO sqlalchemy.engine.base.Engine ('2014-06-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,333 INFO sqlalchemy.engine.base.Engine ('2015-11-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,335 INFO sqlalchemy.engine.base.Engine ('2015-11-14 00:00:00.000000', 0.17, 78)
2018-05-08 18:31:34,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,337 INFO sqlalchemy.engine.base.Engine ('2015-11-15 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:34,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,339 INFO sqlalchemy.engine.base.Engine ('2015-11-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,340 INFO sqlalchemy.engine.base.Engine ('2015-11-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,342 INFO sqlalchemy.engine.base.Engine ('2015-11-18 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:34,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,344 INFO sqlalchemy.engine.base.Engine ('2015-11-19 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,347 INFO sqlalchemy.engine.base.Engine ('2015-11-20 00:00:00.000000', 1.57, 73)
2018-05-08 18:31:34,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,349 INFO sqlalchemy.engine.base.Engine ('2015-11-21 00:00:00.000000', 0.85, 75)
2018-05-08 18:31:34,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,350 INFO sqlalchemy.engine.base.Engine ('2015-11-22 00:00:00.000000', 0.33, 75)
2018-05-08 18:31:34,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,352 INFO sqlalchemy.engine.base.Engine ('2015-11-23 00:00:00.000000', 0.62, 76)
2018-05-08 18:31:34,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,354 INFO sqlalchemy.engine.base.Engine ('2015-11-24 00:00:00.000000', 0.75, 71)
2018-05-08 18:31:34,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,355 INFO sqlalchemy.engine.base.Engine ('2015-11-25 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:34,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,357 INFO sqlalchemy.engine.base.Engine ('2015-11-26 00:00:00.000000', 0.36, 76)
2018-05-08 18:31:34,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,359 INFO sqlalchemy.engine.base.Engine ('2015-11-27 00:00:00.000000', 0.11, 77)
2018-05-08 18:31:34,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,361 INFO sqlalchemy.engine.base.Engine ('2015-11-28 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:34,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,407 INFO sqlalchemy.engine.base.Engine ('2015-11-29 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:34,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,409 INFO sqlalchemy.engine.base.Engine ('2015-11-30 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,411 INFO sqlalchemy.engine.base.Engine ('2015-12-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,413 INFO sqlalchemy.engine.base.Engine ('2015-12-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,415 INFO sqlalchemy.engine.base.Engine ('2015-12-03 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:34,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,417 INFO sqlalchemy.engine.base.Engine ('2015-12-04 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:34,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,419 INFO sqlalchemy.engine.base.Engine ('2015-12-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,420 INFO sqlalchemy.engine.base.Engine ('2015-12-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,422 INFO sqlalchemy.engine.base.Engine ('2015-12-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,424 INFO sqlalchemy.engine.base.Engine ('2015-12-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,426 INFO sqlalchemy.engine.base.Engine ('2015-12-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,428 INFO sqlalchemy.engine.base.Engine ('2015-12-10 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:34,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,430 INFO sqlalchemy.engine.base.Engine ('2015-12-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,432 INFO sqlalchemy.engine.base.Engine ('2015-12-12 00:00:00.000000', 0.39, 72)
2018-05-08 18:31:34,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,434 INFO sqlalchemy.engine.base.Engine ('2015-12-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,435 INFO sqlalchemy.engine.base.Engine ('2015-12-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:34,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,437 INFO sqlalchemy.engine.base.Engine ('2015-12-15 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:34,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,439 INFO sqlalchemy.engine.base.Engine ('2015-12-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,440 INFO sqlalchemy.engine.base.Engine ('2015-12-17 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:34,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,442 INFO sqlalchemy.engine.base.Engine ('2015-12-18 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:34,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,444 INFO sqlalchemy.engine.base.Engine ('2015-12-19 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:34,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,446 INFO sqlalchemy.engine.base.Engine ('2015-12-20 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:34,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,449 INFO sqlalchemy.engine.base.Engine ('2015-12-21 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:34,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,450 INFO sqlalchemy.engine.base.Engine ('2015-12-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,452 INFO sqlalchemy.engine.base.Engine ('2015-12-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,453 INFO sqlalchemy.engine.base.Engine ('2015-12-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,455 INFO sqlalchemy.engine.base.Engine ('2015-12-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,457 INFO sqlalchemy.engine.base.Engine ('2015-12-26 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:34,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,458 INFO sqlalchemy.engine.base.Engine ('2015-12-27 00:00:00.000000', 0.43, 74)
2018-05-08 18:31:34,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,460 INFO sqlalchemy.engine.base.Engine ('2015-12-28 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,462 INFO sqlalchemy.engine.base.Engine ('2015-12-29 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,464 INFO sqlalchemy.engine.base.Engine ('2015-12-30 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,466 INFO sqlalchemy.engine.base.Engine ('2015-12-31 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,468 INFO sqlalchemy.engine.base.Engine ('2016-01-01 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:34,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,470 INFO sqlalchemy.engine.base.Engine ('2016-01-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,472 INFO sqlalchemy.engine.base.Engine ('2016-01-03 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:34,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,473 INFO sqlalchemy.engine.base.Engine ('2016-01-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:34,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,475 INFO sqlalchemy.engine.base.Engine ('2016-01-05 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,477 INFO sqlalchemy.engine.base.Engine ('2016-01-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,480 INFO sqlalchemy.engine.base.Engine ('2016-01-07 00:00:00.000000', 0.18, 65)
2018-05-08 18:31:34,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,482 INFO sqlalchemy.engine.base.Engine ('2016-01-08 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:34,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,483 INFO sqlalchemy.engine.base.Engine ('2016-01-09 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:34,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,485 INFO sqlalchemy.engine.base.Engine ('2016-01-10 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:34,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,487 INFO sqlalchemy.engine.base.Engine ('2016-01-11 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,488 INFO sqlalchemy.engine.base.Engine ('2016-01-12 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:34,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,490 INFO sqlalchemy.engine.base.Engine ('2016-01-13 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:34,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,492 INFO sqlalchemy.engine.base.Engine ('2016-01-14 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:34,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,494 INFO sqlalchemy.engine.base.Engine ('2016-01-15 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,496 INFO sqlalchemy.engine.base.Engine ('2016-01-16 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:34,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,498 INFO sqlalchemy.engine.base.Engine ('2016-01-17 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:34,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,500 INFO sqlalchemy.engine.base.Engine ('2016-01-18 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:34,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,501 INFO sqlalchemy.engine.base.Engine ('2016-01-19 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:34,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,503 INFO sqlalchemy.engine.base.Engine ('2016-01-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,504 INFO sqlalchemy.engine.base.Engine ('2016-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,506 INFO sqlalchemy.engine.base.Engine ('2016-01-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,508 INFO sqlalchemy.engine.base.Engine ('2016-01-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,511 INFO sqlalchemy.engine.base.Engine ('2016-01-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,513 INFO sqlalchemy.engine.base.Engine ('2016-01-25 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:34,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,516 INFO sqlalchemy.engine.base.Engine ('2016-01-26 00:00:00.000000', 0.16, 68)
2018-05-08 18:31:34,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,517 INFO sqlalchemy.engine.base.Engine ('2016-01-27 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:34,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,519 INFO sqlalchemy.engine.base.Engine ('2016-01-28 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:34,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,520 INFO sqlalchemy.engine.base.Engine ('2016-01-29 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:34,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,522 INFO sqlalchemy.engine.base.Engine ('2016-01-30 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:34,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,523 INFO sqlalchemy.engine.base.Engine ('2016-01-31 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,525 INFO sqlalchemy.engine.base.Engine ('2016-02-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,527 INFO sqlalchemy.engine.base.Engine ('2016-02-02 00:00:00.000000', 0.06, 68)
2018-05-08 18:31:34,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,528 INFO sqlalchemy.engine.base.Engine ('2016-02-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,530 INFO sqlalchemy.engine.base.Engine ('2016-02-04 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:34,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,532 INFO sqlalchemy.engine.base.Engine ('2016-02-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,533 INFO sqlalchemy.engine.base.Engine ('2016-02-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:34,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,535 INFO sqlalchemy.engine.base.Engine ('2016-02-07 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:34,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,536 INFO sqlalchemy.engine.base.Engine ('2016-02-08 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:34,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,538 INFO sqlalchemy.engine.base.Engine ('2016-02-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,539 INFO sqlalchemy.engine.base.Engine ('2016-02-10 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:34,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,541 INFO sqlalchemy.engine.base.Engine ('2016-02-11 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:34,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,543 INFO sqlalchemy.engine.base.Engine ('2016-02-12 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:34,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,545 INFO sqlalchemy.engine.base.Engine ('2016-02-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,547 INFO sqlalchemy.engine.base.Engine ('2016-02-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,549 INFO sqlalchemy.engine.base.Engine ('2016-02-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,550 INFO sqlalchemy.engine.base.Engine ('2016-02-16 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:34,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,551 INFO sqlalchemy.engine.base.Engine ('2016-02-17 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:34,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,553 INFO sqlalchemy.engine.base.Engine ('2016-02-18 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:34,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,555 INFO sqlalchemy.engine.base.Engine ('2016-02-19 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:34,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,556 INFO sqlalchemy.engine.base.Engine ('2016-02-20 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:34,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,557 INFO sqlalchemy.engine.base.Engine ('2016-02-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,559 INFO sqlalchemy.engine.base.Engine ('2016-02-22 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:34,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,561 INFO sqlalchemy.engine.base.Engine ('2016-02-23 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:34,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,563 INFO sqlalchemy.engine.base.Engine ('2016-02-24 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:34,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,565 INFO sqlalchemy.engine.base.Engine ('2016-02-25 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:34,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,566 INFO sqlalchemy.engine.base.Engine ('2016-02-26 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,568 INFO sqlalchemy.engine.base.Engine ('2016-02-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,570 INFO sqlalchemy.engine.base.Engine ('2016-02-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,571 INFO sqlalchemy.engine.base.Engine ('2016-02-29 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,573 INFO sqlalchemy.engine.base.Engine ('2016-03-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,575 INFO sqlalchemy.engine.base.Engine ('2016-03-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,577 INFO sqlalchemy.engine.base.Engine ('2016-03-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:34,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,578 INFO sqlalchemy.engine.base.Engine ('2016-03-04 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:34,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,580 INFO sqlalchemy.engine.base.Engine ('2016-03-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:34,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,583 INFO sqlalchemy.engine.base.Engine ('2016-03-06 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:34,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,585 INFO sqlalchemy.engine.base.Engine ('2016-03-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,640 INFO sqlalchemy.engine.base.Engine ('2016-03-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,641 INFO sqlalchemy.engine.base.Engine ('2016-03-09 00:00:00.000000', 0.19, 68)
2018-05-08 18:31:34,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,643 INFO sqlalchemy.engine.base.Engine ('2016-03-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,645 INFO sqlalchemy.engine.base.Engine ('2016-03-11 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,647 INFO sqlalchemy.engine.base.Engine ('2016-03-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,648 INFO sqlalchemy.engine.base.Engine ('2016-03-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,651 INFO sqlalchemy.engine.base.Engine ('2016-03-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:34,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,652 INFO sqlalchemy.engine.base.Engine ('2016-03-15 00:00:00.000000', 0.08, 66)
2018-05-08 18:31:34,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,654 INFO sqlalchemy.engine.base.Engine ('2016-03-16 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:34,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,655 INFO sqlalchemy.engine.base.Engine ('2016-03-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,657 INFO sqlalchemy.engine.base.Engine ('2016-03-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:34,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,658 INFO sqlalchemy.engine.base.Engine ('2016-03-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,661 INFO sqlalchemy.engine.base.Engine ('2016-03-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,663 INFO sqlalchemy.engine.base.Engine ('2016-03-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,665 INFO sqlalchemy.engine.base.Engine ('2016-03-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,666 INFO sqlalchemy.engine.base.Engine ('2016-03-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,668 INFO sqlalchemy.engine.base.Engine ('2016-03-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:34,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,670 INFO sqlalchemy.engine.base.Engine ('2016-03-25 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:34,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,671 INFO sqlalchemy.engine.base.Engine ('2016-03-26 00:00:00.000000', 0.09, 68)
2018-05-08 18:31:34,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,672 INFO sqlalchemy.engine.base.Engine ('2016-03-27 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:34,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,674 INFO sqlalchemy.engine.base.Engine ('2016-03-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:34,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,676 INFO sqlalchemy.engine.base.Engine ('2016-03-29 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:34,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,677 INFO sqlalchemy.engine.base.Engine ('2016-03-30 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:34,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,679 INFO sqlalchemy.engine.base.Engine ('2016-03-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,681 INFO sqlalchemy.engine.base.Engine ('2016-04-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,683 INFO sqlalchemy.engine.base.Engine ('2016-04-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:34,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,684 INFO sqlalchemy.engine.base.Engine ('2016-04-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,686 INFO sqlalchemy.engine.base.Engine ('2016-04-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:34,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,687 INFO sqlalchemy.engine.base.Engine ('2016-04-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,689 INFO sqlalchemy.engine.base.Engine ('2016-04-06 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:34,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,690 INFO sqlalchemy.engine.base.Engine ('2016-04-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,692 INFO sqlalchemy.engine.base.Engine ('2016-04-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,694 INFO sqlalchemy.engine.base.Engine ('2016-04-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,696 INFO sqlalchemy.engine.base.Engine ('2016-04-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,698 INFO sqlalchemy.engine.base.Engine ('2016-04-11 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:34,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,700 INFO sqlalchemy.engine.base.Engine ('2016-04-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,701 INFO sqlalchemy.engine.base.Engine ('2016-04-13 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,703 INFO sqlalchemy.engine.base.Engine ('2016-04-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,704 INFO sqlalchemy.engine.base.Engine ('2016-04-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,706 INFO sqlalchemy.engine.base.Engine ('2016-04-16 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,707 INFO sqlalchemy.engine.base.Engine ('2016-04-17 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:34,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,709 INFO sqlalchemy.engine.base.Engine ('2016-04-18 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:34,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,711 INFO sqlalchemy.engine.base.Engine ('2016-04-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,713 INFO sqlalchemy.engine.base.Engine ('2016-04-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,715 INFO sqlalchemy.engine.base.Engine ('2016-04-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,717 INFO sqlalchemy.engine.base.Engine ('2016-04-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,718 INFO sqlalchemy.engine.base.Engine ('2016-04-23 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:34,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,719 INFO sqlalchemy.engine.base.Engine ('2016-04-24 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:34,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,721 INFO sqlalchemy.engine.base.Engine ('2016-04-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,722 INFO sqlalchemy.engine.base.Engine ('2016-04-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,724 INFO sqlalchemy.engine.base.Engine ('2016-04-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,726 INFO sqlalchemy.engine.base.Engine ('2016-04-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,727 INFO sqlalchemy.engine.base.Engine ('2016-04-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,729 INFO sqlalchemy.engine.base.Engine ('2016-04-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,731 INFO sqlalchemy.engine.base.Engine ('2016-05-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,733 INFO sqlalchemy.engine.base.Engine ('2016-05-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,734 INFO sqlalchemy.engine.base.Engine ('2016-05-03 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:34,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,736 INFO sqlalchemy.engine.base.Engine ('2016-05-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,738 INFO sqlalchemy.engine.base.Engine ('2016-05-05 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:34,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,739 INFO sqlalchemy.engine.base.Engine ('2016-05-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,741 INFO sqlalchemy.engine.base.Engine ('2016-05-07 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:34,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,742 INFO sqlalchemy.engine.base.Engine ('2016-05-08 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:34,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,744 INFO sqlalchemy.engine.base.Engine ('2016-05-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,747 INFO sqlalchemy.engine.base.Engine ('2016-05-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,748 INFO sqlalchemy.engine.base.Engine ('2016-05-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,750 INFO sqlalchemy.engine.base.Engine ('2016-05-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,752 INFO sqlalchemy.engine.base.Engine ('2016-05-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:34,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,753 INFO sqlalchemy.engine.base.Engine ('2016-05-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,754 INFO sqlalchemy.engine.base.Engine ('2016-05-15 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:34,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,756 INFO sqlalchemy.engine.base.Engine ('2016-05-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,758 INFO sqlalchemy.engine.base.Engine ('2016-05-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,760 INFO sqlalchemy.engine.base.Engine ('2016-05-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,761 INFO sqlalchemy.engine.base.Engine ('2016-05-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,763 INFO sqlalchemy.engine.base.Engine ('2016-05-20 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,765 INFO sqlalchemy.engine.base.Engine ('2016-05-21 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:34,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,767 INFO sqlalchemy.engine.base.Engine ('2016-05-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,768 INFO sqlalchemy.engine.base.Engine ('2016-05-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,770 INFO sqlalchemy.engine.base.Engine ('2016-05-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,772 INFO sqlalchemy.engine.base.Engine ('2016-05-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,773 INFO sqlalchemy.engine.base.Engine ('2016-05-26 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:34,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,775 INFO sqlalchemy.engine.base.Engine ('2016-05-27 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,777 INFO sqlalchemy.engine.base.Engine ('2016-05-28 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:34,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,779 INFO sqlalchemy.engine.base.Engine ('2016-05-29 00:00:00.000000', 0.54, 73)
2018-05-08 18:31:34,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,781 INFO sqlalchemy.engine.base.Engine ('2016-05-30 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:34,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,783 INFO sqlalchemy.engine.base.Engine ('2016-05-31 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:34,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,784 INFO sqlalchemy.engine.base.Engine ('2016-06-01 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:34,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,786 INFO sqlalchemy.engine.base.Engine ('2016-06-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,787 INFO sqlalchemy.engine.base.Engine ('2016-06-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:34,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,789 INFO sqlalchemy.engine.base.Engine ('2016-06-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:34,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,790 INFO sqlalchemy.engine.base.Engine ('2016-06-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,792 INFO sqlalchemy.engine.base.Engine ('2016-06-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,794 INFO sqlalchemy.engine.base.Engine ('2016-06-07 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,796 INFO sqlalchemy.engine.base.Engine ('2016-06-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,798 INFO sqlalchemy.engine.base.Engine ('2016-06-09 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:34,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,799 INFO sqlalchemy.engine.base.Engine ('2016-06-10 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:34,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,801 INFO sqlalchemy.engine.base.Engine ('2016-06-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,803 INFO sqlalchemy.engine.base.Engine ('2016-06-12 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:34,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,804 INFO sqlalchemy.engine.base.Engine ('2016-06-13 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,805 INFO sqlalchemy.engine.base.Engine ('2016-06-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,807 INFO sqlalchemy.engine.base.Engine ('2016-06-15 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:34,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,852 INFO sqlalchemy.engine.base.Engine ('2016-06-16 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:34,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,854 INFO sqlalchemy.engine.base.Engine ('2016-06-17 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:34,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,856 INFO sqlalchemy.engine.base.Engine ('2016-06-18 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,857 INFO sqlalchemy.engine.base.Engine ('2016-06-19 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,859 INFO sqlalchemy.engine.base.Engine ('2016-06-20 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:34,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,861 INFO sqlalchemy.engine.base.Engine ('2016-06-21 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,863 INFO sqlalchemy.engine.base.Engine ('2016-06-22 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,865 INFO sqlalchemy.engine.base.Engine ('2016-06-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,866 INFO sqlalchemy.engine.base.Engine ('2016-06-24 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:34,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,868 INFO sqlalchemy.engine.base.Engine ('2016-06-25 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:34,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,869 INFO sqlalchemy.engine.base.Engine ('2016-06-26 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:34,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,871 INFO sqlalchemy.engine.base.Engine ('2016-06-27 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:34,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,872 INFO sqlalchemy.engine.base.Engine ('2016-06-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:34,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,874 INFO sqlalchemy.engine.base.Engine ('2016-06-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,876 INFO sqlalchemy.engine.base.Engine ('2016-06-30 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,877 INFO sqlalchemy.engine.base.Engine ('2016-07-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,879 INFO sqlalchemy.engine.base.Engine ('2016-07-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,881 INFO sqlalchemy.engine.base.Engine ('2016-07-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,882 INFO sqlalchemy.engine.base.Engine ('2016-07-04 00:00:00.000000', 0.04, 79)
2018-05-08 18:31:34,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,884 INFO sqlalchemy.engine.base.Engine ('2016-07-05 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:34,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,885 INFO sqlalchemy.engine.base.Engine ('2016-07-06 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:34,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,887 INFO sqlalchemy.engine.base.Engine ('2016-07-07 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:34,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,888 INFO sqlalchemy.engine.base.Engine ('2016-07-08 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,890 INFO sqlalchemy.engine.base.Engine ('2016-07-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,892 INFO sqlalchemy.engine.base.Engine ('2016-07-10 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:34,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,893 INFO sqlalchemy.engine.base.Engine ('2016-07-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:34,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,895 INFO sqlalchemy.engine.base.Engine ('2016-07-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,897 INFO sqlalchemy.engine.base.Engine ('2016-07-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,899 INFO sqlalchemy.engine.base.Engine ('2016-07-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,900 INFO sqlalchemy.engine.base.Engine ('2016-07-15 00:00:00.000000', 0.46, 78)
2018-05-08 18:31:34,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,902 INFO sqlalchemy.engine.base.Engine ('2016-07-16 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:34,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,903 INFO sqlalchemy.engine.base.Engine ('2016-07-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,905 INFO sqlalchemy.engine.base.Engine ('2016-07-18 00:00:00.000000', 1.25, 76)
2018-05-08 18:31:34,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,906 INFO sqlalchemy.engine.base.Engine ('2016-07-19 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:34,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,908 INFO sqlalchemy.engine.base.Engine ('2016-07-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,910 INFO sqlalchemy.engine.base.Engine ('2016-07-21 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:34,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,911 INFO sqlalchemy.engine.base.Engine ('2016-07-22 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:34,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,913 INFO sqlalchemy.engine.base.Engine ('2016-07-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,915 INFO sqlalchemy.engine.base.Engine ('2016-07-24 00:00:00.000000', 0.13, 79)
2018-05-08 18:31:34,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,916 INFO sqlalchemy.engine.base.Engine ('2016-07-25 00:00:00.000000', 4.2, 78)
2018-05-08 18:31:34,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,918 INFO sqlalchemy.engine.base.Engine ('2016-07-26 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,920 INFO sqlalchemy.engine.base.Engine ('2016-07-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,921 INFO sqlalchemy.engine.base.Engine ('2016-07-28 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,923 INFO sqlalchemy.engine.base.Engine ('2016-07-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,925 INFO sqlalchemy.engine.base.Engine ('2016-07-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,926 INFO sqlalchemy.engine.base.Engine ('2016-07-31 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:34,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,929 INFO sqlalchemy.engine.base.Engine ('2016-08-01 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:34,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,930 INFO sqlalchemy.engine.base.Engine ('2016-08-02 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:34,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,932 INFO sqlalchemy.engine.base.Engine ('2016-08-03 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,933 INFO sqlalchemy.engine.base.Engine ('2016-08-04 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:34,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,935 INFO sqlalchemy.engine.base.Engine ('2016-08-05 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:34,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,937 INFO sqlalchemy.engine.base.Engine ('2016-08-06 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,938 INFO sqlalchemy.engine.base.Engine ('2016-08-07 00:00:00.000000', 0.39, 77)
2018-05-08 18:31:34,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,940 INFO sqlalchemy.engine.base.Engine ('2016-08-08 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:34,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,941 INFO sqlalchemy.engine.base.Engine ('2016-08-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,943 INFO sqlalchemy.engine.base.Engine ('2016-08-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,945 INFO sqlalchemy.engine.base.Engine ('2016-08-11 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,947 INFO sqlalchemy.engine.base.Engine ('2016-08-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,948 INFO sqlalchemy.engine.base.Engine ('2016-08-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,950 INFO sqlalchemy.engine.base.Engine ('2016-08-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,952 INFO sqlalchemy.engine.base.Engine ('2016-08-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,953 INFO sqlalchemy.engine.base.Engine ('2016-08-16 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,955 INFO sqlalchemy.engine.base.Engine ('2016-08-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,956 INFO sqlalchemy.engine.base.Engine ('2016-08-18 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,959 INFO sqlalchemy.engine.base.Engine ('2016-08-19 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:34,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,960 INFO sqlalchemy.engine.base.Engine ('2016-08-20 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,962 INFO sqlalchemy.engine.base.Engine ('2016-08-21 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:34,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,964 INFO sqlalchemy.engine.base.Engine ('2016-08-22 00:00:00.000000', 0.4, 77)
2018-05-08 18:31:34,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,967 INFO sqlalchemy.engine.base.Engine ('2016-08-23 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:34,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,968 INFO sqlalchemy.engine.base.Engine ('2016-08-24 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:34,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:34,970 INFO sqlalchemy.engine.base.Engine ('2016-08-25 00:00:00.000000', 0.08, 80)
2018-05-08 18:31:34,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,972 INFO sqlalchemy.engine.base.Engine ('2016-08-26 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,973 INFO sqlalchemy.engine.base.Engine ('2016-08-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:34,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,975 INFO sqlalchemy.engine.base.Engine ('2016-08-28 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:34,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,978 INFO sqlalchemy.engine.base.Engine ('2016-08-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,979 INFO sqlalchemy.engine.base.Engine ('2016-08-30 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,982 INFO sqlalchemy.engine.base.Engine ('2016-08-31 00:00:00.000000', 0.13, 80)
2018-05-08 18:31:34,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,983 INFO sqlalchemy.engine.base.Engine ('2016-09-01 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:34,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,985 INFO sqlalchemy.engine.base.Engine ('2016-09-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,986 INFO sqlalchemy.engine.base.Engine ('2016-09-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:34,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,988 INFO sqlalchemy.engine.base.Engine ('2016-09-04 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:34,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,990 INFO sqlalchemy.engine.base.Engine ('2016-09-07 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:34,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,991 INFO sqlalchemy.engine.base.Engine ('2016-09-08 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:34,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,993 INFO sqlalchemy.engine.base.Engine ('2016-09-09 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:34,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,995 INFO sqlalchemy.engine.base.Engine ('2016-09-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:34,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,997 INFO sqlalchemy.engine.base.Engine ('2016-09-11 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:34,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:34,999 INFO sqlalchemy.engine.base.Engine ('2016-09-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,001 INFO sqlalchemy.engine.base.Engine ('2016-09-13 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:35,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,002 INFO sqlalchemy.engine.base.Engine ('2016-09-14 00:00:00.000000', 1.32, 75)
2018-05-08 18:31:35,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,004 INFO sqlalchemy.engine.base.Engine ('2016-09-15 00:00:00.000000', 0.42, 79)
2018-05-08 18:31:35,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,005 INFO sqlalchemy.engine.base.Engine ('2016-09-16 00:00:00.000000', 0.06, 80)
2018-05-08 18:31:35,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,007 INFO sqlalchemy.engine.base.Engine ('2016-09-17 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:35,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,010 INFO sqlalchemy.engine.base.Engine ('2016-09-18 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:35,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,012 INFO sqlalchemy.engine.base.Engine ('2016-09-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,013 INFO sqlalchemy.engine.base.Engine ('2016-09-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,016 INFO sqlalchemy.engine.base.Engine ('2016-09-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,017 INFO sqlalchemy.engine.base.Engine ('2016-09-22 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:35,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,019 INFO sqlalchemy.engine.base.Engine ('2016-09-23 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:35,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,020 INFO sqlalchemy.engine.base.Engine ('2016-09-24 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:35,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,021 INFO sqlalchemy.engine.base.Engine ('2016-09-25 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,071 INFO sqlalchemy.engine.base.Engine ('2016-09-26 00:00:00.000000', 0.06, 80)
2018-05-08 18:31:35,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,072 INFO sqlalchemy.engine.base.Engine ('2016-09-27 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:35,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,074 INFO sqlalchemy.engine.base.Engine ('2016-09-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,076 INFO sqlalchemy.engine.base.Engine ('2016-09-29 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,078 INFO sqlalchemy.engine.base.Engine ('2016-09-30 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:35,079 INFO sqlalchemy.engine.base.Engine ('2016-10-01 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,081 INFO sqlalchemy.engine.base.Engine ('2016-10-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,082 INFO sqlalchemy.engine.base.Engine ('2016-10-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,084 INFO sqlalchemy.engine.base.Engine ('2016-10-04 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,085 INFO sqlalchemy.engine.base.Engine ('2016-10-05 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,087 INFO sqlalchemy.engine.base.Engine ('2016-10-06 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,088 INFO sqlalchemy.engine.base.Engine ('2016-10-07 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,090 INFO sqlalchemy.engine.base.Engine ('2016-10-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,092 INFO sqlalchemy.engine.base.Engine ('2016-10-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:35,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,094 INFO sqlalchemy.engine.base.Engine ('2016-10-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:35,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,096 INFO sqlalchemy.engine.base.Engine ('2016-10-11 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,098 INFO sqlalchemy.engine.base.Engine ('2016-10-12 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,099 INFO sqlalchemy.engine.base.Engine ('2016-10-13 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,101 INFO sqlalchemy.engine.base.Engine ('2016-10-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,103 INFO sqlalchemy.engine.base.Engine ('2016-10-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,106 INFO sqlalchemy.engine.base.Engine ('2016-10-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,109 INFO sqlalchemy.engine.base.Engine ('2016-10-17 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:35,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,111 INFO sqlalchemy.engine.base.Engine ('2016-10-18 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:35,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,112 INFO sqlalchemy.engine.base.Engine ('2016-10-19 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:35,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,115 INFO sqlalchemy.engine.base.Engine ('2016-10-20 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:35,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,116 INFO sqlalchemy.engine.base.Engine ('2016-10-21 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:35,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,117 INFO sqlalchemy.engine.base.Engine ('2016-10-22 00:00:00.000000', 0.15, 79)
2018-05-08 18:31:35,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,119 INFO sqlalchemy.engine.base.Engine ('2016-10-23 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:35,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,121 INFO sqlalchemy.engine.base.Engine ('2016-10-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,122 INFO sqlalchemy.engine.base.Engine ('2016-10-25 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:35,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,124 INFO sqlalchemy.engine.base.Engine ('2016-10-26 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,125 INFO sqlalchemy.engine.base.Engine ('2016-10-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,127 INFO sqlalchemy.engine.base.Engine ('2016-10-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,129 INFO sqlalchemy.engine.base.Engine ('2016-10-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,131 INFO sqlalchemy.engine.base.Engine ('2016-10-30 00:00:00.000000', 0.24, 76)
2018-05-08 18:31:35,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,132 INFO sqlalchemy.engine.base.Engine ('2016-10-31 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:35,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,133 INFO sqlalchemy.engine.base.Engine ('2016-11-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,135 INFO sqlalchemy.engine.base.Engine ('2016-11-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,136 INFO sqlalchemy.engine.base.Engine ('2016-11-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,138 INFO sqlalchemy.engine.base.Engine ('2016-11-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:35,140 INFO sqlalchemy.engine.base.Engine ('2016-11-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:35,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,141 INFO sqlalchemy.engine.base.Engine ('2016-11-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:35,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,143 INFO sqlalchemy.engine.base.Engine ('2016-11-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,145 INFO sqlalchemy.engine.base.Engine ('2016-11-08 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:35,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,148 INFO sqlalchemy.engine.base.Engine ('2016-11-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,149 INFO sqlalchemy.engine.base.Engine ('2016-11-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,151 INFO sqlalchemy.engine.base.Engine ('2016-11-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,152 INFO sqlalchemy.engine.base.Engine ('2016-11-12 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,154 INFO sqlalchemy.engine.base.Engine ('2016-11-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,155 INFO sqlalchemy.engine.base.Engine ('2016-11-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,157 INFO sqlalchemy.engine.base.Engine ('2016-11-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,158 INFO sqlalchemy.engine.base.Engine ('2016-11-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,160 INFO sqlalchemy.engine.base.Engine ('2016-11-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,161 INFO sqlalchemy.engine.base.Engine ('2016-11-18 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,163 INFO sqlalchemy.engine.base.Engine ('2016-11-19 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:35,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,165 INFO sqlalchemy.engine.base.Engine ('2016-11-20 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:35,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,167 INFO sqlalchemy.engine.base.Engine ('2016-11-21 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:35,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,169 INFO sqlalchemy.engine.base.Engine ('2016-11-22 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:35,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,170 INFO sqlalchemy.engine.base.Engine ('2016-11-23 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:35,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,172 INFO sqlalchemy.engine.base.Engine ('2016-11-24 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:35,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,174 INFO sqlalchemy.engine.base.Engine ('2016-11-25 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:35,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,176 INFO sqlalchemy.engine.base.Engine ('2016-11-26 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:35,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,177 INFO sqlalchemy.engine.base.Engine ('2016-11-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:35,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,179 INFO sqlalchemy.engine.base.Engine ('2016-11-28 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:35,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,181 INFO sqlalchemy.engine.base.Engine ('2016-11-29 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:35,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,183 INFO sqlalchemy.engine.base.Engine ('2016-11-30 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:35,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,184 INFO sqlalchemy.engine.base.Engine ('2016-12-01 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:35,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,185 INFO sqlalchemy.engine.base.Engine ('2016-12-02 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:35,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,187 INFO sqlalchemy.engine.base.Engine ('2016-12-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:35,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,188 INFO sqlalchemy.engine.base.Engine ('2016-12-04 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:35,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,190 INFO sqlalchemy.engine.base.Engine ('2016-12-05 00:00:00.000000', 0.43, 68)
2018-05-08 18:31:35,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,192 INFO sqlalchemy.engine.base.Engine ('2016-12-06 00:00:00.000000', 0.02, 67)
2018-05-08 18:31:35,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,194 INFO sqlalchemy.engine.base.Engine ('2016-12-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:35,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,195 INFO sqlalchemy.engine.base.Engine ('2016-12-08 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:35,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,198 INFO sqlalchemy.engine.base.Engine ('2016-12-09 00:00:00.000000', 0.52, 70)

2018-05-08 18:31:35,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,200 INFO sqlalchemy.engine.base.Engine ('2016-12-10 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:35,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,202 INFO sqlalchemy.engine.base.Engine ('2016-12-11 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:35,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,204 INFO sqlalchemy.engine.base.Engine ('2016-12-12 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:35,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,205 INFO sqlalchemy.engine.base.Engine ('2016-12-13 00:00:00.000000', 0.05, 67)
2018-05-08 18:31:35,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,207 INFO sqlalchemy.engine.base.Engine ('2016-12-14 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:35,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,209 INFO sqlalchemy.engine.base.Engine ('2016-12-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:35,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,210 INFO sqlalchemy.engine.base.Engine ('2016-12-16 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:35,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,213 INFO sqlalchemy.engine.base.Engine ('2016-12-17 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:35,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,215 INFO sqlalchemy.engine.base.Engine ('2016-12-18 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:35,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,216 INFO sqlalchemy.engine.base.Engine ('2016-12-19 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:35,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,218 INFO sqlalchemy.engine.base.Engine ('2016-12-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:35,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,219 INFO sqlalchemy.engine.base.Engine ('2016-12-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,221 INFO sqlalchemy.engine.base.Engine ('2016-12-22 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:35,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,222 INFO sqlalchemy.engine.base.Engine ('2016-12-23 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:35,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,224 INFO sqlalchemy.engine.base.Engine ('2016-12-24 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:35,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,226 INFO sqlalchemy.engine.base.Engine ('2016-12-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,228 INFO sqlalchemy.engine.base.Engine ('2016-12-26 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:35,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,230 INFO sqlalchemy.engine.base.Engine ('2016-12-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,231 INFO sqlalchemy.engine.base.Engine ('2016-12-28 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:35,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,233 INFO sqlalchemy.engine.base.Engine ('2016-12-29 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:35,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,235 INFO sqlalchemy.engine.base.Engine ('2016-12-30 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:35,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,236 INFO sqlalchemy.engine.base.Engine ('2016-12-31 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:35,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,238 INFO sqlalchemy.engine.base.Engine ('2017-01-01 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:35,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,240 INFO sqlalchemy.engine.base.Engine ('2017-01-02 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:35,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,241 INFO sqlalchemy.engine.base.Engine ('2017-01-03 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:35,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,282 INFO sqlalchemy.engine.base.Engine ('2017-01-04 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:35,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,283 INFO sqlalchemy.engine.base.Engine ('2017-01-05 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:35,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,285 INFO sqlalchemy.engine.base.Engine ('2017-01-06 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:35,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,287 INFO sqlalchemy.engine.base.Engine ('2017-01-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:35,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,288 INFO sqlalchemy.engine.base.Engine ('2017-01-08 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:35,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,290 INFO sqlalchemy.engine.base.Engine ('2017-01-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:35,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,292 INFO sqlalchemy.engine.base.Engine ('2017-01-10 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:35,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,294 INFO sqlalchemy.engine.base.Engine ('2017-01-11 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:35,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,297 INFO sqlalchemy.engine.base.Engine ('2017-01-12 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:35,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,298 INFO sqlalchemy.engine.base.Engine ('2017-01-13 00:00:00.000000', 0.0, 67)

2018-05-08 18:31:35,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,300 INFO sqlalchemy.engine.base.Engine ('2017-01-14 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:35,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,301 INFO sqlalchemy.engine.base.Engine ('2017-01-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:35,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,303 INFO sqlalchemy.engine.base.Engine ('2017-01-16 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:35,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,305 INFO sqlalchemy.engine.base.Engine ('2017-01-17 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:35,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,306 INFO sqlalchemy.engine.base.Engine ('2017-01-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,308 INFO sqlalchemy.engine.base.Engine ('2017-01-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:35,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,310 INFO sqlalchemy.engine.base.Engine ('2017-01-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,312 INFO sqlalchemy.engine.base.Engine ('2017-01-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,314 INFO sqlalchemy.engine.base.Engine ('2017-01-22 00:00:00.000000', 0.16, 72)
2018-05-08 18:31:35,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,316 INFO sqlalchemy.engine.base.Engine ('2017-01-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,317 INFO sqlalchemy.engine.base.Engine ('2017-01-24 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:35,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,319 INFO sqlalchemy.engine.base.Engine ('2017-01-25 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:35,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,320 INFO sqlalchemy.engine.base.Engine ('2017-01-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,322 INFO sqlalchemy.engine.base.Engine ('2017-01-27 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:35,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,324 INFO sqlalchemy.engine.base.Engine ('2017-01-28 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:35,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,326 INFO sqlalchemy.engine.base.Engine ('2017-01-29 00:00:00.000000', 0.18, 67)
2018-05-08 18:31:35,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,327 INFO sqlalchemy.engine.base.Engine ('2017-01-30 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:35,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,329 INFO sqlalchemy.engine.base.Engine ('2017-01-31 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:35,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,331 INFO sqlalchemy.engine.base.Engine ('2017-02-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:35,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,332 INFO sqlalchemy.engine.base.Engine ('2017-02-02 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:35,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,334 INFO sqlalchemy.engine.base.Engine ('2017-02-03 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:35,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,335 INFO sqlalchemy.engine.base.Engine ('2017-02-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,337 INFO sqlalchemy.engine.base.Engine ('2017-02-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:35,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,338 INFO sqlalchemy.engine.base.Engine ('2017-02-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:35,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,339 INFO sqlalchemy.engine.base.Engine ('2017-02-07 00:00:00.000000', 0.51, 64)
2018-05-08 18:31:35,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,341 INFO sqlalchemy.engine.base.Engine ('2017-02-08 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:35,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,343 INFO sqlalchemy.engine.base.Engine ('2017-02-09 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:35,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,345 INFO sqlalchemy.engine.base.Engine ('2017-02-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,347 INFO sqlalchemy.engine.base.Engine ('2017-02-11 00:00:00.000000', 0.31, 69)
2018-05-08 18:31:35,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,348 INFO sqlalchemy.engine.base.Engine ('2017-02-12 00:00:00.000000', 2.62, 68)
2018-05-08 18:31:35,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,350 INFO sqlalchemy.engine.base.Engine ('2017-02-13 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:35,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,351 INFO sqlalchemy.engine.base.Engine ('2017-02-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:35,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,353 INFO sqlalchemy.engine.base.Engine ('2017-02-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:35,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,354 INFO sqlalchemy.engine.base.Engine ('2017-02-16 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:35,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,356 INFO sqlalchemy.engine.base.Engine ('2017-02-17 00:00:00.000000', 0.0, 71)

2018-05-08 18:31:35,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,358 INFO sqlalchemy.engine.base.Engine ('2017-02-18 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:35,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,359 INFO sqlalchemy.engine.base.Engine ('2017-02-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:35,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,361 INFO sqlalchemy.engine.base.Engine ('2017-02-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,363 INFO sqlalchemy.engine.base.Engine ('2017-02-21 00:00:00.000000', 0.06, 70)
2018-05-08 18:31:35,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,365 INFO sqlalchemy.engine.base.Engine ('2017-02-22 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:35,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,366 INFO sqlalchemy.engine.base.Engine ('2017-02-23 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:35,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,368 INFO sqlalchemy.engine.base.Engine ('2017-02-24 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:35,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,370 INFO sqlalchemy.engine.base.Engine ('2017-02-25 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:35,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,372 INFO sqlalchemy.engine.base.Engine ('2017-02-26 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:35,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,373 INFO sqlalchemy.engine.base.Engine ('2017-02-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,375 INFO sqlalchemy.engine.base.Engine ('2017-02-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,377 INFO sqlalchemy.engine.base.Engine ('2017-03-01 00:00:00.000000', 1.19, 66)
2018-05-08 18:31:35,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,379 INFO sqlalchemy.engine.base.Engine ('2017-03-02 00:00:00.000000', 0.73, 73)
2018-05-08 18:31:35,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,381 INFO sqlalchemy.engine.base.Engine ('2017-03-03 00:00:00.000000', 0.47, 69)
2018-05-08 18:31:35,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,382 INFO sqlalchemy.engine.base.Engine ('2017-03-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,384 INFO sqlalchemy.engine.base.Engine ('2017-03-05 00:00:00.000000', 0.35, 71)
2018-05-08 18:31:35,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,386 INFO sqlalchemy.engine.base.Engine ('2017-03-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:35,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,388 INFO sqlalchemy.engine.base.Engine ('2017-03-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:35,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,389 INFO sqlalchemy.engine.base.Engine ('2017-03-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,391 INFO sqlalchemy.engine.base.Engine ('2017-03-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,394 INFO sqlalchemy.engine.base.Engine ('2017-03-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:35,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,396 INFO sqlalchemy.engine.base.Engine ('2017-03-11 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,398 INFO sqlalchemy.engine.base.Engine ('2017-03-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,400 INFO sqlalchemy.engine.base.Engine ('2017-03-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,401 INFO sqlalchemy.engine.base.Engine ('2017-03-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,403 INFO sqlalchemy.engine.base.Engine ('2017-03-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:35,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,405 INFO sqlalchemy.engine.base.Engine ('2017-03-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:35,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,406 INFO sqlalchemy.engine.base.Engine ('2017-03-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:35,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,408 INFO sqlalchemy.engine.base.Engine ('2017-03-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:35,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,410 INFO sqlalchemy.engine.base.Engine ('2017-03-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:35,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,413 INFO sqlalchemy.engine.base.Engine ('2017-03-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:35,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,415 INFO sqlalchemy.engine.base.Engine ('2017-03-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:35,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,416 INFO sqlalchemy.engine.base.Engine ('2017-03-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:35,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,418 INFO sqlalchemy.engine.base.Engine ('2017-03-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:35,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,419 INFO sqlalchemy.engine.base.Engine ('2017-03-24 00:00:00.000000', 0.02, 73)

2018-05-08 18:31:35,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,421 INFO sqlalchemy.engine.base.Engine ('2017-03-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:35,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519397" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:35,422 INFO sqlalchemy.engine.base.Engine ('2017-03-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,435 INFO sqlalchemy.engine.base.Engine ('2011-02-01 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:36,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,437 INFO sqlalchemy.engine.base.Engine ('2011-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,439 INFO sqlalchemy.engine.base.Engine ('2011-02-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,440 INFO sqlalchemy.engine.base.Engine ('2011-02-04 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:36,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,442 INFO sqlalchemy.engine.base.Engine ('2011-02-08 00:00:00.000000', 0.3, 70)
2018-05-08 18:31:36,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,443 INFO sqlalchemy.engine.base.Engine ('2011-02-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,445 INFO sqlalchemy.engine.base.Engine ('2011-02-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,446 INFO sqlalchemy.engine.base.Engine ('2011-02-11 00:00:00.000000', 0.34, 66)
2018-05-08 18:31:36,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,449 INFO sqlalchemy.engine.base.Engine ('2011-02-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:36,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,450 INFO sqlalchemy.engine.base.Engine ('2011-02-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,452 INFO sqlalchemy.engine.base.Engine ('2011-02-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,453 INFO sqlalchemy.engine.base.Engine ('2011-02-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:36,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,455 INFO sqlalchemy.engine.base.Engine ('2011-02-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,456 INFO sqlalchemy.engine.base.Engine ('2011-02-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,458 INFO sqlalchemy.engine.base.Engine ('2011-02-24 00:00:00.000000', 3.33, 68)
2018-05-08 18:31:36,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,459 INFO sqlalchemy.engine.base.Engine ('2011-02-25 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,461 INFO sqlalchemy.engine.base.Engine ('2011-03-01 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:36,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,462 INFO sqlalchemy.engine.base.Engine ('2011-03-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,464 INFO sqlalchemy.engine.base.Engine ('2011-03-03 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:36,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,465 INFO sqlalchemy.engine.base.Engine ('2011-03-04 00:00:00.000000', 1.45, 73)
2018-05-08 18:31:36,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,467 INFO sqlalchemy.engine.base.Engine ('2011-03-05 00:00:00.000000', 0.26, 68)
2018-05-08 18:31:36,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,469 INFO sqlalchemy.engine.base.Engine ('2011-03-06 00:00:00.000000', 0.64, 75)
2018-05-08 18:31:36,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,470 INFO sqlalchemy.engine.base.Engine ('2011-03-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,471 INFO sqlalchemy.engine.base.Engine ('2011-03-08 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:36,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,473 INFO sqlalchemy.engine.base.Engine ('2011-03-09 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:36,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,474 INFO sqlalchemy.engine.base.Engine ('2011-03-10 00:00:00.000000', 1.4, 68)
2018-05-08 18:31:36,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,476 INFO sqlalchemy.engine.base.Engine ('2011-03-11 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:36,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,478 INFO sqlalchemy.engine.base.Engine ('2011-03-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,479 INFO sqlalchemy.engine.base.Engine ('2011-03-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,481 INFO sqlalchemy.engine.base.Engine ('2011-03-17 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:36,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,482 INFO sqlalchemy.engine.base.Engine ('2011-03-18 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:36,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,483 INFO sqlalchemy.engine.base.Engine ('2011-03-19 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:36,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,485 INFO sqlalchemy.engine.base.Engine ('2011-03-22 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:36,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:36,486 INFO sqlalchemy.engine.base.Engine ('2011-03-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,488 INFO sqlalchemy.engine.base.Engine ('2011-03-24 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:36,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,490 INFO sqlalchemy.engine.base.Engine ('2011-03-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,492 INFO sqlalchemy.engine.base.Engine ('2011-03-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,494 INFO sqlalchemy.engine.base.Engine ('2011-03-31 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:36,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,495 INFO sqlalchemy.engine.base.Engine ('2011-04-01 00:00:00.000000', 0.35, 71)
2018-05-08 18:31:36,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,497 INFO sqlalchemy.engine.base.Engine ('2011-04-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,498 INFO sqlalchemy.engine.base.Engine ('2011-04-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,500 INFO sqlalchemy.engine.base.Engine ('2011-04-07 00:00:00.000000', 0.59, 67)
2018-05-08 18:31:36,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,501 INFO sqlalchemy.engine.base.Engine ('2011-04-08 00:00:00.000000', 0.31, 69)
2018-05-08 18:31:36,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,503 INFO sqlalchemy.engine.base.Engine ('2011-04-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,504 INFO sqlalchemy.engine.base.Engine ('2011-04-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,506 INFO sqlalchemy.engine.base.Engine ('2011-04-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:36,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,507 INFO sqlalchemy.engine.base.Engine ('2011-04-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,509 INFO sqlalchemy.engine.base.Engine ('2011-04-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,510 INFO sqlalchemy.engine.base.Engine ('2011-04-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,512 INFO sqlalchemy.engine.base.Engine ('2011-04-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,513 INFO sqlalchemy.engine.base.Engine ('2011-04-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,515 INFO sqlalchemy.engine.base.Engine ('2011-04-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,517 INFO sqlalchemy.engine.base.Engine ('2011-04-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,518 INFO sqlalchemy.engine.base.Engine ('2011-04-23 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:36,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,520 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,521 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,523 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:36,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,524 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,526 INFO sqlalchemy.engine.base.Engine ('2011-04-29 00:00:00.000000', 0.34, 72)
2018-05-08 18:31:36,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,527 INFO sqlalchemy.engine.base.Engine ('2011-04-30 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:36,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,529 INFO sqlalchemy.engine.base.Engine ('2011-05-03 00:00:00.000000', 0.64, 71)
2018-05-08 18:31:36,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,530 INFO sqlalchemy.engine.base.Engine ('2011-05-04 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:36,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,532 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:36,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,533 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 0.4, 69)
2018-05-08 18:31:36,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,535 INFO sqlalchemy.engine.base.Engine ('2011-05-07 00:00:00.000000', 0.99, 70)
2018-05-08 18:31:36,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,536 INFO sqlalchemy.engine.base.Engine ('2011-05-10 00:00:00.000000', 0.38, 73)
2018-05-08 18:31:36,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,537 INFO sqlalchemy.engine.base.Engine ('2011-05-11 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:36,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,539 INFO sqlalchemy.engine.base.Engine ('2011-05-12 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:36,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,541 INFO sqlalchemy.engine.base.Engine ('2011-05-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,543 INFO sqlalchemy.engine.base.Engine ('2011-05-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,579 INFO sqlalchemy.engine.base.Engine ('2011-05-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,581 INFO sqlalchemy.engine.base.Engine ('2011-05-18 00:00:00.000000', 0.56, 68)
2018-05-08 18:31:36,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,582 INFO sqlalchemy.engine.base.Engine ('2011-05-19 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:36,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,584 INFO sqlalchemy.engine.base.Engine ('2011-05-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,585 INFO sqlalchemy.engine.base.Engine ('2011-05-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,587 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,588 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:36,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,590 INFO sqlalchemy.engine.base.Engine ('2011-05-26 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:36,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,592 INFO sqlalchemy.engine.base.Engine ('2011-05-27 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:36,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,593 INFO sqlalchemy.engine.base.Engine ('2011-05-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,594 INFO sqlalchemy.engine.base.Engine ('2011-06-01 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:36,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,596 INFO sqlalchemy.engine.base.Engine ('2011-06-02 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:36,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,598 INFO sqlalchemy.engine.base.Engine ('2011-06-03 00:00:00.000000', 1.75, 67)
2018-05-08 18:31:36,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,599 INFO sqlalchemy.engine.base.Engine ('2011-06-04 00:00:00.000000', 1.14, 69)
2018-05-08 18:31:36,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,601 INFO sqlalchemy.engine.base.Engine ('2011-06-05 00:00:00.000000', 3.6, 76)
2018-05-08 18:31:36,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,603 INFO sqlalchemy.engine.base.Engine ('2011-06-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,604 INFO sqlalchemy.engine.base.Engine ('2011-06-07 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:36,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,606 INFO sqlalchemy.engine.base.Engine ('2011-06-08 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:36,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,608 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,609 INFO sqlalchemy.engine.base.Engine ('2011-06-10 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:36,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,610 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:36,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,612 INFO sqlalchemy.engine.base.Engine ('2011-06-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,614 INFO sqlalchemy.engine.base.Engine ('2011-06-16 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:36,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,615 INFO sqlalchemy.engine.base.Engine ('2011-06-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,617 INFO sqlalchemy.engine.base.Engine ('2011-06-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,618 INFO sqlalchemy.engine.base.Engine ('2011-06-19 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:36,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,620 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:36,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,621 INFO sqlalchemy.engine.base.Engine ('2011-06-23 00:00:00.000000', 0.09, 70)
2018-05-08 18:31:36,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,623 INFO sqlalchemy.engine.base.Engine ('2011-06-24 00:00:00.000000', 0.17, 74)
2018-05-08 18:31:36,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,624 INFO sqlalchemy.engine.base.Engine ('2011-06-25 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:36,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,626 INFO sqlalchemy.engine.base.Engine ('2011-06-28 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:36,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,627 INFO sqlalchemy.engine.base.Engine ('2011-07-01 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:36,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,629 INFO sqlalchemy.engine.base.Engine ('2011-07-04 00:00:00.000000', 0.02, 76)

2018-05-08 18:31:36,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,631 INFO sqlalchemy.engine.base.Engine ('2011-07-05 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:36,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,632 INFO sqlalchemy.engine.base.Engine ('2011-07-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,634 INFO sqlalchemy.engine.base.Engine ('2011-07-07 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:36,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,636 INFO sqlalchemy.engine.base.Engine ('2011-07-08 00:00:00.000000', 0.15, 74)
2018-05-08 18:31:36,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,637 INFO sqlalchemy.engine.base.Engine ('2011-07-09 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:36,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,638 INFO sqlalchemy.engine.base.Engine ('2011-07-10 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:36,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,640 INFO sqlalchemy.engine.base.Engine ('2011-07-13 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:36,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,642 INFO sqlalchemy.engine.base.Engine ('2011-07-14 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:36,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,643 INFO sqlalchemy.engine.base.Engine ('2011-07-15 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:36,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,645 INFO sqlalchemy.engine.base.Engine ('2011-07-16 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:36,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,646 INFO sqlalchemy.engine.base.Engine ('2011-07-19 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:36,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,648 INFO sqlalchemy.engine.base.Engine ('2011-07-20 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:36,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,649 INFO sqlalchemy.engine.base.Engine ('2011-07-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,651 INFO sqlalchemy.engine.base.Engine ('2011-07-22 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:36,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,653 INFO sqlalchemy.engine.base.Engine ('2011-07-26 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:36,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,654 INFO sqlalchemy.engine.base.Engine ('2011-07-27 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:36,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,657 INFO sqlalchemy.engine.base.Engine ('2011-07-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,659 INFO sqlalchemy.engine.base.Engine ('2011-07-29 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:36,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,660 INFO sqlalchemy.engine.base.Engine ('2011-07-30 00:00:00.000000', 0.39, 76)
2018-05-08 18:31:36,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,662 INFO sqlalchemy.engine.base.Engine ('2011-08-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,663 INFO sqlalchemy.engine.base.Engine ('2011-08-02 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:36,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,665 INFO sqlalchemy.engine.base.Engine ('2011-08-03 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:36,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,666 INFO sqlalchemy.engine.base.Engine ('2011-08-04 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:36,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,668 INFO sqlalchemy.engine.base.Engine ('2011-08-05 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:36,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,669 INFO sqlalchemy.engine.base.Engine ('2011-08-07 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:36,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,671 INFO sqlalchemy.engine.base.Engine ('2011-08-16 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:36,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,672 INFO sqlalchemy.engine.base.Engine ('2011-08-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,674 INFO sqlalchemy.engine.base.Engine ('2011-08-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,675 INFO sqlalchemy.engine.base.Engine ('2011-08-26 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:36,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,677 INFO sqlalchemy.engine.base.Engine ('2011-08-27 00:00:00.000000', 0.12, 78)
2018-05-08 18:31:36,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,678 INFO sqlalchemy.engine.base.Engine ('2011-08-30 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:36,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,680 INFO sqlalchemy.engine.base.Engine ('2011-08-31 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:36,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,681 INFO sqlalchemy.engine.base.Engine ('2011-09-01 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:36,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,683 INFO sqlalchemy.engine.base.Engine ('2011-09-02 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:36,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,684 INFO sqlalchemy.engine.base.Engine ('2011-09-03 00:00:00.000000', 0.07, 76)

2018-05-08 18:31:36,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,686 INFO sqlalchemy.engine.base.Engine ('2011-09-04 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:36,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,688 INFO sqlalchemy.engine.base.Engine ('2011-09-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,689 INFO sqlalchemy.engine.base.Engine ('2011-09-10 00:00:00.000000', 0.23, 78)
2018-05-08 18:31:36,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,691 INFO sqlalchemy.engine.base.Engine ('2011-09-13 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:36,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,692 INFO sqlalchemy.engine.base.Engine ('2011-09-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,694 INFO sqlalchemy.engine.base.Engine ('2011-09-15 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:36,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,695 INFO sqlalchemy.engine.base.Engine ('2011-09-16 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:36,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,697 INFO sqlalchemy.engine.base.Engine ('2011-09-17 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:36,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,699 INFO sqlalchemy.engine.base.Engine ('2011-09-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:36,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,700 INFO sqlalchemy.engine.base.Engine ('2011-09-21 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:36,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,702 INFO sqlalchemy.engine.base.Engine ('2011-09-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:36,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,703 INFO sqlalchemy.engine.base.Engine ('2011-09-23 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:36,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,704 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,706 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:36,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,708 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:36,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,709 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,711 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:36,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,712 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.19, 77)
2018-05-08 18:31:36,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,714 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,716 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,717 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:36,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,719 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:36,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,721 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:36,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,723 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:36,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,724 INFO sqlalchemy.engine.base.Engine ('2011-10-08 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:36,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,726 INFO sqlalchemy.engine.base.Engine ('2011-10-11 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:36,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,728 INFO sqlalchemy.engine.base.Engine ('2011-10-12 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:36,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,729 INFO sqlalchemy.engine.base.Engine ('2011-10-13 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:36,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,731 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:36,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,732 INFO sqlalchemy.engine.base.Engine ('2011-10-15 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:36,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,734 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:36,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,736 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,781 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.54, 68)
2018-05-08 18:31:36,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,783 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:36,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,785 INFO sqlalchemy.engine.base.Engine ('2011-10-21 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:36,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,787 INFO sqlalchemy.engine.base.Engine ('2011-10-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:36,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,789 INFO sqlalchemy.engine.base.Engine ('2011-10-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,793 INFO sqlalchemy.engine.base.Engine ('2011-10-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,795 INFO sqlalchemy.engine.base.Engine ('2011-10-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,797 INFO sqlalchemy.engine.base.Engine ('2011-10-28 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:36,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,798 INFO sqlalchemy.engine.base.Engine ('2011-10-29 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:36,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,800 INFO sqlalchemy.engine.base.Engine ('2011-10-30 00:00:00.000000', 0.27, 75)
2018-05-08 18:31:36,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,802 INFO sqlalchemy.engine.base.Engine ('2011-10-31 00:00:00.000000', 0.39, 74)
2018-05-08 18:31:36,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,803 INFO sqlalchemy.engine.base.Engine ('2011-11-01 00:00:00.000000', 0.7, 74)
2018-05-08 18:31:36,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,804 INFO sqlalchemy.engine.base.Engine ('2011-11-02 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:36,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,806 INFO sqlalchemy.engine.base.Engine ('2011-11-03 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:36,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,809 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 0.4, 71)
2018-05-08 18:31:36,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,811 INFO sqlalchemy.engine.base.Engine ('2011-11-05 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:36,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,812 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:36,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,814 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:36,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,815 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:36,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,817 INFO sqlalchemy.engine.base.Engine ('2011-11-11 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:36,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,818 INFO sqlalchemy.engine.base.Engine ('2011-11-15 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,820 INFO sqlalchemy.engine.base.Engine ('2011-11-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:36,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,822 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,823 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.21, 72)
2018-05-08 18:31:36,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,826 INFO sqlalchemy.engine.base.Engine ('2011-11-19 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:36,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,828 INFO sqlalchemy.engine.base.Engine ('2011-11-22 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:36,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,829 INFO sqlalchemy.engine.base.Engine ('2011-11-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,831 INFO sqlalchemy.engine.base.Engine ('2011-11-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,832 INFO sqlalchemy.engine.base.Engine ('2011-11-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:36,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,834 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:36,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,836 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.14, 67)
2018-05-08 18:31:36,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,837 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:36,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,838 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.24, 68)
2018-05-08 18:31:36,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,840 INFO sqlalchemy.engine.base.Engine ('2011-12-03 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:36,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,842 INFO sqlalchemy.engine.base.Engine ('2011-12-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,844 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,846 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,847 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.04, 70)

2018-05-08 18:31:36,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,849 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,850 INFO sqlalchemy.engine.base.Engine ('2011-12-09 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:36,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,852 INFO sqlalchemy.engine.base.Engine ('2011-12-10 00:00:00.000000', 0.36, 72)
2018-05-08 18:31:36,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,853 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 0.47, 71)
2018-05-08 18:31:36,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,855 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:36,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,856 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:36,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,858 INFO sqlalchemy.engine.base.Engine ('2011-12-16 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:36,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,859 INFO sqlalchemy.engine.base.Engine ('2011-12-19 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:36,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,861 INFO sqlalchemy.engine.base.Engine ('2011-12-20 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:36,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,862 INFO sqlalchemy.engine.base.Engine ('2011-12-21 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:36,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,864 INFO sqlalchemy.engine.base.Engine ('2011-12-22 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:36,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,866 INFO sqlalchemy.engine.base.Engine ('2011-12-27 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:36,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,867 INFO sqlalchemy.engine.base.Engine ('2011-12-30 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:36,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,869 INFO sqlalchemy.engine.base.Engine ('2011-12-31 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:36,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,871 INFO sqlalchemy.engine.base.Engine ('2012-01-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,873 INFO sqlalchemy.engine.base.Engine ('2012-01-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:36,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,874 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,876 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,878 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,879 INFO sqlalchemy.engine.base.Engine ('2012-01-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,881 INFO sqlalchemy.engine.base.Engine ('2012-01-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,882 INFO sqlalchemy.engine.base.Engine ('2012-01-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:36,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,884 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,885 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:36,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,886 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:36,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,888 INFO sqlalchemy.engine.base.Engine ('2012-01-13 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:36,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,890 INFO sqlalchemy.engine.base.Engine ('2012-01-16 00:00:00.000000', 0.45, 73)
2018-05-08 18:31:36,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,892 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:36,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,893 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:36,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,896 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:36,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,897 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,899 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:36,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,900 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.23, 70)
2018-05-08 18:31:36,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,902 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:36,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,903 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.25, 63)

2018-05-08 18:31:36,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,905 INFO sqlalchemy.engine.base.Engine ('2012-01-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:36,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,906 INFO sqlalchemy.engine.base.Engine ('2012-01-30 00:00:00.000000', 0.08, 67)
2018-05-08 18:31:36,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,909 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:36,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,910 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:36,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,911 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:36,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,913 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:36,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:36,915 INFO sqlalchemy.engine.base.Engine ('2012-02-06 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:37,424 INFO sqlalchemy.engine.base.Engine ('2013-03-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,426 INFO sqlalchemy.engine.base.Engine ('2013-03-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,428 INFO sqlalchemy.engine.base.Engine ('2013-03-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:37,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,429 INFO sqlalchemy.engine.base.Engine ('2013-03-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,431 INFO sqlalchemy.engine.base.Engine ('2013-03-07 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:37,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,433 INFO sqlalchemy.engine.base.Engine ('2013-03-08 00:00:00.000000', 0.13, 67)
2018-05-08 18:31:37,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,435 INFO sqlalchemy.engine.base.Engine ('2013-03-11 00:00:00.000000', 0.27, 67)
2018-05-08 18:31:37,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,436 INFO sqlalchemy.engine.base.Engine ('2013-03-12 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:37,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,438 INFO sqlalchemy.engine.base.Engine ('2013-03-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,439 INFO sqlalchemy.engine.base.Engine ('2013-03-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:37,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,442 INFO sqlalchemy.engine.base.Engine ('2013-03-19 00:00:00.000000', 0.19, 70)
2018-05-08 18:31:37,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,445 INFO sqlalchemy.engine.base.Engine ('2013-03-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,447 INFO sqlalchemy.engine.base.Engine ('2013-03-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,449 INFO sqlalchemy.engine.base.Engine ('2013-03-28 00:00:00.000000', 0.28, 75)
2018-05-08 18:31:37,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,450 INFO sqlalchemy.engine.base.Engine ('2013-03-29 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:37,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,452 INFO sqlalchemy.engine.base.Engine ('2013-04-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:37,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,454 INFO sqlalchemy.engine.base.Engine ('2013-04-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,455 INFO sqlalchemy.engine.base.Engine ('2013-04-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,459 INFO sqlalchemy.engine.base.Engine ('2013-04-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,461 INFO sqlalchemy.engine.base.Engine ('2013-04-09 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:37,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,463 INFO sqlalchemy.engine.base.Engine ('2013-04-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,467 INFO sqlalchemy.engine.base.Engine ('2013-04-11 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:37,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,468 INFO sqlalchemy.engine.base.Engine ('2013-04-12 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:37,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,470 INFO sqlalchemy.engine.base.Engine ('2013-04-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,471 INFO sqlalchemy.engine.base.Engine ('2013-04-14 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:37,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,475 INFO sqlalchemy.engine.base.Engine ('2013-04-15 00:00:00.000000', 0.57, 75)
2018-05-08 18:31:37,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,478 INFO sqlalchemy.engine.base.Engine ('2013-04-16 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:37,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,480 INFO sqlalchemy.engine.base.Engine ('2013-04-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,481 INFO sqlalchemy.engine.base.Engine ('2013-04-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,483 INFO sqlalchemy.engine.base.Engine ('2013-04-19 00:00:00.000000', 0.22, 73)
2018-05-08 18:31:37,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,485 INFO sqlalchemy.engine.base.Engine ('2013-04-20 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:37,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,488 INFO sqlalchemy.engine.base.Engine ('2013-04-23 00:00:00.000000', 0.32, 77)
2018-05-08 18:31:37,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,491 INFO sqlalchemy.engine.base.Engine ('2013-04-24 00:00:00.000000', 1.52, 69)
2018-05-08 18:31:37,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,494 INFO sqlalchemy.engine.base.Engine ('2013-04-25 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:37,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,497 INFO sqlalchemy.engine.base.Engine ('2013-04-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,499 INFO sqlalchemy.engine.base.Engine ('2013-04-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,501 INFO sqlalchemy.engine.base.Engine ('2013-05-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,502 INFO sqlalchemy.engine.base.Engine ('2013-05-02 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:37,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,504 INFO sqlalchemy.engine.base.Engine ('2013-05-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,507 INFO sqlalchemy.engine.base.Engine ('2013-05-06 00:00:00.000000', 0.29, 73)
2018-05-08 18:31:37,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,510 INFO sqlalchemy.engine.base.Engine ('2013-05-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,511 INFO sqlalchemy.engine.base.Engine ('2013-05-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,513 INFO sqlalchemy.engine.base.Engine ('2013-05-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,515 INFO sqlalchemy.engine.base.Engine ('2013-05-10 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:37,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,516 INFO sqlalchemy.engine.base.Engine ('2013-05-13 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:37,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,518 INFO sqlalchemy.engine.base.Engine ('2013-05-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,519 INFO sqlalchemy.engine.base.Engine ('2013-05-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,521 INFO sqlalchemy.engine.base.Engine ('2013-05-16 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:37,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,524 INFO sqlalchemy.engine.base.Engine ('2013-05-17 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:37,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,526 INFO sqlalchemy.engine.base.Engine ('2013-05-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,529 INFO sqlalchemy.engine.base.Engine ('2013-05-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,531 INFO sqlalchemy.engine.base.Engine ('2013-05-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,532 INFO sqlalchemy.engine.base.Engine ('2013-05-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,534 INFO sqlalchemy.engine.base.Engine ('2013-05-25 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:37,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,536 INFO sqlalchemy.engine.base.Engine ('2013-05-28 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:37,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,537 INFO sqlalchemy.engine.base.Engine ('2013-05-29 00:00:00.000000', 0.63, 74)
2018-05-08 18:31:37,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,539 INFO sqlalchemy.engine.base.Engine ('2013-05-30 00:00:00.000000', 1.07, 77)
2018-05-08 18:31:37,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,542 INFO sqlalchemy.engine.base.Engine ('2013-05-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,543 INFO sqlalchemy.engine.base.Engine ('2013-06-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,545 INFO sqlalchemy.engine.base.Engine ('2013-06-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,546 INFO sqlalchemy.engine.base.Engine ('2013-06-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,548 INFO sqlalchemy.engine.base.Engine ('2013-06-07 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:37,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,550 INFO sqlalchemy.engine.base.Engine ('2013-06-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,551 INFO sqlalchemy.engine.base.Engine ('2013-06-09 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:37,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,553 INFO sqlalchemy.engine.base.Engine ('2013-06-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,555 INFO sqlalchemy.engine.base.Engine ('2013-06-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,556 INFO sqlalchemy.engine.base.Engine ('2013-06-12 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:37,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,558 INFO sqlalchemy.engine.base.Engine ('2013-06-13 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:37,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,560 INFO sqlalchemy.engine.base.Engine ('2013-06-14 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:37,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,561 INFO sqlalchemy.engine.base.Engine ('2013-06-17 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:37,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,563 INFO sqlalchemy.engine.base.Engine ('2013-06-18 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:37,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,565 INFO sqlalchemy.engine.base.Engine ('2013-06-19 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:37,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,566 INFO sqlalchemy.engine.base.Engine ('2013-06-20 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:37,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,568 INFO sqlalchemy.engine.base.Engine ('2013-06-26 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:37,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,569 INFO sqlalchemy.engine.base.Engine ('2013-06-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,571 INFO sqlalchemy.engine.base.Engine ('2013-07-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,573 INFO sqlalchemy.engine.base.Engine ('2013-07-02 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:37,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,574 INFO sqlalchemy.engine.base.Engine ('2013-07-03 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:37,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,576 INFO sqlalchemy.engine.base.Engine ('2013-07-04 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,578 INFO sqlalchemy.engine.base.Engine ('2013-07-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,579 INFO sqlalchemy.engine.base.Engine ('2013-07-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,581 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,581 INFO sqlalchemy.engine.base.Engine ('2013-07-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,583 INFO sqlalchemy.engine.base.Engine ('2013-07-10 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:37,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,585 INFO sqlalchemy.engine.base.Engine ('2013-07-11 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:37,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,586 INFO sqlalchemy.engine.base.Engine ('2013-07-12 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:37,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,588 INFO sqlalchemy.engine.base.Engine ('2013-07-13 00:00:00.000000', 0.15, 78)
2018-05-08 18:31:37,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,590 INFO sqlalchemy.engine.base.Engine ('2013-07-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:37,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,591 INFO sqlalchemy.engine.base.Engine ('2013-07-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,593 INFO sqlalchemy.engine.base.Engine ('2013-07-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,595 INFO sqlalchemy.engine.base.Engine ('2013-07-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,597 INFO sqlalchemy.engine.base.Engine ('2013-07-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,598 INFO sqlalchemy.engine.base.Engine ('2013-07-19 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:37,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,600 INFO sqlalchemy.engine.base.Engine ('2013-07-20 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:37,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,602 INFO sqlalchemy.engine.base.Engine ('2013-07-23 00:00:00.000000', 0.14, 76)
2018-05-08 18:31:37,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,603 INFO sqlalchemy.engine.base.Engine ('2013-07-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,605 INFO sqlalchemy.engine.base.Engine ('2013-07-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,606 INFO sqlalchemy.engine.base.Engine ('2013-07-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,608 INFO sqlalchemy.engine.base.Engine ('2013-07-27 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,610 INFO sqlalchemy.engine.base.Engine ('2013-07-30 00:00:00.000000', 0.11, 78)
2018-05-08 18:31:37,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,611 INFO sqlalchemy.engine.base.Engine ('2013-07-31 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:37,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,663 INFO sqlalchemy.engine.base.Engine ('2013-08-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,665 INFO sqlalchemy.engine.base.Engine ('2013-08-21 00:00:00.000000', 0.43, 77)
2018-05-08 18:31:37,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,667 INFO sqlalchemy.engine.base.Engine ('2013-08-22 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,668 INFO sqlalchemy.engine.base.Engine ('2013-08-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,670 INFO sqlalchemy.engine.base.Engine ('2013-08-26 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,671 INFO sqlalchemy.engine.base.Engine ('2013-08-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,673 INFO sqlalchemy.engine.base.Engine ('2013-08-28 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:37,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,675 INFO sqlalchemy.engine.base.Engine ('2013-08-29 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:37,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,676 INFO sqlalchemy.engine.base.Engine ('2013-08-30 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:37,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,678 INFO sqlalchemy.engine.base.Engine ('2013-08-31 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:37,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,680 INFO sqlalchemy.engine.base.Engine ('2013-09-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,682 INFO sqlalchemy.engine.base.Engine ('2013-09-04 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:37,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,683 INFO sqlalchemy.engine.base.Engine ('2013-09-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,685 INFO sqlalchemy.engine.base.Engine ('2013-09-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,686 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,686 INFO sqlalchemy.engine.base.Engine ('2013-09-07 00:00:00.000000', 0.36, 81)
2018-05-08 18:31:37,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,688 INFO sqlalchemy.engine.base.Engine ('2013-09-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,690 INFO sqlalchemy.engine.base.Engine ('2013-09-11 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:37,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,692 INFO sqlalchemy.engine.base.Engine ('2013-09-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,693 INFO sqlalchemy.engine.base.Engine ('2013-09-13 00:00:00.000000', 0.85, 74)
2018-05-08 18:31:37,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,695 INFO sqlalchemy.engine.base.Engine ('2013-09-14 00:00:00.000000', 0.02, 82)
2018-05-08 18:31:37,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,696 INFO sqlalchemy.engine.base.Engine ('2013-09-17 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:37,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,698 INFO sqlalchemy.engine.base.Engine ('2013-09-18 00:00:00.000000', 0.03, 80)
2018-05-08 18:31:37,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,700 INFO sqlalchemy.engine.base.Engine ('2013-09-19 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,701 INFO sqlalchemy.engine.base.Engine ('2013-09-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,703 INFO sqlalchemy.engine.base.Engine ('2013-09-23 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:37,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,704 INFO sqlalchemy.engine.base.Engine ('2013-09-24 00:00:00.000000', 0.17, 78)
2018-05-08 18:31:37,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,706 INFO sqlalchemy.engine.base.Engine ('2013-09-25 00:00:00.000000', 0.12, 78)
2018-05-08 18:31:37,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,708 INFO sqlalchemy.engine.base.Engine ('2013-09-26 00:00:00.000000', 0.19, 77)
2018-05-08 18:31:37,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,709 INFO sqlalchemy.engine.base.Engine ('2013-09-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,711 INFO sqlalchemy.engine.base.Engine ('2013-09-28 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:37,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,712 INFO sqlalchemy.engine.base.Engine ('2013-10-01 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:37,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,714 INFO sqlalchemy.engine.base.Engine ('2013-10-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:37,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,716 INFO sqlalchemy.engine.base.Engine ('2013-10-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,718 INFO sqlalchemy.engine.base.Engine ('2013-10-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,719 INFO sqlalchemy.engine.base.Engine ('2013-10-07 00:00:00.000000', 0.24, 78)
2018-05-08 18:31:37,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,721 INFO sqlalchemy.engine.base.Engine ('2013-10-08 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:37,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,723 INFO sqlalchemy.engine.base.Engine ('2013-10-09 00:00:00.000000', 0.31, 76)
2018-05-08 18:31:37,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,724 INFO sqlalchemy.engine.base.Engine ('2013-10-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,726 INFO sqlalchemy.engine.base.Engine ('2013-10-11 00:00:00.000000', 1.95, 77)
2018-05-08 18:31:37,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,728 INFO sqlalchemy.engine.base.Engine ('2013-10-15 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:37,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,730 INFO sqlalchemy.engine.base.Engine ('2013-10-16 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:37,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,732 INFO sqlalchemy.engine.base.Engine ('2013-10-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,733 INFO sqlalchemy.engine.base.Engine ('2013-10-18 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:37,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,735 INFO sqlalchemy.engine.base.Engine ('2013-10-19 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:37,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,737 INFO sqlalchemy.engine.base.Engine ('2013-10-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,738 INFO sqlalchemy.engine.base.Engine ('2013-10-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,740 INFO sqlalchemy.engine.base.Engine ('2013-10-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,742 INFO sqlalchemy.engine.base.Engine ('2013-10-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,744 INFO sqlalchemy.engine.base.Engine ('2013-10-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,745 INFO sqlalchemy.engine.base.Engine ('2013-10-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,747 INFO sqlalchemy.engine.base.Engine ('2013-10-26 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:37,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,749 INFO sqlalchemy.engine.base.Engine ('2013-10-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,750 INFO sqlalchemy.engine.base.Engine ('2013-10-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,752 INFO sqlalchemy.engine.base.Engine ('2013-10-31 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:37,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,754 INFO sqlalchemy.engine.base.Engine ('2013-11-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,756 INFO sqlalchemy.engine.base.Engine ('2013-11-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,757 INFO sqlalchemy.engine.base.Engine ('2013-11-06 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:37,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,759 INFO sqlalchemy.engine.base.Engine ('2013-11-07 00:00:00.000000', 0.62, 74)
2018-05-08 18:31:37,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,761 INFO sqlalchemy.engine.base.Engine ('2013-11-08 00:00:00.000000', 1.55, 74)
2018-05-08 18:31:37,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,762 INFO sqlalchemy.engine.base.Engine ('2013-11-09 00:00:00.000000', 0.87, 73)
2018-05-08 18:31:37,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,764 INFO sqlalchemy.engine.base.Engine ('2013-11-10 00:00:00.000000', 2.77, 77)
2018-05-08 18:31:37,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,765 INFO sqlalchemy.engine.base.Engine ('2013-11-11 00:00:00.000000', 0.32, 74)
2018-05-08 18:31:37,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,767 INFO sqlalchemy.engine.base.Engine ('2013-11-12 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:37,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,768 INFO sqlalchemy.engine.base.Engine ('2013-11-13 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:37,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,770 INFO sqlalchemy.engine.base.Engine ('2013-11-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,772 INFO sqlalchemy.engine.base.Engine ('2013-11-15 00:00:00.000000', 0.47, 75)
2018-05-08 18:31:37,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,773 INFO sqlalchemy.engine.base.Engine ('2013-11-16 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:37,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,775 INFO sqlalchemy.engine.base.Engine ('2013-11-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,776 INFO sqlalchemy.engine.base.Engine ('2013-11-18 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:37,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,778 INFO sqlalchemy.engine.base.Engine ('2013-11-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,780 INFO sqlalchemy.engine.base.Engine ('2013-11-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,781 INFO sqlalchemy.engine.base.Engine ('2013-11-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,783 INFO sqlalchemy.engine.base.Engine ('2013-11-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,784 INFO sqlalchemy.engine.base.Engine ('2013-11-23 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:37,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,786 INFO sqlalchemy.engine.base.Engine ('2013-11-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,787 INFO sqlalchemy.engine.base.Engine ('2013-11-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,789 INFO sqlalchemy.engine.base.Engine ('2013-11-30 00:00:00.000000', 0.26, 79)
2018-05-08 18:31:37,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,791 INFO sqlalchemy.engine.base.Engine ('2013-12-03 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:37,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,793 INFO sqlalchemy.engine.base.Engine ('2013-12-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,794 INFO sqlalchemy.engine.base.Engine ('2013-12-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,796 INFO sqlalchemy.engine.base.Engine ('2013-12-06 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:37,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,797 INFO sqlalchemy.engine.base.Engine ('2013-12-07 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:37,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,799 INFO sqlalchemy.engine.base.Engine ('2013-12-08 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,800 INFO sqlalchemy.engine.base.Engine ('2013-12-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:37,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,801 INFO sqlalchemy.engine.base.Engine ('2013-12-10 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:37,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,803 INFO sqlalchemy.engine.base.Engine ('2013-12-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,805 INFO sqlalchemy.engine.base.Engine ('2013-12-12 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,806 INFO sqlalchemy.engine.base.Engine ('2013-12-13 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:37,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,808 INFO sqlalchemy.engine.base.Engine ('2013-12-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:37,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,809 INFO sqlalchemy.engine.base.Engine ('2013-12-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,811 INFO sqlalchemy.engine.base.Engine ('2013-12-18 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:37,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,812 INFO sqlalchemy.engine.base.Engine ('2013-12-19 00:00:00.000000', 0.52, 71)
2018-05-08 18:31:37,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,814 INFO sqlalchemy.engine.base.Engine ('2013-12-20 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:37,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,815 INFO sqlalchemy.engine.base.Engine ('2013-12-21 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:37,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,817 INFO sqlalchemy.engine.base.Engine ('2013-12-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,819 INFO sqlalchemy.engine.base.Engine ('2013-12-27 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:37,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,820 INFO sqlalchemy.engine.base.Engine ('2013-12-28 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:37,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,822 INFO sqlalchemy.engine.base.Engine ('2013-12-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,824 INFO sqlalchemy.engine.base.Engine ('2013-12-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,825 INFO sqlalchemy.engine.base.Engine ('2013-12-31 00:00:00.000000', 0.23, 75)
2018-05-08 18:31:37,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,875 INFO sqlalchemy.engine.base.Engine ('2014-01-03 00:00:00.000000', 0.35, 71)
2018-05-08 18:31:37,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,876 INFO sqlalchemy.engine.base.Engine ('2014-01-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,878 INFO sqlalchemy.engine.base.Engine ('2014-01-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,879 INFO sqlalchemy.engine.base.Engine ('2014-01-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,881 INFO sqlalchemy.engine.base.Engine ('2014-01-09 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:37,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,883 INFO sqlalchemy.engine.base.Engine ('2014-01-10 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:37,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,884 INFO sqlalchemy.engine.base.Engine ('2014-01-11 00:00:00.000000', 0.62, 75)
2018-05-08 18:31:37,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,886 INFO sqlalchemy.engine.base.Engine ('2014-01-14 00:00:00.000000', 0.59, 74)
2018-05-08 18:31:37,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,889 INFO sqlalchemy.engine.base.Engine ('2014-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,890 INFO sqlalchemy.engine.base.Engine ('2014-01-16 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:37,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,892 INFO sqlalchemy.engine.base.Engine ('2014-01-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,893 INFO sqlalchemy.engine.base.Engine ('2014-01-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,895 INFO sqlalchemy.engine.base.Engine ('2014-01-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,896 INFO sqlalchemy.engine.base.Engine ('2014-01-24 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:37,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,898 INFO sqlalchemy.engine.base.Engine ('2014-01-28 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:37,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,900 INFO sqlalchemy.engine.base.Engine ('2014-01-29 00:00:00.000000', 0.24, 69)
2018-05-08 18:31:37,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,902 INFO sqlalchemy.engine.base.Engine ('2014-01-30 00:00:00.000000', 0.19, 70)
2018-05-08 18:31:37,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,904 INFO sqlalchemy.engine.base.Engine ('2014-01-31 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,906 INFO sqlalchemy.engine.base.Engine ('2014-02-04 00:00:00.000000', 1.12, 65)
2018-05-08 18:31:37,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,908 INFO sqlalchemy.engine.base.Engine ('2014-02-05 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:37,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,910 INFO sqlalchemy.engine.base.Engine ('2014-02-06 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:37,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,911 INFO sqlalchemy.engine.base.Engine ('2014-02-07 00:00:00.000000', 0.25, 70)
2018-05-08 18:31:37,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,913 INFO sqlalchemy.engine.base.Engine ('2014-02-11 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:37,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,914 INFO sqlalchemy.engine.base.Engine ('2014-02-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,916 INFO sqlalchemy.engine.base.Engine ('2014-02-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,918 INFO sqlalchemy.engine.base.Engine ('2014-02-14 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:37,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,919 INFO sqlalchemy.engine.base.Engine ('2014-02-15 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:37,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,921 INFO sqlalchemy.engine.base.Engine ('2014-02-18 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:37,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,923 INFO sqlalchemy.engine.base.Engine ('2014-02-19 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:37,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,925 INFO sqlalchemy.engine.base.Engine ('2014-02-26 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:37,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,927 INFO sqlalchemy.engine.base.Engine ('2014-02-27 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:37,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,928 INFO sqlalchemy.engine.base.Engine ('2014-02-28 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:37,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,930 INFO sqlalchemy.engine.base.Engine ('2014-03-01 00:00:00.000000', 0.23, 76)
2018-05-08 18:31:37,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,931 INFO sqlalchemy.engine.base.Engine ('2014-03-02 00:00:00.000000', 0.23, 67)
2018-05-08 18:31:37,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,933 INFO sqlalchemy.engine.base.Engine ('2014-03-03 00:00:00.000000', 0.16, 72)
2018-05-08 18:31:37,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,935 INFO sqlalchemy.engine.base.Engine ('2014-03-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,936 INFO sqlalchemy.engine.base.Engine ('2014-03-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:37,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,938 INFO sqlalchemy.engine.base.Engine ('2014-03-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,940 INFO sqlalchemy.engine.base.Engine ('2014-03-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,942 INFO sqlalchemy.engine.base.Engine ('2014-03-08 00:00:00.000000', 0.42, 69)
2018-05-08 18:31:37,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,943 INFO sqlalchemy.engine.base.Engine ('2014-03-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,945 INFO sqlalchemy.engine.base.Engine ('2014-03-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,946 INFO sqlalchemy.engine.base.Engine ('2014-03-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,948 INFO sqlalchemy.engine.base.Engine ('2014-03-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,950 INFO sqlalchemy.engine.base.Engine ('2014-03-17 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:37,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,951 INFO sqlalchemy.engine.base.Engine ('2014-03-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:37,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,953 INFO sqlalchemy.engine.base.Engine ('2014-03-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,954 INFO sqlalchemy.engine.base.Engine ('2014-03-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,956 INFO sqlalchemy.engine.base.Engine ('2014-03-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,958 INFO sqlalchemy.engine.base.Engine ('2014-03-31 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:37,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,959 INFO sqlalchemy.engine.base.Engine ('2014-04-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:37,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,961 INFO sqlalchemy.engine.base.Engine ('2014-04-02 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:37,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,963 INFO sqlalchemy.engine.base.Engine ('2014-04-03 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:37,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,964 INFO sqlalchemy.engine.base.Engine ('2014-04-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,966 INFO sqlalchemy.engine.base.Engine ('2014-04-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,968 INFO sqlalchemy.engine.base.Engine ('2014-04-06 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:37,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,970 INFO sqlalchemy.engine.base.Engine ('2014-04-07 00:00:00.000000', 0.31, 70)
2018-05-08 18:31:37,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,972 INFO sqlalchemy.engine.base.Engine ('2014-04-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,974 INFO sqlalchemy.engine.base.Engine ('2014-04-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,975 INFO sqlalchemy.engine.base.Engine ('2014-04-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:37,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,977 INFO sqlalchemy.engine.base.Engine ('2014-04-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,979 INFO sqlalchemy.engine.base.Engine ('2014-04-12 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:37,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,981 INFO sqlalchemy.engine.base.Engine ('2014-04-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,982 INFO sqlalchemy.engine.base.Engine ('2014-04-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,984 INFO sqlalchemy.engine.base.Engine ('2014-04-15 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:37,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,985 INFO sqlalchemy.engine.base.Engine ('2014-04-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:37,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,987 INFO sqlalchemy.engine.base.Engine ('2014-04-17 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:37,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,989 INFO sqlalchemy.engine.base.Engine ('2014-04-18 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:37,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,990 INFO sqlalchemy.engine.base.Engine ('2014-04-21 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:37,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,992 INFO sqlalchemy.engine.base.Engine ('2014-04-22 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:37,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,994 INFO sqlalchemy.engine.base.Engine ('2014-04-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:37,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,995 INFO sqlalchemy.engine.base.Engine ('2014-04-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:37,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:37,997 INFO sqlalchemy.engine.base.Engine ('2014-04-25 00:00:00.000000', 0.25, 76)
2018-05-08 18:31:37,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:37,998 INFO sqlalchemy.engine.base.Engine ('2014-04-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:37,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,000 INFO sqlalchemy.engine.base.Engine ('2014-04-30 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:38,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,001 INFO sqlalchemy.engine.base.Engine ('2014-05-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:38,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,003 INFO sqlalchemy.engine.base.Engine ('2014-05-02 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:38,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,004 INFO sqlalchemy.engine.base.Engine ('2014-05-03 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:38,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,006 INFO sqlalchemy.engine.base.Engine ('2014-05-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,008 INFO sqlalchemy.engine.base.Engine ('2014-05-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,009 INFO sqlalchemy.engine.base.Engine ('2014-05-06 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:38,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,011 INFO sqlalchemy.engine.base.Engine ('2014-05-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,012 INFO sqlalchemy.engine.base.Engine ('2014-05-08 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:38,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,014 INFO sqlalchemy.engine.base.Engine ('2014-05-09 00:00:00.000000', 0.22, 78)
2018-05-08 18:31:38,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,015 INFO sqlalchemy.engine.base.Engine ('2014-05-13 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:38,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,017 INFO sqlalchemy.engine.base.Engine ('2014-05-14 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:38,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,018 INFO sqlalchemy.engine.base.Engine ('2014-05-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,020 INFO sqlalchemy.engine.base.Engine ('2014-05-16 00:00:00.000000', 0.37, 75)
2018-05-08 18:31:38,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,022 INFO sqlalchemy.engine.base.Engine ('2014-05-17 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:38,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,024 INFO sqlalchemy.engine.base.Engine ('2014-05-20 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:38,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,025 INFO sqlalchemy.engine.base.Engine ('2014-05-21 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,027 INFO sqlalchemy.engine.base.Engine ('2014-05-22 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:38,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,029 INFO sqlalchemy.engine.base.Engine ('2014-05-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,031 INFO sqlalchemy.engine.base.Engine ('2014-05-27 00:00:00.000000', 0.9, 77)
2018-05-08 18:31:38,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,033 INFO sqlalchemy.engine.base.Engine ('2014-05-28 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:38,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,034 INFO sqlalchemy.engine.base.Engine ('2014-05-29 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:38,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,036 INFO sqlalchemy.engine.base.Engine ('2014-05-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,038 INFO sqlalchemy.engine.base.Engine ('2014-06-02 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:38,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,040 INFO sqlalchemy.engine.base.Engine ('2014-06-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,041 INFO sqlalchemy.engine.base.Engine ('2014-06-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,084 INFO sqlalchemy.engine.base.Engine ('2014-06-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,086 INFO sqlalchemy.engine.base.Engine ('2014-06-06 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:38,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,087 INFO sqlalchemy.engine.base.Engine ('2014-06-07 00:00:00.000000', 0.04, 79)
2018-05-08 18:31:38,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,089 INFO sqlalchemy.engine.base.Engine ('2014-06-10 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:38,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,091 INFO sqlalchemy.engine.base.Engine ('2014-06-11 00:00:00.000000', 0.17, 76)
2018-05-08 18:31:38,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,093 INFO sqlalchemy.engine.base.Engine ('2014-06-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,095 INFO sqlalchemy.engine.base.Engine ('2014-06-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,096 INFO sqlalchemy.engine.base.Engine ('2014-06-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:38,098 INFO sqlalchemy.engine.base.Engine ('2014-06-17 00:00:00.000000', 0.39, 75)
2018-05-08 18:31:38,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,100 INFO sqlalchemy.engine.base.Engine ('2014-06-18 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:38,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,101 INFO sqlalchemy.engine.base.Engine ('2014-06-19 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:38,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,103 INFO sqlalchemy.engine.base.Engine ('2014-06-20 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:38,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,105 INFO sqlalchemy.engine.base.Engine ('2014-06-21 00:00:00.000000', 0.11, 78)
2018-05-08 18:31:38,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,107 INFO sqlalchemy.engine.base.Engine ('2014-06-24 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:38,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,108 INFO sqlalchemy.engine.base.Engine ('2014-06-25 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:38,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,110 INFO sqlalchemy.engine.base.Engine ('2014-06-26 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:38,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,112 INFO sqlalchemy.engine.base.Engine ('2014-06-27 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:38,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,114 INFO sqlalchemy.engine.base.Engine ('2014-06-30 00:00:00.000000', 0.04, 79)
2018-05-08 18:31:38,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,115 INFO sqlalchemy.engine.base.Engine ('2014-07-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,117 INFO sqlalchemy.engine.base.Engine ('2014-07-02 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:38,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,119 INFO sqlalchemy.engine.base.Engine ('2014-07-03 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:38,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,121 INFO sqlalchemy.engine.base.Engine ('2014-07-04 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:38,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,122 INFO sqlalchemy.engine.base.Engine ('2014-07-05 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:38,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,124 INFO sqlalchemy.engine.base.Engine ('2014-07-06 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:38,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,126 INFO sqlalchemy.engine.base.Engine ('2014-07-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,128 INFO sqlalchemy.engine.base.Engine ('2014-07-08 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:38,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,129 INFO sqlalchemy.engine.base.Engine ('2014-07-09 00:00:00.000000', 0.09, 78)
2018-05-08 18:31:38,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,131 INFO sqlalchemy.engine.base.Engine ('2014-07-10 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:38,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,133 INFO sqlalchemy.engine.base.Engine ('2014-07-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,135 INFO sqlalchemy.engine.base.Engine ('2014-07-12 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:38,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,137 INFO sqlalchemy.engine.base.Engine ('2014-07-13 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:38,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,139 INFO sqlalchemy.engine.base.Engine ('2014-07-14 00:00:00.000000', 0.15, 78)
2018-05-08 18:31:38,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,140 INFO sqlalchemy.engine.base.Engine ('2014-07-15 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:38,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,142 INFO sqlalchemy.engine.base.Engine ('2014-07-16 00:00:00.000000', 0.32, 78)
2018-05-08 18:31:38,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,144 INFO sqlalchemy.engine.base.Engine ('2014-07-17 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:38,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,145 INFO sqlalchemy.engine.base.Engine ('2014-07-18 00:00:00.000000', 0.09, 79)
2018-05-08 18:31:38,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,147 INFO sqlalchemy.engine.base.Engine ('2014-07-19 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,148 INFO sqlalchemy.engine.base.Engine ('2014-07-20 00:00:00.000000', 11.53, 76)
2018-05-08 18:31:38,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,150 INFO sqlalchemy.engine.base.Engine ('2014-07-21 00:00:00.000000', 0.57, 78)
2018-05-08 18:31:38,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,152 INFO sqlalchemy.engine.base.Engine ('2014-07-22 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:38,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,154 INFO sqlalchemy.engine.base.Engine ('2014-07-23 00:00:00.000000', 0.26, 77)
2018-05-08 18:31:38,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,156 INFO sqlalchemy.engine.base.Engine ('2014-07-24 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:38,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,158 INFO sqlalchemy.engine.base.Engine ('2014-07-25 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:38,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:38,159 INFO sqlalchemy.engine.base.Engine ('2014-07-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,161 INFO sqlalchemy.engine.base.Engine ('2014-07-29 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,162 INFO sqlalchemy.engine.base.Engine ('2014-07-30 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,164 INFO sqlalchemy.engine.base.Engine ('2014-07-31 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,165 INFO sqlalchemy.engine.base.Engine ('2014-08-01 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,167 INFO sqlalchemy.engine.base.Engine ('2014-08-02 00:00:00.000000', 0.09, 78)
2018-05-08 18:31:38,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,168 INFO sqlalchemy.engine.base.Engine ('2014-08-05 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,170 INFO sqlalchemy.engine.base.Engine ('2014-08-06 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:38,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,172 INFO sqlalchemy.engine.base.Engine ('2014-08-07 00:00:00.000000', 0.29, 79)
2018-05-08 18:31:38,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,174 INFO sqlalchemy.engine.base.Engine ('2014-08-08 00:00:00.000000', 0.56, 76)
2018-05-08 18:31:38,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,176 INFO sqlalchemy.engine.base.Engine ('2014-08-09 00:00:00.000000', 0.72, 79)
2018-05-08 18:31:38,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,178 INFO sqlalchemy.engine.base.Engine ('2014-08-12 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:38,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,180 INFO sqlalchemy.engine.base.Engine ('2014-08-13 00:00:00.000000', 0.1, 79)
2018-05-08 18:31:38,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,182 INFO sqlalchemy.engine.base.Engine ('2014-08-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,183 INFO sqlalchemy.engine.base.Engine ('2014-08-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,185 INFO sqlalchemy.engine.base.Engine ('2014-08-18 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,187 INFO sqlalchemy.engine.base.Engine ('2014-08-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,188 INFO sqlalchemy.engine.base.Engine ('2014-08-20 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:38,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,190 INFO sqlalchemy.engine.base.Engine ('2014-08-21 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,192 INFO sqlalchemy.engine.base.Engine ('2014-08-22 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:38,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,195 INFO sqlalchemy.engine.base.Engine ('2014-08-25 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,196 INFO sqlalchemy.engine.base.Engine ('2014-08-26 00:00:00.000000', 0.19, 80)
2018-05-08 18:31:38,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,198 INFO sqlalchemy.engine.base.Engine ('2014-08-27 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:38,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,200 INFO sqlalchemy.engine.base.Engine ('2014-08-28 00:00:00.000000', 0.09, 80)
2018-05-08 18:31:38,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,202 INFO sqlalchemy.engine.base.Engine ('2014-08-29 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:38,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,203 INFO sqlalchemy.engine.base.Engine ('2014-08-30 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:38,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,205 INFO sqlalchemy.engine.base.Engine ('2014-09-02 00:00:00.000000', 0.47, 80)
2018-05-08 18:31:38,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,206 INFO sqlalchemy.engine.base.Engine ('2014-09-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,208 INFO sqlalchemy.engine.base.Engine ('2014-09-04 00:00:00.000000', 0.01, 82)
2018-05-08 18:31:38,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,210 INFO sqlalchemy.engine.base.Engine ('2014-09-05 00:00:00.000000', 0.09, 79)
2018-05-08 18:31:38,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,211 INFO sqlalchemy.engine.base.Engine ('2014-09-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,213 INFO sqlalchemy.engine.base.Engine ('2014-09-09 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,215 INFO sqlalchemy.engine.base.Engine ('2014-09-10 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:38,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,216 INFO sqlalchemy.engine.base.Engine ('2014-09-11 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,218 INFO sqlalchemy.engine.base.Engine ('2014-09-12 00:00:00.000000', 0.3, 80)
2018-05-08 18:31:38,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:38,219 INFO sqlalchemy.engine.base.Engine ('2014-09-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:38,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,221 INFO sqlalchemy.engine.base.Engine ('2014-09-17 00:00:00.000000', 0.09, 80)
2018-05-08 18:31:38,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,223 INFO sqlalchemy.engine.base.Engine ('2014-10-03 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:38,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,225 INFO sqlalchemy.engine.base.Engine ('2014-10-04 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:38,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,227 INFO sqlalchemy.engine.base.Engine ('2014-10-07 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:38,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,228 INFO sqlalchemy.engine.base.Engine ('2014-10-08 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,230 INFO sqlalchemy.engine.base.Engine ('2014-10-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,232 INFO sqlalchemy.engine.base.Engine ('2014-10-10 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:38,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,233 INFO sqlalchemy.engine.base.Engine ('2014-10-11 00:00:00.000000', 0.13, 80)
2018-05-08 18:31:38,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,235 INFO sqlalchemy.engine.base.Engine ('2014-10-12 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:38,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,237 INFO sqlalchemy.engine.base.Engine ('2014-10-13 00:00:00.000000', 0.11, 81)
2018-05-08 18:31:38,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,238 INFO sqlalchemy.engine.base.Engine ('2014-10-14 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:38,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,240 INFO sqlalchemy.engine.base.Engine ('2014-10-15 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:38,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,242 INFO sqlalchemy.engine.base.Engine ('2014-10-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:38,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,243 INFO sqlalchemy.engine.base.Engine ('2014-10-17 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:38,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,245 INFO sqlalchemy.engine.base.Engine ('2014-10-18 00:00:00.000000', 0.12, 81)
2018-05-08 18:31:38,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,248 INFO sqlalchemy.engine.base.Engine ('2014-10-19 00:00:00.000000', 3.48, 76)
2018-05-08 18:31:38,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,250 INFO sqlalchemy.engine.base.Engine ('2014-10-20 00:00:00.000000', 1.0, 80)
2018-05-08 18:31:38,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,252 INFO sqlalchemy.engine.base.Engine ('2014-10-23 00:00:00.000000', 0.16, 81)
2018-05-08 18:31:38,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,254 INFO sqlalchemy.engine.base.Engine ('2014-10-24 00:00:00.000000', 0.12, 79)
2018-05-08 18:31:38,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,255 INFO sqlalchemy.engine.base.Engine ('2014-10-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,257 INFO sqlalchemy.engine.base.Engine ('2014-10-28 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:38,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,301 INFO sqlalchemy.engine.base.Engine ('2014-10-29 00:00:00.000000', 0.18, 75)
2018-05-08 18:31:38,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,302 INFO sqlalchemy.engine.base.Engine ('2014-10-30 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:38,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,304 INFO sqlalchemy.engine.base.Engine ('2014-10-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,306 INFO sqlalchemy.engine.base.Engine ('2014-11-01 00:00:00.000000', 0.4, 81)
2018-05-08 18:31:38,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,308 INFO sqlalchemy.engine.base.Engine ('2014-11-02 00:00:00.000000', 0.13, 80)
2018-05-08 18:31:38,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,310 INFO sqlalchemy.engine.base.Engine ('2014-11-03 00:00:00.000000', 0.1, 79)
2018-05-08 18:31:38,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,312 INFO sqlalchemy.engine.base.Engine ('2014-11-04 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:38,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,314 INFO sqlalchemy.engine.base.Engine ('2014-11-05 00:00:00.000000', 0.43, 74)
2018-05-08 18:31:38,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,316 INFO sqlalchemy.engine.base.Engine ('2014-11-08 00:00:00.000000', 0.3, 75)
2018-05-08 18:31:38,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,317 INFO sqlalchemy.engine.base.Engine ('2014-11-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,319 INFO sqlalchemy.engine.base.Engine ('2014-11-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,321 INFO sqlalchemy.engine.base.Engine ('2014-11-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,323 INFO sqlalchemy.engine.base.Engine ('2014-11-12 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:38,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:38,325 INFO sqlalchemy.engine.base.Engine ('2014-11-15 00:00:00.000000', 0.21, 75)
2018-05-08 18:31:38,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,327 INFO sqlalchemy.engine.base.Engine ('2014-11-16 00:00:00.000000', 0.72, 76)
2018-05-08 18:31:38,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,329 INFO sqlalchemy.engine.base.Engine ('2014-11-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,331 INFO sqlalchemy.engine.base.Engine ('2014-11-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,332 INFO sqlalchemy.engine.base.Engine ('2014-11-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,334 INFO sqlalchemy.engine.base.Engine ('2014-11-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,336 INFO sqlalchemy.engine.base.Engine ('2014-11-21 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:38,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,338 INFO sqlalchemy.engine.base.Engine ('2014-11-22 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,340 INFO sqlalchemy.engine.base.Engine ('2014-11-23 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:38,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,342 INFO sqlalchemy.engine.base.Engine ('2014-11-24 00:00:00.000000', 0.34, 72)
2018-05-08 18:31:38,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,343 INFO sqlalchemy.engine.base.Engine ('2014-11-25 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:38,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,345 INFO sqlalchemy.engine.base.Engine ('2014-11-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:38,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,347 INFO sqlalchemy.engine.base.Engine ('2014-11-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,348 INFO sqlalchemy.engine.base.Engine ('2014-11-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,350 INFO sqlalchemy.engine.base.Engine ('2014-11-29 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:38,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,352 INFO sqlalchemy.engine.base.Engine ('2014-11-30 00:00:00.000000', 0.24, 78)
2018-05-08 18:31:38,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,354 INFO sqlalchemy.engine.base.Engine ('2014-12-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:38,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,356 INFO sqlalchemy.engine.base.Engine ('2014-12-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:38,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,357 INFO sqlalchemy.engine.base.Engine ('2014-12-03 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:38,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,360 INFO sqlalchemy.engine.base.Engine ('2014-12-04 00:00:00.000000', 1.51, 73)
2018-05-08 18:31:38,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,361 INFO sqlalchemy.engine.base.Engine ('2014-12-05 00:00:00.000000', 0.26, 70)
2018-05-08 18:31:38,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,363 INFO sqlalchemy.engine.base.Engine ('2014-12-06 00:00:00.000000', 0.48, 76)
2018-05-08 18:31:38,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,365 INFO sqlalchemy.engine.base.Engine ('2014-12-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,367 INFO sqlalchemy.engine.base.Engine ('2014-12-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,368 INFO sqlalchemy.engine.base.Engine ('2014-12-11 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:38,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,370 INFO sqlalchemy.engine.base.Engine ('2014-12-12 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:38,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,372 INFO sqlalchemy.engine.base.Engine ('2014-12-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,374 INFO sqlalchemy.engine.base.Engine ('2014-12-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:38,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,376 INFO sqlalchemy.engine.base.Engine ('2014-12-17 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:38,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,378 INFO sqlalchemy.engine.base.Engine ('2014-12-18 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:38,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,379 INFO sqlalchemy.engine.base.Engine ('2014-12-19 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:38,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,381 INFO sqlalchemy.engine.base.Engine ('2014-12-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:38,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,382 INFO sqlalchemy.engine.base.Engine ('2014-12-23 00:00:00.000000', 0.58, 73)
2018-05-08 18:31:38,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,384 INFO sqlalchemy.engine.base.Engine ('2015-01-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:38,385 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,386 INFO sqlalchemy.engine.base.Engine ('2015-01-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:38,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:38,388 INFO sqlalchemy.engine.base.Engine ('2015-01-03 00:00:00.000000', 0.68, 72)
2018-05-08 18:31:38,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,390 INFO sqlalchemy.engine.base.Engine ('2015-01-04 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:38,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,392 INFO sqlalchemy.engine.base.Engine ('2015-01-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:38,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,393 INFO sqlalchemy.engine.base.Engine ('2015-01-06 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:38,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,395 INFO sqlalchemy.engine.base.Engine ('2015-01-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:38,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,397 INFO sqlalchemy.engine.base.Engine ('2015-01-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:38,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,399 INFO sqlalchemy.engine.base.Engine ('2015-01-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,400 INFO sqlalchemy.engine.base.Engine ('2015-01-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:38,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,402 INFO sqlalchemy.engine.base.Engine ('2015-01-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:38,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,404 INFO sqlalchemy.engine.base.Engine ('2015-01-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:38,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,406 INFO sqlalchemy.engine.base.Engine ('2015-01-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,408 INFO sqlalchemy.engine.base.Engine ('2015-01-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:38,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,410 INFO sqlalchemy.engine.base.Engine ('2015-01-17 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:38,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,411 INFO sqlalchemy.engine.base.Engine ('2015-01-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,413 INFO sqlalchemy.engine.base.Engine ('2015-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:38,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,416 INFO sqlalchemy.engine.base.Engine ('2015-01-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,417 INFO sqlalchemy.engine.base.Engine ('2015-01-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:38,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,419 INFO sqlalchemy.engine.base.Engine ('2015-01-24 00:00:00.000000', 0.39, 67)
2018-05-08 18:31:38,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,421 INFO sqlalchemy.engine.base.Engine ('2015-01-30 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:38,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,423 INFO sqlalchemy.engine.base.Engine ('2015-01-31 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:38,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,425 INFO sqlalchemy.engine.base.Engine ('2015-02-03 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:38,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,426 INFO sqlalchemy.engine.base.Engine ('2015-02-04 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:38,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,428 INFO sqlalchemy.engine.base.Engine ('2015-02-05 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:38,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,430 INFO sqlalchemy.engine.base.Engine ('2015-02-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:38,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,431 INFO sqlalchemy.engine.base.Engine ('2015-02-10 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:38,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,433 INFO sqlalchemy.engine.base.Engine ('2015-02-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:38,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,435 INFO sqlalchemy.engine.base.Engine ('2015-02-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:38,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,436 INFO sqlalchemy.engine.base.Engine ('2015-02-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,438 INFO sqlalchemy.engine.base.Engine ('2015-02-14 00:00:00.000000', 0.9, 73)
2018-05-08 18:31:38,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,440 INFO sqlalchemy.engine.base.Engine ('2015-02-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:38,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,441 INFO sqlalchemy.engine.base.Engine ('2015-02-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,443 INFO sqlalchemy.engine.base.Engine ('2015-02-20 00:00:00.000000', 0.26, 67)
2018-05-08 18:31:38,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,444 INFO sqlalchemy.engine.base.Engine ('2015-02-21 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:38,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,446 INFO sqlalchemy.engine.base.Engine ('2015-02-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,448 INFO sqlalchemy.engine.base.Engine ('2015-02-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:38,449 INFO sqlalchemy.engine.base.Engine ('2015-02-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,452 INFO sqlalchemy.engine.base.Engine ('2015-02-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,454 INFO sqlalchemy.engine.base.Engine ('2015-02-26 00:00:00.000000', 0.41, 74)
2018-05-08 18:31:38,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,456 INFO sqlalchemy.engine.base.Engine ('2015-03-02 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:38,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,457 INFO sqlalchemy.engine.base.Engine ('2015-03-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:38,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,459 INFO sqlalchemy.engine.base.Engine ('2015-03-04 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:38,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,460 INFO sqlalchemy.engine.base.Engine ('2015-03-05 00:00:00.000000', 0.42, 72)
2018-05-08 18:31:38,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,462 INFO sqlalchemy.engine.base.Engine ('2015-03-06 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:38,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,464 INFO sqlalchemy.engine.base.Engine ('2015-03-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:38,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,465 INFO sqlalchemy.engine.base.Engine ('2015-03-12 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:38,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,467 INFO sqlalchemy.engine.base.Engine ('2015-03-13 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:38,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,469 INFO sqlalchemy.engine.base.Engine ('2015-03-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:38,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,471 INFO sqlalchemy.engine.base.Engine ('2015-03-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:38,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,473 INFO sqlalchemy.engine.base.Engine ('2015-03-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:38,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,475 INFO sqlalchemy.engine.base.Engine ('2015-03-20 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:38,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:38,477 INFO sqlalchemy.engine.base.Engine ('2015-03-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:38,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,383 INFO sqlalchemy.engine.base.Engine ('2016-10-20 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:39,385 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,386 INFO sqlalchemy.engine.base.Engine ('2016-10-21 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:39,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,387 INFO sqlalchemy.engine.base.Engine ('2016-10-24 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:39,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,389 INFO sqlalchemy.engine.base.Engine ('2016-10-25 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,391 INFO sqlalchemy.engine.base.Engine ('2016-10-27 00:00:00.000000', 0.2, 78)
2018-05-08 18:31:39,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,392 INFO sqlalchemy.engine.base.Engine ('2016-10-28 00:00:00.000000', 0.07, 78)
2018-05-08 18:31:39,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,394 INFO sqlalchemy.engine.base.Engine ('2016-10-29 00:00:00.000000', 0.26, 76)
2018-05-08 18:31:39,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,395 INFO sqlalchemy.engine.base.Engine ('2016-10-30 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:39,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,397 INFO sqlalchemy.engine.base.Engine ('2016-10-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,399 INFO sqlalchemy.engine.base.Engine ('2016-11-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,400 INFO sqlalchemy.engine.base.Engine ('2016-11-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,402 INFO sqlalchemy.engine.base.Engine ('2016-11-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,403 INFO sqlalchemy.engine.base.Engine ('2016-11-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,405 INFO sqlalchemy.engine.base.Engine ('2016-11-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,407 INFO sqlalchemy.engine.base.Engine ('2016-11-06 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,409 INFO sqlalchemy.engine.base.Engine ('2016-11-07 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:39,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,411 INFO sqlalchemy.engine.base.Engine ('2016-11-08 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:39,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,413 INFO sqlalchemy.engine.base.Engine ('2016-11-09 00:00:00.000000', 0.17, 74)
2018-05-08 18:31:39,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,414 INFO sqlalchemy.engine.base.Engine ('2016-11-10 00:00:00.000000', 0.0, 75)

2018-05-08 18:31:39,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,417 INFO sqlalchemy.engine.base.Engine ('2016-11-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,418 INFO sqlalchemy.engine.base.Engine ('2016-11-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,420 INFO sqlalchemy.engine.base.Engine ('2016-11-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,422 INFO sqlalchemy.engine.base.Engine ('2016-11-14 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:39,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,424 INFO sqlalchemy.engine.base.Engine ('2016-11-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,425 INFO sqlalchemy.engine.base.Engine ('2016-11-16 00:00:00.000000', 0.18, 78)
2018-05-08 18:31:39,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,427 INFO sqlalchemy.engine.base.Engine ('2016-11-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,429 INFO sqlalchemy.engine.base.Engine ('2016-11-26 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:39,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,430 INFO sqlalchemy.engine.base.Engine ('2016-11-27 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:39,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,432 INFO sqlalchemy.engine.base.Engine ('2016-11-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,434 INFO sqlalchemy.engine.base.Engine ('2016-11-29 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:39,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,435 INFO sqlalchemy.engine.base.Engine ('2016-11-30 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:39,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,437 INFO sqlalchemy.engine.base.Engine ('2016-12-01 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:39,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,438 INFO sqlalchemy.engine.base.Engine ('2016-12-02 00:00:00.000000', 0.4, 77)
2018-05-08 18:31:39,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,440 INFO sqlalchemy.engine.base.Engine ('2016-12-03 00:00:00.000000', 0.26, 75)
2018-05-08 18:31:39,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,442 INFO sqlalchemy.engine.base.Engine ('2016-12-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,443 INFO sqlalchemy.engine.base.Engine ('2016-12-05 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:39,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,445 INFO sqlalchemy.engine.base.Engine ('2016-12-08 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:39,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,447 INFO sqlalchemy.engine.base.Engine ('2016-12-09 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:39,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,448 INFO sqlalchemy.engine.base.Engine ('2016-12-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,450 INFO sqlalchemy.engine.base.Engine ('2016-12-13 00:00:00.000000', 0.34, 72)
2018-05-08 18:31:39,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,451 INFO sqlalchemy.engine.base.Engine ('2016-12-14 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:39,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,453 INFO sqlalchemy.engine.base.Engine ('2016-12-15 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:39,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,454 INFO sqlalchemy.engine.base.Engine ('2016-12-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:39,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,456 INFO sqlalchemy.engine.base.Engine ('2016-12-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:39,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,458 INFO sqlalchemy.engine.base.Engine ('2016-12-18 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:39,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,459 INFO sqlalchemy.engine.base.Engine ('2016-12-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,461 INFO sqlalchemy.engine.base.Engine ('2016-12-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,463 INFO sqlalchemy.engine.base.Engine ('2016-12-21 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:39,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,464 INFO sqlalchemy.engine.base.Engine ('2016-12-22 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:39,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,466 INFO sqlalchemy.engine.base.Engine ('2016-12-23 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:39,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,467 INFO sqlalchemy.engine.base.Engine ('2016-12-24 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:39,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,469 INFO sqlalchemy.engine.base.Engine ('2016-12-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:39,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,470 INFO sqlalchemy.engine.base.Engine ('2016-12-28 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:39,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,472 INFO sqlalchemy.engine.base.Engine ('2016-12-29 00:00:00.000000', 0.56, 73)

2018-05-08 18:31:39,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,474 INFO sqlalchemy.engine.base.Engine ('2016-12-30 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:39,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,475 INFO sqlalchemy.engine.base.Engine ('2016-12-31 00:00:00.000000', 0.36, 72)
2018-05-08 18:31:39,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,477 INFO sqlalchemy.engine.base.Engine ('2017-01-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,479 INFO sqlalchemy.engine.base.Engine ('2017-01-02 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:39,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,480 INFO sqlalchemy.engine.base.Engine ('2017-01-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:39,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,526 INFO sqlalchemy.engine.base.Engine ('2017-01-04 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,528 INFO sqlalchemy.engine.base.Engine ('2017-01-05 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:39,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,529 INFO sqlalchemy.engine.base.Engine ('2017-01-06 00:00:00.000000', 0.59, 71)
2018-05-08 18:31:39,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,531 INFO sqlalchemy.engine.base.Engine ('2017-01-07 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,533 INFO sqlalchemy.engine.base.Engine ('2017-01-08 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:39,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,534 INFO sqlalchemy.engine.base.Engine ('2017-01-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:39,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,536 INFO sqlalchemy.engine.base.Engine ('2017-01-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:39,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,537 INFO sqlalchemy.engine.base.Engine ('2017-01-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,539 INFO sqlalchemy.engine.base.Engine ('2017-01-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,541 INFO sqlalchemy.engine.base.Engine ('2017-01-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:39,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,543 INFO sqlalchemy.engine.base.Engine ('2017-01-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:39,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,544 INFO sqlalchemy.engine.base.Engine ('2017-01-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,546 INFO sqlalchemy.engine.base.Engine ('2017-01-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,547 INFO sqlalchemy.engine.base.Engine ('2017-01-21 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:39,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,549 INFO sqlalchemy.engine.base.Engine ('2017-01-26 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:39,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,550 INFO sqlalchemy.engine.base.Engine ('2017-01-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,552 INFO sqlalchemy.engine.base.Engine ('2017-01-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,553 INFO sqlalchemy.engine.base.Engine ('2017-01-31 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:39,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,555 INFO sqlalchemy.engine.base.Engine ('2017-02-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:39,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,556 INFO sqlalchemy.engine.base.Engine ('2017-02-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:39,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,558 INFO sqlalchemy.engine.base.Engine ('2017-02-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:39,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,559 INFO sqlalchemy.engine.base.Engine ('2017-02-06 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:39,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,561 INFO sqlalchemy.engine.base.Engine ('2017-02-07 00:00:00.000000', 0.9, 76)
2018-05-08 18:31:39,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,562 INFO sqlalchemy.engine.base.Engine ('2017-02-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:39,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,563 INFO sqlalchemy.engine.base.Engine ('2017-02-09 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,565 INFO sqlalchemy.engine.base.Engine ('2017-02-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:39,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,567 INFO sqlalchemy.engine.base.Engine ('2017-02-11 00:00:00.000000', 2.39, 69)
2018-05-08 18:31:39,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,568 INFO sqlalchemy.engine.base.Engine ('2017-02-12 00:00:00.000000', 1.91, 76)
2018-05-08 18:31:39,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,570 INFO sqlalchemy.engine.base.Engine ('2017-02-13 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:39,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,571 INFO sqlalchemy.engine.base.Engine ('2017-02-14 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:39,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,573 INFO sqlalchemy.engine.base.Engine ('2017-02-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,575 INFO sqlalchemy.engine.base.Engine ('2017-02-16 00:00:00.000000', 0.62, 73)
2018-05-08 18:31:39,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,576 INFO sqlalchemy.engine.base.Engine ('2017-02-17 00:00:00.000000', 0.06, 77)
2018-05-08 18:31:39,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,578 INFO sqlalchemy.engine.base.Engine ('2017-02-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,579 INFO sqlalchemy.engine.base.Engine ('2017-02-22 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:39,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,581 INFO sqlalchemy.engine.base.Engine ('2017-02-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:39,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,582 INFO sqlalchemy.engine.base.Engine ('2017-02-24 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,583 INFO sqlalchemy.engine.base.Engine ('2017-02-27 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,585 INFO sqlalchemy.engine.base.Engine ('2017-02-28 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:39,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,586 INFO sqlalchemy.engine.base.Engine ('2017-03-01 00:00:00.000000', 1.12, 71)
2018-05-08 18:31:39,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,589 INFO sqlalchemy.engine.base.Engine ('2017-03-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,591 INFO sqlalchemy.engine.base.Engine ('2017-03-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,592 INFO sqlalchemy.engine.base.Engine ('2017-03-09 00:00:00.000000', 0.5, 69)
2018-05-08 18:31:39,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,594 INFO sqlalchemy.engine.base.Engine ('2017-03-10 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:39,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,596 INFO sqlalchemy.engine.base.Engine ('2017-03-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,597 INFO sqlalchemy.engine.base.Engine ('2017-03-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,599 INFO sqlalchemy.engine.base.Engine ('2017-03-17 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:39,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,600 INFO sqlalchemy.engine.base.Engine ('2017-03-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,602 INFO sqlalchemy.engine.base.Engine ('2017-03-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,603 INFO sqlalchemy.engine.base.Engine ('2017-03-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,605 INFO sqlalchemy.engine.base.Engine ('2017-03-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,607 INFO sqlalchemy.engine.base.Engine ('2017-03-24 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:39,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,608 INFO sqlalchemy.engine.base.Engine ('2017-03-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,610 INFO sqlalchemy.engine.base.Engine ('2017-03-29 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:39,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,611 INFO sqlalchemy.engine.base.Engine ('2017-03-30 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:39,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,613 INFO sqlalchemy.engine.base.Engine ('2017-03-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,615 INFO sqlalchemy.engine.base.Engine ('2017-04-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,616 INFO sqlalchemy.engine.base.Engine ('2017-04-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,618 INFO sqlalchemy.engine.base.Engine ('2017-04-03 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:39,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,619 INFO sqlalchemy.engine.base.Engine ('2017-04-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,622 INFO sqlalchemy.engine.base.Engine ('2017-04-05 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:39,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,623 INFO sqlalchemy.engine.base.Engine ('2017-04-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,624 INFO sqlalchemy.engine.base.Engine ('2017-04-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,626 INFO sqlalchemy.engine.base.Engine ('2017-04-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:39,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,627 INFO sqlalchemy.engine.base.Engine ('2017-04-11 00:00:00.000000', 0.16, 77)

2018-05-08 18:31:39,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,629 INFO sqlalchemy.engine.base.Engine ('2017-04-12 00:00:00.000000', 0.29, 77)
2018-05-08 18:31:39,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,630 INFO sqlalchemy.engine.base.Engine ('2017-04-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,632 INFO sqlalchemy.engine.base.Engine ('2017-04-14 00:00:00.000000', 0.29, 77)
2018-05-08 18:31:39,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,633 INFO sqlalchemy.engine.base.Engine ('2017-04-18 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:39,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,635 INFO sqlalchemy.engine.base.Engine ('2017-04-19 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:39,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,636 INFO sqlalchemy.engine.base.Engine ('2017-04-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,638 INFO sqlalchemy.engine.base.Engine ('2017-04-21 00:00:00.000000', 1.05, 70)
2018-05-08 18:31:39,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,639 INFO sqlalchemy.engine.base.Engine ('2017-04-22 00:00:00.000000', 0.7, 74)
2018-05-08 18:31:39,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,641 INFO sqlalchemy.engine.base.Engine ('2017-04-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,642 INFO sqlalchemy.engine.base.Engine ('2017-04-26 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:39,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,644 INFO sqlalchemy.engine.base.Engine ('2017-04-27 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:39,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,645 INFO sqlalchemy.engine.base.Engine ('2017-04-28 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:39,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,647 INFO sqlalchemy.engine.base.Engine ('2017-04-29 00:00:00.000000', 0.95, 71)
2018-05-08 18:31:39,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,648 INFO sqlalchemy.engine.base.Engine ('2017-04-30 00:00:00.000000', 1.17, 63)
2018-05-08 18:31:39,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,650 INFO sqlalchemy.engine.base.Engine ('2017-05-01 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:39,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,651 INFO sqlalchemy.engine.base.Engine ('2017-05-02 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:39,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,652 INFO sqlalchemy.engine.base.Engine ('2017-05-03 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:39,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,654 INFO sqlalchemy.engine.base.Engine ('2017-05-04 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:39,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,655 INFO sqlalchemy.engine.base.Engine ('2017-05-05 00:00:00.000000', 0.28, 78)
2018-05-08 18:31:39,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,657 INFO sqlalchemy.engine.base.Engine ('2017-05-06 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:39,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,658 INFO sqlalchemy.engine.base.Engine ('2017-05-08 00:00:00.000000', 0.95, 73)
2018-05-08 18:31:39,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,660 INFO sqlalchemy.engine.base.Engine ('2017-05-09 00:00:00.000000', 0.52, 79)
2018-05-08 18:31:39,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,661 INFO sqlalchemy.engine.base.Engine ('2017-05-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:39,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,662 INFO sqlalchemy.engine.base.Engine ('2017-05-16 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:39,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,664 INFO sqlalchemy.engine.base.Engine ('2017-05-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,665 INFO sqlalchemy.engine.base.Engine ('2017-05-18 00:00:00.000000', 0.16, 78)
2018-05-08 18:31:39,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,667 INFO sqlalchemy.engine.base.Engine ('2017-05-19 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:39,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,669 INFO sqlalchemy.engine.base.Engine ('2017-05-20 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:39,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,671 INFO sqlalchemy.engine.base.Engine ('2017-05-23 00:00:00.000000', 0.11, 78)
2018-05-08 18:31:39,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,675 INFO sqlalchemy.engine.base.Engine ('2017-05-24 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:39,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,676 INFO sqlalchemy.engine.base.Engine ('2017-05-25 00:00:00.000000', 0.07, 79)
2018-05-08 18:31:39,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,678 INFO sqlalchemy.engine.base.Engine ('2017-05-26 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:39,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,680 INFO sqlalchemy.engine.base.Engine ('2017-05-27 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:39,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,681 INFO sqlalchemy.engine.base.Engine ('2017-05-28 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:39,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,683 INFO sqlalchemy.engine.base.Engine ('2017-05-29 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:39,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,734 INFO sqlalchemy.engine.base.Engine ('2017-05-30 00:00:00.000000', 0.04, 81)
2018-05-08 18:31:39,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,735 INFO sqlalchemy.engine.base.Engine ('2017-05-31 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,737 INFO sqlalchemy.engine.base.Engine ('2017-06-01 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,738 INFO sqlalchemy.engine.base.Engine ('2017-06-02 00:00:00.000000', 0.15, 78)
2018-05-08 18:31:39,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,742 INFO sqlalchemy.engine.base.Engine ('2017-06-03 00:00:00.000000', 0.16, 80)
2018-05-08 18:31:39,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,745 INFO sqlalchemy.engine.base.Engine ('2017-06-04 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:39,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,746 INFO sqlalchemy.engine.base.Engine ('2017-06-05 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:39,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,748 INFO sqlalchemy.engine.base.Engine ('2017-06-06 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:39,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,749 INFO sqlalchemy.engine.base.Engine ('2017-06-07 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,751 INFO sqlalchemy.engine.base.Engine ('2017-06-08 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:39,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,752 INFO sqlalchemy.engine.base.Engine ('2017-06-09 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,754 INFO sqlalchemy.engine.base.Engine ('2017-06-10 00:00:00.000000', 0.53, 78)
2018-05-08 18:31:39,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,757 INFO sqlalchemy.engine.base.Engine ('2017-06-11 00:00:00.000000', 0.14, 79)
2018-05-08 18:31:39,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,759 INFO sqlalchemy.engine.base.Engine ('2017-06-12 00:00:00.000000', 0.35, 79)
2018-05-08 18:31:39,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,762 INFO sqlalchemy.engine.base.Engine ('2017-06-13 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:39,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,763 INFO sqlalchemy.engine.base.Engine ('2017-06-14 00:00:00.000000', 0.21, 79)
2018-05-08 18:31:39,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,765 INFO sqlalchemy.engine.base.Engine ('2017-06-15 00:00:00.000000', 0.3, 78)
2018-05-08 18:31:39,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,767 INFO sqlalchemy.engine.base.Engine ('2017-06-16 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:39,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,768 INFO sqlalchemy.engine.base.Engine ('2017-06-17 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:39,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,770 INFO sqlalchemy.engine.base.Engine ('2017-06-18 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:39,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,772 INFO sqlalchemy.engine.base.Engine ('2017-06-19 00:00:00.000000', 0.19, 78)
2018-05-08 18:31:39,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,775 INFO sqlalchemy.engine.base.Engine ('2017-06-20 00:00:00.000000', 0.17, 79)
2018-05-08 18:31:39,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,777 INFO sqlalchemy.engine.base.Engine ('2017-06-30 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,778 INFO sqlalchemy.engine.base.Engine ('2017-07-08 00:00:00.000000', 0.06, 81)
2018-05-08 18:31:39,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,780 INFO sqlalchemy.engine.base.Engine ('2017-07-09 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:39,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,782 INFO sqlalchemy.engine.base.Engine ('2017-07-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:39,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,784 INFO sqlalchemy.engine.base.Engine ('2017-07-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:39,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,785 INFO sqlalchemy.engine.base.Engine ('2017-07-12 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:39,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,787 INFO sqlalchemy.engine.base.Engine ('2017-07-13 00:00:00.000000', 0.3, 81)
2018-05-08 18:31:39,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,789 INFO sqlalchemy.engine.base.Engine ('2017-07-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:39,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,790 INFO sqlalchemy.engine.base.Engine ('2017-07-15 00:00:00.000000', 0.01, 82)
2018-05-08 18:31:39,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,792 INFO sqlalchemy.engine.base.Engine ('2017-07-16 00:00:00.000000', 0.12, 79)
2018-05-08 18:31:39,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,794 INFO sqlalchemy.engine.base.Engine ('2017-07-17 00:00:00.000000', 0.16, 82)
2018-05-08 18:31:39,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,795 INFO sqlalchemy.engine.base.Engine ('2017-07-18 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:39,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,797 INFO sqlalchemy.engine.base.Engine ('2017-07-19 00:00:00.000000', 0.09, 80)

2018-05-08 18:31:39,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,798 INFO sqlalchemy.engine.base.Engine ('2017-07-20 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:39,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,799 INFO sqlalchemy.engine.base.Engine ('2017-07-21 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:39,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,801 INFO sqlalchemy.engine.base.Engine ('2017-07-22 00:00:00.000000', 0.12, 80)
2018-05-08 18:31:39,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,802 INFO sqlalchemy.engine.base.Engine ('2017-07-23 00:00:00.000000', 0.07, 82)
2018-05-08 18:31:39,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,804 INFO sqlalchemy.engine.base.Engine ('2017-07-24 00:00:00.000000', 1.19, 79)
2018-05-08 18:31:39,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,806 INFO sqlalchemy.engine.base.Engine ('2017-07-25 00:00:00.000000', 0.12, 80)
2018-05-08 18:31:39,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,807 INFO sqlalchemy.engine.base.Engine ('2017-07-26 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:39,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,809 INFO sqlalchemy.engine.base.Engine ('2017-07-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:39,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,810 INFO sqlalchemy.engine.base.Engine ('2017-07-28 00:00:00.000000', 0.14, 81)
2018-05-08 18:31:39,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,812 INFO sqlalchemy.engine.base.Engine ('2017-07-29 00:00:00.000000', 0.02, 82)
2018-05-08 18:31:39,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,813 INFO sqlalchemy.engine.base.Engine ('2017-08-01 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:39,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,815 INFO sqlalchemy.engine.base.Engine ('2017-08-02 00:00:00.000000', 0.05, 80)
2018-05-08 18:31:39,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,816 INFO sqlalchemy.engine.base.Engine ('2017-08-03 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:39,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,818 INFO sqlalchemy.engine.base.Engine ('2017-08-04 00:00:00.000000', 0.04, 81)
2018-05-08 18:31:39,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,819 INFO sqlalchemy.engine.base.Engine ('2017-08-06 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:39,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,821 INFO sqlalchemy.engine.base.Engine ('2017-08-07 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,823 INFO sqlalchemy.engine.base.Engine ('2017-08-08 00:00:00.000000', 0.1, 78)
2018-05-08 18:31:39,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,824 INFO sqlalchemy.engine.base.Engine ('2017-08-09 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,826 INFO sqlalchemy.engine.base.Engine ('2017-08-10 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,827 INFO sqlalchemy.engine.base.Engine ('2017-08-11 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:39,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,829 INFO sqlalchemy.engine.base.Engine ('2017-08-14 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:39,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,830 INFO sqlalchemy.engine.base.Engine ('2017-08-15 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:39,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,832 INFO sqlalchemy.engine.base.Engine ('2017-08-16 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:39,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,833 INFO sqlalchemy.engine.base.Engine ('2017-08-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:39,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,835 INFO sqlalchemy.engine.base.Engine ('2017-08-18 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:39,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,837 INFO sqlalchemy.engine.base.Engine ('2017-08-19 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:39,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,839 INFO sqlalchemy.engine.base.Engine ('2017-08-20 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:39,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,840 INFO sqlalchemy.engine.base.Engine ('2017-08-21 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:39,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00514830" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,842 INFO sqlalchemy.engine.base.Engine ('2017-08-23 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:39,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,850 INFO sqlalchemy.engine.base.Engine ('2010-01-01 00:00:00.000000', 0.21, 72)
2018-05-08 18:31:39,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,852 INFO sqlalchemy.engine.base.Engine ('2010-01-02 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:39,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,853 INFO sqlalchemy.engine.base.Engine ('2010-01-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:39,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,855 INFO sqlalchemy.engine.base.Engine ('2010-01-04 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:39,856 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,857 INFO sqlalchemy.engine.base.Engine ('2010-01-05 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:39,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,859 INFO sqlalchemy.engine.base.Engine ('2010-01-08 00:00:00.000000', 0.03, 73)

2018-05-08 18:31:39,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,860 INFO sqlalchemy.engine.base.Engine ('2010-01-09 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:39,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,862 INFO sqlalchemy.engine.base.Engine ('2010-01-10 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:39,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,863 INFO sqlalchemy.engine.base.Engine ('2010-01-11 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:39,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,865 INFO sqlalchemy.engine.base.Engine ('2010-01-12 00:00:00.000000', 0.02, 60)
2018-05-08 18:31:39,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,866 INFO sqlalchemy.engine.base.Engine ('2010-01-13 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:39,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,868 INFO sqlalchemy.engine.base.Engine ('2010-01-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:39,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,869 INFO sqlalchemy.engine.base.Engine ('2010-01-19 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:39,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,871 INFO sqlalchemy.engine.base.Engine ('2010-01-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:39,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,873 INFO sqlalchemy.engine.base.Engine ('2010-01-26 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:39,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,874 INFO sqlalchemy.engine.base.Engine ('2010-01-27 00:00:00.000000', 0.21, 70)
2018-05-08 18:31:39,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,875 INFO sqlalchemy.engine.base.Engine ('2010-01-28 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:39,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,877 INFO sqlalchemy.engine.base.Engine ('2010-02-03 00:00:00.000000', 0.87, 65)
2018-05-08 18:31:39,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,878 INFO sqlalchemy.engine.base.Engine ('2010-02-04 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:39,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,880 INFO sqlalchemy.engine.base.Engine ('2010-02-05 00:00:00.000000', 0.01, 59)
2018-05-08 18:31:39,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,881 INFO sqlalchemy.engine.base.Engine ('2010-02-06 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:39,882 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,883 INFO sqlalchemy.engine.base.Engine ('2010-02-07 00:00:00.000000', 0.01, 62)
2018-05-08 18:31:39,884 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,884 INFO sqlalchemy.engine.base.Engine ('2010-02-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:39,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,886 INFO sqlalchemy.engine.base.Engine ('2010-02-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:39,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,887 INFO sqlalchemy.engine.base.Engine ('2010-02-13 00:00:00.000000', 0.06, 67)
2018-05-08 18:31:39,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,889 INFO sqlalchemy.engine.base.Engine ('2010-02-14 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:39,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,890 INFO sqlalchemy.engine.base.Engine ('2010-02-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:39,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,893 INFO sqlalchemy.engine.base.Engine ('2010-02-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:39,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,895 INFO sqlalchemy.engine.base.Engine ('2010-02-17 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:39,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,896 INFO sqlalchemy.engine.base.Engine ('2010-02-20 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:39,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,898 INFO sqlalchemy.engine.base.Engine ('2010-02-21 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:39,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,933 INFO sqlalchemy.engine.base.Engine ('2010-02-24 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:39,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,935 INFO sqlalchemy.engine.base.Engine ('2010-02-25 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:39,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,937 INFO sqlalchemy.engine.base.Engine ('2010-03-02 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:39,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,939 INFO sqlalchemy.engine.base.Engine ('2010-03-06 00:00:00.000000', 1.08, 63)
2018-05-08 18:31:39,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,940 INFO sqlalchemy.engine.base.Engine ('2010-03-07 00:00:00.000000', 0.17, 67)
2018-05-08 18:31:39,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,962 INFO sqlalchemy.engine.base.Engine ('2010-03-08 00:00:00.000000', 0.64, 66)
2018-05-08 18:31:39,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,963 INFO sqlalchemy.engine.base.Engine ('2010-03-09 00:00:00.000000', 0.23, 67)
2018-05-08 18:31:39,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,964 INFO sqlalchemy.engine.base.Engine ('2010-03-12 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:39,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,966 INFO sqlalchemy.engine.base.Engine ('2010-03-13 00:00:00.000000', 0.03, 62)
2018-05-08 18:31:39,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,967 INFO sqlalchemy.engine.base.Engine ('2010-03-14 00:00:00.000000', 0.02, 62)

2018-05-08 18:31:39,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,969 INFO sqlalchemy.engine.base.Engine ('2010-03-15 00:00:00.000000', 0.13, 65)
2018-05-08 18:31:39,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,970 INFO sqlalchemy.engine.base.Engine ('2010-03-16 00:00:00.000000', 0.46, 63)
2018-05-08 18:31:39,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:39,972 INFO sqlalchemy.engine.base.Engine ('2010-03-29 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:40,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,001 INFO sqlalchemy.engine.base.Engine ('2010-03-30 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:40,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,002 INFO sqlalchemy.engine.base.Engine ('2010-04-03 00:00:00.000000', 0.53, 67)
2018-05-08 18:31:40,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,004 INFO sqlalchemy.engine.base.Engine ('2010-04-04 00:00:00.000000', 0.87, 66)
2018-05-08 18:31:40,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,006 INFO sqlalchemy.engine.base.Engine ('2010-04-05 00:00:00.000000', 1.8, 67)
2018-05-08 18:31:40,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,007 INFO sqlalchemy.engine.base.Engine ('2010-04-06 00:00:00.000000', 0.3, 70)
2018-05-08 18:31:40,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,008 INFO sqlalchemy.engine.base.Engine ('2010-04-07 00:00:00.000000', 2.12, 72)
2018-05-08 18:31:40,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,010 INFO sqlalchemy.engine.base.Engine ('2010-04-08 00:00:00.000000', 0.47, 74)
2018-05-08 18:31:40,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,011 INFO sqlalchemy.engine.base.Engine ('2010-04-09 00:00:00.000000', 0.8, 71)
2018-05-08 18:31:40,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,012 INFO sqlalchemy.engine.base.Engine ('2010-04-14 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:40,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,014 INFO sqlalchemy.engine.base.Engine ('2010-04-17 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:40,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,015 INFO sqlalchemy.engine.base.Engine ('2010-04-18 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:40,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,036 INFO sqlalchemy.engine.base.Engine ('2010-04-22 00:00:00.000000', 0.54, 72)
2018-05-08 18:31:40,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,037 INFO sqlalchemy.engine.base.Engine ('2010-04-23 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:40,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,039 INFO sqlalchemy.engine.base.Engine ('2010-04-24 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:40,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,040 INFO sqlalchemy.engine.base.Engine ('2010-04-25 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:40,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,041 INFO sqlalchemy.engine.base.Engine ('2010-04-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:40,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,043 INFO sqlalchemy.engine.base.Engine ('2010-05-01 00:00:00.000000', 0.29, 69)
2018-05-08 18:31:40,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,044 INFO sqlalchemy.engine.base.Engine ('2010-05-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:40,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,046 INFO sqlalchemy.engine.base.Engine ('2010-05-03 00:00:00.000000', 0.87, 67)
2018-05-08 18:31:40,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,048 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:40,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,049 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:40,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,051 INFO sqlalchemy.engine.base.Engine ('2010-05-09 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:40,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,052 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:40,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,054 INFO sqlalchemy.engine.base.Engine ('2010-05-11 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:40,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,055 INFO sqlalchemy.engine.base.Engine ('2010-05-12 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:40,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,056 INFO sqlalchemy.engine.base.Engine ('2010-05-13 00:00:00.000000', 0.04, 78)
2018-05-08 18:31:40,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,057 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:40,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,059 INFO sqlalchemy.engine.base.Engine ('2010-05-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,060 INFO sqlalchemy.engine.base.Engine ('2010-05-17 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:40,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,062 INFO sqlalchemy.engine.base.Engine ('2010-05-20 00:00:00.000000', 0.56, 71)
2018-05-08 18:31:40,063 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,063 INFO sqlalchemy.engine.base.Engine ('2010-05-21 00:00:00.000000', 0.45, 70)
2018-05-08 18:31:40,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,065 INFO sqlalchemy.engine.base.Engine ('2010-05-22 00:00:00.000000', 0.04, 74)

2018-05-08 18:31:40,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,066 INFO sqlalchemy.engine.base.Engine ('2010-05-23 00:00:00.000000', 0.6, 70)
2018-05-08 18:31:40,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,068 INFO sqlalchemy.engine.base.Engine ('2010-05-24 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:40,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,070 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:40,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,071 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:40,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,073 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:40,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,075 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:40,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,076 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:40,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,078 INFO sqlalchemy.engine.base.Engine ('2010-06-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:40,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,079 INFO sqlalchemy.engine.base.Engine ('2010-06-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:40,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,081 INFO sqlalchemy.engine.base.Engine ('2010-06-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:40,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,082 INFO sqlalchemy.engine.base.Engine ('2010-06-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,084 INFO sqlalchemy.engine.base.Engine ('2010-06-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:40,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,085 INFO sqlalchemy.engine.base.Engine ('2010-06-13 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:40,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,087 INFO sqlalchemy.engine.base.Engine ('2010-06-17 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,088 INFO sqlalchemy.engine.base.Engine ('2010-06-18 00:00:00.000000', 0.3, 70)
2018-05-08 18:31:40,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,090 INFO sqlalchemy.engine.base.Engine ('2010-06-19 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:40,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,092 INFO sqlalchemy.engine.base.Engine ('2010-06-20 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:40,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,093 INFO sqlalchemy.engine.base.Engine ('2010-06-23 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:40,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,095 INFO sqlalchemy.engine.base.Engine ('2010-06-24 00:00:00.000000', 0.28, 73)
2018-05-08 18:31:40,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,096 INFO sqlalchemy.engine.base.Engine ('2010-06-25 00:00:00.000000', 0.3, 74)
2018-05-08 18:31:40,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,098 INFO sqlalchemy.engine.base.Engine ('2010-06-29 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:40,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,099 INFO sqlalchemy.engine.base.Engine ('2010-06-30 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:40,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,101 INFO sqlalchemy.engine.base.Engine ('2010-07-01 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:40,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,103 INFO sqlalchemy.engine.base.Engine ('2010-07-02 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:40,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,104 INFO sqlalchemy.engine.base.Engine ('2010-07-03 00:00:00.000000', 0.84, 73)
2018-05-08 18:31:40,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,106 INFO sqlalchemy.engine.base.Engine ('2010-07-04 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:40,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,107 INFO sqlalchemy.engine.base.Engine ('2010-07-05 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:40,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,109 INFO sqlalchemy.engine.base.Engine ('2010-07-06 00:00:00.000000', 0.41, 71)
2018-05-08 18:31:40,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,111 INFO sqlalchemy.engine.base.Engine ('2010-07-07 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:40,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,112 INFO sqlalchemy.engine.base.Engine ('2010-07-10 00:00:00.000000', 0.44, 71)
2018-05-08 18:31:40,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,114 INFO sqlalchemy.engine.base.Engine ('2010-07-11 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:40,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,115 INFO sqlalchemy.engine.base.Engine ('2010-07-16 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:40,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,117 INFO sqlalchemy.engine.base.Engine ('2010-07-28 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:40,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,118 INFO sqlalchemy.engine.base.Engine ('2010-08-03 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:40,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,120 INFO sqlalchemy.engine.base.Engine ('2010-08-04 00:00:00.000000', 0.25, 72)

2018-05-08 18:31:40,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,121 INFO sqlalchemy.engine.base.Engine ('2010-08-05 00:00:00.000000', 0.36, 73)
2018-05-08 18:31:40,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,123 INFO sqlalchemy.engine.base.Engine ('2010-08-06 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:40,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,124 INFO sqlalchemy.engine.base.Engine ('2010-08-07 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:40,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,126 INFO sqlalchemy.engine.base.Engine ('2010-08-10 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:40,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,127 INFO sqlalchemy.engine.base.Engine ('2010-08-11 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:40,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,129 INFO sqlalchemy.engine.base.Engine ('2010-08-18 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:40,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,130 INFO sqlalchemy.engine.base.Engine ('2010-08-19 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:40,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,132 INFO sqlalchemy.engine.base.Engine ('2010-08-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:40,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,133 INFO sqlalchemy.engine.base.Engine ('2010-08-26 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:40,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,135 INFO sqlalchemy.engine.base.Engine ('2010-08-29 00:00:00.000000', 0.38, 74)
2018-05-08 18:31:40,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,136 INFO sqlalchemy.engine.base.Engine ('2010-08-30 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:40,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,138 INFO sqlalchemy.engine.base.Engine ('2010-08-31 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:40,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,140 INFO sqlalchemy.engine.base.Engine ('2010-09-01 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:40,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,141 INFO sqlalchemy.engine.base.Engine ('2010-09-04 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:40,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,143 INFO sqlalchemy.engine.base.Engine ('2010-09-05 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:40,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,144 INFO sqlalchemy.engine.base.Engine ('2010-09-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:40,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,146 INFO sqlalchemy.engine.base.Engine ('2010-09-07 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:40,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,147 INFO sqlalchemy.engine.base.Engine ('2010-09-10 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:40,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,149 INFO sqlalchemy.engine.base.Engine ('2010-09-13 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:40,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,151 INFO sqlalchemy.engine.base.Engine ('2010-09-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:40,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,152 INFO sqlalchemy.engine.base.Engine ('2010-09-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,154 INFO sqlalchemy.engine.base.Engine ('2010-09-16 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:40,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,156 INFO sqlalchemy.engine.base.Engine ('2010-09-17 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,158 INFO sqlalchemy.engine.base.Engine ('2010-09-18 00:00:00.000000', 0.03, 78)
2018-05-08 18:31:40,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,160 INFO sqlalchemy.engine.base.Engine ('2010-09-22 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:40,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,200 INFO sqlalchemy.engine.base.Engine ('2010-09-23 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:40,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,201 INFO sqlalchemy.engine.base.Engine ('2010-09-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,203 INFO sqlalchemy.engine.base.Engine ('2010-09-27 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:40,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,204 INFO sqlalchemy.engine.base.Engine ('2010-09-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,205 INFO sqlalchemy.engine.base.Engine ('2010-10-01 00:00:00.000000', 0.25, 71)
2018-05-08 18:31:40,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,207 INFO sqlalchemy.engine.base.Engine ('2010-10-02 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:40,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,208 INFO sqlalchemy.engine.base.Engine ('2010-10-03 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:40,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,210 INFO sqlalchemy.engine.base.Engine ('2010-10-04 00:00:00.000000', 0.53, 77)
2018-05-08 18:31:40,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,211 INFO sqlalchemy.engine.base.Engine ('2010-10-05 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:40,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,213 INFO sqlalchemy.engine.base.Engine ('2010-10-06 00:00:00.000000', 0.01, 79)

2018-05-08 18:31:40,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,214 INFO sqlalchemy.engine.base.Engine ('2010-10-07 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:40,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,216 INFO sqlalchemy.engine.base.Engine ('2010-10-08 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:40,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,217 INFO sqlalchemy.engine.base.Engine ('2010-10-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,219 INFO sqlalchemy.engine.base.Engine ('2010-10-26 00:00:00.000000', 1.1, 73)
2018-05-08 18:31:40,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,220 INFO sqlalchemy.engine.base.Engine ('2010-10-27 00:00:00.000000', 0.4, 75)
2018-05-08 18:31:40,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,222 INFO sqlalchemy.engine.base.Engine ('2010-10-28 00:00:00.000000', 0.38, 73)
2018-05-08 18:31:40,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,223 INFO sqlalchemy.engine.base.Engine ('2010-10-29 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:40,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,225 INFO sqlalchemy.engine.base.Engine ('2010-10-30 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:40,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,226 INFO sqlalchemy.engine.base.Engine ('2010-10-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:40,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,227 INFO sqlalchemy.engine.base.Engine ('2010-11-01 00:00:00.000000', 0.21, 72)
2018-05-08 18:31:40,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,229 INFO sqlalchemy.engine.base.Engine ('2010-11-02 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:40,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,230 INFO sqlalchemy.engine.base.Engine ('2010-11-03 00:00:00.000000', 0.25, 70)
2018-05-08 18:31:40,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,232 INFO sqlalchemy.engine.base.Engine ('2010-11-04 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:40,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,233 INFO sqlalchemy.engine.base.Engine ('2010-11-05 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:40,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,235 INFO sqlalchemy.engine.base.Engine ('2010-11-16 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:40,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,237 INFO sqlalchemy.engine.base.Engine ('2010-11-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,238 INFO sqlalchemy.engine.base.Engine ('2010-11-19 00:00:00.000000', 0.35, 72)
2018-05-08 18:31:40,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,239 INFO sqlalchemy.engine.base.Engine ('2010-11-23 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:40,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,241 INFO sqlalchemy.engine.base.Engine ('2010-11-24 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:40,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,242 INFO sqlalchemy.engine.base.Engine ('2010-12-03 00:00:00.000000', 0.78, 70)
2018-05-08 18:31:40,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,244 INFO sqlalchemy.engine.base.Engine ('2010-12-06 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:40,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,245 INFO sqlalchemy.engine.base.Engine ('2010-12-07 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:40,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,247 INFO sqlalchemy.engine.base.Engine ('2010-12-08 00:00:00.000000', 0.33, 73)
2018-05-08 18:31:40,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,248 INFO sqlalchemy.engine.base.Engine ('2010-12-09 00:00:00.000000', 1.43, 74)
2018-05-08 18:31:40,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,250 INFO sqlalchemy.engine.base.Engine ('2010-12-10 00:00:00.000000', 2.5, 63)
2018-05-08 18:31:40,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,251 INFO sqlalchemy.engine.base.Engine ('2010-12-11 00:00:00.000000', 1.5, 72)
2018-05-08 18:31:40,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,253 INFO sqlalchemy.engine.base.Engine ('2010-12-14 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:40,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,254 INFO sqlalchemy.engine.base.Engine ('2010-12-15 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:40,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,256 INFO sqlalchemy.engine.base.Engine ('2010-12-16 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:40,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,257 INFO sqlalchemy.engine.base.Engine ('2011-01-05 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:40,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,258 INFO sqlalchemy.engine.base.Engine ('2011-01-06 00:00:00.000000', 0.14, 65)
2018-05-08 18:31:40,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,260 INFO sqlalchemy.engine.base.Engine ('2011-01-07 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:40,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,261 INFO sqlalchemy.engine.base.Engine ('2011-01-11 00:00:00.000000', 0.73, 74)
2018-05-08 18:31:40,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,263 INFO sqlalchemy.engine.base.Engine ('2011-01-12 00:00:00.000000', 1.15, 66)
2018-05-08 18:31:40,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,264 INFO sqlalchemy.engine.base.Engine ('2011-01-13 00:00:00.000000', 6.3, 66)

2018-05-08 18:31:40,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,266 INFO sqlalchemy.engine.base.Engine ('2011-01-14 00:00:00.000000', 0.7, 71)
2018-05-08 18:31:40,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,267 INFO sqlalchemy.engine.base.Engine ('2011-01-19 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:40,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,269 INFO sqlalchemy.engine.base.Engine ('2011-01-20 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:40,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,270 INFO sqlalchemy.engine.base.Engine ('2011-01-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:40,271 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,272 INFO sqlalchemy.engine.base.Engine ('2011-01-25 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:40,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,273 INFO sqlalchemy.engine.base.Engine ('2011-01-26 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:40,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,275 INFO sqlalchemy.engine.base.Engine ('2011-01-27 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:40,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,276 INFO sqlalchemy.engine.base.Engine ('2011-01-28 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:40,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,278 INFO sqlalchemy.engine.base.Engine ('2011-02-01 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:40,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,279 INFO sqlalchemy.engine.base.Engine ('2011-02-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,281 INFO sqlalchemy.engine.base.Engine ('2011-02-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:40,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,282 INFO sqlalchemy.engine.base.Engine ('2011-02-04 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:40,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,284 INFO sqlalchemy.engine.base.Engine ('2011-02-10 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:40,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,285 INFO sqlalchemy.engine.base.Engine ('2011-02-11 00:00:00.000000', 1.0, 69)
2018-05-08 18:31:40,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,287 INFO sqlalchemy.engine.base.Engine ('2011-02-15 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:40,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,289 INFO sqlalchemy.engine.base.Engine ('2011-02-16 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:40,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,291 INFO sqlalchemy.engine.base.Engine ('2011-02-17 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:40,292 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,292 INFO sqlalchemy.engine.base.Engine ('2011-02-18 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:40,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,294 INFO sqlalchemy.engine.base.Engine ('2011-02-23 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:40,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,295 INFO sqlalchemy.engine.base.Engine ('2011-02-24 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:40,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,297 INFO sqlalchemy.engine.base.Engine ('2011-02-25 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:40,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,298 INFO sqlalchemy.engine.base.Engine ('2011-03-01 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:40,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,300 INFO sqlalchemy.engine.base.Engine ('2011-03-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:40,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,301 INFO sqlalchemy.engine.base.Engine ('2011-03-03 00:00:00.000000', 0.89, 74)
2018-05-08 18:31:40,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,303 INFO sqlalchemy.engine.base.Engine ('2011-03-04 00:00:00.000000', 1.42, 73)
2018-05-08 18:31:40,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,304 INFO sqlalchemy.engine.base.Engine ('2011-03-08 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:40,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,307 INFO sqlalchemy.engine.base.Engine ('2011-03-09 00:00:00.000000', 0.66, 69)
2018-05-08 18:31:40,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,309 INFO sqlalchemy.engine.base.Engine ('2011-03-10 00:00:00.000000', 0.36, 71)
2018-05-08 18:31:40,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,311 INFO sqlalchemy.engine.base.Engine ('2011-03-22 00:00:00.000000', 0.32, 73)
2018-05-08 18:31:40,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,312 INFO sqlalchemy.engine.base.Engine ('2011-03-23 00:00:00.000000', 0.34, 74)
2018-05-08 18:31:40,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,314 INFO sqlalchemy.engine.base.Engine ('2011-03-24 00:00:00.000000', 0.39, 74)
2018-05-08 18:31:40,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,316 INFO sqlalchemy.engine.base.Engine ('2011-03-30 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:40,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,317 INFO sqlalchemy.engine.base.Engine ('2011-03-31 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:40,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,318 INFO sqlalchemy.engine.base.Engine ('2011-04-01 00:00:00.000000', 0.34, 74)
2018-05-08 18:31:40,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,320 INFO sqlalchemy.engine.base.Engine ('2011-04-07 00:00:00.000000', 2.4, 70)

2018-05-08 18:31:40,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,322 INFO sqlalchemy.engine.base.Engine ('2011-04-08 00:00:00.000000', 0.57, 68)
2018-05-08 18:31:40,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,323 INFO sqlalchemy.engine.base.Engine ('2011-04-12 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:40,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,324 INFO sqlalchemy.engine.base.Engine ('2011-04-13 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:40,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,326 INFO sqlalchemy.engine.base.Engine ('2011-04-14 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:40,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,327 INFO sqlalchemy.engine.base.Engine ('2011-04-15 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:40,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,329 INFO sqlalchemy.engine.base.Engine ('2011-04-19 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:40,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,330 INFO sqlalchemy.engine.base.Engine ('2011-04-20 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:40,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,332 INFO sqlalchemy.engine.base.Engine ('2011-04-21 00:00:00.000000', 0.19, 75)
2018-05-08 18:31:40,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,334 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,335 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:40,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,337 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.2, 72)
2018-05-08 18:31:40,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,338 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:40,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,340 INFO sqlalchemy.engine.base.Engine ('2011-04-29 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:40,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,342 INFO sqlalchemy.engine.base.Engine ('2011-05-03 00:00:00.000000', 0.53, 71)
2018-05-08 18:31:40,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,344 INFO sqlalchemy.engine.base.Engine ('2011-05-04 00:00:00.000000', 2.1, 71)
2018-05-08 18:31:40,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,345 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.52, 72)
2018-05-08 18:31:40,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,347 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:40,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,348 INFO sqlalchemy.engine.base.Engine ('2011-05-10 00:00:00.000000', 0.35, 72)
2018-05-08 18:31:40,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,350 INFO sqlalchemy.engine.base.Engine ('2011-05-11 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:40,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,351 INFO sqlalchemy.engine.base.Engine ('2011-05-12 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:40,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,392 INFO sqlalchemy.engine.base.Engine ('2011-05-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,393 INFO sqlalchemy.engine.base.Engine ('2011-05-17 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:40,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,395 INFO sqlalchemy.engine.base.Engine ('2011-05-18 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:40,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,397 INFO sqlalchemy.engine.base.Engine ('2011-05-19 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:40,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,398 INFO sqlalchemy.engine.base.Engine ('2011-05-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,400 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:40,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,401 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:40,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,403 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:40,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,406 INFO sqlalchemy.engine.base.Engine ('2011-06-13 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:40,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,407 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:40,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,409 INFO sqlalchemy.engine.base.Engine ('2011-06-15 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:40,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,411 INFO sqlalchemy.engine.base.Engine ('2011-06-16 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:40,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,412 INFO sqlalchemy.engine.base.Engine ('2011-06-21 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:40,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,414 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 0.82, 77)
2018-05-08 18:31:40,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,415 INFO sqlalchemy.engine.base.Engine ('2011-07-06 00:00:00.000000', 0.05, 72)

2018-05-08 18:31:40,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,416 INFO sqlalchemy.engine.base.Engine ('2011-07-07 00:00:00.000000', 0.74, 73)
2018-05-08 18:31:40,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,418 INFO sqlalchemy.engine.base.Engine ('2011-08-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:40,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,419 INFO sqlalchemy.engine.base.Engine ('2011-09-01 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:40,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,421 INFO sqlalchemy.engine.base.Engine ('2011-09-02 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:40,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,422 INFO sqlalchemy.engine.base.Engine ('2011-09-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:40,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,424 INFO sqlalchemy.engine.base.Engine ('2011-09-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:40,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,425 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:40,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,426 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 0.6, 72)
2018-05-08 18:31:40,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,428 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:40,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,430 INFO sqlalchemy.engine.base.Engine ('2012-01-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:40,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,431 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:40,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,433 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:40,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,434 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:40,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,436 INFO sqlalchemy.engine.base.Engine ('2012-01-14 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:40,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,438 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.26, 69)
2018-05-08 18:31:40,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,439 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 1.26, 73)
2018-05-08 18:31:40,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,441 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:40,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,442 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:40,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,444 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:40,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,446 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:40,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,447 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:40,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,449 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 1.03, 72)
2018-05-08 18:31:40,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00518838" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:40,450 INFO sqlalchemy.engine.base.Engine ('2012-01-28 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:41,391 INFO sqlalchemy.engine.base.Engine ('2011-01-29 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,394 INFO sqlalchemy.engine.base.Engine ('2011-01-30 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:41,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,395 INFO sqlalchemy.engine.base.Engine ('2011-01-31 00:00:00.000000', 0.15, 66)
2018-05-08 18:31:41,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,397 INFO sqlalchemy.engine.base.Engine ('2011-02-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:41,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,443 INFO sqlalchemy.engine.base.Engine ('2011-02-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:41,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,444 INFO sqlalchemy.engine.base.Engine ('2011-02-03 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:41,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,446 INFO sqlalchemy.engine.base.Engine ('2011-02-04 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:41,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,447 INFO sqlalchemy.engine.base.Engine ('2011-02-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,449 INFO sqlalchemy.engine.base.Engine ('2011-02-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,450 INFO sqlalchemy.engine.base.Engine ('2011-02-07 00:00:00.000000', 0.95, 67)
2018-05-08 18:31:41,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,452 INFO sqlalchemy.engine.base.Engine ('2011-02-08 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:41,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,454 INFO sqlalchemy.engine.base.Engine ('2011-02-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,456 INFO sqlalchemy.engine.base.Engine ('2011-02-10 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:41,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,458 INFO sqlalchemy.engine.base.Engine ('2011-02-11 00:00:00.000000', 0.29, 68)
2018-05-08 18:31:41,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,459 INFO sqlalchemy.engine.base.Engine ('2011-02-12 00:00:00.000000', 1.82, 72)
2018-05-08 18:31:41,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,461 INFO sqlalchemy.engine.base.Engine ('2011-02-13 00:00:00.000000', 0.71, 76)
2018-05-08 18:31:41,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,463 INFO sqlalchemy.engine.base.Engine ('2011-02-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,464 INFO sqlalchemy.engine.base.Engine ('2011-02-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,466 INFO sqlalchemy.engine.base.Engine ('2011-02-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:41,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,467 INFO sqlalchemy.engine.base.Engine ('2011-02-18 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,469 INFO sqlalchemy.engine.base.Engine ('2011-02-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,471 INFO sqlalchemy.engine.base.Engine ('2011-02-20 00:00:00.000000', 0.3, 73)
2018-05-08 18:31:41,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,472 INFO sqlalchemy.engine.base.Engine ('2011-02-21 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:41,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,474 INFO sqlalchemy.engine.base.Engine ('2011-02-22 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:41,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,476 INFO sqlalchemy.engine.base.Engine ('2011-02-23 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:41,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,477 INFO sqlalchemy.engine.base.Engine ('2011-02-24 00:00:00.000000', 1.44, 68)
2018-05-08 18:31:41,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,479 INFO sqlalchemy.engine.base.Engine ('2011-02-25 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:41,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,481 INFO sqlalchemy.engine.base.Engine ('2011-02-26 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:41,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,482 INFO sqlalchemy.engine.base.Engine ('2011-02-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,484 INFO sqlalchemy.engine.base.Engine ('2011-02-28 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:41,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,486 INFO sqlalchemy.engine.base.Engine ('2011-03-01 00:00:00.000000', 0.18, 67)
2018-05-08 18:31:41,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,488 INFO sqlalchemy.engine.base.Engine ('2011-03-02 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:41,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,489 INFO sqlalchemy.engine.base.Engine ('2011-03-03 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:41,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,491 INFO sqlalchemy.engine.base.Engine ('2011-03-04 00:00:00.000000', 1.7, 72)
2018-05-08 18:31:41,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,493 INFO sqlalchemy.engine.base.Engine ('2011-03-05 00:00:00.000000', 0.22, 69)
2018-05-08 18:31:41,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,494 INFO sqlalchemy.engine.base.Engine ('2011-03-06 00:00:00.000000', 0.27, 74)
2018-05-08 18:31:41,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,496 INFO sqlalchemy.engine.base.Engine ('2011-03-07 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:41,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,497 INFO sqlalchemy.engine.base.Engine ('2011-03-08 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:41,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,499 INFO sqlalchemy.engine.base.Engine ('2011-03-09 00:00:00.000000', 0.9, 70)
2018-05-08 18:31:41,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,500 INFO sqlalchemy.engine.base.Engine ('2011-03-10 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:41,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,502 INFO sqlalchemy.engine.base.Engine ('2011-03-11 00:00:00.000000', 0.2, 71)
2018-05-08 18:31:41,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,503 INFO sqlalchemy.engine.base.Engine ('2011-03-12 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:41,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,505 INFO sqlalchemy.engine.base.Engine ('2011-03-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,507 INFO sqlalchemy.engine.base.Engine ('2011-03-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:41,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,509 INFO sqlalchemy.engine.base.Engine ('2011-03-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,510 INFO sqlalchemy.engine.base.Engine ('2011-03-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,512 INFO sqlalchemy.engine.base.Engine ('2011-03-17 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:41,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,513 INFO sqlalchemy.engine.base.Engine ('2011-03-18 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:41,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,515 INFO sqlalchemy.engine.base.Engine ('2011-03-19 00:00:00.000000', 0.08, 73)
2018-05-08 18:31:41,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,516 INFO sqlalchemy.engine.base.Engine ('2011-03-20 00:00:00.000000', 0.23, 74)
2018-05-08 18:31:41,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,519 INFO sqlalchemy.engine.base.Engine ('2011-03-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,520 INFO sqlalchemy.engine.base.Engine ('2011-03-22 00:00:00.000000', 0.17, 73)
2018-05-08 18:31:41,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,522 INFO sqlalchemy.engine.base.Engine ('2011-03-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,523 INFO sqlalchemy.engine.base.Engine ('2011-03-24 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:41,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,525 INFO sqlalchemy.engine.base.Engine ('2011-03-25 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:41,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,527 INFO sqlalchemy.engine.base.Engine ('2011-03-26 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,529 INFO sqlalchemy.engine.base.Engine ('2011-03-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,530 INFO sqlalchemy.engine.base.Engine ('2011-03-29 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,531 INFO sqlalchemy.engine.base.Engine ('2011-03-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,533 INFO sqlalchemy.engine.base.Engine ('2011-03-31 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,534 INFO sqlalchemy.engine.base.Engine ('2011-04-01 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:41,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,536 INFO sqlalchemy.engine.base.Engine ('2011-04-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,537 INFO sqlalchemy.engine.base.Engine ('2011-04-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,539 INFO sqlalchemy.engine.base.Engine ('2011-04-04 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,541 INFO sqlalchemy.engine.base.Engine ('2011-04-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,543 INFO sqlalchemy.engine.base.Engine ('2011-04-06 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:41,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,544 INFO sqlalchemy.engine.base.Engine ('2011-04-07 00:00:00.000000', 0.5, 67)
2018-05-08 18:31:41,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,546 INFO sqlalchemy.engine.base.Engine ('2011-04-08 00:00:00.000000', 0.68, 69)
2018-05-08 18:31:41,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,548 INFO sqlalchemy.engine.base.Engine ('2011-04-09 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:41,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,550 INFO sqlalchemy.engine.base.Engine ('2011-04-10 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:41,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,551 INFO sqlalchemy.engine.base.Engine ('2011-04-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,553 INFO sqlalchemy.engine.base.Engine ('2011-04-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,555 INFO sqlalchemy.engine.base.Engine ('2011-04-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:41,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,556 INFO sqlalchemy.engine.base.Engine ('2011-04-14 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:41,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,560 INFO sqlalchemy.engine.base.Engine ('2011-04-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,562 INFO sqlalchemy.engine.base.Engine ('2011-04-16 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:41,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,563 INFO sqlalchemy.engine.base.Engine ('2011-04-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,565 INFO sqlalchemy.engine.base.Engine ('2011-04-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,566 INFO sqlalchemy.engine.base.Engine ('2011-04-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,568 INFO sqlalchemy.engine.base.Engine ('2011-04-20 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:41,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,569 INFO sqlalchemy.engine.base.Engine ('2011-04-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,571 INFO sqlalchemy.engine.base.Engine ('2011-04-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,574 INFO sqlalchemy.engine.base.Engine ('2011-04-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,576 INFO sqlalchemy.engine.base.Engine ('2011-04-24 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,578 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,580 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,581 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,582 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,584 INFO sqlalchemy.engine.base.Engine ('2011-04-29 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:41,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,586 INFO sqlalchemy.engine.base.Engine ('2011-04-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,588 INFO sqlalchemy.engine.base.Engine ('2011-05-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,589 INFO sqlalchemy.engine.base.Engine ('2011-05-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,591 INFO sqlalchemy.engine.base.Engine ('2011-05-03 00:00:00.000000', 1.03, 73)
2018-05-08 18:31:41,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,593 INFO sqlalchemy.engine.base.Engine ('2011-05-04 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:41,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,595 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,596 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:41,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,597 INFO sqlalchemy.engine.base.Engine ('2011-05-07 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:41,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,599 INFO sqlalchemy.engine.base.Engine ('2011-05-08 00:00:00.000000', 0.51, 75)
2018-05-08 18:31:41,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,601 INFO sqlalchemy.engine.base.Engine ('2011-05-09 00:00:00.000000', 0.1, 75)
2018-05-08 18:31:41,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,602 INFO sqlalchemy.engine.base.Engine ('2011-05-10 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:41,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,604 INFO sqlalchemy.engine.base.Engine ('2011-05-11 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:41,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,605 INFO sqlalchemy.engine.base.Engine ('2011-05-12 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:41,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,607 INFO sqlalchemy.engine.base.Engine ('2011-05-13 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:41,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,609 INFO sqlalchemy.engine.base.Engine ('2011-05-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,655 INFO sqlalchemy.engine.base.Engine ('2011-05-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,657 INFO sqlalchemy.engine.base.Engine ('2011-05-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,659 INFO sqlalchemy.engine.base.Engine ('2011-05-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,660 INFO sqlalchemy.engine.base.Engine ('2011-05-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:41,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,662 INFO sqlalchemy.engine.base.Engine ('2011-05-19 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:41,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,663 INFO sqlalchemy.engine.base.Engine ('2011-05-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,665 INFO sqlalchemy.engine.base.Engine ('2011-05-21 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,667 INFO sqlalchemy.engine.base.Engine ('2011-05-22 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:41,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,668 INFO sqlalchemy.engine.base.Engine ('2011-05-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,669 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,671 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,673 INFO sqlalchemy.engine.base.Engine ('2011-05-26 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,675 INFO sqlalchemy.engine.base.Engine ('2011-05-27 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:41,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,676 INFO sqlalchemy.engine.base.Engine ('2011-05-28 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:41,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,678 INFO sqlalchemy.engine.base.Engine ('2011-05-29 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:41,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,679 INFO sqlalchemy.engine.base.Engine ('2011-05-30 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,681 INFO sqlalchemy.engine.base.Engine ('2011-05-31 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:41,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,682 INFO sqlalchemy.engine.base.Engine ('2011-06-01 00:00:00.000000', 0.15, 79)
2018-05-08 18:31:41,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,684 INFO sqlalchemy.engine.base.Engine ('2011-06-02 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,685 INFO sqlalchemy.engine.base.Engine ('2011-06-03 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:41,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,687 INFO sqlalchemy.engine.base.Engine ('2011-06-04 00:00:00.000000', 0.51, 71)
2018-05-08 18:31:41,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,689 INFO sqlalchemy.engine.base.Engine ('2011-06-05 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:41,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,691 INFO sqlalchemy.engine.base.Engine ('2011-06-06 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:41,692 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,693 INFO sqlalchemy.engine.base.Engine ('2011-06-07 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:41,694 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,694 INFO sqlalchemy.engine.base.Engine ('2011-06-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,696 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,697 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,698 INFO sqlalchemy.engine.base.Engine ('2011-06-10 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,699 INFO sqlalchemy.engine.base.Engine ('2011-06-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,701 INFO sqlalchemy.engine.base.Engine ('2011-06-12 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:41,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,702 INFO sqlalchemy.engine.base.Engine ('2011-06-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,704 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,706 INFO sqlalchemy.engine.base.Engine ('2011-06-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,708 INFO sqlalchemy.engine.base.Engine ('2011-06-16 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:41,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,709 INFO sqlalchemy.engine.base.Engine ('2011-06-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,711 INFO sqlalchemy.engine.base.Engine ('2011-06-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,712 INFO sqlalchemy.engine.base.Engine ('2011-06-19 00:00:00.000000', 0.17, 79)
2018-05-08 18:31:41,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,714 INFO sqlalchemy.engine.base.Engine ('2011-06-20 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:41,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,715 INFO sqlalchemy.engine.base.Engine ('2011-06-21 00:00:00.000000', 0.38, 73)
2018-05-08 18:31:41,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,717 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 0.17, 75)
2018-05-08 18:31:41,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,718 INFO sqlalchemy.engine.base.Engine ('2011-06-23 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:41,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,720 INFO sqlalchemy.engine.base.Engine ('2011-06-24 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:41,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,721 INFO sqlalchemy.engine.base.Engine ('2011-06-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,723 INFO sqlalchemy.engine.base.Engine ('2011-06-26 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:41,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,725 INFO sqlalchemy.engine.base.Engine ('2011-06-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:41,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,727 INFO sqlalchemy.engine.base.Engine ('2011-06-28 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:41,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,728 INFO sqlalchemy.engine.base.Engine ('2011-06-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,730 INFO sqlalchemy.engine.base.Engine ('2011-06-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,731 INFO sqlalchemy.engine.base.Engine ('2011-07-01 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:41,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,733 INFO sqlalchemy.engine.base.Engine ('2011-07-02 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,734 INFO sqlalchemy.engine.base.Engine ('2011-07-03 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:41,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,736 INFO sqlalchemy.engine.base.Engine ('2011-07-04 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:41,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,738 INFO sqlalchemy.engine.base.Engine ('2011-07-05 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:41,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,739 INFO sqlalchemy.engine.base.Engine ('2011-07-06 00:00:00.000000', 0.08, 79)
2018-05-08 18:31:41,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,741 INFO sqlalchemy.engine.base.Engine ('2011-07-07 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:41,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,743 INFO sqlalchemy.engine.base.Engine ('2011-07-08 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:41,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,745 INFO sqlalchemy.engine.base.Engine ('2011-07-09 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:41,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,813 INFO sqlalchemy.engine.base.Engine ('2011-07-10 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:41,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,814 INFO sqlalchemy.engine.base.Engine ('2011-07-11 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,816 INFO sqlalchemy.engine.base.Engine ('2011-07-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,818 INFO sqlalchemy.engine.base.Engine ('2011-07-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,819 INFO sqlalchemy.engine.base.Engine ('2011-07-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,821 INFO sqlalchemy.engine.base.Engine ('2011-07-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,823 INFO sqlalchemy.engine.base.Engine ('2011-07-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,824 INFO sqlalchemy.engine.base.Engine ('2011-07-17 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:41,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,825 INFO sqlalchemy.engine.base.Engine ('2011-07-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,827 INFO sqlalchemy.engine.base.Engine ('2011-07-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,828 INFO sqlalchemy.engine.base.Engine ('2011-07-20 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:41,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,830 INFO sqlalchemy.engine.base.Engine ('2011-07-21 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,831 INFO sqlalchemy.engine.base.Engine ('2011-07-22 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:41,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,833 INFO sqlalchemy.engine.base.Engine ('2011-07-23 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:41,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,834 INFO sqlalchemy.engine.base.Engine ('2011-07-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:41,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,836 INFO sqlalchemy.engine.base.Engine ('2011-07-25 00:00:00.000000', 0.12, 76)
2018-05-08 18:31:41,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,837 INFO sqlalchemy.engine.base.Engine ('2011-07-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,839 INFO sqlalchemy.engine.base.Engine ('2011-07-27 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:41,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,840 INFO sqlalchemy.engine.base.Engine ('2011-07-28 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:41,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,843 INFO sqlalchemy.engine.base.Engine ('2011-07-29 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:41,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,844 INFO sqlalchemy.engine.base.Engine ('2011-07-30 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:41,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,846 INFO sqlalchemy.engine.base.Engine ('2011-07-31 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:41,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,847 INFO sqlalchemy.engine.base.Engine ('2011-08-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,849 INFO sqlalchemy.engine.base.Engine ('2011-08-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,850 INFO sqlalchemy.engine.base.Engine ('2011-08-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,851 INFO sqlalchemy.engine.base.Engine ('2011-08-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,853 INFO sqlalchemy.engine.base.Engine ('2011-08-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,854 INFO sqlalchemy.engine.base.Engine ('2011-08-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,856 INFO sqlalchemy.engine.base.Engine ('2011-08-07 00:00:00.000000', 0.12, 77)
2018-05-08 18:31:41,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,858 INFO sqlalchemy.engine.base.Engine ('2011-08-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,859 INFO sqlalchemy.engine.base.Engine ('2011-08-09 00:00:00.000000', 0.19, 78)
2018-05-08 18:31:41,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,861 INFO sqlalchemy.engine.base.Engine ('2011-08-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,862 INFO sqlalchemy.engine.base.Engine ('2011-08-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,864 INFO sqlalchemy.engine.base.Engine ('2011-08-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,865 INFO sqlalchemy.engine.base.Engine ('2011-08-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,867 INFO sqlalchemy.engine.base.Engine ('2011-08-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:41,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,868 INFO sqlalchemy.engine.base.Engine ('2011-08-15 00:00:00.000000', 0.5, 76)
2018-05-08 18:31:41,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,871 INFO sqlalchemy.engine.base.Engine ('2011-08-16 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,872 INFO sqlalchemy.engine.base.Engine ('2011-08-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,874 INFO sqlalchemy.engine.base.Engine ('2011-08-18 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:41,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,876 INFO sqlalchemy.engine.base.Engine ('2011-08-19 00:00:00.000000', 0.02, 83)
2018-05-08 18:31:41,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,877 INFO sqlalchemy.engine.base.Engine ('2011-08-20 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:41,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,879 INFO sqlalchemy.engine.base.Engine ('2011-08-21 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:41,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,880 INFO sqlalchemy.engine.base.Engine ('2011-08-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,920 INFO sqlalchemy.engine.base.Engine ('2011-08-23 00:00:00.000000', 0.22, 75)
2018-05-08 18:31:41,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,922 INFO sqlalchemy.engine.base.Engine ('2011-08-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,924 INFO sqlalchemy.engine.base.Engine ('2011-08-25 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:41,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,925 INFO sqlalchemy.engine.base.Engine ('2011-08-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,926 INFO sqlalchemy.engine.base.Engine ('2011-08-27 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:41,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,928 INFO sqlalchemy.engine.base.Engine ('2011-08-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,929 INFO sqlalchemy.engine.base.Engine ('2011-08-29 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:41,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,931 INFO sqlalchemy.engine.base.Engine ('2011-08-30 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:41,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,932 INFO sqlalchemy.engine.base.Engine ('2011-08-31 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:41,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,934 INFO sqlalchemy.engine.base.Engine ('2011-09-01 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:41,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,935 INFO sqlalchemy.engine.base.Engine ('2011-09-02 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:41,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,936 INFO sqlalchemy.engine.base.Engine ('2011-09-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,938 INFO sqlalchemy.engine.base.Engine ('2011-09-04 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:41,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,939 INFO sqlalchemy.engine.base.Engine ('2011-09-05 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,941 INFO sqlalchemy.engine.base.Engine ('2011-09-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:41,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,942 INFO sqlalchemy.engine.base.Engine ('2011-09-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:41,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,944 INFO sqlalchemy.engine.base.Engine ('2011-09-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,945 INFO sqlalchemy.engine.base.Engine ('2011-09-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:41,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:41,947 INFO sqlalchemy.engine.base.Engine ('2011-09-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,948 INFO sqlalchemy.engine.base.Engine ('2011-09-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,949 INFO sqlalchemy.engine.base.Engine ('2011-09-13 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:41,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,951 INFO sqlalchemy.engine.base.Engine ('2011-09-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,952 INFO sqlalchemy.engine.base.Engine ('2011-09-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,954 INFO sqlalchemy.engine.base.Engine ('2011-09-16 00:00:00.000000', 0.17, 80)
2018-05-08 18:31:41,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,955 INFO sqlalchemy.engine.base.Engine ('2011-09-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,957 INFO sqlalchemy.engine.base.Engine ('2011-09-18 00:00:00.000000', 0.2, 77)
2018-05-08 18:31:41,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,958 INFO sqlalchemy.engine.base.Engine ('2011-09-19 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:41,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,960 INFO sqlalchemy.engine.base.Engine ('2011-09-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,962 INFO sqlalchemy.engine.base.Engine ('2011-09-21 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:41,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,964 INFO sqlalchemy.engine.base.Engine ('2011-09-22 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:41,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,965 INFO sqlalchemy.engine.base.Engine ('2011-09-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,966 INFO sqlalchemy.engine.base.Engine ('2011-09-24 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:41,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,968 INFO sqlalchemy.engine.base.Engine ('2011-09-25 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:41,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,969 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:41,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,971 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,973 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:41,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,974 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,976 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:41,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,977 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:41,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,979 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:41,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,980 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 84)
2018-05-08 18:31:41,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,982 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:41,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,983 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:41,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:41,985 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:41,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,340 INFO sqlalchemy.engine.base.Engine ('2012-03-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,342 INFO sqlalchemy.engine.base.Engine ('2012-04-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,343 INFO sqlalchemy.engine.base.Engine ('2012-04-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,345 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,346 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,348 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,349 INFO sqlalchemy.engine.base.Engine ('2012-04-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,351 INFO sqlalchemy.engine.base.Engine ('2012-04-07 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:42,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,352 INFO sqlalchemy.engine.base.Engine ('2012-04-08 00:00:00.000000', 0.0, 75)

2018-05-08 18:31:42,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,354 INFO sqlalchemy.engine.base.Engine ('2012-04-09 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:42,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,356 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:42,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,357 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:42,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,359 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,361 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:42,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,362 INFO sqlalchemy.engine.base.Engine ('2012-04-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,364 INFO sqlalchemy.engine.base.Engine ('2012-04-15 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:42,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,366 INFO sqlalchemy.engine.base.Engine ('2012-04-16 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,367 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,369 INFO sqlalchemy.engine.base.Engine ('2012-04-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,371 INFO sqlalchemy.engine.base.Engine ('2012-04-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,373 INFO sqlalchemy.engine.base.Engine ('2012-04-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,374 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,374 INFO sqlalchemy.engine.base.Engine ('2012-04-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,376 INFO sqlalchemy.engine.base.Engine ('2012-04-22 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:42,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,378 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:42,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,379 INFO sqlalchemy.engine.base.Engine ('2012-04-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,381 INFO sqlalchemy.engine.base.Engine ('2012-04-25 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:42,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,383 INFO sqlalchemy.engine.base.Engine ('2012-04-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,385 INFO sqlalchemy.engine.base.Engine ('2012-04-27 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:42,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,386 INFO sqlalchemy.engine.base.Engine ('2012-04-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,387 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,388 INFO sqlalchemy.engine.base.Engine ('2012-04-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,389 INFO sqlalchemy.engine.base.Engine ('2012-04-30 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,391 INFO sqlalchemy.engine.base.Engine ('2012-05-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,393 INFO sqlalchemy.engine.base.Engine ('2012-05-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,394 INFO sqlalchemy.engine.base.Engine ('2012-05-03 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:42,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,396 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:42,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,398 INFO sqlalchemy.engine.base.Engine ('2012-05-05 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:42,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,399 INFO sqlalchemy.engine.base.Engine ('2012-05-06 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:42,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,401 INFO sqlalchemy.engine.base.Engine ('2012-05-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,403 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,404 INFO sqlalchemy.engine.base.Engine ('2012-05-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,406 INFO sqlalchemy.engine.base.Engine ('2012-05-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,408 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,409 INFO sqlalchemy.engine.base.Engine ('2012-05-12 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,411 INFO sqlalchemy.engine.base.Engine ('2012-05-13 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:42,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,412 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,414 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:42,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,415 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,417 INFO sqlalchemy.engine.base.Engine ('2012-05-17 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:42,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,419 INFO sqlalchemy.engine.base.Engine ('2012-05-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,421 INFO sqlalchemy.engine.base.Engine ('2012-05-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,423 INFO sqlalchemy.engine.base.Engine ('2012-05-20 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,424 INFO sqlalchemy.engine.base.Engine ('2012-05-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,426 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,427 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,430 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,431 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,433 INFO sqlalchemy.engine.base.Engine ('2012-05-26 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:42,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,435 INFO sqlalchemy.engine.base.Engine ('2012-05-27 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:42,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,436 INFO sqlalchemy.engine.base.Engine ('2012-05-28 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,438 INFO sqlalchemy.engine.base.Engine ('2012-05-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,439 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,441 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:42,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,443 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,444 INFO sqlalchemy.engine.base.Engine ('2012-06-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,446 INFO sqlalchemy.engine.base.Engine ('2012-06-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,447 INFO sqlalchemy.engine.base.Engine ('2012-06-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,449 INFO sqlalchemy.engine.base.Engine ('2012-06-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,450 INFO sqlalchemy.engine.base.Engine ('2012-06-06 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:42,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,452 INFO sqlalchemy.engine.base.Engine ('2012-06-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,454 INFO sqlalchemy.engine.base.Engine ('2012-06-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,455 INFO sqlalchemy.engine.base.Engine ('2012-06-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,457 INFO sqlalchemy.engine.base.Engine ('2012-06-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,458 INFO sqlalchemy.engine.base.Engine ('2012-06-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,460 INFO sqlalchemy.engine.base.Engine ('2012-06-12 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:42,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,462 INFO sqlalchemy.engine.base.Engine ('2012-06-13 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:42,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,463 INFO sqlalchemy.engine.base.Engine ('2012-06-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,465 INFO sqlalchemy.engine.base.Engine ('2012-06-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,466 INFO sqlalchemy.engine.base.Engine ('2012-06-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,468 INFO sqlalchemy.engine.base.Engine ('2012-06-17 00:00:00.000000', 0.0, 80)

2018-05-08 18:31:42,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,470 INFO sqlalchemy.engine.base.Engine ('2012-06-18 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,519 INFO sqlalchemy.engine.base.Engine ('2012-06-19 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:42,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,520 INFO sqlalchemy.engine.base.Engine ('2012-06-20 00:00:00.000000', 0.25, 72)
2018-05-08 18:31:42,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,522 INFO sqlalchemy.engine.base.Engine ('2012-06-21 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,524 INFO sqlalchemy.engine.base.Engine ('2012-06-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,525 INFO sqlalchemy.engine.base.Engine ('2012-06-23 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:42,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,527 INFO sqlalchemy.engine.base.Engine ('2012-06-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,528 INFO sqlalchemy.engine.base.Engine ('2012-06-25 00:00:00.000000', 0.51, 72)
2018-05-08 18:31:42,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,530 INFO sqlalchemy.engine.base.Engine ('2012-06-26 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:42,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,531 INFO sqlalchemy.engine.base.Engine ('2012-06-27 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:42,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,533 INFO sqlalchemy.engine.base.Engine ('2012-06-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,535 INFO sqlalchemy.engine.base.Engine ('2012-06-29 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:42,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,536 INFO sqlalchemy.engine.base.Engine ('2012-06-30 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:42,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,538 INFO sqlalchemy.engine.base.Engine ('2012-07-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,540 INFO sqlalchemy.engine.base.Engine ('2012-07-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,541 INFO sqlalchemy.engine.base.Engine ('2012-07-03 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:42,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,543 INFO sqlalchemy.engine.base.Engine ('2012-07-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,544 INFO sqlalchemy.engine.base.Engine ('2012-07-05 00:00:00.000000', 0.13, 77)
2018-05-08 18:31:42,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,546 INFO sqlalchemy.engine.base.Engine ('2012-07-06 00:00:00.000000', 0.07, 79)
2018-05-08 18:31:42,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,548 INFO sqlalchemy.engine.base.Engine ('2012-07-07 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:42,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,549 INFO sqlalchemy.engine.base.Engine ('2012-07-08 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:42,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,551 INFO sqlalchemy.engine.base.Engine ('2012-07-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,552 INFO sqlalchemy.engine.base.Engine ('2012-07-10 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,554 INFO sqlalchemy.engine.base.Engine ('2012-07-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,555 INFO sqlalchemy.engine.base.Engine ('2012-07-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,557 INFO sqlalchemy.engine.base.Engine ('2012-07-13 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,559 INFO sqlalchemy.engine.base.Engine ('2012-07-14 00:00:00.000000', 0.02, 82)
2018-05-08 18:31:42,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,560 INFO sqlalchemy.engine.base.Engine ('2012-07-15 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:42,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,563 INFO sqlalchemy.engine.base.Engine ('2012-07-16 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:42,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,564 INFO sqlalchemy.engine.base.Engine ('2012-07-17 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:42,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,566 INFO sqlalchemy.engine.base.Engine ('2012-07-18 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:42,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,568 INFO sqlalchemy.engine.base.Engine ('2012-07-19 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:42,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,569 INFO sqlalchemy.engine.base.Engine ('2012-07-20 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:42,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,571 INFO sqlalchemy.engine.base.Engine ('2012-07-21 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:42,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,573 INFO sqlalchemy.engine.base.Engine ('2012-07-22 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:42,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,574 INFO sqlalchemy.engine.base.Engine ('2012-07-23 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:42,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,576 INFO sqlalchemy.engine.base.Engine ('2012-07-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,578 INFO sqlalchemy.engine.base.Engine ('2012-07-25 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,579 INFO sqlalchemy.engine.base.Engine ('2012-07-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,581 INFO sqlalchemy.engine.base.Engine ('2012-07-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,582 INFO sqlalchemy.engine.base.Engine ('2012-07-28 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:42,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,584 INFO sqlalchemy.engine.base.Engine ('2012-07-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,585 INFO sqlalchemy.engine.base.Engine ('2012-07-30 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:42,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,587 INFO sqlalchemy.engine.base.Engine ('2012-07-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,588 INFO sqlalchemy.engine.base.Engine ('2012-08-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,590 INFO sqlalchemy.engine.base.Engine ('2012-08-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,592 INFO sqlalchemy.engine.base.Engine ('2012-08-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,593 INFO sqlalchemy.engine.base.Engine ('2012-08-04 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:42,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,595 INFO sqlalchemy.engine.base.Engine ('2012-08-05 00:00:00.000000', 0.05, 82)
2018-05-08 18:31:42,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,596 INFO sqlalchemy.engine.base.Engine ('2012-08-06 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:42,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,598 INFO sqlalchemy.engine.base.Engine ('2012-08-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,600 INFO sqlalchemy.engine.base.Engine ('2012-08-08 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:42,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,601 INFO sqlalchemy.engine.base.Engine ('2012-08-09 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:42,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,603 INFO sqlalchemy.engine.base.Engine ('2012-08-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,605 INFO sqlalchemy.engine.base.Engine ('2012-08-11 00:00:00.000000', 0.19, 73)
2018-05-08 18:31:42,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,606 INFO sqlalchemy.engine.base.Engine ('2012-08-12 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:42,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,608 INFO sqlalchemy.engine.base.Engine ('2012-08-13 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:42,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,610 INFO sqlalchemy.engine.base.Engine ('2012-08-14 00:00:00.000000', 0.09, 76)
2018-05-08 18:31:42,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,612 INFO sqlalchemy.engine.base.Engine ('2012-08-15 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,613 INFO sqlalchemy.engine.base.Engine ('2012-08-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,616 INFO sqlalchemy.engine.base.Engine ('2012-08-17 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:42,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,617 INFO sqlalchemy.engine.base.Engine ('2012-08-18 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:42,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,619 INFO sqlalchemy.engine.base.Engine ('2012-08-19 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:42,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,620 INFO sqlalchemy.engine.base.Engine ('2012-08-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,622 INFO sqlalchemy.engine.base.Engine ('2012-08-21 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:42,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,624 INFO sqlalchemy.engine.base.Engine ('2012-08-22 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:42,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,625 INFO sqlalchemy.engine.base.Engine ('2012-08-23 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,627 INFO sqlalchemy.engine.base.Engine ('2012-08-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,628 INFO sqlalchemy.engine.base.Engine ('2012-08-25 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,630 INFO sqlalchemy.engine.base.Engine ('2012-08-26 00:00:00.000000', 0.01, 78)

2018-05-08 18:31:42,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,632 INFO sqlalchemy.engine.base.Engine ('2012-08-27 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:42,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,633 INFO sqlalchemy.engine.base.Engine ('2012-08-28 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:42,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,635 INFO sqlalchemy.engine.base.Engine ('2012-08-29 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:42,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,637 INFO sqlalchemy.engine.base.Engine ('2012-08-30 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:42,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,638 INFO sqlalchemy.engine.base.Engine ('2012-08-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,640 INFO sqlalchemy.engine.base.Engine ('2012-09-01 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:42,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,641 INFO sqlalchemy.engine.base.Engine ('2012-09-02 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:42,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,643 INFO sqlalchemy.engine.base.Engine ('2012-09-03 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:42,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,645 INFO sqlalchemy.engine.base.Engine ('2012-09-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,646 INFO sqlalchemy.engine.base.Engine ('2012-09-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,648 INFO sqlalchemy.engine.base.Engine ('2012-09-06 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:42,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,649 INFO sqlalchemy.engine.base.Engine ('2012-09-07 00:00:00.000000', 0.02, 82)
2018-05-08 18:31:42,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,651 INFO sqlalchemy.engine.base.Engine ('2012-09-08 00:00:00.000000', 0.14, 79)
2018-05-08 18:31:42,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,652 INFO sqlalchemy.engine.base.Engine ('2012-09-09 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:42,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,654 INFO sqlalchemy.engine.base.Engine ('2012-09-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,656 INFO sqlalchemy.engine.base.Engine ('2012-09-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,657 INFO sqlalchemy.engine.base.Engine ('2012-09-12 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:42,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,658 INFO sqlalchemy.engine.base.Engine ('2012-09-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,660 INFO sqlalchemy.engine.base.Engine ('2012-09-14 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:42,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,661 INFO sqlalchemy.engine.base.Engine ('2012-09-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,663 INFO sqlalchemy.engine.base.Engine ('2012-09-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,664 INFO sqlalchemy.engine.base.Engine ('2012-09-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,666 INFO sqlalchemy.engine.base.Engine ('2012-09-18 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:42,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,667 INFO sqlalchemy.engine.base.Engine ('2012-09-19 00:00:00.000000', 0.27, 75)
2018-05-08 18:31:42,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,669 INFO sqlalchemy.engine.base.Engine ('2012-09-20 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:42,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,670 INFO sqlalchemy.engine.base.Engine ('2012-09-21 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:42,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,671 INFO sqlalchemy.engine.base.Engine ('2012-09-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,673 INFO sqlalchemy.engine.base.Engine ('2012-09-23 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:42,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,675 INFO sqlalchemy.engine.base.Engine ('2012-09-24 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:42,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,677 INFO sqlalchemy.engine.base.Engine ('2012-09-25 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:42,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,678 INFO sqlalchemy.engine.base.Engine ('2012-09-26 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:42,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,726 INFO sqlalchemy.engine.base.Engine ('2012-09-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,728 INFO sqlalchemy.engine.base.Engine ('2012-09-28 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,729 INFO sqlalchemy.engine.base.Engine ('2012-09-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,731 INFO sqlalchemy.engine.base.Engine ('2012-09-30 00:00:00.000000', 0.04, 77)

2018-05-08 18:31:42,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,732 INFO sqlalchemy.engine.base.Engine ('2012-10-01 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:42,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,734 INFO sqlalchemy.engine.base.Engine ('2012-10-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,736 INFO sqlalchemy.engine.base.Engine ('2012-10-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,737 INFO sqlalchemy.engine.base.Engine ('2012-10-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,739 INFO sqlalchemy.engine.base.Engine ('2012-10-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,740 INFO sqlalchemy.engine.base.Engine ('2012-10-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,742 INFO sqlalchemy.engine.base.Engine ('2012-10-07 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:42,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,743 INFO sqlalchemy.engine.base.Engine ('2012-10-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,745 INFO sqlalchemy.engine.base.Engine ('2012-10-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,746 INFO sqlalchemy.engine.base.Engine ('2012-10-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,748 INFO sqlalchemy.engine.base.Engine ('2012-10-11 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:42,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,749 INFO sqlalchemy.engine.base.Engine ('2012-10-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,751 INFO sqlalchemy.engine.base.Engine ('2012-10-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,752 INFO sqlalchemy.engine.base.Engine ('2012-10-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,754 INFO sqlalchemy.engine.base.Engine ('2012-10-15 00:00:00.000000', 0.2, 76)
2018-05-08 18:31:42,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,755 INFO sqlalchemy.engine.base.Engine ('2012-10-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,757 INFO sqlalchemy.engine.base.Engine ('2012-10-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:42,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,758 INFO sqlalchemy.engine.base.Engine ('2012-10-18 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:42,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,760 INFO sqlalchemy.engine.base.Engine ('2012-10-19 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:42,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,761 INFO sqlalchemy.engine.base.Engine ('2012-10-20 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,762 INFO sqlalchemy.engine.base.Engine ('2012-10-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,764 INFO sqlalchemy.engine.base.Engine ('2012-10-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,765 INFO sqlalchemy.engine.base.Engine ('2012-10-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,767 INFO sqlalchemy.engine.base.Engine ('2012-10-24 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:42,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,768 INFO sqlalchemy.engine.base.Engine ('2012-10-25 00:00:00.000000', 0.82, 73)
2018-05-08 18:31:42,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,770 INFO sqlalchemy.engine.base.Engine ('2012-10-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,771 INFO sqlalchemy.engine.base.Engine ('2012-10-27 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,773 INFO sqlalchemy.engine.base.Engine ('2012-10-28 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:42,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,774 INFO sqlalchemy.engine.base.Engine ('2012-10-29 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:42,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,776 INFO sqlalchemy.engine.base.Engine ('2012-10-30 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:42,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,777 INFO sqlalchemy.engine.base.Engine ('2012-11-02 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:42,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,779 INFO sqlalchemy.engine.base.Engine ('2012-11-03 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,780 INFO sqlalchemy.engine.base.Engine ('2012-11-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:42,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,782 INFO sqlalchemy.engine.base.Engine ('2012-11-05 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,783 INFO sqlalchemy.engine.base.Engine ('2012-11-06 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:42,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,785 INFO sqlalchemy.engine.base.Engine ('2012-11-07 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:42,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,786 INFO sqlalchemy.engine.base.Engine ('2012-11-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,788 INFO sqlalchemy.engine.base.Engine ('2012-11-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,790 INFO sqlalchemy.engine.base.Engine ('2012-11-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,791 INFO sqlalchemy.engine.base.Engine ('2012-11-11 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:42,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,793 INFO sqlalchemy.engine.base.Engine ('2012-11-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,795 INFO sqlalchemy.engine.base.Engine ('2012-11-13 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:42,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,796 INFO sqlalchemy.engine.base.Engine ('2012-11-14 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:42,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,798 INFO sqlalchemy.engine.base.Engine ('2012-11-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,799 INFO sqlalchemy.engine.base.Engine ('2012-11-17 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:42,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,801 INFO sqlalchemy.engine.base.Engine ('2012-11-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,802 INFO sqlalchemy.engine.base.Engine ('2012-11-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,804 INFO sqlalchemy.engine.base.Engine ('2012-11-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,805 INFO sqlalchemy.engine.base.Engine ('2012-11-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,807 INFO sqlalchemy.engine.base.Engine ('2012-11-22 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:42,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,808 INFO sqlalchemy.engine.base.Engine ('2012-11-23 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:42,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,810 INFO sqlalchemy.engine.base.Engine ('2012-11-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,811 INFO sqlalchemy.engine.base.Engine ('2012-11-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:42,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,812 INFO sqlalchemy.engine.base.Engine ('2012-11-26 00:00:00.000000', 0.16, 72)
2018-05-08 18:31:42,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,814 INFO sqlalchemy.engine.base.Engine ('2012-11-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,816 INFO sqlalchemy.engine.base.Engine ('2012-11-28 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:42,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,819 INFO sqlalchemy.engine.base.Engine ('2012-11-29 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:42,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,820 INFO sqlalchemy.engine.base.Engine ('2012-11-30 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:42,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,822 INFO sqlalchemy.engine.base.Engine ('2012-12-01 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:42,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,824 INFO sqlalchemy.engine.base.Engine ('2012-12-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,825 INFO sqlalchemy.engine.base.Engine ('2012-12-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,827 INFO sqlalchemy.engine.base.Engine ('2012-12-04 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:42,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,828 INFO sqlalchemy.engine.base.Engine ('2012-12-05 00:00:00.000000', 1.02, 72)
2018-05-08 18:31:42,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,830 INFO sqlalchemy.engine.base.Engine ('2012-12-06 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:42,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,832 INFO sqlalchemy.engine.base.Engine ('2012-12-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,833 INFO sqlalchemy.engine.base.Engine ('2012-12-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,835 INFO sqlalchemy.engine.base.Engine ('2012-12-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,836 INFO sqlalchemy.engine.base.Engine ('2012-12-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,838 INFO sqlalchemy.engine.base.Engine ('2012-12-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,839 INFO sqlalchemy.engine.base.Engine ('2012-12-12 00:00:00.000000', 0.04, 73)

2018-05-08 18:31:42,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,841 INFO sqlalchemy.engine.base.Engine ('2012-12-13 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:42,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,842 INFO sqlalchemy.engine.base.Engine ('2012-12-14 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:42,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,844 INFO sqlalchemy.engine.base.Engine ('2012-12-15 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:42,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,845 INFO sqlalchemy.engine.base.Engine ('2012-12-16 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:42,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,847 INFO sqlalchemy.engine.base.Engine ('2012-12-17 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:42,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,848 INFO sqlalchemy.engine.base.Engine ('2012-12-18 00:00:00.000000', 0.22, 77)
2018-05-08 18:31:42,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,849 INFO sqlalchemy.engine.base.Engine ('2012-12-19 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:42,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,851 INFO sqlalchemy.engine.base.Engine ('2012-12-20 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:42,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,853 INFO sqlalchemy.engine.base.Engine ('2012-12-21 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:42,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,854 INFO sqlalchemy.engine.base.Engine ('2012-12-22 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,856 INFO sqlalchemy.engine.base.Engine ('2012-12-23 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:42,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,857 INFO sqlalchemy.engine.base.Engine ('2012-12-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:42,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,858 INFO sqlalchemy.engine.base.Engine ('2012-12-25 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:42,859 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,860 INFO sqlalchemy.engine.base.Engine ('2012-12-26 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:42,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,861 INFO sqlalchemy.engine.base.Engine ('2012-12-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,862 INFO sqlalchemy.engine.base.Engine ('2012-12-28 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:42,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,864 INFO sqlalchemy.engine.base.Engine ('2012-12-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:42,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,865 INFO sqlalchemy.engine.base.Engine ('2012-12-30 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:42,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,867 INFO sqlalchemy.engine.base.Engine ('2012-12-31 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:42,868 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,868 INFO sqlalchemy.engine.base.Engine ('2013-01-01 00:00:00.000000', 0.38, 72)
2018-05-08 18:31:42,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,870 INFO sqlalchemy.engine.base.Engine ('2013-01-02 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:42,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,871 INFO sqlalchemy.engine.base.Engine ('2013-01-03 00:00:00.000000', 0.43, 69)
2018-05-08 18:31:42,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,873 INFO sqlalchemy.engine.base.Engine ('2013-01-04 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:42,874 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,875 INFO sqlalchemy.engine.base.Engine ('2013-01-05 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:42,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,876 INFO sqlalchemy.engine.base.Engine ('2013-01-06 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:42,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,878 INFO sqlalchemy.engine.base.Engine ('2013-01-07 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:42,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,928 INFO sqlalchemy.engine.base.Engine ('2013-01-08 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:42,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,929 INFO sqlalchemy.engine.base.Engine ('2013-01-09 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:42,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,931 INFO sqlalchemy.engine.base.Engine ('2013-01-10 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:42,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,932 INFO sqlalchemy.engine.base.Engine ('2013-01-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,934 INFO sqlalchemy.engine.base.Engine ('2013-01-12 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:42,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,935 INFO sqlalchemy.engine.base.Engine ('2013-01-13 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:42,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,937 INFO sqlalchemy.engine.base.Engine ('2013-01-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,938 INFO sqlalchemy.engine.base.Engine ('2013-01-15 00:00:00.000000', 1.07, 73)
2018-05-08 18:31:42,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,939 INFO sqlalchemy.engine.base.Engine ('2013-01-16 00:00:00.000000', 0.0, 56)

2018-05-08 18:31:42,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,941 INFO sqlalchemy.engine.base.Engine ('2013-01-17 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:42,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,942 INFO sqlalchemy.engine.base.Engine ('2013-01-18 00:00:00.000000', 0.01, 61)
2018-05-08 18:31:42,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,944 INFO sqlalchemy.engine.base.Engine ('2013-01-19 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:42,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,945 INFO sqlalchemy.engine.base.Engine ('2013-01-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,947 INFO sqlalchemy.engine.base.Engine ('2013-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:42,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,948 INFO sqlalchemy.engine.base.Engine ('2013-01-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,950 INFO sqlalchemy.engine.base.Engine ('2013-01-25 00:00:00.000000', 0.43, 63)
2018-05-08 18:31:42,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,952 INFO sqlalchemy.engine.base.Engine ('2013-01-26 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:42,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,953 INFO sqlalchemy.engine.base.Engine ('2013-01-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:42,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,955 INFO sqlalchemy.engine.base.Engine ('2013-01-28 00:00:00.000000', 2.48, 65)
2018-05-08 18:31:42,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,956 INFO sqlalchemy.engine.base.Engine ('2013-01-29 00:00:00.000000', 0.61, 66)
2018-05-08 18:31:42,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,957 INFO sqlalchemy.engine.base.Engine ('2013-01-30 00:00:00.000000', 0.03, 63)
2018-05-08 18:31:42,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,959 INFO sqlalchemy.engine.base.Engine ('2013-01-31 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:42,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,961 INFO sqlalchemy.engine.base.Engine ('2013-02-01 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:42,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,962 INFO sqlalchemy.engine.base.Engine ('2013-02-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:42,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,964 INFO sqlalchemy.engine.base.Engine ('2013-02-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:42,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,966 INFO sqlalchemy.engine.base.Engine ('2013-02-04 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:42,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,967 INFO sqlalchemy.engine.base.Engine ('2013-02-05 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:42,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,969 INFO sqlalchemy.engine.base.Engine ('2013-02-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:42,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,970 INFO sqlalchemy.engine.base.Engine ('2013-02-07 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:42,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,972 INFO sqlalchemy.engine.base.Engine ('2013-02-08 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:42,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,974 INFO sqlalchemy.engine.base.Engine ('2013-02-09 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:42,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,975 INFO sqlalchemy.engine.base.Engine ('2013-02-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,977 INFO sqlalchemy.engine.base.Engine ('2013-02-11 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:42,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,978 INFO sqlalchemy.engine.base.Engine ('2013-02-12 00:00:00.000000', 0.06, 68)
2018-05-08 18:31:42,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,980 INFO sqlalchemy.engine.base.Engine ('2013-02-13 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,981 INFO sqlalchemy.engine.base.Engine ('2013-02-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:42,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,983 INFO sqlalchemy.engine.base.Engine ('2013-02-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:42,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,984 INFO sqlalchemy.engine.base.Engine ('2013-02-16 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:42,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,986 INFO sqlalchemy.engine.base.Engine ('2013-02-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,987 INFO sqlalchemy.engine.base.Engine ('2013-02-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:42,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,989 INFO sqlalchemy.engine.base.Engine ('2013-02-19 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:42,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,991 INFO sqlalchemy.engine.base.Engine ('2013-02-20 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:42,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,992 INFO sqlalchemy.engine.base.Engine ('2013-02-21 00:00:00.000000', 0.13, 70)
2018-05-08 18:31:42,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,994 INFO sqlalchemy.engine.base.Engine ('2013-02-22 00:00:00.000000', 0.25, 71)

2018-05-08 18:31:42,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,995 INFO sqlalchemy.engine.base.Engine ('2013-02-23 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:42,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,997 INFO sqlalchemy.engine.base.Engine ('2013-02-24 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:42,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:42,998 INFO sqlalchemy.engine.base.Engine ('2013-02-25 00:00:00.000000', 0.07, 70)
2018-05-08 18:31:42,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,000 INFO sqlalchemy.engine.base.Engine ('2013-02-26 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:43,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,002 INFO sqlalchemy.engine.base.Engine ('2013-02-27 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:43,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,003 INFO sqlalchemy.engine.base.Engine ('2013-02-28 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:43,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,005 INFO sqlalchemy.engine.base.Engine ('2013-03-01 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:43,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,006 INFO sqlalchemy.engine.base.Engine ('2013-03-02 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:43,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,008 INFO sqlalchemy.engine.base.Engine ('2013-03-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:43,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,009 INFO sqlalchemy.engine.base.Engine ('2013-03-04 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:43,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,010 INFO sqlalchemy.engine.base.Engine ('2013-03-05 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:43,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,012 INFO sqlalchemy.engine.base.Engine ('2013-03-06 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:43,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,013 INFO sqlalchemy.engine.base.Engine ('2013-03-07 00:00:00.000000', 0.04, 67)
2018-05-08 18:31:43,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,015 INFO sqlalchemy.engine.base.Engine ('2013-03-08 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:43,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,016 INFO sqlalchemy.engine.base.Engine ('2013-03-09 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:43,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,018 INFO sqlalchemy.engine.base.Engine ('2013-03-10 00:00:00.000000', 1.11, 68)
2018-05-08 18:31:43,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,019 INFO sqlalchemy.engine.base.Engine ('2013-03-11 00:00:00.000000', 1.02, 60)
2018-05-08 18:31:43,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,021 INFO sqlalchemy.engine.base.Engine ('2013-03-12 00:00:00.000000', 0.02, 65)
2018-05-08 18:31:43,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,023 INFO sqlalchemy.engine.base.Engine ('2013-03-13 00:00:00.000000', 0.06, 67)
2018-05-08 18:31:43,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,025 INFO sqlalchemy.engine.base.Engine ('2013-03-14 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:43,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,026 INFO sqlalchemy.engine.base.Engine ('2013-03-15 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:43,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,028 INFO sqlalchemy.engine.base.Engine ('2013-03-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:43,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,029 INFO sqlalchemy.engine.base.Engine ('2013-03-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,031 INFO sqlalchemy.engine.base.Engine ('2013-03-18 00:00:00.000000', 0.09, 57)
2018-05-08 18:31:43,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,032 INFO sqlalchemy.engine.base.Engine ('2013-03-19 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:43,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,034 INFO sqlalchemy.engine.base.Engine ('2013-03-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:43,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,036 INFO sqlalchemy.engine.base.Engine ('2013-03-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:43,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,037 INFO sqlalchemy.engine.base.Engine ('2013-03-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:43,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,039 INFO sqlalchemy.engine.base.Engine ('2013-03-23 00:00:00.000000', 0.59, 67)
2018-05-08 18:31:43,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,041 INFO sqlalchemy.engine.base.Engine ('2013-03-26 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:43,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,042 INFO sqlalchemy.engine.base.Engine ('2013-03-27 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:43,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,044 INFO sqlalchemy.engine.base.Engine ('2013-03-28 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:43,045 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,046 INFO sqlalchemy.engine.base.Engine ('2013-03-29 00:00:00.000000', 0.15, 73)
2018-05-08 18:31:43,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,047 INFO sqlalchemy.engine.base.Engine ('2013-03-30 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:43,048 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,049 INFO sqlalchemy.engine.base.Engine ('2013-03-31 00:00:00.000000', 0.02, 69)

2018-05-08 18:31:43,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,050 INFO sqlalchemy.engine.base.Engine ('2013-04-01 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:43,051 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,052 INFO sqlalchemy.engine.base.Engine ('2013-04-02 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:43,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,053 INFO sqlalchemy.engine.base.Engine ('2013-04-03 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:43,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,055 INFO sqlalchemy.engine.base.Engine ('2013-04-04 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:43,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,056 INFO sqlalchemy.engine.base.Engine ('2013-04-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,057 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,058 INFO sqlalchemy.engine.base.Engine ('2013-04-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,059 INFO sqlalchemy.engine.base.Engine ('2013-04-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,061 INFO sqlalchemy.engine.base.Engine ('2013-04-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,063 INFO sqlalchemy.engine.base.Engine ('2013-04-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,064 INFO sqlalchemy.engine.base.Engine ('2013-04-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:43,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,066 INFO sqlalchemy.engine.base.Engine ('2013-04-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,067 INFO sqlalchemy.engine.base.Engine ('2013-04-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,069 INFO sqlalchemy.engine.base.Engine ('2013-04-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,070 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,071 INFO sqlalchemy.engine.base.Engine ('2013-04-14 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,072 INFO sqlalchemy.engine.base.Engine ('2013-04-15 00:00:00.000000', 0.44, 71)
2018-05-08 18:31:43,073 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,074 INFO sqlalchemy.engine.base.Engine ('2013-04-16 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:43,075 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,076 INFO sqlalchemy.engine.base.Engine ('2013-04-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,077 INFO sqlalchemy.engine.base.Engine ('2013-04-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,078 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,079 INFO sqlalchemy.engine.base.Engine ('2013-04-19 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:43,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,080 INFO sqlalchemy.engine.base.Engine ('2013-04-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:43,081 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,082 INFO sqlalchemy.engine.base.Engine ('2013-04-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:43,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,126 INFO sqlalchemy.engine.base.Engine ('2013-04-22 00:00:00.000000', 0.35, 71)
2018-05-08 18:31:43,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,127 INFO sqlalchemy.engine.base.Engine ('2013-04-23 00:00:00.000000', 0.34, 75)
2018-05-08 18:31:43,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,129 INFO sqlalchemy.engine.base.Engine ('2013-04-24 00:00:00.000000', 2.05, 69)
2018-05-08 18:31:43,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,130 INFO sqlalchemy.engine.base.Engine ('2013-04-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:43,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,132 INFO sqlalchemy.engine.base.Engine ('2013-04-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,133 INFO sqlalchemy.engine.base.Engine ('2013-04-29 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,135 INFO sqlalchemy.engine.base.Engine ('2013-04-30 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,136 INFO sqlalchemy.engine.base.Engine ('2013-05-01 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,138 INFO sqlalchemy.engine.base.Engine ('2013-05-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,139 INFO sqlalchemy.engine.base.Engine ('2013-05-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,141 INFO sqlalchemy.engine.base.Engine ('2013-05-04 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:43,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,142 INFO sqlalchemy.engine.base.Engine ('2013-05-05 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:43,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,144 INFO sqlalchemy.engine.base.Engine ('2013-05-06 00:00:00.000000', 1.24, 72)
2018-05-08 18:31:43,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,145 INFO sqlalchemy.engine.base.Engine ('2013-05-07 00:00:00.000000', 0.04, 74)

2018-05-08 18:31:43,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,146 INFO sqlalchemy.engine.base.Engine ('2013-05-08 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,148 INFO sqlalchemy.engine.base.Engine ('2013-05-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:43,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,149 INFO sqlalchemy.engine.base.Engine ('2013-05-10 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:43,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,151 INFO sqlalchemy.engine.base.Engine ('2013-05-11 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:43,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,152 INFO sqlalchemy.engine.base.Engine ('2013-05-12 00:00:00.000000', 0.4, 70)
2018-05-08 18:31:43,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,154 INFO sqlalchemy.engine.base.Engine ('2013-05-13 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:43,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,156 INFO sqlalchemy.engine.base.Engine ('2013-05-14 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:43,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,157 INFO sqlalchemy.engine.base.Engine ('2013-05-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:43,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,159 INFO sqlalchemy.engine.base.Engine ('2013-05-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:43,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,160 INFO sqlalchemy.engine.base.Engine ('2013-05-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,161 INFO sqlalchemy.engine.base.Engine ('2013-05-18 00:00:00.000000', 0.13, 78)
2018-05-08 18:31:43,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,163 INFO sqlalchemy.engine.base.Engine ('2013-05-19 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:43,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,164 INFO sqlalchemy.engine.base.Engine ('2013-05-20 00:00:00.000000', 1.96, 70)
2018-05-08 18:31:43,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,165 INFO sqlalchemy.engine.base.Engine ('2013-05-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:43,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,167 INFO sqlalchemy.engine.base.Engine ('2013-05-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,169 INFO sqlalchemy.engine.base.Engine ('2013-05-23 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:43,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,170 INFO sqlalchemy.engine.base.Engine ('2013-05-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,172 INFO sqlalchemy.engine.base.Engine ('2013-05-25 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:43,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,173 INFO sqlalchemy.engine.base.Engine ('2013-05-26 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:43,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,175 INFO sqlalchemy.engine.base.Engine ('2013-05-27 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,176 INFO sqlalchemy.engine.base.Engine ('2013-05-28 00:00:00.000000', 0.1, 78)
2018-05-08 18:31:43,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,178 INFO sqlalchemy.engine.base.Engine ('2013-05-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:43,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,179 INFO sqlalchemy.engine.base.Engine ('2013-05-30 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,181 INFO sqlalchemy.engine.base.Engine ('2013-05-31 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,182 INFO sqlalchemy.engine.base.Engine ('2013-06-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,184 INFO sqlalchemy.engine.base.Engine ('2013-06-02 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:43,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,185 INFO sqlalchemy.engine.base.Engine ('2013-06-03 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:43,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,187 INFO sqlalchemy.engine.base.Engine ('2013-06-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,188 INFO sqlalchemy.engine.base.Engine ('2013-06-05 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,190 INFO sqlalchemy.engine.base.Engine ('2013-06-06 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,191 INFO sqlalchemy.engine.base.Engine ('2013-06-07 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:43,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,192 INFO sqlalchemy.engine.base.Engine ('2013-06-08 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,194 INFO sqlalchemy.engine.base.Engine ('2013-06-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,195 INFO sqlalchemy.engine.base.Engine ('2013-06-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:43,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,197 INFO sqlalchemy.engine.base.Engine ('2013-06-11 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:43,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,198 INFO sqlalchemy.engine.base.Engine ('2013-06-12 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:43,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,200 INFO sqlalchemy.engine.base.Engine ('2013-06-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,201 INFO sqlalchemy.engine.base.Engine ('2013-06-14 00:00:00.000000', 0.28, 75)
2018-05-08 18:31:43,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,202 INFO sqlalchemy.engine.base.Engine ('2013-06-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,204 INFO sqlalchemy.engine.base.Engine ('2013-06-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:43,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,205 INFO sqlalchemy.engine.base.Engine ('2013-06-17 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,207 INFO sqlalchemy.engine.base.Engine ('2013-06-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,208 INFO sqlalchemy.engine.base.Engine ('2013-06-19 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,210 INFO sqlalchemy.engine.base.Engine ('2013-06-20 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:43,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,212 INFO sqlalchemy.engine.base.Engine ('2013-06-21 00:00:00.000000', 0.32, 73)
2018-05-08 18:31:43,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,213 INFO sqlalchemy.engine.base.Engine ('2013-06-22 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:43,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,214 INFO sqlalchemy.engine.base.Engine ('2013-06-23 00:00:00.000000', 0.08, 74)
2018-05-08 18:31:43,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,216 INFO sqlalchemy.engine.base.Engine ('2013-06-24 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:43,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,217 INFO sqlalchemy.engine.base.Engine ('2013-06-25 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:43,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,219 INFO sqlalchemy.engine.base.Engine ('2013-06-26 00:00:00.000000', 0.42, 73)
2018-05-08 18:31:43,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,220 INFO sqlalchemy.engine.base.Engine ('2013-06-27 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:43,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,222 INFO sqlalchemy.engine.base.Engine ('2013-06-29 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:43,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,224 INFO sqlalchemy.engine.base.Engine ('2013-06-30 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,225 INFO sqlalchemy.engine.base.Engine ('2013-07-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:43,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,227 INFO sqlalchemy.engine.base.Engine ('2013-07-02 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:43,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,229 INFO sqlalchemy.engine.base.Engine ('2013-07-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,230 INFO sqlalchemy.engine.base.Engine ('2013-07-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,232 INFO sqlalchemy.engine.base.Engine ('2013-07-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:43,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,233 INFO sqlalchemy.engine.base.Engine ('2013-07-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:43,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,235 INFO sqlalchemy.engine.base.Engine ('2013-07-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,236 INFO sqlalchemy.engine.base.Engine ('2013-07-08 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:43,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,238 INFO sqlalchemy.engine.base.Engine ('2013-07-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,239 INFO sqlalchemy.engine.base.Engine ('2013-07-10 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:43,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,241 INFO sqlalchemy.engine.base.Engine ('2013-07-11 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:43,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,242 INFO sqlalchemy.engine.base.Engine ('2013-07-12 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:43,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,244 INFO sqlalchemy.engine.base.Engine ('2013-07-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,245 INFO sqlalchemy.engine.base.Engine ('2013-07-14 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:43,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,247 INFO sqlalchemy.engine.base.Engine ('2013-07-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,248 INFO sqlalchemy.engine.base.Engine ('2013-07-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,250 INFO sqlalchemy.engine.base.Engine ('2013-07-17 00:00:00.000000', 0.0, 77)

2018-05-08 18:31:43,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,252 INFO sqlalchemy.engine.base.Engine ('2013-07-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,254 INFO sqlalchemy.engine.base.Engine ('2013-07-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,255 INFO sqlalchemy.engine.base.Engine ('2013-07-20 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,256 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,257 INFO sqlalchemy.engine.base.Engine ('2013-07-21 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,258 INFO sqlalchemy.engine.base.Engine ('2013-07-22 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:43,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,260 INFO sqlalchemy.engine.base.Engine ('2013-07-23 00:00:00.000000', 0.2, 74)
2018-05-08 18:31:43,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,261 INFO sqlalchemy.engine.base.Engine ('2013-07-24 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:43,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,263 INFO sqlalchemy.engine.base.Engine ('2013-07-25 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:43,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,265 INFO sqlalchemy.engine.base.Engine ('2013-07-26 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,266 INFO sqlalchemy.engine.base.Engine ('2013-07-29 00:00:00.000000', 0.2, 77)
2018-05-08 18:31:43,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,268 INFO sqlalchemy.engine.base.Engine ('2013-07-30 00:00:00.000000', 0.27, 79)
2018-05-08 18:31:43,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,269 INFO sqlalchemy.engine.base.Engine ('2013-07-31 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:43,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,271 INFO sqlalchemy.engine.base.Engine ('2013-08-01 00:00:00.000000', 0.15, 77)
2018-05-08 18:31:43,272 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,272 INFO sqlalchemy.engine.base.Engine ('2013-08-02 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:43,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,273 INFO sqlalchemy.engine.base.Engine ('2013-08-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,275 INFO sqlalchemy.engine.base.Engine ('2013-08-04 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,316 INFO sqlalchemy.engine.base.Engine ('2013-08-05 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,317 INFO sqlalchemy.engine.base.Engine ('2013-08-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,319 INFO sqlalchemy.engine.base.Engine ('2013-08-07 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,320 INFO sqlalchemy.engine.base.Engine ('2013-08-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,322 INFO sqlalchemy.engine.base.Engine ('2013-08-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,323 INFO sqlalchemy.engine.base.Engine ('2013-08-10 00:00:00.000000', 1.67, 73)
2018-05-08 18:31:43,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,325 INFO sqlalchemy.engine.base.Engine ('2013-08-11 00:00:00.000000', 0.42, 82)
2018-05-08 18:31:43,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,327 INFO sqlalchemy.engine.base.Engine ('2013-08-12 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:43,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,328 INFO sqlalchemy.engine.base.Engine ('2013-08-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:43,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,330 INFO sqlalchemy.engine.base.Engine ('2013-08-14 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:43,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,331 INFO sqlalchemy.engine.base.Engine ('2013-08-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:43,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,333 INFO sqlalchemy.engine.base.Engine ('2013-08-16 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:43,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,334 INFO sqlalchemy.engine.base.Engine ('2013-08-17 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:43,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,336 INFO sqlalchemy.engine.base.Engine ('2013-08-18 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:43,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,338 INFO sqlalchemy.engine.base.Engine ('2013-08-19 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:43,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,339 INFO sqlalchemy.engine.base.Engine ('2013-08-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:43,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,341 INFO sqlalchemy.engine.base.Engine ('2013-08-21 00:00:00.000000', 0.43, 73)
2018-05-08 18:31:43,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,342 INFO sqlalchemy.engine.base.Engine ('2013-08-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:43,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:43,344 INFO sqlalchemy.engine.base.Engine ('2013-08-23 00:00:00.000000', 0.0, 74)

2018-05-08 18:31:44,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,101 INFO sqlalchemy.engine.base.Engine ('2014-11-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,103 INFO sqlalchemy.engine.base.Engine ('2014-11-15 00:00:00.000000', 0.65, 76)
2018-05-08 18:31:44,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,104 INFO sqlalchemy.engine.base.Engine ('2014-11-16 00:00:00.000000', 0.36, 73)
2018-05-08 18:31:44,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,106 INFO sqlalchemy.engine.base.Engine ('2014-11-17 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:44,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,107 INFO sqlalchemy.engine.base.Engine ('2014-11-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,109 INFO sqlalchemy.engine.base.Engine ('2014-11-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,111 INFO sqlalchemy.engine.base.Engine ('2014-11-23 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,112 INFO sqlalchemy.engine.base.Engine ('2014-11-24 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:44,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,114 INFO sqlalchemy.engine.base.Engine ('2014-11-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,115 INFO sqlalchemy.engine.base.Engine ('2014-11-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,117 INFO sqlalchemy.engine.base.Engine ('2014-11-29 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:44,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,119 INFO sqlalchemy.engine.base.Engine ('2014-11-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,121 INFO sqlalchemy.engine.base.Engine ('2014-12-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,122 INFO sqlalchemy.engine.base.Engine ('2014-12-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,124 INFO sqlalchemy.engine.base.Engine ('2014-12-03 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:44,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,125 INFO sqlalchemy.engine.base.Engine ('2014-12-04 00:00:00.000000', 1.02, 72)
2018-05-08 18:31:44,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,127 INFO sqlalchemy.engine.base.Engine ('2014-12-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,129 INFO sqlalchemy.engine.base.Engine ('2014-12-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,130 INFO sqlalchemy.engine.base.Engine ('2014-12-07 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,132 INFO sqlalchemy.engine.base.Engine ('2014-12-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,134 INFO sqlalchemy.engine.base.Engine ('2014-12-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,135 INFO sqlalchemy.engine.base.Engine ('2014-12-10 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,137 INFO sqlalchemy.engine.base.Engine ('2014-12-11 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:44,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,139 INFO sqlalchemy.engine.base.Engine ('2014-12-12 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:44,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,140 INFO sqlalchemy.engine.base.Engine ('2014-12-13 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:44,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,142 INFO sqlalchemy.engine.base.Engine ('2014-12-14 00:00:00.000000', 0.2, 71)
2018-05-08 18:31:44,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,143 INFO sqlalchemy.engine.base.Engine ('2014-12-15 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:44,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,145 INFO sqlalchemy.engine.base.Engine ('2014-12-16 00:00:00.000000', 0.05, 74)
2018-05-08 18:31:44,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,147 INFO sqlalchemy.engine.base.Engine ('2014-12-17 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:44,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,148 INFO sqlalchemy.engine.base.Engine ('2014-12-18 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,150 INFO sqlalchemy.engine.base.Engine ('2014-12-19 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,151 INFO sqlalchemy.engine.base.Engine ('2014-12-20 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,153 INFO sqlalchemy.engine.base.Engine ('2014-12-23 00:00:00.000000', 1.52, 71)
2018-05-08 18:31:44,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,155 INFO sqlalchemy.engine.base.Engine ('2014-12-24 00:00:00.000000', 1.01, 68)
2018-05-08 18:31:44,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,157 INFO sqlalchemy.engine.base.Engine ('2014-12-25 00:00:00.000000', 0.53, 66)

2018-05-08 18:31:44,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,158 INFO sqlalchemy.engine.base.Engine ('2014-12-26 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:44,159 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,160 INFO sqlalchemy.engine.base.Engine ('2014-12-27 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:44,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,162 INFO sqlalchemy.engine.base.Engine ('2014-12-28 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,163 INFO sqlalchemy.engine.base.Engine ('2014-12-29 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,164 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,165 INFO sqlalchemy.engine.base.Engine ('2014-12-30 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:44,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,167 INFO sqlalchemy.engine.base.Engine ('2014-12-31 00:00:00.000000', 0.63, 56)
2018-05-08 18:31:44,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,168 INFO sqlalchemy.engine.base.Engine ('2015-01-01 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:44,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,170 INFO sqlalchemy.engine.base.Engine ('2015-01-02 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,171 INFO sqlalchemy.engine.base.Engine ('2015-01-03 00:00:00.000000', 1.23, 69)
2018-05-08 18:31:44,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,173 INFO sqlalchemy.engine.base.Engine ('2015-01-04 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:44,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,175 INFO sqlalchemy.engine.base.Engine ('2015-01-05 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:44,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,176 INFO sqlalchemy.engine.base.Engine ('2015-01-06 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,179 INFO sqlalchemy.engine.base.Engine ('2015-01-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,180 INFO sqlalchemy.engine.base.Engine ('2015-01-08 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,182 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,182 INFO sqlalchemy.engine.base.Engine ('2015-01-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,184 INFO sqlalchemy.engine.base.Engine ('2015-01-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,185 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,186 INFO sqlalchemy.engine.base.Engine ('2015-01-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,187 INFO sqlalchemy.engine.base.Engine ('2015-01-12 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:44,188 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,189 INFO sqlalchemy.engine.base.Engine ('2015-01-13 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:44,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,191 INFO sqlalchemy.engine.base.Engine ('2015-01-14 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,193 INFO sqlalchemy.engine.base.Engine ('2015-01-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,195 INFO sqlalchemy.engine.base.Engine ('2015-01-16 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:44,196 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,196 INFO sqlalchemy.engine.base.Engine ('2015-01-17 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,198 INFO sqlalchemy.engine.base.Engine ('2015-01-18 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,200 INFO sqlalchemy.engine.base.Engine ('2015-01-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,202 INFO sqlalchemy.engine.base.Engine ('2015-01-20 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:44,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,204 INFO sqlalchemy.engine.base.Engine ('2015-01-21 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:44,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,206 INFO sqlalchemy.engine.base.Engine ('2015-01-22 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:44,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,207 INFO sqlalchemy.engine.base.Engine ('2015-01-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,209 INFO sqlalchemy.engine.base.Engine ('2015-01-24 00:00:00.000000', 0.47, 72)
2018-05-08 18:31:44,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,210 INFO sqlalchemy.engine.base.Engine ('2015-01-25 00:00:00.000000', 0.59, 67)
2018-05-08 18:31:44,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,212 INFO sqlalchemy.engine.base.Engine ('2015-01-26 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:44,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,213 INFO sqlalchemy.engine.base.Engine ('2015-01-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,215 INFO sqlalchemy.engine.base.Engine ('2015-01-28 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:44,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,217 INFO sqlalchemy.engine.base.Engine ('2015-01-29 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:44,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,219 INFO sqlalchemy.engine.base.Engine ('2015-01-30 00:00:00.000000', 0.01, 63)
2018-05-08 18:31:44,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,220 INFO sqlalchemy.engine.base.Engine ('2015-01-31 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:44,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,222 INFO sqlalchemy.engine.base.Engine ('2015-02-01 00:00:00.000000', 0.04, 66)
2018-05-08 18:31:44,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,224 INFO sqlalchemy.engine.base.Engine ('2015-02-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,225 INFO sqlalchemy.engine.base.Engine ('2015-02-05 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:44,226 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,227 INFO sqlalchemy.engine.base.Engine ('2015-02-06 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,229 INFO sqlalchemy.engine.base.Engine ('2015-02-07 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,231 INFO sqlalchemy.engine.base.Engine ('2015-02-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,232 INFO sqlalchemy.engine.base.Engine ('2015-02-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,233 INFO sqlalchemy.engine.base.Engine ('2015-02-10 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:44,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,235 INFO sqlalchemy.engine.base.Engine ('2015-02-11 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:44,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,236 INFO sqlalchemy.engine.base.Engine ('2015-02-12 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:44,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,238 INFO sqlalchemy.engine.base.Engine ('2015-02-13 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,239 INFO sqlalchemy.engine.base.Engine ('2015-02-14 00:00:00.000000', 0.22, 74)
2018-05-08 18:31:44,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,241 INFO sqlalchemy.engine.base.Engine ('2015-02-15 00:00:00.000000', 0.97, 67)
2018-05-08 18:31:44,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,242 INFO sqlalchemy.engine.base.Engine ('2015-02-16 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:44,243 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,243 INFO sqlalchemy.engine.base.Engine ('2015-02-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,245 INFO sqlalchemy.engine.base.Engine ('2015-02-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:44,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,247 INFO sqlalchemy.engine.base.Engine ('2015-02-21 00:00:00.000000', 0.73, 73)
2018-05-08 18:31:44,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,248 INFO sqlalchemy.engine.base.Engine ('2015-02-22 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,250 INFO sqlalchemy.engine.base.Engine ('2015-02-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,251 INFO sqlalchemy.engine.base.Engine ('2015-02-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,252 INFO sqlalchemy.engine.base.Engine ('2015-02-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,254 INFO sqlalchemy.engine.base.Engine ('2015-02-26 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:44,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,256 INFO sqlalchemy.engine.base.Engine ('2015-02-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,257 INFO sqlalchemy.engine.base.Engine ('2015-02-28 00:00:00.000000', 1.08, 71)
2018-05-08 18:31:44,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,259 INFO sqlalchemy.engine.base.Engine ('2015-03-01 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:44,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,260 INFO sqlalchemy.engine.base.Engine ('2015-03-02 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:44,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,262 INFO sqlalchemy.engine.base.Engine ('2015-03-03 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:44,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,263 INFO sqlalchemy.engine.base.Engine ('2015-03-04 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:44,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,313 INFO sqlalchemy.engine.base.Engine ('2015-03-05 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:44,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,314 INFO sqlalchemy.engine.base.Engine ('2015-03-06 00:00:00.000000', 0.1, 68)
2018-05-08 18:31:44,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,316 INFO sqlalchemy.engine.base.Engine ('2015-03-07 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:44,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,317 INFO sqlalchemy.engine.base.Engine ('2015-03-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,319 INFO sqlalchemy.engine.base.Engine ('2015-03-09 00:00:00.000000', 0.03, 63)

2018-05-08 18:31:44,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,320 INFO sqlalchemy.engine.base.Engine ('2015-03-10 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:44,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,321 INFO sqlalchemy.engine.base.Engine ('2015-03-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,323 INFO sqlalchemy.engine.base.Engine ('2015-03-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,324 INFO sqlalchemy.engine.base.Engine ('2015-03-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,326 INFO sqlalchemy.engine.base.Engine ('2015-03-16 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:44,327 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,328 INFO sqlalchemy.engine.base.Engine ('2015-03-17 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:44,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,329 INFO sqlalchemy.engine.base.Engine ('2015-03-18 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:44,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,330 INFO sqlalchemy.engine.base.Engine ('2015-03-19 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:44,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,332 INFO sqlalchemy.engine.base.Engine ('2015-03-20 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,333 INFO sqlalchemy.engine.base.Engine ('2015-03-21 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:44,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,335 INFO sqlalchemy.engine.base.Engine ('2015-03-22 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:44,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,337 INFO sqlalchemy.engine.base.Engine ('2015-03-23 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,338 INFO sqlalchemy.engine.base.Engine ('2015-03-26 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,340 INFO sqlalchemy.engine.base.Engine ('2015-03-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,341 INFO sqlalchemy.engine.base.Engine ('2015-03-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,343 INFO sqlalchemy.engine.base.Engine ('2015-03-29 00:00:00.000000', 1.94, 75)
2018-05-08 18:31:44,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,344 INFO sqlalchemy.engine.base.Engine ('2015-03-30 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:44,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,346 INFO sqlalchemy.engine.base.Engine ('2015-03-31 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:44,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,347 INFO sqlalchemy.engine.base.Engine ('2015-04-01 00:00:00.000000', 0.25, 78)
2018-05-08 18:31:44,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,349 INFO sqlalchemy.engine.base.Engine ('2015-04-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,350 INFO sqlalchemy.engine.base.Engine ('2015-04-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,352 INFO sqlalchemy.engine.base.Engine ('2015-04-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,353 INFO sqlalchemy.engine.base.Engine ('2015-04-05 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,355 INFO sqlalchemy.engine.base.Engine ('2015-04-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,356 INFO sqlalchemy.engine.base.Engine ('2015-04-07 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,357 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,358 INFO sqlalchemy.engine.base.Engine ('2015-04-08 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:44,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,359 INFO sqlalchemy.engine.base.Engine ('2015-04-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,362 INFO sqlalchemy.engine.base.Engine ('2015-04-12 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,363 INFO sqlalchemy.engine.base.Engine ('2015-04-13 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,365 INFO sqlalchemy.engine.base.Engine ('2015-04-14 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:44,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,366 INFO sqlalchemy.engine.base.Engine ('2015-04-15 00:00:00.000000', 0.02, 76)
2018-05-08 18:31:44,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,368 INFO sqlalchemy.engine.base.Engine ('2015-04-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,369 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,369 INFO sqlalchemy.engine.base.Engine ('2015-04-17 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:44,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,371 INFO sqlalchemy.engine.base.Engine ('2015-04-18 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,373 INFO sqlalchemy.engine.base.Engine ('2015-04-19 00:00:00.000000', 0.03, 74)

2018-05-08 18:31:44,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,374 INFO sqlalchemy.engine.base.Engine ('2015-04-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,376 INFO sqlalchemy.engine.base.Engine ('2015-04-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,378 INFO sqlalchemy.engine.base.Engine ('2015-04-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,379 INFO sqlalchemy.engine.base.Engine ('2015-04-23 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:44,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,380 INFO sqlalchemy.engine.base.Engine ('2015-04-24 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:44,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,382 INFO sqlalchemy.engine.base.Engine ('2015-04-25 00:00:00.000000', 0.05, 81)
2018-05-08 18:31:44,383 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,384 INFO sqlalchemy.engine.base.Engine ('2015-04-26 00:00:00.000000', 0.02, 81)
2018-05-08 18:31:44,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,385 INFO sqlalchemy.engine.base.Engine ('2015-04-27 00:00:00.000000', 3.62, 73)
2018-05-08 18:31:44,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,387 INFO sqlalchemy.engine.base.Engine ('2015-04-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,388 INFO sqlalchemy.engine.base.Engine ('2015-05-01 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:44,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,390 INFO sqlalchemy.engine.base.Engine ('2015-05-02 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,391 INFO sqlalchemy.engine.base.Engine ('2015-05-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,392 INFO sqlalchemy.engine.base.Engine ('2015-05-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,394 INFO sqlalchemy.engine.base.Engine ('2015-05-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,395 INFO sqlalchemy.engine.base.Engine ('2015-05-06 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,397 INFO sqlalchemy.engine.base.Engine ('2015-05-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,398 INFO sqlalchemy.engine.base.Engine ('2015-05-08 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:44,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,399 INFO sqlalchemy.engine.base.Engine ('2015-05-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,401 INFO sqlalchemy.engine.base.Engine ('2015-05-10 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,403 INFO sqlalchemy.engine.base.Engine ('2015-05-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,404 INFO sqlalchemy.engine.base.Engine ('2015-05-12 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,406 INFO sqlalchemy.engine.base.Engine ('2015-05-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,407 INFO sqlalchemy.engine.base.Engine ('2015-05-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,409 INFO sqlalchemy.engine.base.Engine ('2015-05-15 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,411 INFO sqlalchemy.engine.base.Engine ('2015-05-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,413 INFO sqlalchemy.engine.base.Engine ('2015-05-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,414 INFO sqlalchemy.engine.base.Engine ('2015-05-18 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,415 INFO sqlalchemy.engine.base.Engine ('2015-05-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,417 INFO sqlalchemy.engine.base.Engine ('2015-05-20 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,419 INFO sqlalchemy.engine.base.Engine ('2015-05-21 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:44,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,420 INFO sqlalchemy.engine.base.Engine ('2015-05-22 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:44,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,421 INFO sqlalchemy.engine.base.Engine ('2015-05-23 00:00:00.000000', 1.32, 75)
2018-05-08 18:31:44,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,423 INFO sqlalchemy.engine.base.Engine ('2015-05-24 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,424 INFO sqlalchemy.engine.base.Engine ('2015-05-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,426 INFO sqlalchemy.engine.base.Engine ('2015-05-26 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:44,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,427 INFO sqlalchemy.engine.base.Engine ('2015-05-27 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:44,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,429 INFO sqlalchemy.engine.base.Engine ('2015-05-28 00:00:00.000000', 0.68, 73)
2018-05-08 18:31:44,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,431 INFO sqlalchemy.engine.base.Engine ('2015-05-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,432 INFO sqlalchemy.engine.base.Engine ('2015-05-30 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:44,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,433 INFO sqlalchemy.engine.base.Engine ('2015-05-31 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,435 INFO sqlalchemy.engine.base.Engine ('2015-06-01 00:00:00.000000', 0.13, 77)
2018-05-08 18:31:44,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,436 INFO sqlalchemy.engine.base.Engine ('2015-06-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,438 INFO sqlalchemy.engine.base.Engine ('2015-06-03 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,439 INFO sqlalchemy.engine.base.Engine ('2015-06-04 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:44,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,441 INFO sqlalchemy.engine.base.Engine ('2015-06-05 00:00:00.000000', 0.01, 75)
2018-05-08 18:31:44,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,442 INFO sqlalchemy.engine.base.Engine ('2015-06-06 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,444 INFO sqlalchemy.engine.base.Engine ('2015-06-07 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,445 INFO sqlalchemy.engine.base.Engine ('2015-06-08 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:44,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,447 INFO sqlalchemy.engine.base.Engine ('2015-06-09 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:44,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,448 INFO sqlalchemy.engine.base.Engine ('2015-06-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,449 INFO sqlalchemy.engine.base.Engine ('2015-06-11 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,451 INFO sqlalchemy.engine.base.Engine ('2015-06-12 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,453 INFO sqlalchemy.engine.base.Engine ('2015-06-13 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,454 INFO sqlalchemy.engine.base.Engine ('2015-06-14 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,456 INFO sqlalchemy.engine.base.Engine ('2015-06-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,457 INFO sqlalchemy.engine.base.Engine ('2015-06-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,458 INFO sqlalchemy.engine.base.Engine ('2015-06-17 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:44,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,460 INFO sqlalchemy.engine.base.Engine ('2015-06-18 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:44,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,461 INFO sqlalchemy.engine.base.Engine ('2015-06-19 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,463 INFO sqlalchemy.engine.base.Engine ('2015-06-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,508 INFO sqlalchemy.engine.base.Engine ('2015-06-21 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,510 INFO sqlalchemy.engine.base.Engine ('2015-06-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,511 INFO sqlalchemy.engine.base.Engine ('2015-06-23 00:00:00.000000', 0.05, 79)
2018-05-08 18:31:44,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,512 INFO sqlalchemy.engine.base.Engine ('2015-06-24 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,514 INFO sqlalchemy.engine.base.Engine ('2015-06-25 00:00:00.000000', 0.14, 77)
2018-05-08 18:31:44,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,515 INFO sqlalchemy.engine.base.Engine ('2015-06-26 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,516 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,517 INFO sqlalchemy.engine.base.Engine ('2015-06-27 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,518 INFO sqlalchemy.engine.base.Engine ('2015-06-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,520 INFO sqlalchemy.engine.base.Engine ('2015-07-01 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:44,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,521 INFO sqlalchemy.engine.base.Engine ('2015-07-02 00:00:00.000000', 0.0, 80)

2018-05-08 18:31:44,522 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,523 INFO sqlalchemy.engine.base.Engine ('2015-07-07 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:44,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,524 INFO sqlalchemy.engine.base.Engine ('2015-07-08 00:00:00.000000', 0.26, 79)
2018-05-08 18:31:44,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,526 INFO sqlalchemy.engine.base.Engine ('2015-07-09 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,528 INFO sqlalchemy.engine.base.Engine ('2015-07-10 00:00:00.000000', 0.3, 78)
2018-05-08 18:31:44,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,530 INFO sqlalchemy.engine.base.Engine ('2015-07-11 00:00:00.000000', 0.22, 77)
2018-05-08 18:31:44,530 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,531 INFO sqlalchemy.engine.base.Engine ('2015-07-12 00:00:00.000000', 0.43, 78)
2018-05-08 18:31:44,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,532 INFO sqlalchemy.engine.base.Engine ('2015-07-13 00:00:00.000000', 0.06, 78)
2018-05-08 18:31:44,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,534 INFO sqlalchemy.engine.base.Engine ('2015-07-14 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:44,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,536 INFO sqlalchemy.engine.base.Engine ('2015-07-15 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,537 INFO sqlalchemy.engine.base.Engine ('2015-07-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,539 INFO sqlalchemy.engine.base.Engine ('2015-07-17 00:00:00.000000', 0.13, 79)
2018-05-08 18:31:44,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,540 INFO sqlalchemy.engine.base.Engine ('2015-07-18 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,542 INFO sqlalchemy.engine.base.Engine ('2015-07-19 00:00:00.000000', 0.11, 82)
2018-05-08 18:31:44,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,543 INFO sqlalchemy.engine.base.Engine ('2015-07-20 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,544 INFO sqlalchemy.engine.base.Engine ('2015-07-21 00:00:00.000000', 0.0, 83)
2018-05-08 18:31:44,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,546 INFO sqlalchemy.engine.base.Engine ('2015-07-24 00:00:00.000000', 0.18, 78)
2018-05-08 18:31:44,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,548 INFO sqlalchemy.engine.base.Engine ('2015-07-25 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,549 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,549 INFO sqlalchemy.engine.base.Engine ('2015-07-26 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:44,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,551 INFO sqlalchemy.engine.base.Engine ('2015-07-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,552 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,552 INFO sqlalchemy.engine.base.Engine ('2015-07-28 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,554 INFO sqlalchemy.engine.base.Engine ('2015-07-29 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,554 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,555 INFO sqlalchemy.engine.base.Engine ('2015-07-30 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:44,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,557 INFO sqlalchemy.engine.base.Engine ('2015-07-31 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,557 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,558 INFO sqlalchemy.engine.base.Engine ('2015-08-01 00:00:00.000000', 0.16, 79)
2018-05-08 18:31:44,559 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,560 INFO sqlalchemy.engine.base.Engine ('2015-08-02 00:00:00.000000', 0.01, 84)
2018-05-08 18:31:44,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,561 INFO sqlalchemy.engine.base.Engine ('2015-08-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,562 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,563 INFO sqlalchemy.engine.base.Engine ('2015-08-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,564 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,565 INFO sqlalchemy.engine.base.Engine ('2015-08-05 00:00:00.000000', 0.1, 81)
2018-05-08 18:31:44,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,566 INFO sqlalchemy.engine.base.Engine ('2015-08-06 00:00:00.000000', 0.13, 80)
2018-05-08 18:31:44,567 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,568 INFO sqlalchemy.engine.base.Engine ('2015-08-07 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:44,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,569 INFO sqlalchemy.engine.base.Engine ('2015-08-08 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:44,570 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,571 INFO sqlalchemy.engine.base.Engine ('2015-08-09 00:00:00.000000', 0.09, 77)
2018-05-08 18:31:44,572 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,572 INFO sqlalchemy.engine.base.Engine ('2015-08-10 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:44,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,574 INFO sqlalchemy.engine.base.Engine ('2015-08-11 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,575 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,575 INFO sqlalchemy.engine.base.Engine ('2015-08-12 00:00:00.000000', 0.0, 81)

2018-05-08 18:31:44,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,577 INFO sqlalchemy.engine.base.Engine ('2015-08-13 00:00:00.000000', 0.06, 83)
2018-05-08 18:31:44,578 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,578 INFO sqlalchemy.engine.base.Engine ('2015-08-14 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,581 INFO sqlalchemy.engine.base.Engine ('2015-08-15 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,582 INFO sqlalchemy.engine.base.Engine ('2015-08-16 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,583 INFO sqlalchemy.engine.base.Engine ('2015-08-17 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:44,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,585 INFO sqlalchemy.engine.base.Engine ('2015-08-18 00:00:00.000000', 1.14, 76)
2018-05-08 18:31:44,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,586 INFO sqlalchemy.engine.base.Engine ('2015-08-19 00:00:00.000000', 0.42, 75)
2018-05-08 18:31:44,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,588 INFO sqlalchemy.engine.base.Engine ('2015-08-20 00:00:00.000000', 1.05, 75)
2018-05-08 18:31:44,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,589 INFO sqlalchemy.engine.base.Engine ('2015-08-23 00:00:00.000000', 0.07, 81)
2018-05-08 18:31:44,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,591 INFO sqlalchemy.engine.base.Engine ('2015-08-24 00:00:00.000000', 3.43, 74)
2018-05-08 18:31:44,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,593 INFO sqlalchemy.engine.base.Engine ('2015-08-25 00:00:00.000000', 0.12, 80)
2018-05-08 18:31:44,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,595 INFO sqlalchemy.engine.base.Engine ('2015-08-26 00:00:00.000000', 0.5, 76)
2018-05-08 18:31:44,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,596 INFO sqlalchemy.engine.base.Engine ('2015-08-27 00:00:00.000000', 2.29, 76)
2018-05-08 18:31:44,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,598 INFO sqlalchemy.engine.base.Engine ('2015-08-28 00:00:00.000000', 0.12, 79)
2018-05-08 18:31:44,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,599 INFO sqlalchemy.engine.base.Engine ('2015-08-29 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:44,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,601 INFO sqlalchemy.engine.base.Engine ('2015-08-30 00:00:00.000000', 0.02, 80)
2018-05-08 18:31:44,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,602 INFO sqlalchemy.engine.base.Engine ('2015-08-31 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,604 INFO sqlalchemy.engine.base.Engine ('2015-09-01 00:00:00.000000', 0.09, 79)
2018-05-08 18:31:44,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,605 INFO sqlalchemy.engine.base.Engine ('2015-09-04 00:00:00.000000', 0.81, 84)
2018-05-08 18:31:44,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,607 INFO sqlalchemy.engine.base.Engine ('2015-09-07 00:00:00.000000', 0.48, 80)
2018-05-08 18:31:44,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,609 INFO sqlalchemy.engine.base.Engine ('2015-09-08 00:00:00.000000', 1.16, 77)
2018-05-08 18:31:44,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,610 INFO sqlalchemy.engine.base.Engine ('2015-09-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,612 INFO sqlalchemy.engine.base.Engine ('2015-09-10 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,613 INFO sqlalchemy.engine.base.Engine ('2015-09-11 00:00:00.000000', 0.55, 82)
2018-05-08 18:31:44,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,615 INFO sqlalchemy.engine.base.Engine ('2015-09-12 00:00:00.000000', 2.28, 83)
2018-05-08 18:31:44,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,616 INFO sqlalchemy.engine.base.Engine ('2015-09-13 00:00:00.000000', 0.07, 80)
2018-05-08 18:31:44,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,618 INFO sqlalchemy.engine.base.Engine ('2015-09-14 00:00:00.000000', 0.31, 77)
2018-05-08 18:31:44,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,619 INFO sqlalchemy.engine.base.Engine ('2015-09-15 00:00:00.000000', 1.17, 77)
2018-05-08 18:31:44,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,621 INFO sqlalchemy.engine.base.Engine ('2015-09-16 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:44,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,622 INFO sqlalchemy.engine.base.Engine ('2015-09-17 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:44,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,624 INFO sqlalchemy.engine.base.Engine ('2015-09-18 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,625 INFO sqlalchemy.engine.base.Engine ('2015-09-19 00:00:00.000000', 0.0, 81)
2018-05-08 18:31:44,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,627 INFO sqlalchemy.engine.base.Engine ('2015-09-20 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:44,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,628 INFO sqlalchemy.engine.base.Engine ('2015-09-21 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:44,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,630 INFO sqlalchemy.engine.base.Engine ('2015-09-22 00:00:00.000000', 0.11, 80)

2018-05-08 18:31:44,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,631 INFO sqlalchemy.engine.base.Engine ('2015-09-23 00:00:00.000000', 0.03, 79)
2018-05-08 18:31:44,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,633 INFO sqlalchemy.engine.base.Engine ('2015-09-24 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:44,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,634 INFO sqlalchemy.engine.base.Engine ('2015-09-25 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:44,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,636 INFO sqlalchemy.engine.base.Engine ('2015-09-26 00:00:00.000000', 0.01, 80)
2018-05-08 18:31:44,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,638 INFO sqlalchemy.engine.base.Engine ('2015-09-27 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:44,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,639 INFO sqlalchemy.engine.base.Engine ('2015-09-28 00:00:00.000000', 0.14, 78)
2018-05-08 18:31:44,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,641 INFO sqlalchemy.engine.base.Engine ('2015-09-29 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:44,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,642 INFO sqlalchemy.engine.base.Engine ('2015-10-03 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,644 INFO sqlalchemy.engine.base.Engine ('2015-10-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,645 INFO sqlalchemy.engine.base.Engine ('2015-10-05 00:00:00.000000', 0.65, 76)
2018-05-08 18:31:44,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,648 INFO sqlalchemy.engine.base.Engine ('2015-10-06 00:00:00.000000', 0.55, 77)
2018-05-08 18:31:44,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,649 INFO sqlalchemy.engine.base.Engine ('2015-10-07 00:00:00.000000', 0.12, 73)
2018-05-08 18:31:44,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,651 INFO sqlalchemy.engine.base.Engine ('2015-10-08 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,652 INFO sqlalchemy.engine.base.Engine ('2015-10-09 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:44,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,654 INFO sqlalchemy.engine.base.Engine ('2015-10-12 00:00:00.000000', 0.56, 76)
2018-05-08 18:31:44,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,655 INFO sqlalchemy.engine.base.Engine ('2015-10-13 00:00:00.000000', 2.24, 76)
2018-05-08 18:31:44,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,657 INFO sqlalchemy.engine.base.Engine ('2015-10-14 00:00:00.000000', 1.42, 75)
2018-05-08 18:31:44,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,658 INFO sqlalchemy.engine.base.Engine ('2015-10-15 00:00:00.000000', 0.75, 74)
2018-05-08 18:31:44,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,660 INFO sqlalchemy.engine.base.Engine ('2015-10-16 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:44,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,662 INFO sqlalchemy.engine.base.Engine ('2015-10-17 00:00:00.000000', 0.15, 79)
2018-05-08 18:31:44,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,697 INFO sqlalchemy.engine.base.Engine ('2015-10-18 00:00:00.000000', 0.05, 81)
2018-05-08 18:31:44,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,698 INFO sqlalchemy.engine.base.Engine ('2015-10-21 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:44,699 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,700 INFO sqlalchemy.engine.base.Engine ('2015-10-22 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:44,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,702 INFO sqlalchemy.engine.base.Engine ('2015-10-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,703 INFO sqlalchemy.engine.base.Engine ('2015-10-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,705 INFO sqlalchemy.engine.base.Engine ('2015-10-25 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,705 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,706 INFO sqlalchemy.engine.base.Engine ('2015-10-26 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:44,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,708 INFO sqlalchemy.engine.base.Engine ('2015-10-27 00:00:00.000000', 0.33, 77)
2018-05-08 18:31:44,708 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,709 INFO sqlalchemy.engine.base.Engine ('2015-10-28 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,711 INFO sqlalchemy.engine.base.Engine ('2015-10-29 00:00:00.000000', 0.64, 70)
2018-05-08 18:31:44,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,712 INFO sqlalchemy.engine.base.Engine ('2015-10-30 00:00:00.000000', 0.11, 73)
2018-05-08 18:31:44,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,714 INFO sqlalchemy.engine.base.Engine ('2015-10-31 00:00:00.000000', 0.04, 80)
2018-05-08 18:31:44,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,715 INFO sqlalchemy.engine.base.Engine ('2015-11-01 00:00:00.000000', 0.17, 81)
2018-05-08 18:31:44,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,717 INFO sqlalchemy.engine.base.Engine ('2015-11-02 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,719 INFO sqlalchemy.engine.base.Engine ('2015-11-03 00:00:00.000000', 0.0, 78)

2018-05-08 18:31:44,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,721 INFO sqlalchemy.engine.base.Engine ('2015-11-04 00:00:00.000000', 0.13, 76)
2018-05-08 18:31:44,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,723 INFO sqlalchemy.engine.base.Engine ('2015-11-05 00:00:00.000000', 0.15, 76)
2018-05-08 18:31:44,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,724 INFO sqlalchemy.engine.base.Engine ('2015-11-06 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,726 INFO sqlalchemy.engine.base.Engine ('2015-11-07 00:00:00.000000', 0.21, 76)
2018-05-08 18:31:44,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,727 INFO sqlalchemy.engine.base.Engine ('2015-11-08 00:00:00.000000', 0.05, 81)
2018-05-08 18:31:44,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,729 INFO sqlalchemy.engine.base.Engine ('2015-11-09 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:44,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,730 INFO sqlalchemy.engine.base.Engine ('2015-11-12 00:00:00.000000', 0.03, 80)
2018-05-08 18:31:44,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,732 INFO sqlalchemy.engine.base.Engine ('2015-11-13 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:44,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,733 INFO sqlalchemy.engine.base.Engine ('2015-11-14 00:00:00.000000', 0.12, 77)
2018-05-08 18:31:44,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,735 INFO sqlalchemy.engine.base.Engine ('2015-11-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,736 INFO sqlalchemy.engine.base.Engine ('2015-11-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,738 INFO sqlalchemy.engine.base.Engine ('2015-11-17 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,739 INFO sqlalchemy.engine.base.Engine ('2015-11-18 00:00:00.000000', 0.23, 74)
2018-05-08 18:31:44,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,740 INFO sqlalchemy.engine.base.Engine ('2015-11-19 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:44,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,742 INFO sqlalchemy.engine.base.Engine ('2015-11-20 00:00:00.000000', 1.75, 73)
2018-05-08 18:31:44,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,743 INFO sqlalchemy.engine.base.Engine ('2015-11-21 00:00:00.000000', 2.3, 79)
2018-05-08 18:31:44,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,745 INFO sqlalchemy.engine.base.Engine ('2015-11-22 00:00:00.000000', 1.84, 76)
2018-05-08 18:31:44,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,747 INFO sqlalchemy.engine.base.Engine ('2015-11-23 00:00:00.000000', 1.1, 75)
2018-05-08 18:31:44,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,748 INFO sqlalchemy.engine.base.Engine ('2015-11-24 00:00:00.000000', 1.12, 73)
2018-05-08 18:31:44,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,750 INFO sqlalchemy.engine.base.Engine ('2015-11-25 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:44,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,751 INFO sqlalchemy.engine.base.Engine ('2015-11-26 00:00:00.000000', 0.58, 76)
2018-05-08 18:31:44,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,753 INFO sqlalchemy.engine.base.Engine ('2015-11-27 00:00:00.000000', 0.49, 76)
2018-05-08 18:31:44,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,755 INFO sqlalchemy.engine.base.Engine ('2015-11-28 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:44,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,756 INFO sqlalchemy.engine.base.Engine ('2015-11-29 00:00:00.000000', 0.14, 79)
2018-05-08 18:31:44,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,758 INFO sqlalchemy.engine.base.Engine ('2015-11-30 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:44,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,759 INFO sqlalchemy.engine.base.Engine ('2015-12-03 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:44,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,761 INFO sqlalchemy.engine.base.Engine ('2015-12-04 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,762 INFO sqlalchemy.engine.base.Engine ('2015-12-05 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,764 INFO sqlalchemy.engine.base.Engine ('2015-12-08 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:44,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,765 INFO sqlalchemy.engine.base.Engine ('2015-12-09 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:44,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,767 INFO sqlalchemy.engine.base.Engine ('2015-12-10 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:44,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,769 INFO sqlalchemy.engine.base.Engine ('2015-12-11 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:44,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,770 INFO sqlalchemy.engine.base.Engine ('2015-12-12 00:00:00.000000', 0.41, 72)
2018-05-08 18:31:44,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,771 INFO sqlalchemy.engine.base.Engine ('2015-12-13 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:44,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,773 INFO sqlalchemy.engine.base.Engine ('2015-12-14 00:00:00.000000', 0.03, 69)

2018-05-08 18:31:44,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,774 INFO sqlalchemy.engine.base.Engine ('2015-12-15 00:00:00.000000', 0.28, 75)
2018-05-08 18:31:44,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,775 INFO sqlalchemy.engine.base.Engine ('2015-12-16 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,777 INFO sqlalchemy.engine.base.Engine ('2015-12-17 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:44,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,779 INFO sqlalchemy.engine.base.Engine ('2015-12-18 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:44,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,780 INFO sqlalchemy.engine.base.Engine ('2015-12-19 00:00:00.000000', 0.24, 76)
2018-05-08 18:31:44,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,782 INFO sqlalchemy.engine.base.Engine ('2015-12-20 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:44,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,783 INFO sqlalchemy.engine.base.Engine ('2015-12-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,784 INFO sqlalchemy.engine.base.Engine ('2015-12-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,786 INFO sqlalchemy.engine.base.Engine ('2015-12-25 00:00:00.000000', 0.23, 79)
2018-05-08 18:31:44,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,787 INFO sqlalchemy.engine.base.Engine ('2015-12-26 00:00:00.000000', 0.15, 75)
2018-05-08 18:31:44,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,789 INFO sqlalchemy.engine.base.Engine ('2015-12-27 00:00:00.000000', 0.48, 76)
2018-05-08 18:31:44,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,791 INFO sqlalchemy.engine.base.Engine ('2015-12-28 00:00:00.000000', 0.05, 76)
2018-05-08 18:31:44,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,792 INFO sqlalchemy.engine.base.Engine ('2015-12-29 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:44,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,794 INFO sqlalchemy.engine.base.Engine ('2016-01-01 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:44,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,795 INFO sqlalchemy.engine.base.Engine ('2016-01-02 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:44,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,796 INFO sqlalchemy.engine.base.Engine ('2016-01-03 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,798 INFO sqlalchemy.engine.base.Engine ('2016-01-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,800 INFO sqlalchemy.engine.base.Engine ('2016-01-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,802 INFO sqlalchemy.engine.base.Engine ('2016-01-08 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:44,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,803 INFO sqlalchemy.engine.base.Engine ('2016-01-09 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,805 INFO sqlalchemy.engine.base.Engine ('2016-01-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:44,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,806 INFO sqlalchemy.engine.base.Engine ('2016-01-11 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:44,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,808 INFO sqlalchemy.engine.base.Engine ('2016-01-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,809 INFO sqlalchemy.engine.base.Engine ('2016-01-13 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:44,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,810 INFO sqlalchemy.engine.base.Engine ('2016-01-14 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:44,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,812 INFO sqlalchemy.engine.base.Engine ('2016-01-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,813 INFO sqlalchemy.engine.base.Engine ('2016-01-16 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,815 INFO sqlalchemy.engine.base.Engine ('2016-01-17 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,816 INFO sqlalchemy.engine.base.Engine ('2016-01-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:44,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,817 INFO sqlalchemy.engine.base.Engine ('2016-01-21 00:00:00.000000', 0.39, 70)
2018-05-08 18:31:44,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,819 INFO sqlalchemy.engine.base.Engine ('2016-01-22 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,820 INFO sqlalchemy.engine.base.Engine ('2016-01-25 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:44,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,822 INFO sqlalchemy.engine.base.Engine ('2016-01-26 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,823 INFO sqlalchemy.engine.base.Engine ('2016-01-31 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,825 INFO sqlalchemy.engine.base.Engine ('2016-02-01 00:00:00.000000', 0.0, 69)

2018-05-08 18:31:44,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,826 INFO sqlalchemy.engine.base.Engine ('2016-02-02 00:00:00.000000', 0.39, 70)
2018-05-08 18:31:44,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,827 INFO sqlalchemy.engine.base.Engine ('2016-02-03 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:44,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,829 INFO sqlalchemy.engine.base.Engine ('2016-02-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,831 INFO sqlalchemy.engine.base.Engine ('2016-02-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,832 INFO sqlalchemy.engine.base.Engine ('2016-02-08 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:44,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,834 INFO sqlalchemy.engine.base.Engine ('2016-02-09 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:44,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,835 INFO sqlalchemy.engine.base.Engine ('2016-02-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,836 INFO sqlalchemy.engine.base.Engine ('2016-02-11 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,838 INFO sqlalchemy.engine.base.Engine ('2016-02-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,839 INFO sqlalchemy.engine.base.Engine ('2016-02-16 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:44,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,841 INFO sqlalchemy.engine.base.Engine ('2016-02-17 00:00:00.000000', 0.22, 72)
2018-05-08 18:31:44,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,843 INFO sqlalchemy.engine.base.Engine ('2016-02-18 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,845 INFO sqlalchemy.engine.base.Engine ('2016-02-19 00:00:00.000000', 0.2, 68)
2018-05-08 18:31:44,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,846 INFO sqlalchemy.engine.base.Engine ('2016-02-20 00:00:00.000000', 0.05, 65)
2018-05-08 18:31:44,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,848 INFO sqlalchemy.engine.base.Engine ('2016-02-21 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:44,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,894 INFO sqlalchemy.engine.base.Engine ('2016-02-22 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,896 INFO sqlalchemy.engine.base.Engine ('2016-02-23 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:44,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,897 INFO sqlalchemy.engine.base.Engine ('2016-02-24 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:44,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,899 INFO sqlalchemy.engine.base.Engine ('2016-02-25 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,900 INFO sqlalchemy.engine.base.Engine ('2016-02-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:44,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,902 INFO sqlalchemy.engine.base.Engine ('2016-02-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,903 INFO sqlalchemy.engine.base.Engine ('2016-02-28 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,905 INFO sqlalchemy.engine.base.Engine ('2016-02-29 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:44,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,906 INFO sqlalchemy.engine.base.Engine ('2016-03-01 00:00:00.000000', 0.33, 73)
2018-05-08 18:31:44,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,908 INFO sqlalchemy.engine.base.Engine ('2016-03-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,909 INFO sqlalchemy.engine.base.Engine ('2016-03-03 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,911 INFO sqlalchemy.engine.base.Engine ('2016-03-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,912 INFO sqlalchemy.engine.base.Engine ('2016-03-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,914 INFO sqlalchemy.engine.base.Engine ('2016-03-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,916 INFO sqlalchemy.engine.base.Engine ('2016-03-07 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:44,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,917 INFO sqlalchemy.engine.base.Engine ('2016-03-08 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:44,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,919 INFO sqlalchemy.engine.base.Engine ('2016-03-09 00:00:00.000000', 0.3, 68)
2018-05-08 18:31:44,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,921 INFO sqlalchemy.engine.base.Engine ('2016-03-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,922 INFO sqlalchemy.engine.base.Engine ('2016-03-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,924 INFO sqlalchemy.engine.base.Engine ('2016-03-12 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:44,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,925 INFO sqlalchemy.engine.base.Engine ('2016-03-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,927 INFO sqlalchemy.engine.base.Engine ('2016-03-18 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:44,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,928 INFO sqlalchemy.engine.base.Engine ('2016-03-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,930 INFO sqlalchemy.engine.base.Engine ('2016-03-23 00:00:00.000000', 1.05, 70)
2018-05-08 18:31:44,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,931 INFO sqlalchemy.engine.base.Engine ('2016-03-24 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,932 INFO sqlalchemy.engine.base.Engine ('2016-03-25 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:44,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,934 INFO sqlalchemy.engine.base.Engine ('2016-03-26 00:00:00.000000', 0.03, 77)
2018-05-08 18:31:44,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,936 INFO sqlalchemy.engine.base.Engine ('2016-03-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,937 INFO sqlalchemy.engine.base.Engine ('2016-03-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,939 INFO sqlalchemy.engine.base.Engine ('2016-03-29 00:00:00.000000', 0.04, 75)
2018-05-08 18:31:44,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,940 INFO sqlalchemy.engine.base.Engine ('2016-03-30 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:44,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,942 INFO sqlalchemy.engine.base.Engine ('2016-03-31 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:44,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,943 INFO sqlalchemy.engine.base.Engine ('2016-04-01 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,945 INFO sqlalchemy.engine.base.Engine ('2016-04-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,946 INFO sqlalchemy.engine.base.Engine ('2016-04-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,948 INFO sqlalchemy.engine.base.Engine ('2016-04-04 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,949 INFO sqlalchemy.engine.base.Engine ('2016-04-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:44,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,951 INFO sqlalchemy.engine.base.Engine ('2016-04-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,952 INFO sqlalchemy.engine.base.Engine ('2016-04-09 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,954 INFO sqlalchemy.engine.base.Engine ('2016-04-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,955 INFO sqlalchemy.engine.base.Engine ('2016-04-11 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,957 INFO sqlalchemy.engine.base.Engine ('2016-04-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,958 INFO sqlalchemy.engine.base.Engine ('2016-04-13 00:00:00.000000', 0.18, 77)
2018-05-08 18:31:44,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,960 INFO sqlalchemy.engine.base.Engine ('2016-04-14 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:44,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,961 INFO sqlalchemy.engine.base.Engine ('2016-04-15 00:00:00.000000', 0.04, 79)
2018-05-08 18:31:44,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,963 INFO sqlalchemy.engine.base.Engine ('2016-04-16 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,965 INFO sqlalchemy.engine.base.Engine ('2016-04-17 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:44,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,967 INFO sqlalchemy.engine.base.Engine ('2016-04-18 00:00:00.000000', 0.46, 73)
2018-05-08 18:31:44,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,969 INFO sqlalchemy.engine.base.Engine ('2016-04-21 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,970 INFO sqlalchemy.engine.base.Engine ('2016-04-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,972 INFO sqlalchemy.engine.base.Engine ('2016-04-23 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:44,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,973 INFO sqlalchemy.engine.base.Engine ('2016-04-24 00:00:00.000000', 0.29, 75)
2018-05-08 18:31:44,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,975 INFO sqlalchemy.engine.base.Engine ('2016-04-25 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,976 INFO sqlalchemy.engine.base.Engine ('2016-04-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:44,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,978 INFO sqlalchemy.engine.base.Engine ('2016-04-27 00:00:00.000000', 0.0, 79)

2018-05-08 18:31:44,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,979 INFO sqlalchemy.engine.base.Engine ('2016-04-28 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:44,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,981 INFO sqlalchemy.engine.base.Engine ('2016-04-29 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,982 INFO sqlalchemy.engine.base.Engine ('2016-04-30 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:44,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,984 INFO sqlalchemy.engine.base.Engine ('2016-05-01 00:00:00.000000', 0.09, 78)
2018-05-08 18:31:44,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,985 INFO sqlalchemy.engine.base.Engine ('2016-05-02 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:44,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,987 INFO sqlalchemy.engine.base.Engine ('2016-05-03 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:44,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,988 INFO sqlalchemy.engine.base.Engine ('2016-05-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:44,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,990 INFO sqlalchemy.engine.base.Engine ('2016-05-05 00:00:00.000000', 0.27, 77)
2018-05-08 18:31:44,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,991 INFO sqlalchemy.engine.base.Engine ('2016-05-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:44,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,993 INFO sqlalchemy.engine.base.Engine ('2016-05-07 00:00:00.000000', 1.8, 71)
2018-05-08 18:31:44,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,994 INFO sqlalchemy.engine.base.Engine ('2016-05-08 00:00:00.000000', 0.75, 71)
2018-05-08 18:31:44,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,995 INFO sqlalchemy.engine.base.Engine ('2016-05-09 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:44,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,997 INFO sqlalchemy.engine.base.Engine ('2016-05-10 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:44,998 INFO sqlalchemy.engine.base.Engine ('2016-05-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:44,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,000 INFO sqlalchemy.engine.base.Engine ('2016-05-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:45,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,001 INFO sqlalchemy.engine.base.Engine ('2016-05-13 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:45,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,003 INFO sqlalchemy.engine.base.Engine ('2016-05-14 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:45,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,004 INFO sqlalchemy.engine.base.Engine ('2016-05-15 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:45,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,006 INFO sqlalchemy.engine.base.Engine ('2016-05-16 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:45,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,008 INFO sqlalchemy.engine.base.Engine ('2016-05-17 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:45,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,010 INFO sqlalchemy.engine.base.Engine ('2016-05-18 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:45,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,011 INFO sqlalchemy.engine.base.Engine ('2016-05-19 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:45,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,013 INFO sqlalchemy.engine.base.Engine ('2016-05-20 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:45,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,014 INFO sqlalchemy.engine.base.Engine ('2016-05-21 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:45,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,016 INFO sqlalchemy.engine.base.Engine ('2016-05-22 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:45,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,017 INFO sqlalchemy.engine.base.Engine ('2016-05-23 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:45,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,019 INFO sqlalchemy.engine.base.Engine ('2016-05-24 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:45,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,021 INFO sqlalchemy.engine.base.Engine ('2016-05-25 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:45,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,023 INFO sqlalchemy.engine.base.Engine ('2016-05-26 00:00:00.000000', 0.01, 81)
2018-05-08 18:31:45,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,024 INFO sqlalchemy.engine.base.Engine ('2016-05-27 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:45,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,025 INFO sqlalchemy.engine.base.Engine ('2016-05-28 00:00:00.000000', 0.36, 79)
2018-05-08 18:31:45,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,027 INFO sqlalchemy.engine.base.Engine ('2016-05-29 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:45,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,028 INFO sqlalchemy.engine.base.Engine ('2016-05-30 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:45,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,030 INFO sqlalchemy.engine.base.Engine ('2016-05-31 00:00:00.000000', 1.18, 71)
2018-05-08 18:31:45,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,031 INFO sqlalchemy.engine.base.Engine ('2016-06-01 00:00:00.000000', 0.38, 75)

2018-05-08 18:31:45,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,033 INFO sqlalchemy.engine.base.Engine ('2016-06-02 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:45,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,034 INFO sqlalchemy.engine.base.Engine ('2016-06-03 00:00:00.000000', 0.47, 75)
2018-05-08 18:31:45,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,036 INFO sqlalchemy.engine.base.Engine ('2016-06-04 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:45,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,038 INFO sqlalchemy.engine.base.Engine ('2016-06-05 00:00:00.000000', 0.14, 73)
2018-05-08 18:31:45,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,039 INFO sqlalchemy.engine.base.Engine ('2016-06-06 00:00:00.000000', 0.17, 78)
2018-05-08 18:31:45,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,040 INFO sqlalchemy.engine.base.Engine ('2016-06-07 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:45,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,042 INFO sqlalchemy.engine.base.Engine ('2016-06-08 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:45,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,043 INFO sqlalchemy.engine.base.Engine ('2016-06-09 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:45,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00519523" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,887 INFO sqlalchemy.engine.base.Engine ('2010-01-23 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:45,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,889 INFO sqlalchemy.engine.base.Engine ('2010-01-24 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:45,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,890 INFO sqlalchemy.engine.base.Engine ('2010-01-25 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:45,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,892 INFO sqlalchemy.engine.base.Engine ('2010-01-26 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:45,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,894 INFO sqlalchemy.engine.base.Engine ('2010-01-27 00:00:00.000000', 0.31, 65)
2018-05-08 18:31:45,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,895 INFO sqlalchemy.engine.base.Engine ('2010-01-28 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:45,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,897 INFO sqlalchemy.engine.base.Engine ('2010-01-29 00:00:00.000000', 0.1, 65)
2018-05-08 18:31:45,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,898 INFO sqlalchemy.engine.base.Engine ('2010-01-30 00:00:00.000000', 0.33, 69)
2018-05-08 18:31:45,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,899 INFO sqlalchemy.engine.base.Engine ('2010-01-31 00:00:00.000000', 1.1, 74)
2018-05-08 18:31:45,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,901 INFO sqlalchemy.engine.base.Engine ('2010-02-01 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:45,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,902 INFO sqlalchemy.engine.base.Engine ('2010-02-02 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:45,903 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,903 INFO sqlalchemy.engine.base.Engine ('2010-02-03 00:00:00.000000', 0.67, 63)
2018-05-08 18:31:45,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,905 INFO sqlalchemy.engine.base.Engine ('2010-02-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:45,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,906 INFO sqlalchemy.engine.base.Engine ('2010-02-05 00:00:00.000000', 0.09, 66)
2018-05-08 18:31:45,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,908 INFO sqlalchemy.engine.base.Engine ('2010-02-06 00:00:00.000000', 0.04, 62)
2018-05-08 18:31:45,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,909 INFO sqlalchemy.engine.base.Engine ('2010-02-08 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:45,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,911 INFO sqlalchemy.engine.base.Engine ('2010-02-09 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:45,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,912 INFO sqlalchemy.engine.base.Engine ('2010-02-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:45,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,914 INFO sqlalchemy.engine.base.Engine ('2010-02-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:45,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,916 INFO sqlalchemy.engine.base.Engine ('2010-02-12 00:00:00.000000', 0.65, 66)
2018-05-08 18:31:45,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,917 INFO sqlalchemy.engine.base.Engine ('2010-02-13 00:00:00.000000', 0.62, 70)
2018-05-08 18:31:45,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,919 INFO sqlalchemy.engine.base.Engine ('2010-02-14 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:45,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,920 INFO sqlalchemy.engine.base.Engine ('2010-02-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:45,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,921 INFO sqlalchemy.engine.base.Engine ('2010-02-16 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:45,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,923 INFO sqlalchemy.engine.base.Engine ('2010-02-17 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:45,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,925 INFO sqlalchemy.engine.base.Engine ('2010-02-18 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:45,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:45,926 INFO sqlalchemy.engine.base.Engine ('2010-02-19 00:00:00.000000', 0.42, 60)
2018-05-08 18:31:45,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,928 INFO sqlalchemy.engine.base.Engine ('2010-02-20 00:00:00.000000', 0.55, 74)
2018-05-08 18:31:45,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,929 INFO sqlalchemy.engine.base.Engine ('2010-02-23 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:45,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,931 INFO sqlalchemy.engine.base.Engine ('2010-02-24 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:45,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,932 INFO sqlalchemy.engine.base.Engine ('2010-02-25 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:45,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,934 INFO sqlalchemy.engine.base.Engine ('2010-02-26 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:45,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,935 INFO sqlalchemy.engine.base.Engine ('2010-02-27 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:45,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,936 INFO sqlalchemy.engine.base.Engine ('2010-02-28 00:00:00.000000', 0.2, 67)
2018-05-08 18:31:45,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,938 INFO sqlalchemy.engine.base.Engine ('2010-03-01 00:00:00.000000', 0.12, 66)
2018-05-08 18:31:45,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,940 INFO sqlalchemy.engine.base.Engine ('2010-03-02 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:45,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,941 INFO sqlalchemy.engine.base.Engine ('2010-03-03 00:00:00.000000', 0.12, 66)
2018-05-08 18:31:45,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,943 INFO sqlalchemy.engine.base.Engine ('2010-03-04 00:00:00.000000', 1.41, 65)
2018-05-08 18:31:45,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,944 INFO sqlalchemy.engine.base.Engine ('2010-03-05 00:00:00.000000', 1.33, 65)
2018-05-08 18:31:45,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,946 INFO sqlalchemy.engine.base.Engine ('2010-03-06 00:00:00.000000', 0.9, 68)
2018-05-08 18:31:45,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,947 INFO sqlalchemy.engine.base.Engine ('2010-03-07 00:00:00.000000', 0.35, 69)
2018-05-08 18:31:45,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,949 INFO sqlalchemy.engine.base.Engine ('2010-03-08 00:00:00.000000', 0.7, 65)
2018-05-08 18:31:45,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,950 INFO sqlalchemy.engine.base.Engine ('2010-03-09 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:45,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,951 INFO sqlalchemy.engine.base.Engine ('2010-03-10 00:00:00.000000', 0.14, 66)
2018-05-08 18:31:45,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,953 INFO sqlalchemy.engine.base.Engine ('2010-03-11 00:00:00.000000', 0.68, 71)
2018-05-08 18:31:45,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,954 INFO sqlalchemy.engine.base.Engine ('2010-03-12 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:45,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,956 INFO sqlalchemy.engine.base.Engine ('2010-03-13 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:45,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,957 INFO sqlalchemy.engine.base.Engine ('2010-03-14 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:45,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,959 INFO sqlalchemy.engine.base.Engine ('2010-03-15 00:00:00.000000', 0.83, 66)
2018-05-08 18:31:45,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,960 INFO sqlalchemy.engine.base.Engine ('2010-03-16 00:00:00.000000', 2.2, 69)
2018-05-08 18:31:45,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,962 INFO sqlalchemy.engine.base.Engine ('2010-03-17 00:00:00.000000', 1.32, 65)
2018-05-08 18:31:45,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,963 INFO sqlalchemy.engine.base.Engine ('2010-03-18 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:45,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,965 INFO sqlalchemy.engine.base.Engine ('2010-03-19 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:45,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,966 INFO sqlalchemy.engine.base.Engine ('2010-03-20 00:00:00.000000', 0.18, 65)
2018-05-08 18:31:45,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,969 INFO sqlalchemy.engine.base.Engine ('2010-03-21 00:00:00.000000', 1.0, 74)
2018-05-08 18:31:45,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,970 INFO sqlalchemy.engine.base.Engine ('2010-03-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:45,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,972 INFO sqlalchemy.engine.base.Engine ('2010-03-23 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:45,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,973 INFO sqlalchemy.engine.base.Engine ('2010-03-24 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:45,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,975 INFO sqlalchemy.engine.base.Engine ('2010-03-25 00:00:00.000000', 0.35, 67)
2018-05-08 18:31:45,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,976 INFO sqlalchemy.engine.base.Engine ('2010-03-26 00:00:00.000000', 0.91, 71)
2018-05-08 18:31:45,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,978 INFO sqlalchemy.engine.base.Engine ('2010-03-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:45,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:45,979 INFO sqlalchemy.engine.base.Engine ('2010-03-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:45,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,981 INFO sqlalchemy.engine.base.Engine ('2010-03-29 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:45,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,982 INFO sqlalchemy.engine.base.Engine ('2010-03-30 00:00:00.000000', 0.49, 68)
2018-05-08 18:31:45,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,984 INFO sqlalchemy.engine.base.Engine ('2010-03-31 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:45,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,985 INFO sqlalchemy.engine.base.Engine ('2010-04-01 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:45,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,987 INFO sqlalchemy.engine.base.Engine ('2010-04-02 00:00:00.000000', 0.19, 73)
2018-05-08 18:31:45,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,988 INFO sqlalchemy.engine.base.Engine ('2010-04-03 00:00:00.000000', 0.92, 67)
2018-05-08 18:31:45,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,990 INFO sqlalchemy.engine.base.Engine ('2010-04-04 00:00:00.000000', 2.56, 67)
2018-05-08 18:31:45,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,991 INFO sqlalchemy.engine.base.Engine ('2010-04-05 00:00:00.000000', 0.87, 69)
2018-05-08 18:31:45,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,993 INFO sqlalchemy.engine.base.Engine ('2010-04-06 00:00:00.000000', 1.83, 69)
2018-05-08 18:31:45,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,994 INFO sqlalchemy.engine.base.Engine ('2010-04-07 00:00:00.000000', 1.43, 68)
2018-05-08 18:31:45,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,996 INFO sqlalchemy.engine.base.Engine ('2010-04-08 00:00:00.000000', 0.35, 76)
2018-05-08 18:31:45,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,997 INFO sqlalchemy.engine.base.Engine ('2010-04-09 00:00:00.000000', 0.5, 68)
2018-05-08 18:31:45,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:45,998 INFO sqlalchemy.engine.base.Engine ('2010-04-10 00:00:00.000000', 0.4, 67)
2018-05-08 18:31:45,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,000 INFO sqlalchemy.engine.base.Engine ('2010-04-11 00:00:00.000000', 1.04, 73)
2018-05-08 18:31:46,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,002 INFO sqlalchemy.engine.base.Engine ('2010-04-12 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:46,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,004 INFO sqlalchemy.engine.base.Engine ('2010-04-13 00:00:00.000000', 0.93, 71)
2018-05-08 18:31:46,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,006 INFO sqlalchemy.engine.base.Engine ('2010-04-14 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:46,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,007 INFO sqlalchemy.engine.base.Engine ('2010-04-15 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:46,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,008 INFO sqlalchemy.engine.base.Engine ('2010-04-16 00:00:00.000000', 0.06, 65)
2018-05-08 18:31:46,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,010 INFO sqlalchemy.engine.base.Engine ('2010-04-17 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:46,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,011 INFO sqlalchemy.engine.base.Engine ('2010-04-18 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:46,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,012 INFO sqlalchemy.engine.base.Engine ('2010-04-19 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:46,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,014 INFO sqlalchemy.engine.base.Engine ('2010-04-20 00:00:00.000000', 0.68, 71)
2018-05-08 18:31:46,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,015 INFO sqlalchemy.engine.base.Engine ('2010-04-21 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:46,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,017 INFO sqlalchemy.engine.base.Engine ('2010-04-24 00:00:00.000000', 0.17, 75)
2018-05-08 18:31:46,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,018 INFO sqlalchemy.engine.base.Engine ('2010-04-25 00:00:00.000000', 0.08, 78)
2018-05-08 18:31:46,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,020 INFO sqlalchemy.engine.base.Engine ('2010-04-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,022 INFO sqlalchemy.engine.base.Engine ('2010-04-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:46,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,023 INFO sqlalchemy.engine.base.Engine ('2010-04-28 00:00:00.000000', 0.49, 76)
2018-05-08 18:31:46,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,025 INFO sqlalchemy.engine.base.Engine ('2010-04-29 00:00:00.000000', 1.29, 69)
2018-05-08 18:31:46,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,026 INFO sqlalchemy.engine.base.Engine ('2010-04-30 00:00:00.000000', 0.92, 72)
2018-05-08 18:31:46,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,027 INFO sqlalchemy.engine.base.Engine ('2010-05-01 00:00:00.000000', 0.31, 73)
2018-05-08 18:31:46,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,029 INFO sqlalchemy.engine.base.Engine ('2010-05-02 00:00:00.000000', 0.37, 74)
2018-05-08 18:31:46,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,031 INFO sqlalchemy.engine.base.Engine ('2010-05-03 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:46,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:46,032 INFO sqlalchemy.engine.base.Engine ('2010-05-04 00:00:00.000000', 0.21, 77)
2018-05-08 18:31:46,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,034 INFO sqlalchemy.engine.base.Engine ('2010-05-05 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:46,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,035 INFO sqlalchemy.engine.base.Engine ('2010-05-06 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:46,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,036 INFO sqlalchemy.engine.base.Engine ('2010-05-07 00:00:00.000000', 0.24, 69)
2018-05-08 18:31:46,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,083 INFO sqlalchemy.engine.base.Engine ('2010-05-08 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:46,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,084 INFO sqlalchemy.engine.base.Engine ('2010-05-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,086 INFO sqlalchemy.engine.base.Engine ('2010-05-10 00:00:00.000000', 0.55, 71)
2018-05-08 18:31:46,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,087 INFO sqlalchemy.engine.base.Engine ('2010-05-13 00:00:00.000000', 0.32, 70)
2018-05-08 18:31:46,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,089 INFO sqlalchemy.engine.base.Engine ('2010-05-14 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,089 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,090 INFO sqlalchemy.engine.base.Engine ('2010-05-15 00:00:00.000000', 0.25, 73)
2018-05-08 18:31:46,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,092 INFO sqlalchemy.engine.base.Engine ('2010-05-16 00:00:00.000000', 0.61, 73)
2018-05-08 18:31:46,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,093 INFO sqlalchemy.engine.base.Engine ('2010-05-17 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:46,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,094 INFO sqlalchemy.engine.base.Engine ('2010-05-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:46,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,096 INFO sqlalchemy.engine.base.Engine ('2010-05-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:46,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,098 INFO sqlalchemy.engine.base.Engine ('2010-05-20 00:00:00.000000', 0.67, 71)
2018-05-08 18:31:46,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,099 INFO sqlalchemy.engine.base.Engine ('2010-05-21 00:00:00.000000', 0.38, 71)
2018-05-08 18:31:46,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,100 INFO sqlalchemy.engine.base.Engine ('2010-05-22 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:46,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,102 INFO sqlalchemy.engine.base.Engine ('2010-05-25 00:00:00.000000', 0.83, 71)
2018-05-08 18:31:46,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,104 INFO sqlalchemy.engine.base.Engine ('2010-05-26 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:46,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,105 INFO sqlalchemy.engine.base.Engine ('2010-05-27 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:46,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,107 INFO sqlalchemy.engine.base.Engine ('2010-05-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,108 INFO sqlalchemy.engine.base.Engine ('2010-06-01 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:46,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,110 INFO sqlalchemy.engine.base.Engine ('2010-06-02 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:46,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,111 INFO sqlalchemy.engine.base.Engine ('2010-06-03 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:46,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,113 INFO sqlalchemy.engine.base.Engine ('2010-06-04 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:46,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,115 INFO sqlalchemy.engine.base.Engine ('2010-06-05 00:00:00.000000', 0.09, 79)
2018-05-08 18:31:46,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,116 INFO sqlalchemy.engine.base.Engine ('2010-06-06 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:46,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,118 INFO sqlalchemy.engine.base.Engine ('2010-06-07 00:00:00.000000', 0.44, 75)
2018-05-08 18:31:46,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,119 INFO sqlalchemy.engine.base.Engine ('2010-06-08 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:46,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,121 INFO sqlalchemy.engine.base.Engine ('2010-06-09 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:46,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,122 INFO sqlalchemy.engine.base.Engine ('2010-06-17 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:46,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,124 INFO sqlalchemy.engine.base.Engine ('2010-06-23 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:46,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,125 INFO sqlalchemy.engine.base.Engine ('2010-06-24 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:46,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,127 INFO sqlalchemy.engine.base.Engine ('2010-06-25 00:00:00.000000', 0.79, 70)
2018-05-08 18:31:46,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,128 INFO sqlalchemy.engine.base.Engine ('2010-06-26 00:00:00.000000', 0.88, 69)
2018-05-08 18:31:46,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)

2018-05-08 18:31:46,130 INFO sqlalchemy.engine.base.Engine ('2010-06-27 00:00:00.000000', 0.37, 73)
2018-05-08 18:31:46,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,131 INFO sqlalchemy.engine.base.Engine ('2010-06-28 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:46,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,132 INFO sqlalchemy.engine.base.Engine ('2010-06-29 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:46,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,133 INFO sqlalchemy.engine.base.Engine ('2010-06-30 00:00:00.000000', 0.71, 72)
2018-05-08 18:31:46,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,135 INFO sqlalchemy.engine.base.Engine ('2010-07-01 00:00:00.000000', 0.44, 70)
2018-05-08 18:31:46,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,137 INFO sqlalchemy.engine.base.Engine ('2010-07-02 00:00:00.000000', 0.7, 69)
2018-05-08 18:31:46,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,138 INFO sqlalchemy.engine.base.Engine ('2010-07-03 00:00:00.000000', 1.81, 69)
2018-05-08 18:31:46,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,139 INFO sqlalchemy.engine.base.Engine ('2010-07-04 00:00:00.000000', 0.44, 72)
2018-05-08 18:31:46,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,141 INFO sqlalchemy.engine.base.Engine ('2010-07-05 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:46,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,142 INFO sqlalchemy.engine.base.Engine ('2010-07-06 00:00:00.000000', 1.01, 69)
2018-05-08 18:31:46,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,144 INFO sqlalchemy.engine.base.Engine ('2010-07-07 00:00:00.000000', 1.05, 69)
2018-05-08 18:31:46,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,145 INFO sqlalchemy.engine.base.Engine ('2010-07-08 00:00:00.000000', 0.9, 69)
2018-05-08 18:31:46,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,147 INFO sqlalchemy.engine.base.Engine ('2010-07-09 00:00:00.000000', 0.75, 68)
2018-05-08 18:31:46,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,148 INFO sqlalchemy.engine.base.Engine ('2010-07-10 00:00:00.000000', 0.75, 68)
2018-05-08 18:31:46,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,150 INFO sqlalchemy.engine.base.Engine ('2010-07-11 00:00:00.000000', 0.31, 71)
2018-05-08 18:31:46,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,152 INFO sqlalchemy.engine.base.Engine ('2010-07-12 00:00:00.000000', 0.25, 70)
2018-05-08 18:31:46,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,154 INFO sqlalchemy.engine.base.Engine ('2010-07-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,156 INFO sqlalchemy.engine.base.Engine ('2010-07-14 00:00:00.000000', 0.48, 69)
2018-05-08 18:31:46,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,157 INFO sqlalchemy.engine.base.Engine ('2010-07-15 00:00:00.000000', 0.24, 68)
2018-05-08 18:31:46,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,158 INFO sqlalchemy.engine.base.Engine ('2010-07-16 00:00:00.000000', 0.19, 70)
2018-05-08 18:31:46,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,161 INFO sqlalchemy.engine.base.Engine ('2010-07-17 00:00:00.000000', 0.46, 70)
2018-05-08 18:31:46,161 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,162 INFO sqlalchemy.engine.base.Engine ('2010-07-18 00:00:00.000000', 2.14, 74)
2018-05-08 18:31:46,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,164 INFO sqlalchemy.engine.base.Engine ('2010-07-19 00:00:00.000000', 0.35, 69)
2018-05-08 18:31:46,164 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,165 INFO sqlalchemy.engine.base.Engine ('2010-07-20 00:00:00.000000', 1.23, 70)
2018-05-08 18:31:46,166 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,167 INFO sqlalchemy.engine.base.Engine ('2010-07-21 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:46,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,168 INFO sqlalchemy.engine.base.Engine ('2010-07-22 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:46,169 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,170 INFO sqlalchemy.engine.base.Engine ('2010-07-23 00:00:00.000000', 1.0, 71)
2018-05-08 18:31:46,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,171 INFO sqlalchemy.engine.base.Engine ('2010-07-24 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:46,172 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,173 INFO sqlalchemy.engine.base.Engine ('2010-07-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,174 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,174 INFO sqlalchemy.engine.base.Engine ('2010-07-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,176 INFO sqlalchemy.engine.base.Engine ('2010-07-27 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:46,177 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,177 INFO sqlalchemy.engine.base.Engine ('2010-07-28 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:46,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,179 INFO sqlalchemy.engine.base.Engine ('2010-07-29 00:00:00.000000', 0.38, 72)
2018-05-08 18:31:46,180 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,181 INFO sqlalchemy.engine.base.Engine ('2010-07-30 00:00:00.000000', 0.29, 69)
2018-05-08 18:31:46,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,182 INFO sqlalchemy.engine.base.Engine ('2010-07-31 00:00:00.000000', 0.05, 73)

2018-05-08 18:31:46,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,185 INFO sqlalchemy.engine.base.Engine ('2010-08-01 00:00:00.000000', 0.52, 71)
2018-05-08 18:31:46,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,186 INFO sqlalchemy.engine.base.Engine ('2010-08-02 00:00:00.000000', 1.45, 70)
2018-05-08 18:31:46,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,188 INFO sqlalchemy.engine.base.Engine ('2010-08-03 00:00:00.000000', 0.58, 70)
2018-05-08 18:31:46,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,189 INFO sqlalchemy.engine.base.Engine ('2010-08-04 00:00:00.000000', 1.89, 69)
2018-05-08 18:31:46,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,191 INFO sqlalchemy.engine.base.Engine ('2010-08-05 00:00:00.000000', 0.93, 69)
2018-05-08 18:31:46,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,192 INFO sqlalchemy.engine.base.Engine ('2010-08-06 00:00:00.000000', 0.35, 70)
2018-05-08 18:31:46,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,194 INFO sqlalchemy.engine.base.Engine ('2010-08-07 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:46,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,196 INFO sqlalchemy.engine.base.Engine ('2010-08-08 00:00:00.000000', 0.82, 71)
2018-05-08 18:31:46,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,197 INFO sqlalchemy.engine.base.Engine ('2010-08-09 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:46,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,198 INFO sqlalchemy.engine.base.Engine ('2010-08-10 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:46,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,200 INFO sqlalchemy.engine.base.Engine ('2010-08-11 00:00:00.000000', 0.13, 69)
2018-05-08 18:31:46,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,202 INFO sqlalchemy.engine.base.Engine ('2010-08-12 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:46,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,203 INFO sqlalchemy.engine.base.Engine ('2010-08-13 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:46,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,205 INFO sqlalchemy.engine.base.Engine ('2010-08-14 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:46,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,207 INFO sqlalchemy.engine.base.Engine ('2010-08-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,207 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,208 INFO sqlalchemy.engine.base.Engine ('2010-08-16 00:00:00.000000', 0.42, 69)
2018-05-08 18:31:46,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,210 INFO sqlalchemy.engine.base.Engine ('2010-08-17 00:00:00.000000', 0.88, 69)
2018-05-08 18:31:46,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,211 INFO sqlalchemy.engine.base.Engine ('2010-08-18 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:46,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,213 INFO sqlalchemy.engine.base.Engine ('2010-08-19 00:00:00.000000', 0.12, 74)
2018-05-08 18:31:46,213 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,214 INFO sqlalchemy.engine.base.Engine ('2010-08-20 00:00:00.000000', 0.24, 71)
2018-05-08 18:31:46,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,216 INFO sqlalchemy.engine.base.Engine ('2010-08-21 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:46,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,217 INFO sqlalchemy.engine.base.Engine ('2010-08-22 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:46,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,219 INFO sqlalchemy.engine.base.Engine ('2010-08-23 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:46,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,220 INFO sqlalchemy.engine.base.Engine ('2010-08-24 00:00:00.000000', 0.41, 70)
2018-05-08 18:31:46,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,222 INFO sqlalchemy.engine.base.Engine ('2010-08-25 00:00:00.000000', 0.45, 69)
2018-05-08 18:31:46,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,223 INFO sqlalchemy.engine.base.Engine ('2010-08-26 00:00:00.000000', 0.61, 71)
2018-05-08 18:31:46,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,225 INFO sqlalchemy.engine.base.Engine ('2010-08-27 00:00:00.000000', 1.13, 73)
2018-05-08 18:31:46,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,226 INFO sqlalchemy.engine.base.Engine ('2010-08-28 00:00:00.000000', 0.41, 73)
2018-05-08 18:31:46,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,228 INFO sqlalchemy.engine.base.Engine ('2010-08-29 00:00:00.000000', 1.0, 71)
2018-05-08 18:31:46,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,229 INFO sqlalchemy.engine.base.Engine ('2010-08-30 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:46,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,231 INFO sqlalchemy.engine.base.Engine ('2010-08-31 00:00:00.000000', 0.21, 70)
2018-05-08 18:31:46,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,232 INFO sqlalchemy.engine.base.Engine ('2010-09-01 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:46,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,234 INFO sqlalchemy.engine.base.Engine ('2010-09-02 00:00:00.000000', 0.54, 72)
2018-05-08 18:31:46,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,235 INFO sqlalchemy.engine.base.Engine ('2010-09-03 00:00:00.000000', 0.52, 69)
2018-05-08 18:31:46,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,278 INFO sqlalchemy.engine.base.Engine ('2010-09-04 00:00:00.000000', 0.32, 68)

2018-05-08 18:31:46,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,280 INFO sqlalchemy.engine.base.Engine ('2010-09-05 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:46,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,282 INFO sqlalchemy.engine.base.Engine ('2010-09-06 00:00:00.000000', 0.38, 68)
2018-05-08 18:31:46,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,283 INFO sqlalchemy.engine.base.Engine ('2010-09-07 00:00:00.000000', 1.51, 69)
2018-05-08 18:31:46,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,284 INFO sqlalchemy.engine.base.Engine ('2010-09-08 00:00:00.000000', 0.28, 70)
2018-05-08 18:31:46,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,286 INFO sqlalchemy.engine.base.Engine ('2010-09-09 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:46,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,287 INFO sqlalchemy.engine.base.Engine ('2010-09-10 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:46,288 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,289 INFO sqlalchemy.engine.base.Engine ('2010-09-11 00:00:00.000000', 0.24, 74)
2018-05-08 18:31:46,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,290 INFO sqlalchemy.engine.base.Engine ('2010-09-12 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,292 INFO sqlalchemy.engine.base.Engine ('2010-09-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,293 INFO sqlalchemy.engine.base.Engine ('2010-09-14 00:00:00.000000', 0.27, 74)
2018-05-08 18:31:46,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,295 INFO sqlalchemy.engine.base.Engine ('2010-09-15 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:46,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,296 INFO sqlalchemy.engine.base.Engine ('2010-09-16 00:00:00.000000', 0.21, 72)
2018-05-08 18:31:46,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,299 INFO sqlalchemy.engine.base.Engine ('2010-09-17 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,300 INFO sqlalchemy.engine.base.Engine ('2010-09-18 00:00:00.000000', 0.19, 71)
2018-05-08 18:31:46,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,302 INFO sqlalchemy.engine.base.Engine ('2010-09-19 00:00:00.000000', 0.58, 74)
2018-05-08 18:31:46,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,303 INFO sqlalchemy.engine.base.Engine ('2010-09-20 00:00:00.000000', 0.26, 74)
2018-05-08 18:31:46,304 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,305 INFO sqlalchemy.engine.base.Engine ('2010-09-21 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:46,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,307 INFO sqlalchemy.engine.base.Engine ('2010-09-22 00:00:00.000000', 0.42, 72)
2018-05-08 18:31:46,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,308 INFO sqlalchemy.engine.base.Engine ('2010-09-23 00:00:00.000000', 0.86, 73)
2018-05-08 18:31:46,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,310 INFO sqlalchemy.engine.base.Engine ('2010-09-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,312 INFO sqlalchemy.engine.base.Engine ('2010-09-25 00:00:00.000000', 0.57, 71)
2018-05-08 18:31:46,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,314 INFO sqlalchemy.engine.base.Engine ('2010-09-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,316 INFO sqlalchemy.engine.base.Engine ('2010-09-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,317 INFO sqlalchemy.engine.base.Engine ('2010-09-28 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:46,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,319 INFO sqlalchemy.engine.base.Engine ('2010-09-29 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,321 INFO sqlalchemy.engine.base.Engine ('2010-09-30 00:00:00.000000', 1.18, 70)
2018-05-08 18:31:46,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,322 INFO sqlalchemy.engine.base.Engine ('2010-10-01 00:00:00.000000', 3.14, 73)
2018-05-08 18:31:46,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,324 INFO sqlalchemy.engine.base.Engine ('2010-10-02 00:00:00.000000', 1.27, 73)
2018-05-08 18:31:46,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,325 INFO sqlalchemy.engine.base.Engine ('2010-10-03 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:46,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,327 INFO sqlalchemy.engine.base.Engine ('2010-10-04 00:00:00.000000', 0.24, 71)
2018-05-08 18:31:46,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,328 INFO sqlalchemy.engine.base.Engine ('2010-10-05 00:00:00.000000', 0.21, 76)
2018-05-08 18:31:46,329 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,330 INFO sqlalchemy.engine.base.Engine ('2010-10-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,332 INFO sqlalchemy.engine.base.Engine ('2010-10-07 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,333 INFO sqlalchemy.engine.base.Engine ('2010-10-08 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,334 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,335 INFO sqlalchemy.engine.base.Engine ('2010-10-09 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:46,336 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,336 INFO sqlalchemy.engine.base.Engine ('2010-10-10 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,338 INFO sqlalchemy.engine.base.Engine ('2010-10-11 00:00:00.000000', 0.41, 71)
2018-05-08 18:31:46,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,339 INFO sqlalchemy.engine.base.Engine ('2010-10-12 00:00:00.000000', 0.25, 71)
2018-05-08 18:31:46,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,341 INFO sqlalchemy.engine.base.Engine ('2010-10-13 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:46,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,342 INFO sqlalchemy.engine.base.Engine ('2010-10-14 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:46,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,344 INFO sqlalchemy.engine.base.Engine ('2010-10-15 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:46,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,345 INFO sqlalchemy.engine.base.Engine ('2010-10-16 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:46,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,347 INFO sqlalchemy.engine.base.Engine ('2010-10-17 00:00:00.000000', 0.21, 74)
2018-05-08 18:31:46,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,348 INFO sqlalchemy.engine.base.Engine ('2010-10-18 00:00:00.000000', 0.07, 74)
2018-05-08 18:31:46,349 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,350 INFO sqlalchemy.engine.base.Engine ('2010-10-19 00:00:00.000000', 4.01, 69)
2018-05-08 18:31:46,351 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,351 INFO sqlalchemy.engine.base.Engine ('2010-10-20 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:46,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,353 INFO sqlalchemy.engine.base.Engine ('2010-10-21 00:00:00.000000', 0.39, 73)
2018-05-08 18:31:46,354 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,355 INFO sqlalchemy.engine.base.Engine ('2010-10-22 00:00:00.000000', 0.21, 74)
2018-05-08 18:31:46,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,714 INFO sqlalchemy.engine.base.Engine ('2011-04-24 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:46,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,716 INFO sqlalchemy.engine.base.Engine ('2011-04-25 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:46,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,718 INFO sqlalchemy.engine.base.Engine ('2011-04-26 00:00:00.000000', 0.46, 71)
2018-05-08 18:31:46,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,719 INFO sqlalchemy.engine.base.Engine ('2011-04-27 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:46,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,721 INFO sqlalchemy.engine.base.Engine ('2011-04-28 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:46,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,723 INFO sqlalchemy.engine.base.Engine ('2011-04-29 00:00:00.000000', 0.9, 71)
2018-05-08 18:31:46,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,724 INFO sqlalchemy.engine.base.Engine ('2011-05-01 00:00:00.000000', 1.21, 72)
2018-05-08 18:31:46,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,726 INFO sqlalchemy.engine.base.Engine ('2011-05-02 00:00:00.000000', 0.35, 73)
2018-05-08 18:31:46,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,727 INFO sqlalchemy.engine.base.Engine ('2011-05-03 00:00:00.000000', 3.05, 70)
2018-05-08 18:31:46,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,729 INFO sqlalchemy.engine.base.Engine ('2011-05-05 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:46,730 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,730 INFO sqlalchemy.engine.base.Engine ('2011-05-06 00:00:00.000000', 2.07, 67)
2018-05-08 18:31:46,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,732 INFO sqlalchemy.engine.base.Engine ('2011-05-07 00:00:00.000000', 1.91, 67)
2018-05-08 18:31:46,733 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,734 INFO sqlalchemy.engine.base.Engine ('2011-05-08 00:00:00.000000', 2.26, 70)
2018-05-08 18:31:46,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,735 INFO sqlalchemy.engine.base.Engine ('2011-05-09 00:00:00.000000', 0.31, 73)
2018-05-08 18:31:46,736 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,737 INFO sqlalchemy.engine.base.Engine ('2011-05-10 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:46,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,739 INFO sqlalchemy.engine.base.Engine ('2011-05-11 00:00:00.000000', 0.74, 72)
2018-05-08 18:31:46,739 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,740 INFO sqlalchemy.engine.base.Engine ('2011-05-12 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:46,741 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,742 INFO sqlalchemy.engine.base.Engine ('2011-05-13 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:46,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,743 INFO sqlalchemy.engine.base.Engine ('2011-05-14 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:46,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,745 INFO sqlalchemy.engine.base.Engine ('2011-05-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,747 INFO sqlalchemy.engine.base.Engine ('2011-05-16 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:46,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,749 INFO sqlalchemy.engine.base.Engine ('2011-05-17 00:00:00.000000', 0.03, 70)

2018-05-08 18:31:46,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,750 INFO sqlalchemy.engine.base.Engine ('2011-05-18 00:00:00.000000', 0.19, 75)
2018-05-08 18:31:46,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,752 INFO sqlalchemy.engine.base.Engine ('2011-05-19 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:46,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,754 INFO sqlalchemy.engine.base.Engine ('2011-05-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,755 INFO sqlalchemy.engine.base.Engine ('2011-05-21 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:46,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,757 INFO sqlalchemy.engine.base.Engine ('2011-05-22 00:00:00.000000', 0.71, 69)
2018-05-08 18:31:46,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,758 INFO sqlalchemy.engine.base.Engine ('2011-05-23 00:00:00.000000', 0.17, 72)
2018-05-08 18:31:46,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,760 INFO sqlalchemy.engine.base.Engine ('2011-05-24 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:46,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,762 INFO sqlalchemy.engine.base.Engine ('2011-05-25 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:46,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,763 INFO sqlalchemy.engine.base.Engine ('2011-05-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,765 INFO sqlalchemy.engine.base.Engine ('2011-05-27 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:46,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,766 INFO sqlalchemy.engine.base.Engine ('2011-05-28 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:46,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,768 INFO sqlalchemy.engine.base.Engine ('2011-05-29 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:46,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,769 INFO sqlalchemy.engine.base.Engine ('2011-05-30 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:46,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,771 INFO sqlalchemy.engine.base.Engine ('2011-05-31 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:46,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,772 INFO sqlalchemy.engine.base.Engine ('2011-06-01 00:00:00.000000', 0.61, 69)
2018-05-08 18:31:46,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,774 INFO sqlalchemy.engine.base.Engine ('2011-06-02 00:00:00.000000', 0.22, 72)
2018-05-08 18:31:46,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,776 INFO sqlalchemy.engine.base.Engine ('2011-06-03 00:00:00.000000', 2.0, 66)
2018-05-08 18:31:46,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,777 INFO sqlalchemy.engine.base.Engine ('2011-06-04 00:00:00.000000', 2.45, 67)
2018-05-08 18:31:46,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,779 INFO sqlalchemy.engine.base.Engine ('2011-06-05 00:00:00.000000', 0.76, 71)
2018-05-08 18:31:46,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,781 INFO sqlalchemy.engine.base.Engine ('2011-06-06 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:46,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,782 INFO sqlalchemy.engine.base.Engine ('2011-06-07 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:46,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,784 INFO sqlalchemy.engine.base.Engine ('2011-06-08 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:46,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,786 INFO sqlalchemy.engine.base.Engine ('2011-06-09 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:46,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,787 INFO sqlalchemy.engine.base.Engine ('2011-06-10 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:46,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,789 INFO sqlalchemy.engine.base.Engine ('2011-06-11 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:46,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,791 INFO sqlalchemy.engine.base.Engine ('2011-06-12 00:00:00.000000', 1.5, 69)
2018-05-08 18:31:46,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,792 INFO sqlalchemy.engine.base.Engine ('2011-06-13 00:00:00.000000', 0.41, 68)
2018-05-08 18:31:46,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,795 INFO sqlalchemy.engine.base.Engine ('2011-06-14 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:46,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,796 INFO sqlalchemy.engine.base.Engine ('2011-06-15 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:46,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,798 INFO sqlalchemy.engine.base.Engine ('2011-06-16 00:00:00.000000', 0.83, 72)
2018-05-08 18:31:46,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,799 INFO sqlalchemy.engine.base.Engine ('2011-06-17 00:00:00.000000', 0.18, 74)
2018-05-08 18:31:46,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,801 INFO sqlalchemy.engine.base.Engine ('2011-06-18 00:00:00.000000', 0.07, 70)
2018-05-08 18:31:46,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,803 INFO sqlalchemy.engine.base.Engine ('2011-06-19 00:00:00.000000', 1.84, 72)
2018-05-08 18:31:46,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,805 INFO sqlalchemy.engine.base.Engine ('2011-06-20 00:00:00.000000', 0.91, 71)
2018-05-08 18:31:46,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,806 INFO sqlalchemy.engine.base.Engine ('2011-06-21 00:00:00.000000', 1.03, 71)

2018-05-08 18:31:46,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,808 INFO sqlalchemy.engine.base.Engine ('2011-06-22 00:00:00.000000', 1.65, 70)
2018-05-08 18:31:46,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,809 INFO sqlalchemy.engine.base.Engine ('2011-06-23 00:00:00.000000', 0.68, 70)
2018-05-08 18:31:46,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,811 INFO sqlalchemy.engine.base.Engine ('2011-06-24 00:00:00.000000', 1.16, 69)
2018-05-08 18:31:46,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,813 INFO sqlalchemy.engine.base.Engine ('2011-06-25 00:00:00.000000', 0.06, 74)
2018-05-08 18:31:46,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,814 INFO sqlalchemy.engine.base.Engine ('2011-06-26 00:00:00.000000', 0.29, 69)
2018-05-08 18:31:46,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,816 INFO sqlalchemy.engine.base.Engine ('2011-06-27 00:00:00.000000', 0.98, 72)
2018-05-08 18:31:46,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,819 INFO sqlalchemy.engine.base.Engine ('2011-06-28 00:00:00.000000', 0.25, 70)
2018-05-08 18:31:46,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,820 INFO sqlalchemy.engine.base.Engine ('2011-06-29 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:46,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,822 INFO sqlalchemy.engine.base.Engine ('2011-06-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,824 INFO sqlalchemy.engine.base.Engine ('2011-07-01 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:46,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,825 INFO sqlalchemy.engine.base.Engine ('2011-07-02 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:46,826 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,827 INFO sqlalchemy.engine.base.Engine ('2011-07-03 00:00:00.000000', 0.31, 71)
2018-05-08 18:31:46,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,829 INFO sqlalchemy.engine.base.Engine ('2011-07-04 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:46,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,830 INFO sqlalchemy.engine.base.Engine ('2011-07-05 00:00:00.000000', 0.24, 71)
2018-05-08 18:31:46,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,874 INFO sqlalchemy.engine.base.Engine ('2011-07-06 00:00:00.000000', 0.15, 69)
2018-05-08 18:31:46,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,876 INFO sqlalchemy.engine.base.Engine ('2011-07-11 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:46,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,877 INFO sqlalchemy.engine.base.Engine ('2011-07-14 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:46,879 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,880 INFO sqlalchemy.engine.base.Engine ('2011-07-15 00:00:00.000000', 0.4, 70)
2018-05-08 18:31:46,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,882 INFO sqlalchemy.engine.base.Engine ('2011-07-16 00:00:00.000000', 0.3, 74)
2018-05-08 18:31:46,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,884 INFO sqlalchemy.engine.base.Engine ('2011-07-17 00:00:00.000000', 0.66, 74)
2018-05-08 18:31:46,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,885 INFO sqlalchemy.engine.base.Engine ('2011-07-18 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:46,887 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,887 INFO sqlalchemy.engine.base.Engine ('2011-07-19 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:46,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,889 INFO sqlalchemy.engine.base.Engine ('2011-07-20 00:00:00.000000', 0.72, 69)
2018-05-08 18:31:46,890 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,891 INFO sqlalchemy.engine.base.Engine ('2011-07-21 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,892 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,892 INFO sqlalchemy.engine.base.Engine ('2011-07-22 00:00:00.000000', 1.34, 70)
2018-05-08 18:31:46,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,894 INFO sqlalchemy.engine.base.Engine ('2011-07-23 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:46,895 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,896 INFO sqlalchemy.engine.base.Engine ('2011-07-24 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:46,897 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,898 INFO sqlalchemy.engine.base.Engine ('2011-07-25 00:00:00.000000', 0.23, 74)
2018-05-08 18:31:46,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,899 INFO sqlalchemy.engine.base.Engine ('2011-07-26 00:00:00.000000', 0.35, 74)
2018-05-08 18:31:46,900 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,901 INFO sqlalchemy.engine.base.Engine ('2011-07-27 00:00:00.000000', 2.12, 75)
2018-05-08 18:31:46,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,903 INFO sqlalchemy.engine.base.Engine ('2011-07-28 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:46,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,904 INFO sqlalchemy.engine.base.Engine ('2011-07-29 00:00:00.000000', 0.7, 71)
2018-05-08 18:31:46,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,906 INFO sqlalchemy.engine.base.Engine ('2011-08-01 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,908 INFO sqlalchemy.engine.base.Engine ('2011-08-02 00:00:00.000000', 0.26, 70)
2018-05-08 18:31:46,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,910 INFO sqlalchemy.engine.base.Engine ('2011-08-03 00:00:00.000000', 0.17, 71)

2018-05-08 18:31:46,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,911 INFO sqlalchemy.engine.base.Engine ('2011-08-04 00:00:00.000000', 0.26, 77)
2018-05-08 18:31:46,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,913 INFO sqlalchemy.engine.base.Engine ('2011-08-05 00:00:00.000000', 0.51, 77)
2018-05-08 18:31:46,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,915 INFO sqlalchemy.engine.base.Engine ('2011-08-06 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:46,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,916 INFO sqlalchemy.engine.base.Engine ('2011-08-07 00:00:00.000000', 0.18, 76)
2018-05-08 18:31:46,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,918 INFO sqlalchemy.engine.base.Engine ('2011-08-08 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:46,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,920 INFO sqlalchemy.engine.base.Engine ('2011-08-09 00:00:00.000000', 1.25, 73)
2018-05-08 18:31:46,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,922 INFO sqlalchemy.engine.base.Engine ('2011-08-10 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:46,922 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,923 INFO sqlalchemy.engine.base.Engine ('2011-08-11 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:46,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,925 INFO sqlalchemy.engine.base.Engine ('2011-08-12 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:46,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,927 INFO sqlalchemy.engine.base.Engine ('2011-08-13 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:46,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,929 INFO sqlalchemy.engine.base.Engine ('2011-08-14 00:00:00.000000', 0.53, 74)
2018-05-08 18:31:46,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,930 INFO sqlalchemy.engine.base.Engine ('2011-08-15 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:46,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,932 INFO sqlalchemy.engine.base.Engine ('2011-08-16 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:46,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,934 INFO sqlalchemy.engine.base.Engine ('2011-08-17 00:00:00.000000', 0.55, 74)
2018-05-08 18:31:46,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,935 INFO sqlalchemy.engine.base.Engine ('2011-08-18 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:46,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,937 INFO sqlalchemy.engine.base.Engine ('2011-08-19 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:46,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,939 INFO sqlalchemy.engine.base.Engine ('2011-08-20 00:00:00.000000', 0.36, 71)
2018-05-08 18:31:46,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,941 INFO sqlalchemy.engine.base.Engine ('2011-08-23 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:46,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,942 INFO sqlalchemy.engine.base.Engine ('2011-08-24 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:46,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,944 INFO sqlalchemy.engine.base.Engine ('2011-08-25 00:00:00.000000', 0.39, 71)
2018-05-08 18:31:46,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,946 INFO sqlalchemy.engine.base.Engine ('2011-08-26 00:00:00.000000', 0.2, 71)
2018-05-08 18:31:46,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,948 INFO sqlalchemy.engine.base.Engine ('2011-08-27 00:00:00.000000', 0.6, 70)
2018-05-08 18:31:46,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,949 INFO sqlalchemy.engine.base.Engine ('2011-08-28 00:00:00.000000', 0.41, 71)
2018-05-08 18:31:46,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,951 INFO sqlalchemy.engine.base.Engine ('2011-08-29 00:00:00.000000', 1.11, 70)
2018-05-08 18:31:46,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,953 INFO sqlalchemy.engine.base.Engine ('2011-08-30 00:00:00.000000', 0.56, 72)
2018-05-08 18:31:46,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,955 INFO sqlalchemy.engine.base.Engine ('2011-08-31 00:00:00.000000', 0.57, 74)
2018-05-08 18:31:46,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,956 INFO sqlalchemy.engine.base.Engine ('2011-09-01 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:46,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,958 INFO sqlalchemy.engine.base.Engine ('2011-09-02 00:00:00.000000', 0.3, 76)
2018-05-08 18:31:46,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,959 INFO sqlalchemy.engine.base.Engine ('2011-09-03 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:46,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,961 INFO sqlalchemy.engine.base.Engine ('2011-09-04 00:00:00.000000', 0.18, 80)
2018-05-08 18:31:46,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,963 INFO sqlalchemy.engine.base.Engine ('2011-09-05 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:46,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,965 INFO sqlalchemy.engine.base.Engine ('2011-09-06 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:46,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,966 INFO sqlalchemy.engine.base.Engine ('2011-09-07 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:46,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,968 INFO sqlalchemy.engine.base.Engine ('2011-09-08 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:46,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,970 INFO sqlalchemy.engine.base.Engine ('2011-09-09 00:00:00.000000', 0.09, 75)

2018-05-08 18:31:46,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,972 INFO sqlalchemy.engine.base.Engine ('2011-09-10 00:00:00.000000', 0.25, 76)
2018-05-08 18:31:46,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,974 INFO sqlalchemy.engine.base.Engine ('2011-09-11 00:00:00.000000', 0.21, 71)
2018-05-08 18:31:46,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,976 INFO sqlalchemy.engine.base.Engine ('2011-09-12 00:00:00.000000', 0.38, 70)
2018-05-08 18:31:46,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,977 INFO sqlalchemy.engine.base.Engine ('2011-09-13 00:00:00.000000', 0.5, 72)
2018-05-08 18:31:46,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,979 INFO sqlalchemy.engine.base.Engine ('2011-09-14 00:00:00.000000', 0.19, 73)
2018-05-08 18:31:46,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,981 INFO sqlalchemy.engine.base.Engine ('2011-09-15 00:00:00.000000', 0.41, 74)
2018-05-08 18:31:46,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,982 INFO sqlalchemy.engine.base.Engine ('2011-09-16 00:00:00.000000', 0.95, 73)
2018-05-08 18:31:46,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,984 INFO sqlalchemy.engine.base.Engine ('2011-09-17 00:00:00.000000', 0.21, 70)
2018-05-08 18:31:46,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,986 INFO sqlalchemy.engine.base.Engine ('2011-09-18 00:00:00.000000', 0.88, 71)
2018-05-08 18:31:46,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,988 INFO sqlalchemy.engine.base.Engine ('2011-09-19 00:00:00.000000', 0.18, 73)
2018-05-08 18:31:46,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,989 INFO sqlalchemy.engine.base.Engine ('2011-09-20 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:46,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,991 INFO sqlalchemy.engine.base.Engine ('2011-09-21 00:00:00.000000', 0.19, 73)
2018-05-08 18:31:46,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,993 INFO sqlalchemy.engine.base.Engine ('2011-09-22 00:00:00.000000', 0.21, 72)
2018-05-08 18:31:46,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,994 INFO sqlalchemy.engine.base.Engine ('2011-09-23 00:00:00.000000', 0.39, 71)
2018-05-08 18:31:46,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,996 INFO sqlalchemy.engine.base.Engine ('2011-09-24 00:00:00.000000', 0.01, 76)
2018-05-08 18:31:46,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,998 INFO sqlalchemy.engine.base.Engine ('2011-09-25 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:46,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:46,999 INFO sqlalchemy.engine.base.Engine ('2011-09-26 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:47,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,001 INFO sqlalchemy.engine.base.Engine ('2011-09-27 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:47,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,003 INFO sqlalchemy.engine.base.Engine ('2011-09-28 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:47,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,005 INFO sqlalchemy.engine.base.Engine ('2011-09-29 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:47,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,007 INFO sqlalchemy.engine.base.Engine ('2011-09-30 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:47,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,009 INFO sqlalchemy.engine.base.Engine ('2011-10-01 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,011 INFO sqlalchemy.engine.base.Engine ('2011-10-02 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:47,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,012 INFO sqlalchemy.engine.base.Engine ('2011-10-03 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:47,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,014 INFO sqlalchemy.engine.base.Engine ('2011-10-04 00:00:00.000000', 0.57, 71)
2018-05-08 18:31:47,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,016 INFO sqlalchemy.engine.base.Engine ('2011-10-05 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:47,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,017 INFO sqlalchemy.engine.base.Engine ('2011-10-06 00:00:00.000000', 0.65, 73)
2018-05-08 18:31:47,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,019 INFO sqlalchemy.engine.base.Engine ('2011-10-07 00:00:00.000000', 0.44, 77)
2018-05-08 18:31:47,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,021 INFO sqlalchemy.engine.base.Engine ('2011-10-14 00:00:00.000000', 0.57, 72)
2018-05-08 18:31:47,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,022 INFO sqlalchemy.engine.base.Engine ('2011-10-15 00:00:00.000000', 1.72, 77)
2018-05-08 18:31:47,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,024 INFO sqlalchemy.engine.base.Engine ('2011-10-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:47,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,026 INFO sqlalchemy.engine.base.Engine ('2011-10-17 00:00:00.000000', 0.43, 70)
2018-05-08 18:31:47,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,027 INFO sqlalchemy.engine.base.Engine ('2011-10-18 00:00:00.000000', 0.44, 70)
2018-05-08 18:31:47,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,028 INFO sqlalchemy.engine.base.Engine ('2011-10-19 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:47,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,030 INFO sqlalchemy.engine.base.Engine ('2011-10-20 00:00:00.000000', 0.22, 68)

2018-05-08 18:31:47,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,032 INFO sqlalchemy.engine.base.Engine ('2011-10-21 00:00:00.000000', 0.46, 71)
2018-05-08 18:31:47,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,033 INFO sqlalchemy.engine.base.Engine ('2011-10-26 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:47,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,035 INFO sqlalchemy.engine.base.Engine ('2011-10-29 00:00:00.000000', 0.01, 69)
2018-05-08 18:31:47,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,036 INFO sqlalchemy.engine.base.Engine ('2011-10-30 00:00:00.000000', 0.3, 71)
2018-05-08 18:31:47,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,038 INFO sqlalchemy.engine.base.Engine ('2011-10-31 00:00:00.000000', 0.76, 70)
2018-05-08 18:31:47,039 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,040 INFO sqlalchemy.engine.base.Engine ('2011-11-01 00:00:00.000000', 2.24, 73)
2018-05-08 18:31:47,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,041 INFO sqlalchemy.engine.base.Engine ('2011-11-02 00:00:00.000000', 0.93, 71)
2018-05-08 18:31:47,042 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,043 INFO sqlalchemy.engine.base.Engine ('2011-11-03 00:00:00.000000', 0.58, 70)
2018-05-08 18:31:47,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,044 INFO sqlalchemy.engine.base.Engine ('2011-11-04 00:00:00.000000', 1.06, 71)
2018-05-08 18:31:47,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,092 INFO sqlalchemy.engine.base.Engine ('2011-11-05 00:00:00.000000', 0.17, 69)
2018-05-08 18:31:47,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,093 INFO sqlalchemy.engine.base.Engine ('2011-11-06 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:47,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,095 INFO sqlalchemy.engine.base.Engine ('2011-11-07 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:47,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,096 INFO sqlalchemy.engine.base.Engine ('2011-11-08 00:00:00.000000', 0.27, 73)
2018-05-08 18:31:47,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,098 INFO sqlalchemy.engine.base.Engine ('2011-11-09 00:00:00.000000', 0.28, 71)
2018-05-08 18:31:47,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,099 INFO sqlalchemy.engine.base.Engine ('2011-11-10 00:00:00.000000', 0.17, 71)
2018-05-08 18:31:47,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,101 INFO sqlalchemy.engine.base.Engine ('2011-11-11 00:00:00.000000', 1.96, 68)
2018-05-08 18:31:47,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,102 INFO sqlalchemy.engine.base.Engine ('2011-11-12 00:00:00.000000', 0.42, 67)
2018-05-08 18:31:47,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,104 INFO sqlalchemy.engine.base.Engine ('2011-11-13 00:00:00.000000', 0.07, 70)
2018-05-08 18:31:47,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,106 INFO sqlalchemy.engine.base.Engine ('2011-11-14 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:47,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,107 INFO sqlalchemy.engine.base.Engine ('2011-11-15 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:47,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,109 INFO sqlalchemy.engine.base.Engine ('2011-11-16 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,110 INFO sqlalchemy.engine.base.Engine ('2011-11-17 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:47,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,112 INFO sqlalchemy.engine.base.Engine ('2011-11-18 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:47,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,113 INFO sqlalchemy.engine.base.Engine ('2011-11-19 00:00:00.000000', 0.29, 76)
2018-05-08 18:31:47,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,115 INFO sqlalchemy.engine.base.Engine ('2011-11-20 00:00:00.000000', 0.4, 70)
2018-05-08 18:31:47,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,116 INFO sqlalchemy.engine.base.Engine ('2011-11-21 00:00:00.000000', 1.15, 72)
2018-05-08 18:31:47,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,118 INFO sqlalchemy.engine.base.Engine ('2011-11-22 00:00:00.000000', 1.13, 69)
2018-05-08 18:31:47,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,120 INFO sqlalchemy.engine.base.Engine ('2011-11-23 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:47,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,121 INFO sqlalchemy.engine.base.Engine ('2011-11-24 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:47,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,123 INFO sqlalchemy.engine.base.Engine ('2011-11-25 00:00:00.000000', 0.21, 67)
2018-05-08 18:31:47,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,124 INFO sqlalchemy.engine.base.Engine ('2011-11-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,126 INFO sqlalchemy.engine.base.Engine ('2011-11-27 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:47,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,127 INFO sqlalchemy.engine.base.Engine ('2011-11-28 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:47,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,129 INFO sqlalchemy.engine.base.Engine ('2011-11-29 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:47,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,131 INFO sqlalchemy.engine.base.Engine ('2011-11-30 00:00:00.000000', 0.32, 68)

2018-05-08 18:31:47,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,132 INFO sqlalchemy.engine.base.Engine ('2011-12-01 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:47,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,134 INFO sqlalchemy.engine.base.Engine ('2011-12-02 00:00:00.000000', 0.46, 73)
2018-05-08 18:31:47,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,136 INFO sqlalchemy.engine.base.Engine ('2011-12-03 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:47,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,138 INFO sqlalchemy.engine.base.Engine ('2011-12-04 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:47,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,139 INFO sqlalchemy.engine.base.Engine ('2011-12-05 00:00:00.000000', 0.22, 68)
2018-05-08 18:31:47,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,141 INFO sqlalchemy.engine.base.Engine ('2011-12-06 00:00:00.000000', 0.12, 67)
2018-05-08 18:31:47,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,142 INFO sqlalchemy.engine.base.Engine ('2011-12-07 00:00:00.000000', 0.26, 70)
2018-05-08 18:31:47,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,144 INFO sqlalchemy.engine.base.Engine ('2011-12-08 00:00:00.000000', 0.53, 67)
2018-05-08 18:31:47,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,146 INFO sqlalchemy.engine.base.Engine ('2011-12-11 00:00:00.000000', 1.35, 71)
2018-05-08 18:31:47,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,147 INFO sqlalchemy.engine.base.Engine ('2011-12-12 00:00:00.000000', 1.71, 69)
2018-05-08 18:31:47,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,149 INFO sqlalchemy.engine.base.Engine ('2011-12-13 00:00:00.000000', 6.42, 69)
2018-05-08 18:31:47,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,151 INFO sqlalchemy.engine.base.Engine ('2011-12-14 00:00:00.000000', 1.37, 68)
2018-05-08 18:31:47,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,153 INFO sqlalchemy.engine.base.Engine ('2011-12-15 00:00:00.000000', 1.18, 69)
2018-05-08 18:31:47,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,154 INFO sqlalchemy.engine.base.Engine ('2011-12-16 00:00:00.000000', 1.09, 69)
2018-05-08 18:31:47,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,156 INFO sqlalchemy.engine.base.Engine ('2011-12-17 00:00:00.000000', 0.63, 67)
2018-05-08 18:31:47,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,157 INFO sqlalchemy.engine.base.Engine ('2011-12-18 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:47,158 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,159 INFO sqlalchemy.engine.base.Engine ('2011-12-19 00:00:00.000000', 0.87, 68)
2018-05-08 18:31:47,160 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,161 INFO sqlalchemy.engine.base.Engine ('2011-12-20 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:47,162 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,162 INFO sqlalchemy.engine.base.Engine ('2011-12-21 00:00:00.000000', 1.52, 68)
2018-05-08 18:31:47,163 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,164 INFO sqlalchemy.engine.base.Engine ('2011-12-22 00:00:00.000000', 0.27, 69)
2018-05-08 18:31:47,165 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,166 INFO sqlalchemy.engine.base.Engine ('2011-12-23 00:00:00.000000', 0.42, 71)
2018-05-08 18:31:47,167 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,167 INFO sqlalchemy.engine.base.Engine ('2011-12-24 00:00:00.000000', 0.8, 65)
2018-05-08 18:31:47,168 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,169 INFO sqlalchemy.engine.base.Engine ('2011-12-25 00:00:00.000000', 0.58, 69)
2018-05-08 18:31:47,170 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,170 INFO sqlalchemy.engine.base.Engine ('2011-12-26 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:47,171 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,172 INFO sqlalchemy.engine.base.Engine ('2011-12-27 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:47,173 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,174 INFO sqlalchemy.engine.base.Engine ('2011-12-28 00:00:00.000000', 0.06, 69)
2018-05-08 18:31:47,175 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,175 INFO sqlalchemy.engine.base.Engine ('2011-12-29 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,176 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,177 INFO sqlalchemy.engine.base.Engine ('2011-12-30 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:47,178 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,179 INFO sqlalchemy.engine.base.Engine ('2011-12-31 00:00:00.000000', 0.25, 67)
2018-05-08 18:31:47,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,180 INFO sqlalchemy.engine.base.Engine ('2012-01-01 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:47,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,182 INFO sqlalchemy.engine.base.Engine ('2012-01-02 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:47,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,183 INFO sqlalchemy.engine.base.Engine ('2012-01-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,185 INFO sqlalchemy.engine.base.Engine ('2012-01-04 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:47,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,186 INFO sqlalchemy.engine.base.Engine ('2012-01-05 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:47,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,188 INFO sqlalchemy.engine.base.Engine ('2012-01-06 00:00:00.000000', 0.0, 72)

2018-05-08 18:31:47,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,190 INFO sqlalchemy.engine.base.Engine ('2012-01-10 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:47,191 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,191 INFO sqlalchemy.engine.base.Engine ('2012-01-11 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:47,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,193 INFO sqlalchemy.engine.base.Engine ('2012-01-12 00:00:00.000000', 0.11, 72)
2018-05-08 18:31:47,194 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,194 INFO sqlalchemy.engine.base.Engine ('2012-01-13 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:47,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,196 INFO sqlalchemy.engine.base.Engine ('2012-01-14 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:47,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,198 INFO sqlalchemy.engine.base.Engine ('2012-01-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:47,199 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,199 INFO sqlalchemy.engine.base.Engine ('2012-01-16 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:47,201 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,202 INFO sqlalchemy.engine.base.Engine ('2012-01-17 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:47,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,203 INFO sqlalchemy.engine.base.Engine ('2012-01-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,204 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,205 INFO sqlalchemy.engine.base.Engine ('2012-01-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:47,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,208 INFO sqlalchemy.engine.base.Engine ('2012-01-20 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,209 INFO sqlalchemy.engine.base.Engine ('2012-01-21 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,211 INFO sqlalchemy.engine.base.Engine ('2012-01-22 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:47,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,213 INFO sqlalchemy.engine.base.Engine ('2012-01-23 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:47,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,214 INFO sqlalchemy.engine.base.Engine ('2012-01-24 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:47,215 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,216 INFO sqlalchemy.engine.base.Engine ('2012-01-25 00:00:00.000000', 0.06, 67)
2018-05-08 18:31:47,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,218 INFO sqlalchemy.engine.base.Engine ('2012-01-26 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,219 INFO sqlalchemy.engine.base.Engine ('2012-01-27 00:00:00.000000', 0.05, 66)
2018-05-08 18:31:47,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,221 INFO sqlalchemy.engine.base.Engine ('2012-01-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,223 INFO sqlalchemy.engine.base.Engine ('2012-01-29 00:00:00.000000', 0.67, 69)
2018-05-08 18:31:47,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,224 INFO sqlalchemy.engine.base.Engine ('2012-01-30 00:00:00.000000', 0.35, 66)
2018-05-08 18:31:47,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,226 INFO sqlalchemy.engine.base.Engine ('2012-01-31 00:00:00.000000', 0.04, 67)
2018-05-08 18:31:47,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,227 INFO sqlalchemy.engine.base.Engine ('2012-02-01 00:00:00.000000', 0.01, 66)
2018-05-08 18:31:47,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,229 INFO sqlalchemy.engine.base.Engine ('2012-02-02 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,231 INFO sqlalchemy.engine.base.Engine ('2012-02-03 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:47,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,232 INFO sqlalchemy.engine.base.Engine ('2012-02-04 00:00:00.000000', 0.0, 61)
2018-05-08 18:31:47,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,234 INFO sqlalchemy.engine.base.Engine ('2012-02-05 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:47,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,235 INFO sqlalchemy.engine.base.Engine ('2012-02-06 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:47,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,238 INFO sqlalchemy.engine.base.Engine ('2012-02-07 00:00:00.000000', 0.7, 70)
2018-05-08 18:31:47,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,239 INFO sqlalchemy.engine.base.Engine ('2012-02-08 00:00:00.000000', 0.44, 66)
2018-05-08 18:31:47,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,241 INFO sqlalchemy.engine.base.Engine ('2012-02-09 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:47,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,243 INFO sqlalchemy.engine.base.Engine ('2012-02-10 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:47,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,244 INFO sqlalchemy.engine.base.Engine ('2012-02-11 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:47,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,246 INFO sqlalchemy.engine.base.Engine ('2012-02-12 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:47,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,248 INFO sqlalchemy.engine.base.Engine ('2012-02-13 00:00:00.000000', 1.26, 67)

2018-05-08 18:31:47,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,249 INFO sqlalchemy.engine.base.Engine ('2012-02-14 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:47,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,251 INFO sqlalchemy.engine.base.Engine ('2012-02-15 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,253 INFO sqlalchemy.engine.base.Engine ('2012-02-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,254 INFO sqlalchemy.engine.base.Engine ('2012-02-17 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:47,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,299 INFO sqlalchemy.engine.base.Engine ('2012-02-18 00:00:00.000000', 0.67, 69)
2018-05-08 18:31:47,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,300 INFO sqlalchemy.engine.base.Engine ('2012-02-19 00:00:00.000000', 1.29, 72)
2018-05-08 18:31:47,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,302 INFO sqlalchemy.engine.base.Engine ('2012-02-20 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:47,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,304 INFO sqlalchemy.engine.base.Engine ('2012-02-21 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,305 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,305 INFO sqlalchemy.engine.base.Engine ('2012-02-22 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,307 INFO sqlalchemy.engine.base.Engine ('2012-02-23 00:00:00.000000', 1.31, 67)
2018-05-08 18:31:47,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,309 INFO sqlalchemy.engine.base.Engine ('2012-02-24 00:00:00.000000', 0.77, 74)
2018-05-08 18:31:47,310 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,311 INFO sqlalchemy.engine.base.Engine ('2012-02-25 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:47,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,313 INFO sqlalchemy.engine.base.Engine ('2012-02-26 00:00:00.000000', 0.3, 71)
2018-05-08 18:31:47,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,314 INFO sqlalchemy.engine.base.Engine ('2012-02-27 00:00:00.000000', 0.44, 69)
2018-05-08 18:31:47,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,316 INFO sqlalchemy.engine.base.Engine ('2012-02-28 00:00:00.000000', 0.4, 69)
2018-05-08 18:31:47,317 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,318 INFO sqlalchemy.engine.base.Engine ('2012-02-29 00:00:00.000000', 0.55, 69)
2018-05-08 18:31:47,319 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,320 INFO sqlalchemy.engine.base.Engine ('2012-03-01 00:00:00.000000', 0.64, 67)
2018-05-08 18:31:47,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,321 INFO sqlalchemy.engine.base.Engine ('2012-03-02 00:00:00.000000', 0.26, 66)
2018-05-08 18:31:47,322 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,323 INFO sqlalchemy.engine.base.Engine ('2012-03-03 00:00:00.000000', 1.1, 66)
2018-05-08 18:31:47,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,325 INFO sqlalchemy.engine.base.Engine ('2012-03-04 00:00:00.000000', 2.0, 67)
2018-05-08 18:31:47,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,327 INFO sqlalchemy.engine.base.Engine ('2012-03-05 00:00:00.000000', 5.37, 64)
2018-05-08 18:31:47,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,328 INFO sqlalchemy.engine.base.Engine ('2012-03-06 00:00:00.000000', 2.61, 67)
2018-05-08 18:31:47,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,330 INFO sqlalchemy.engine.base.Engine ('2012-03-07 00:00:00.000000', 2.63, 69)
2018-05-08 18:31:47,331 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,332 INFO sqlalchemy.engine.base.Engine ('2012-03-08 00:00:00.000000', 2.09, 66)
2018-05-08 18:31:47,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,334 INFO sqlalchemy.engine.base.Engine ('2012-03-09 00:00:00.000000', 3.23, 64)
2018-05-08 18:31:47,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,336 INFO sqlalchemy.engine.base.Engine ('2012-03-10 00:00:00.000000', 0.15, 70)
2018-05-08 18:31:47,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,337 INFO sqlalchemy.engine.base.Engine ('2012-03-11 00:00:00.000000', 0.31, 71)
2018-05-08 18:31:47,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,339 INFO sqlalchemy.engine.base.Engine ('2012-03-12 00:00:00.000000', 1.6, 67)
2018-05-08 18:31:47,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,340 INFO sqlalchemy.engine.base.Engine ('2012-03-13 00:00:00.000000', 0.45, 67)
2018-05-08 18:31:47,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,342 INFO sqlalchemy.engine.base.Engine ('2012-03-14 00:00:00.000000', 0.01, 65)
2018-05-08 18:31:47,343 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,344 INFO sqlalchemy.engine.base.Engine ('2012-03-15 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:47,345 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,346 INFO sqlalchemy.engine.base.Engine ('2012-03-16 00:00:00.000000', 0.08, 66)
2018-05-08 18:31:47,347 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,347 INFO sqlalchemy.engine.base.Engine ('2012-03-17 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:47,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,349 INFO sqlalchemy.engine.base.Engine ('2012-03-18 00:00:00.000000', 0.65, 66)
2018-05-08 18:31:47,350 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,351 INFO sqlalchemy.engine.base.Engine ('2012-03-19 00:00:00.000000', 1.61, 69)

2018-05-08 18:31:47,352 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,352 INFO sqlalchemy.engine.base.Engine ('2012-03-20 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:47,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,354 INFO sqlalchemy.engine.base.Engine ('2012-03-21 00:00:00.000000', 0.43, 65)
2018-05-08 18:31:47,355 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,355 INFO sqlalchemy.engine.base.Engine ('2012-03-22 00:00:00.000000', 0.48, 69)
2018-05-08 18:31:47,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,357 INFO sqlalchemy.engine.base.Engine ('2012-03-23 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:47,358 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,359 INFO sqlalchemy.engine.base.Engine ('2012-03-24 00:00:00.000000', 0.06, 67)
2018-05-08 18:31:47,360 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,360 INFO sqlalchemy.engine.base.Engine ('2012-03-25 00:00:00.000000', 1.92, 68)
2018-05-08 18:31:47,361 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,362 INFO sqlalchemy.engine.base.Engine ('2012-03-26 00:00:00.000000', 0.37, 66)
2018-05-08 18:31:47,363 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,364 INFO sqlalchemy.engine.base.Engine ('2012-03-27 00:00:00.000000', 0.57, 66)
2018-05-08 18:31:47,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,365 INFO sqlalchemy.engine.base.Engine ('2012-03-28 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:47,366 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,367 INFO sqlalchemy.engine.base.Engine ('2012-03-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:47,368 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,369 INFO sqlalchemy.engine.base.Engine ('2012-03-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,370 INFO sqlalchemy.engine.base.Engine ('2012-03-31 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,371 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,372 INFO sqlalchemy.engine.base.Engine ('2012-04-01 00:00:00.000000', 0.04, 71)
2018-05-08 18:31:47,373 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,374 INFO sqlalchemy.engine.base.Engine ('2012-04-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,375 INFO sqlalchemy.engine.base.Engine ('2012-04-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,376 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,377 INFO sqlalchemy.engine.base.Engine ('2012-04-04 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:47,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,378 INFO sqlalchemy.engine.base.Engine ('2012-04-05 00:00:00.000000', 0.89, 69)
2018-05-08 18:31:47,379 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,380 INFO sqlalchemy.engine.base.Engine ('2012-04-06 00:00:00.000000', 0.1, 68)
2018-05-08 18:31:47,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,382 INFO sqlalchemy.engine.base.Engine ('2012-04-07 00:00:00.000000', 1.75, 70)
2018-05-08 18:31:47,382 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,383 INFO sqlalchemy.engine.base.Engine ('2012-04-08 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:47,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,385 INFO sqlalchemy.engine.base.Engine ('2012-04-09 00:00:00.000000', 3.27, 64)
2018-05-08 18:31:47,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,387 INFO sqlalchemy.engine.base.Engine ('2012-04-10 00:00:00.000000', 1.32, 64)
2018-05-08 18:31:47,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,389 INFO sqlalchemy.engine.base.Engine ('2012-04-11 00:00:00.000000', 1.47, 69)
2018-05-08 18:31:47,390 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,390 INFO sqlalchemy.engine.base.Engine ('2012-04-12 00:00:00.000000', 0.15, 69)
2018-05-08 18:31:47,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,392 INFO sqlalchemy.engine.base.Engine ('2012-04-13 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:47,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,394 INFO sqlalchemy.engine.base.Engine ('2012-04-14 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:47,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,395 INFO sqlalchemy.engine.base.Engine ('2012-04-15 00:00:00.000000', 0.18, 69)
2018-05-08 18:31:47,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,397 INFO sqlalchemy.engine.base.Engine ('2012-04-16 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:47,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,399 INFO sqlalchemy.engine.base.Engine ('2012-04-17 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:47,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,400 INFO sqlalchemy.engine.base.Engine ('2012-04-18 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:47,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,402 INFO sqlalchemy.engine.base.Engine ('2012-04-19 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:47,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,404 INFO sqlalchemy.engine.base.Engine ('2012-04-20 00:00:00.000000', 0.04, 67)
2018-05-08 18:31:47,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,405 INFO sqlalchemy.engine.base.Engine ('2012-04-23 00:00:00.000000', 1.62, 65)
2018-05-08 18:31:47,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,407 INFO sqlalchemy.engine.base.Engine ('2012-04-24 00:00:00.000000', 0.2, 68)
2018-05-08 18:31:47,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,409 INFO sqlalchemy.engine.base.Engine ('2012-04-25 00:00:00.000000', 0.3, 66)

2018-05-08 18:31:47,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,410 INFO sqlalchemy.engine.base.Engine ('2012-04-26 00:00:00.000000', 0.61, 76)
2018-05-08 18:31:47,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,412 INFO sqlalchemy.engine.base.Engine ('2012-04-27 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:47,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,414 INFO sqlalchemy.engine.base.Engine ('2012-04-28 00:00:00.000000', 0.65, 68)
2018-05-08 18:31:47,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,415 INFO sqlalchemy.engine.base.Engine ('2012-04-29 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:47,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,417 INFO sqlalchemy.engine.base.Engine ('2012-04-30 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:47,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,419 INFO sqlalchemy.engine.base.Engine ('2012-05-01 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:47,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,421 INFO sqlalchemy.engine.base.Engine ('2012-05-02 00:00:00.000000', 0.57, 67)
2018-05-08 18:31:47,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,422 INFO sqlalchemy.engine.base.Engine ('2012-05-03 00:00:00.000000', 0.16, 70)
2018-05-08 18:31:47,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,423 INFO sqlalchemy.engine.base.Engine ('2012-05-04 00:00:00.000000', 1.21, 66)
2018-05-08 18:31:47,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,425 INFO sqlalchemy.engine.base.Engine ('2012-05-05 00:00:00.000000', 0.9, 67)
2018-05-08 18:31:47,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,426 INFO sqlalchemy.engine.base.Engine ('2012-05-06 00:00:00.000000', 0.14, 67)
2018-05-08 18:31:47,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,428 INFO sqlalchemy.engine.base.Engine ('2012-05-07 00:00:00.000000', 0.54, 68)
2018-05-08 18:31:47,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,430 INFO sqlalchemy.engine.base.Engine ('2012-05-08 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:47,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,432 INFO sqlalchemy.engine.base.Engine ('2012-05-09 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:47,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,433 INFO sqlalchemy.engine.base.Engine ('2012-05-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:47,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,435 INFO sqlalchemy.engine.base.Engine ('2012-05-11 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:47,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,437 INFO sqlalchemy.engine.base.Engine ('2012-05-12 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:47,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,438 INFO sqlalchemy.engine.base.Engine ('2012-05-13 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:47,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,440 INFO sqlalchemy.engine.base.Engine ('2012-05-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:47,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,441 INFO sqlalchemy.engine.base.Engine ('2012-05-15 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:47,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,443 INFO sqlalchemy.engine.base.Engine ('2012-05-16 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:47,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,445 INFO sqlalchemy.engine.base.Engine ('2012-05-17 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:47,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,447 INFO sqlalchemy.engine.base.Engine ('2012-05-18 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:47,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,449 INFO sqlalchemy.engine.base.Engine ('2012-05-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:47,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,450 INFO sqlalchemy.engine.base.Engine ('2012-05-20 00:00:00.000000', 0.02, 68)
2018-05-08 18:31:47,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,452 INFO sqlalchemy.engine.base.Engine ('2012-05-21 00:00:00.000000', 0.2, 73)
2018-05-08 18:31:47,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,454 INFO sqlalchemy.engine.base.Engine ('2012-05-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,455 INFO sqlalchemy.engine.base.Engine ('2012-05-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,457 INFO sqlalchemy.engine.base.Engine ('2012-05-24 00:00:00.000000', 0.07, 72)
2018-05-08 18:31:47,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,459 INFO sqlalchemy.engine.base.Engine ('2012-05-25 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:47,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,460 INFO sqlalchemy.engine.base.Engine ('2012-05-26 00:00:00.000000', 0.37, 74)
2018-05-08 18:31:47,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,462 INFO sqlalchemy.engine.base.Engine ('2012-05-27 00:00:00.000000', 0.67, 73)
2018-05-08 18:31:47,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,464 INFO sqlalchemy.engine.base.Engine ('2012-05-28 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:47,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,466 INFO sqlalchemy.engine.base.Engine ('2012-05-29 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:47,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,510 INFO sqlalchemy.engine.base.Engine ('2012-05-30 00:00:00.000000', 0.01, 70)

2018-05-08 18:31:47,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,511 INFO sqlalchemy.engine.base.Engine ('2012-05-31 00:00:00.000000', 0.62, 68)
2018-05-08 18:31:47,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,513 INFO sqlalchemy.engine.base.Engine ('2012-06-01 00:00:00.000000', 0.26, 69)
2018-05-08 18:31:47,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,514 INFO sqlalchemy.engine.base.Engine ('2012-06-02 00:00:00.000000', 0.22, 73)
2018-05-08 18:31:47,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,516 INFO sqlalchemy.engine.base.Engine ('2012-06-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,517 INFO sqlalchemy.engine.base.Engine ('2012-06-04 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:47,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,519 INFO sqlalchemy.engine.base.Engine ('2012-06-05 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,520 INFO sqlalchemy.engine.base.Engine ('2012-06-06 00:00:00.000000', 0.72, 72)
2018-05-08 18:31:47,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,522 INFO sqlalchemy.engine.base.Engine ('2012-06-07 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:47,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,524 INFO sqlalchemy.engine.base.Engine ('2012-06-08 00:00:00.000000', 0.3, 74)
2018-05-08 18:31:47,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,525 INFO sqlalchemy.engine.base.Engine ('2012-06-09 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:47,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,527 INFO sqlalchemy.engine.base.Engine ('2012-06-10 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:47,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,528 INFO sqlalchemy.engine.base.Engine ('2012-06-11 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:47,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,530 INFO sqlalchemy.engine.base.Engine ('2012-06-12 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:47,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,532 INFO sqlalchemy.engine.base.Engine ('2012-06-13 00:00:00.000000', 0.48, 70)
2018-05-08 18:31:47,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,533 INFO sqlalchemy.engine.base.Engine ('2012-06-14 00:00:00.000000', 0.21, 73)
2018-05-08 18:31:47,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,535 INFO sqlalchemy.engine.base.Engine ('2012-06-15 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,536 INFO sqlalchemy.engine.base.Engine ('2012-06-16 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,538 INFO sqlalchemy.engine.base.Engine ('2012-06-17 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:47,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,539 INFO sqlalchemy.engine.base.Engine ('2012-06-18 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,541 INFO sqlalchemy.engine.base.Engine ('2012-06-19 00:00:00.000000', 0.38, 70)
2018-05-08 18:31:47,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,542 INFO sqlalchemy.engine.base.Engine ('2012-06-20 00:00:00.000000', 1.84, 69)
2018-05-08 18:31:47,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,544 INFO sqlalchemy.engine.base.Engine ('2012-06-21 00:00:00.000000', 0.34, 71)
2018-05-08 18:31:47,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,546 INFO sqlalchemy.engine.base.Engine ('2012-06-23 00:00:00.000000', 0.94, 68)
2018-05-08 18:31:47,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,547 INFO sqlalchemy.engine.base.Engine ('2012-06-24 00:00:00.000000', 1.13, 68)
2018-05-08 18:31:47,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,549 INFO sqlalchemy.engine.base.Engine ('2012-06-25 00:00:00.000000', 0.89, 68)
2018-05-08 18:31:47,550 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,550 INFO sqlalchemy.engine.base.Engine ('2012-06-26 00:00:00.000000', 0.92, 69)
2018-05-08 18:31:47,551 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,552 INFO sqlalchemy.engine.base.Engine ('2012-06-27 00:00:00.000000', 0.73, 69)
2018-05-08 18:31:47,553 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,554 INFO sqlalchemy.engine.base.Engine ('2012-06-28 00:00:00.000000', 0.37, 69)
2018-05-08 18:31:47,555 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,555 INFO sqlalchemy.engine.base.Engine ('2012-06-29 00:00:00.000000', 0.79, 71)
2018-05-08 18:31:47,556 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,557 INFO sqlalchemy.engine.base.Engine ('2012-07-02 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:47,558 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,559 INFO sqlalchemy.engine.base.Engine ('2012-07-03 00:00:00.000000', 1.04, 68)
2018-05-08 18:31:47,560 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,560 INFO sqlalchemy.engine.base.Engine ('2012-07-04 00:00:00.000000', 0.85, 70)
2018-05-08 18:31:47,561 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,562 INFO sqlalchemy.engine.base.Engine ('2012-07-05 00:00:00.000000', 0.98, 71)
2018-05-08 18:31:47,563 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,564 INFO sqlalchemy.engine.base.Engine ('2012-07-06 00:00:00.000000', 1.08, 70)
2018-05-08 18:31:47,565 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,565 INFO sqlalchemy.engine.base.Engine ('2012-07-07 00:00:00.000000', 0.86, 70)

2018-05-08 18:31:47,566 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,567 INFO sqlalchemy.engine.base.Engine ('2012-07-08 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:47,568 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,568 INFO sqlalchemy.engine.base.Engine ('2012-07-09 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:47,569 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,570 INFO sqlalchemy.engine.base.Engine ('2012-07-10 00:00:00.000000', 0.12, 70)
2018-05-08 18:31:47,571 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,571 INFO sqlalchemy.engine.base.Engine ('2012-07-11 00:00:00.000000', 0.39, 70)
2018-05-08 18:31:47,573 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,573 INFO sqlalchemy.engine.base.Engine ('2012-07-12 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,574 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,575 INFO sqlalchemy.engine.base.Engine ('2012-07-13 00:00:00.000000', 0.52, 72)
2018-05-08 18:31:47,576 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,576 INFO sqlalchemy.engine.base.Engine ('2012-07-14 00:00:00.000000', 0.29, 74)
2018-05-08 18:31:47,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,578 INFO sqlalchemy.engine.base.Engine ('2012-07-15 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:47,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,580 INFO sqlalchemy.engine.base.Engine ('2012-07-16 00:00:00.000000', 0.83, 72)
2018-05-08 18:31:47,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,581 INFO sqlalchemy.engine.base.Engine ('2012-07-17 00:00:00.000000', 0.71, 75)
2018-05-08 18:31:47,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,583 INFO sqlalchemy.engine.base.Engine ('2012-07-18 00:00:00.000000', 1.0, 72)
2018-05-08 18:31:47,584 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,584 INFO sqlalchemy.engine.base.Engine ('2012-07-19 00:00:00.000000', 0.34, 68)
2018-05-08 18:31:47,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,586 INFO sqlalchemy.engine.base.Engine ('2012-07-20 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:47,587 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,588 INFO sqlalchemy.engine.base.Engine ('2012-07-21 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:47,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,589 INFO sqlalchemy.engine.base.Engine ('2012-07-22 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:47,590 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,591 INFO sqlalchemy.engine.base.Engine ('2012-07-23 00:00:00.000000', 0.29, 73)
2018-05-08 18:31:47,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,592 INFO sqlalchemy.engine.base.Engine ('2012-07-24 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:47,593 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,594 INFO sqlalchemy.engine.base.Engine ('2012-07-25 00:00:00.000000', 0.18, 72)
2018-05-08 18:31:47,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,596 INFO sqlalchemy.engine.base.Engine ('2012-07-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,598 INFO sqlalchemy.engine.base.Engine ('2012-07-27 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:47,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,600 INFO sqlalchemy.engine.base.Engine ('2012-07-28 00:00:00.000000', 0.5, 70)
2018-05-08 18:31:47,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,602 INFO sqlalchemy.engine.base.Engine ('2012-07-29 00:00:00.000000', 2.87, 69)
2018-05-08 18:31:47,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,603 INFO sqlalchemy.engine.base.Engine ('2012-07-30 00:00:00.000000', 0.36, 72)
2018-05-08 18:31:47,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,605 INFO sqlalchemy.engine.base.Engine ('2012-07-31 00:00:00.000000', 0.59, 73)
2018-05-08 18:31:47,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,606 INFO sqlalchemy.engine.base.Engine ('2012-08-01 00:00:00.000000', 0.05, 71)
2018-05-08 18:31:47,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,608 INFO sqlalchemy.engine.base.Engine ('2012-08-02 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:47,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,609 INFO sqlalchemy.engine.base.Engine ('2012-08-03 00:00:00.000000', 0.09, 72)
2018-05-08 18:31:47,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,611 INFO sqlalchemy.engine.base.Engine ('2012-08-04 00:00:00.000000', 0.06, 72)
2018-05-08 18:31:47,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,613 INFO sqlalchemy.engine.base.Engine ('2012-08-05 00:00:00.000000', 0.44, 70)
2018-05-08 18:31:47,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,614 INFO sqlalchemy.engine.base.Engine ('2012-08-06 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:47,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,616 INFO sqlalchemy.engine.base.Engine ('2012-08-07 00:00:00.000000', 0.22, 71)
2018-05-08 18:31:47,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,618 INFO sqlalchemy.engine.base.Engine ('2012-08-08 00:00:00.000000', 0.44, 71)
2018-05-08 18:31:47,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,620 INFO sqlalchemy.engine.base.Engine ('2012-08-09 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:47,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,621 INFO sqlalchemy.engine.base.Engine ('2012-08-10 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:47,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,623 INFO sqlalchemy.engine.base.Engine ('2012-08-11 00:00:00.000000', 0.26, 67)

2018-05-08 18:31:47,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,625 INFO sqlalchemy.engine.base.Engine ('2012-08-12 00:00:00.000000', 0.23, 69)
2018-05-08 18:31:47,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,626 INFO sqlalchemy.engine.base.Engine ('2012-08-13 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:47,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,628 INFO sqlalchemy.engine.base.Engine ('2012-08-14 00:00:00.000000', 0.26, 73)
2018-05-08 18:31:47,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,630 INFO sqlalchemy.engine.base.Engine ('2012-08-15 00:00:00.000000', 0.02, 73)
2018-05-08 18:31:47,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,631 INFO sqlalchemy.engine.base.Engine ('2012-08-16 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,633 INFO sqlalchemy.engine.base.Engine ('2012-08-17 00:00:00.000000', 0.24, 72)
2018-05-08 18:31:47,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,634 INFO sqlalchemy.engine.base.Engine ('2012-08-20 00:00:00.000000', 0.38, 72)
2018-05-08 18:31:47,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,636 INFO sqlalchemy.engine.base.Engine ('2012-08-21 00:00:00.000000', 0.41, 71)
2018-05-08 18:31:47,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,638 INFO sqlalchemy.engine.base.Engine ('2012-08-22 00:00:00.000000', 0.24, 73)
2018-05-08 18:31:47,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,639 INFO sqlalchemy.engine.base.Engine ('2012-08-23 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:47,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,641 INFO sqlalchemy.engine.base.Engine ('2012-08-24 00:00:00.000000', 0.53, 72)
2018-05-08 18:31:47,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,643 INFO sqlalchemy.engine.base.Engine ('2012-08-25 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:47,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,644 INFO sqlalchemy.engine.base.Engine ('2012-08-28 00:00:00.000000', 1.19, 69)
2018-05-08 18:31:47,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,646 INFO sqlalchemy.engine.base.Engine ('2012-08-29 00:00:00.000000', 0.9, 72)
2018-05-08 18:31:47,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,648 INFO sqlalchemy.engine.base.Engine ('2012-08-30 00:00:00.000000', 0.44, 72)
2018-05-08 18:31:47,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,649 INFO sqlalchemy.engine.base.Engine ('2012-08-31 00:00:00.000000', 0.26, 70)
2018-05-08 18:31:47,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,651 INFO sqlalchemy.engine.base.Engine ('2012-09-01 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:47,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,652 INFO sqlalchemy.engine.base.Engine ('2012-09-02 00:00:00.000000', 0.46, 67)
2018-05-08 18:31:47,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,654 INFO sqlalchemy.engine.base.Engine ('2012-09-03 00:00:00.000000', 0.19, 69)
2018-05-08 18:31:47,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,656 INFO sqlalchemy.engine.base.Engine ('2012-09-04 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:47,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,657 INFO sqlalchemy.engine.base.Engine ('2012-09-05 00:00:00.000000', 0.59, 69)
2018-05-08 18:31:47,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,659 INFO sqlalchemy.engine.base.Engine ('2012-09-06 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:47,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,661 INFO sqlalchemy.engine.base.Engine ('2012-09-07 00:00:00.000000', 1.24, 69)
2018-05-08 18:31:47,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,663 INFO sqlalchemy.engine.base.Engine ('2012-09-08 00:00:00.000000', 2.48, 69)
2018-05-08 18:31:47,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,665 INFO sqlalchemy.engine.base.Engine ('2012-09-09 00:00:00.000000', 2.57, 71)
2018-05-08 18:31:47,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,667 INFO sqlalchemy.engine.base.Engine ('2012-09-10 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:47,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,669 INFO sqlalchemy.engine.base.Engine ('2012-09-11 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:47,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,671 INFO sqlalchemy.engine.base.Engine ('2012-09-12 00:00:00.000000', 0.23, 71)
2018-05-08 18:31:47,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,672 INFO sqlalchemy.engine.base.Engine ('2012-09-13 00:00:00.000000', 0.04, 70)
2018-05-08 18:31:47,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,720 INFO sqlalchemy.engine.base.Engine ('2012-09-14 00:00:00.000000', 0.52, 69)
2018-05-08 18:31:47,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,721 INFO sqlalchemy.engine.base.Engine ('2012-09-15 00:00:00.000000', 0.41, 67)
2018-05-08 18:31:47,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,723 INFO sqlalchemy.engine.base.Engine ('2012-09-16 00:00:00.000000', 0.62, 70)
2018-05-08 18:31:47,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,725 INFO sqlalchemy.engine.base.Engine ('2012-09-17 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:47,726 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,726 INFO sqlalchemy.engine.base.Engine ('2012-09-18 00:00:00.000000', 0.38, 68)
2018-05-08 18:31:47,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,728 INFO sqlalchemy.engine.base.Engine ('2012-09-19 00:00:00.000000', 0.35, 70)

2018-05-08 18:31:47,729 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,730 INFO sqlalchemy.engine.base.Engine ('2012-09-20 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:47,731 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,731 INFO sqlalchemy.engine.base.Engine ('2012-09-21 00:00:00.000000', 0.39, 70)
2018-05-08 18:31:47,732 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,733 INFO sqlalchemy.engine.base.Engine ('2012-09-22 00:00:00.000000', 0.17, 69)
2018-05-08 18:31:47,734 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,734 INFO sqlalchemy.engine.base.Engine ('2012-09-23 00:00:00.000000', 0.99, 71)
2018-05-08 18:31:47,735 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,736 INFO sqlalchemy.engine.base.Engine ('2012-09-24 00:00:00.000000', 1.58, 69)
2018-05-08 18:31:47,737 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,737 INFO sqlalchemy.engine.base.Engine ('2012-09-25 00:00:00.000000', 0.56, 69)
2018-05-08 18:31:47,738 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,739 INFO sqlalchemy.engine.base.Engine ('2012-09-26 00:00:00.000000', 0.3, 69)
2018-05-08 18:31:47,740 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,741 INFO sqlalchemy.engine.base.Engine ('2012-09-27 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:47,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,743 INFO sqlalchemy.engine.base.Engine ('2012-09-28 00:00:00.000000', 0.31, 70)
2018-05-08 18:31:47,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,744 INFO sqlalchemy.engine.base.Engine ('2012-10-09 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:47,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,746 INFO sqlalchemy.engine.base.Engine ('2012-10-10 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:47,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,748 INFO sqlalchemy.engine.base.Engine ('2012-10-11 00:00:00.000000', 0.4, 76)
2018-05-08 18:31:47,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,749 INFO sqlalchemy.engine.base.Engine ('2012-10-12 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:47,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,751 INFO sqlalchemy.engine.base.Engine ('2012-10-23 00:00:00.000000', 0.08, 71)
2018-05-08 18:31:47,752 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,752 INFO sqlalchemy.engine.base.Engine ('2012-10-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:47,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,754 INFO sqlalchemy.engine.base.Engine ('2012-10-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:47,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,756 INFO sqlalchemy.engine.base.Engine ('2012-10-26 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:47,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,757 INFO sqlalchemy.engine.base.Engine ('2012-10-27 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:47,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,759 INFO sqlalchemy.engine.base.Engine ('2012-10-28 00:00:00.000000', 0.49, 71)
2018-05-08 18:31:47,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,761 INFO sqlalchemy.engine.base.Engine ('2012-10-29 00:00:00.000000', 0.53, 74)
2018-05-08 18:31:47,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,762 INFO sqlalchemy.engine.base.Engine ('2012-10-30 00:00:00.000000', 0.2, 68)
2018-05-08 18:31:47,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:47,764 INFO sqlalchemy.engine.base.Engine ('2012-10-31 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:47,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,631 INFO sqlalchemy.engine.base.Engine ('2014-02-09 00:00:00.000000', 0.22, 69)
2018-05-08 18:31:48,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,633 INFO sqlalchemy.engine.base.Engine ('2014-02-10 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:48,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,635 INFO sqlalchemy.engine.base.Engine ('2014-02-11 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:48,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,636 INFO sqlalchemy.engine.base.Engine ('2014-02-12 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:48,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,638 INFO sqlalchemy.engine.base.Engine ('2014-02-13 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:48,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,640 INFO sqlalchemy.engine.base.Engine ('2014-02-14 00:00:00.000000', 0.12, 69)
2018-05-08 18:31:48,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,641 INFO sqlalchemy.engine.base.Engine ('2014-02-15 00:00:00.000000', 2.97, 69)
2018-05-08 18:31:48,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,643 INFO sqlalchemy.engine.base.Engine ('2014-02-16 00:00:00.000000', 0.76, 69)
2018-05-08 18:31:48,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,645 INFO sqlalchemy.engine.base.Engine ('2014-02-17 00:00:00.000000', 0.36, 68)
2018-05-08 18:31:48,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,646 INFO sqlalchemy.engine.base.Engine ('2014-02-18 00:00:00.000000', 0.26, 68)
2018-05-08 18:31:48,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,648 INFO sqlalchemy.engine.base.Engine ('2014-02-19 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:48,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,649 INFO sqlalchemy.engine.base.Engine ('2014-02-22 00:00:00.000000', 0.02, 83)
2018-05-08 18:31:48,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,651 INFO sqlalchemy.engine.base.Engine ('2014-02-23 00:00:00.000000', 0.08, 66)

2018-05-08 18:31:48,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,653 INFO sqlalchemy.engine.base.Engine ('2014-02-24 00:00:00.000000', 0.05, 68)
2018-05-08 18:31:48,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,654 INFO sqlalchemy.engine.base.Engine ('2014-02-25 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:48,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,656 INFO sqlalchemy.engine.base.Engine ('2014-02-26 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:48,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,657 INFO sqlalchemy.engine.base.Engine ('2014-02-27 00:00:00.000000', 0.05, 67)
2018-05-08 18:31:48,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,659 INFO sqlalchemy.engine.base.Engine ('2014-02-28 00:00:00.000000', 0.15, 68)
2018-05-08 18:31:48,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,661 INFO sqlalchemy.engine.base.Engine ('2014-03-01 00:00:00.000000', 0.42, 69)
2018-05-08 18:31:48,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,662 INFO sqlalchemy.engine.base.Engine ('2014-03-02 00:00:00.000000', 0.79, 66)
2018-05-08 18:31:48,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,664 INFO sqlalchemy.engine.base.Engine ('2014-03-03 00:00:00.000000', 0.14, 60)
2018-05-08 18:31:48,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,666 INFO sqlalchemy.engine.base.Engine ('2014-03-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:48,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,667 INFO sqlalchemy.engine.base.Engine ('2014-03-05 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:48,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,669 INFO sqlalchemy.engine.base.Engine ('2014-03-06 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:48,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,671 INFO sqlalchemy.engine.base.Engine ('2014-03-07 00:00:00.000000', 0.4, 69)
2018-05-08 18:31:48,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,672 INFO sqlalchemy.engine.base.Engine ('2014-03-08 00:00:00.000000', 0.78, 65)
2018-05-08 18:31:48,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,674 INFO sqlalchemy.engine.base.Engine ('2014-03-09 00:00:00.000000', 3.4, 68)
2018-05-08 18:31:48,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,677 INFO sqlalchemy.engine.base.Engine ('2014-03-10 00:00:00.000000', 2.14, 68)
2018-05-08 18:31:48,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,678 INFO sqlalchemy.engine.base.Engine ('2014-03-11 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:48,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,680 INFO sqlalchemy.engine.base.Engine ('2014-03-12 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:48,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,682 INFO sqlalchemy.engine.base.Engine ('2014-03-13 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:48,683 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,684 INFO sqlalchemy.engine.base.Engine ('2014-03-16 00:00:00.000000', 0.49, 66)
2018-05-08 18:31:48,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,686 INFO sqlalchemy.engine.base.Engine ('2014-03-26 00:00:00.000000', 1.47, 77)
2018-05-08 18:31:48,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,688 INFO sqlalchemy.engine.base.Engine ('2014-03-27 00:00:00.000000', 0.39, 69)
2018-05-08 18:31:48,689 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,690 INFO sqlalchemy.engine.base.Engine ('2014-03-28 00:00:00.000000', 0.36, 71)
2018-05-08 18:31:48,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,692 INFO sqlalchemy.engine.base.Engine ('2014-03-29 00:00:00.000000', 1.48, 70)
2018-05-08 18:31:48,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,694 INFO sqlalchemy.engine.base.Engine ('2014-04-01 00:00:00.000000', 0.79, 69)
2018-05-08 18:31:48,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,695 INFO sqlalchemy.engine.base.Engine ('2014-04-02 00:00:00.000000', 0.77, 71)
2018-05-08 18:31:48,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,697 INFO sqlalchemy.engine.base.Engine ('2014-04-03 00:00:00.000000', 0.44, 71)
2018-05-08 18:31:48,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,699 INFO sqlalchemy.engine.base.Engine ('2014-04-04 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:48,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,701 INFO sqlalchemy.engine.base.Engine ('2014-04-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:48,702 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,703 INFO sqlalchemy.engine.base.Engine ('2014-04-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:48,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,705 INFO sqlalchemy.engine.base.Engine ('2014-04-07 00:00:00.000000', 1.26, 66)
2018-05-08 18:31:48,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,706 INFO sqlalchemy.engine.base.Engine ('2014-04-08 00:00:00.000000', 0.38, 66)
2018-05-08 18:31:48,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,708 INFO sqlalchemy.engine.base.Engine ('2014-04-09 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:48,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,710 INFO sqlalchemy.engine.base.Engine ('2014-04-10 00:00:00.000000', 0.08, 64)
2018-05-08 18:31:48,711 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,711 INFO sqlalchemy.engine.base.Engine ('2014-04-11 00:00:00.000000', 0.02, 69)
2018-05-08 18:31:48,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,713 INFO sqlalchemy.engine.base.Engine ('2014-04-12 00:00:00.000000', 1.18, 65)

2018-05-08 18:31:48,714 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,715 INFO sqlalchemy.engine.base.Engine ('2014-04-13 00:00:00.000000', 0.53, 67)
2018-05-08 18:31:48,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,716 INFO sqlalchemy.engine.base.Engine ('2014-04-14 00:00:00.000000', 0.72, 68)
2018-05-08 18:31:48,717 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,718 INFO sqlalchemy.engine.base.Engine ('2014-04-15 00:00:00.000000', 0.05, 69)
2018-05-08 18:31:48,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,719 INFO sqlalchemy.engine.base.Engine ('2014-04-16 00:00:00.000000', 0.88, 70)
2018-05-08 18:31:48,720 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,721 INFO sqlalchemy.engine.base.Engine ('2014-04-17 00:00:00.000000', 0.08, 72)
2018-05-08 18:31:48,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,723 INFO sqlalchemy.engine.base.Engine ('2014-04-18 00:00:00.000000', 0.78, 70)
2018-05-08 18:31:48,723 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,724 INFO sqlalchemy.engine.base.Engine ('2014-04-19 00:00:00.000000', 0.44, 72)
2018-05-08 18:31:48,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,774 INFO sqlalchemy.engine.base.Engine ('2014-04-20 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:48,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,775 INFO sqlalchemy.engine.base.Engine ('2014-04-21 00:00:00.000000', 1.9, 68)
2018-05-08 18:31:48,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,777 INFO sqlalchemy.engine.base.Engine ('2014-04-22 00:00:00.000000', 1.56, 71)
2018-05-08 18:31:48,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,778 INFO sqlalchemy.engine.base.Engine ('2014-04-23 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:48,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,780 INFO sqlalchemy.engine.base.Engine ('2014-04-24 00:00:00.000000', 0.23, 71)
2018-05-08 18:31:48,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,782 INFO sqlalchemy.engine.base.Engine ('2014-04-25 00:00:00.000000', 0.81, 70)
2018-05-08 18:31:48,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,784 INFO sqlalchemy.engine.base.Engine ('2014-04-26 00:00:00.000000', 0.1, 68)
2018-05-08 18:31:48,785 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,785 INFO sqlalchemy.engine.base.Engine ('2014-04-27 00:00:00.000000', 2.44, 67)
2018-05-08 18:31:48,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,787 INFO sqlalchemy.engine.base.Engine ('2014-04-28 00:00:00.000000', 1.06, 66)
2018-05-08 18:31:48,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,788 INFO sqlalchemy.engine.base.Engine ('2014-04-29 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:48,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,790 INFO sqlalchemy.engine.base.Engine ('2014-04-30 00:00:00.000000', 0.22, 67)
2018-05-08 18:31:48,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,791 INFO sqlalchemy.engine.base.Engine ('2014-05-01 00:00:00.000000', 0.52, 67)
2018-05-08 18:31:48,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,793 INFO sqlalchemy.engine.base.Engine ('2014-05-02 00:00:00.000000', 0.15, 69)
2018-05-08 18:31:48,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,795 INFO sqlalchemy.engine.base.Engine ('2014-05-03 00:00:00.000000', 1.14, 71)
2018-05-08 18:31:48,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,797 INFO sqlalchemy.engine.base.Engine ('2014-05-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:48,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,798 INFO sqlalchemy.engine.base.Engine ('2014-05-05 00:00:00.000000', 0.03, 67)
2018-05-08 18:31:48,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,800 INFO sqlalchemy.engine.base.Engine ('2014-05-06 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:48,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,801 INFO sqlalchemy.engine.base.Engine ('2014-05-07 00:00:00.000000', 0.31, 69)
2018-05-08 18:31:48,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,803 INFO sqlalchemy.engine.base.Engine ('2014-05-08 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:48,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,805 INFO sqlalchemy.engine.base.Engine ('2014-05-09 00:00:00.000000', 0.23, 70)
2018-05-08 18:31:48,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,806 INFO sqlalchemy.engine.base.Engine ('2014-05-12 00:00:00.000000', 2.79, 69)
2018-05-08 18:31:48,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,808 INFO sqlalchemy.engine.base.Engine ('2014-05-13 00:00:00.000000', 0.17, 69)
2018-05-08 18:31:48,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,809 INFO sqlalchemy.engine.base.Engine ('2014-05-14 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:48,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,811 INFO sqlalchemy.engine.base.Engine ('2014-05-15 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:48,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,813 INFO sqlalchemy.engine.base.Engine ('2014-05-16 00:00:00.000000', 0.18, 71)
2018-05-08 18:31:48,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,814 INFO sqlalchemy.engine.base.Engine ('2014-05-17 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:48,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,815 INFO sqlalchemy.engine.base.Engine ('2014-05-18 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:48,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,817 INFO sqlalchemy.engine.base.Engine ('2014-05-19 00:00:00.000000', 0.15, 68)

2018-05-08 18:31:48,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,818 INFO sqlalchemy.engine.base.Engine ('2014-05-20 00:00:00.000000', 0.24, 70)
2018-05-08 18:31:48,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,820 INFO sqlalchemy.engine.base.Engine ('2014-05-21 00:00:00.000000', 0.04, 73)
2018-05-08 18:31:48,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,822 INFO sqlalchemy.engine.base.Engine ('2014-05-22 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:48,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,823 INFO sqlalchemy.engine.base.Engine ('2014-05-23 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:48,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,825 INFO sqlalchemy.engine.base.Engine ('2014-05-24 00:00:00.000000', 0.05, 73)
2018-05-08 18:31:48,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,826 INFO sqlalchemy.engine.base.Engine ('2014-05-25 00:00:00.000000', 0.51, 77)
2018-05-08 18:31:48,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,828 INFO sqlalchemy.engine.base.Engine ('2014-05-26 00:00:00.000000', 2.2, 70)
2018-05-08 18:31:48,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,829 INFO sqlalchemy.engine.base.Engine ('2014-05-27 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:48,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,831 INFO sqlalchemy.engine.base.Engine ('2014-05-28 00:00:00.000000', 0.41, 71)
2018-05-08 18:31:48,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,832 INFO sqlalchemy.engine.base.Engine ('2014-05-29 00:00:00.000000', 0.19, 70)
2018-05-08 18:31:48,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,834 INFO sqlalchemy.engine.base.Engine ('2014-05-30 00:00:00.000000', 0.41, 73)
2018-05-08 18:31:48,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,835 INFO sqlalchemy.engine.base.Engine ('2014-06-01 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:48,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,837 INFO sqlalchemy.engine.base.Engine ('2014-06-02 00:00:00.000000', 0.68, 75)
2018-05-08 18:31:48,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,839 INFO sqlalchemy.engine.base.Engine ('2014-06-03 00:00:00.000000', 0.19, 73)
2018-05-08 18:31:48,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,840 INFO sqlalchemy.engine.base.Engine ('2014-06-04 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:48,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,842 INFO sqlalchemy.engine.base.Engine ('2014-06-05 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:48,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,843 INFO sqlalchemy.engine.base.Engine ('2014-06-06 00:00:00.000000', 0.88, 71)
2018-05-08 18:31:48,844 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,845 INFO sqlalchemy.engine.base.Engine ('2014-06-07 00:00:00.000000', 0.15, 77)
2018-05-08 18:31:48,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,846 INFO sqlalchemy.engine.base.Engine ('2014-06-08 00:00:00.000000', 0.29, 73)
2018-05-08 18:31:48,847 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,848 INFO sqlalchemy.engine.base.Engine ('2014-06-09 00:00:00.000000', 1.0, 70)
2018-05-08 18:31:48,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,849 INFO sqlalchemy.engine.base.Engine ('2014-06-10 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:48,850 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,851 INFO sqlalchemy.engine.base.Engine ('2014-06-11 00:00:00.000000', 0.57, 76)
2018-05-08 18:31:48,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,852 INFO sqlalchemy.engine.base.Engine ('2014-06-12 00:00:00.000000', 0.02, 72)
2018-05-08 18:31:48,853 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,854 INFO sqlalchemy.engine.base.Engine ('2014-06-13 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:48,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,856 INFO sqlalchemy.engine.base.Engine ('2014-06-14 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:48,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,857 INFO sqlalchemy.engine.base.Engine ('2014-06-15 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:48,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,859 INFO sqlalchemy.engine.base.Engine ('2014-06-16 00:00:00.000000', 0.38, 70)
2018-05-08 18:31:48,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,861 INFO sqlalchemy.engine.base.Engine ('2014-06-17 00:00:00.000000', 1.45, 68)
2018-05-08 18:31:48,862 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,863 INFO sqlalchemy.engine.base.Engine ('2014-06-18 00:00:00.000000', 0.32, 69)
2018-05-08 18:31:48,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,865 INFO sqlalchemy.engine.base.Engine ('2014-06-19 00:00:00.000000', 0.2, 70)
2018-05-08 18:31:48,865 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,866 INFO sqlalchemy.engine.base.Engine ('2014-06-20 00:00:00.000000', 0.75, 70)
2018-05-08 18:31:48,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,868 INFO sqlalchemy.engine.base.Engine ('2014-06-21 00:00:00.000000', 0.09, 73)
2018-05-08 18:31:48,869 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,869 INFO sqlalchemy.engine.base.Engine ('2014-06-22 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:48,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,871 INFO sqlalchemy.engine.base.Engine ('2014-06-23 00:00:00.000000', 0.74, 69)
2018-05-08 18:31:48,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,872 INFO sqlalchemy.engine.base.Engine ('2014-06-24 00:00:00.000000', 0.07, 71)

2018-05-08 18:31:48,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,874 INFO sqlalchemy.engine.base.Engine ('2014-06-25 00:00:00.000000', 0.97, 70)
2018-05-08 18:31:48,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,876 INFO sqlalchemy.engine.base.Engine ('2014-06-26 00:00:00.000000', 0.42, 70)
2018-05-08 18:31:48,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,877 INFO sqlalchemy.engine.base.Engine ('2014-06-27 00:00:00.000000', 0.9, 72)
2018-05-08 18:31:48,878 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,879 INFO sqlalchemy.engine.base.Engine ('2014-06-28 00:00:00.000000', 1.29, 71)
2018-05-08 18:31:48,880 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,880 INFO sqlalchemy.engine.base.Engine ('2014-06-29 00:00:00.000000', 1.29, 70)
2018-05-08 18:31:48,881 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,882 INFO sqlalchemy.engine.base.Engine ('2014-07-02 00:00:00.000000', 0.42, 71)
2018-05-08 18:31:48,883 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,884 INFO sqlalchemy.engine.base.Engine ('2014-07-03 00:00:00.000000', 1.1, 71)
2018-05-08 18:31:48,885 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,885 INFO sqlalchemy.engine.base.Engine ('2014-07-04 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:48,886 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,887 INFO sqlalchemy.engine.base.Engine ('2014-07-05 00:00:00.000000', 0.12, 71)
2018-05-08 18:31:48,888 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,889 INFO sqlalchemy.engine.base.Engine ('2014-07-06 00:00:00.000000', 1.34, 71)
2018-05-08 18:31:48,889 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,890 INFO sqlalchemy.engine.base.Engine ('2014-07-07 00:00:00.000000', 0.57, 69)
2018-05-08 18:31:48,891 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,891 INFO sqlalchemy.engine.base.Engine ('2014-07-08 00:00:00.000000', 0.42, 73)
2018-05-08 18:31:48,893 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,893 INFO sqlalchemy.engine.base.Engine ('2014-07-09 00:00:00.000000', 0.55, 70)
2018-05-08 18:31:48,894 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,895 INFO sqlalchemy.engine.base.Engine ('2014-07-10 00:00:00.000000', 0.33, 74)
2018-05-08 18:31:48,896 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,897 INFO sqlalchemy.engine.base.Engine ('2014-07-11 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:48,898 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,898 INFO sqlalchemy.engine.base.Engine ('2014-07-12 00:00:00.000000', 0.16, 73)
2018-05-08 18:31:48,899 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,900 INFO sqlalchemy.engine.base.Engine ('2014-07-13 00:00:00.000000', 1.23, 72)
2018-05-08 18:31:48,901 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,901 INFO sqlalchemy.engine.base.Engine ('2014-07-14 00:00:00.000000', 1.01, 73)
2018-05-08 18:31:48,902 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,903 INFO sqlalchemy.engine.base.Engine ('2014-07-15 00:00:00.000000', 1.18, 75)
2018-05-08 18:31:48,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,905 INFO sqlalchemy.engine.base.Engine ('2014-07-18 00:00:00.000000', 1.04, 73)
2018-05-08 18:31:48,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,906 INFO sqlalchemy.engine.base.Engine ('2014-07-19 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:48,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,908 INFO sqlalchemy.engine.base.Engine ('2014-07-20 00:00:00.000000', 4.3, 72)
2018-05-08 18:31:48,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,910 INFO sqlalchemy.engine.base.Engine ('2014-07-21 00:00:00.000000', 0.72, 73)
2018-05-08 18:31:48,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,912 INFO sqlalchemy.engine.base.Engine ('2014-07-22 00:00:00.000000', 0.14, 75)
2018-05-08 18:31:48,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,913 INFO sqlalchemy.engine.base.Engine ('2014-07-23 00:00:00.000000', 0.93, 75)
2018-05-08 18:31:48,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,915 INFO sqlalchemy.engine.base.Engine ('2014-07-24 00:00:00.000000', 0.13, 73)
2018-05-08 18:31:48,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,917 INFO sqlalchemy.engine.base.Engine ('2014-07-25 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:48,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,918 INFO sqlalchemy.engine.base.Engine ('2014-07-26 00:00:00.000000', 0.26, 74)
2018-05-08 18:31:48,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,920 INFO sqlalchemy.engine.base.Engine ('2014-07-27 00:00:00.000000', 1.43, 75)
2018-05-08 18:31:48,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,922 INFO sqlalchemy.engine.base.Engine ('2014-07-28 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:48,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,923 INFO sqlalchemy.engine.base.Engine ('2014-07-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:48,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,925 INFO sqlalchemy.engine.base.Engine ('2014-07-30 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:48,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,927 INFO sqlalchemy.engine.base.Engine ('2014-07-31 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:48,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,928 INFO sqlalchemy.engine.base.Engine ('2014-08-01 00:00:00.000000', 0.06, 73)
2018-05-08 18:31:48,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,930 INFO sqlalchemy.engine.base.Engine ('2014-08-02 00:00:00.000000', 0.95, 73)

2018-05-08 18:31:48,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,932 INFO sqlalchemy.engine.base.Engine ('2014-08-03 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:48,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,933 INFO sqlalchemy.engine.base.Engine ('2014-08-06 00:00:00.000000', 0.26, 71)
2018-05-08 18:31:48,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,976 INFO sqlalchemy.engine.base.Engine ('2014-08-07 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:48,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,978 INFO sqlalchemy.engine.base.Engine ('2014-08-08 00:00:00.000000', 1.1, 73)
2018-05-08 18:31:48,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,979 INFO sqlalchemy.engine.base.Engine ('2014-08-09 00:00:00.000000', 1.2, 73)
2018-05-08 18:31:48,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,981 INFO sqlalchemy.engine.base.Engine ('2014-08-10 00:00:00.000000', 0.41, 74)
2018-05-08 18:31:48,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,982 INFO sqlalchemy.engine.base.Engine ('2014-08-13 00:00:00.000000', 0.11, 74)
2018-05-08 18:31:48,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,984 INFO sqlalchemy.engine.base.Engine ('2014-08-14 00:00:00.000000', 0.07, 76)
2018-05-08 18:31:48,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,986 INFO sqlalchemy.engine.base.Engine ('2014-08-15 00:00:00.000000', 0.11, 71)
2018-05-08 18:31:48,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,987 INFO sqlalchemy.engine.base.Engine ('2014-08-16 00:00:00.000000', 0.16, 71)
2018-05-08 18:31:48,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,989 INFO sqlalchemy.engine.base.Engine ('2014-08-17 00:00:00.000000', 0.29, 71)
2018-05-08 18:31:48,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,991 INFO sqlalchemy.engine.base.Engine ('2014-08-20 00:00:00.000000', 0.16, 75)
2018-05-08 18:31:48,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,992 INFO sqlalchemy.engine.base.Engine ('2014-08-21 00:00:00.000000', 0.52, 73)
2018-05-08 18:31:48,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,993 INFO sqlalchemy.engine.base.Engine ('2014-08-22 00:00:00.000000', 0.88, 73)
2018-05-08 18:31:48,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,995 INFO sqlalchemy.engine.base.Engine ('2014-08-23 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:48,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,996 INFO sqlalchemy.engine.base.Engine ('2014-08-24 00:00:00.000000', 0.37, 72)
2018-05-08 18:31:48,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,998 INFO sqlalchemy.engine.base.Engine ('2014-08-25 00:00:00.000000', 0.71, 70)
2018-05-08 18:31:48,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:48,999 INFO sqlalchemy.engine.base.Engine ('2014-08-26 00:00:00.000000', 1.14, 72)
2018-05-08 18:31:49,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,001 INFO sqlalchemy.engine.base.Engine ('2014-08-27 00:00:00.000000', 0.37, 72)
2018-05-08 18:31:49,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,003 INFO sqlalchemy.engine.base.Engine ('2014-09-01 00:00:00.000000', 0.01, 73)
2018-05-08 18:31:49,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,004 INFO sqlalchemy.engine.base.Engine ('2014-09-02 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:49,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,006 INFO sqlalchemy.engine.base.Engine ('2014-09-03 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:49,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,007 INFO sqlalchemy.engine.base.Engine ('2014-09-04 00:00:00.000000', 0.24, 74)
2018-05-08 18:31:49,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,009 INFO sqlalchemy.engine.base.Engine ('2014-09-05 00:00:00.000000', 0.44, 75)
2018-05-08 18:31:49,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,011 INFO sqlalchemy.engine.base.Engine ('2014-09-06 00:00:00.000000', 0.93, 74)
2018-05-08 18:31:49,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,012 INFO sqlalchemy.engine.base.Engine ('2014-09-07 00:00:00.000000', 0.14, 72)
2018-05-08 18:31:49,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,014 INFO sqlalchemy.engine.base.Engine ('2014-09-14 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:49,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,016 INFO sqlalchemy.engine.base.Engine ('2014-09-15 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:49,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,017 INFO sqlalchemy.engine.base.Engine ('2014-09-16 00:00:00.000000', 0.01, 78)
2018-05-08 18:31:49,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,019 INFO sqlalchemy.engine.base.Engine ('2014-09-19 00:00:00.000000', 0.0, 80)
2018-05-08 18:31:49,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,021 INFO sqlalchemy.engine.base.Engine ('2014-09-20 00:00:00.000000', 0.02, 78)
2018-05-08 18:31:49,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,022 INFO sqlalchemy.engine.base.Engine ('2014-09-21 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:49,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,024 INFO sqlalchemy.engine.base.Engine ('2014-09-22 00:00:00.000000', 0.08, 77)
2018-05-08 18:31:49,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,026 INFO sqlalchemy.engine.base.Engine ('2014-09-23 00:00:00.000000', 0.05, 77)
2018-05-08 18:31:49,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,028 INFO sqlalchemy.engine.base.Engine ('2014-09-24 00:00:00.000000', 0.0, 76)

2018-05-08 18:31:49,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,029 INFO sqlalchemy.engine.base.Engine ('2014-09-25 00:00:00.000000', 0.85, 77)
2018-05-08 18:31:49,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,031 INFO sqlalchemy.engine.base.Engine ('2014-09-26 00:00:00.000000', 1.8, 75)
2018-05-08 18:31:49,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,033 INFO sqlalchemy.engine.base.Engine ('2014-09-27 00:00:00.000000', 1.3, 74)
2018-05-08 18:31:49,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,034 INFO sqlalchemy.engine.base.Engine ('2014-09-28 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:49,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,037 INFO sqlalchemy.engine.base.Engine ('2014-09-29 00:00:00.000000', 0.55, 74)
2018-05-08 18:31:49,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,039 INFO sqlalchemy.engine.base.Engine ('2014-09-30 00:00:00.000000', 0.12, 75)
2018-05-08 18:31:49,040 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,040 INFO sqlalchemy.engine.base.Engine ('2014-10-01 00:00:00.000000', 1.19, 74)
2018-05-08 18:31:49,041 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,042 INFO sqlalchemy.engine.base.Engine ('2014-10-02 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:49,043 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,043 INFO sqlalchemy.engine.base.Engine ('2014-10-03 00:00:00.000000', 0.03, 75)
2018-05-08 18:31:49,044 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,045 INFO sqlalchemy.engine.base.Engine ('2014-10-04 00:00:00.000000', 0.69, 74)
2018-05-08 18:31:49,046 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,046 INFO sqlalchemy.engine.base.Engine ('2014-10-05 00:00:00.000000', 0.27, 81)
2018-05-08 18:31:49,047 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,048 INFO sqlalchemy.engine.base.Engine ('2014-10-06 00:00:00.000000', 0.58, 73)
2018-05-08 18:31:49,049 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,049 INFO sqlalchemy.engine.base.Engine ('2014-10-07 00:00:00.000000', 0.06, 80)
2018-05-08 18:31:49,050 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,051 INFO sqlalchemy.engine.base.Engine ('2014-10-10 00:00:00.000000', 0.1, 76)
2018-05-08 18:31:49,053 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,053 INFO sqlalchemy.engine.base.Engine ('2014-10-11 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:49,054 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,055 INFO sqlalchemy.engine.base.Engine ('2014-10-12 00:00:00.000000', 0.04, 74)
2018-05-08 18:31:49,056 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,057 INFO sqlalchemy.engine.base.Engine ('2014-10-13 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:49,058 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,058 INFO sqlalchemy.engine.base.Engine ('2014-10-14 00:00:00.000000', 0.29, 72)
2018-05-08 18:31:49,059 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,060 INFO sqlalchemy.engine.base.Engine ('2014-10-15 00:00:00.000000', 0.3, 73)
2018-05-08 18:31:49,061 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,061 INFO sqlalchemy.engine.base.Engine ('2014-10-16 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:49,062 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,063 INFO sqlalchemy.engine.base.Engine ('2014-10-17 00:00:00.000000', 0.26, 75)
2018-05-08 18:31:49,064 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,064 INFO sqlalchemy.engine.base.Engine ('2014-10-18 00:00:00.000000', 1.88, 78)
2018-05-08 18:31:49,065 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,066 INFO sqlalchemy.engine.base.Engine ('2014-10-19 00:00:00.000000', 2.98, 73)
2018-05-08 18:31:49,067 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,068 INFO sqlalchemy.engine.base.Engine ('2014-10-20 00:00:00.000000', 2.31, 75)
2018-05-08 18:31:49,069 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,070 INFO sqlalchemy.engine.base.Engine ('2014-10-21 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:49,071 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,071 INFO sqlalchemy.engine.base.Engine ('2014-10-22 00:00:00.000000', 0.61, 76)
2018-05-08 18:31:49,072 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,073 INFO sqlalchemy.engine.base.Engine ('2014-10-23 00:00:00.000000', 2.31, 75)
2018-05-08 18:31:49,074 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,075 INFO sqlalchemy.engine.base.Engine ('2014-10-24 00:00:00.000000', 0.68, 72)
2018-05-08 18:31:49,076 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,076 INFO sqlalchemy.engine.base.Engine ('2014-10-25 00:00:00.000000', 0.51, 74)
2018-05-08 18:31:49,077 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,078 INFO sqlalchemy.engine.base.Engine ('2014-10-26 00:00:00.000000', 0.31, 74)
2018-05-08 18:31:49,079 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,079 INFO sqlalchemy.engine.base.Engine ('2014-10-27 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:49,080 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,081 INFO sqlalchemy.engine.base.Engine ('2014-10-28 00:00:00.000000', 0.48, 74)
2018-05-08 18:31:49,082 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,083 INFO sqlalchemy.engine.base.Engine ('2014-10-29 00:00:00.000000', 0.76, 75)
2018-05-08 18:31:49,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,084 INFO sqlalchemy.engine.base.Engine ('2014-10-30 00:00:00.000000', 0.69, 73)
2018-05-08 18:31:49,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,086 INFO sqlalchemy.engine.base.Engine ('2014-10-31 00:00:00.000000', 0.3, 73)

2018-05-08 18:31:49,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,088 INFO sqlalchemy.engine.base.Engine ('2014-11-01 00:00:00.000000', 0.59, 76)
2018-05-08 18:31:49,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,089 INFO sqlalchemy.engine.base.Engine ('2014-11-02 00:00:00.000000', 0.79, 71)
2018-05-08 18:31:49,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,091 INFO sqlalchemy.engine.base.Engine ('2014-11-03 00:00:00.000000', 1.25, 71)
2018-05-08 18:31:49,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,093 INFO sqlalchemy.engine.base.Engine ('2014-11-04 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:49,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,094 INFO sqlalchemy.engine.base.Engine ('2014-11-05 00:00:00.000000', 0.73, 71)
2018-05-08 18:31:49,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,096 INFO sqlalchemy.engine.base.Engine ('2014-11-06 00:00:00.000000', 0.6, 75)
2018-05-08 18:31:49,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,097 INFO sqlalchemy.engine.base.Engine ('2014-11-07 00:00:00.000000', 0.17, 76)
2018-05-08 18:31:49,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,099 INFO sqlalchemy.engine.base.Engine ('2014-11-08 00:00:00.000000', 0.58, 69)
2018-05-08 18:31:49,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,101 INFO sqlalchemy.engine.base.Engine ('2014-11-09 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:49,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,102 INFO sqlalchemy.engine.base.Engine ('2014-11-10 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:49,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,103 INFO sqlalchemy.engine.base.Engine ('2014-11-13 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:49,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,105 INFO sqlalchemy.engine.base.Engine ('2014-11-14 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,107 INFO sqlalchemy.engine.base.Engine ('2014-11-15 00:00:00.000000', 1.11, 71)
2018-05-08 18:31:49,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,108 INFO sqlalchemy.engine.base.Engine ('2014-11-16 00:00:00.000000', 0.21, 74)
2018-05-08 18:31:49,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,110 INFO sqlalchemy.engine.base.Engine ('2014-11-17 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,111 INFO sqlalchemy.engine.base.Engine ('2014-11-20 00:00:00.000000', 0.61, 71)
2018-05-08 18:31:49,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,113 INFO sqlalchemy.engine.base.Engine ('2014-11-21 00:00:00.000000', 0.03, 74)
2018-05-08 18:31:49,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,115 INFO sqlalchemy.engine.base.Engine ('2014-11-22 00:00:00.000000', 0.44, 74)
2018-05-08 18:31:49,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,116 INFO sqlalchemy.engine.base.Engine ('2014-11-23 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:49,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,118 INFO sqlalchemy.engine.base.Engine ('2014-11-26 00:00:00.000000', 0.01, 71)
2018-05-08 18:31:49,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,119 INFO sqlalchemy.engine.base.Engine ('2014-11-27 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,121 INFO sqlalchemy.engine.base.Engine ('2014-11-28 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:49,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,122 INFO sqlalchemy.engine.base.Engine ('2014-11-29 00:00:00.000000', 1.21, 68)
2018-05-08 18:31:49,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,124 INFO sqlalchemy.engine.base.Engine ('2014-11-30 00:00:00.000000', 0.94, 66)
2018-05-08 18:31:49,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,126 INFO sqlalchemy.engine.base.Engine ('2014-12-01 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:49,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,127 INFO sqlalchemy.engine.base.Engine ('2014-12-02 00:00:00.000000', 0.07, 70)
2018-05-08 18:31:49,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,129 INFO sqlalchemy.engine.base.Engine ('2014-12-03 00:00:00.000000', 1.82, 67)
2018-05-08 18:31:49,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,130 INFO sqlalchemy.engine.base.Engine ('2014-12-04 00:00:00.000000', 1.41, 70)
2018-05-08 18:31:49,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,132 INFO sqlalchemy.engine.base.Engine ('2014-12-05 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:49,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,133 INFO sqlalchemy.engine.base.Engine ('2014-12-06 00:00:00.000000', 0.11, 70)
2018-05-08 18:31:49,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,135 INFO sqlalchemy.engine.base.Engine ('2014-12-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:49,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,137 INFO sqlalchemy.engine.base.Engine ('2014-12-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,179 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,180 INFO sqlalchemy.engine.base.Engine ('2014-12-11 00:00:00.000000', 1.09, 71)
2018-05-08 18:31:49,181 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,182 INFO sqlalchemy.engine.base.Engine ('2014-12-12 00:00:00.000000', 0.83, 68)
2018-05-08 18:31:49,183 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,183 INFO sqlalchemy.engine.base.Engine ('2014-12-13 00:00:00.000000', 0.0, 71)

2018-05-08 18:31:49,184 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,185 INFO sqlalchemy.engine.base.Engine ('2014-12-14 00:00:00.000000', 1.75, 67)
2018-05-08 18:31:49,186 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,186 INFO sqlalchemy.engine.base.Engine ('2014-12-15 00:00:00.000000', 0.55, 65)
2018-05-08 18:31:49,187 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,188 INFO sqlalchemy.engine.base.Engine ('2014-12-16 00:00:00.000000', 0.58, 66)
2018-05-08 18:31:49,189 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,189 INFO sqlalchemy.engine.base.Engine ('2014-12-17 00:00:00.000000', 0.8, 70)
2018-05-08 18:31:49,190 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,191 INFO sqlalchemy.engine.base.Engine ('2014-12-18 00:00:00.000000', 0.21, 69)
2018-05-08 18:31:49,192 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,192 INFO sqlalchemy.engine.base.Engine ('2014-12-19 00:00:00.000000', 0.51, 70)
2018-05-08 18:31:49,193 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,194 INFO sqlalchemy.engine.base.Engine ('2014-12-22 00:00:00.000000', 0.59, 67)
2018-05-08 18:31:49,195 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,196 INFO sqlalchemy.engine.base.Engine ('2014-12-23 00:00:00.000000', 4.03, 68)
2018-05-08 18:31:49,197 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,197 INFO sqlalchemy.engine.base.Engine ('2014-12-24 00:00:00.000000', 0.4, 64)
2018-05-08 18:31:49,198 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,199 INFO sqlalchemy.engine.base.Engine ('2014-12-25 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:49,200 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,201 INFO sqlalchemy.engine.base.Engine ('2014-12-26 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:49,202 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,202 INFO sqlalchemy.engine.base.Engine ('2014-12-27 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:49,203 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,204 INFO sqlalchemy.engine.base.Engine ('2014-12-28 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:49,205 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,205 INFO sqlalchemy.engine.base.Engine ('2014-12-29 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:49,206 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,207 INFO sqlalchemy.engine.base.Engine ('2015-01-02 00:00:00.000000', 0.02, 64)
2018-05-08 18:31:49,208 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,209 INFO sqlalchemy.engine.base.Engine ('2015-01-03 00:00:00.000000', 0.85, 63)
2018-05-08 18:31:49,210 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,210 INFO sqlalchemy.engine.base.Engine ('2015-01-04 00:00:00.000000', 0.02, 58)
2018-05-08 18:31:49,211 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,212 INFO sqlalchemy.engine.base.Engine ('2015-01-05 00:00:00.000000', 0.0, 58)
2018-05-08 18:31:49,212 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,213 INFO sqlalchemy.engine.base.Engine ('2015-01-06 00:00:00.000000', 0.06, 66)
2018-05-08 18:31:49,214 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,215 INFO sqlalchemy.engine.base.Engine ('2015-01-07 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:49,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,216 INFO sqlalchemy.engine.base.Engine ('2015-01-08 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:49,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,218 INFO sqlalchemy.engine.base.Engine ('2015-01-09 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:49,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,219 INFO sqlalchemy.engine.base.Engine ('2015-01-12 00:00:00.000000', 0.03, 62)
2018-05-08 18:31:49,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,221 INFO sqlalchemy.engine.base.Engine ('2015-01-13 00:00:00.000000', 0.01, 70)
2018-05-08 18:31:49,222 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,222 INFO sqlalchemy.engine.base.Engine ('2015-01-14 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:49,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,224 INFO sqlalchemy.engine.base.Engine ('2015-01-15 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:49,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,226 INFO sqlalchemy.engine.base.Engine ('2015-01-16 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:49,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,227 INFO sqlalchemy.engine.base.Engine ('2015-01-17 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:49,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,229 INFO sqlalchemy.engine.base.Engine ('2015-01-18 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:49,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,231 INFO sqlalchemy.engine.base.Engine ('2015-01-19 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:49,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,232 INFO sqlalchemy.engine.base.Engine ('2015-01-20 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:49,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,234 INFO sqlalchemy.engine.base.Engine ('2015-01-21 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:49,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,235 INFO sqlalchemy.engine.base.Engine ('2015-01-22 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:49,236 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,237 INFO sqlalchemy.engine.base.Engine ('2015-01-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,238 INFO sqlalchemy.engine.base.Engine ('2015-01-24 00:00:00.000000', 0.22, 66)

2018-05-08 18:31:49,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,240 INFO sqlalchemy.engine.base.Engine ('2015-01-25 00:00:00.000000', 0.33, 64)
2018-05-08 18:31:49,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,241 INFO sqlalchemy.engine.base.Engine ('2015-01-26 00:00:00.000000', 0.29, 67)
2018-05-08 18:31:49,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,243 INFO sqlalchemy.engine.base.Engine ('2015-02-03 00:00:00.000000', 0.03, 72)
2018-05-08 18:31:49,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,245 INFO sqlalchemy.engine.base.Engine ('2015-02-04 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:49,245 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,246 INFO sqlalchemy.engine.base.Engine ('2015-02-05 00:00:00.000000', 0.03, 63)
2018-05-08 18:31:49,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,248 INFO sqlalchemy.engine.base.Engine ('2015-02-06 00:00:00.000000', 0.0, 59)
2018-05-08 18:31:49,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,249 INFO sqlalchemy.engine.base.Engine ('2015-02-07 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:49,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,251 INFO sqlalchemy.engine.base.Engine ('2015-02-08 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:49,252 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,253 INFO sqlalchemy.engine.base.Engine ('2015-02-11 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:49,254 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,255 INFO sqlalchemy.engine.base.Engine ('2015-02-12 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:49,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,256 INFO sqlalchemy.engine.base.Engine ('2015-02-13 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:49,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,258 INFO sqlalchemy.engine.base.Engine ('2015-02-18 00:00:00.000000', 0.01, 64)
2018-05-08 18:31:49,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,259 INFO sqlalchemy.engine.base.Engine ('2015-02-19 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:49,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,261 INFO sqlalchemy.engine.base.Engine ('2015-02-20 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:49,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,263 INFO sqlalchemy.engine.base.Engine ('2015-02-21 00:00:00.000000', 0.26, 68)
2018-05-08 18:31:49,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,264 INFO sqlalchemy.engine.base.Engine ('2015-02-22 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:49,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,266 INFO sqlalchemy.engine.base.Engine ('2015-02-23 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:49,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,267 INFO sqlalchemy.engine.base.Engine ('2015-02-24 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:49,268 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,269 INFO sqlalchemy.engine.base.Engine ('2015-02-25 00:00:00.000000', 0.1, 69)
2018-05-08 18:31:49,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,271 INFO sqlalchemy.engine.base.Engine ('2015-02-26 00:00:00.000000', 0.25, 68)
2018-05-08 18:31:49,272 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,272 INFO sqlalchemy.engine.base.Engine ('2015-02-27 00:00:00.000000', 0.01, 67)
2018-05-08 18:31:49,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,274 INFO sqlalchemy.engine.base.Engine ('2015-02-28 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:49,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,276 INFO sqlalchemy.engine.base.Engine ('2015-03-01 00:00:00.000000', 0.12, 68)
2018-05-08 18:31:49,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,277 INFO sqlalchemy.engine.base.Engine ('2015-03-02 00:00:00.000000', 0.32, 76)
2018-05-08 18:31:49,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,279 INFO sqlalchemy.engine.base.Engine ('2015-03-03 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:49,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,280 INFO sqlalchemy.engine.base.Engine ('2015-03-04 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:49,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,282 INFO sqlalchemy.engine.base.Engine ('2015-03-05 00:00:00.000000', 2.07, 65)
2018-05-08 18:31:49,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,283 INFO sqlalchemy.engine.base.Engine ('2015-03-06 00:00:00.000000', 0.92, 65)
2018-05-08 18:31:49,284 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,285 INFO sqlalchemy.engine.base.Engine ('2015-03-07 00:00:00.000000', 0.02, 66)
2018-05-08 18:31:49,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,286 INFO sqlalchemy.engine.base.Engine ('2015-03-08 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:49,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,288 INFO sqlalchemy.engine.base.Engine ('2015-03-09 00:00:00.000000', 0.01, 61)
2018-05-08 18:31:49,289 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,290 INFO sqlalchemy.engine.base.Engine ('2015-03-10 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:49,291 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,292 INFO sqlalchemy.engine.base.Engine ('2015-03-11 00:00:00.000000', 0.0, 62)
2018-05-08 18:31:49,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,294 INFO sqlalchemy.engine.base.Engine ('2015-03-12 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:49,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,295 INFO sqlalchemy.engine.base.Engine ('2015-03-13 00:00:00.000000', 0.01, 64)

2018-05-08 18:31:49,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,297 INFO sqlalchemy.engine.base.Engine ('2015-03-14 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:49,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,299 INFO sqlalchemy.engine.base.Engine ('2015-03-15 00:00:00.000000', 0.0, 63)
2018-05-08 18:31:49,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,300 INFO sqlalchemy.engine.base.Engine ('2015-03-16 00:00:00.000000', 0.01, 60)
2018-05-08 18:31:49,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,302 INFO sqlalchemy.engine.base.Engine ('2015-03-17 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:49,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,305 INFO sqlalchemy.engine.base.Engine ('2015-03-18 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:49,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,306 INFO sqlalchemy.engine.base.Engine ('2015-03-19 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:49,307 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,308 INFO sqlalchemy.engine.base.Engine ('2015-03-20 00:00:00.000000', 0.3, 67)
2018-05-08 18:31:49,309 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,310 INFO sqlalchemy.engine.base.Engine ('2015-03-23 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:49,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,312 INFO sqlalchemy.engine.base.Engine ('2015-03-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:49,313 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,313 INFO sqlalchemy.engine.base.Engine ('2015-03-25 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:49,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,315 INFO sqlalchemy.engine.base.Engine ('2015-03-26 00:00:00.000000', 0.56, 66)
2018-05-08 18:31:49,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,317 INFO sqlalchemy.engine.base.Engine ('2015-03-27 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:49,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,319 INFO sqlalchemy.engine.base.Engine ('2015-03-28 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:49,320 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,320 INFO sqlalchemy.engine.base.Engine ('2015-03-29 00:00:00.000000', 2.02, 68)
2018-05-08 18:31:49,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,322 INFO sqlalchemy.engine.base.Engine ('2015-03-30 00:00:00.000000', 0.72, 67)
2018-05-08 18:31:49,323 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,324 INFO sqlalchemy.engine.base.Engine ('2015-03-31 00:00:00.000000', 1.5, 68)
2018-05-08 18:31:49,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,325 INFO sqlalchemy.engine.base.Engine ('2015-04-01 00:00:00.000000', 0.48, 69)
2018-05-08 18:31:49,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,327 INFO sqlalchemy.engine.base.Engine ('2015-04-02 00:00:00.000000', 0.47, 68)
2018-05-08 18:31:49,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,329 INFO sqlalchemy.engine.base.Engine ('2015-04-05 00:00:00.000000', 0.32, 70)
2018-05-08 18:31:49,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,331 INFO sqlalchemy.engine.base.Engine ('2015-04-08 00:00:00.000000', 0.23, 70)
2018-05-08 18:31:49,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,332 INFO sqlalchemy.engine.base.Engine ('2015-04-09 00:00:00.000000', 0.08, 69)
2018-05-08 18:31:49,333 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,334 INFO sqlalchemy.engine.base.Engine ('2015-04-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,336 INFO sqlalchemy.engine.base.Engine ('2015-04-11 00:00:00.000000', 0.09, 69)
2018-05-08 18:31:49,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,337 INFO sqlalchemy.engine.base.Engine ('2015-04-12 00:00:00.000000', 0.73, 69)
2018-05-08 18:31:49,338 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,339 INFO sqlalchemy.engine.base.Engine ('2015-04-13 00:00:00.000000', 0.28, 69)
2018-05-08 18:31:49,340 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,341 INFO sqlalchemy.engine.base.Engine ('2015-04-14 00:00:00.000000', 0.74, 69)
2018-05-08 18:31:49,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,342 INFO sqlalchemy.engine.base.Engine ('2015-04-15 00:00:00.000000', 0.62, 68)
2018-05-08 18:31:49,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,387 INFO sqlalchemy.engine.base.Engine ('2015-04-16 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:49,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,388 INFO sqlalchemy.engine.base.Engine ('2015-04-17 00:00:00.000000', 1.2, 70)
2018-05-08 18:31:49,389 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,390 INFO sqlalchemy.engine.base.Engine ('2015-04-18 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:49,391 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,391 INFO sqlalchemy.engine.base.Engine ('2015-04-19 00:00:00.000000', 0.09, 68)
2018-05-08 18:31:49,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,393 INFO sqlalchemy.engine.base.Engine ('2015-04-22 00:00:00.000000', 1.68, 73)
2018-05-08 18:31:49,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,396 INFO sqlalchemy.engine.base.Engine ('2015-04-23 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:49,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,397 INFO sqlalchemy.engine.base.Engine ('2015-04-24 00:00:00.000000', 0.37, 72)
2018-05-08 18:31:49,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,399 INFO sqlalchemy.engine.base.Engine ('2015-04-25 00:00:00.000000', 0.04, 73)

2018-05-08 18:31:49,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,400 INFO sqlalchemy.engine.base.Engine ('2015-04-26 00:00:00.000000', 0.05, 70)
2018-05-08 18:31:49,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,402 INFO sqlalchemy.engine.base.Engine ('2015-04-27 00:00:00.000000', 0.63, 68)
2018-05-08 18:31:49,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,403 INFO sqlalchemy.engine.base.Engine ('2015-04-28 00:00:00.000000', 3.26, 69)
2018-05-08 18:31:49,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,405 INFO sqlalchemy.engine.base.Engine ('2015-04-29 00:00:00.000000', 0.45, 71)
2018-05-08 18:31:49,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,406 INFO sqlalchemy.engine.base.Engine ('2015-04-30 00:00:00.000000', 0.14, 69)
2018-05-08 18:31:49,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,408 INFO sqlalchemy.engine.base.Engine ('2015-05-01 00:00:00.000000', 1.79, 69)
2018-05-08 18:31:49,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,409 INFO sqlalchemy.engine.base.Engine ('2015-05-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:49,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,411 INFO sqlalchemy.engine.base.Engine ('2015-05-03 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:49,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,413 INFO sqlalchemy.engine.base.Engine ('2015-05-04 00:00:00.000000', 0.21, 77)
2018-05-08 18:31:49,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,414 INFO sqlalchemy.engine.base.Engine ('2015-05-05 00:00:00.000000', 1.27, 68)
2018-05-08 18:31:49,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,416 INFO sqlalchemy.engine.base.Engine ('2015-05-06 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:49,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,417 INFO sqlalchemy.engine.base.Engine ('2015-05-07 00:00:00.000000', 0.04, 69)
2018-05-08 18:31:49,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,419 INFO sqlalchemy.engine.base.Engine ('2015-05-08 00:00:00.000000', 1.88, 67)
2018-05-08 18:31:49,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,421 INFO sqlalchemy.engine.base.Engine ('2015-05-09 00:00:00.000000', 0.67, 69)
2018-05-08 18:31:49,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,422 INFO sqlalchemy.engine.base.Engine ('2015-05-10 00:00:00.000000', 0.92, 68)
2018-05-08 18:31:49,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,424 INFO sqlalchemy.engine.base.Engine ('2015-05-11 00:00:00.000000', 0.27, 71)
2018-05-08 18:31:49,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,426 INFO sqlalchemy.engine.base.Engine ('2015-05-12 00:00:00.000000', 0.08, 70)
2018-05-08 18:31:49,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,427 INFO sqlalchemy.engine.base.Engine ('2015-05-13 00:00:00.000000', 0.02, 70)
2018-05-08 18:31:49,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,429 INFO sqlalchemy.engine.base.Engine ('2015-05-14 00:00:00.000000', 0.84, 72)
2018-05-08 18:31:49,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,431 INFO sqlalchemy.engine.base.Engine ('2015-05-15 00:00:00.000000', 0.58, 72)
2018-05-08 18:31:49,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,433 INFO sqlalchemy.engine.base.Engine ('2015-05-16 00:00:00.000000', 0.12, 72)
2018-05-08 18:31:49,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,434 INFO sqlalchemy.engine.base.Engine ('2015-05-17 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:49,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,436 INFO sqlalchemy.engine.base.Engine ('2015-05-18 00:00:00.000000', 0.22, 70)
2018-05-08 18:31:49,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,437 INFO sqlalchemy.engine.base.Engine ('2015-05-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:49,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,439 INFO sqlalchemy.engine.base.Engine ('2015-05-20 00:00:00.000000', 0.41, 69)
2018-05-08 18:31:49,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,440 INFO sqlalchemy.engine.base.Engine ('2015-05-21 00:00:00.000000', 0.3, 76)
2018-05-08 18:31:49,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,442 INFO sqlalchemy.engine.base.Engine ('2015-05-22 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:49,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,443 INFO sqlalchemy.engine.base.Engine ('2015-05-23 00:00:00.000000', 0.19, 69)
2018-05-08 18:31:49,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,445 INFO sqlalchemy.engine.base.Engine ('2015-05-24 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:49,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,447 INFO sqlalchemy.engine.base.Engine ('2015-05-25 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:49,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,448 INFO sqlalchemy.engine.base.Engine ('2015-05-26 00:00:00.000000', 0.04, 68)
2018-05-08 18:31:49,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,450 INFO sqlalchemy.engine.base.Engine ('2015-05-27 00:00:00.000000', 0.03, 73)
2018-05-08 18:31:49,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,451 INFO sqlalchemy.engine.base.Engine ('2015-05-28 00:00:00.000000', 0.03, 71)
2018-05-08 18:31:49,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,453 INFO sqlalchemy.engine.base.Engine ('2015-05-29 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:49,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,455 INFO sqlalchemy.engine.base.Engine ('2015-05-30 00:00:00.000000', 0.01, 72)

2018-05-08 18:31:49,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,457 INFO sqlalchemy.engine.base.Engine ('2015-05-31 00:00:00.000000', 1.12, 69)
2018-05-08 18:31:49,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,458 INFO sqlalchemy.engine.base.Engine ('2015-06-01 00:00:00.000000', 2.47, 69)
2018-05-08 18:31:49,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,460 INFO sqlalchemy.engine.base.Engine ('2015-06-02 00:00:00.000000', 0.27, 72)
2018-05-08 18:31:49,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,461 INFO sqlalchemy.engine.base.Engine ('2015-06-03 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:49,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,463 INFO sqlalchemy.engine.base.Engine ('2015-06-04 00:00:00.000000', 1.12, 71)
2018-05-08 18:31:49,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,464 INFO sqlalchemy.engine.base.Engine ('2015-06-05 00:00:00.000000', 0.16, 76)
2018-05-08 18:31:49,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,466 INFO sqlalchemy.engine.base.Engine ('2015-06-06 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:49,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,467 INFO sqlalchemy.engine.base.Engine ('2015-06-07 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:49,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,469 INFO sqlalchemy.engine.base.Engine ('2015-06-08 00:00:00.000000', 0.34, 70)
2018-05-08 18:31:49,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,471 INFO sqlalchemy.engine.base.Engine ('2015-06-09 00:00:00.000000', 0.26, 72)
2018-05-08 18:31:49,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,472 INFO sqlalchemy.engine.base.Engine ('2015-06-10 00:00:00.000000', 0.04, 72)
2018-05-08 18:31:49,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,474 INFO sqlalchemy.engine.base.Engine ('2015-06-13 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,476 INFO sqlalchemy.engine.base.Engine ('2015-06-14 00:00:00.000000', 0.47, 69)
2018-05-08 18:31:49,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,477 INFO sqlalchemy.engine.base.Engine ('2015-06-15 00:00:00.000000', 0.67, 70)
2018-05-08 18:31:49,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,479 INFO sqlalchemy.engine.base.Engine ('2015-06-16 00:00:00.000000', 0.94, 73)
2018-05-08 18:31:49,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,481 INFO sqlalchemy.engine.base.Engine ('2015-06-17 00:00:00.000000', 0.48, 70)
2018-05-08 18:31:49,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,482 INFO sqlalchemy.engine.base.Engine ('2015-06-18 00:00:00.000000', 0.54, 72)
2018-05-08 18:31:49,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,484 INFO sqlalchemy.engine.base.Engine ('2015-06-19 00:00:00.000000', 0.69, 72)
2018-05-08 18:31:49,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,485 INFO sqlalchemy.engine.base.Engine ('2015-06-20 00:00:00.000000', 0.13, 71)
2018-05-08 18:31:49,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,487 INFO sqlalchemy.engine.base.Engine ('2015-06-21 00:00:00.000000', 0.1, 73)
2018-05-08 18:31:49,488 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,489 INFO sqlalchemy.engine.base.Engine ('2015-06-22 00:00:00.000000', 0.19, 72)
2018-05-08 18:31:49,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,490 INFO sqlalchemy.engine.base.Engine ('2015-06-23 00:00:00.000000', 0.31, 73)
2018-05-08 18:31:49,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,492 INFO sqlalchemy.engine.base.Engine ('2015-06-24 00:00:00.000000', 0.78, 72)
2018-05-08 18:31:49,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,493 INFO sqlalchemy.engine.base.Engine ('2015-06-25 00:00:00.000000', 1.36, 71)
2018-05-08 18:31:49,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,495 INFO sqlalchemy.engine.base.Engine ('2015-06-26 00:00:00.000000', 0.4, 70)
2018-05-08 18:31:49,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,497 INFO sqlalchemy.engine.base.Engine ('2015-06-27 00:00:00.000000', 0.17, 75)
2018-05-08 18:31:49,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,498 INFO sqlalchemy.engine.base.Engine ('2015-06-28 00:00:00.000000', 0.16, 72)
2018-05-08 18:31:49,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,500 INFO sqlalchemy.engine.base.Engine ('2015-06-29 00:00:00.000000', 1.62, 70)
2018-05-08 18:31:49,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,501 INFO sqlalchemy.engine.base.Engine ('2015-06-30 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:49,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,503 INFO sqlalchemy.engine.base.Engine ('2015-07-01 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:49,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,504 INFO sqlalchemy.engine.base.Engine ('2015-07-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:49,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,506 INFO sqlalchemy.engine.base.Engine ('2015-07-03 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:49,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,508 INFO sqlalchemy.engine.base.Engine ('2015-07-04 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:49,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,509 INFO sqlalchemy.engine.base.Engine ('2015-07-05 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:49,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,511 INFO sqlalchemy.engine.base.Engine ('2015-07-06 00:00:00.000000', 0.04, 74)

2018-05-08 18:31:49,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,512 INFO sqlalchemy.engine.base.Engine ('2015-07-07 00:00:00.000000', 0.13, 74)
2018-05-08 18:31:49,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,514 INFO sqlalchemy.engine.base.Engine ('2015-07-08 00:00:00.000000', 1.26, 73)
2018-05-08 18:31:49,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,516 INFO sqlalchemy.engine.base.Engine ('2015-07-09 00:00:00.000000', 0.13, 75)
2018-05-08 18:31:49,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,517 INFO sqlalchemy.engine.base.Engine ('2015-07-10 00:00:00.000000', 2.23, 73)
2018-05-08 18:31:49,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,519 INFO sqlalchemy.engine.base.Engine ('2015-07-11 00:00:00.000000', 1.57, 76)
2018-05-08 18:31:49,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,520 INFO sqlalchemy.engine.base.Engine ('2015-07-12 00:00:00.000000', 0.49, 78)
2018-05-08 18:31:49,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,522 INFO sqlalchemy.engine.base.Engine ('2015-07-13 00:00:00.000000', 2.59, 74)
2018-05-08 18:31:49,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,524 INFO sqlalchemy.engine.base.Engine ('2015-07-14 00:00:00.000000', 0.4, 72)
2018-05-08 18:31:49,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,525 INFO sqlalchemy.engine.base.Engine ('2015-07-15 00:00:00.000000', 0.68, 74)
2018-05-08 18:31:49,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,527 INFO sqlalchemy.engine.base.Engine ('2015-07-16 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:49,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,528 INFO sqlalchemy.engine.base.Engine ('2015-07-17 00:00:00.000000', 0.47, 76)
2018-05-08 18:31:49,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,530 INFO sqlalchemy.engine.base.Engine ('2015-07-18 00:00:00.000000', 0.44, 75)
2018-05-08 18:31:49,531 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,531 INFO sqlalchemy.engine.base.Engine ('2015-07-19 00:00:00.000000', 0.74, 72)
2018-05-08 18:31:49,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,533 INFO sqlalchemy.engine.base.Engine ('2015-07-22 00:00:00.000000', 2.44, 72)
2018-05-08 18:31:49,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,534 INFO sqlalchemy.engine.base.Engine ('2015-07-23 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:49,535 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,536 INFO sqlalchemy.engine.base.Engine ('2015-07-24 00:00:00.000000', 0.25, 75)
2018-05-08 18:31:49,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,538 INFO sqlalchemy.engine.base.Engine ('2015-07-25 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:49,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,539 INFO sqlalchemy.engine.base.Engine ('2015-07-26 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:49,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,541 INFO sqlalchemy.engine.base.Engine ('2015-07-27 00:00:00.000000', 0.09, 74)
2018-05-08 18:31:49,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,542 INFO sqlalchemy.engine.base.Engine ('2015-07-28 00:00:00.000000', 0.42, 76)
2018-05-08 18:31:49,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,544 INFO sqlalchemy.engine.base.Engine ('2015-07-29 00:00:00.000000', 0.12, 77)
2018-05-08 18:31:49,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,545 INFO sqlalchemy.engine.base.Engine ('2015-07-30 00:00:00.000000', 0.06, 75)
2018-05-08 18:31:49,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,591 INFO sqlalchemy.engine.base.Engine ('2015-07-31 00:00:00.000000', 0.11, 75)
2018-05-08 18:31:49,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,593 INFO sqlalchemy.engine.base.Engine ('2015-08-01 00:00:00.000000', 0.54, 73)
2018-05-08 18:31:49,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,595 INFO sqlalchemy.engine.base.Engine ('2015-08-02 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:49,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,596 INFO sqlalchemy.engine.base.Engine ('2015-08-03 00:00:00.000000', 0.03, 76)
2018-05-08 18:31:49,597 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,597 INFO sqlalchemy.engine.base.Engine ('2015-08-04 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:49,599 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,599 INFO sqlalchemy.engine.base.Engine ('2015-08-05 00:00:00.000000', 0.59, 74)
2018-05-08 18:31:49,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,601 INFO sqlalchemy.engine.base.Engine ('2015-08-06 00:00:00.000000', 0.5, 76)
2018-05-08 18:31:49,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,602 INFO sqlalchemy.engine.base.Engine ('2015-08-07 00:00:00.000000', 0.09, 75)
2018-05-08 18:31:49,603 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,604 INFO sqlalchemy.engine.base.Engine ('2015-08-08 00:00:00.000000', 0.01, 77)
2018-05-08 18:31:49,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,605 INFO sqlalchemy.engine.base.Engine ('2015-08-09 00:00:00.000000', 0.54, 73)
2018-05-08 18:31:49,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,607 INFO sqlalchemy.engine.base.Engine ('2015-08-10 00:00:00.000000', 0.41, 75)
2018-05-08 18:31:49,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,608 INFO sqlalchemy.engine.base.Engine ('2015-08-11 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:49,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,610 INFO sqlalchemy.engine.base.Engine ('2015-08-12 00:00:00.000000', 0.39, 77)

2018-05-08 18:31:49,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,611 INFO sqlalchemy.engine.base.Engine ('2015-08-13 00:00:00.000000', 0.44, 75)
2018-05-08 18:31:49,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,612 INFO sqlalchemy.engine.base.Engine ('2015-08-14 00:00:00.000000', 0.92, 74)
2018-05-08 18:31:49,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,614 INFO sqlalchemy.engine.base.Engine ('2015-08-15 00:00:00.000000', 1.28, 73)
2018-05-08 18:31:49,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,615 INFO sqlalchemy.engine.base.Engine ('2015-08-16 00:00:00.000000', 0.29, 75)
2018-05-08 18:31:49,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,617 INFO sqlalchemy.engine.base.Engine ('2015-08-17 00:00:00.000000', 0.08, 75)
2018-05-08 18:31:49,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,618 INFO sqlalchemy.engine.base.Engine ('2015-08-18 00:00:00.000000', 1.59, 76)
2018-05-08 18:31:49,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,620 INFO sqlalchemy.engine.base.Engine ('2015-08-19 00:00:00.000000', 0.08, 76)
2018-05-08 18:31:49,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,622 INFO sqlalchemy.engine.base.Engine ('2015-08-20 00:00:00.000000', 0.11, 77)
2018-05-08 18:31:49,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,623 INFO sqlalchemy.engine.base.Engine ('2015-08-21 00:00:00.000000', 0.17, 75)
2018-05-08 18:31:49,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,625 INFO sqlalchemy.engine.base.Engine ('2015-08-22 00:00:00.000000', 0.11, 79)
2018-05-08 18:31:49,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,626 INFO sqlalchemy.engine.base.Engine ('2015-08-23 00:00:00.000000', 0.43, 75)
2018-05-08 18:31:49,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,627 INFO sqlalchemy.engine.base.Engine ('2015-08-24 00:00:00.000000', 4.81, 72)
2018-05-08 18:31:49,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,629 INFO sqlalchemy.engine.base.Engine ('2015-08-25 00:00:00.000000', 0.1, 77)
2018-05-08 18:31:49,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,630 INFO sqlalchemy.engine.base.Engine ('2015-08-26 00:00:00.000000', 0.79, 76)
2018-05-08 18:31:49,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,632 INFO sqlalchemy.engine.base.Engine ('2015-08-27 00:00:00.000000', 2.67, 77)
2018-05-08 18:31:49,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,633 INFO sqlalchemy.engine.base.Engine ('2015-08-28 00:00:00.000000', 0.19, 76)
2018-05-08 18:31:49,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,634 INFO sqlalchemy.engine.base.Engine ('2015-08-29 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:49,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,636 INFO sqlalchemy.engine.base.Engine ('2015-08-30 00:00:00.000000', 0.04, 77)
2018-05-08 18:31:49,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,637 INFO sqlalchemy.engine.base.Engine ('2015-08-31 00:00:00.000000', 0.26, 78)
2018-05-08 18:31:49,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,638 INFO sqlalchemy.engine.base.Engine ('2015-09-01 00:00:00.000000', 0.07, 77)
2018-05-08 18:31:49,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,640 INFO sqlalchemy.engine.base.Engine ('2015-09-02 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:49,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,641 INFO sqlalchemy.engine.base.Engine ('2015-09-03 00:00:00.000000', 0.16, 74)
2018-05-08 18:31:49,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,642 INFO sqlalchemy.engine.base.Engine ('2015-09-04 00:00:00.000000', 1.04, 75)
2018-05-08 18:31:49,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,644 INFO sqlalchemy.engine.base.Engine ('2015-09-05 00:00:00.000000', 0.06, 79)
2018-05-08 18:31:49,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,645 INFO sqlalchemy.engine.base.Engine ('2015-09-06 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:49,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,647 INFO sqlalchemy.engine.base.Engine ('2015-09-07 00:00:00.000000', 0.32, 76)
2018-05-08 18:31:49,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,649 INFO sqlalchemy.engine.base.Engine ('2015-09-08 00:00:00.000000', 0.29, 79)
2018-05-08 18:31:49,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,650 INFO sqlalchemy.engine.base.Engine ('2015-09-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:49,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,652 INFO sqlalchemy.engine.base.Engine ('2015-09-10 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:49,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,653 INFO sqlalchemy.engine.base.Engine ('2015-09-11 00:00:00.000000', 0.52, 75)
2018-05-08 18:31:49,654 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:49,655 INFO sqlalchemy.engine.base.Engine ('2015-09-12 00:00:00.000000', 2.44, 76)
2018-05-08 18:31:50,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,441 INFO sqlalchemy.engine.base.Engine ('2016-12-15 00:00:00.000000', 0.03, 64)
2018-05-08 18:31:50,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,442 INFO sqlalchemy.engine.base.Engine ('2016-12-16 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:50,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,444 INFO sqlalchemy.engine.base.Engine ('2016-12-19 00:00:00.000000', 0.15, 72)
2018-05-08 18:31:50,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,446 INFO sqlalchemy.engine.base.Engine ('2016-12-20 00:00:00.000000', 0.0, 73)

2018-05-08 18:31:50,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,447 INFO sqlalchemy.engine.base.Engine ('2016-12-21 00:00:00.000000', 0.55, 70)
2018-05-08 18:31:50,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,449 INFO sqlalchemy.engine.base.Engine ('2016-12-22 00:00:00.000000', 1.24, 68)
2018-05-08 18:31:50,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,450 INFO sqlalchemy.engine.base.Engine ('2016-12-23 00:00:00.000000', 0.83, 69)
2018-05-08 18:31:50,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,452 INFO sqlalchemy.engine.base.Engine ('2016-12-24 00:00:00.000000', 1.08, 69)
2018-05-08 18:31:50,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,453 INFO sqlalchemy.engine.base.Engine ('2016-12-25 00:00:00.000000', 0.38, 69)
2018-05-08 18:31:50,454 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,455 INFO sqlalchemy.engine.base.Engine ('2016-12-26 00:00:00.000000', 1.48, 71)
2018-05-08 18:31:50,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,456 INFO sqlalchemy.engine.base.Engine ('2016-12-27 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:50,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,458 INFO sqlalchemy.engine.base.Engine ('2016-12-28 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:50,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,459 INFO sqlalchemy.engine.base.Engine ('2016-12-29 00:00:00.000000', 1.03, 69)
2018-05-08 18:31:50,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,461 INFO sqlalchemy.engine.base.Engine ('2016-12-30 00:00:00.000000', 2.37, 65)
2018-05-08 18:31:50,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,462 INFO sqlalchemy.engine.base.Engine ('2016-12-31 00:00:00.000000', 0.9, 65)
2018-05-08 18:31:50,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,464 INFO sqlalchemy.engine.base.Engine ('2017-01-01 00:00:00.000000', 0.03, 68)
2018-05-08 18:31:50,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,466 INFO sqlalchemy.engine.base.Engine ('2017-01-02 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:50,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,467 INFO sqlalchemy.engine.base.Engine ('2017-01-03 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:50,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,469 INFO sqlalchemy.engine.base.Engine ('2017-01-04 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:50,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,470 INFO sqlalchemy.engine.base.Engine ('2017-01-05 00:00:00.000000', 0.47, 71)
2018-05-08 18:31:50,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,472 INFO sqlalchemy.engine.base.Engine ('2017-01-06 00:00:00.000000', 0.1, 65)
2018-05-08 18:31:50,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,473 INFO sqlalchemy.engine.base.Engine ('2017-01-07 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:50,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,476 INFO sqlalchemy.engine.base.Engine ('2017-01-08 00:00:00.000000', 0.03, 66)
2018-05-08 18:31:50,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,477 INFO sqlalchemy.engine.base.Engine ('2017-01-09 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,479 INFO sqlalchemy.engine.base.Engine ('2017-01-10 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:50,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,481 INFO sqlalchemy.engine.base.Engine ('2017-01-11 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:50,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,483 INFO sqlalchemy.engine.base.Engine ('2017-01-12 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,484 INFO sqlalchemy.engine.base.Engine ('2017-01-13 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:50,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,486 INFO sqlalchemy.engine.base.Engine ('2017-01-14 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:50,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,488 INFO sqlalchemy.engine.base.Engine ('2017-01-15 00:00:00.000000', 0.01, 68)
2018-05-08 18:31:50,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,490 INFO sqlalchemy.engine.base.Engine ('2017-01-16 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,491 INFO sqlalchemy.engine.base.Engine ('2017-01-17 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,493 INFO sqlalchemy.engine.base.Engine ('2017-01-18 00:00:00.000000', 0.07, 73)
2018-05-08 18:31:50,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,494 INFO sqlalchemy.engine.base.Engine ('2017-01-19 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:50,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,496 INFO sqlalchemy.engine.base.Engine ('2017-01-20 00:00:00.000000', 0.0, 67)
2018-05-08 18:31:50,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,497 INFO sqlalchemy.engine.base.Engine ('2017-01-21 00:00:00.000000', 0.08, 67)
2018-05-08 18:31:50,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,499 INFO sqlalchemy.engine.base.Engine ('2017-01-22 00:00:00.000000', 0.72, 68)
2018-05-08 18:31:50,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,501 INFO sqlalchemy.engine.base.Engine ('2017-01-23 00:00:00.000000', 0.85, 70)
2018-05-08 18:31:50,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,502 INFO sqlalchemy.engine.base.Engine ('2017-01-24 00:00:00.000000', 1.85, 67)

2018-05-08 18:31:50,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,504 INFO sqlalchemy.engine.base.Engine ('2017-01-25 00:00:00.000000', 2.64, 69)
2018-05-08 18:31:50,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,505 INFO sqlalchemy.engine.base.Engine ('2017-01-26 00:00:00.000000', 0.1, 67)
2018-05-08 18:31:50,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,506 INFO sqlalchemy.engine.base.Engine ('2017-01-27 00:00:00.000000', 0.03, 69)
2018-05-08 18:31:50,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,508 INFO sqlalchemy.engine.base.Engine ('2017-01-28 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:50,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,510 INFO sqlalchemy.engine.base.Engine ('2017-01-29 00:00:00.000000', 0.55, 67)
2018-05-08 18:31:50,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,511 INFO sqlalchemy.engine.base.Engine ('2017-01-30 00:00:00.000000', 0.0, 66)
2018-05-08 18:31:50,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,513 INFO sqlalchemy.engine.base.Engine ('2017-01-31 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:50,514 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,514 INFO sqlalchemy.engine.base.Engine ('2017-02-01 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:50,515 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,516 INFO sqlalchemy.engine.base.Engine ('2017-02-02 00:00:00.000000', 0.0, 60)
2018-05-08 18:31:50,517 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,517 INFO sqlalchemy.engine.base.Engine ('2017-02-05 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,518 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,519 INFO sqlalchemy.engine.base.Engine ('2017-02-06 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:50,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,520 INFO sqlalchemy.engine.base.Engine ('2017-02-07 00:00:00.000000', 1.79, 68)
2018-05-08 18:31:50,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,522 INFO sqlalchemy.engine.base.Engine ('2017-02-08 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,523 INFO sqlalchemy.engine.base.Engine ('2017-02-09 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:50,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,525 INFO sqlalchemy.engine.base.Engine ('2017-02-10 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:50,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,527 INFO sqlalchemy.engine.base.Engine ('2017-02-11 00:00:00.000000', 0.73, 66)
2018-05-08 18:31:50,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,528 INFO sqlalchemy.engine.base.Engine ('2017-02-12 00:00:00.000000', 1.83, 65)
2018-05-08 18:31:50,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,529 INFO sqlalchemy.engine.base.Engine ('2017-02-13 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,577 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,578 INFO sqlalchemy.engine.base.Engine ('2017-02-14 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:50,579 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,579 INFO sqlalchemy.engine.base.Engine ('2017-02-15 00:00:00.000000', 0.07, 71)
2018-05-08 18:31:50,580 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,581 INFO sqlalchemy.engine.base.Engine ('2017-02-16 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:50,582 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,582 INFO sqlalchemy.engine.base.Engine ('2017-02-19 00:00:00.000000', 0.1, 68)
2018-05-08 18:31:50,583 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,584 INFO sqlalchemy.engine.base.Engine ('2017-02-20 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,585 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,585 INFO sqlalchemy.engine.base.Engine ('2017-02-21 00:00:00.000000', 0.07, 65)
2018-05-08 18:31:50,586 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,587 INFO sqlalchemy.engine.base.Engine ('2017-02-22 00:00:00.000000', 0.32, 69)
2018-05-08 18:31:50,588 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,588 INFO sqlalchemy.engine.base.Engine ('2017-02-23 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,589 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,590 INFO sqlalchemy.engine.base.Engine ('2017-02-24 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,591 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,591 INFO sqlalchemy.engine.base.Engine ('2017-02-25 00:00:00.000000', 0.12, 66)
2018-05-08 18:31:50,592 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,593 INFO sqlalchemy.engine.base.Engine ('2017-02-26 00:00:00.000000', 0.0, 64)
2018-05-08 18:31:50,594 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,594 INFO sqlalchemy.engine.base.Engine ('2017-02-27 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,595 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,595 INFO sqlalchemy.engine.base.Engine ('2017-02-28 00:00:00.000000', 0.58, 69)
2018-05-08 18:31:50,596 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,597 INFO sqlalchemy.engine.base.Engine ('2017-03-01 00:00:00.000000', 2.0, 64)
2018-05-08 18:31:50,598 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,599 INFO sqlalchemy.engine.base.Engine ('2017-03-02 00:00:00.000000', 0.58, 72)
2018-05-08 18:31:50,600 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,600 INFO sqlalchemy.engine.base.Engine ('2017-03-03 00:00:00.000000', 0.56, 78)
2018-05-08 18:31:50,601 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,601 INFO sqlalchemy.engine.base.Engine ('2017-03-04 00:00:00.000000', 0.0, 70)

2018-05-08 18:31:50,602 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,603 INFO sqlalchemy.engine.base.Engine ('2017-03-05 00:00:00.000000', 0.35, 68)
2018-05-08 18:31:50,604 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,604 INFO sqlalchemy.engine.base.Engine ('2017-03-06 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:50,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,606 INFO sqlalchemy.engine.base.Engine ('2017-03-07 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,607 INFO sqlalchemy.engine.base.Engine ('2017-03-08 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,609 INFO sqlalchemy.engine.base.Engine ('2017-03-09 00:00:00.000000', 0.01, 72)
2018-05-08 18:31:50,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,610 INFO sqlalchemy.engine.base.Engine ('2017-03-10 00:00:00.000000', 0.0, 65)
2018-05-08 18:31:50,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,612 INFO sqlalchemy.engine.base.Engine ('2017-03-11 00:00:00.000000', 0.0, 82)
2018-05-08 18:31:50,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,614 INFO sqlalchemy.engine.base.Engine ('2017-03-14 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:50,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,615 INFO sqlalchemy.engine.base.Engine ('2017-03-15 00:00:00.000000', 0.0, 76)
2018-05-08 18:31:50,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,616 INFO sqlalchemy.engine.base.Engine ('2017-03-16 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:50,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,618 INFO sqlalchemy.engine.base.Engine ('2017-03-19 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,619 INFO sqlalchemy.engine.base.Engine ('2017-03-20 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,621 INFO sqlalchemy.engine.base.Engine ('2017-03-21 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,622 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,623 INFO sqlalchemy.engine.base.Engine ('2017-03-22 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,624 INFO sqlalchemy.engine.base.Engine ('2017-03-23 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:50,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,626 INFO sqlalchemy.engine.base.Engine ('2017-03-24 00:00:00.000000', 0.17, 70)
2018-05-08 18:31:50,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,627 INFO sqlalchemy.engine.base.Engine ('2017-03-25 00:00:00.000000', 0.48, 72)
2018-05-08 18:31:50,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,629 INFO sqlalchemy.engine.base.Engine ('2017-03-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,630 INFO sqlalchemy.engine.base.Engine ('2017-03-27 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,632 INFO sqlalchemy.engine.base.Engine ('2017-03-28 00:00:00.000000', 0.68, 69)
2018-05-08 18:31:50,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,633 INFO sqlalchemy.engine.base.Engine ('2017-03-29 00:00:00.000000', 0.07, 69)
2018-05-08 18:31:50,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,635 INFO sqlalchemy.engine.base.Engine ('2017-04-01 00:00:00.000000', 0.2, 69)
2018-05-08 18:31:50,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,636 INFO sqlalchemy.engine.base.Engine ('2017-04-02 00:00:00.000000', 0.0, 71)
2018-05-08 18:31:50,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,638 INFO sqlalchemy.engine.base.Engine ('2017-04-03 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:50,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,639 INFO sqlalchemy.engine.base.Engine ('2017-04-04 00:00:00.000000', 0.02, 75)
2018-05-08 18:31:50,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,640 INFO sqlalchemy.engine.base.Engine ('2017-04-05 00:00:00.000000', 0.45, 69)
2018-05-08 18:31:50,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,642 INFO sqlalchemy.engine.base.Engine ('2017-04-06 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,643 INFO sqlalchemy.engine.base.Engine ('2017-04-09 00:00:00.000000', 0.0, 70)
2018-05-08 18:31:50,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,645 INFO sqlalchemy.engine.base.Engine ('2017-04-10 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,647 INFO sqlalchemy.engine.base.Engine ('2017-04-11 00:00:00.000000', 0.25, 71)
2018-05-08 18:31:50,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,648 INFO sqlalchemy.engine.base.Engine ('2017-04-12 00:00:00.000000', 0.65, 70)
2018-05-08 18:31:50,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,649 INFO sqlalchemy.engine.base.Engine ('2017-04-13 00:00:00.000000', 0.23, 73)
2018-05-08 18:31:50,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,651 INFO sqlalchemy.engine.base.Engine ('2017-04-14 00:00:00.000000', 2.82, 72)
2018-05-08 18:31:50,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,652 INFO sqlalchemy.engine.base.Engine ('2017-04-15 00:00:00.000000', 0.9, 70)
2018-05-08 18:31:50,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,654 INFO sqlalchemy.engine.base.Engine ('2017-04-16 00:00:00.000000', 0.11, 71)

2018-05-08 18:31:50,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,656 INFO sqlalchemy.engine.base.Engine ('2017-04-17 00:00:00.000000', 1.3, 69)
2018-05-08 18:31:50,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,657 INFO sqlalchemy.engine.base.Engine ('2017-04-18 00:00:00.000000', 0.98, 71)
2018-05-08 18:31:50,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,659 INFO sqlalchemy.engine.base.Engine ('2017-04-19 00:00:00.000000', 0.14, 71)
2018-05-08 18:31:50,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,660 INFO sqlalchemy.engine.base.Engine ('2017-04-20 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,662 INFO sqlalchemy.engine.base.Engine ('2017-04-21 00:00:00.000000', 1.84, 70)
2018-05-08 18:31:50,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,663 INFO sqlalchemy.engine.base.Engine ('2017-04-22 00:00:00.000000', 1.35, 73)
2018-05-08 18:31:50,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,665 INFO sqlalchemy.engine.base.Engine ('2017-04-23 00:00:00.000000', 0.35, 70)
2018-05-08 18:31:50,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,667 INFO sqlalchemy.engine.base.Engine ('2017-04-24 00:00:00.000000', 0.05, 75)
2018-05-08 18:31:50,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,668 INFO sqlalchemy.engine.base.Engine ('2017-04-25 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,670 INFO sqlalchemy.engine.base.Engine ('2017-04-26 00:00:00.000000', 0.22, 77)
2018-05-08 18:31:50,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,671 INFO sqlalchemy.engine.base.Engine ('2017-04-27 00:00:00.000000', 0.11, 76)
2018-05-08 18:31:50,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,673 INFO sqlalchemy.engine.base.Engine ('2017-04-28 00:00:00.000000', 0.79, 71)
2018-05-08 18:31:50,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,674 INFO sqlalchemy.engine.base.Engine ('2017-04-29 00:00:00.000000', 0.0, 68)
2018-05-08 18:31:50,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,676 INFO sqlalchemy.engine.base.Engine ('2017-04-30 00:00:00.000000', 0.8, 58)
2018-05-08 18:31:50,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,678 INFO sqlalchemy.engine.base.Engine ('2017-05-01 00:00:00.000000', 0.25, 73)
2018-05-08 18:31:50,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,680 INFO sqlalchemy.engine.base.Engine ('2017-05-02 00:00:00.000000', 0.0, 79)
2018-05-08 18:31:50,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,681 INFO sqlalchemy.engine.base.Engine ('2017-05-05 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:50,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,683 INFO sqlalchemy.engine.base.Engine ('2017-05-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,684 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,684 INFO sqlalchemy.engine.base.Engine ('2017-05-07 00:00:00.000000', 0.03, 70)
2018-05-08 18:31:50,685 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,686 INFO sqlalchemy.engine.base.Engine ('2017-05-08 00:00:00.000000', 1.11, 66)
2018-05-08 18:31:50,687 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,687 INFO sqlalchemy.engine.base.Engine ('2017-05-09 00:00:00.000000', 0.23, 72)
2018-05-08 18:31:50,688 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,689 INFO sqlalchemy.engine.base.Engine ('2017-05-10 00:00:00.000000', 0.55, 72)
2018-05-08 18:31:50,690 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,690 INFO sqlalchemy.engine.base.Engine ('2017-05-11 00:00:00.000000', 0.44, 78)
2018-05-08 18:31:50,691 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,692 INFO sqlalchemy.engine.base.Engine ('2017-05-12 00:00:00.000000', 0.1, 70)
2018-05-08 18:31:50,693 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,694 INFO sqlalchemy.engine.base.Engine ('2017-05-13 00:00:00.000000', 0.1, 71)
2018-05-08 18:31:50,695 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,695 INFO sqlalchemy.engine.base.Engine ('2017-05-14 00:00:00.000000', 1.0, 70)
2018-05-08 18:31:50,696 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,697 INFO sqlalchemy.engine.base.Engine ('2017-05-15 00:00:00.000000', 0.6, 72)
2018-05-08 18:31:50,698 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,698 INFO sqlalchemy.engine.base.Engine ('2017-05-16 00:00:00.000000', 0.3, 71)
2018-05-08 18:31:50,700 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,700 INFO sqlalchemy.engine.base.Engine ('2017-05-17 00:00:00.000000', 0.06, 71)
2018-05-08 18:31:50,701 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,702 INFO sqlalchemy.engine.base.Engine ('2017-05-18 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,703 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,704 INFO sqlalchemy.engine.base.Engine ('2017-05-21 00:00:00.000000', 0.0, 69)
2018-05-08 18:31:50,704 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,705 INFO sqlalchemy.engine.base.Engine ('2017-05-22 00:00:00.000000', 0.3, 72)
2018-05-08 18:31:50,706 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,706 INFO sqlalchemy.engine.base.Engine ('2017-05-23 00:00:00.000000', 0.44, 69)
2018-05-08 18:31:50,707 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,708 INFO sqlalchemy.engine.base.Engine ('2017-05-24 00:00:00.000000', 2.17, 70)
2018-05-08 18:31:50,709 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,709 INFO sqlalchemy.engine.base.Engine ('2017-05-25 00:00:00.000000', 0.88, 75)

2018-05-08 18:31:50,710 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,711 INFO sqlalchemy.engine.base.Engine ('2017-05-26 00:00:00.000000', 0.0, 72)
2018-05-08 18:31:50,712 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,712 INFO sqlalchemy.engine.base.Engine ('2017-05-27 00:00:00.000000', 0.5, 72)
2018-05-08 18:31:50,713 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,714 INFO sqlalchemy.engine.base.Engine ('2017-05-28 00:00:00.000000', 0.0, 73)
2018-05-08 18:31:50,715 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,715 INFO sqlalchemy.engine.base.Engine ('2017-06-01 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:50,716 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,717 INFO sqlalchemy.engine.base.Engine ('2017-06-04 00:00:00.000000', 0.82, 77)
2018-05-08 18:31:50,718 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,718 INFO sqlalchemy.engine.base.Engine ('2017-06-05 00:00:00.000000', 0.01, 74)
2018-05-08 18:31:50,719 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,720 INFO sqlalchemy.engine.base.Engine ('2017-06-06 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,721 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,721 INFO sqlalchemy.engine.base.Engine ('2017-06-07 00:00:00.000000', 0.01, 79)
2018-05-08 18:31:50,722 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,723 INFO sqlalchemy.engine.base.Engine ('2017-06-08 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:50,724 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,724 INFO sqlalchemy.engine.base.Engine ('2017-06-11 00:00:00.000000', 0.7, 76)
2018-05-08 18:31:50,725 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,726 INFO sqlalchemy.engine.base.Engine ('2017-06-12 00:00:00.000000', 0.81, 74)
2018-05-08 18:31:50,727 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,727 INFO sqlalchemy.engine.base.Engine ('2017-06-13 00:00:00.000000', 0.65, 73)
2018-05-08 18:31:50,728 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,729 INFO sqlalchemy.engine.base.Engine ('2017-06-14 00:00:00.000000', 0.81, 74)
2018-05-08 18:31:50,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,777 INFO sqlalchemy.engine.base.Engine ('2017-06-15 00:00:00.000000', 1.69, 77)
2018-05-08 18:31:50,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,779 INFO sqlalchemy.engine.base.Engine ('2017-06-16 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:50,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,780 INFO sqlalchemy.engine.base.Engine ('2017-06-17 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:50,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,782 INFO sqlalchemy.engine.base.Engine ('2017-06-18 00:00:00.000000', 0.7, 77)
2018-05-08 18:31:50,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,783 INFO sqlalchemy.engine.base.Engine ('2017-06-19 00:00:00.000000', 0.4, 76)
2018-05-08 18:31:50,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,785 INFO sqlalchemy.engine.base.Engine ('2017-06-20 00:00:00.000000', 0.31, 74)
2018-05-08 18:31:50,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,786 INFO sqlalchemy.engine.base.Engine ('2017-06-21 00:00:00.000000', 0.3, 75)
2018-05-08 18:31:50,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,788 INFO sqlalchemy.engine.base.Engine ('2017-06-22 00:00:00.000000', 0.28, 76)
2018-05-08 18:31:50,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,789 INFO sqlalchemy.engine.base.Engine ('2017-06-23 00:00:00.000000', 0.5, 71)
2018-05-08 18:31:50,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,791 INFO sqlalchemy.engine.base.Engine ('2017-06-24 00:00:00.000000', 0.22, 73)
2018-05-08 18:31:50,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,792 INFO sqlalchemy.engine.base.Engine ('2017-06-25 00:00:00.000000', 0.5, 79)
2018-05-08 18:31:50,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,794 INFO sqlalchemy.engine.base.Engine ('2017-06-26 00:00:00.000000', 0.02, 79)
2018-05-08 18:31:50,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,796 INFO sqlalchemy.engine.base.Engine ('2017-06-27 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:50,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,797 INFO sqlalchemy.engine.base.Engine ('2017-06-28 00:00:00.000000', 0.02, 74)
2018-05-08 18:31:50,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,799 INFO sqlalchemy.engine.base.Engine ('2017-06-29 00:00:00.000000', 0.04, 76)
2018-05-08 18:31:50,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,800 INFO sqlalchemy.engine.base.Engine ('2017-06-30 00:00:00.000000', 0.2, 75)
2018-05-08 18:31:50,801 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,802 INFO sqlalchemy.engine.base.Engine ('2017-07-01 00:00:00.000000', 0.1, 74)
2018-05-08 18:31:50,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,804 INFO sqlalchemy.engine.base.Engine ('2017-07-02 00:00:00.000000', 0.5, 78)
2018-05-08 18:31:50,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,805 INFO sqlalchemy.engine.base.Engine ('2017-07-03 00:00:00.000000', 0.4, 77)
2018-05-08 18:31:50,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,806 INFO sqlalchemy.engine.base.Engine ('2017-07-04 00:00:00.000000', 0.0, 77)
2018-05-08 18:31:50,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,807 INFO sqlalchemy.engine.base.Engine ('2017-07-05 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:50,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,809 INFO sqlalchemy.engine.base.Engine ('2017-07-06 00:00:00.000000', 0.02, 74)

2018-05-08 18:31:50,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,810 INFO sqlalchemy.engine.base.Engine ('2017-07-07 00:00:00.000000', 0.3, 74)
2018-05-08 18:31:50,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,812 INFO sqlalchemy.engine.base.Engine ('2017-07-08 00:00:00.000000', 0.02, 71)
2018-05-08 18:31:50,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,814 INFO sqlalchemy.engine.base.Engine ('2017-07-09 00:00:00.000000', 0.0, 78)
2018-05-08 18:31:50,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,815 INFO sqlalchemy.engine.base.Engine ('2017-07-10 00:00:00.000000', 0.02, 77)
2018-05-08 18:31:50,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,817 INFO sqlalchemy.engine.base.Engine ('2017-07-11 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,818 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,818 INFO sqlalchemy.engine.base.Engine ('2017-07-12 00:00:00.000000', 0.05, 72)
2018-05-08 18:31:50,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,820 INFO sqlalchemy.engine.base.Engine ('2017-07-13 00:00:00.000000', 0.68, 77)
2018-05-08 18:31:50,821 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,821 INFO sqlalchemy.engine.base.Engine ('2017-07-14 00:00:00.000000', 0.68, 76)
2018-05-08 18:31:50,822 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,823 INFO sqlalchemy.engine.base.Engine ('2017-07-15 00:00:00.000000', 0.1, 78)
2018-05-08 18:31:50,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,824 INFO sqlalchemy.engine.base.Engine ('2017-07-16 00:00:00.000000', 0.5, 75)
2018-05-08 18:31:50,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,826 INFO sqlalchemy.engine.base.Engine ('2017-07-17 00:00:00.000000', 0.39, 72)
2018-05-08 18:31:50,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,828 INFO sqlalchemy.engine.base.Engine ('2017-07-18 00:00:00.000000', 2.4, 77)
2018-05-08 18:31:50,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,830 INFO sqlalchemy.engine.base.Engine ('2017-07-19 00:00:00.000000', 0.27, 74)
2018-05-08 18:31:50,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,831 INFO sqlalchemy.engine.base.Engine ('2017-07-20 00:00:00.000000', 0.7, 75)
2018-05-08 18:31:50,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,832 INFO sqlalchemy.engine.base.Engine ('2017-07-21 00:00:00.000000', 0.1, 72)
2018-05-08 18:31:50,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,835 INFO sqlalchemy.engine.base.Engine ('2017-07-22 00:00:00.000000', 4.0, 72)
2018-05-08 18:31:50,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,836 INFO sqlalchemy.engine.base.Engine ('2017-07-23 00:00:00.000000', 0.8, 78)
2018-05-08 18:31:50,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,838 INFO sqlalchemy.engine.base.Engine ('2017-07-24 00:00:00.000000', 0.84, 77)
2018-05-08 18:31:50,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,839 INFO sqlalchemy.engine.base.Engine ('2017-07-25 00:00:00.000000', 0.3, 79)
2018-05-08 18:31:50,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,841 INFO sqlalchemy.engine.base.Engine ('2017-07-26 00:00:00.000000', 0.3, 73)
2018-05-08 18:31:50,842 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,843 INFO sqlalchemy.engine.base.Engine ('2017-07-27 00:00:00.000000', 0.0, 75)
2018-05-08 18:31:50,843 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,844 INFO sqlalchemy.engine.base.Engine ('2017-07-28 00:00:00.000000', 0.4, 73)
2018-05-08 18:31:50,845 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,846 INFO sqlalchemy.engine.base.Engine ('2017-07-29 00:00:00.000000', 0.3, 77)
2018-05-08 18:31:50,846 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,847 INFO sqlalchemy.engine.base.Engine ('2017-07-30 00:00:00.000000', 0.3, 79)
2018-05-08 18:31:50,848 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,849 INFO sqlalchemy.engine.base.Engine ('2017-07-31 00:00:00.000000', 0.0, 74)
2018-05-08 18:31:50,849 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,850 INFO sqlalchemy.engine.base.Engine ('2017-08-02 00:00:00.000000', 0.25, 80)
2018-05-08 18:31:50,851 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,851 INFO sqlalchemy.engine.base.Engine ('2017-08-03 00:00:00.000000', 0.06, 76)
2018-05-08 18:31:50,852 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,853 INFO sqlalchemy.engine.base.Engine ('2017-08-07 00:00:00.000000', 0.05, 78)
2018-05-08 18:31:50,854 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,855 INFO sqlalchemy.engine.base.Engine ('2017-08-08 00:00:00.000000', 0.34, 74)
2018-05-08 18:31:50,855 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,856 INFO sqlalchemy.engine.base.Engine ('2017-08-09 00:00:00.000000', 0.15, 71)
2018-05-08 18:31:50,857 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,857 INFO sqlalchemy.engine.base.Engine ('2017-08-10 00:00:00.000000', 0.07, 75)
2018-05-08 18:31:50,858 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,859 INFO sqlalchemy.engine.base.Engine ('2017-08-12 00:00:00.000000', 0.14, 74)
2018-05-08 18:31:50,860 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,860 INFO sqlalchemy.engine.base.Engine ('2017-08-14 00:00:00.000000', 0.22, 79)
2018-05-08 18:31:50,861 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,862 INFO sqlalchemy.engine.base.Engine ('2017-08-15 00:00:00.000000', 0.42, 70)
2018-05-08 18:31:50,863 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,863 INFO sqlalchemy.engine.base.Engine ('2017-08-16 00:00:00.000000', 0.42, 71)

2018-05-08 18:31:50,864 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,865 INFO sqlalchemy.engine.base.Engine ('2017-08-17 00:00:00.000000', 0.13, 72)
2018-05-08 18:31:50,866 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,866 INFO sqlalchemy.engine.base.Engine ('2017-08-19 00:00:00.000000', 0.09, 71)
2018-05-08 18:31:50,867 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,869 INFO sqlalchemy.engine.base.Engine ('2017-08-21 00:00:00.000000', 0.56, 76)
2018-05-08 18:31:50,870 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,871 INFO sqlalchemy.engine.base.Engine ('2017-08-22 00:00:00.000000', 0.5, 76)
2018-05-08 18:31:50,872 INFO sqlalchemy.engine.base.Engine INSERT INTO "measurement_USC00516128" ("Date", prcp, tobs) VALUES (?, ?, ?)
2018-05-08 18:31:50,872 INFO sqlalchemy.engine.base.Engine ('2017-08-23 00:00:00.000000', 0.45, 76)
2018-05-08 18:31:51,131 INFO sqlalchemy.engine.base.Engine COMMIT